import ErdosProblems.Erdos1124.TorusAction
import Mathlib.MeasureTheory.Measure.Haar.Unique

open scoped BigOperators
open Set Function MeasureTheory

namespace Erdos1124.FreeTuple

noncomputable section

/-- Haar measure on the unit additive circle has no atoms.  This direct
proof from the closed-ball formula avoids requiring a global typeclass
instance. -/
lemma volume_singleton_circle (x : UnitAddCircle) : volume ({x} : Set UnitAddCircle) = 0 := by
  rw [← Metric.closedBall_zero, AddCircle.volume_closedBall]
  norm_num

abbrev CircleTuple (d : ℕ) := Fin d → UnitAddCircle

/-- Integer displacement generated by a tuple of points of the circle. -/
def circleDisplacement {d : ℕ} (u : CircleTuple d) (n : TorusAction.Lattice d) :
    UnitAddCircle :=
  ∑ i, n i • u i

/-- Freeness of the lattice action generated by points of the circle. -/
def CircleFree {d : ℕ} (u : CircleTuple d) : Prop :=
  Function.Injective (circleDisplacement u)

/-- A free coordinate projection makes a tuple of translations on a
higher-dimensional torus free. -/
lemma torus_free_of_coordinate_circleFree {d k : ℕ}
    (u : Fin d → TorusAction.Torus k) (j : Fin k)
    (hfree : CircleFree fun i => u i j) : TorusAction.Free u := by
  intro m n hmn
  apply hfree
  simpa [circleDisplacement, TorusAction.displacement] using congrFun hmn j

/-- The character of a tuple of circle translations associated to an integer
coefficient vector. -/
def relationHom {d : ℕ} (n : TorusAction.Lattice d) :
    CircleTuple d →+ UnitAddCircle where
  toFun u := circleDisplacement u n
  map_zero' := by simp [circleDisplacement]
  map_add' u v := by
    simp only [circleDisplacement, Pi.add_apply, zsmul_add, Finset.sum_add_distrib]

@[simp]
lemma relationHom_apply {d : ℕ} (n : TorusAction.Lattice d) (u : CircleTuple d) :
    relationHom n u = circleDisplacement u n := rfl

lemma continuous_relationHom {d : ℕ} (n : TorusAction.Lattice d) :
    Continuous (relationHom n) := by
  change Continuous fun u : CircleTuple d => ∑ i, n i • u i
  fun_prop

lemma relationHom_surjective {d : ℕ} {n : TorusAction.Lattice d} (hn : n ≠ 0) :
    Function.Surjective (relationHom n) := by
  obtain ⟨j, hj⟩ : ∃ j, n j ≠ 0 := by
    simpa only [ne_eq, funext_iff, Pi.zero_apply, not_forall, not_not] using hn
  intro y
  let u : CircleTuple d := Function.update 0 j (DivisibleBy.div y (n j))
  refine ⟨u, ?_⟩
  change circleDisplacement u n = y
  rw [circleDisplacement]
  rw [Finset.sum_eq_single j]
  · simpa [u] using DivisibleBy.div_cancel y hj
  · intro i _ hij
    simp [u, hij]
  · simp

lemma relationHom_measurePreserving {d : ℕ} {n : TorusAction.Lattice d} (hn : n ≠ 0) :
    MeasurePreserving (relationHom n) volume volume := by
  apply (relationHom n).measurePreserving (continuous_relationHom n)
      (relationHom_surjective hn)
  rw [MeasureTheory.volume_pi, Measure.pi_univ]
  simp [AddCircle.measure_univ]

/-- Every nontrivial integer relation cuts out a Haar-null subset of the
space of tuples. -/
lemma measure_relation_zero {d : ℕ} {n : TorusAction.Lattice d} (hn : n ≠ 0) :
    volume {u : CircleTuple d | circleDisplacement u n = 0} = 0 := by
  change volume ((relationHom n) ⁻¹' {0}) = 0
  exact (relationHom_measurePreserving hn).measure_preimage
    (nullMeasurableSet_singleton 0) |>.trans (volume_singleton_circle 0)

/-- Almost every tuple of circle translations generates a free lattice
action. -/
theorem ae_free (d : ℕ) : ∀ᵐ u : CircleTuple d, CircleFree u := by
  have hrelation : ∀ n : TorusAction.Lattice d, n ≠ 0 →
      ∀ᵐ u : CircleTuple d, circleDisplacement u n ≠ 0 := by
    intro n hn
    exact compl_mem_ae_iff.mpr (measure_relation_zero hn)
  have hall : ∀ᵐ u : CircleTuple d,
      ∀ n : TorusAction.Lattice d, n ≠ 0 → circleDisplacement u n ≠ 0 := by
    rw [ae_all_iff]
    intro n
    by_cases hn : n = 0
    · simp [hn]
    · exact Filter.Eventually.mono (hrelation n hn) fun _ h _ => h
  filter_upwards [hall] with u hu
  intro m n hmn
  by_contra hne
  have hsub : m - n ≠ 0 := sub_ne_zero.mpr hne
  apply hu (m - n) hsub
  rw [circleDisplacement]
  simp only [Pi.sub_apply, sub_zsmul]
  rw [Finset.sum_add_distrib]
  rw [Finset.sum_neg_distrib]
  unfold circleDisplacement at hmn
  rw [hmn, add_neg_cancel]

/-- The exceptional set of non-free tuples has product Haar measure zero. -/
theorem measure_not_free_zero (d : ℕ) :
    volume {u : CircleTuple d | ¬ CircleFree u} = 0 :=
  ae_iff.mp (ae_free d)

/-- Consequently, every set of tuples with nonzero outer Haar measure
contains a tuple which generates a free action. -/
theorem exists_mem_circleFree_of_measure_ne_zero {d : ℕ} {S : Set (CircleTuple d)}
    (hS : volume S ≠ 0) : ∃ u ∈ S, CircleFree u := by
  by_contra h
  apply hS
  apply measure_mono_null (t := {u : CircleTuple d | ¬ CircleFree u})
  · intro u hu hfree
    exact h ⟨u, hu, hfree⟩
  · exact measure_not_free_zero d

end

end Erdos1124.FreeTuple
