import ErdosProblems.Erdos1124.Flow

/-!
# Lattice actions and discrepancy on the unit torus

This file fixes the conventions connecting the analytic discrepancy estimates
to the dyadic flow algebra in `Flow.lean`.
-/

open scoped BigOperators
open Set MeasureTheory

namespace Erdos1124.TorusAction

noncomputable section

/-- The `k`-dimensional unit torus. -/
abbrev Torus (k : ℕ) := UnitAddTorus (Fin k)

/-- The lattice acting on the torus. -/
abbrev Lattice (d : ℕ) := Flow.Lattice d

/-- The torus displacement belonging to an integer coefficient vector. -/
def displacement {d k : ℕ} (u : Fin d → Torus k) (n : Lattice d) : Torus k :=
  ∑ i, n i • u i

lemma displacement_zero {d k : ℕ} (u : Fin d → Torus k) :
    displacement u 0 = 0 := by
  simp [displacement]

lemma displacement_add {d k : ℕ} (u : Fin d → Torus k) (m n : Lattice d) :
    displacement u (m + n) = displacement u m + displacement u n := by
  simp [displacement, add_zsmul, Finset.sum_add_distrib]

/-- The additive action generated by `u`. -/
@[instance_reducible]
def torusAddAction {d k : ℕ} (u : Fin d → Torus k) :
    AddAction (Lattice d) (Torus k) where
  vadd n x := displacement u n + x
  zero_vadd x := by
    change displacement u 0 + x = x
    simp [displacement_zero]
  add_vadd m n x := by
    change displacement u (m + n) + x = displacement u m + (displacement u n + x)
    rw [displacement_add]
    abel

/-- Freeness of the generated lattice action, stated as injectivity of the
displacement homomorphism. -/
def Free {d k : ℕ} (u : Fin d → Torus k) : Prop :=
  Function.Injective (displacement u)

/-- The point of the negative orbit cube with index `q`. -/
def orbitPoint {d k n : ℕ} (u : Fin d → Torus k) (x : Torus k)
    (q : Fin d → Fin n) : Torus k :=
  displacement u (-Flow.cubeIndex q) + x

lemma cubeIndex_injective {d n : ℕ} :
    Function.Injective (@Flow.cubeIndex d n) := by
  intro q r h
  funext i
  apply Fin.ext
  have hi := congrFun h i
  change ((q i : ℕ) : ℤ) = ((r i : ℕ) : ℤ) at hi
  exact_mod_cast hi

/-- Freeness makes the orbit-cube indexing injective. -/
lemma orbitPoint_injective {d k n : ℕ} {u : Fin d → Torus k}
    (hu : Free u) (x : Torus k) :
    Function.Injective (orbitPoint (n := n) u x) := by
  intro q r hqr
  apply cubeIndex_injective
  apply neg_injective
  apply hu
  exact add_right_cancel hqr

/-- The finite set underlying an orbit cube. -/
noncomputable def cubePoints {d k : ℕ} (u : Fin d → Torus k)
    (n : ℕ) (x : Torus k) : Finset (Torus k) := by
  classical
  exact Finset.univ.image (orbitPoint (n := n) u x)

lemma card_cubePoints {d k : ℕ} {u : Fin d → Torus k} (hu : Free u)
    (n : ℕ) (x : Torus k) :
    (cubePoints u n x).card = n ^ d := by
  classical
  rw [cubePoints, Finset.card_image_of_injective _ (orbitPoint_injective hu x),
    Finset.card_univ, Fintype.card_fun, Fintype.card_fin, Fintype.card_fin]

/-- Number of points of an indexed negative orbit cube which lie in `E`.
Under `Free u` the indexing has no repetitions. -/
def cubeCount {d k : ℕ} (u : Fin d → Torus k) (E : Set (Torus k))
    (n : ℕ) (x : Torus k) : ℕ := by
  classical
  letI := torusAddAction u
  exact ∑ q : Fin d → Fin n, if (-Flow.cubeIndex q +ᵥ x) ∈ E then 1 else 0

/-- Normalized orbit-cube count. -/
def cubeDensity {d k : ℕ} (u : Fin d → Torus k) (E : Set (Torus k))
    (n : ℕ) (x : Torus k) : ℝ :=
  cubeCount u E n x / (n : ℝ) ^ d

/-- Absolute discrepancy of an indexed orbit cube. -/
def discrepancy {d k : ℕ} (u : Fin d → Torus k) (E : Set (Torus k))
    (n : ℕ) (x : Torus k) : ℝ :=
  |cubeDensity u E n x - (volume E).toReal|

/-- Difference of the two indicator functions. -/
noncomputable def signedIndicator {k : ℕ} (A B : Set (Torus k))
    (x : Torus k) : ℝ := by
  classical
  exact (if x ∈ A then 1 else 0) - if x ∈ B then 1 else 0

/-- The dyadic cube average of the signed indicator is the difference of the
two normalized cube counts. -/
lemma cubeAverage_signedIndicator {d k : ℕ} (u : Fin d → Torus k)
    (A B : Set (Torus k)) (n : ℕ) (x : Torus k) :
    letI := torusAddAction u
    Flow.cubeAverage (d := d) (signedIndicator A B) n x =
      cubeDensity u A n x - cubeDensity u B n x := by
  let := torusAddAction u
  rw [Flow.cubeAverage, Flow.cubeSum]
  simp only [signedIndicator, Finset.sum_sub_distrib]
  unfold cubeDensity cubeCount
  push_cast
  ring

/-- Two discrepancy estimates about the same mean bound the signed cube
average by twice the error. -/
lemma abs_cubeAverage_signedIndicator_le {d k : ℕ} (u : Fin d → Torus k)
    (A B : Set (Torus k)) (n : ℕ) (x : Torus k) (mean error : ℝ)
    (hA : |cubeDensity u A n x - mean| ≤ error)
    (hB : |cubeDensity u B n x - mean| ≤ error) :
    letI := torusAddAction u
    |Flow.cubeAverage (d := d) (signedIndicator A B) n x| ≤ 2 * error := by
  let := torusAddAction u
  rw [cubeAverage_signedIndicator]
  have hid : cubeDensity u A n x - cubeDensity u B n x =
      (cubeDensity u A n x - mean) - (cubeDensity u B n x - mean) := by ring
  rw [hid]
  calc
    |cubeDensity u A n x - mean - (cubeDensity u B n x - mean)| ≤
        |cubeDensity u A n x - mean| + |cubeDensity u B n x - mean| := abs_sub _ _
    _ ≤ error + error := add_le_add hA hB
    _ = 2 * error := by ring

end

end Erdos1124.TorusAction
