import ErdosProblems.Erdos140.BohrBasic
import ErdosProblems.Erdos140.Chang
import ErdosProblems.Erdos140.RegularSpectrumPhase
import ErdosProblems.Erdos140.RelativeChangSanders

/-!
# Large spectra and finite Bohr data

This file supplies the change of models between Mathlib's complex characters
`AddChar G ℂ` and the additive-circle characters used by `Erdos140.BohrData`.
-/

open Finset Function Real
open scoped BigOperators NNReal

namespace Erdos140.LocalSpectrum

variable {G : Type*} [Fintype G] [AddCommGroup G] [DecidableEq G]

/-- The additive-circle character corresponding to a complex character of a
finite abelian group. -/
noncomputable def circleLogCharacter (psi : AddChar G ℂ) : AddCharacter G := by
  let e := AddCircle.homeomorphCircle (by norm_num : (1 : ℝ) ≠ 0)
  exact
    { toFun := fun x ↦ e.symm ((AddChar.circleEquivComplex.symm psi) x)
      map_zero' := by
        apply e.injective
        simp [e, AddCircle.homeomorphCircle_apply]
      map_add' := by
        intro x y
        apply e.injective
        rw [e.apply_symm_apply]
        rw [show e (e.symm ((AddChar.circleEquivComplex.symm psi) x) +
              e.symm ((AddChar.circleEquivComplex.symm psi) y)) =
            AddCircle.toCircle (e.symm ((AddChar.circleEquivComplex.symm psi) x) +
              e.symm ((AddChar.circleEquivComplex.symm psi) y)) by
              exact AddCircle.homeomorphCircle_apply _ _]
        rw [AddCircle.toCircle_add]
        rw [← AddCircle.homeomorphCircle_apply (by norm_num : (1 : ℝ) ≠ 0),
          e.apply_symm_apply]
        rw [← AddCircle.homeomorphCircle_apply (by norm_num : (1 : ℝ) ≠ 0),
          e.apply_symm_apply]
        exact AddChar.map_add_eq_mul _ _ _ }

theorem toCircle_circleLogCharacter (psi : AddChar G ℂ) (x : G) :
    AddCircle.toCircle (circleLogCharacter psi x) =
      (AddChar.circleEquivComplex.symm psi) x := by
  rw [← AddCircle.homeomorphCircle_apply (by norm_num : (1 : ℝ) ≠ 0)]
  simp [circleLogCharacter]

theorem coe_toCircle_circleLogCharacter (psi : AddChar G ℂ) (x : G) :
    (AddCircle.toCircle (circleLogCharacter psi x) : ℂ) = psi x := by
  rw [toCircle_circleLogCharacter]
  exact DFunLike.congr_fun (AddChar.circleEquivComplex.apply_symm_apply psi) x

theorem circleLogCharacter_injective :
    Function.Injective (circleLogCharacter (G := G)) := by
  intro psi chi h
  ext x
  have hx := DFunLike.congr_fun h x
  have hh := congrArg (fun z : AddCircle (1 : ℝ) ↦ (AddCircle.toCircle z : ℂ)) hx
  simpa only [coe_toCircle_circleLogCharacter] using hh

/-- Conversion of complex characters to additive-circle characters is an
additive homomorphism. -/
noncomputable def circleLogHom :
    AddChar G ℂ →+ AddCharacter G where
  toFun := circleLogCharacter
  map_zero' := by
    ext x
    apply AddCircle.injective_toCircle (by norm_num : (1 : ℝ) ≠ 0)
    apply Subtype.ext
    simp [coe_toCircle_circleLogCharacter]
  map_add' psi chi := by
    ext x
    apply AddCircle.injective_toCircle (by norm_num : (1 : ℝ) ≠ 0)
    apply Subtype.ext
    simp [coe_toCircle_circleLogCharacter, AddCircle.toCircle_add,
      AddChar.add_apply]

@[simp] theorem circleLogHom_apply (psi : AddChar G ℂ) :
    circleLogHom psi = circleLogCharacter psi := rfl

/-! ## The Bohr datum generated by a character basis -/

/-- The Bohr datum with frequency basis `Delta` and constant arc width `r`. -/
noncomputable def basisBohrData (Delta : Finset (AddChar G ℂ)) (r : ℝ≥0) :
    BohrData G where
  freq := Delta.image circleLogCharacter
  width := fun _ ↦ r

@[simp] theorem basisBohrData_rank (Delta : Finset (AddChar G ℂ)) (r : ℝ≥0) :
    (basisBohrData Delta r).rank = Delta.card := by
  classical
  rw [BohrData.rank, basisBohrData]
  exact Finset.card_image_iff.mpr circleLogCharacter_injective.injOn

@[simp] theorem basisBohrData_width (Delta : Finset (AddChar G ℂ)) (r : ℝ≥0)
    (gamma : AddCharacter G) :
    (basisBohrData Delta r).width gamma = r := rfl

/-- A point of the basis Bohr set approximately annihilates every character
in the `{0,1,-1}`-span of the basis. -/
theorem norm_circleLogCharacter_le_card_mul_of_mem_addSpan
    {Delta : Finset (AddChar G ℂ)} {r : ℝ≥0} {psi : AddChar G ℂ} {x : G}
    (hx : x ∈ (basisBohrData Delta r).carrier)
    (hpsi : psi ∈ Delta.addSpan) :
    ‖circleLogCharacter psi x‖ ≤ (Delta.card : ℝ) * (r : ℝ) := by
  classical
  rw [Finset.mem_addSpan] at hpsi
  obtain ⟨epsilon, hepsilon, hsum⟩ := hpsi
  have hsumLog :
      ∑ gamma ∈ Delta, epsilon gamma • circleLogCharacter gamma =
        circleLogCharacter psi := by
    change ∑ gamma ∈ Delta, epsilon gamma • circleLogHom gamma = circleLogHom psi
    calc
      ∑ gamma ∈ Delta, epsilon gamma • circleLogHom gamma =
          ∑ gamma ∈ Delta, circleLogHom (epsilon gamma • gamma) := by
            apply sum_congr rfl
            intro gamma hgamma
            exact (map_zsmul circleLogHom (epsilon gamma) gamma).symm
      _ = circleLogHom (∑ gamma ∈ Delta, epsilon gamma • gamma) := by
        exact (map_sum circleLogHom (fun gamma ↦ epsilon gamma • gamma) Delta).symm
      _ = circleLogHom psi := congrArg circleLogHom hsum
  have hsumApply :
      (∑ gamma ∈ Delta, epsilon gamma • circleLogCharacter gamma) x =
        ∑ gamma ∈ Delta, (epsilon gamma • circleLogCharacter gamma) x := by
    induction Delta using Finset.induction_on with
    | empty => simp
    | @insert gamma Delta hgamma ih => simp [hgamma, ih]
  rw [← hsumLog, hsumApply]
  calc
    ‖∑ gamma ∈ Delta, (epsilon gamma • circleLogCharacter gamma) x‖ ≤
        ∑ gamma ∈ Delta, ‖(epsilon gamma • circleLogCharacter gamma) x‖ :=
      norm_sum_le _ _
    _ ≤ ∑ _gamma ∈ Delta, (r : ℝ) := by
      apply sum_le_sum
      intro gamma hgamma
      have hfreq : circleLogCharacter gamma ∈ (basisBohrData Delta r).freq := by
        exact Finset.mem_image.mpr ⟨gamma, hgamma, rfl⟩
      have hwidth := (BohrData.mem_carrier _ _).mp hx
        (circleLogCharacter gamma) hfreq
      have hw : ‖circleLogCharacter gamma x‖ ≤ (r : ℝ) := by
        simpa only [basisBohrData_width] using hwidth
      rcases hepsilon gamma with hneg | hzero | hone
      · simpa [hneg] using hw
      · simp [hzero]
      · simpa [hone] using hw
    _ = (Delta.card : ℝ) * (r : ℝ) := by simp

/-! ## Adjoining a basis to existing Bohr data -/

/-- Intersect a dilate of existing Bohr data with the constant-width Bohr
datum generated by `Delta`.  Frequencies occurring in both data receive the
minimum of the two widths. -/
noncomputable def adjoinBasis (B : BohrData G)
    (Delta : Finset (AddChar G ℂ)) (kappa r : ℝ≥0) : BohrData G := by
  classical
  let newFreq := Delta.image circleLogCharacter
  exact
    { freq := B.freq ∪ newFreq
      width := fun gamma ↦
        if gamma ∈ B.freq then
          if gamma ∈ newFreq then min (kappa * B.width gamma) r
          else kappa * B.width gamma
        else r }

theorem adjoinBasis_rank_le (B : BohrData G)
    (Delta : Finset (AddChar G ℂ)) (kappa r : ℝ≥0) :
    (adjoinBasis B Delta kappa r).rank ≤ B.rank + Delta.card := by
  classical
  rw [BohrData.rank, BohrData.rank, adjoinBasis]
  exact (Finset.card_union_le _ _).trans_eq (by
    rw [Finset.card_image_iff.mpr circleLogCharacter_injective.injOn])

theorem adjoinBasis_carrier_subset_dilate (B : BohrData G)
    (Delta : Finset (AddChar G ℂ)) (kappa r : ℝ≥0) :
    (adjoinBasis B Delta kappa r).carrier ⊆ (B.dilate kappa).carrier := by
  classical
  intro x hx
  rw [BohrData.mem_carrier] at hx ⊢
  intro gamma hgamma
  have hgammaB : gamma ∈ B.freq := by simpa using hgamma
  have hUnion : gamma ∈ B.freq ∪ Delta.image circleLogCharacter :=
    Finset.mem_union_left _ hgammaB
  have hbound := hx gamma (by simpa [adjoinBasis] using hUnion)
  by_cases hnew : gamma ∈ Delta.image circleLogCharacter
  · change ‖gamma x‖ ≤
      (((if gamma ∈ B.freq then
          if gamma ∈ Delta.image circleLogCharacter then
            min (kappa * B.width gamma) r else kappa * B.width gamma
        else r) : ℝ≥0) : ℝ) at hbound
    rw [if_pos hgammaB, if_pos hnew] at hbound
    simpa only [BohrData.width_dilate, NNReal.coe_mul] using
      hbound.trans (by exact_mod_cast (min_le_left (kappa * B.width gamma) r))
  · change ‖gamma x‖ ≤
      (((if gamma ∈ B.freq then
          if gamma ∈ Delta.image circleLogCharacter then
            min (kappa * B.width gamma) r else kappa * B.width gamma
        else r) : ℝ≥0) : ℝ) at hbound
    rw [if_pos hgammaB, if_neg hnew] at hbound
    simpa only [BohrData.width_dilate, NNReal.coe_mul] using hbound

theorem adjoinBasis_carrier_subset_basisBohrData (B : BohrData G)
    (Delta : Finset (AddChar G ℂ)) (kappa r : ℝ≥0) :
    (adjoinBasis B Delta kappa r).carrier ⊆ (basisBohrData Delta r).carrier := by
  classical
  intro x hx
  rw [BohrData.mem_carrier] at hx ⊢
  intro gamma hgamma
  rw [basisBohrData_width]
  obtain ⟨psi, hpsi, rfl⟩ := Finset.mem_image.mp hgamma
  have hnew : circleLogCharacter psi ∈ Delta.image circleLogCharacter :=
    Finset.mem_image.mpr ⟨psi, hpsi, rfl⟩
  have hUnion : circleLogCharacter psi ∈ B.freq ∪ Delta.image circleLogCharacter :=
    Finset.mem_union_right _ hnew
  have hbound := hx (circleLogCharacter psi) (by simpa [adjoinBasis] using hUnion)
  by_cases hold : circleLogCharacter psi ∈ B.freq
  · change ‖circleLogCharacter psi x‖ ≤
      (((if circleLogCharacter psi ∈ B.freq then
          if circleLogCharacter psi ∈ Delta.image circleLogCharacter then
            min (kappa * B.width (circleLogCharacter psi)) r
          else kappa * B.width (circleLogCharacter psi)
        else r) : ℝ≥0) : ℝ) at hbound
    rw [if_pos hold, if_pos hnew] at hbound
    exact hbound.trans (by
      exact_mod_cast (min_le_right (kappa * B.width (circleLogCharacter psi)) r))
  · change ‖circleLogCharacter psi x‖ ≤
      (((if circleLogCharacter psi ∈ B.freq then
          if circleLogCharacter psi ∈ Delta.image circleLogCharacter then
            min (kappa * B.width (circleLogCharacter psi)) r
          else kappa * B.width (circleLogCharacter psi)
        else r) : ℝ≥0) : ℝ) at hbound
    rw [if_neg hold] at hbound
    exact hbound

/-- The adjoined datum is subordinate to `B.dilate kappa` and annihilates
the whole signed span of the new basis. -/
theorem norm_circleLogCharacter_le_card_mul_of_mem_adjoinBasis
    (B : BohrData G) {Delta : Finset (AddChar G ℂ)} {kappa r : ℝ≥0}
    {psi : AddChar G ℂ} {x : G}
    (hx : x ∈ (adjoinBasis B Delta kappa r).carrier)
    (hpsi : psi ∈ Delta.addSpan) :
    ‖circleLogCharacter psi x‖ ≤ (Delta.card : ℝ) * (r : ℝ) :=
  norm_circleLogCharacter_le_card_mul_of_mem_addSpan
    (adjoinBasis_carrier_subset_basisBohrData B Delta kappa r hx) hpsi

/-- The adjoined carrier is exactly the intersection of the old dilate with
the constant-width basis carrier. -/
theorem adjoinBasis_carrier_eq_inter (B : BohrData G)
    (Delta : Finset (AddChar G ℂ)) (kappa r : ℝ≥0) :
    (adjoinBasis B Delta kappa r).carrier =
      (B.dilate kappa).carrier ∩ (basisBohrData Delta r).carrier := by
  classical
  apply Finset.Subset.antisymm
  · intro x hx
    rw [Finset.mem_inter]
    exact ⟨adjoinBasis_carrier_subset_dilate B Delta kappa r hx,
      adjoinBasis_carrier_subset_basisBohrData B Delta kappa r hx⟩
  · intro x hx
    rw [Finset.mem_inter] at hx
    rw [BohrData.mem_carrier]
    intro gamma hgamma
    have hgammaUnion : gamma ∈ B.freq ∪ Delta.image circleLogCharacter := by
      simpa [adjoinBasis] using hgamma
    rw [Finset.mem_union] at hgammaUnion
    by_cases hold : gamma ∈ B.freq
    · have hB := (BohrData.mem_carrier _ _).mp hx.1 gamma (by simpa using hold)
      by_cases hnew : gamma ∈ Delta.image circleLogCharacter
      · have hN := (BohrData.mem_carrier _ _).mp hx.2 gamma (by
          simpa [basisBohrData] using hnew)
        change ‖gamma x‖ ≤
          (((if gamma ∈ B.freq then
              if gamma ∈ Delta.image circleLogCharacter then
                min (kappa * B.width gamma) r else kappa * B.width gamma
            else r) : ℝ≥0) : ℝ)
        rw [if_pos hold, if_pos hnew, NNReal.coe_min]
        exact le_min (by simpa using hB) (by simpa using hN)
      · change ‖gamma x‖ ≤
          (((if gamma ∈ B.freq then
              if gamma ∈ Delta.image circleLogCharacter then
                min (kappa * B.width gamma) r else kappa * B.width gamma
            else r) : ℝ≥0) : ℝ)
        rw [if_pos hold, if_neg hnew]
        simpa using hB
    · have hnew : gamma ∈ Delta.image circleLogCharacter :=
        hgammaUnion.resolve_left hold
      have hN := (BohrData.mem_carrier _ _).mp hx.2 gamma (by
        simpa [basisBohrData] using hnew)
      change ‖gamma x‖ ≤
        (((if gamma ∈ B.freq then
            if gamma ∈ Delta.image circleLogCharacter then
              min (kappa * B.width gamma) r else kappa * B.width gamma
          else r) : ℝ≥0) : ℝ)
      rw [if_neg hold]
      simpa using hN

/-! ## Arc norm versus chord norm -/

/-- On a short arc, chord length is at most four pi times additive-circle
norm.  The coarse factor four lets us use Mathlib's elementary local estimate
for the complex exponential. -/
theorem norm_one_sub_character_le_four_pi_mul
    (psi : AddChar G ℂ) (x : G)
    (hshort : ‖circleLogCharacter psi x‖ ≤ (2 * Real.pi)⁻¹) :
    ‖1 - psi x‖ ≤ 4 * Real.pi * ‖circleLogCharacter psi x‖ := by
  let a : ℝ := AddCircle.equivIoc (1 : ℝ) (-1 / 2) (circleLogCharacter psi x)
  have ha_mem : a ∈ Set.Ioc (-1 / 2) (-1 / 2 + 1) :=
    (AddCircle.equivIoc (1 : ℝ) (-1 / 2) (circleLogCharacter psi x)).property
  have ha_abs : |a| ≤ 1 / 2 := by
    rw [abs_le]
    constructor <;> linarith [ha_mem.1, ha_mem.2]
  have hcoe : (a : AddCircle (1 : ℝ)) = circleLogCharacter psi x := by
    exact AddCircle.coe_equivIoc
  have hnorm_a : ‖circleLogCharacter psi x‖ = |a| := by
    rw [← hcoe]
    exact (AddCircle.norm_coe_eq_abs_iff (1 : ℝ) (by norm_num)).2 (by simpa using ha_abs)
  have hnorm_scalar : ‖(2 * Real.pi * a : ℂ)‖ = 2 * Real.pi * |a| := by
    simp [norm_mul, Real.norm_eq_abs, abs_mul, abs_of_nonneg Real.pi_nonneg]
  have harg : ‖(2 * Real.pi * a : ℂ) * Complex.I‖ ≤ 1 := by
    rw [norm_mul, Complex.norm_I, mul_one, hnorm_scalar, ← hnorm_a]
    have hpi : 0 < 2 * Real.pi := by positivity
    calc
      2 * Real.pi * ‖circleLogCharacter psi x‖ ≤
          2 * Real.pi * (2 * Real.pi)⁻¹ :=
        mul_le_mul_of_nonneg_left hshort hpi.le
      _ = 1 := by field_simp
  have hexp := Complex.norm_exp_sub_one_le harg
  have heval : psi x = Complex.exp ((2 * Real.pi * a : ℂ) * Complex.I) := by
    rw [← coe_toCircle_circleLogCharacter psi x, ← hcoe]
    simp only [AddCircle.toCircle_apply_mk, Circle.coe_exp]
    congr 1
    push_cast
    field_simp
  rw [heval, norm_sub_rev]
  calc
    ‖Complex.exp ((2 * Real.pi * a : ℂ) * Complex.I) - 1‖
        ≤ 2 * ‖(2 * Real.pi * a : ℂ) * Complex.I‖ := hexp
    _ = 4 * Real.pi * ‖circleLogCharacter psi x‖ := by
      rw [norm_mul, Complex.norm_I, mul_one, hnorm_scalar, hnorm_a]
      ring

/-- Chord-length version of signed-span annihilation on an adjoined Bohr
datum. -/
theorem norm_one_sub_character_le_of_mem_adjoinBasis
    (B : BohrData G) {Delta : Finset (AddChar G ℂ)} {kappa r : ℝ≥0}
    {psi : AddChar G ℂ} {x : G}
    (hsmall : (Delta.card : ℝ) * (r : ℝ) ≤ (2 * Real.pi)⁻¹)
    (hx : x ∈ (adjoinBasis B Delta kappa r).carrier)
    (hpsi : psi ∈ Delta.addSpan) :
    ‖1 - psi x‖ ≤ 4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) := by
  have harc := norm_circleLogCharacter_le_card_mul_of_mem_adjoinBasis
    B hx hpsi
  calc
    ‖1 - psi x‖ ≤ 4 * Real.pi * ‖circleLogCharacter psi x‖ :=
      norm_one_sub_character_le_four_pi_mul psi x (harc.trans hsmall)
    _ ≤ 4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) :=
      mul_le_mul_of_nonneg_left harc (by positivity)

/-- If a family of characters is covered by the signed span of `Delta` plus
a residual family, then the adjoined datum annihilates the covered family up
to the sum of the two errors.  This is the algebraic assembly step in the
relative Chang--Sanders argument. -/
theorem norm_one_sub_character_le_of_addSpan_add_cover
    (B : BohrData G) {Delta Q S : Finset (AddChar G ℂ)} {kappa r : ℝ≥0}
    {beta : ℝ} {x : G}
    (hsmall : (Delta.card : ℝ) * (r : ℝ) ≤ (2 * Real.pi)⁻¹)
    (hx : x ∈ (adjoinBasis B Delta kappa r).carrier)
    (hcover : ∀ psi ∈ Q, ∃ z ∈ Delta.addSpan, ∃ s ∈ S, psi = z + s)
    (hresidual : ∀ s ∈ S, ‖1 - s x‖ ≤ beta) :
    ∀ psi ∈ Q,
      ‖1 - psi x‖ ≤ 4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) + beta := by
  intro psi hpsi
  obtain ⟨z, hz, s, hs, rfl⟩ := hcover psi hpsi
  have hzbound :
      ‖1 - z x‖ ≤ 4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) :=
    norm_one_sub_character_le_of_mem_adjoinBasis B hsmall hx hz
  calc
    ‖1 - (z + s) x‖ = ‖(1 - z x) + z x * (1 - s x)‖ := by
      rw [AddChar.add_apply]
      congr 1
      ring
    _ ≤ ‖1 - z x‖ + ‖z x * (1 - s x)‖ := norm_add_le _ _
    _ = ‖1 - z x‖ + ‖1 - s x‖ := by
      rw [norm_mul, AddChar.norm_apply, one_mul]
    _ ≤ 4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) + beta :=
      add_le_add hzbound (hresidual s hs)

/-- Relative-cover specialization for a rank-regular Bohr datum.  The
residual set is the half-large spectrum of the old carrier, so membership in
the old `sigma`-dilate supplies its phase error.  This is the geometric half
of the local Chang--Sanders theorem. -/
theorem norm_one_sub_character_le_of_localSpectrum_cover
    (C : BohrData G) (hreg : C.IsRankRegular)
    {Delta Q : Finset (AddChar G ℂ)} {sigma r : ℝ≥0}
    (hsigma : sigma ≤
      1 / (100 * (max C.rank 1 : ℕ) : ℝ≥0))
    (hsmall : (Delta.card : ℝ) * (r : ℝ) ≤ (2 * Real.pi)⁻¹)
    (hcover : ∀ psi ∈ Q, ∃ z ∈ Delta.addSpan,
      ∃ s ∈ Chang.largeSpectrum C.carrier (1 / 2), psi = z + s) :
    ∀ x ∈ (adjoinBasis C Delta sigma r).carrier, ∀ psi ∈ Q,
      ‖1 - psi x‖ ≤
        4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) +
          400 * ((max C.rank 1 : ℕ) : ℝ) * (sigma : ℝ) := by
  intro x hx
  apply norm_one_sub_character_le_of_addSpan_add_cover
    C hsmall hx hcover
  intro s hs
  exact Erdos140.norm_one_sub_le_of_mem_largeSpectrum_half
    hreg hsigma hs (adjoinBasis_carrier_subset_dilate C Delta sigma r hx)

/-- Rank, subordination, and phase control bundled for the explicit datum
obtained from a local signed-span-plus-spectrum cover. -/
theorem controlled_bohr_of_localSpectrum_cover
    (C : BohrData G) (hreg : C.IsRankRegular)
    {Delta Q : Finset (AddChar G ℂ)} {sigma r : ℝ≥0}
    (hsigma : sigma ≤
      1 / (100 * (max C.rank 1 : ℕ) : ℝ≥0))
    (hsmall : (Delta.card : ℝ) * (r : ℝ) ≤ (2 * Real.pi)⁻¹)
    (hcover : ∀ psi ∈ Q, ∃ z ∈ Delta.addSpan,
      ∃ s ∈ Chang.largeSpectrum C.carrier (1 / 2), psi = z + s) :
    let D := adjoinBasis C Delta sigma r
    D.rank ≤ C.rank + Delta.card ∧
      D.carrier ⊆ (C.dilate sigma).carrier ∧
      ∀ x ∈ D.carrier, ∀ psi ∈ Q,
        ‖1 - psi x‖ ≤
          4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) +
            400 * ((max C.rank 1 : ℕ) : ℝ) * (sigma : ℝ) := by
  refine ⟨adjoinBasis_rank_le C Delta sigma r,
    adjoinBasis_carrier_subset_dilate C Delta sigma r, ?_⟩
  exact norm_one_sub_character_le_of_localSpectrum_cover
    C hreg hsigma hsmall hcover

/-! ## The relative Chang--Sanders Bohr theorem -/

/-- **Relative Chang--Sanders, in explicit Bohr form.**

For a nonempty `X` inside a rank-regular Bohr set `B`, the `eta`-large
spectrum is annihilated on an explicit datum obtained by adjoining at most
`localChangDimension B X eta` frequencies to a regular narrow dilate `C` of
`B`.  The logarithm in that dimension is relative, namely
`log (2 * |B| / |X|)`, and has no ambient-group cardinality.

The parameters `sigma` and `r` are respectively the relative width inside
`C` and the constant width of each new frequency.  The two displayed
hypotheses are precisely the short-arc conditions needed by the old and new
frequency estimates. -/
theorem exists_controlled_relativeLargeSpectrum_bohr
    (B : BohrData G) (hBreg : B.IsRankRegular)
    (X : Finset G) (hX : X.Nonempty) (hXB : X ⊆ B.carrier)
    (eta : ℝ) (heta : 0 < eta) (sigma r : ℝ≥0)
    (hsigma : sigma ≤
      1 / (100 * (max B.rank 1 : ℕ) : ℝ≥0))
    (hr : RelativeChangSanders.localChangDimension B X eta * (r : ℝ) ≤
      (2 * Real.pi)⁻¹) :
    ∃ rho : ℝ≥0, ∃ C : BohrData G,
      ∃ Delta : Finset (AddChar G ℂ),
        1 / 2 ≤ rho ∧ rho ≤ 1 ∧
        C = B.dilate
          (rho * RelativeChangSanders.localChangBaseScale B X eta) ∧
        C.IsRankRegular ∧
        (Delta.card : ℝ) ≤
          RelativeChangSanders.localChangDimension B X eta ∧
        Delta ⊆ Chang.largeSpectrum X eta ∧
        let D := adjoinBasis C Delta sigma r
        D.rank ≤ B.rank + Delta.card ∧
          D.carrier ⊆ (C.dilate sigma).carrier ∧
          ∀ x ∈ D.carrier, ∀ psi ∈ Chang.largeSpectrum X eta,
            ‖1 - psi x‖ ≤
              4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) +
                400 * ((max B.rank 1 : ℕ) : ℝ) * (sigma : ℝ) := by
  classical
  obtain ⟨rho, C, Delta, hrho0, hrho1, hC, hCreg,
      hDeltaCard, hDeltaSpec, hcover⟩ :=
    RelativeChangSanders.exists_relativeLargeSpectrum_cover
      B hBreg X hX hXB eta heta
  have hCrank : C.rank = B.rank := by simp [hC]
  have hsigmaC : sigma ≤
      1 / (100 * (max C.rank 1 : ℕ) : ℝ≥0) := by
    simpa [hCrank] using hsigma
  have hsmall : (Delta.card : ℝ) * (r : ℝ) ≤
      (2 * Real.pi)⁻¹ := by
    exact (mul_le_mul_of_nonneg_right hDeltaCard r.coe_nonneg).trans hr
  have hcontrolled := controlled_bohr_of_localSpectrum_cover
    C hCreg hsigmaC hsmall hcover
  refine ⟨rho, C, Delta, hrho0, hrho1, hC, hCreg,
    hDeltaCard, hDeltaSpec, ?_⟩
  refine ⟨?_, hcontrolled.2.1, ?_⟩
  · simpa [hCrank] using hcontrolled.1
  · intro x hx psi hpsi
    simpa [hCrank] using hcontrolled.2.2 x hx psi hpsi

/-! ## Global Chang-to-Bohr corollary -/

/-- Global Chang's theorem, packaged as a Bohr annihilation statement.  This
corollary is useful when the ambient density `|A|/|G|` is the relevant one;
the relative Chang--Sanders theorem used inside a small ambient Bohr set needs
the additional weighted argument developed separately. -/
theorem exists_bohr_largeSpectrum
    (A : Finset G) (eta theta : ℝ)
    (hA : A.Nonempty) (heta : 0 < eta)
    (htheta0 : 0 ≤ theta) (htheta1 : theta ≤ 1) :
    ∃ D : BohrData G,
      D.rank ≤
        ⌈2 * Real.log ((Fintype.card G : ℝ) / A.card) / eta ^ 2⌉₊ ∧
      ∀ t ∈ D.carrier, ∀ psi ∈ Chang.largeSpectrum A eta,
        ‖1 - psi t‖ ≤ theta := by
  classical
  obtain ⟨Delta, hDeltaSpec, hDeltaCard, hspan⟩ :=
    Chang.exists_largeSpectrum_subset_addSpan A eta hA heta
  let m : ℕ := max Delta.card 1
  have hmpos : (0 : ℝ) < m := by
    exact_mod_cast (show 0 < m by simp [m])
  let r : ℝ≥0 :=
    ⟨theta / (4 * Real.pi * (m : ℝ)),
      div_nonneg htheta0 (by positivity)⟩
  refine ⟨basisBohrData Delta r, ?_, ?_⟩
  · rw [basisBohrData_rank]
    exact hDeltaCard
  · intro t ht psi hpsi
    have hcardm : (Delta.card : ℝ) ≤ (m : ℝ) := by
      exact_mod_cast Nat.le_max_left Delta.card 1
    have hrnonneg : 0 ≤ (r : ℝ) := r.coe_nonneg
    have hspanArc := norm_circleLogCharacter_le_card_mul_of_mem_addSpan
      ht (hspan hpsi)
    have hrbound : (Delta.card : ℝ) * (r : ℝ) ≤ theta / (4 * Real.pi) := by
      calc
        (Delta.card : ℝ) * (r : ℝ) ≤ (m : ℝ) * (r : ℝ) :=
          mul_le_mul_of_nonneg_right hcardm hrnonneg
        _ = theta / (4 * Real.pi) := by
          dsimp [r]
          change (m : ℝ) * (theta / (4 * Real.pi * (m : ℝ))) =
            theta / (4 * Real.pi)
          field_simp [hmpos.ne', Real.pi_ne_zero]
    have hshort : ‖circleLogCharacter psi t‖ ≤ (2 * Real.pi)⁻¹ := by
      apply hspanArc.trans
      apply hrbound.trans
      rw [div_le_iff₀ (by positivity : 0 < 4 * Real.pi)]
      calc
        theta ≤ 2 := htheta1.trans (by norm_num)
        _ = (2 * Real.pi)⁻¹ * (4 * Real.pi) := by
          field_simp [Real.pi_ne_zero]
          norm_num
    calc
      ‖1 - psi t‖ ≤ 4 * Real.pi * ‖circleLogCharacter psi t‖ :=
        norm_one_sub_character_le_four_pi_mul psi t hshort
      _ ≤ 4 * Real.pi * ((Delta.card : ℝ) * (r : ℝ)) :=
        mul_le_mul_of_nonneg_left hspanArc (by positivity)
      _ ≤ 4 * Real.pi * (theta / (4 * Real.pi)) :=
        mul_le_mul_of_nonneg_left hrbound (by positivity)
      _ = theta := by field_simp

end Erdos140.LocalSpectrum

#print axioms Erdos140.LocalSpectrum.circleLogCharacter_injective
#print axioms Erdos140.LocalSpectrum.norm_circleLogCharacter_le_card_mul_of_mem_addSpan
#print axioms Erdos140.LocalSpectrum.adjoinBasis_carrier_eq_inter
#print axioms Erdos140.LocalSpectrum.norm_one_sub_character_le_four_pi_mul
#print axioms Erdos140.LocalSpectrum.norm_one_sub_character_le_of_mem_adjoinBasis
#print axioms Erdos140.LocalSpectrum.norm_one_sub_character_le_of_addSpan_add_cover
#print axioms Erdos140.LocalSpectrum.norm_one_sub_character_le_of_localSpectrum_cover
#print axioms Erdos140.LocalSpectrum.controlled_bohr_of_localSpectrum_cover
#print axioms Erdos140.LocalSpectrum.exists_controlled_relativeLargeSpectrum_bohr
#print axioms Erdos140.LocalSpectrum.exists_bohr_largeSpectrum
