/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
import ErdosProblems.Erdos547b.Claim616HierarchicalCoordinateHostLayout
import ErdosProblems.Erdos547b.Claim616CoordinateEdgeMaps
import ErdosProblems.Erdos547b.Claim616RichCoordinateAllocation

/-!
# Relevance of the concrete rich coordinate slots

Every slot generated by the rich source allocation belongs to one of the
three literal decomposition edge families recognized by the coordinate host
layout.  This is a source/host-index statement only.
-/

open scoped SimpleGraph
noncomputable section

namespace Erdos547b.ZhaoClaim616CoordinateSlotRelevance

open Finset Fintype SimpleGraph
open Erdos547b.ZhaoStability
open Erdos547b.TreePartition
open Erdos547b.ZhaoClaim68ParityHalf
open Erdos547b.ZhaoClaim617BranchCount
open Erdos547b.ZhaoClaim616
open Erdos547b.ZhaoLemma611Full
open Erdos547b.ZhaoClaim616SourceBridge
open Erdos547b.ZhaoClaim616ResidualAllocation
open Erdos547b.ZhaoClaim616HierarchyClassification
open Erdos547b.ZhaoClaim616HierarchicalAllocation
open Erdos547b.ZhaoClaim616HierarchicalCoordinateSourceLayout
open Erdos547b.ZhaoClaim616HierarchicalCoordinateHostLayout
open Erdos547b.ZhaoClaim616CoordinateEdgeMaps
open Erdos547b.ZhaoClaim616RichCoordinateAllocation

universe u v w

variable {V : Type u} {B : Type v} {K : Type w}
variable [Fintype V] [DecidableEq V]
variable [Fintype B] [DecidableEq B] [Fintype K] [DecidableEq K]
variable {T : SimpleGraph V} [DecidableRel T.Adj]
variable {globalRoot : V} {small target slack : ℕ}
variable (G : SimpleGraph B) [DecidableRel G.Adj]
variable (cluster : K → Finset B) (epsilon density : ℚ)
variable [DecidableRel
  (regularityReducedGraph G cluster epsilon density).Adj]
variable {L O : Finset K} {miss lowerV1 upperV1 upperV2 mbBound : ℕ}
variable {C67 : Claim67Certificate
  (regularityReducedGraph G cluster epsilon density) L miss}
variable {degreeA : Finset (MatchingEdge C67.M) → ℝ}
variable
  (D : MatchingDecomposition L O miss C67 lowerV1 upperV1 upperV2 mbBound
    degreeA)
variable (C : Finset K)

variable
    (hT : T.IsTree) (P : ZhaoForestPartition T globalRoot small)
    (optional : Finset V)
    (S : SelectedF0Within (branchForest P) (halfBranches P) target slack)
    (clusterCap base0 base1 baseb : ℕ)
    (orient : BranchIndex P → Fin 2 ≃ Fin 2)

/- The allowed-access finsets do not affect the slot definitions.  To keep
the theorem usable with the actual indexed allowed sets, the main statements
below quantify that function rather than using the convenient `univ` value
from the section declaration. -/

theorem coordinateRootSlot_relevant
    (allowed0 : Fin C.card →
      Finset (Fin D.Mout.edgeSet.toFinite.toFinset.card))
    (A : SourceSegmentAllocation hT P optional S
      (fun _ : Fin C.card ↦ clusterCap) allowed0
      (fun _ : RemainingMinEdge D C ↦ base1)
      (fun _ : ReservedEdge D ↦ baseb) base0)
    (i : SegmentIndex hT P optional) :
    RelevantSlot (G := G) (cluster := cluster) (epsilon := epsilon)
      (density := density) (D := D) (C := C)
      (coordinateHierarchyRootSlot hT P optional S
        (fun _ : Fin C.card ↦ clusterCap) allowed0
        (fun _ : RemainingMinEdge D C ↦ base1)
        (fun _ : ReservedEdge D ↦ baseb) base0 A
        (fun e : RemainingMinEdge D C ↦ e.1)
        (fun e : ReservedEdge D ↦ e.1) orient i) := by
  cases hclass : segmentSourceClass hT P optional i with
  | inl q => simp [coordinateHierarchyRootSlot, RelevantSlot, hclass]
  | inr j =>
      by_cases hj0 : j ∈ S.selected
      · simp [coordinateHierarchyRootSlot, coordinateBranchRootSlot,
          RelevantSlot, hclass, hj0]
      · by_cases hj1 : j ∈ majorResidualBranches P S
        · simpa [coordinateHierarchyRootSlot, coordinateBranchRootSlot,
            RelevantSlot, hclass, hj0, hj1] using (Or.inl (A.F1edge j).2)
        · simpa [coordinateHierarchyRootSlot, coordinateBranchRootSlot,
            RelevantSlot, hclass, hj0, hj1] using
            (Or.inr (D.mb_subset (A.Fbedge j).2))

theorem coordinateInteriorSlot_relevant
    (allowed0 : Fin C.card →
      Finset (Fin D.Mout.edgeSet.toFinite.toFinset.card))
    (A : SourceSegmentAllocation hT P optional S
      (fun _ : Fin C.card ↦ clusterCap) allowed0
      (fun _ : RemainingMinEdge D C ↦ base1)
      (fun _ : ReservedEdge D ↦ baseb) base0)
    (i : SegmentIndex hT P optional)
    (a : Fin ((AllocationHierarchy hT P optional).segments.size i)) :
    RelevantSlot (G := G) (cluster := cluster) (epsilon := epsilon)
      (density := density) (D := D) (C := C)
      (coordinateHierarchyInteriorSlot hT P optional S
        (fun _ : Fin C.card ↦ clusterCap) allowed0
        (fun _ : RemainingMinEdge D C ↦ base1)
        (fun _ : ReservedEdge D ↦ baseb) base0 A
        (moutOriginalEdge D)
        (fun e : RemainingMinEdge D C ↦ e.1)
        (fun e : ReservedEdge D ↦ e.1) orient i a) := by
  cases hclass : segmentSourceClass hT P optional i with
  | inl q =>
      unfold coordinateHierarchyInteriorSlot
      rw [hclass]
      simp [RelevantSlot]
  | inr j =>
      rw [coordinateHierarchyInteriorSlot_branch hT P optional S
        (fun _ : Fin C.card ↦ clusterCap) allowed0
        (fun _ : RemainingMinEdge D C ↦ base1)
        (fun _ : ReservedEdge D ↦ baseb) base0 A
        (moutOriginalEdge D)
        (fun e : RemainingMinEdge D C ↦ e.1)
        (fun e : ReservedEdge D ↦ e.1) orient i j hclass a]
      by_cases hj0 : j ∈ S.selected
      · simpa [hj0, RelevantSlot] using
          (Or.inr (moutOriginalEdge_mem D (A.F0edge j)))
      · by_cases hj1 : j ∈ majorResidualBranches P S
        · simpa [hj0, hj1, RelevantSlot] using (Or.inl (A.F1edge j).2)
        · simpa [hj0, hj1, RelevantSlot] using
            (Or.inr (D.mb_subset (A.Fbedge j).2))

end Erdos547b.ZhaoClaim616CoordinateSlotRelevance

#print axioms Erdos547b.ZhaoClaim616CoordinateSlotRelevance.coordinateRootSlot_relevant
#print axioms Erdos547b.ZhaoClaim616CoordinateSlotRelevance.coordinateInteriorSlot_relevant
