/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
import ErdosProblems.Erdos547b.Claim616CoordinateRootLoad
import ErdosProblems.Erdos547b.Claim616HierarchyCoordinatePoolLoad

/-!
# Load bounds on the actual coordinate slots

The three matching-edge maps need not have globally disjoint ranges: an
unused `M_out` edge may also be an `M_b` edge.  Consequently the sound total
statement is indexed by slots actually generated by the source layout.  Such
a slot carries its source class, so it can be bounded by exactly the matching
family that generated it.
-/

open scoped SimpleGraph BigOperators
noncomputable section

namespace Erdos547b.ZhaoClaim616CoordinateActualLoad

open Finset Fintype SimpleGraph
open Erdos547b.TreePartition
open Erdos547b.ZhaoClaim68
open Erdos547b.ZhaoClaim68BranchAdapter
open Erdos547b.ZhaoClaim617BranchCount
open Erdos547b.ZhaoClaim616SourceBridge
open Erdos547b.ZhaoClaim616ResidualAllocation
open Erdos547b.ZhaoClaim616HierarchyClassification
open Erdos547b.ZhaoClaim616HierarchyAttachments
open Erdos547b.ZhaoClaim616HierarchicalAllocation
open Erdos547b.ZhaoClaim616HierarchicalSourceLayout
open Erdos547b.ZhaoClaim616HierarchicalCoordinateSourceLayout
open Erdos547b.ZhaoClaim616CoordinateRootLoad
open Erdos547b.ZhaoClaim616HierarchyCoordinatePoolLoad
open Erdos547b.ZhaoLemma58GroupedSmallForest
open Erdos547b.ZhaoLemma59HierarchicalCoordinatePools
open Erdos547b.ZhaoLemma59HierarchicalCoordinatePools.HierarchicalSegmentForest

universe u

variable {V : Type u} [Fintype V] [DecidableEq V]
variable {T : SimpleGraph V} [DecidableRel T.Adj]
variable {globalRoot : V} {small target slack : ℕ}

section

variable
    {CIndex K0 K1 Kb Edge : Type*}
    [Fintype CIndex] [DecidableEq CIndex]
    [Fintype K0] [DecidableEq K0]
    [Fintype K1] [DecidableEq K1]
    [Fintype Kb] [DecidableEq Kb]
    [DecidableEq Edge]

variable
    (hT : T.IsTree) (P : ZhaoForestPartition T globalRoot small)
    (optional : Finset V)
    (S : SelectedF0Within (branchForest P) (halfBranches P) target slack)
    (clusterCapacity : CIndex → ℕ)
    (allowed0 : CIndex → Finset K0)
    (capacity1 : K1 → ℕ) (capacityb : Kb → ℕ) (base0 : ℕ)
    (A : SourceSegmentAllocation hT P optional S clusterCapacity allowed0
      capacity1 capacityb base0)
    (edge0 : K0 → Edge) (edge1 : K1 → Edge) (edgeb : Kb → Edge)
    (orient : BranchIndex P → Fin 2 ≃ Fin 2)

private abbrev sourceRootPool :=
  coordinateHierarchyRootSlot hT P optional S clusterCapacity allowed0
    capacity1 capacityb base0 A edge1 edgeb orient

private abbrev sourceInteriorPool :=
  coordinateHierarchyInteriorSlot hT P optional S clusterCapacity allowed0
    capacity1 capacityb base0 A edge0 edge1 edgeb orient

variable
    (cap : RootSlot CIndex Edge → ℕ)
    (hparity : OptionalBranchRootParity P optional)
    (hedge0 : Function.Injective edge0)
    (hedge1 : Function.Injective edge1)
    (hedgeb : Function.Injective edgeb)
    (hdisj01 : Disjoint (Finset.univ.image edge0) (Finset.univ.image edge1))
    (hF0b : ∀ j ∈ S.selected, ∀ eb, edge0 (A.F0edge j) ≠ edgeb eb)
    (hdisj1b : Disjoint (Finset.univ.image edge1) (Finset.univ.image edgeb))
    (hroot : ∀ side,
      #(rootReservoirSegments hT P optional side) ≤ cap (Sum.inl side))
    (hcluster : ∀ C0,
      clusterCapacity C0 ≤ cap (Sum.inr (Sum.inl C0)))
    (hside0 : ∀ e c,
      (∑ j ∈ S.selected.filter (A.F0edge · = e),
          orientedClassSize (branchForest P).branches orient j c) ≤
        cap (Sum.inr (Sum.inr ⟨edge0 e, c⟩)))
    (hside1 : ∀ e c,
      (∑ j ∈ (majorResidualBranches P S).filter (A.F1edge · = e),
          orientedClassSize (branchForest P).branches orient j c) ≤
        cap (Sum.inr (Sum.inr ⟨edge1 e, c⟩)))
    (hsideb : ∀ e c,
      (∑ j ∈ (minorBranches P).filter (A.Fbedge · = e),
          orientedClassSize (branchForest P).branches orient j c) ≤
        cap (Sum.inr (Sum.inr ⟨edgeb e, c⟩)))

include hparity hedge1 hedgeb hdisj01 hF0b hdisj1b hroot hcluster hside1
  hsideb

/-- Every root slot actually generated by the coordinate hierarchy satisfies
its prescribed capacity bound. -/
theorem coordinateRootSlot_load_le (i : SegmentIndex hT P optional) :
    coordinatePoolLoad (AllocationHierarchy hT P optional)
        (sourceRootPool hT P optional S clusterCapacity allowed0 capacity1
          capacityb base0 A edge1 edgeb orient)
        (sourceInteriorPool hT P optional S clusterCapacity allowed0 capacity1
          capacityb base0 A edge0 edge1 edgeb orient)
        (sourceRootPool hT P optional S clusterCapacity allowed0 capacity1
          capacityb base0 A edge1 edgeb orient i) ≤
      cap (sourceRootPool hT P optional S clusterCapacity allowed0 capacity1
        capacityb base0 A edge1 edgeb orient i) := by
  unfold sourceRootPool sourceInteriorPool
  cases hclass : segmentSourceClass hT P optional i with
  | inl q =>
      simp only [coordinateHierarchyRootSlot, hclass]
      exact coordinatePoolLoad_rootReservoir_le hT P optional S clusterCapacity
        allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient _ _
        (hroot (componentReservoirSide P q))
  | inr j =>
      rw [coordinateHierarchyRootSlot_branch hT P optional S clusterCapacity
        allowed0 capacity1 capacityb base0 A edge1 edgeb orient i j hclass]
      by_cases hj0 : j ∈ S.selected
      · simp only [coordinateBranchRootSlot, dif_pos hj0]
        exact (coordinatePoolLoad_selectedCluster_le hT P optional S
          clusterCapacity allowed0 capacity1 capacityb base0 A edge0 edge1
          edgeb orient (A.F0cluster j)).trans (hcluster (A.F0cluster j))
      · by_cases hj1 : j ∈ majorResidualBranches P S
        · simp only [coordinateBranchRootSlot, dif_neg hj0, dif_pos hj1]
          exact (coordinatePoolLoad_edge1_le hT P optional S clusterCapacity
            allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient
            hparity hedge1 hdisj01 hdisj1b (A.F1edge j) (orient j 0)).trans
              (hside1 (A.F1edge j) (orient j 0))
        · simp only [coordinateBranchRootSlot, dif_neg hj0, dif_neg hj1]
          exact (coordinatePoolLoad_edgeb_le hT P optional S clusterCapacity
            allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient
            hparity hedgeb hF0b hdisj1b (A.Fbedge j) (orient j 0)).trans
              (hsideb (A.Fbedge j) (orient j 0))

omit hcluster
include hedge0 hside0

/-- Every coordinate slot actually generated by the hierarchy satisfies its
prescribed capacity bound. -/
theorem coordinateInteriorSlot_load_le
    (i : SegmentIndex hT P optional)
    (a : Fin ((AllocationHierarchy hT P optional).segments.size i)) :
    coordinatePoolLoad (AllocationHierarchy hT P optional)
        (sourceRootPool hT P optional S clusterCapacity allowed0 capacity1
          capacityb base0 A edge1 edgeb orient)
        (sourceInteriorPool hT P optional S clusterCapacity allowed0 capacity1
          capacityb base0 A edge0 edge1 edgeb orient)
        (sourceInteriorPool hT P optional S clusterCapacity allowed0 capacity1
          capacityb base0 A edge0 edge1 edgeb orient i a) ≤
      cap (sourceInteriorPool hT P optional S clusterCapacity allowed0
        capacity1 capacityb base0 A edge0 edge1 edgeb orient i a) := by
  unfold sourceRootPool sourceInteriorPool
  cases hclass : segmentSourceClass hT P optional i with
  | inl q =>
      have hslot :
          coordinateHierarchyInteriorSlot hT P optional S clusterCapacity
              allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient
              i a =
            (Sum.inl (componentReservoirSide P q) : RootSlot CIndex Edge) := by
        unfold coordinateHierarchyInteriorSlot
        rw [hclass]
      rw [hslot]
      exact coordinatePoolLoad_rootReservoir_le hT P optional S clusterCapacity
        allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient _ _
        (hroot (componentReservoirSide P q))
  | inr j =>
      rw [coordinateHierarchyInteriorSlot_branch hT P optional S
        clusterCapacity allowed0 capacity1 capacityb base0 A edge0 edge1
        edgeb orient i j hclass a]
      by_cases hj0 : j ∈ S.selected
      · simp only [dif_pos hj0]
        exact (coordinatePoolLoad_edge0_le hT P optional S clusterCapacity
          allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient hedge0
          hdisj01 hF0b (A.F0edge j) ⟨j, hj0, rfl⟩
          (orient j (segmentEndpointSide hT P optional i j a))).trans
            (hside0 (A.F0edge j)
              (orient j (segmentEndpointSide hT P optional i j a)))
      · by_cases hj1 : j ∈ majorResidualBranches P S
        · simp only [dif_neg hj0, dif_pos hj1]
          exact (coordinatePoolLoad_edge1_le hT P optional S clusterCapacity
            allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient
            hparity hedge1 hdisj01 hdisj1b (A.F1edge j)
            (orient j (segmentEndpointSide hT P optional i j a))).trans
              (hside1 (A.F1edge j)
                (orient j (segmentEndpointSide hT P optional i j a)))
        · simp only [dif_neg hj0, dif_neg hj1]
          exact (coordinatePoolLoad_edgeb_le hT P optional S clusterCapacity
            allowed0 capacity1 capacityb base0 A edge0 edge1 edgeb orient
            hparity hedgeb hF0b hdisj1b (A.Fbedge j)
            (orient j (segmentEndpointSide hT P optional i j a))).trans
              (hsideb (A.Fbedge j)
                (orient j (segmentEndpointSide hT P optional i j a)))

end

end Erdos547b.ZhaoClaim616CoordinateActualLoad

#print axioms Erdos547b.ZhaoClaim616CoordinateActualLoad.coordinateRootSlot_load_le
#print axioms Erdos547b.ZhaoClaim616CoordinateActualLoad.coordinateInteriorSlot_load_le
