/-
Copyright (c) 2026 Sebastian Kumar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Sebastian Kumar
-/
module

/- Adapted from mathlib PR #28246, commit
037ad801e1e5a5b7aa1750957c07f7769812effc. See PROVENANCE.md for local changes. -/

public import Wikipedia.NoExoticSixSphere.Topology.Compat

/-!
# The van Kampen Theorem

This file develops the topological foundations for the van Kampen theorem,
which computes the fundamental group (and groupoid) of a topological space covered
by a collection of path-connected open sets.

Currently, this file provides the heavily analytical "surjectivity" half of the
theorem: the path factorization lemma. It proves that any loop in a space covered
by open sets (whose pairwise intersections are path-connected) can be factored
up to homotopy into a concatenation of loops, each entirely contained within a
single set of the cover.

## Main results

- `exists_loops_homotopic_concat_of_open_cover`: Decomposes a path into a sequence
  of loops subordinate to an open cover. This is Lemma 1.15 from [hatcher02].

## TODO

- Formulate and prove the "injectivity" half of the theorem (showing that the
  kernel of the natural map is generated by the fundamental groups of the pairwise
  intersections).
- State the final van Kampen theorem as a pushout of fundamental groups
  (and fundamental groupoids).

## References

* [A. Hatcher, *Algebraic Topology*][hatcher02]
-/

@[expose] public section

open Fin Set unitInterval

universe u v

variable {X : Type u} [TopologicalSpace X] {ι : Type v} {c : ι → Set X} {a b : X}

namespace Path

/-- Given a path `γ` in a space `X` and an open cover of `X`, we can pull back to a partition
of `[0, 1]` such that, on each element, `γ` is contained in a fixed element of our open cover. -/
theorem exists_partition_unitInterval_of_open_cover (hc₁ : ∀ i, IsOpen (c i))
    (hc₂ : univ ⊆ ⋃ i, c i) (γ : Path a a) : ∃ (n : ℕ) (t : Fin (n + 2) → I),
    t 0 = 0 ∧ t (last (n + 1)) = 1 ∧
      ∀ k : Fin (n + 1), ∃ i, γ '' (uIcc (t k.castSucc) (t k.succ)) ⊆ c i := by
  have ⟨t, ht₀, ht_mono, ⟨n, ht₁⟩, ht_sub⟩ := exists_monotone_Icc_subset_open_cover_unitInterval
    (fun i ↦ IsOpen.preimage (Path.continuous γ) (hc₁ i))
    (fun s _ ↦ (preimage_iUnion ▸ hc₂ (mem_univ _)))
  use n, t ∘ Fin.toNat
  suffices ∀ (k : Fin (n + 1)), ∃ i, uIcc (t ↑k) (t (↑k + 1)) ⊆ ⇑γ ⁻¹' c i by simpa [ht₀, ht₁]
  intro k
  have ⟨i, hi⟩ := ht_sub k
  use i
  rwa [uIcc_of_le (ht_mono (Nat.le_add_right _ _))]

/-- If we have a cover with pairwise path connected intersections, then we can extract a sequence
of paths whose range lie in such intersections. -/
theorem exists_path_range_of_isPathConnected_inter (hc₃ : ∀ i j, IsPathConnected (c i ∩ c j))
    (ha : ∀ i, a ∈ c i) {n : ℕ} (τ : Fin (n + 1) → ι) (p : Fin (n + 2) → X)
    (hτ₁ : ∀ k, p k.castSucc ∈ c (τ k)) (hτ₂ : ∀ k, p k.succ ∈ c (τ k)) :
    ∀ k : Fin n, ∃ g : Path a (p k.succ.castSucc),
      Set.range g ⊆ c (τ k.castSucc) ∩ c (τ k.succ) := by
  intro k
  have ⟨γ, hγ⟩ := (hc₃ (τ k.castSucc) (τ k.succ)).joinedIn
    a ⟨ha (τ k.castSucc), ha (τ k.succ)⟩ (p k.castSucc.succ) ⟨hτ₂ k.castSucc, hτ₁ k.succ⟩
  use γ
  exact range_subset_iff.mpr hγ

namespace Homotopic

/-- Cancellation at a junction, stated without dependent subdivision indices. -/
private lemma cancel_junction {a b c d e f : X}
    (p : Path a b) (q : Path b c) (r : Path d c) (s : Path c e) (t : Path e f) :
    ((p ≫ₚ q ≫ₚ r.symm) ≫ₚ (r ≫ₚ s ≫ₚ t)).Homotopic (p ≫ₚ (q ≫ₚ s) ≫ₚ t) := by
  apply Quotient.exact
  simp only [Quotient.mk_trans, Quotient.mk_symm, Quotient.trans_assoc]
  rw [← Quotient.trans_assoc (Quotient.mk r).symm (Quotient.mk r),
    Quotient.symm_trans, Quotient.refl_trans]

/-- This lemma looks complicated but amounts to cancelling out each path `G k` with its reverse. -/
lemma concat_trans_trans_symm {n : ℕ} (p q : Fin (n + 1) → X)
    (F : ∀ k : Fin n, Path (p k.castSucc) (p k.succ)) (G : ∀ k : Fin (n + 1), Path (q k) (p k)) :
    (concat q (fun k ↦ (G k.castSucc) ≫ₚ (F k) ≫ₚ (G k.succ).symm)).Homotopic
      ((G 0) ≫ₚ (concat p F) ≫ₚ (G (last n)).symm) := by
  induction n with
  | zero =>
    simp only [concat_zero, ← FundamentalGroupoid.fromPath_eq_iff_homotopic]
    aesop_cat
  | succ n hn =>
    have ih := hn (p ∘ castSucc) (q ∘ castSucc)
      (fun k ↦ F k.castSucc) (fun k ↦ G k.castSucc)
    rw [concat_succ q, concat_succ p]
    exact (ih.hcomp (Homotopic.refl _)).trans
      (cancel_junction (G 0) (concat (p ∘ castSucc) (fun k ↦ F k.castSucc))
        (G (last n).castSucc) (F (last n)) (G (last (n + 1))).symm)

/-- Technical lemma to prove homotopy in `exists_loops_homotopic_concat_of_open_cover`. -/
private lemma cast_trans_trans_homotopic_of_homotopic_cast {x x₀ x₁ : X} {h₀ : x₀ = x} {h₁ : x₁ = x}
    {p : Path x₀ x₁} {q : Path x x} (h : p.Homotopic (q.cast h₀ h₁)) :
    (((Path.refl x).cast rfl h₀) ≫ₚ p ≫ₚ ((Path.refl x).cast h₁ rfl)).Homotopic q := by
  subst_vars
  exact trans (trans ⟨Homotopy.reflTrans _⟩ ⟨Homotopy.transRefl _⟩) h

/-- If a topological space `X` can be covered by open sets `c i` whose pairwise intersections
are path-connected, then for any path `γ` with basepoint `a` in the intersection of the `c i`'s
we may find a sequence of loops `D k`, each contained in some `c i`, such that `γ` is homotopic
to the concatenation of the `D k`'s.

This is Lemma 1.15 from [hatcher02]. -/
theorem exists_loops_homotopic_concat_of_open_cover (hc₁ : ∀ i, IsOpen (c i))
    (hc₂ : univ ⊆ ⋃ i, c i) (hc₃ : ∀ i j, IsPathConnected (c i ∩ c j)) (ha : ∀ i, a ∈ c i)
    (γ : Path a a) : ∃ (n : ℕ) (D : Fin (n + 1) → Path a a), Homotopic (concat (fun _ ↦ a) D) γ
      ∧ (∀ k, ∃ i : ι , Set.range (D k) ⊆ c i) := by
  have ⟨n, t, ht₀, ht₁, ht_range⟩ := exists_partition_unitInterval_of_open_cover hc₁ hc₂ γ
  -- `τ` indexes a sequence of sets in our open cover which our path traverses between.
  choose τ hτ using ht_range
  have := exists_path_range_of_isPathConnected_inter hc₃ ha τ (γ ∘ t)
    (fun k ↦ hτ k (mem_image_of_mem γ left_mem_uIcc))
    (fun k ↦ hτ k (mem_image_of_mem γ right_mem_uIcc))
  /- `G k` is a path lying in `c (τ k.castSucc) ∩ c (τ k.succ)` which connects our basepoint `a`
  to the point `γ (t k)`. Note that `γ (t k)` is where our path changes from lying in
  `c (τ k.castSucc)` to lying in `c (τ k.succ)`. -/
  choose G hG using this
  -- We add `Path.refl a` to the start and end of `G` to obtain `G'`.
  let G' := snoc (α := fun k ↦ Path a (γ (t k)))
    (cons (α := fun k ↦ Path a (γ (t k.castSucc))) ((Path.refl a).cast rfl (ht₀ ▸ γ.source)) G)
    ((Path.refl a).cast rfl (ht₁ ▸ γ.target))
  -- We now list some basic properties of `G'` to be used later in the proof.
  have hG'₀ : G' 0 = (Path.refl a).cast rfl (ht₀ ▸ γ.source) :=
    (snoc_apply_zero _ _).trans (cons_zero _ _)
  have hG'₁ : G' (last (n + 1)) = (Path.refl a).cast rfl (ht₁ ▸ γ.target) := snoc_last _ _
  have hG'_range₀ k : range (G' k.castSucc) ⊆ c (τ k) := by
    unfold G'
    rw [snoc_castSucc]
    cases k using Fin.cases with
    | zero =>
      change range (fun _ : I ↦ a) ⊆ c (τ 0)
      simpa only [range_const, singleton_subset_iff] using ha (τ 0)
    | succ j => exact (subset_inter_iff.mp (hG j)).right
  have hG'_range₁ k : range (G' k.succ) ⊆ c (τ k) := by
    unfold G'
    cases k using Fin.lastCases with
    | cast => rw [succ_castSucc, snoc_castSucc]; exact (subset_inter_iff.mp (hG _)).left
    | last =>
      rw [succ_last, snoc_last]
      change range (fun _ : I ↦ a) ⊆ c (τ (last n))
      simpa only [range_const, singleton_subset_iff] using ha (τ (last n))
  /- Our desired sequence of loops is obtained by concatenating each subpath of `γ` lying in some
  element `c (τ k)` of our open cover with the paths `G' (k.castSucc)` and `(G' (k. succ)).symm`.
  Intuitively, we are attaching both ends of our subpath to our basepoint by leveraging `G'`.
  Our previously established results then make it relatively easy to prove that the concatenation
  of these loops is homotopic to `γ`, and that each loop has the appropriate range. -/
  use n, fun k ↦
    (G' k.castSucc) ≫ₚ (γ.subpath (t k.castSucc) (t k.succ)) ≫ₚ (G' k.succ).symm
  constructor
  · apply trans (concat_trans_trans_symm _ _ _ _)
    rw [hG'₀, hG'₁, ← cast_symm, refl_symm]
    refine cast_trans_trans_homotopic_of_homotopic_cast (trans (concat_subpath _ _) ?_)
    rw! (castMode := .all) [ht₀, ht₁, subpath_zero_one]
    rfl
  · intro k
    use τ k
    grind [trans_range, symm_range, union_subset, range_subpath]

end Path.Homotopic
