import ErdosProblems.Erdos1002.GaussRoofIdentity
import ErdosProblems.Erdos1002.GaussTransferAdjoint
import ErdosProblems.Erdos1002.GaussPrefixMarkedMixedFourier

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# Relative mixing of an arbitrary finite Gauss prefix with the future

The one-digit transfer estimate is not, by itself, an estimate for the
sigma-algebra generated by a whole finite prefix.  This file supplies the
missing bridge.  We first compute the exact conditional tail density of an
arbitrary positive word.  Its closed Möbius formula gives distortion and
Lipschitz constants independent of the word length.  Positive mixtures then
give the same bounds for every event measurable with respect to the finite
prefix partition, and the already proved transfer contraction removes a
positive gap.
-/

open Filter MeasureTheory Set
open scoped BigOperators ENNReal NNReal Topology

namespace Erdos1002

noncomputable section

/-! ## The exact density of one inverse word -/

/-- Radon--Nikodym density of the inverse branch encoded by `w`, relative to
Gauss measure.  The recursion is in the same order as `gaussInverseWord`:
the density of the outer branch is evaluated at the inverse image of the
remaining tail. -/
def gaussPrefixTailRatio : List ℕ → ℝ → ℝ
  | [], _ => 1
  | q :: w, y =>
      gaussPrefixTailRatio w y *
        gaussBranchRatio q (gaussInverseWord w y)

@[simp] theorem gaussPrefixTailRatio_nil (y : ℝ) :
    gaussPrefixTailRatio [] y = 1 := rfl

@[simp] theorem gaussPrefixTailRatio_cons (q : ℕ) (w : List ℕ) (y : ℝ) :
    gaussPrefixTailRatio (q :: w) y =
      gaussPrefixTailRatio w y *
        gaussBranchRatio q (gaussInverseWord w y) := rfl

/-- Closed Möbius formula for the inverse-word density. -/
theorem gaussPrefixTailRatio_eq_mobius
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    gaussPrefixTailRatio w y =
      (1 + y) /
        ((((gaussPrefixMobius w).C : ℝ) * y +
              (gaussPrefixMobius w).D) *
          ((((gaussPrefixMobius w).A : ℝ) +
                (gaussPrefixMobius w).C) * y +
            ((gaussPrefixMobius w).B : ℝ) +
              (gaussPrefixMobius w).D)) := by
  induction w with
  | nil =>
      norm_num [gaussPrefixTailRatio, gaussPrefixMobius]
      have hy1 : 1 + y ≠ 0 := by linarith [hy.1]
      rw [show y + 1 = 1 + y by ring, div_self hy1]
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : IsPositiveCFWord w := by
        intro a ha
        exact hpos a (by simp [ha])
      let M := gaussPrefixMobius w
      let d : ℝ := (M.C : ℝ) * y + M.D
      let n : ℝ := (M.A : ℝ) * y + M.B
      have hD : (0 : ℝ) < M.D := by
        dsimp [M]
        exact_mod_cast gaussPrefixMobius_D_pos htail
      have hA : (0 : ℝ) ≤ M.A := Nat.cast_nonneg _
      have hB : (0 : ℝ) ≤ M.B := Nat.cast_nonneg _
      have hC : (0 : ℝ) ≤ M.C := Nat.cast_nonneg _
      have hn : 0 ≤ n := by
        dsimp [n]
        exact add_nonneg (mul_nonneg hA hy.1) hB
      have hd : 0 < d := by
        dsimp [d]
        exact add_pos_of_nonneg_of_pos (mul_nonneg hC hy.1) hD
      have hqR : (0 : ℝ) < q := by exact_mod_cast hq
      have hqd : 0 < (q : ℝ) * d + n := by
        exact add_pos_of_pos_of_nonneg (mul_pos hqR hd) hn
      have hqsd : 0 < ((q : ℝ) + 1) * d + n := by
        exact add_pos_of_pos_of_nonneg
          (mul_pos (by linarith : 0 < (q : ℝ) + 1) hd) hn
      rw [gaussPrefixTailRatio_cons, ih htail,
        gaussInverseWord_eq_gaussPrefixMobius htail hy.1]
      simp only [gaussPrefixMobius_cons_A, gaussPrefixMobius_cons_B,
        gaussPrefixMobius_cons_C, gaussPrefixMobius_cons_D]
      push_cast
      have hold :
          (((M.A : ℝ) + M.C) * y + (M.B : ℝ) + M.D) = n + d := by
        dsimp [n, d]
        ring
      have hnew₁ :
          (((q : ℝ) * M.C + M.A) * y +
              ((q : ℝ) * M.D + M.B)) = (q : ℝ) * d + n := by
        dsimp [n, d]
        ring
      have hnew₂ :
          (((M.C : ℝ) + ((q : ℝ) * M.C + M.A)) * y +
              (M.D : ℝ) + ((q : ℝ) * M.D + M.B)) =
            ((q : ℝ) + 1) * d + n := by
        dsimp [n, d]
        ring
      change
        (1 + y) / (d *
            (((M.A : ℝ) + M.C) * y + (M.B : ℝ) + M.D)) *
              gaussBranchRatio q (n / d) =
          (1 + y) /
            ((((q : ℝ) * M.C + M.A) * y +
                ((q : ℝ) * M.D + M.B)) *
              (((M.C : ℝ) + ((q : ℝ) * M.C + M.A)) * y +
                (M.D : ℝ) + ((q : ℝ) * M.D + M.B)))
      rw [hold, hnew₁, hnew₂]
      have hbranch :
          gaussBranchRatio q (n / d) =
            ((n + d) * d) /
              (((q : ℝ) * d + n) * (((q : ℝ) + 1) * d + n)) := by
        unfold gaussBranchRatio
        field_simp [ne_of_gt hd, ne_of_gt hqd, ne_of_gt hqsd]
        ring
      rw [hbranch]
      have hnd : 0 < n + d := add_pos_of_nonneg_of_pos hn hd
      field_simp [ne_of_gt hd, ne_of_gt hnd, ne_of_gt hqd,
        ne_of_gt hqsd]

/-! ## Uniform distortion of every word density -/

/-- Besides `C ≤ D`, the second pair of denominator coefficients obeys the
matching inequality `A+C ≤ B+D`. -/
theorem gaussPrefixMobius_A_add_C_le_B_add_D
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    (gaussPrefixMobius w).A + (gaussPrefixMobius w).C ≤
      (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by
  induction w with
  | nil => simp [gaussPrefixMobius]
  | cons q w ih =>
      have htail : IsPositiveCFWord w := by
        intro a ha
        exact hpos a (by simp [ha])
      have hCD := gaussPrefixMobius_C_le_D htail
      simp only [gaussPrefixMobius_cons_A, gaussPrefixMobius_cons_B,
        gaussPrefixMobius_cons_C, gaussPrefixMobius_cons_D]
      calc
        (gaussPrefixMobius w).C +
              (q * (gaussPrefixMobius w).C + (gaussPrefixMobius w).A) =
            q * (gaussPrefixMobius w).C +
              ((gaussPrefixMobius w).A + (gaussPrefixMobius w).C) := by omega
        _ ≤ q * (gaussPrefixMobius w).D +
              ((gaussPrefixMobius w).B + (gaussPrefixMobius w).D) :=
          Nat.add_le_add (Nat.mul_le_mul_left q hCD) (ih htail)
        _ = (gaussPrefixMobius w).D +
              (q * (gaussPrefixMobius w).D + (gaussPrefixMobius w).B) := by
          omega

/-- A four-parameter form of the Möbius density, used to keep the analytic
bounds separate from continued-fraction bookkeeping. -/
def mobiusTailDensity (C D E F : ℝ) (y : ℝ) : ℝ :=
  (1 + y) / ((C * y + D) * (E * y + F))

theorem gaussPrefixTailRatio_eq_mobiusTailDensity
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    gaussPrefixTailRatio w y =
      mobiusTailDensity
        (gaussPrefixMobius w).C (gaussPrefixMobius w).D
        ((gaussPrefixMobius w).A + (gaussPrefixMobius w).C)
        ((gaussPrefixMobius w).B + (gaussPrefixMobius w).D) y := by
  rw [gaussPrefixTailRatio_eq_mobius hpos hy]
  unfold mobiusTailDensity
  ring_nf

theorem mobiusTailDensity_pos
    {C D E F y : ℝ} (hC : 0 ≤ C) (hD : 0 < D)
    (hE : 0 ≤ E) (hF : 0 < F) (hy : 0 ≤ y) :
    0 < mobiusTailDensity C D E F y := by
  unfold mobiusTailDensity
  exact div_pos (by linarith)
    (mul_pos (add_pos_of_nonneg_of_pos (mul_nonneg hC hy) hD)
      (add_pos_of_nonneg_of_pos (mul_nonneg hE hy) hF))

/-- Every admissible Möbius density has distortion at most eight on the
closed Gauss state interval. -/
theorem mobiusTailDensity_le_eight_mul
    {C D E F : ℝ} (hC : 0 ≤ C) (hD : 0 < D) (hCD : C ≤ D)
    (hE : 0 ≤ E) (hF : 0 < F) (hEF : E ≤ F)
    {y z : ℝ} (hy : y ∈ Icc (0 : ℝ) 1)
    (hz : z ∈ Icc (0 : ℝ) 1) :
    mobiusTailDensity C D E F y ≤
      8 * mobiusTailDensity C D E F z := by
  let uy := C * y + D
  let vy := E * y + F
  let uz := C * z + D
  let vz := E * z + F
  have huy : 0 < uy := by
    dsimp [uy]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hC hy.1) hD
  have hvy : 0 < vy := by
    dsimp [vy]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hE hy.1) hF
  have huz : 0 < uz := by
    dsimp [uz]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hC hz.1) hD
  have hvz : 0 < vz := by
    dsimp [vz]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hE hz.1) hF
  have huyLower : D ≤ uy := by
    dsimp [uy]
    nlinarith [mul_nonneg hC hy.1]
  have hvyLower : F ≤ vy := by
    dsimp [vy]
    nlinarith [mul_nonneg hE hy.1]
  have huzUpper : uz ≤ 2 * D := by
    dsimp [uz]
    have hCz : C * z ≤ C := mul_le_of_le_one_right hC hz.2
    linarith
  have hvzUpper : vz ≤ 2 * F := by
    dsimp [vz]
    have hEz : E * z ≤ E := mul_le_of_le_one_right hE hz.2
    linarith
  have hdenLower : D * F ≤ uy * vy :=
    mul_le_mul huyLower hvyLower hF.le (le_trans hD.le huyLower)
  have hdenUpper : uz * vz ≤ 4 * (D * F) := by
    calc
      uz * vz ≤ (2 * D) * (2 * F) :=
        mul_le_mul huzUpper hvzUpper hvz.le
          (le_trans huz.le huzUpper)
      _ = 4 * (D * F) := by ring
  unfold mobiusTailDensity
  change (1 + y) / (uy * vy) ≤ 8 * ((1 + z) / (uz * vz))
  rw [div_le_iff₀ (mul_pos huy hvy)]
  rw [show 8 * ((1 + z) / (uz * vz)) * (uy * vy) =
      (8 * (1 + z) * (uy * vy)) / (uz * vz) by ring]
  rw [le_div_iff₀ (mul_pos huz hvz)]
  calc
    (1 + y) * (uz * vz) ≤ 2 * (4 * (D * F)) := by
      exact mul_le_mul (by linarith [hy.2]) hdenUpper
        (mul_nonneg huz.le hvz.le) (by norm_num)
    _ = 8 * (D * F) := by ring
    _ ≤ 8 * ((1 + z) * (uy * vy)) := by
      apply mul_le_mul_of_nonneg_left _ (by norm_num)
      calc
        D * F ≤ uy * vy := hdenLower
        _ ≤ (1 + z) * (uy * vy) := by
          have hp : 0 ≤ uy * vy := mul_nonneg huy.le hvy.le
          have hzp : 0 ≤ z * (uy * vy) := mul_nonneg hz.1 hp
          nlinarith
    _ = 8 * (1 + z) * (uy * vy) := by ring

theorem mobiusTailDensity_le_two_div
    {C D E F : ℝ} (hC : 0 ≤ C) (hD : 0 < D)
    (hE : 0 ≤ E) (hF : 0 < F)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    mobiusTailDensity C D E F y ≤ 2 / (D * F) := by
  let u := C * y + D
  let v := E * y + F
  have hu : 0 < u := by
    dsimp [u]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hC hy.1) hD
  have hv : 0 < v := by
    dsimp [v]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hE hy.1) hF
  have hden : D * F ≤ u * v := by
    apply mul_le_mul
    · dsimp [u]
      nlinarith [mul_nonneg hC hy.1]
    · dsimp [v]
      nlinarith [mul_nonneg hE hy.1]
    · exact hF.le
    · exact le_trans hD.le (by
        dsimp [u]
        nlinarith [mul_nonneg hC hy.1])
  unfold mobiusTailDensity
  change (1 + y) / (u * v) ≤ 2 / (D * F)
  rw [div_le_div_iff₀ (mul_pos hu hv) (mul_pos hD hF)]
  have hDF : 0 ≤ D * F := (mul_pos hD hF).le
  calc
    (1 + y) * (D * F) ≤ 2 * (D * F) := by
      exact mul_le_mul_of_nonneg_right (by linarith [hy.2]) hDF
    _ ≤ 2 * (u * v) := mul_le_mul_of_nonneg_left hden (by norm_num)

theorem one_div_four_mul_le_mobiusTailDensity
    {C D E F : ℝ} (hC : 0 ≤ C) (hD : 0 < D) (hCD : C ≤ D)
    (hE : 0 ≤ E) (hF : 0 < F) (hEF : E ≤ F)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    1 / (4 * (D * F)) ≤ mobiusTailDensity C D E F y := by
  let u := C * y + D
  let v := E * y + F
  have hu : 0 < u := by
    dsimp [u]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hC hy.1) hD
  have hv : 0 < v := by
    dsimp [v]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hE hy.1) hF
  have huUpper : u ≤ 2 * D := by
    dsimp [u]
    have hCy : C * y ≤ C := mul_le_of_le_one_right hC hy.2
    linarith
  have hvUpper : v ≤ 2 * F := by
    dsimp [v]
    have hEy : E * y ≤ E := mul_le_of_le_one_right hE hy.2
    linarith
  have hdenUpper : u * v ≤ 4 * (D * F) := by
    calc
      u * v ≤ (2 * D) * (2 * F) :=
        mul_le_mul huUpper hvUpper hv.le
          (le_trans hu.le huUpper)
      _ = 4 * (D * F) := by ring
  unfold mobiusTailDensity
  change 1 / (4 * (D * F)) ≤ (1 + y) / (u * v)
  rw [div_le_div_iff₀ (by positivity : 0 < 4 * (D * F))
    (mul_pos hu hv)]
  norm_num only [one_mul]
  calc
    u * v ≤ 4 * (D * F) := hdenUpper
    _ ≤ (1 + y) * (4 * (D * F)) := by
      have hp : 0 ≤ 4 * (D * F) := by positivity
      have hyp : 0 ≤ y * (4 * (D * F)) := mul_nonneg hy.1 hp
      nlinarith

/-- Exact derivative of the four-parameter density. -/
theorem hasDerivAt_mobiusTailDensity
    {C D E F y : ℝ}
    (hu : C * y + D ≠ 0) (hv : E * y + F ≠ 0) :
    HasDerivAt (mobiusTailDensity C D E F)
      (((C * y + D) * (E * y + F) -
          (1 + y) * (C * (E * y + F) + (C * y + D) * E)) /
        (((C * y + D) * (E * y + F)) ^ 2)) y := by
  unfold mobiusTailDensity
  have hn := (hasDerivAt_const y (1 : ℝ)).add (hasDerivAt_id y)
  have h₁ := ((hasDerivAt_const y C).mul (hasDerivAt_id y)).add_const D
  have h₂ := ((hasDerivAt_const y E).mul (hasDerivAt_id y)).add_const F
  have hd := h₁.mul h₂
  convert! hn.div hd (mul_ne_zero hu hv) using 1
  all_goals
    simp only [Pi.add_apply, Pi.mul_apply, id_eq, zero_mul, zero_add,
      mul_one]
    ring

/-- A uniform derivative bound.  Its scale is the reciprocal product of
the two constant denominator coefficients. -/
theorem abs_deriv_mobiusTailDensity_le
    {C D E F : ℝ} (hC : 0 ≤ C) (hD : 0 < D) (hCD : C ≤ D)
    (hE : 0 ≤ E) (hF : 0 < F) (hEF : E ≤ F)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    |deriv (mobiusTailDensity C D E F) y| ≤ 12 / (D * F) := by
  let u := C * y + D
  let v := E * y + F
  have hu : 0 < u := by
    dsimp [u]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hC hy.1) hD
  have hv : 0 < v := by
    dsimp [v]
    exact add_pos_of_nonneg_of_pos (mul_nonneg hE hy.1) hF
  have huLower : D ≤ u := by
    dsimp [u]
    nlinarith [mul_nonneg hC hy.1]
  have hvLower : F ≤ v := by
    dsimp [v]
    nlinarith [mul_nonneg hE hy.1]
  have huUpper : u ≤ 2 * D := by
    dsimp [u]
    have hCy : C * y ≤ C := mul_le_of_le_one_right hC hy.2
    linarith
  have hvUpper : v ≤ 2 * F := by
    dsimp [v]
    have hEy : E * y ≤ E := mul_le_of_le_one_right hE hy.2
    linarith
  have hdenLower : D * F ≤ u * v :=
    mul_le_mul huLower hvLower hF.le (le_trans hD.le huLower)
  have hdenUpper : u * v ≤ 4 * (D * F) := by
    calc
      u * v ≤ (2 * D) * (2 * F) :=
        mul_le_mul huUpper hvUpper hv.le (le_trans hu.le huUpper)
      _ = 4 * (D * F) := by ring
  have hderUpper : C * v + u * E ≤ 4 * (D * F) := by
    have hCv : C * v ≤ D * (2 * F) :=
      mul_le_mul hCD hvUpper hv.le hD.le
    have huE : u * E ≤ (2 * D) * F :=
      mul_le_mul huUpper hEF hE (le_trans hu.le huUpper)
    nlinarith
  have hterm :
      (1 + y) * (C * v + u * E) ≤ 8 * (D * F) := by
    have hnonneg : 0 ≤ C * v + u * E :=
      add_nonneg (mul_nonneg hC hv.le) (mul_nonneg hu.le hE)
    calc
      (1 + y) * (C * v + u * E) ≤ 2 * (C * v + u * E) :=
        mul_le_mul_of_nonneg_right (by linarith [hy.2]) hnonneg
      _ ≤ 2 * (4 * (D * F)) :=
        mul_le_mul_of_nonneg_left hderUpper (by norm_num)
      _ = 8 * (D * F) := by ring
  rw [(hasDerivAt_mobiusTailDensity (C := C) (D := D)
    (E := E) (F := F) (y := y) (ne_of_gt hu) (ne_of_gt hv)).deriv]
  change |(u * v - (1 + y) * (C * v + u * E)) / (u * v) ^ 2| ≤ _
  rw [abs_div, abs_pow, abs_of_pos (mul_pos hu hv)]
  have hnum :
      |u * v - (1 + y) * (C * v + u * E)| ≤ 12 * (D * F) := by
    calc
      |u * v - (1 + y) * (C * v + u * E)| ≤
          |u * v| + |(1 + y) * (C * v + u * E)| := abs_sub _ _
      _ = u * v + (1 + y) * (C * v + u * E) := by
        rw [abs_of_nonneg (mul_nonneg hu.le hv.le),
          abs_of_nonneg (mul_nonneg (by linarith [hy.1])
            (add_nonneg (mul_nonneg hC hv.le) (mul_nonneg hu.le hE)))]
      _ ≤ 4 * (D * F) + 8 * (D * F) := add_le_add hdenUpper hterm
      _ = 12 * (D * F) := by ring
  have hDF : 0 < D * F := mul_pos hD hF
  have hdenSq : (D * F) ^ 2 ≤ (u * v) ^ 2 := by nlinarith
  calc
    |u * v - (1 + y) * (C * v + u * E)| / (u * v) ^ 2 ≤
        (12 * (D * F)) / (u * v) ^ 2 :=
      div_le_div_of_nonneg_right hnum (sq_nonneg _)
    _ ≤ (12 * (D * F)) / (D * F) ^ 2 := by
      exact div_le_div_of_nonneg_left (by positivity) (sq_pos_of_pos hDF)
        hdenSq
    _ = 12 / (D * F) := by field_simp [ne_of_gt hDF]

theorem mobiusTailDensity_lipschitz
    {C D E F : ℝ} (hC : 0 ≤ C) (hD : 0 < D) (hCD : C ≤ D)
    (hE : 0 ≤ E) (hF : 0 < F) (hEF : E ≤ F) :
    GaussUnitLipschitzBound (12 / (D * F))
      (mobiusTailDensity C D E F) := by
  have hdiff : ∀ x ∈ Icc (0 : ℝ) 1,
      DifferentiableAt ℝ (mobiusTailDensity C D E F) x := by
    intro x hx
    apply (hasDerivAt_mobiusTailDensity
      (ne_of_gt (add_pos_of_nonneg_of_pos (mul_nonneg hC hx.1) hD))
      (ne_of_gt (add_pos_of_nonneg_of_pos (mul_nonneg hE hx.1) hF))).differentiableAt
  have hbound : ∀ x ∈ Icc (0 : ℝ) 1,
      ‖deriv (mobiusTailDensity C D E F) x‖₊ ≤
        (12 / (D * F)).toNNReal := by
    intro x hx
    apply NNReal.coe_le_coe.mp
    rw [coe_nnnorm, Real.norm_eq_abs,
      Real.coe_toNNReal _ (div_nonneg (by norm_num) (mul_pos hD hF).le)]
    exact abs_deriv_mobiusTailDensity_le hC hD hCD hE hF hEF hx
  have hlip := Convex.lipschitzOnWith_of_nnnorm_deriv_le
    hdiff hbound (convex_Icc (0 : ℝ) 1)
  intro y hy z hz
  have hK : 0 ≤ 12 / (D * F) :=
    div_nonneg (by norm_num) (mul_pos hD hF).le
  have h := hlip.norm_sub_le hy hz
  simpa only [Real.norm_eq_abs, Real.coe_toNNReal _ hK] using! h

theorem gaussPrefixTailRatio_pos
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    0 < gaussPrefixTailRatio w y := by
  rw [gaussPrefixTailRatio_eq_mobiusTailDensity hpos hy]
  apply mobiusTailDensity_pos
  · positivity
  · exact_mod_cast gaussPrefixMobius_D_pos hpos
  · positivity
  · have hD : 0 < (gaussPrefixMobius w).D :=
      gaussPrefixMobius_D_pos hpos
    have hFNat : 0 <
        (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by omega
    exact_mod_cast hFNat
  · exact hy.1

theorem gaussPrefixTailRatio_le_eight_mul
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y z : ℝ} (hy : y ∈ Icc (0 : ℝ) 1)
    (hz : z ∈ Icc (0 : ℝ) 1) :
    gaussPrefixTailRatio w y ≤ 8 * gaussPrefixTailRatio w z := by
  rw [gaussPrefixTailRatio_eq_mobiusTailDensity hpos hy,
    gaussPrefixTailRatio_eq_mobiusTailDensity hpos hz]
  apply mobiusTailDensity_le_eight_mul
  · positivity
  · exact_mod_cast gaussPrefixMobius_D_pos hpos
  · exact_mod_cast gaussPrefixMobius_C_le_D hpos
  · positivity
  · have hD : 0 < (gaussPrefixMobius w).D :=
      gaussPrefixMobius_D_pos hpos
    have hFNat : 0 <
        (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by omega
    exact_mod_cast hFNat
  · exact_mod_cast gaussPrefixMobius_A_add_C_le_B_add_D hpos
  · exact hy
  · exact hz

theorem measurable_gaussInverseWord (w : List ℕ) :
    Measurable (gaussInverseWord w) := by
  induction w with
  | nil => simpa [gaussInverseWord] using! measurable_id
  | cons q w ih =>
      simpa only [gaussInverseWord] using!
        (measurable_gaussInverseBranch q).comp ih

theorem measurable_gaussPrefixTailRatio (w : List ℕ) :
    Measurable (gaussPrefixTailRatio w) := by
  induction w with
  | nil => exact measurable_const
  | cons q w ih =>
      exact ih.mul ((measurable_gaussBranchRatio q).comp
        (measurable_gaussInverseWord w))

theorem gaussPrefixTailRatio_lipschitz_scaled
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    GaussUnitLipschitzBound
      (12 / (((gaussPrefixMobius w).D : ℝ) *
        ((gaussPrefixMobius w).B + (gaussPrefixMobius w).D : ℕ)))
      (gaussPrefixTailRatio w) := by
  let C : ℝ := (gaussPrefixMobius w).C
  let D : ℝ := (gaussPrefixMobius w).D
  let E : ℝ := (gaussPrefixMobius w).A + (gaussPrefixMobius w).C
  let F : ℝ := (gaussPrefixMobius w).B + (gaussPrefixMobius w).D
  have hD : 0 < D := by
    dsimp [D]
    exact_mod_cast gaussPrefixMobius_D_pos hpos
  have hF : 0 < F := by
    have hDNat := gaussPrefixMobius_D_pos hpos
    have hFNat : 0 <
        (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by omega
    dsimp [F]
    exact_mod_cast hFNat
  have hlip := mobiusTailDensity_lipschitz
    (C := C) (D := D) (E := E) (F := F)
    (by positivity) hD (by
      dsimp [C, D]
      exact_mod_cast gaussPrefixMobius_C_le_D hpos)
    (by positivity) hF (by
      dsimp [E, F]
      exact_mod_cast gaussPrefixMobius_A_add_C_le_B_add_D hpos)
  intro y hy z hz
  rw [gaussPrefixTailRatio_eq_mobiusTailDensity hpos hy,
    gaussPrefixTailRatio_eq_mobiusTailDensity hpos hz]
  simpa only [C, D, E, F, Nat.cast_add] using! hlip hy hz

/-! ## Exact inverse-word change of variables -/

theorem measurableSet_gaussInverseWord_image
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {s : Set ℝ} (hsM : MeasurableSet s)
    (hs : s ⊆ Icc (0 : ℝ) 1) :
    MeasurableSet (gaussInverseWord w '' s) := by
  induction w with
  | nil => simpa [gaussInverseWord] using! hsM
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : IsPositiveCFWord w := by
        intro a ha
        exact hpos a (by simp [ha])
      have himageM := ih htail
      have himageSub : gaussInverseWord w '' s ⊆ Icc (0 : ℝ) 1 := by
        rintro _ ⟨y, hy, rfl⟩
        exact gaussInverseWord_mem_Icc htail (hs hy)
      have hbranch := measurableSet_gaussInverseBranch_image hq
        himageM himageSub
      convert! hbranch using 1
      ext x
      constructor
      · rintro ⟨y, hy, rfl⟩
        exact ⟨gaussInverseWord w y, ⟨y, hy, rfl⟩, rfl⟩
      · rintro ⟨_z, ⟨y, hy, rfl⟩, rfl⟩
        exact ⟨y, hy, rfl⟩

/-- Iterated nonnegative change of variables along a complete inverse word.
This is the exact Radon--Nikodym identity from which all prefix/future event
formulae below are derived. -/
theorem gaussInverseWord_lintegral_change
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {s : Set ℝ} (hsM : MeasurableSet s)
    (hs : s ⊆ Icc (0 : ℝ) 1)
    (u : ℝ → ℝ≥0∞) (hu : Measurable u) :
    (∫⁻ x in gaussInverseWord w '' s, u x ∂gaussMeasure) =
      ∫⁻ y in s,
        ENNReal.ofReal (gaussPrefixTailRatio w y) *
          u (gaussInverseWord w y) ∂gaussMeasure := by
  induction w generalizing s u with
  | nil => simp [gaussInverseWord, gaussPrefixTailRatio]
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : IsPositiveCFWord w := by
        intro a ha
        exact hpos a (by simp [ha])
      let t : Set ℝ := gaussInverseWord w '' s
      have htM : MeasurableSet t :=
        measurableSet_gaussInverseWord_image htail hsM hs
      have ht : t ⊆ Icc (0 : ℝ) 1 := by
        rintro _ ⟨y, hy, rfl⟩
        exact gaussInverseWord_mem_Icc htail (hs hy)
      let v : ℝ → ℝ≥0∞ := fun z =>
        ENNReal.ofReal (gaussBranchRatio q z) *
          u (gaussInverseBranch q z)
      have hv : Measurable v :=
        (measurable_ofReal_gaussBranchRatio q).mul
          (hu.comp (measurable_gaussInverseBranch q))
      have himage : gaussInverseWord (q :: w) '' s =
          gaussInverseBranch q '' t := by
        ext x
        constructor
        · rintro ⟨y, hy, rfl⟩
          exact ⟨gaussInverseWord w y, ⟨y, hy, rfl⟩, rfl⟩
        · rintro ⟨_z, ⟨y, hy, rfl⟩, rfl⟩
          exact ⟨y, hy, rfl⟩
      rw [himage, gaussBranch_lintegral_change hq htM ht u hu]
      change (∫⁻ z in t, v z ∂gaussMeasure) = _
      rw [ih htail hsM hs v hv]
      apply lintegral_congr_ae
      filter_upwards [ae_restrict_mem hsM] with y hy
      have hycc := hs hy
      have hr0 := (gaussPrefixTailRatio_pos htail hycc).le
      have hb0 := (gaussBranchRatio_pos hq
        (gaussInverseWord_mem_Icc htail hycc)).le
      simp only [v, gaussPrefixTailRatio_cons, gaussInverseWord]
      rw [ENNReal.ofReal_mul hr0]
      ac_rfl

/-! ## Endpoint comparison with the actual half-open cylinder -/

theorem gaussInverseWord_mem_gaussHalfOpenPrefixCylinder_of_Ioo
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y : ℝ} (hy : y ∈ Ioo (0 : ℝ) 1) :
    gaussInverseWord w y ∈ gaussHalfOpenPrefixCylinder w := by
  induction w with
  | nil => exact ⟨hy.1.le, hy.2⟩
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : IsPositiveCFWord w := by
        intro a ha
        exact hpos a (by simp [ha])
      have htailIoo := gaussInverseWord_mem_Ioo htail hy
      constructor
      · exact gaussInverseBranch_mem_firstDigitCylinder
          ⟨htailIoo.1.le, htailIoo.2⟩ q hq
      · change gaussMap
          (gaussInverseBranch q (gaussInverseWord w y)) ∈
            gaussHalfOpenPrefixCylinder w
        rw [gaussMap_gaussInverseBranch
          ⟨htailIoo.1.le, htailIoo.2⟩ q hq]
        exact ih htail

theorem gaussHalfOpenPrefixCylinder_subset_gaussInverseWord_image_Ico
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    gaussHalfOpenPrefixCylinder w ⊆
      gaussInverseWord w '' Ico (0 : ℝ) 1 := by
  intro x hx
  let y := gaussOrbit w.length x
  have hy : y ∈ Ico (0 : ℝ) 1 := by
    cases hlen : w.length with
    | zero =>
        have hw : w = [] := by simpa using! hlen
        subst w
        simpa [y, gaussOrbit, gaussHalfOpenPrefixCylinder] using! hx
    | succ n =>
        dsimp [y]
        rw [hlen]
        exact gaussOrbit_succ_mem_Ico n x
  exact ⟨y, hy, (eq_gaussInverseWord_gaussOrbit_of_mem_prefix hpos hx).symm⟩

/-- The inverse-word parametrization and the recursive half-open cylinder
differ, at worst, at the single terminating endpoint corresponding to tail
zero. -/
theorem gaussInverseWord_image_Ico_diff_prefix_subset_singleton
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    gaussInverseWord w '' Ico (0 : ℝ) 1 \
        gaussHalfOpenPrefixCylinder w ⊆
      {gaussInverseWord w 0} := by
  rintro x ⟨⟨y, hy, rfl⟩, hnot⟩
  have hy0 : y = 0 := by
    by_contra hne
    have hyIoo : y ∈ Ioo (0 : ℝ) 1 :=
      ⟨lt_of_le_of_ne hy.1 (Ne.symm hne), hy.2⟩
    exact hnot (gaussInverseWord_mem_gaussHalfOpenPrefixCylinder_of_Ioo
      hpos hyIoo)
  simp only [mem_singleton_iff, hy0]

theorem gaussMeasure_gaussInverseWord_image_Ico_eq_prefixCylinder
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    gaussMeasure (gaussInverseWord w '' Ico (0 : ℝ) 1) =
      gaussMeasure (gaussHalfOpenPrefixCylinder w) := by
  have hnull : gaussMeasure ({gaussInverseWord w 0} : Set ℝ) = 0 :=
    gaussMeasure_singleton _
  apply measure_congr
  filter_upwards [measure_eq_zero_iff_ae_notMem.mp hnull] with x hx
  apply propext
  constructor
  · intro himage
    by_contra hnot
    exact hx (gaussInverseWord_image_Ico_diff_prefix_subset_singleton
      hpos ⟨himage, hnot⟩)
  · exact fun hpref =>
      gaussHalfOpenPrefixCylinder_subset_gaussInverseWord_image_Ico hpos hpref

theorem gaussMeasure_prefixCylinder_eq_tailRatio_lintegral
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    gaussMeasure (gaussHalfOpenPrefixCylinder w) =
      ∫⁻ y in Ico (0 : ℝ) 1,
        ENNReal.ofReal (gaussPrefixTailRatio w y) ∂gaussMeasure := by
  rw [← gaussMeasure_gaussInverseWord_image_Ico_eq_prefixCylinder hpos]
  simpa using!
    gaussInverseWord_lintegral_change hpos measurableSet_Ico
      (fun _ hy => ⟨hy.1, hy.2.le⟩) (fun _ => 1) measurable_const

/-! ## Normalization of one word density -/

def gaussPrefixWordProbability (w : List ℕ) : ℝ :=
  gaussMeasure.real (gaussHalfOpenPrefixCylinder w)

theorem gaussPrefixWordProbability_nonneg (w : List ℕ) :
    0 ≤ gaussPrefixWordProbability w := measureReal_nonneg

theorem one_div_prefixScale_le_gaussPrefixWordProbability
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    1 / (4 * (((gaussPrefixMobius w).D : ℝ) *
      ((gaussPrefixMobius w).B + (gaussPrefixMobius w).D : ℕ))) ≤
      gaussPrefixWordProbability w := by
  let C : ℝ := (gaussPrefixMobius w).C
  let D : ℝ := (gaussPrefixMobius w).D
  let E : ℝ := (gaussPrefixMobius w).A + (gaussPrefixMobius w).C
  let F : ℝ := (gaussPrefixMobius w).B + (gaussPrefixMobius w).D
  let c : ℝ := 1 / (4 * (D * F))
  have hD : 0 < D := by
    dsimp [D]
    exact_mod_cast gaussPrefixMobius_D_pos hpos
  have hF : 0 < F := by
    have hDNat := gaussPrefixMobius_D_pos hpos
    have hFNat : 0 <
        (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by omega
    dsimp [F]
    exact_mod_cast hFNat
  have hc : 0 < c := by dsimp [c]; positivity
  have hENN : ENNReal.ofReal c ≤
      gaussMeasure (gaussHalfOpenPrefixCylinder w) := by
    rw [gaussMeasure_prefixCylinder_eq_tailRatio_lintegral hpos]
    calc
      ENNReal.ofReal c =
          ∫⁻ _z in Ico (0 : ℝ) 1, ENNReal.ofReal c ∂gaussMeasure := by
        simp [gaussMeasure_Ico_unit]
      _ ≤ ∫⁻ z in Ico (0 : ℝ) 1,
          ENNReal.ofReal (gaussPrefixTailRatio w z) ∂gaussMeasure := by
        apply lintegral_mono_ae
        filter_upwards [ae_restrict_mem measurableSet_Ico] with z hz
        apply ENNReal.ofReal_le_ofReal
        rw [gaussPrefixTailRatio_eq_mobiusTailDensity hpos
          ⟨hz.1, hz.2.le⟩]
        exact one_div_four_mul_le_mobiusTailDensity
          (C := C) (D := D) (E := E) (F := F)
          (by positivity) hD (by
            dsimp [C, D]
            exact_mod_cast gaussPrefixMobius_C_le_D hpos)
          (by positivity) hF (by
            dsimp [E, F]
            exact_mod_cast gaussPrefixMobius_A_add_C_le_B_add_D hpos)
          ⟨hz.1, hz.2.le⟩
  have hreal := ENNReal.toReal_mono (measure_ne_top _ _) hENN
  rw [ENNReal.toReal_ofReal hc.le] at hreal
  change c ≤ gaussPrefixWordProbability w at hreal
  simpa only [c, C, D, E, F, Nat.cast_add] using! hreal

theorem gaussPrefixWordProbability_pos
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    0 < gaussPrefixWordProbability w := by
  have hD : (0 : ℝ) < (gaussPrefixMobius w).D := by
    exact_mod_cast gaussPrefixMobius_D_pos hpos
  have hFNat : 0 <
      (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by
    have hDNat := gaussPrefixMobius_D_pos hpos
    omega
  have hF : (0 : ℝ) <
      ((gaussPrefixMobius w).B + (gaussPrefixMobius w).D : ℕ) := by
    exact_mod_cast hFNat
  have hlower := one_div_prefixScale_le_gaussPrefixWordProbability hpos
  exact lt_of_lt_of_le (by positivity) hlower

theorem gaussPrefixTailRatio_le_eight_mul_probability
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    gaussPrefixTailRatio w y ≤
      8 * gaussPrefixWordProbability w := by
  have hENN : ENNReal.ofReal (gaussPrefixTailRatio w y) ≤
      8 * gaussMeasure (gaussHalfOpenPrefixCylinder w) := by
    rw [gaussMeasure_prefixCylinder_eq_tailRatio_lintegral hpos]
    calc
      ENNReal.ofReal (gaussPrefixTailRatio w y) =
          ∫⁻ _z in Ico (0 : ℝ) 1,
            ENNReal.ofReal (gaussPrefixTailRatio w y) ∂gaussMeasure := by
        simp [gaussMeasure_Ico_unit]
      _ ≤ ∫⁻ z in Ico (0 : ℝ) 1,
          8 * ENNReal.ofReal (gaussPrefixTailRatio w z)
            ∂gaussMeasure := by
        apply lintegral_mono_ae
        filter_upwards [ae_restrict_mem measurableSet_Ico] with z hz
        rw [show (8 : ℝ≥0∞) = ENNReal.ofReal (8 : ℝ) by norm_num,
          ← ENNReal.ofReal_mul (by norm_num : (0 : ℝ) ≤ 8)]
        exact ENNReal.ofReal_le_ofReal
          (gaussPrefixTailRatio_le_eight_mul hpos hy ⟨hz.1, hz.2.le⟩)
      _ = 8 * ∫⁻ z in Ico (0 : ℝ) 1,
          ENNReal.ofReal (gaussPrefixTailRatio w z) ∂gaussMeasure := by
        rw [lintegral_const_mul]
        exact (measurable_gaussPrefixTailRatio w).ennreal_ofReal
  have hreal := ENNReal.toReal_mono (by finiteness) hENN
  simpa only [ENNReal.toReal_ofReal
      (gaussPrefixTailRatio_pos hpos hy).le,
    ENNReal.toReal_mul, ENNReal.toReal_ofNat, measureReal_def,
    gaussPrefixWordProbability] using! hreal

def gaussPrefixWordNormalizedDensity (w : List ℕ) (y : ℝ) : ℝ :=
  gaussPrefixTailRatio w y / gaussPrefixWordProbability w

theorem measurable_gaussPrefixWordNormalizedDensity (w : List ℕ) :
    Measurable (gaussPrefixWordNormalizedDensity w) :=
  (measurable_gaussPrefixTailRatio w).div_const _

theorem gaussPrefixWordNormalizedDensity_nonnegative
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    GaussUnitNonnegative (gaussPrefixWordNormalizedDensity w) := by
  intro y hy
  exact div_nonneg (gaussPrefixTailRatio_pos hpos hy).le
    (gaussPrefixWordProbability_pos hpos).le

theorem gaussPrefixWordNormalizedDensity_upperBound_eight
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    GaussUnitUpperBound 8 (gaussPrefixWordNormalizedDensity w) := by
  intro y hy
  unfold gaussPrefixWordNormalizedDensity
  rw [div_le_iff₀ (gaussPrefixWordProbability_pos hpos)]
  simpa only [mul_comm] using!
    gaussPrefixTailRatio_le_eight_mul_probability hpos hy

theorem gaussPrefixWordNormalizedDensity_lipschitz
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    GaussUnitLipschitzBound 48
      (gaussPrefixWordNormalizedDensity w) := by
  let D : ℝ := (gaussPrefixMobius w).D
  let F : ℝ :=
    ((gaussPrefixMobius w).B + (gaussPrefixMobius w).D : ℕ)
  let p : ℝ := gaussPrefixWordProbability w
  have hp : 0 < p := gaussPrefixWordProbability_pos hpos
  have hD : 0 < D := by
    dsimp [D]
    exact_mod_cast gaussPrefixMobius_D_pos hpos
  have hF : 0 < F := by
    have hDNat := gaussPrefixMobius_D_pos hpos
    have hFNat : 0 <
        (gaussPrefixMobius w).B + (gaussPrefixMobius w).D := by omega
    dsimp [F]
    exact_mod_cast hFNat
  have hscale : 12 / (D * F) ≤ 48 * p := by
    have hlower := one_div_prefixScale_le_gaussPrefixWordProbability hpos
    have hlower' : 1 / (4 * (D * F)) ≤ p := by
      simpa only [D, F, p] using! hlower
    calc
      12 / (D * F) = 48 * (1 / (4 * (D * F))) := by
        field_simp [ne_of_gt (mul_pos hD hF)]
        norm_num
      _ ≤ 48 * p := mul_le_mul_of_nonneg_left hlower' (by norm_num)
  have hlip : GaussUnitLipschitzBound (12 / (D * F))
      (gaussPrefixTailRatio w) := by
    simpa only [D, F] using! gaussPrefixTailRatio_lipschitz_scaled hpos
  intro y hy z hz
  unfold gaussPrefixWordNormalizedDensity
  rw [div_sub_div_same, abs_div, abs_of_pos hp]
  calc
    |gaussPrefixTailRatio w y - gaussPrefixTailRatio w z| / p ≤
        (12 / (D * F) * |y - z|) / p := by
      exact div_le_div_of_nonneg_right (hlip hy hz) hp.le
    _ ≤ (48 * p * |y - z|) / p := by
      exact div_le_div_of_nonneg_right
        (mul_le_mul_of_nonneg_right hscale (abs_nonneg _)) hp.le
    _ = 48 * |y - z| := by field_simp [ne_of_gt hp]

theorem lintegral_gaussPrefixWordNormalizedDensity
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    (∫⁻ y, ENNReal.ofReal (gaussPrefixWordNormalizedDensity w y)
      ∂gaussMeasure) = 1 := by
  have hp : 0 < gaussPrefixWordProbability w :=
    gaussPrefixWordProbability_pos hpos
  have hAE : (Set.univ : Set ℝ) =ᵐ[gaussMeasure] Ico (0 : ℝ) 1 := by
    filter_upwards [gaussMeasure_Ico_ae] with y hy
    apply propext
    constructor
    · intro _h
      exact hy
    · intro _h
      exact mem_univ y
  have hrestrict : gaussMeasure =
      gaussMeasure.restrict (Ico (0 : ℝ) 1) := by
    calc
      gaussMeasure = gaussMeasure.restrict (Set.univ : Set ℝ) :=
        (Measure.restrict_univ (μ := gaussMeasure)).symm
      _ = gaussMeasure.restrict (Ico (0 : ℝ) 1) :=
        Measure.restrict_congr_set hAE
  unfold gaussPrefixWordNormalizedDensity
  simp_rw [ENNReal.ofReal_div_of_pos hp, div_eq_mul_inv]
  rw [lintegral_mul_const]
  · rw [hrestrict]
    rw [← gaussMeasure_prefixCylinder_eq_tailRatio_lintegral hpos]
    rw [show gaussMeasure (gaussHalfOpenPrefixCylinder w) =
        ENNReal.ofReal (gaussPrefixWordProbability w) by
      exact (ENNReal.ofReal_toReal (measure_ne_top _ _)).symm]
    exact ENNReal.mul_inv_cancel
      (by
        rw [ENNReal.ofReal_ne_zero_iff]
        exact hp)
      ENNReal.ofReal_ne_top
  · exact (measurable_gaussPrefixTailRatio w).ennreal_ofReal

/-! ## Exact prefix/future event formula -/

theorem gaussOrbit_gaussInverseWord_of_Ioo
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {y : ℝ} (hy : y ∈ Ioo (0 : ℝ) 1) :
    gaussOrbit w.length (gaussInverseWord w y) = y := by
  induction w with
  | nil => simp [gaussOrbit, gaussInverseWord]
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : IsPositiveCFWord w := by
        intro a ha
        exact hpos a (by simp [ha])
      have htailIoo := gaussInverseWord_mem_Ioo htail hy
      simp only [List.length_cons, gaussInverseWord]
      rw [show w.length + 1 = w.length + 1 by rfl,
        gaussOrbit_succ_apply_right,
        gaussMap_gaussInverseBranch
          ⟨htailIoo.1.le, htailIoo.2⟩ q hq]
      exact ih htail

theorem gaussMeasure_prefixCylinder_inter_orbit_preimage_eq_image
    {w : List ℕ} (hpos : IsPositiveCFWord w) {B : Set ℝ} :
    gaussMeasure (gaussHalfOpenPrefixCylinder w ∩
        (gaussOrbit w.length) ⁻¹' B) =
      gaussMeasure (gaussInverseWord w '' (B ∩ Ico (0 : ℝ) 1)) := by
  have hnull : gaussMeasure ({gaussInverseWord w 0} : Set ℝ) = 0 :=
    gaussMeasure_singleton _
  apply measure_congr
  filter_upwards [measure_eq_zero_iff_ae_notMem.mp hnull] with x hx
  apply propext
  constructor
  · rintro ⟨hpref, hfuture⟩
    let y := gaussOrbit w.length x
    have hy : y ∈ Ico (0 : ℝ) 1 := by
      cases hlen : w.length with
      | zero =>
          have hw : w = [] := by simpa using! hlen
          subst w
          simpa [y, gaussOrbit, gaussHalfOpenPrefixCylinder] using! hpref
      | succ n =>
          dsimp [y]
          rw [hlen]
          exact gaussOrbit_succ_mem_Ico n x
    exact ⟨y, ⟨hfuture, hy⟩,
      (eq_gaussInverseWord_gaussOrbit_of_mem_prefix hpos hpref).symm⟩
  · rintro ⟨y, ⟨hyB, hyIco⟩, rfl⟩
    have hy0 : y ≠ 0 := by
      intro hzero
      subst y
      exact hx (mem_singleton _)
    have hyIoo : y ∈ Ioo (0 : ℝ) 1 :=
      ⟨lt_of_le_of_ne hyIco.1 (Ne.symm hy0), hyIco.2⟩
    exact ⟨gaussInverseWord_mem_gaussHalfOpenPrefixCylinder_of_Ioo
        hpos hyIoo,
      by simpa [gaussOrbit_gaussInverseWord_of_Ioo hpos hyIoo] using! hyB⟩

theorem gaussMeasure_prefixCylinder_inter_orbit_preimage
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {B : Set ℝ} (hBM : MeasurableSet B) :
    gaussMeasure (gaussHalfOpenPrefixCylinder w ∩
        (gaussOrbit w.length) ⁻¹' B) =
      ∫⁻ y in B,
        ENNReal.ofReal (gaussPrefixTailRatio w y) ∂gaussMeasure := by
  rw [gaussMeasure_prefixCylinder_inter_orbit_preimage_eq_image hpos]
  let tail : Set ℝ := B ∩ Ico (0 : ℝ) 1
  have hchange := gaussInverseWord_lintegral_change hpos
    (hBM.inter measurableSet_Ico)
    (fun _ hy => ⟨hy.2.1, hy.2.2.le⟩) (fun _ => 1) measurable_const
  have hBAE : B =ᵐ[gaussMeasure] tail := by
    filter_upwards [gaussMeasure_Ico_ae] with y hy
    apply propext
    constructor
    · intro hyB
      exact ⟨hyB, hy⟩
    · intro hyInter
      exact hyInter.1
  calc
    gaussMeasure (gaussInverseWord w '' tail) =
        ∫⁻ y in tail,
          ENNReal.ofReal (gaussPrefixTailRatio w y) ∂gaussMeasure := by
      calc
        gaussMeasure (gaussInverseWord w '' tail) =
            ∫⁻ _x in gaussInverseWord w '' tail, (1 : ℝ≥0∞)
              ∂gaussMeasure := by simp
        _ = ∫⁻ y in tail,
            ENNReal.ofReal (gaussPrefixTailRatio w y) * 1
              ∂gaussMeasure := by
          simpa only [tail] using! hchange
        _ = ∫⁻ y in tail,
            ENNReal.ofReal (gaussPrefixTailRatio w y)
              ∂gaussMeasure := by simp
    _ = ∫⁻ y in B,
          ENNReal.ofReal (gaussPrefixTailRatio w y) ∂gaussMeasure := by
      rw [Measure.restrict_congr_set hBAE.symm]

/-- After a gap of `m` Gauss steps beyond the prefix, the exact conditional
density is the `m`th transfer iterate of the word density. -/
theorem gaussMeasure_prefixCylinder_inter_later_preimage
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {B : Set ℝ} (hBM : MeasurableSet B) (m : ℕ) :
    gaussMeasure (gaussHalfOpenPrefixCylinder w ∩
        (gaussOrbit (w.length + m)) ⁻¹' B) =
      ∫⁻ y in B, (gaussTransferENN^[m])
        (fun z => ENNReal.ofReal (gaussPrefixTailRatio w z)) y
        ∂gaussMeasure := by
  have hfutureM : MeasurableSet ((gaussOrbit m) ⁻¹' B) :=
    hBM.preimage (measurable_gaussOrbit m)
  have hset : (gaussOrbit (w.length + m)) ⁻¹' B =
      (gaussOrbit w.length) ⁻¹' ((gaussOrbit m) ⁻¹' B) := by
    ext x
    change (gaussOrbit (w.length + m) x ∈ B) ↔
      (gaussOrbit m (gaussOrbit w.length x) ∈ B)
    rw [gaussOrbit_add_apply_right]
  rw [hset, gaussMeasure_prefixCylinder_inter_orbit_preimage hpos hfutureM]
  exact (setLIntegral_gaussTransferENN_iterate
    (measurable_gaussPrefixTailRatio w).ennreal_ofReal m hBM).symm

/-! ## Loss of memory after the prefix -/

theorem lintegral_gaussPrefixWordNormalizedDensity_iterate
    {w : List ℕ} (hpos : IsPositiveCFWord w) (m : ℕ) :
    (∫⁻ y, ENNReal.ofReal
        ((gaussTransfer^[m]) (gaussPrefixWordNormalizedDensity w) y)
      ∂gaussMeasure) = 1 := by
  let f := gaussPrefixWordNormalizedDensity w
  have hf0 := gaussPrefixWordNormalizedDensity_nonnegative hpos
  have hf8 := gaussPrefixWordNormalizedDensity_upperBound_eight hpos
  have hpoint : ∀ᵐ y ∂gaussMeasure,
      ENNReal.ofReal ((gaussTransfer^[m]) f y) =
        (gaussTransferENN^[m]) (fun x => ENNReal.ofReal (f x)) y := by
    filter_upwards [gaussMeasure_unit_ae] with y hy
    exact ofReal_gaussTransfer_iterate_eq_gaussTransferENN_iterate
      (A := 8) hf0 hf8 m ⟨hy.1.le, hy.2⟩
  calc
    (∫⁻ y, ENNReal.ofReal ((gaussTransfer^[m]) f y)
        ∂gaussMeasure) =
      ∫⁻ y, (gaussTransferENN^[m])
        (fun x => ENNReal.ofReal (f x)) y ∂gaussMeasure :=
      lintegral_congr_ae hpoint
    _ = ∫⁻ y, ENNReal.ofReal (f y) ∂gaussMeasure :=
      lintegral_gaussTransferENN_iterate
        (measurable_gaussPrefixWordNormalizedDensity w).ennreal_ofReal m
    _ = 1 := lintegral_gaussPrefixWordNormalizedDensity hpos

theorem abs_gaussPrefixWordNormalizedDensity_iterate_sub_one_le
    {w : List ℕ} (hpos : IsPositiveCFWord w) (m : ℕ)
    {y : ℝ} (hy : y ∈ Icc (0 : ℝ) 1) :
    |(gaussTransfer^[m]) (gaussPrefixWordNormalizedDensity w) y - 1| ≤
      48 * (527 / 540 : ℝ) ^ m := by
  have hf0 := gaussPrefixWordNormalizedDensity_nonnegative hpos
  have hf8 := gaussPrefixWordNormalizedDensity_upperBound_eight hpos
  have hlip := gaussTransfer_iterate_lipschitz
    (A := 8) (K := 48) (by norm_num) hf0 hf8
      (gaussPrefixWordNormalizedDensity_lipschitz hpos) m
  have hlip' : GaussUnitLipschitzBound
      (48 * (527 / 540 : ℝ) ^ m)
      ((gaussTransfer^[m]) (gaussPrefixWordNormalizedDensity w)) := by
    convert! hlip using 1
    ring
  exact abs_sub_one_le_of_gaussMean_one_of_unit_lipschitz
    (by positivity) hlip'
    (lintegral_gaussPrefixWordNormalizedDensity_iterate hpos m) hy

theorem ofReal_gaussPrefixTailRatio_eq_probability_mul_normalized_on_unit
    {w : List ℕ} (hpos : IsPositiveCFWord w) :
    GaussENNUnitEq
      (fun x => ENNReal.ofReal (gaussPrefixTailRatio w x))
      (fun x => ENNReal.ofReal (gaussPrefixWordProbability w) *
        ENNReal.ofReal (gaussPrefixWordNormalizedDensity w x)) := by
  intro x hx
  change ENNReal.ofReal (gaussPrefixTailRatio w x) =
    ENNReal.ofReal (gaussPrefixWordProbability w) *
      ENNReal.ofReal (gaussPrefixWordNormalizedDensity w x)
  rw [← ENNReal.ofReal_mul (gaussPrefixWordProbability_pos hpos).le]
  congr 1
  unfold gaussPrefixWordNormalizedDensity
  field_simp [ne_of_gt (gaussPrefixWordProbability_pos hpos)]

theorem gaussMeasure_prefixCylinder_inter_later_preimage_normalized
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {B : Set ℝ} (hBM : MeasurableSet B) (m : ℕ) :
    gaussMeasure (gaussHalfOpenPrefixCylinder w ∩
        (gaussOrbit (w.length + m)) ⁻¹' B) =
      ENNReal.ofReal (gaussPrefixWordProbability w) *
        ∫⁻ y in B, ENNReal.ofReal
          ((gaussTransfer^[m])
            (gaussPrefixWordNormalizedDensity w) y) ∂gaussMeasure := by
  let p := gaussPrefixWordProbability w
  let g := gaussPrefixWordNormalizedDensity w
  let c : ℝ≥0∞ := ENNReal.ofReal p
  let h : ℝ → ℝ≥0∞ := fun x =>
    ENNReal.ofReal (gaussPrefixTailRatio w x)
  let gE : ℝ → ℝ≥0∞ := fun x => ENNReal.ofReal (g x)
  have hp : 0 < p := gaussPrefixWordProbability_pos hpos
  have hunit : GaussENNUnitEq h (fun x => c * gE x) := by
    simpa only [h, c, gE, g, p] using!
      ofReal_gaussPrefixTailRatio_eq_probability_mul_normalized_on_unit hpos
  have hitUnit := gaussTransferENN_iterate_unit_congr hunit m
  have hrealUnit : ∀ ⦃y⦄, y ∈ Icc (0 : ℝ) 1 →
      (gaussTransferENN^[m]) gE y =
        ENNReal.ofReal ((gaussTransfer^[m]) g y) := by
    intro y hy
    exact (ofReal_gaussTransfer_iterate_eq_gaussTransferENN_iterate
      (A := 8)
      (gaussPrefixWordNormalizedDensity_nonnegative hpos)
      (gaussPrefixWordNormalizedDensity_upperBound_eight hpos)
      m hy).symm
  rw [gaussMeasure_prefixCylinder_inter_later_preimage hpos hBM m]
  change (∫⁻ y in B, (gaussTransferENN^[m]) h y ∂gaussMeasure) = _
  calc
    (∫⁻ y in B, (gaussTransferENN^[m]) h y ∂gaussMeasure) =
      ∫⁻ y in B, c * (gaussTransferENN^[m]) gE y
        ∂gaussMeasure := by
      apply lintegral_congr_ae
      filter_upwards [ae_restrict_of_ae gaussMeasure_unit_ae] with y hy
      calc
        (gaussTransferENN^[m]) h y =
            (gaussTransferENN^[m]) (fun x => c * gE x) y :=
          hitUnit ⟨hy.1.le, hy.2⟩
        _ = c * (gaussTransferENN^[m]) gE y :=
          gaussTransferENN_iterate_const_mul c gE m y
    _ = c * ∫⁻ y in B, (gaussTransferENN^[m]) gE y
          ∂gaussMeasure := by
      rw [lintegral_const_mul]
      exact measurable_gaussTransferENN_iterate
        (measurable_gaussPrefixWordNormalizedDensity w).ennreal_ofReal m
    _ = c * ∫⁻ y in B,
        ENNReal.ofReal ((gaussTransfer^[m]) g y) ∂gaussMeasure := by
      congr 1
      apply lintegral_congr_ae
      filter_upwards [ae_restrict_of_ae gaussMeasure_unit_ae] with y hy
      exact hrealUnit ⟨hy.1.le, hy.2⟩

theorem gaussMeasureReal_prefixCylinder_inter_later_preimage_eq
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {B : Set ℝ} (hBM : MeasurableSet B) (m : ℕ) :
    gaussMeasure.real (gaussHalfOpenPrefixCylinder w ∩
        (gaussOrbit (w.length + m)) ⁻¹' B) =
      gaussPrefixWordProbability w *
        (∫⁻ y in B, ENNReal.ofReal
          ((gaussTransfer^[m])
            (gaussPrefixWordNormalizedDensity w) y)
          ∂gaussMeasure).toReal := by
  have h := congrArg ENNReal.toReal
    (gaussMeasure_prefixCylinder_inter_later_preimage_normalized
      hpos hBM m)
  simpa only [measureReal_def, ENNReal.toReal_mul,
    ENNReal.toReal_ofReal (gaussPrefixWordProbability_pos hpos).le] using! h

/-- Relative event mixing for one complete positive prefix and an arbitrary
measurable future event, with a constant independent of the prefix length. -/
theorem gaussMeasureReal_prefixCylinder_inter_later_preimage_error_le
    {w : List ℕ} (hpos : IsPositiveCFWord w)
    {B : Set ℝ} (hBM : MeasurableSet B) (m : ℕ) :
    |gaussMeasure.real (gaussHalfOpenPrefixCylinder w ∩
        (gaussOrbit (w.length + m)) ⁻¹' B) -
      gaussMeasure.real (gaussHalfOpenPrefixCylinder w) *
        gaussMeasure.real B| ≤
      (48 * (527 / 540 : ℝ) ^ m) *
        gaussMeasure.real (gaussHalfOpenPrefixCylinder w) *
          gaussMeasure.real B := by
  let g := gaussPrefixWordNormalizedDensity w
  let I : ℝ := (∫⁻ y in B, ENNReal.ofReal
    ((gaussTransfer^[m]) g y) ∂gaussMeasure).toReal
  let p := gaussPrefixWordProbability w
  have hp : 0 < p := gaussPrefixWordProbability_pos hpos
  have hrepr := gaussMeasureReal_prefixCylinder_inter_later_preimage_eq
    hpos hBM m
  have hdev : |I - gaussMeasure.real B| ≤
      (48 * (527 / 540 : ℝ) ^ m) * gaussMeasure.real B := by
    apply abs_setLIntegral_toReal_sub_measureReal_le (by positivity)
      (gaussTransfer_iterate_unit_bounds (A := 8)
        (gaussPrefixWordNormalizedDensity_nonnegative hpos)
        (gaussPrefixWordNormalizedDensity_upperBound_eight hpos) m).1
    intro y hy
    exact abs_gaussPrefixWordNormalizedDensity_iterate_sub_one_le
      hpos m hy
  rw [hrepr]
  change |p * I - p * gaussMeasure.real B| ≤
    (48 * (527 / 540 : ℝ) ^ m) * p * gaussMeasure.real B
  rw [← mul_sub, abs_mul, abs_of_pos hp]
  calc
    p * |I - gaussMeasure.real B| ≤
        p * ((48 * (527 / 540 : ℝ) ^ m) *
          gaussMeasure.real B) :=
      mul_le_mul_of_nonneg_left hdev hp.le
    _ = (48 * (527 / 540 : ℝ) ^ m) * p *
        gaussMeasure.real B := by ring

/-! ## Finite and countable unions of prefix atoms -/

def finiteGaussPrefixEvent (b : ℕ)
    (words : Finset (PositiveDigitWord b)) : Set ℝ :=
  ⋃ w ∈ words, positivePrefixCylinder b w

theorem measurableSet_finiteGaussPrefixEvent
    (b : ℕ) (words : Finset (PositiveDigitWord b)) :
    MeasurableSet (finiteGaussPrefixEvent b words) := by
  unfold finiteGaussPrefixEvent
  exact MeasurableSet.iUnion fun w => MeasurableSet.iUnion fun _ =>
    measurableSet_positivePrefixCylinder b w

theorem pairwiseDisjoint_positivePrefixCylinder_on_finset
    (b : ℕ) (words : Finset (PositiveDigitWord b)) :
    (↑words : Set (PositiveDigitWord b)).PairwiseDisjoint
      (positivePrefixCylinder b) := by
  intro w _hw v _hv hwv
  exact pairwise_disjoint_positivePrefixCylinder b hwv

theorem pairwiseDisjoint_positivePrefixCylinder_inter_future_on_finset
    (b : ℕ) (words : Finset (PositiveDigitWord b)) (F : Set ℝ) :
    (↑words : Set (PositiveDigitWord b)).PairwiseDisjoint
      (fun w => positivePrefixCylinder b w ∩ F) := by
  intro w _hw v _hv hwv
  exact (pairwise_disjoint_positivePrefixCylinder b hwv).mono
    inter_subset_left inter_subset_left

theorem gaussMeasure_finiteGaussPrefixEvent
    (b : ℕ) (words : Finset (PositiveDigitWord b)) :
    gaussMeasure (finiteGaussPrefixEvent b words) =
      ∑ w ∈ words, gaussMeasure (positivePrefixCylinder b w) := by
  unfold finiteGaussPrefixEvent
  exact measure_biUnion_finset
    (pairwiseDisjoint_positivePrefixCylinder_on_finset b words)
    (fun w _ => measurableSet_positivePrefixCylinder b w)

theorem gaussMeasure_finiteGaussPrefixEvent_inter
    (b : ℕ) (words : Finset (PositiveDigitWord b))
    {F : Set ℝ} (hFM : MeasurableSet F) :
    gaussMeasure (finiteGaussPrefixEvent b words ∩ F) =
      ∑ w ∈ words,
        gaussMeasure (positivePrefixCylinder b w ∩ F) := by
  have hset : finiteGaussPrefixEvent b words ∩ F =
      ⋃ w ∈ words, (positivePrefixCylinder b w ∩ F) := by
    unfold finiteGaussPrefixEvent
    rw [iUnion_inter]
    congr 1
    funext w
    rw [iUnion_inter]
  rw [hset]
  exact measure_biUnion_finset
    (pairwiseDisjoint_positivePrefixCylinder_inter_future_on_finset
      b words F)
    (fun w _ => (measurableSet_positivePrefixCylinder b w).inter hFM)

/-- Relative mixing for an arbitrary finite union of length-`b` prefix
cylinders.  The constant remains independent of both `b` and the union. -/
theorem gaussMeasureReal_finiteGaussPrefixEvent_inter_later_error_le
    (b : ℕ) (words : Finset (PositiveDigitWord b))
    {B : Set ℝ} (hBM : MeasurableSet B) (m : ℕ) :
    |gaussMeasure.real (finiteGaussPrefixEvent b words ∩
        (gaussOrbit (b + m)) ⁻¹' B) -
      gaussMeasure.real (finiteGaussPrefixEvent b words) *
        gaussMeasure.real B| ≤
      (48 * (527 / 540 : ℝ) ^ m) *
        gaussMeasure.real (finiteGaussPrefixEvent b words) *
          gaussMeasure.real B := by
  let ε : ℝ := 48 * (527 / 540 : ℝ) ^ m
  let q : ℝ := gaussMeasure.real B
  let F : Set ℝ := (gaussOrbit (b + m)) ⁻¹' B
  have hFM : MeasurableSet F := hBM.preimage (measurable_gaussOrbit (b + m))
  have hinter := congrArg ENNReal.toReal
    (gaussMeasure_finiteGaussPrefixEvent_inter b words hFM)
  have hevent := congrArg ENNReal.toReal
    (gaussMeasure_finiteGaussPrefixEvent b words)
  have hinterReal : gaussMeasure.real
      (finiteGaussPrefixEvent b words ∩ F) =
      ∑ w ∈ words, gaussMeasure.real
        (positivePrefixCylinder b w ∩ F) := by
    simpa only [measureReal_def, ENNReal.toReal_sum
      (fun w _ => measure_ne_top _ _)] using! hinter
  have heventReal : gaussMeasure.real (finiteGaussPrefixEvent b words) =
      ∑ w ∈ words, gaussMeasure.real
        (positivePrefixCylinder b w) := by
    simpa only [measureReal_def, ENNReal.toReal_sum
      (fun w _ => measure_ne_top _ _)] using! hevent
  rw [hinterReal, heventReal]
  change |(∑ w ∈ words,
      gaussMeasure.real (positivePrefixCylinder b w ∩ F)) -
      (∑ w ∈ words, gaussMeasure.real (positivePrefixCylinder b w)) * q| ≤
    ε * (∑ w ∈ words, gaussMeasure.real (positivePrefixCylinder b w)) * q
  rw [Finset.sum_mul, ← Finset.sum_sub_distrib]
  calc
    |∑ w ∈ words,
        (gaussMeasure.real (positivePrefixCylinder b w ∩ F) -
          gaussMeasure.real (positivePrefixCylinder b w) * q)| ≤
      ∑ w ∈ words,
        |gaussMeasure.real (positivePrefixCylinder b w ∩ F) -
          gaussMeasure.real (positivePrefixCylinder b w) * q| :=
      Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ w ∈ words,
        ε * gaussMeasure.real (positivePrefixCylinder b w) * q := by
      apply Finset.sum_le_sum
      intro w hw
      have hsingle :=
        gaussMeasureReal_prefixCylinder_inter_later_preimage_error_le
          w.2.2 hBM m
      have hlen : w.1.length + m = b + m := by rw [w.2.1]
      simpa only [positivePrefixCylinder, F, ε, q, hlen] using! hsingle
    _ = ε * (∑ w ∈ words,
          gaussMeasure.real (positivePrefixCylinder b w)) * q := by
      rw [Finset.mul_sum, Finset.sum_mul]

/-- A fixed injection supplies explicit finite truncations of the countable
set of positive words. -/
def positiveDigitWordCode (b : ℕ) : PositiveDigitWord b → ℕ :=
  Classical.choose (Countable.exists_injective_nat (PositiveDigitWord b))

theorem injective_positiveDigitWordCode (b : ℕ) :
    Function.Injective (positiveDigitWordCode b) :=
  Classical.choose_spec
    (Countable.exists_injective_nat (PositiveDigitWord b))

theorem finite_positiveDigitWordCode_preimage_range (b R : ℕ) :
    ((positiveDigitWordCode b) ⁻¹'
      (↑(Finset.range R) : Set ℕ)).Finite := by
  exact Set.Finite.preimage
    (Set.injOn_of_injective (injective_positiveDigitWordCode b))
    (Finset.finite_toSet (Finset.range R))

def truncatedGaussPrefixWords (b : ℕ)
    (S : Set (PositiveDigitWord b)) (R : ℕ) :
    Finset (PositiveDigitWord b) := by
  classical
  exact ((finite_positiveDigitWordCode_preimage_range b R).toFinset).filter
    fun w => w ∈ S

theorem mem_truncatedGaussPrefixWords_iff
    {b : ℕ} {S : Set (PositiveDigitWord b)} {R : ℕ}
    {w : PositiveDigitWord b} :
    w ∈ truncatedGaussPrefixWords b S R ↔
      positiveDigitWordCode b w < R ∧ w ∈ S := by
  classical
  simp only [truncatedGaussPrefixWords, Finset.mem_filter,
    Set.Finite.mem_toFinset, Set.mem_preimage, Finset.mem_coe,
    Finset.mem_range]

def gaussPrefixSetEvent (b : ℕ)
    (S : Set (PositiveDigitWord b)) : Set ℝ := by
  classical
  exact ⋃ w : PositiveDigitWord b,
    if w ∈ S then positivePrefixCylinder b w else ∅

theorem measurableSet_gaussPrefixSetEvent
    (b : ℕ) (S : Set (PositiveDigitWord b)) :
    MeasurableSet (gaussPrefixSetEvent b S) := by
  classical
  unfold gaussPrefixSetEvent
  apply MeasurableSet.iUnion
  intro w
  by_cases hw : w ∈ S
  · rw [if_pos hw]
    exact measurableSet_positivePrefixCylinder b w
  · rw [if_neg hw]
    exact MeasurableSet.empty

def truncatedGaussPrefixEvent (b : ℕ)
    (S : Set (PositiveDigitWord b)) (R : ℕ) : Set ℝ :=
  finiteGaussPrefixEvent b (truncatedGaussPrefixWords b S R)

theorem monotone_truncatedGaussPrefixEvent
    (b : ℕ) (S : Set (PositiveDigitWord b)) :
    Monotone (truncatedGaussPrefixEvent b S) := by
  intro R T hRT x hx
  unfold truncatedGaussPrefixEvent finiteGaussPrefixEvent at hx ⊢
  obtain ⟨w, hwR, hxw⟩ := mem_iUnion₂.mp hx
  apply mem_iUnion₂.mpr
  refine ⟨w, ?_, hxw⟩
  rw [mem_truncatedGaussPrefixWords_iff] at hwR ⊢
  exact ⟨hwR.1.trans_le hRT, hwR.2⟩

theorem iUnion_truncatedGaussPrefixEvent
    (b : ℕ) (S : Set (PositiveDigitWord b)) :
    (⋃ R : ℕ, truncatedGaussPrefixEvent b S R) =
      gaussPrefixSetEvent b S := by
  classical
  ext x
  constructor
  · intro hx
    obtain ⟨R, hxR⟩ := mem_iUnion.mp hx
    unfold truncatedGaussPrefixEvent finiteGaussPrefixEvent at hxR
    obtain ⟨w, hwR, hxw⟩ := mem_iUnion₂.mp hxR
    rw [mem_truncatedGaussPrefixWords_iff] at hwR
    unfold gaussPrefixSetEvent
    apply mem_iUnion.mpr
    refine ⟨w, ?_⟩
    simpa only [if_pos hwR.2] using! hxw
  · intro hx
    unfold gaussPrefixSetEvent at hx
    obtain ⟨w, hxw⟩ := mem_iUnion.mp hx
    by_cases hwS : w ∈ S
    · apply mem_iUnion.mpr
      refine ⟨positiveDigitWordCode b w + 1, ?_⟩
      unfold truncatedGaussPrefixEvent finiteGaussPrefixEvent
      apply mem_iUnion₂.mpr
      refine ⟨w, ?_, ?_⟩
      · rw [mem_truncatedGaussPrefixWords_iff]
        exact ⟨Nat.lt_succ_self _, hwS⟩
      · simpa only [if_pos hwS] using! hxw
    · rw [if_neg hwS] at hxw
      exact hxw.elim

/-- Relative mixing for an arbitrary (possibly infinite) union of prefix
atoms.  The proof is the monotone limit of the finite-union theorem. -/
theorem gaussMeasureReal_gaussPrefixSetEvent_inter_later_error_le
    (b : ℕ) (S : Set (PositiveDigitWord b))
    {B : Set ℝ} (hBM : MeasurableSet B) (m : ℕ) :
    |gaussMeasure.real (gaussPrefixSetEvent b S ∩
        (gaussOrbit (b + m)) ⁻¹' B) -
      gaussMeasure.real (gaussPrefixSetEvent b S) *
        gaussMeasure.real B| ≤
      (48 * (527 / 540 : ℝ) ^ m) *
        gaussMeasure.real (gaussPrefixSetEvent b S) *
          gaussMeasure.real B := by
  let A : Set ℝ := gaussPrefixSetEvent b S
  let F : Set ℝ := (gaussOrbit (b + m)) ⁻¹' B
  let AR : ℕ → Set ℝ := truncatedGaussPrefixEvent b S
  let ε : ℝ := 48 * (527 / 540 : ℝ) ^ m
  have hmonoA : Monotone AR := monotone_truncatedGaussPrefixEvent b S
  have hunionA : (⋃ R : ℕ, AR R) = A :=
    iUnion_truncatedGaussPrefixEvent b S
  have hmonoI : Monotone fun R => AR R ∩ F := by
    intro R T hRT
    exact inter_subset_inter_left F (hmonoA hRT)
  have hunionI : (⋃ R : ℕ, AR R ∩ F) = A ∩ F := by
    ext x
    constructor
    · intro hx
      obtain ⟨R, hxR⟩ := mem_iUnion.mp hx
      exact ⟨by
        rw [← hunionA]
        exact mem_iUnion.mpr ⟨R, hxR.1⟩, hxR.2⟩
    · rintro ⟨hxA, hxF⟩
      rw [← hunionA] at hxA
      obtain ⟨R, hxR⟩ := mem_iUnion.mp hxA
      exact mem_iUnion.mpr ⟨R, hxR, hxF⟩
  have hAENN := tendsto_measure_iUnion_atTop
    (μ := gaussMeasure) hmonoA
  rw [hunionA] at hAENN
  have hIENN := tendsto_measure_iUnion_atTop
    (μ := gaussMeasure) hmonoI
  rw [hunionI] at hIENN
  have hAreal : Tendsto (fun R => gaussMeasure.real (AR R)) atTop
      (𝓝 (gaussMeasure.real A)) := by
    have h := (ENNReal.continuousAt_toReal (by finiteness)).tendsto.comp hAENN
    simpa only [Function.comp_apply, measureReal_def] using! h
  have hIreal : Tendsto (fun R => gaussMeasure.real (AR R ∩ F)) atTop
      (𝓝 (gaussMeasure.real (A ∩ F))) := by
    have h := (ENNReal.continuousAt_toReal (by finiteness)).tendsto.comp hIENN
    simpa only [Function.comp_apply, measureReal_def] using! h
  have hleft : Tendsto
      (fun R => |gaussMeasure.real (AR R ∩ F) -
        gaussMeasure.real (AR R) * gaussMeasure.real B|) atTop
      (𝓝 |gaussMeasure.real (A ∩ F) -
        gaussMeasure.real A * gaussMeasure.real B|) :=
    (hIreal.sub (hAreal.mul tendsto_const_nhds)).abs
  have hright : Tendsto
      (fun R => ε * gaussMeasure.real (AR R) * gaussMeasure.real B) atTop
      (𝓝 (ε * gaussMeasure.real A * gaussMeasure.real B)) :=
    (tendsto_const_nhds.mul hAreal).mul tendsto_const_nhds
  have hfinite : ∀ R : ℕ,
      |gaussMeasure.real (AR R ∩ F) -
        gaussMeasure.real (AR R) * gaussMeasure.real B| ≤
      ε * gaussMeasure.real (AR R) * gaussMeasure.real B := by
    intro R
    exact gaussMeasureReal_finiteGaussPrefixEvent_inter_later_error_le
      b (truncatedGaussPrefixWords b S R) hBM m
  exact le_of_tendsto_of_tendsto hleft hright
    (Filter.Eventually.of_forall hfinite)

/-! ## The complete finite-prefix sigma-algebra -/

theorem gaussMeasure_unit_diff_positivePrefixDomain (b : ℕ) :
    gaussMeasure (Ioc (0 : ℝ) 1 \ positivePrefixDomain b) = 0 :=
  measure_mono_null (unit_diff_positivePrefixDomain_subset_exceptional b)
    (gaussMeasure_gaussPrefixExceptional b)

/-- On a full Gauss-measure set, selecting the unique prefix word and then
testing membership in `S` is exactly the union of the corresponding prefix
cylinders. -/
theorem selectedGaussPrefixWord_preimage_ae_eq_gaussPrefixSetEvent
    (b : ℕ) (S : Set (PositiveDigitWord b)) :
    (selectedGaussPrefixWord b) ⁻¹' S =ᵐ[gaussMeasure]
      gaussPrefixSetEvent b S := by
  have hdiffAE : ∀ᵐ x ∂gaussMeasure,
      x ∉ Ioc (0 : ℝ) 1 \ positivePrefixDomain b :=
    measure_eq_zero_iff_ae_notMem.mp
      (gaussMeasure_unit_diff_positivePrefixDomain b)
  filter_upwards [gaussMeasure_unit_ae, hdiffAE] with x hxunit hxdiff
  have hdomain : x ∈ positivePrefixDomain b := by
    by_contra hnot
    exact hxdiff ⟨hxunit, hnot⟩
  apply propext
  constructor
  · intro hxS
    have hxS' : selectedGaussPrefixWord b x ∈ S := hxS
    unfold gaussPrefixSetEvent
    apply mem_iUnion.mpr
    refine ⟨selectedGaussPrefixWord b x, ?_⟩
    rw [if_pos hxS']
    exact selectedGaussPrefixWord_mem hdomain
  · intro hxEvent
    unfold gaussPrefixSetEvent at hxEvent
    obtain ⟨w, hxw⟩ := mem_iUnion.mp hxEvent
    by_cases hwS : w ∈ S
    · have hxCell : x ∈ positivePrefixCylinder b w := by
        simpa only [if_pos hwS] using! hxw
      have hselected := selectedGaussPrefixWord_eq_of_mem w hxCell
      change selectedGaussPrefixWord b x ∈ S
      rw [hselected]
      exact hwS
    · rw [if_neg hwS] at hxw
      exact hxw.elim

/-- The sigma-algebra generated by the first `b` positive Gauss digits,
represented by the measurable selected-word map. -/
def gaussPrefixMeasurableSpace (b : ℕ) : MeasurableSpace ℝ :=
  MeasurableSpace.comap (selectedGaussPrefixWord b) ⊤

/-- The sigma-algebra generated by the state at time `n`. -/
def gaussFutureMeasurableSpace (n : ℕ) : MeasurableSpace ℝ :=
  MeasurableSpace.comap (gaussOrbit n) (borel ℝ)

theorem gaussPrefixMeasurableSpace_le (b : ℕ) :
    gaussPrefixMeasurableSpace b ≤ (borel ℝ) := by
  unfold gaussPrefixMeasurableSpace
  exact (measurable_selectedGaussPrefixWord b).comap_le

theorem gaussFutureMeasurableSpace_le (n : ℕ) :
    gaussFutureMeasurableSpace n ≤ (borel ℝ) := by
  unfold gaussFutureMeasurableSpace
  exact (measurable_gaussOrbit n).comap_le

theorem gaussMeasureReal_prefixMeasurableSet_inter_later_error_le
    (b : ℕ) {A B : Set ℝ}
    (hAM : @MeasurableSet ℝ (gaussPrefixMeasurableSpace b) A)
    (hBM : MeasurableSet B) (m : ℕ) :
    |gaussMeasure.real (A ∩ (gaussOrbit (b + m)) ⁻¹' B) -
      gaussMeasure.real A * gaussMeasure.real B| ≤
      (48 * (527 / 540 : ℝ) ^ m) *
        gaussMeasure.real A * gaussMeasure.real B := by
  rw [MeasurableSpace.measurableSet_comap] at hAM
  obtain ⟨S, _hSM, hpre⟩ := hAM
  have hAE := selectedGaussPrefixWord_preimage_ae_eq_gaussPrefixSetEvent b S
  have hAmeasure := hAE.measure_eq
  have hFself : ((gaussOrbit (b + m)) ⁻¹' B : Set ℝ) =ᵐ[gaussMeasure]
      (gaussOrbit (b + m)) ⁻¹' B :=
    Filter.Eventually.of_forall fun _ => rfl
  have hIAE := hAE.inter hFself
  have hImeasure := hIAE.measure_eq
  have hAreal : gaussMeasure.real ((selectedGaussPrefixWord b) ⁻¹' S) =
      gaussMeasure.real (gaussPrefixSetEvent b S) := by
    simpa only [measureReal_def] using! congrArg ENNReal.toReal hAmeasure
  have hIreal : gaussMeasure.real
      ((selectedGaussPrefixWord b) ⁻¹' S ∩
        (gaussOrbit (b + m)) ⁻¹' B) =
      gaussMeasure.real (gaussPrefixSetEvent b S ∩
        (gaussOrbit (b + m)) ⁻¹' B) := by
    simpa only [measureReal_def] using! congrArg ENNReal.toReal hImeasure
  rw [← hpre]
  rw [hIreal, hAreal]
  exact gaussMeasureReal_gaussPrefixSetEvent_inter_later_error_le
    b S hBM m

/-- Full event-level relative mixing between an arbitrary finite-prefix
event and an arbitrary event of the future state. -/
theorem gaussPrefixFuture_eventRelativeMixing (b m : ℕ) :
    EventRelativeMixing (gaussPrefixMeasurableSpace b)
      (gaussFutureMeasurableSpace (b + m)) gaussMeasure
      (48 * (527 / 540 : ℝ) ^ m) := by
  intro A B hAM hBM
  rw [MeasurableSpace.measurableSet_comap] at hBM
  obtain ⟨C, hCM, hpre⟩ := hBM
  rw [← hpre]
  rw [gaussMeasure_real_gaussOrbit_preimage (b + m) hCM]
  exact gaussMeasureReal_prefixMeasurableSet_inter_later_error_le
    b hAM hCM m

/-- Reusable real-valued covariance form of finite-prefix/future mixing. -/
theorem gaussPrefixFuture_covariance_real
    (b m : ℕ) {f g : ℝ → ℝ}
    (hfM : @Measurable ℝ ℝ (gaussPrefixMeasurableSpace b) (borel ℝ) f)
    (hgM : @Measurable ℝ ℝ (gaussFutureMeasurableSpace (b + m))
      (borel ℝ) g)
    (hfi : Integrable f gaussMeasure) (hgi : Integrable g gaussMeasure) :
    Integrable (fun x => f x * g x) gaussMeasure ∧
      |(∫ x, f x * g x ∂gaussMeasure) -
          (∫ x, f x ∂gaussMeasure) * ∫ x, g x ∂gaussMeasure| ≤
        (48 * (527 / 540 : ℝ) ^ m) *
          (∫ x, |f x| ∂gaussMeasure) *
            ∫ x, |g x| ∂gaussMeasure := by
  exact (gaussPrefixFuture_eventRelativeMixing b m).covariance_real
    (gaussPrefixMeasurableSpace b) (gaussFutureMeasurableSpace (b + m))
    gaussMeasure (48 * (527 / 540 : ℝ) ^ m) (by positivity)
    (gaussPrefixMeasurableSpace_le b)
    (gaussFutureMeasurableSpace_le (b + m)) hfM hgM hfi hgi

/-- Reusable complex-valued covariance form.  This is the exact functional
version needed by the late marked-Fourier case. -/
theorem gaussPrefixFuture_covariance_complex
    (b m : ℕ) {f g : ℝ → ℂ}
    (hfM : @Measurable ℝ ℂ (gaussPrefixMeasurableSpace b) (borel ℂ) f)
    (hgM : @Measurable ℝ ℂ (gaussFutureMeasurableSpace (b + m))
      (borel ℂ) g)
    (hfi : Integrable f gaussMeasure) (hgi : Integrable g gaussMeasure) :
    Integrable (fun x => f x * g x) gaussMeasure ∧
      ‖(∫ x, f x * g x ∂gaussMeasure) -
          (∫ x, f x ∂gaussMeasure) * ∫ x, g x ∂gaussMeasure‖ ≤
        4 * (48 * (527 / 540 : ℝ) ^ m) *
          (∫ x, ‖f x‖ ∂gaussMeasure) *
            ∫ x, ‖g x‖ ∂gaussMeasure := by
  exact (gaussPrefixFuture_eventRelativeMixing b m).covariance_complex
    (gaussPrefixMeasurableSpace b) (gaussFutureMeasurableSpace (b + m))
    gaussMeasure (48 * (527 / 540 : ℝ) ^ m) (by positivity)
    (gaussPrefixMeasurableSpace_le b)
    (gaussFutureMeasurableSpace_le (b + m)) hfM hgM hfi hgi

end

end Erdos1002
