import ErdosProblems.Erdos1058.Erdos1058CharacterData
import ErdosProblems.Erdos1058.Erdos1058PrimeBatchData0

/- The matching prime batch keeps the expensive certificates in four build lanes. -/

/- Generated by generate_character_sieve.py; every witness is kernel-checked. -/
set_option Elab.async false
set_option maxRecDepth 4096
set_option linter.style.longLine false

namespace Erdos1058.PeriodicSieveCertificate

private def periodic_2_0_exceptions : List ExceptionWitness := [
  ⟨2, 0, false⟩]

theorem periodic_2_0 : Obstruction 2 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_2_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_2_1_exceptions : List ExceptionWitness := [
]

theorem periodic_2_1 : Obstruction 2 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_2_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_4_0_exceptions : List ExceptionWitness := [
]

theorem periodic_4_0 : Obstruction 4 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_4_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_4_1_exceptions : List ExceptionWitness := [
]

theorem periodic_4_1 : Obstruction 4 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_4_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_6_0_exceptions : List ExceptionWitness := [
  ⟨3, 0, false⟩,
  ⟨12, 0, false⟩,
  ⟨250, 0, false⟩]

theorem periodic_6_0 : Obstruction 6 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_6_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_6_1_exceptions : List ExceptionWitness := [
]

theorem periodic_6_1 : Obstruction 6 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_6_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_8_0_exceptions : List ExceptionWitness := [
]

theorem periodic_8_0 : Obstruction 8 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_8_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_8_1_exceptions : List ExceptionWitness := [
]

theorem periodic_8_1 : Obstruction 8 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_8_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_10_0_exceptions : List ExceptionWitness := [
]

theorem periodic_10_0 : Obstruction 10 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_10_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_10_1_exceptions : List ExceptionWitness := [
]

theorem periodic_10_1 : Obstruction 10 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_10_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_12_0_exceptions : List ExceptionWitness := [
  ⟨4, 0, false⟩,
  ⟨36, 0, false⟩]

theorem periodic_12_0 : Obstruction 12 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_12_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_12_1_exceptions : List ExceptionWitness := [
]

theorem periodic_12_1 : Obstruction 12 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_12_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_14_0_exceptions : List ExceptionWitness := [
]

theorem periodic_14_0 : Obstruction 14 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_14_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_14_1_exceptions : List ExceptionWitness := [
  ⟨2, 0, false⟩]

theorem periodic_14_1 : Obstruction 14 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_14_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_16_0_exceptions : List ExceptionWitness := [
  ⟨16, 0, false⟩]

theorem periodic_16_0 : Obstruction 16 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_16_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_16_1_exceptions : List ExceptionWitness := [
]

theorem periodic_16_1 : Obstruction 16 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_16_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_18_0_exceptions : List ExceptionWitness := [
]

theorem periodic_18_0 : Obstruction 18 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_18_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_18_1_exceptions : List ExceptionWitness := [
]

theorem periodic_18_1 : Obstruction 18 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_18_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_20_0_exceptions : List ExceptionWitness := [
  ⟨5, 0, false⟩,
  ⟨80, 0, false⟩,
  ⟨108, 0, false⟩]

theorem periodic_20_0 : Obstruction 20 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_20_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_20_1_exceptions : List ExceptionWitness := [
]

theorem periodic_20_1 : Obstruction 20 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_20_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_22_0_exceptions : List ExceptionWitness := [
  ⟨32, 0, false⟩]

theorem periodic_22_0 : Obstruction 22 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_22_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_22_1_exceptions : List ExceptionWitness := [
]

theorem periodic_22_1 : Obstruction 22 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_22_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_24_0_exceptions : List ExceptionWitness := [
]

theorem periodic_24_0 : Obstruction 24 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_24_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_24_1_exceptions : List ExceptionWitness := [
]

theorem periodic_24_1 : Obstruction 24 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_24_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_26_0_exceptions : List ExceptionWitness := [
  ⟨1, 0, false⟩]

theorem periodic_26_0 : Obstruction 26 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_26_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_26_1_exceptions : List ExceptionWitness := [
  ⟨1, 0, false⟩]

theorem periodic_26_1 : Obstruction 26 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_26_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_28_0_exceptions : List ExceptionWitness := [
]

theorem periodic_28_0 : Obstruction 28 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_28_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_28_1_exceptions : List ExceptionWitness := [
  ⟨4, 0, false⟩]

theorem periodic_28_1 : Obstruction 28 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_28_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_30_0_exceptions : List ExceptionWitness := [
  ⟨2, 0, false⟩,
  ⟨6, 0, false⟩,
  ⟨20, 0, false⟩,
  ⟨45, 0, false⟩,
  ⟨150, 0, false⟩,
  ⟨450, 2, false⟩,
  ⟨2400, 2, false⟩]

theorem periodic_30_0 : Obstruction 30 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_30_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_30_1_exceptions : List ExceptionWitness := [
]

theorem periodic_30_1 : Obstruction 30 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_30_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_32_0_exceptions : List ExceptionWitness := [
]

theorem periodic_32_0 : Obstruction 32 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_32_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_32_1_exceptions : List ExceptionWitness := [
]

theorem periodic_32_1 : Obstruction 32 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_32_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_34_0_exceptions : List ExceptionWitness := [
  ⟨544, 2, false⟩]

theorem periodic_34_0 : Obstruction 34 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_34_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_34_1_exceptions : List ExceptionWitness := [
]

theorem periodic_34_1 : Obstruction 34 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_34_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_36_0_exceptions : List ExceptionWitness := [
]

theorem periodic_36_0 : Obstruction 36 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_36_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_36_1_exceptions : List ExceptionWitness := [
]

theorem periodic_36_1 : Obstruction 36 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_36_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_38_0_exceptions : List ExceptionWitness := [
]

theorem periodic_38_0 : Obstruction 38 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_38_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_38_1_exceptions : List ExceptionWitness := [
  ⟨16, 0, false⟩]

theorem periodic_38_1 : Obstruction 38 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_38_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_40_0_exceptions : List ExceptionWitness := [
]

theorem periodic_40_0 : Obstruction 40 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_40_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_40_1_exceptions : List ExceptionWitness := [
]

theorem periodic_40_1 : Obstruction 40 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_40_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_42_0_exceptions : List ExceptionWitness := [
]

theorem periodic_42_0 : Obstruction 42 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_42_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_42_1_exceptions : List ExceptionWitness := [
  ⟨6, 0, false⟩]

theorem periodic_42_1 : Obstruction 42 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_42_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_44_0_exceptions : List ExceptionWitness := [
]

theorem periodic_44_0 : Obstruction 44 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_44_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_44_1_exceptions : List ExceptionWitness := [
]

theorem periodic_44_1 : Obstruction 44 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_44_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_46_0_exceptions : List ExceptionWitness := [
]

theorem periodic_46_0 : Obstruction 46 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_46_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_46_1_exceptions : List ExceptionWitness := [
]

theorem periodic_46_1 : Obstruction 46 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_46_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_48_0_exceptions : List ExceptionWitness := [
  ⟨24, 0, false⟩,
  ⟨96, 0, false⟩,
  ⟨2000, 2, false⟩]

theorem periodic_48_0 : Obstruction 48 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_48_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_48_1_exceptions : List ExceptionWitness := [
]

theorem periodic_48_1 : Obstruction 48 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_48_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_50_0_exceptions : List ExceptionWitness := [
  ⟨4, 0, false⟩,
  ⟨625, 5, false⟩]

theorem periodic_50_0 : Obstruction 50 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_50_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_50_1_exceptions : List ExceptionWitness := [
]

theorem periodic_50_1 : Obstruction 50 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_50_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_52_0_exceptions : List ExceptionWitness := [
]

theorem periodic_52_0 : Obstruction 52 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_52_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_52_1_exceptions : List ExceptionWitness := [
  ⟨2, 0, false⟩]

theorem periodic_52_1 : Obstruction 52 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_52_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_54_0_exceptions : List ExceptionWitness := [
  ⟨54, 0, false⟩]

theorem periodic_54_0 : Obstruction 54 0 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_54_0_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

private def periodic_54_1_exceptions : List ExceptionWitness := [
]

theorem periodic_54_1 : Obstruction 54 1 :=
  obstruction_of_character_certificate (rows := characterRows)
    (exceptions := periodic_54_1_exceptions) (by decide) characterRows_checked
    (by rfl) (by rfl)

end Erdos1058.PeriodicSieveCertificate
