import ErdosProblems.Erdos980.ElliottTail.OddPrimeTensorBridge

/-!
# Collision congruences for the odd-prime sieve

Equality of `ell`-th power residue symbols is not equality of residues: a
power-class fibre contains many residue classes.  Consequently the symbol
tensor in `OddPrimeTensorBridge` cannot by itself imply that a product of
auxiliary primes divides a difference of primary generators.

This file records the exact unconditional replacement.  The local code is
refined to the full tuple of residues.  Equality of that code gives one
congruence for every auxiliary modulus, and pairwise comaximality combines
the congruences into divisibility by their product.  We also prove that a
full-residue collision implies a normalized-symbol collision, so the former
is a genuine refinement of the code used by reciprocity.
-/

open scoped BigOperators NumberField nonZeroDivisors

namespace Erdos980.ElliottTail.OddSymbolCollision

noncomputable section

open Function
open BernoulliRegular
open BernoulliRegular.Furtwaengler
open NumberField
open NumberFieldLargerSieve
open OddPowerReciprocity
open OddPrimeTensorBridge
open RayPrincipalization

/-! ## Generic finite CRT collision lemmas -/

/-- The full tuple of residues of an element at a family of ideals. -/
abbrev FullResidueCode {R Q : Type*} [CommRing R]
    (I : Q → Ideal R) :=
  ∀ t, R ⧸ I t

/-- The full residue code attached to an element of a commutative ring. -/
def fullResidueCode {R Q : Type*} [CommRing R]
    (I : Q → Ideal R) (a : R) : FullResidueCode I :=
  fun t => Ideal.Quotient.mk (I t) a

@[simp] theorem fullResidueCode_apply
    {R Q : Type*} [CommRing R] (I : Q → Ideal R) (a : R) (t : Q) :
    fullResidueCode I a t = Ideal.Quotient.mk (I t) a :=
  rfl

/-- Products of principal ideals are generated by the product of their
generators. -/
theorem finset_prod_span_singleton
    {R Q : Type*} [CommRing R] (s : Finset Q) (f : Q → R) :
    (∏ t ∈ s, Ideal.span ({f t} : Set R)) =
      Ideal.span ({∏ t ∈ s, f t} : Set R) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.prod_insert ha, ih,
        Ideal.span_singleton_mul_span_singleton]

/-- Coordinatewise congruence at pairwise comaximal ideals combines to
membership in their product. -/
theorem sub_mem_idealProduct_of_residue_eq
    {R Q : Type*} [CommRing R]
    (s : Finset Q) (I : Q → Ideal R) (a b : R)
    (hpair : (s : Set Q).Pairwise (IsCoprime on I))
    (hcong : ∀ t ∈ s,
      Ideal.Quotient.mk (I t) a = Ideal.Quotient.mk (I t) b) :
    a - b ∈ ∏ t ∈ s, I t := by
  rw [Ideal.prod_eq_iInf_of_pairwise_isCoprime hpair]
  rw [Ideal.mem_iInf]
  intro t
  rw [Ideal.mem_iInf]
  intro ht
  exact (Ideal.Quotient.mk_eq_mk_iff_sub_mem a b).mp (hcong t ht)

/-- Ideal-divisibility formulation of
`sub_mem_idealProduct_of_residue_eq`.  The order is intentionally
`span {a-b} ≤ product`: in the ideal lattice this says that the product
divides `a-b`. -/
theorem span_sub_le_idealProduct_of_residue_eq
    {R Q : Type*} [CommRing R]
    (s : Finset Q) (I : Q → Ideal R) (a b : R)
    (hpair : (s : Set Q).Pairwise (IsCoprime on I))
    (hcong : ∀ t ∈ s,
      Ideal.Quotient.mk (I t) a = Ideal.Quotient.mk (I t) b) :
    Ideal.span ({a - b} : Set R) ≤ ∏ t ∈ s, I t := by
  exact (Ideal.span_singleton_le_iff_mem _).mpr
    (sub_mem_idealProduct_of_residue_eq s I a b hpair hcong)

/-! ## Rational-integer moduli in a number field -/

variable {K : Type*} [Field K] [NumberField K]

/-- The full tuple of residues modulo the rational integer ideals `(q_t)`. -/
abbrev RationalResidueTensor (Q : Type*) (q : Q → ℕ) :=
  ∀ t, 𝓞 K ⧸ rationalIntIdeal (K := K) (q t : ℤ)

/-- Full rational-ideal residue code of an algebraic integer. -/
def rationalResidueCode {Q : Type*} (q : Q → ℕ) (a : 𝓞 K) :
    RationalResidueTensor (K := K) Q q :=
  fun t => Ideal.Quotient.mk
    (rationalIntIdeal (K := K) (q t : ℤ)) a

@[simp] theorem rationalResidueCode_apply
    {Q : Type*} (q : Q → ℕ) (a : 𝓞 K) (t : Q) :
    rationalResidueCode (K := K) q a t =
      Ideal.Quotient.mk (rationalIntIdeal (K := K) (q t : ℤ)) a :=
  rfl

/-- Pairwise coprime rational integers generate pairwise comaximal ideals in
the ring of integers. -/
theorem pairwise_isCoprime_rationalIntIdeal
    {Q : Type*} (s : Finset Q) (q : Q → ℕ)
    (hpair : (s : Set Q).Pairwise fun i j => Nat.Coprime (q i) (q j)) :
    (s : Set Q).Pairwise
      (IsCoprime on fun t => rationalIntIdeal (K := K) (q t : ℤ)) := by
  intro i hi j hj hij
  change IsCoprime
    (Ideal.span ({algebraMap ℤ (𝓞 K) (q i : ℤ)} : Set (𝓞 K)))
    (Ideal.span ({algebraMap ℤ (𝓞 K) (q j : ℤ)} : Set (𝓞 K)))
  rw [Ideal.isCoprime_span_singleton_iff]
  simpa only [map_natCast] using
    (hpair hi hj hij).cast (R := 𝓞 K)

/-- Equality of full residue tuples forces the product of the rational test
integers to divide the difference of the algebraic integers. -/
theorem rationalPrimeProduct_dvd_sub_of_residueCode_eq
    {Q : Type*} (s : Finset Q) (q : Q → ℕ) (a b : 𝓞 K)
    (hpair : (s : Set Q).Pairwise fun i j => Nat.Coprime (q i) (q j))
    (hcode : rationalResidueCode (K := K) q a =
      rationalResidueCode (K := K) q b) :
    (∏ t ∈ s, (q t : 𝓞 K)) ∣ a - b := by
  have hmem : a - b ∈
      ∏ t ∈ s, rationalIntIdeal (K := K) (q t : ℤ) := by
    apply sub_mem_idealProduct_of_residue_eq s
      (fun t => rationalIntIdeal (K := K) (q t : ℤ)) a b
      (pairwise_isCoprime_rationalIntIdeal (K := K) s q hpair)
    intro t ht
    exact congrFun hcode t
  have hprod :
      (∏ t ∈ s, rationalIntIdeal (K := K) (q t : ℤ)) =
        Ideal.span ({∏ t ∈ s, (q t : 𝓞 K)} : Set (𝓞 K)) := by
    simpa only [rationalIntIdeal, map_natCast] using
      finset_prod_span_singleton s (fun t => (q t : 𝓞 K))
  rw [hprod, Ideal.mem_span_singleton] at hmem
  exact hmem

/-- Explicit witness form of the product divisibility collision. -/
theorem exists_sub_eq_rationalPrimeProduct_mul_of_residueCode_eq
    {Q : Type*} (s : Finset Q) (q : Q → ℕ) (a b : 𝓞 K)
    (hpair : (s : Set Q).Pairwise fun i j => Nat.Coprime (q i) (q j))
    (hcode : rationalResidueCode (K := K) q a =
      rationalResidueCode (K := K) q b) :
    ∃ c : 𝓞 K, a - b = (∏ t ∈ s, (q t : 𝓞 K)) * c := by
  exact rationalPrimeProduct_dvd_sub_of_residueCode_eq
    (K := K) s q a b hpair hcode

/-! ## Corrected primary generators -/

variable (ell : ℕ) [Fact ell.Prime]
  (K : Type*) [Field K] [NumberField K]
  [IsCyclotomicExtension {ell} ℚ K]

local notation "lambdaIdeal" =>
  Ideal.span ({FLT37.zetaSubOne ell K} : Set (𝓞 K))

/-- Full residue code of the canonical primary generator selected by finite
ray principalization. -/
def primaryGeneratorResidueCode
    {A Q : Type*} (q : Q → ℕ)
    (P : A → (Ideal (𝓞 K))⁰)
    (hPL : ∀ a, lambdaIdeal ⊔ (P a : Ideal (𝓞 K)) = ⊤)
    (a : A) : RationalResidueTensor (K := K) Q q :=
  rationalResidueCode (K := K) q
    (primaryGeneratorOf ell K (P a) (hPL a))

/-- A collision of the full primary-generator residue code implies a
collision of every correction-normalized residue-symbol coordinate. -/
theorem normalizedSymbolCode_eq_of_primaryGeneratorResidueCode_eq
    {A Q : Type*} (q : Q → ℕ)
    (P : A → (Ideal (𝓞 K))⁰)
    (hPL : ∀ a, lambdaIdeal ⊔ (P a : Ideal (𝓞 K)) = ⊤)
    (i : CyclotomicRayCorrectionIndex ell K) {a b : A}
    (hcode : primaryGeneratorResidueCode ell K q P hPL a =
      primaryGeneratorResidueCode ell K q P hPL b) :
    normalizedSymbolCode ell K q P hPL i a =
      normalizedSymbolCode ell K q P hPL i b := by
  funext t
  change
    pthSymbolAtInt_canonical (p := ell) (K := K)
        (primaryGeneratorOf ell K (P a) (hPL a)) (q t : ℤ) - _ =
      pthSymbolAtInt_canonical (p := ell) (K := K)
        (primaryGeneratorOf ell K (P b) (hPL b)) (q t : ℤ) - _
  rw [integerSymbol_eq_of_residue_eq (q t : ℤ) (congrFun hcode t)]

/-- Full residue collision gives product divisibility for the selected
primary generators. -/
theorem rationalPrimeProduct_dvd_primaryGenerator_sub_of_residueCode_eq
    {A Q : Type*} (s : Finset Q) (q : Q → ℕ)
    (P : A → (Ideal (𝓞 K))⁰)
    (hPL : ∀ a, lambdaIdeal ⊔ (P a : Ideal (𝓞 K)) = ⊤)
    {a b : A}
    (hpair : (s : Set Q).Pairwise fun i j => Nat.Coprime (q i) (q j))
    (hcode : primaryGeneratorResidueCode ell K q P hPL a =
      primaryGeneratorResidueCode ell K q P hPL b) :
    (∏ t ∈ s, (q t : 𝓞 K)) ∣
      primaryGeneratorOf ell K (P a) (hPL a) -
        primaryGeneratorOf ell K (P b) (hPL b) := by
  exact rationalPrimeProduct_dvd_sub_of_residueCode_eq
    (K := K) s q _ _ hpair hcode

/-- The complete valid collision package for two conductors in the same
finite correction fibre.  Full residue equality gives both the desired
product divisibility and equality of the normalized symbol tensors. -/
theorem sameCorrection_fullResidueCollision
    {A Q : Type*} (s : Finset Q) (q : Q → ℕ)
    (P : A → (Ideal (𝓞 K))⁰)
    (hPL : ∀ a, lambdaIdeal ⊔ (P a : Ideal (𝓞 K)) = ⊤)
    {a b : A}
    (hpair : (s : Set Q).Pairwise fun i j => Nat.Coprime (q i) (q j))
    (hindex : correctionIndexOf ell K (P a) (hPL a) =
      correctionIndexOf ell K (P b) (hPL b))
    (hcode : primaryGeneratorResidueCode ell K q P hPL a =
      primaryGeneratorResidueCode ell K q P hPL b) :
    ((∏ t ∈ s, (q t : 𝓞 K)) ∣
        primaryGeneratorOf ell K (P a) (hPL a) -
          primaryGeneratorOf ell K (P b) (hPL b)) ∧
      normalizedSymbolCode ell K q P hPL
          (correctionIndexOf ell K (P a) (hPL a)) a =
        normalizedSymbolCode ell K q P hPL
          (correctionIndexOf ell K (P b) (hPL b)) b := by
  constructor
  · exact rationalPrimeProduct_dvd_primaryGenerator_sub_of_residueCode_eq
      ell K s q P hPL hpair hcode
  · rw [← hindex]
    exact normalizedSymbolCode_eq_of_primaryGeneratorResidueCode_eq
      ell K q P hPL _ hcode

/-! ## Why symbol equality alone cannot yield congruence -/

/-- A concrete odd-prime power-class collision with distinct residues.
Thus even one exact local power-class coordinate is too coarse to recover a
congruence, before any number-field complications enter. -/
theorem cubicPowerClass_collision_without_residueCollision :
    powerClass 3 (-1 : (ZMod 7)ˣ) =
        powerClass 3 (1 : (ZMod 7)ˣ) ∧
      (((-1 : (ZMod 7)ˣ) : ZMod 7) ≠
        ((1 : (ZMod 7)ˣ) : ZMod 7)) := by
  constructor
  · apply (powerClass_eq_one_iff 3 (-1 : (ZMod 7)ˣ)).mpr
    exact ⟨-1, by norm_num⟩
  · exact @ZMod.neg_one_ne_one 7 ⟨by norm_num⟩

end

end Erdos980.ElliottTail.OddSymbolCollision
