import Mathlib

/-!
# Quadrilateral components in a hexagon-free graph

This file supplies the finite, edge-level language used in the
Füredi--Naor--Verstraëte analysis of `C₆`-free graphs.  Two edges are related
when they occur on a common quadrilateral, and a quadrilateral component is an
equivalence class for the relation generated by these elementary moves.

The definitions near the end of the file are a literal certificate interface
for the structural lemma U1.  They record the three exceptional configurations
from the paper, strong inducedness, and a cover by at most ten maximal complete
bipartite pieces.  Keeping this data in one certificate makes the exact
dependency of the later multiplicity arguments explicit.
-/

namespace Erdos59

open Finset SimpleGraph

noncomputable section

variable {V : Type*} (G : SimpleGraph V)

attribute [local instance] Classical.propDecidable

noncomputable local instance : DecidableEq V := Classical.typeDecidableEq V

/-- An edge of `G`, carrying its proof of membership in the edge set. -/
abbrev GraphEdge := G.edgeSet

/-- Two edges share a quadrilateral when a simple closed walk of length four
contains both.  The edges need not be distinct. -/
def SharesQuadrilateral (e f : GraphEdge G) : Prop :=
  ∃ (v : V) (q : G.Walk v v), q.IsCycle ∧ q.length = 4 ∧
    e.1 ∈ q.edges ∧ f.1 ∈ q.edges

/-- An edge occurs in at least one quadrilateral. -/
def EdgeInQuadrilateral (e : GraphEdge G) : Prop :=
  ∃ (v : V) (q : G.Walk v v), q.IsCycle ∧ q.length = 4 ∧ e.1 ∈ q.edges

theorem edgeInQuadrilateral_of_shares_left {e f : GraphEdge G}
    (h : SharesQuadrilateral G e f) : EdgeInQuadrilateral G e := by
  rcases h with ⟨v, q, hq, hlen, he, -⟩
  exact ⟨v, q, hq, hlen, he⟩

theorem edgeInQuadrilateral_of_shares_right {e f : GraphEdge G}
    (h : SharesQuadrilateral G e f) : EdgeInQuadrilateral G f := by
  rcases h with ⟨v, q, hq, hlen, -, hf⟩
  exact ⟨v, q, hq, hlen, hf⟩

theorem sharesQuadrilateral_symm {e f : GraphEdge G}
    (h : SharesQuadrilateral G e f) : SharesQuadrilateral G f e := by
  rcases h with ⟨v, q, hq, hlen, he, hf⟩
  exact ⟨v, q, hq, hlen, hf, he⟩

/-- The equivalence relation generated by sharing a quadrilateral. -/
def QuadrilateralConnected (e f : GraphEdge G) : Prop :=
  Relation.EqvGen (SharesQuadrilateral G) e f

theorem quadrilateralConnected_refl (e : GraphEdge G) :
    QuadrilateralConnected G e e :=
  Relation.EqvGen.refl e

theorem quadrilateralConnected_symm {e f : GraphEdge G}
    (h : QuadrilateralConnected G e f) : QuadrilateralConnected G f e :=
  Relation.EqvGen.symm e f h

theorem quadrilateralConnected_trans {e f k : GraphEdge G}
    (hef : QuadrilateralConnected G e f) (hfk : QuadrilateralConnected G f k) :
    QuadrilateralConnected G e k :=
  Relation.EqvGen.trans e f k hef hfk

theorem quadrilateralConnected_of_shares {e f : GraphEdge G}
    (h : SharesQuadrilateral G e f) : QuadrilateralConnected G e f :=
  Relation.EqvGen.rel e f h

/-- The setoid generated by the quadrilateral relation. -/
def quadrilateralSetoid : Setoid (GraphEdge G) :=
  Relation.EqvGen.setoid (SharesQuadrilateral G)

/-- A quadrilateral component is an equivalence class of edges. -/
abbrev QuadrilateralComponent := Quotient (quadrilateralSetoid G)

/-- The component containing an edge. -/
def componentOf (e : GraphEdge G) : QuadrilateralComponent G :=
  Quotient.mk (quadrilateralSetoid G) e

theorem componentOf_eq_iff {e f : GraphEdge G} :
    componentOf G e = componentOf G f ↔ QuadrilateralConnected G e f := by
  constructor
  · exact Quotient.exact
  · intro h
    change Quotient.mk (quadrilateralSetoid G) e =
      Quotient.mk (quadrilateralSetoid G) f
    apply Quotient.sound
    exact h

theorem componentOf_eq_of_shares {e f : GraphEdge G}
    (h : SharesQuadrilateral G e f) : componentOf G e = componentOf G f := by
  exact (componentOf_eq_iff G).2 (quadrilateralConnected_of_shares G h)

/-- An edge in no quadrilateral is isolated in the generated relation. -/
theorem quadrilateralConnected_eq_of_not_edgeInQuadrilateral
    {e f : GraphEdge G} (he : ¬ EdgeInQuadrilateral G e)
    (h : QuadrilateralConnected G e f) : e = f := by
  let sameSide : GraphEdge G → GraphEdge G → Prop :=
    fun x y ↦ (x = e ↔ y = e)
  have sameSide_equiv : Equivalence sameSide := by
    refine ⟨?_, ?_, ?_⟩
    · intro x
      exact Iff.rfl
    · intro x y hxy
      exact hxy.symm
    · intro x y z hxy hyz
      exact hxy.trans hyz
  letI : IsEquiv (GraphEdge G) sameSide := sameSide_equiv.isEquiv
  have hstep : SharesQuadrilateral G ≤ sameSide := by
    intro x y hxy
    constructor
    · intro hxe
      subst x
      exact False.elim (he (edgeInQuadrilateral_of_shares_left G hxy))
    · intro hye
      subst y
      exact False.elim (he (edgeInQuadrilateral_of_shares_right G hxy))
  have hs : sameSide e f := Relation.EqvGen.eqvGen_le hstep e f h
  exact (hs.mp rfl).symm

section Finite

variable [Fintype V]

/-- The finite set of edges in a quadrilateral component. -/
def componentEdges (C : QuadrilateralComponent G) : Finset (GraphEdge G) :=
  Finset.univ.filter fun e ↦ componentOf G e = C

@[simp] theorem mem_componentEdges {C : QuadrilateralComponent G} {e : GraphEdge G} :
    e ∈ componentEdges G C ↔ componentOf G e = C := by
  simp [componentEdges]

@[simp] theorem mem_own_component (e : GraphEdge G) :
    e ∈ componentEdges G (componentOf G e) := by
  simp

theorem componentEdges_nonempty (C : QuadrilateralComponent G) :
    (componentEdges G C).Nonempty := by
  refine Quotient.inductionOn C ?_
  intro e
  exact ⟨e, mem_own_component G e⟩

theorem componentEdges_injective : Function.Injective (componentEdges G) := by
  intro C D hCD
  obtain ⟨e, heC⟩ := componentEdges_nonempty G C
  have heD : e ∈ componentEdges G D := by simpa [hCD] using heC
  exact ((mem_componentEdges G).1 heC).symm.trans ((mem_componentEdges G).1 heD)

@[simp] theorem componentEdges_eq_iff {C D : QuadrilateralComponent G} :
    componentEdges G C = componentEdges G D ↔ C = D := by
  exact componentEdges_injective G |>.eq_iff

theorem componentEdges_disjoint {C D : QuadrilateralComponent G} (hCD : C ≠ D) :
    Disjoint (componentEdges G C) (componentEdges G D) := by
  rw [Finset.disjoint_left]
  intro e heC heD
  apply hCD
  exact ((mem_componentEdges G).1 heC).symm.trans ((mem_componentEdges G).1 heD)

theorem components_equal_of_common_edge {C D : QuadrilateralComponent G}
    {e : GraphEdge G} (heC : e ∈ componentEdges G C)
    (heD : e ∈ componentEdges G D) : C = D := by
  exact ((mem_componentEdges G).1 heC).symm.trans ((mem_componentEdges G).1 heD)

/-- The component sets form a partition: each edge belongs to a unique one. -/
theorem existsUnique_component (e : GraphEdge G) :
    ∃! C : QuadrilateralComponent G, e ∈ componentEdges G C := by
  refine ⟨componentOf G e, mem_own_component G e, ?_⟩
  intro C heC
  exact ((mem_componentEdges G).1 heC).symm

/-- The union of all component edge sets is the full edge type. -/
theorem biUnion_componentEdges :
    Finset.univ.biUnion (componentEdges G) =
      (Finset.univ : Finset (GraphEdge G)) := by
  ext e
  simp only [Finset.mem_biUnion, Finset.mem_univ, true_and]
  exact ⟨fun _ ↦ trivial, fun _ ↦ ⟨componentOf G e, mem_own_component G e⟩⟩

/-- A component represented as a spanning subgraph of `G`. -/
def componentGraph (C : QuadrilateralComponent G) : SimpleGraph V :=
  SimpleGraph.fromEdgeSet ((fun e : GraphEdge G ↦ e.1) '' (componentEdges G C : Set (GraphEdge G)))

theorem componentGraph_edgeSet (C : QuadrilateralComponent G) :
    (componentGraph G C).edgeSet =
      (fun e : GraphEdge G ↦ e.1) '' (componentEdges G C : Set (GraphEdge G)) := by
  rw [componentGraph, SimpleGraph.edgeSet_fromEdgeSet]
  apply Disjoint.sdiff_eq_left
  rw [Set.disjoint_left]
  rintro e ⟨e', -, rfl⟩ he'
  exact (G.edgeSet_subset_compl_diagSet e'.property) he'

theorem componentGraph_le (C : QuadrilateralComponent G) : componentGraph G C ≤ G := by
  rw [← SimpleGraph.edgeSet_subset_edgeSet, componentGraph_edgeSet]
  rintro _ ⟨e, -, rfl⟩
  exact e.property

/-- Vertices incident with at least one edge in the component. -/
def componentVertices (C : QuadrilateralComponent G) : Finset V :=
  Finset.univ.filter fun v ↦
    ∃ e ∈ componentEdges G C, v ∈ e.1.toFinset

@[simp] theorem mem_componentVertices {C : QuadrilateralComponent G} {v : V} :
    v ∈ componentVertices G C ↔
      ∃ e ∈ componentEdges G C, v ∈ e.1.toFinset := by
  simp [componentVertices]

/-- A component not participating in any quadrilateral is a singleton. -/
def IsSingletonComponent (C : QuadrilateralComponent G) : Prop :=
  (componentEdges G C).card = 1

theorem isSingletonComponent_iff_exists {C : QuadrilateralComponent G} :
    IsSingletonComponent G C ↔ ∃ e, componentEdges G C = {e} := by
  simp [IsSingletonComponent, Finset.card_eq_one]

theorem singletonComponent_of_not_edgeInQuadrilateral {e : GraphEdge G}
    (he : ¬ EdgeInQuadrilateral G e) :
    IsSingletonComponent G (componentOf G e) := by
  have hset : componentEdges G (componentOf G e) = {e} := by
    ext f
    simp only [mem_componentEdges, Finset.mem_singleton]
    constructor
    · intro hf
      have hconn : QuadrilateralConnected G e f := by
        apply quadrilateralConnected_symm G
        exact (componentOf_eq_iff G).1 hf
      exact (quadrilateralConnected_eq_of_not_edgeInQuadrilateral G he hconn).symm
    · intro hfe
      subst f
      rfl
  rw [IsSingletonComponent, hset]
  simp

theorem edgeInQuadrilateral_of_not_singleton {e : GraphEdge G}
    (he : ¬ IsSingletonComponent G (componentOf G e)) :
    EdgeInQuadrilateral G e := by
  by_contra hquad
  exact he (singletonComponent_of_not_edgeInQuadrilateral G hquad)

theorem not_singletonComponent_of_edgeInQuadrilateral {e : GraphEdge G}
    (he : EdgeInQuadrilateral G e) :
    ¬ IsSingletonComponent G (componentOf G e) := by
  rcases he with ⟨v, q, hq, hlen, heq⟩
  have hcard : q.edges.toFinset.card = 4 := by
    rw [List.toFinset_card_of_nodup hq.edges_nodup, q.length_edges, hlen]
  obtain ⟨f, hfq, hfe⟩ :=
    q.edges.toFinset.exists_mem_ne (by omega) e.1
  let f' : GraphEdge G :=
    ⟨f, q.edges_subset_edgeSet (List.mem_toFinset.mp hfq)⟩
  have hshares : SharesQuadrilateral G e f' := by
    exact ⟨v, q, hq, hlen, heq, List.mem_toFinset.mp hfq⟩
  have hfcomp : f' ∈ componentEdges G (componentOf G e) := by
    rw [mem_componentEdges]
    exact (componentOf_eq_of_shares G hshares).symm
  have hecomp : e ∈ componentEdges G (componentOf G e) := mem_own_component G e
  intro hsingle
  obtain ⟨a, ha⟩ := Finset.card_eq_one.mp hsingle
  have hea : e = a := by simpa [ha] using hecomp
  have hfa : f' = a := by simpa [ha] using hfcomp
  apply hfe
  exact congrArg Subtype.val (hfa.trans hea.symm)

theorem singletonComponent_iff_not_edgeInQuadrilateral {e : GraphEdge G} :
    IsSingletonComponent G (componentOf G e) ↔ ¬ EdgeInQuadrilateral G e := by
  constructor
  · intro hs he
    exact not_singletonComponent_of_edgeInQuadrilateral G he hs
  · exact singletonComponent_of_not_edgeInQuadrilateral G

end Finite

/-! ## Complete bipartite pieces -/

section Pieces

variable [Fintype V]

/-- An edge crosses two named vertex sets. -/
def EdgeCrosses (L R : Finset V) (e : GraphEdge G) : Prop :=
  ∃ x ∈ L, ∃ y ∈ R, e.1 = s(x, y)

/-- `p` is exactly the edge set of a complete bipartite graph with both sides
of size at least two.  Thus a piece always contains a quadrilateral. -/
def IsCompleteBipartitePiece (p : Finset (GraphEdge G)) : Prop :=
  ∃ L R : Finset V,
    Disjoint L R ∧ 2 ≤ L.card ∧ 2 ≤ R.card ∧
    (∀ x ∈ L, ∀ y ∈ R, G.Adj x y) ∧
    ∀ e : GraphEdge G, e ∈ p ↔ EdgeCrosses G L R e

/-- A maximal complete bipartite piece, maximal by inclusion of edge sets. -/
def IsMaximalCompleteBipartitePiece (p : Finset (GraphEdge G)) : Prop :=
  IsCompleteBipartitePiece G p ∧
    ∀ q : Finset (GraphEdge G), IsCompleteBipartitePiece G q → p ⊆ q → q = p

/-- A quadrilateral component which itself is one maximal complete bipartite
piece. -/
def IsMaximalCompleteBipartiteComponent (C : QuadrilateralComponent G) : Prop :=
  IsMaximalCompleteBipartitePiece G (componentEdges G C)

/-- A family of maximal complete bipartite pieces covers the component. -/
def IsMaximalBicliqueCover (C : QuadrilateralComponent G)
    (pieces : Finset (Finset (GraphEdge G))) : Prop :=
  (∀ p ∈ pieces, IsMaximalCompleteBipartitePiece G p) ∧
    componentEdges G C = pieces.biUnion id

/-- The uniform numerical part of U1. -/
def HasAtMostTenBicliquePieces (C : QuadrilateralComponent G) : Prop :=
  ∃ pieces : Finset (Finset (GraphEdge G)),
    pieces.card ≤ 10 ∧ IsMaximalBicliqueCover G C pieces

theorem maximalCompleteBipartiteComponent_hasAtMostTen
    {C : QuadrilateralComponent G} (hC : IsMaximalCompleteBipartiteComponent G C) :
    HasAtMostTenBicliquePieces G C := by
  refine ⟨{componentEdges G C}, by simp, ?_, ?_⟩
  · intro p hp
    simp only [Finset.mem_singleton] at hp
    subst p
    exact hC
  · simp

end Pieces

/-! ## Strong inducedness and the three exceptional types -/

/-- Exclusion of a simple six-cycle. -/
def WalkC6Free : Prop :=
  ∀ (v : V) (q : G.Walk v v), q.IsCycle → q.length ≠ 6

/-- Every path of length at most four whose endpoints lie in `S` stays in
`S`.  Since the exceptional component is induced on `S`, this is precisely
the strongly-induced condition used by Füredi--Naor--Verstraëte. -/
def StronglyInduced (S : Set V) : Prop :=
  ∀ ⦃u v : V⦄ (p : G.Walk u v), p.IsPath → p.length ≤ 4 →
    u ∈ S → v ∈ S → ∀ x ∈ p.support, x ∈ S

section Exceptional

variable [Fintype V]

/-- `p` contains exactly the edges of `G` induced by `S`. -/
def IsInducedEdgeSet (S : Finset V) (p : Finset (GraphEdge G)) : Prop :=
  ∀ e : GraphEdge G, e ∈ p ↔ e.1.toFinset ⊆ S

/-- The first exceptional FNV configuration: a triangle `a b c`, together
with all additional common neighbours of `a,b` and of `a,c`; the two sets
of additional neighbours are nonempty and disjoint. -/
structure ExceptionalTypeOne (C : QuadrilateralComponent G) where
  a : V
  b : V
  c : V
  A : Finset V
  B : Finset V
  triangle_ab : G.Adj a b
  triangle_bc : G.Adj b c
  triangle_ca : G.Adj c a
  A_nonempty : A.Nonempty
  B_nonempty : B.Nonempty
  A_disjoint_B : Disjoint A B
  mem_A : ∀ x, x ∈ A ↔ x ≠ c ∧ G.Adj a x ∧ G.Adj b x
  mem_B : ∀ x, x ∈ B ↔ x ≠ b ∧ G.Adj a x ∧ G.Adj c x
  vertices : componentVertices G C = insert a (insert b (insert c (A ∪ B)))
  induced : IsInducedEdgeSet G (componentVertices G C) (componentEdges G C)
  stronglyInduced : StronglyInduced G (componentVertices G C : Set V)

/-- The second exceptional FNV configuration: a `K₄` on `a,b,c,d`,
together with all the other common neighbours of `a,b`. -/
structure ExceptionalTypeTwo (C : QuadrilateralComponent G) where
  a : V
  b : V
  c : V
  d : V
  A : Finset V
  core_card : ({a, b, c, d} : Finset V).card = 4
  core_clique : ∀ x ∈ ({a, b, c, d} : Finset V),
    ∀ y ∈ ({a, b, c, d} : Finset V), x ≠ y → G.Adj x y
  mem_A : ∀ x, x ∈ A ↔ x ≠ c ∧ x ≠ d ∧ G.Adj a x ∧ G.Adj b x
  vertices : componentVertices G C = insert a (insert b (insert c (insert d A)))
  induced : IsInducedEdgeSet G (componentVertices G C) (componentEdges G C)
  stronglyInduced : StronglyInduced G (componentVertices G C : Set V)

/-- The third exceptional FNV configuration: an induced five-vertex graph
of minimum internal degree at least three. -/
structure ExceptionalTypeThree (C : QuadrilateralComponent G) where
  S : Finset V
  card_S : S.card = 5
  vertices : componentVertices G C = S
  induced : IsInducedEdgeSet G S (componentEdges G C)
  minDegree : ∀ x ∈ S, 3 ≤ (S.erase x |>.filter fun y ↦ G.Adj x y).card
  stronglyInduced : StronglyInduced G (S : Set V)

/-- The disjunction of the three exceptional configurations. -/
def IsExceptionalComponent (C : QuadrilateralComponent G) : Prop :=
  Nonempty (ExceptionalTypeOne G C) ∨ Nonempty (ExceptionalTypeTwo G C) ∨
    Nonempty (ExceptionalTypeThree G C)

theorem exceptionalTypeOne_stronglyInduced {C : QuadrilateralComponent G}
    (h : ExceptionalTypeOne G C) :
    StronglyInduced G (componentVertices G C : Set V) :=
  h.stronglyInduced

theorem exceptionalTypeTwo_stronglyInduced {C : QuadrilateralComponent G}
    (h : ExceptionalTypeTwo G C) :
    StronglyInduced G (componentVertices G C : Set V) :=
  h.stronglyInduced

theorem exceptionalTypeThree_stronglyInduced {C : QuadrilateralComponent G}
    (h : ExceptionalTypeThree G C) :
    StronglyInduced G (componentVertices G C : Set V) := by
  simpa [h.vertices] using h.stronglyInduced

theorem exceptionalComponent_stronglyInduced {C : QuadrilateralComponent G}
    (h : IsExceptionalComponent G C) :
    StronglyInduced G (componentVertices G C : Set V) := by
  rcases h with h | h | h
  · exact h.some.stronglyInduced
  · exact h.some.stronglyInduced
  · simpa [h.some.vertices] using h.some.stronglyInduced

end Exceptional

/-! ## The finite U1 certificate -/

section Certificate

variable [Fintype V]

/-- The five mutually named outcomes in the U1 classification.  A bounded
biclique cover is stored for exceptional components because it is the exact
piece of the Appendix classification consumed by the later path-counting
argument. -/
inductive U1ComponentClassification (C : QuadrilateralComponent G) : Prop
  | singleton (h : IsSingletonComponent G C)
  | maximalBiclique (h : IsMaximalCompleteBipartiteComponent G C)
  | exceptionalOne (shape : ExceptionalTypeOne G C)
      (pieces : HasAtMostTenBicliquePieces G C)
  | exceptionalTwo (shape : ExceptionalTypeTwo G C)
      (pieces : HasAtMostTenBicliquePieces G C)
  | exceptionalThree (shape : ExceptionalTypeThree G C)
      (pieces : HasAtMostTenBicliquePieces G C)

/-- A finite certificate for FNV U1 on `G`. -/
structure U1Certificate : Prop where
  c6Free : WalkC6Free G
  classify : ∀ C : QuadrilateralComponent G, U1ComponentClassification G C

theorem U1ComponentClassification.shape_disjunction
    {C : QuadrilateralComponent G} (h : U1ComponentClassification G C) :
    IsSingletonComponent G C ∨ IsMaximalCompleteBipartiteComponent G C ∨
      IsExceptionalComponent G C := by
  cases h with
  | singleton hs => exact Or.inl hs
  | maximalBiclique hb => exact Or.inr (Or.inl hb)
  | exceptionalOne hs _ => exact Or.inr (Or.inr (Or.inl ⟨hs⟩))
  | exceptionalTwo hs _ => exact Or.inr (Or.inr (Or.inr (Or.inl ⟨hs⟩)))
  | exceptionalThree hs _ => exact Or.inr (Or.inr (Or.inr (Or.inr ⟨hs⟩)))

theorem U1ComponentClassification.piece_bound
    {C : QuadrilateralComponent G} (h : U1ComponentClassification G C) :
    IsSingletonComponent G C ∨ HasAtMostTenBicliquePieces G C := by
  cases h with
  | singleton hs => exact Or.inl hs
  | maximalBiclique hb => exact Or.inr (maximalCompleteBipartiteComponent_hasAtMostTen G hb)
  | exceptionalOne _ hp => exact Or.inr hp
  | exceptionalTwo _ hp => exact Or.inr hp
  | exceptionalThree _ hp => exact Or.inr hp

theorem U1ComponentClassification.exception_stronglyInduced
    {C : QuadrilateralComponent G} (h : U1ComponentClassification G C)
    (he : IsExceptionalComponent G C) :
    StronglyInduced G (componentVertices G C : Set V) :=
  exceptionalComponent_stronglyInduced G he

/-- U1, projected to its classification statement. -/
theorem U1Certificate.classification (h : U1Certificate G)
    (C : QuadrilateralComponent G) :
    IsSingletonComponent G C ∨ IsMaximalCompleteBipartiteComponent G C ∨
      IsExceptionalComponent G C :=
  (h.classify C).shape_disjunction

/-- U1, projected to the uniform bound of ten maximal biclique pieces. -/
theorem U1Certificate.atMostTenPieces (h : U1Certificate G)
    (C : QuadrilateralComponent G) :
    IsSingletonComponent G C ∨ HasAtMostTenBicliquePieces G C :=
  (h.classify C).piece_bound

/-- U1, projected to strong inducedness of every exceptional component. -/
theorem U1Certificate.exceptionStronglyInduced (h : U1Certificate G)
    {C : QuadrilateralComponent G} (he : IsExceptionalComponent G C) :
    StronglyInduced G (componentVertices G C : Set V) :=
  exceptionalComponent_stronglyInduced G he

/-- The complete finite U1 interface used downstream: partition, classification,
ten-piece bound, and strong inducedness. -/
theorem fnvU1 (h : U1Certificate G) :
    (∀ e : GraphEdge G, ∃! C : QuadrilateralComponent G,
      e ∈ componentEdges G C) ∧
    (∀ C : QuadrilateralComponent G,
      IsSingletonComponent G C ∨ IsMaximalCompleteBipartiteComponent G C ∨
        IsExceptionalComponent G C) ∧
    (∀ C : QuadrilateralComponent G,
      IsSingletonComponent G C ∨ HasAtMostTenBicliquePieces G C) ∧
    (∀ C : QuadrilateralComponent G, IsExceptionalComponent G C →
      StronglyInduced G (componentVertices G C : Set V)) := by
  exact ⟨existsUnique_component G, h.classification, h.atMostTenPieces,
    fun _ ↦ h.exceptionStronglyInduced⟩

end Certificate

end

end Erdos59
