import Arxiv.Arxiv2411_18291.HalfAlphaDecoderFamily
import Arxiv.Arxiv2411_18291.HalfAlphaSignedAbsorber
import Arxiv.Arxiv2411_18291.Absorption
import Arxiv.Arxiv2411_18291.CliqueSupportBounds

/-! # Finite sparse absorbers from multiplicity-16 integral generators -/

open Finset

noncomputable section

namespace Arxiv2411_18291

/-- Every leaf generated by the supplied family is absorbed by one fixed
host. All decoders, exchange patterns, and placements are constructed at n0. -/
theorem exists_absorber_for_generated_leaves_paper_threshold {q r n : ℕ}
    (hqr : r + 1 < q) (hn : paperSizeThreshold q (r + 1) ≤ n)
    (B : Hypergraph (Fin n) (r + 1)) (D₁ : Finset (Block (Fin n) q))
    (hB : IsGraphBounded B (2 * (n : ℝ) ^ (-(paperAlpha q (r + 1) / 2))))
    (hDB : cliqueSupport (r + 1) D₁ ⊆ B)
    (hmult : ∀ e : Block (Fin n) (r + 1), (D₁.filter fun Q => e.val ⊆ Q.val).card ≤ 16) :
    ∃ H : Hypergraph (Fin n) (r + 1), HasDecomposition q H ∧ Disjoint H B ∧
      IsGraphBounded H ((n : ℝ) ^ (-(paperAlpha q (r + 1) / 4))) ∧
      AbsorbsGeneratedLeaves D₁ B H := by
  obtain ⟨D, B', _, hBB', hD, hB', hDB', hmult', hrep⟩ :=
    exists_normalized_decoder_family_half_alpha hqr hn B D₁ hB hDB hmult
  obtain ⟨H, hH, hdis, hbound, habs⟩ :=
    exists_normalized_signed_absorber_paper_threshold hqr hn D B' hD hB' hDB' hmult'
  refine ⟨H, hH, Disjoint.mono_right hBB' hdis, hbound, ?_⟩
  intro L hLB hgen
  obtain ⟨Φ, hb, hs, hc⟩ := hrep L hLB hgen
  exact habs L (hLB.trans hBB') Φ hc hs hb

/-- The only input not constructed by this finite absorber theorem is the
sparse integral generating family. Its multiplicity may be 16. -/
theorem exists_sparse_absorber_paper_threshold_of_generators {q r n : ℕ}
    (hqr : r + 1 < q) (hn : paperSizeThreshold q (r + 1) ≤ n)
    (R : Hypergraph (Fin n) (r + 1))
    (hR : IsGraphBounded R ((n : ℝ) ^ (-paperRho q (r + 1))))
    (D : Finset (Block (Fin n) q))
    (hD : IsCliqueFamilyBounded r D ((n : ℝ) ^ (-(paperAlpha q (r + 1) / 2))))
    (hmult : ∀ e : Block (Fin n) (r + 1), (D.filter fun Q => e.val ⊆ Q.val).card ≤ 16)
    (hspan : ∀ J : Block (Fin n) (r + 1) → ℤ, (∀ e, e ∉ R → J e = 0) →
      IntegrallyDecomposable q J → GeneratedBy D J) :
    ∃ H : Hypergraph (Fin n) (r + 1), IsAbsorber q H R ∧
      IsGraphBounded H ((n : ℝ) ^ (-(paperAlpha q (r + 1) / 4))) := by
  have hn1 : (1 : ℝ) ≤ n := by
    exact_mod_cast ((paperSizeThreshold_one_lt hqr).le.trans hn)
  have hα := paperAlpha_pos hqr
  have hαρ := paperAlpha_le_rho hqr
  have hR' : IsGraphBounded R ((n : ℝ) ^ (-(paperAlpha q (r + 1) / 2))) :=
    hR.mono (Real.rpow_le_rpow_of_exponent_le hn1 (by linarith only [hα, hαρ]))
  let B := R ∪ cliqueSupport (r + 1) D
  have hB : IsGraphBounded B (2 * (n : ℝ) ^ (-(paperAlpha q (r + 1) / 2))) := by
    simpa only [two_mul] using hR'.union hD.support_graphBounded
  obtain ⟨H, _, hdis, hbound, habs⟩ := exists_absorber_for_generated_leaves_paper_threshold
    hqr hn B D hB subset_union_right hmult
  refine ⟨H, ⟨Disjoint.mono_right subset_union_left hdis, ?_⟩, hbound⟩
  intro L hLR hL
  apply habs L (hLR.trans subset_union_left)
  exact hspan (indicator L)
    (fun e he => indicator_apply_of_notMem (fun h => he (hLR h))) hL

end Arxiv2411_18291
