import Arxiv.Arxiv2411_18291.RainbowPaletteUnion
import Arxiv.Arxiv2411_18291.IntegralExchangeGeneration

/-!
# Generating a cancelling pair using a rainbow elimination copy

The root edges other than the common edge are joined to an extension with
disjoint colour labels. Every remaining elimination clique avoids the common
edge, so it is a rainbow clique and the pair difference is generated by
the rainbow clique family over the integers.
-/

open Finset

noncomputable section

namespace Arxiv2411_18291

variable {I V : Type*} [Fintype V] [DecidableEq V] {q r : ℕ}

open Classical in
def rainbowCliqueFamily (colour : I → Hypergraph V r) (q : ℕ) : Finset (Block V q) :=
  univ.filter fun Q => IsRainbow colour (cliqueEdges r Q)

theorem mem_rainbowCliqueFamily (colour : I → Hypergraph V r) (Q : Block V q) :
    Q ∈ rainbowCliqueFamily colour q ↔ IsRainbow colour (cliqueEdges r Q) := by
  simp only [rainbowCliqueFamily, mem_filter, mem_univ, true_and]

omit [Fintype V] in
theorem IsRainbowAvoiding.fill_root {colour : I → Hypergraph V r}
    (H R : Hypergraph V r) (e : Block V r) {B : Finset I}
    (hnew : IsRainbowAvoiding colour (H \ R) B) (c : R.erase e ↪ I)
    (hc : ∀ f : R.erase e, f.val ∈ colour (c f)) (hB : ∀ f : R.erase e, c f ∈ B) :
    IsRainbow colour (H.erase e) := by
  apply (hnew.union_left c hc hB).mono
  intro f hf
  obtain ⟨hne, hfH⟩ := mem_erase.mp hf
  by_cases hfR : f ∈ R
  · exact mem_union_left _ (mem_erase.mpr ⟨hne, hfR⟩)
  · exact mem_union_right _ (mem_sdiff.mpr ⟨hfH, hfR⟩)

theorem ExchangeSystem.rainbow_elimination_generated (S : ExchangeSystem V q r)
    {N : Block V q} (hN : N ∈ S.negative) (e : Block V r)
    (heP : e ∈ cliqueEdges r S.base) (heN : e ∈ cliqueEdges r N)
    (colour : I → Hypergraph V r) (hcol : IsRainbow colour (S.graph.erase e)) :
    GeneratedBy (rainbowCliqueFamily colour q)
      (indicator (cliqueEdges r S.base) - indicator (cliqueEdges r N)) := by
  apply (S.generatedBy_elimination hN).mono
  intro Q hQ
  apply (mem_rainbowCliqueFamily colour Q).mpr
  apply hcol.mono
  intro f hf
  exact mem_erase.mpr ⟨fun h => S.elimination_avoids_common hN heP heN hQ (h ▸ hf),
    S.elimination_clique_subset N hQ hf⟩

end Arxiv2411_18291
