import ErdosProblems.Erdos1123.FiniteProfiles
import Mathlib.Order.BooleanSubalgebra
import Mathlib.Topology.Algebra.GroupWithZero

/-! # Boolean algebras of matched pairs of sets -/

namespace Erdos1123

open Filter
open scoped Topology Classical

variable {α β : Type*}

/-- A Boolean algebra of pairs of sets with matching asymptotic mass profiles.
Such an algebra induces a partial isomorphism on the null quotients. -/
structure Coupling (W : WeightSequence α) (V : WeightSequence β) where
  algebra : BooleanSubalgebra (Set α × Set β)
  matching : ∀ p ∈ algebra, Tendsto (fun n => W.mass p.1 n - V.mass p.2 n) atTop (𝓝 0)

/-- The simultaneous membership pattern in a finite family of sets. -/
noncomputable def jointLabel {ι : Type*} (a : ι → Set α) (x : α) : ι → Bool :=
  fun i => decide (x ∈ a i)

namespace Coupling

variable {W : WeightSequence α} {V : WeightSequence β} (C : Coupling W V)

theorem pattern_matching {ι : Type*} [Fintype ι] (p : ι → C.algebra) (σ : ι → Bool) :
    Tendsto (fun n =>
      W.profile (jointLabel (fun i => (p i).val.1)) n σ -
      V.profile (jointLabel (fun i => (p i).val.2)) n σ) atTop (𝓝 0) := by
  let q : Set α × Set β := ⨅ i, if σ i then (p i).val else (p i).valᶜ
  have hq : q ∈ C.algebra := by
    apply C.algebra.iInf_mem
    intro i
    split_ifs
    · exact (p i).property
    · exact C.algebra.compl_mem (p i).property
  have hfst : q.1 = {x | jointLabel (fun i => (p i).val.1) x = σ} := by
    ext x
    simp only [q, Prod.fst_iInf, Set.iInf_eq_iInter, Set.mem_iInter,
      Set.mem_ofPred_eq, funext_iff, jointLabel]
    apply forall_congr'
    intro i
    cases σ i <;> simp
  have hsnd : q.2 = {x | jointLabel (fun i => (p i).val.2) x = σ} := by
    ext x
    simp only [q, Prod.snd_iInf, Set.iInf_eq_iInter, Set.mem_iInter,
      Set.mem_ofPred_eq, funext_iff, jointLabel]
    apply forall_congr'
    intro i
    cases σ i <;> simp
  simpa only [hfst, hsnd, WeightSequence.profile] using C.matching q hq

/-- Every finite partition generated by a coupling has matching mass distributions. -/
theorem profileDistance_tendsto {ι : Type*} [Fintype ι] [DecidableEq ι] (p : ι → C.algebra) :
    Tendsto (W.profileDistance V
      (jointLabel (fun i => (p i).val.1)) (jointLabel (fun i => (p i).val.2)))
      atTop (𝓝 0) := by
  have h (σ : ι → Bool) := (C.pattern_matching p σ).abs
  change Tendsto (fun n => ∑ σ, |W.profile (jointLabel (fun i => (p i).val.1)) n σ -
    V.profile (jointLabel (fun i => (p i).val.2)) n σ|) atTop (𝓝 0)
  simpa only [abs_zero, Finset.sum_const_zero]
    using tendsto_finsetSum Finset.univ (fun σ _ => h σ)

end Coupling
end Erdos1123
