/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.PZ.Intersection.SelectedFullRank
import ErdosProblems.Erdos186.PZ.Intersection.SideTarget
import ErdosProblems.Erdos186.PZ.Intersection.RankCastGAP

/-!
# Quantitative inversion in the displayed steps of a square GAP

For the residual-absorption step one must return from ambient coordinates to
the *actual* displayed coefficients of the selected CFP progression.  An
adapted basis of the generated lattice is not sufficient for this purpose.

This file isolates the exact algebraic bridge.  Membership in the generated
step lattice supplies integral displayed coefficients.  Nonsingularity makes
them unique and the adjugate identity bounds them.  If the resulting explicit
adjugate bound fits inside the centered coefficient radii of a dilate, the
ambient lattice point belongs to that dilate.
-/

namespace Erdos186.PZ.Intersection

open scoped BigOperators

noncomputable section

set_option autoImplicit false

/-- Every point of the subgroup generated by a finite square step family is
an integral linear combination of those displayed steps. -/
theorem exists_stepCoefficients_of_mem_stepLattice {d : ℕ}
    (P : GAP d d) {x : LatticePoint d} (hx : x ∈ stepLattice P) :
    ∃ a : Fin d → ℤ, x = ∑ i, a i • P.steps i := by
  refine AddSubgroup.closure_induction
    (p := fun y _ ↦ ∃ a : Fin d → ℤ, y = ∑ i, a i • P.steps i)
    ?_ ?_ ?_ ?_ hx
  · rintro y ⟨i, rfl⟩
    refine ⟨Pi.single i 1, ?_⟩
    funext j
    rw [Finset.sum_eq_single i]
    · simp
    · intro k _hk hki
      simp [hki]
    · simp
  · exact ⟨0, by simp⟩
  · rintro y z _hy _hz ⟨a, rfl⟩ ⟨b, rfl⟩
    refine ⟨a + b, ?_⟩
    simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
  · rintro y _hy ⟨a, rfl⟩
    refine ⟨-a, ?_⟩
    simp

/-- Cramer's rule in row-vector form for the displayed coefficients. -/
theorem det_mul_stepCoefficient_eq_sum_adjugate {d : ℕ}
    (P : GAP d d) {x : LatticePoint d} (a : Fin d → ℤ)
    (hx : x = ∑ i, a i • P.steps i) (i : Fin d) :
    (stepMatrix P).det * a i =
      ∑ j, x j * (stepMatrix P).adjugate j i := by
  let M := stepMatrix P
  have hvec : Matrix.vecMul a M = x := by
    funext j
    change (∑ k, a k * P.steps k j) = x j
    rw [hx]
    simp [Finset.sum_apply]
  have hi : Matrix.vecMul a (M * M.adjugate) i =
      Matrix.vecMul x M.adjugate i := by
    rw [← Matrix.vecMul_vecMul, hvec]
  rw [Matrix.mul_adjugate] at hi
  simpa [Matrix.vecMul, dotProduct, Matrix.one_apply, M, mul_comm] using hi

/-- A coefficient vector lying in the centered radii represents a point of
the corresponding dilate. -/
theorem mem_dilate_of_stepCoefficients_le {d margin : ℕ}
    (P : GAP d d) {radii : Fin d → ℕ} (hP : P.Centered radii)
    {x : LatticePoint d} (a : Fin d → ℤ)
    (hx : x = ∑ i, a i • P.steps i)
    (ha : ∀ i, |a i| ≤ (margin * radii i : ℕ)) :
    x ∈ (P.dilate margin).carrier := by
  let hPd := hP.dilate margin
  let n : (P.dilate margin).Coord := fun i ↦
    ⟨(a i + (margin * radii i : ℕ)).toNat, by
      have hai := (abs_le.mp (ha i))
      have hnonneg : 0 ≤ a i + (margin * radii i : ℕ) := by omega
      have hwidth := hPd.width_eq i
      change (a i + (margin * radii i : ℕ)).toNat <
        (P.dilate margin).widths i
      rw [hwidth]
      have hto := Int.toNat_of_nonneg hnonneg
      omega⟩
  apply GAP.mem_carrier_iff.mpr
  refine ⟨n, ?_⟩
  rw [hPd.coordPoint_eq, hx]
  funext j
  simp only [GAP.dilate_steps, Finset.sum_apply, Pi.smul_apply,
    smul_eq_mul]
  apply Finset.sum_congr rfl
  intro i _hi
  have hai := (abs_le.mp (ha i))
  have hnonneg : 0 ≤ a i + (margin * radii i : ℕ) := by omega
  change
    ((((a i + (margin * radii i : ℕ)).toNat : ℕ) : ℤ) -
        (margin * radii i : ℕ)) * P.steps i j =
      (a i • P.steps i) j
  rw [Int.toNat_of_nonneg hnonneg]
  simp

/-- The exact inverse-coordinate inequality needed for a bounded lattice
point to lie in a dilate of the original displayed progression.

The premise is deliberately numerical: it is the first quantity which the
Theorem 4 parameter hierarchy must dominate. -/
theorem mem_dilate_of_mem_stepLattice_of_adjugate_bound
    {d margin E : ℕ} (P : GAP d d) {radii : Fin d → ℕ}
    (hP : P.Centered radii) (hdet : (stepMatrix P).det ≠ 0)
    (hinverse : ∀ i,
      E * ∑ j, ((stepMatrix P).adjugate j i).natAbs ≤
        (stepMatrix P).det.natAbs * (margin * radii i))
    {x : LatticePoint d} (hxL : x ∈ stepLattice P)
    (hx : ∀ j, (x j).natAbs ≤ E) :
    x ∈ (P.dilate margin).carrier := by
  obtain ⟨a, ha⟩ := exists_stepCoefficients_of_mem_stepLattice P hxL
  apply mem_dilate_of_stepCoefficients_le P hP a ha
  intro i
  have hcramer := det_mul_stepCoefficient_eq_sum_adjugate P a ha i
  have habs :
      ((stepMatrix P).det * a i).natAbs ≤
        E * ∑ j, ((stepMatrix P).adjugate j i).natAbs := by
    rw [hcramer]
    calc
      (∑ j, x j * (stepMatrix P).adjugate j i).natAbs ≤
          ∑ j, (x j * (stepMatrix P).adjugate j i).natAbs :=
        Int.natAbs_sum_le _ _
      _ = ∑ j, (x j).natAbs *
          ((stepMatrix P).adjugate j i).natAbs := by
        apply Finset.sum_congr rfl
        intro j _hj
        rw [Int.natAbs_mul]
      _ ≤ ∑ j, E * ((stepMatrix P).adjugate j i).natAbs := by
        apply Finset.sum_le_sum
        intro j _hj
        exact Nat.mul_le_mul_right _ (hx j)
      _ = E * ∑ j, ((stepMatrix P).adjugate j i).natAbs := by
        rw [Finset.mul_sum]
  rw [Int.natAbs_mul] at habs
  have hdetpos : 0 < (stepMatrix P).det.natAbs := Int.natAbs_pos.mpr hdet
  have hnat : (a i).natAbs ≤ margin * radii i :=
    Nat.le_of_mul_le_mul_left (habs.trans (hinverse i)) hdetpos
  have hcast : ((a i).natAbs : ℤ) ≤ (margin * radii i : ℕ) := by
    exact_mod_cast hnat
  simpa using hcast

/-- Real-coordinate-box wrapper matching the error-box premise used by the
canonical side target. -/
theorem errorBox_subset_dilate_of_adjugate_bound
    {d margin E : ℕ} (P : GAP d d) {radii : Fin d → ℕ}
    (hP : P.Centered radii) (hdet : (stepMatrix P).det ≠ 0)
    (radius : ℝ) (hradius : radius ≤ E)
    (hinverse : ∀ i,
      E * ∑ j, ((stepMatrix P).adjugate j i).natAbs ≤
        (stepMatrix P).det.natAbs * (margin * radii i)) :
    ∀ e : LatticePoint d, e ∈ stepLattice P →
      (∀ j, |(e j : ℝ)| ≤ radius) →
      e ∈ (P.dilate margin).carrier := by
  intro e heL he
  apply mem_dilate_of_mem_stepLattice_of_adjugate_bound
    P hP hdet hinverse heL
  intro j
  have hj : |(e j : ℝ)| ≤ (E : ℝ) := (he j).trans hradius
  have hj' : (((e j).natAbs : ℕ) : ℝ) ≤ (E : ℝ) := by
    simpa only [Nat.cast_natAbs, Int.cast_abs] using hj
  exact_mod_cast hj'

theorem castGAPRank_dilate_carrier' {d r r' margin : ℕ}
    (P : GAP d r) (h : r = r') :
    ((castGAPRank P h).dilate margin).carrier =
      (P.dilate margin).carrier := by
  subst r'
  rfl

@[simp] theorem squareProgression_dilate_carrier
    {d : ℕ} {X : Finset (LatticePoint d)}
    (T : PZ.Reduction.SelectedCFP X) (hdim : T.dimension = d)
    (margin : ℕ) :
    ((selectedSquareProgression T hdim).dilate margin).carrier =
      (T.progression.dilate margin).carrier := by
  exact castGAPRank_dilate_carrier' T.progression hdim

/-- The real error-box conclusion transported from the square rank cast back
to the selected CFP progression. -/
theorem selected_errorBox_subset_dilate_of_adjugate_bound
    {d : ℕ} {X : Finset (LatticePoint d)}
    (T : PZ.Reduction.SelectedCFP X) (hdim : T.dimension = d)
    {radii : Fin d → ℕ}
    (hcentered : (selectedSquareProgression T hdim).Centered radii)
    (hdet : (stepMatrix (selectedSquareProgression T hdim)).det ≠ 0)
    (margin E : ℕ) (radius : ℝ) (hradius : radius ≤ E)
    (hinverse : ∀ i,
      E * ∑ j,
          ((stepMatrix (selectedSquareProgression T hdim)).adjugate j i).natAbs ≤
        (stepMatrix (selectedSquareProgression T hdim)).det.natAbs *
          (margin * radii i)) :
    ∀ e : LatticePoint d, e ∈ gapStepLattice T.progression →
      (∀ j, |(e j : ℝ)| ≤ radius) →
      e ∈ (T.progression.dilate margin).carrier := by
  intro e heL he
  have heL' : e ∈ stepLattice (selectedSquareProgression T hdim) := by
    rw [← gapStepLattice_squareProgression T hdim]
    exact heL
  have he' := errorBox_subset_dilate_of_adjugate_bound
    (selectedSquareProgression T hdim) hcentered hdet radius hradius
    hinverse e heL' he
  simpa only [squareProgression_dilate_carrier T hdim margin] using he'

/-- Enhanced-witness form consumed by `CanonicalPostCFPAssembly`. -/
theorem enhancedWitness_errorBox_subset_dilate_of_adjugate_bound
    {d s D k loss : ℕ} {X : Finset (LatticePoint d)}
    (W : CFP.EnhancedCFPWitness X s D k loss) (hrank : W.rank = d)
    {radii : Fin d → ℕ}
    (hcentered : (rankCastGAP W.progression hrank).Centered radii)
    (hdet : (stepMatrix (rankCastGAP W.progression hrank)).det ≠ 0)
    (margin E : ℕ) (radius : ℝ) (hradius : radius ≤ E)
    (hinverse : ∀ i,
      E * ∑ j,
          ((stepMatrix (rankCastGAP W.progression hrank)).adjugate j i).natAbs ≤
        (stepMatrix (rankCastGAP W.progression hrank)).det.natAbs *
          (margin * radii i)) :
    ∀ e : LatticePoint d, e ∈ gapStepLattice W.progression →
      (∀ j, |(e j : ℝ)| ≤ radius) →
      e ∈ (W.progression.dilate margin).carrier := by
  intro e heL he
  have heL' : e ∈ stepLattice (rankCastGAP W.progression hrank) := by
    rw [rankCastGAP_stepLattice W.progression hrank]
    exact heL
  have he' := errorBox_subset_dilate_of_adjugate_bound
    (rankCastGAP W.progression hrank) hcentered hdet radius hradius
    hinverse e heL' he
  simpa only [rankCastGAP_dilate_carrier W.progression hrank] using he'

end

end Erdos186.PZ.Intersection
