/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import Mathlib

/-!
# Centered zonotopes in the Pham--Zakharov intersection argument

This file isolates the elementary translation step used in Lemma 14 of
Pham--Zakharov.  The generators are integer vectors, while both zonotopes
live in the corresponding real vector space.  The ordinary zonotope has
coefficients in `[0, 1]`; the centered zonotope with radii `Delta` has
coefficients in `[-Delta x, Delta x]`.

If `0 <= q x <= 1 / 2`, translating the centered zonotope with radius `q x`
by `sum_x q x * x` puts it inside the ordinary zonotope: the new coefficient
is simply `q x + t x`.  We also record versions with smaller radii and with
larger finite sets of generators.
-/

namespace Erdos186.PZ.Intersection

open scoped BigOperators

noncomputable section

set_option autoImplicit false

/-- Regard an integer vector as a real vector, coordinate by coordinate. -/
def realVector {d : ℕ} (x : Fin d → ℤ) : Fin d → ℝ :=
  fun i ↦ (x i : ℝ)

/-- The ordinary zonotope generated by `A`: all linear combinations of the
generators with coefficients in `[0, 1]`. -/
def zonotope {d : ℕ} (A : Finset (Fin d → ℤ)) : Set (Fin d → ℝ) :=
  {y | ∃ c : (Fin d → ℤ) → ℝ,
    (∀ x ∈ A, 0 ≤ c x ∧ c x ≤ 1) ∧
      ∀ i, y i = ∑ x ∈ A, c x * realVector x i}

/-- The weighted center associated with coefficients `q`. -/
def zonotopeCenter {d : ℕ} (A : Finset (Fin d → ℤ))
    (q : (Fin d → ℤ) → ℝ) : Fin d → ℝ :=
  fun i ↦ ∑ x ∈ A, q x * realVector x i

/-- The centered zonotope with generator-dependent radii `Delta`. -/
def centeredZonotope {d : ℕ} (A : Finset (Fin d → ℤ))
    (Delta : (Fin d → ℤ) → ℝ) : Set (Fin d → ℝ) :=
  {y | ∃ t : (Fin d → ℤ) → ℝ,
    (∀ x ∈ A, |t x| ≤ Delta x) ∧
      ∀ i, y i = ∑ x ∈ A, t x * realVector x i}

@[simp]
theorem mem_zonotope_iff {d : ℕ} {A : Finset (Fin d → ℤ)}
    {y : Fin d → ℝ} :
    y ∈ zonotope A ↔
      ∃ c : (Fin d → ℤ) → ℝ,
        (∀ x ∈ A, 0 ≤ c x ∧ c x ≤ 1) ∧
          ∀ i, y i = ∑ x ∈ A, c x * realVector x i := by
  rfl

@[simp]
theorem mem_centeredZonotope_iff {d : ℕ} {A : Finset (Fin d → ℤ)}
    {Delta : (Fin d → ℤ) → ℝ} {y : Fin d → ℝ} :
    y ∈ centeredZonotope A Delta ↔
      ∃ t : (Fin d → ℤ) → ℝ,
        (∀ x ∈ A, |t x| ≤ Delta x) ∧
          ∀ i, y i = ∑ x ∈ A, t x * realVector x i := by
  rfl

/-- The origin belongs to a centered zonotope with nonnegative radii. -/
theorem zero_mem_centeredZonotope {d : ℕ} {A : Finset (Fin d → ℤ)}
    {Delta : (Fin d → ℤ) → ℝ} (hDelta : ∀ x ∈ A, 0 ≤ Delta x) :
    (0 : Fin d → ℝ) ∈ centeredZonotope A Delta := by
  refine ⟨fun _ ↦ 0, ?_, ?_⟩
  · intro x hx
    simpa using hDelta x hx
  · intro i
    simp

/-- Increasing every radius enlarges a centered zonotope. -/
theorem centeredZonotope_mono_radius {d : ℕ} {A : Finset (Fin d → ℤ)}
    {Delta Delta' : (Fin d → ℤ) → ℝ}
    (hDelta : ∀ x ∈ A, Delta x ≤ Delta' x) :
    centeredZonotope A Delta ⊆ centeredZonotope A Delta' := by
  rintro y ⟨t, ht, hy⟩
  exact ⟨t, fun x hx ↦ (ht x hx).trans (hDelta x hx), hy⟩

/-- Adding generators enlarges the ordinary zonotope.  Coefficients of the
new generators are set to zero. -/
theorem zonotope_mono {d : ℕ} {A B : Finset (Fin d → ℤ)}
    (hAB : A ⊆ B) : zonotope A ⊆ zonotope B := by
  classical
  rintro y ⟨c, hc, hy⟩
  let c' : (Fin d → ℤ) → ℝ := fun x ↦ if x ∈ A then c x else 0
  refine ⟨c', ?_, ?_⟩
  · intro x hxB
    by_cases hxA : x ∈ A
    · simpa [c', hxA] using hc x hxA
    · simp [c', hxA]
  · intro i
    rw [hy i]
    calc
      (∑ x ∈ A, c x * realVector x i) =
          ∑ x ∈ A, c' x * realVector x i := by
        apply Finset.sum_congr rfl
        intro x hxA
        simp [c', hxA]
      _ = ∑ x ∈ B, c' x * realVector x i := by
        apply Finset.sum_subset hAB
        intro x hxB hxA
        simp [c', hxA]

/-- Adding generators with nonnegative radii enlarges a centered zonotope.
Coefficients of the new generators are set to zero. -/
theorem centeredZonotope_mono {d : ℕ} {A B : Finset (Fin d → ℤ)}
    {Delta : (Fin d → ℤ) → ℝ} (hAB : A ⊆ B)
    (hDelta : ∀ x ∈ B, 0 ≤ Delta x) :
    centeredZonotope A Delta ⊆ centeredZonotope B Delta := by
  classical
  rintro y ⟨t, ht, hy⟩
  let t' : (Fin d → ℤ) → ℝ := fun x ↦ if x ∈ A then t x else 0
  refine ⟨t', ?_, ?_⟩
  · intro x hxB
    by_cases hxA : x ∈ A
    · simpa [t', hxA] using ht x hxA
    · simpa [t', hxA] using hDelta x hxB
  · intro i
    rw [hy i]
    calc
      (∑ x ∈ A, t x * realVector x i) =
          ∑ x ∈ A, t' x * realVector x i := by
        apply Finset.sum_congr rfl
        intro x hxA
        simp [t', hxA]
      _ = ∑ x ∈ B, t' x * realVector x i := by
        apply Finset.sum_subset hAB
        intro x hxB hxA
        simp [t', hxA]

/-- Translation lemma with radii bounded by the center coefficients. -/
theorem center_add_centeredZonotope_subset {d : ℕ}
    (A : Finset (Fin d → ℤ)) (q Delta : (Fin d → ℤ) → ℝ)
    (hq : ∀ x ∈ A, 0 ≤ q x ∧ q x ≤ (1 : ℝ) / 2)
    (hDelta : ∀ x ∈ A, Delta x ≤ q x) :
    (fun z ↦ zonotopeCenter A q + z) '' centeredZonotope A Delta ⊆
      zonotope A := by
  rintro y ⟨z, ⟨t, ht, hz⟩, rfl⟩
  refine ⟨fun x ↦ q x + t x, ?_, ?_⟩
  · intro x hx
    have hq' := hq x hx
    have ht' := abs_le.mp (ht x hx)
    have hDelta' := hDelta x hx
    constructor <;> linarith
  · intro i
    change zonotopeCenter A q i + z i =
      ∑ x ∈ A, (q x + t x) * realVector x i
    rw [hz i]
    change (∑ x ∈ A, q x * realVector x i) +
        (∑ x ∈ A, t x * realVector x i) =
      ∑ x ∈ A, (q x + t x) * realVector x i
    rw [← Finset.sum_add_distrib]
    apply Finset.sum_congr rfl
    intro x hx
    ring

/-- Elementary centered-zonotope inclusion underlying Pham--Zakharov,
Lemma 14.  A deviation whose `x`-coefficient lies in `[-q x, q x]`, added
to the center with coefficient `q x`, has all coefficients in `[0, 1]`. -/
theorem lemma14_center_add_centeredZonotope_subset {d : ℕ}
    (A : Finset (Fin d → ℤ)) (q : (Fin d → ℤ) → ℝ)
    (hq : ∀ x ∈ A, 0 ≤ q x ∧ q x ≤ (1 : ℝ) / 2) :
    (fun z ↦ zonotopeCenter A q + z) '' centeredZonotope A q ⊆
      zonotope A := by
  exact center_add_centeredZonotope_subset A q q hq fun _ _ ↦ le_rfl

/-- Pointwise formulation of the same inclusion, convenient when a thickness
lemma supplies one particular centered deviation. -/
theorem add_mem_zonotope_of_mem_centeredZonotope {d : ℕ}
    (A : Finset (Fin d → ℤ)) (q : (Fin d → ℤ) → ℝ)
    (hq : ∀ x ∈ A, 0 ≤ q x ∧ q x ≤ (1 : ℝ) / 2)
    {z : Fin d → ℝ} (hz : z ∈ centeredZonotope A q) :
    zonotopeCenter A q + z ∈ zonotope A := by
  exact lemma14_center_add_centeredZonotope_subset A q hq ⟨z, hz, rfl⟩

/-- Subtraction form of the elementary translation lemma.  This is useful
when a geometric thickness theorem is stated as a neighbourhood of the
origin while the target zonotope is centred at `zonotopeCenter A q`. -/
theorem mem_zonotope_of_sub_center_mem_centeredZonotope {d : ℕ}
    (A : Finset (Fin d → ℤ)) (q : (Fin d → ℤ) → ℝ)
    (hq : ∀ x ∈ A, 0 ≤ q x ∧ q x ≤ (1 : ℝ) / 2)
    {y : Fin d → ℝ}
    (hy : y - zonotopeCenter A q ∈ centeredZonotope A q) :
    y ∈ zonotope A := by
  have hadd := add_mem_zonotope_of_mem_centeredZonotope A q hq hy
  simpa [add_sub_cancel] using hadd

/-- A centred-zonotope cube estimate implies the corresponding translated
cube lies in the ordinary zonotope.  The hard content of PZ Lemma 14 is
precisely the hypothesis `hthick`; the conclusion packages its elementary
translation-and-coefficient consequence without hiding that input. -/
theorem mem_zonotope_of_centeredZonotope_cube {d : ℕ}
    (A : Finset (Fin d → ℤ)) (q : (Fin d → ℤ) → ℝ) (radius : ℝ)
    (hq : ∀ x ∈ A, 0 ≤ q x ∧ q x ≤ (1 : ℝ) / 2)
    (hthick : ∀ z : Fin d → ℝ, (∀ i, |z i| ≤ radius) →
      z ∈ centeredZonotope A q)
    {y : Fin d → ℝ}
    (hy : ∀ i, |y i - zonotopeCenter A q i| ≤ radius) :
    y ∈ zonotope A := by
  apply mem_zonotope_of_sub_center_mem_centeredZonotope A q hq
  apply hthick
  intro i
  simpa using hy i

end

end Erdos186.PZ.Intersection
