/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.Witness
import ErdosProblems.Erdos186.LatticeIntersection

/-!
# The full-rank datum missing from a finite proper GAP

A proper rank-`d` GAP need not have a full-rank step lattice in `Z^d`:
properness only tests relations inside the finite coefficient box.  This file
records the natural step lattice and gives a concrete rank-two, ambient-
dimension-two counterexample.  Consequently the full-rank hypotheses in the
covolume intersection step cannot be derived from the current
`EnhancedCFPWitness` progression fields alone.
-/

namespace Erdos186.PZ.Intersection

open Erdos186.LatticeIntersection

noncomputable section

set_option autoImplicit false

/-- The additive lattice generated by the displayed steps of a GAP. -/
def gapStepLattice {d r : ℕ} (P : GAP d r) : Sublattice d :=
  AddSubgroup.closure (Set.range P.steps)

/-- A symmetric proper rank-two GAP in `Z^2` whose two steps are collinear.
The coefficient width is too small to see the relation `3 * step₀ = step₁`.
-/
def collinearProperGAP : GAP 2 2 where
  offset := fun j ↦ if j = 0 then -4 else 0
  steps := fun i j ↦ if j = 0 then (2 * (i : ℕ) + 1 : ℕ) else 0
  widths := fun _ ↦ 3
  width_pos := by intro i; omega

theorem collinearProperGAP_centered :
    collinearProperGAP.Centered (fun _ ↦ 1) := by
  constructor
  · funext i
    simp [collinearProperGAP]
  · funext j
    fin_cases j <;> norm_num [collinearProperGAP]

theorem collinearProperGAP_symmetric : collinearProperGAP.Symmetric :=
  ⟨fun _ ↦ 1, collinearProperGAP_centered⟩

theorem collinearProperGAP_nondegenerate :
    collinearProperGAP.Nondegenerate := by
  intro i
  simp [collinearProperGAP]

theorem collinearProperGAP_proper : collinearProperGAP.Proper := by
  intro n m hnm
  have hcoord := congrFun hnm 0
  have hn0lt : (n 0 : ℕ) < 3 := by
    simpa [collinearProperGAP] using (n 0).isLt
  have hn1lt : (n 1 : ℕ) < 3 := by
    simpa [collinearProperGAP] using (n 1).isLt
  have hm0lt : (m 0 : ℕ) < 3 := by
    simpa [collinearProperGAP] using (m 0).isLt
  have hm1lt : (m 1 : ℕ) < 3 := by
    simpa [collinearProperGAP] using (m 1).isLt
  have heq : (n 0 : ℤ) + (n 1 : ℤ) * 3 =
      (m 0 : ℤ) + (m 1 : ℤ) * 3 := by
    simpa [collinearProperGAP, GAP.coordPoint] using hcoord
  have h1 : n 1 = m 1 := by
    apply Fin.ext
    omega
  have h0 : n 0 = m 0 := by
    apply Fin.ext
    omega
  funext i
  fin_cases i
  · exact h0
  · exact h1

/-- Every generated step has second coordinate zero. -/
theorem gapStepLattice_collinear_le :
    gapStepLattice collinearProperGAP ≤
      (Pi.evalAddMonoidHom (fun _ : Fin 2 ↦ ℤ) 1).ker := by
  apply (AddSubgroup.closure_le _).mpr
  rintro x ⟨i, rfl⟩
  simp [collinearProperGAP]

/-- Vertical vectors give infinitely many distinct cosets of the step
lattice. -/
theorem collinearProperGAP_stepLattice_infinite_quotient :
    Infinite (LatticePoint 2 ⧸ gapStepLattice collinearProperGAP) := by
  let vertical : ℤ → LatticePoint 2 :=
    fun z i ↦ if i = 1 then z else 0
  let f : ℤ → LatticePoint 2 ⧸ gapStepLattice collinearProperGAP :=
    fun z ↦ QuotientAddGroup.mk' (gapStepLattice collinearProperGAP) (vertical z)
  have hf : Function.Injective f := by
    intro x y hxy
    rw [QuotientAddGroup.mk'_eq_mk'] at hxy
    obtain ⟨z, hzL, hz⟩ := hxy
    have hz0 : z 1 = 0 := gapStepLattice_collinear_le hzL
    have hcoord := congrFun hz 1
    simp [vertical, hz0] at hcoord
    exact hcoord
  exact Infinite.of_injective f hf

/-- Thus displayed rank = ambient dimension, finite properness, symmetry,
and nondegeneracy still do not imply the full-rank lattice input required by
the covolume argument. -/
theorem not_fullRank_gapStepLattice_collinearProperGAP :
    ¬ FullRank (gapStepLattice collinearProperGAP) := by
  intro hfull
  apply hfull
  change (gapStepLattice collinearProperGAP).index = 0
  rw [AddSubgroup.index_eq_zero_iff_infinite]
  exact collinearProperGAP_stepLattice_infinite_quotient

/-! ## The obstruction occurs for an actual enhanced CFP witness -/

/-- Embed one integer on the horizontal axis of `Z^2`. -/
def horizontalPoint (z : ℤ) : LatticePoint 2 :=
  fun j ↦ if j = 0 then z else 0

/-- Four horizontal points whose subset sums cover the translated carrier of
`collinearProperGAP`. -/
def collinearWitnessSet : Finset (LatticePoint 2) :=
  {horizontalPoint 1, horizontalPoint 2,
    horizontalPoint 3, horizontalPoint 4}

/-- All fields of `EnhancedCFPWitness` can hold while the progression step
lattice has infinite index. -/
def collinearEnhancedCFPWitness :
    CFP.EnhancedCFPWitness collinearWitnessSet 4 2 1 0 where
  core := collinearWitnessSet
  reserved := collinearWitnessSet
  rank := 2
  rank_le := le_rfl
  progression := collinearProperGAP
  core_subset := Finset.Subset.rfl
  reserved_subset_core := Finset.Subset.rfl
  core_large := by simp
  reserved_small := by decide
  core_zero_subset := by decide
  homogeneous := collinearProperGAP_centered.homogeneous
  translatePoint := horizontalPoint 4
  covered := by decide
  dilate_proper := by
    simpa [GAP.dilate, collinearProperGAP] using collinearProperGAP_proper
  k_pos := by omega
  scaleNum := 1
  scaleDen := 4
  scaleNum_pos := by omega
  scaleDen_pos := by omega
  scale_lower := by omega
  scale_upper := by omega
  progression_proper := collinearProperGAP_proper
  progression_symmetric := collinearProperGAP_symmetric
  progression_nondegenerate := collinearProperGAP_nondegenerate
  covered_translate_homogeneous := by
    refine ⟨0, ?_⟩
    funext j
    fin_cases j <;>
      norm_num [horizontalPoint, collinearProperGAP, GAP.dilate]

/-- Concrete impossibility result: no theorem can extract full rank merely
from an arbitrary current `EnhancedCFPWitness`. -/
theorem enhancedCFPWitness_does_not_force_fullRank :
    ¬ FullRank
      (gapStepLattice collinearEnhancedCFPWitness.progression) := by
  exact not_fullRank_gapStepLattice_collinearProperGAP

end

end Erdos186.PZ.Intersection
