/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.AdaptedHNF
import ErdosProblems.Erdos186.CFP.SymmetricGAP
import ErdosProblems.Erdos186.LatticeIntersection
import ErdosProblems.Erdos186.PZ.Intersection.CovolumeCovering
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv

/-!
# Full-rank lattices generated by progression steps

This file packages the lattice part of Pham--Zakharov's intersection
argument.  A nonsingular square step matrix generates a sublattice
containing the rectangular lattice with period `|det|`.  Consequently its
index is nonzero and is at most `|det|^d`, and two such step lattices have
the common covering-radius bound used in Theorem 4.
-/

namespace Erdos186.PZ.Intersection

open scoped BigOperators
open Erdos186.LatticeIntersection
open Erdos186.CFP.LatticeBasis

noncomputable section

set_option autoImplicit false

/-- The square matrix whose rows are the displayed steps of a rank-`d` GAP
in `ℤ^d`. -/
def stepMatrix {d : ℕ} (P : GAP d d) : Matrix (Fin d) (Fin d) ℤ :=
  fun i j ↦ P.steps i j

/-- A singular square step presentation has a nontrivial rational relation
among its displayed step vectors. -/
theorem exists_nonzero_rational_step_relation_of_det_eq_zero {d : ℕ}
    (P : GAP d d) (hdet : (stepMatrix P).det = 0) :
    ∃ a : Fin d → ℚ, a ≠ 0 ∧
      ∀ j, (∑ i, a i * (P.steps i j : ℚ)) = 0 := by
  let M : Matrix (Fin d) (Fin d) ℚ :=
    (stepMatrix P).map (Int.castRingHom ℚ)
  have hdetM : M.det = 0 := by
    rw [show M.det = ((stepMatrix P).det : ℚ) by
      exact ((Int.castRingHom ℚ).map_det (stepMatrix P)).symm]
    simp [hdet]
  have hdetMT : M.transpose.det = 0 := by
    simpa using hdetM
  obtain ⟨a, ha, hmul⟩ :=
    (Matrix.exists_mulVec_eq_zero_iff (M := M.transpose)).2 hdetMT
  refine ⟨a, ha, ?_⟩
  intro j
  have hj := congrFun hmul j
  simpa [M, Matrix.mulVec, stepMatrix, dotProduct, mul_comm] using hj

/-- Singular steps also furnish a nonzero rational functional on the
ambient lattice which annihilates every displayed step.  This right-kernel
form is the one used in the quantitative codimension-one counting argument.
-/
theorem exists_nonzero_rational_ambient_functional_of_det_eq_zero {d : ℕ}
    (P : GAP d d) (hdet : (stepMatrix P).det = 0) :
    ∃ b : Fin d → ℚ, b ≠ 0 ∧
      ∀ i, (∑ j, (P.steps i j : ℚ) * b j) = 0 := by
  let M : Matrix (Fin d) (Fin d) ℚ :=
    (stepMatrix P).map (Int.castRingHom ℚ)
  have hdetM : M.det = 0 := by
    rw [show M.det = ((stepMatrix P).det : ℚ) by
      exact ((Int.castRingHom ℚ).map_det (stepMatrix P)).symm]
    simp [hdet]
  obtain ⟨b, hb, hmul⟩ :=
    (Matrix.exists_mulVec_eq_zero_iff (M := M)).2 hdetM
  refine ⟨b, hb, ?_⟩
  intro i
  have hi := congrFun hmul i
  simpa [M, Matrix.mulVec, stepMatrix, dotProduct] using hi

/-- The rational additive functional with coefficient vector `b`. -/
def rationalAmbientFunctional {d : ℕ} (b : Fin d → ℚ) :
    LatticePoint d →+ ℚ where
  toFun x := ∑ j, (x j : ℚ) * b j
  map_zero' := by simp
  map_add' x y := by
    simp only [Pi.add_apply, Int.cast_add, add_mul, Finset.sum_add_distrib]

/-- The additive subgroup generated by the displayed progression steps. -/
def stepLattice {d : ℕ} (P : GAP d d) :
    Erdos186.LatticeIntersection.Sublattice d :=
  AddSubgroup.closure (Set.range P.steps)

/-- If a rational functional annihilates every displayed step, it
annihilates the entire generated step lattice. -/
theorem stepLattice_le_ker_rationalAmbientFunctional {d : ℕ}
    (P : GAP d d) (b : Fin d → ℚ)
    (hb : ∀ i, (∑ j, (P.steps i j : ℚ) * b j) = 0) :
    stepLattice P ≤ (rationalAmbientFunctional b).ker := by
  apply (AddSubgroup.closure_le _).mpr
  rintro x ⟨i, rfl⟩
  exact hb i

/-- Delete one coordinate by replacing it with zero. -/
def zeroCoordinate {d : ℕ} (j : Fin d) (x : LatticePoint d) :
    LatticePoint d :=
  fun i ↦ if i = j then 0 else x i

/-- On the kernel of a functional whose `j`-th coefficient is nonzero,
all remaining coordinates determine the deleted coordinate. -/
theorem zeroCoordinate_injOn_functional_ker {d : ℕ}
    (b : Fin d → ℚ) (j : Fin d) (hb : b j ≠ 0) :
    Set.InjOn (zeroCoordinate j) (rationalAmbientFunctional b).ker := by
  intro x hx y hy hproject
  have hother : ∀ i, i ≠ j → x i = y i := by
    intro i hij
    have hi := congrFun hproject i
    simpa [zeroCoordinate, hij] using hi
  have hsub : x - y ∈ (rationalAmbientFunctional b).ker :=
    AddSubgroup.sub_mem _ hx hy
  change (∑ i, (((x - y) i : ℤ) : ℚ) * b i) = 0 at hsub
  have hsingle :
      (∑ i, (((x - y) i : ℤ) : ℚ) * b i) =
        (((x - y) j : ℤ) : ℚ) * b j := by
    apply Finset.sum_eq_single j
    · intro i _hi hij
      simp [Pi.sub_apply, hother i hij]
    · simp
  rw [hsingle] at hsub
  have hjcast : (((x - y) j : ℤ) : ℚ) = 0 :=
    (mul_eq_zero.mp hsub).resolve_right hb
  have hj : x j = y j := by
    norm_cast at hjcast
    simpa [Pi.sub_apply] using sub_eq_zero.mp hjcast
  funext i
  by_cases hij : i = j
  · simpa [hij] using hj
  · exact hother i hij

theorem step_mem_stepLattice {d : ℕ} (P : GAP d d) (i : Fin d) :
    P.steps i ∈ stepLattice P := by
  exact AddSubgroup.subset_closure ⟨i, rfl⟩

/-- Any sublattice containing a positive rectangular lattice is full rank. -/
theorem fullRank_of_rectangular_le {d : ℕ} {v : Fin d → ℕ}
    (hv : ∀ i, 0 < v i)
    (Gamma : Erdos186.LatticeIntersection.Sublattice d)
    (hrect : rectangularSubgroup v ≤ Gamma) : FullRank Gamma := by
  intro hzero
  have heq := rectangular_relIndex_mul_index v Gamma hrect
  have hindex : Gamma.index = 0 := by
    simpa [FullRank, covolume] using hzero
  rw [hindex, mul_zero] at heq
  have hprod : 0 < ∏ i, v i := Finset.prod_pos fun i _ ↦ hv i
  omega

/-- The corresponding covolume is at most the rectangular period product. -/
theorem covolume_le_prod_of_rectangular_le {d : ℕ} {v : Fin d → ℕ}
    (hv : ∀ i, 0 < v i)
    (Gamma : Erdos186.LatticeIntersection.Sublattice d)
    (hrect : rectangularSubgroup v ≤ Gamma) :
    covolume Gamma ≤ ∏ i, v i := by
  have heq := rectangular_relIndex_mul_index v Gamma hrect
  have hprod : 0 < ∏ i, v i := Finset.prod_pos fun i _ ↦ hv i
  apply Nat.le_of_dvd hprod
  refine ⟨(rectangularSubgroup v).relIndex Gamma, ?_⟩
  simpa [covolume, Nat.mul_comm] using heq.symm

/-- A finite sum of integer multiples of displayed steps lies in the step
lattice. -/
theorem sum_steps_mem_stepLattice {d : ℕ} (P : GAP d d)
    (a : Fin d → ℤ) :
    (∑ i, a i • P.steps i) ∈ stepLattice P := by
  exact AddSubgroup.sum_mem _ fun i _ ↦
    AddSubgroup.zsmul_mem _ (step_mem_stepLattice P i) (a i)

/-- Symmetry writes the offset as an integer combination of the steps. -/
theorem offset_mem_stepLattice_of_symmetric {d : ℕ} (P : GAP d d)
    (hP : P.Symmetric) : P.offset ∈ stepLattice P := by
  obtain ⟨radii, hcenter⟩ := hP
  have hsum := sum_steps_mem_stepLattice P
    (fun i ↦ (radii i : ℤ))
  have hneg := AddSubgroup.neg_mem (stepLattice P) hsum
  have hoffset := hcenter.offset_eq
  have heq : P.offset =
      -(∑ i, (radii i : ℤ) • P.steps i) := by
    funext j
    rw [hoffset]
    simp [Finset.sum_apply]
  rw [heq]
  exact hneg

/-- Every point of every dilate of a symmetric progression lies in the
lattice generated by its steps. -/
theorem dilate_carrier_subset_stepLattice_of_symmetric {d k : ℕ}
    (P : GAP d d) (hP : P.Symmetric) :
    ∀ ⦃x⦄, x ∈ (P.dilate k).carrier → x ∈ stepLattice P := by
  intro x hx
  obtain ⟨n, rfl⟩ := GAP.mem_carrier_iff.mp hx
  have hrepr : (P.dilate k).coordPoint n =
      (k : ℤ) • P.offset + ∑ i, (n i : ℤ) • P.steps i := by
    funext j
    simp [GAP.coordPoint, GAP.dilate, Finset.sum_apply]
  rw [hrepr]
  exact AddSubgroup.add_mem _
    (AddSubgroup.zsmul_mem _ (offset_mem_stepLattice_of_symmetric P hP) k)
    (sum_steps_mem_stepLattice P fun i ↦ (n i : ℤ))

/-- If the square step matrix is singular, every point of every symmetric
dilate lies in the kernel of one nonzero rational ambient functional. -/
theorem exists_nonzero_functional_vanishing_on_dilate_of_det_eq_zero
    {d k : ℕ} (P : GAP d d) (hP : P.Symmetric)
    (hdet : (stepMatrix P).det = 0) :
    ∃ b : Fin d → ℚ, b ≠ 0 ∧
      ∀ x ∈ (P.dilate k).carrier, rationalAmbientFunctional b x = 0 := by
  obtain ⟨b, hbne, hb⟩ :=
    exists_nonzero_rational_ambient_functional_of_det_eq_zero P hdet
  refine ⟨b, hbne, ?_⟩
  intro x hx
  exact stepLattice_le_ker_rationalAmbientFunctional P b hb
    (dilate_carrier_subset_stepLattice_of_symmetric P hP hx)

/-- The adjugate identity expresses `det(M)` times each standard basis vector
as an integer combination of the rows of `M`. -/
theorem det_smul_basis_eq_sum_steps {d : ℕ} (P : GAP d d) (j : Fin d) :
    (stepMatrix P).det • (Pi.single j 1 : LatticePoint d) =
      ∑ i, (stepMatrix P).adjugate j i • P.steps i := by
  funext k
  have h := congrArg (fun M : Matrix (Fin d) (Fin d) ℤ ↦ M j k)
    (Matrix.adjugate_mul (stepMatrix P))
  simpa [stepMatrix, Matrix.mul_apply, Matrix.one_apply, Pi.single_apply,
    eq_comm] using h.symm

/-- Linear independence of the displayed square family is exactly the
nonsingularity input needed by the lattice argument. -/
theorem det_ne_zero_of_linearIndependent_steps {d : ℕ} (P : GAP d d)
    (hsteps : LinearIndependent ℤ P.steps) :
    (stepMatrix P).det ≠ 0 := by
  apply Matrix.separatingLeft_iff_det_ne_zero.mp
  rw [Matrix.separatingLeft_iff_forall_vecMul_eq_zero]
  intro v hv
  rw [Matrix.vecMul_eq_sum] at hv
  change (∑ i, v i • P.steps i) = 0 at hv
  have hcoeff := (Fintype.linearIndependent_iff.mp hsteps) v hv
  funext i
  exact hcoeff i

/-- A nonsingular square step matrix makes the step lattice contain the
rectangular lattice of period `|det|`. -/
theorem rectangularSubgroup_det_le_stepLattice {d : ℕ} (P : GAP d d)
    (hdet : (stepMatrix P).det ≠ 0) :
    rectangularSubgroup (fun _ ↦ (stepMatrix P).det.natAbs) ≤
      stepLattice P := by
  intro x hx
  rw [mem_rectangularSubgroup_iff] at hx
  let q : ℤ := (stepMatrix P).det
  let a : Fin d → ℤ := fun j ↦ x j / q
  have hcoord : x = ∑ j, a j • (q • (Pi.single j 1 : LatticePoint d)) := by
    funext k
    have hdiv : q ∣ x k := by
      apply Int.natAbs_dvd_natAbs.mp
      exact Int.natCast_dvd.mp (hx k)
    obtain ⟨z, hz⟩ := hdiv
    have hak : a k = z := by
      dsimp only [a]
      rw [hz]
      exact Int.mul_ediv_cancel_left z hdet
    calc
      x k = q * z := hz
      _ = z * q := Int.mul_comm _ _
      _ = a k * q := by rw [hak]
      _ = (∑ j, a j • (q • (Pi.single j 1 : LatticePoint d))) k := by
        simp [Pi.single_apply]
  rw [hcoord]
  apply AddSubgroup.sum_mem
  intro j _
  apply AddSubgroup.zsmul_mem
  · rw [det_smul_basis_eq_sum_steps P j]
    exact sum_steps_mem_stepLattice P _

/-- Nonsingularity alone supplies full rank and the explicit determinant
power bound for the generated step lattice. -/
theorem stepLattice_fullRank_and_covolume_le {d : ℕ} (P : GAP d d)
    (hdet : (stepMatrix P).det ≠ 0) :
    FullRank (stepLattice P) ∧
      covolume (stepLattice P) ≤ (stepMatrix P).det.natAbs ^ d := by
  let v : Fin d → ℕ := fun _ ↦ (stepMatrix P).det.natAbs
  have hv : ∀ i, 0 < v i := by
    intro i
    exact Int.natAbs_pos.mpr hdet
  have hrect : rectangularSubgroup v ≤ stepLattice P :=
    rectangularSubgroup_det_le_stepLattice P hdet
  refine ⟨fullRank_of_rectangular_le hv _ hrect, ?_⟩
  simpa [v] using covolume_le_prod_of_rectangular_le hv _ hrect

/-- Linear-independent form of the preceding result. -/
theorem stepLattice_fullRank_and_covolume_le_of_linearIndependent
    {d : ℕ} (P : GAP d d) (hsteps : LinearIndependent ℤ P.steps) :
    FullRank (stepLattice P) ∧
      covolume (stepLattice P) ≤ (stepMatrix P).det.natAbs ^ d := by
  exact stepLattice_fullRank_and_covolume_le P
    (det_ne_zero_of_linearIndependent_steps P hsteps)

/-- Two nonsingular progression step lattices have the common covering
radius given by the product of determinant powers. -/
theorem stepLattices_commonCoveringRadius {d : ℕ} (P₁ P₂ : GAP d d)
    (hdet₁ : (stepMatrix P₁).det ≠ 0)
    (hdet₂ : (stepMatrix P₂).det ≠ 0) :
    HasCommonCoveringRadius
      (stepLattice P₁ : Set (LatticePoint d))
      (stepLattice P₂ : Set (LatticePoint d))
      ((stepMatrix P₁).det.natAbs ^ d *
        (stepMatrix P₂).det.natAbs ^ d) := by
  obtain ⟨hfull₁, hcov₁⟩ := stepLattice_fullRank_and_covolume_le P₁ hdet₁
  obtain ⟨hfull₂, hcov₂⟩ := stepLattice_fullRank_and_covolume_le P₂ hdet₂
  exact hasCommonCoveringRadius_of_covolume_le _ _ hfull₁ hfull₂ hcov₁ hcov₂

/-- Linear-independent form of the two-lattice covering theorem. -/
theorem stepLattices_commonCoveringRadius_of_linearIndependent
    {d : ℕ} (P₁ P₂ : GAP d d)
    (hsteps₁ : LinearIndependent ℤ P₁.steps)
    (hsteps₂ : LinearIndependent ℤ P₂.steps) :
    HasCommonCoveringRadius
      (stepLattice P₁ : Set (LatticePoint d))
      (stepLattice P₂ : Set (LatticePoint d))
      ((stepMatrix P₁).det.natAbs ^ d *
        (stepMatrix P₂).det.natAbs ^ d) := by
  exact stepLattices_commonCoveringRadius P₁ P₂
    (det_ne_zero_of_linearIndependent_steps P₁ hsteps₁)
    (det_ne_zero_of_linearIndependent_steps P₂ hsteps₂)

end

end Erdos186.PZ.Intersection
