/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.PZ.Intersection.Main
import ErdosProblems.Erdos186.PZ.Intersection.SideLattice

/-!
# Feeding progression step lattices into the post-CFP intersection theorem

This small adapter identifies the abstract lattice fields of
`IntersectionSideInput` with the concrete lattices generated by square GAP
step matrices.  Nonsingularity then discharges the complete common-covering
conclusion used by `Theorem4PostCFPData.ofSourceLemmas`.
-/

namespace Erdos186.PZ.Intersection

noncomputable section

set_option autoImplicit false

/-- The full-rank/covolume source conclusion for two side inputs follows
from identifying their lattices with the step lattices of two nonsingular
rank-`d` progressions. -/
theorem fullRankLatticeCovolumeConclusion_of_stepLattices {d : ℕ}
    {A₁ A₂ : Finset (LatticePoint d)} {a : LatticePoint d}
    (I₁ : IntersectionSideInput A₁ a .forward)
    (I₂ : IntersectionSideInput A₂ a .reverse)
    (P₁ P₂ : GAP d d)
    (hlattice₁ : I₁.lattice =
      (stepLattice P₁ : Set (LatticePoint d)))
    (hlattice₂ : I₂.lattice =
      (stepLattice P₂ : Set (LatticePoint d)))
    (hdet₁ : (stepMatrix P₁).det ≠ 0)
    (hdet₂ : (stepMatrix P₂).det ≠ 0) :
    FullRankLatticeCovolumeConclusion I₁ I₂
      ((stepMatrix P₁).det.natAbs ^ d *
        (stepMatrix P₂).det.natAbs ^ d) := by
  rw [FullRankLatticeCovolumeConclusion, hlattice₁, hlattice₂]
  exact stepLattices_commonCoveringRadius P₁ P₂ hdet₁ hdet₂

end

end Erdos186.PZ.Intersection
