import ErdosProblems.Erdos67.LogDerivativeTower
import ErdosProblems.Erdos1149.HigherDerivative

/-!
# A finite higher-derivative test for the logarithmic phase

This file connects the elementary derivative tower of `a * log x` with the
controlled Weyl--Kusmin--Landau machinery.  The statement is deliberately
finite: for every off-diagonal leaf generated by `s` identical controlled
Weyl steps, explicit lower and upper derivative inequalities imply the exact
terminal increment condition.

The alternating sign of the logarithmic derivatives is harmless.  We
multiply the whole derivative tower by `(-1)^s`, apply the nonpositive-next-
derivative form of the finite derivative test, and then remove this global
sign from the terminal condition.
-/

open Set

namespace Erdos67.LogPhaseHigherDerivative

noncomputable section

open Erdos1149
open Erdos67.LogDerivativeTower

/-- A logarithmic phase translated to a block beginning at `X`. -/
def shiftedLogPhase (a X x : ℝ) : ℝ :=
  a * Real.log (X + x)

/-- The translated logarithmic derivative tower, with the terminal-order
sign normalization already inserted. -/
def signedShiftedLogDerivative (a X : ℝ) (s j : ℕ) (x : ℝ) : ℝ :=
  (-1 : ℝ) ^ s * F a j (X + x)

@[simp]
theorem signedShiftedLogDerivative_zero (a X : ℝ) (s : ℕ) :
    signedShiftedLogDerivative a X s 0 =
      fun x ↦ (-1 : ℝ) ^ s * shiftedLogPhase a X x := by
  funext x
  rfl

/-- The signed translated tower differentiates term by term throughout the
positive half-line of its untranslated argument. -/
theorem hasDerivAt_signedShiftedLogDerivative
    (a X : ℝ) (s j : ℕ) {x : ℝ} (hx : 0 < X + x) :
    HasDerivAt (signedShiftedLogDerivative a X s j)
      (signedShiftedLogDerivative a X s (j + 1) x) x := by
  have hinner : HasDerivAt (fun y : ℝ ↦ X + y) 1 x := by
    simpa only [id_eq, one_mul] using (hasDerivAt_id x).const_add X
  have hcomp := (hasDerivAt_F a j hx).comp x hinner
  have hsigned := hcomp.const_mul ((-1 : ℝ) ^ s)
  change HasDerivAt (fun y ↦ (-1 : ℝ) ^ s * F a j (X + y))
    ((-1 : ℝ) ^ s * F a (j + 1) (X + x)) x
  simpa only [Function.comp_apply, mul_one] using hsigned

private theorem neg_one_pow_square (s : ℕ) :
    (-1 : ℝ) ^ s * (-1 : ℝ) ^ s = 1 := by
  rw [← pow_add, ← two_mul, pow_mul]
  norm_num

/-- Exact positive terminal derivative after sign normalization. -/
theorem signedShiftedLogDerivative_terminal
    (a X x : ℝ) (s : ℕ) :
    signedShiftedLogDerivative a X s (s + 1) x =
      a * (s.factorial : ℝ) * (X + x) ^ (-((s + 1 : ℕ) : ℤ)) := by
  exact sign_normalized_logDerivative a (X + x) s

/-- Exact negative next derivative after sign normalization. -/
theorem signedShiftedLogDerivative_next
    (a X x : ℝ) (s : ℕ) :
    signedShiftedLogDerivative a X s (s + 2) x =
      -(a * ((s + 1).factorial : ℝ) *
        (X + x) ^ (-((s + 2 : ℕ) : ℤ))) := by
  rw [show s + 2 = (s + 1) + 1 by omega]
  simp only [signedShiftedLogDerivative, F_succ]
  have hsquare := neg_one_pow_square s
  rw [pow_succ]
  ring_nf at hsquare ⊢
  rw [hsquare]
  have hexp : (-1 : ℤ) - ((1 + s : ℕ) : ℤ) = -((2 + s : ℕ) : ℤ) := by
    push_cast
    ring
  rw [hexp]
  ring

/-- Lower magnitude bound for a positive logarithmic derivative when only
an arbitrary positive upper endpoint is known. -/
theorem lower_abs_logDerivative_succ_of_le
    {a x B : ℝ} (hx : 0 < x) (hB : x ≤ B) (j : ℕ) :
    |a| * (j.factorial : ℝ) * B ^ (-(j + 1 : ℤ)) ≤
      |F a (j + 1) x| := by
  rw [abs_logDerivative_succ hx]
  have hpow : x ^ (j + 1) ≤ B ^ (j + 1) :=
    pow_le_pow_left₀ hx.le hB _
  have hinv : (B ^ (j + 1))⁻¹ ≤ (x ^ (j + 1))⁻¹ :=
    inv_anti₀ (pow_pos hx _) hpow
  simp only [zpow_neg, zpow_natCast]
  exact mul_le_mul_of_nonneg_left hinv
    (mul_nonneg (abs_nonneg a) (Nat.cast_nonneg _))

/-- Upper magnitude bound for a positive logarithmic derivative from a
positive lower endpoint. -/
theorem upper_abs_logDerivative_succ_of_le
    {a X x : ℝ} (hX : 0 < X) (hXx : X ≤ x) (j : ℕ) :
    |F a (j + 1) x| ≤
      |a| * (j.factorial : ℝ) * X ^ (-(j + 1 : ℤ)) := by
  have hx : 0 < x := hX.trans_le hXx
  rw [abs_logDerivative_succ hx]
  have hpow : X ^ (j + 1) ≤ x ^ (j + 1) :=
    pow_le_pow_left₀ hX.le hXx _
  have hinv : (x ^ (j + 1))⁻¹ ≤ (X ^ (j + 1))⁻¹ :=
    inv_anti₀ (pow_pos hX _) hpow
  simp only [zpow_neg, zpow_natCast]
  exact mul_le_mul_of_nonneg_left hinv
    (mul_nonneg (abs_nonneg a) (Nat.cast_nonneg _))

/-- The terminal increment condition is invariant under negating a real
phase.  This local copy keeps the logarithmic module independent of the
monomial application where the same elementary fact is also useful. -/
theorem terminalIncrementCondition_neg
    {g : ℕ → ℝ} {N : ℕ} {lam : ℝ}
    (h : HigherDerivative.TerminalIncrementCondition g N lam) :
    HigherDerivative.TerminalIncrementCondition (fun n ↦ -g n) N lam := by
  rcases h with ⟨hb, hm | ha⟩ | ⟨hb, hm | ha⟩
  · right
    refine ⟨?_, Or.inr ?_⟩
    · intro k hk
      have hbk := hb k hk
      constructor <;> dsimp only <;> linarith
    · intro i hi j hj hij
      dsimp only
      convert neg_le_neg (hm hi hj hij) using 1 <;> ring
  · right
    refine ⟨?_, Or.inl ?_⟩
    · intro k hk
      have hbk := hb k hk
      constructor <;> dsimp only <;> linarith
    · intro i hi j hj hij
      dsimp only
      convert neg_le_neg (ha hi hj hij) using 1 <;> ring
  · left
    refine ⟨?_, Or.inr ?_⟩
    · intro k hk
      have hbk := hb k hk
      constructor <;> dsimp only <;> linarith
    · intro i hi j hj hij
      dsimp only
      convert neg_le_neg (hm hi hj hij) using 1 <;> ring
  · left
    refine ⟨?_, Or.inl ?_⟩
    · intro k hk
      have hbk := hb k hk
      constructor <;> dsimp only <;> linarith
    · intro i hi j hj hij
      dsimp only
      convert neg_le_neg (ha hi hj hij) using 1 <;> ring

/-- Iterated pair differencing is linear under a global minus sign. -/
theorem iteratedPairDifference_neg
    (g : ℕ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (x : ℕ) :
    HigherDerivative.iteratedPairDifference (fun n ↦ -g n) hs x =
      -HigherDerivative.iteratedPairDifference g hs x := by
  induction hs generalizing x with
  | nil => rfl
  | cons h hs ih =>
      rcases h with ⟨d, k, l⟩
      simp only [HigherDerivative.iteratedPairDifference,
        HigherDerivative.pairDifference, ih]
      ring

/-- Explicit terminal derivative test for one constant-controlled Weyl leaf
of a logarithmic phase.  All bounds are uniform on the translated interval
`[X,3X]`.

The window hypothesis ensures that every iterated-difference integration
point, including the final unit increment, stays in this interval. -/
theorem terminalIncrementCondition_shiftedLog
    {a X lam : ℝ} {s K d P : ℕ}
    (ha : 0 < a) (hX : 0 < X) (hK : 0 < K)
    (leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (HigherDerivative.constantControlledSteps s K d hK) [])
    (hwindow : (P : ℝ) + (s : ℝ) * K * d + 1 ≤ 2 * X)
    (hlower : lam ≤ (d : ℝ) ^ s *
      (a * (s.factorial : ℝ) *
        (3 * X) ^ (-((s + 1 : ℕ) : ℤ))))
    (hupper : ((K : ℝ) * d) ^ s *
      (a * (s.factorial : ℝ) * X ^ (-((s + 1 : ℕ) : ℤ))) ≤
        1 - lam) :
    HigherDerivative.TerminalIncrementCondition
      (HigherDerivative.iteratedPairDifference
        (fun n ↦ shiftedLogPhase a X n) leaf) P lam := by
  let eps : ℝ := (-1 : ℝ) ^ s
  let tower : ℕ → ℝ → ℝ := signedShiftedLogDerivative a X s
  let f : ℝ → ℝ := fun x ↦ eps * shiftedLogPhase a X x
  let L : ℝ := a * (s.factorial : ℝ) *
    (3 * X) ^ (-((s + 1 : ℕ) : ℤ))
  let U : ℝ := a * (s.factorial : ℝ) *
    X ^ (-((s + 1 : ℕ) : ℤ))
  let Lnext : ℝ := -(a * ((s + 1).factorial : ℝ) *
    X ^ (-((s + 2 : ℕ) : ℤ)))
  have hbaseSteps :=
    HigherDerivative.historyBase_add_steps_sum_le_of_constantControlledSteps
      s K d hK leaf hleaf
  have hprodLower :=
    HigherDerivative.pow_le_historySteps_prod_of_constantControlledSteps
      s K d hK leaf hleaf
  have hprodUpper :=
    HigherDerivative.historySteps_prod_le_pow_of_constantControlledSteps
      s K d hK leaf hleaf
  have hlen : (MixedDifference.historySteps
      (MixedDifference.realHistory leaf)).length = s := by
    rw [MixedDifference.length_historySteps, MixedDifference.length_realHistory,
      HigherDerivative.leaf_length_eq_of_constantControlledSteps s K d hK leaf hleaf]
  have hLnonneg : 0 ≤ L := by
    dsimp only [L]
    positivity
  have hUnonneg : 0 ≤ U := by
    dsimp only [U]
    positivity
  have hsigned : HigherDerivative.TerminalIncrementCondition
      (HigherDerivative.iteratedPairDifference (fun n ↦ f n) leaf) P lam := by
    apply HigherDerivative.terminalIncrementCondition_of_derivBounds_and_next_nonpos_on_Icc
      tower f leaf P 0 (2 * X) L U Lnext 0 lam
    · dsimp only [tower, f, eps]
      exact signedShiftedLogDerivative_zero a X s
    · rw [MixedDifference.historyBase_realHistory]
      unfold MixedDifference.natHistoryBase
      refine List.sum_nonneg ?_
      intro z hz
      obtain ⟨entry, hentry, rfl⟩ := List.mem_map.mp hz
      unfold MixedDifference.natPairBase
      positivity
    · linarith
    · intro j hj y hy
      apply hasDerivAt_signedShiftedLogDerivative
      exact add_pos_of_pos_of_nonneg hX hy.1
    · intro y hy
      rcases hy with ⟨hy0, hyX⟩
      have hxy : X + y ∈ Set.Icc X (3 * X) := by
        constructor <;> linarith
      have hl := lower_abs_logDerivative_succ_of_le (a := a)
        (hX.trans_le hxy.1) hxy.2 s
      have hu := upper_abs_logDerivative_succ_of_le (a := a) hX hxy.1 s
      dsimp only [tower]
      rw [hlen, signedShiftedLogDerivative_terminal]
      dsimp only [L, U]
      rw [abs_of_pos ha] at hl hu
      rw [abs_logDerivative_succ (hX.trans_le hxy.1), abs_of_pos ha] at hl hu
      constructor
      · convert hl using 1 <;> norm_num
      · convert hu using 1 <;> norm_num
    · intro y hy
      rcases hy with ⟨hy0, hyX⟩
      have hxypos : 0 < X + y := add_pos_of_pos_of_nonneg hX hy0
      dsimp only [tower]
      rw [hlen, signedShiftedLogDerivative_next]
      dsimp only [Lnext]
      constructor
      · have habs := upper_abs_logDerivative_succ_of_le
          (a := a) hX (show X ≤ X + y by linarith) (s + 1)
        rw [abs_logDerivative_succ hxypos] at habs
        simp only [abs_of_pos ha] at habs
        have hexp : -((s + 2 : ℕ) : ℤ) =
            -(((s + 1 : ℕ) : ℤ) + 1) := by
          push_cast
          ring
        rw [hexp]
        apply neg_le_neg
        exact habs
      · exact neg_nonpos.mpr (by positivity)
    · exact le_rfl
    · dsimp only [L]
      calc
        lam ≤ (d : ℝ) ^ s *
            (a * (s.factorial : ℝ) *
              (3 * X) ^ (-((s + 1 : ℕ) : ℤ))) := hlower
        _ = L * (d : ℝ) ^ s := by dsimp only [L]; ring
        _ ≤ L * (MixedDifference.historySteps
              (MixedDifference.realHistory leaf)).prod :=
          mul_le_mul_of_nonneg_left hprodLower hLnonneg
    · dsimp only [U]
      calc
        U * (MixedDifference.historySteps
              (MixedDifference.realHistory leaf)).prod ≤
            U * ((K : ℝ) * d) ^ s :=
          mul_le_mul_of_nonneg_left hprodUpper hUnonneg
        _ = ((K : ℝ) * d) ^ s *
            (a * (s.factorial : ℝ) *
              X ^ (-((s + 1 : ℕ) : ℤ))) := by dsimp only [U]; ring
        _ ≤ 1 - lam := hupper
  rcases neg_one_pow_eq_or ℝ s with heps | heps
  · simpa only [f, eps, heps, one_mul] using hsigned
  · have hneg := terminalIncrementCondition_neg hsigned
    simpa only [f, eps, heps, neg_mul, one_mul, iteratedPairDifference_neg,
      neg_neg] using hneg

end

end Erdos67.LogPhaseHigherDerivative
