import Wikipedia.SzemeredisTheorem.Hypergraph.OrderedRemovalParameters

/-!
# One-rank growth-function regularity

This file packages the preliminary one-rank selector underlying the
growth-function form of hypergraph regularity.  For a natural-valued growth
function `F`, an initial complexity bound `M₀`, and a fixed upper layer, the
schedule is constructed triangularly:

```
M 0       = M₀,
τ n       = 1 / F (M n),
B n       = ⌈card (OrderedFace k (j + 1)) / (τ n)²⌉ + 1,
M (n + 1) = (2^(j+1))^(B n) * M n.
```

The existing fixed-upper tower then selects adjacent coarse and fine stages.
The fine stage is preliminarily regular with error exactly `τ i`; a
one-rank energy pigeonhole makes the coarse/fine gap at most any prescribed
positive `γ`.  All numerical schedules are ambient-independent.
-/

namespace Wikipedia.SzemeredisTheorem

/-! ## Natural growth functions -/

/-- A natural growth function is monotone and lies strictly above the
diagonal.  The latter hypothesis ensures that all reciprocal tolerances are
positive, including when the initial complexity bound is zero. -/
structure NatGrowthFunction where
  toFun : ℕ → ℕ
  monotone' : Monotone toFun
  above_diagonal : ∀ n, n + 1 ≤ toFun n

namespace NatGrowthFunction

instance : CoeFun NatGrowthFunction (fun _ => ℕ → ℕ) :=
  ⟨NatGrowthFunction.toFun⟩

theorem monotone (F : NatGrowthFunction) :
    Monotone F :=
  F.monotone'

theorem positive (F : NatGrowthFunction) (n : ℕ) :
    0 < F n := by
  exact lt_of_lt_of_le (Nat.zero_lt_succ n)
    (F.above_diagonal n)

theorem one_le (F : NatGrowthFunction) (n : ℕ) :
    1 ≤ F n :=
  F.positive n

end NatGrowthFunction

/-! ## The triangular numerical schedule -/

/-- Reciprocal growth-function tolerance at a displayed complexity. -/
noncomputable def growthRegularityStepTolerance
    (F : NatGrowthFunction) (M : ℕ) : ℝ :=
  1 / (F M : ℝ)

/-- Ceiling budget for one preliminary regularity pass at the reciprocal
growth-function tolerance. -/
noncomputable def growthRegularityStepBudget
    (k j : ℕ) (F : NatGrowthFunction) (M : ℕ) : ℕ :=
  orderedRemovalRegularityBudget
    k j (growthRegularityStepTolerance F M)

/-- The triangular complexity sequence generated by the fixed-upper tower
factor and the budget computed from the current complexity. -/
noncomputable def growthRegularityComplexity
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ℕ → ℕ
  | 0 => initialBound
  | n + 1 =>
      (2 ^ (j + 1)) ^
          growthRegularityStepBudget
            k j F
              (growthRegularityComplexity
                k j initialBound F n) *
        growthRegularityComplexity
          k j initialBound F n

/-- Stagewise reciprocal tolerance obtained from the triangular complexity
sequence. -/
noncomputable def growthRegularityTolerance
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ℕ → ℝ :=
  fun n =>
    growthRegularityStepTolerance F
      (growthRegularityComplexity
        k j initialBound F n)

/-- Stagewise ceiling budget obtained from the same triangular sequence. -/
noncomputable def growthRegularityBudget
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ℕ → ℕ :=
  fun n =>
    growthRegularityStepBudget k j F
      (growthRegularityComplexity
        k j initialBound F n)

@[simp]
theorem growthRegularityComplexity_zero
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    growthRegularityComplexity
      k j initialBound F 0 = initialBound :=
  rfl

@[simp]
theorem growthRegularityComplexity_succ
    (k j initialBound n : ℕ) (F : NatGrowthFunction) :
    growthRegularityComplexity
        k j initialBound F (n + 1) =
      (2 ^ (j + 1)) ^
          growthRegularityBudget
            k j initialBound F n *
        growthRegularityComplexity
          k j initialBound F n :=
  rfl

@[simp]
theorem growthRegularityTolerance_eq
    (k j initialBound n : ℕ) (F : NatGrowthFunction) :
    growthRegularityTolerance
        k j initialBound F n =
      1 /
        (F (growthRegularityComplexity
          k j initialBound F n) : ℝ) :=
  rfl

@[simp]
theorem growthRegularityBudget_eq
    (k j initialBound n : ℕ) (F : NatGrowthFunction) :
    growthRegularityBudget
        k j initialBound F n =
      Nat.ceil
          ((Fintype.card
              (OrderedFace k (j + 1)) : ℝ) /
            (growthRegularityTolerance
              k j initialBound F n) ^ 2) +
        1 :=
  rfl

theorem growthRegularityStepTolerance_pos
    (F : NatGrowthFunction) (M : ℕ) :
    0 < growthRegularityStepTolerance F M := by
  unfold growthRegularityStepTolerance
  exact one_div_pos.mpr
    (by exact_mod_cast F.positive M)

theorem growthRegularityTolerance_pos
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ∀ n,
      0 <
        growthRegularityTolerance
          k j initialBound F n := by
  intro n
  exact growthRegularityStepTolerance_pos F
    (growthRegularityComplexity
      k j initialBound F n)

theorem growthRegularityBudget_pos
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ∀ n,
      0 <
        growthRegularityBudget
          k j initialBound F n := by
  intro n
  exact orderedRemovalRegularityBudget_pos _ _ _

/-- Every triangular ceiling budget is strictly long enough for the
corresponding preliminary regularity pass. -/
theorem growthRegularityBudget_spec
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ∀ n,
      (Fintype.card
          (OrderedFace k (j + 1)) : ℝ) <
        (growthRegularityBudget
            k j initialBound F n : ℝ) *
          (growthRegularityTolerance
            k j initialBound F n) ^ 2 := by
  intro n
  exact orderedRemovalRegularityBudget_spec
    (growthRegularityTolerance_pos
      k j initialBound F n)

/-- The triangular sequence is exactly the standard fixed-upper recursive
complexity factor multiplied by the initial bound. -/
theorem growthRegularityComplexity_eq_factor_mul
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    ∀ n,
      growthRegularityComplexity
          k j initialBound F n =
        fixedUpperLayerComplexityFactor
            j (growthRegularityBudget
              k j initialBound F) n *
          initialBound := by
  intro n
  induction n with
  | zero =>
      simp [fixedUpperLayerComplexityFactor]
  | succ n ih =>
      rw [growthRegularityComplexity_succ, ih]
      simp [fixedUpperLayerComplexityFactor,
        Nat.mul_assoc]

theorem growthRegularityComplexity_pos
    {k j initialBound : ℕ} (F : NatGrowthFunction)
    (hinitial : 0 < initialBound) :
    ∀ n,
      0 <
        growthRegularityComplexity
          k j initialBound F n := by
  intro n
  induction n with
  | zero =>
      simpa using hinitial
  | succ n ih =>
      rw [growthRegularityComplexity_succ]
      exact Nat.mul_pos
        (pow_pos (by positivity) _)
        ih

theorem growthRegularityComplexity_monotone
    (k j initialBound : ℕ) (F : NatGrowthFunction) :
    Monotone
      (growthRegularityComplexity
        k j initialBound F) := by
  apply monotone_nat_of_le_succ
  intro n
  rw [growthRegularityComplexity_succ]
  exact Nat.le_mul_of_pos_left _
    (pow_pos (by positivity) _)

/-! ## A one-rank energy timescale -/

/-- Ceiling length making the rank-`j` aggregate energy increment at most
the prescribed positive target. -/
noncomputable def growthRegularityLength
    (k j : ℕ) (γ : ℝ) : ℕ :=
  Nat.ceil
      ((Fintype.card
        (OrderedFace k (j + 1)) : ℝ) / γ) +
    1

theorem growthRegularityLength_pos
    (k j : ℕ) (γ : ℝ) :
    0 < growthRegularityLength k j γ := by
  unfold growthRegularityLength
  omega

/-- The reciprocal one-rank energy budget is strictly smaller than `γ`. -/
theorem orderedFace_card_div_growthRegularityLength_lt
    {k j : ℕ} {γ : ℝ} (hγ : 0 < γ) :
    (Fintype.card
        (OrderedFace k (j + 1)) : ℝ) /
        (growthRegularityLength k j γ : ℝ) <
      γ := by
  let A : ℝ :=
    (Fintype.card
      (OrderedFace k (j + 1)) : ℝ)
  let L : ℕ :=
    growthRegularityLength k j γ
  have hLNat : 0 < L :=
    growthRegularityLength_pos k j γ
  have hLCast : (0 : ℝ) < (L : ℝ) := by
    exact_mod_cast hLNat
  have hquot : A / γ < (L : ℝ) := by
    dsimp only [A, L]
    unfold growthRegularityLength
    calc
      (Fintype.card
          (OrderedFace k (j + 1)) : ℝ) / γ ≤
          (Nat.ceil
            ((Fintype.card
              (OrderedFace k (j + 1)) : ℝ) / γ) : ℝ) :=
        Nat.le_ceil _
      _ <
          (Nat.ceil
            ((Fintype.card
              (OrderedFace k (j + 1)) : ℝ) / γ) : ℝ) + 1 := by
        linarith
      _ =
          ((Nat.ceil
            ((Fintype.card
              (OrderedFace k (j + 1)) : ℝ) / γ) + 1 : ℕ) : ℝ) := by
        norm_num
  have hA : A < (L : ℝ) * γ :=
    (div_lt_iff₀ hγ).1 hquot
  apply (div_lt_iff₀ hLCast).2
  simpa [mul_comm] using hA

/-! ## Growth-function fixed-upper selection -/

/-- Selected adjacent fixed-upper tower stages with their bounds rewritten
in terms of the triangular growth-function complexity sequence. -/
structure GrowthFunctionFixedUpperCertificate
    (G : Type*) [Fintype G] [DecidableEq G]
    (k j initialBound : ℕ)
    (initial : OrderedFacePartitionSystem G k j)
    (upper : OrderedFacePartitionSystem G k (j + 1))
    (F : NatGrowthFunction) (γ : ℝ) where
  index : ℕ
  index_lt :
    index < growthRegularityLength k j γ
  coarse : OrderedFacePartitionSystem G k j
  fine : OrderedFacePartitionSystem G k j
  refines : OrderedFacePartitionRefines fine coarse
  coarse_refines_initial :
    OrderedFacePartitionRefines coarse initial
  fine_regular :
    IsPreliminaryOrderedRegular fine upper
      (1 /
        (F (growthRegularityComplexity
          k j initialBound F index) : ℝ))
  gap_nonneg :
    0 ≤
      orderedLayerAtomEnergy fine upper -
        orderedLayerAtomEnergy coarse upper
  gap_le :
    orderedLayerAtomEnergy fine upper -
        orderedLayerAtomEnergy coarse upper ≤ γ
  coarse_complexity :
    ∀ e,
      FacePartition.complexity (coarse e) ≤
        growthRegularityComplexity
          k j initialBound F index
  fine_complexity :
    ∀ e,
      FacePartition.complexity (fine e) ≤
        growthRegularityComplexity
          k j initialBound F (index + 1)

/-- One-rank preliminary growth-function selector obtained from the
fixed-upper coarse/fine tower. -/
theorem GrowthFunctionFixedUpperCertificate.nonempty
    {G : Type*} [Fintype G] [DecidableEq G] [Nonempty G]
    {k j initialBound : ℕ}
    (initial : OrderedFacePartitionSystem G k j)
    (upper : OrderedFacePartitionSystem G k (j + 1))
    (F : NatGrowthFunction) {γ : ℝ} (hγ : 0 < γ)
    (hinitial :
      ∀ e,
        FacePartition.complexity (initial e) ≤
          initialBound) :
    Nonempty
      (GrowthFunctionFixedUpperCertificate
        G k j initialBound initial upper F γ) := by
  let τ : ℕ → ℝ :=
    growthRegularityTolerance k j initialBound F
  let B : ℕ → ℕ :=
    growthRegularityBudget k j initialBound F
  let L : ℕ :=
    growthRegularityLength k j γ
  obtain ⟨R⟩ :=
    FixedUpperLayerCoarseFine.nonempty
      initial upper τ B
      (fun n =>
        (growthRegularityTolerance_pos
          k j initialBound F n).le)
      (growthRegularityBudget_spec
        k j initialBound F)
      (growthRegularityLength_pos k j γ)
  refine ⟨{
    index := R.index
    index_lt := R.index_lt
    coarse := R.coarse
    fine := R.fine
    refines := R.refines
    coarse_refines_initial :=
      R.coarse_refines_initial
    fine_regular := ?_
    gap_nonneg := R.gap_nonneg
    gap_le := ?_
    coarse_complexity := ?_
    fine_complexity := ?_ }⟩
  · simpa [τ, growthRegularityTolerance_eq] using
      R.fine_regular
  · exact R.gap_le.trans
      (orderedFace_card_div_growthRegularityLength_lt
        hγ).le
  · intro e
    calc
      FacePartition.complexity (R.coarse e) ≤
          fixedUpperLayerComplexityFactor
              j B R.index *
            FacePartition.complexity (initial e) :=
        R.coarse_complexity e
      _ ≤
          fixedUpperLayerComplexityFactor
              j B R.index *
            initialBound :=
        Nat.mul_le_mul_left _ (hinitial e)
      _ =
          growthRegularityComplexity
            k j initialBound F R.index := by
        rw [growthRegularityComplexity_eq_factor_mul]
  · intro e
    calc
      FacePartition.complexity (R.fine e) ≤
          fixedUpperLayerComplexityFactor
              j B (R.index + 1) *
            FacePartition.complexity (initial e) :=
        R.fine_complexity e
      _ ≤
          fixedUpperLayerComplexityFactor
              j B (R.index + 1) *
            initialBound :=
        Nat.mul_le_mul_left _ (hinitial e)
      _ =
          growthRegularityComplexity
            k j initialBound F (R.index + 1) := by
        rw [growthRegularityComplexity_eq_factor_mul]

end Wikipedia.SzemeredisTheorem
