import ErdosProblems.Erdos593.Graph.Parity
import ErdosProblems.Erdos593.TripleSystem.DisjointUnion
import ErdosProblems.Erdos593.TripleSystem.Expansion
import ErdosProblems.Erdos593.TripleSystem.Isomorph
import ErdosProblems.Erdos593.TripleSystem.Intrinsic
import ErdosProblems.Erdos593.TripleSystem.OnePointAmalgamation

set_option relaxedAutoImplicit true
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# The finite constructive class

This file defines the class generated by finite edgeless triple systems and
private-vertex expansions of finite two-colourable graphs, with closure under
binary disjoint unions, one-point amalgamations, and isomorphism.  Binary
constructors suffice because every construction term is finite.
-/

namespace Erdos593

universe w

namespace TripleSystem

/-- A universe-polymorphic empty edge-index type. -/
abbrev EdgelessEdge : Type w := ULift.{w} Empty

/-- The canonical triple system with vertex type `V` and no hyperedges. -/
def edgeless (V : Type w) : TripleSystem V EdgelessEdge where
  Inc _ e := nomatch e.down
  edge_ncard e := nomatch e.down
  simple e := nomatch e.down

/-- The constructive class generated by finite edgeless systems and
private-vertex expansions of finite two-colourable graphs, and closed under
binary disjoint unions, one-point amalgamations, and isomorphism. -/
inductive Constructible : {V E : Type w} → TripleSystem V E → Prop
  | ofEdgeless (V : Type w) [Fintype V] : Constructible (edgeless V)
  | ofExpansion {V : Type w} [Fintype V] (G : _root_.SimpleGraph V)
      (hG : G.Colorable 2) : Constructible (privateVertexExpansion G)
  | disjointUnion {V E W D : Type w}
      {F : TripleSystem V E} {G : TripleSystem W D}
      (hF : Constructible F) (hG : Constructible G) :
      Constructible (F.disjointUnion G)
  | amalgam {V₀ E₀ V₁ E₁ : Type w}
      {F₀ : TripleSystem V₀ E₀} {F₁ : TripleSystem V₁ E₁}
      (h₀ : Constructible F₀) (h₁ : Constructible F₁)
      (r₀ : V₀) (r₁ : V₁) :
      Constructible (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁)
  | ofIso {V E V' E' : Type w}
      {F : TripleSystem V E} {F' : TripleSystem V' E'}
      (hF : Constructible F) (f : Iso F F') : Constructible F'

/-- Finite edgeless systems satisfy all three intrinsic conditions
vacuously. -/
theorem edgeless_intrinsic (V : Type w) : (edgeless V).Intrinsic := by
  refine ⟨?_, ?_, ?_⟩
  · intro e
    exact Empty.elim e.down
  · intro e
    exact Empty.elim e.down
  · intro z c hc
    cases c with
    | nil => simp at hc
    | @cons u v w h p =>
        cases z with
        | inl x =>
            cases v with
            | inl y => exact ((edgeless V).not_levi_adj_point_point h).elim
            | inr e => exact Empty.elim e.down
        | inr e => exact Empty.elim e.down

end TripleSystem
end Erdos593
