import ErdosProblems.Erdos593.TripleSystem.SequenceLiftBaseFiberSupportIncidenceAcyclicEndpoints
import ErdosProblems.Erdos593.TripleSystem.FiniteLinearImageTrace
import ErdosProblems.Erdos593.TripleSystem.FiniteLiftGeneratedBergeCycleTrace

set_option relaxedAutoImplicit true
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# Endpoints for finite linear sources embedded in a sequence lift

The finite-linear endpoint for a selected restriction is transported back to
an arbitrary finite source through the exact image restriction of an embedding.
The transport deliberately passes through the isolated reduction: that is the
object for which `FiniteLiftGenerated` is invariant under the exact image
isomorphism.

The source and the sequence lift share a universe here because the existing
`FiniteLiftGenerated.ofIso` API is same-universe.  A heterogeneous-universe
wrapper, if needed, should be introduced separately via an explicit `ULift`
transport rather than hidden in this endpoint.
-/

namespace Erdos593

universe u

namespace SequenceLift

variable {V : Type u} {G : _root_.SimpleGraph V}
variable {X I : Type u} {F : TripleSystem X I}

/-- The isolated reduction of a finite linear source embedded in a sequence
lift is finitely lift-generated by the host graph. -/
theorem isolatedReduction_finiteLiftGenerated_of_linear_of_embedding
    [Fintype I]
    (f : F.Embedding (system G)) (hlinear : F.Linear) :
    TripleSystem.FiniteLiftGenerated G F.isolatedReduction := by
  have htrace :=
    TripleSystem.Embedding.finiteLinear_isolatedReduction_imageTrace f hlinear
  exact TripleSystem.FiniteLiftGenerated.ofIso
    (edgeRestriction_finiteLiftGenerated_of_linear htrace.1 htrace.2.1)
    (Classical.choice htrace.2.2).symm

/-- Every Berge cycle in the isolated reduction of a finite linear source
embedded in a sequence lift contracts to a host closed walk of half its Levi
length.  This is the transport interface used by the odd-Berge obstruction. -/
theorem isolatedReduction_bergeCycleTraceTo_of_linear_of_embedding
    [Fintype I]
    (f : F.Embedding (system G)) (hlinear : F.Linear) :
    TripleSystem.BergeCycleTraceTo G F.isolatedReduction := by
  exact TripleSystem.FiniteLiftGenerated.bergeCycleTraceTo G
    (isolatedReduction_finiteLiftGenerated_of_linear_of_embedding f hlinear)

/-- In a two-colourable host, the isolated reduction of a finite linear
embedded source is constructible. -/
theorem isolatedReduction_constructible_of_linear_of_embedding
    [Fintype I]
    (f : F.Embedding (system G)) (hlinear : F.Linear)
    (hG : G.Colorable 2) :
    TripleSystem.Constructible F.isolatedReduction := by
  exact TripleSystem.FiniteLiftGenerated.constructible_of_hostColorable hG
    (isolatedReduction_finiteLiftGenerated_of_linear_of_embedding f hlinear)

/-- In a two-colourable host, the isolated reduction of a finite linear
embedded source is obligatory. -/
theorem isolatedReduction_isObligatory_of_linear_of_embedding
    [Fintype I]
    (f : F.Embedding (system G)) (hlinear : F.Linear)
    (hG : G.Colorable 2) :
    F.isolatedReduction.IsObligatory := by
  exact TripleSystem.FiniteLiftGenerated.isObligatory_of_hostColorable hG
    (isolatedReduction_finiteLiftGenerated_of_linear_of_embedding f hlinear)

/-- A finite linear source embedded in a two-colourable sequence lift is
obligatory. -/
theorem isObligatory_of_linear_of_embedding
    [Fintype X] [Fintype I]
    (f : F.Embedding (system G)) (hlinear : F.Linear)
    (hG : G.Colorable 2) :
    F.IsObligatory := by
  exact TripleSystem.IsObligatory.of_isolatedReduction
    (isolatedReduction_isObligatory_of_linear_of_embedding f hlinear hG)

end SequenceLift

end Erdos593
