/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
/- Original license: Apache 2.0. Note: This file has been modified. -/
/-
This is a Lean formalization of a solution to Erdős Problem 631.
https://www.erdosproblems.com/forum/thread/631

Informal authors:
- Carsten Thomassen
- Margit Voigt

Formal authors:
- Codex
- GPT-5.6 Sol

URLs:
- https://github.com/plby/lean-proofs/blob/main/ErdosProblems/Erdos631.md
-/
import ErdosProblems.Erdos753
import Mathlib.Tactic

namespace Erdos631

/-!
# Erdős Problem 631

Every finite planar graph is 5-choosable, and the bound is sharp.

The upper bound is Thomassen's 1994 theorem.  Because Mathlib v4.33.0 has no
notion of a planar graph or plane embedding, finite planarity is represented
by the standard recursive certificate for triangulated discs: triangles,
gluing along a boundary chord, and inserting a fan at the end of the outer
boundary.  Repeated rooted edge sums cover the cut-pair presentation used by
Gutner's explicit non-4-choosable planar graph.
-/

open Finset

/-! ## A finite combinatorial certificate for plane triangulated discs -/

/-- We store one orientation of each edge.  Adjacency below is the symmetric
closure, so this is only a compact finite representation of an undirected
edge set. -/
abbrev Edge := ℕ × ℕ

/-- The grammar of rooted triangulated discs.  In a `glue` node, `pre`,
`post`, `rest`, `u`, and `v` record the two boundary decompositions
`pre ++ u :: v :: post` and `u :: v :: rest`.  In a `fan` node the child
boundary is `prefix ++ tail`; the fresh vertex replaces `tail` on the outer
boundary and is joined to the last vertex of `prefix`, every vertex of
`tail`, and the first root vertex. -/
inductive DiskExpr where
  | triangle (a b c : ℕ)
  | glue (left right : DiskExpr) (pre post rest : List ℕ) (u v : ℕ)
  | fan (child : DiskExpr) (pref tail : List ℕ) (z : ℕ)
  deriving Repr

namespace DiskExpr

def root₁ : DiskExpr → ℕ
  | .triangle a _ _ => a
  | .glue left _ _ _ _ _ _ => left.root₁
  | .fan child _ _ _ => child.root₁

def root₂ : DiskExpr → ℕ
  | .triangle _ b _ => b
  | .glue left _ _ _ _ _ _ => left.root₂
  | .fan child _ _ _ => child.root₂

def vertices : DiskExpr → Finset ℕ
  | .triangle a b c => {a, b, c}
  | .glue left right _ _ _ _ _ => left.vertices ∪ right.vertices
  | .fan child _ _ z => insert z child.vertices

def boundary : DiskExpr → List ℕ
  | .triangle a b c => [a, b, c]
  | .glue _ _ pre post rest u v => pre ++ u :: rest.reverse ++ v :: post
  | .fan _ pref _ z => pref ++ [z]

/-- The vertices to which a fan vertex is joined. -/
def fanNeighbors (child : DiskExpr) (pref tail : List ℕ) : List ℕ :=
  match pref.getLast? with
  | none => []
  | some w => w :: (tail ++ [child.root₁])

def edges : DiskExpr → Finset Edge
  | .triangle a b c => {(a, b), (b, c), (c, a)}
  | .glue left right _ _ _ _ _ => left.edges ∪ right.edges
  | .fan child pref tail z =>
      child.edges ∪ (child.fanNeighbors pref tail).toFinset.image (fun x => (z, x))

/-- Structural validity of a disc expression.  These are precisely the
freshness, boundary-order, and intersection facts used by the two planar
disc operations. -/
inductive Valid : DiskExpr → Prop where
  | triangle {a b c : ℕ} (hab : a ≠ b) (hbc : b ≠ c) (hca : c ≠ a) :
      Valid (.triangle a b c)
  | glue {left right : DiskExpr} {pre post rest : List ℕ} {u v : ℕ}
      (hleft : Valid left) (hright : Valid right)
      (hboundary_left : left.boundary = pre ++ u :: v :: post)
      (hboundary_right : right.boundary = u :: v :: rest)
      (hroot_right₁ : right.root₁ = u) (hroot_right₂ : right.root₂ = v)
      (hinter : left.vertices ∩ right.vertices = {u, v})
      (hedge : (u, v) ∈ left.edges ∨ (v, u) ∈ left.edges)
      (huv : u ≠ v) :
      Valid (.glue left right pre post rest u v)
  | fan {child : DiskExpr} {pref tail : List ℕ} {z : ℕ}
      (hchild : Valid child)
      (hboundary : child.boundary = pref ++ tail)
      (hpref : 2 ≤ pref.length)
      (hdisjoint : Disjoint pref.toFinset tail.toFinset)
      (hneighbors : (child.fanNeighbors pref tail).toFinset ⊆ child.vertices)
      (hroot₁_pref : child.root₁ ∈ pref.toFinset)
      (hroot₂_pref : child.root₂ ∈ pref.toFinset)
      (hfresh : z ∉ child.vertices) :
      Valid (.fan child pref tail z)

/-- Symmetric adjacency generated by a finite oriented edge set. -/
def EdgeAdj (E : Finset Edge) (x y : ℕ) : Prop :=
  (x, y) ∈ E ∨ (y, x) ∈ E

instance (E : Finset Edge) : DecidableRel (EdgeAdj E) := fun x y => by
  unfold EdgeAdj
  infer_instance

@[simp] lemma edgeAdj_comm {E : Finset Edge} {x y : ℕ} :
    EdgeAdj E x y ↔ EdgeAdj E y x := by
  simp only [EdgeAdj, or_comm]

/-- The simple graph carried by a disc expression.  The explicit inequality
in `Adj` makes looplessness definitionally independent of the chosen edge
representatives. -/
def graph (D : DiskExpr) : SimpleGraph {x // x ∈ D.vertices} where
  Adj x y := x.1 ≠ y.1 ∧ EdgeAdj D.edges x.1 y.1
  symm.symm _ _ h := ⟨h.1.symm, edgeAdj_comm.mp h.2⟩
  loopless.irrefl _ h := h.1 rfl

/-- A raw list-colouring of the finite graph represented by `V,E`. -/
def HasListColoring (V : Finset ℕ) (E : Finset Edge)
    (L : ℕ → Finset ℕ) : Prop :=
  ∃ c : ℕ → ℕ,
    (∀ x ∈ V, c x ∈ L x) ∧
    (∀ e ∈ E, c e.1 ≠ c e.2)

/-- The hypotheses in Thomassen's rooted extension theorem. -/
def ThomassenLists (D : DiskExpr) (L : ℕ → Finset ℕ) : Prop :=
  (∃ a, L D.root₁ = {a}) ∧
  (∃ b, L D.root₂ = {b}) ∧
  (∀ a b, L D.root₁ = {a} → L D.root₂ = {b} → a ≠ b) ∧
  (∀ x ∈ D.boundary.toFinset, x ≠ D.root₁ → x ≠ D.root₂ → 3 ≤ (L x).card) ∧
  (∀ x ∈ D.vertices, x ∉ D.boundary.toFinset → 5 ≤ (L x).card)

lemma boundary_glue_toFinset {left right : DiskExpr} {pre post rest : List ℕ}
    {u v : ℕ} (hl : left.boundary = pre ++ u :: v :: post)
    (hr : right.boundary = u :: v :: rest) :
    (DiskExpr.glue left right pre post rest u v).boundary.toFinset =
      left.boundary.toFinset ∪ right.boundary.toFinset := by
  change (pre ++ u :: rest.reverse ++ v :: post).toFinset =
    left.boundary.toFinset ∪ right.boundary.toFinset
  rw [hl, hr]
  ext x
  simp only [List.toFinset_append, List.toFinset_cons, List.toFinset_reverse,
    mem_union, mem_insert]
  tauto

lemma boundary_fan_toFinset (child : DiskExpr) (pref tail : List ℕ) (z : ℕ) :
    (DiskExpr.fan child pref tail z).boundary.toFinset = insert z pref.toFinset := by
  ext x
  simp [boundary]

lemma Valid.boundary_subset_vertices {D : DiskExpr} (hD : Valid D) :
    D.boundary.toFinset ⊆ D.vertices := by
  induction hD with
  | triangle hab hbc hca => simp [boundary, vertices]
  | @glue left right pre post rest u v hleft hright hbl hbr hr1 hr2 hinter hedge huv ihl ihr =>
      rw [boundary_glue_toFinset hbl hbr]
      intro x hx
      rw [mem_union] at hx
      simp only [vertices, mem_union]
      exact hx.elim (fun h => Or.inl (ihl h)) (fun h => Or.inr (ihr h))
  | @fan child pref tail z hchild hb hp hd hn hr1 hr2 hf ih =>
      rw [boundary_fan_toFinset]
      intro x hx
      rw [mem_insert] at hx
      simp only [vertices, mem_insert]
      rcases hx with rfl | hx
      · exact Or.inl rfl
      · exact Or.inr (ih (by
          rw [hb]
          simp only [List.toFinset_append, mem_union]
          exact Or.inl hx))

lemma Valid.root₁_mem_vertices {D : DiskExpr} (hD : Valid D) :
    D.root₁ ∈ D.vertices := by
  induction hD with
  | triangle => simp [root₁, vertices]
  | glue hleft hright hbl hbr hr1 hr2 hi he huv ihl ihr =>
      exact Finset.mem_union_left _ ihl
  | fan hchild hb hp hd hn hr1 hr2 hf ih =>
      exact Finset.mem_insert_of_mem ih

lemma Valid.root₂_mem_vertices {D : DiskExpr} (hD : Valid D) :
    D.root₂ ∈ D.vertices := by
  induction hD with
  | triangle => simp [root₂, vertices]
  | glue hleft hright hbl hbr hr1 hr2 hi he huv ihl ihr =>
      exact Finset.mem_union_left _ ihl
  | fan hchild hb hp hd hn hr1 hr2 hf ih =>
      exact Finset.mem_insert_of_mem ih

lemma Valid.edge_endpoints {D : DiskExpr} (hD : Valid D) {e : Edge}
    (he : e ∈ D.edges) : e.1 ∈ D.vertices ∧ e.2 ∈ D.vertices := by
  induction hD with
  | @triangle a b c hab hbc hca =>
      simp only [edges, mem_insert, mem_singleton] at he
      rcases he with rfl | rfl | rfl <;> simp [vertices]
  | @glue left right pre post rest u v hleft hright hbl hbr hr1 hr2 hi hedge huv ihl ihr =>
      rw [edges, mem_union] at he
      simp only [vertices, mem_union]
      rcases he with he | he
      · exact ⟨Or.inl (ihl he).1, Or.inl (ihl he).2⟩
      · exact ⟨Or.inr (ihr he).1, Or.inr (ihr he).2⟩
  | @fan child pref tail z hchild hb hp hd hn hr1 hr2 hf ih =>
      rw [edges, mem_union] at he
      simp only [vertices, mem_insert]
      rcases he with he | he
      · exact ⟨Or.inr (ih he).1, Or.inr (ih he).2⟩
      · obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp he
        exact ⟨Or.inl rfl, Or.inr (hn hx)⟩

end DiskExpr

/-! ## Elementary finite-list lemmas -/

lemma exists_mem_ne_ne {s : Finset ℕ} (hcard : 3 ≤ s.card) (a b : ℕ) :
    ∃ c ∈ s, c ≠ a ∧ c ≠ b := by
  have hlt : ({a, b} : Finset ℕ).card < s.card := by
    have hle : ({a, b} : Finset ℕ).card ≤ 2 := Finset.card_le_two
    omega
  obtain ⟨c, hcs, hc⟩ := Finset.exists_mem_notMem_of_card_lt_card hlt
  have hne : c ≠ a ∧ c ≠ b := by
    simpa only [mem_insert, mem_singleton, not_or] using hc
  exact ⟨c, hcs, hne.1, hne.2⟩

lemma card_sdiff_pair_ge_three {s : Finset ℕ} (hcard : 5 ≤ s.card) (a b : ℕ) :
    3 ≤ (s \ {a, b}).card := by
  have hpair : ({a, b} : Finset ℕ).card ≤ 2 := Finset.card_le_two
  have hle := Finset.le_card_sdiff ({a, b} : Finset ℕ) s
  omega

private lemma thomassen_triangle (a b c : ℕ) (hab : a ≠ b) (hbc : b ≠ c)
    (hca : c ≠ a) (L : ℕ → Finset ℕ)
    (hL : DiskExpr.ThomassenLists (DiskExpr.triangle a b c) L) :
    DiskExpr.HasListColoring (DiskExpr.triangle a b c).vertices
      (DiskExpr.triangle a b c).edges L := by
  rcases hL with ⟨⟨ca, hLa⟩, ⟨cb, hLb⟩, hne, hboundary, hinterior⟩
  have hcab : ca ≠ cb := hne ca cb hLa hLb
  have hcardc : 3 ≤ (L c).card := by
    apply hboundary c
    · simp [DiskExpr.boundary]
    · simpa [DiskExpr.root₁] using hca
    · simpa [DiskExpr.root₂] using hbc.symm
  obtain ⟨cc, hcc, hcca, hccb⟩ := exists_mem_ne_ne hcardc ca cb
  have hLa' : L a = {ca} := by simpa [DiskExpr.root₁] using hLa
  have hLb' : L b = {cb} := by simpa [DiskExpr.root₂] using hLb
  have hca_mem : ca ∈ L a := by
    simp [hLa']
  have hcb_mem : cb ∈ L b := by
    simp [hLb']
  let color : ℕ → ℕ := fun x => if x = a then ca else if x = b then cb else cc
  refine ⟨color, ?_, ?_⟩
  · intro x hx
    change x ∈ ({a, b, c} : Finset ℕ) at hx
    simp only [mem_insert, mem_singleton] at hx
    rcases hx with rfl | rfl | rfl
    · simpa [color] using hca_mem
    · simpa [color, hab.symm] using hcb_mem
    · simp only [color, if_neg hca, if_neg hbc.symm]
      exact hcc
  · intro e he
    change e ∈ ({(a, b), (b, c), (c, a)} : Finset Edge) at he
    simp only [mem_insert, mem_singleton] at he
    rcases he with rfl | rfl | rfl
    · simpa [color, hab, hab.symm] using hcab
    · simpa [color, hab.symm, hca, hbc, hbc.symm] using hccb.symm
    · simpa [color, hca, hca.symm, hbc.symm] using hcca

private lemma thomassen_glue {left right : DiskExpr} {pre post rest : List ℕ}
    {u v : ℕ} (hleft : left.Valid) (hright : right.Valid)
    (hbl : left.boundary = pre ++ u :: v :: post)
    (hbr : right.boundary = u :: v :: rest)
    (hr1 : right.root₁ = u) (hr2 : right.root₂ = v)
    (hinter : left.vertices ∩ right.vertices = {u, v})
    (hedge : (u, v) ∈ left.edges ∨ (v, u) ∈ left.edges) (huv : u ≠ v)
    (ihleft : ∀ L, left.ThomassenLists L →
      DiskExpr.HasListColoring left.vertices left.edges L)
    (ihright : ∀ L, right.ThomassenLists L →
      DiskExpr.HasListColoring right.vertices right.edges L)
    (L : ℕ → Finset ℕ)
    (hL : (DiskExpr.glue left right pre post rest u v).ThomassenLists L) :
    DiskExpr.HasListColoring
      (DiskExpr.glue left right pre post rest u v).vertices
      (DiskExpr.glue left right pre post rest u v).edges L := by
  rcases hL with ⟨hroot1, hroot2, hroots_ne, hboundary, hinterior⟩
  have hboundary_union := DiskExpr.boundary_glue_toFinset hbl hbr
  have hleft_lists : left.ThomassenLists L := by
    refine ⟨hroot1, hroot2, hroots_ne, ?_, ?_⟩
    · intro x hx hx1 hx2
      apply hboundary x
      · rw [hboundary_union]
        exact Finset.mem_union_left _ hx
      · exact hx1
      · exact hx2
    · intro x hxV hxB
      apply hinterior x
      · exact Finset.mem_union_left _ hxV
      · intro hxParent
        rw [hboundary_union, mem_union] at hxParent
        rcases hxParent with hxLeft | hxRight
        · exact hxB hxLeft
        · have hxBoth : x ∈ left.vertices ∩ right.vertices :=
            Finset.mem_inter.mpr ⟨hxV, hright.boundary_subset_vertices hxRight⟩
          rw [hinter] at hxBoth
          simp only [mem_insert, mem_singleton] at hxBoth
          rcases hxBoth with rfl | rfl
          · apply hxB
            rw [hbl]
            simp
          · apply hxB
            rw [hbl]
            simp
  obtain ⟨c₁, hc₁mem, hc₁edge⟩ := ihleft L hleft_lists
  have hcuv : c₁ u ≠ c₁ v := by
    rcases hedge with hedge | hedge
    · exact hc₁edge (u, v) hedge
    · exact (hc₁edge (v, u) hedge).symm
  let Lright : ℕ → Finset ℕ := fun x =>
    if x = u then {c₁ u} else if x = v then {c₁ v} else L x
  have hright_boundary_ne_left_root₁ {x : ℕ} (hxB : x ∈ right.boundary.toFinset)
      (hxu : x ≠ u) (hxv : x ≠ v) : x ≠ left.root₁ := by
    intro hx
    have hxBoth : x ∈ left.vertices ∩ right.vertices := Finset.mem_inter.mpr ⟨by
      rw [hx]
      exact hleft.root₁_mem_vertices, hright.boundary_subset_vertices hxB⟩
    rw [hinter] at hxBoth
    simp only [mem_insert, mem_singleton] at hxBoth
    exact hxBoth.elim hxu hxv
  have hright_boundary_ne_left_root₂ {x : ℕ} (hxB : x ∈ right.boundary.toFinset)
      (hxu : x ≠ u) (hxv : x ≠ v) : x ≠ left.root₂ := by
    intro hx
    have hxBoth : x ∈ left.vertices ∩ right.vertices := Finset.mem_inter.mpr ⟨by
      rw [hx]
      exact hleft.root₂_mem_vertices, hright.boundary_subset_vertices hxB⟩
    rw [hinter] at hxBoth
    simp only [mem_insert, mem_singleton] at hxBoth
    exact hxBoth.elim hxu hxv
  have hright_lists : right.ThomassenLists Lright := by
    refine ⟨⟨c₁ u, ?_⟩, ⟨c₁ v, ?_⟩, ?_, ?_, ?_⟩
    · simp [Lright, hr1]
    · simp [Lright, hr2, huv.symm]
    · intro a b ha hb
      have ha' : c₁ u = a := by
        have := congrArg (fun s : Finset ℕ => c₁ u ∈ s) ha
        simpa [Lright, hr1] using this.symm
      have hb' : c₁ v = b := by
        have := congrArg (fun s : Finset ℕ => c₁ v ∈ s) hb
        simpa [Lright, hr2, huv.symm] using this.symm
      simpa [ha', hb'] using hcuv
    · intro x hxB hx1 hx2
      have hxu : x ≠ u := by simpa [hr1] using hx1
      have hxv : x ≠ v := by simpa [hr2] using hx2
      simp only [Lright, if_neg hxu, if_neg hxv]
      apply hboundary x
      · rw [hboundary_union]
        exact Finset.mem_union_right _ hxB
      · exact hright_boundary_ne_left_root₁ hxB hxu hxv
      · exact hright_boundary_ne_left_root₂ hxB hxu hxv
    · intro x hxV hxB
      have hxu : x ≠ u := by
        intro hx
        apply hxB
        rw [hbr, hx]
        simp
      have hxv : x ≠ v := by
        intro hx
        apply hxB
        rw [hbr, hx]
        simp
      simp only [Lright, if_neg hxu, if_neg hxv]
      apply hinterior x
      · exact Finset.mem_union_right _ hxV
      · intro hxParent
        rw [hboundary_union, mem_union] at hxParent
        rcases hxParent with hxLeft | hxRight
        · have hxBoth : x ∈ left.vertices ∩ right.vertices :=
            Finset.mem_inter.mpr ⟨hleft.boundary_subset_vertices hxLeft, hxV⟩
          rw [hinter] at hxBoth
          simp only [mem_insert, mem_singleton] at hxBoth
          exact hxBoth.elim hxu hxv
        · exact hxB hxRight
  obtain ⟨c₂, hc₂mem, hc₂edge⟩ := ihright Lright hright_lists
  have hc₂u : c₂ u = c₁ u := by
    have huV : u ∈ right.vertices := by
      rw [← hr1]
      exact hright.root₁_mem_vertices
    have := hc₂mem u huV
    simpa [Lright] using this
  have hc₂v : c₂ v = c₁ v := by
    have hvV : v ∈ right.vertices := by
      rw [← hr2]
      exact hright.root₂_mem_vertices
    have := hc₂mem v hvV
    simpa [Lright, huv.symm] using this
  let color : ℕ → ℕ := fun x => if x ∈ left.vertices then c₁ x else c₂ x
  have color_eq_right {x : ℕ} (hxR : x ∈ right.vertices) : color x = c₂ x := by
    by_cases hxL : x ∈ left.vertices
    · have hxBoth : x ∈ left.vertices ∩ right.vertices := Finset.mem_inter.mpr ⟨hxL, hxR⟩
      rw [hinter] at hxBoth
      simp only [mem_insert, mem_singleton] at hxBoth
      rcases hxBoth with rfl | rfl
      · simp [color, hxL, hc₂u]
      · simp [color, hxL, hc₂v]
    · simp [color, hxL]
  refine ⟨color, ?_, ?_⟩
  · intro x hxV
    change x ∈ left.vertices ∪ right.vertices at hxV
    rw [mem_union] at hxV
    rcases hxV with hxL | hxR
    · simpa [color, hxL] using hc₁mem x hxL
    · have hc2L : c₂ x ∈ Lright x := hc₂mem x hxR
      have hxAgreement := color_eq_right hxR
      by_cases hxu : x = u
      · subst x
        rw [hxAgreement, hc₂u]
        exact hc₁mem u (by
          have huBoth : u ∈ left.vertices ∩ right.vertices := by
            rw [hinter]
            simp
          exact (Finset.mem_inter.mp huBoth).1)
      · by_cases hxv : x = v
        · subst x
          rw [hxAgreement, hc₂v]
          exact hc₁mem v (by
            have hvBoth : v ∈ left.vertices ∩ right.vertices := by
              rw [hinter]
              simp
            exact (Finset.mem_inter.mp hvBoth).1)
        · rw [hxAgreement]
          simpa [Lright, hxu, hxv] using hc2L
  · intro e he
    change e ∈ left.edges ∪ right.edges at he
    rw [mem_union] at he
    rcases he with heL | heR
    · have hend := hleft.edge_endpoints heL
      simpa [color, hend.1, hend.2] using hc₁edge e heL
    · have hend := hright.edge_endpoints heR
      rw [color_eq_right hend.1, color_eq_right hend.2]
      exact hc₂edge e heR

private lemma thomassen_fan {child : DiskExpr} {pref tail : List ℕ} {z : ℕ}
    (hchild : child.Valid) (hb : child.boundary = pref ++ tail)
    (hpref : 2 ≤ pref.length) (hdisjoint : Disjoint pref.toFinset tail.toFinset)
    (hneighbors : (child.fanNeighbors pref tail).toFinset ⊆ child.vertices)
    (hroot1pref : child.root₁ ∈ pref.toFinset)
    (hroot2pref : child.root₂ ∈ pref.toFinset) (hfresh : z ∉ child.vertices)
    (ih : ∀ L, child.ThomassenLists L →
      DiskExpr.HasListColoring child.vertices child.edges L)
    (L : ℕ → Finset ℕ) (hL : (DiskExpr.fan child pref tail z).ThomassenLists L) :
    DiskExpr.HasListColoring (DiskExpr.fan child pref tail z).vertices
      (DiskExpr.fan child pref tail z).edges L := by
  rcases hL with ⟨⟨q, hq⟩, hroot2, hroots_ne, hboundary, hinterior⟩
  have hzRoot1 : z ≠ child.root₁ := by
    intro hz
    apply hfresh
    rw [hz]
    exact hchild.root₁_mem_vertices
  have hzRoot2 : z ≠ child.root₂ := by
    intro hz
    apply hfresh
    rw [hz]
    exact hchild.root₂_mem_vertices
  have hcardz : 3 ≤ (L z).card := by
    apply hboundary z
    · rw [DiskExpr.boundary_fan_toFinset]
      simp
    · exact hzRoot1
    · exact hzRoot2
  obtain ⟨x, hxL, hxq, _⟩ := exists_mem_ne_ne hcardz q q
  obtain ⟨y, hyL, hyq, hyx⟩ := exists_mem_ne_ne hcardz q x
  have hq' : L child.root₁ = {q} := by
    simpa [DiskExpr.root₁] using hq
  let Lchild : ℕ → Finset ℕ := fun t =>
    if t ∈ tail.toFinset then L t \ {x, y} else L t
  have hroot1notTail : child.root₁ ∉ tail.toFinset := by
    exact fun ht => Finset.disjoint_left.mp hdisjoint hroot1pref ht
  have hroot2notTail : child.root₂ ∉ tail.toFinset := by
    exact fun ht => Finset.disjoint_left.mp hdisjoint hroot2pref ht
  have hchild_lists : child.ThomassenLists Lchild := by
    refine ⟨⟨q, ?_⟩, ?_, ?_, ?_, ?_⟩
    · dsimp [Lchild]
      rw [if_neg hroot1notTail]
      exact hq'
    · rcases hroot2 with ⟨r, hr⟩
      have hr' : L child.root₂ = {r} := by
        simpa [DiskExpr.root₂] using hr
      refine ⟨r, ?_⟩
      dsimp [Lchild]
      rw [if_neg hroot2notTail]
      exact hr'
    · intro a b ha hb'
      apply hroots_ne a b
      · have : L child.root₁ = {a} := by
          dsimp [Lchild] at ha
          rw [if_neg hroot1notTail] at ha
          exact ha
        simpa [DiskExpr.root₁] using this
      · have : L child.root₂ = {b} := by
          dsimp [Lchild] at hb'
          rw [if_neg hroot2notTail] at hb'
          exact hb'
        simpa [DiskExpr.root₂] using this
    · intro t htB ht1 ht2
      rw [hb, List.toFinset_append, mem_union] at htB
      rcases htB with htPref | htTail
      · have htNotTail : t ∉ tail.toFinset := by
          exact fun ht => Finset.disjoint_left.mp hdisjoint htPref ht
        simp only [Lchild, if_neg htNotTail]
        apply hboundary t
        · rw [DiskExpr.boundary_fan_toFinset]
          exact mem_insert_of_mem htPref
        · exact ht1
        · exact ht2
      · have htV : t ∈ child.vertices := hchild.boundary_subset_vertices (by
          rw [hb, List.toFinset_append]
          exact Finset.mem_union_right _ htTail)
        have htz : t ≠ z := by
          intro htz
          apply hfresh
          rwa [← htz]
        have htNotPref : t ∉ pref.toFinset := by
          exact fun ht => Finset.disjoint_left.mp hdisjoint ht htTail
        have hcard : 5 ≤ (L t).card := by
          apply hinterior t
          · exact mem_insert_of_mem htV
          · rw [DiskExpr.boundary_fan_toFinset]
            simp [htz, htNotPref]
        simp only [Lchild, if_pos htTail]
        exact card_sdiff_pair_ge_three hcard x y
    · intro t htV htB
      have htNotTail : t ∉ tail.toFinset := by
        intro htTail
        apply htB
        rw [hb, List.toFinset_append]
        exact Finset.mem_union_right _ htTail
      have htz : t ≠ z := by
        intro htz
        apply hfresh
        rwa [← htz]
      have htNotPref : t ∉ pref.toFinset := by
        intro htPref
        apply htB
        rw [hb, List.toFinset_append]
        exact Finset.mem_union_left _ htPref
      simp only [Lchild, if_neg htNotTail]
      apply hinterior t
      · exact mem_insert_of_mem htV
      · rw [DiskExpr.boundary_fan_toFinset]
        simp [htz, htNotPref]
  obtain ⟨c, hcmem, hcedge⟩ := ih Lchild hchild_lists
  have hpref_ne : pref ≠ [] := by
    intro hp
    simp [hp] at hpref
  let w := pref.getLast hpref_ne
  have hwPref : w ∈ pref.toFinset := by
    exact List.mem_toFinset.mpr (List.getLast_mem hpref_ne)
  have hwNeighbor : w ∈ (child.fanNeighbors pref tail).toFinset := by
    have hlast : pref.getLast? = some w := List.getLast?_eq_getLast_of_ne_nil hpref_ne
    simp [DiskExpr.fanNeighbors, hlast]
  have hwV : w ∈ child.vertices := hneighbors hwNeighbor
  let zcolor : ℕ := if c w = x then y else x
  have hzcolor_mem : zcolor ∈ L z := by
    by_cases hcw : c w = x
    · simpa [zcolor, hcw] using hyL
    · simpa [zcolor, hcw] using hxL
  have hzcolor_ne_w : zcolor ≠ c w := by
    by_cases hcw : c w = x
    · simpa [zcolor, hcw] using hyx
    · simpa [zcolor, hcw] using Ne.symm hcw
  have hroot_color : c child.root₁ = q := by
    have hc := hcmem child.root₁ hchild.root₁_mem_vertices
    have : c child.root₁ ∈ ({q} : Finset ℕ) := by
      dsimp [Lchild] at hc
      rw [if_neg hroot1notTail] at hc
      simpa [hq'] using hc
    simpa using this
  have hzcolor_ne_root : zcolor ≠ c child.root₁ := by
    rw [hroot_color]
    by_cases hcw : c w = x
    · simpa [zcolor, hcw] using hyq
    · simpa [zcolor, hcw] using hxq
  have hzcolor_ne_tail {t : ℕ} (htTail : t ∈ tail.toFinset) : zcolor ≠ c t := by
    have hc := hcmem t (hchild.boundary_subset_vertices (by
      rw [hb, List.toFinset_append]
      exact Finset.mem_union_right _ htTail))
    have hdiff : c t ∈ L t \ {x, y} := by
      dsimp [Lchild] at hc
      rw [if_pos htTail] at hc
      exact hc
    have hne := (Finset.mem_sdiff.mp hdiff).2
    simp only [mem_insert, mem_singleton, not_or] at hne
    by_cases hcw : c w = x
    · simpa [zcolor, hcw] using Ne.symm hne.2
    · simpa [zcolor, hcw] using Ne.symm hne.1
  have hzcolor_ne_neighbor {t : ℕ}
      (ht : t ∈ (child.fanNeighbors pref tail).toFinset) : zcolor ≠ c t := by
    have hlast : pref.getLast? = some w := List.getLast?_eq_getLast_of_ne_nil hpref_ne
    have ht' : t = w ∨ t = child.root₁ ∨ t ∈ tail.toFinset := by
      simpa [DiskExpr.fanNeighbors, hlast] using ht
    rcases ht' with rfl | rfl | htTail
    · exact hzcolor_ne_w
    · exact hzcolor_ne_root
    · exact hzcolor_ne_tail htTail
  let color : ℕ → ℕ := fun t => if t = z then zcolor else c t
  refine ⟨color, ?_, ?_⟩
  · intro t htV
    change t ∈ insert z child.vertices at htV
    rw [mem_insert] at htV
    rcases htV with rfl | htChild
    · simpa [color] using hzcolor_mem
    · have htz : t ≠ z := by
        intro htz
        apply hfresh
        rwa [← htz]
      have hc := hcmem t htChild
      have hcL : c t ∈ L t := by
        by_cases htTail : t ∈ tail.toFinset
        · have hdiff : c t ∈ L t \ {x, y} := by
            dsimp [Lchild] at hc
            rw [if_pos htTail] at hc
            exact hc
          exact (Finset.mem_sdiff.mp hdiff).1
        · dsimp [Lchild] at hc
          rw [if_neg htTail] at hc
          exact hc
      simpa [color, htz] using hcL
  · intro e he
    change e ∈ child.edges ∪
      (child.fanNeighbors pref tail).toFinset.image (fun t => (z, t)) at he
    rw [mem_union] at he
    rcases he with heChild | heStar
    · have hend := hchild.edge_endpoints heChild
      have hne1 : e.1 ≠ z := fun h => hfresh (h ▸ hend.1)
      have hne2 : e.2 ≠ z := fun h => hfresh (h ▸ hend.2)
      simpa [color, hne1, hne2] using hcedge e heChild
    · obtain ⟨t, ht, rfl⟩ := Finset.mem_image.mp heStar
      have htV : t ∈ child.vertices := hneighbors ht
      have htz : t ≠ z := fun h => hfresh (h ▸ htV)
      simpa [color, htz] using hzcolor_ne_neighbor ht

/-- Thomassen's rooted extension theorem for the recursive plane-disc
certificate. -/
theorem thomassen_extension {D : DiskExpr} (hD : D.Valid)
    (L : ℕ → Finset ℕ) (hL : D.ThomassenLists L) :
    DiskExpr.HasListColoring D.vertices D.edges L := by
  revert L
  induction hD with
  | @triangle a b c hab hbc hca =>
      intro L hL
      exact thomassen_triangle a b c hab hbc hca L hL
  | @glue left right pre post rest u v hleft hright hbl hbr hr1 hr2 hinter hedge huv ihl ihr =>
      intro L hL
      exact thomassen_glue hleft hright hbl hbr hr1 hr2 hinter hedge huv
        ihl ihr L hL
  | @fan child pref tail z hchild hb hp hd hn hr1 hr2 hf ih =>
      intro L hL
      exact thomassen_fan hchild hb hp hd hn hr1 hr2 hf ih L hL

lemma DiskExpr.Valid.root₁_mem_boundary {D : DiskExpr} (hD : D.Valid) :
    D.root₁ ∈ D.boundary.toFinset := by
  induction hD with
  | triangle => simp [DiskExpr.root₁, DiskExpr.boundary]
  | @glue left right pre post rest u v hl hr hbl hbr hr1 hr2 hi he huv ihl ihr =>
      rw [DiskExpr.boundary_glue_toFinset hbl hbr]
      exact mem_union_left _ ihl
  | @fan child pref tail z hc hb hp hd hn hr1 hr2 hf ih =>
      rw [DiskExpr.boundary_fan_toFinset]
      exact mem_insert_of_mem hr1

lemma DiskExpr.Valid.root₂_mem_boundary {D : DiskExpr} (hD : D.Valid) :
    D.root₂ ∈ D.boundary.toFinset := by
  induction hD with
  | triangle => simp [DiskExpr.root₂, DiskExpr.boundary]
  | @glue left right pre post rest u v hl hr hbl hbr hr1 hr2 hi he huv ihl ihr =>
      rw [DiskExpr.boundary_glue_toFinset hbl hbr]
      exact mem_union_left _ ihl
  | @fan child pref tail z hc hb hp hd hn hr1 hr2 hf ih =>
      rw [DiskExpr.boundary_fan_toFinset]
      exact mem_insert_of_mem hr2

/-! ## Rooted edge sums of plane discs -/

inductive PlaneExpr where
  | disk (D : DiskExpr)
  | edgeSum (left right : PlaneExpr)

namespace PlaneExpr

def root₁ : PlaneExpr → ℕ
  | .disk D => D.root₁
  | .edgeSum left _ => left.root₁

def root₂ : PlaneExpr → ℕ
  | .disk D => D.root₂
  | .edgeSum left _ => left.root₂

def vertices : PlaneExpr → Finset ℕ
  | .disk D => D.vertices
  | .edgeSum left right => left.vertices ∪ right.vertices

def edges : PlaneExpr → Finset Edge
  | .disk D => D.edges
  | .edgeSum left right => left.edges ∪ right.edges

/-- A recursive plane certificate.  `edgeSum` glues two already embedded
plane graphs along exactly their common root edge. -/
inductive Valid : PlaneExpr → Prop where
  | disk {D : DiskExpr} (hD : D.Valid) : Valid (.disk D)
  | edgeSum {left right : PlaneExpr} (hleft : Valid left) (hright : Valid right)
      (hroot₁ : right.root₁ = left.root₁) (hroot₂ : right.root₂ = left.root₂)
      (hinter : left.vertices ∩ right.vertices = {left.root₁, left.root₂}) :
      Valid (.edgeSum left right)

lemma disk_root_ne {D : DiskExpr} (hD : D.Valid) : D.root₁ ≠ D.root₂ := by
  induction hD with
  | triangle hab => exact hab
  | glue hleft hright hbl hbr hr1 hr2 hinter hedge huv ihl ihr => exact ihl
  | fan hchild hb hp hd hn hr1 hr2 hf ih => exact ih

lemma Valid.root_ne {P : PlaneExpr} (hP : P.Valid) : P.root₁ ≠ P.root₂ := by
  induction hP with
  | disk hD => exact disk_root_ne hD
  | edgeSum hleft hright hr1 hr2 hinter ihl ihr => exact ihl

lemma Valid.root₁_mem_vertices {P : PlaneExpr} (hP : P.Valid) : P.root₁ ∈ P.vertices := by
  induction hP with
  | disk hD => exact hD.root₁_mem_vertices
  | edgeSum hleft hright hr1 hr2 hinter ihl ihr => exact mem_union_left _ ihl

lemma Valid.root₂_mem_vertices {P : PlaneExpr} (hP : P.Valid) : P.root₂ ∈ P.vertices := by
  induction hP with
  | disk hD => exact hD.root₂_mem_vertices
  | edgeSum hleft hright hr1 hr2 hinter ihl ihr => exact mem_union_left _ ihl

lemma Valid.edge_endpoints {P : PlaneExpr} (hP : P.Valid) {e : Edge}
    (he : e ∈ P.edges) : e.1 ∈ P.vertices ∧ e.2 ∈ P.vertices := by
  induction hP with
  | disk hD => exact hD.edge_endpoints he
  | @edgeSum left right hleft hright hr1 hr2 hinter ihl ihr =>
      rw [edges, mem_union] at he
      simp only [vertices, mem_union]
      rcases he with he | he
      · exact ⟨Or.inl (ihl he).1, Or.inl (ihl he).2⟩
      · exact ⟨Or.inr (ihr he).1, Or.inr (ihr he).2⟩

/-- The rooted form used to color edge sums: the two roots have distinct
singleton lists and every other vertex has a list of at least five colors. -/
def RootedFiveLists (P : PlaneExpr) (L : ℕ → Finset ℕ) : Prop :=
  (∃ a, L P.root₁ = {a}) ∧
  (∃ b, L P.root₂ = {b}) ∧
  (∀ a b, L P.root₁ = {a} → L P.root₂ = {b} → a ≠ b) ∧
  (∀ x ∈ P.vertices, x ≠ P.root₁ → x ≠ P.root₂ → 5 ≤ (L x).card)

private lemma disk_rooted_five_lists {D : DiskExpr} {L : ℕ → Finset ℕ}
    (hD : D.Valid) (hL : (PlaneExpr.disk D).RootedFiveLists L) :
    D.ThomassenLists L := by
  rcases hL with ⟨h1, h2, hne, hcard⟩
  refine ⟨h1, h2, hne, ?_, ?_⟩
  · intro x hxB hx1 hx2
    exact (hcard x (hD.boundary_subset_vertices hxB) hx1 hx2).trans' (by omega)
  · intro x hxV hxB
    by_cases hx1 : x = D.root₁
    · subst x
      exfalso
      exact hxB hD.root₁_mem_boundary
    · by_cases hx2 : x = D.root₂
      · subst x
        exfalso
        exact hxB hD.root₂_mem_boundary
      · exact hcard x hxV hx1 hx2

/-- Rooted 5-list extension for recursive edge sums. -/
theorem rooted_five_extension {P : PlaneExpr} (hP : P.Valid)
    (L : ℕ → Finset ℕ) (hL : P.RootedFiveLists L) :
    DiskExpr.HasListColoring P.vertices P.edges L := by
  revert L
  induction hP with
  | @disk D hD =>
      intro L hL
      exact thomassen_extension hD L (disk_rooted_five_lists hD hL)
  | @edgeSum left right hleft hright hr1 hr2 hinter ihleft ihright =>
      intro L hL
      rcases hL with ⟨hroot1, hroot2, hroots_ne, hcard⟩
      have hleftLists : left.RootedFiveLists L := by
        refine ⟨hroot1, hroot2, hroots_ne, ?_⟩
        intro x hxV hx1 hx2
        exact hcard x (mem_union_left _ hxV) hx1 hx2
      obtain ⟨c₁, hc₁mem, hc₁edge⟩ := ihleft L hleftLists
      have hleftRoots : left.root₁ ∈ left.vertices ∩ right.vertices := by
        rw [hinter]
        simp
      have hleftRoot2s : left.root₂ ∈ left.vertices ∩ right.vertices := by
        rw [hinter]
        simp
      have hcRootNe : c₁ left.root₁ ≠ c₁ left.root₂ := by
        rcases hroot1 with ⟨a, ha⟩
        rcases hroot2 with ⟨b, hb⟩
        have hab := hroots_ne a b ha hb
        have ha' : L left.root₁ = {a} := by simpa [PlaneExpr.root₁] using ha
        have hb' : L left.root₂ = {b} := by simpa [PlaneExpr.root₂] using hb
        have hca : c₁ left.root₁ = a := by
          have := hc₁mem left.root₁ hleft.root₁_mem_vertices
          rw [ha'] at this
          simpa using this
        have hcb : c₁ left.root₂ = b := by
          have := hc₁mem left.root₂ hleft.root₂_mem_vertices
          rw [hb'] at this
          simpa using this
        simpa [hca, hcb] using hab
      let Lright : ℕ → Finset ℕ := fun x =>
        if x = right.root₁ then {c₁ left.root₁}
        else if x = right.root₂ then {c₁ left.root₂} else L x
      have hrightLists : right.RootedFiveLists Lright := by
        refine ⟨⟨c₁ left.root₁, by simp [Lright]⟩,
          ⟨c₁ left.root₂, by simp [Lright, hright.root_ne.symm]⟩, ?_, ?_⟩
        · intro a b ha hb
          have ha' : c₁ left.root₁ = a := by
            have := congrArg (fun s : Finset ℕ => c₁ left.root₁ ∈ s) ha
            simpa [Lright] using this.symm
          have hb' : c₁ left.root₂ = b := by
            have := congrArg (fun s : Finset ℕ => c₁ left.root₂ ∈ s) hb
            simpa [Lright, hright.root_ne.symm] using this.symm
          simpa [ha', hb'] using hcRootNe
        · intro x hxV hx1 hx2
          simp only [Lright, if_neg hx1, if_neg hx2]
          apply hcard x (mem_union_right _ hxV)
          · intro hx
            have hxBoth : x ∈ left.vertices ∩ right.vertices :=
              mem_inter.mpr ⟨hx ▸ hleft.root₁_mem_vertices, hxV⟩
            rw [hinter] at hxBoth
            simp only [mem_insert, mem_singleton] at hxBoth
            rcases hxBoth with h | h
            · exact hx1 (h.trans hr1.symm)
            · exact hx2 (h.trans hr2.symm)
          · intro hx
            have hxBoth : x ∈ left.vertices ∩ right.vertices :=
              mem_inter.mpr ⟨hx ▸ hleft.root₂_mem_vertices, hxV⟩
            rw [hinter] at hxBoth
            simp only [mem_insert, mem_singleton] at hxBoth
            rcases hxBoth with h | h
            · exact hx1 (h.trans hr1.symm)
            · exact hx2 (h.trans hr2.symm)
      obtain ⟨c₂, hc₂mem, hc₂edge⟩ := ihright Lright hrightLists
      have hc₂root1 : c₂ right.root₁ = c₁ left.root₁ := by
        have := hc₂mem right.root₁ hright.root₁_mem_vertices
        simpa [Lright] using this
      have hc₂root2 : c₂ right.root₂ = c₁ left.root₂ := by
        have := hc₂mem right.root₂ hright.root₂_mem_vertices
        simpa [Lright, hright.root_ne.symm] using this
      let color : ℕ → ℕ := fun x => if x ∈ left.vertices then c₁ x else c₂ x
      have color_eq_right {x : ℕ} (hxR : x ∈ right.vertices) : color x = c₂ x := by
        by_cases hxL : x ∈ left.vertices
        · have hxBoth : x ∈ left.vertices ∩ right.vertices := mem_inter.mpr ⟨hxL, hxR⟩
          rw [hinter] at hxBoth
          simp only [mem_insert, mem_singleton] at hxBoth
          rcases hxBoth with rfl | rfl
          · simp [color, ← hr1, hc₂root1]
          · simp [color, ← hr2, hc₂root2]
        · simp [color, hxL]
      refine ⟨color, ?_, ?_⟩
      · intro x hxV
        change x ∈ left.vertices ∪ right.vertices at hxV
        rw [mem_union] at hxV
        rcases hxV with hxL | hxR
        · simpa [color, hxL] using hc₁mem x hxL
        · have hc2 := hc₂mem x hxR
          rw [color_eq_right hxR]
          by_cases hx1 : x = right.root₁
          · subst x
            rw [hc₂root1]
            simpa [hr1] using hc₁mem left.root₁ hleft.root₁_mem_vertices
          · by_cases hx2 : x = right.root₂
            · subst x
              rw [hc₂root2]
              simpa [hr2] using hc₁mem left.root₂ hleft.root₂_mem_vertices
            · simpa [Lright, hx1, hx2] using hc2
      · intro e he
        change e ∈ left.edges ∪ right.edges at he
        rw [mem_union] at he
        rcases he with heL | heR
        · have hend := hleft.edge_endpoints heL
          simpa [color, hend.1, hend.2] using hc₁edge e heL
        · have hend := hright.edge_endpoints heR
          rw [color_eq_right hend.1, color_eq_right hend.2]
          exact hc₂edge e heR

end PlaneExpr

lemma PlaneExpr.edges_left_subset (left right : PlaneExpr) :
    left.edges ⊆ (PlaneExpr.edgeSum left right).edges :=
  Finset.subset_union_left

lemma PlaneExpr.edges_right_subset (left right : PlaneExpr) :
    right.edges ⊆ (PlaneExpr.edgeSum left right).edges :=
  Finset.subset_union_right

/-! ## Planar graphs and the five-list upper bound -/

/-- A kernel-checkable finite planarity certificate: the graph embeds as a
subgraph of a recursive plane triangulation.  This is equivalent to the usual
topological definition for finite simple graphs, by planar augmentation to a
triangulation. -/
structure PlanarCertificate {V : Type*} (G : SimpleGraph V) where
  plane : PlaneExpr
  valid : plane.Valid
  embed : V ↪ ℕ
  vertex_mem : ∀ v, embed v ∈ plane.vertices
  adj_sub : ∀ {v w}, G.Adj v w → DiskExpr.EdgeAdj plane.edges (embed v) (embed w)

def IsPlanar {V : Type*} (G : SimpleGraph V) : Prop :=
  Nonempty (PlanarCertificate G)

private lemma plane_five_choosable {P : PlaneExpr} (hP : P.Valid)
    (L : ℕ → Finset ℕ) (hcard : ∀ x, (L x).card = 5) :
    DiskExpr.HasListColoring P.vertices P.edges L := by
  have hroot1card : 3 ≤ (L P.root₁).card := by rw [hcard]; omega
  have hroot2card : 3 ≤ (L P.root₂).card := by rw [hcard]; omega
  obtain ⟨a, haL⟩ : ∃ a, a ∈ L P.root₁ := by
    exact Finset.card_pos.mp (by rw [hcard]; omega)
  obtain ⟨b, hbL, hba, _⟩ := exists_mem_ne_ne hroot2card a a
  let L' : ℕ → Finset ℕ := fun x =>
    if x = P.root₁ then {a} else if x = P.root₂ then {b} else L x
  have hrooted : P.RootedFiveLists L' := by
    refine ⟨⟨a, by simp [L']⟩, ⟨b, by simp [L', hP.root_ne.symm]⟩, ?_, ?_⟩
    · intro x y hx hy
      have hx' : a = x := by
        have := congrArg (fun s : Finset ℕ => a ∈ s) hx
        simpa [L'] using this
      have hy' : b = y := by
        have := congrArg (fun s : Finset ℕ => b ∈ s) hy
        simpa [L', hP.root_ne.symm] using this
      simpa [← hx', ← hy'] using hba.symm
    · intro x hxV hx1 hx2
      simp only [L', if_neg hx1, if_neg hx2]
      rw [hcard]
  obtain ⟨c, hcmem, hcedge⟩ := P.rooted_five_extension hP L' hrooted
  refine ⟨c, ?_, hcedge⟩
  intro x hxV
  have hc := hcmem x hxV
  by_cases hx1 : x = P.root₁
  · subst x
    have : c P.root₁ = a := by simpa [L'] using hc
    simpa [this] using haL
  · by_cases hx2 : x = P.root₂
    · subst x
      have : c P.root₂ = b := by simpa [L', hP.root_ne.symm] using hc
      simpa [this] using hbL
    · simpa [L', hx1, hx2] using hc

/-- Thomassen's theorem: every finite planar graph is 5-choosable. -/
theorem planar_isFiveChoosable {V : Type*} [Fintype V] (G : SimpleGraph V)
    (hG : IsPlanar G) : Erdos753.IsKChoosable G 5 := by
  classical
  rcases hG with ⟨hG⟩
  intro lists hlists
  let planeLists : ℕ → Finset ℕ := fun x =>
    if h : ∃ v, hG.embed v = x then lists (Classical.choose h) else Finset.range 5
  have hplaneCard : ∀ x, (planeLists x).card = 5 := by
    intro x
    by_cases h : ∃ v, hG.embed v = x
    · simp [planeLists, h, hlists]
    · simp [planeLists, h]
  obtain ⟨c, hcmem, hcedge⟩ := plane_five_choosable hG.valid planeLists hplaneCard
  have himage_mem (v : V) : c (hG.embed v) ∈ lists v := by
    have hvPlane := hcmem (hG.embed v) (hG.vertex_mem v)
    have hex : ∃ w, hG.embed w = hG.embed v := ⟨v, rfl⟩
    have hchoose : Classical.choose hex = v :=
      hG.embed.injective (Classical.choose_spec hex)
    simpa [planeLists, hex, hchoose] using hvPlane
  let coloring : G.Coloring ℕ := SimpleGraph.Coloring.mk (fun v => c (hG.embed v)) (by
    intro v w hvw
    rcases hG.adj_sub hvw with he | he
    · exact hcedge (hG.embed v, hG.embed w) he
    · exact (hcedge (hG.embed w, hG.embed v) he).symm)
  exact ⟨coloring, himage_mem⟩

theorem planar_listChromaticNumber_le_five {V : Type*} [Fintype V]
    (G : SimpleGraph V) (hG : IsPlanar G) :
    Erdos753.listChromaticNumber G ≤ 5 :=
  Erdos753.listChromaticNumber_le (planar_isFiveChoosable G hG)

/-! ## Gutner's planar non-4-choosable graph -/

def blockBase (i : ℕ) : ℕ := 2 + 7 * i

/-- One of Gutner's twelve blocks.  Its vertices, in order, are
`w,x₁,x₂,x₃,y₁,y₂,y₃`; vertices `0,1` are the common roots. -/
def gutnerBlock (i : ℕ) : DiskExpr :=
  let w := blockBase i
  let x₁ := w + 1
  let x₂ := w + 2
  let x₃ := w + 3
  let y₁ := w + 4
  let y₂ := w + 5
  let y₃ := w + 6
  let d₀ := DiskExpr.triangle 0 1 x₂
  let d₁ := DiskExpr.glue d₀ (DiskExpr.triangle 1 x₂ x₃) [0] [] [x₃] 1 x₂
  let d₂ := DiskExpr.fan d₁ [0, 1, x₃] [x₂] x₁
  let d₃ := DiskExpr.fan d₂ [0, 1] [x₃, x₁] w
  let d₄ := DiskExpr.glue d₃ (DiskExpr.triangle 1 w y₃) [0] [] [y₃] 1 w
  let d₅ := DiskExpr.fan d₄ [0, 1, y₃] [w] y₁
  DiskExpr.fan d₅ [0, 1] [y₃, y₁] y₂

lemma gutnerBlock_valid (i : Fin 12) : (gutnerBlock i).Valid := by
  fin_cases i <;> (
    unfold gutnerBlock blockBase
    apply DiskExpr.Valid.fan
    · apply DiskExpr.Valid.fan
      · apply DiskExpr.Valid.glue
        · apply DiskExpr.Valid.fan
          · apply DiskExpr.Valid.fan
            · apply DiskExpr.Valid.glue
              · apply DiskExpr.Valid.triangle <;> decide
              · apply DiskExpr.Valid.triangle <;> decide
              · decide
              · decide
              · decide
              · decide
              · decide
              · decide
              · decide
            · decide
            · decide
            · decide
            · decide
            · decide
            · decide
            · decide
          · decide
          · decide
          · decide
          · decide
          · decide
          · decide
          · decide
        · apply DiskExpr.Valid.triangle <;> decide
        · decide
        · decide
        · decide
        · decide
        · decide
        · decide
        · decide
      · decide
      · decide
      · decide
      · decide
      · decide
      · decide
      · decide
    · decide
    · decide
    · decide
    · decide
    · decide
    · decide
    · decide)

def gutnerPlane01 : PlaneExpr :=
  .edgeSum (.disk (gutnerBlock 0)) (.disk (gutnerBlock 1))
def gutnerPlane23 : PlaneExpr :=
  .edgeSum (.disk (gutnerBlock 2)) (.disk (gutnerBlock 3))
def gutnerPlane45 : PlaneExpr :=
  .edgeSum (.disk (gutnerBlock 4)) (.disk (gutnerBlock 5))
def gutnerPlane67 : PlaneExpr :=
  .edgeSum (.disk (gutnerBlock 6)) (.disk (gutnerBlock 7))
def gutnerPlane89 : PlaneExpr :=
  .edgeSum (.disk (gutnerBlock 8)) (.disk (gutnerBlock 9))
def gutnerPlane1011 : PlaneExpr :=
  .edgeSum (.disk (gutnerBlock 10)) (.disk (gutnerBlock 11))
def gutnerPlane03 : PlaneExpr := .edgeSum gutnerPlane01 gutnerPlane23
def gutnerPlane47 : PlaneExpr := .edgeSum gutnerPlane45 gutnerPlane67
def gutnerPlane811 : PlaneExpr := .edgeSum gutnerPlane89 gutnerPlane1011
def gutnerPlane411 : PlaneExpr := .edgeSum gutnerPlane47 gutnerPlane811
def gutnerPlane : PlaneExpr := .edgeSum gutnerPlane03 gutnerPlane411

lemma gutnerPlane_valid : gutnerPlane.Valid := by
  unfold gutnerPlane gutnerPlane03 gutnerPlane411 gutnerPlane47 gutnerPlane811
    gutnerPlane01 gutnerPlane23 gutnerPlane45 gutnerPlane67 gutnerPlane89 gutnerPlane1011
  apply PlaneExpr.Valid.edgeSum
  · apply PlaneExpr.Valid.edgeSum
    · apply PlaneExpr.Valid.edgeSum
      · exact .disk (gutnerBlock_valid 0)
      · exact .disk (gutnerBlock_valid 1)
      · decide
      · decide
      · decide
    · apply PlaneExpr.Valid.edgeSum
      · exact .disk (gutnerBlock_valid 2)
      · exact .disk (gutnerBlock_valid 3)
      · decide
      · decide
      · decide
    · decide
    · decide
    · decide
  · apply PlaneExpr.Valid.edgeSum
    · apply PlaneExpr.Valid.edgeSum
      · apply PlaneExpr.Valid.edgeSum
        · exact .disk (gutnerBlock_valid 4)
        · exact .disk (gutnerBlock_valid 5)
        · decide
        · decide
        · decide
      · apply PlaneExpr.Valid.edgeSum
        · exact .disk (gutnerBlock_valid 6)
        · exact .disk (gutnerBlock_valid 7)
        · decide
        · decide
        · decide
      · decide
      · decide
      · decide
    · apply PlaneExpr.Valid.edgeSum
      · apply PlaneExpr.Valid.edgeSum
        · exact .disk (gutnerBlock_valid 8)
        · exact .disk (gutnerBlock_valid 9)
        · decide
        · decide
        · decide
      · apply PlaneExpr.Valid.edgeSum
        · exact .disk (gutnerBlock_valid 10)
        · exact .disk (gutnerBlock_valid 11)
        · decide
        · decide
        · decide
      · decide
      · decide
      · decide
    · decide
    · decide
    · decide
  · decide
  · decide
  · decide

private lemma gutnerBlock_vertices (i : ℕ) :
    (gutnerBlock i).vertices =
      {0, 1, blockBase i, blockBase i + 1, blockBase i + 2, blockBase i + 3,
        blockBase i + 4, blockBase i + 5, blockBase i + 6} := by
  ext x
  simp [gutnerBlock, DiskExpr.vertices]
  tauto

lemma gutnerPlane_vertices : gutnerPlane.vertices = Finset.range 86 := by
  ext x
  simp only [gutnerPlane, gutnerPlane03, gutnerPlane411, gutnerPlane47,
    gutnerPlane811, gutnerPlane01, gutnerPlane23, gutnerPlane45, gutnerPlane67,
    gutnerPlane89, gutnerPlane1011, PlaneExpr.vertices, mem_union]
  rw [gutnerBlock_vertices 0, gutnerBlock_vertices 1, gutnerBlock_vertices 2,
    gutnerBlock_vertices 3, gutnerBlock_vertices 4, gutnerBlock_vertices 5,
    gutnerBlock_vertices 6, gutnerBlock_vertices 7, gutnerBlock_vertices 8,
    gutnerBlock_vertices 9, gutnerBlock_vertices 10, gutnerBlock_vertices 11]
  simp only [mem_insert, mem_singleton, mem_range]
  unfold blockBase
  omega

private lemma gutnerBlock_edges_subset (i : Fin 12) :
    (gutnerBlock i).edges ⊆ gutnerPlane.edges := by
  fin_cases i
  · exact (PlaneExpr.edges_left_subset _ _).trans
      ((PlaneExpr.edges_left_subset gutnerPlane01 gutnerPlane23).trans
        (PlaneExpr.edges_left_subset gutnerPlane03 gutnerPlane411))
  · exact (PlaneExpr.edges_right_subset _ _).trans
      ((PlaneExpr.edges_left_subset gutnerPlane01 gutnerPlane23).trans
        (PlaneExpr.edges_left_subset gutnerPlane03 gutnerPlane411))
  · exact (PlaneExpr.edges_left_subset _ _).trans
      ((PlaneExpr.edges_right_subset gutnerPlane01 gutnerPlane23).trans
        (PlaneExpr.edges_left_subset gutnerPlane03 gutnerPlane411))
  · exact (PlaneExpr.edges_right_subset _ _).trans
      ((PlaneExpr.edges_right_subset gutnerPlane01 gutnerPlane23).trans
        (PlaneExpr.edges_left_subset gutnerPlane03 gutnerPlane411))
  · exact (PlaneExpr.edges_left_subset _ _).trans
      ((PlaneExpr.edges_left_subset gutnerPlane45 gutnerPlane67).trans
        ((PlaneExpr.edges_left_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_right_subset _ _).trans
      ((PlaneExpr.edges_left_subset gutnerPlane45 gutnerPlane67).trans
        ((PlaneExpr.edges_left_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_left_subset _ _).trans
      ((PlaneExpr.edges_right_subset gutnerPlane45 gutnerPlane67).trans
        ((PlaneExpr.edges_left_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_right_subset _ _).trans
      ((PlaneExpr.edges_right_subset gutnerPlane45 gutnerPlane67).trans
        ((PlaneExpr.edges_left_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_left_subset _ _).trans
      ((PlaneExpr.edges_left_subset gutnerPlane89 gutnerPlane1011).trans
        ((PlaneExpr.edges_right_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_right_subset _ _).trans
      ((PlaneExpr.edges_left_subset gutnerPlane89 gutnerPlane1011).trans
        ((PlaneExpr.edges_right_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_left_subset _ _).trans
      ((PlaneExpr.edges_right_subset gutnerPlane89 gutnerPlane1011).trans
        ((PlaneExpr.edges_right_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))
  · exact (PlaneExpr.edges_right_subset _ _).trans
      ((PlaneExpr.edges_right_subset gutnerPlane89 gutnerPlane1011).trans
        ((PlaneExpr.edges_right_subset gutnerPlane47 gutnerPlane811).trans
          (PlaneExpr.edges_right_subset gutnerPlane03 gutnerPlane411)))

private lemma gutnerBlock_adj_to_plane (i : Fin 12) {x y : ℕ}
    (h : DiskExpr.EdgeAdj (gutnerBlock i).edges x y) :
    DiskExpr.EdgeAdj gutnerPlane.edges x y := by
  rcases h with h | h
  · exact Or.inl (gutnerBlock_edges_subset i h)
  · exact Or.inr (gutnerBlock_edges_subset i h)

def gutnerGraph : SimpleGraph (Fin 86) where
  Adj x y := x ≠ y ∧
    ((x.1 = 0 ∧ y.1 = 1) ∨ (x.1 = 1 ∧ y.1 = 0) ∨
      ∃ i : Fin 12, DiskExpr.EdgeAdj (gutnerBlock i).edges x.1 y.1)
  symm.symm x y h := by
    refine ⟨h.1.symm, ?_⟩
    rcases h.2 with h | h | ⟨i, hi⟩
    · exact Or.inr (Or.inl ⟨h.2, h.1⟩)
    · exact Or.inl ⟨h.2, h.1⟩
    · exact Or.inr (Or.inr ⟨i, DiskExpr.edgeAdj_comm.mp hi⟩)
  loopless.irrefl x h := h.1 rfl

lemma gutnerGraph_planar : IsPlanar gutnerGraph := by
  refine ⟨{
    plane := gutnerPlane
    valid := gutnerPlane_valid
    embed := ⟨fun v => v.1, Fin.val_injective⟩
    vertex_mem := ?_
    adj_sub := ?_ }⟩
  · intro v
    rw [gutnerPlane_vertices]
    exact Finset.mem_range.mpr v.2
  · intro v w hvw
    rcases hvw.2 with huv | hvu | ⟨i, hi⟩
    · have hlocal : DiskExpr.EdgeAdj (gutnerBlock 0).edges v.1 w.1 := by
        have h01 : DiskExpr.EdgeAdj (gutnerBlock 0).edges 0 1 := by decide
        simpa [huv.1, huv.2] using h01
      exact gutnerBlock_adj_to_plane 0 hlocal
    · have hlocal : DiskExpr.EdgeAdj (gutnerBlock 0).edges v.1 w.1 := by
        have h10 : DiskExpr.EdgeAdj (gutnerBlock 0).edges 1 0 := by decide
        simpa [hvu.1, hvu.2] using h10
      exact gutnerBlock_adj_to_plane 0 hlocal
    · exact gutnerBlock_adj_to_plane i hi

def gutnerA (i : ℕ) : ℕ := 7 + i / 3

def gutnerB (i : ℕ) : ℕ :=
  let r := i % 3
  let a := i / 3
  7 + if r < a then r else r + 1

def gutnerLists (v : Fin 86) : Finset ℕ :=
  if v.1 < 2 then {7, 8, 9, 10}
  else
    let i := (v.1 - 2) / 7
    let r := (v.1 - 2) % 7
    match r with
    | 0 => {gutnerA i, gutnerB i, 1, 2}
    | 1 => {gutnerA i, 1, 3, 4}
    | 2 => {gutnerA i, gutnerB i, 3, 4}
    | 3 => {gutnerB i, 1, 3, 4}
    | 4 => {gutnerA i, 2, 5, 6}
    | 5 => {gutnerA i, gutnerB i, 5, 6}
    | _ => {gutnerB i, 2, 5, 6}

lemma gutnerLists_card (v : Fin 86) : (gutnerLists v).card = 4 := by
  fin_cases v <;> decide

def gutnerU : Fin 86 := 0
def gutnerV : Fin 86 := 1

def gutnerVertex (i : Fin 12) (r : Fin 7) : Fin 86 :=
  ⟨blockBase i + r, by
    unfold blockBase
    omega⟩

private lemma exists_gutner_pair {a b : ℕ} (ha : a ∈ ({7, 8, 9, 10} : Finset ℕ))
    (hb : b ∈ ({7, 8, 9, 10} : Finset ℕ)) (hab : a ≠ b) :
    ∃ i : Fin 12, gutnerA i = a ∧ gutnerB i = b := by
  simp only [mem_insert, mem_singleton] at ha hb
  rcases ha with rfl | rfl | rfl | rfl <;>
    rcases hb with rfl | rfl | rfl | rfl <;>
    first
    | contradiction
    | exact ⟨0, by decide, by decide⟩
    | exact ⟨1, by decide, by decide⟩
    | exact ⟨2, by decide, by decide⟩
    | exact ⟨3, by decide, by decide⟩
    | exact ⟨4, by decide, by decide⟩
    | exact ⟨5, by decide, by decide⟩
    | exact ⟨6, by decide, by decide⟩
    | exact ⟨7, by decide, by decide⟩
    | exact ⟨8, by decide, by decide⟩
    | exact ⟨9, by decide, by decide⟩
    | exact ⟨10, by decide, by decide⟩
    | exact ⟨11, by decide, by decide⟩

private lemma gutnerLists_w (i : Fin 12) :
    gutnerLists (gutnerVertex i 0) = {gutnerA i, gutnerB i, 1, 2} := by
  fin_cases i <;> decide

private lemma gutnerLists_x1 (i : Fin 12) :
    gutnerLists (gutnerVertex i 1) = {gutnerA i, 1, 3, 4} := by
  fin_cases i <;> decide

private lemma gutnerLists_x2 (i : Fin 12) :
    gutnerLists (gutnerVertex i 2) = {gutnerA i, gutnerB i, 3, 4} := by
  fin_cases i <;> decide

private lemma gutnerLists_x3 (i : Fin 12) :
    gutnerLists (gutnerVertex i 3) = {gutnerB i, 1, 3, 4} := by
  fin_cases i <;> decide

private lemma gutnerLists_y1 (i : Fin 12) :
    gutnerLists (gutnerVertex i 4) = {gutnerA i, 2, 5, 6} := by
  fin_cases i <;> decide

private lemma gutnerLists_y2 (i : Fin 12) :
    gutnerLists (gutnerVertex i 5) = {gutnerA i, gutnerB i, 5, 6} := by
  fin_cases i <;> decide

private lemma gutnerLists_y3 (i : Fin 12) :
    gutnerLists (gutnerVertex i 6) = {gutnerB i, 2, 5, 6} := by
  fin_cases i <;> decide

private lemma gutner_adj_from_block (i : Fin 12) {x y : Fin 86} (hne : x ≠ y)
    (hlocal : DiskExpr.EdgeAdj (gutnerBlock i).edges x.1 y.1) :
    gutnerGraph.Adj x y :=
  ⟨hne, Or.inr (Or.inr ⟨i, hlocal⟩)⟩

private lemma gutnerU_ne_vertex (i : Fin 12) (r : Fin 7) :
    gutnerU ≠ gutnerVertex i r := by
  intro h
  have hval := congrArg Fin.val h
  simp [gutnerU, gutnerVertex, blockBase] at hval
  omega

private lemma gutnerV_ne_vertex (i : Fin 12) (r : Fin 7) :
    gutnerV ≠ gutnerVertex i r := by
  intro h
  have hval := congrArg Fin.val h
  simp [gutnerV, gutnerVertex, blockBase] at hval
  omega

private lemma gutnerVertex_ne (i : Fin 12) {r s : Fin 7} (hrs : r ≠ s) :
    gutnerVertex i r ≠ gutnerVertex i s := by
  intro h
  apply hrs
  apply Fin.ext
  have hval := congrArg Fin.val h
  simp [gutnerVertex, blockBase] at hval
  omega

private lemma gutner_adj_uw (i : Fin 12) :
    gutnerGraph.Adj gutnerU (gutnerVertex i 0) := by
  apply gutner_adj_from_block i (gutnerU_ne_vertex i 0)
  fin_cases i <;> decide
private lemma gutner_adj_vw (i : Fin 12) :
    gutnerGraph.Adj gutnerV (gutnerVertex i 0) := by
  apply gutner_adj_from_block i (gutnerV_ne_vertex i 0)
  fin_cases i <;> decide
private lemma gutner_adj_ux1 (i : Fin 12) :
    gutnerGraph.Adj gutnerU (gutnerVertex i 1) := by
  apply gutner_adj_from_block i (gutnerU_ne_vertex i 1)
  fin_cases i <;> decide
private lemma gutner_adj_wx1 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 0) (gutnerVertex i 1) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_ux2 (i : Fin 12) :
    gutnerGraph.Adj gutnerU (gutnerVertex i 2) := by
  apply gutner_adj_from_block i (gutnerU_ne_vertex i 2)
  fin_cases i <;> decide
private lemma gutner_adj_vx2 (i : Fin 12) :
    gutnerGraph.Adj gutnerV (gutnerVertex i 2) := by
  apply gutner_adj_from_block i (gutnerV_ne_vertex i 2)
  fin_cases i <;> decide
private lemma gutner_adj_vx3 (i : Fin 12) :
    gutnerGraph.Adj gutnerV (gutnerVertex i 3) := by
  apply gutner_adj_from_block i (gutnerV_ne_vertex i 3)
  fin_cases i <;> decide
private lemma gutner_adj_wx3 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 0) (gutnerVertex i 3) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_x12 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 1) (gutnerVertex i 2) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_x23 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 2) (gutnerVertex i 3) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_x31 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 3) (gutnerVertex i 1) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_uy1 (i : Fin 12) :
    gutnerGraph.Adj gutnerU (gutnerVertex i 4) := by
  apply gutner_adj_from_block i (gutnerU_ne_vertex i 4)
  fin_cases i <;> decide
private lemma gutner_adj_wy1 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 0) (gutnerVertex i 4) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_uy2 (i : Fin 12) :
    gutnerGraph.Adj gutnerU (gutnerVertex i 5) := by
  apply gutner_adj_from_block i (gutnerU_ne_vertex i 5)
  fin_cases i <;> decide
private lemma gutner_adj_vy2 (i : Fin 12) :
    gutnerGraph.Adj gutnerV (gutnerVertex i 5) := by
  apply gutner_adj_from_block i (gutnerV_ne_vertex i 5)
  fin_cases i <;> decide
private lemma gutner_adj_vy3 (i : Fin 12) :
    gutnerGraph.Adj gutnerV (gutnerVertex i 6) := by
  apply gutner_adj_from_block i (gutnerV_ne_vertex i 6)
  fin_cases i <;> decide
private lemma gutner_adj_wy3 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 0) (gutnerVertex i 6) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_y12 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 4) (gutnerVertex i 5) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_y23 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 5) (gutnerVertex i 6) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide
private lemma gutner_adj_y31 (i : Fin 12) :
    gutnerGraph.Adj (gutnerVertex i 6) (gutnerVertex i 4) := by
  apply gutner_adj_from_block i (gutnerVertex_ne i (by decide))
  fin_cases i <;> decide

private lemma gutner_x_triangle_impossible (i : Fin 12) (c : gutnerGraph.Coloring ℕ)
    (hmem : ∀ v, c v ∈ gutnerLists v) (hu : c gutnerU = gutnerA i)
    (hv : c gutnerV = gutnerB i) (hw : c (gutnerVertex i 0) = 1) : False := by
  have hux1 := c.valid (gutner_adj_ux1 i)
  have hwx1 := c.valid (gutner_adj_wx1 i)
  have hux2 := c.valid (gutner_adj_ux2 i)
  have hvx2 := c.valid (gutner_adj_vx2 i)
  have hvx3 := c.valid (gutner_adj_vx3 i)
  have hwx3 := c.valid (gutner_adj_wx3 i)
  have hx12 := c.valid (gutner_adj_x12 i)
  have hx23 := c.valid (gutner_adj_x23 i)
  have hx31 := c.valid (gutner_adj_x31 i)
  have hx1 := hmem (gutnerVertex i 1)
  have hx2 := hmem (gutnerVertex i 2)
  have hx3 := hmem (gutnerVertex i 3)
  rw [gutnerLists_x1] at hx1
  rw [gutnerLists_x2] at hx2
  rw [gutnerLists_x3] at hx3
  simp only [mem_insert, mem_singleton] at hx1 hx2 hx3
  omega

private lemma gutner_y_triangle_impossible (i : Fin 12) (c : gutnerGraph.Coloring ℕ)
    (hmem : ∀ v, c v ∈ gutnerLists v) (hu : c gutnerU = gutnerA i)
    (hv : c gutnerV = gutnerB i) (hw : c (gutnerVertex i 0) = 2) : False := by
  have huy1 := c.valid (gutner_adj_uy1 i)
  have hwy1 := c.valid (gutner_adj_wy1 i)
  have huy2 := c.valid (gutner_adj_uy2 i)
  have hvy2 := c.valid (gutner_adj_vy2 i)
  have hvy3 := c.valid (gutner_adj_vy3 i)
  have hwy3 := c.valid (gutner_adj_wy3 i)
  have hy12 := c.valid (gutner_adj_y12 i)
  have hy23 := c.valid (gutner_adj_y23 i)
  have hy31 := c.valid (gutner_adj_y31 i)
  have hy1 := hmem (gutnerVertex i 4)
  have hy2 := hmem (gutnerVertex i 5)
  have hy3 := hmem (gutnerVertex i 6)
  rw [gutnerLists_y1] at hy1
  rw [gutnerLists_y2] at hy2
  rw [gutnerLists_y3] at hy3
  simp only [mem_insert, mem_singleton] at hy1 hy2 hy3
  omega

private lemma gutner_block_forbidden (i : Fin 12) (c : gutnerGraph.Coloring ℕ)
    (hmem : ∀ v, c v ∈ gutnerLists v)
    (hu : c gutnerU = gutnerA i) (hv : c gutnerV = gutnerB i) : False := by
  have huw := c.valid (gutner_adj_uw i)
  have hvw := c.valid (gutner_adj_vw i)
  have hw := hmem (gutnerVertex i 0)
  rw [gutnerLists_w] at hw
  simp only [mem_insert, mem_singleton] at hw
  rcases hw with hw | hw | hw | hw
  · exact huw (hu.trans hw.symm)
  · exact hvw (hv.trans hw.symm)
  · exact gutner_x_triangle_impossible i c hmem hu hv hw
  · exact gutner_y_triangle_impossible i c hmem hu hv hw

theorem gutner_not_four_choosable :
    ¬ Erdos753.IsKChoosable gutnerGraph 4 := by
  intro hfour
  obtain ⟨c, hmem⟩ := hfour gutnerLists gutnerLists_card
  have huMem := hmem gutnerU
  have hvMem := hmem gutnerV
  have huv := c.valid (show gutnerGraph.Adj gutnerU gutnerV from
    ⟨by decide, Or.inl ⟨rfl, rfl⟩⟩)
  have huEndpoint : c gutnerU ∈ ({7, 8, 9, 10} : Finset ℕ) := by
    simpa [gutnerLists, gutnerU] using huMem
  have hvEndpoint : c gutnerV ∈ ({7, 8, 9, 10} : Finset ℕ) := by
    simpa [gutnerLists, gutnerV] using hvMem
  obtain ⟨i, hiu, hiv⟩ := exists_gutner_pair huEndpoint hvEndpoint huv
  exact gutner_block_forbidden i c hmem hiu.symm hiv.symm

theorem gutner_listChromaticNumber_eq_five :
    Erdos753.listChromaticNumber gutnerGraph = 5 := by
  have hle : Erdos753.listChromaticNumber gutnerGraph ≤ 5 :=
    planar_listChromaticNumber_le_five gutnerGraph gutnerGraph_planar
  have hmin : Erdos753.IsKChoosable gutnerGraph
      (Erdos753.listChromaticNumber gutnerGraph) := by
    simpa only [Erdos753.listChromaticNumber, Set.mem_ofPred_eq] using
      (Nat.sInf_mem (Erdos753.choosable_set_nonempty gutnerGraph))
  have hge : 5 ≤ Erdos753.listChromaticNumber gutnerGraph := by
    by_contra h
    have hle4 : Erdos753.listChromaticNumber gutnerGraph ≤ 4 := by omega
    exact gutner_not_four_choosable (hmin.mono hle4)
  omega

/-- **Resolution of Erdős Problem 631.** Every finite planar graph has list
chromatic number at most five, and Gutner's finite planar graph shows that the
constant five is best possible. -/
theorem erdos_631 :
    (∀ {V : Type*} [Fintype V] (G : SimpleGraph V), IsPlanar G →
      Erdos753.listChromaticNumber G ≤ 5) ∧
    (∃ G : SimpleGraph (Fin 86), IsPlanar G ∧
      Erdos753.listChromaticNumber G = 5) := by
  constructor
  · intro V _ G hG
    exact planar_listChromaticNumber_le_five G hG
  · exact ⟨gutnerGraph, gutnerGraph_planar, gutner_listChromaticNumber_eq_five⟩

#print axioms erdos_631

end Erdos631

alias _root_.Erdos631.erdos631 := _root_.Erdos631.erdos_631
