/- leanprover/lean4:v4.32.0  mathlib v4.32.0 -/
/-
This is a Lean formalization of a solution to Erdős Problem 751.
https://www.erdosproblems.com/forum/thread/751

Informal authors:
- J. A. Bondy
- A. Vince
- ChatGPT 5.2 Thinking

Formal authors:
- ChatGPT 5.2 Thinking
- GPT-5.2 Codex
- scp020

URLs:
- https://www.erdosproblems.com/forum/thread/751#post-3835
- https://people.clas.ufl.edu/avince/files/Cycles.pdf
- https://github.com/SpringSense-Innovation-Institute/ai-for-math-lean/tree/main/erdos-problems/erdos751
-/
import Mathlib.Combinatorics.SimpleGraph.Paths
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Subgraph
import Mathlib.Combinatorics.SimpleGraph.Subgraph
import Mathlib.Combinatorics.SimpleGraph.Trails
import Mathlib.Combinatorics.SimpleGraph.Ends.Defs
import Mathlib.Combinatorics.SimpleGraph.Girth
import Mathlib.Combinatorics.SimpleGraph.Coloring.VertexColoring
import Mathlib.Data.Nat.Find
import Mathlib.Data.Finset.Card
import Mathlib.Data.Nat.Dist
import Mathlib.Tactic

namespace Erdos751

universe u
variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

namespace BV

/-- Paper-cycle: based closed walk + IsCycle + explicit length ≥ 3. -/
structure Cycle where
  base : V
  walk : G.Walk base base
  isCycle : walk.IsCycle
  len_ge_three : 3 ≤ walk.length

namespace Cycle

/-- Length of a cycle as walk length. -/
def length (C : Cycle (G := G)) : Nat := C.walk.length

/-- Vertex finset of a cycle (support of the walk). -/
noncomputable def verts (C : Cycle (G := G)) : Finset V := by
  classical
  exact C.walk.support.toFinset

/-- Vertex set of a cycle. -/
def vSet (C : Cycle (G := G)) : Set V := fun v => v ∈ C.verts (G := G)

omit [Fintype V] [DecidableRel G.Adj] in
lemma mem_vSet_iff {C : Cycle (G := G)} {v : V} :
    v ∈ C.vSet (G := G) ↔ v ∈ C.verts (G := G) := Iff.rfl

/-- The subgraph generated by the walk. -/
noncomputable def toSubgraph (C : Cycle (G := G)) : G.Subgraph := by
  classical
  exact C.walk.toSubgraph

/-- A chord: an edge of G between cycle vertices not present in the walk-subgraph. -/
def IsChord (C : Cycle (G := G)) (v w : V) : Prop :=
  v ∈ C.vSet (G := G) ∧
  w ∈ C.vSet (G := G) ∧
  G.Adj v w ∧
  ¬ (C.toSubgraph (G := G)).Adj v w

/-- Chordless/induced cycle: no chord exists. -/
def IsChordless (C : Cycle (G := G)) : Prop :=
  ¬ ∃ v w : V, C.IsChord (G := G) v w

end Cycle

/-! ### BV-level hypotheses (single source of truth) -/

/-- Vertex-two-connected interface (delete any vertex keeps connected). -/
def VertexTwoConnected : Prop :=
  G.Connected ∧ ∀ v : V, (G.induce (fun w : V => w ≠ v)).Connected

/-- Minimum degree ≥ 3. -/
def MinDegreeGE3 : Prop := ∀ v : V, 3 ≤ G.degree v

/-- Minimum degree ≥ 2 (used for cycle existence). -/
def MinDegreeGE2 : Prop := ∀ v : V, 2 ≤ G.degree v

/-
Bridges.

We use `ComponentCompl` to model connected components of the complement of the cycle-vertex set.
Avoid coercions / `.supp` outside this file: define `bridgeSet` as the stable API.
-/

/-- Component-bridge: connected component of the complement of `C.vSet`. -/
abbrev Bridge (C : Cycle (G := G)) : Type _ :=
  G.ComponentCompl (C.vSet (G := G))

/-! `bridgeSet` is the only API for bridge carriers (avoid `.supp` entirely). -/
def bridgeSet (C : Cycle (G := G)) (K : Bridge (G := G) C) : Set V := (K : Set V)

omit [Fintype V] [DecidableRel G.Adj] in
@[simp] lemma mem_bridgeSet_iff {C : Cycle (G := G)} {K : Bridge (G := G) C} {v : V} :
    v ∈ bridgeSet (G := G) C K ↔ v ∈ (K : Set V) := Iff.rfl

omit [Fintype V] [DecidableRel G.Adj] in
theorem bridgeSet_subset_compl_vSet
    (C : Cycle (G := G)) (K : Bridge (G := G) C) :
    bridgeSet (G := G) C K ⊆ (C.vSet (G := G))ᶜ := by
  classical
  intro v hv
  -- hv : v ∈ bridgeSet C K = v ∈ (K : Set V)
  have hvK : v ∈ (K : Set V) := by
    simpa [bridgeSet] using hv
  have hnot : v ∉ C.vSet (G := G) := by
    -- `v` 在该 lemma 里是隐式参数；显式给 `v := v` 最稳
    exact SimpleGraph.ComponentCompl.notMem_of_mem
      (G := G) (K := C.vSet (G := G)) (C := K) (c := v) hvK
  simpa [Set.mem_compl_iff] using hnot


/-- Internal vertices of a bridge as a finset. -/
noncomputable def internalFinset (C : Cycle (G := G)) (K : Bridge (G := G) C) : Finset V := by
  classical
  exact (bridgeSet (G := G) C K).toFinset

/-- Internal cardinality of a bridge component. -/
noncomputable def internalCard (C : Cycle (G := G)) (K : Bridge (G := G) C) : Nat :=
  (internalFinset (G := G) C K).card

/-- Attachment set: cycle vertices adjacent to some vertex in the bridge. -/
def attachSet (C : Cycle (G := G)) (K : Bridge (G := G) C) : Set V :=
  fun x : V =>
    x ∈ C.vSet (G := G) ∧ ∃ w : V, w ∈ bridgeSet (G := G) C K ∧ G.Adj x w

/-- Predicate for `findGreatest`: some bridge has internalCard = n. -/
def Pbridge (C : Cycle (G := G)) (n : Nat) : Prop :=
  ∃ K : Bridge (G := G) C, internalCard (G := G) C K = n

/-- M(C): max internalCard among bridges (using card V as a uniform bound). -/
noncomputable def M (C : Cycle (G := G)) : Nat := by
  classical
  exact Nat.findGreatest (Pbridge (G := G) C) (Fintype.card V)

/-- Pcycle n: there exists a chordless cycle with M(C)=n. -/
def Pcycle (n : Nat) : Prop :=
  ∃ C : Cycle (G := G), C.IsChordless (G := G) ∧ M (G := G) C = n

omit [DecidableRel G.Adj] in
/-- Crude bound: internalCard ≤ card V. -/
theorem internalCard_le_cardV (C : Cycle (G := G)) (K : Bridge (G := G) C) :
    internalCard (G := G) C K ≤ Fintype.card V := by
  classical
  simpa [internalCard, internalFinset] using
    (Finset.card_le_univ (s := (bridgeSet (G := G) C K).toFinset))

omit [DecidableRel G.Adj] in
/-- Bound: M(C) ≤ card V. -/
theorem M_le_cardV (C : Cycle (G := G)) : M (G := G) C ≤ Fintype.card V := by
  classical
  simpa [M] using
    (Nat.findGreatest_le (P := Pbridge (G := G) C) (n := Fintype.card V))

omit [DecidableRel G.Adj] in
/-- Witness for `Pcycle`: from a chordless cycle we get some `n ≤ card V` with `Pcycle n`. -/
theorem exists_Pcycle_of_exists_chordless
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) :
    ∃ n : Nat, n ≤ Fintype.card V ∧ Pcycle (G := G) n := by
  classical
  rcases hch with ⟨C, hC⟩
  refine ⟨M (G := G) C, M_le_cardV (G := G) C, ?_⟩
  exact ⟨C, hC, rfl⟩

/-- nMax: global max value of M(C) among chordless cycles, needs an explicit seed witness. -/
noncomputable def nMax
    (_hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) : Nat := by
  classical
  exact Nat.findGreatest (Pcycle (G := G)) (Fintype.card V)

omit [DecidableRel G.Adj] in
/-- Pcycle holds at nMax (spec lemma; proof filled later). -/
theorem Pcycle_nMax
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) :
    Pcycle (G := G) (nMax (G := G) hch) := by
  classical
  rcases exists_Pcycle_of_exists_chordless (G := G) hch with ⟨n, hnle, hnP⟩
  simpa [nMax] using
    (Nat.findGreatest_spec (P := Pcycle (G := G)) (m := n)
      (n := Fintype.card V) hnle hnP)

/-- Choose Cmax: a chordless cycle attaining nMax. -/
noncomputable def Cmax
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) : Cycle (G := G) :=
  Classical.choose (Pcycle_nMax (G := G) hch)

omit [DecidableRel G.Adj] in
theorem Cmax_isChordless
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) :
    (Cmax (G := G) hch).IsChordless (G := G) := by
  classical
  exact (Classical.choose_spec (Pcycle_nMax (G := G) hch)).1

omit [DecidableRel G.Adj] in
theorem M_Cmax_eq_nMax
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) :
    M (G := G) (Cmax (G := G) hch) = nMax (G := G) hch := by
  classical
  exact (Classical.choose_spec (Pcycle_nMax (G := G) hch)).2

omit [Fintype V] [DecidableRel G.Adj] in
/-- Nonempty bridge ↔ there exists a vertex outside the cycle vertex-set. -/
theorem nonempty_bridge_iff_exists_outside
    (C : Cycle (G := G)) :
    Nonempty (Bridge (G := G) C) ↔ ∃ v : V, v ∉ C.vSet (G := G) := by
  classical
  constructor
  · rintro ⟨K⟩
    rcases (SimpleGraph.ComponentCompl.nonempty (C := K)) with ⟨v, hv⟩
    have hnot : v ∉ C.vSet (G := G) :=
      SimpleGraph.ComponentCompl.notMem_of_mem
        (G := G) (K := C.vSet (G := G)) (C := K) (c := v) hv
    exact ⟨v, hnot⟩
  · rintro ⟨v, hv⟩
    exact ⟨G.componentComplMk (K := C.vSet (G := G)) hv⟩

omit [DecidableRel G.Adj] in
/-- Existence of a bridge attaining M(C), assuming nonemptiness. -/
theorem exists_bridge_attaining_M_of_nonempty
    (C : Cycle (G := G)) (hne : Nonempty (Bridge (G := G) C)) :
    ∃ K : Bridge (G := G) C, internalCard (G := G) C K = M (G := G) C := by
  classical
  rcases hne with ⟨K0⟩
  have hP : Pbridge (G := G) C (internalCard (G := G) C K0) := ⟨K0, rfl⟩
  have hle : internalCard (G := G) C K0 ≤ Fintype.card V :=
    internalCard_le_cardV (G := G) C K0
  have hPmax : Pbridge (G := G) C (M (G := G) C) := by
    simpa [M] using
      (Nat.findGreatest_spec (P := Pbridge (G := G) C) (m := internalCard (G := G) C K0)
        (n := Fintype.card V) hle hP)
  rcases hPmax with ⟨K, hK⟩
  exact ⟨K, hK⟩

/-- Choose Bmax for Cmax, but only with explicit `Nonempty (Bridge (Cmax ...))`. -/
noncomputable def Bmax
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G))
    (hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch))) :
    Bridge (G := G) (Cmax (G := G) hch) :=
  Classical.choose
    (exists_bridge_attaining_M_of_nonempty (G := G) (Cmax (G := G) hch) hne)

omit [DecidableRel G.Adj] in
theorem internalCard_Bmax_eq_M
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G))
    (hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch))) :
    internalCard (G := G) (Cmax (G := G) hch) (Bmax (G := G) hch hne)
      = M (G := G) (Cmax (G := G) hch) := by
  classical
  exact (Classical.choose_spec
    (exists_bridge_attaining_M_of_nonempty (G := G) (Cmax (G := G) hch) hne))

end BV
end Erdos751

namespace Erdos751

universe u
variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

namespace BV

omit [Fintype V] [DecidableRel G.Adj] in
/-- Any vertex in a bridge component lies outside the cycle vertex-set. -/
theorem mem_bridge_imp_not_mem_cycle
    (C : Cycle (G := G)) (K : Bridge (G := G) C) {v : V} :
    v ∈ bridgeSet (G := G) C K → v ∉ C.vSet (G := G) := by
  classical
  intro hv
  have : v ∈ (C.vSet (G := G))ᶜ := (bridgeSet_subset_compl_vSet (G := G) C K) hv
  simpa [Set.mem_compl_iff] using this

omit [Fintype V] [DecidableRel G.Adj] in
/-- Component uniqueness: if a vertex lies in both components, the components are equal. -/
theorem bridge_eq_of_mem_mem
    (C : Cycle (G := G))
    {K1 K2 : Bridge (G := G) C} {v : V} :
    v ∈ bridgeSet (G := G) C K1 → v ∈ bridgeSet (G := G) C K2 → K1 = K2 := by
  classical
  intro hv1 hv2
  have hnot : ¬ Disjoint (K1 : Set V) (K2 : Set V) := by
    refine Set.not_disjoint_iff.mpr ?_
    refine ⟨v, ?_, ?_⟩
    · simpa [bridgeSet] using hv1
    · simpa [bridgeSet] using hv2
  exact
    (SimpleGraph.ComponentCompl.pairwise_disjoint (G := G) (K := C.vSet (G := G))).eq hnot

omit [Fintype V] [DecidableRel G.Adj] in
/-- If components are different, then their carrier sets are disjoint. -/
theorem disjoint_bridge_of_ne
    (C : Cycle (G := G)) {K1 K2 : Bridge (G := G) C} :
    K1 ≠ K2 → Disjoint (bridgeSet (G := G) C K1) (bridgeSet (G := G) C K2) := by
  classical
  intro hne
  refine Set.disjoint_left.2 ?_
  intro v hv1 hv2
  have : K1 = K2 :=
    bridge_eq_of_mem_mem (G := G) C (K1 := K1) (K2 := K2) (v := v) hv1 hv2
  exact hne this

omit [Fintype V] [DecidableRel G.Adj] in
/-- Any two vertices in a bridge component are joined by a path inside the bridge. -/
theorem exists_path_in_bridge
    (C : Cycle (G := G)) (K : Bridge (G := G) C) {u v : V}
    (hu : u ∈ bridgeSet (G := G) C K) (hv : v ∈ bridgeSet (G := G) C K) :
    ∃ p : G.Walk u v, p.IsPath ∧
      (∀ t : V, t ∈ p.support → t ∈ bridgeSet (G := G) C K) := by
        sorry
omit [Fintype V] [DecidableRel G.Adj] in
/-- From two attachments, build an x-y path whose internal vertices lie in the bridge. -/
theorem exists_path_between_attach
    (C : Cycle (G := G)) (K : Bridge (G := G) C) {x y : V}
    (hx : x ∈ attachSet (G := G) C K) (hy : y ∈ attachSet (G := G) C K) (hxy : x ≠ y) :
    ∃ p : G.Walk x y, p.IsPath ∧
      (∀ v : V, v ∈ p.support → v = x ∨ v = y ∨ v ∈ bridgeSet (G := G) C K) ∧
      ∃ w : V, w ∈ bridgeSet (G := G) C K ∧ s(x, w) ∈ p.edges := by
  classical
  rcases hx with ⟨hxC, ⟨wx, hwxK, hAdjx⟩⟩
  rcases hy with ⟨hyC, ⟨wy, hwyK, hAdjy⟩⟩
  obtain ⟨pK, hpK_path, hpK_supp⟩ :=
    exists_path_in_bridge (G := G) (C := C) (K := K) hwxK hwyK
  have hx_not_bridge : x ∉ bridgeSet (G := G) C K := by
    intro hxB
    exact (mem_bridge_imp_not_mem_cycle (G := G) C K hxB) hxC
  have hy_not_bridge : y ∉ bridgeSet (G := G) C K := by
    intro hyB
    exact (mem_bridge_imp_not_mem_cycle (G := G) C K hyB) hyC
  have hx_not_pK : x ∉ pK.support := by
    intro hxmem
    exact hx_not_bridge (hpK_supp x hxmem)
  have hy_not_pK : y ∉ pK.support := by
    intro hymem
    exact hy_not_bridge (hpK_supp y hymem)
  let p1 : G.Walk wx y := pK.concat hAdjy.symm
  have hp1_path : p1.IsPath := by
    exact SimpleGraph.Walk.IsPath.concat hpK_path hy_not_pK hAdjy.symm
  have hx_not_p1 : x ∉ p1.support := by
    intro hxmem
    have hxmem' : x ∈ pK.support ∨ x = y := by
      have : x ∈ pK.support ++ [y] := by
        simpa [p1, SimpleGraph.Walk.support_concat, List.concat_eq_append] using hxmem
      rcases List.mem_append.mp this with hxmem'' | hxmem''
      · exact Or.inl hxmem''
      · exact Or.inr (by simpa using hxmem'')
    cases hxmem' with
    | inl hxmem'' => exact hx_not_pK hxmem''
    | inr hxy' => exact hxy hxy'
  let p : G.Walk x y := SimpleGraph.Walk.cons hAdjx p1
  have hp_path : p.IsPath := by
    exact SimpleGraph.Walk.IsPath.cons hp1_path hx_not_p1
  have hp_supp : ∀ v : V, v ∈ p.support → v = x ∨ v = y ∨ v ∈ bridgeSet (G := G) C K := by
    intro v hv
    have hv' : v = x ∨ v ∈ p1.support := by
      simpa [p, SimpleGraph.Walk.support_cons] using hv
    cases hv' with
    | inl hvx => exact Or.inl hvx
    | inr hvp1 =>
        have hvp1' : v ∈ pK.support ++ [y] := by
          simpa [p1, SimpleGraph.Walk.support_concat, List.concat_eq_append] using hvp1
        rcases List.mem_append.mp hvp1' with hvpK | hvy
        · exact Or.inr (Or.inr (hpK_supp v hvpK))
        · exact Or.inr (Or.inl (by simpa using hvy))
  -- the first edge is x-wx, with wx in the bridge
  have hEdge : s(x, wx) ∈ p.edges := by
    simp [p]
  exact ⟨p, hp_path, hp_supp, ⟨wx, hwxK, hEdge⟩⟩

end BV
end Erdos751

namespace Erdos751

universe u
variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

namespace BV

/-!
Stable engineering layer (v4.23.0-safe):
Downstream files should rely only on these wrappers for IsPath / reachability.
-/

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
theorem exists_walk_of_reachable {x y : V} (h : G.Reachable x y) :
    ∃ _ : G.Walk x y, True := by
  classical
  rcases h with ⟨p⟩
  exact ⟨p, trivial⟩

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
theorem exists_walk_of_connected (hconn : G.Connected) (x y : V) :
    ∃ _ : G.Walk x y, True := by
  classical
  have hr : G.Reachable x y := hconn x y
  exact exists_walk_of_reachable (G := G) hr

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
/-- Reduce a walk to a simple path (IsPath) with the same endpoints. -/
theorem reduce_to_isPath {x y : V} (p : G.Walk x y) :
    ∃ q : G.Walk x y, q.IsPath := by
  classical
  have hr : G.Reachable x y := p.reachable
  exact hr.exists_isPath

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
theorem exists_isPath_of_reachable {x y : V} (h : G.Reachable x y) :
    ∃ p : G.Walk x y, p.IsPath := by
  classical
  rcases exists_walk_of_reachable (G := G) h with ⟨p, _⟩
  exact reduce_to_isPath (G := G) p

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
theorem exists_isPath_of_connected (hconn : G.Connected) (x y : V) :
    ∃ p : G.Walk x y, p.IsPath := by
  classical
  rcases exists_walk_of_connected (G := G) hconn x y with ⟨p, _⟩
  exact reduce_to_isPath (G := G) p

end BV
end Erdos751

namespace Erdos751

open SimpleGraph

universe u
variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

namespace BV

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
private lemma shorter_cycle_of_chord
    {v : V} {c : G.Walk v v} (hc : c.IsCycle)
    {x y : V} (hx : x ∈ c.support) (hy : y ∈ c.support)
    (hxy : G.Adj x y) (hnot : ¬ c.toSubgraph.Adj x y) :
    ∃ a : V, ∃ c' : G.Walk a a, c'.IsCycle ∧ c'.length < c.length := by
  classical
  let r := c.rotate x hx
  have hr_cycle : r.IsCycle := hc.rotate hx
  have hlen_rot : r.length = c.length := by
    have hlen1 :
        (c.takeUntil x hx).length + (c.dropUntil x hx).length = c.length := by
      have hlen1' := congrArg SimpleGraph.Walk.length (SimpleGraph.Walk.take_spec c hx)
      rw [SimpleGraph.Walk.length_append] at hlen1'
      exact hlen1'
    -- rotate swaps the two pieces, so length is preserved
    calc
      r.length
          = (c.dropUntil x hx).length + (c.takeUntil x hx).length := by
              simp [r, SimpleGraph.Walk.rotate, SimpleGraph.Walk.length_append]
      _ = (c.takeUntil x hx).length + (c.dropUntil x hx).length := by
              simp [add_comm]
      _ = c.length := hlen1
  have hy' : y ∈ r.support := by
    have hyv : y ∈ c.toSubgraph.verts := by
      simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using hy
    have : y ∈ r.toSubgraph.verts := by
      simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using hyv
    simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using this
  let p := r.takeUntil y hy'
  have hp_path : p.IsPath := hr_cycle.isPath_takeUntil hy'
  have hnot_adj_r : ¬ r.toSubgraph.Adj x y := by
    simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using hnot
  have hnot_edge_r : s(x, y) ∉ r.edges := by
    intro hmem
    have : r.toSubgraph.Adj x y := by
      have : s(x, y) ∈ r.toSubgraph.edgeSet := (r.mem_edges_toSubgraph).2 hmem
      exact (SimpleGraph.Subgraph.mem_edgeSet (G' := r.toSubgraph) (v := x) (w := y)).1 this
    exact hnot_adj_r this
  have hnot_edge_p : s(x, y) ∉ p.edges := by
    intro hmem
    have hmem' : s(x, y) ∈ r.edges := (r.edges_takeUntil_subset hy') hmem
    exact hnot_edge_r hmem'
  have hp_len_lt : p.length < r.length := by
    have hne : y ≠ x := (G.ne_of_adj hxy).symm
    exact r.length_takeUntil_lt hy' hne
  have hlen_ne : p.length + 1 ≠ r.length := by
    intro hlen
    have hlen' : p.length = r.length - 1 := by omega
    have hget : r.getVert p.length = y := by
      have hpl : p.getVert p.length = y := by simp
      have hpr : p.getVert p.length = r.getVert p.length := by
        dsimp [p]
        exact r.getVert_takeUntil hy' (by rfl)
      exact hpr.symm.trans hpl
    have hpend : r.penultimate = y := by
      simpa [SimpleGraph.Walk.penultimate, hlen'] using hget
    have hnotnil : ¬ r.Nil := hr_cycle.not_nil
    have hadj_pen : r.toSubgraph.Adj r.penultimate x :=
      r.toSubgraph_adj_penultimate hnotnil
    have : r.toSubgraph.Adj x y := by
      have hsymm :
          r.toSubgraph.Adj x r.penultimate := by
            simpa using
              (SimpleGraph.Subgraph.adj_comm (G' := r.toSubgraph) r.penultimate x).1 hadj_pen
      simpa [hpend] using hsymm
    exact hnot_adj_r this
  have hlen_short : p.length + 1 < r.length := by
    have hle : p.length + 1 ≤ r.length := Nat.succ_le_iff.2 hp_len_lt
    exact lt_of_le_of_ne hle hlen_ne
  have hcyc' : (SimpleGraph.Walk.cons hxy.symm p).IsCycle := by
    have hnot_edge_p' : s(y, x) ∉ p.edges := by
      simpa [Sym2.eq_swap] using hnot_edge_p
    let pp : SimpleGraph.Path (G := G) x y := ⟨p, hp_path⟩
    exact SimpleGraph.Path.cons_isCycle (p := pp) (h := hxy.symm) hnot_edge_p'
  refine ⟨y, SimpleGraph.Walk.cons hxy.symm p, hcyc', ?_⟩
  simpa [SimpleGraph.Walk.length_cons, hlen_rot] using hlen_short

omit [DecidableEq V] in
/-- Existence of a (paper-)cycle from connected + δ≥2 + card≥2. -/
theorem exists_cycle_of_connected_minDegreeGE2
    (hconn : G.Connected) (hδ2 : MinDegreeGE2 (G := G)) (hcard2 : Fintype.card V ≥ 2) :
    ∃ _ : Cycle (G := G), True := by
  classical
  by_contra hno
  have hacyc : G.IsAcyclic := by
    intro v c hc
    apply hno
    refine ⟨⟨v, c, hc, ?_⟩, trivial⟩
    simpa using hc.three_le_length
  have h1 : 1 < Fintype.card V := (Nat.succ_le_iff).1 hcard2
  haveI : Nontrivial V := (Fintype.one_lt_card_iff_nontrivial).1 h1
  haveI : Nonempty V := inferInstance
  have htree : G.IsTree := ⟨hconn, hacyc⟩
  have hmin1 : G.minDegree = 1 :=
    SimpleGraph.IsTree.minDegree_eq_one_of_nontrivial (G := G) htree
  have hmin2 : 2 ≤ G.minDegree :=
    SimpleGraph.le_minDegree_of_forall_le_degree (G := G) 2 hδ2
  have hmin2' : (2 : ℕ) ≤ 1 := by
    convert hmin2 using 1
    simp [hmin1]
  exact (Nat.not_succ_le_self 1) hmin2'

omit [Fintype V] [DecidableRel G.Adj] in
/-- From a cycle, extract a chordless (induced) cycle by choosing a shortest one. -/
theorem exists_chordless_cycle_of_exists_cycle
    (hcyc : ∃ _ : Cycle (G := G), True) :
    ∃ C : Cycle (G := G), C.IsChordless (G := G) := by
  classical
  rcases hcyc with ⟨C0, _⟩
  have hnot : ¬ G.IsAcyclic := by
    intro hacyc
    exact hacyc C0.walk C0.isCycle
  obtain ⟨a, c, hc, hlen⟩ :=
    (SimpleGraph.exists_girth_eq_length (G := G)).2 hnot
  let C : Cycle (G := G) :=
    { base := a
      walk := c
      isCycle := hc
      len_ge_three := by simpa using hc.three_le_length }
  refine ⟨C, ?_⟩
  by_contra hch
  have hch' : ∃ x y : V, C.IsChord (G := G) x y := by
    simpa [Cycle.IsChordless] using hch
  rcases hch' with ⟨x, y, hx, hy, hxy, hnotadj⟩
  have hx_supp : x ∈ c.support := by
    have hx' : x ∈ C.verts (G := G) := (C.mem_vSet_iff).1 hx
    simpa [Cycle.verts, C] using hx'
  have hy_supp : y ∈ c.support := by
    have hy' : y ∈ C.verts (G := G) := (C.mem_vSet_iff).1 hy
    simpa [Cycle.verts, C] using hy'
  have hnotadj' : ¬ c.toSubgraph.Adj x y := by
    simpa [Cycle.toSubgraph, C] using hnotadj
  obtain ⟨a', c', hc', hlt⟩ :=
    shorter_cycle_of_chord (G := G) hc hx_supp hy_supp hxy hnotadj'
  have hle := SimpleGraph.girth_le_length (G := G) hc'
  have hlt' : c.length < c.length := by
    simpa [hlen] using (lt_of_le_of_lt hle hlt)
  exact (lt_irrefl _ hlt')

/-- Convenience: obtain a chordless cycle seed from VertexTwoConnected + δ≥3 + card≥4. -/
theorem exists_chordless_cycle_of_h2_hδ3
    (h2 : VertexTwoConnected (G := G)) (hδ3 : MinDegreeGE3 (G := G))
    (hcard4 : Fintype.card V ≥ 4) :
    ∃ C : Cycle (G := G), C.IsChordless (G := G) := by
  classical
  have hconn : G.Connected := h2.1
  have hδ2 : MinDegreeGE2 (G := G) := by
    intro v
    exact le_trans (by decide : 2 ≤ 3) (hδ3 v)
  have hcard2 : Fintype.card V ≥ 2 := by omega
  obtain ⟨C, _⟩ :=
    exists_cycle_of_connected_minDegreeGE2 (G := G) hconn hδ2 hcard2
  exact exists_chordless_cycle_of_exists_cycle (G := G) ⟨C, trivial⟩

/-- δ≥3 implies Cmax has a bridge. -/
theorem nonempty_bridge_Cmax_of_hδ3
    (hδ3 : MinDegreeGE3 (G := G)) (hcard4 : Fintype.card V ≥ 4)
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G)) :
    Nonempty (Bridge (G := G) (Cmax (G := G) hch)) := by
  classical
  by_contra hne
  let C : Cycle (G := G) := Cmax (G := G) hch
  have hchordless : C.IsChordless (G := G) := Cmax_isChordless (G := G) hch
  have hno : ¬ ∃ v : V, v ∉ C.vSet (G := G) := by
    intro h
    exact hne ((nonempty_bridge_iff_exists_outside (G := G) (C := C)).2 h)
  have hcover : ∀ v : V, v ∈ C.vSet (G := G) := by
    intro v
    by_contra hv
    exact hno ⟨v, hv⟩
  have hdeg : ∀ v : V, G.degree v = 2 := by
    intro v
    have hv_supp : v ∈ C.walk.support := by
      have hv' : v ∈ C.verts (G := G) := (C.mem_vSet_iff).1 (hcover v)
      simpa [Cycle.verts, C] using hv'
    have htwo : ((C.toSubgraph (G := G)).neighborSet v).ncard = 2 := by
      simpa [Cycle.toSubgraph, C] using
        (C.isCycle.ncard_neighborSet_toSubgraph_eq_two (G := G) (h := hv_supp))
    have hneigh : G.neighborSet v = (C.toSubgraph (G := G)).neighborSet v := by
      ext w
      constructor
      · intro hw
        have hAdj : G.Adj v w := (SimpleGraph.mem_neighborSet (G := G) v w).1 hw
        have hv : v ∈ C.vSet (G := G) := hcover v
        have hw' : w ∈ C.vSet (G := G) := hcover w
        have hAdj' : (C.toSubgraph (G := G)).Adj v w := by
          by_contra hnot
          exact hchordless ⟨v, w, hv, hw', hAdj, hnot⟩
        exact (SimpleGraph.Subgraph.mem_neighborSet (G' := C.toSubgraph (G := G)) v w).2 hAdj'
      · intro hw
        have hAdj' : (C.toSubgraph (G := G)).Adj v w :=
          (SimpleGraph.Subgraph.mem_neighborSet (G' := C.toSubgraph (G := G)) v w).1 hw
        have hAdj : G.Adj v w := (C.toSubgraph (G := G)).adj_sub hAdj'
        exact (SimpleGraph.mem_neighborSet (G := G) v w).2 hAdj
    have htwo_toFinset : ((C.toSubgraph (G := G)).neighborSet v).toFinset.card = 2 := by
      have htwo' := htwo
      rw [Set.ncard_eq_toFinset_card' ((C.toSubgraph (G := G)).neighborSet v)] at htwo'
      exact htwo'
    have htwo' : Fintype.card ((C.toSubgraph (G := G)).neighborSet v) = 2 := by
      simpa using htwo_toFinset
    have htwo'' : Fintype.card (G.neighborSet v) = 2 := by
      simpa [hneigh] using htwo'
    calc
      G.degree v = Fintype.card (G.neighborSet v) := by
        exact (SimpleGraph.card_neighborSet_eq_degree (G := G) (v := v)).symm
      _ = 2 := htwo''
  -- pick any vertex to contradict δ≥3
  have hpos : 0 < Fintype.card V := lt_of_lt_of_le (by decide : 0 < 4) hcard4
  haveI : Nonempty V := (Fintype.card_pos_iff.1 hpos)
  classical
  obtain ⟨v⟩ := ‹Nonempty V›
  have hδ3v : 3 ≤ G.degree v := hδ3 v
  have hcontra : (3 : ℕ) ≤ 2 := by
    rw [hdeg v] at hδ3v
    exact hδ3v
  exact (Nat.not_succ_le_self 2) hcontra

def AllAttachOnly (C : Cycle (G := G)) (x y : V) : Prop :=
  ∀ K : Bridge (G := G) C, attachSet (G := G) C K ⊆ ({x, y} : Set V)

def AttachExactly (C : Cycle (G := G)) (K : Bridge (G := G) C) (x y : V) : Prop :=
  attachSet (G := G) C K = ({x, y} : Set V)

def IsXYPathBridge (C : Cycle (G := G)) (K : Bridge (G := G) C) (x y : V) : Prop :=
  ∃ p : G.Walk x y,
    p.IsPath ∧
      (∀ v : V,
        v ∈ (p.support.toFinset.erase x |>.erase y) → v ∈ internalFinset (G := G) C K)

omit [Fintype V] [DecidableRel G.Adj] in
/-- If a vertex in a bridge is adjacent to a vertex outside the cycle, then that vertex is in the
same bridge. -/
lemma mem_bridge_of_adj_outside
    (C : Cycle (G := G)) (K : Bridge (G := G) C)
    {u v : V} (hu : u ∈ bridgeSet (G := G) C K)
    (hv : v ∉ C.vSet (G := G)) (hAdj : G.Adj u v) :
    v ∈ bridgeSet (G := G) C K := by
  classical
  have hu' : u ∈ (K : Set V) := by simpa [bridgeSet] using hu
  rcases (SimpleGraph.ComponentCompl.mem_supp_iff (G := G) (K := C.vSet (G := G))
      (C := K) (v := u)).1 hu' with ⟨huK, hcompu⟩
  have hvK : v ∈ (C.vSet (G := G))ᶜ := by
    simpa [Set.mem_compl_iff] using hv
  have hreach :
      (G.induce (C.vSet (G := G))ᶜ).Reachable ⟨u, huK⟩ ⟨v, hvK⟩ := by
    refine ⟨SimpleGraph.Walk.cons ?_ SimpleGraph.Walk.nil⟩
    simpa using hAdj
  have hcomp :
      G.componentComplMk (K := C.vSet (G := G)) huK =
        G.componentComplMk (K := C.vSet (G := G)) hvK := by
    simpa [SimpleGraph.componentComplMk] using
      (SimpleGraph.ConnectedComponent.eq
        (G := G.induce (C.vSet (G := G))ᶜ)
        (v := ⟨u, huK⟩) (w := ⟨v, hvK⟩)).2 hreach
  exact (SimpleGraph.ComponentCompl.mem_supp_iff (G := G) (K := C.vSet (G := G))
    (C := K) (v := v)).2 ⟨hvK, by simpa [hcompu] using hcomp.symm⟩

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
/-- Lift a walk to the induced graph on a set containing its support. -/
lemma exists_walkSubtype
    {W : Set V} {u v : V} (p : G.Walk u v)
    (hW : ∀ x : V, x ∈ p.support → x ∈ W) :
    ∃ (hu : u ∈ W) (hv : v ∈ W),
      ∃ psub : (G.induce W).Walk ⟨u, hu⟩ ⟨v, hv⟩,
        psub.map (SimpleGraph.Embedding.induce (G := G) (s := W)).toHom = p := by
  classical
  -- define by recursion on the walk
  revert hW
  refine SimpleGraph.Walk.rec (motive := fun {u v} (p : G.Walk u v) =>
      (∀ x : V, x ∈ p.support → x ∈ W) →
        ∃ (hu : u ∈ W) (hv : v ∈ W),
          ∃ psub : (G.induce W).Walk ⟨u, hu⟩ ⟨v, hv⟩,
            psub.map (SimpleGraph.Embedding.induce (G := G) (s := W)).toHom = p) ?_ ?_ p
  · intro u hW
    have hu : u ∈ W := hW u (by simp)
    refine ⟨hu, hu, SimpleGraph.Walk.nil, ?_⟩
    simp
  · intro u v w h q ih hW
    have hu : u ∈ W := hW u (by simp)
    have hWq : ∀ x : V, x ∈ q.support → x ∈ W := by
      intro x hx
      exact hW x ((SimpleGraph.Walk.support_subset_support_cons (p := q) (hadj := h)) hx)
    obtain ⟨hv, hw, qsub, hmap⟩ := ih hWq
    have hvq : v ∈ W := hWq v (by simp )
    let hAdj' : (G.induce W).Adj ⟨u, hu⟩ ⟨v, hvq⟩ := by
      simpa using h
    refine ⟨hu, hw, SimpleGraph.Walk.cons hAdj' qsub, ?_⟩
    simp [SimpleGraph.Walk.map_cons, hmap]

omit [DecidableRel G.Adj] in
theorem compression
    (_ : VertexTwoConnected (G := G))
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G))
    (hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch)))
    (K : Bridge (G := G) (Cmax (G := G) hch))
    (hK : K ≠ Bmax (G := G) hch hne)
    {x y : V} :
    x ≠ y →
    x ∈ attachSet (G := G) (Cmax (G := G) hch) K →
    y ∈ attachSet (G := G) (Cmax (G := G) hch) K →
    attachSet (G := G) (Cmax (G := G) hch) (Bmax (G := G) hch hne) ⊆ ({x, y} : Set V) := by
      sorry
omit [DecidableRel G.Adj] in
theorem BV_Lemma1_core
    (h2 : VertexTwoConnected (G := G))
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G))
    (hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch))) :
    (Subsingleton (Bridge (G := G) (Cmax (G := G) hch))) ∨
      ∃ x y : V,
        x ≠ y ∧
        x ∈ (Cmax (G := G) hch).vSet (G := G) ∧
        y ∈ (Cmax (G := G) hch).vSet (G := G) ∧
        AttachExactly (G := G) (Cmax (G := G) hch) (Bmax (G := G) hch hne) x y ∧
        AllAttachOnly (G := G) (Cmax (G := G) hch) x y ∧
        ∀ K : Bridge (G := G) (Cmax (G := G) hch),
          K ≠ Bmax (G := G) hch hne →
            IsXYPathBridge (G := G) (Cmax (G := G) hch) K x y := by
              sorry
theorem BVDelta3_key_core
    (h2 : VertexTwoConnected (G := G))
    (hδ3 : MinDegreeGE3 (G := G))
    (_ : Fintype.card V ≥ 4)
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G))
    (hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch))) :
    (Subsingleton (Bridge (G := G) (Cmax (G := G) hch))) ∧
    attachSet (G := G) (Cmax (G := G) hch) (Bmax (G := G) hch hne)
      = (Cmax (G := G) hch).vSet (G := G) := by
  classical
  let C : Cycle (G := G) := Cmax (G := G) hch
  let B : Bridge (G := G) C := Bmax (G := G) hch hne
  have hchordless : C.IsChordless (G := G) := Cmax_isChordless (G := G) hch
  -- helper: degree 2 if all neighbors stay on the cycle
  have hdeg_two_of_all_in_cycle :
      ∀ v : V, v ∈ C.vSet (G := G) →
        (∀ w : V, G.Adj v w → w ∈ C.vSet (G := G)) → G.degree v = 2 := by
    intro v hv hAll
    have hv_supp : v ∈ C.walk.support := by
      have hv' : v ∈ C.verts (G := G) := (C.mem_vSet_iff (G := G)).1 hv
      simpa [Cycle.verts, C] using hv'
    have htwo : ((C.toSubgraph (G := G)).neighborSet v).ncard = 2 := by
      simpa [Cycle.toSubgraph, C] using
        (C.isCycle.ncard_neighborSet_toSubgraph_eq_two (G := G) (h := hv_supp))
    have hneigh : G.neighborSet v = (C.toSubgraph (G := G)).neighborSet v := by
      ext w
      constructor
      · intro hw
        have hAdj : G.Adj v w := (SimpleGraph.mem_neighborSet (G := G) v w).1 hw
        have hwC : w ∈ C.vSet (G := G) := hAll w hAdj
        have hAdj' : (C.toSubgraph (G := G)).Adj v w := by
          by_contra hnot
          exact hchordless ⟨v, w, hv, hwC, hAdj, hnot⟩
        exact (SimpleGraph.Subgraph.mem_neighborSet (G' := C.toSubgraph (G := G)) v w).2 hAdj'
      · intro hw
        have hAdj' : (C.toSubgraph (G := G)).Adj v w :=
          (SimpleGraph.Subgraph.mem_neighborSet (G' := C.toSubgraph (G := G)) v w).1 hw
        have hAdj : G.Adj v w := (C.toSubgraph (G := G)).adj_sub hAdj'
        exact (SimpleGraph.mem_neighborSet (G := G) v w).2 hAdj
    have htwo_toFinset : ((C.toSubgraph (G := G)).neighborSet v).toFinset.card = 2 := by
      have htwo' := htwo
      rw [Set.ncard_eq_toFinset_card' ((C.toSubgraph (G := G)).neighborSet v)] at htwo'
      exact htwo'
    have htwo' : Fintype.card ((C.toSubgraph (G := G)).neighborSet v) = 2 := by
      simpa using htwo_toFinset
    have htwo'' : Fintype.card (G.neighborSet v) = 2 := by
      simpa [hneigh] using htwo'
    calc
      G.degree v = Fintype.card (G.neighborSet v) := by
        exact (SimpleGraph.card_neighborSet_eq_degree (G := G) (v := v)).symm
      _ = 2 := htwo''
  -- apply BV lemma 1
  have hlem := BV_Lemma1_core (G := G) h2 hch hne
  cases hlem with
  | inl hsub =>
      -- subsingleton bridges, attachments cover the cycle
      have hcover : C.vSet (G := G) ⊆ attachSet (G := G) C B := by
        intro v hv
        by_contra hno
        have hAll : ∀ w : V, G.Adj v w → w ∈ C.vSet (G := G) := by
          intro w hAdj
          by_contra hw
          have : v ∈ attachSet (G := G) C B := by
            -- any neighbor outside the cycle lies in the unique bridge
            have hwB : w ∈ bridgeSet (G := G) C B := by
              -- since B is the only bridge
              have :
                  (bridgeSet (G := G) C (G.componentComplMk (K := C.vSet (G := G)) hw)) =
                    bridgeSet (G := G) C B := by
                -- use subsingleton
                have : (G.componentComplMk (K := C.vSet (G := G)) hw) = B := by
                  exact (Subsingleton.elim _ _)
                simp [this]
              -- membership in its own component
              have hw' :
                  w ∈ bridgeSet (G := G) C
                    (G.componentComplMk (K := C.vSet (G := G)) hw) := by
                simpa [bridgeSet] using (G.componentComplMk_mem (K := C.vSet (G := G)) hw)
              -- rewrite via the component equality
              simpa [this] using hw'
            exact ⟨hv, ⟨w, hwB, hAdj⟩⟩
          exact hno this
        have hdeg : G.degree v = 2 := hdeg_two_of_all_in_cycle v hv hAll
        have hδ3v : 3 ≤ G.degree v := hδ3 v
        have hcontra : (3 : ℕ) ≤ 2 := by simp [hdeg] at hδ3v
        exact (Nat.not_succ_le_self 2) hcontra
      have hsubset : attachSet (G := G) C B ⊆ C.vSet (G := G) := by
        intro v hv
        exact hv.1
      exact ⟨hsub, Set.Subset.antisymm hsubset hcover⟩
  | inr h =>
      rcases h with ⟨x, y, hxy, hxC, hyC, hAttachB, hAll, _⟩
      -- pick a vertex z on the cycle with z ≠ x,y
      have hx_supp : x ∈ C.walk.support := by
        have hx' : x ∈ C.verts (G := G) := (C.mem_vSet_iff (G := G)).1 hxC
        simpa [Cycle.verts, C] using hx'
      let r := C.walk.rotate x hx_supp
      have hr_cycle : r.IsCycle := C.isCycle.rotate hx_supp
      have hr_not_nil : ¬ r.Nil := hr_cycle.not_nil
      have hlen_eq : r.length = C.walk.length := by
        have hlen' :
            (C.walk.takeUntil x hx_supp).length + (C.walk.dropUntil x hx_supp).length =
              C.walk.length := by
          have hspec :=
            SimpleGraph.Walk.take_spec (p := C.walk) (h := hx_supp)
          have hlen'' :
              (C.walk.takeUntil x hx_supp).length +
                  (C.walk.dropUntil x hx_supp).length =
                ((C.walk.takeUntil x hx_supp).append (C.walk.dropUntil x hx_supp)).length := by
            simpa using
              (SimpleGraph.Walk.length_append
                (p := C.walk.takeUntil x hx_supp)
                (q := C.walk.dropUntil x hx_supp)).symm
          calc
            (C.walk.takeUntil x hx_supp).length +
                (C.walk.dropUntil x hx_supp).length =
                ((C.walk.takeUntil x hx_supp).append
                    (C.walk.dropUntil x hx_supp)).length := hlen''
            _ = C.walk.length := by
              simp
        calc
          r.length =
              (C.walk.dropUntil x hx_supp).length +
                (C.walk.takeUntil x hx_supp).length := by
            simp [r, SimpleGraph.Walk.rotate]
          _ =
              (C.walk.takeUntil x hx_supp).length +
                (C.walk.dropUntil x hx_supp).length := by
            simp [add_comm]
          _ = C.walk.length := hlen'
      have hlen : 3 ≤ r.length := by
        simpa [hlen_eq] using C.len_ge_three
      let y1 : V := r.snd
      let y2 : V := r.getVert 2
      have hy1_ne_x : y1 ≠ x := by
        have hadj : G.Adj x y1 := SimpleGraph.Walk.adj_snd (p := r) hr_not_nil
        exact (G.ne_of_adj hadj).symm
      have hy1_ne_y2 : y1 ≠ y2 := by
        intro hEq
        have h1 : (1 : ℕ) ∈ {i | 1 ≤ i ∧ i ≤ r.length} := by
          exact ⟨by decide, le_trans (by decide : 1 ≤ 3) hlen⟩
        have h2 : (2 : ℕ) ∈ {i | 1 ≤ i ∧ i ≤ r.length} := by
          exact ⟨by decide, le_trans (by decide : 2 ≤ 3) hlen⟩
        have := hr_cycle.getVert_injOn h1 h2 hEq
        exact (by decide : (1 : ℕ) ≠ 2) this
      have hy2_ne_x : y2 ≠ x := by
        intro hEq
        have h1 : (2 : ℕ) ∈ {i | 1 ≤ i ∧ i ≤ r.length} := by
          exact ⟨by decide, le_trans (by decide : 2 ≤ 3) hlen⟩
        have h2 : r.length ∈ {i | 1 ≤ i ∧ i ≤ r.length} := by
          exact ⟨le_trans (by decide : 1 ≤ 3) hlen, le_rfl⟩
        have hEq' : r.getVert 2 = r.getVert r.length := by
          have hEq'' : r.getVert 2 = x := by
            simpa [y2] using hEq
          have hlenEq : r.getVert r.length = x := by
            simp
          exact hEq''.trans hlenEq.symm
        have hidx := hr_cycle.getVert_injOn h1 h2 hEq'
        have : (2 : ℕ) = r.length := hidx
        have : (r.length) ≤ 2 := by simp [this]
        have : (3 : ℕ) ≤ 2 := le_trans hlen this
        exact (Nat.not_succ_le_self 2) this
      let z : V := if hzy : y1 = y then y2 else y1
      have hz_ne_x : z ≠ x := by
        by_cases hzy : y1 = y
        · simpa [z, hzy] using hy2_ne_x
        · simpa [z, hzy] using hy1_ne_x
      have hz_ne_y : z ≠ y := by
        by_cases hzy : y1 = y
        · have : y2 ≠ y := by simpa [hzy] using hy1_ne_y2.symm
          simpa [z, hzy] using this
        · simp [z, hzy]
      have hzC : z ∈ C.vSet (G := G) := by
        have hy1_mem : y1 ∈ r.support :=
          SimpleGraph.Walk.getVert_mem_support (p := r) 1
        have hy2_mem : y2 ∈ r.support :=
          SimpleGraph.Walk.getVert_mem_support (p := r) 2
        have hy1_mem' : y1 ∈ C.walk.support := by
          have : y1 ∈ r.toSubgraph.verts := by
            simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using hy1_mem
          have : y1 ∈ C.walk.toSubgraph.verts := by
            simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using this
          simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using this
        have hy2_mem' : y2 ∈ C.walk.support := by
          have : y2 ∈ r.toSubgraph.verts := by
            simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using hy2_mem
          have : y2 ∈ C.walk.toSubgraph.verts := by
            simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using this
          simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using this
        have hz' : z ∈ C.walk.support := by
          by_cases hzy : y1 = y
          · simpa [z, hzy] using hy2_mem'
          · simpa [z, hzy] using hy1_mem'
        have hz'' : z ∈ C.verts (G := G) := by
          simpa [Cycle.verts, C] using hz'
        exact (C.mem_vSet_iff (G := G)).2 hz''
      -- z has no neighbor outside the cycle
      have hAllNbr : ∀ w : V, G.Adj z w → w ∈ C.vSet (G := G) := by
        intro w hAdj
        by_contra hw
        -- then z would be an attachment of some bridge, contradicting hAll
        have hzatt : z ∈ attachSet (G := G) C (G.componentComplMk (K := C.vSet (G := G)) hw) := by
          refine ⟨hzC, ⟨w, ?_, hAdj⟩⟩
          simpa [bridgeSet] using (G.componentComplMk_mem (K := C.vSet (G := G)) hw)
        have hz_in : z ∈ ({x, y} : Set V) := hAll _ hzatt
        rcases Set.mem_insert_iff.mp hz_in with hz | hz
        · exact (hz_ne_x hz).elim
        · have : z = y := by simpa [Set.mem_singleton_iff] using hz
          exact (hz_ne_y this).elim
      have hdeg : G.degree z = 2 := hdeg_two_of_all_in_cycle z hzC hAllNbr
      have hδ3z : 3 ≤ G.degree z := hδ3 z
      have hcontra : (3 : ℕ) ≤ 2 := by simp [hdeg] at hδ3z
      exfalso
      exact (Nat.not_succ_le_self 2) hcontra

omit [DecidableRel G.Adj] in
theorem exists_external_path_in_Bmax
    (hch : ∃ C : Cycle (G := G), C.IsChordless (G := G))
    (hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch)))
    {x y : V} :
    x ≠ y →
    x ∈ attachSet (G := G) (Cmax (G := G) hch) (Bmax (G := G) hch hne) →
    y ∈ attachSet (G := G) (Cmax (G := G) hch) (Bmax (G := G) hch hne) →
    ∃ p : G.Walk x y, p.IsPath ∧
      (∀ v : V, v ∈ (p.support.toFinset.erase x |>.erase y) →
        v ∉ (Cmax (G := G) hch).vSet (G := G)) := by
  classical
  intro hxy hx hy
  let C : Cycle (G := G) := Cmax (G := G) hch
  let B : Bridge (G := G) C := Bmax (G := G) hch hne
  obtain ⟨p, hp_path, hp_supp, _⟩ :=
    exists_path_between_attach (G := G) (C := C) (K := B) hx hy hxy
  refine ⟨p, hp_path, ?_⟩
  intro v hv
  have hv1 : v ≠ y ∧ v ∈ (p.support.toFinset.erase x) := by
    simpa using (Finset.mem_erase.mp hv)
  have hv2 : v ≠ x ∧ v ∈ p.support.toFinset := by
    simpa using (Finset.mem_erase.mp hv1.2)
  have hv_support : v ∈ p.support := by
    simpa using hv2.2
  have hv_bridge : v ∈ bridgeSet (G := G) C B := by
    have hcases := hp_supp v hv_support
    rcases hcases with rfl | rfl | hvK
    · exact (hv2.1 rfl).elim
    · exact (hv1.1 rfl).elim
    · exact hvK
  exact mem_bridge_imp_not_mem_cycle (G := G) (C := C) B hv_bridge

omit [DecidableEq V] in
theorem exists_two_cycles_length_dist_1_or_2
    (h2 : VertexTwoConnected (G := G))
    (hδ3 : MinDegreeGE3 (G := G))
    (hcard4 : Fintype.card V ≥ 4) :
    ∃ C1 C2 : Cycle (G := G),
      (Nat.dist (Cycle.length (G := G) C1) (Cycle.length (G := G) C2) = 1) ∨
      (Nat.dist (Cycle.length (G := G) C1) (Cycle.length (G := G) C2) = 2) := by
  classical
  have hch : ∃ C : Cycle (G := G), C.IsChordless (G := G) :=
    exists_chordless_cycle_of_h2_hδ3 (G := G) h2 hδ3 hcard4
  have hne : Nonempty (Bridge (G := G) (Cmax (G := G) hch)) :=
    nonempty_bridge_Cmax_of_hδ3 (G := G) hδ3 hcard4 hch
  let C : Cycle (G := G) := Cmax (G := G) hch
  let B : Bridge (G := G) C := Bmax (G := G) hch hne
  have hkey := BVDelta3_key_core (G := G) h2 hδ3 hcard4 hch hne
  have hattach : attachSet (G := G) C B = C.vSet (G := G) := hkey.2
  -- choose k on the cycle so that the two arc lengths differ by 1 or 2
  have hx_supp : C.base ∈ C.walk.support := by
    simp
  let r := C.walk.rotate C.base hx_supp
  have hr_cycle : r.IsCycle := C.isCycle.rotate hx_supp
  have hlen_eq : r.length = C.walk.length := by
    have hlen' :
        (C.walk.takeUntil C.base hx_supp).length + (C.walk.dropUntil C.base hx_supp).length =
          C.walk.length := by
      have hspec := SimpleGraph.Walk.take_spec (p := C.walk) (h := hx_supp)
      have hlen'' :
          (C.walk.takeUntil C.base hx_supp).length +
              (C.walk.dropUntil C.base hx_supp).length =
            ((C.walk.takeUntil C.base hx_supp).append
                (C.walk.dropUntil C.base hx_supp)).length := by
        simp
      calc
        (C.walk.takeUntil C.base hx_supp).length +
            (C.walk.dropUntil C.base hx_supp).length =
            ((C.walk.takeUntil C.base hx_supp).append
                (C.walk.dropUntil C.base hx_supp)).length := hlen''
        _ = C.walk.length := by
          simp
    calc
      r.length =
          (C.walk.dropUntil C.base hx_supp).length +
            (C.walk.takeUntil C.base hx_supp).length := by
        simp [r, SimpleGraph.Walk.rotate]
      _ =
          (C.walk.takeUntil C.base hx_supp).length +
            (C.walk.dropUntil C.base hx_supp).length := by
        simp [add_comm]
      _ = C.walk.length := hlen'
  let n : Nat := r.length
  have hn_ge3 : 3 ≤ n := by
    simpa [n, hlen_eq] using C.len_ge_three
  have hk_exists :
      ∃ k : Nat, 1 ≤ k ∧ k < n ∧
        (Nat.dist k (n - k) = 1 ∨ Nat.dist k (n - k) = 2) := by
    cases Nat.even_or_odd n with
    | inl hEven =>
        rcases hEven with ⟨m, hm⟩
        have hm_ge2 : 2 ≤ m := by
          have : 3 ≤ m + m := by
            simpa [hm, two_mul] using hn_ge3
          omega
        let k : Nat := m - 1
        have hk1 : 1 ≤ k := by
          have : 1 ≤ m - 1 := by omega
          simpa [k] using this
        have hklt : k < n := by
          have : m - 1 < m + m := by omega
          simpa [k, hm, two_mul] using this
        have hnk : n - k = m + 1 := by
          -- (2m) - (m-1) = m+1
          have : m + m - (m - 1) = m + 1 := by omega
          simpa [hm, k, two_mul] using this
        have hdist : Nat.dist k (n - k) = 2 := by
          have hdist' : Nat.dist (m - 1) (m + 1) = 2 := by
            have hle : m - 1 ≤ m + 1 := by omega
            calc
              Nat.dist (m - 1) (m + 1) = (m + 1) - (m - 1) :=
                Nat.dist_eq_sub_of_le hle
              _ = 2 := by omega
          simpa [k, hnk] using hdist'
        exact ⟨k, hk1, hklt, Or.inr hdist⟩
    | inr hOdd =>
        rcases hOdd with ⟨m, hm⟩
        let k : Nat := m
        have hk1 : 1 ≤ k := by
          have : 1 ≤ m := by
            have : 3 ≤ m + m + 1 := by
              simpa [hm, two_mul, add_assoc] using hn_ge3
            omega
          simpa [k] using this
        have hklt : k < n := by
          have : m < m + m + 1 := by omega
          simp [k, hm, two_mul, add_assoc]
        have hnk : n - k = m + 1 := by
          have : (m + m + 1) - m = m + 1 := by omega
          simp [hm, k, two_mul, add_assoc]
        have hdist : Nat.dist k (n - k) = 1 := by
          have hdist' : Nat.dist m (m + 1) = 1 := by
            simpa using (Nat.dist_eq_sub_of_le (Nat.le_succ m))
          simpa [k, hnk] using hdist'
        exact ⟨k, hk1, hklt, Or.inl hdist⟩
  rcases hk_exists with ⟨k, hk1, hklt, hkdist⟩
  -- define x and y on the cycle
  let x : V := C.base
  have hxC : x ∈ C.vSet (G := G) := by
    have hx' : x ∈ C.verts (G := G) := by
      have hx0 : C.base ∈ C.walk.support :=
        SimpleGraph.Walk.start_mem_support (p := C.walk)
      simp [Cycle.verts, C, x]
    exact (C.mem_vSet_iff (G := G)).2 hx'
  let y : V := r.getVert k
  have hy' : y ∈ r.support := by
    simp [y]
  have hyC : y ∈ C.vSet (G := G) := by
    have hy_mem' : y ∈ C.walk.support := by
      have : y ∈ r.toSubgraph.verts := by
        simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using hy'
      have : y ∈ C.walk.toSubgraph.verts := by
        simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using this
      simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using this
    have hy'' : y ∈ C.verts (G := G) := by
      simpa [Cycle.verts, C] using hy_mem'
    exact (C.mem_vSet_iff (G := G)).2 hy''
  have hk_le : k ≤ r.length := Nat.le_of_lt hklt
  have hxy : x ≠ y := by
    intro h
    have : r.getVert k = x := by
      simpa [x, y] using h.symm
    have hk' := (hr_cycle.getVert_endpoint_iff (i := k) hk_le).1 this
    rcases hk' with hk0 | hklen
    · have hkpos : 0 < k := (Nat.succ_le_iff).1 hk1
      exact (Nat.ne_of_gt hkpos) hk0
    · exact (Nat.ne_of_lt hklt) hklen
  -- attachments of x,y
  have hxAtt : x ∈ attachSet (G := G) C B := by
    simpa [hattach] using hxC
  have hyAtt : y ∈ attachSet (G := G) C B := by
    simpa [hattach] using hyC
  -- external path in Bmax
  obtain ⟨P, hP_path, hP_supp, ⟨w, hwB, hEdgeXw⟩⟩ :=
    exists_path_between_attach (G := G) (C := C) (K := B) hxAtt hyAtt hxy
  have hw_notC : w ∉ C.vSet (G := G) :=
    mem_bridge_imp_not_mem_cycle (G := G) (C := C) B hwB
  have hw_ne_y : w ≠ y := by
    intro hwy
    exact hw_notC (by simpa [hwy] using hyC)
  have hP_out :
      ∀ v : V, v ∈ P.support → v ≠ x → v ≠ y → v ∉ C.vSet (G := G) := by
    intro v hv hneX hneY
    have hv' : v ∈ (P.support.toFinset.erase x |>.erase y) := by
      have hv1 : v ≠ y ∧ v ∈ (P.support.toFinset.erase x) := by
        refine ⟨hneY, ?_⟩
        exact (Finset.mem_erase.mpr ⟨hneX, by simpa using hv⟩)
      exact (Finset.mem_erase.mpr hv1)
    have hcases := hP_supp v hv
    rcases hcases with rfl | rfl | hvK
    · exact (hneX rfl).elim
    · exact (hneY rfl).elim
    · exact mem_bridge_imp_not_mem_cycle (G := G) (C := C) B hvK
  -- arc decomposition on the cycle
  let a1 : G.Walk x y := r.takeUntil y hy'
  let a2 : G.Walk x y := (r.dropUntil y hy').reverse
  have ha1_path : a1.IsPath := hr_cycle.isPath_takeUntil hy'
  have ha1_not_nil : ¬ a1.Nil := by
    intro hnil
    have hy_mem : y ∈ a1.support := by simp [a1]
    have hsup : a1.support = [x] :=
      (SimpleGraph.Walk.nil_iff_support_eq (p := a1)).1 hnil
    have hy_eq_x : y = x := by
      have : y ∈ ([x] : List V) := by
        simpa [hsup] using hy_mem
      simpa using this
    exact hxy hy_eq_x.symm
  have hspec : r = a1.append (r.dropUntil y hy') := by
    have hspec := SimpleGraph.Walk.take_spec (p := r) (h := hy')
    simp [a1]
  have hdrop_path : (r.dropUntil y hy').IsPath := by
    have hcyc' : (a1.append (r.dropUntil y hy')).IsCycle := by
      exact (hspec ▸ hr_cycle)
    exact (SimpleGraph.Walk.IsCycle.isPath_of_append_right
      (p := a1) (q := r.dropUntil y hy') ha1_not_nil hcyc')
  have ha2_path : a2.IsPath := hdrop_path.reverse
  have ha1_subset : ∀ v : V, v ∈ a1.support → v ∈ C.vSet (G := G) := by
    intro v hv
    have hv' : v ∈ r.support := (SimpleGraph.Walk.support_takeUntil_subset_support _ _ hv)
    have hv'' : v ∈ C.walk.support := by
      have : v ∈ r.toSubgraph.verts := by
        simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using hv'
      have : v ∈ C.walk.toSubgraph.verts := by
        simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using this
      simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using this
    have hv''' : v ∈ C.verts (G := G) := by
      simpa [Cycle.verts, C] using hv''
    exact (C.mem_vSet_iff (G := G)).2 hv'''
  have ha2_subset : ∀ v : V, v ∈ a2.support → v ∈ C.vSet (G := G) := by
    intro v hv
    have hv' : v ∈ (r.dropUntil y hy').support := by
      simpa [a2, SimpleGraph.Walk.support_reverse] using hv
    have hv'' : v ∈ r.support := (SimpleGraph.Walk.support_dropUntil_subset _ _ hv')
    have hv''' : v ∈ C.walk.support := by
      have : v ∈ r.toSubgraph.verts := by
        simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using hv''
      have : v ∈ C.walk.toSubgraph.verts := by
        simpa [r, SimpleGraph.Walk.toSubgraph_rotate] using this
      simpa [SimpleGraph.Walk.mem_verts_toSubgraph] using this
    have hv'''' : v ∈ C.verts (G := G) := by
      simpa [Cycle.verts, C] using hv'''
    exact (C.mem_vSet_iff (G := G)).2 hv''''
  -- compute a1 length = k
  have ha1_len_le : a1.length ≤ r.length :=
    SimpleGraph.Walk.length_takeUntil_le (p := r) (h := hy')
  have ha1_len_lt : a1.length < r.length := by
    have hxy' : y ≠ x := hxy.symm
    exact SimpleGraph.Walk.length_takeUntil_lt (p := r) hy' hxy'
  have ha1_len_pos : 1 ≤ a1.length := by
    have : ¬ a1.Nil := ha1_not_nil
    have : 0 < a1.length := (SimpleGraph.Walk.not_nil_iff_lt_length).1 this
    exact Nat.succ_le_iff.2 this
  have ha1_len_mem : a1.length ∈ {i | 1 ≤ i ∧ i ≤ r.length} := by
    exact ⟨ha1_len_pos, ha1_len_le⟩
  have hk_mem : k ∈ {i | 1 ≤ i ∧ i ≤ r.length} := by
    exact ⟨hk1, hk_le⟩
  have hget_a1 : r.getVert a1.length = y := by
    have h1 : a1.getVert a1.length = y := by
      simp
    have h2 : a1.getVert a1.length = r.getVert a1.length := by
      exact r.getVert_takeUntil hy' (by rfl)
    exact h2.symm.trans h1
  have hlen_a1 : a1.length = k := by
    have hEq : r.getVert a1.length = r.getVert k := by
      simpa [y] using hget_a1
    exact hr_cycle.getVert_injOn ha1_len_mem hk_mem hEq
  -- length of a2
  have hlen_drop :
      (r.dropUntil y hy').length = r.length - a1.length := by
    have hlen' :
        a1.length + (r.dropUntil y hy').length = r.length := by
      have hspec := SimpleGraph.Walk.take_spec (p := r) (h := hy')
      have hlen'' : (a1.append (r.dropUntil y hy')).length = r.length := by
        simp [a1]
      simpa [SimpleGraph.Walk.length_append] using hlen''
    omega
  have hlen_a2 : a2.length = r.length - a1.length := by
    simp [a2, SimpleGraph.Walk.length_reverse, hlen_drop]
  -- support facts for P
  have hP_mem_cycle :
      ∀ v : V, v ∈ P.support → v ∈ C.vSet (G := G) → v = x ∨ v = y := by
    intro v hv hvC
    by_cases hnx : v = x
    · exact Or.inl hnx
    by_cases hny : v = y
    · exact Or.inr hny
    have : v ∉ C.vSet (G := G) := hP_out v hv hnx hny
    exact (this hvC).elim
  -- show s(x,y) not in P.edges (x has only one incident edge in a path)
  have hEdgeX_first : ∀ {u : V}, s(x, u) ∈ P.edges → s(x, u) = s(x, P.snd) := by
    intro u hmem
    have hP_not_nil : ¬ P.Nil := SimpleGraph.Walk.not_nil_of_ne (p := P) hxy
    have hcons : SimpleGraph.Walk.cons (P.adj_snd hP_not_nil) P.tail = P :=
      SimpleGraph.Walk.cons_tail_eq (p := P) hP_not_nil
    have hEdges' :
        P.edges = s(x, P.snd) :: P.tail.edges := by
      have hEdges'' :
          (SimpleGraph.Walk.cons (P.adj_snd hP_not_nil) P.tail).edges =
            s(x, P.snd) :: P.tail.edges := by
        simp
      simpa [hcons] using hEdges''
    have hmem' : s(x, u) = s(x, P.snd) ∨ s(x, u) ∈ P.tail.edges := by
      have : s(x, u) ∈ s(x, P.snd) :: P.tail.edges := by
        simpa [hEdges'] using hmem
      simpa using (List.mem_cons.1 this)
    rcases hmem' with hmem' | hmem'
    · exact hmem'
    · have hP_nodup : P.support.Nodup :=
        (SimpleGraph.Walk.isPath_def (p := P)).1 hP_path
      have hx_not_tail : x ∉ P.support.tail := by
        have hsup : P.support = x :: P.support.tail :=
          (SimpleGraph.Walk.cons_tail_support (p := P)).symm
        have hcons' : (x :: P.support.tail).Nodup := by
          exact hsup ▸ hP_nodup
        exact (List.nodup_cons.mp hcons').1
      have hx_not_tail' : x ∉ P.tail.support := by
        have htail : P.tail.support = P.support.tail := by
          simpa using (SimpleGraph.Walk.support_tail_of_not_nil (p := P) hP_not_nil)
        simpa [htail] using hx_not_tail
      have hx_in_tail : x ∈ P.tail.support :=
        SimpleGraph.Walk.fst_mem_support_of_mem_edges (p := P.tail) hmem'
      exact (hx_not_tail' hx_in_tail).elim
  have hEdgeXY_not : s(x, y) ∉ P.edges := by
    intro hxyEdge
    have hxy1 : s(x, y) = s(x, P.snd) := hEdgeX_first hxyEdge
    have hxw1 : s(x, w) = s(x, P.snd) := hEdgeX_first hEdgeXw
    have hxyw : s(x, y) = s(x, w) := hxy1.trans hxw1.symm
    have hw : w = y := by
      have : w ∈ s(x, y) := by
        have : w ∈ s(x, w) := by simp
        simp [hxyw]
      have := (Sym2.mem_iff.mp this)
      cases this with
      | inl h =>
          exact (hw_notC (by simpa [h] using hxC)).elim
      | inr h => exact h
    exact (hw_ne_y hw).elim
  -- cycles built from a1/a2 and external path
  let W1 : G.Walk x x := a1.append P.reverse
  let W2 : G.Walk x x := a2.append P.reverse
  have hPrev_path : P.reverse.IsPath := hP_path.reverse
  have hW1_cycle : W1.IsCycle := by
    -- IsTrail via edges nodup
    have hA1_nodup : a1.support.Nodup :=
      (SimpleGraph.Walk.isPath_def _).1 ha1_path
    have hP_nodup : P.support.Nodup :=
      (SimpleGraph.Walk.isPath_def _).1 hP_path
    have hA1_edges_nodup : a1.edges.Nodup :=
      SimpleGraph.Walk.edges_nodup_of_support_nodup hA1_nodup
    have hP_edges_nodup : (P.reverse).edges.Nodup := by
      have hP_edges : P.edges.Nodup :=
        SimpleGraph.Walk.edges_nodup_of_support_nodup hP_nodup
      have : P.edges.reverse.Nodup := (List.nodup_reverse.mpr hP_edges)
      simpa [SimpleGraph.Walk.edges_reverse] using this
    have hdis_edges : List.Disjoint a1.edges (P.reverse).edges := by
      intro e he1 he2
      have he2' : e ∈ P.edges := by
        have : e ∈ P.edges.reverse := by
          simpa [SimpleGraph.Walk.edges_reverse] using he2
        simpa using (List.mem_reverse.mp this)
      -- endpoints of e lie on C via a1
      have he1' : s(e.out.1, e.out.2) ∈ a1.edges := by
        simpa [e.out_eq] using he1
      have he2'' : s(e.out.1, e.out.2) ∈ P.edges := by
        simpa [e.out_eq] using he2'
      have hu : e.out.1 ∈ a1.support :=
        SimpleGraph.Walk.fst_mem_support_of_mem_edges (p := a1) he1'
      have hv : e.out.2 ∈ a1.support :=
        SimpleGraph.Walk.snd_mem_support_of_mem_edges (p := a1) he1'
      have huC : e.out.1 ∈ C.vSet (G := G) := ha1_subset _ hu
      have hvC : e.out.2 ∈ C.vSet (G := G) := ha1_subset _ hv
      have huP : e.out.1 ∈ P.support :=
        SimpleGraph.Walk.fst_mem_support_of_mem_edges (p := P) he2''
      have hvP : e.out.2 ∈ P.support :=
        SimpleGraph.Walk.snd_mem_support_of_mem_edges (p := P) he2''
      have huXY : e.out.1 = x ∨ e.out.1 = y := hP_mem_cycle _ huP huC
      have hvXY : e.out.2 = x ∨ e.out.2 = y := hP_mem_cycle _ hvP hvC
      have he_xy : e = s(x, y) := by
        have hAdj : G.Adj e.out.1 e.out.2 :=
          SimpleGraph.Walk.adj_of_mem_edges (p := a1) he1'
        have hne : e.out.1 ≠ e.out.2 := G.ne_of_adj hAdj
        have heout : s(e.out.1, e.out.2) = e := by
          simp [Sym2.mk]
        cases huXY with
        | inl hux =>
            cases hvXY with
            | inl hvx =>
                exfalso
                exact hne (by simp [hux, hvx])
            | inr hvy =>
                have : e = s(x, y) := by
                  calc
                    e = s(e.out.1, e.out.2) := heout.symm
                    _ = s(x, y) := by simp [hux, hvy]
                exact this
        | inr huy =>
            cases hvXY with
            | inl hvx =>
                have : e = s(y, x) := by
                  calc
                    e = s(e.out.1, e.out.2) := heout.symm
                    _ = s(y, x) := by simp [huy, hvx]
                simpa [Sym2.eq_swap] using this
            | inr hvy =>
                exfalso
                exact hne (by simp [huy, hvy])
      have : s(x, y) ∈ P.edges := by
        simpa [he_xy] using he2'
      exact (hEdgeXY_not this).elim
    have htrail : W1.IsTrail := by
      -- use edges_nodup for append
      have : (a1.edges ++ (P.reverse).edges).Nodup :=
        (List.Nodup.append hA1_edges_nodup hP_edges_nodup hdis_edges)
      -- rewrite edges of append
      have hnodup : W1.edges.Nodup := by
        simpa [W1, SimpleGraph.Walk.edges_append] using this
      exact (SimpleGraph.Walk.isTrail_def (p := W1)).2 hnodup
    have htail_nodup : W1.support.tail.Nodup := by
      have hA1_tail : a1.support.tail.Nodup := hA1_nodup.tail
      have hPrev_nodup : (P.reverse).support.Nodup :=
        (SimpleGraph.Walk.isPath_def _).1 hPrev_path
      have hPrev_tail : (P.reverse).support.tail.Nodup := hPrev_nodup.tail
      have hdis_tail : List.Disjoint a1.support.tail (P.reverse).support.tail := by
        intro v hv1 hv2
        have hv1' : v ∈ a1.support := List.mem_of_mem_tail hv1
        have hvC : v ∈ C.vSet (G := G) := ha1_subset _ hv1'
        have hv2' : v ∈ (P.reverse).support := List.mem_of_mem_tail hv2
        have hv2'' : v ∈ P.support := by
          have hrev : (P.reverse).support = P.support.reverse :=
            SimpleGraph.Walk.support_reverse (p := P)
          have hv2'' : v ∈ P.support.reverse := by
            simpa [hrev] using hv2'
          exact (List.mem_reverse.mp hv2'')
        have hx_not_tail : x ∉ a1.support.tail := by
          have hsup : a1.support = x :: a1.support.tail :=
            (SimpleGraph.Walk.cons_tail_support (p := a1)).symm
          have hcons : (x :: a1.support.tail).Nodup := by
            exact hsup ▸ hA1_nodup
          exact (List.nodup_cons.mp hcons).1
        have hy_not_tail : y ∉ (P.reverse).support.tail := by
          have hsup : (P.reverse).support = y :: (P.reverse).support.tail :=
            (SimpleGraph.Walk.cons_tail_support (p := P.reverse)).symm
          have hcons : (y :: (P.reverse).support.tail).Nodup := by
            exact hsup ▸ hPrev_nodup
          exact (List.nodup_cons.mp hcons).1
        have hv_ne_x : v ≠ x := by
          intro h
          subst h
          exact (hx_not_tail hv1).elim
        have hv_ne_y : v ≠ y := by
          intro h
          subst h
          exact (hy_not_tail hv2).elim
        have hv_out : v ∉ C.vSet (G := G) := hP_out v hv2'' hv_ne_x hv_ne_y
        exact (hv_out hvC).elim
      have : (a1.support.tail ++ (P.reverse).support.tail).Nodup :=
        (List.Nodup.append hA1_tail hPrev_tail hdis_tail)
      have htail_eq :
          W1.support.tail = a1.support.tail ++ (P.reverse).support.tail := by
        simpa [W1] using
          (SimpleGraph.Walk.tail_support_append (p := a1) (p' := P.reverse))
      simpa [htail_eq] using this
    -- assemble IsCycle
    have hnot_nil : W1 ≠ SimpleGraph.Walk.nil := by
      intro hnil
      have : (0 : Nat) < W1.length := by
        have : 0 < a1.length := (SimpleGraph.Walk.not_nil_iff_lt_length).1 ha1_not_nil
        have : 0 < a1.length + P.length := Nat.lt_of_lt_of_le this (Nat.le_add_right _ _)
        simpa [W1, SimpleGraph.Walk.length_append, SimpleGraph.Walk.length_reverse] using this
      exact (SimpleGraph.Walk.not_nil_iff_lt_length).2 this (by simp [hnil])
    -- use isCycle_def
    have hcycle_def : W1.IsCycle :=
      (SimpleGraph.Walk.isCycle_def (p := W1)).2 ⟨htrail, hnot_nil, htail_nodup⟩
    exact hcycle_def
  have hW2_cycle : W2.IsCycle := by
    -- same argument with a2
    have hA2_nodup : a2.support.Nodup :=
      (SimpleGraph.Walk.isPath_def _).1 ha2_path
    have hP_nodup : P.support.Nodup :=
      (SimpleGraph.Walk.isPath_def _).1 hP_path
    have hA2_edges_nodup : a2.edges.Nodup :=
      SimpleGraph.Walk.edges_nodup_of_support_nodup hA2_nodup
    have hP_edges_nodup : (P.reverse).edges.Nodup := by
      have hP_edges : P.edges.Nodup :=
        SimpleGraph.Walk.edges_nodup_of_support_nodup hP_nodup
      have : P.edges.reverse.Nodup := (List.nodup_reverse.mpr hP_edges)
      simpa [SimpleGraph.Walk.edges_reverse] using this
    have hdis_edges : List.Disjoint a2.edges (P.reverse).edges := by
      intro e he1 he2
      have he2' : e ∈ P.edges := by
        have : e ∈ P.edges.reverse := by
          simpa [SimpleGraph.Walk.edges_reverse] using he2
        simpa using (List.mem_reverse.mp this)
      have he1' : s(e.out.1, e.out.2) ∈ a2.edges := by
        simpa [e.out_eq] using he1
      have he2'' : s(e.out.1, e.out.2) ∈ P.edges := by
        simpa [e.out_eq] using he2'
      have hu : e.out.1 ∈ a2.support :=
        SimpleGraph.Walk.fst_mem_support_of_mem_edges (p := a2) he1'
      have hv : e.out.2 ∈ a2.support :=
        SimpleGraph.Walk.snd_mem_support_of_mem_edges (p := a2) he1'
      have huC : e.out.1 ∈ C.vSet (G := G) := ha2_subset _ hu
      have hvC : e.out.2 ∈ C.vSet (G := G) := ha2_subset _ hv
      have huP : e.out.1 ∈ P.support :=
        SimpleGraph.Walk.fst_mem_support_of_mem_edges (p := P) he2''
      have hvP : e.out.2 ∈ P.support :=
        SimpleGraph.Walk.snd_mem_support_of_mem_edges (p := P) he2''
      have huXY : e.out.1 = x ∨ e.out.1 = y := hP_mem_cycle _ huP huC
      have hvXY : e.out.2 = x ∨ e.out.2 = y := hP_mem_cycle _ hvP hvC
      have he_xy : e = s(x, y) := by
        have hAdj : G.Adj e.out.1 e.out.2 :=
          SimpleGraph.Walk.adj_of_mem_edges (p := a2) he1'
        have hne : e.out.1 ≠ e.out.2 := G.ne_of_adj hAdj
        have heout : s(e.out.1, e.out.2) = e := by
          simp [Sym2.mk]
        cases huXY with
        | inl hux =>
            cases hvXY with
            | inl hvx =>
                exfalso
                exact hne (by simp [hux, hvx])
            | inr hvy =>
                have : e = s(x, y) := by
                  calc
                    e = s(e.out.1, e.out.2) := heout.symm
                    _ = s(x, y) := by simp [hux, hvy]
                exact this
        | inr huy =>
            cases hvXY with
            | inl hvx =>
                have : e = s(y, x) := by
                  calc
                    e = s(e.out.1, e.out.2) := heout.symm
                    _ = s(y, x) := by simp [huy, hvx]
                simpa [Sym2.eq_swap] using this
            | inr hvy =>
                exfalso
                exact hne (by simp [huy, hvy])
      have : s(x, y) ∈ P.edges := by
        simpa [he_xy] using he2'
      exact (hEdgeXY_not this).elim
    have htrail : W2.IsTrail := by
      have : (a2.edges ++ (P.reverse).edges).Nodup :=
        (List.Nodup.append hA2_edges_nodup hP_edges_nodup hdis_edges)
      have hnodup : W2.edges.Nodup := by
        simpa [W2, SimpleGraph.Walk.edges_append] using this
      exact (SimpleGraph.Walk.isTrail_def (p := W2)).2 hnodup
    have htail_nodup : W2.support.tail.Nodup := by
      have hA2_tail : a2.support.tail.Nodup := hA2_nodup.tail
      have hPrev_nodup : (P.reverse).support.Nodup :=
        (SimpleGraph.Walk.isPath_def _).1 hPrev_path
      have hPrev_tail : (P.reverse).support.tail.Nodup := hPrev_nodup.tail
      have hdis_tail : List.Disjoint a2.support.tail (P.reverse).support.tail := by
        intro v hv1 hv2
        have hv1' : v ∈ a2.support := List.mem_of_mem_tail hv1
        have hvC : v ∈ C.vSet (G := G) := ha2_subset _ hv1'
        have hv2' : v ∈ (P.reverse).support := List.mem_of_mem_tail hv2
        have hv2'' : v ∈ P.support := by
          have hrev : (P.reverse).support = P.support.reverse :=
            SimpleGraph.Walk.support_reverse (p := P)
          have hv2'' : v ∈ P.support.reverse := by
            simpa [hrev] using hv2'
          exact (List.mem_reverse.mp hv2'')
        have hx_not_tail : x ∉ a2.support.tail := by
          have hsup : a2.support = x :: a2.support.tail :=
            (SimpleGraph.Walk.cons_tail_support (p := a2)).symm
          have hcons : (x :: a2.support.tail).Nodup := by
            exact hsup ▸ hA2_nodup
          exact (List.nodup_cons.mp hcons).1
        have hy_not_tail : y ∉ (P.reverse).support.tail := by
          have hsup : (P.reverse).support = y :: (P.reverse).support.tail :=
            (SimpleGraph.Walk.cons_tail_support (p := P.reverse)).symm
          have hcons : (y :: (P.reverse).support.tail).Nodup := by
            exact hsup ▸ hPrev_nodup
          exact (List.nodup_cons.mp hcons).1
        have hv_ne_x : v ≠ x := by
          intro h
          subst h
          exact (hx_not_tail hv1).elim
        have hv_ne_y : v ≠ y := by
          intro h
          subst h
          exact (hy_not_tail hv2).elim
        have hv_out : v ∉ C.vSet (G := G) := hP_out v hv2'' hv_ne_x hv_ne_y
        exact (hv_out hvC).elim
      have : (a2.support.tail ++ (P.reverse).support.tail).Nodup :=
        (List.Nodup.append hA2_tail hPrev_tail hdis_tail)
      have htail_eq :
          W2.support.tail = a2.support.tail ++ (P.reverse).support.tail := by
        simpa [W2] using
          (SimpleGraph.Walk.tail_support_append (p := a2) (p' := P.reverse))
      simpa [htail_eq] using this
    have hnot_nil : W2 ≠ SimpleGraph.Walk.nil := by
      intro hnil
      have : (0 : Nat) < W2.length := by
        have : 0 < a2.length := by
          have : ¬ a2.Nil := by
            intro hnil'
            have hy_mem : y ∈ a2.support := by simp [a2]
            have hy_eq_x : y = x := by
              simpa [SimpleGraph.Walk.nil_iff_support_eq.mp hnil'] using hy_mem
            exact hxy hy_eq_x.symm
          exact (SimpleGraph.Walk.not_nil_iff_lt_length).1 this
        have : 0 < a2.length + P.length := Nat.lt_of_lt_of_le this (Nat.le_add_right _ _)
        simpa [W2, SimpleGraph.Walk.length_append, SimpleGraph.Walk.length_reverse] using this
      exact (SimpleGraph.Walk.not_nil_iff_lt_length).2 this (by simp [hnil])
    have hcycle_def : W2.IsCycle :=
      (SimpleGraph.Walk.isCycle_def (p := W2)).2 ⟨htrail, hnot_nil, htail_nodup⟩
    exact hcycle_def
  -- build Cycle structures
  let C1 : Cycle (G := G) :=
    { base := x
      walk := W1
      isCycle := hW1_cycle
      len_ge_three := by simpa using hW1_cycle.three_le_length }
  let C2 : Cycle (G := G) :=
    { base := x
      walk := W2
      isCycle := hW2_cycle
      len_ge_three := by simpa using hW2_cycle.three_le_length }
  have hlenC1 : Cycle.length (G := G) C1 = P.length + a1.length := by
    simp [C1, W1, Cycle.length, SimpleGraph.Walk.length_append, SimpleGraph.Walk.length_reverse,
      Nat.add_comm]
  have hlenC2 : Cycle.length (G := G) C2 = P.length + a2.length := by
    simp [C2, W2, Cycle.length, SimpleGraph.Walk.length_append, SimpleGraph.Walk.length_reverse,
      Nat.add_comm]
  have hdist :
      Nat.dist (Cycle.length (G := G) C1) (Cycle.length (G := G) C2) =
        Nat.dist k (n - k) := by
    -- cancel P.length, use arc lengths
    have hdist' :
        Nat.dist (P.length + a1.length) (P.length + a2.length) =
          Nat.dist a1.length a2.length := by
      simp [Nat.dist_add_add_left]
    have hdist'' : Nat.dist a1.length a2.length = Nat.dist k (n - k) := by
      -- rewrite a1.length = k and a2.length = n - a1.length
      calc
        Nat.dist a1.length a2.length =
            Nat.dist k (r.length - a1.length) := by
              simp [hlen_a1, hlen_a2]
        _ = Nat.dist k (n - k) := by
              simp [n, hlen_a1]
    simpa [hlenC1, hlenC2] using hdist'.trans hdist''
  cases hkdist with
  | inl h1 =>
      refine ⟨C1, C2, Or.inl ?_⟩
      simpa [h1] using hdist
  | inr h2 =>
      refine ⟨C1, C2, Or.inr ?_⟩
      simpa [h2] using hdist

end BV
end Erdos751

namespace Erdos751

universe u
variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

namespace Critical

/-
  IMPORTANT ENGINEERING NOTE

  We must *fix* the Fintype instance on the subtype `{v // v ∈ S}`.
  Otherwise, `hδ3` and `hcard4` can be stored under one instance
  (e.g. `Finset.Subtype.fintype S`) while `Main` expects another
  (e.g. `Subtype.fintype ...`), and definitional equality will fail.

  Therefore: use `Finset.Subtype.fintype S` everywhere for the witness subtype.
-/

/-- Canonical (locked) `Fintype` instance on `{v // v ∈ S}`. -/
abbrev instSub (S : Finset V) : Fintype {v : V // v ∈ S} :=
  Finset.Subtype.fintype S

structure Witness where
  S : Finset V
  h2 : BV.VertexTwoConnected (G := G.induce (fun v : V => v ∈ S))

  -- Store hypotheses under the *locked* subtype Fintype instance.
  hδ3 :
    @BV.MinDegreeGE3 {v : V // v ∈ S}
      (instSub (V := V) S)
      (G.induce (fun v : V => v ∈ S))
      (by infer_instance)

  hcard4 :
    @Fintype.card {v : V // v ∈ S} (instSub (V := V) S) ≥ 4

/-- Induced graph carried by a witness (abbrev => definitional equality behaves). -/
abbrev H (W : Witness (G := G)) : SimpleGraph {v : V // v ∈ W.S} :=
  G.induce (fun v : V => v ∈ W.S)

set_option maxHeartbeats 50000000 in
-- This construction minimizes over induced subgraphs and builds the critical witness;
-- the proof repeatedly unfolds finite colorability witnesses and needs a higher bound.
noncomputable def exists_witness_of_chromaticNumber_ge_4
    (hχ : (4 : ℕ∞) ≤ G.chromaticNumber) :
    Witness (G := G) := by
      sorry
end Critical
end Erdos751

namespace Erdos751

universe u
variable {V : Type u} [Fintype V] [DecidableEq V]
variable (G : SimpleGraph V) [DecidableRel G.Adj]

namespace Main

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
theorem lift_cycle_from_induce_preserve_length
    {S : Finset V}
    (C : BV.Cycle (G := G.induce (fun v : V => v ∈ S))) :
    ∃ C' : BV.Cycle (G := G),
      BV.Cycle.length (G := G) C' =
        BV.Cycle.length (G := G.induce (fun v : V => v ∈ S)) C := by
  classical
  let f : (G.induce (fun v : V => v ∈ S)) →g G :=
    { toFun := fun v => v.1
      map_rel' := by
        intro v w h
        simpa using h }
  have hinj : Function.Injective f := by
    intro v w h
    apply Subtype.ext
    exact h
  let C' : BV.Cycle (G := G) :=
    { base := C.base.1
      walk := C.walk.map f
      isCycle := by
        simpa using (C.isCycle.map hinj)
      len_ge_three := by
        simpa using C.len_ge_three }
  refine ⟨C', ?_⟩
  simp [BV.Cycle.length, C', SimpleGraph.Walk.length_map]

omit [Fintype V] [DecidableEq V] [DecidableRel G.Adj] in
theorem erdos_751_strong [Finite V]
    (hχ : (4 : ℕ∞) ≤ G.chromaticNumber) :
    ∃ C1 C2 : BV.Cycle (G := G),
      (Nat.dist (BV.Cycle.length (G := G) C1) (BV.Cycle.length (G := G) C2) = 1) ∨
      (Nat.dist (BV.Cycle.length (G := G) C1) (BV.Cycle.length (G := G) C2) = 2) := by
        sorry
-- 'Erdos751.Main.erdos_751_strong' depends on axioms: [propext, choice, Quot.sound]

end Main
end Erdos751
