/- leanprover/lean4:v4.32.0  mathlib v4.32.0 -/
/-
This file derives the existence and nontriviality of the natural density of
semiperfect numbers from the solution of Erdős Problem 469.
-/
import ErdosProblems.Erdos469
import Util.Density

namespace Erdos469b

open Filter Set
open scoped Topology

open Erdos469

noncomputable section

/-- The positive multiples of `a`. -/
def positiveMultiples (a : ℕ) : Set ℕ := {n | 0 < n ∧ a ∣ n}

/-- The positive multiples generated by a finite set. -/
def finiteMultiples (s : Finset ℕ) : Set ℕ :=
  {n | 0 < n ∧ ∃ a ∈ s, a ∣ n}

@[simp]
theorem mem_positiveMultiples {a n : ℕ} :
    n ∈ positiveMultiples a ↔ 0 < n ∧ a ∣ n := Iff.rfl

@[simp]
theorem mem_finiteMultiples {s : Finset ℕ} {n : ℕ} :
    n ∈ finiteMultiples s ↔ 0 < n ∧ ∃ a ∈ s, a ∣ n := Iff.rfl

@[simp]
theorem finiteMultiples_empty : finiteMultiples ∅ = ∅ := by
  ext n
  simp

theorem finiteMultiples_insert (a : ℕ) (s : Finset ℕ) :
    finiteMultiples (insert a s) = positiveMultiples a ∪ finiteMultiples s := by
  ext n
  simp only [mem_finiteMultiples, Finset.mem_insert, mem_positiveMultiples,
    Set.mem_union]
  aesop

theorem positiveMultiples_inter (a b : ℕ) :
    positiveMultiples a ∩ positiveMultiples b = positiveMultiples (a.lcm b) := by
  ext n
  simp only [Set.mem_inter_iff, mem_positiveMultiples, Nat.lcm_dvd_iff]
  aesop

theorem positiveMultiples_inter_finiteMultiples (a : ℕ) (s : Finset ℕ) :
    positiveMultiples a ∩ finiteMultiples s =
      finiteMultiples (s.image (Nat.lcm a)) := by
  ext n
  constructor
  · rintro ⟨⟨hn, han⟩, ⟨_, b, hb, hbn⟩⟩
    exact ⟨hn, a.lcm b, Finset.mem_image.mpr ⟨b, hb, rfl⟩,
      Nat.lcm_dvd_iff.mpr ⟨han, hbn⟩⟩
  · rintro ⟨hn, c, hc, hcn⟩
    obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hc
    exact ⟨⟨hn, (Nat.lcm_dvd_iff.mp hcn).1⟩,
      ⟨hn, b, hb, (Nat.lcm_dvd_iff.mp hcn).2⟩⟩

/-- Inclusion-exclusion transfers natural densities to a union. -/
theorem hasDensity_union_of_inter {S T : Set ℕ} {dS dT dI : ℝ}
    (hS : S.HasDensity dS) (hT : T.HasDensity dT)
    (hI : (S ∩ T).HasDensity dI) :
    (S ∪ T).HasDensity (dS + dT - dI) := by
  rw [Set.HasDensity] at hS hT hI ⊢
  apply (hS.add hT).sub hI |>.congr'
  filter_upwards with n
  simp only [Set.partialDensity, Set.inter_univ, Set.univ_inter]
  have hcard := Set.ncard_union_add_ncard_inter
    (S ∩ Set.Iio n) (T ∩ Set.Iio n)
  have hunion : (S ∪ T) ∩ Set.Iio n =
      (S ∩ Set.Iio n) ∪ (T ∩ Set.Iio n) := by aesop
  have hinter : (S ∩ T) ∩ Set.Iio n =
      (S ∩ Set.Iio n) ∩ (T ∩ Set.Iio n) := by aesop
  rw [hunion, hinter]
  rw [div_eq_mul_inv, div_eq_mul_inv, div_eq_mul_inv, div_eq_mul_inv]
  have hcardR :
      ((S ∩ Set.Iio n ∪ T ∩ Set.Iio n).ncard : ℝ) +
          ((S ∩ Set.Iio n ∩ (T ∩ Set.Iio n)).ncard : ℝ) =
        ((S ∩ Set.Iio n).ncard : ℝ) +
          ((T ∩ Set.Iio n).ncard : ℝ) := by
    exact_mod_cast hcard
  linear_combination -hcardR * (((Set.Iio n).ncard : ℝ)⁻¹)

/-- A bounded-error linear count has the expected limiting density. -/
theorem hasDensity_of_counting_error
    (S : Set ℕ) (c C : ℝ)
    (h : ∀ n, |((S ∩ Set.Iio n).ncard : ℝ) - c * n| ≤ C) :
    S.HasDensity c := by
  rw [Set.HasDensity]
  have hzero : Tendsto
      (fun n : ℕ =>
        (((S ∩ Set.Iio n).ncard : ℝ) - c * n) / n)
      atTop (𝓝 0) := by
    exact squeeze_zero_norm
      (fun n => by
        simpa [abs_div] using
          div_le_div_of_nonneg_right (h n) (Nat.cast_nonneg n))
      (tendsto_const_nhds.div_atTop tendsto_natCast_atTop_atTop)
  simpa only [zero_add] using (hzero.add_const c).congr' (by
    filter_upwards [Filter.eventually_gt_atTop 0] with n hn
    simp only [Set.partialDensity, Set.inter_univ, Set.univ_inter]
    have hIio : (Set.Iio n).ncard = n := by simp
    rw [hIio]
    field_simp
    ring)

/-- The positive multiples of a positive integer have density `1 / a`. -/
theorem positiveMultiples_hasDensity {a : ℕ} (ha : 0 < a) :
    (positiveMultiples a).HasDensity (1 / (a : ℝ)) := by
  apply hasDensity_of_counting_error _ _ 2
  intro n
  rcases n.eq_zero_or_pos with rfl | hn
  · simp [positiveMultiples]
  have hcard : (positiveMultiples a ∩ Set.Iio n).ncard = (n - 1) / a := by
    rw [show positiveMultiples a ∩ Set.Iio n =
        ↑((Finset.Ioc 0 (n - 1)).filter (fun m => a ∣ m)) by
      ext m
      simp only [Set.mem_inter_iff, mem_positiveMultiples, Set.mem_Iio,
        Finset.mem_coe, Finset.mem_filter, Finset.mem_Ioc]
      omega]
    simp only [Set.ncard_coe_finset]
    exact Nat.Ioc_filter_dvd_card_eq_div (n - 1) a
  rw [hcard]
  have hdivle : (((n - 1) / a : ℕ) : ℝ) ≤ ((n - 1 : ℕ) : ℝ) / a :=
    Nat.cast_div_le
  have hdivlower : ((n - 1 : ℕ) : ℝ) / a - 1 <
      (((n - 1) / a : ℕ) : ℝ) := by
    have hfloorNat : n - 1 < ((n - 1) / a + 1) * a :=
      (Nat.div_lt_iff_lt_mul ha).mp (by omega)
    have haR : (0 : ℝ) < a := by exact_mod_cast ha
    rw [sub_lt_iff_lt_add, div_lt_iff₀ haR]
    exact_mod_cast hfloorNat
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  have haR : (0 : ℝ) < a := by exact_mod_cast ha
  have haOne : (1 : ℝ) ≤ a := by exact_mod_cast ha
  have hainvle : (1 : ℝ) / a ≤ 1 := by
    exact (div_le_one₀ haR).mpr haOne
  have hnsub : ((n - 1 : ℕ) : ℝ) = n - 1 := by
    rw [Nat.cast_sub (Nat.one_le_iff_ne_zero.mpr hn.ne')]
    norm_num
  rw [hnsub] at hdivle hdivlower
  have hnonpos : (((n - 1) / a : ℕ) : ℝ) -
      1 / (a : ℝ) * n ≤ 0 := by
    have hqle : (((n - 1) / a : ℕ) : ℝ) ≤ (n : ℝ) / a :=
      hdivle.trans (div_le_div_of_nonneg_right (by linarith) haR.le)
    simpa [div_eq_mul_inv, one_div, mul_comm] using sub_nonpos.mpr hqle
  rw [abs_of_nonpos hnonpos]
  have hsplit : (n - 1 : ℝ) / a = n / a - 1 / a := by ring
  rw [hsplit] at hdivlower
  have hlower : (n : ℝ) / a - 2 < (((n - 1) / a : ℕ) : ℝ) := by
    linarith
  have hmul : (n : ℝ) / a = 1 / (a : ℝ) * n := by ring
  rw [← hmul]
  linarith

/-- Every finite union of sets of positive multiples has a natural density. -/
theorem finiteMultiples_hasDensity (s : Finset ℕ)
    (hpos : ∀ a ∈ s, 0 < a) :
    ∃ d : ℝ, (finiteMultiples s).HasDensity d := by
  classical
  induction hcard : s.card using Nat.strong_induction_on generalizing s with
  | h k ih =>
      by_cases hs : s = ∅
      · subst s
        exact ⟨0, by simp [Set.HasDensity, finiteMultiples_empty,
          Set.partialDensity]⟩
      · obtain ⟨a, ha⟩ := s.nonempty_iff_ne_empty.mpr hs
        let t := s.erase a
        have htcard : t.card < k := by
          rw [← hcard]
          exact Finset.card_erase_lt_of_mem ha
        have htpos : ∀ b ∈ t, 0 < b := fun b hb => hpos b (Finset.mem_of_mem_erase hb)
        obtain ⟨dt, hdt⟩ := ih t.card htcard t htpos rfl
        let u := t.image (Nat.lcm a)
        have hucard : u.card < k :=
          (Finset.card_image_le.trans_lt htcard)
        have hupos : ∀ b ∈ u, 0 < b := by
          intro b hb
          obtain ⟨c, hc, rfl⟩ := Finset.mem_image.mp hb
          exact Nat.lcm_pos (hpos a ha) (htpos c hc)
        obtain ⟨du, hdu⟩ := ih u.card hucard u hupos rfl
        have haDensity := positiveMultiples_hasDensity (hpos a ha)
        have hinter : (positiveMultiples a ∩ finiteMultiples t).HasDensity du := by
          simpa [u, positiveMultiples_inter_finiteMultiples] using hdu
        refine ⟨1 / (a : ℝ) + dt - du, ?_⟩
        rw [show s = insert a t by simp [t, ha]]
        rw [finiteMultiples_insert]
        exact hasDensity_union_of_inter haDensity hdt hinter

/-- The set of all multiples of an indexed family. -/
def indexedMultiples {ι : Type*} (A : ι → ℕ) : Set ℕ :=
  Set.range fun x : ℕ × ι => x.1 * A x.2

/-- The number of positive multiples below `N` is bounded by the reciprocal
sum of the generators. -/
theorem card_indexedMultiples_inter_Ioo_le {ι : Type*}
    (A : ι → ℕ) (h : Summable fun i => 1 / (A i : ℝ)) (N : ℕ) :
    ((indexedMultiples A ∩ Set.Ioo 0 N).ncard : ℝ) ≤
      N * ∑' i, 1 / (A i : ℝ) := by
  classical
  rcases N.eq_zero_or_pos with rfl | hN
  · simp [indexedMultiples]
  let exceptional : Finset ι :=
    (h.tendsto_cofinite_zero.eventually
      (gt_mem_nhds (show (0 : ℝ) < 1 / N by positivity))).toFinset
  have hcount :
      (Finset.filter
        (fun n => ∃ i, A i ≠ 0 ∧ A i ∣ n)
        (Finset.Ioo 0 N)).card ≤
        ∑ i ∈ exceptional, N / A i := by
    calc
      (Finset.filter
          (fun n => ∃ i, A i ≠ 0 ∧ A i ∣ n)
          (Finset.Ioo 0 N)).card
          ≤ (Finset.biUnion exceptional fun i =>
              Finset.filter (fun n => A i ∣ n) (Finset.Ioo 0 N)).card := by
            apply Finset.card_le_card
            simp only [Finset.subset_iff, Finset.mem_filter, Finset.mem_Ioo,
              Finset.mem_biUnion, exceptional]
            rintro x ⟨⟨hxpos, hxN⟩, ⟨i, hi0, hix⟩⟩
            refine ⟨i, ?_, ⟨hxpos, hxN⟩, hix⟩
            have hAi : A i ≤ N :=
              (Nat.le_of_dvd hxpos hix).trans (Nat.le_of_lt hxN)
            have hinv : (1 : ℝ) / N ≤ 1 / A i := by
              exact one_div_le_one_div_of_le
                (Nat.cast_pos.mpr (Nat.pos_of_ne_zero hi0)) (by exact_mod_cast hAi)
            simpa [exceptional] using not_lt_of_ge hinv
      _ ≤ ∑ i ∈ exceptional,
          (Finset.filter (fun n => A i ∣ n) (Finset.Ioo 0 N)).card :=
        Finset.card_biUnion_le
      _ ≤ ∑ i ∈ exceptional, N / A i := by
        apply Finset.sum_le_sum
        intro i hi
        let multiples :=
          (Finset.Ico 1 (N / A i + 1)).image fun k => A i * k
        calc
          (Finset.filter (fun n => A i ∣ n) (Finset.Ioo 0 N)).card
              ≤ multiples.card := by
                apply Finset.card_le_card
                intro x hx
                simp only [Finset.mem_filter, Finset.mem_Ioo] at hx
                obtain ⟨⟨hxpos, hxN⟩, hAix⟩ := hx
                have hi0 : A i ≠ 0 := by
                  intro hi
                  rw [hi] at hAix
                  have hxzero : x = 0 := by simpa using hAix
                  omega
                refine Finset.mem_image.mpr
                  ⟨x / A i, ?_, Nat.mul_div_cancel' hAix⟩
                simp only [Finset.mem_Ico]
                exact ⟨Nat.div_pos (Nat.le_of_dvd hxpos hAix)
                  (Nat.pos_of_ne_zero hi0),
                    (Nat.div_le_div_right hxN.le).trans_lt (Nat.lt_succ_self _)⟩
          _ ≤ (Finset.Ico 1 (N / A i + 1)).card := Finset.card_image_le
          _ = N / A i := by simp
  have hfiniteSum :
      (∑ i ∈ exceptional, (N / A i : ℕ) : ℕ) ≤
        N * ∑ i ∈ exceptional, (1 / (A i : ℝ)) := by
    push_cast
    rw [Finset.mul_sum]
    apply Finset.sum_le_sum
    intro i hi
    simpa [div_eq_mul_inv, one_div] using
      (Nat.cast_div_le (α := ℝ) (m := N) (n := A i))
  calc
    ((indexedMultiples A ∩ Set.Ioo 0 N).ncard : ℝ)
        ≤ ((Finset.filter
            (fun n => ∃ i, A i ≠ 0 ∧ A i ∣ n)
            (Finset.Ioo 0 N)).card : ℝ) := by
          exact_mod_cast (show
            (indexedMultiples A ∩ Set.Ioo 0 N).ncard ≤
              (Finset.filter
                (fun n => ∃ i, A i ≠ 0 ∧ A i ∣ n)
                (Finset.Ioo 0 N)).card from by
            have hsub : indexedMultiples A ∩ Set.Ioo 0 N ⊆
                ↑(Finset.filter
                  (fun n => ∃ i, A i ≠ 0 ∧ A i ∣ n)
                  (Finset.Ioo 0 N)) := by
              intro x hx
              rcases hx.1 with ⟨⟨k, i⟩, rfl⟩
              have hxpos := hx.2.1
              exact Finset.mem_filter.mpr ⟨Finset.mem_Ioo.mpr hx.2,
                ⟨i, by aesop, dvd_mul_left _ _⟩⟩
            have hc := Set.ncard_le_ncard hsub
            rw [Set.ncard_coe_finset] at hc
            exact hc)
    _ ≤ (∑ i ∈ exceptional, (N / A i : ℕ) : ℕ) := by exact_mod_cast hcount
    _ ≤ N * ∑ i ∈ exceptional, (1 / (A i : ℝ)) := hfiniteSum
    _ ≤ N * ∑' i, 1 / (A i : ℝ) := by
      apply mul_le_mul_of_nonneg_left _ (Nat.cast_nonneg N)
      exact h.sum_le_tsum exceptional (fun _ _ => by positivity)

/-- Semiperfectness is inherited by positive multiples. -/
theorem Erdos469.Semiperfect.of_dvd {m n : ℕ} (hm : Semiperfect m)
    (hmn : m ∣ n) (hn : 0 < n) : Semiperfect n := by
  obtain ⟨k, rfl⟩ := hmn
  have hk : 0 < k := by
    by_contra hk
    simp only [Nat.not_lt, Nat.le_zero] at hk
    subst k
    simp at hn
  obtain ⟨D, hD, hsum⟩ := Finset.mem_subsetSum_iff.mp hm.2
  refine ⟨hn, Finset.mem_subsetSum_iff.mpr
    ⟨D.image (fun d => k * d), ?_, ?_⟩⟩
  · intro x hx
    obtain ⟨d, hdD, rfl⟩ := Finset.mem_image.mp hx
    obtain ⟨hdvd, hdlt⟩ := Nat.mem_properDivisors.mp (hD hdD)
    apply Nat.mem_properDivisors.mpr
    constructor
    · simpa [Nat.mul_comm] using Nat.mul_dvd_mul_left k hdvd
    · simpa [Nat.mul_comm] using (Nat.mul_lt_mul_left hk).mpr hdlt
  · rw [Finset.sum_image]
    · rw [← Finset.mul_sum, hsum, Nat.mul_comm]
    · intro a ha b hb hab
      exact Nat.eq_of_mul_eq_mul_left hk hab

/-- Every semiperfect number has a primitive semiperfect divisor. -/
theorem Erdos469.Semiperfect.exists_primitive_divisor {n : ℕ}
    (hn : Semiperfect n) :
    ∃ a, PrimitiveSemiperfect a ∧ a ∣ n := by
  classical
  let candidates := n.divisors.filter Semiperfect
  have hcandidates : candidates.Nonempty := by
    refine ⟨n, Finset.mem_filter.mpr ⟨?_, hn⟩⟩
    exact Nat.mem_divisors.mpr ⟨Nat.dvd_refl n, hn.1.ne'⟩
  let a := candidates.min' hcandidates
  have haCandidates : a ∈ candidates := Finset.min'_mem _ _
  have haData := Finset.mem_filter.mp haCandidates
  refine ⟨a, ⟨haData.2, ?_⟩, Nat.dvd_of_mem_divisors haData.1⟩
  intro d hdProper hdSemi
  have hdn : d ∣ n :=
    (Nat.mem_properDivisors.mp hdProper).1.trans
      (Nat.dvd_of_mem_divisors haData.1)
  have hdCandidates : d ∈ candidates := by
    apply Finset.mem_filter.mpr
    exact ⟨Nat.mem_divisors.mpr ⟨hdn, hn.1.ne'⟩, hdSemi⟩
  have had : a ≤ d := Finset.min'_le candidates d hdCandidates
  exact (Nat.not_lt_of_ge had) (Nat.mem_properDivisors.mp hdProper).2

/-- Semiperfect numbers are exactly the positive multiples of primitive
semiperfect numbers. -/
theorem semiperfect_iff_exists_primitive_divisor (n : ℕ) :
    Semiperfect n ↔
      0 < n ∧ ∃ a, PrimitiveSemiperfect a ∧ a ∣ n := by
  constructor
  · intro hn
    obtain ⟨a, ha, han⟩ :=
      Erdos469.Semiperfect.exists_primitive_divisor hn
    exact ⟨hn.1, a, ha, han⟩
  · rintro ⟨hn, a, ha, han⟩
    exact Erdos469.Semiperfect.of_dvd ha.1 han hn

/-- The set whose density is studied below. -/
def semiperfectNumbers : Set ℕ := {n | Semiperfect n}

/-- The subtype of primitive semiperfect numbers. -/
abbrev PrimitiveIndex := {a : ℕ // PrimitiveSemiperfect a}

/-- The natural-number value of a primitive semiperfect index. -/
def primitiveValue (a : PrimitiveIndex) : ℕ := a.1

theorem primitiveValue_pos (a : PrimitiveIndex) : 0 < primitiveValue a := a.2.1.1

/-- Set-theoretic form of the primitive-divisor characterization. -/
theorem semiperfectNumbers_eq_indexedMultiples :
    semiperfectNumbers =
      indexedMultiples primitiveValue ∩ Set.Ioi 0 := by
  ext n
  rw [Set.mem_inter_iff]
  simp only [semiperfectNumbers, Set.mem_setOf_eq, Set.mem_Ioi,
    semiperfect_iff_exists_primitive_divisor, indexedMultiples,
    Set.mem_range]
  constructor
  · rintro ⟨hn, a, ha, han⟩
    obtain ⟨k, rfl⟩ := han
    exact ⟨⟨⟨k, ⟨a, ha⟩⟩, by simp [primitiveValue, Nat.mul_comm]⟩, hn⟩
  · rintro ⟨⟨⟨k, a⟩, hka⟩, hn⟩
    refine ⟨hn, a.1, a.2, ?_⟩
    rw [← hka]
    exact dvd_mul_left _ _

/-- Reciprocal summability of primitive semiperfect numbers, in the notation
of this file. This is the deep input from `Erdos469.erdos469`. -/
theorem primitiveReciprocal_summable :
    Summable fun a : PrimitiveIndex => 1 / (primitiveValue a : ℝ) := by
  simpa [primitiveValue, one_div] using Erdos469.erdos469

/-- The finite approximation generated by a finite family of primitive
semiperfect numbers. -/
def finitePrimitiveMultiples (F : Finset PrimitiveIndex) : Set ℕ :=
  finiteMultiples (F.image primitiveValue)

/-- The primitive indices outside a finite approximation. -/
abbrev PrimitiveTail (F : Finset PrimitiveIndex) :=
  {a : PrimitiveIndex // a ∉ F}

theorem finitePrimitiveMultiples_hasDensity (F : Finset PrimitiveIndex) :
    ∃ d : ℝ, (finitePrimitiveMultiples F).HasDensity d := by
  apply finiteMultiples_hasDensity
  intro a ha
  obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp ha
  exact primitiveValue_pos b

theorem finitePrimitiveMultiples_subset (F : Finset PrimitiveIndex) :
    finitePrimitiveMultiples F ⊆ semiperfectNumbers := by
  intro n hn
  obtain ⟨hnpos, a, ha, han⟩ := hn
  obtain ⟨b, hb, hba⟩ := Finset.mem_image.mp ha
  rw [← hba] at han
  rw [semiperfectNumbers, Set.mem_setOf_eq]
  exact Erdos469.Semiperfect.of_dvd b.2.1 han hnpos

/-- Anything missed by a finite primitive approximation is a positive
multiple of one of the remaining primitive indices. -/
theorem semiperfectNumbers_sdiff_finite_subset_tail
    (F : Finset PrimitiveIndex) :
    semiperfectNumbers \ finitePrimitiveMultiples F ⊆
      indexedMultiples (fun a : PrimitiveTail F => primitiveValue a.1) ∩
        Set.Ioi 0 := by
  intro n hn
  have hnSemi : Semiperfect n := hn.1
  obtain ⟨hnpos, a, ha, han⟩ :=
    (semiperfect_iff_exists_primitive_divisor n).mp hnSemi
  let ai : PrimitiveIndex := ⟨a, ha⟩
  have hai : ai ∉ F := by
    intro haiF
    apply hn.2
    exact ⟨hnpos, a, Finset.mem_image.mpr ⟨ai, haiF, rfl⟩, han⟩
  obtain ⟨k, hka⟩ := han
  constructor
  · refine ⟨⟨k, ⟨ai, hai⟩⟩, ?_⟩
    simpa [primitiveValue, ai, Nat.mul_comm] using hka.symm
  · exact hnpos

/-- The partial-density sequence used by `Set.HasDensity`. -/
def densitySequence (S : Set ℕ) (n : ℕ) : ℝ :=
  S.partialDensity Set.univ n

theorem densitySequence_mono_of_subset {S T : Set ℕ} (hST : S ⊆ T) (n : ℕ) :
    densitySequence S n ≤ densitySequence T n := by
  simp only [densitySequence, Set.partialDensity, Set.inter_univ,
    Set.univ_inter]
  apply div_le_div_of_nonneg_right _ (Nat.cast_nonneg _)
  exact_mod_cast Set.ncard_le_ncard
    (Set.inter_subset_inter_left (Set.Iio n) hST)

/-- Uniform tail control of the full density by a finite primitive
approximation. -/
theorem densitySequence_le_finite_add_tail
    (F : Finset PrimitiveIndex) (n : ℕ) :
    densitySequence semiperfectNumbers n ≤
      densitySequence (finitePrimitiveMultiples F) n +
        ∑' a : PrimitiveTail F, 1 / (primitiveValue a.1 : ℝ) := by
  rcases n.eq_zero_or_pos with rfl | hn
  · simp only [densitySequence, Set.partialDensity]
    rw [show Set.Iio (0 : ℕ) = ∅ by ext x; simp]
    simp only [Set.inter_empty, Set.ncard_empty, Nat.cast_zero, zero_div,
      zero_add]
    exact tsum_nonneg fun _ => by positivity
  let tailSet :=
    indexedMultiples (fun a : PrimitiveTail F => primitiveValue a.1)
  have hcover : semiperfectNumbers ∩ Set.Iio n ⊆
      (finitePrimitiveMultiples F ∩ Set.Iio n) ∪
        (tailSet ∩ Set.Ioo 0 n) := by
    intro x hx
    by_cases hxF : x ∈ finitePrimitiveMultiples F
    · exact Or.inl ⟨hxF, hx.2⟩
    · right
      have htail := semiperfectNumbers_sdiff_finite_subset_tail F ⟨hx.1, hxF⟩
      exact ⟨htail.1, htail.2, hx.2⟩
  have hcard : (semiperfectNumbers ∩ Set.Iio n).ncard ≤
      (finitePrimitiveMultiples F ∩ Set.Iio n).ncard +
        (tailSet ∩ Set.Ioo 0 n).ncard :=
    (Set.ncard_le_ncard hcover).trans (Set.ncard_union_le _ _)
  have htailSummable : Summable fun a : PrimitiveTail F =>
      1 / (primitiveValue a.1 : ℝ) := by
    simpa [Function.comp_def] using
      primitiveReciprocal_summable.subtype (fun a => a ∉ F)
  have htailCard := card_indexedMultiples_inter_Ioo_le
    (fun a : PrimitiveTail F => primitiveValue a.1) htailSummable n
  change ((tailSet ∩ Set.Ioo 0 n).ncard : ℝ) ≤
    n * ∑' a : PrimitiveTail F, 1 / (primitiveValue a.1 : ℝ) at htailCard
  have hreal : ((semiperfectNumbers ∩ Set.Iio n).ncard : ℝ) ≤
      ((finitePrimitiveMultiples F ∩ Set.Iio n).ncard : ℝ) +
        n * ∑' a : PrimitiveTail F, 1 / (primitiveValue a.1 : ℝ) := by
    calc
      ((semiperfectNumbers ∩ Set.Iio n).ncard : ℝ)
          ≤ ((finitePrimitiveMultiples F ∩ Set.Iio n).ncard : ℝ) +
              ((tailSet ∩ Set.Ioo 0 n).ncard : ℝ) := by exact_mod_cast hcard
      _ ≤ ((finitePrimitiveMultiples F ∩ Set.Iio n).ncard : ℝ) +
            n * ∑' a : PrimitiveTail F,
              1 / (primitiveValue a.1 : ℝ) := by
        simpa [add_comm] using add_le_add_right htailCard
          ((finitePrimitiveMultiples F ∩ Set.Iio n).ncard : ℝ)
  simp only [densitySequence, Set.partialDensity, Set.inter_univ,
    Set.univ_inter]
  have hIio : (Set.Iio n).ncard = n := by simp
  rw [hIio]
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  apply (div_le_iff₀ hnR).2
  rw [add_mul, div_mul_cancel₀ _ hnR.ne']
  simpa [mul_comm] using hreal

theorem densitySequence_dist_finite_le_tail
    (F : Finset PrimitiveIndex) (n : ℕ) :
    dist (densitySequence semiperfectNumbers n)
        (densitySequence (finitePrimitiveMultiples F) n) ≤
      ∑' a : PrimitiveTail F, 1 / (primitiveValue a.1 : ℝ) := by
  have hlower := densitySequence_mono_of_subset
    (finitePrimitiveMultiples_subset F) n
  have hupper := densitySequence_le_finite_add_tail F n
  rw [Real.dist_eq, abs_of_nonneg (sub_nonneg.mpr hlower)]
  linarith

/-- The natural density of semiperfect numbers exists. -/
theorem semiperfectNumbers_hasDensity :
    ∃ d : ℝ, semiperfectNumbers.HasDensity d := by
  let u := densitySequence semiperfectNumbers
  have huCauchy : CauchySeq u := by
    apply Metric.cauchySeq_iff'.mpr
    intro ε hε
    have htailTendsto := tendsto_tsum_compl_atTop_zero
      (fun a : PrimitiveIndex => 1 / (primitiveValue a : ℝ))
    obtain ⟨F, hFtail⟩ :=
      ((tendsto_order.1 htailTendsto).2 (ε / 3) (by positivity)).exists
    obtain ⟨dF, hFdensity⟩ := finitePrimitiveMultiples_hasDensity F
    have hFseq : Tendsto (densitySequence (finitePrimitiveMultiples F))
        atTop (𝓝 dF) := by
      rw [Set.HasDensity] at hFdensity
      exact hFdensity
    obtain ⟨N, hN⟩ := (Metric.cauchySeq_iff'.mp hFseq.cauchySeq)
      (ε / 3) (by positivity)
    refine ⟨N, fun n hn => ?_⟩
    have hnTail := densitySequence_dist_finite_le_tail F n
    have hNTail := densitySequence_dist_finite_le_tail F N
    have hNTail' :
        dist (densitySequence (finitePrimitiveMultiples F) N)
            (densitySequence semiperfectNumbers N) ≤
          ∑' a : PrimitiveTail F, 1 / (primitiveValue a.1 : ℝ) := by
      simpa [dist_comm] using hNTail
    have hmiddle := hN n hn
    calc
      dist (u n) (u N) ≤
          dist (u n) (densitySequence (finitePrimitiveMultiples F) n) +
            dist (densitySequence (finitePrimitiveMultiples F) n) (u N) :=
        dist_triangle _ _ _
      _ ≤ dist (u n) (densitySequence (finitePrimitiveMultiples F) n) +
          (dist (densitySequence (finitePrimitiveMultiples F) n)
              (densitySequence (finitePrimitiveMultiples F) N) +
            dist (densitySequence (finitePrimitiveMultiples F) N) (u N)) := by
        gcongr
        exact dist_triangle _ _ _
      _ < ε := by
        dsimp [u]
        nlinarith
  obtain ⟨d, hd⟩ := cauchySeq_tendsto_of_complete huCauchy
  refine ⟨d, ?_⟩
  rw [Set.HasDensity]
  exact hd

/-- Density is monotone under set inclusion whenever both densities exist. -/
theorem hasDensity_mono {S T : Set ℕ} {dS dT : ℝ} (hST : S ⊆ T)
    (hS : S.HasDensity dS) (hT : T.HasDensity dT) : dS ≤ dT := by
  rw [Set.HasDensity] at hS hT
  apply le_of_tendsto_of_tendsto hS hT
  exact Filter.Eventually.of_forall fun n =>
    densitySequence_mono_of_subset hST n

theorem semiperfect_six : Semiperfect 6 := by
  norm_num [Semiperfect, Finset.mem_subsetSum_iff]
  exact ⟨{1, 2, 3}, by norm_num [Finset.subset_iff], by norm_num⟩

theorem positiveMultiples_six_subset :
    positiveMultiples 6 ⊆ semiperfectNumbers := by
  intro n hn
  exact Erdos469.Semiperfect.of_dvd semiperfect_six hn.2 hn.1

/-- Any natural density of the semiperfect numbers is at least `1 / 6`. -/
theorem semiperfect_density_lower {d : ℝ}
    (hd : semiperfectNumbers.HasDensity d) :
    (1 : ℝ) / 6 ≤ d := by
  exact hasDensity_mono positiveMultiples_six_subset
    (positiveMultiples_hasDensity (by norm_num : 0 < 6)) hd

/-- The divisor-sum ratio is the sum of the reciprocals of the divisors. -/
theorem sigma_div_eq_sum_divisors_inv {n : ℕ} (hn : 0 < n) :
    (sigma n : ℝ) / n = ∑ d ∈ n.divisors, 1 / (d : ℝ) := by
  calc
    (sigma n : ℝ) / n = ∑ d ∈ n.divisors, (d : ℝ) / n := by
      rw [sigma_eq_sum_divisors]
      push_cast
      rw [Finset.sum_div]
    _ = ∑ d ∈ n.divisors, 1 / ((n / d : ℕ) : ℝ) := by
      apply Finset.sum_congr rfl
      intro d hd
      have hdvd := Nat.dvd_of_mem_divisors hd
      have hdpos := Nat.pos_of_dvd_of_pos hdvd hn
      have hquotpos : 0 < n / d := Nat.div_pos (Nat.le_of_dvd hn hdvd) hdpos
      have hnR : (n : ℝ) ≠ 0 := by exact_mod_cast hn.ne'
      have hquotR : ((n / d : ℕ) : ℝ) ≠ 0 := by
        exact_mod_cast hquotpos.ne'
      field_simp [hnR, hquotR]
      exact_mod_cast Nat.mul_div_cancel' hdvd
    _ = ∑ d ∈ n.divisors, 1 / (d : ℝ) := by
      simpa using Nat.sum_div_divisors n (fun d : ℕ => 1 / (d : ℝ))

/-- The reciprocal contribution of the nontrivial divisors of `n`. -/
def reciprocalDivisorWeight (n : ℕ) : ℝ :=
  ∑ d ∈ n.divisors.erase 1, 1 / (d : ℝ)

theorem reciprocalDivisorWeight_nonneg (n : ℕ) :
    0 ≤ reciprocalDivisorWeight n := by
  apply Finset.sum_nonneg
  intro d hd
  positivity

/-- Semiperfectness forces at least one unit of nontrivial reciprocal-divisor
weight. -/
theorem one_le_reciprocalDivisorWeight {n : ℕ} (hn : Semiperfect n) :
    1 ≤ reciprocalDivisorWeight n := by
  have hratio : (2 : ℝ) ≤ (sigma n : ℝ) / n := by
    apply (le_div_iff₀ (by exact_mod_cast hn.1 : (0 : ℝ) < n)).2
    exact_mod_cast hn.nondeficient.2
  rw [sigma_div_eq_sum_divisors_inv hn.1] at hratio
  have hone : 1 ∈ n.divisors := Nat.one_mem_divisors.mpr hn.1.ne'
  have hsplit : reciprocalDivisorWeight n + 1 =
      ∑ d ∈ n.divisors, 1 / (d : ℝ) := by
    simpa [reciprocalDivisorWeight] using
      Finset.sum_erase_add n.divisors (fun d : ℕ => 1 / (d : ℝ)) hone
  linarith

/-- The reciprocal-divisor weight with all possible divisors restricted to
the interval relevant below `N`. -/
def boundedDivisorWeight (N n : ℕ) : ℝ :=
  ∑ d ∈ (Finset.Ico 2 N).filter (fun d => d ∣ n), 1 / (d : ℝ)

theorem reciprocalDivisorWeight_le_bounded {N n : ℕ} (hn : n < N) :
    reciprocalDivisorWeight n ≤ boundedDivisorWeight N n := by
  unfold reciprocalDivisorWeight boundedDivisorWeight
  apply Finset.sum_le_sum_of_subset_of_nonneg
  · intro d hd
    obtain ⟨hdne, hdDiv⟩ := Finset.mem_erase.mp hd
    have hdvd := Nat.dvd_of_mem_divisors hdDiv
    have hdpos := Nat.pos_of_mem_divisors hdDiv
    have hdle := Nat.divisor_le hdDiv
    apply Finset.mem_filter.mpr
    exact ⟨Finset.mem_Ico.mpr ⟨by omega, hdle.trans_lt hn⟩, hdvd⟩
  · intro d hdTarget hdSource
    positivity

theorem card_semiperfect_Ioo_le_weight_sum (N : ℕ) :
    ((semiperfectNumbers ∩ Set.Iio N).ncard : ℝ) ≤
      ∑ n ∈ Finset.Ioo 0 N, boundedDivisorWeight N n := by
  classical
  have hset : semiperfectNumbers ∩ Set.Iio N =
      ↑(Finset.filter Semiperfect (Finset.Ioo 0 N)) := by
    ext n
    simp only [semiperfectNumbers, Set.mem_inter_iff, Set.mem_setOf_eq,
      Set.mem_Iio, Finset.mem_coe, Finset.mem_filter, Finset.mem_Ioo]
    constructor
    · intro hn
      exact ⟨⟨hn.1.1, hn.2⟩, hn.1⟩
    · intro hn
      exact ⟨hn.2, hn.1.2⟩
  calc
    ((semiperfectNumbers ∩ Set.Iio N).ncard : ℝ) =
        ∑ n ∈ Finset.Ioo 0 N, if Semiperfect n then (1 : ℝ) else 0 := by
      rw [hset, Set.ncard_coe_finset]
      simp
    _ ≤ ∑ n ∈ Finset.Ioo 0 N, boundedDivisorWeight N n := by
      apply Finset.sum_le_sum
      intro n hn
      have hnN := (Finset.mem_Ioo.mp hn).2
      split_ifs with hnSemi
      · exact (one_le_reciprocalDivisorWeight hnSemi).trans
          (reciprocalDivisorWeight_le_bounded hnN)
      · exact reciprocalDivisorWeight_nonneg n |>.trans
          (reciprocalDivisorWeight_le_bounded hnN)

/-- Double counting the pairs `d ∣ n` bounds the average reciprocal-divisor
weight by a partial sum of the reciprocal-square series. -/
theorem sum_boundedDivisorWeight_le (N : ℕ) :
    ∑ n ∈ Finset.Ioo 0 N, boundedDivisorWeight N n ≤
      (N : ℝ) * ∑ d ∈ Finset.Ico 2 N, 1 / (d : ℝ) ^ 2 := by
  unfold boundedDivisorWeight
  simp_rw [Finset.sum_filter]
  calc
    (∑ n ∈ Finset.Ioo 0 N,
        ∑ d ∈ Finset.Ico 2 N, if d ∣ n then 1 / (d : ℝ) else 0) =
        ∑ d ∈ Finset.Ico 2 N,
          ∑ n ∈ Finset.Ioo 0 N, if d ∣ n then 1 / (d : ℝ) else 0 := by
      rw [Finset.sum_comm]
    _ ≤ ∑ d ∈ Finset.Ico 2 N, (N : ℝ) * (1 / (d : ℝ) ^ 2) := by
      apply Finset.sum_le_sum
      intro d hd
      have hdData := Finset.mem_Ico.mp hd
      have hdpos : 0 < d := by omega
      have hNpos : 0 < N := by omega
      have hinterval : Finset.Ioo 0 N = Finset.Ioc 0 (N - 1) := by
        ext n
        simp only [Finset.mem_Ioo, Finset.mem_Ioc]
        omega
      have hcard :
          ((Finset.Ioo 0 N).filter (fun n => d ∣ n)).card = (N - 1) / d := by
        rw [hinterval]
        exact Nat.Ioc_filter_dvd_card_eq_div (N - 1) d
      have hcardBound :
          (((Finset.Ioo 0 N).filter (fun n => d ∣ n)).card : ℝ) ≤
            (N : ℝ) / d := by
        rw [hcard]
        calc
          (((N - 1) / d : ℕ) : ℝ) ≤ ((N - 1 : ℕ) : ℝ) / d :=
            Nat.cast_div_le
          _ ≤ (N : ℝ) / d := by
            apply div_le_div_of_nonneg_right _ (by exact_mod_cast hdpos.le)
            exact_mod_cast Nat.sub_le N 1
      calc
        (∑ n ∈ Finset.Ioo 0 N, if d ∣ n then 1 / (d : ℝ) else 0) =
            (((Finset.Ioo 0 N).filter (fun n => d ∣ n)).card : ℝ) *
              (1 / (d : ℝ)) := by
          rw [← Finset.sum_filter]
          simp
        _ ≤ ((N : ℝ) / d) * (1 / (d : ℝ)) := by
          exact mul_le_mul_of_nonneg_right hcardBound (by positivity)
        _ = (N : ℝ) * (1 / (d : ℝ) ^ 2) := by
          field_simp
    _ = (N : ℝ) * ∑ d ∈ Finset.Ico 2 N, 1 / (d : ℝ) ^ 2 := by
      rw [Finset.mul_sum]

/-- The reciprocal-square contribution from integers at least two is at
most `π² / 6 - 1`. -/
theorem sum_Ico_reciprocal_sq_le (N : ℕ) :
    ∑ d ∈ Finset.Ico 2 N, 1 / (d : ℝ) ^ 2 ≤ Real.pi ^ 2 / 6 - 1 := by
  have hone : 1 ∉ Finset.Ico 2 N := by simp
  have hsum := hasSum_zeta_two.summable.sum_le_tsum
    (insert 1 (Finset.Ico 2 N)) (fun n hn => by positivity)
  rw [hasSum_zeta_two.tsum_eq, Finset.sum_insert hone] at hsum
  norm_num at hsum
  rw [le_sub_iff_add_le]
  simpa [one_div, add_comm] using hsum

/-- A uniform upper bound for every partial density. -/
theorem densitySequence_semiperfect_le (N : ℕ) :
    densitySequence semiperfectNumbers N ≤ Real.pi ^ 2 / 6 - 1 := by
  rcases N.eq_zero_or_pos with rfl | hN
  · have hzero := sum_Ico_reciprocal_sq_le 0
    simp only [densitySequence, Set.partialDensity]
    rw [show Set.Iio (0 : ℕ) = ∅ by ext x; simp]
    simpa using hzero
  · simp only [densitySequence, Set.partialDensity, Set.inter_univ,
      Set.univ_inter]
    have hIio : (Set.Iio N).ncard = N := by simp
    rw [hIio]
    have hNR : (0 : ℝ) < N := by exact_mod_cast hN
    apply (div_le_iff₀ hNR).2
    calc
      ((semiperfectNumbers ∩ Set.Iio N).ncard : ℝ) ≤
          ∑ n ∈ Finset.Ioo 0 N, boundedDivisorWeight N n :=
        card_semiperfect_Ioo_le_weight_sum N
      _ ≤ (N : ℝ) * ∑ d ∈ Finset.Ico 2 N, 1 / (d : ℝ) ^ 2 :=
        sum_boundedDivisorWeight_le N
      _ ≤ (N : ℝ) * (Real.pi ^ 2 / 6 - 1) := by
        exact mul_le_mul_of_nonneg_left (sum_Ico_reciprocal_sq_le N) hNR.le
      _ = (Real.pi ^ 2 / 6 - 1) * (N : ℝ) := by ring

/-- Any natural density of the semiperfect numbers is bounded strictly below
one. -/
theorem semiperfect_density_upper {d : ℝ}
    (hd : semiperfectNumbers.HasDensity d) :
    d ≤ Real.pi ^ 2 / 6 - 1 := by
  rw [Set.HasDensity] at hd
  exact le_of_tendsto hd (Filter.Eventually.of_forall
    densitySequence_semiperfect_le)

theorem pi_sq_div_six_sub_one_lt_one :
    Real.pi ^ 2 / 6 - 1 < 1 := by
  have hpiPos := Real.pi_pos
  have hpiBound := Real.pi_lt_d20
  nlinarith

/-- The semiperfect numbers have a natural density, quantitatively trapped
between `1 / 6` and `π² / 6 - 1`. -/
theorem semiperfect_density_exists_with_bounds :
    ∃ d : ℝ, semiperfectNumbers.HasDensity d ∧
      (1 : ℝ) / 6 ≤ d ∧ d ≤ Real.pi ^ 2 / 6 - 1 := by
  obtain ⟨d, hd⟩ := semiperfectNumbers_hasDensity
  exact ⟨d, hd, semiperfect_density_lower hd, semiperfect_density_upper hd⟩

/-- The density of the integers that are sums of distinct proper divisors
exists and lies strictly between zero and one. -/
theorem semiperfect_density_exists_between_zero_and_one :
    ∃ d : ℝ, semiperfectNumbers.HasDensity d ∧ 0 < d ∧ d < 1 := by
  obtain ⟨d, hd, hdLower, hdUpper⟩ :=
    semiperfect_density_exists_with_bounds
  refine ⟨d, hd, ?_, hdUpper.trans_lt pi_sq_div_six_sub_one_lt_one⟩
  linarith

end

end Erdos469b
