/- leanprover/lean4:v4.29.1  mathlib v4.29.1 -/
/-
Define a red/blue-colouring of $\mathbb{R}^2$ to be unit-distance-avoiding if no two blue points are distance $1$ apart. Solving Erdős Problem #214 (https://www.erdosproblems.com/214), Juhász proved that for any unit-distance-avoiding two-colouring, there must be four red points forming a unit square. More generally, she proved that for any configuration $K$ of four points and any unit-distance-avoiding two-colouring, there must be a red congruent copy of $K$.

R. Juhász, Ramsey type theorems in the plane. J. Combin. Theory Ser. A (1979), 152-160. 

In the reverse direction, in Theorem 2 of her paper she also gave an example of a configuration $K$ of $12$ points and a specific unit-distance-avoiding colouring of the plane such that any congruent copy of $K$ contains a blue point. 

The formalization of this Theorem 2 can be found below, and was written by Aristotle from Harmonic (aristotle-harmonic@harmonic.fun).

It is noteworthy that Csizmadia and Tóth improved upon the second result and showed that such an example already exists with $8$ points. Perhaps their paper can be formalized as well, although I have not attempted this myself.

G. Csizmadia and G. Tóth, Note on a Ramsey-type problem in geometry. J. Combin. Theory Ser. A (1994), 302-306.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A circle of radius r centered at O is t-alternating if any two points on it at distance t have different colors.
-/
abbrev Point : Type := EuclideanSpace ℝ (Fin 2)

inductive Color
| Red
| Blue

/-
Definition of the coloring used in Theorem 2. The lattice is generated by a regular 2-rhombus. Blue points are within distance 1/2 of lattice points, with specific boundary conditions.
-/
def lattice_color_basis_1 : Point := !₂[(2 : ℝ), 0]
def lattice_color_basis_2 : Point := !₂[(1 : ℝ), Real.sqrt 3]

def lattice_color_set : Set Point :=
  { p | ∃ m n : ℤ, p = m • lattice_color_basis_1 + n • lattice_color_basis_2 }

def is_blue_relative (P O : Point) : Prop :=
  let v := P - O
  dist P O < 0.5 ∨ (dist P O = 0.5 ∧ (v 1 < 0 ∨ (v 1 = 0 ∧ v 0 < 0)))

noncomputable def coloring_theorem_2 (P : Point) : Color :=
  if ∃ L ∈ lattice_color_set, is_blue_relative P L then Color.Blue else Color.Red

/-
The quadratic form m^2 + mn + n^2 is at least 1 for integers m, n not both zero.
-/
lemma int_quadratic_form_ge_1 (m n : ℤ) (h : m ≠ 0 ∨ n ≠ 0) : m^2 + m * n + n^2 ≥ 1 := by
  cases h <;> nlinarith [ sq_nonneg ( m + n ), mul_self_pos.2 ‹_› ]

/-
The minimum distance between two distinct points in the lattice is at least 2.
-/
lemma lattice_min_dist (L1 L2 : Point)
  (h1 : L1 ∈ lattice_color_set)
  (h2 : L2 ∈ lattice_color_set)
  (h_neq : L1 ≠ L2) :
  dist L1 L2 ≥ 2 := by
    -- Let's express the coordinates of L1 and L2 in terms of the lattice basis vectors.
    obtain ⟨m1, n1, hm1⟩ := h1
    obtain ⟨m2, n2, hm2⟩ := h2
    have h_dist : dist L1 L2 = 2 * Real.sqrt ((m1 - m2)^2 + (m1 - m2) * (n1 - n2) + (n1 - n2)^2) := by
      norm_num [ dist_eq_norm, EuclideanSpace.norm_eq, hm1, hm2, lattice_color_basis_1, lattice_color_basis_2 ] ; ring_nf; norm_num; ring_nf;
      rw [ show (m1 : ℝ) * n1 * 4 - m1 * m2 * 8 - m1 * n2 * 4 + m1 ^ 2 * 4 -
            n1 * m2 * 4 - n1 * n2 * 8 + n1 ^ 2 * 4 + m2 * n2 * 4 +
            m2 ^ 2 * 4 + n2 ^ 2 * 4 =
            (m1 * n1 - m1 * m2 * 2 - m1 * n2 + m1 ^ 2 - n1 * m2 -
              n1 * n2 * 2 + n1 ^ 2 + m2 * n2 + m2 ^ 2 + n2 ^ 2) * 4 by ring_nf,
        Real.sqrt_mul' ] <;> norm_num
    generalize_proofs at *; (
    -- Since $m1 \neq m2$ or $n1 \neq n2$, we have $(m1 - m2)^2 + (m1 - m2) * (n1 - n2) + (n1 - n2)^2 \geq 1$.
    have h_ineq : (m1 - m2 : ℝ)^2 + (m1 - m2) * (n1 - n2) + (n1 - n2)^2 ≥ 1 := by
      norm_cast
      generalize_proofs at *; (
      exact int_quadratic_form_ge_1 ( m1 - m2 ) ( n1 - n2 ) ( by contrapose! h_neq; simp_all +decide [ sub_eq_iff_eq_add ] ) |> fun h => by linarith;)
    generalize_proofs at *; (
    exact h_dist.symm ▸ le_mul_of_one_le_right ( by norm_num ) ( Real.le_sqrt_of_sq_le ( by linarith ) ) |> le_trans ( by norm_num ) ;))

/-
Two points in the same blue region cannot be at distance 1.
-/
lemma single_disc_no_dist_1 (P Q L : Point)
  (hP : is_blue_relative P L)
  (hQ : is_blue_relative Q L) :
  dist P Q ≠ 1 := by
    unfold is_blue_relative at *;
    norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at *;
    rcases hP with ( hP | hP ) <;> rcases hQ with ( hQ | hQ ) <;> norm_num [ Real.sqrt_lt' ] at *;
    · linarith [ sq_nonneg ( P 0 - Q 0 - 2 * ( P 0 - L 0 ) ), sq_nonneg ( P 0 - Q 0 + 2 * ( P 0 - L 0 ) ), sq_nonneg ( P 1 - Q 1 - 2 * ( P 1 - L 1 ) ), sq_nonneg ( P 1 - Q 1 + 2 * ( P 1 - L 1 ) ) ];
    · rw [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] at hQ <;> norm_num at *;
      cases hQ.2 <;> nlinarith [ sq_nonneg ( P 0 - L 0 - ( Q 0 - L 0 ) ), sq_nonneg ( P 0 - L 0 + ( Q 0 - L 0 ) ), sq_nonneg ( P 1 - L 1 - ( Q 1 - L 1 ) ), sq_nonneg ( P 1 - L 1 + ( Q 1 - L 1 ) ) ];
    · rw [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] at hP <;> norm_num at *;
      cases hP.2 <;> nlinarith [ sq_nonneg ( P 0 - L 0 - ( Q 0 - L 0 ) ), sq_nonneg ( P 0 - L 0 + ( Q 0 - L 0 ) ), sq_nonneg ( P 1 - L 1 - ( Q 1 - L 1 ) ), sq_nonneg ( P 1 - L 1 + ( Q 1 - L 1 ) ) ];
    · rw [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] at * <;> norm_num at *;
      cases hP.2 <;> cases hQ.2 <;> nlinarith [ sq_nonneg ( P 0 - Q 0 ), sq_nonneg ( P 1 - Q 1 ) ]

/-
Two points in different blue regions cannot be at distance 1.
-/
lemma two_discs_no_dist_1 (P Q L1 L2 : Point)
  (hL1 : L1 ∈ lattice_color_set)
  (hL2 : L2 ∈ lattice_color_set)
  (h_neq : L1 ≠ L2)
  (hP : is_blue_relative P L1)
  (hQ : is_blue_relative Q L2) :
  dist P Q ≠ 1 := by
    -- If dist P Q = 1, then by the triangle inequality, L1, P, Q, L2 must be collinear.
    set u : Point := (1 / dist L2 L1) • (L2 - L1);
    by_contra h_contra;
    have h_collinear : dist L1 L2 = 2 ∧ dist P L1 = 0.5 ∧ dist Q L2 = 0.5 := by
      have h_collinear : dist L1 L2 ≥ 2 ∧ dist P L1 ≤ 0.5 ∧ dist Q L2 ≤ 0.5 := by
        exact ⟨ lattice_min_dist L1 L2 hL1 hL2 h_neq, by cases hP <;> norm_num at * <;> linarith, by cases hQ <;> norm_num at * <;> linarith ⟩;
      have h_collinear : dist L1 L2 ≤ dist L1 P + dist P Q + dist Q L2 := by
        exact dist_triangle4 _ _ _ _;
      norm_num [ dist_comm ] at * ; exact ⟨ by linarith, by linarith, by linarith ⟩;
    -- Since $P = L1 + 0.5 * u$ and $Q = L2 - 0.5 * u$, we have $P = L1 + 0.5 * (L2 - L1) / 2$ and $Q = L2 - 0.5 * (L2 - L1) / 2$.
    have hP_eq : P = L1 + (0.5 : ℝ) • u := by
      have h_collinear : dist P L1 = 0.5 ∧ dist P L2 = 1.5 := by
        have h_collinear : dist P L2 ≤ dist P Q + dist Q L2 := by
          exact dist_triangle _ _ _;
        have h_collinear : dist P L2 ≥ dist L1 L2 - dist P L1 := by
          have h_collinear : dist L1 L2 ≤ dist L1 P + dist P L2 := by
            exact dist_triangle _ _ _;
          linarith [ dist_comm L1 P ];
        exact ⟨ by linarith, by norm_num at *; linarith ⟩;
      norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at *;
      norm_num [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] at *;
      ext i; fin_cases i <;> norm_num [ u ] <;> ring_nf at * <;> norm_num at *;
      · norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at *;
        rw [ show ( L2 0 - L1 0 ) ^ 2 + ( L2 1 - L1 1 ) ^ 2 = 4 by linarith ] ; norm_num ; ring_nf;
        grind;
      · norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at *;
        norm_num [ show ( L2 0 - L1 0 ) ^ 2 + ( L2 1 - L1 1 ) ^ 2 = 4 by linarith ] at *;
        grind
    have hQ_eq : Q = L2 - (0.5 : ℝ) • u := by
      have hQ_eq : ‖Q - L2 + (0.5 : ℝ) • u‖ = 0 := by
        have hQ_eq : ‖Q - L2 + (0.5 : ℝ) • u‖^2 = ‖Q - L2‖^2 + ‖(0.5 : ℝ) • u‖^2 + 2 * inner ℝ (Q - L2) ((0.5 : ℝ) • u) := by
          rw [ @norm_add_sq ℝ ] ; norm_num ; ring;
        have hQ_eq : inner ℝ (Q - L2) u = -0.5 := by
          have hQ_eq : inner ℝ (Q - L2) (L2 - L1) = -0.5 * dist L2 L1 := by
            have hQ_eq : ‖Q - L1‖^2 = ‖Q - L2‖^2 + ‖L2 - L1‖^2 + 2 * inner ℝ (Q - L2) (L2 - L1) := by
              rw [ show Q - L1 = ( Q - L2 ) + ( L2 - L1 ) by abel1, norm_add_sq_real ] ; ring;
            have hQ_eq : ‖Q - L1‖ = 1.5 := by
              have hQ_eq : ‖Q - L1‖ ≤ ‖Q - P‖ + ‖P - L1‖ := by
                simpa using norm_add_le ( Q - P ) ( P - L1 );
              have hQ_eq : ‖Q - L1‖ ≥ ‖L1 - L2‖ - ‖Q - L2‖ := by
                have := norm_sub_le ( Q - L1 ) ( Q - L2 ) ; simp_all +decide [ norm_sub_rev ] ;
              norm_num [ dist_eq_norm ] at *;
              linarith [ norm_sub_rev P Q ];
            norm_num [ dist_eq_norm' ] at *;
            norm_num [ norm_sub_rev ] at * ; nlinarith;
          convert congr_arg ( fun x : ℝ => x * ( 1 / dist L2 L1 ) ) hQ_eq using 1 <;> ring_nf;
          · rw [ inner_smul_right ] ; ring;
          · rw [ mul_inv_cancel₀ ( ne_of_gt ( dist_pos.mpr ( by tauto ) ) ), one_mul ];
        have hQ_eq : ‖Q - L2‖ = 0.5 ∧ ‖u‖ = 1 := by
          simp_all +decide [ dist_eq_norm' ];
          norm_num +zetaDelta at *;
          exact ⟨ by simpa only [ norm_sub_rev ] using h_collinear.2.2, by simpa [ norm_smul, h_collinear.1 ] using h_collinear.2.1 ⟩;
        norm_num [ norm_smul, hQ_eq ] at *;
        norm_num [ inner_smul_right ] at * ; aesop;
      norm_num +zetaDelta at *;
      exact eq_sub_of_add_eq <| by
        ext i
        have := congr_arg (fun x : Point => x i) hQ_eq
        norm_num at *
        linarith
    unfold is_blue_relative at *; norm_num [ hP_eq, hQ_eq ] at *;
    norm_num [ norm_smul, h_collinear ] at *;
    cases hP <;> cases hQ <;> linarith

/-
Under the coloring defined for Theorem 2, no two blue points are at distance 1 apart.
-/
lemma coloring_theorem_2_no_blue_dist_1 (P Q : Point)
  (h_dist : dist P Q = 1)
  (hP : coloring_theorem_2 P = Color.Blue)
  (hQ : coloring_theorem_2 Q = Color.Blue) :
  False := by
    -- By definition of coloring_theorem_2, there exist lattice points L_P and L_Q such that P is blue relative to L_P and Q is blue relative to L_Q.
    obtain ⟨L_P, hL_P⟩ : ∃ L_P ∈ lattice_color_set, is_blue_relative P L_P := by
      unfold coloring_theorem_2 at hP; aesop;
    obtain ⟨L_Q, hL_Q⟩ : ∃ L_Q ∈ lattice_color_set, is_blue_relative Q L_Q := by
      unfold coloring_theorem_2 at hQ; aesop;
    by_cases h_eq : L_P = L_Q;
    · exact single_disc_no_dist_1 P Q L_P hL_P.2 ( by aesop ) h_dist;
    · exact absurd ( two_discs_no_dist_1 P Q L_P L_Q hL_P.1 hL_Q.1 h_eq hL_P.2 hL_Q.2 ) ( by aesop )

/-
Definition of the configuration lattice and the set X. The lattice is generated by a regular sqrt(3)/2-rhombus. X is the set of lattice points within a specific radius of the center of a base triangle.
-/
def config_lattice_basis_1 : Point := !₂[Real.sqrt 3 / 2, 0]
def config_lattice_basis_2 : Point := !₂[Real.sqrt 3 / 4, 3 / 4]

def config_lattice : Set Point :=
  { p | ∃ m n : ℤ, p = m • config_lattice_basis_1 + n • config_lattice_basis_2 }

def config_center : Point := (1 / 3 : ℝ) • (config_lattice_basis_1 + config_lattice_basis_2)

def config_radius : ℝ := 2 * Real.sqrt 3 / 3 + 0.5

def config_X : Set Point :=
  { p ∈ config_lattice | dist p config_center < config_radius }

/-
The set X of lattice points within the specified radius is finite.
-/
lemma config_X_finite : config_X.Finite := by
  -- The set of lattice points within a bounded distance from a fixed point is finite.
  have h_bounded : ∃ M : ℝ, ∀ p ∈ config_lattice, dist p config_center < config_radius → ‖p‖ ≤ M := by
    use config_radius + ‖config_center‖ + 1;
    exact fun p hp hp' => by linarith [ norm_sub_norm_le p config_center, dist_eq_norm p config_center ] ;
  -- Since the lattice points are bounded, there are only finitely many pairs (m, n) such that m*v1 + n*v2 lies within the bounded region.
  obtain ⟨M, hM⟩ : ∃ M : ℝ, ∀ p ∈ config_lattice, dist p config_center < config_radius → ‖p‖ ≤ M := h_bounded;
  have h_finite_pairs : ∃ M' : ℝ, ∀ m n : ℤ, ‖m • config_lattice_basis_1 + n • config_lattice_basis_2‖ ≤ M → abs m ≤ M' ∧ abs n ≤ M' := by
    norm_num [ EuclideanSpace.norm_eq, config_lattice_basis_1, config_lattice_basis_2 ];
    refine' ⟨ M * 2 + 1, fun m n hmn => ⟨ _, _ ⟩ ⟩ <;> rw [ Real.sqrt_le_iff ] at hmn <;> ring_nf at * <;> norm_num at *;
    · exact abs_le.mpr ⟨ by nlinarith [ sq_nonneg ( m + n : ℝ ) ], by nlinarith [ sq_nonneg ( m + n : ℝ ) ] ⟩;
    · exact abs_le.mpr ⟨ by nlinarith [ sq_nonneg ( m + n : ℝ ) ], by nlinarith [ sq_nonneg ( m + n : ℝ ) ] ⟩;
  obtain ⟨ M', hM' ⟩ := h_finite_pairs; have h_finite_pairs : Set.Finite { p : Point | ∃ m n : ℤ, p = m • config_lattice_basis_1 + n • config_lattice_basis_2 ∧ ‖p‖ ≤ M } := by
    have h_finite_pairs : Set.Finite { p : ℤ × ℤ | abs p.1 ≤ M' ∧ abs p.2 ≤ M' } := by
      exact Set.Finite.subset ( Set.Finite.prod ( Set.finite_Icc ( -⌈M'⌉₊ : ℤ ) ⌈M'⌉₊ ) ( Set.finite_Icc ( -⌈M'⌉₊ : ℤ ) ⌈M'⌉₊ ) ) fun p hp => ⟨ ⟨ by exact neg_le_of_abs_le <| by exact_mod_cast hp.1.trans <| Nat.le_ceil _, by exact le_of_abs_le <| by exact_mod_cast hp.1.trans <| Nat.le_ceil _ ⟩, ⟨ by exact neg_le_of_abs_le <| by exact_mod_cast hp.2.trans <| Nat.le_ceil _, by exact le_of_abs_le <| by exact_mod_cast hp.2.trans <| Nat.le_ceil _ ⟩ ⟩;
    exact Set.Finite.subset ( h_finite_pairs.image fun p : ℤ × ℤ => p.1 • config_lattice_basis_1 + p.2 • config_lattice_basis_2 ) fun p hp => by obtain ⟨ m, n, rfl, hp ⟩ := hp; exact ⟨ ( m, n ), ⟨ hM' m n hp |>.1, hM' m n hp |>.2 ⟩, rfl ⟩ ;;
  exact h_finite_pairs.subset fun p hp => by obtain ⟨ m, n, rfl, hp' ⟩ := hp.1; exact ⟨ m, n, rfl, hM _ hp.1 hp.2 ⟩ ;

/-
The set X consists exactly of the 12 points listed.
-/
def config_points_list : List (ℤ × ℤ) :=
  [(0,0), (1,0), (0,1), (-1,0), (0,-1), (1,-1), (-1,1), (2,0), (0,2), (1,1), (2,-1), (-1,2)]

lemma config_X_eq_list : config_X = { p | ∃ c ∈ config_points_list, p = c.1 • config_lattice_basis_1 + c.2 • config_lattice_basis_2 } := by
  unfold config_X config_points_list
  generalize_proofs at *;
  apply Set.eq_of_subset_of_subset;
  · intro p hp;
    obtain ⟨ ⟨ m, n, rfl ⟩, hp ⟩ := hp;
    norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at hp;
    unfold config_center config_radius config_lattice_basis_1 config_lattice_basis_2 at hp;
    field_simp at hp;
    rw [ ← Real.sqrt_sq ( show 0 ≤ Real.sqrt 3 * 2 + 3 * 0.5 by positivity ) ] at hp ; rw [ Real.lt_sqrt ( by positivity ) ] at hp ; ring_nf at hp ; norm_num at hp;
    rw [ Real.sq_sqrt ] at hp <;> ring_nf at hp <;> norm_num at hp ⊢;
    · -- By simplifying, we can see that the inequality holds for the given values of m and n.
      have h_simplified : (m : ℝ)^2 + m * n + n^2 - m - n ≤ 3 := by
        by_contra h_contra;
        exact h_contra <| by nlinarith [ Real.sqrt_nonneg 3, Real.sq_sqrt <| show 0 ≤ 3 by norm_num, show ( m : ℝ ) ^ 2 + m * n + n ^ 2 - m - n ≥ 4 by exact_mod_cast Int.le_of_lt_add_one <| by { rw [ ← @Int.cast_lt ℝ ] ; push_cast; nlinarith [ Real.sqrt_nonneg 3, Real.sq_sqrt <| show 0 ≤ 3 by norm_num ] } ] ;
      have h_simplified : m ≤ 2 ∧ m ≥ -2 ∧ n ≤ 2 ∧ n ≥ -2 := by
        norm_cast at h_simplified;
        exact ⟨ by nlinarith only [ h_simplified, sq_nonneg ( m + n ) ], by nlinarith only [ h_simplified, sq_nonneg ( m + n ) ], by nlinarith only [ h_simplified, sq_nonneg ( m + n ) ], by nlinarith only [ h_simplified, sq_nonneg ( m + n ) ] ⟩;
      rcases h_simplified with ⟨ hm₁, hm₂, hn₁, hn₂ ⟩ ; interval_cases m <;> interval_cases n <;> norm_num at hp ⊢;
      all_goals norm_num at *;
    · field_simp;
      rcases m with ⟨ _ | _ | m ⟩ <;> rcases n with ⟨ _ | _ | n ⟩ <;> norm_num at * <;> ring_nf at * <;> nlinarith;
  · intro p hp
    obtain ⟨c, hc, rfl⟩ := hp
    generalize_proofs at *;
    refine' ⟨ ⟨ c.1, c.2, rfl ⟩, _ ⟩;
    unfold config_center config_radius config_lattice_basis_1 config_lattice_basis_2; norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] ; ring_nf ; norm_num;
    rw [ Real.sqrt_lt' ] <;> ring_nf <;> norm_num;
    · fin_cases hc <;> norm_num <;> nlinarith [ Real.sqrt_nonneg 3, Real.sq_sqrt ( show 0 ≤ 3 by norm_num ) ];
    · positivity

/-
The covering radius of the lattice is 2*sqrt(3)/3. That is, for any point P, there is a lattice point L within distance 2*sqrt(3)/3.
-/
lemma lattice_covering_radius (P : Point) :
  ∃ L ∈ lattice_color_set, dist P L ≤ 2 * Real.sqrt 3 / 3 := by
    -- By definition of lattice_color_set, there exists a point L in the lattice such that P - L is within the parallelogram generated by lattice_color_basis_1 and lattice_color_basis_2.
    obtain ⟨L, hL⟩ : ∃ L : ℤ × ℤ, dist P (L.1 • lattice_color_basis_1 + L.2 • lattice_color_basis_2) ≤ 2 * Real.sqrt 3 / 3 := by
      obtain ⟨m, n, hm⟩ : ∃ m n : ℝ, P = m • lattice_color_basis_1 + n • lattice_color_basis_2 := by
        unfold lattice_color_basis_1 lattice_color_basis_2;
        -- We can solve the system of linear equations given by $P = m • ![2, 0] + n • ![1, Real.sqrt 3]$ to find $m$ and $n$.
        have h_solve : ∃ m n : ℝ, m * 2 + n * 1 = P 0 ∧ m * 0 + n * Real.sqrt 3 = P 1 := by
          exact ⟨ ( P 0 - P 1 / Real.sqrt 3 ) / 2, P 1 / Real.sqrt 3, by ring, by ring_nf; norm_num ⟩;
        obtain ⟨ m, n, hm, hn ⟩ := h_solve; use m, n; ext i; fin_cases i <;> norm_num <;> linarith!;
      -- Let $m = k + a$ and $n = l + b$ where $k, l \in \mathbb{Z}$ and $0 \leq a, b < 1$.
      obtain ⟨k, l, a, b, hk, hl, ha, hb⟩ : ∃ k l : ℤ, ∃ a b : ℝ, 0 ≤ a ∧ a < 1 ∧ 0 ≤ b ∧ b < 1 ∧ m = k + a ∧ n = l + b := by
        exact ⟨ ⌊m⌋, ⌊n⌋, m - ⌊m⌋, n - ⌊n⌋, Int.fract_nonneg _, Int.fract_lt_one _, Int.fract_nonneg _, Int.fract_lt_one _, by ring, by ring ⟩;
      -- We need to show that the distance from $P$ to the nearest lattice point is at most $2\sqrt{3}/3$.
      have h_dist : dist (a • lattice_color_basis_1 + b • lattice_color_basis_2) 0 ≤ 2 * Real.sqrt 3 / 3 ∨ dist (a • lattice_color_basis_1 + b • lattice_color_basis_2) (lattice_color_basis_1) ≤ 2 * Real.sqrt 3 / 3 ∨ dist (a • lattice_color_basis_1 + b • lattice_color_basis_2) (lattice_color_basis_2) ≤ 2 * Real.sqrt 3 / 3 ∨ dist (a • lattice_color_basis_1 + b • lattice_color_basis_2) (lattice_color_basis_1 + lattice_color_basis_2) ≤ 2 * Real.sqrt 3 / 3 := by
        norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at *;
        unfold lattice_color_basis_1 lattice_color_basis_2; norm_num [ Real.sqrt_le_iff ] ; ring_nf ; norm_num;
        contrapose! hb;
        intro hb' hm' hn';
        nlinarith only [ hb, hk, hl, ha, hb', mul_nonneg ha hk, mul_nonneg ha ( sub_nonneg_of_le hl.le ), mul_nonneg ha ( sub_nonneg_of_le hb'.le ), mul_nonneg hk ( sub_nonneg_of_le hl.le ), mul_nonneg hk ( sub_nonneg_of_le hb'.le ), mul_nonneg ( sub_nonneg_of_le hl.le ) ( sub_nonneg_of_le hb'.le ) ];
      rcases h_dist with h|h|h|h <;> simp_all +decide [ dist_eq_norm ];
      · refine' ⟨ k, l, _ ⟩ ; convert h using 1 ; ring_nf!; norm_num [ EuclideanSpace.norm_eq ] ; ring_nf!;
      · use k + 1, l;
        convert h using 2 ; ext i ; fin_cases i <;> norm_num <;> ring;
      · use k, l + 1;
        convert h using 2 ; ext i ; fin_cases i <;> norm_num <;> ring;
      · use k + 1, l + 1;
        convert h using 2 ; ext i ; fin_cases i <;> norm_num <;> ring;
    exact ⟨ _, ⟨ L.1, L.2, rfl ⟩, hL ⟩

/-
Any disc of radius `config_radius` contains a full blue region (weak inequality version).
-/
lemma lemma_A_weak (C : Point) :
  ∃ L ∈ lattice_color_set, ∀ P, is_blue_relative P L → dist P C ≤ config_radius := by
    obtain ⟨L, hL_in, hL_dist⟩ := lattice_covering_radius C
    use L, hL_in
    intro P hP
    have h_dist_PL : dist P L ≤ 0.5 := by
      unfold is_blue_relative at hP
      cases hP
      · linarith
      · linarith
    have h_tri : dist P C ≤ dist P L + dist L C := dist_triangle P L C
    rw [dist_comm L C] at h_tri
    unfold config_radius
    linarith

/-
The distance from any configuration lattice point to the center is never equal to the configuration radius.
-/
lemma lemma_boundary_irrational (C : Point) (L : Point)
  (hL : L ∈ config_lattice)
  (hC : C = config_center) :
  dist L C ≠ config_radius := by
    obtain ⟨ m, n, hm ⟩ := hL;
    norm_num [ dist_eq_norm, EuclideanSpace.norm_eq, hm, hC, config_center ];
    rw [ Real.sqrt_eq_iff_mul_self_eq_of_pos ] <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2, config_radius ] <;> ring_nf <;> norm_num;
    · by_contra h_contra;
      exact Nat.Prime.irrational_sqrt ( by norm_num : Nat.Prime 3 ) ⟨ ( 1 / 4 + - ( 3 * m * ( 1 / 4 ) ) + 3 * m * n * ( 1 / 4 ) + 3 * m ^ 2 * ( 1 / 4 ) + - ( 3 * n * ( 1 / 8 ) ) + 3 * n ^ 2 * ( 1 / 16 ) + - ( n * ( 3 / 8 ) ) + n ^ 2 * ( 9 / 16 ) - 1 / 4 - 4 / 3 ) / ( 2 / 3 ), by push_cast [ ← h_contra ] ; ring ⟩;
    · positivity

/-
If three vectors sum to zero and are not all zero, they cannot all belong to the "red boundary" set (upper half plane plus non-negative x-axis).
-/
def is_red_boundary_vector (v : Point) : Prop :=
  v 1 > 0 ∨ (v 1 = 0 ∧ v 0 ≥ 0)

lemma equilateral_triangle_not_red_boundary (v1 v2 v3 : Point)
  (h_sum : v1 + v2 + v3 = 0)
  (h_nonzero : v1 ≠ 0) :
  ¬ (is_red_boundary_vector v1 ∧ is_red_boundary_vector v2 ∧ is_red_boundary_vector v3) := by
    intro h
    have hsum0 := congr_arg (fun x : Point => x 0) h_sum
    have hsum1 := congr_arg (fun x : Point => x 1) h_sum
    norm_num [ is_red_boundary_vector ] at h
    norm_num at hsum0 hsum1
    rcases h with ⟨h1, h2, h3⟩
    rcases h1 with h1 | h1 <;> rcases h2 with h2 | h2 <;> rcases h3 with h3 | h3
    all_goals try linarith
    exact h_nonzero <| by
      ext i
      fin_cases i
      · norm_num
        linarith [h1.2, h2.2, h3.2]
      · norm_num
        exact h1.1

/-
Definition of the Blue region relative to a lattice point L.
-/
def Blue (L : Point) : Set Point := { P | is_blue_relative P L }

/-
If three points map to an equilateral triangle on the boundary of the blue region of L, then at least one is blue.
-/
lemma lemma_triangle_blue_intersection (L : Point) (p1 p2 p3 : Point) (f : Point ≃ᵃⁱ[ℝ] Point)
  (h_center : p1 + p2 + p3 = 3 • (f.symm L))
  (h_dist : dist (f p1) L = 0.5 ∧ dist (f p2) L = 0.5 ∧ dist (f p3) L = 0.5)
  (_h_tri : dist (f p1) (f p2) = 0.5 * Real.sqrt 3 ∧ dist (f p2) (f p3) = 0.5 * Real.sqrt 3 ∧ dist (f p3) (f p1) = 0.5 * Real.sqrt 3) :
  f p1 ∈ Blue L ∨ f p2 ∈ Blue L ∨ f p3 ∈ Blue L := by
    -- By `equilateral_triangle_not_red_boundary`, not all $v_i$ are in the red boundary.
    have h_not_all_red_boundary : ¬ (is_red_boundary_vector (f p1 - L) ∧ is_red_boundary_vector (f p2 - L) ∧ is_red_boundary_vector (f p3 - L)) := by
      apply equilateral_triangle_not_red_boundary;
      · have h_sum : f (p1 + p2 + p3) = f p1 + f p2 + f p3 - 2 • f 0 := by
          have h_sum : ∀ (p q : Point), f (p + q) = f p + f q - f 0 := by
            intro p q; have := f.map_vadd 0 ( p + q ) ; have := f.map_vadd 0 p; have := f.map_vadd 0 q; simp_all +decide [ add_assoc ] ;
            abel1;
          rw [ h_sum, h_sum ] ; abel_nf;
        have h_sum : f (3 • f.symm L) = 3 • f (f.symm L) - 2 • f 0 := by
          have h_sum : ∀ (x y : Point), f (x + y) = f x + f y - f 0 := by
            intro x y; exact (by
            have := f.map_vadd 0 ( x + y ) ; have := f.map_vadd 0 x; have := f.map_vadd 0 y; simp_all +decide [add_left_comm,
              add_comm] ;);
          rw [ show 3 • f.symm L = f.symm L + f.symm L + f.symm L by ext i; norm_num; ring, h_sum, h_sum ] ; ext i ; norm_num ; ring;
        simp_all +decide [ ← eq_sub_iff_add_eq' ];
        grind;
      · intro h; norm_num [ sub_eq_zero.mp h ] at h_dist;
    norm_num [ Blue, is_blue_relative ] at *;
    contrapose! h_not_all_red_boundary; simp_all +decide [ is_red_boundary_vector ] ;
    grind

/-
The cardinality of the configuration X is 12.
-/
lemma lemma_config_X_card : config_X.ncard = 12 := by
  -- Since config_X is equal to the set generated by config_points_list, and that set has 12 elements, the cardinality of config_X is 12.
  have h_card_eq : config_X = Finset.image (fun p : ℤ × ℤ => p.1 • config_lattice_basis_1 + p.2 • config_lattice_basis_2) (Finset.image (fun p : ℤ × ℤ => p) (config_points_list.toFinset)) := by
    convert config_X_eq_list using 1 ; aesop;
  rw [ h_card_eq, Set.ncard_coe_finset, Finset.card_image_of_injective ] <;> norm_num [ Function.Injective ];
  · decide +revert;
  · intros a b c d h
    have h0 := congr_arg (fun x : Point => x 0) h
    have h1 := congr_arg (fun x : Point => x 1) h
    norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] at h0 h1
    aesop

/-
If a point in the fundamental triangle is at distance at least 0.5 from all vertices, it must be the centroid (1/3, 1/3).
-/
lemma lemma_fundamental_triangle_unique_max (u v : ℝ)
  (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
  let b1 := config_lattice_basis_1
  let b2 := config_lattice_basis_2
  let P := u • b1 + v • b2
  (dist P 0 ≥ 0.5 ∧ dist P b1 ≥ 0.5 ∧ dist P b2 ≥ 0.5) →
  (u = 1/3 ∧ v = 1/3) := by
    norm_num [ config_lattice_basis_1, config_lattice_basis_2, dist_eq_norm, EuclideanSpace.norm_eq ];
    intro h₁ h₂ h₃; rw [ Real.le_sqrt ] at * <;> try positivity;
    constructor <;> ring_nf at * <;> norm_num at * <;> nlinarith [ Real.sqrt_nonneg 3, Real.sq_sqrt ( show 0 ≤ 3 by norm_num ) ]

/-
For any point P, either there is a lattice point strictly within distance 0.5, or P is the circumcenter of an equilateral triangle of lattice points with side sqrt(3)/2 at distance 0.5.
-/
lemma lemma_lattice_cover_cases (P : Point) :
  (∃ L ∈ config_lattice, dist P L < 0.5) ∨
  (∃ L1 L2 L3 : Point, L1 ∈ config_lattice ∧ L2 ∈ config_lattice ∧ L3 ∈ config_lattice ∧
    dist P L1 = 0.5 ∧ dist P L2 = 0.5 ∧ dist P L3 = 0.5 ∧
    dist L1 L2 = Real.sqrt 3 / 2 ∧ dist L2 L3 = Real.sqrt 3 / 2 ∧ dist L3 L1 = Real.sqrt 3 / 2) := by
      apply Classical.byContradiction
      intro h_no_close_lattice;
      -- By definition of config_lattice, there exist integers m and n such that P = m • config_lattice_basis_1 + n • config_lattice_basis_2 + u • config_lattice_basis_1 + v • config_lattice_basis_2 for some u, v in [0, 1).
      obtain ⟨m, n, u, v, hu, hv, h_eq⟩ : ∃ m n : ℤ, ∃ u v : ℝ, 0 ≤ u ∧ u < 1 ∧ 0 ≤ v ∧ v < 1 ∧ P = m • config_lattice_basis_1 + n • config_lattice_basis_2 + u • config_lattice_basis_1 + v • config_lattice_basis_2 := by
        obtain ⟨m, n, u, v, hu, hv, h_eq⟩ : ∃ m n : ℤ, ∃ u v : ℝ, P = m • config_lattice_basis_1 + n • config_lattice_basis_2 + u • config_lattice_basis_1 + v • config_lattice_basis_2 := by
          -- By definition of config_lattice_basis_1 and config_lattice_basis_2, we can express any point P as a linear combination of these basis vectors.
          obtain ⟨u, v, hu⟩ : ∃ u v : ℝ, P = u • config_lattice_basis_1 + v • config_lattice_basis_2 := by
            -- We can solve the system of linear equations given by P = u • config_lattice_basis_1 + v • config_lattice_basis_2 to find u and v.
            have h_solve : ∀ (x y : ℝ), ∃ u v : ℝ, x = u * (Real.sqrt 3 / 2) + v * (Real.sqrt 3 / 4) ∧ y = v * (3 / 4) := by
              exact fun x y => ⟨ ( x - ( y * ( 4 / 3 ) ) * ( Real.sqrt 3 / 4 ) ) / ( Real.sqrt 3 / 2 ), y * ( 4 / 3 ), by rw [ div_mul_cancel₀ _ ( by positivity ) ] ; ring, by ring ⟩;
            obtain ⟨ u, v, hu, hv ⟩ := h_solve ( P 0 ) ( P 1 ) ; use u, v; ext i; fin_cases i <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] <;> linarith!;
          exact ⟨ 0, 0, u, v, by simpa using hu ⟩;
        refine' ⟨ m + ⌊u⌋, n + ⌊v⌋, u - ⌊u⌋, v - ⌊v⌋, _, _, _, _, _ ⟩ <;> norm_num;
        · exact Int.fract_lt_one u;
        · exact Int.fract_lt_one v;
        · rw [ Int.fract, Int.fract ] ; ext i ; norm_num ; ring_nf;
          rw [ Int.fract, Int.fract ] ; ring;
      -- Consider two cases: $u + v \leq 1$ and $u + v > 1$.
      by_cases h_case : u + v ≤ 1;
      · -- If $u + v \leq 1$, then by `lemma_fundamental_triangle_cover`, either $dist(P', V) < 0.5$ for some $V \in \{0, b_1, b_2\}$, or $dist(P', V) \geq 0.5$ for all $V \in \{0, b_1, b_2\}$.
        obtain h_dist | h_dist : (∃ V ∈ ({0, config_lattice_basis_1, config_lattice_basis_2} : Set Point), dist (u • config_lattice_basis_1 + v • config_lattice_basis_2) V < 0.5) ∨ (∀ V ∈ ({0, config_lattice_basis_1, config_lattice_basis_2} : Set Point), dist (u • config_lattice_basis_1 + v • config_lattice_basis_2) V ≥ 0.5) := by
          exact Classical.or_iff_not_imp_left.2 fun h => by push Not at h; exact h;
        · obtain ⟨ V, hV₁, hV₂ ⟩ := h_dist;
          refine' h_no_close_lattice <| Or.inl ⟨ m • config_lattice_basis_1 + n • config_lattice_basis_2 + V, _, _ ⟩ <;> simp_all +decide [ dist_eq_norm ];
          · rcases hV₁ with ( rfl | rfl | rfl ) <;> [ exact ⟨ m, n, by norm_num ⟩ ; exact ⟨ m + 1, n, by ext i ; fin_cases i <;> norm_num <;> ring ⟩ ; exact ⟨ m, n + 1, by ext i ; fin_cases i <;> norm_num <;> ring ⟩ ];
          · convert hV₂ using 2 ; abel_nf;
        · -- If $dist(P', V) \geq 0.5$ for all $V \in \{0, b_1, b_2\}$, then by `lemma_fundamental_triangle_unique_max`, $u = v = 1/3$.
          have h_u_v : u = 1 / 3 ∧ v = 1 / 3 := by
            apply lemma_fundamental_triangle_unique_max u v hu h_eq.left h_case;
            exact ⟨ h_dist 0 ( by norm_num ), h_dist config_lattice_basis_1 ( by norm_num ), h_dist config_lattice_basis_2 ( by norm_num ) ⟩;
          refine' h_no_close_lattice <| Or.inr ⟨ m • config_lattice_basis_1 + n • config_lattice_basis_2, m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_1, m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_2, _, _, _, _, _ ⟩ <;> norm_num [ h_u_v, h_eq ];
          · exact ⟨ m, n, rfl ⟩;
          · exact ⟨ m + 1, n, by ext i; fin_cases i <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] ; ring ⟩;
          · exact ⟨ m, n + 1, by ext i; fin_cases i <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] <;> ring ⟩;
          · norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ];
            unfold config_lattice_basis_1 config_lattice_basis_2; norm_num; ring_nf; norm_num;
          · norm_num [ dist_eq_norm, EuclideanSpace.norm_eq, config_lattice_basis_1, config_lattice_basis_2 ];
            ring_nf; norm_num;
            ring;
      · -- Let $u' = 1 - u$ and $v' = 1 - v$. Then $u' + v' < 1$.
        set u' := 1 - u
        set v' := 1 - v
        have h_case2 : u' + v' < 1 := by
          exact show ( 1 - u ) + ( 1 - v ) < 1 from by linarith;
        -- By `lemma_fundamental_triangle_cover`, either there is a vertex within distance 0.5, or the point is the centroid.
        by_cases h_case2_cover : dist (u' • config_lattice_basis_1 + v' • config_lattice_basis_2) 0 < 0.5 ∨ dist (u' • config_lattice_basis_1 + v' • config_lattice_basis_2) config_lattice_basis_1 < 0.5 ∨ dist (u' • config_lattice_basis_1 + v' • config_lattice_basis_2) config_lattice_basis_2 < 0.5;
        · rcases h_case2_cover with h|h|h <;> simp_all +decide [ dist_eq_norm ];
          · have := h_no_close_lattice.1 ( m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_1 + config_lattice_basis_2 ) ?_ <;> norm_num at *;
            · convert this.not_gt _ using 1;
              convert h using 1 ; ring_nf!;
              rw [ ← norm_neg ] ; congr ; ext i ; fin_cases i <;> norm_num <;> ring;
            · exact ⟨ m + 1, n + 1, by ext i; fin_cases i <;> norm_num <;> ring ⟩;
          · have := h_no_close_lattice.1 ( m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_2 ) ?_ <;> norm_num at *;
            · convert this.not_gt _ using 1;
              convert h using 1 ; norm_num [ EuclideanSpace.norm_eq ] ; ring_nf;
              exact congrArg Real.sqrt ( by ring );
            · exact ⟨ m, n + 1, by ext i; fin_cases i <;> norm_num <;> ring ⟩;
          · have := h_no_close_lattice.1 ( m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_1 ) ?_ <;> norm_num at *;
            · convert this.not_gt _ using 1;
              convert h using 1;
              rw [ ← norm_neg ] ; congr ; ext i ; fin_cases i <;> norm_num <;> ring;
            · exact ⟨ m + 1, n, by ext i; fin_cases i <;> norm_num <;> ring ⟩;
        · -- By `lemma_fundamental_triangle_unique_max`, if $u' + v' < 1$ and the point is not within distance 0.5 of any vertex, then $u' = v' = 1/3$.
          have h_case2_unique : u' = 1 / 3 ∧ v' = 1 / 3 := by
            apply lemma_fundamental_triangle_unique_max u' v' (by
            exact sub_nonneg_of_le hv.le) (by
            exact sub_nonneg_of_le h_eq.2.1.le) (by
            linarith);
            exact ⟨ le_of_not_gt fun h => h_case2_cover <| Or.inl h, le_of_not_gt fun h => h_case2_cover <| Or.inr <| Or.inl h, le_of_not_gt fun h => h_case2_cover <| Or.inr <| Or.inr h ⟩;
          norm_num [ show u = 2 / 3 by linear_combination -h_case2_unique.1, show v = 2 / 3 by linear_combination -h_case2_unique.2 ] at *;
          refine' h_no_close_lattice.2 ( m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_1 ) _ ( m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_2 ) _ ( m • config_lattice_basis_1 + n • config_lattice_basis_2 + config_lattice_basis_1 + config_lattice_basis_2 ) _ _ _ _ _ _ _ <;> norm_num [ h_eq, dist_eq_norm ];
          any_goals rw [ EuclideanSpace.norm_eq ] ; norm_num [ config_lattice_basis_1, config_lattice_basis_2 ];
          any_goals rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> ring_nf <;> norm_num;
          · exact ⟨ m + 1, n, by ext i; fin_cases i <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] ; ring ⟩;
          · exact ⟨ m, n + 1, by ext i; fin_cases i <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] <;> ring ⟩;
          · exact ⟨ m + 1, n + 1, by ext i; fin_cases i <;> norm_num [ config_lattice_basis_1, config_lattice_basis_2 ] <;> ring ⟩

/-
For an equilateral triangle with side sqrt(3)/2 and circumradius 0.5, the circumcenter is the centroid.
-/
lemma lemma_equilateral_circumcenter_is_centroid (A B C P : Point)
  (hPA : dist P A = 0.5)
  (hPB : dist P B = 0.5)
  (hPC : dist P C = 0.5)
  (hAB : dist A B = Real.sqrt 3 / 2)
  (hBC : dist B C = Real.sqrt 3 / 2)
  (hCA : dist C A = Real.sqrt 3 / 2) :
  A + B + C = 3 • P := by
    norm_num [ dist_eq_norm, EuclideanSpace.norm_eq ] at *;
    ext i;
    fin_cases i <;> norm_num [ Fin.sum_univ_two ] at *;
    · grind;
    · grind

/-
For any isometry f, the image of the configuration X contains a blue point.
-/
lemma lemma_config_intersects_blue (f : Point ≃ᵃⁱ[ℝ] Point) :
  ∃ P ∈ f '' config_X, coloring_theorem_2 P = Color.Blue := by
    by_contra! h_contra;
    -- By `lemma_A_weak`, there exists $L_{color} \in \text{lattice\_color\_set}$ such that the blue region of $L_{color}$ is contained in the disk $D(C', \text{config\_radius})$.
    obtain ⟨L_color, hL_color⟩ : ∃ L_color ∈ lattice_color_set, ∀ P, is_blue_relative P L_color → dist P (f config_center) ≤ config_radius := by
      exact lemma_A_weak (f config_center);
    -- By `lemma_lattice_cover_cases`, there are two cases for $Q = f^{-1}(L_{color})$.
    obtain ⟨Q, hQ⟩ : ∃ Q, f Q = L_color := by
      exact f.surjective L_color
    have hQ_cases : (∃ L ∈ config_lattice, dist Q L < 0.5) ∨ (∃ L1 L2 L3 : Point, L1 ∈ config_lattice ∧ L2 ∈ config_lattice ∧ L3 ∈ config_lattice ∧ dist Q L1 = 0.5 ∧ dist Q L2 = 0.5 ∧ dist Q L3 = 0.5 ∧ dist L1 L2 = Real.sqrt 3 / 2 ∧ dist L2 L3 = Real.sqrt 3 / 2 ∧ dist L3 L1 = Real.sqrt 3 / 2) := by
      exact lemma_lattice_cover_cases Q;
    obtain h | h := hQ_cases;
    · obtain ⟨ L, hL₁, hL₂ ⟩ := h;
      have hL₃ : dist (f L) L_color < 0.5 := by
        convert hL₂ using 1;
        rw [ ← hQ ];
        rw [ dist_comm, f.isometry.dist_eq ];
      have hL₄ : coloring_theorem_2 (f L) = Color.Blue := by
        exact if_pos ⟨ L_color, hL_color.1, Or.inl hL₃ ⟩;
      exact h_contra (f L) (by
      exact ⟨ L, ⟨ hL₁, by
        have hL₅ : dist (f L) (f config_center) ≤ config_radius := by
          apply hL_color.right;
          exact Or.inl hL₃;
        have hL₆ : dist (f L) (f config_center) = dist L config_center := by
          exact f.isometry.dist_eq _ _;
        refine' lt_of_le_of_ne ( hL₆ ▸ hL₅ ) _;
        apply lemma_boundary_irrational; assumption; rfl; ⟩, rfl ⟩) hL₄;
    · obtain ⟨L1, L2, L3, hL1, hL2, hL3, hQ1, hQ2, hQ3, hL1L2, hL2L3, hL3L1⟩ := h
      have h_fL1 : dist L_color (f L1) = 0.5 ∧ dist L_color (f L2) = 0.5 ∧ dist L_color (f L3) = 0.5 := by
        aesop
      have h_fL1L2 : dist (f L1) (f L2) = Real.sqrt 3 / 2 ∧ dist (f L2) (f L3) = Real.sqrt 3 / 2 ∧ dist (f L3) (f L1) = Real.sqrt 3 / 2 := by
        exact ⟨ by simpa [ dist_comm ] using f.isometry.dist_eq L1 L2 |> fun x => x.trans hL1L2, by simpa [ dist_comm ] using f.isometry.dist_eq L2 L3 |> fun x => x.trans hL2L3, by simpa [ dist_comm ] using f.isometry.dist_eq L3 L1 |> fun x => x.trans hL3L1 ⟩;
      have h_fL1_blue : f L1 ∈ Blue L_color ∨ f L2 ∈ Blue L_color ∨ f L3 ∈ Blue L_color := by
        apply lemma_triangle_blue_intersection L_color L1 L2 L3 f;
        · have h_fL1L2 : L1 + L2 + L3 = 3 • Q := by
            apply_rules [ lemma_equilateral_circumcenter_is_centroid ];
          aesop;
        · exact ⟨ by rw [ dist_comm ] ; exact h_fL1.1, by rw [ dist_comm ] ; exact h_fL1.2.1, by rw [ dist_comm ] ; exact h_fL1.2.2 ⟩;
        · exact ⟨ by rw [ h_fL1L2.1 ] ; ring, by rw [ h_fL1L2.2.1 ] ; ring, by rw [ h_fL1L2.2.2 ] ; ring ⟩;
      obtain h | h | h := h_fL1_blue <;> simp_all +decide [ Blue ];
      · apply h_contra L1;
        · refine' ⟨ hL1, _ ⟩;
          have := hL_color.2 ( f L1 ) h; simp_all +decide [ dist_comm ] ;
          refine' lt_of_le_of_ne this _;
          apply_rules [ lemma_boundary_irrational ];
        · unfold coloring_theorem_2; aesop;
      · have h_fL2_in_X : dist (f L2) (f config_center) < config_radius := by
          refine' lt_of_le_of_ne ( hL_color.2 _ h ) _;
          have h_fL2_in_X : dist (f L2) (f config_center) ≠ config_radius := by
            have h_fL2_in_X : dist L2 config_center ≠ config_radius := by
              apply lemma_boundary_irrational; assumption; exact rfl;
            convert h_fL2_in_X using 1;
            exact f.isometry.dist_eq _ _;
          exact h_fL2_in_X;
        have h_fL2_in_X : L2 ∈ config_X := by
          exact ⟨ hL2, by simpa [ dist_comm ] using h_fL2_in_X ⟩;
        exact h_contra L2 h_fL2_in_X ( by unfold coloring_theorem_2; aesop );
      · have h_fL3_in_X : f L3 ∈ f '' config_X := by
          have h_fL3_in_X : dist (f L3) (f config_center) ≤ config_radius := by
            exact hL_color.2 _ h;
          have h_fL3_in_X : dist L3 config_center < config_radius := by
            exact lt_of_le_of_ne ( by simpa [ dist_comm ] using h_fL3_in_X ) fun h => by have := lemma_boundary_irrational config_center L3 hL3 rfl; aesop;
          exact ⟨ L3, ⟨ hL3, h_fL3_in_X ⟩, rfl ⟩;
        exact h_contra L3 ( by
          exact f.injective.mem_set_image.mp h_fL3_in_X |> fun h => by aesop; ) ( by
          exact if_pos ⟨ L_color, hL_color.1, h ⟩ )

/-
There exists a coloring of the plane without blue points at distance 1 and a configuration X consisting of 12 points such that any configuration which is congruent to X contains necessarily a blue point.
-/
theorem theorem_2 :
  ∃ (c : Point → Color) (X : Set Point),
    (∀ P Q, dist P Q = 1 → ¬ (c P = Color.Blue ∧ c Q = Color.Blue)) ∧
    X.Finite ∧ X.ncard = 12 ∧
    ∀ (X' : Set Point), (∃ f : Point ≃ᵃⁱ[ℝ] Point, f '' X = X') → ∃ P ∈ X', c P = Color.Blue := by
      use coloring_theorem_2, config_X;
      refine' ⟨ _, _, _, _ ⟩;
      · exact fun P Q h => fun h' => coloring_theorem_2_no_blue_dist_1 P Q h h'.1 h'.2;
      · exact config_X_finite;
      · exact lemma_config_X_card;
      · rintro X' ⟨ f, rfl ⟩ ; exact lemma_config_intersects_blue f;

#print axioms theorem_2
