/- leanprover/lean4:v4.29.1  mathlib v4.29.1 -/
/-
This is a Lean formalization of a solution to Erdős Problem 967.
https://www.erdosproblems.com/forum/thread/967

Informal authors:
- Fredy Yip

Formal authors:
- Aristotle
- Lawrence Wu

URLs:
- https://www.erdosproblems.com/forum/thread/967#post-2303
- https://gist.githubusercontent.com/llllvvuu/d25f037d1f1000bdabd6ca928c74c9bb/raw/50871c3840af1e49c4e5acabefac6604c9b65c65/967.lean
-/
/-
Note from poster (@llllvvuu):
Aristotle was run on the main.tex file from the "TeX Source" link
at https://arxiv.org/abs/2512.16528,
with no further context.
Aristotle generated the proof over two sessions, lasting 3 hours, then 30 minutes.
-/

/-
This file was generated by Aristotle.

This project request had uuid: def10f24-0ce5-480b-9502-6ed6361d246f
-/

/-
Formalization of the disproof of a question by Erdős and Ingham regarding the non-vanishing of a zeta-like series. We define the question, the main theorem asserting the existence of a sequence with prescribed sum, and the disproof.
-/

import Mathlib

set_option linter.style.longLine false
set_option linter.style.multiGoal false
set_option linter.style.refine false
set_option aesop.warn.nonterminal false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Pointwise

namespace Erdos967

/-
Bound for the difference of complex powers using the Mean Value Theorem.
-/
set_option linter.flexible false in
lemma mvt_estimate (t : ℝ) (x : ℝ) (hx : 0 < x) (n : ℝ) (hn : x ≤ n) :
  ‖(n : ℂ) ^ (-(1 + Complex.I * t)) - (x : ℂ) ^ (-(1 + Complex.I * t))‖ ≤ ‖1 + Complex.I * t‖ / x ^ 2 * (n - x) := by
    field_simp;
    -- Applying the fundamental theorem of calculus, we can express the difference as an integral.
    have h_ftc : Complex.ofReal n ^ (-(1 + Complex.I * t)) - Complex.ofReal x ^ (-(1 + Complex.I * t)) = -∫ u in (x)..n, (1 + Complex.I * t) * Complex.ofReal u ^ (-(2 + Complex.I * t)) := by
      rw [ intervalIntegral.integral_eq_sub_of_hasDerivAt ];
      rotate_right;
      use fun u => - ( u : ℂ ) ^ ( - ( 1 + Complex.I * t ) );
      · ring_nf;
      · intro u hu; convert HasDerivAt.neg ( HasDerivAt.comp u ( hasDerivAt_id' _ |> HasDerivAt.cpow_const <| _ ) <| HasDerivAt.ofReal_comp <| hasDerivAt_id' _ ) using 1 <;> aesop;
        · ring_nf;
        · linarith;
      · apply_rules [ ContinuousOn.intervalIntegrable ];
        exact continuousOn_of_forall_continuousAt fun u hu => ContinuousAt.mul continuousAt_const <| ContinuousAt.cpow ( Complex.continuous_ofReal.continuousAt ) continuousAt_const <| Or.inl <| by norm_cast; cases Set.mem_uIcc.mp hu <;> linarith;
    -- We can bound the integrand using the fact that $|u^{-2-it}| \leq x^{-2}$ for $u \in [x, n]$.
    have h_bound : ∀ u ∈ Set.Icc x n, ‖(1 + Complex.I * t) * Complex.ofReal u ^ (-(2 + Complex.I * t))‖ ≤ ‖1 + Complex.I * t‖ * x ^ (-2 : ℝ) := by
      aesop;
      rw [ Complex.norm_cpow_of_ne_zero ] <;> norm_num [ show u ≠ 0 by linarith ];
      norm_num [ Complex.arg ];
      field_simp;
      rw [ if_pos ( by linarith ) ] ; norm_num;
      rw [ div_le_iff₀ ] <;> nlinarith [ show 0 < ‖1 + Complex.I * t‖ by norm_num [ Complex.ext_iff ], show x ^ 2 ≤ u ^ 2 by nlinarith ];
    -- Using the bound on the integrand, we can bound the integral.
    have h_integral_bound : ‖∫ u in (x)..n, (1 + Complex.I * t) * Complex.ofReal u ^ (-(2 + Complex.I * t))‖ ≤ ‖1 + Complex.I * t‖ * x ^ (-2 : ℝ) * (n - x) := by
      refine' le_trans ( intervalIntegral.norm_integral_le_of_norm_le_const _ ) _;
      exacts [ ‖1 + Complex.I * t‖ * x ^ ( -2 : ℝ ), fun u hu => h_bound u <| by constructor <;> cases Set.mem_uIoc.mp hu <;> linarith, by rw [ abs_of_nonneg ( by linarith ) ] ];
    simp_all +decide [ Real.rpow_neg hx.le ];
    exact le_trans ( mul_le_mul_of_nonneg_right h_integral_bound ( sq_nonneg _ ) ) ( by nlinarith [ inv_mul_cancel_left₀ ( ne_of_gt ( sq_pos_of_pos hx ) ) ( ‖1 + Complex.I * t‖ * ( n - x ) ) ] )

/-
Existence of a real number x >= N such that x^{-it} is parallel to c.
-/
lemma exist_x_parallel (t : ℝ) (ht : t ≠ 0) (N : ℝ) (c : ℂ) (_hc : c ≠ 0) :
  ∃ x : ℝ, x ≥ N ∧ c = ‖c‖ * (x : ℂ) ^ (-(Complex.I * t)) := by
    -- Let's choose $k$ such that $x = \exp(-(θ + 2 * k * π) / t) \ge N$.
    obtain ⟨k, hk⟩ : ∃ k : ℤ, Real.exp (-(Complex.arg c + 2 * k * Real.pi) / t) ≥ N := by
      by_cases ht_neg : t < 0;
      · -- Since $t < 0$, we can choose $k$ such that $-(θ + 2 * k * π) / t \ge \ln N$.
        have h_k_neg : ∃ k : ℤ, -(Complex.arg c + 2 * k * Real.pi) / t ≥ Real.log N := by
          exact ⟨ ⌈ ( Real.log N * t + c.arg ) / ( -2 * Real.pi ) ⌉ + 1, by push_cast; rw [ ge_iff_le ] ; rw [ le_div_iff_of_neg ] <;> nlinarith [ Int.le_ceil ( ( Real.log N * t + c.arg ) / ( -2 * Real.pi ) ), Real.pi_pos, mul_div_cancel₀ ( Real.log N * t + c.arg ) ( by linarith [ Real.pi_pos ] : ( -2 * Real.pi ) ≠ 0 ) ] ⟩;
        exact ⟨ h_k_neg.choose, if hN : N ≤ 0 then by linarith [ Real.exp_pos ( - ( Complex.arg c + 2 * ( h_k_neg.choose : ℝ ) * Real.pi ) / t ) ] else by have := h_k_neg.choose_spec; rw [ ge_iff_le ] at *; rw [ Real.log_le_iff_le_exp ] at * <;> linarith ⟩;
      · -- Since $t > 0$, we can choose $k$ such that $-(Complex.arg c + 2 * k * Real.pi) / t \ge \log N$.
        obtain ⟨k, hk⟩ : ∃ k : ℤ, -(Complex.arg c + 2 * k * Real.pi) ≥ t * Real.log N := by
          exact ⟨ ⌊- ( t * Real.log N + Complex.arg c ) / ( 2 * Real.pi ) ⌋ - 1, by push_cast; nlinarith [ Int.floor_le ( - ( t * Real.log N + Complex.arg c ) / ( 2 * Real.pi ) ), Int.lt_floor_add_one ( - ( t * Real.log N + Complex.arg c ) / ( 2 * Real.pi ) ), Real.pi_pos, mul_div_cancel₀ ( - ( t * Real.log N + Complex.arg c ) ) ( by positivity : ( 2 * Real.pi ) ≠ 0 ) ] ⟩;
        by_cases hN : N > 0;
        · exact ⟨ k, by rw [ ge_iff_le ] ; rw [ ← Real.log_le_log_iff ( by positivity ) ( by positivity ), Real.log_exp ] ; rw [ le_div_iff₀ ( lt_of_le_of_ne ( le_of_not_gt ht_neg ) ht.symm ) ] ; linarith ⟩;
        · exact ⟨ k, le_trans ( le_of_not_gt hN ) ( Real.exp_nonneg _ ) ⟩;
    refine' ⟨ Real.exp ( - ( Complex.arg c + 2 * k * Real.pi ) / t ), hk, _ ⟩;
    rw [ Complex.cpow_def_of_ne_zero ] <;> norm_num [ ht ];
    rw [ Complex.log_exp ] <;> norm_num [ Complex.ext_iff, Complex.exp_re, Complex.exp_im, mul_assoc, ht, mul_left_comm ];
    · positivity;
    · positivity

/-
Main lemma: existence of a set S' approximating c.
-/
set_option linter.flexible false in
lemma lemma_2_1 (t : ℝ) (ht : t ≠ 0) (N : ℕ) (_hN : N > 0) (c : ℂ) :
  ∃ S' : Finset ℕ, (∀ n ∈ S', N ≤ n) ∧
  (∑ n ∈ S', (n : ℝ)⁻¹) ≤ ‖c‖ ∧
  ‖c - ∑ n ∈ S', (n : ℂ) ^ (-(1 + Complex.I * (t : ℂ)))‖ ≤ (1 + ‖1 + Complex.I * (t : ℂ)‖) * ‖c‖ ^ 2 := by
    by_cases hc : c = 0;
    · exact ⟨ ∅, by norm_num [ hc ] ⟩;
    · -- Assume $N \geq \max(|c|^{-2}, |c|^{-1})$. Use `exist_x_parallel` to find $x \geq N$ such that $c = ‖c‖ * (x : ℂ) ^ (-(Complex.I * t))$.
      obtain ⟨x, hx₁, hx₂⟩ : ∃ x : ℝ, x ≥ max (‖c‖⁻¹ ^ 2) (‖c‖⁻¹) ∧ x ≥ N ∧ c = ‖c‖ * (x : ℂ) ^ (-(Complex.I * t)) := by
        have hx' := exist_x_parallel t ht ( Max.max ( Max.max ( ‖c‖⁻¹ ^ 2 ) ‖c‖⁻¹ ) N ) c hc;
        exact ⟨ hx'.choose, le_trans ( le_max_left _ _ ) hx'.choose_spec.1, le_trans ( le_max_right _ _ ) hx'.choose_spec.1, hx'.choose_spec.2 ⟩;
      -- Let $s = \lfloor x \|c\| \rfloor$. Let $S' = \{n \in \mathbb{N} \mid \lceil x \rceil \leq n < \lceil x \rceil + s\}$.
      set s := Nat.floor (x * ‖c‖)
      set S' := Finset.Ico (Nat.ceil x) (Nat.ceil x + s);
      refine' ⟨ S', _, _, _ ⟩;
      · exact fun n hn => Nat.cast_le.mp ( le_trans ( show ( N : ℝ ) ≤ ⌈x⌉₊ by exact_mod_cast Nat.le_of_lt_succ <| by { rw [ ← @Nat.cast_lt ℝ ] ; push_cast; nlinarith [ Nat.le_ceil x, inv_pos.mpr ( norm_pos_iff.mpr hc ) ] } ) <| Nat.cast_le.mpr <| Finset.mem_Ico.mp hn |>.1 );
      · -- Since $n \geq x$ for all $n \in S'$, we have $\sum_{n \in S'} \frac{1}{n} \leq \sum_{n \in S'} \frac{1}{x} = \frac{s}{x}$.
        have h_sum_le_s_over_x : ∑ n ∈ S', (n : ℝ)⁻¹ ≤ s / x := by
          have h_sum_le_s_over_x : ∀ n ∈ S', (n : ℝ)⁻¹ ≤ 1 / x := by
            simp +zetaDelta at *;
            exact fun n hn₁ hn₂ => inv_anti₀ ( show 0 < x from lt_of_lt_of_le ( by positivity ) hx₁.2 ) hn₁;
          convert Finset.sum_le_sum h_sum_le_s_over_x ; norm_num ; ring_nf;
          norm_num [ mul_comm, S' ];
        exact h_sum_le_s_over_x.trans ( div_le_of_le_mul₀ ( by linarith [ inv_nonneg.2 ( sq_nonneg ‖c‖ ) ] ) ( by linarith [ norm_nonneg c ] ) ( by nlinarith [ Nat.floor_le ( show 0 ≤ x * ‖c‖ by nlinarith [ norm_nonneg c, inv_nonneg.2 ( sq_nonneg ‖c‖ ) ] ), norm_nonneg c ] ) );
      · -- Sum of errors \le s * |1+it|/x^2 * s = s^2/x^2 * |1+it| \le |c|^2 * |1+it|.
        have h_sum_errors : ‖∑ n ∈ S', ((n : ℂ) ^ (-(1 + Complex.I * t))) - ∑ n ∈ S', ((x : ℂ) ^ (-(1 + Complex.I * t)))‖ ≤ ‖1 + Complex.I * t‖ * ‖c‖ ^ 2 := by
          have h_sum_errors : ∀ n ∈ S', ‖((n : ℂ) ^ (-(1 + Complex.I * t))) - ((x : ℂ) ^ (-(1 + Complex.I * t)))‖ ≤ ‖1 + Complex.I * t‖ / x ^ 2 * (n - x) := by
            intros n hn;
            convert mvt_estimate t x ( show 0 < x from lt_of_lt_of_le ( by positivity ) hx₁ ) n ( show x ≤ n from le_trans ( Nat.le_ceil _ ) ( mod_cast Finset.mem_Ico.mp hn |>.1 ) ) using 1;
          have h_sum_errors : ‖∑ n ∈ S', ((n : ℂ) ^ (-(1 + Complex.I * t))) - ∑ n ∈ S', ((x : ℂ) ^ (-(1 + Complex.I * t)))‖ ≤ ‖1 + Complex.I * t‖ / x ^ 2 * ∑ n ∈ S', (n - x) := by
            simpa only [ ← Finset.sum_sub_distrib, Finset.mul_sum _ _ _ ] using le_trans ( norm_sum_le _ _ ) ( Finset.sum_le_sum h_sum_errors );
          -- Sum of errors \le s * |1+it|/x^2 * s = s^2/x^2 * |1+it| \le |c|^2 * |1+it|. Use the fact that $\sum_{n \in S'} (n - x) \leq s^2$.
          have h_sum_errors_le_s2 : ∑ n ∈ S', (n - x) ≤ s^2 := by
            have h_sum_errors_le_s2 : ∑ n ∈ Finset.range s, (Nat.ceil x + n - x) ≤ s^2 := by
              have h_sum_errors_le_s2 : ∑ n ∈ Finset.range s, (Nat.ceil x + n - x) ≤ ∑ n ∈ Finset.range s, (s : ℝ) := by
                gcongr ; norm_cast ; norm_num;
                linarith [ Nat.ceil_lt_add_one ( show 0 ≤ x by linarith [ show 0 ≤ x by exact le_trans ( by positivity ) hx₁ ] ), Nat.floor_le ( show 0 ≤ x * ‖c‖ by exact mul_nonneg ( by linarith [ show 0 ≤ x by exact le_trans ( by positivity ) hx₁ ] ) ( norm_nonneg c ) ), Nat.lt_floor_add_one ( x * ‖c‖ ), show ( ↑‹ℕ› : ℝ ) + 1 ≤ s from mod_cast Finset.mem_range.mp ‹_› ];
              simpa [ sq ] using h_sum_errors_le_s2;
            convert h_sum_errors_le_s2 using 1;
            rw [ Finset.sum_Ico_eq_sum_range ] ; norm_num [ add_comm, add_left_comm, add_assoc ];
          -- Since $s \leq x \|c\|$, we have $s^2 \leq x^2 \|c\|^2$.
          have h_s2_le_x2c2 : s^2 ≤ x^2 * ‖c‖^2 := by
            rw [ ← mul_pow ] ; exact pow_le_pow_left₀ ( Nat.cast_nonneg _ ) ( Nat.floor_le ( mul_nonneg ( le_trans ( by positivity ) hx₁ ) ( norm_nonneg _ ) ) ) _;
          refine le_trans h_sum_errors ?_;
          rw [ div_mul_eq_mul_div, div_le_iff₀ ] <;> nlinarith [ show 0 < x ^ 2 by exact sq_pos_of_pos <| lt_of_lt_of_le ( by positivity ) hx₁, show 0 < ‖1 + Complex.I * t‖ by exact norm_pos_iff.mpr <| by norm_num [ Complex.ext_iff ] ];
        -- The main term is $\sum x^{-(1+it)} = s * x^{-(1+it)}$.
        have h_main_term : ‖c - ∑ n ∈ S', ((x : ℂ) ^ (-(1 + Complex.I * t)))‖ ≤ ‖c‖ ^ 2 := by
          -- The main term is $\sum x^{-(1+it)} = s * x^{-(1+it)}$. Use `hx₂` to simplify the expression.
          have h_main_term_simplified : c - ∑ n ∈ S', ((x : ℂ) ^ (-(1 + Complex.I * t))) = (‖c‖ - s / x) * (x : ℂ) ^ (-(Complex.I * t)) := by
            rw [ hx₂.2 ] ; ring_nf;
            norm_num [ Complex.cpow_sub, Complex.cpow_neg, show x ≠ 0 by linarith [ show 0 < x by exact lt_of_lt_of_le ( by positivity ) hx₁ ] ] ; ring_nf;
            norm_num [ Complex.norm_cpow_of_ne_zero, show x ≠ 0 by linarith [ show 0 < x by exact lt_of_lt_of_le ( by positivity ) hx₁ ] ] ; ring_nf;
            norm_num [ mul_assoc, mul_comm, mul_left_comm, Finset.card_range, Complex.arg_ofReal_of_nonneg ( show 0 ≤ x by linarith [ show 0 < x by exact lt_of_lt_of_le ( by positivity ) hx₁ ] ) ];
            norm_num +zetaDelta at *;
          -- Since $|x^{-it}| = 1$, we have $‖c - \sum_{n \in S'} x^{-(1+it)}‖ = ‖‖c‖ - s / x‖$.
          have h_main_term_norm : ‖c - ∑ n ∈ S', ((x : ℂ) ^ (-(1 + Complex.I * t)))‖ = ‖‖c‖ - s / x‖ := by
            rw [ h_main_term_simplified, norm_mul ];
            norm_num [ Complex.norm_cpow_of_ne_zero ( show ( x : ℂ ) ≠ 0 by norm_cast; linarith [ show 0 < x by exact lt_of_lt_of_le ( by positivity ) hx₁ ] ) ];
            norm_num [ Complex.arg_ofReal_of_nonneg ( show 0 ≤ x by linarith [ show 0 ≤ x by exact le_trans ( by positivity ) hx₁ ] ) ];
            norm_cast;
          -- Since $|x^{-it}| = 1$, we have $‖‖c‖ - s / x‖ \leq 1 / x$.
          have h_main_term_bound : ‖‖c‖ - s / x‖ ≤ 1 / x := by
            norm_num [ abs_le ];
            constructor <;> nlinarith [ Nat.floor_le ( show 0 ≤ x * ‖c‖ by exact mul_nonneg ( le_trans ( by positivity ) hx₁ ) ( norm_nonneg c ) ), Nat.lt_floor_add_one ( x * ‖c‖ ), show 0 < x by exact lt_of_lt_of_le ( by positivity ) hx₁, mul_inv_cancel₀ ( show x ≠ 0 by exact ne_of_gt ( lt_of_lt_of_le ( by positivity ) hx₁ ) ), mul_div_cancel₀ ( s : ℝ ) ( show x ≠ 0 by exact ne_of_gt ( lt_of_lt_of_le ( by positivity ) hx₁ ) ) ];
          refine le_trans h_main_term_norm.le <| h_main_term_bound.trans ?_;
          rw [ div_le_iff₀ ] <;> nlinarith [ show 0 < ‖c‖ by exact norm_pos_iff.mpr hc, inv_pos.mpr ( show 0 < ‖c‖ by exact norm_pos_iff.mpr hc ), mul_inv_cancel₀ ( ne_of_gt ( show 0 < ‖c‖ by exact norm_pos_iff.mpr hc ) ), le_max_left ( ‖c‖⁻¹ ^ 2 ) ‖c‖⁻¹, le_max_right ( ‖c‖⁻¹ ^ 2 ) ‖c‖⁻¹ ];
        have := norm_sub_le ( c - ∑ n ∈ S', ( x : ℂ ) ^ ( - ( 1 + Complex.I * t ) ) ) ( ∑ n ∈ S', ( n : ℂ ) ^ ( - ( 1 + Complex.I * t ) ) - ∑ n ∈ S', ( x : ℂ ) ^ ( - ( 1 + Complex.I * t ) ) );
        norm_num at *; linarith;

/-
Existence of a finite set S' that reduces the remainder by a guaranteed amount.
-/
noncomputable def step_target (t : ℝ) (rem : ℂ) : ℂ :=
  let r := (2 + 2 * ‖1 + Complex.I * (t : ℂ)‖)⁻¹
  if ‖rem‖ ≤ r then rem else (r / ‖rem‖) * rem

set_option linter.flexible false in
lemma step_exists (t : ℝ) (ht : t ≠ 0) (N : ℕ) (hN : N > 0) (rem : ℂ) :
  ∃ S' : Finset ℕ, (∀ n ∈ S', n ≥ N) ∧
  (∑ n ∈ S', (n : ℝ)⁻¹) ≤ ‖step_target t rem‖ ∧
  ‖rem - ∑ n ∈ S', (n : ℂ) ^ (-(1 + Complex.I * (t : ℂ)))‖ ≤ max (‖rem‖ / 2) (‖rem‖ - (2 + 2 * ‖1 + Complex.I * (t : ℂ)‖)⁻¹ / 2) := by
    -- Let's first apply Lemma 2.1 to the complex number $c = \text{step\_target}(t, \text{rem})$.
    obtain ⟨S', hS₁, hS₂, hS₃⟩ := lemma_2_1 t ht N hN (step_target t rem);
    refine' ⟨ S', hS₁, hS₂, _ ⟩;
    -- Let's consider the two cases: $|rem| \le r$ and $|rem| > r$.
    by_cases h_case : ‖rem‖ ≤ (2 + 2 * ‖1 + Complex.I * t‖)⁻¹;
    · unfold step_target at * ; aesop;
      rw [ inv_eq_one_div, le_div_iff₀ ] at h_case <;> try positivity;
      exact Or.inl ( hS₃.trans ( by nlinarith [ norm_nonneg rem, norm_nonneg ( 1 + Complex.I * t ) ] ) );
    · -- Since $|rem| > r$, we have $|rem - c| = |rem| - r$.
      have h_case2 : ‖rem - step_target t rem‖ = ‖rem‖ - (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ := by
        unfold step_target; aesop;
        · linarith;
        · rw [ show rem - ( 2 + 2 * ( ‖1 + Complex.I * t‖ : ℂ ) ) ⁻¹ / ( ‖rem‖ : ℂ ) * rem = ( 1 - ( 2 + 2 * ( ‖1 + Complex.I * t‖ : ℂ ) ) ⁻¹ / ( ‖rem‖ : ℂ ) ) * rem by ring_nf, norm_mul ] ; norm_cast ; aesop;
          rw [ abs_of_nonneg ( sub_nonneg_of_le <| by rw [ div_le_iff₀ <| by linarith [ inv_pos.mpr <| show 0 < 2 + 2 * ‖1 + Complex.I * t‖ by positivity ] ] ; linarith [ inv_pos.mpr <| show 0 < 2 + 2 * ‖1 + Complex.I * t‖ by positivity ] ), sub_mul, div_mul_cancel₀ _ <| by linarith [ inv_pos.mpr <| show 0 < 2 + 2 * ‖1 + Complex.I * t‖ by positivity ] ] ; ring_nf;
      -- Using the triangle inequality and the bounds from Lemma 2.1, we get:
      have h_triangle : ‖rem - ∑ n ∈ S', (n : ℂ) ^ (-(1 + Complex.I * t))‖ ≤ ‖rem - step_target t rem‖ + ‖step_target t rem - ∑ n ∈ S', (n : ℂ) ^ (-(1 + Complex.I * t))‖ := by
        simpa using norm_add_le ( rem - step_target t rem ) ( step_target t rem - ∑ n ∈ S', ( n : ℂ ) ^ ( - ( 1 + Complex.I * t ) ) );
      -- Using the bounds from Lemma 2.1, we get:
      have h_bound : (1 + ‖1 + Complex.I * t‖) * ‖step_target t rem‖ ^ 2 ≤ (1 + ‖1 + Complex.I * t‖) * ((2 + 2 * ‖1 + Complex.I * t‖)⁻¹) ^ 2 := by
        unfold step_target; aesop;
        · linarith;
        · norm_cast ; norm_num [ show ‖rem‖ ≠ 0 by linarith [ inv_pos.mpr ( show 0 < 2 + 2 * ‖1 + Complex.I * t‖ by positivity ) ] ];
          norm_cast ; norm_num [ Complex.normSq, Complex.norm_def ];
          rw [ Real.sq_sqrt ( by positivity ) ] ; ring_nf ; norm_num;
      simp +zetaDelta at *;
      exact Or.inr ( by nlinarith [ inv_mul_cancel₀ ( by positivity : ( 2 + 2 * ‖1 + Complex.I * t‖ ) ≠ 0 ), inv_mul_cancel₀ ( by positivity : ( 2 + 2 * ‖1 + Complex.I * t‖ ) ^ 2 ≠ 0 ), norm_nonneg ( 1 + Complex.I * t ) ] )

/-
We choose a specific set S' satisfying the conditions of the existence lemma.
-/
noncomputable def choose_S (t : ℝ) (ht : t ≠ 0) (N : ℕ) (hN : N > 0) (rem : ℂ) : Finset ℕ :=
  Classical.choose (step_exists t ht N hN rem)

lemma choose_S_spec (t : ℝ) (ht : t ≠ 0) (N : ℕ) (hN : N > 0) (rem : ℂ) :
  let S' := choose_S t ht N hN rem
  (∀ n ∈ S', n ≥ N) ∧
  (∑ n ∈ S', (n : ℝ)⁻¹) ≤ ‖step_target t rem‖ ∧
  ‖rem - ∑ n ∈ S', (n : ℂ) ^ (-(1 + Complex.I * (t : ℂ)))‖ ≤ max (‖rem‖ / 2) (‖rem‖ - (2 + 2 * ‖1 + Complex.I * (t : ℂ)‖)⁻¹ / 2) :=
  Classical.choose_spec (step_exists t ht N hN rem)

/-
The sets S_k in the construction are pairwise disjoint.
-/
noncomputable def construction_seq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) : ℕ → (Finset ℕ × ℂ × ℕ)
| 0 => (∅, lambda_val, 1)
| k + 1 =>
  let ⟨_, rem_k, M_k⟩ := construction_seq t ht lambda_val k
  let N := M_k + 1
  let S_next := choose_S t ht N (Nat.succ_pos M_k) rem_k
  let rem_next := rem_k - ∑ n ∈ S_next, (n : ℂ) ^ (-(1 + Complex.I * (t : ℂ)))
  let M_next := max M_k (S_next.sup id)
  (S_next, rem_next, M_next)

def constructed_S (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) : Set ℕ :=
  ⋃ k, (construction_seq t ht lambda_val k).1

set_option linter.flexible false in
lemma construction_disjoint (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) (k l : ℕ) (h : k < l) :
  Disjoint (construction_seq t ht lambda_val k).1 (construction_seq t ht lambda_val l).1 := by
    rw [ Finset.disjoint_left ];
    aesop;
    -- By definition of construction_seq, we know that a is in the set S_k and a is in the set S_l.
    have h_ak : a ≤ (construction_seq t ht lambda_val k).2.2 := by
      -- Since $a \in S_k$, we have $a \leq M_k$ by definition of $M_k$.
      have h_ak_le_Mk : a ≤ (construction_seq t ht lambda_val k).2.2 := by
        have h_def : ∀ n ∈ (construction_seq t ht lambda_val k).1, n ≤ (construction_seq t ht lambda_val k).2.2 := by
          induction k with
          | zero =>
            simp_all +decide [ construction_seq ]
          | succ k ih =>
            simp_all +decide [ construction_seq ]
            exact fun n hn => Or.inr <| Finset.le_sup ( f := id ) hn
        exact h_def a a_1;
      exact h_ak_le_Mk
    have h_al : a ≥ (construction_seq t ht lambda_val (l - 1)).2.2 + 1 := by
      have h_al : a ∈ (choose_S t ht (Nat.succ (construction_seq t ht lambda_val (l - 1)).2.2) (Nat.succ_pos (construction_seq t ht lambda_val (l - 1)).2.2) ((construction_seq t ht lambda_val (l - 1)).2.1)) := by
        cases l <;> aesop;
      have := choose_S_spec t ht ( Nat.succ ( construction_seq t ht lambda_val ( l - 1 ) |>.2.2 ) ) ( Nat.succ_pos _ ) ( construction_seq t ht lambda_val ( l - 1 ) |>.2.1 ) ; aesop;
    -- By definition of construction_seq, we know that M_k is non-decreasing.
    have h_mk_nondec : ∀ k l, k ≤ l → (construction_seq t ht lambda_val k).2.2 ≤ (construction_seq t ht lambda_val l).2.2 := by
      intros k l hkl; induction hkl <;> aesop;
      exact le_trans a_ih ( by exact le_max_left _ _ );
    linarith [ h_mk_nondec k ( l - 1 ) ( Nat.le_sub_one_of_lt h ) ]

/-
Helper functions to access the set S_k and the remainder rem_k from the construction sequence.
-/
noncomputable def S_seq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) (k : ℕ) : Finset ℕ :=
  (construction_seq t ht lambda_val k).1

noncomputable def rem_seq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) (k : ℕ) : ℂ :=
  (construction_seq t ht lambda_val k).2.1

/-
The remainder sequence converges to 0.
-/
lemma rem_convergence (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  Filter.Tendsto (rem_seq t ht lambda_val) Filter.atTop (nhds 0) := by
    -- Let `rem_k` be the remainder at step `k`.
    set rem := rem_seq t ht lambda_val
    -- We have |rem_{k+1}| \le |rem_k|/2 if |rem_k| \le r, and |rem_{k+1}| \le |rem_k| - r/2 if |rem_k| > r.
    have h_rem_bound : ∀ k, ‖rem (k + 1)‖ ≤ max (‖rem k‖ / 2) (‖rem k‖ - (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ / 2) := by
      intro k;
      have := choose_S_spec t ht ( ( construction_seq t ht lambda_val k ).2.2 + 1 ) ( Nat.succ_pos _ ) ( rem k );
      convert this.2.2 using 1;
    -- If |rem_k| stays above r, it decreases by r/2 each step, which is impossible. So eventually |rem_k| ≤ r.
    have h_rem_le_r : ∃ k, ‖rem k‖ ≤ (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ := by
      by_contra h_contra;
      -- If |rem_k| stays above r, it decreases by r/2 each step, which is impossible. So eventually |rem_k| ≤ r. We prove this by induction.
      have h_induction : ∀ k, ‖rem k‖ ≤ ‖rem 0‖ - k * (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ / 2 := by
        intro k; induction k <;> aesop;
        cases h_rem_bound n <;> linarith [ h_contra n, h_contra ( n + 1 ) ];
      exact h_contra ⟨ ⌊2 * ‖rem 0‖ / ( 2 + 2 * ‖1 + Complex.I * t‖ ) ⁻¹⌋₊ + 1, by have := h_induction ( ⌊2 * ‖rem 0‖ / ( 2 + 2 * ‖1 + Complex.I * t‖ ) ⁻¹⌋₊ + 1 ) ; push_cast at *; nlinarith [ Nat.lt_floor_add_one ( 2 * ‖rem 0‖ / ( 2 + 2 * ‖1 + Complex.I * t‖ ) ⁻¹ ), norm_nonneg ( rem 0 ), inv_pos.mpr ( by positivity : 0 < ( 2 + 2 * ‖1 + Complex.I * t‖ ) ), mul_inv_cancel₀ ( by positivity : ( 2 + 2 * ‖1 + Complex.I * t‖ ) ≠ 0 ), mul_div_cancel₀ ( 2 * ‖rem 0‖ ) ( by positivity : ( 2 + 2 * ‖1 + Complex.I * t‖ ) ⁻¹ ≠ 0 ) ] ⟩;
    obtain ⟨ k, hk ⟩ := h_rem_le_r;
    -- Once |rem_k| ≤ r, it halves each step, so it converges to 0 exponentially.
    have h_rem_exp : ∀ m ≥ k, ‖rem m‖ ≤ (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ * (1 / 2) ^ (m - k) := by
      intro m hm; induction hm <;> aesop;
      cases h_rem_bound m_1 <;> simp_all +decide [ Nat.succ_sub a, pow_succ' ];
      · linarith;
      · nlinarith [ inv_pos.mpr ( show 0 < ( 2 + 2 * ‖1 + Complex.I * t‖ ) by positivity ), inv_pos.mpr ( show 0 < ( 2 ^ ( m_1 - k ) : ℝ ) by positivity ), mul_inv_cancel₀ ( show ( 2 + 2 * ‖1 + Complex.I * t‖ ) ≠ 0 by positivity ), mul_inv_cancel₀ ( show ( 2 ^ ( m_1 - k ) : ℝ ) ≠ 0 by positivity ), pow_le_pow_right₀ ( by norm_num : ( 1 : ℝ ) ≤ 2 ) ( Nat.zero_le ( m_1 - k ) ) ];
    exact squeeze_zero_norm' ( Filter.eventually_atTop.mpr ⟨ k, h_rem_exp ⟩ ) ( by simpa using tendsto_const_nhds.mul ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by norm_num ) ( by norm_num : ( 1 : ℝ ) / 2 < 1 ) |> Filter.Tendsto.comp <| Filter.tendsto_sub_atTop_nat k ) )

/-
The sum of reciprocals of the elements in the constructed set is summable.
-/
lemma sum_recip_bounded (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  Summable (fun k => ∑ n ∈ S_seq t ht lambda_val k, (n : ℝ)⁻¹) := by
    -- The choice of $S_{k+1}$ ensures that $|rem_{k+1}| \le \max(|rem_k| / 2, |rem_k| - r / 2)$ where $r = (2 + 2 * ‖1 + Complex.I * t‖)⁻¹$.
    have h_rem_recurrence : ∀ k, ‖rem_seq t ht lambda_val (k + 1)‖ ≤ max (‖rem_seq t ht lambda_val k‖ / 2) (‖rem_seq t ht lambda_val k‖ - (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ / 2) := by
      intro k;
      convert choose_S_spec t ht ( Nat.succ ( construction_seq t ht lambda_val k |>.2.2 ) ) ( Nat.succ_pos _ ) ( rem_seq t ht lambda_val k ) |> And.right |> And.right using 1;
    -- Since $|rem_k|$ is non-increasing and converges to $0$, there exists $K$ such that for all $k \ge K$, $|rem_k| \le r$.
    obtain ⟨K, hK⟩ : ∃ K, ∀ k ≥ K, ‖rem_seq t ht lambda_val k‖ ≤ (2 + 2 * ‖1 + Complex.I * t‖)⁻¹ := by
      have := rem_convergence t ht lambda_val;
      simpa using this.eventually ( Metric.closedBall_mem_nhds _ <| by positivity );
    -- For $k \ge K$, we have $|rem_{k+1}| \le |rem_k| / 2$, so the sum of the reciprocals of the elements in $S_{k+1}$ is bounded by $|rem_k|$.
    have h_sum_bound : ∀ k ≥ K, ∑ n ∈ S_seq t ht lambda_val (k + 1), (n : ℝ)⁻¹ ≤ ‖rem_seq t ht lambda_val k‖ := by
      intros k hk
      have h_step_target : ‖step_target t (rem_seq t ht lambda_val k)‖ ≤ ‖rem_seq t ht lambda_val k‖ := by
        unfold step_target; aesop;
      have := choose_S_spec t ht ( ( construction_seq t ht lambda_val k ).2.2 + 1 ) ( Nat.succ_pos _ ) ( rem_seq t ht lambda_val k ) ; aesop;
      · convert left_1.trans h_step_target using 1;
      · exact le_trans left_1 h_step_target;
    -- Since $|rem_k|$ is non-increasing and converges to $0$, the series $\sum_{k=K}^{\infty} |rem_k|$ is summable.
    have h_rem_summable : Summable (fun k => ‖rem_seq t ht lambda_val (k + K)‖) := by
      -- Since $|rem_k|$ is non-increasing and converges to $0$, we can apply the comparison test with the geometric series $\sum_{k=0}^{\infty} (1/2)^k$.
      have h_comparison : ∀ k, ‖rem_seq t ht lambda_val (k + K)‖ ≤ ‖rem_seq t ht lambda_val K‖ * (1 / 2) ^ k := by
        intro k
        induction k with
        | zero =>
          norm_num [ pow_succ, ← mul_assoc ] at *
        | succ k ih =>
          norm_num [ pow_succ, ← mul_assoc ] at *
          cases h_rem_recurrence ( k + K ) <;> rw [ Nat.succ_add ] at * <;>
            nlinarith [ hK ( k + K ) ( by linarith ),
              hK ( k + K + 1 ) ( by linarith ),
              inv_pos.mpr ( show 0 < ( 2 + 2 * ‖1 + Complex.I * t‖ ) by positivity ) ];
      exact Summable.of_nonneg_of_le ( fun k => norm_nonneg _ ) h_comparison ( Summable.mul_left _ ( summable_geometric_two ) );
    rw [ ← summable_nat_add_iff ( K + 1 ) ];
    exact Summable.of_nonneg_of_le ( fun n => Finset.sum_nonneg fun _ _ => inv_nonneg.2 <| Nat.cast_nonneg _ ) ( fun n => by simpa only [ add_comm, add_left_comm, add_assoc ] using h_sum_bound _ <| Nat.le_add_left _ _ ) h_rem_summable

/-
The partial sum of the series over the first N+1 blocks equals lambda minus the N-th remainder.
-/
lemma partial_sum_eq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) (N : ℕ) :
  ∑ k ∈ Finset.range (N + 1), ∑ n ∈ S_seq t ht lambda_val k, (n : ℂ) ^ (-(1 + Complex.I * t)) = lambda_val - rem_seq t ht lambda_val N := by
    induction N with
    | zero =>
      unfold S_seq rem_seq; norm_num;
      unfold construction_seq; norm_num;
    | succ N ih =>
      -- By definition of `construction_seq`, we have `rem_seq t ht lambda_val (N + 1) = rem_seq t ht lambda_val N - ∑ n ∈ S_seq t ht lambda_val (N + 1), (n : ℂ) ^ (-(1 + Complex.I * t))`.
      have h_rem_succ : rem_seq t ht lambda_val (N + 1) = rem_seq t ht lambda_val N - ∑ n ∈ S_seq t ht lambda_val (N + 1), (n : ℂ) ^ (-(1 + Complex.I * t)) := by
        exact Complex.ext rfl rfl;
      rw [ Finset.sum_range_succ, ih, h_rem_succ ] ; ring_nf

/-
The sum of the series grouped by blocks equals lambda.
-/
lemma grouped_sum_eq_lambda (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  (∑' k, ∑ n ∈ S_seq t ht lambda_val k, (n : ℂ) ^ (-(1 + Complex.I * t))) = lambda_val := by
    refine' HasSum.tsum_eq _;
    rw [ hasSum_iff_tendsto_nat_of_summable_norm ];
    · have h_partial_sum : ∀ N, ∑ k ∈ Finset.range (N + 1), ∑ n ∈ S_seq t ht lambda_val k, (n : ℂ) ^ (-(1 + Complex.I * t)) = lambda_val - rem_seq t ht lambda_val N := by
        exact fun N ↦ partial_sum_eq t ht lambda_val N;
      rw [ ← Filter.tendsto_add_atTop_iff_nat 1 ] ; aesop;
      simpa using tendsto_const_nhds.sub ( rem_convergence t ht lambda_val );
    · refine' .of_nonneg_of_le ( fun k => norm_nonneg _ ) ( fun k => _ ) ( show Summable fun k => ∑ n ∈ S_seq t ht lambda_val k, ( n : ℝ ) ⁻¹ from _ );
      · -- Apply the triangle inequality to the sum.
        have h_triangle : ∀ n ∈ S_seq t ht lambda_val k, ‖(n : ℂ) ^ (-(1 + Complex.I * t))‖ ≤ (n : ℝ)⁻¹ := by
          -- Apply the lemma norm_complex_pow with σ = 1 and τ = t.
          have h_norm : ∀ n : ℕ, n > 0 → ‖(n : ℂ) ^ (-(1 + Complex.I * t))‖ = n ^ (-1 : ℝ) := by
            intro n hn; rw [ Complex.norm_cpow_of_ne_zero ( Nat.cast_ne_zero.mpr hn.ne' ) ] ; norm_num;
          intro n hn; specialize h_norm n; by_cases hn' : 0 < n <;> aesop;
          · rw [ Real.rpow_neg_one ];
          · norm_num [ Complex.ext_iff ] at a;
        exact le_trans ( norm_sum_le _ _ ) ( Finset.sum_le_sum h_triangle );
      · exact sum_recip_bounded t ht lambda_val

/-
The sum of reciprocals over the constructed set S is summable.
-/
open Classical in
lemma summable_constructed_S (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  Summable (fun n => if n ∈ constructed_S t ht lambda_val then (n : ℝ)⁻¹ else 0) := by
    refine' summable_of_sum_le _ _;
    exact ∑' k, ∑ n ∈ S_seq t ht lambda_val k, ( n : ℝ ) ⁻¹;
    · exact fun n => by positivity;
    · intro u;
      -- Since $u$ is finite, we can find a maximum index $M$ such that all elements of $u$ are in $S_k$ for some $k \leq M$.
      obtain ⟨M, hM⟩ : ∃ M : ℕ, ∀ n ∈ u, n ∈ constructed_S t ht lambda_val → ∃ k ≤ M, n ∈ S_seq t ht lambda_val k := by
        have h_finite : ∀ n ∈ u, n ∈ constructed_S t ht lambda_val → ∃ k, n ∈ S_seq t ht lambda_val k := by
          unfold constructed_S; aesop;
        choose! k hk using h_finite;
        exact ⟨ Finset.sup u k, fun n hn hn' => ⟨ k n, Finset.le_sup ( f := k ) hn, hk n hn hn' ⟩ ⟩;
      -- Using the maximum index $M$, we can bound the sum over $u$ by the sum over the first $M+1$ blocks.
      have h_bound : ∑ x ∈ u, (if x ∈ constructed_S t ht lambda_val then (x : ℝ)⁻¹ else 0) ≤ ∑ k ∈ Finset.range (M + 1), ∑ n ∈ S_seq t ht lambda_val k, (n : ℝ)⁻¹ := by
        have h_bound : ∑ x ∈ u, (if x ∈ constructed_S t ht lambda_val then (x : ℝ)⁻¹ else 0) ≤ ∑ k ∈ Finset.range (M + 1), ∑ n ∈ u, (if n ∈ S_seq t ht lambda_val k then (n : ℝ)⁻¹ else 0) := by
          rw [ Finset.sum_comm ];
          gcongr ; aesop;
          · obtain ⟨ k, hk₁, hk₂ ⟩ := hM i a h; exact le_trans ( by aesop ) ( Finset.single_le_sum ( fun x _ => by positivity ) ( Finset.mem_range.mpr ( Nat.lt_succ_of_le hk₁ ) ) ) ;
          · exact Finset.sum_nonneg fun _ _ => by positivity;
        refine le_trans h_bound ?_;
        gcongr ; aesop;
        exact Finset.sum_le_sum_of_subset_of_nonneg ( Finset.inter_subset_right ) fun _ _ _ => by positivity;
      refine' le_trans h_bound ( Summable.sum_le_tsum _ _ _ );
      · exact fun _ _ => Finset.sum_nonneg fun _ _ => inv_nonneg.2 <| Nat.cast_nonneg _;
      · exact sum_recip_bounded t ht lambda_val

/-
The complex power series is summable on the constructed set.
-/
open Classical in
lemma summable_complex_constructed_S (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  Summable (fun n => if n ∈ constructed_S t ht lambda_val then (n : ℂ) ^ (-(1 + Complex.I * t)) else 0) := by
    -- We know `summable_constructed_S` gives summability of `n^{-1}` on `constructed_S`, and `|n^{-(1+it)}| = n^{-1}` for `n > 0`.
    -- Elements of `constructed_S` are `>= 2`, so `n > 0`. Thus the norm of the complex term is bounded by the real term (actually equal).
    -- Since the real series is summable, the complex series is absolutely summable.
    have norm_eq : ∀ n ∈ constructed_S t ht lambda_val, ‖(n : ℂ) ^ (-(1 + Complex.I * t))‖ = (n : ℝ)⁻¹ := by
      intro n hn;
      cases lt_trichotomy n 0 <;> aesop;
      · norm_num [ Complex.ext_iff ] at a;
      · rw [ Complex.norm_cpow_of_ne_zero ] <;> aesop;
        rw [ Real.rpow_neg_one ];
    have := summable_constructed_S t ht lambda_val;
    rw [ ← summable_norm_iff ] at * ; aesop;
    exact this.congr fun n => by aesop;

/-
Equivalence between the constructed set and the sigma type of the sequence of sets.
-/
noncomputable def equiv_constructed_S (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  {n : ℕ // n ∈ constructed_S t ht lambda_val} ≃ (Σ k : ℕ, {n : ℕ // n ∈ S_seq t ht lambda_val k}) where
  toFun := fun ⟨n, hn⟩ =>
    let k := (Set.mem_iUnion.mp hn).choose
    have hk : n ∈ S_seq t ht lambda_val k := (Set.mem_iUnion.mp hn).choose_spec
    ⟨k, n, hk⟩
  invFun := fun ⟨k, n, hn⟩ => ⟨n, Set.mem_iUnion.mpr ⟨k, hn⟩⟩
  left_inv := fun ⟨n, hn⟩ => by
    field_simp
  right_inv := fun ⟨k, n, hn⟩ => by
    congr!;
    have h_unique : ∀ k' : ℕ, n ∈ S_seq t ht lambda_val k' → k' = k := by
      intros k' hk'
      have h_disjoint : ∀ k1 k2 : ℕ, k1 ≠ k2 → Disjoint (S_seq t ht lambda_val k1) (S_seq t ht lambda_val k2) := by
        intros k1 k2 hne; cases lt_or_gt_of_ne hne <;> [ exact construction_disjoint _ _ _ _ _ ‹_› ; exact Disjoint.symm ( construction_disjoint _ _ _ _ _ ‹_› ) ] ;
      exact Classical.not_not.1 fun h => Finset.disjoint_left.1 ( h_disjoint _ _ h ) hk' hn;
    exact h_unique _ ( Classical.choose_spec ( show ∃ k', n ∈ S_seq t ht lambda_val k' from ⟨ k, hn ⟩ ) )

/-
The sum of a function supported on the constructed set equals the sum of sums over the disjoint blocks.
-/
lemma tsum_constructed_S_eq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) (f : ℕ → ℂ)
  (hf : ∀ n ∉ constructed_S t ht lambda_val, f n = 0)
  (h_summable : Summable f) :
  ∑' n, f n = ∑' k, ∑ n ∈ S_seq t ht lambda_val k, f n := by
    classical
    let e := equiv_constructed_S t ht lambda_val
    have hsupport : Function.support f ⊆ constructed_S t ht lambda_val := by
      intro n hn
      by_contra hnS
      exact hn (hf n hnS)
    have h_sigma_summable :
        Summable (fun p : (Σ k : ℕ, {n : ℕ // n ∈ S_seq t ht lambda_val k}) =>
          f p.2.1) := by
      refine h_summable.comp_injective ?_
      intro p q hpq
      cases p with
      | mk pk pn =>
        cases q with
        | mk qk qn =>
          simp only at hpq
          have h_disjoint :
              ∀ k l : ℕ, k ≠ l → Disjoint (S_seq t ht lambda_val k)
                (S_seq t ht lambda_val l) := by
            intro k l hkl
            cases lt_or_gt_of_ne hkl with
            | inl hlt => exact construction_disjoint t ht lambda_val k l hlt
            | inr hlt => exact Disjoint.symm (construction_disjoint t ht lambda_val l k hlt)
          have hk : pk = qk := by
            by_contra hpqk
            have hqmem : (pn : ℕ) ∈ S_seq t ht lambda_val qk := by
              simp [hpq, qn.2]
            exact Finset.disjoint_left.mp (h_disjoint pk qk hpqk) pn.2 hqmem
          cases hk
          congr
          exact Subtype.ext hpq
    calc
      ∑' n, f n
          = ∑' n : {n : ℕ // n ∈ constructed_S t ht lambda_val}, f n := by
            exact (tsum_subtype_eq_of_support_subset hsupport).symm
      _ = ∑' p : (Σ k : ℕ, {n : ℕ // n ∈ S_seq t ht lambda_val k}), f p.2.1 := by
            calc
              ∑' n : {n : ℕ // n ∈ constructed_S t ht lambda_val}, f n.1
                  = ∑' n : {n : ℕ // n ∈ constructed_S t ht lambda_val}, f (e n).2.1 := by
                    exact tsum_congr fun n => rfl
              _ = ∑' p : (Σ k : ℕ, {n : ℕ // n ∈ S_seq t ht lambda_val k}), f p.2.1 := by
                    exact e.tsum_eq (fun p : (Σ k : ℕ, {n : ℕ // n ∈ S_seq t ht lambda_val k}) => f p.2.1)
      _ = ∑' k, ∑' n : {n : ℕ // n ∈ S_seq t ht lambda_val k}, f n.1 := by
            exact h_sigma_summable.tsum_sigma
      _ = ∑' k, ∑ n ∈ S_seq t ht lambda_val k, f n := by
            exact tsum_congr fun k => Finset.tsum_subtype (S_seq t ht lambda_val k) f

/-
All elements in the constructed set S are greater than or equal to 2.
-/
set_option linter.flexible false in
lemma main_theorem_ge_2 (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  ∀ n ∈ constructed_S t ht lambda_val, n ≥ 2 := by
    intro n hn;
    obtain ⟨ k, hk ⟩ := Set.mem_iUnion.mp hn;
    -- By definition of `construction_seq`, we know that all elements in `S_seq k` are greater than or equal to `M_seq (k - 1) + 1`.
    have h_M_seq : ∀ k, ∀ n ∈ S_seq t ht lambda_val k, n ≥ (construction_seq t ht lambda_val (k - 1)).2.2 + 1 := by
      rintro ( _ | k ) n hn <;> simp_all +decide [ construction_seq ];
      · exact absurd hn ( by erw [ show S_seq t ht lambda_val 0 = ∅ by rfl ] ; norm_num );
      · exact Classical.choose_spec ( step_exists t ht ( ( construction_seq t ht lambda_val k ).2.2 + 1 ) ( Nat.succ_pos _ ) ( ( construction_seq t ht lambda_val k ).2.1 ) ) |>.1 n hn;
    exact le_trans ( Nat.succ_le_succ <| Nat.one_le_iff_ne_zero.mpr <| by
      induction k - 1 with
      | zero =>
        norm_num [ *, construction_seq ]
      | succ m ih =>
        norm_num [ *, construction_seq ] ) ( h_M_seq k n hk )

/-
The infinite sum of the terms equals lambda.
-/
open Classical in
lemma tsum_eq_lambda (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  ∑' n, (if n ∈ constructed_S t ht lambda_val then (n : ℂ) ^ (-(1 + Complex.I * (t : ℂ))) else 0) = lambda_val := by
    -- Apply the lemma `grouped_sum_eq_lambda` to conclude that the sum of the series is lambda.
    have h_sum : ∑' n, (if n ∈ constructed_S t ht lambda_val then (n : ℂ) ^ (-(1 + Complex.I * t)) else 0) = ∑' k, ∑ n ∈ S_seq t ht lambda_val k, (n : ℂ) ^ (-(1 + Complex.I * t)) := by
      convert tsum_constructed_S_eq t ht lambda_val _ _ _ using 1;
      · refine' tsum_congr fun k => Finset.sum_congr rfl fun n hn => _;
        rw [ if_pos ];
        exact Set.mem_iUnion.mpr ⟨ k, hn ⟩;
      · aesop;
      · exact summable_complex_constructed_S t ht lambda_val
    have h_final : ∑' k, ∑ n ∈ S_seq t ht lambda_val k, (n : ℂ) ^ (-(1 + Complex.I * t)) = lambda_val := by
      exact grouped_sum_eq_lambda t ht lambda_val
    rw [h_sum, h_final]

/-
The sequence defined by the target terms is summable.
-/
open Classical in
noncomputable def target_seq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) (n : ℕ) : ℂ :=
  if n ∈ constructed_S t ht lambda_val then (n : ℂ) ^ (-(1 + Complex.I * (t : ℂ))) else 0

lemma summable_target_seq (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  Summable (target_seq t ht lambda_val) := by
    have := summable_complex_constructed_S t ht lambda_val;
    convert this using 1

/-
For any real number t ≠ 0 and any complex number λ, there exists a subset S ⊆ ℤ≥2 such that ∑_{n∈S} 1/n < ∞ and ∑_{n∈S} 1/n^{1+it} = λ.
-/
open Classical in
theorem main_theorem (t : ℝ) (ht : t ≠ 0) (lambda_val : ℂ) :
  ∃ S : Set ℕ, (∀ n ∈ S, n ≥ 2) ∧
  Summable (fun n => if n ∈ S then (n : ℝ)⁻¹ else 0) ∧
  (∑' n, if n ∈ S then (n : ℂ) ^ (-(1 + Complex.I * t)) else 0) = lambda_val := by
    refine' ⟨ constructed_S t ht lambda_val, _, _, _ ⟩;
    · exact main_theorem_ge_2 t ht lambda_val
    · exact summable_constructed_S t ht lambda_val
    · exact tsum_eq_lambda t ht lambda_val

/-
Conjecture 3.1: For any finite set S ⊆ ℤ≥2 and any real number t, 1 + ∑_{n∈S} 1/n^{1+it} ≠ 0.
-/
def conjecture_3_1_statement : Prop :=
  ∀ (S : Finset ℕ), (∀ n ∈ S, 2 ≤ n) → ∀ (t : ℝ),
  1 + ∑ n ∈ S, (n : ℂ) ^ (-(1 + Complex.I * t)) ≠ 0

/-
Question 3.2: Is it true that for every real number t, 1 + 2^{-1-it} + 3^{-1-it} + 5^{-1-it} ≠ 0?
-/
def erdos_ingham_2_3_5_statement : Prop :=
  ∀ (t : ℝ), 1 + (2 : ℂ) ^ (-(1 + Complex.I * t)) + (3 : ℂ) ^ (-(1 + Complex.I * t)) + (5 : ℂ) ^ (-(1 + Complex.I * t)) ≠ 0

/-
Question 1.1: Let 1 < a_1 < a_2 < ... be a (finite or infinite) sequence of integers such that sum a_k^{-1} < infinity. Is it true that, for every t in R, 1 + sum a_k^{-1-it} != 0?
-/
open Classical in
def question_1_1_statement : Prop :=
  ∀ (S : Set ℕ), (∀ n ∈ S, 1 < n) →
  Summable (fun n => if n ∈ S then (n : ℝ)⁻¹ else 0) →
  ∀ (t : ℝ), 1 + (∑' n, if n ∈ S then (n : ℂ) ^ (-(1 + Complex.I * t)) else 0) ≠ 0

/-
Disproof of Question 1.1: It is not true that for every sequence 1 < a_1 < ... with summable reciprocals and every t, 1 + sum a_k^{-1-it} != 0.
-/
theorem disproof_of_question_1_1 : ¬ question_1_1_statement := by
  by_contra h_contra;
  -- Apply the main theorem to obtain the set S.
  obtain ⟨S, hS⟩ := main_theorem 1 (by norm_num) (-1);
  specialize h_contra S hS.1 hS.2.1 ; aesop;
  exact h_contra 1 ( by norm_num [ right ] )

#print axioms main_theorem
-- 'Erdos967.main_theorem' depends on axioms: [propext, Classical.choice, Quot.sound]
#print axioms disproof_of_question_1_1
-- 'Erdos967.disproof_of_question_1_1' depends on axioms: [propext, Classical.choice, Quot.sound]

end Erdos967
