/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import ErdosProblems.Erdos735.SignVectorDoubleRestriction

/-!
# Counts on the one-dimensional double restriction

The common kernel of two independent normals is the line generated by their cross product.  Thus
a nonempty family cuts that line into exactly two strict sign regions when every prior normal is
nonzero on the line, and into no strict regions when one prior normal vanishes there.  For the
empty family there is the unique empty sign pattern.
-/

open scoped BigOperators Matrix
open Matrix

namespace Erdos735.SignVector

noncomputable section

variable {I : Type*} [Fintype I]

lemma eq_smul_cross_of_dot_eq_zero {h k x : Vec3}
    (hind : h ⨯₃ k ≠ 0) (hhx : h ⬝ᵥ x = 0) (hkx : k ⬝ᵥ x = 0) :
    ∃ a : ℝ, x = a • (h ⨯₃ k) := by
  have hcross : (h ⨯₃ k) ⨯₃ x = 0 := by
    rw [cross_cross_eq_smul_sub_smul, hhx, hkx]
    simp
  have hnotli : ¬ LinearIndependent ℝ ![h ⨯₃ k, x] := by
    rw [← crossProduct_ne_zero_iff_linearIndependent]
    exact not_ne_iff.mpr hcross
  rw [LinearIndependent.pair_iff' hind] at hnotli
  push_neg at hnotli
  obtain ⟨a, ha⟩ := hnotli
  exact ⟨a, ha.symm⟩

lemma realizes_of_realizes_pos_smul {n : I → Vec3} {s : I → Bool}
    {x : Vec3} {a : ℝ} (ha : 0 < a) (hx : Realizes n s (a • x)) :
    Realizes n s x := by
  intro i
  have hi := hx i
  simp only [dotProduct_smul, smul_eq_mul, signed_mul] at hi
  exact (mul_pos_iff_of_pos_left ha).mp hi

lemma doubleRestrictedRealizable_iff_realizes_cross_or_neg
    [Nonempty I] (n : I → Vec3) {h k : Vec3} (hind : h ⨯₃ k ≠ 0)
    (s : I → Bool) :
    DoubleRestrictedRealizable n h k s ↔
      Realizes n s (h ⨯₃ k) ∨ Realizes n s (-(h ⨯₃ k)) := by
  constructor
  · rintro ⟨x, hx, hhx, hkx⟩
    obtain ⟨a, rfl⟩ := eq_smul_cross_of_dot_eq_zero hind hhx hkx
    have ha : a ≠ 0 := by
      intro ha
      subst a
      let i : I := Classical.choice inferInstance
      have hi := hx i
      simp [signed] at hi
    rcases lt_or_gt_of_ne ha with ha | ha
    · right
      have hrewrite : a • (h ⨯₃ k) = (-a) • (-(h ⨯₃ k)) := by
        rw [smul_neg, neg_smul, neg_neg]
      apply realizes_of_realizes_pos_smul (neg_pos.mpr ha)
      rwa [← hrewrite]
    · left
      exact realizes_of_realizes_pos_smul ha hx
  · rintro (hx | hx)
    · exact ⟨h ⨯₃ k, hx, dot_self_cross h k, dot_cross_self h k⟩
    · refine ⟨-(h ⨯₃ k), hx, ?_, ?_⟩ <;> simp

def strictSignAt (n : I → Vec3) (x : Vec3) (i : I) : Bool :=
  decide (0 < n i ⬝ᵥ x)

lemma realizes_strictSignAt_iff (n : I → Vec3) (x : Vec3) :
    Realizes n (strictSignAt n x) x ↔ ∀ i, n i ⬝ᵥ x ≠ 0 := by
  constructor
  · intro hx i hzero
    have hi := hx i
    rw [hzero] at hi
    cases h : strictSignAt n x i <;> simp [signed, h] at hi
  · intro hne i
    by_cases hpos : 0 < n i ⬝ᵥ x
    · simp [strictSignAt, hpos, signed]
    · have hneg : n i ⬝ᵥ x < 0 :=
        lt_of_le_of_ne (le_of_not_gt hpos) (hne i)
      simp [strictSignAt, hpos, signed, hneg]

lemma eq_strictSignAt_of_realizes (n : I → Vec3) (x : Vec3) (s : I → Bool)
    (hs : Realizes n s x) : s = strictSignAt n x := by
  funext i
  have hi := hs i
  cases hb : s i with
  | false =>
      have hneg : n i ⬝ᵥ x < 0 := by simpa [signed, hb] using hi
      simp [strictSignAt, hb, not_lt.mpr hneg.le]
  | true =>
      have hpos : 0 < n i ⬝ᵥ x := by simpa [signed, hb] using hi
      simp [strictSignAt, hb, hpos]

lemma realizes_iff_eq_strictSignAt (n : I → Vec3) (x : Vec3)
    (hne : ∀ i, n i ⬝ᵥ x ≠ 0) (s : I → Bool) :
    Realizes n s x ↔ s = strictSignAt n x := by
  constructor
  · exact eq_strictSignAt_of_realizes n x s
  · rintro rfl
    exact (realizes_strictSignAt_iff n x).2 hne

lemma strictSignAt_neg_eq_antipodalSign (n : I → Vec3) (x : Vec3)
    (hne : ∀ i, n i ⬝ᵥ x ≠ 0) :
    strictSignAt n (-x) = antipodalSign (strictSignAt n x) := by
  have hx : Realizes n (strictSignAt n x) x :=
    (realizes_strictSignAt_iff n x).2 hne
  have hneg : Realizes n (antipodalSign (strictSignAt n x)) (-x) :=
    (realizes_antipodalSign_neg_iff n (strictSignAt n x) x).2 hx
  exact (eq_strictSignAt_of_realizes n (-x) _ hneg).symm

theorem doubleRestrictedFaceCount_eq_two
    [Nonempty I] (n : I → Vec3) {h k : Vec3} (hind : h ⨯₃ k ≠ 0)
    (hne : ∀ i, n i ⬝ᵥ (h ⨯₃ k) ≠ 0) :
    doubleRestrictedFaceCount n h k = 2 := by
  classical
  let c := h ⨯₃ k
  have hneneg : ∀ i, n i ⬝ᵥ (-c) ≠ 0 := by
    intro i
    simpa [dotProduct_neg] using hne i
  have hpatterns : doubleRestrictedFacePatterns n h k =
      {strictSignAt n c, strictSignAt n (-c)} := by
    ext s
    simp only [doubleRestrictedFacePatterns, Finset.mem_filter, Finset.mem_univ,
      true_and, Finset.mem_insert, Finset.mem_singleton]
    rw [doubleRestrictedRealizable_iff_realizes_cross_or_neg n hind]
    change Realizes n s c ∨ Realizes n s (-c) ↔ _
    rw [realizes_iff_eq_strictSignAt n c hne,
      realizes_iff_eq_strictSignAt n (-c) hneneg]
  have hdistinct : strictSignAt n c ≠ strictSignAt n (-c) := by
    rw [strictSignAt_neg_eq_antipodalSign n c hne]
    exact (antipodalSign_ne (strictSignAt n c)).symm
  rw [doubleRestrictedFaceCount, hpatterns]
  simp [hdistinct]

theorem doubleRestrictedFaceCount_eq_zero_of_exists_dot_cross_eq_zero
    [Nonempty I] (n : I → Vec3) {h k : Vec3} (hind : h ⨯₃ k ≠ 0)
    (hzero : ∃ i, n i ⬝ᵥ (h ⨯₃ k) = 0) :
    doubleRestrictedFaceCount n h k = 0 := by
  classical
  obtain ⟨i, hi⟩ := hzero
  have hnone : ∀ s, ¬ DoubleRestrictedRealizable n h k s := by
    intro s hs
    rw [doubleRestrictedRealizable_iff_realizes_cross_or_neg n hind] at hs
    rcases hs with hs | hs
    · have := hs i
      rw [hi] at this
      cases h : s i <;> simp [signed, h] at this
    · have := hs i
      rw [dotProduct_neg, hi] at this
      cases h : s i <;> simp [signed, h] at this
  rw [doubleRestrictedFaceCount, doubleRestrictedFacePatterns]
  simp [hnone]

theorem doubleRestrictedFaceCount_fin_zero (n : Fin 0 → Vec3) (h k : Vec3) :
    doubleRestrictedFaceCount n h k = 1 := by
  classical
  rw [doubleRestrictedFaceCount, doubleRestrictedFacePatterns]
  have hpatterns : (Finset.univ.filter (DoubleRestrictedRealizable n h k)) = Finset.univ := by
    ext s
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    constructor
    · intro
      trivial
    · intro
      exact ⟨0, (fun i => Fin.elim0 i), by simp, by simp⟩
  exact (congrArg Finset.card hpatterns).trans (by simp)

end

end Erdos735.SignVector
