import ErdosProblems.Erdos4

/-! Kernel dependency checks, including the unconditional final theorem
and an explicit restatement of its arbitrary-positive-constant conclusion. -/

#print axioms Erdos4.DirectMoments.mean_miss_le_moment_ratio
#print axioms Erdos4.PrimitiveProfile.exists_arbitrary_gain
#print axioms Erdos4.PrimitiveProfile.integral_profile
#print axioms Erdos4.LocalOrthogonality.mean_expansion_sq
#print axioms Erdos4.LocalOrthogonality.sum_evaluation_sq
#print axioms Erdos4.ProductOrthogonality.mean_expansion_sq
#print axioms Erdos4.RestrictedProductNorm.abs_restrictedForm_le
#print axioms Erdos4.SliceBounds.norm_matrix_slice_sum_le
#print axioms Erdos4.DivisorCoefficients.coefficient_le_removedFactor_mul_erase
#print axioms Erdos4.DivisorCoefficients.one_le_coefficient_energy
#print axioms Erdos4.DivisorSlices.slice_energy_le
#print axioms Erdos4.LocalFourier.weighted_twistedMatrix_le
#print axioms Erdos4.ConductorDecay.norm_contractedTwist_le
#print axioms Erdos4.ConductorSupport.tensorForm_eq_zero_of_large_conductor
#print axioms Erdos4.TensorMoments.coefficient_moment_factorization
#print axioms Erdos4.RootStates.twisted_rootState_matrix
#print axioms Erdos4.AnchorRoots.rootState_eq_some_iff
#print axioms Erdos4.LocalCharacterMatrix.weighted_characterMatrix_le
#print axioms Erdos4.RestrictedTensor.tensorForm_mixed
#print axioms Erdos4.ProductCharacterMatrix.fourierCoefficient_eq_zero_of_large_conductor
#print axioms Erdos4.FourierDecay.norm_fourierCoefficient_le
#print axioms Erdos4.UnitFourier.raw_eq_density_mul_coefficient
#print axioms Erdos4.UnitFourier.principal_coefficient_eq_restrictedForm
#print axioms Erdos4.UnitFourier.norm_coefficient_le
#print axioms Erdos4.UnitFourier.coefficient_eq_zero_of_large_conductor
#print axioms Erdos4.CoefficientMass.occupied_label_energy_le
#print axioms Erdos4.CoefficientMass.reciprocalMass_energy_le
#print axioms Erdos4.CoefficientMass.excessive_mass_energy_le
#print axioms Erdos4.ProjectionKernel.tensor_form_sq_le_energy
#print axioms Erdos4.IdealProjection.weighted_kernel_formula
#print axioms Erdos4.IdealAction.action_coefficient_eq_ratio
#print axioms Erdos4.ProjectionNormals.normal_difference_some_le
#print axioms Erdos4.LocalProjectionComparison.local_comparison_le
#print axioms Erdos4.ProjectionSliceBound.norm_actual_slice_sum_le
#print axioms Erdos4.ProjectionReplacement.norm_single_replacement_le
#print axioms Erdos4.ProductProjectionComparison.ideal_form_sub_error_le_true
#print axioms Erdos4.CutoffSimplex.completion_parameter_eq
#print axioms Erdos4.ReciprocalTail.exists_reciprocal_square_cutoff
#print axioms Erdos4.HarmonicUniform.fixed_modulus_uniform_real
#print axioms Erdos4.ProfileSmooth.variation_le_one
#print axioms Erdos4.ProfileAbel.weighted_error_le
#print axioms Erdos4.WeightedHarmonic.uniform_asymptotic
#print axioms Erdos4.ArithmeticFibers.coordinateDivisor_completion
#print axioms Erdos4.ArithmeticFibers.totalDivisor_completion
#print axioms Erdos4.ArithmeticFibers.fiberWeight_completion
#print axioms Erdos4.FiberLowerBound.primeWindow_admissibleSum_le
#print axioms Erdos4.FiberExclusions.divisible_sum_le
#print axioms Erdos4.FiberExclusions.primeWindow_weightedSum_sub_mass_le
#print axioms Erdos4.FiberAsymptotic.eventually_fiber_lower
#print axioms Erdos4.PrincipalLowerBound.sum_forms_lower
#print axioms Erdos4.PrincipalGain.exists_eventual_principal_lower
#print axioms weak_mertens_third_upper_all
#print axioms Erdos4.EulerDensity.exists_arbitrary_principal_gain
#print axioms Erdos4.ProductFourierInversion.actual_coefficient_inversion
#print axioms Erdos4.ProductCharacterEncoding.entry_injective
#print axioms Erdos4.ProductCharacterEncoding.entry_valid
#print axioms Erdos4.ProductCharacterEncoding.conductor_le_support
#print axioms Erdos4.ProductCharacterEncoding.entry_value_eq_product
#print axioms Erdos4.FiniteCharacterSupport.card_smallCharacters_le
#print axioms Erdos4.FiniteCharacterSupport.coefficient_zero_outside
#print axioms Erdos4.FiniteCharacterSupport.norm_nonprincipal_coefficient_le
#print axioms Erdos4.ProductPrimeMeanSquare.actual_source_error_mean_square
#print axioms Erdos4.AnchoredFourierAverage.square_eq_realSquare
#print axioms Erdos4.AnchoredFourierAverage.source_average_eq
#print axioms Erdos4.AnchoredFourierAverage.source_average_mean_square
#print axioms Erdos4.AffineWeights.shift_mod_injective
#print axioms Erdos4.AffineWeights.weight_anchor
#print axioms Erdos4.LocalIndicatorExpansion.local_expansion
#print axioms Erdos4.LocalIndicatorExpansion.row_bound
#print axioms Erdos4.CutoffMass.mass_le_of_small_tail
#print axioms Erdos4.DivisibilityExpansion.expansion_eq
#print axioms Erdos4.DivisibilityExpansion.sum_abs_coefficient_le_mass
#print axioms Erdos4.WindowWeightBound.exists_uniform_bounds
#print axioms Erdos4.AffineResidueMean.mean_expansion_sq
#print axioms BoundedGaps.Maynard.intervalModEqCardError_abs_le_one
#print axioms Erdos4.CoprimeResidueCount.density_error_le
#print axioms Erdos4.IndicatorProducts.coefficient_joint_sum_eq_energy
#print axioms Erdos4.LabelResidueClass.evaluation_is_residue
#print axioms Erdos4.LabelResidueClass.count_error_le
#print axioms Erdos4.AffineNormalization.normalizer_error_le
#print axioms Erdos4.WindowNormalization.exists_uniform_normalization
#print axioms Erdos4.NormalizationAsymptotic.exists_eventual_probability_bounds
#print axioms Erdos4.AffineSourceAverage.discrepancy_mean_square
#print axioms Erdos4.ExposureBounds.badTargets_card_le
#print axioms Erdos4.ExposureBounds.exposure_lower
#print axioms Erdos4.RandomResidueSieve.survivalMass_eq
#print axioms Erdos4.RandomResidueSieve.sum_conditionalWeight
#print axioms Erdos4.RandomResidueSieve.conditional_survivalMass
#print axioms Erdos4.LocalSurvivalRatios.local_modulus_ratio_error
#print axioms Erdos4.LocalSurvivalRatios.product_ratio_error_le
#print axioms Erdos4.CollisionModuli.collision_reciprocal_le
#print axioms Erdos4.JointSurvivalEstimate.uniform_relative_error_le
#print axioms Erdos4.JointSurvivalAsymptotic.eventually_uniform_relative_error
#print axioms Erdos4.AffineTuples.intersection_eq_singleton
#print axioms Erdos4.TupleCollisionMass.mixed_collision_mass_le
#print axioms Erdos4.TupleCollisionMass.anchor_sum_eq_hitMass
#print axioms Erdos4.ConditionalTupleMoments.conditional_relative_error
#print axioms Erdos4.ConditionalTupleMoments.firstMoment_bounds
#print axioms Erdos4.ConditionalProductMoments.mean_product_expansions
#print axioms Erdos4.ConditionalProductMoments.mixed_product_le
#print axioms Erdos4.AggregatedTupleMoments.secondMoment_le
#print axioms Erdos4.AggregatedTupleMoments.mixedMoment_le
#print axioms Erdos4.TupleSurvivalBounds.eventually_accurate
#print axioms Erdos4.TupleSurvivalBounds.three_moments
#print axioms Erdos4.ConditionalCovering.mean_miss_le_three_moments
#print axioms Erdos4.CoveringError.moment_ratio_bound
#print axioms Erdos4.CoveringError.mean_miss_le_explicit
#print axioms Erdos4.ProbabilityFallback.sum_probability
#print axioms Erdos4.ProbabilityFallback.miss_mass_le
#print axioms Erdos4.CenterChoice.assignment_miss_mass_le
#print axioms Erdos4.TwoStageSelection.exists_choices
#print axioms Erdos4.SelectedResidueCover.exists_cover_with_reserve
#print axioms Erdos4.CoverBudget.exists_cover_of_exceptional_budget
#print axioms weak_mertens_third_lower_all
#print axioms Erdos4.EulerDensityBounds.exists_uniform_density_upper
#print axioms Erdos4.EulerDensityBounds.exists_window_density_bounds
#print axioms Erdos4.ChebyshevIntervals.eventually_primeInterval_lower
#print axioms Erdos4.ZeroSieveResidual.survivors_subset
#print axioms Erdos4.ZeroSieveResidual.exists_zero_cover
#print axioms Erdos4.PlainSmoothBound.exists_uniform_plain_smooth_bound
#print axioms Erdos4.OuterRay.eventually_small_le_smooth
#print axioms Erdos4.OuterDensity.exists_survival_density_bounds
#print axioms Erdos4.OuterAccuracy.eventually_random_accuracy
#print axioms Erdos4.OuterPrimeSupply.exists_prime_supply
#print axioms Erdos4.CompleteCover.exists_cover_with_extra
#print axioms Erdos4.CompleteCover.exists_ray_cover_of_budget
#print axioms Erdos4.PrimeExposure.exists_exceptional_targets
#print axioms Erdos4.DoubleMeanSquare.exceptional_targets_card_le
#print axioms Erdos4.GramBound.weighted_mean_square_le
#print axioms Erdos4.GramBound.transform_duality
#print axioms Erdos4.CharacterCorrelations.primitive_correlation_multiples_le
#print axioms Erdos4.SieveMajorant.sum_weight_le
#print axioms Erdos4.SelbergCoefficients.sum_abs_coefficient_le
#print axioms Erdos4.UpperMobiusInversion.coefficient_transform
#print axioms Erdos4.SelbergOptimization.sum_weight_coefficient_le
#print axioms Erdos4.SelbergHarmonicMass.eventually_sum_weight_le
#print axioms Erdos4.PrimitiveCharacterFamily.card_family_le_square
#print axioms Erdos4.PrimitiveCharacterFamily.prime_mean_square_le
#print axioms Erdos4.PrimeMeanSquare.eventually_prime_mean_square
#print axioms Erdos4.PrimeMeanSquare.eventually_prime_mean_square_dual
#print axioms Erdos4.erdos4For_of_residue_covers

#print axioms Erdos4.WindowPrimeExposure.exists_exceptional_targets
#print axioms Erdos4.ExposureConstants.exists_decay
#print axioms Erdos4.ExposureParameters.exists_parameters
#print axioms Erdos4.ExposureParameters.exposure_eq_hitMass
#print axioms Erdos4.OuterExposure.exists_parameters
#print axioms Erdos4.OuterAtomDecay.eventually_power_atom_small
#print axioms Erdos4.CoveringScalars.collision_ratio_le
#print axioms Erdos4.OuterNoncoverage.exists_parameters
#print axioms Erdos4.OuterCleanup.eventually_small_prime_cost
#print axioms Erdos4.OuterCleanup.eventually_length_le_zeroCutoff
#print axioms Erdos4.OuterCleanup.exists_negligible_smooth
#print axioms Erdos4.OuterCover.exists_arbitrary_length_covers
#print axioms Erdos4.OuterLogBounds.upper_logs
#print axioms Erdos4.OuterLogBounds.lower_third_log
#print axioms Erdos4.OuterThreshold.threshold_le
#print axioms Erdos4.OuterThreshold.eventually_log_endpoint
#print axioms Erdos4.erdos4

example (C : ℝ) (hC : 0 < C) :
    {n : ℕ | (Nat.nth Nat.Prime (n + 1) : ℝ) - Nat.nth Nat.Prime n >
      C * Real.log (Real.log (n : ℝ)) * Real.log (Real.log (Real.log (Real.log (n : ℝ)))) /
        Real.log (Real.log (Real.log (n : ℝ))) ^ 2 * Real.log (n : ℝ)}.Infinite :=
  Erdos4.erdos4 C hC
