name = "ComparatorChallenges"
version = "0.1.0"
defaultTargets = [
  "ComparatorChallenges",
  "BorisBukhChallenges",
  "HundredTheoremsChallenges",
  "MathOverflowChallenges",
  "WikipediaChallenges"
]

[[require]]
name = "Comparator"
git = "https://github.com/leanprover/comparator.git"
rev = "v4.33.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0"

[[lean_lib]]
name = "ComparatorChallenges"
srcDir = "ErdosProblems"
roots = [
  "Erdos16",
  "Erdos24",
  "Erdos26",
  "Erdos31",
  "Erdos34",
  "Erdos38",
  "Erdos42",
  "Erdos45",
  "Erdos46",
  "Erdos47",
  "Erdos56",
  "Erdos93",
  "Erdos94",
  "Erdos105",
  "Erdos106",
  "Erdos115",
  "Erdos119",
  "Erdos123",
  "Erdos124b",
  "Erdos125",
  "Erdos134",
  "Erdos150",
  "Erdos154",
  "Erdos164",
  "Erdos178",
  "Erdos189",
  "Erdos194",
  "Erdos198",
  "Erdos199",
  "Erdos202",
  "Erdos204",
  "Erdos205",
  "Erdos206",
  "Erdos214",
  "Erdos221",
  "Erdos224",
  "Erdos226",
  "Erdos229",
  "Erdos237",
  "Erdos246",
  "Erdos250",
  "Erdos253",
  "Erdos258",
  "Erdos259",
  "Erdos264",
  "Erdos264b",
  "Erdos266",
  "Erdos268",
  "Erdos275",
  "Erdos280",
  "Erdos281",
  "Erdos283",
  "Erdos283b",
  "Erdos290",
  "Erdos291b",
  "Erdos296",
  "Erdos298",
  "Erdos299",
  "Erdos303",
  "Erdos314",
  "Erdos315",
  "Erdos316",
  "Erdos331",
  "Erdos333",
  "Erdos337",
  "Erdos347",
  "Erdos350",
  "Erdos351",
  "Erdos355",
  "Erdos363",
  "Erdos367b",
  "Erdos368b",
  "Erdos369",
  "Erdos370",
  "Erdos379",
  "Erdos392",
  "Erdos397",
  "Erdos399",
  "Erdos401",
  "Erdos418",
  "Erdos419",
  "Erdos424",
  "Erdos426",
  "Erdos427",
  "Erdos429",
  "Erdos433",
  "Erdos434",
  "Erdos435",
  "Erdos443",
  "Erdos447",
  "Erdos453",
  "Erdos457",
  "Erdos459",
  "Erdos469",
  "Erdos476",
  "Erdos481",
  "Erdos484",
  "Erdos485b",
  "Erdos487",
  "Erdos490",
  "Erdos493",
  "Erdos497",
  "Erdos498",
  "Erdos499",
  "Erdos502",
  "Erdos505",
  "Erdos519",
  "Erdos532",
  "Erdos537",
  "Erdos540",
  "Erdos541",
  "Erdos582",
  "Erdos613",
  "Erdos618",
  "Erdos621",
  "Erdos639",
  "Erdos645",
  "Erdos646",
  "Erdos648",
  "Erdos649",
  "Erdos650",
  "Erdos658",
  "Erdos659",
  "Erdos666",
  "Erdos674",
  "Erdos678",
  "Erdos692",
  "Erdos694",
  "Erdos698",
  "Erdos707",
  "Erdos728",
  "Erdos728p",
  "Erdos729",
  "Erdos741",
  "Erdos741b",
  "Erdos751",
  "Erdos753",
  "Erdos756",
  "Erdos760",
  "Erdos762",
  "Erdos775",
  "Erdos785",
  "Erdos794",
  "Erdos798",
  "Erdos818",
  "Erdos844",
  "Erdos845",
  "Erdos846",
  "Erdos862",
  "Erdos866b",
  "Erdos867",
  "Erdos871",
  "Erdos897",
  "Erdos898",
  "Erdos904",
  "Erdos905",
  "Erdos907",
  "Erdos914",
  "Erdos923",
  "Erdos947",
  "Erdos958",
  "Erdos964",
  "Erdos966",
  "Erdos967",
  "Erdos974",
  "Erdos990",
  "Erdos990b",
  "Erdos997",
  "Erdos1000",
  "Erdos1007",
  "Erdos1008",
  "Erdos1014",
  "Erdos1022",
  "Erdos1023",
  "Erdos1026",
  "Erdos1028",
  "Erdos1034",
  "Erdos1036",
  "Erdos1037",
  "Erdos1043",
  "Erdos1044",
  "Erdos1047",
  "Erdos1048",
  "Erdos1048b",
  "Erdos1051",
  "Erdos1056b",
  "Erdos1067",
  "Erdos1071",
  "Erdos1080",
  "Erdos1090",
  "Erdos1095b",
  "Erdos1098",
  "Erdos1100b",
  "Erdos1102",
  "Erdos1121",
  "Erdos1125",
  "Erdos1126",
  "Erdos1136",
  "Erdos1138",
  "Erdos1141",
  "Erdos1148",
  "Erdos1187b",
  "Erdos1190",
  "Erdos1193",
  "Erdos1196",
  "Erdos1197",
  "Erdos277",
  "Erdos285",
  "Erdos318",
  "Erdos321",
  "Erdos358",
  "Erdos387",
  "Erdos402",
  "Erdos442",
  "Erdos448",
  "Erdos480",
  "Erdos494",
  "Erdos533",
  "Erdos594",
  "Erdos615",
  "Erdos697",
  "Erdos742",
  "Erdos755",
  "Erdos825",
  "Erdos847",
  "Erdos848",
  "Erdos888",
  "Erdos899",
  "Erdos987",
  "Erdos1092",
  "Erdos1105",
  "Erdos1119",
  "Erdos920",
  "Erdos965",
  "Erdos1064",
  "Erdos1077",
  "Erdos152",
  "Erdos119",
  "Erdos22",
  "Erdos13",
  "Erdos6",
  "Erdos590",
  "Erdos851",
  "Erdos868",
  "Erdos516",
  "Erdos139",
  "Erdos219",
  "Erdos705",
  "Erdos110",

  "Erdos310",

  "Erdos343",

  "Erdos384",

  "Erdos29",

  "Erdos37",

  "Erdos53",

  "Erdos466",

  "Erdos925",

  "Erdos894",

  "Erdos441",

  "Erdos35",

  "Erdos262",

  "Erdos405",

  "Erdos58",

  "Erdos79",

  "Erdos83",

  "Erdos27",

  "Erdos737",

  "Erdos473",

  "Erdos308",

  "Erdos309",

  "Erdos395",

  "Erdos465",

  "Erdos559",

  "Erdos59",

  "Erdos574",

  "Erdos292",

  "Erdos986",

  "Erdos223",

  "Erdos54",

  "Erdos55",

  "Erdos631",

  "Erdos116",

  "Erdos121",

  "Erdos127",

  "Erdos144",

  "Erdos166",

  "Erdos171",

  "Erdos191",

  "Erdos210",

  "Erdos220",

  "Erdos305",

  "Erdos2",

  "Erdos8",

  "Erdos630",

  "Erdos632",

  "Erdos565",

  "Erdos673",

  "Erdos294",

  "Erdos297",

  "Erdos362",

  "Erdos924",

  "Erdos182",

  "Erdos179",

  "Erdos391",

  "Erdos49",

  "Erdos1129",

  "Erdos211",

  "Erdos777",

  "Erdos1213",

  "Erdos1195",

  "Erdos1205",

  "Erdos1198",

  "Erdos95",

  "Erdos1202",

  "Erdos21",

  "Erdos767",

  "Erdos780",

  "Erdos764",

  "Erdos863",

  "Erdos834",

  "Erdos874",

  "Erdos880",

  "Erdos882",

  "Erdos603",

  "Erdos147",

  "Erdos581",

  "Erdos903",

  "Erdos215",

  "Erdos763",

  "Erdos998",

  "Erdos994",

  "Erdos703",

  "Erdos1050",

  "Erdos175",

  "Erdos1216",

  "Erdos652",

  "Erdos895",

  "Erdos641",

  "Erdos1217",

  "Erdos896",

  "Erdos1187",

  "Erdos682",

  "Erdos690",

  "Erdos1019",

  "Erdos758",

  "Erdos1031",

  "Erdos1006",

  "Erdos1025",

  "Erdos1078",

  "Erdos1079",

  "Erdos1099",

  "Erdos1042",

  "Erdos1046",

  "Erdos1114",

  "Erdos63",

  "Erdos57",

  "Erdos72",

  "Erdos622",

  "Erdos752",

  "Erdos781",

  "Erdos877",

  "Erdos1027",

  "Erdos1069",

  "Erdos1076",

  "Erdos1089",

  "Erdos1115",

  "Erdos1021",

  "Erdos1116",

  "Erdos1215",

  "Erdos759",

  "Erdos1024",

  "Erdos636",

  "Erdos869",

  "Erdos900",

  "Erdos133",

  "Erdos771",

  "Erdos607",

  "Erdos549",

  "Erdos800",

  "Erdos992",

  "Erdos605",

  "Erdos732",

  "Erdos286",

  "Erdos356",

  "Erdos437",

  "Erdos926",

  "Erdos1185",

  "Erdos915",

  "Erdos235",

  "Erdos744",

  "Erdos799",

  "Erdos270",

  "Erdos833",

  "Erdos988",

  "Erdos1001",

  "Erdos1147",

  "Erdos113",

  "Erdos255",

  "Erdos284",

  "Erdos300",

  "Erdos339",

  "Erdos543",

  "Erdos553",

  "Erdos578",

  "Erdos807",

  "Erdos832",

  "Erdos444",

  "Erdos449",

  "Erdos546",

  "Erdos637",

  "Erdos651",

  "Erdos842",

  "Erdos991",

  "Erdos230",

  "Erdos440",

  "Erdos438",

  "Erdos808",

  "Erdos1018",

  "Erdos320",

  "Erdos135",

  "Erdos922",

  "Erdos1180",

  "Erdos372",

  "Erdos664",

  "Erdos784",

  "Erdos843",

  "Erdos804",

  "Erdos960",

  "Erdos858",

  "Erdos1015",

  "Erdos482",

  "Erdos754",

  "Erdos542",

  "Erdos586",

  "Erdos185",

  "Erdos190",

  "Erdos772",

  "Erdos511",

  "Erdos861",

  "Erdos1009",

  "Erdos1179",

  "Erdos656",

  "Erdos136",

  "Erdos378",

  "Erdos1118",

  "Erdos140",

  "Erdos186",

  "Erdos225",

  "Erdos921",

  "Erdos948",

  "Erdos570",

  "Erdos981",

  "Erdos1149",

  "Erdos984",

  "Erdos1124",

  "Erdos1161",

  "Erdos1211",

  "Erdos702",

  "Erdos1140",

  "Erdos999",

]

[[lean_lib]]
name = "BorisBukhChallenges"
srcDir = "BorisBukh"
roots = ["BasisSubset"]

[[lean_lib]]
name = "HundredTheoremsChallenges"
srcDir = "HundredTheorems"
roots = ["Theorem8", "Theorem28", "Theorem61", "Theorem84", "Theorem87"]

[[lean_lib]]
name = "MathOverflowChallenges"
srcDir = "MathOverflow"
roots = ["MO420333", "MO508681", "MO509164", "MO509493"]

[[lean_lib]]
name = "WikipediaChallenges"
srcDir = "Wikipedia"
roots = ["CycleDoubleCoverConjecture", "SzemeredisTheorem", "GreenTao"]
