/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/

import Mathlib

/-!
Strong restart for an iid product measure at a natural-number-valued random
time.  Erdős 1166 uses this for finite blocks of walk increments following a
bounded stopping time.
-/

open MeasureTheory
open scoped ENNReal

namespace ProbabilityTheory

variable {X : Type*} [MeasurableSpace X]

/-- The sigma algebra generated by coordinates with index strictly smaller
than `k`. -/
@[instance_reducible] def iidHistory (k : ℕ) : MeasurableSpace (ℕ → X) :=
  ⨆ i : ℕ, ⨆ (_ : i < k),
    MeasurableSpace.comap (fun ω : ℕ → X ↦ ω i) inferInstance

/-- The sigma algebra generated by coordinates with index at least `k`. -/
@[instance_reducible] def iidTail (k : ℕ) : MeasurableSpace (ℕ → X) :=
  ⨆ i : ℕ, ⨆ (_ : k ≤ i),
    MeasurableSpace.comap (fun ω : ℕ → X ↦ ω i) inferInstance

lemma iidHistory_le (k : ℕ) :
    iidHistory (X := X) k ≤ (inferInstance : MeasurableSpace (ℕ → X)) := by
  refine iSup_le fun i ↦ iSup_le fun _ ↦ ?_
  exact Measurable.comap_le (measurable_pi_apply i)

lemma iidTail_le (k : ℕ) :
    iidTail (X := X) k ≤ (inferInstance : MeasurableSpace (ℕ → X)) := by
  refine iSup_le fun i ↦ iSup_le fun _ ↦ ?_
  exact Measurable.comap_le (measurable_pi_apply i)

lemma iidHistory_indep_iidTail (μ : Measure X) [IsProbabilityMeasure μ] (k : ℕ) :
    Indep (iidHistory (X := X) k) (iidTail (X := X) k)
      (Measure.infinitePi fun _ : ℕ ↦ μ) := by
  let P : Measure (ℕ → X) := Measure.infinitePi fun _ : ℕ ↦ μ
  have hi : iIndepFun (fun i : ℕ ↦ fun ω : ℕ → X ↦ ω i) P :=
    iIndepFun_infinitePi (X := fun _ x ↦ x) (fun _ ↦ measurable_id)
  have h := indep_iSup_of_disjoint
    (μ := P)
    (m := fun i : ℕ ↦ MeasurableSpace.comap (fun ω : ℕ → X ↦ ω i) inferInstance)
    (fun i ↦ Measurable.comap_le (measurable_pi_apply i)) hi.iIndep
    (S := {i : ℕ | i < k}) (T := {i : ℕ | k ≤ i})
    (by
      rw [Set.disjoint_left]
      exact fun i hik hki ↦ (Nat.not_lt_of_ge hki) hik)
  simpa [P, iidHistory, iidTail] using h

/-- A block of `m` consecutive coordinates starting at deterministic time
`k`. -/
def iidBlock (k m : ℕ) (ω : ℕ → X) (i : Fin m) : X :=
  ω (k + i)

lemma measurable_iidBlock (k m : ℕ) :
    Measurable (iidBlock (X := X) k m) := by
  apply measurable_pi_lambda
  intro i
  exact measurable_pi_apply (k + (i : ℕ))

lemma measurable_iidBlock_iidTail (k m : ℕ) :
    Measurable[iidTail (X := X) k] (iidBlock (X := X) k m) := by
  let _ : MeasurableSpace (ℕ → X) := iidTail (X := X) k
  apply measurable_pi_lambda
  intro i
  apply measurable_iff_comap_le.mpr
  exact le_iSup_of_le (k + (i : ℕ))
    (le_iSup_of_le (by omega : k ≤ k + (i : ℕ)) le_rfl)

lemma iidBlock_map (μ : Measure X) [IsProbabilityMeasure μ] (k m : ℕ) :
    (Measure.infinitePi fun _ : ℕ ↦ μ).map (iidBlock (X := X) k m) =
      Measure.infinitePi fun _ : Fin m ↦ μ := by
  have hblock : iidBlock (X := X) k m = fun ω i ↦ ω (k + (i : ℕ)) := by
    rfl
  rw [hblock]
  simpa using
    (Measure.map_infinitePi_infinitePi_of_inj
      (P := fun _ : ℕ ↦ μ) (f := fun i : Fin m ↦ k + (i : ℕ))
      (fun i j hij ↦ Fin.ext (Nat.add_left_cancel hij)))

lemma measure_inter_iidBlock_eq_mul
    (μ : Measure X) [IsProbabilityMeasure μ] (k m : ℕ)
    {C : Set (ℕ → X)} (hC : MeasurableSet[iidHistory (X := X) k] C)
    {B : Set (Fin m → X)} (hB : MeasurableSet B) :
    (Measure.infinitePi fun _ : ℕ ↦ μ)
        (C ∩ iidBlock (X := X) k m ⁻¹' B) =
      (Measure.infinitePi fun _ : ℕ ↦ μ) C *
        (Measure.infinitePi fun _ : Fin m ↦ μ) B := by
  let P : Measure (ℕ → X) := Measure.infinitePi fun _ : ℕ ↦ μ
  have hInd : IndepSet C (iidBlock (X := X) k m ⁻¹' B) P :=
    (iidHistory_indep_iidTail μ k).indepSet_of_measurableSet hC
      (measurable_iidBlock_iidTail k m hB)
  rw [hInd.measure_inter_eq_mul]
  congr 1
  rw [← Measure.map_apply (measurable_iidBlock k m) hB, iidBlock_map μ k m]

/-- The `m` coordinates immediately after a natural-number-valued random
time. -/
def iidBlockAfter (τ : (ℕ → X) → ℕ) (m : ℕ) (ω : ℕ → X) (i : Fin m) : X :=
  ω (τ ω + i)

/-- Strong restart for an iid product: if the fiber of `A` at `τ = k` only
depends on coordinates strictly before `k`, then the block starting at `τ`
has fresh product law, independently of `A`. -/
theorem measure_inter_iidBlockAfter_eq_mul
    (μ : Measure X) [IsProbabilityMeasure μ]
    (τ : (ℕ → X) → ℕ) (m : ℕ) (A : Set (ℕ → X))
    (hA : ∀ k, MeasurableSet[iidHistory (X := X) k]
      (A ∩ {ω | τ ω = k}))
    {B : Set (Fin m → X)} (hB : MeasurableSet B) :
    (Measure.infinitePi fun _ : ℕ ↦ μ)
        (A ∩ iidBlockAfter (X := X) τ m ⁻¹' B) =
      (Measure.infinitePi fun _ : ℕ ↦ μ) A *
        (Measure.infinitePi fun _ : Fin m ↦ μ) B := by
  let P : Measure (ℕ → X) := Measure.infinitePi fun _ : ℕ ↦ μ
  let C : ℕ → Set (ℕ → X) := fun k ↦ A ∩ {ω | τ ω = k}
  let D : ℕ → Set (ℕ → X) := fun k ↦
    C k ∩ iidBlock (X := X) k m ⁻¹' B
  let q : ℝ≥0∞ := (Measure.infinitePi fun _ : Fin m ↦ μ) B
  have hC_meas (k : ℕ) : MeasurableSet (C k) := by
    exact iidHistory_le k _ (hA k)
  have hD_meas (k : ℕ) : MeasurableSet (D k) := by
    exact (hC_meas k).inter (measurable_iidBlock k m hB)
  have hC_disj : Pairwise fun i j ↦ Disjoint (C i) (C j) := by
    intro i j hij
    rw [Set.disjoint_left]
    intro ω hωi hωj
    exact hij (hωi.2.symm.trans hωj.2)
  have hD_disj : Pairwise fun i j ↦ Disjoint (D i) (D j) := by
    intro i j hij
    exact (hC_disj hij).mono Set.inter_subset_left Set.inter_subset_left
  have hC_union : (⋃ k, C k) = A := by
    ext ω
    simp only [Set.mem_iUnion, C, Set.mem_inter_iff, Set.mem_ofPred_eq]
    exact ⟨fun h ↦ h.choose_spec.1, fun h ↦ ⟨τ ω, h, rfl⟩⟩
  have hD_union : (⋃ k, D k) =
      A ∩ iidBlockAfter (X := X) τ m ⁻¹' B := by
    ext ω
    constructor
    · intro hω
      rcases Set.mem_iUnion.mp hω with ⟨k, hk⟩
      change ω ∈ C k ∩ iidBlock (X := X) k m ⁻¹' B at hk
      rcases hk with ⟨hωC, hωB⟩
      change ω ∈ A ∩ {ω | τ ω = k} at hωC
      rcases hωC with ⟨hωA, hτ⟩
      refine ⟨hωA, ?_⟩
      have hb : iidBlockAfter (X := X) τ m ω = iidBlock (X := X) k m ω := by
        funext i
        change ω (τ ω + (i : ℕ)) = ω (k + (i : ℕ))
        rw [hτ]
      change iidBlockAfter (X := X) τ m ω ∈ B
      change iidBlock (X := X) k m ω ∈ B at hωB
      rw [hb]
      exact hωB
    · intro hω
      change ω ∈ A ∩ iidBlockAfter (X := X) τ m ⁻¹' B at hω
      rcases hω with ⟨hωA, hωB⟩
      apply Set.mem_iUnion.mpr
      refine ⟨τ ω, ?_⟩
      change ω ∈ C (τ ω) ∩ iidBlock (X := X) (τ ω) m ⁻¹' B
      refine ⟨⟨hωA, rfl⟩, ?_⟩
      have hb : iidBlockAfter (X := X) τ m ω =
          iidBlock (X := X) (τ ω) m ω := by
        rfl
      change iidBlock (X := X) (τ ω) m ω ∈ B
      change iidBlockAfter (X := X) τ m ω ∈ B at hωB
      rw [← hb]
      exact hωB
  calc
    P (A ∩ iidBlockAfter (X := X) τ m ⁻¹' B) = ∑' k, P (D k) := by
      rw [← hD_union, measure_iUnion hD_disj hD_meas]
    _ = ∑' k, P (C k) * q := by
      apply tsum_congr
      intro k
      exact measure_inter_iidBlock_eq_mul μ k m (hA k) hB
    _ = (∑' k, P (C k)) * q := ENNReal.tsum_mul_right
    _ = P A * q := by rw [← measure_iUnion hC_disj hC_meas, hC_union]

/-- Strong restart at a possibly unbounded `WithTop ℕ`-valued time, on a
past event contained in the event that the time is finite.  No bounded
horizon is needed: on `A`, the arbitrary value chosen by `untopA` at `⊤` is
never used. -/
theorem measure_inter_iidBlockAfter_untopA_eq_mul
    (μ : Measure X) [IsProbabilityMeasure μ]
    (τ : (ℕ → X) → WithTop ℕ) (m : ℕ) (A : Set (ℕ → X))
    (hA_finite : A ⊆ {ω | τ ω ≠ ⊤})
    (hA : ∀ k, MeasurableSet[iidHistory (X := X) k]
      (A ∩ {ω | τ ω = k}))
    {B : Set (Fin m → X)} (hB : MeasurableSet B) :
    (Measure.infinitePi fun _ : ℕ ↦ μ)
        (A ∩ iidBlockAfter (X := X) (fun ω ↦ (τ ω).untopA) m ⁻¹' B) =
      (Measure.infinitePi fun _ : ℕ ↦ μ) A *
        (Measure.infinitePi fun _ : Fin m ↦ μ) B := by
  apply measure_inter_iidBlockAfter_eq_mul μ
    (fun ω ↦ (τ ω).untopA) m A ?_ hB
  intro k
  convert hA k using 1
  ext ω
  simp only [Set.mem_inter_iff, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨hωA, hτk⟩
    refine ⟨hωA, ?_⟩
    have hτ_ne_top : τ ω ≠ ⊤ := hA_finite hωA
    have hcoe : ((τ ω).untopA : WithTop ℕ) = τ ω := by
      rw [WithTop.untopA_eq_untop hτ_ne_top]
      exact WithTop.coe_untop _ hτ_ne_top
    calc
      τ ω = ((τ ω).untopA : WithTop ℕ) := hcoe.symm
      _ = (k : WithTop ℕ) := congrArg ((↑) : ℕ → WithTop ℕ) hτk
  · rintro ⟨hωA, hτk⟩
    refine ⟨hωA, ?_⟩
    rw [hτk]
    rfl

/-- In particular, the post-`τ` block has fresh product law conditional on
the event that a possibly unbounded `WithTop ℕ`-valued time is finite. -/
theorem measure_inter_iidBlockAfter_untopA_finite_eq_mul
    (μ : Measure X) [IsProbabilityMeasure μ]
    (τ : (ℕ → X) → WithTop ℕ) (m : ℕ)
    (hτ : ∀ k, MeasurableSet[iidHistory (X := X) k] {ω | τ ω = k})
    {B : Set (Fin m → X)} (hB : MeasurableSet B) :
    (Measure.infinitePi fun _ : ℕ ↦ μ)
        ({ω | τ ω ≠ ⊤} ∩
          iidBlockAfter (X := X) (fun ω ↦ (τ ω).untopA) m ⁻¹' B) =
      (Measure.infinitePi fun _ : ℕ ↦ μ) {ω | τ ω ≠ ⊤} *
        (Measure.infinitePi fun _ : Fin m ↦ μ) B := by
  apply measure_inter_iidBlockAfter_untopA_eq_mul μ τ m {ω | τ ω ≠ ⊤}
  · exact fun _ hω ↦ hω
  · intro k
    convert hτ k using 1
    ext ω
    simp only [Set.mem_inter_iff, Set.mem_ofPred_eq]
    constructor
    · exact fun hω ↦ hω.2
    · intro hω
      refine ⟨?_, hω⟩
      rw [hω]
      exact WithTop.coe_ne_top
  · exact hB

end ProbabilityTheory
