/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import Mathlib
import Util.Density
import ErdosProblems.Erdos697.Erdos697CRTModel
import ErdosProblems.Erdos697.Erdos697PrimeWindow
import ErdosProblems.Erdos697.Erdos697Cover
import ErdosProblems.Erdos697.Erdos697Smooth
import ErdosProblems.Erdos697.Erdos697UpperBound
import ErdosProblems.Erdos694

/-!
# Erdős Problem 697

For `m : ℕ` and `α : ℝ`, let `divisorSet m α` be the natural numbers
divisible by a `d ≡ 1 (mod m)` with `1 < d < exp (m ^ α)`.  We prove that
this set has a natural density and formalize Hall's sharp transition at
`1 / log 2`.

The hypotheses in the two limit declarations in the upstream
`formal-conjectures` file are reversed.  The corrected directions below
agree with its prose and with Hall's theorem: the limit is zero below the
critical exponent and one above it.
-/

open Filter Set Real
open scoped Topology

namespace Erdos697

noncomputable section

/-! ## Finite unions of sets of multiples -/

/-- The positive multiples of `a`. -/
private def positiveMultiples (a : ℕ) : Set ℕ := {n | 0 < n ∧ a ∣ n}

/-- The positive multiples generated by a finite set. -/
private def finitePositiveMultiples (s : Finset ℕ) : Set ℕ :=
  {n | 0 < n ∧ ∃ a ∈ s, a ∣ n}

theorem erdos_697 :
    ∃ β : ℝ, 1 < β ∧
      (∀ α : ℝ, α < β → Tendsto (fun m : ℕ => δ m α) atTop (𝓝 0)) ∧
      (∀ α : ℝ, β < α → Tendsto (fun m : ℕ => δ m α) atTop (𝓝 1)) := by
  sorry

