import Mathlib

/-!
# Erdős Problem 697

For `m : ℕ` and `α : ℝ`, let `divisorSet m α` be the natural numbers
divisible by a `d ≡ 1 (mod m)` with `1 < d < exp (m ^ α)`.  We prove that
this set has a natural density and formalize Hall's sharp transition at
`1 / log 2`.

The hypotheses in the two limit declarations in the upstream
`formal-conjectures` file are reversed.  The corrected directions below
agree with its prose and with Hall's theorem: the limit is zero below the
critical exponent and one above it.
-/

open Filter Set Real
open scoped Topology

namespace Set

@[inline]
noncomputable abbrev partialDensity {β : Type*} [Preorder β] [LocallyFiniteOrderBot β]
    (S : Set β) (A : Set β := Set.univ) (b : β) : ℝ :=
  ((S ∩ A) ∩ Iio b).ncard / (A ∩ Iio b).ncard

def HasDensity {β : Type*} [Preorder β] [LocallyFiniteOrderBot β]
    (S : Set β) (α : ℝ) (A : Set β := Set.univ) : Prop :=
  Tendsto (fun (b : β) => S.partialDensity A b) atTop (𝓝 α)

end Set

namespace Erdos697

noncomputable section

/-! ## Finite unions of sets of multiples -/

/-- The positive multiples of `a`. -/
private def positiveMultiples (a : ℕ) : Set ℕ := {n | 0 < n ∧ a ∣ n}

/-- The positive multiples generated by a finite set. -/
private def finitePositiveMultiples (s : Finset ℕ) : Set ℕ :=
  {n | 0 < n ∧ ∃ a ∈ s, a ∣ n}


@[simp]
private theorem mem_positiveMultiples {a n : ℕ} :
    n ∈ positiveMultiples a ↔ 0 < n ∧ a ∣ n := Iff.rfl

@[simp]
private theorem mem_finitePositiveMultiples {s : Finset ℕ} {n : ℕ} :
    n ∈ finitePositiveMultiples s ↔ 0 < n ∧ ∃ a ∈ s, a ∣ n := Iff.rfl

@[simp]
private theorem finitePositiveMultiples_empty :
    finitePositiveMultiples ∅ = ∅ := by
  ext n
  simp

private theorem finitePositiveMultiples_insert (a : ℕ) (s : Finset ℕ) :
    finitePositiveMultiples (insert a s) =
      positiveMultiples a ∪ finitePositiveMultiples s := by
  ext n
  simp only [mem_finitePositiveMultiples, Finset.mem_insert,
    mem_positiveMultiples, Set.mem_union]
  aesop

private theorem positiveMultiples_inter_finitePositiveMultiples
    (a : ℕ) (s : Finset ℕ) :
    positiveMultiples a ∩ finitePositiveMultiples s =
      finitePositiveMultiples (s.image (Nat.lcm a)) := by
  ext n
  constructor
  · rintro ⟨⟨hn, han⟩, ⟨_, b, hb, hbn⟩⟩
    exact ⟨hn, a.lcm b, Finset.mem_image.mpr ⟨b, hb, rfl⟩,
      Nat.lcm_dvd_iff.mpr ⟨han, hbn⟩⟩
  · rintro ⟨hn, c, hc, hcn⟩
    obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hc
    exact ⟨⟨hn, (Nat.lcm_dvd_iff.mp hcn).1⟩,
      ⟨hn, b, hb, (Nat.lcm_dvd_iff.mp hcn).2⟩⟩

/-- Inclusion-exclusion transfers natural densities to a union. -/
private theorem hasDensity_union_of_inter {S T : Set ℕ} {dS dT dI : ℝ}
    (hS : S.HasDensity dS) (hT : T.HasDensity dT)
    (hI : (S ∩ T).HasDensity dI) :
    (S ∪ T).HasDensity (dS + dT - dI) := by
  rw [Set.HasDensity] at hS hT hI ⊢
  apply (hS.add hT).sub hI |>.congr'
  filter_upwards with n
  simp only [Set.partialDensity, Set.inter_univ, Set.univ_inter]
  have hcard := Set.ncard_union_add_ncard_inter
    (S ∩ Set.Iio n) (T ∩ Set.Iio n)
  have hunion : (S ∪ T) ∩ Set.Iio n =
      (S ∩ Set.Iio n) ∪ (T ∩ Set.Iio n) := by aesop
  have hinter : (S ∩ T) ∩ Set.Iio n =
      (S ∩ Set.Iio n) ∩ (T ∩ Set.Iio n) := by aesop
  rw [hunion, hinter]
  rw [div_eq_mul_inv, div_eq_mul_inv, div_eq_mul_inv, div_eq_mul_inv]
  have hcardR :
      ((S ∩ Set.Iio n ∪ T ∩ Set.Iio n).ncard : ℝ) +
          ((S ∩ Set.Iio n ∩ (T ∩ Set.Iio n)).ncard : ℝ) =
        ((S ∩ Set.Iio n).ncard : ℝ) +
          ((T ∩ Set.Iio n).ncard : ℝ) := by
    exact_mod_cast hcard
  linear_combination -hcardR * (((Set.Iio n).ncard : ℝ)⁻¹)

/-- A bounded-error linear count has the expected limiting density. -/
private theorem hasDensity_of_counting_error
    (S : Set ℕ) (c C : ℝ)
    (h : ∀ n, |((S ∩ Set.Iio n).ncard : ℝ) - c * n| ≤ C) :
    S.HasDensity c := by
  rw [Set.HasDensity]
  have hzero : Tendsto
      (fun n : ℕ => (((S ∩ Set.Iio n).ncard : ℝ) - c * n) / n)
      atTop (𝓝 0) := by
    exact squeeze_zero_norm
      (fun n => by
        simpa [abs_div] using
          div_le_div_of_nonneg_right (h n) (Nat.cast_nonneg n))
      (tendsto_const_nhds.div_atTop tendsto_natCast_atTop_atTop)
  simpa only [zero_add] using (hzero.add_const c).congr' (by
    filter_upwards [Filter.eventually_gt_atTop 0] with n hn
    simp only [Set.partialDensity, Set.inter_univ, Set.univ_inter]
    have hIio : (Set.Iio n).ncard = n := by simp
    rw [hIio]
    field_simp
    ring)

private theorem singleton_zero_hasDensity : ({0} : Set ℕ).HasDensity 0 := by
  apply hasDensity_of_counting_error _ _ 1
  intro n
  simp only [zero_mul, sub_zero, Nat.cast_nonneg, abs_of_nonneg]
  by_cases hn : n = 0
  · subst n
    simp
  · have hnpos : 0 < n := Nat.pos_of_ne_zero hn
    have hset : ({0} : Set ℕ) ∩ Set.Iio n = {0} := by
      ext x
      simp [hnpos]
    rw [hset]
    simp

/-- The positive multiples of a positive integer have density `1 / a`. -/
private theorem positiveMultiples_hasDensity {a : ℕ} (ha : 0 < a) :
    (positiveMultiples a).HasDensity (1 / (a : ℝ)) := by
  apply hasDensity_of_counting_error _ _ 2
  intro n
  rcases n.eq_zero_or_pos with rfl | hn
  · simp [positiveMultiples]
  have hcard :
      (positiveMultiples a ∩ Set.Iio n).ncard = (n - 1) / a := by
    rw [show positiveMultiples a ∩ Set.Iio n =
        ↑((Finset.Ioc 0 (n - 1)).filter (fun m => a ∣ m)) by
      ext m
      simp only [Set.mem_inter_iff, mem_positiveMultiples, Set.mem_Iio,
        Finset.mem_coe, Finset.mem_filter, Finset.mem_Ioc]
      omega]
    simp only [Set.ncard_coe_finset]
    exact Nat.Ioc_filter_dvd_card_eq_div (n - 1) a
  rw [hcard]
  have hdivle : (((n - 1) / a : ℕ) : ℝ) ≤ ((n - 1 : ℕ) : ℝ) / a :=
    Nat.cast_div_le
  have hdivlower : ((n - 1 : ℕ) : ℝ) / a - 1 <
      (((n - 1) / a : ℕ) : ℝ) := by
    have hfloorNat : n - 1 < ((n - 1) / a + 1) * a :=
      (Nat.div_lt_iff_lt_mul ha).mp (by omega)
    have haR : (0 : ℝ) < a := by exact_mod_cast ha
    rw [sub_lt_iff_lt_add, div_lt_iff₀ haR]
    exact_mod_cast hfloorNat
  have hnR : (0 : ℝ) < n := by exact_mod_cast hn
  have haR : (0 : ℝ) < a := by exact_mod_cast ha
  have haOne : (1 : ℝ) ≤ a := by exact_mod_cast ha
  have hainvle : (1 : ℝ) / a ≤ 1 := by
    exact (div_le_one₀ haR).mpr haOne
  have hnsub : ((n - 1 : ℕ) : ℝ) = n - 1 := by
    rw [Nat.cast_sub (Nat.one_le_iff_ne_zero.mpr hn.ne')]
    norm_num
  rw [hnsub] at hdivle hdivlower
  have hnonpos : (((n - 1) / a : ℕ) : ℝ) -
      1 / (a : ℝ) * n ≤ 0 := by
    have hqle : (((n - 1) / a : ℕ) : ℝ) ≤ (n : ℝ) / a :=
      hdivle.trans (div_le_div_of_nonneg_right (by linarith) haR.le)
    simpa [div_eq_mul_inv, one_div, mul_comm] using sub_nonpos.mpr hqle
  rw [abs_of_nonpos hnonpos]
  have hsplit : (n - 1 : ℝ) / a = n / a - 1 / a := by ring
  rw [hsplit] at hdivlower
  have hlower : (n : ℝ) / a - 2 < (((n - 1) / a : ℕ) : ℝ) := by
    linarith
  have hmul : (n : ℝ) / a = 1 / (a : ℝ) * n := by ring
  rw [← hmul]
  linarith

/-- Every finite union of sets of positive multiples has a natural density. -/
private theorem finitePositiveMultiples_hasDensity (s : Finset ℕ)
    (hpos : ∀ a ∈ s, 0 < a) :
    ∃ d : ℝ, (finitePositiveMultiples s).HasDensity d := by
  classical
  induction hcard : s.card using Nat.strong_induction_on generalizing s with
  | h k ih =>
      by_cases hs : s = ∅
      · subst s
        exact ⟨0, by simp [Set.HasDensity, finitePositiveMultiples_empty,
          Set.partialDensity]⟩
      · obtain ⟨a, ha⟩ := s.nonempty_iff_ne_empty.mpr hs
        let t := s.erase a
        have htcard : t.card < k := by
          rw [← hcard]
          exact Finset.card_erase_lt_of_mem ha
        have htpos : ∀ b ∈ t, 0 < b :=
          fun b hb => hpos b (Finset.mem_of_mem_erase hb)
        obtain ⟨dt, hdt⟩ := ih t.card htcard t htpos rfl
        let u := t.image (Nat.lcm a)
        have hucard : u.card < k := Finset.card_image_le.trans_lt htcard
        have hupos : ∀ b ∈ u, 0 < b := by
          intro b hb
          obtain ⟨c, hc, rfl⟩ := Finset.mem_image.mp hb
          exact Nat.lcm_pos (hpos a ha) (htpos c hc)
        obtain ⟨du, hdu⟩ := ih u.card hucard u hupos rfl
        have haDensity := positiveMultiples_hasDensity (hpos a ha)
        have hinter :
            (positiveMultiples a ∩ finitePositiveMultiples t).HasDensity du := by
          simpa [u, positiveMultiples_inter_finitePositiveMultiples] using hdu
        refine ⟨1 / (a : ℝ) + dt - du, ?_⟩
        rw [show s = insert a t by simp [t, ha]]
        rw [finitePositiveMultiples_insert]
        exact hasDensity_union_of_inter haDensity hdt hinter

/-- All (including zero) multiples generated by a finite set. -/
private def finiteMultiples (s : Finset ℕ) : Set ℕ :=
  {n | ∃ a ∈ s, a ∣ n}

private theorem finiteMultiples_hasDensity_of_positiveDensity (s : Finset ℕ)
    (hs : s.Nonempty) {d : ℝ}
    (hd : (finitePositiveMultiples s).HasDensity d) :
    (finiteMultiples s).HasDensity d := by
  have hinter : (({0} : Set ℕ) ∩ finitePositiveMultiples s).HasDensity 0 := by
    have : ({0} : Set ℕ) ∩ finitePositiveMultiples s = ∅ := by
      ext n
      simp [finitePositiveMultiples]
    rw [this]
    simp [Set.HasDensity, Set.partialDensity]
  have hunion := hasDensity_union_of_inter singleton_zero_hasDensity hd hinter
  have hset : finiteMultiples s = ({0} : Set ℕ) ∪ finitePositiveMultiples s := by
    ext n
    simp only [finiteMultiples, Set.mem_ofPred_eq, Set.mem_union, Set.mem_singleton_iff,
      mem_finitePositiveMultiples]
    constructor
    · rintro ⟨a, ha, hadvd⟩
      rcases n.eq_zero_or_pos with rfl | hn
      · exact Or.inl rfl
      · exact Or.inr ⟨hn, a, ha, hadvd⟩
    · rintro (rfl | ⟨hn, a, ha, hadvd⟩)
      · obtain ⟨a, ha⟩ := hs
        exact ⟨a, ha, dvd_zero a⟩
      · exact ⟨a, ha, hadvd⟩
  rw [hset]
  simpa using hunion

private theorem finiteMultiples_hasDensity (s : Finset ℕ)
    (hpos : ∀ a ∈ s, 0 < a) :
    ∃ d : ℝ, (finiteMultiples s).HasDensity d := by
  classical
  by_cases hs : s = ∅
  · subst s
    exact ⟨0, by simp [finiteMultiples, Set.HasDensity, Set.partialDensity]⟩
  obtain ⟨d, hd⟩ := finitePositiveMultiples_hasDensity s hpos
  exact ⟨d, finiteMultiples_hasDensity_of_positiveDensity s
    (s.nonempty_iff_ne_empty.mpr hs) hd⟩

/-! ## The divisor set in Problem 697 -/

/-- The finite set of eligible divisors. -/
def eligibleDivisors (m : ℕ) (α : ℝ) : Finset ℕ :=
  (Finset.range (Nat.ceil (Real.exp (m ^ α)))).filter fun d =>
    d ≡ 1 [MOD m] ∧ (d : ℝ) ∈ Set.Ioo 1 (Real.exp (m ^ α))

/-- The set whose density is denoted by `δ(m, α)`. -/
def divisorSet (m : ℕ) (α : ℝ) : Set ℕ :=
  {n : ℕ | ∃ d, d ≡ 1 [MOD m] ∧
    (d : ℝ) ∈ Set.Ioo 1 (Real.exp (m ^ α)) ∧ d ∣ n}

theorem divisorSet_eq_finiteMultiples (m : ℕ) (α : ℝ) :
    divisorSet m α = finiteMultiples (eligibleDivisors m α) := by
  ext n
  constructor
  · rintro ⟨d, hdmod, hdIoo, hdn⟩
    refine ⟨d, ?_, hdn⟩
    simp only [eligibleDivisors, Finset.mem_filter, Finset.mem_range]
    exact ⟨Nat.lt_ceil.mpr hdIoo.2, hdmod, hdIoo⟩
  · rintro ⟨d, hd, hdn⟩
    simp only [eligibleDivisors, Finset.mem_filter, Finset.mem_range] at hd
    exact ⟨d, hd.2.1, hd.2.2, hdn⟩

/-- The density in the definition of Problem 697 exists. -/
theorem density_exists (m : ℕ) (α : ℝ) :
    ∃ d, (divisorSet m α).HasDensity d := by
  rw [divisorSet_eq_finiteMultiples]
  apply finiteMultiples_hasDensity
  intro d hd
  have hd' := (Finset.mem_filter.mp hd).2.2.1
  exact_mod_cast (show (0 : ℝ) < d by linarith)

/-- The uniquely determined density of `divisorSet m α`. -/
noncomputable def δ (m : ℕ) (α : ℝ) : ℝ :=
  (density_exists m α).choose

theorem erdos_697 :
    ∃ β : ℝ, 1 < β ∧
      (∀ α : ℝ, α < β → Tendsto (fun m : ℕ => δ m α) atTop (𝓝 0)) ∧
      (∀ α : ℝ, β < α → Tendsto (fun m : ℕ => δ m α) atTop (𝓝 1)) := by
  sorry
