/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/

import ErdosProblems.Erdos387.FiniteWeylInequality
import ErdosProblems.Erdos1149.RestrictedWeyl
import ErdosProblems.Erdos1149.KusminLandau
import ErdosProblems.Erdos1149.MixedDifference
import Mathlib.Analysis.Calculus.Deriv.MeanValue

/-!
# Finite higher differencing for real exponential phases

This is the algebraic higher-differencing layer used for the power phases
in Erdős problem 1149.  Successive complex correlations are identified
with Fourier phases of successive real forward differences, and the finite
Weyl inequality is honestly iterated.  The endpoint is designed to accept
a Kusmin--Landau bound.
-/

namespace Erdos1149

open scoped BigOperators ComplexConjugate

namespace HigherDerivative

/-- The standard real Fourier phase `e(x) = exp(2πix)`. -/
noncomputable def phase (x : ℝ) : ℂ :=
  Real.fourierChar x

@[simp] theorem norm_phase (x : ℝ) : ‖phase x‖ = 1 :=
  Circle.norm_coe _

theorem phase_sub (x y : ℝ) :
    phase (x - y) = phase x * starRingEnd ℂ (phase y) := by
  have hadd (u v : ℝ) : phase (u + v) = phase u * phase v := by
    change ((Real.fourierChar (u + v) : Circle) : ℂ) =
      ((Real.fourierChar u : Circle) : ℂ) * Real.fourierChar v
    rw [AddChar.map_add_eq_mul, Circle.coe_mul]
  have hneg (u : ℝ) : phase (-u) = starRingEnd ℂ (phase u) := by
    change ((Real.fourierChar (-u) : Circle) : ℂ) =
      starRingEnd ℂ ((Real.fourierChar u : Circle) : ℂ)
    rw [AddChar.map_neg_eq_inv, Circle.coe_inv_eq_conj]
  rw [sub_eq_add_neg, hadd, hneg]

/-- Forward difference with displacement `h+1`, matching the convention in
`InverseWeyl.positiveShiftCorrelation`. -/
def positiveDifference (f : ℕ → ℝ) (h x : ℕ) : ℝ :=
  f (x + h + 1) - f x

/-- Iterated positive forward differences. -/
def iteratedPositiveDifference (f : ℕ → ℝ) : List ℕ → ℕ → ℝ
  | [], x => f x
  | h :: hs, x =>
      positiveDifference (iteratedPositiveDifference f hs) h x

@[simp] theorem iteratedPositiveDifference_nil (f : ℕ → ℝ) (x : ℕ) :
    iteratedPositiveDifference f [] x = f x := rfl

@[simp] theorem iteratedPositiveDifference_cons
    (f : ℕ → ℝ) (h : ℕ) (hs : List ℕ) (x : ℕ) :
    iteratedPositiveDifference f (h :: hs) x =
      iteratedPositiveDifference f hs (x + h + 1) -
        iteratedPositiveDifference f hs x := rfl

theorem positiveShiftCorrelation_phase_eq
    (f : ℕ → ℝ) (h x : ℕ) :
    Erdos387.InverseWeyl.positiveShiftCorrelation
        (fun n ↦ phase (f n)) h x =
      phase (positiveDifference f h x) := by
  unfold Erdos387.InverseWeyl.positiveShiftCorrelation positiveDifference
  rw [phase_sub]

/-- Iterating complex correlations commutes with iterating real forward
differences. -/
theorem iteratedPositiveShiftCorrelation_phase_eq
    (f : ℕ → ℝ) (hs : List ℕ) (x : ℕ) :
    Erdos387.InverseWeyl.iteratedPositiveShiftCorrelation
        (fun n ↦ phase (f n)) hs x =
      phase (iteratedPositiveDifference f hs x) := by
  induction hs generalizing x with
  | nil => rfl
  | cons h hs ih =>
      simp only [Erdos387.InverseWeyl.iteratedPositiveShiftCorrelation,
        Erdos387.InverseWeyl.positiveShiftCorrelation,
        iteratedPositiveDifference, positiveDifference, ih]
      rw [phase_sub]

/-- Recursive envelope for `r` finite Weyl steps, when every terminal sum
is at most `terminal`. -/
noncomputable def finiteWeylEnvelope (terminal : ℝ) : ℕ → ℕ → ℝ
  | 0, _P => terminal
  | r + 1, P => Real.sqrt (P + 2 * P * finiteWeylEnvelope terminal r P)

theorem finiteWeylEnvelope_nonneg
    {terminal : ℝ} (hterminal : 0 ≤ terminal) (r P : ℕ) :
    0 ≤ finiteWeylEnvelope terminal r P := by
  induction r with
  | zero => simpa [finiteWeylEnvelope] using hterminal
  | succ r ih =>
      simp only [finiteWeylEnvelope]
      exact Real.sqrt_nonneg _

theorem finiteWeylEnvelope_mono_length
    {terminal : ℝ} (hterminal : 0 ≤ terminal) (r : ℕ) :
    Monotone (finiteWeylEnvelope terminal r) := by
  induction r with
  | zero =>
      intro P Q hPQ
      simp only [finiteWeylEnvelope]
      exact le_rfl
  | succ r ih =>
      intro P Q hPQ
      simp only [finiteWeylEnvelope]
      apply Real.sqrt_le_sqrt
      have hEP : 0 ≤ finiteWeylEnvelope terminal r P :=
        finiteWeylEnvelope_nonneg hterminal r P
      have hE := ih hPQ
      have hcast : (P : ℝ) ≤ Q := by exact_mod_cast hPQ
      nlinarith [mul_le_mul hcast hE hEP (by positivity : (0 : ℝ) ≤ Q)]

/-- Honest iteration of the finite positive-shift Weyl inequality.

The endpoint hypothesis is uniform over histories of length `r` and all
shortened intervals `Q ≤ P`; these are precisely the leaves generated by
the finite Weyl tree. -/
theorem norm_sum_iteratedPhase_le_finiteWeylEnvelope
    (f : ℕ → ℝ) (P r : ℕ) (root : List ℕ)
    {terminal : ℝ} (hterminal_nonneg : 0 ≤ terminal)
    (hterminal : ∀ hs : List ℕ, hs.length = r → ∀ Q ≤ P,
      ‖∑ x ∈ Finset.range Q,
          phase (iteratedPositiveDifference f (hs ++ root) x)‖ ≤ terminal) :
    ‖∑ x ∈ Finset.range P,
        phase (iteratedPositiveDifference f root x)‖ ≤
      finiteWeylEnvelope terminal r P := by
  induction r generalizing P root with
  | zero =>
      simpa only [finiteWeylEnvelope, List.length_eq_zero_iff,
        forall_eq, List.nil_append] using hterminal [] rfl P le_rfl
  | succ r ih =>
      let z : ℕ → ℂ := fun x ↦
        phase (iteratedPositiveDifference f root x)
      have hz : ∀ x, ‖z x‖ = 1 := fun x ↦ norm_phase _
      have hweyl := Erdos387.FiniteWeyl.norm_sum_iteratedCorrelation_sq_le
        z hz [] P
      have hcorr (h y : ℕ) :
          Erdos387.InverseWeyl.iteratedPositiveShiftCorrelation z [h] y =
            phase (iteratedPositiveDifference f (h :: root) y) := by
        change Erdos387.InverseWeyl.positiveShiftCorrelation z h y = _
        simp only [z, Erdos387.InverseWeyl.positiveShiftCorrelation,
          iteratedPositiveDifference, positiveDifference]
        rw [phase_sub]
      have hchild : ∀ h < P,
          ‖∑ y ∈ Finset.range (P - h - 1),
              phase (iteratedPositiveDifference f (h :: root) y)‖ ≤
            finiteWeylEnvelope terminal r P := by
        intro h hh
        have hQP : P - h - 1 ≤ P := by omega
        calc
          ‖∑ y ∈ Finset.range (P - h - 1),
              phase (iteratedPositiveDifference f (h :: root) y)‖ ≤
              finiteWeylEnvelope terminal r (P - h - 1) := by
            apply ih (P := P - h - 1) (root := h :: root)
            intro hs hlen Q hQ
            have ht := hterminal (hs ++ [h]) (by simp [hlen]) Q
              (hQ.trans hQP)
            simpa only [List.append_assoc, List.singleton_append] using ht
          _ ≤ finiteWeylEnvelope terminal r P :=
            finiteWeylEnvelope_mono_length hterminal_nonneg r hQP
      have henergy :
          ‖∑ x ∈ Finset.range P,
              phase (iteratedPositiveDifference f root x)‖ ^ 2 ≤
            P + 2 * P * finiteWeylEnvelope terminal r P := by
        calc
          ‖∑ x ∈ Finset.range P,
              phase (iteratedPositiveDifference f root x)‖ ^ 2 ≤
              P + 2 * ∑ h ∈ Finset.range P,
                ‖∑ y ∈ Finset.range (P - h - 1),
                  phase (iteratedPositiveDifference f (h :: root) y)‖ := by
            simpa only [z,
              Erdos387.InverseWeyl.iteratedPositiveShiftCorrelation,
              positiveShiftCorrelation_phase_eq,
              iteratedPositiveDifference, positiveDifference] using hweyl
          _ ≤ P + 2 * ∑ _h ∈ Finset.range P,
                finiteWeylEnvelope terminal r P := by
            apply add_le_add le_rfl
            apply mul_le_mul_of_nonneg_left _ (by positivity)
            exact Finset.sum_le_sum fun h hh ↦
              hchild h (Finset.mem_range.mp hh)
          _ = P + 2 * P * finiteWeylEnvelope terminal r P := by
            simp only [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
            ring
      simp only [finiteWeylEnvelope]
      have hE : 0 ≤ finiteWeylEnvelope terminal r P :=
        finiteWeylEnvelope_nonneg hterminal_nonneg r P
      have hrad : 0 ≤
          (P : ℝ) + 2 * P * finiteWeylEnvelope terminal r P := by
        positivity
      have hsqrt := Real.sq_sqrt hrad
      have hnorm : 0 ≤ ‖∑ x ∈ Finset.range P,
          phase (iteratedPositiveDifference f root x)‖ := norm_nonneg _
      have hsqrtnonneg := Real.sqrt_nonneg
        ((P : ℝ) + 2 * P * finiteWeylEnvelope terminal r P)
      nlinarith

/-- Root-history version of the finite higher-differencing estimate. -/
theorem norm_phaseSum_le_finiteWeylEnvelope
    (f : ℕ → ℝ) (P r : ℕ)
    {terminal : ℝ} (hterminal_nonneg : 0 ≤ terminal)
    (hterminal : ∀ hs : List ℕ, hs.length = r → ∀ Q ≤ P,
      ‖∑ x ∈ Finset.range Q,
          phase (iteratedPositiveDifference f hs x)‖ ≤ terminal) :
    ‖∑ x ∈ Finset.range P, phase (f x)‖ ≤
      finiteWeylEnvelope terminal r P := by
  simpa only [iteratedPositiveDifference_nil] using
    norm_sum_iteratedPhase_le_finiteWeylEnvelope
      f P r [] hterminal_nonneg (by
        intro hs hlen Q hQ
        simpa only [List.append_nil] using hterminal hs hlen Q hQ)

/-- Shifted-interval form used on dyadic blocks. -/
theorem norm_phaseSum_add_le_finiteWeylEnvelope
    (f : ℕ → ℝ) (a P r : ℕ)
    {terminal : ℝ} (hterminal_nonneg : 0 ≤ terminal)
    (hterminal : ∀ hs : List ℕ, hs.length = r → ∀ Q ≤ P,
      ‖∑ x ∈ Finset.range Q,
          phase (iteratedPositiveDifference (fun n ↦ f (a + n)) hs x)‖ ≤
        terminal) :
    ‖∑ x ∈ Finset.range P, phase (f (a + x))‖ ≤
      finiteWeylEnvelope terminal r P := by
  exact norm_phaseSum_le_finiteWeylEnvelope
    (fun n ↦ f (a + n)) P r hterminal_nonneg hterminal

/-! ## Continuous mixed-difference calculus -/

/-- A real forward difference with an arbitrary nonnegative real step. -/
def realPositiveDifference (f : ℝ → ℝ) (h x : ℝ) : ℝ :=
  f (x + h) - f x

/-- Iterated real forward differences. -/
def iteratedRealPositiveDifference (f : ℝ → ℝ) :
    List ℝ → ℝ → ℝ
  | [], x => f x
  | h :: hs, x =>
      realPositiveDifference (iteratedRealPositiveDifference f hs) h x

@[simp] theorem iteratedRealPositiveDifference_nil
    (f : ℝ → ℝ) (x : ℝ) :
    iteratedRealPositiveDifference f [] x = f x := rfl

@[simp] theorem iteratedRealPositiveDifference_cons
    (f : ℝ → ℝ) (h : ℝ) (hs : List ℝ) (x : ℝ) :
    iteratedRealPositiveDifference f (h :: hs) x =
      iteratedRealPositiveDifference f hs (x + h) -
        iteratedRealPositiveDifference f hs x := rfl

/-- Differentiation commutes with every finite forward-difference history. -/
theorem hasDerivAt_iteratedRealPositiveDifference
    {f f' : ℝ → ℝ} (hf : ∀ x, HasDerivAt f (f' x) x)
    (hs : List ℝ) (x : ℝ) :
    HasDerivAt (iteratedRealPositiveDifference f hs)
      (iteratedRealPositiveDifference f' hs x) x := by
  induction hs generalizing x with
  | nil => simpa [iteratedRealPositiveDifference] using hf x
  | cons h hs ih =>
      simp only [iteratedRealPositiveDifference_cons]
      have hshift : HasDerivAt
          (fun y : ℝ ↦ iteratedRealPositiveDifference f hs (y + h))
          (iteratedRealPositiveDifference f' hs (x + h)) x := by
        simpa [Function.comp_def] using
          (ih (x + h)).comp x
            (HasDerivAt.add_const h (hasDerivAt_id x))
      exact hshift.sub (ih x)

/-- Quantitative mixed mean-value theorem.  If the final derivative lies
between `L` and `U`, then an iterated positive difference lies between the
same constants multiplied by the product of its step lengths. -/
theorem iteratedRealPositiveDifference_bounds
    (F : ℕ → ℝ → ℝ) (hs : List ℝ) (L U x : ℝ)
    (hsteps : ∀ h ∈ hs, 0 ≤ h)
    (hsmooth : ∀ j < hs.length, ∀ y,
      HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y, L ≤ F hs.length y ∧ F hs.length y ≤ U) :
    L * hs.prod ≤ iteratedRealPositiveDifference (F 0) hs x ∧
      iteratedRealPositiveDifference (F 0) hs x ≤ U * hs.prod := by
  induction hs generalizing F L U x with
  | nil =>
      simpa only [iteratedRealPositiveDifference_nil, List.prod_nil,
        mul_one, List.length_nil] using hfinal x
  | cons h hs ih =>
      have hh : 0 ≤ h := hsteps h (by simp)
      have htail : ∀ t ∈ hs, 0 ≤ t := by
        intro t ht
        exact hsteps t (by simp [ht])
      let G : ℕ → ℝ → ℝ := fun j ↦ F (j + 1)
      have hsmoothTail : ∀ j < hs.length, ∀ y,
          HasDerivAt (G j) (G (j + 1) y) y := by
        intro j hj y
        simpa only [G, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
          hsmooth (j + 1) (by simp only [List.length_cons]; omega) y
      have hfinalTail : ∀ y,
          L ≤ G hs.length y ∧ G hs.length y ≤ U := by
        intro y
        simpa only [G, List.length_cons, Nat.add_comm] using hfinal y
      have hderivBounds (y : ℝ) :
          L * hs.prod ≤ iteratedRealPositiveDifference (F 1) hs y ∧
            iteratedRealPositiveDifference (F 1) hs y ≤ U * hs.prod := by
        simpa only [G] using
          ih G L U y htail hsmoothTail hfinalTail
      let g : ℝ → ℝ := iteratedRealPositiveDifference (F 0) hs
      let g' : ℝ → ℝ := iteratedRealPositiveDifference (F 1) hs
      have hgderiv (y : ℝ) : HasDerivAt g (g' y) y := by
        apply hasDerivAt_iteratedRealPositiveDifference
        intro z
        simpa only [g, g'] using hsmooth 0 (by simp) z
      have hgd : Differentiable ℝ g := fun y ↦ (hgderiv y).differentiableAt
      have hderivEq (y : ℝ) : deriv g y = g' y := (hgderiv y).deriv
      have hxy : x ≤ x + h := by linarith
      have hlower :
          (L * hs.prod) * ((x + h) - x) ≤ g (x + h) - g x := by
        apply mul_sub_le_image_sub_of_le_deriv hgd
        · intro y
          rw [hderivEq]
          exact (hderivBounds y).1
        · exact hxy
      have hupper :
          g (x + h) - g x ≤ (U * hs.prod) * ((x + h) - x) := by
        apply image_sub_le_mul_sub_of_deriv_le hgd
        · intro y
          rw [hderivEq]
          exact (hderivBounds y).2
        · exact hxy
      simpa only [iteratedRealPositiveDifference_cons, g, List.prod_cons] using
        And.intro (by nlinarith) (by nlinarith)

/-! ## Controlled-shift higher differencing

Unlike the preceding all-positive-shifts inequality, this form permits the
shift counts and step sizes to be chosen independently at every level.  It
is the form needed for nonintegral power phases: choosing small shift counts
keeps the final derivative away from nonzero integers.
-/

/-- One controlled Weyl step with `K` translates separated by the base
spacing `d`. -/
def controlledStep (K d : ℕ) (hK : 0 < K) : RestrictedWeyl.ConductorStep where
  shiftCount := K
  stepSize := d
  shiftCount_pos := hK

/-- Repeat the same controlled shift scale a prescribed number of times. -/
def constantControlledSteps (r K d : ℕ) (hK : 0 < K) :
    List RestrictedWeyl.ConductorStep :=
  List.replicate r (controlledStep K d hK)

@[simp] theorem length_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K) :
    (constantControlledSteps r K d hK).length = r := by
  simp [constantControlledSteps]

/-- Numerical description of one history entry generated by the constant
controlled step `(K,d)`. -/
def IsConstantControlledEntry (K d : ℕ) (h : ℕ × ℕ × ℕ) : Prop :=
  h.1 = d ∧ h.2.1 < K ∧ h.2.2 < K ∧ h.2.1 ≠ h.2.2

private theorem leaf_length_eq_add_of_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K)
    (base leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) base) :
    leaf.length = r + base.length := by
  induction r generalizing base leaf with
  | zero =>
      simp only [constantControlledSteps, List.replicate_zero,
        RestrictedWeyl.offDiagonalHistoryLeaves, Finset.mem_singleton] at hleaf
      subst leaf
      simp
  | succ r ih =>
      simp only [constantControlledSteps, List.replicate_succ,
        RestrictedWeyl.offDiagonalHistoryLeaves, Finset.mem_biUnion] at hleaf
      obtain ⟨child, hchild, hleaf⟩ := hleaf
      rw [RestrictedWeyl.offDiagonalChildren] at hchild
      obtain ⟨kl, hkl, rfl⟩ := Finset.mem_image.mp hchild
      have hlen := ih ((d, kl.1, kl.2) :: base) leaf hleaf
      simp only [List.length_cons] at hlen ⊢
      omega

/-- Every constant-step leaf has exactly one entry per Weyl step. -/
theorem leaf_length_eq_of_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K) (leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) []) :
    leaf.length = r := by
  simpa using
    leaf_length_eq_add_of_constantControlledSteps r K d hK [] leaf hleaf

private theorem leaf_entries_of_constantControlledSteps_aux
    (r K d : ℕ) (hK : 0 < K)
    (base leaf : RestrictedWeyl.History)
    (hbase : ∀ h ∈ base, IsConstantControlledEntry K d h)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) base) :
    ∀ h ∈ leaf, IsConstantControlledEntry K d h := by
  induction r generalizing base leaf with
  | zero =>
      simp only [constantControlledSteps, List.replicate_zero,
        RestrictedWeyl.offDiagonalHistoryLeaves, Finset.mem_singleton] at hleaf
      subst leaf
      exact hbase
  | succ r ih =>
      simp only [constantControlledSteps, List.replicate_succ,
        RestrictedWeyl.offDiagonalHistoryLeaves, Finset.mem_biUnion] at hleaf
      obtain ⟨child, hchild, hleaf⟩ := hleaf
      rw [RestrictedWeyl.offDiagonalChildren] at hchild
      obtain ⟨kl, hkl, rfl⟩ := Finset.mem_image.mp hchild
      have hkl' := RestrictedWeyl.mem_offDiagonalPairs_iff.mp hkl
      apply ih ((d, kl.1, kl.2) :: base) leaf
      · intro h hh
        simp only [List.mem_cons] at hh
        rcases hh with rfl | hh
        · exact ⟨rfl, hkl'.1, hkl'.2.1, hkl'.2.2⟩
        · exact hbase h hh
      · exact hleaf

/-- Every entry of a constant-step leaf has the prescribed base step,
off-diagonal indices, and indices below the shift count. -/
theorem leaf_entries_of_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K) (leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) []) :
    ∀ h ∈ leaf, IsConstantControlledEntry K d h := by
  apply leaf_entries_of_constantControlledSteps_aux r K d hK [] leaf
  · simp
  · exact hleaf

private theorem natPairStep_lower_of_constantControlledEntry
    {K d : ℕ} {h : ℕ × ℕ × ℕ}
    (hh : IsConstantControlledEntry K d h) :
    (d : ℝ) ≤ MixedDifference.natPairStep h := by
  rcases h with ⟨d', k, l⟩
  change d' = d ∧ k < K ∧ l < K ∧ k ≠ l at hh
  rcases hh with ⟨hd, hk, hl, hne⟩
  subst d'
  simp only [MixedDifference.natPairStep]
  have habs : (1 : ℝ) ≤ |(k : ℝ) - l| := by
    rcases lt_or_gt_of_ne hne with hkl | hlk
    · rw [abs_of_nonpos (sub_nonpos.mpr (by exact_mod_cast hkl.le))]
      have hc : (k : ℝ) + 1 ≤ l := by
        exact_mod_cast (Nat.add_one_le_iff.mpr hkl)
      linarith
    · rw [abs_of_nonneg (sub_nonneg.mpr (by exact_mod_cast hlk.le))]
      have hc : (l : ℝ) + 1 ≤ k := by
        exact_mod_cast (Nat.add_one_le_iff.mpr hlk)
      linarith
  calc
    (d : ℝ) = d * 1 := by ring
    _ ≤ d * |(k : ℝ) - l| :=
      mul_le_mul_of_nonneg_left habs (by positivity)

private theorem pow_length_le_prod_natHistorySteps
    (K d : ℕ) (leaf : RestrictedWeyl.History)
    (hentries : ∀ h ∈ leaf, IsConstantControlledEntry K d h) :
    (d : ℝ) ^ leaf.length ≤ (MixedDifference.natHistorySteps leaf).prod := by
  induction leaf with
  | nil => simp [MixedDifference.natHistorySteps]
  | cons h leaf ih =>
      have hh := natPairStep_lower_of_constantControlledEntry
        (hentries h (by simp))
      have htail : ∀ t ∈ leaf, IsConstantControlledEntry K d t := by
        intro t ht
        exact hentries t (by simp [ht])
      have hi := ih htail
      have hprod0 : 0 ≤ (MixedDifference.natHistorySteps leaf).prod := by
        apply List.prod_nonneg
        intro t ht
        obtain ⟨entry, hentry, rfl⟩ := List.mem_map.mp ht
        unfold MixedDifference.natPairStep
        positivity
      simp only [List.length_cons, MixedDifference.natHistorySteps,
        List.map_cons, List.prod_cons, pow_succ]
      calc
        (d : ℝ) ^ leaf.length * d ≤
            (MixedDifference.natHistorySteps leaf).prod *
              MixedDifference.natPairStep h :=
          mul_le_mul hi hh (by positivity) hprod0
        _ = MixedDifference.natPairStep h *
            (MixedDifference.natHistorySteps leaf).prod := by ring

/-- Every constant-step leaf gains at least one factor `d` in every
positive mixed-difference step. -/
theorem pow_le_historySteps_prod_of_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K) (leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) []) :
    (d : ℝ) ^ r ≤
      (MixedDifference.historySteps (MixedDifference.realHistory leaf)).prod := by
  rw [MixedDifference.historySteps_realHistory]
  rw [← leaf_length_eq_of_constantControlledSteps r K d hK leaf hleaf]
  exact pow_length_le_prod_natHistorySteps K d leaf
    (leaf_entries_of_constantControlledSteps r K d hK leaf hleaf)

private theorem natPairBase_add_step_le_of_constantControlledEntry
    {K d : ℕ} {h : ℕ × ℕ × ℕ}
    (hh : IsConstantControlledEntry K d h) :
    MixedDifference.natPairBase h + MixedDifference.natPairStep h ≤
      (K : ℝ) * d := by
  rcases h with ⟨d', k, l⟩
  change d' = d ∧ k < K ∧ l < K ∧ k ≠ l at hh
  rcases hh with ⟨hd, hk, hl, hne⟩
  subst d'
  simp only [MixedDifference.natPairBase, MixedDifference.natPairStep]
  by_cases hkl : k ≤ l
  · rw [min_eq_left hkl,
      abs_of_nonpos (sub_nonpos.mpr (by exact_mod_cast hkl))]
    have hlK : (l : ℝ) ≤ K := by exact_mod_cast hl.le
    calc
      (d : ℝ) * k + d * (-((k : ℝ) - l)) = d * l := by ring
      _ ≤ d * K := mul_le_mul_of_nonneg_left hlK (by positivity)
      _ = (K : ℝ) * d := by ring
  · have hlk : l ≤ k := le_of_not_ge hkl
    rw [min_eq_right hlk,
      abs_of_nonneg (sub_nonneg.mpr (by exact_mod_cast hlk))]
    have hkK : (k : ℝ) ≤ K := by exact_mod_cast hk.le
    calc
      (d : ℝ) * l + d * ((k : ℝ) - l) = d * k := by ring
      _ ≤ d * K := mul_le_mul_of_nonneg_left hkK (by positivity)
      _ = (K : ℝ) * d := by ring

private theorem natPairStep_upper_of_constantControlledEntry
    {K d : ℕ} {h : ℕ × ℕ × ℕ}
    (hh : IsConstantControlledEntry K d h) :
    MixedDifference.natPairStep h ≤ (K : ℝ) * d := by
  have hsum := natPairBase_add_step_le_of_constantControlledEntry hh
  have hbase : 0 ≤ MixedDifference.natPairBase h := by
    unfold MixedDifference.natPairBase
    positivity
  linarith

private theorem prod_natHistorySteps_le_pow_length
    (K d : ℕ) (leaf : RestrictedWeyl.History)
    (hentries : ∀ h ∈ leaf, IsConstantControlledEntry K d h) :
    (MixedDifference.natHistorySteps leaf).prod ≤
      ((K : ℝ) * d) ^ leaf.length := by
  induction leaf with
  | nil => simp [MixedDifference.natHistorySteps]
  | cons h leaf ih =>
      have hh := natPairStep_upper_of_constantControlledEntry
        (hentries h (by simp))
      have htail : ∀ t ∈ leaf, IsConstantControlledEntry K d t := by
        intro t ht
        exact hentries t (by simp [ht])
      have hi := ih htail
      have hprod0 : 0 ≤ (MixedDifference.natHistorySteps leaf).prod := by
        apply List.prod_nonneg
        intro t ht
        obtain ⟨entry, hentry, rfl⟩ := List.mem_map.mp ht
        unfold MixedDifference.natPairStep
        positivity
      simp only [List.length_cons, MixedDifference.natHistorySteps,
        List.map_cons, List.prod_cons, pow_succ]
      calc
        MixedDifference.natPairStep h *
              (MixedDifference.natHistorySteps leaf).prod ≤
            ((K : ℝ) * d) * (((K : ℝ) * d) ^ leaf.length) :=
          mul_le_mul hh hi hprod0 (by positivity)
        _ = ((K : ℝ) * d) ^ leaf.length * ((K : ℝ) * d) := by ring

/-- Every positive mixed-difference step is at most `K*d`, so a depth-`r`
constant-step leaf has product at most `(K*d)^r`. -/
theorem historySteps_prod_le_pow_of_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K) (leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) []) :
    (MixedDifference.historySteps
        (MixedDifference.realHistory leaf)).prod ≤
      ((K : ℝ) * d) ^ r := by
  rw [MixedDifference.historySteps_realHistory,
    ← leaf_length_eq_of_constantControlledSteps r K d hK leaf hleaf]
  exact prod_natHistorySteps_le_pow_length K d leaf
    (leaf_entries_of_constantControlledSteps r K d hK leaf hleaf)

private theorem natHistoryBase_add_steps_sum_le
    (K d : ℕ) (leaf : RestrictedWeyl.History)
    (hentries : ∀ h ∈ leaf, IsConstantControlledEntry K d h) :
    MixedDifference.natHistoryBase leaf +
        (MixedDifference.natHistorySteps leaf).sum ≤
      (leaf.length : ℝ) * K * d := by
  induction leaf with
  | nil => simp [MixedDifference.natHistoryBase, MixedDifference.natHistorySteps]
  | cons h leaf ih =>
      have hh := natPairBase_add_step_le_of_constantControlledEntry
        (hentries h (by simp))
      have htail : ∀ t ∈ leaf, IsConstantControlledEntry K d t := by
        intro t ht
        exact hentries t (by simp [ht])
      have hi := ih htail
      simp only [MixedDifference.natHistoryBase,
        MixedDifference.natHistorySteps, List.map_cons, List.sum_cons,
        List.length_cons, Nat.cast_add, Nat.cast_one]
      calc
        MixedDifference.natPairBase h +
              (List.map MixedDifference.natPairBase leaf).sum +
            (MixedDifference.natPairStep h +
              (List.map MixedDifference.natPairStep leaf).sum) =
            (MixedDifference.natPairBase h + MixedDifference.natPairStep h) +
              ((List.map MixedDifference.natPairBase leaf).sum +
                (List.map MixedDifference.natPairStep leaf).sum) := by ring
        _ ≤ (K : ℝ) * d + (leaf.length : ℝ) * K * d :=
          add_le_add hh hi
        _ = ((leaf.length : ℝ) + 1) * K * d := by ring

/-- The total base translation plus all positive step lengths of a leaf is
bounded by `r*K*d`. -/
theorem historyBase_add_steps_sum_le_of_constantControlledSteps
    (r K d : ℕ) (hK : 0 < K) (leaf : RestrictedWeyl.History)
    (hleaf : leaf ∈ RestrictedWeyl.offDiagonalHistoryLeaves
      (constantControlledSteps r K d hK) []) :
    MixedDifference.historyBase (MixedDifference.realHistory leaf) +
        (MixedDifference.historySteps (MixedDifference.realHistory leaf)).sum ≤
      (r : ℝ) * K * d := by
  rw [MixedDifference.historyBase_realHistory,
    MixedDifference.historySteps_realHistory,
    ← leaf_length_eq_of_constantControlledSteps r K d hK leaf hleaf]
  exact natHistoryBase_add_steps_sum_le K d leaf
    (leaf_entries_of_constantControlledSteps r K d hK leaf hleaf)

/-- A source-facing one-step estimate for the recursive controlled Weyl
envelope.  Dividing by `K²` gives
`E_j² ≤ 2(P²/K + P E_{j+1} + 4 K²d²)`. -/
theorem shiftCount_sq_mul_finiteHistoryEnvelope_cons_sq_le
    (P : ℕ) {terminal : ℝ} (hterminal : 0 ≤ terminal)
    (steps : List RestrictedWeyl.ConductorStep)
    (K d : ℕ) (hK : 0 < K) :
    (K : ℝ) ^ 2 *
        RestrictedWeyl.finiteHistoryEnvelope P terminal
          (controlledStep K d hK :: steps) ^ 2 ≤
      2 * ((K : ℝ) * P ^ 2 + (K : ℝ) ^ 2 * P *
          RestrictedWeyl.finiteHistoryEnvelope P terminal steps +
        4 * (K : ℝ) ^ 4 * d ^ 2) := by
  let E := RestrictedWeyl.finiteHistoryEnvelope P terminal steps
  have hE : 0 ≤ E :=
    RestrictedWeyl.finiteHistoryEnvelope_nonneg P hterminal steps
  have hrad : 0 ≤ RestrictedWeyl.stepRadicand P
      (controlledStep K d hK) E :=
    RestrictedWeyl.stepRadicand_nonneg P (controlledStep K d hK) hE
  have hsqrt : Real.sqrt (RestrictedWeyl.stepRadicand P
      (controlledStep K d hK) E) ^ 2 =
      RestrictedWeyl.stepRadicand P (controlledStep K d hK) E :=
    Real.sq_sqrt hrad
  have hK0 : (0 : ℝ) < K := by exact_mod_cast hK
  have hB := RestrictedWeyl.boundaryBudget_le K d
  have hB0 : 0 ≤ RestrictedWeyl.boundaryBudget K d :=
    RestrictedWeyl.boundaryBudget_nonneg K d
  have hBsq : RestrictedWeyl.boundaryBudget K d ^ 2 ≤
      (2 * (K : ℝ) ^ 2 * d) ^ 2 :=
    pow_le_pow_left₀ hB0 hB 2
  have hKm1 : (((K - 1 : ℕ) : ℝ)) ≤ K := by
    exact_mod_cast Nat.sub_le K 1
  simp only [RestrictedWeyl.finiteHistoryEnvelope, controlledStep]
  rw [div_pow]
  have hsqrt' := hsqrt
  simp only [controlledStep, E] at hsqrt'
  rw [hsqrt']
  field_simp [hK0.ne']
  change
    2 * ((P : ℝ) * ((K : ℝ) * P + (K : ℝ) * (K - 1 : ℕ) * E) +
        RestrictedWeyl.boundaryBudget K d ^ 2) ≤
      (K : ℝ) * 2 * ((P : ℝ) * (P + (K : ℝ) * E) +
        (K : ℝ) ^ 3 * 4 * d ^ 2)
  calc
    2 * ((P : ℝ) * ((K : ℝ) * P + (K : ℝ) * (K - 1 : ℕ) * E) +
        RestrictedWeyl.boundaryBudget K d ^ 2) ≤
        2 * ((P : ℝ) * ((K : ℝ) * P + (K : ℝ) * K * E) +
          (2 * (K : ℝ) ^ 2 * d) ^ 2) := by
      gcongr
    _ = (K : ℝ) * 2 * ((P : ℝ) * (P + (K : ℝ) * E) +
        (K : ℝ) ^ 3 * 4 * d ^ 2) := by ring

/-- A real translate-pair difference with translations `k*d` and `l*d`. -/
def pairDifference (f : ℕ → ℝ) (d k l x : ℕ) : ℝ :=
  f (x + k * d) - f (x + l * d)

/-- Iterated real translate-pair differences, in the history convention of
`RestrictedIntervalWeyl.iteratedPairCorrelation`. -/
def iteratedPairDifference (f : ℕ → ℝ) :
    List (ℕ × ℕ × ℕ) → ℕ → ℝ
  | [], x => f x
  | (d, k, l) :: hs, x =>
      pairDifference (iteratedPairDifference f hs) d k l x

/-- The phase-side recursion is definitionally the natural mixed-difference
recursion analyzed in `MixedDifference`. -/
theorem iteratedPairDifference_eq_iteratedNatPairDifference
    (f : ℕ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (x : ℕ) :
    iteratedPairDifference f hs x =
      MixedDifference.iteratedNatPairDifference f hs x := by
  induction hs generalizing x with
  | nil => rfl
  | cons h hs ih =>
      rcases h with ⟨d, k, l⟩
      simp only [iteratedPairDifference,
        MixedDifference.iteratedNatPairDifference, pairDifference, ih]

/-- Normal form of a sampled controlled phase: one orientation sign, one
nonnegative forward-difference history, and one base translation. -/
theorem iteratedPairDifference_sample_eq_normalForm
    (f : ℝ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (x : ℕ) :
    iteratedPairDifference (fun n ↦ f n) hs x =
      MixedDifference.historyOrientation (MixedDifference.realHistory hs) *
        MixedDifference.iteratedRealPositiveDifference f
          (MixedDifference.historySteps (MixedDifference.realHistory hs))
          ((x : ℝ) + MixedDifference.historyBase
            (MixedDifference.realHistory hs)) := by
  rw [iteratedPairDifference_eq_iteratedNatPairDifference,
    MixedDifference.iteratedNatPairDifference_eq_normalForm]

/-- Local dyadic derivative bounds transfer directly to the absolute unit
increments of the real phase attached to a controlled Weyl leaf. -/
theorem abs_iteratedPairDifference_unitIncrement_bounds_on_Icc
    (F : ℕ → ℝ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (x : ℕ)
    (A B L U : ℝ) (hL : 0 ≤ L)
    (hxA : A ≤ (x : ℝ) + MixedDifference.historyBase
      (MixedDifference.realHistory hs))
    (hxB : (x : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) + 1 +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 1,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ≤ U) :
    L * (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod ≤
        |iteratedPairDifference (fun n ↦ F 0 n) hs (x + 1) -
          iteratedPairDifference (fun n ↦ F 0 n) hs x| ∧
      |iteratedPairDifference (fun n ↦ F 0 n) hs (x + 1) -
          iteratedPairDifference (fun n ↦ F 0 n) hs x| ≤
        U * (MixedDifference.historySteps
          (MixedDifference.realHistory hs)).prod := by
  simpa only [iteratedPairDifference_eq_iteratedNatPairDifference] using
    MixedDifference.abs_iteratedNatPairDifference_unitIncrement_bounds_on_Icc
      F hs x A B L U hL hxA hxB hsmooth hfinal

theorem iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement
    (f : ℝ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (x : ℕ) :
    iteratedPairDifference (fun n ↦ f n) hs (x + 1) -
        iteratedPairDifference (fun n ↦ f n) hs x =
      MixedDifference.mixedNatUnitIncrement f hs x := by
  simp only [iteratedPairDifference_eq_iteratedNatPairDifference,
    MixedDifference.mixedNatUnitIncrement]

/-- A uniform localized derivative window controls every normalized leaf
increment in a finite prefix. -/
theorem normalizedNatUnitIncrement_bounds_on_Icc_for_range
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (P : ℕ)
    (A B L U : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (P : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 1,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ≤ U) :
    ∀ k < P,
      L * (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod ≤
          MixedDifference.normalizedNatUnitIncrement f hs k ∧
        MixedDifference.normalizedNatUnitIncrement f hs k ≤
          U * (MixedDifference.historySteps
            (MixedDifference.realHistory hs)).prod := by
  intro k hk
  let steps := MixedDifference.historySteps (MixedDifference.realHistory hs)
  let base := MixedDifference.historyBase (MixedDifference.realHistory hs)
  have hk0 : (0 : ℝ) ≤ k := by positivity
  have hkP : ((k : ℝ) + 1) ≤ P := by exact_mod_cast (Nat.add_one_le_iff.mpr hk)
  have hxA : A ≤ (k : ℝ) + base := by
    dsimp only [base]
    linarith
  have hxB : (k : ℝ) + base + 1 + steps.sum ≤ B := by
    dsimp only [steps, base] at ⊢
    linarith
  have hb := MixedDifference.iteratedRealPositiveDifference_unitIncrement_bounds_on_Icc
    F steps A B L U ((k : ℝ) + base)
      (MixedDifference.historySteps_nonneg (MixedDifference.realHistory hs))
      hxA hxB (by simpa only [steps] using hsmooth)
      (by simpa only [steps] using hfinal)
  simpa only [MixedDifference.normalizedNatUnitIncrement, steps, base, hF] using hb

/-- A nonnegative derivative one order beyond the terminal increment bound
makes the normalized increments monotone on the natural prefix. -/
theorem normalizedNatUnitIncrement_monotoneOn_Iio_of_finalDerivative_nonneg_on_Icc
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (N : ℕ)
    (A B L U : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (N : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) + 1 +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hL : 0 ≤ L)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 2,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ≤ U) :
    MonotoneOn (MixedDifference.normalizedNatUnitIncrement f hs)
      (Set.Iio N) := by
  let steps := MixedDifference.historySteps (MixedDifference.realHistory hs)
  let base := MixedDifference.historyBase (MixedDifference.realHistory hs)
  have hm := MixedDifference.monotoneOn_unitIncrement_of_finalDerivative_nonneg_on_Icc
    F steps A B base ((N : ℝ) + base) L U
      (MixedDifference.historySteps_nonneg (MixedDifference.realHistory hs))
      (by simpa only [base] using hA)
      (by simpa only [steps, base, add_assoc] using hB)
      hL (by simpa only [steps] using hsmooth)
      (by simpa only [steps] using hfinal)
  intro x hx y hy hxy
  have hxr : (x : ℝ) + base ∈ Set.Icc base ((N : ℝ) + base) := by
    constructor
    · have hx0 : (0 : ℝ) ≤ x := by positivity
      linarith
    · have hxN : (x : ℝ) ≤ N := by exact_mod_cast hx.le
      linarith
  have hyr : (y : ℝ) + base ∈ Set.Icc base ((N : ℝ) + base) := by
    constructor
    · have hy0 : (0 : ℝ) ≤ y := by positivity
      linarith
    · have hyN : (y : ℝ) ≤ N := by exact_mod_cast hy.le
      linarith
  have hxy' : (x : ℝ) + base ≤ (y : ℝ) + base := by
    have hxy'' : (x : ℝ) ≤ y := by exact_mod_cast hxy
    linarith
  have hmono := hm hxr hyr hxy'
  simpa only [MixedDifference.normalizedNatUnitIncrement, steps, base, hF,
    Nat.cast_add, Nat.cast_one] using hmono

/-- A nonpositive derivative one order beyond the terminal increment bound
makes the normalized increments antitone on the natural prefix. -/
theorem normalizedNatUnitIncrement_antitoneOn_Iio_of_finalDerivative_nonpos_on_Icc
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (N : ℕ)
    (A B L U : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (N : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) + 1 +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hU : U ≤ 0)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 2,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ≤ U) :
    AntitoneOn (MixedDifference.normalizedNatUnitIncrement f hs)
      (Set.Iio N) := by
  let steps := MixedDifference.historySteps (MixedDifference.realHistory hs)
  let base := MixedDifference.historyBase (MixedDifference.realHistory hs)
  have hm := MixedDifference.antitoneOn_unitIncrement_of_finalDerivative_nonpos_on_Icc
    F steps A B base ((N : ℝ) + base) L U
      (MixedDifference.historySteps_nonneg (MixedDifference.realHistory hs))
      (by simpa only [base] using hA)
      (by simpa only [steps, base, add_assoc] using hB)
      hU (by simpa only [steps] using hsmooth)
      (by simpa only [steps] using hfinal)
  intro x hx y hy hxy
  have hxr : (x : ℝ) + base ∈ Set.Icc base ((N : ℝ) + base) := by
    constructor
    · have hx0 : (0 : ℝ) ≤ x := by positivity
      linarith
    · have hxN : (x : ℝ) ≤ N := by exact_mod_cast hx.le
      linarith
  have hyr : (y : ℝ) + base ∈ Set.Icc base ((N : ℝ) + base) := by
    constructor
    · have hy0 : (0 : ℝ) ≤ y := by positivity
      linarith
    · have hyN : (y : ℝ) ≤ N := by exact_mod_cast hy.le
      linarith
  have hxy' : (x : ℝ) + base ≤ (y : ℝ) + base := by
    have hxy'' : (x : ℝ) ≤ y := by exact_mod_cast hxy
    linarith
  have hanti := hm hxr hyr hxy'
  simpa only [MixedDifference.normalizedNatUnitIncrement, steps, base, hF,
    Nat.cast_add, Nat.cast_one] using hanti

@[simp] theorem iteratedPairDifference_nil (f : ℕ → ℝ) (x : ℕ) :
    iteratedPairDifference f [] x = f x := rfl

@[simp] theorem iteratedPairDifference_cons
    (f : ℕ → ℝ) (d k l : ℕ)
    (hs : List (ℕ × ℕ × ℕ)) (x : ℕ) :
    iteratedPairDifference f ((d, k, l) :: hs) x =
      iteratedPairDifference f hs (x + k * d) -
        iteratedPairDifference f hs (x + l * d) := rfl

/-- The restricted complex pair correlation is exactly the phase of the
corresponding real pair difference. -/
theorem translatedPairCorrelation_phase_eq
    (f : ℕ → ℝ) (d k l x : ℕ) :
    RestrictedWeyl.translatedPairCorrelation
        (fun n ↦ phase (f n)) d k l x =
      phase (pairDifference f d k l x) := by
  unfold RestrictedWeyl.translatedPairCorrelation
    pairDifference
  rw [phase_sub]

/-- Exact compatibility of the full controlled correlation history with
iterated real pair differences. -/
theorem iteratedPairCorrelation_phase_eq
    (f : ℕ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (x : ℕ) :
    RestrictedWeyl.iteratedPairCorrelation
        (fun n ↦ phase (f n)) hs x =
      phase (iteratedPairDifference f hs x) := by
  induction hs generalizing x with
  | nil => rfl
  | cons h hs ih =>
      rcases h with ⟨d, k, l⟩
      simp only [RestrictedWeyl.iteratedPairCorrelation,
        RestrictedWeyl.translatedPairCorrelation,
        iteratedPairDifference, pairDifference, ih]
      rw [phase_sub]

/-- Fully explicit controlled-shift higher-differencing theorem.

Every leaf is an iterated real pair difference using exactly the prescribed
small shifts.  A first-derivative estimate such as Kusmin--Landau supplies
`hterminal`; all diagonal, off-diagonal, and finite-interval boundary losses
are then accounted for by `finiteHistoryEnvelope`. -/
theorem norm_phaseSum_le_controlledHistoryEnvelope
    (f : ℕ → ℝ) (P : ℕ)
    (steps : List RestrictedWeyl.ConductorStep)
    {terminal : ℝ} (hterminal_nonneg : 0 ≤ terminal)
    (hterminal : ∀ leaf ∈
        RestrictedWeyl.offDiagonalHistoryLeaves
          steps [],
      ‖∑ x ∈ Finset.range P,
          phase (iteratedPairDifference f leaf x)‖ ≤ terminal) :
    ‖∑ x ∈ Finset.range P, phase (f x)‖ ≤
      RestrictedWeyl.finiteHistoryEnvelope
        P terminal steps := by
  apply
    RestrictedWeyl.norm_rawPrefix_le_finiteHistoryEnvelope
      (fun n ↦ phase (f n)) (fun n ↦ (norm_phase (f n)).le) P steps
        hterminal_nonneg
  intro leaf hleaf
  simpa only [iteratedPairCorrelation_phase_eq] using
    hterminal leaf hleaf

/-- Shifted-interval version of the controlled history theorem. -/
theorem norm_phaseSum_add_le_controlledHistoryEnvelope
    (f : ℕ → ℝ) (a P : ℕ)
    (steps : List RestrictedWeyl.ConductorStep)
    {terminal : ℝ} (hterminal_nonneg : 0 ≤ terminal)
    (hterminal : ∀ leaf ∈
        RestrictedWeyl.offDiagonalHistoryLeaves
          steps [],
      ‖∑ x ∈ Finset.range P,
          phase (iteratedPairDifference (fun n ↦ f (a + n)) leaf x)‖ ≤
        terminal) :
    ‖∑ x ∈ Finset.range P, phase (f (a + x))‖ ≤
      RestrictedWeyl.finiteHistoryEnvelope
        P terminal steps := by
  exact norm_phaseSum_le_controlledHistoryEnvelope
    (fun n ↦ f (a + n)) P steps hterminal_nonneg hterminal

/-- The two orientations of the terminal first-difference hypothesis used
by Kusmin--Landau.  Pair differencing may reverse orientation, so retaining
both cases avoids an artificial ordering convention on every Weyl leaf. -/
def TerminalIncrementCondition (g : ℕ → ℝ) (N : ℕ) (lam : ℝ) : Prop :=
  ((∀ k < N, lam ≤ g (k + 1) - g k ∧ g (k + 1) - g k ≤ 1 - lam) ∧
      (MonotoneOn (fun k : ℕ ↦ g (k + 1) - g k) (Set.Iio N) ∨
        AntitoneOn (fun k : ℕ ↦ g (k + 1) - g k) (Set.Iio N))) ∨
    ((∀ k < N, -1 + lam ≤ g (k + 1) - g k ∧
        g (k + 1) - g k ≤ -lam) ∧
      (MonotoneOn (fun k : ℕ ↦ g (k + 1) - g k) (Set.Iio N) ∨
        AntitoneOn (fun k : ℕ ↦ g (k + 1) - g k) (Set.Iio N)))

/-- The signed normal form converts positive monotone normalized increments
into exactly one of the two Kusmin--Landau orientations. -/
theorem terminalIncrementCondition_of_normalized_monotone
    (f : ℝ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (N : ℕ) (lam : ℝ)
    (hbounds : ∀ k < N,
      lam ≤ MixedDifference.normalizedNatUnitIncrement f hs k ∧
        MixedDifference.normalizedNatUnitIncrement f hs k ≤ 1 - lam)
    (hmono : MonotoneOn (MixedDifference.normalizedNatUnitIncrement f hs)
      (Set.Iio N)) :
    TerminalIncrementCondition
      (iteratedPairDifference (fun n ↦ f n) hs) N lam := by
  rcases MixedDifference.historyOrientation_eq_one_or_neg_one
    (MixedDifference.realHistory hs) with hor | hor
  · left
    constructor
    · intro k hk
      have hb := hbounds k hk
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor, one_mul]
      exact hb
    · left
      intro i hi j hj hij
      change
        iteratedPairDifference (fun n ↦ f n) hs (i + 1) -
            iteratedPairDifference (fun n ↦ f n) hs i ≤
          iteratedPairDifference (fun n ↦ f n) hs (j + 1) -
            iteratedPairDifference (fun n ↦ f n) hs j
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor,
        one_mul, one_mul]
      exact hmono hi hj hij
  · right
    constructor
    · intro k hk
      have hb := hbounds k hk
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor,
        neg_one_mul]
      constructor <;> linarith
    · right
      intro i hi j hj hij
      change
        iteratedPairDifference (fun n ↦ f n) hs (j + 1) -
            iteratedPairDifference (fun n ↦ f n) hs j ≤
          iteratedPairDifference (fun n ↦ f n) hs (i + 1) -
            iteratedPairDifference (fun n ↦ f n) hs i
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor,
        neg_one_mul, neg_one_mul]
      exact neg_le_neg (hmono hi hj hij)

/-- The complementary orientation transfer for antitone normalized
increments. -/
theorem terminalIncrementCondition_of_normalized_antitone
    (f : ℝ → ℝ) (hs : List (ℕ × ℕ × ℕ)) (N : ℕ) (lam : ℝ)
    (hbounds : ∀ k < N,
      lam ≤ MixedDifference.normalizedNatUnitIncrement f hs k ∧
        MixedDifference.normalizedNatUnitIncrement f hs k ≤ 1 - lam)
    (hanti : AntitoneOn (MixedDifference.normalizedNatUnitIncrement f hs)
      (Set.Iio N)) :
    TerminalIncrementCondition
      (iteratedPairDifference (fun n ↦ f n) hs) N lam := by
  rcases MixedDifference.historyOrientation_eq_one_or_neg_one
    (MixedDifference.realHistory hs) with hor | hor
  · left
    constructor
    · intro k hk
      have hb := hbounds k hk
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor, one_mul]
      exact hb
    · right
      intro i hi j hj hij
      change
        iteratedPairDifference (fun n ↦ f n) hs (j + 1) -
            iteratedPairDifference (fun n ↦ f n) hs j ≤
          iteratedPairDifference (fun n ↦ f n) hs (i + 1) -
            iteratedPairDifference (fun n ↦ f n) hs i
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor,
        one_mul, one_mul]
      exact hanti hi hj hij
  · right
    constructor
    · intro k hk
      have hb := hbounds k hk
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor,
        neg_one_mul]
      constructor <;> linarith
    · left
      intro i hi j hj hij
      change
        iteratedPairDifference (fun n ↦ f n) hs (i + 1) -
            iteratedPairDifference (fun n ↦ f n) hs i ≤
          iteratedPairDifference (fun n ↦ f n) hs (j + 1) -
            iteratedPairDifference (fun n ↦ f n) hs j
      rw [iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        iteratedPairDifference_unitIncrement_eq_mixedNatUnitIncrement,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul,
        MixedDifference.mixedNatUnitIncrement_eq_orientation_mul, hor,
        neg_one_mul, neg_one_mul]
      exact neg_le_neg (hanti hi hj hij)

/-- Local higher-derivative bounds on `[A,B]`, together with monotonicity of
the normalized increments, imply the terminal condition consumed by the
controlled Weyl--Kusmin--Landau theorem. -/
theorem terminalIncrementCondition_of_derivBounds_on_Icc
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (N : ℕ)
    (A B L U lam : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (N : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 1,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ≤ U)
    (hlower : lam ≤
      L * (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod)
    (hupper : U *
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod ≤
      1 - lam)
    (hmono : MonotoneOn (MixedDifference.normalizedNatUnitIncrement f hs)
      (Set.Iio N)) :
    TerminalIncrementCondition
      (iteratedPairDifference (fun n ↦ f n) hs) N lam := by
  apply terminalIncrementCondition_of_normalized_monotone f hs N lam
  · intro k hk
    have hb := normalizedNatUnitIncrement_bounds_on_Icc_for_range
      F f hs N A B L U hF hA hB hsmooth hfinal k hk
    exact ⟨hlower.trans hb.1, hb.2.trans hupper⟩
  · exact hmono

/-- Antitone-normalized counterpart of
`terminalIncrementCondition_of_derivBounds_on_Icc`. -/
theorem terminalIncrementCondition_of_derivBounds_on_Icc_of_antitone
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (N : ℕ)
    (A B L U lam : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (N : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 1,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hfinal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ≤ U)
    (hlower : lam ≤
      L * (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod)
    (hupper : U *
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod ≤
      1 - lam)
    (hanti : AntitoneOn (MixedDifference.normalizedNatUnitIncrement f hs)
      (Set.Iio N)) :
    TerminalIncrementCondition
      (iteratedPairDifference (fun n ↦ f n) hs) N lam := by
  apply terminalIncrementCondition_of_normalized_antitone f hs N lam
  · intro k hk
    have hb := normalizedNatUnitIncrement_bounds_on_Icc_for_range
      F f hs N A B L U hF hA hB hsmooth hfinal k hk
    exact ⟨hlower.trans hb.1, hb.2.trans hupper⟩
  · exact hanti

/-- A localized derivative tower supplies both the terminal increment window
and its monotonicity: order `hs.length + 1` controls the increment size, and a
nonnegative derivative of the next order makes normalized increments
monotone. -/
theorem terminalIncrementCondition_of_derivBounds_and_next_nonneg_on_Icc
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (N : ℕ)
    (A B L U Lnext Unext lam : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (N : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) + 1 +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 2,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hterminal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ≤ U)
    (hnext : ∀ y ∈ Set.Icc A B,
      Lnext ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ≤ Unext)
    (hLnext : 0 ≤ Lnext)
    (hlower : lam ≤
      L * (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod)
    (hupper : U *
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod ≤
      1 - lam) :
    TerminalIncrementCondition
      (iteratedPairDifference (fun n ↦ f n) hs) N lam := by
  apply terminalIncrementCondition_of_derivBounds_on_Icc
    F f hs N A B L U lam hF hA
  · linarith
  · intro j hj y hy
    exact hsmooth j (by omega) y hy
  · exact hterminal
  · exact hlower
  · exact hupper
  · exact normalizedNatUnitIncrement_monotoneOn_Iio_of_finalDerivative_nonneg_on_Icc
      F f hs N A B Lnext Unext hF hA hB hLnext hsmooth hnext

/-- Nonpositive next derivative counterpart of
`terminalIncrementCondition_of_derivBounds_and_next_nonneg_on_Icc`; here the
normalized terminal increments are antitone. -/
theorem terminalIncrementCondition_of_derivBounds_and_next_nonpos_on_Icc
    (F : ℕ → ℝ → ℝ) (f : ℝ → ℝ)
    (hs : List (ℕ × ℕ × ℕ)) (N : ℕ)
    (A B L U Lnext Unext lam : ℝ) (hF : F 0 = f)
    (hA : A ≤ MixedDifference.historyBase (MixedDifference.realHistory hs))
    (hB : (N : ℝ) + MixedDifference.historyBase
        (MixedDifference.realHistory hs) + 1 +
      (MixedDifference.historySteps (MixedDifference.realHistory hs)).sum ≤ B)
    (hsmooth : ∀ j <
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).length + 2,
      ∀ y ∈ Set.Icc A B, HasDerivAt (F j) (F (j + 1) y) y)
    (hterminal : ∀ y ∈ Set.Icc A B,
      L ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 1) y ≤ U)
    (hnext : ∀ y ∈ Set.Icc A B,
      Lnext ≤ F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ∧
        F ((MixedDifference.historySteps
          (MixedDifference.realHistory hs)).length + 2) y ≤ Unext)
    (hUnext : Unext ≤ 0)
    (hlower : lam ≤
      L * (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod)
    (hupper : U *
        (MixedDifference.historySteps (MixedDifference.realHistory hs)).prod ≤
      1 - lam) :
    TerminalIncrementCondition
      (iteratedPairDifference (fun n ↦ f n) hs) N lam := by
  apply terminalIncrementCondition_of_derivBounds_on_Icc_of_antitone
    F f hs N A B L U lam hF hA
  · linarith
  · intro j hj y hy
    exact hsmooth j (by omega) y hy
  · exact hterminal
  · exact hlower
  · exact hupper
  · exact normalizedNatUnitIncrement_antitoneOn_Iio_of_finalDerivative_nonpos_on_Icc
      F f hs N A B Lnext Unext hF hA hB hUnext hsmooth hnext

/-- Terminal Kusmin--Landau bound in the local phase notation. -/
theorem norm_phaseSum_le_inv_of_terminalIncrementCondition
    (g : ℕ → ℝ) (N : ℕ) (lam : ℝ)
    (hlam : 0 < lam) (hlamhalf : lam ≤ 1 / 2)
    (hg : TerminalIncrementCondition g N lam) :
    ‖∑ k ∈ Finset.range N, phase (g k)‖ ≤ 1 / lam := by
  rcases hg with ⟨hinc, hmono | hanti⟩ | ⟨hinc, hmono | hanti⟩
  · simpa only [phase, Erdos587.phase, zero_add] using
      norm_sum_phase_add_range_le_inv g 0 N lam hlam hlamhalf
        (by simpa only [zero_add] using hinc) (by simpa only [zero_add] using hmono)
  · simpa only [phase, Erdos587.phase, zero_add] using
      norm_sum_phase_add_range_le_inv_of_antitone_pos g 0 N lam hlam hlamhalf
        (by simpa only [zero_add] using hinc) (by simpa only [zero_add] using hanti)
  · simpa only [phase, Erdos587.phase, zero_add] using
      norm_sum_phase_add_range_le_inv_of_monotone_neg g 0 N lam hlam hlamhalf
        (by simpa only [zero_add] using hinc) (by simpa only [zero_add] using hmono)
  · simpa only [phase, Erdos587.phase, zero_add] using
      norm_sum_phase_add_range_le_inv_of_antitone g 0 N lam hlam hlamhalf
        (by simpa only [zero_add] using hinc) (by simpa only [zero_add] using hanti)

/-- Controlled finite higher-derivative test with the terminal analytic
hypotheses stated explicitly.  In monomial applications the mixed
mean-value theorem above verifies `hleaf`; the conclusion then follows from
finite Weyl differencing and Kusmin--Landau with no asymptotic gap. -/
theorem norm_phaseSum_add_le_controlled_of_terminalIncrements
    (f : ℕ → ℝ) (a P : ℕ)
    (steps : List RestrictedWeyl.ConductorStep)
    (lam : ℝ) (hlam : 0 < lam) (hlamhalf : lam ≤ 1 / 2)
    (hleaf : ∀ leaf ∈
        RestrictedWeyl.offDiagonalHistoryLeaves
          steps [],
      TerminalIncrementCondition
        (iteratedPairDifference (fun n ↦ f (a + n)) leaf) P lam) :
    ‖∑ x ∈ Finset.range P, phase (f (a + x))‖ ≤
      RestrictedWeyl.finiteHistoryEnvelope
        P (1 / lam) steps := by
  apply norm_phaseSum_add_le_controlledHistoryEnvelope
    f a P steps (by positivity)
  intro leaf hleafMem
  exact norm_phaseSum_le_inv_of_terminalIncrementCondition
    _ P lam hlam hlamhalf (hleaf leaf hleafMem)

end HigherDerivative

end Erdos1149
