import ErdosProblems.Erdos118
import ErdosProblems.Erdos118.InterlacingAudit

/-! Audit the exact positive-three/negative-five counterexample, its
universal disproof, and the preserved auxiliary development. -/

#print axioms Erdos118.exists_cardinal_clique_iff
#print axioms Erdos118.cliqueFree_iff_no_cardinal_clique
#print axioms Erdos118.type_range
#print axioms Erdos118.exists_clique_type_iff
#print axioms Erdos118.exists_independent_type_iff
#print axioms Erdos118.partition_iff
#print axioms Erdos118.partition_iff_orderEmbedding
#print axioms Erdos118.not_partition_iff
#print axioms Erdos118.partition_mono_finite
#print axioms Erdos118.not_partition_mono_finite
#print axioms Erdos118.cliqueFree_comap
#print axioms Erdos118.not_partition_of_model
#print axioms Erdos118.neighborhood_type_lt
#print axioms Erdos118.card_lambda
#print axioms Erdos118.lambda_countable
#print axioms Erdos118.omega_lt_lambda
#print axioms Erdos118.same_cardinal_different_order_type
#print axioms Erdos118.lambda_eq_natural_inner_power
#print axioms Erdos118.counterexampleBlue_cliqueFree_six
#print axioms Erdos118.counterexampleBlue_meets_full_copy
#print axioms Erdos118.negative_six
#print axioms Erdos118.FrontierSteps.pair_swap
#print axioms Erdos118.FrontierSteps.split_joint
#print axioms Erdos118.FrontierSteps.joint_supported
#print axioms Erdos118.FrontierSteps.next_ne
#print axioms Erdos118.FrontierSteps.opposite_before
#print axioms Erdos118.FrontierSteps.advance_leaf
#print axioms Erdos118.FrontierSteps.advance_body
#print axioms Erdos118.FrontierSteps.finish
#print axioms Erdos118.FullScheduler.projection_jointCuts
#print axioms Erdos118.FullScheduler.pending
#print axioms Erdos118.FullScheduler.initial
#print axioms Erdos118.RedFamily.projected_clear
#print axioms Erdos118.RedFamily.vertex_root
#print axioms Erdos118.RedFamily.ordered_pair
#print axioms Erdos118.RedFamily.distinct_root_pair
#print axioms Erdos118.RedFamily.exists_full_family
#print axioms Erdos118.RedFamily.independent_of_initial_red
#print axioms Erdos118.RedFamily.independent_of_inside_red
#print axioms Erdos118.RedFamily.inside_blue_of_no_independent
#print axioms Erdos118.EdgeRefinement.red_or
#print axioms Erdos118.EdgeRefinement.blue_summand
#print axioms Erdos118.EdgeRefinement.edgeClass_cliqueFree
#print axioms Erdos118.EdgeRefinement.payoff_edgeClass_or
#print axioms Erdos118.EdgeRefinement.blue_edgeClass
#print axioms Erdos118.ProjectionBounds.body_label_pairwise
#print axioms Erdos118.IntrinsicAnnotations.completed_eq
#print axioms Erdos118.IntrinsicAnnotations.clear_pair_unique
#print axioms Erdos118.IntrinsicAnnotations.onVertices_iff
#print axioms Erdos118.IntrinsicAnnotations.color_symm
#print axioms Erdos118.IntrinsicAnnotations.color_at_clear
#print axioms Erdos118.IntrinsicAnnotations.class_test
#print axioms Erdos118.IntrinsicAnnotations.refine_test
#print axioms Erdos118.LastBodyRefinement.lastIndex_of_extension
#print axioms Erdos118.LastBodyRefinement.lastLabel_of_extension
#print axioms Erdos118.LastBodyRefinement.remaining_leaf_not_singleton
#print axioms Erdos118.LastBodyRefinement.not_all_singleton
#print axioms Erdos118.LastBodyRefinement.exists_refined
#print axioms Erdos118.LastBodyRefinement.pending_label_not_singleton
#print axioms Erdos118.LastBodyRefinement.positive_last_body
#print axioms Erdos118.InterlacingAudit.all_increasing
#print axioms Erdos118.InterlacingAudit.five_clique
#print axioms Erdos118.InterlacingAudit.not_cliqueFree_five
#print axioms Erdos118.BoundedNeighborhoods.step_of_small_neighborhoods
#print axioms Erdos118.BoundedNeighborhoods.exists_independent_of_small_neighborhoods
#print axioms Erdos118.BoundedNeighborhoods.not_large_of_type_lt
#print axioms Erdos118.BoundedNeighborhoods.comap_neighborhood_type_le
#print axioms Erdos118.BoundedNeighborhoods.omega_mul_nat_lt_omega_sq
#print axioms Erdos118.BoundedNeighborhoods.reservoir_mul_lambda
#print axioms Erdos118.BoundedNeighborhoods.omega_mul_lambda
#print axioms Erdos118.BoundedNeighborhoods.exists_independent_lambda_of_bounded_neighborhoods
#print axioms Erdos118.BoundedNeighborhoods.high_degree_set_type
#print axioms Erdos118.RamseyGame.almostSubset_of_subset
#print axioms Erdos118.RamseyGame.almostSubset_tail
#print axioms Erdos118.RamseyGame.diagonalPick_mem
#print axioms Erdos118.RamseyGame.diagonalPick_strictMono
#print axioms Erdos118.RamseyGame.infinite_pseudointersection
#print axioms Erdos118.RamseyGame.simultaneous_nat
#print axioms Erdos118.RamseyGame.simultaneous_countable
#print axioms Erdos118.RamseyGame.ResponseFamily.nonempty
#print axioms Erdos118.RamseyGame.ResponseFamily.conservative_exists
#print axioms Erdos118.RamseyGame.child_wellFounded
#print axioms Erdos118.RamseyGame.Outcome.almost_mono
#print axioms Erdos118.RamseyGame.dichotomy
#print axioms Erdos118.RamseyGame.Outcome.not_both
#print axioms Erdos118.RamseyGame.dichotomy_unique
#print axioms Erdos118.RamseyGame.outcome_leaf_iff
#print axioms Erdos118.RamseyGame.pairGame_triangle
#print axioms Erdos118.RamseyGame.pairGame_not_true
#print axioms Erdos118.RamseyGame.pairGame_red_thinning
#print axioms Erdos118.CoordinateModel.length_le_marker
#print axioms Erdos118.CoordinateModel.body_length
#print axioms Erdos118.CoordinateModel.q_lt_marker
#print axioms Erdos118.CoordinateModel.marker_lt_mem_body
#print axioms Erdos118.CoordinateModel.level_pairwise
#print axioms Erdos118.CoordinateModel.level_supported
#print axioms Erdos118.CoordinateModel.level_lt_lastBound
#print axioms Erdos118.CoordinateModel.normalizeTail_length
#print axioms Erdos118.CoordinateModel.normalizeTail_spec
#print axioms Erdos118.CoordinateModel.padded_length
#print axioms Erdos118.CoordinateModel.normalize_length
#print axioms Erdos118.CoordinateModel.normalize_good
#print axioms Erdos118.CoordinateModel.normalize_supported
#print axioms Erdos118.CoordinateModel.body_SL_mono
#print axioms Erdos118.CoordinateModel.normalizeTail_lex_mono
#print axioms Erdos118.CoordinateModel.normalize_mono
#print axioms Erdos118.CoordinateModel.type_supported
#print axioms Erdos118.WordResponses.levelWord_prefix_cancel
#print axioms Erdos118.WordResponses.flatMap_prefix_rigid
#print axioms Erdos118.WordResponses.word_prefix_rigid
#print axioms Erdos118.WordResponses.support_injective
#print axioms Erdos118.WordResponses.family_thin
#print axioms Erdos118.WordResponses.family_hits
#print axioms Erdos118.WordResponses.supportEquiv_apply
#print axioms Erdos118.WordResponses.support_symm
#print axioms Erdos118.WordResponses.supported_iff
#print axioms Erdos118.WordResponses.red_completion_thinning
#print axioms Erdos118.PartialWordResponses.completion_above
#print axioms Erdos118.PartialWordResponses.completionFamily_thin
#print axioms Erdos118.PartialWordResponses.completionFamily_hits
#print axioms Erdos118.RootInterleaving.singletonFamily_thin
#print axioms Erdos118.RootInterleaving.rootEquiv_apply
#print axioms Erdos118.RootInterleaving.assemble_word
#print axioms Erdos118.RootInterleaving.assemble_support
#print axioms Erdos118.RootInterleaving.response_outcome_iff
#print axioms Erdos118.RootInterleaving.root_high
#print axioms Erdos118.RootInterleaving.inside_triangle
#print axioms Erdos118.RootInterleaving.outside_triangle
#print axioms Erdos118.RootInterleaving.inside_red_outcome
#print axioms Erdos118.RootInterleaving.outside_red_outcome
#print axioms Erdos118.RootInterleaving.both_red_outcomes
#print axioms Erdos118.RootInterleaving.rootProtocol_pairGame
#print axioms Erdos118.SynchronizedRounds.triangle
#print axioms Erdos118.SynchronizedRounds.not_blue
#print axioms Erdos118.SynchronizedRounds.red_outcome
#print axioms Erdos118.SynchronizedRounds.simultaneous_red
#print axioms Erdos118.ConservativeAlphabet.sequence_strictMono
#print axioms Erdos118.ConservativeAlphabet.sequence_bound
#print axioms Erdos118.ConservativeAlphabet.exists_alphabet
#print axioms Erdos118.ConservativeAlphabet.exists_full_type_alphabet
#print axioms Erdos118.ConservativeAlphabet.separated_pairs_red
#print axioms Erdos118.RootAssembly.independent_of_triangleFree_product
#print axioms Erdos118.RootAssembly.reservoir_eq_theta_pow
#print axioms Erdos118.RootAssembly.reservoir_mul_self
#print axioms Erdos118.RootAssembly.omega_mul_reservoir
#print axioms Erdos118.RootAssembly.local_three
#print axioms Erdos118.RootAssembly.local_independent_subset
#print axioms Erdos118.RootAssembly.lambda_le_of_reservoir_bounds
#print axioms Erdos118.RootAssembly.increasing_large_roots
#print axioms Erdos118.RootAssembly.independent_of_red_global_pairs
#print axioms Erdos118.StructuralThinning.slice_strictMono
#print axioms Erdos118.StructuralThinning.slice_eq_iff
#print axioms Erdos118.StructuralThinning.allocated_disjoint
#print axioms Erdos118.StructuralThinning.normalize_length
#print axioms Erdos118.StructuralThinning.normalize_good
#print axioms Erdos118.StructuralThinning.normalize_allocated
#print axioms Erdos118.StructuralThinning.normalize_mono
#print axioms Erdos118.StructuralThinning.exists_disjoint_root_family
#print axioms Erdos118.StructuralThinning.shift_no_triangle
#print axioms Erdos118.StructuralThinning.shift_cliqueFree_three
#print axioms Erdos118.StructuralThinning.shift_adj_roots_ne
#print axioms Erdos118.StructuralThinning.forward_common_coordinate
#print axioms Erdos118.StructuralThinning.root_firstMarker_of_word
#print axioms Erdos118.StructuralThinning.shift_edge_in_every_alphabet
#print axioms Erdos118.StructuralThinning.shift_not_globally_red_on_alphabet
#print axioms Erdos118.StructuralThinning.shift_independent_full_type
#print axioms Erdos118.InteriorWords.fresh_list
#print axioms Erdos118.InteriorWords.start
#print axioms Erdos118.InteriorWords.advance_leaf
#print axioms Erdos118.InteriorWords.advance_body
#print axioms Erdos118.InteriorWords.complete
#print axioms Erdos118.PrefixOrder.flatMap_lex_mono
#print axioms Erdos118.PrefixOrder.word_lex_mono
#print axioms Erdos118.PrefixOrder.word_lex_iff
#print axioms Erdos118.PrefixOrder.code_nil
#print axioms Erdos118.PrefixOrder.code_append
#print axioms Erdos118.PrefixOrder.code_injective
#print axioms Erdos118.PrefixOrder.code_lt_child
#print axioms Erdos118.PrefixOrder.code_le_append
#print axioms Erdos118.PrefixOrder.code_lt_append
#print axioms Erdos118.PrefixOrder.code_siblings
#print axioms Erdos118.PrefixRealization.run_append
#print axioms Erdos118.PrefixRealization.run_entries
#print axioms Erdos118.PrefixRealization.run_bodies
#print axioms Erdos118.PrefixRealization.run_word
#print axioms Erdos118.PrefixRealization.run_word_terminal
#print axioms Erdos118.PrefixRealization.run_dead
#print axioms Erdos118.PrefixRealization.step_exists
#print axioms Erdos118.PrefixRealization.advance_phase
#print axioms Erdos118.PrefixRealization.advance_word
#print axioms Erdos118.PrefixRealization.decode_code
#print axioms Erdos118.PrefixRealization.code_decode
#print axioms Erdos118.PrefixRealization.parent_code_lt
#print axioms Erdos118.PrefixRealization.frame_nil
#print axioms Erdos118.PrefixRealization.frame_child
#print axioms Erdos118.PrefixRealization.frame_phase
#print axioms Erdos118.PrefixRealization.previousBound_ge
#print axioms Erdos118.PrefixRealization.block_spec
#print axioms Erdos118.PrefixRealization.live_of_next_ne_dead
#print axioms Erdos118.PrefixRealization.live_ne_dead
#print axioms Erdos118.PrefixRealization.ne_dead_of_run
#print axioms Erdos118.PrefixRealization.frame_prefix_append
#print axioms Erdos118.PrefixRealization.frame_prefix
#print axioms Erdos118.PrefixRealization.frame_supported
#print axioms Erdos118.PrefixRealization.terminalValue_word
#print axioms Erdos118.PrefixRealization.output_word
#print axioms Erdos118.PrefixRealization.output_supported
#print axioms Erdos118.PrefixRealization.lex_split
#print axioms Erdos118.PrefixRealization.output_mono
#print axioms Erdos118.PrefixRealization.output_range_type
#print axioms Erdos118.PrefixRealization.coordinate_block
#print axioms Erdos118.PrefixRealization.blocks_ordered
#print axioms Erdos118.PrefixRealization.head_eq_of_common_prefix
#print axioms Erdos118.PrefixRealization.block_separated_from_coordinate
#print axioms Erdos118.PrefixRealization.below_eq_self
#print axioms Erdos118.PrefixRealization.below_append_above
#print axioms Erdos118.PrefixRealization.below_frame_prefix
#print axioms Erdos118.PrefixRealization.live_of_proper_prefix
#print axioms Erdos118.PrefixRealization.output_interior_cut
#print axioms Erdos118.PrefixRealization.output_root_eq_of_length_eq
#print axioms Erdos118.PrefixRealization.output_support_disjoint
#print axioms Erdos118.PrefixRealization.exists_interior_family
#print axioms Erdos118.LabelledExtensions.ordinary_sublist_decorated
#print axioms Erdos118.LabelledExtensions.plain_decorated
#print axioms Erdos118.LabelledExtensions.plain_ordinary
#print axioms Erdos118.LabelledExtensions.Stem.ordinary_sublist
#print axioms Erdos118.LabelledExtensions.Stem.label_before_root
#print axioms Erdos118.LabelledExtensions.Stem.label_pairwise
#print axioms Erdos118.LabelledExtensions.Position.ordinary_sublist
#print axioms Erdos118.LabelledExtensions.Position.label_before_marker
#print axioms Erdos118.LabelledExtensions.Position.label_pairwise
#print axioms Erdos118.LabelledExtensions.Position.toInterior_word
#print axioms Erdos118.LabelledExtensions.empty_stem
#print axioms Erdos118.LabelledExtensions.fill_stem
#print axioms Erdos118.LabelledExtensions.start_body
#print axioms Erdos118.LabelledExtensions.advance_leaf
#print axioms Erdos118.LabelledExtensions.finish_body
#print axioms Erdos118.LabelledExtensions.fill_to_stem
#print axioms Erdos118.LabelledExtensions.Stem.toGood_word
#print axioms Erdos118.LabelledExtensions.complete
#print axioms Erdos118.LabelledExtensions.start
#print axioms Erdos118.LabelledExtensions.advance_body
#print axioms Erdos118.LabelledFrames.Slots.nil
#print axioms Erdos118.LabelledFrames.Slots.tail
#print axioms Erdos118.LabelledFrames.label_tail_slots
#print axioms Erdos118.LabelledFrames.first_mem
#print axioms Erdos118.LabelledFrames.start_pending
#print axioms Erdos118.LabelledFrames.step_exists
#print axioms Erdos118.LabelledExtensions.Stem.bodyLabels_prefix
#print axioms Erdos118.LabelledFrames.LabelsExtend.refl
#print axioms Erdos118.LabelledFrames.LabelsExtend.trans
#print axioms Erdos118.LabelledFrames.LabelsExtend.initial
#print axioms Erdos118.LabelledFrames.LabelsExtend.pending
#print axioms Erdos118.LabelledFrames.LabelsExtend.terminal
#print axioms Erdos118.LabelledFrames.step_preserving_exists
#print axioms Erdos118.LabelledRealization.ordinary_sublist
#print axioms Erdos118.LabelledRealization.decorated_pairwise
#print axioms Erdos118.LabelledRealization.advance_phase
#print axioms Erdos118.LabelledRealization.advance_spec
#print axioms Erdos118.LabelledRealization.frame_nil
#print axioms Erdos118.LabelledRealization.frame_child
#print axioms Erdos118.LabelledRealization.frame_phase
#print axioms Erdos118.LabelledRealization.previousBound_ge
#print axioms Erdos118.LabelledRealization.block_spec
#print axioms Erdos118.LabelledRealization.frame_prefix_append
#print axioms Erdos118.LabelledRealization.frame_prefix
#print axioms Erdos118.LabelledRealization.frame_supported
#print axioms Erdos118.LabelledRealization.terminalData_frame
#print axioms Erdos118.LabelledRealization.output_frame
#print axioms Erdos118.LabelledRealization.output_ordinary
#print axioms Erdos118.LabelledRealization.output_decorated
#print axioms Erdos118.LabelledRealization.vertex_word
#print axioms Erdos118.LabelledRealization.output_supported
#print axioms Erdos118.LabelledRealization.vertex_supported
#print axioms Erdos118.LabelledRealization.vertex_mono
#print axioms Erdos118.LabelledRealization.vertex_range_type
#print axioms Erdos118.LabelledRealization.decorated_coordinate_block
#print axioms Erdos118.LabelledRealization.blocks_ordered
#print axioms Erdos118.LabelledRealization.block_separated_from_coordinate
#print axioms Erdos118.LabelledRealization.below_frame_prefix_joint
#print axioms Erdos118.LabelledRealization.output_joint_cut
#print axioms Erdos118.LabelledRealization.vertex_root_eq_of_length_eq
#print axioms Erdos118.LabelledRealization.output_decorated_disjoint
#print axioms Erdos118.LabelledRealization.output_properties_of_roots_ne
#print axioms Erdos118.LabelCoarsening.filterBodies_length
#print axioms Erdos118.LabelCoarsening.filterBodies_ordinary
#print axioms Erdos118.LabelCoarsening.filterBodies_decorated
#print axioms Erdos118.LabelCoarsening.filterBodies_labels
#print axioms Erdos118.LabelCoarsening.filterLabels_prefix
#print axioms Erdos118.LabelCoarsening.coarsenStem_ordinary
#print axioms Erdos118.LabelCoarsening.coarsenStem_decorated
#print axioms Erdos118.LabelCoarsening.coarsenStem_labels
#print axioms Erdos118.LabelCoarsening.coarsenPosition_ordinary
#print axioms Erdos118.LabelCoarsening.coarsenPosition_decorated
#print axioms Erdos118.LabelCoarsening.coarsenPosition_labels
#print axioms Erdos118.LabelCoarsening.slots_filter
#print axioms Erdos118.LabelCoarsening.coarsenPending_extends
#print axioms Erdos118.LabelCoarsening.selected_root_mem
#print axioms Erdos118.LabelCoarsening.selected_body_mem
#print axioms Erdos118.LabelCoarsening.decorated_prefix_cancel
#print axioms Erdos118.LabelCoarsening.cutExtension_of_prefix
#print axioms Erdos118.LabelCoarsening.filterBodies_append
#print axioms Erdos118.LabelCoarsening.cutExtension_coarsen_split
#print axioms Erdos118.LabelCoarsening.below_split_bounds
#print axioms Erdos118.LabelCoarsening.coarsen_decorated_cut
#print axioms Erdos118.LabelCoarsening.rootKeep_true
#print axioms Erdos118.LabelCoarsening.bodyKeep_true
#print axioms Erdos118.LabelCoarsening.selected_root_exact
#print axioms Erdos118.LabelCoarsening.selected_body_exact
#print axioms Erdos118.LabelCoarsening.project_cut_family
#print axioms Erdos118.LabelCoarsening.project_joint_cut
#print axioms Erdos118.LabelCoarsening.finite_joint_cuts
#print axioms Erdos118.LabelCoarsening.project_thresholds
#print axioms Erdos118.LabelCoarsening.output_pair_projection
#print axioms Erdos118.BodyResponses.newWord_pairwise
#print axioms Erdos118.BodyResponses.newWord_prefix_cancel
#print axioms Erdos118.BodyResponses.setup_eq_of_prefix
#print axioms Erdos118.BodyResponses.support_injective
#print axioms Erdos118.BodyResponses.family_thin
#print axioms Erdos118.BodyResponses.setup_above
#print axioms Erdos118.BodyResponses.family_hits
#print axioms Erdos118.BodyResponses.supportEquiv_apply
#print axioms Erdos118.BodyResponses.support_symm
#print axioms Erdos118.BodyResponses.setup_decorated
#print axioms Erdos118.BodyResponses.setup_ordinary
#print axioms Erdos118.LabelledExtensions.fill_stem_plain
#print axioms Erdos118.RootResponses.bodies_eq_plain
#print axioms Erdos118.RootResponses.setup_eq_of_prefix
#print axioms Erdos118.RootResponses.Setup.room
#print axioms Erdos118.RootResponses.support_injective
#print axioms Erdos118.RootResponses.family_thin
#print axioms Erdos118.RootResponses.setup_above
#print axioms Erdos118.RootResponses.family_hits
#print axioms Erdos118.RootResponses.supportEquiv_apply
#print axioms Erdos118.RootResponses.support_symm
#print axioms Erdos118.RootResponses.toPending_phase
#print axioms Erdos118.StemResponses.bodies_eq_of_projections
#print axioms Erdos118.StemResponses.newWord_pairwise
#print axioms Erdos118.StemResponses.setup_eq_of_prefix
#print axioms Erdos118.StemResponses.support_injective
#print axioms Erdos118.StemResponses.family_thin
#print axioms Erdos118.StemResponses.setup_above
#print axioms Erdos118.StemResponses.family_hits
#print axioms Erdos118.StemResponses.supportEquiv_apply
#print axioms Erdos118.StemResponses.support_symm
#print axioms Erdos118.StemResponses.labels_prefix
#print axioms Erdos118.StemResponses.completed_word
#print axioms Erdos118.LeafResponses.newWord_pairwise
#print axioms Erdos118.LeafResponses.setup_eq_of_prefix
#print axioms Erdos118.LeafResponses.support_injective
#print axioms Erdos118.LeafResponses.family_thin
#print axioms Erdos118.LeafResponses.setup_above
#print axioms Erdos118.LeafResponses.family_hits
#print axioms Erdos118.LeafResponses.supportEquiv_apply
#print axioms Erdos118.LeafResponses.support_symm
#print axioms Erdos118.LeafResponses.newWord_ne_nil
#print axioms Erdos118.LeafResponses.position_length
#print axioms Erdos118.LeafResponses.position_decorated
#print axioms Erdos118.LeafResponses.position_ordinary
#print axioms Erdos118.LeafResponses.toPending_phase
#print axioms Erdos118.DecisionStates.next_body_bounds
#print axioms Erdos118.DecisionStates.ofGood_ordinary
#print axioms Erdos118.DecisionStates.ofGood_decorated
#print axioms Erdos118.DecisionStates.LabelsExtend.refl
#print axioms Erdos118.DecisionStates.LabelsExtend.trans
#print axioms Erdos118.DecisionStates.step_extensions
#print axioms Erdos118.DecisionStates.step_labels
#print axioms Erdos118.DecisionStates.rank_wellFounded
#print axioms Erdos118.DecisionStates.step_decreases
#print axioms Erdos118.DecisionStates.step_wellFounded
#print axioms Erdos118.DecisionStates.rankLT_add
#print axioms Erdos118.DecisionStates.addRank_comm
#print axioms Erdos118.DecisionStates.pairStep_decreases
#print axioms Erdos118.DecisionStates.pairStep_wellFounded
#print axioms Erdos118.AdaptiveGame.forgetBound_value
#print axioms Erdos118.AdaptiveGame.afterBound_large
#print axioms Erdos118.AdaptiveGame.Response.fresh_suffix
#print axioms Erdos118.AdaptiveGame.pairBound_left
#print axioms Erdos118.AdaptiveGame.pairBound_right
#print axioms Erdos118.AdaptiveGame.game_eq
#print axioms Erdos118.AdaptiveGame.game_complete
#print axioms Erdos118.AdaptiveGame.responseFor_none_iff
#print axioms Erdos118.AdaptiveGame.responseFor_available
#print axioms Erdos118.AdaptiveGame.outcome_thinning
#print axioms Erdos118.CutIndices.partial_bodies_injective
#print axioms Erdos118.CutIndices.interior_word_injective
#print axioms Erdos118.CutIndices.cut_congr
#print axioms Erdos118.CutIndices.jointCut_indices
#print axioms Erdos118.CutIndices.projection_interior
#print axioms Erdos118.CutIndices.projection_root_exact
#print axioms Erdos118.CutIndices.projection_body_exact
#print axioms Erdos118.CutIndices.projection_exact
#print axioms Erdos118.CutIndices.interiorCuts_congr_other
#print axioms Erdos118.CutIndices.exactAnnotations_congr_other
#print axioms Erdos118.CutIndices.output_pair_annotations
#print axioms Erdos118.ClearPairs.frame_empty_decorated
#print axioms Erdos118.ClearPairs.below_eq_nil_iff
#print axioms Erdos118.ClearPairs.below_sublist_empty
#print axioms Erdos118.ClearPairs.output_empty_cut
#print axioms Erdos118.ClearPairs.body_marker_mem
#print axioms Erdos118.ClearPairs.body_label_mem
#print axioms Erdos118.ClearPairs.foreign_ne
#print axioms Erdos118.ClearPairs.jointCut_body_separated
#print axioms Erdos118.ClearPairs.nodeSeparated_of_cuts
#print axioms Erdos118.ClearPairs.projection_emptyCuts
#print axioms Erdos118.ClearPairs.emptyCuts_congr_other
#print axioms Erdos118.ClearPairs.ClearPair.symm
#print axioms Erdos118.ClearPairs.ClearPair.roots_ne
#print axioms Erdos118.ClearPairs.clearPair_of_projections
#print axioms Erdos118.ClearPairs.output_pair_clear
#print axioms Erdos118.GraphPayoff.vertex_eq_of_ordinary_eq
#print axioms Erdos118.GraphPayoff.endpoint_mem
#print axioms Erdos118.GraphPayoff.endpoints_ne
#print axioms Erdos118.GraphPayoff.oriented_exists
#print axioms Erdos118.GraphPayoff.payoff_true_iff
#print axioms Erdos118.GraphPayoff.terminal_red
#print axioms Erdos118.GraphPayoff.terminal_red_of_both
#print axioms Erdos118.GraphPayoff.outcome_thinning
#print axioms Erdos118.ConservativeRuns.terminal_none_of_left_response
#print axioms Erdos118.ConservativeRuns.terminal_none_of_right_response
#print axioms Erdos118.ConservativeRuns.red_left_bound
#print axioms Erdos118.ConservativeRuns.red_right_bound
#print axioms Erdos118.ConservativeRuns.left_guard_exists
#print axioms Erdos118.ConservativeRuns.right_guard_exists
#print axioms Erdos118.ConservativeRuns.Step.preserves_red
#print axioms Erdos118.ConservativeRuns.Step.pairStep
#print axioms Erdos118.ConservativeRuns.Run.preserves_red
#print axioms Erdos118.ConservativeRuns.clear_terminal_red_of_runs
#print axioms Erdos118.SkippedCuts.partial_prefix_same_lengths
#print axioms Erdos118.SkippedCuts.interior_prefix_same_indices
#print axioms Erdos118.SkippedCuts.interior_common_prefix_same_indices
#print axioms Erdos118.SkippedCuts.cut_at_position
#print axioms Erdos118.SkippedCuts.no_cut_across_gap
#print axioms Erdos118.SkippedCuts.not_exact_of_gap
#print axioms Erdos118.SkippedCuts.state_ordinary_sublist
#print axioms Erdos118.SkippedCuts.StateExtension.refl
#print axioms Erdos118.SkippedCuts.StateExtension.trans
#print axioms Erdos118.SkippedCuts.stateExtension_of_step
#print axioms Erdos118.SkippedCuts.run_extensions
#print axioms Erdos118.SkippedCuts.run_right_future
#print axioms Erdos118.SkippedCuts.run_left_future
#print axioms Erdos118.SkippedCuts.response_ordinary_suffix
#print axioms Erdos118.SkippedCuts.consecutive_left_not_clear
#print axioms Erdos118.SkippedCuts.consecutive_right_not_clear
#print axioms Erdos118.BlueRuns.blue_command
#print axioms Erdos118.BlueRuns.blue_completion
#print axioms Erdos118.BlueRuns.consecutive_left_not_blue
#print axioms Erdos118.BlueRuns.consecutive_right_not_blue
#print axioms Erdos118.BlueRuns.handoff_after_left
#print axioms Erdos118.BlueRuns.handoff_after_right
#print axioms Erdos118.BlueRuns.not_leftBlue_complete
#print axioms Erdos118.BlueRuns.not_rightBlue_complete
#print axioms Erdos118.BlueRuns.body_response_pending
#print axioms Erdos118.BlueRuns.body_complete_not_blue
#print axioms Erdos118.BlueRuns.complete_body_not_blue
#print axioms Erdos118.BlueRuns.complete_initial_whole_blue
#print axioms Erdos118.WholeBlue.wholeMember_result
#print axioms Erdos118.WholeBlue.plain_vertex
#print axioms Erdos118.WholeBlue.whole_first_pairGame
#print axioms Erdos118.WholeBlue.whole_first_triangle
#print axioms Erdos118.WholeBlue.initial_root_blue
#print axioms Erdos118.LabelOverlays.shared_extreme_labels
#print axioms Erdos118.LabelOverlays.labels_before_ordinary
#print axioms Erdos118.LabelOverlays.plainStem_ordinary
#print axioms Erdos118.LabelOverlays.plainStem_decorated
#print axioms Erdos118.LabelOverlays.plainStem_supported
#print axioms Erdos118.LabelOverlays.plainStem_before_marker
#print axioms Erdos118.LabelOverlays.position_ordinary
#print axioms Erdos118.LabelOverlays.bodySetup_newWord
#print axioms Erdos118.ExactSlots.above_head
#print axioms Erdos118.ExactSlots.above_after_first
#print axioms Erdos118.ExactSlots.last_of_above_empty
#print axioms Erdos118.ExactSlots.step_exact
#print axioms Erdos118.ExactSlots.run_exact
#print axioms Erdos118.ExactSlots.pending_last_root
#print axioms Erdos118.ExactSlots.pending_last_leaf
#print axioms Erdos118.ReservedResponses.root_reserved
#print axioms Erdos118.ReservedResponses.body_reserved
#print axioms Erdos118.ReservedResponses.before_plain_overlay
#print axioms Erdos118.ReservedResponses.rootMember_value
#print axioms Erdos118.ReservedResponses.rootMember_result
#print axioms Erdos118.ReservedResponses.bodyMember_value
#print axioms Erdos118.ReservedResponses.bodyMember_result
#print axioms Erdos118.ReservedResponses.finishMember_value
#print axioms Erdos118.ReservedResponses.finishMember_result
#print axioms Erdos118.EndpointOrder.run_supported
#print axioms Erdos118.EndpointOrder.completed_ordinary_eq_of_prefix
#print axioms Erdos118.EndpointOrder.completed_endpoint_eq_of_prefix
#print axioms Erdos118.EndpointOrder.ordinary_le_endpoint
#print axioms Erdos118.EndpointOrder.outside_incomplete_complete_not_blue
#print axioms Erdos118.EndpointOrder.outside_right_root_blue
#print axioms Erdos118.EndpointOrder.leaf_step_cases
#print axioms Erdos118.EndpointOrder.leaf_complete_slots_empty
#print axioms Erdos118.EndpointOrder.complete_leaf_slots_empty
#print axioms Erdos118.SecondWhole.finish_selector
#print axioms Erdos118.SecondWhole.completion_edges
#print axioms Erdos118.SecondWhole.blue_pair_above
#print axioms Erdos118.SecondWhole.whole_second_triangle
#print axioms Erdos118.SecondWhole.second_root_blue
#print axioms Erdos118.BlueReservations.left_body_setups
#print axioms Erdos118.BlueReservations.right_body_setups
#print axioms Erdos118.BlueReservations.left_body_reserved
#print axioms Erdos118.BlueReservations.right_body_reserved
#print axioms Erdos118.BlueReservations.initial_root_reserved
#print axioms Erdos118.BlueReservations.second_root_reserved
#print axioms Erdos118.BlueCheckpoints.blue_stop
#print axioms Erdos118.BlueCheckpoints.left_last_leaf
#print axioms Erdos118.BlueCheckpoints.right_last_leaf
#print axioms Erdos118.BlueCheckpoints.left_last_body
#print axioms Erdos118.BlueCheckpoints.right_last_body
#print axioms Erdos118.CompletionReplay.run_supported_suffixes
#print axioms Erdos118.CompletionReplay.partial_completion_decompose
#print axioms Erdos118.CompletionReplay.setup_of_literal_completion
#print axioms Erdos118.CompletionReplay.left_finish_words
#print axioms Erdos118.CompletionReplay.right_finish_words
#print axioms Erdos118.CompletionReplay.completion_edges_of_word
#print axioms Erdos118.BlueReservations.initial_root_setups
#print axioms Erdos118.BlueCheckpoints.blue_stop_with_entry
#print axioms Erdos118.BlueCheckpoints.left_last_leaf_handoff
#print axioms Erdos118.BlueCheckpoints.right_last_leaf_handoff
#print axioms Erdos118.BlueCheckpoints.right_last_leaf_handoff_entry
#print axioms Erdos118.BoundaryRelays.run_last_body_left
#print axioms Erdos118.BoundaryRelays.run_last_body_right
#print axioms Erdos118.BoundaryRelays.body_last_root
#print axioms Erdos118.BoundaryRelays.rootAtLastBody_ordinary
#print axioms Erdos118.BoundaryRelays.rootAtLastBody_decorated
#print axioms Erdos118.BoundaryRelays.rootAtLastBody_supported
#print axioms Erdos118.BoundaryRelays.bodyAtLastLeaf_ordinary
#print axioms Erdos118.BoundaryRelays.bodyAtLastLeaf_newWord
#print axioms Erdos118.BlueRelays.left_root_relay
#print axioms Erdos118.BlueRelays.right_root_relay
#print axioms Erdos118.BlueRelays.left_last_body_relay
#print axioms Erdos118.BlueRelays.right_last_body_relay
#print axioms Erdos118.PreparedRelays.body_setups
#print axioms Erdos118.PreparedRelays.carry_left
#print axioms Erdos118.PreparedRelays.carry_right
#print axioms Erdos118.PreparedRelays.Prepared.setup_ordinary
#print axioms Erdos118.PreparedRelays.Prepared.setup_newWord
#print axioms Erdos118.PreparedRelays.fire
#print axioms Erdos118.PreparedRelays.prepare
#print axioms Erdos118.PreparedRelays.respond_body
#print axioms Erdos118.PreparedRelays.respond
#print axioms Erdos118.ManagedRelays.exists_initial
#print axioms Erdos118.ManagedRelays.Managed.exact
#print axioms Erdos118.ManagedRelays.Managed.working
#print axioms Erdos118.ManagedRelays.respond_body
#print axioms Erdos118.ManagedRelays.respond_leaf
#print axioms Erdos118.ManagedRelays.respond_side
#print axioms Erdos118.ManagedRelays.Managed.fire
#print axioms Erdos118.CoupledRelays.checkpoint
#print axioms Erdos118.CoupledRelays.forks_of_managed
#print axioms Erdos118.CoupledRelays.initial_forks
#print axioms Erdos118.ExactSlots.run_exact_left
#print axioms Erdos118.ExactSlots.run_exact_right
#print axioms Erdos118.CompletionReplay.right_completion_edges_of_word
#print axioms Erdos118.PreparedRelays.carry_left_of_run
#print axioms Erdos118.PreparedRelays.carry_right_of_run
#print axioms Erdos118.PreparedRelays.respond_body_on
#print axioms Erdos118.PreparedRelays.respond_on
#print axioms Erdos118.BlueReservations.second_root_setups
#print axioms Erdos118.OutsideEndgame.last_right_not_rightBlue
#print axioms Erdos118.OutsideEndgame.body_last_not_blue
#print axioms Erdos118.OutsideEndgame.last_right_left_command
#print axioms Erdos118.OutsideEndgame.last_right_leftBlue
#print axioms Erdos118.RightRelays.right_body_ready
#print axioms Erdos118.RightRelays.root_relay
#print axioms Erdos118.RightRelays.last_body_relay
#print axioms Erdos118.RightRelays.root_to_last
#print axioms Erdos118.OutsideTriangle.triangle_of_forks
#print axioms Erdos118.OutsideTriangle.initial_not_blue
#print axioms Erdos118.OutsideTriangle.red_outcome
#print axioms Erdos118.InsideEndgame.complete_incomplete_not_blue
#print axioms Erdos118.InsideEndgame.last_left_not_leftBlue
#print axioms Erdos118.InsideEndgame.last_body_not_blue
#print axioms Erdos118.InsideEndgame.last_left_right_command
#print axioms Erdos118.InsideEndgame.last_left_rightBlue
#print axioms Erdos118.LeafReplay.setup_of_position
#print axioms Erdos118.LeafReplay.selector
#print axioms Erdos118.LeafReplay.member_result
#print axioms Erdos118.LeafReplay.left_leaf_words
#print axioms Erdos118.LeafReplay.right_leaf_words
#print axioms Erdos118.BoundaryRelays.run_last_body_left_cases
#print axioms Erdos118.ExactSlots.pending_next_last
#print axioms Erdos118.InsideEndgame.last_right_command_left_last
#print axioms Erdos118.InsideEndgame.advance_last_left
#print axioms Erdos118.InsideEndgame.penultimate_left
#print axioms Erdos118.LeafReplay.left_leaf_words_slots
#print axioms Erdos118.SharedLast.labels
#print axioms Erdos118.SharedLast.body_reserved
#print axioms Erdos118.SharedLast.Reserve.buffer
#print axioms Erdos118.InitialRelays.root_to_last_first
#print axioms Erdos118.InitialRelays.root_to_last_first_nonbody
#print axioms Erdos118.InsideCompletion.triangle
#print axioms Erdos118.InsideSingleton.triangle_of_reserve
#print axioms Erdos118.InsideSingleton.no_singleton_root_certificate
#print axioms Erdos118.InsideSingleton.initial_root_setups_at_least_two
#print axioms Erdos118.InsideEndgame.last_right_body_setups
#print axioms Erdos118.InsideEndgame.last_right_body_roots
#print axioms Erdos118.InsideEndgame.last_right_pending_cases
#print axioms Erdos118.CompletionReplay.setup_of_literal_stem
#print axioms Erdos118.StemReplay.selector
#print axioms Erdos118.StemReplay.member_result
#print axioms Erdos118.StemReplay.left_body_words
#print axioms Erdos118.ExactSlots.pending_next_last_root
#print axioms Erdos118.RootBuffer.root_reserved
#print axioms Erdos118.RootBuffer.Reserve.buffer
#print axioms Erdos118.PreparedRelays.command_allowed
#print axioms Erdos118.PreparedRelays.body_handoff
#print axioms Erdos118.PreparedRelays.body_step
#print axioms Erdos118.BodyReplay.Prepared.setup_ordinary
#print axioms Erdos118.BodyReplay.Prepared.setup_newWord
#print axioms Erdos118.BodyReplay.fire
#print axioms Erdos118.BodyReplay.carry_of_run
#print axioms Erdos118.BodyReplay.prepare
#print axioms Erdos118.ReplaySources.Source.resolve
#print axioms Erdos118.RetainedController.Managed.exact
#print axioms Erdos118.RetainedController.Managed.working
#print axioms Erdos118.RetainedController.respond_body
#print axioms Erdos118.RetainedController.respond_leaf
#print axioms Erdos118.RetainedController.respond_side
#print axioms Erdos118.RetainedController.checkpoint
#print axioms Erdos118.RetainedController.Managed.fire
#print axioms Erdos118.InsideRootBody.triangle_of_reserve
#print axioms Erdos118.InsideRootLeaf.initial_remaining_leaf
#print axioms Erdos118.CommonFirst.root_setups
#print axioms Erdos118.CommonFirst.body_setups
#print axioms Erdos118.JointOpening.respond_bodies
#print axioms Erdos118.JointOpening.initial_opening
#print axioms Erdos118.JointMoves.ordinary_components
#print axioms Erdos118.JointMoves.respond_leaves
#print axioms Erdos118.JointMoves.respond_stems
#print axioms Erdos118.JointMoves.respond_next_bodies
#print axioms Erdos118.JointFinish.triangle_of_completed_right
#print axioms Erdos118.JointFinish.triangle_of_last_right
#print axioms Erdos118.JointAlignment.kind_eq_finish_iff
#print axioms Erdos118.JointAlignment.Aligned.remaining
#print axioms Erdos118.JointAlignment.Aligned.next_cases
#print axioms Erdos118.JointAlignment.Aligned.advance
#print axioms Erdos118.JointController.Reach.refl
#print axioms Erdos118.JointController.Reach.trans
#print axioms Erdos118.JointController.less_wellFounded
#print axioms Erdos118.JointController.matching_step
#print axioms Erdos118.JointController.checkpoint
#print axioms Erdos118.JointController.initial_checkpoint
#print axioms Erdos118.JointMoves.leaf_bound
#print axioms Erdos118.FreshCheckpoints.blue_stop_above
#print axioms Erdos118.CurrentBody.left_last
#print axioms Erdos118.CurrentBody.right_last
#print axioms Erdos118.CurrentBody.last_on
#print axioms Erdos118.BufferedLeaf.current_body_replay
#print axioms Erdos118.JointMoves.stem_bound
#print axioms Erdos118.ReversedForks.exists_forks
#print axioms Erdos118.OverlapFinish.right_extension_triangle
#print axioms Erdos118.LeafForkTriangle.triangle
#print axioms Erdos118.FreshBodyCheckpoint.left_last
#print axioms Erdos118.RootForkTriangle.triangle
#print axioms Erdos118.RootOverlap.root_setups
#print axioms Erdos118.FirstBody.certificate_exists
#print axioms Erdos118.FirstBody.no_uniform_singleton
#print axioms Erdos118.FirstBody.positive_parameters
#print axioms Erdos118.FiniteGuards.statesOn_finite
#print axioms Erdos118.FiniteGuards.envelope_bounds
#print axioms Erdos118.FiniteGuards.exists_alphabet
#print axioms Erdos118.FiniteGuards.exists_anchored_alphabet
#print axioms Erdos118.FrameAnchors.root_slots_bound
#print axioms Erdos118.FrameAnchors.leaf_slots_bound
#print axioms Erdos118.FrameAnchors.root_sibling_anchor
#print axioms Erdos118.FrameAnchors.body_sibling_anchor
#print axioms Erdos118.SizedExtensions.fill_to_stem_labels
#print axioms Erdos118.SizedExtensions.complete_labels
#print axioms Erdos118.SizedExtensions.start_labels
#print axioms Erdos118.SizedExtensions.advance_body_labels
#print axioms Erdos118.LabelledFrames.start_pending_budget
#print axioms Erdos118.LabelledFrames.step_budget_exists
#print axioms Erdos118.LabelledRealization.advance_budget
#print axioms Erdos118.LabelledRealization.frame_budget
#print axioms Erdos118.LabelOrigins.output_root_label_length
#print axioms Erdos118.LabelOrigins.output_root_label_block
#print axioms Erdos118.LabelOrigins.output_root_projected_command
#print axioms Erdos118.LabelOrigins.frame_body_origin
#print axioms Erdos118.LabelOrigins.output_body_label_origin
#print axioms Erdos118.LabelOrigins.output_body_projected_command
#print axioms Erdos118.ProjectionBounds.projection_root_sublist
#print axioms Erdos118.ProjectionBounds.projection_body_sublist
#print axioms Erdos118.ProjectionBounds.projection_root_command
#print axioms Erdos118.ProjectionBounds.projection_body_command
#print axioms Erdos118.CutOrder.partial_prefix_counts
#print axioms Erdos118.CutOrder.interior_prefix_counts
#print axioms Erdos118.CutOrder.below_prefix
#print axioms Erdos118.CutOrder.first_cut_bounds
#print axioms Erdos118.FirstCutFronts.first_root_head
#print axioms Erdos118.FirstCutFronts.first_leaf_head
#print axioms Erdos118.FirstCutFronts.earlier_bodies_plain
#print axioms Erdos118.FirstCutFronts.first_fronts
#print axioms Erdos118.FiniteGuards.Sparse.mono
#print axioms Erdos118.FiniteGuards.exists_graph_alphabet
#print axioms Erdos118.FirstCutRun.initial
#print axioms Erdos118.WholeCutRun.no_cuts_of_before_root
#print axioms Erdos118.WholeCutRun.no_reverse_cuts_of_before_root
#print axioms Erdos118.WholeCutRun.annotations_empty_of_no_cuts
#print axioms Erdos118.WholeCutRun.ofGood_eq
#print axioms Erdos118.WholeCutRun.decorated_eq_ordinary
#print axioms Erdos118.WholeCutRun.whole_step
#print axioms Erdos118.WholeCutRun.separated_run
#print axioms Erdos118.InitialSplit.jointCut_of_position_eq
#print axioms Erdos118.InitialSplit.initial
#print axioms Erdos118.NextLeafCuts.same_body
#print axioms Erdos118.NextLeafCuts.setup_of_same_body
#print axioms Erdos118.NextLeafCuts.retained_leaf
#print axioms Erdos118.NextLeafCuts.next_leaf_minimal
#print axioms Erdos118.NextLeafCuts.leaf_step
#print axioms Erdos118.FinalCutRun.later_label_empty
#print axioms Erdos118.FinalCutRun.completion_labels
#print axioms Erdos118.FinalCutRun.completed_stem_eq
#print axioms Erdos118.FinalCutRun.completion_setup
#print axioms Erdos118.FinalCutRun.finish_step
#print axioms Erdos118.NextBodyCuts.next_root_minimal
#print axioms Erdos118.NextBodyCuts.between_label_empty
#print axioms Erdos118.NextBodyCuts.stem_eq_of_ordinary_labels
#print axioms Erdos118.NextBodyCuts.earlier_stem_extension
#print axioms Erdos118.NextBodyCuts.intermediate_labels
#print axioms Erdos118.NextBodyCuts.next_stem_setup
#print axioms Erdos118.NextBodyCuts.first_cut_at_body
#print axioms Erdos118.NextBodyCuts.retained_body
#print axioms Erdos118.NextBodyRun.stem_step
#print axioms Erdos118.NextBodyRun.projection_body_anchor
#print axioms Erdos118.NextBodyRun.two_steps
#print axioms Erdos118.CutSuccessors.prefix_of_indices
#print axioms Erdos118.CutSuccessors.indices_of_length
#print axioms Erdos118.CutSuccessors.empty_roots_bound
#print axioms Erdos118.CutSuccessors.empty_leaves_bound
#print axioms Erdos118.CutSuccessors.leaf_successor
#print axioms Erdos118.CutSuccessors.body_successor
#print axioms Erdos118.CutSuccessors.last_no_successor
#print axioms Erdos118.CutFrontiers.joint_cut_length
#print axioms Erdos118.CutFrontiers.joint_cut_proper
#print axioms Erdos118.CutFrontiers.next_threshold
#print axioms Erdos118.CutFrontiers.successor_eq_frontier
#print axioms Erdos118.DecoratedFrontiers.stem_dominated
#print axioms Erdos118.DecoratedFrontiers.position_dominated
#print axioms Erdos118.DecoratedFrontiers.state_dominated
#print axioms Erdos118.DecoratedFrontiers.whole_after_foreign
#print axioms Erdos118.DecoratedFrontiers.pending_suffix_after_foreign
#print axioms Erdos118.DecoratedFrontiers.response_after_state
#print axioms Erdos118.DecoratedFrontiers.joint_cut_retarget
#print axioms Erdos118.OpeningFronts.cut_minimal_of_split
#print axioms Erdos118.OpeningFronts.fronts_of_minimal
#print axioms Erdos118.OpeningRun.initial
#print axioms Erdos118.SecondOpening.initial
#print axioms Erdos118.TerminalFrontiers.slots_empty_of_prefixes
#print axioms Erdos118.TerminalFrontiers.before_next_slots
#print axioms Erdos118.TerminalFrontiers.finish_after_complete
#print axioms Erdos118.TerminalFrontiers.last_before_next

#print axioms Erdos118.LastMarkerRefinement.lastIndex_lt
#print axioms Erdos118.LastMarkerRefinement.lastMarker_mem
#print axioms Erdos118.LastMarkerRefinement.lastMarker_of_extension
#print axioms Erdos118.LastMarkerRefinement.lastMarkers_ne
#print axioms Erdos118.LastMarkerRefinement.pending_sizes_ne
#print axioms Erdos118.LastMarkerRefinement.payoff_true_mono
#print axioms Erdos118.LastMarkerRefinement.exists_refined
#print axioms Erdos118.LastMarkerRefinement.pending_order
#print axioms Erdos118.GapCounts.mem_gaps
#print axioms Erdos118.GapCounts.count_balance
#print axioms Erdos118.GapCounts.count_inside
#print axioms Erdos118.GapCounts.gap_drop_iff
#print axioms Erdos118.GapCounts.gaps_drop_card
#print axioms Erdos118.GapCounts.suffix_counts_of_head_lt
#print axioms Erdos118.GapCounts.suffix_counts_of_head_gt
#print axioms Erdos118.GapPrefixes.below_length_of_between
#print axioms Erdos118.GapPrefixes.between_of_below_length
#print axioms Erdos118.GapPrefixes.gap_iff_below_length
#print axioms Erdos118.GapPrefixes.interior_prefix_length_injective
#print axioms Erdos118.GapPrefixes.gap_iff_cut_length
#print axioms Erdos118.SelectedGapCounts.mem_selected
#print axioms Erdos118.SelectedGapCounts.interior_prefix_root
#print axioms Erdos118.SelectedGapCounts.interior_prefix_body_bound
#print axioms Erdos118.SelectedGapCounts.gaps_card_eq_selected
#print axioms Erdos118.SelectedGapCounts.selected_card
#print axioms Erdos118.InsideCounts.ordinary_disjoint
#print axioms Erdos118.InsideCounts.selected_index_le_last
#print axioms Erdos118.InsideCounts.selected_card_decomposition
#print axioms Erdos118.InsideCounts.selected_inside
#print axioms Erdos118.InsideCounts.inside_decomposition
#print axioms Erdos118.InsideCounts.last_counts_of_before_eq
#print axioms Erdos118.InsideCounts.last_counts_of_before_lt
#print axioms Erdos118.BodySuffixCounts.partial_prefix_length_cutoff
#print axioms Erdos118.BodySuffixCounts.interior_length_cutoff
#print axioms Erdos118.BodySuffixCounts.gaps_filtered_card
#print axioms Erdos118.BodySuffixCounts.suffix_gaps_card
#print axioms Erdos118.LastSuffixCounts.ordinary_split
#print axioms Erdos118.LastSuffixCounts.suffix_eq_drop
#print axioms Erdos118.LastSuffixCounts.suffix_ne_nil
#print axioms Erdos118.LastSuffixCounts.suffix_head
#print axioms Erdos118.LastSuffixCounts.suffix_last
#print axioms Erdos118.LastSuffixCounts.suffix_count
#print axioms Erdos118.LastSuffixCounts.last_counts_of_marker_lt
#print axioms Erdos118.LastSuffixCounts.last_counts_of_marker_gt
#print axioms Erdos118.LastSuffixCounts.marker_lt_iff_before_le
#print axioms Erdos118.PendingCounts.selected_filter_of_prefix
#print axioms Erdos118.PendingCounts.beforeLast_of_extension
#print axioms Erdos118.PendingCounts.rootLabel_ne_nil_of_extension
#print axioms Erdos118.PendingCounts.inside_count
#print axioms Erdos118.PendingCounts.marker_lt_iff_count_le

#print axioms Erdos118.FirstBodyRefinement.firstIndex_of_extension
#print axioms Erdos118.FirstBodyRefinement.firstLabel_of_extension
#print axioms Erdos118.FirstBodyRefinement.first_body
#print axioms Erdos118.FirstBodyRefinement.not_all_singleton
#print axioms Erdos118.FirstBodyRefinement.exists_refined
#print axioms Erdos118.FirstBodyRefinement.certificate_positive
#print axioms Erdos118.FirstBodyRefinement.positive_certificate
#print axioms Erdos118.EndpointRefinement.exists_refined
#print axioms Erdos118.FutureLastMarkers.lastIndex_gt_of_roots
#print axioms Erdos118.FutureLastMarkers.old_decorated_lt_lastMarker
#print axioms Erdos118.FutureLastMarkers.late_right_roots_nil
#print axioms Erdos118.LateMarkerCritical.remaining_leaves_label_gt_one
#print axioms Erdos118.LateMarkerCritical.last_body_right_roots_nil
#print axioms Erdos118.LateMarkerCritical.last_body_right_nonlast
#print axioms Erdos118.LateMarkerCritical.before_last_body_right_nonlast
#print axioms Erdos118.DeferredBodyReplay.current_lt_last
#print axioms Erdos118.DeferredBodyReplay.Prepared.label_length
#print axioms Erdos118.DeferredBodyReplay.Prepared.label_increasing
#print axioms Erdos118.DeferredBodyReplay.Prepared.label_below
#print axioms Erdos118.DeferredBodyReplay.Prepared.label_fresh
#print axioms Erdos118.DeferredBodyReplay.Prepared.second_index
#print axioms Erdos118.DeferredBodyReplay.Prepared.next_index
#print axioms Erdos118.DeferredBodyReplay.Prepared.setup_ordinary
#print axioms Erdos118.DeferredBodyReplay.Prepared.setup_newWord
#print axioms Erdos118.DeferredBodyReplay.fire
#print axioms Erdos118.DeferredBodyReplay.carry_of_run
#print axioms Erdos118.DeferredBodyReplay.prepare

#print axioms Erdos118.DeferredManaged.Managed.exact
#print axioms Erdos118.DeferredManaged.Managed.working
#print axioms Erdos118.DeferredManaged.respond_body
#print axioms Erdos118.DeferredManaged.response_ordinary_fresh
#print axioms Erdos118.DeferredManaged.before_last_not_blue_complete
#print axioms Erdos118.DeferredManaged.respond_right_leaf_with_handoff
#print axioms Erdos118.DeferredManaged.respond_right_leaf
#print axioms Erdos118.DeferredManaged.respond_right
#print axioms Erdos118.DeferredManaged.Managed.fire
#print axioms Erdos118.ManagedCritical.early_before
#print axioms Erdos118.ManagedCritical.early_step
#print axioms Erdos118.ManagedCritical.early_nonterminal
#print axioms Erdos118.ManagedCritical.stop_with_entry
#print axioms Erdos118.ManagedCritical.stop_handoff
#print axioms Erdos118.ManagedCritical.right_leaf_handoff
#print axioms Erdos118.ManagedCritical.right_handoff
#print axioms Erdos118.ManagedCritical.initialReplay
#print axioms Erdos118.ManagedCritical.critical_replay
#print axioms Erdos118.ManagedOpening.initial_critical_replay
#print axioms Erdos118.SingletonBodyReplay.Prepared.setup_ordinary
#print axioms Erdos118.SingletonBodyReplay.Prepared.setup_newWord
#print axioms Erdos118.SingletonBodyReplay.fire
#print axioms Erdos118.SingletonBodyReplay.carry_of_run
#print axioms Erdos118.SingletonBodyReplay.prepare
#print axioms Erdos118.OptionalBodyReplay.Prepared.lastRoot
#print axioms Erdos118.OptionalBodyReplay.Prepared.exactSlots
#print axioms Erdos118.OptionalBodyReplay.fire
#print axioms Erdos118.OptionalBodyReplay.carry_of_run
#print axioms Erdos118.OptionalBodyReplay.prepare
#print axioms Erdos118.FreshCheckpoints.response_suffix
#print axioms Erdos118.ReplaySources.body_command
#print axioms Erdos118.ReplaySources.Source.resolve_exact
#print axioms Erdos118.StemReplay.left_body_words_step
#print axioms Erdos118.SharedLast.labels_sizes
#print axioms Erdos118.SharedLast.body_reserved_sizes
#print axioms Erdos118.DeferredSource.Managed.exact
#print axioms Erdos118.DeferredSource.Managed.working
#print axioms Erdos118.DeferredSource.respond_body
#print axioms Erdos118.DeferredSource.respond_right_leaf
#print axioms Erdos118.DeferredSource.respond_right
#print axioms Erdos118.DeferredSource.right_leaf_handoff
#print axioms Erdos118.DeferredSource.right_handoff
#print axioms Erdos118.DeferredSource.Managed.fire
#print axioms Erdos118.ControlledCritical.stop_with_entry
#print axioms Erdos118.ControlledCritical.stop_handoff
#print axioms Erdos118.SourceCritical.checkpoint
#print axioms Erdos118.RootInsertion.inserted_checkpoint
#print axioms Erdos118.InsertedAlignment.certificate
#print axioms Erdos118.InsertedAlignment.align
#print axioms Erdos118.InsertedAlignment.positive_body
#print axioms Erdos118.LateOpening.exists_opening
#print axioms Erdos118.FreshCheckpoints.fresh_refl
#print axioms Erdos118.FreshCheckpoints.fresh_trans
#print axioms Erdos118.SelectedLeafResponses.certificate_on
#print axioms Erdos118.SelectedLeafResponses.respond
#print axioms Erdos118.MiddleRun.final_left_test
#print axioms Erdos118.MiddleRun.stop
#print axioms Erdos118.MiddleRun.endpoint
#print axioms Erdos118.NextSelectedLeaf.above_first
#print axioms Erdos118.NextSelectedLeaf.next_leaf
#print axioms Erdos118.NextSelectedLeaf.first_roots_nonempty
#print axioms Erdos118.NextSelectedLeaf.ordinary_parts
#print axioms Erdos118.SelectedLeafReplay.exists_certificate
#print axioms Erdos118.SelectedLeafReplay.Certificate.fire
#print axioms Erdos118.SelectedLeafReplay.Certificate.fire_last
#print axioms Erdos118.FirstMiddle.exists_diagram
#print axioms Erdos118.BodyRebase.setup_ordinary
#print axioms Erdos118.BodyRebase.setup_newWord
#print axioms Erdos118.FineBody.exists_response
#print axioms Erdos118.SecondMiddle.exists_last_pair
#print axioms Erdos118.TwoMiddlePositive.triangle
#print axioms Erdos118.StemReplay.right_body_words_step
#print axioms Erdos118.SingletonMiddleRequest.singleton
#print axioms Erdos118.SingletonMiddleRequest.slots
#print axioms Erdos118.SingletonMiddleRequest.exists_request
#print axioms Erdos118.InsideRightCompletion.triangle
#print axioms Erdos118.SingletonMiddleCompletion.extension
#print axioms Erdos118.SingletonMiddleCompletion.triangle
#print axioms Erdos118.LateMarkerExclusion.not_blue
#print axioms Erdos118.TerminalCountRefinement.selected_empty_of_root_nil
#print axioms Erdos118.TerminalCountRefinement.lastLabel_nonempty
#print axioms Erdos118.TerminalCountRefinement.roots_nonempty
#print axioms Erdos118.TerminalCountRefinement.exists_early
#print axioms Erdos118.TerminalCountRefinement.exists_alternative
#print axioms Erdos118.TerminalCountRefinement.pending_alternative
#print axioms Erdos118.TerminalCountRefinement.pending_label_sizes
#print axioms Erdos118.LeafSuffixCounts.interior_length_le_iff
#print axioms Erdos118.LeafSuffixCounts.interior_suffix_cutoff
#print axioms Erdos118.LeafSuffixCounts.gaps_filtered_card
#print axioms Erdos118.LeafSuffixCounts.suffix_gaps_card
#print axioms Erdos118.GapCounts.gaps_cons_card
#print axioms Erdos118.GapCounts.gaps_singleton_left
#print axioms Erdos118.GapCounts.gaps_append_right_below
#print axioms Erdos118.GapCounts.prefix_below_other_of_head_lt
#print axioms Erdos118.ConsecutiveSuffixCounts.append_before_crossing
#print axioms Erdos118.ConsecutiveSuffixCounts.balance
#print axioms Erdos118.SelectedEndpointCounts.lastFiber_card
#print axioms Erdos118.SelectedEndpointCounts.remaining_last_le
#print axioms Erdos118.SelectedEndpointCounts.remaining_card_iff
#print axioms Erdos118.PendingSuffixBalance.exists_completion
#print axioms Erdos118.PendingEndpointCounts.criterion
#print axioms Erdos118.AlignedEndpoint.critical_iff

#print axioms Erdos118.CurrentBody.right_last_entry
#print axioms Erdos118.AlignedRootCounts.beforeLast_pos_iff
#print axioms Erdos118.AlignedRootCounts.right_root_length
#print axioms Erdos118.AlignedRootCounts.right_setup_positive
#print axioms Erdos118.AlignedRootCounts.second_root_setups
#print axioms Erdos118.AlignedRootReserve.labels
#print axioms Erdos118.AlignedRootReserve.root_reserved
#print axioms Erdos118.AlignedRootReserve.Reserve.above_shared
#print axioms Erdos118.AlignedRootReserve.Reserve.pending_iff
#print axioms Erdos118.AlignedRootReserve.Reserve.rootSetup_ordinary
#print axioms Erdos118.AlignedRootReserve.Reserve.rootSetup_supported
#print axioms Erdos118.CurrentBodyReplay.carry_of_run
#print axioms Erdos118.CurrentBodyReplay.Prepared.setup_ordinary
#print axioms Erdos118.CurrentBodyReplay.Prepared.setup_newWord
#print axioms Erdos118.CurrentBodyReplay.fire
#print axioms Erdos118.CurrentBodyReplay.prepare
#print axioms Erdos118.RootBodyCheckpoint.before_step
#print axioms Erdos118.RootBodyCheckpoint.root_before
#print axioms Erdos118.RootBodyCheckpoint.right
#print axioms Erdos118.AlignedCurrentCheckpoint.right_critical
#print axioms Erdos118.AlignedRootPreparation.at_shared
#print axioms Erdos118.AlignedRootPreparation.response_endpoint
#print axioms Erdos118.AlignedRootPreparation.checkpoint
#print axioms Erdos118.AlignedOpening.initial_critical_replay

#print axioms Erdos118.AlignedRightPreparation.at_shared
#print axioms Erdos118.AlignedRightPreparation.checkpoint
#print axioms Erdos118.AlignedInsertion.inserted_checkpoint
#print axioms Erdos118.AlignedLastOpening.exists_opening
#print axioms Erdos118.SharedFirstLast.labels
#print axioms Erdos118.SharedFirstLast.body_pair
#print axioms Erdos118.AlignedFirstBodies.Pair.exactSlots
#print axioms Erdos118.AlignedFirstBodies.Pair.roots_nil
#print axioms Erdos118.AlignedFirstBodies.Pair.leaves_nonempty
#print axioms Erdos118.AlignedFirstBodies.exists_pair
#print axioms Erdos118.AlignedFirstBodies.Pair.requests
#print axioms Erdos118.AlignedPenultimateRun.right
#print axioms Erdos118.AlignedThirdRun.right_body_endpoint
#print axioms Erdos118.AlignedThirdRun.checkpoint
#print axioms Erdos118.AlignedBodyCounts.pending
#print axioms Erdos118.AlignedBodyCounts.right_certificate
#print axioms Erdos118.AlignedMarkerBridge.align
#print axioms Erdos118.AlignedBridgeDiagram.exists_diagram
#print axioms Erdos118.RightLastRefinement.exists_refined
#print axioms Erdos118.RightLastRefinement.right_certificate

#print axioms Erdos118.SharedFirstLast.labels_separated
#print axioms Erdos118.SharedFirstLast.body_pair_of_labels
#print axioms Erdos118.SharedFirstLast.body_pair_separated
#print axioms Erdos118.SharedFirstSecond.labels
#print axioms Erdos118.SharedFirstSecond.body_pair
#print axioms Erdos118.AlignedSecondMarker.align
#print axioms Erdos118.PairedFirstSecond.Pair.exactSlots
#print axioms Erdos118.PairedFirstSecond.Pair.next_upper
#print axioms Erdos118.PairedFirstSecond.exists_pair
#print axioms Erdos118.AlignedAllBodies.exists_t_pair
#print axioms Erdos118.AlignedAllBodies.exists_u_certificates
#print axioms Erdos118.AlignedAllBodies.exists_u_pair
#print axioms Erdos118.SharedFinalLeaf.triangle
#print axioms Erdos118.AlignedSingletonEnding.triangle
#print axioms Erdos118.SelectedLeafReplay.Certificate.buffer
#print axioms Erdos118.AlignedPositiveEnding.triangle
#print axioms Erdos118.AlignedExclusion.not_blue
#print axioms Erdos118.AlignedExclusion.exists_strict

#print axioms Erdos118.CriticalPair.suffix_card_lt
#print axioms Erdos118.CriticalPair.Spec.unique
#print axioms Erdos118.CriticalPair.exists_spec
#print axioms Erdos118.CriticalPair.pair_eq_of_spec
#print axioms Erdos118.CriticalPair.pair_spec
#print axioms Erdos118.CriticalPair.bodyRank_le
#print axioms Erdos118.CriticalPair.leafRank_le
#print axioms Erdos118.CriticalPair.leafRank_pos
#print axioms Erdos118.CriticalPair.last_iff_leafRank_eq
#print axioms Erdos118.StrictCriticalBounds.selected_root
#print axioms Erdos118.StrictCriticalBounds.before_last
#print axioms Erdos118.StrictCriticalBounds.intermediate
#print axioms Erdos118.StrictCriticalBounds.ranks
#print axioms Erdos118.StrictCriticalBounds.terminal
#print axioms Erdos118.CriticalCursor.current_label
#print axioms Erdos118.CriticalCursor.selected_of_extension
#print axioms Erdos118.CriticalCursor.pair_of_extension
#print axioms Erdos118.CriticalCursor.observables
#print axioms Erdos118.CriticalCursor.at_left_endpoint
#print axioms Erdos118.StrictEndpoint.future_roots
#print axioms Erdos118.ResponseRefinement.red_or
#print axioms Erdos118.ResponseRefinement.blue_summand
#print axioms Erdos118.ResponseRefinement.refine_test
#print axioms Erdos118.ResponseRefinement.refine_nat
#print axioms Erdos118.ResponseRankRefinement.right_root
#print axioms Erdos118.ResponseRankRefinement.body
#print axioms Erdos118.StrictBodyLocalization.exists_root
#print axioms Erdos118.LabelRanks.rank_lt
#print axioms Erdos118.LabelRanks.rank_injective
#print axioms Erdos118.LabelRanks.exists_label
#print axioms Erdos118.StrictBodyCheckpoint.right
#print axioms Erdos118.StrictLeafLocalization.exists_body
#print axioms Erdos118.StrictLocalization.at_root
#print axioms Erdos118.SelectedLeafCheckpoint.right_entry
#print axioms Erdos118.StrictLeafCheckpoint.right
#print axioms Erdos118.StrictCriticalOpening.at_body
#print axioms Erdos118.RankedRootReserve.labels
#print axioms Erdos118.RankedRootReserve.root_reserved
#print axioms Erdos118.RankedRootReserve.Reserve.index_of_rank
#print axioms Erdos118.RankedRootReserve.Reserve.rootSetup_ordinary
#print axioms Erdos118.RankedRootReserve.Reserve.rootSetup_supported
#print axioms Erdos118.RankedRootPreparation.at_shared
#print axioms Erdos118.RankedRootPreparation.at_localized
#print axioms Erdos118.SelectedBodyReplay.Prepared.setup_ordinary
#print axioms Erdos118.SelectedBodyReplay.Prepared.setup_newWord
#print axioms Erdos118.SelectedBodyReplay.carry_of_run
#print axioms Erdos118.SelectedBodyReplay.fire
#print axioms Erdos118.RankedLeafLabels.labels
#print axioms Erdos118.RankedLeafLabels.body_setup
#print axioms Erdos118.StrictReservedLeafOpening.exists_opening
#print axioms Erdos118.StrictInitialOpening.exists_opening
#print axioms Erdos118.CriticalLastRefinement.exists_refined
#print axioms Erdos118.CriticalLastRefinement.at_critical
#print axioms Erdos118.CriticalLastRefinement.initial_opening
#print axioms Erdos118.StrictUpperRoot.localize
#print axioms Erdos118.StrictInsertedRoot.exists_opening
#print axioms Erdos118.RootBufferOn.buffer

#print axioms Erdos118.RankedTargetLabels.labels
#print axioms Erdos118.RankedTargetLabels.body_setup
#print axioms Erdos118.RankedRightPreparation.at_shared
#print axioms Erdos118.RankedRightPreparation.at_localized
#print axioms Erdos118.StrictReservedRightOpening.exists_opening
#print axioms Erdos118.StrictTwoRootRequests.exists_requests
#print axioms Erdos118.StrictSecondOpening.at_rank
#print axioms Erdos118.StrictSecondOpening.exists_opening
#print axioms Erdos118.StrictSecondOpening.last_opening
#print axioms Erdos118.StrictSecondOpening.nonlast_opening
#print axioms Erdos118.InsertedCrossAlignment.align
#print axioms Erdos118.StrictSharedBodyRequests.exists_requests
#print axioms Erdos118.StrictSharedFirstLeaves.Pair.exactSlots
#print axioms Erdos118.StrictSharedFirstLeaves.Pair.roots_nil
#print axioms Erdos118.StrictSharedFirstLeaves.Pair.leaves_nonempty
#print axioms Erdos118.StrictSharedFirstLeaves.exists_pair
#print axioms Erdos118.StrictOpeningShape.old_test
#print axioms Erdos118.StrictOpeningShape.inserted_test
#print axioms Erdos118.StrictOpeningShape.inserted_rank
#print axioms Erdos118.StrictOpeningShape.same_test
#print axioms Erdos118.StrictOpeningShape.last_future_roots
#print axioms Erdos118.SplicedRootReserve.labels
#print axioms Erdos118.SplicedRootReserve.root_reserved
#print axioms Erdos118.SplicedRootReserve.Reserve.index_of_rank
#print axioms Erdos118.SplicedRootReserve.Reserve.rootSetup_ordinary
#print axioms Erdos118.SplicedRootReserve.Reserve.rootSetup_supported
#print axioms Erdos118.RootReplayReserve.Reserve.index_of_rank
#print axioms Erdos118.RootReplayReserve.Reserve.rootSetup_ordinary
#print axioms Erdos118.RootReplayReserve.Reserve.rootSetup_supported
#print axioms Erdos118.SplicedRightPreparation.at_localized
#print axioms Erdos118.FreshCriticalCheckpoint.stop_handoff
#print axioms Erdos118.FreshCriticalCheckpoint.right_handoff
#print axioms Erdos118.FreshCriticalCheckpoint.critical_pair
#print axioms Erdos118.StrictTargetCheckpoint.exists_checkpoint
#print axioms Erdos118.PendingRootSuccessor.above_cons_of_gap
#print axioms Erdos118.PendingRootSuccessor.of_gap
#print axioms Erdos118.PendingRootSuccessor.of_rank
#print axioms Erdos118.StrictMarkerRequests.capture
#print axioms Erdos118.StrictMarkerRequests.old_next
#print axioms Erdos118.StrictMarkerRequests.inserted_next
#print axioms Erdos118.StrictMarkerRequests.exists_requests
#print axioms Erdos118.StrictMarkerRequests.target_left_next
#print axioms Erdos118.StrictMarkerRequests.target_right_next
#print axioms Erdos118.CrossMarkerBridge.align
#print axioms Erdos118.StrictLastMarkerBridge.exists_diagram
#print axioms Erdos118.FutureAnchorBounds.selected_body
#print axioms Erdos118.FutureAnchorBounds.body_add_two_le
#print axioms Erdos118.FutureAnchorBounds.spliced_anchor
#print axioms Erdos118.FixedLeftBodyRefinement.refine
#print axioms Erdos118.StrictAnchorLocalization.exists_localized
#print axioms Erdos118.Pentagram.Split6.mem_cases
#print axioms Erdos118.Pentagram.Split6.mem2
#print axioms Erdos118.Pentagram.Split6.mem3
#print axioms Erdos118.Pentagram.Witness.blockList_chain
#print axioms Erdos118.Pentagram.Witness.blockAt_lt
#print axioms Erdos118.Pentagram.Witness.index_lt_of_value_lt
#print axioms Erdos118.Pentagram.Witness.left_index
#print axioms Erdos118.Pentagram.Witness.right_index
#print axioms Erdos118.Pentagram.Witness.firstValue_lt
#print axioms Erdos118.Pentagram.Witness.alternating_box
#print axioms Erdos118.Pentagram.graphOf_adj
#print axioms Erdos118.Pentagram.exists_pattern
#print axioms Erdos118.Pentagram.exists_edge_of_full_type
#print axioms Erdos118.Pentagram.Split6.mem0
#print axioms Erdos118.Pentagram.Split6.mem1
#print axioms Erdos118.Pentagram.Split6.mem4
#print axioms Erdos118.Pentagram.Split6.mem5
#print axioms Erdos118.Pentagram.inside_between
#print axioms Erdos118.Pentagram.Witness.x0_before_y
#print axioms Erdos118.Pentagram.Witness.y_before_x5
#print axioms Erdos118.Pentagram.Witness.inside_first_of_inside_second
#print axioms Erdos118.Pentagram.Witness.second_mem_inside_first
#print axioms Erdos118.Pentagram.Witness.inside_of_internal_index
#print axioms Erdos118.Pentagram.Witness.index_bounds_of_inside
#print axioms Erdos118.Pentagram.Witness.core_iff
#print axioms Erdos118.Pentagram.Witness.core_nonempty
#print axioms Erdos118.Pentagram.core_subset
#print axioms Erdos118.Pentagram.Witness.box_right_parts
#print axioms Erdos118.Pentagram.Witness.low_before_inside
#print axioms Erdos118.Pentagram.Witness.inside_before_high
#print axioms Erdos118.Pentagram.Witness.twixt_before_core
#print axioms Erdos118.Pentagram.Witness.core_before_tween
#print axioms Erdos118.Pentagram.Witness.mid_between_core_boxes
#print axioms Erdos118.Pentagram.Witness.between_core_mem_mid
#print axioms Erdos118.Pentagram.Witness.no_first_between_mid
#print axioms Erdos118.Pentagram.Witness.left_wing
#print axioms Erdos118.Pentagram.Witness.right_wing
#print axioms Erdos118.Pentagram.Witness.no_spanning_core
#print axioms Erdos118.Pentagram.Witness.core_one_side
#print axioms Erdos118.Pentagram.Witness.core_separator
#print axioms Erdos118.Pentagram.Witness.common_box_cuts
#print axioms Erdos118.Pentagram.three_cores_contradiction
#print axioms Erdos118.Pentagram.no_oriented_five
#print axioms Erdos118.Pentagram.graphOf_no_five_clique
#print axioms Erdos118.Pentagram.graph_no_five
#print axioms Erdos118.counterexampleBlueFive_cliqueFree_five
#print axioms Erdos118.counterexampleBlueFive_meets_full_copy
#print axioms Erdos118.negative_five
#print axioms Erdos118.Reused591.Erdos591.Positive.Game.Payoff.architect_triangle
#print axioms Erdos118.Reused591.Erdos591.Positive.Game.Macro.Forest.builder_red_set
#print axioms Erdos118.Reused591.Erdos591.Positive.Game.Payoff.triangle_free_red_set
#print axioms Erdos118.Reused591.Erdos591.schipperus_two
#print axioms Erdos118.positive_three
#print axioms Erdos118.counterexample_at_five
#print axioms Erdos118.counterexample_at_six
#print axioms Erdos118.not_erdos_118
