import StackExchange.Puzzling139335.SymmetryOrbit

#print axioms Puzzling139335.SymmetryOrbit.square_symmetry_classification
#print axioms Puzzling139335.SymmetryOrbit.square_symmetry_pair_classification
#print axioms Puzzling139335.SymmetryOrbit.pairwise_disjoint_commutingOrbit
#print axioms Puzzling139335.SquareDissection.center_mem_interior_of_fixed_piece_packing
#print axioms Puzzling139335.SquareDissection.not_hasProtectedCenter_of_square_symmetry_packing
#print axioms Puzzling139335.SquareDissection.not_hasProtectedCenter_of_three_square_symmetry_copies
#print axioms Puzzling139335.SquareDissection.not_hasProtectedCenter_of_three_square_orbit_images
