import Wikipedia.NoExoticSixSphere.OrthogonalPolygonMinimum
import Wikipedia.NoExoticSixSphere.OrthogonalMinimumPaths

/-!
# The equality case for antipodal polygon energy

Within a compact polygon sublevel, equality in the antipodal energy bound
forces the actual realization to be a minimum exponential generated by an
orthogonal complex structure. Conversely such a realization has precisely
the minimum energy. No smoothness of a broken path at its corners is assumed.
-/

open Set

namespace NoExoticSixSphere.OrthogonalPolygon

open GLOrthonormalization CayleyTransform OrthogonalVertexSpace OrthogonalExponential

variable {n m : ℕ}

theorem isStationary_of_minimum_energy (a b : OrthogonalOperators n)
    (τ : Fin (m + 2) → ℝ) (hτ : StrictMono τ)
    (hzero : τ 0 = 0) (hone : τ (Fin.last (m + 1)) = 1) (E : ℝ)
    (hcompact : IsCompact (energySublevel a b τ E))
    (hanti : (a⁻¹ * b).1.1 = -(1 : Vector n →L[ℝ] Vector n))
    (v : Space n m) (hv : v ∈ energySublevel a b τ E)
    (he : energy a b τ v = (n : ℝ) * Real.pi ^ 2) : IsStationary a b τ v := by
  have hmin : IsMinOn (energy a b τ) (admissible a b m) v := by
    intro w hw
    by_cases hE : energy a b τ w ≤ E
    · rw [he]
      exact antipodal_energy_ge_of_compact_sublevel a b τ hτ hzero hone E hcompact hanti w ⟨hw, hE⟩
    · exact hv.2.trans (lt_of_not_ge hE).le
  exact isStationary_of_isLocalMin a b τ v hv.1
    (hmin.isLocalMin ((isOpen_admissible a b m).mem_nhds hv.1))

theorem energy_eq_min_iff_complexStructure (a b : OrthogonalOperators n)
    (τ : Fin (m + 2) → ℝ) (hτ : StrictMono τ)
    (hzero : τ 0 = 0) (hone : τ (Fin.last (m + 1)) = 1) (E : ℝ)
    (hcompact : IsCompact (energySublevel a b τ E))
    (hanti : (a⁻¹ * b).1.1 = -(1 : Vector n →L[ℝ] Vector n))
    (v : Space n m) (hv : v ∈ energySublevel a b τ E) :
    energy a b τ v = (n : ℝ) * Real.pi ^ 2 ↔
      ∃ J : OrthogonalComplexStructures.Space n, ∀ t ∈ Icc (0 : ℝ) 1,
        path a b τ v t = a * exp (t • (Real.pi • J.1)) := by
  have hpenergy := path_energy_eq a b τ hτ hv.1
  rw [hzero, hone] at hpenergy
  constructor
  · intro he
    have hstat := isStationary_of_minimum_energy a b τ hτ hzero hone E hcompact hanti v hv he
    obtain ⟨K, hend, hpath⟩ := stationary_is_exponential a b τ hτ v hv.1 hstat
    simp only [hzero, hone, sub_zero, one_smul] at hend hpath
    have hexpeq : exp K = a⁻¹ * b := by rw [← hend, inv_mul_cancel_left]
    have hexp : (exp K).1.1 = -(1 : Vector n →L[ℝ] Vector n) := by rwa [hexpeq]
    have hcompare : OrthogonalPathEnergy.energy (fun t ↦ (path a b τ v t).1.1) 0 1 =
        OrthogonalPathEnergy.energy (fun t ↦ (a * exp (t • K)).1.1) 0 1 :=
      OrthogonalPathEnergy.energy_congr_Icc zero_le_one
        (fun t ht ↦ congrArg (fun q : OrthogonalOperators n ↦ q.1.1) (hpath t ht))
    have hsq : HilbertSchmidt.squareNorm (K : Vector n →L[ℝ] Vector n) =
        (n : ℝ) * Real.pi ^ 2 := by
      rw [OrthogonalPathEnergy.energy_left_exp] at hcompare
      simpa only [sub_zero, one_mul] using hcompare.symm.trans (hpenergy.trans he)
    obtain ⟨J, hJ⟩ := (SkewAntipodalSpectrum.squareNorm_eq_iff_complexStructure K hexp).mp hsq
    refine ⟨J, fun t ht ↦ ?_⟩
    simpa only [hJ] using hpath t ht
  · rintro ⟨J, hJ⟩
    rw [← hpenergy, OrthogonalPathEnergy.energy_congr_Icc zero_le_one
      (fun t ht ↦ congrArg (fun q : OrthogonalOperators n ↦ q.1.1) (hJ t ht))]
    exact OrthogonalMinimumPaths.energy_complexStructure a J

end NoExoticSixSphere.OrthogonalPolygon
