/-
Copyright (c) 2026 Boris Alexeev. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Boris Alexeev, Codex
-/
import ErdosProblems.Erdos207.SelectedUncoveredJointInclusion
import ErdosProblems.Erdos207.FiniteKernelConcentration

/-!
# Transfer from available to selected

A retrospective selected-triangle estimate cannot sum the bare insertion
hazard: before its insertion a prescribed triangle must remain available.
This file records the exact finite recurrence which retains that survival.

For a fixed prescribed family `Q`, the event at state `omega` and selected
subfamily `S` says that precisely the members of `S` have already been
selected, every member of `Q \ S` is still available, and all prescribed
graph edges remain uncovered.  One transition either keeps `S` fixed, at a
survival cost, or transfers one `x` from `Q \ (S \ {x})` into `S`, at the
one-point insertion cost.
-/

namespace Erdos207

open Finset
open scoped BigOperators NNReal

noncomputable section

/-- Exact status event for prescribed triangles during a greedy process. -/
def SelectedAvailableUncoveredEvent
    {Omega W Z : Type*} [DecidableEq W] [DecidableEq Z]
    (selected available : Omega -> Finset W) (uncovered : Omega -> Finset Z)
    (Q S : Finset W) (B : Finset Z) (omega : Omega) : Prop :=
  S ⊆ Q ∧ S ⊆ selected omega ∧
    Disjoint (Q \ S) (selected omega) ∧
    Q \ S ⊆ available omega ∧ B ⊆ uncovered omega

/-- Scalar envelope generated by the transfer recurrence.  The exponent
`3 * |Q \ S| + b` is the number of graph-edge survival factors: three for
each prescribed triangle still waiting in the available family, and one for
each prescribed residual edge. -/
def selectedAvailableUncoveredEnvelope
    {W : Type*} [DecidableEq W]
    (delta theta : ℕ -> ℝ≥0) (Q : Finset W) (b : ℕ) :
    ℕ -> Finset W -> ℝ≥0
  | 0, S => if S = ∅ then 1 else 0
  | t + 1, S =>
      theta t ^ (3 * (Q \ S).card + b) *
          selectedAvailableUncoveredEnvelope delta theta Q b t S +
        ∑ x ∈ S, delta t *
          selectedAvailableUncoveredEnvelope delta theta Q b t (S.erase x)

@[simp]
lemma selectedAvailableUncoveredEnvelope_zero
    {W : Type*} [DecidableEq W]
    (delta theta : ℕ -> ℝ≥0) (Q S : Finset W) (b : ℕ) :
    selectedAvailableUncoveredEnvelope delta theta Q b 0 S =
      if S = ∅ then 1 else 0 := rfl

@[simp]
lemma selectedAvailableUncoveredEnvelope_succ
    {W : Type*} [DecidableEq W]
    (delta theta : ℕ -> ℝ≥0) (Q S : Finset W) (b t : ℕ) :
    selectedAvailableUncoveredEnvelope delta theta Q b (t + 1) S =
      theta t ^ (3 * (Q \ S).card + b) *
          selectedAvailableUncoveredEnvelope delta theta Q b t S +
        ∑ x ∈ S, delta t *
          selectedAvailableUncoveredEnvelope delta theta Q b t (S.erase x) :=
  rfl

/-- One transition satisfies the transfer recurrence whenever selected sets
grow by at most one, available and uncovered sets only shrink, and every new
selected point came from the old available set. -/
theorem kernel_probability_selectedAvailableUncovered_le
    {Omega W Z : Type*} [Fintype Omega]
    [DecidableEq W] [DecidableEq Z]
    (K : Omega -> FiniteLaw Omega)
    (selected available : Omega -> Finset W)
    (uncovered : Omega -> Finset Z)
    (delta theta : ℝ≥0)
    (omega : Omega)
    (hsingle : (K omega).SupportedOn fun omega' =>
      selected omega ⊆ selected omega' ∧
        (selected omega' \ selected omega).card <= 1)
    (havailableAnti : (K omega).SupportedOn fun omega' =>
      available omega' ⊆ available omega)
    (huncoveredAnti : (K omega).SupportedOn fun omega' =>
      uncovered omega' ⊆ uncovered omega)
    (hnewAvailable : (K omega).SupportedOn fun omega' =>
      selected omega' \ selected omega ⊆ available omega)
    (Q S : Finset W) (hSQ : S ⊆ Q) (B : Finset Z)
    (hsurvive :
      SelectedAvailableUncoveredEvent selected available uncovered Q S B
          omega ->
      (K omega).probability (fun omega' =>
          Q \ S ⊆ available omega' ∧ B ⊆ uncovered omega') <=
        theta ^ (3 * (Q \ S).card + B.card))
    (hpoint : ∀ x ∈ S,
      SelectedAvailableUncoveredEvent selected available uncovered
          Q (S.erase x) B omega ->
      x ∉ selected omega ->
      (K omega).probability (fun omega' =>
          x ∈ selected omega' ∧ Q \ S ⊆ available omega' ∧
            B ⊆ uncovered omega') <= delta) :
    (K omega).probability
        (SelectedAvailableUncoveredEvent selected available uncovered
          Q S B) <=
      theta ^ (3 * (Q \ S).card + B.card) *
          nnrealIndicator
            (SelectedAvailableUncoveredEvent selected available uncovered
              Q S B omega) +
        ∑ x ∈ S, nnrealIndicatorMul
          (SelectedAvailableUncoveredEvent selected available uncovered
            Q (S.erase x) B omega) delta := by
  classical
  let Event : Finset W -> Omega -> Prop := fun T =>
    SelectedAvailableUncoveredEvent selected available uncovered Q T B
  by_cases hold : Event S omega
  · calc
      (K omega).probability (Event S) <=
          (K omega).probability (fun omega' =>
            Q \ S ⊆ available omega' ∧ B ⊆ uncovered omega') := by
        apply FiniteLaw.probability_mono
        intro omega' htarget
        exact ⟨htarget.2.2.2.1, htarget.2.2.2.2⟩
      _ <= theta ^ (3 * (Q \ S).card + B.card) := hsurvive hold
      _ <= theta ^ (3 * (Q \ S).card + B.card) *
            nnrealIndicator (Event S omega) +
          ∑ x ∈ S, nnrealIndicatorMul
            (Event (S.erase x) omega) delta := by
        simp only [nnrealIndicator, if_pos hold, mul_one]
        exact le_add_of_nonneg_right zero_le
  · have hclassify : ∀ omega',
        (selected omega ⊆ selected omega' ∧
          (selected omega' \ selected omega).card <= 1) ->
        available omega' ⊆ available omega ->
        uncovered omega' ⊆ uncovered omega ->
        selected omega' \ selected omega ⊆ available omega ->
        Event S omega' ->
        ∃ x ∈ S, Event (S.erase x) omega ∧
          x ∉ selected omega ∧ x ∈ selected omega' ∧
          Q \ S ⊆ available omega' ∧ B ⊆ uncovered omega' := by
      intro omega' hsel havail huncovered hnew htarget
      have hSnew : S ⊆ selected omega' := htarget.2.1
      have hSnotOld : ¬ S ⊆ selected omega := by
        intro hSold
        apply hold
        refine ⟨hSQ, hSold, ?_, ?_, ?_⟩
        · exact htarget.2.2.1.mono_right hsel.1
        · exact htarget.2.2.2.1.trans havail
        · exact htarget.2.2.2.2.trans huncovered
      obtain ⟨x, hxS, hxnot, herase⟩ :=
        exists_erase_subset_of_sdiff_card_le_one hSnew hsel.2 hSnotOld
      have hxnew : x ∈ selected omega' := hSnew hxS
      have hpendingDisjoint : Disjoint (Q \ S.erase x) (selected omega) := by
        rw [disjoint_left]
        intro y hyPending hyOld
        have hyQ : y ∈ Q := (mem_sdiff.mp hyPending).1
        have hynotErase : y ∉ S.erase x := (mem_sdiff.mp hyPending).2
        by_cases hyx : y = x
        · subst y
          exact hxnot hyOld
        · have hynotS : y ∉ S := by
            intro hyS
            exact hynotErase (mem_erase.mpr ⟨hyx, hyS⟩)
          have hyQS : y ∈ Q \ S := mem_sdiff.mpr ⟨hyQ, hynotS⟩
          exact disjoint_left.mp htarget.2.2.1 hyQS (hsel.1 hyOld)
      have hpendingAvailable : Q \ S.erase x ⊆ available omega := by
        intro y hyPending
        have hyQ : y ∈ Q := (mem_sdiff.mp hyPending).1
        have hynotErase : y ∉ S.erase x := (mem_sdiff.mp hyPending).2
        by_cases hyx : y = x
        · subst y
          exact hnew (mem_sdiff.mpr ⟨hxnew, hxnot⟩)
        · have hynotS : y ∉ S := by
            intro hyS
            exact hynotErase (mem_erase.mpr ⟨hyx, hyS⟩)
          exact havail (htarget.2.2.2.1
            (mem_sdiff.mpr ⟨hyQ, hynotS⟩))
      have heraseQ : S.erase x ⊆ Q := (erase_subset x S).trans hSQ
      refine ⟨x, hxS,
        ⟨heraseQ, herase, hpendingDisjoint, hpendingAvailable,
          htarget.2.2.2.2.trans huncovered⟩,
        hxnot, hxnew, htarget.2.2.2.1, htarget.2.2.2.2⟩
    have hmono : (K omega).probability (Event S) <=
        (K omega).probability (fun omega' =>
          ∃ x ∈ S, Event (S.erase x) omega ∧
            x ∉ selected omega ∧ x ∈ selected omega' ∧
            Q \ S ⊆ available omega' ∧ B ⊆ uncovered omega') := by
      have hsuppAll : (K omega).SupportedOn fun omega' =>
          (selected omega ⊆ selected omega' ∧
            (selected omega' \ selected omega).card <= 1) ∧
          (available omega' ⊆ available omega) ∧
          (uncovered omega' ⊆ uncovered omega) ∧
          (selected omega' \ selected omega ⊆ available omega) := by
        intro omega' hmass
        exact ⟨hsingle omega' hmass, havailableAnti omega' hmass,
          huncoveredAnti omega' hmass, hnewAvailable omega' hmass⟩
      apply (K omega).probability_mono_of_supported
        hsuppAll
      intro omega' hsupp htarget
      exact hclassify omega' hsupp.1 hsupp.2.1 hsupp.2.2.1 hsupp.2.2.2
        htarget
    have hunion := (K omega).probability_exists_le S (fun x omega' =>
      Event (S.erase x) omega ∧ x ∉ selected omega ∧
        x ∈ selected omega' ∧ Q \ S ⊆ available omega' ∧
        B ⊆ uncovered omega')
    calc
      (K omega).probability (Event S) <=
          (K omega).probability (fun omega' =>
            ∃ x ∈ S, Event (S.erase x) omega ∧
              x ∉ selected omega ∧ x ∈ selected omega' ∧
              Q \ S ⊆ available omega' ∧ B ⊆ uncovered omega') := hmono
      _ <= ∑ x ∈ S, (K omega).probability (fun omega' =>
            Event (S.erase x) omega ∧ x ∉ selected omega ∧
              x ∈ selected omega' ∧ Q \ S ⊆ available omega' ∧
              B ⊆ uncovered omega') := hunion
      _ <= ∑ x ∈ S, nnrealIndicatorMul
            (Event (S.erase x) omega) delta := by
        apply sum_le_sum
        intro x hxS
        by_cases heraseEvent : Event (S.erase x) omega
        · by_cases hxnot : x ∉ selected omega
          · simp only [nnrealIndicatorMul, if_pos heraseEvent]
            exact ((K omega).probability_mono fun omega' hz =>
              ⟨hz.2.2.1, hz.2.2.2.1, hz.2.2.2.2⟩).trans
                (hpoint x hxS heraseEvent hxnot)
          · have hfalse : (fun omega' =>
                Event (S.erase x) omega ∧ x ∉ selected omega ∧
                  x ∈ selected omega' ∧ Q \ S ⊆ available omega' ∧
                  B ⊆ uncovered omega') = (fun _ : Omega => False) := by
              funext omega'
              exact propext ⟨fun hz => hxnot hz.2.1, False.elim⟩
            rw [hfalse, FiniteLaw.probability_false]
            exact zero_le
        · have hfalse : (fun omega' =>
              Event (S.erase x) omega ∧ x ∉ selected omega ∧
                x ∈ selected omega' ∧ Q \ S ⊆ available omega' ∧
                B ⊆ uncovered omega') = (fun _ : Omega => False) := by
            funext omega'
            exact propext ⟨fun hz => heraseEvent hz.1, False.elim⟩
          rw [hfalse, FiniteLaw.probability_false]
          simp [nnrealIndicatorMul, heraseEvent]
      _ = theta ^ (3 * (Q \ S).card + B.card) *
            nnrealIndicator (Event S omega) +
          ∑ x ∈ S, nnrealIndicatorMul
            (Event (S.erase x) omega) delta := by
        simp [nnrealIndicator, hold]

/-- Iteration of a one-step selected/available/uncovered transfer estimate.
This theorem deliberately isolates the probabilistic recurrence from the
later analytic estimate of its scalar envelope. -/
theorem evolveKernels_probability_selectedAvailableUncovered_le_envelope
    {Omega W Z : Type*} [Fintype Omega] [DecidableEq Omega]
    [DecidableEq W] [DecidableEq Z]
    (K : ℕ -> Omega -> FiniteLaw Omega)
    (selected available : Omega -> Finset W)
    (uncovered : Omega -> Finset Z)
    (delta theta : ℕ -> ℝ≥0)
    (Q : Finset W) (B : Finset Z)
    (hstep : ∀ i omega S, S ⊆ Q ->
      (K i omega).probability
          (SelectedAvailableUncoveredEvent selected available uncovered
            Q S B) <=
        theta i ^ (3 * (Q \ S).card + B.card) *
            nnrealIndicator
              (SelectedAvailableUncoveredEvent selected available uncovered
                Q S B omega) +
          ∑ x ∈ S, nnrealIndicatorMul
            (SelectedAvailableUncoveredEvent selected available uncovered
              Q (S.erase x) B omega) (delta i))
    (omega0 : Omega)
    (hQselected : Disjoint Q (selected omega0))
    (hQavailable : Q ⊆ available omega0)
    (hB : B ⊆ uncovered omega0)
    (S : Finset W) (hSQ : S ⊆ Q) (t : ℕ) :
    (FiniteLaw.evolveKernels K t (FiniteLaw.pure omega0)).probability
        (SelectedAvailableUncoveredEvent selected available uncovered
          Q S B) <=
      selectedAvailableUncoveredEnvelope delta theta Q B.card t S := by
  classical
  induction t generalizing S with
  | zero =>
      simp only [FiniteLaw.evolveKernels_zero, FiniteLaw.probability_pure,
        selectedAvailableUncoveredEnvelope_zero]
      by_cases hS : S = ∅
      · subst S
        simp [SelectedAvailableUncoveredEvent, hQselected, hQavailable, hB]
      · have hnot : ¬ S ⊆ selected omega0 := by
          intro hsub
          obtain ⟨x, hxS⟩ := nonempty_iff_ne_empty.mpr hS
          exact disjoint_left.mp hQselected (hSQ hxS) (hsub hxS)
        simp [SelectedAvailableUncoveredEvent, hnot, hS]
  | succ t ih =>
      rw [FiniteLaw.evolveKernels_succ, FiniteLaw.probability_bind]
      let L := FiniteLaw.evolveKernels K t (FiniteLaw.pure omega0)
      let Event : Finset W -> Omega -> Prop := fun T =>
        SelectedAvailableUncoveredEvent selected available uncovered Q T B
      have hconditional (omega : Omega) :
          (K t omega).probability (Event S) <=
            theta t ^ (3 * (Q \ S).card + B.card) *
                nnrealIndicator (Event S omega) +
              ∑ x ∈ S, nnrealIndicatorMul
                (Event (S.erase x) omega) (delta t) := by
        simpa only [Event] using hstep t omega S hSQ
      have hmain : L.probability (Event S) <=
          selectedAvailableUncoveredEnvelope delta theta Q B.card t S := by
        simpa only [L, Event] using ih S hSQ
      have herase : ∀ x ∈ S,
          L.probability (Event (S.erase x)) <=
            selectedAvailableUncoveredEnvelope delta theta Q B.card t
              (S.erase x) := by
        intro x hx
        have heraseQ : S.erase x ⊆ Q := (erase_subset x S).trans hSQ
        simpa only [L, Event] using ih (S.erase x) heraseQ
      calc
        (∑ omega, L.mass omega * (K t omega).probability (Event S)) <=
            ∑ omega, L.mass omega *
              (theta t ^ (3 * (Q \ S).card + B.card) *
                  nnrealIndicator (Event S omega) +
                ∑ x ∈ S, nnrealIndicatorMul
                  (Event (S.erase x) omega) (delta t)) := by
          apply sum_le_sum
          intro omega homega
          simpa only [mul_comm] using
            mul_le_mul_left (hconditional omega) (L.mass omega)
        _ = theta t ^ (3 * (Q \ S).card + B.card) *
              L.probability (Event S) +
            ∑ x ∈ S, delta t * L.probability (Event (S.erase x)) := by
          simp only [mul_add, sum_add_distrib]
          congr 1
          · unfold FiniteLaw.probability
            rw [mul_sum]
            apply sum_congr rfl
            intro omega homega
            by_cases hevent : Event S omega <;>
              simp [nnrealIndicator, hevent, mul_comm]
          · rw [show (∑ omega, L.mass omega *
                  ∑ x ∈ S, nnrealIndicatorMul
                    (Event (S.erase x) omega) (delta t)) =
                ∑ omega, ∑ x ∈ S, L.mass omega *
                  nnrealIndicatorMul
                    (Event (S.erase x) omega) (delta t) by
                apply sum_congr rfl
                intro omega homega
                rw [mul_sum]]
            rw [sum_comm]
            apply sum_congr rfl
            intro x hx
            unfold FiniteLaw.probability
            rw [mul_sum]
            apply sum_congr rfl
            intro omega homega
            by_cases hevent : Event (S.erase x) omega <;>
              simp [nnrealIndicatorMul, hevent, mul_comm]
        _ <= theta t ^ (3 * (Q \ S).card + B.card) *
              selectedAvailableUncoveredEnvelope delta theta Q B.card t S +
            ∑ x ∈ S, delta t *
              selectedAvailableUncoveredEnvelope delta theta Q B.card t
                (S.erase x) := by
          apply add_le_add
          · gcongr
          · apply sum_le_sum
            intro x hx
            gcongr
            exact herase x hx
        _ = selectedAvailableUncoveredEnvelope delta theta Q B.card
              (t + 1) S := rfl

/-- At the fully transferred state the exact-status event is just joint
selection of `Q` and survival of `B`. -/
lemma selectedAvailableUncoveredEvent_self
    {Omega W Z : Type*} [DecidableEq W] [DecidableEq Z]
    (selected available : Omega -> Finset W) (uncovered : Omega -> Finset Z)
    (Q : Finset W) (B : Finset Z) :
    SelectedAvailableUncoveredEvent selected available uncovered Q Q B =
      (fun omega => Q ⊆ selected omega ∧ B ⊆ uncovered omega) := by
  funext omega
  simp [SelectedAvailableUncoveredEvent]

end

end Erdos207
