/-
Copyright (c) 2026 Boris Alexeev. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Boris Alexeev, Codex
-/
import ErdosProblems.Erdos207.VortexCyclicSweep
import ErdosProblems.Erdos207.VortexRootedThreatWeight
import ErdosProblems.Erdos207.RootedThreatExtraction

/-!
# Indexed rooted-threat moments for the cyclic vortex sweep

This file is the first probabilistic use of the common cyclic sweep law.  Its
level-weighted joint-inclusion bound and the uniform sharp W1 coefficient
feed directly into the finite configuration-moment lemma.
-/

namespace Erdos207

open Finset
open scoped BigOperators NNReal

noncomputable section

/-- Indexed rooted witnesses whose remainders are already selected. -/
def activeIndexedRootedThreatWitnesses
    {V : Type*} [Fintype V] [DecidableEq V]
    (q : ℕ) (B P : TripleSystemOn V) (u v : V) :
    Finset (IndexedRootedThreatWitness V q B u v) :=
  univ.filter fun z ↦ rootedThreatRemainder z.1 ⊆ P

@[simp]
lemma mem_activeIndexedRootedThreatWitnesses_iff
    {V : Type*} [Fintype V] [DecidableEq V]
    {q : ℕ} {B P : TripleSystemOn V} {u v : V}
    {z : IndexedRootedThreatWitness V q B u v} :
    z ∈ activeIndexedRootedThreatWitnesses q B P u v ↔
      rootedThreatRemainder z.1 ⊆ P := by
  simp [activeIndexedRootedThreatWitnesses]

/-- The selected-count observable is exactly the number of active indexed
rooted witnesses. -/
lemma selectedCount_indexedRootedThreatRemainder
    {V : Type*} [Fintype V] [DecidableEq V]
    (q : ℕ) (B P : TripleSystemOn V) (u v : V) :
    selectedCount
      (fun z : IndexedRootedThreatWitness V q B u v ↦
        rootedThreatRemainder z.1) P =
      (activeIndexedRootedThreatWitnesses q B P u v).card := by
  classical
  unfold selectedCount activeIndexedRootedThreatWitnesses
  simp only [card_eq_sum_ones, Nat.cast_sum, Nat.cast_one, sum_filter]
  apply sum_congr rfl
  intro z hz
  by_cases h : rootedThreatRemainder z.1 ⊆ P <;> simp [h]

/-- An indexed rooted-threat remainder has at most `q` triangles. -/
lemma card_indexedRootedThreatRemainder_le
    {V : Type*} [Fintype V] [DecidableEq V]
    {q : ℕ} {B : TripleSystemOn V} {u v : V}
    (z : IndexedRootedThreatWitness V q B u v) :
    (rootedThreatRemainder z.1).card ≤ q := by
  have horder := (mem_Icc.mp (indexedRootedThreat_order_mem z)).2
  rw [rootedThreatRemainder, card_erase_of_mem z.1.2.2.1]
  omega

/-- Uniform factorial constant for an `s`th moment of indexed remainders. -/
def vortexRootedMomentJointConstant (q s : ℕ) : ℕ :=
  (s * q).factorial

/-- Moment bound for indexed rooted threats generated by the cyclic vortex
sweep from the empty selected family. -/
theorem cyclicVortexGreedy_indexedRootedThreatMomentBound
    {V : Type*} [Fintype V] [DecidableEq V]
    {ell q s : ℕ} (W : Vortex V ell) (B A : TripleSystemOn V)
    (D : Fin (ell + 1) → ℕ) (hD : ∀ k, 0 < D k)
    (c : ℝ≥0) (hc : c ≤ 1)
    (houter : ∀ i : Fin ell, 0 < (W.U i.castSucc).card)
    (hterminal : 0 < W.terminalSize)
    (hratio : ∀ k : Fin (ell + 1),
      (vortexPackingSaturationFuel V : ℝ≥0) * (D k : ℝ≥0)⁻¹ ≤
        c / (W.U k).card)
    {u v : V} (huv : u ≠ v) :
    (scheduledStoppedVortexGreedyProcessLaw
      (absorberErdosForbiddenConfigurationsOn q B) W
      (vortexCyclicSchedule ell) D
      (vortexPackingSaturationFuel V * (ell + 1))
      (absorberGreedyInitialState
        (absorberErdosForbiddenConfigurationsOn q B) A)).expectation
        (fun S ↦ ((activeIndexedRootedThreatWitnesses
          q B S.chosen u v).card : ℝ≥0) ^ s) ≤
      (vortexRootedMomentJointConstant q s : ℝ≥0) *
        (((2 : ℝ≥0) ^ (s * q) *
          ((Fintype.card V : ℝ≥0) *
            indexedRootedThreatVortexUniformCoefficient W q B)) ^ s) := by
  let F := absorberErdosForbiddenConfigurationsOn q B
  let S₀ := absorberGreedyInitialState F A
  let cycles := vortexPackingSaturationFuel V
  let L := scheduledStoppedVortexGreedyProcessLaw F W
    (vortexCyclicSchedule ell) D (cycles * (ell + 1)) S₀
  have hmoment := configurationMomentBound L
    (fun z : IndexedRootedThreatWitness V q B u v ↦
      rootedThreatRemainder z.1)
    (fun S : GreedyStateOn V ↦ S.chosen)
    (vortexTripleWeight W c)
    (vortexRootedMomentJointConstant q s : ℝ≥0)
    ((Fintype.card V : ℝ≥0) *
      indexedRootedThreatVortexUniformCoefficient W q B)
    (d := q) (s := s)
    card_indexedRootedThreatRemainder_le
    (indexedRootedThreatRemainder_hasExtensionBound_vortex
      W B c hc houter hterminal huv)
    (fun T hTcard ↦ by
      have hjoint :=
        cyclicVortexGreedy_probability_subset_chosen_le_vortexWeight
          F W D hD cycles c hratio S₀ T (by
            simp [S₀, absorberGreedyInitialState])
      apply hjoint.trans
      gcongr
      exact_mod_cast Nat.factorial_le hTcard)
  simpa only [L, F, S₀, cycles,
    selectedCount_indexedRootedThreatRemainder] using hmoment

/-- Markov bound for one ordered pair. -/
theorem cyclicVortexGreedy_probability_indexedRootedThreat_ge_le
    {V : Type*} [Fintype V] [DecidableEq V]
    {ell q s : ℕ} (W : Vortex V ell) (B A : TripleSystemOn V)
    (D : Fin (ell + 1) → ℕ) (hD : ∀ k, 0 < D k)
    (c a : ℝ≥0) (hc : c ≤ 1) (ha : 0 < a)
    (houter : ∀ i : Fin ell, 0 < (W.U i.castSucc).card)
    (hterminal : 0 < W.terminalSize)
    (hratio : ∀ k : Fin (ell + 1),
      (vortexPackingSaturationFuel V : ℝ≥0) * (D k : ℝ≥0)⁻¹ ≤
        c / (W.U k).card)
    (e : DistinctPair V) :
    (scheduledStoppedVortexGreedyProcessLaw
      (absorberErdosForbiddenConfigurationsOn q B) W
      (vortexCyclicSchedule ell) D
      (vortexPackingSaturationFuel V * (ell + 1))
      (absorberGreedyInitialState
        (absorberErdosForbiddenConfigurationsOn q B) A)).probability
        (fun S ↦ a ≤
          (activeIndexedRootedThreatWitnesses
            q B S.chosen e.1.1 e.1.2).card) ≤
      ((vortexRootedMomentJointConstant q s : ℝ≥0) *
        (((2 : ℝ≥0) ^ (s * q) *
          ((Fintype.card V : ℝ≥0) *
            indexedRootedThreatVortexUniformCoefficient W q B)) ^ s)) /
        a ^ s := by
  let F := absorberErdosForbiddenConfigurationsOn q B
  let S₀ := absorberGreedyInitialState F A
  let L := scheduledStoppedVortexGreedyProcessLaw F W
    (vortexCyclicSchedule ell) D
    (vortexPackingSaturationFuel V * (ell + 1)) S₀
  let X : GreedyStateOn V → ℝ≥0 := fun S ↦
    ((activeIndexedRootedThreatWitnesses
      q B S.chosen e.1.1 e.1.2).card : ℝ≥0) ^ s
  have hmono : L.probability (fun S ↦ a ≤
      (activeIndexedRootedThreatWitnesses
        q B S.chosen e.1.1 e.1.2).card) ≤
      L.probability (fun S ↦ a ^ s ≤ X S) := by
    apply L.probability_mono
    intro S hS
    exact pow_le_pow_left' hS s
  refine hmono.trans ?_
  have hmarkov := L.probability_le_expectation_div X (pow_pos ha s)
  refine hmarkov.trans ?_
  apply (div_le_div_iff_of_pos_right (pow_pos ha s)).2
  exact cyclicVortexGreedy_indexedRootedThreatMomentBound
    W B A D hD c hc houter hterminal hratio e.2

/-- Under the explicit union-bound inequality, one outcome of the same
cyclic law has both the structural saturation conclusion and a uniform
indexed rooted-threat cutoff at every ordered pair. -/
theorem exists_cyclicVortexGreedy_globalBound_all_indexedRootedThreat_lt
    {V : Type*} [Fintype V] [DecidableEq V]
    {ell q s : ℕ} (W : Vortex V ell) (B A : TripleSystemOn V)
    (D : Fin (ell + 1) → ℕ) (hD : ∀ k, 0 < D k)
    (c a : ℝ≥0) (hc : c ≤ 1) (ha : 0 < a)
    (houter : ∀ i : Fin ell, 0 < (W.U i.castSucc).card)
    (hterminal : 0 < W.terminalSize)
    (hratio : ∀ k : Fin (ell + 1),
      (vortexPackingSaturationFuel V : ℝ≥0) * (D k : ℝ≥0)⁻¹ ≤
        c / (W.U k).card)
    (hsmall : (Fintype.card (DistinctPair V) : ℝ≥0) *
      (((vortexRootedMomentJointConstant q s : ℝ≥0) *
        (((2 : ℝ≥0) ^ (s * q) *
          ((Fintype.card V : ℝ≥0) *
            indexedRootedThreatVortexUniformCoefficient W q B)) ^ s)) /
        a ^ s) < 1) :
    ∃ S : GreedyStateOn V,
      AbsorberGreedyInvariant
        (absorberErdosForbiddenConfigurationsOn q B) A S ∧
      S.available.card ≤ ∑ k, D k ∧
      S.available ⊆
        (absorberGreedyInitialState
          (absorberErdosForbiddenConfigurationsOn q B) A).available ∧
      ∀ e : DistinctPair V,
        ((activeIndexedRootedThreatWitnesses
          q B S.chosen e.1.1 e.1.2).card : ℝ≥0) < a := by
  let F := absorberErdosForbiddenConfigurationsOn q B
  let S₀ := absorberGreedyInitialState F A
  let L := scheduledStoppedVortexGreedyProcessLaw F W
    (vortexCyclicSchedule ell) D
    (vortexPackingSaturationFuel V * (ell + 1)) S₀
  let Good : GreedyStateOn V → Prop := fun S ↦
    AbsorberGreedyInvariant F A S ∧
      S.available.card ≤ ∑ k, D k ∧ S.available ⊆ S₀.available
  have hS₀ : AbsorberGreedyInvariant F A S₀ := by
    exact absorberGreedyInitialState_invariant F A fun C hC ↦
      absorberErdosForbidden_nonempty hC
  have hsupport : L.SupportedOn Good := by
    exact cyclicVortexGreedy_supported_globalBound hD hS₀
  let eps : ℝ≥0 :=
    ((vortexRootedMomentJointConstant q s : ℝ≥0) *
      (((2 : ℝ≥0) ^ (s * q) *
        ((Fintype.card V : ℝ≥0) *
          indexedRootedThreatVortexUniformCoefficient W q B)) ^ s)) /
      a ^ s
  let bad : Option (DistinctPair V) → GreedyStateOn V → Prop
    | none, S => ¬ Good S
    | some e, S => a ≤
        (activeIndexedRootedThreatWitnesses
          q B S.chosen e.1.1 e.1.2).card
  have hstruct : L.probability (bad none) = 0 := by
    change L.probability (fun S ↦ ¬ Good S) = 0
    rw [L.probability_not, L.probability_eq_one_of_supported Good hsupport]
    simp
  have hprob : ∀ e : DistinctPair V,
      L.probability (bad (some e)) ≤ eps := by
    intro e
    exact cyclicVortexGreedy_probability_indexedRootedThreat_ge_le
      W B A D hD c a hc ha houter hterminal hratio e
  have hsum : ∑ i : Option (DistinctPair V), L.probability (bad i) < 1 := by
    rw [Fintype.sum_option, hstruct, zero_add]
    calc
      ∑ e : DistinctPair V, L.probability (bad (some e)) ≤
          ∑ _e : DistinctPair V, eps := by
        apply sum_le_sum
        intro e he
        exact hprob e
      _ = (Fintype.card (DistinctPair V) : ℝ≥0) * eps := by simp
      _ < 1 := by simpa only [eps] using hsmall
  obtain ⟨S, hS⟩ := L.exists_avoiding_of_sum_probability_lt_one
    (univ : Finset (Option (DistinctPair V))) bad (by simpa using hsum)
  have hGood : Good S := not_not.mp (hS none (mem_univ none))
  refine ⟨S, hGood.1, hGood.2.1, hGood.2.2, ?_⟩
  intro e
  exact lt_of_not_ge (hS (some e) (mem_univ (some e)))

end

end Erdos207
