import ErdosProblems.Erdos788.FiniteField
import Mathlib.Combinatorics.SimpleGraph.Clique

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# Finite-field sum graphs and kernel palettes

This file isolates the exact graph-theoretic consequence needed from the
extractor construction.  The extractor will provide `SetImageExpanding`: a
large source set has a seed for which its linear image contains more than one
representative per antipodal pair.  The union of the seed kernels then has
small cardinality and forces a small independence number.
-/

namespace Erdos788

open Finset

/-- The `k`-dimensional vector space over `ZMod p`. -/
abbrev FFVec (p k : ℕ) := Fin k → ZMod p

/-- The simple sum graph generated by a finite palette in an additive group. -/
def groupSumGraph {V : Type*} [AddCommGroup V] (S : Finset V) :
    SimpleGraph V :=
  SimpleGraph.fromRel fun x y ↦ x + y ∈ S

@[simp]
theorem groupSumGraph_adj {V : Type*} [AddCommGroup V]
    {S : Finset V} {x y : V} :
    (groupSumGraph S).Adj x y ↔ x ≠ y ∧ x + y ∈ S := by
  simp [groupSumGraph, add_comm]

/-- The union of the kernels of an indexed finite family of linear maps. -/
def kernelPalette (p r : ℕ) [Fact p.Prime] {ι : Type*} [DecidableEq ι]
    (Y : Finset ι)
    (F : ι → FFVec p (2 * r) →ₗ[ZMod p] FFVec p r) :
    Finset (FFVec p (2 * r)) :=
  Y.biUnion (kernelFinset p r ∘ F)

/-- The exact set-expansion property used by the kernel-palette argument.

It is enough to prove this property for uniform distributions on source
finsets; the stronger seeded-extractor inequality in the paper implies it.
-/
def SetImageExpanding (p r s : ℕ) {ι : Type*} [DecidableEq ι]
    (Y : Finset ι)
    (F : ι → FFVec p (2 * r) →ₗ[ZMod p] FFVec p r) : Prop :=
  ∀ A : Finset (FFVec p (2 * r)), p ^ (r + s) ≤ A.card →
    ∃ y ∈ Y, p ^ r + 1 < 2 * (A.image (F y)).card

/-- In odd characteristic, the only vector equal to its negative is zero. -/
theorem eq_zero_of_eq_neg_ffVec {p r : ℕ} [Fact p.Prime] (hp : 2 < p)
    (z : FFVec p r) (hz : z = -z) : z = 0 := by
  have htwo : (2 : ZMod p) ≠ 0 := by
    intro hzero
    have hdiv : p ∣ 2 :=
      (ZMod.natCast_eq_zero_iff 2 p).mp (by simpa using! hzero)
    have hle : p ≤ 2 := Nat.le_of_dvd (by omega) hdiv
    omega
  funext i
  change z i = (0 : ZMod p)
  have hzi : z i = -(z i) := congrFun hz i
  have hadd : z i + z i = 0 := (eq_neg_iff_add_eq_zero).mp hzi
  have hmul : (2 : ZMod p) * z i = 0 := by
    simpa [two_mul] using! hadd
  exact (mul_eq_zero.mp hmul).resolve_left htwo

/-- A finite set containing no nonzero antipodal pair occupies at most one
point from each antipodal pair, plus possibly zero. -/
theorem antipodal_support_bound_twice {V : Type*}
    [AddCommGroup V] [Fintype V] [DecidableEq V]
    (T : Finset V)
    (hanti : ∀ z, z ∈ T → -z ∈ T → z = 0) :
    2 * T.card ≤ Fintype.card V + 1 := by
  let Tneg : Finset V := T.image (-·)
  have hnegcard : Tneg.card = T.card := by
    exact Finset.card_image_of_injective T neg_injective
  have hinter : (T ∩ Tneg).card ≤ 1 := by
    rw [Finset.card_le_one]
    intro x hx y hy
    have hx' := Finset.mem_inter.mp hx
    have hy' := Finset.mem_inter.mp hy
    have hxneg : -x ∈ T := by
      rcases Finset.mem_image.mp hx'.2 with ⟨z, hz, hzx⟩
      have hzx' : z = -x := by
        calc
          z = -(-z) := by simp
          _ = -x := congrArg Neg.neg hzx
      simpa [hzx'] using! hz
    have hyneg : -y ∈ T := by
      rcases Finset.mem_image.mp hy'.2 with ⟨z, hz, hzy⟩
      have hzy' : z = -y := by
        calc
          z = -(-z) := by simp
          _ = -y := congrArg Neg.neg hzy
      simpa [hzy'] using! hz
    exact (hanti x hx'.1 hxneg).trans (hanti y hy'.1 hyneg).symm
  have hunion : (T ∪ Tneg).card ≤ Fintype.card V :=
    Finset.card_le_univ _
  have hinclusion := Finset.card_union_add_card_inter T Tneg
  omega

section KernelPalette

variable (p r : ℕ) [Fact p.Prime]

/-- An independent set in a union-of-kernels sum graph has no nonzero
antipodal pair in its image under any selected map. -/
theorem image_antipodal_bound {ι : Type*} [DecidableEq ι]
    (hp : 2 < p) (Y : Finset ι)
    (F : ι → FFVec p (2 * r) →ₗ[ZMod p] FFVec p r)
    (A : Finset (FFVec p (2 * r)))
    (hA : (groupSumGraph (kernelPalette p r Y F)).IsIndepSet
      (A : Set (FFVec p (2 * r))))
    {y : ι} (hy : y ∈ Y) :
    2 * (A.image (F y)).card ≤ p ^ r + 1 := by
  classical
  have hanti : ∀ z, z ∈ A.image (F y) → -z ∈ A.image (F y) → z = 0 := by
    intro z hz hzneg
    rcases Finset.mem_image.mp hz with ⟨a, ha, hFa⟩
    rcases Finset.mem_image.mp hzneg with ⟨a', ha', hFa'⟩
    by_cases hzero : z = 0
    · exact hzero
    · have hneq : a ≠ a' := by
        intro haa'
        subst a'
        have hzneg' : z = -z := hFa.symm.trans hFa'
        exact hzero (eq_zero_of_eq_neg_ffVec hp z hzneg')
      have hker : a + a' ∈ kernelFinset p r (F y) := by
        rw [kernelFinset, Set.mem_toFinset, Set.mem_ofPred_eq]
        change F y (a + a') = 0
        rw [LinearMap.map_add, hFa, hFa', add_neg_cancel]
      have hpal : a + a' ∈ kernelPalette p r Y F := by
        refine Finset.mem_biUnion.mpr ⟨y, hy, ?_⟩
        simpa only [Function.comp_apply] using! hker
      exact (hA ha ha' hneq (groupSumGraph_adj.mpr ⟨hneq, hpal⟩)).elim
  have hbound := antipodal_support_bound_twice (A.image (F y)) hanti
  simpa [FFVec, Fintype.card_fun, ZMod.card] using! hbound

/-- The group-palette proposition in a denominator-free form: a finite
surjective family with the required set-image expansion produces a palette of
size at most `p^(r+d)` and independence number below `p^(r+s)`. -/
theorem exists_kernelPalette_of_setImageExpanding
    {d s : ℕ} {ι : Type*} [DecidableEq ι]
    (hp : 2 < p) (Y : Finset ι)
    (F : ι → FFVec p (2 * r) →ₗ[ZMod p] FFVec p r)
    (hY : Y.card ≤ p ^ d)
    (hF : ∀ y ∈ Y, Function.Surjective (F y))
    (hexpand : SetImageExpanding p r s Y F) :
    ∃ S : Finset (FFVec p (2 * r)),
      S.card ≤ p ^ (r + d) ∧
        (groupSumGraph S).indepNum < p ^ (r + s) := by
  classical
  let S := kernelPalette p r Y F
  refine ⟨S, ?_, ?_⟩
  · calc
      S.card ≤ Y.card * p ^ r := by
        simpa [S, kernelPalette] using! kernel_palette_card_le p r Y F hF
      _ ≤ p ^ d * p ^ r := Nat.mul_le_mul_right (p ^ r) hY
      _ = p ^ (r + d) := by rw [Nat.pow_add]; ac_rfl
  · obtain ⟨A, hA⟩ := (groupSumGraph S).exists_isNIndepSet_indepNum
    by_contra hnot
    have hlarge : p ^ (r + s) ≤ A.card := by
      rw [hA.card_eq]
      omega
    obtain ⟨y, hy, himage⟩ := hexpand A hlarge
    have hsmall : 2 * (A.image (F y)).card ≤ p ^ r + 1 := by
      apply image_antipodal_bound p r hp Y F A
      · simpa [S] using! hA.isIndepSet
      · exact hy
    omega

end KernelPalette

end Erdos788
