import StackExchange.Puzzling139335.CentralRotation.BoundaryOrientation

#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.directionAt_direct
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.winding_direct
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.winding_eq_inside_jordan
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.winding_eq_zero_of_jordan_container
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.winding_boundary_gluing
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.winding_boundary_pieces_eq
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.winding_circle_boundary_ne_zero
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.exists_increasing_boundary_lift_of_winding_eq
#print axioms Puzzling139335.CentralRotation.BoundaryOrientation.exists_increasing_boundary_lift_of_preserves_jordan
#print axioms Puzzling139335.CentralRotation.CrosscutPaths.Data.exists_boundaryLifts_of_direct
