/-
Copyright (c) 2026 The Flypitch Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

Hechler's counterexample in the collapse model: `⊤ ⊩[V 𝔹_collapse] ∼Erdos501_f`, whence
`¬ (ZFC ⊢ Erdos501_f)` and the independence of `Erdos501_f` from `ZFC`.
-/
import ErdosProblems.Erdos501.Flypitch4.Erdos501.CheckReals
import ErdosProblems.Erdos501.Flypitch4.Erdos501.Main
import ErdosProblems.Erdos501.Flypitch4.Summary

set_option relaxedAutoImplicit true

/-!
# Hechler's counterexample in `V 𝔹_collapse`

In the collapse model `V 𝔹_collapse` (`ForcingCH.lean`) the continuum hypothesis holds; here we run
Hechler's construction of a family `⟨A_x : x ∈ ℝ⟩` of countable bounded sets of reals without an
infinite independent set, Boolean-valuedly, for the check-name reals `Rc` (`CheckReals.lean`):

* the collapse generic is a surjection from `ℵ₁̌` onto the ground `𝒫(ω)`; its Boolean values are the
  principal opens `π_af i j` ("the generic maps `i` to `j`") of `ForcingCH.lean`, with
  `⨆ i, π_af i j = ⊤` (`π_af_wide`) and `π_af i j₁ ⊓ π_af i j₂ = ⊥` for `j₁ ≠ j₂` (`π_af_anti`);
* the index type `I` of `ℵ₁̌` is well-ordered with countable initial segments (`toT`);
* `s ∈ A_r` iff `|s| ≤ |r| + 1` and *some* preimage of (the code of) `s` lies below *every*
  preimage of `r` (`memAEv`).  Then `A_r` is bounded (`bounded_Aset`) and countable, so of outer
  measure `< 1` (`outerMeasureLtOne_Aset`: on the piece where the generic maps `i₀` to `r`, `A_r`
  is enumerated along a ground enumeration of the predecessors of `i₀`);
* if `X ⊆ Rc` is infinite and independent, refine (ω-closed refinement, `OmegaClosed.lean`) to a
  nonzero piece deciding an injective sequence `r_k ∈ X` together with the *least* preimages `i_k`
  of the `r_k`; independence forces `i_k < i_l → |r_k| > |r_l| + 1`, which is impossible for a
  sequence of distinct ordinals (`no_independent`).

Hence `⊤ ⊩[V 𝔹_collapse] ∼Erdos501_f` (`neg_erdos501_forced_collapse`),
`Erdos501_f_unprovable : ¬ (ZFC ⊢ₛ' Erdos501_f)` and
`independence_of_Erdos501 : independent ZFC Erdos501_f`.
-/

open Fol bSet Flypitch Lattice collapse_algebra Cardinal
open scoped Flypitch Cardinal

namespace Flypitch.Erdos501

namespace Hechler

open CheckReals

/-- `le_bihimp_iff` in the orientation `a ≤ b ⇔ c ↔ a ⊓ b ≤ c ∧ a ⊓ c ≤ b` (Mathlib's statement is
now generated by `to_dual` and reads `c ⊓ a ≤ b ∧ b ⊓ a ≤ c`). -/
private lemma le_bihimp_iff' {α : Type*} [GeneralizedHeytingAlgebra α] {a b c : α} :
    a ≤ bihimp b c ↔ a ⊓ b ≤ c ∧ a ⊓ c ≤ b := by
  rw [le_bihimp_iff, inf_comm c a, inf_comm b a, and_comm]

private lemma le_bihimp' {α : Type*} [GeneralizedHeytingAlgebra α] {a b c : α}
    (h₁ : a ⊓ b ≤ c) (h₂ : a ⊓ c ≤ b) : a ≤ bihimp b c :=
  le_bihimp_iff'.mpr ⟨h₁, h₂⟩

/-- The collapse algebra (universe `0`). -/
abbrev 𝔹c : Type := collapse_algebra.𝔹_collapse

/-- The index type of the name `ℵ₁̌`. -/
abbrev I : Type := (check pSet_aleph1 : bSet 𝔹c).type

/-- The index type of the name of the ground `𝒫(ω)`. -/
abbrev J : Type := (check (PSet.powerset PSet.omega) : bSet 𝔹c).type

/-! ### Boolean values of ground propositions -/

/-- The Boolean value of a ground proposition. -/
noncomputable def bp (p : Prop) : 𝔹c := ⨆ (_ : p), ⊤

lemma bp_true {p : Prop} (h : p) : bp p = ⊤ := by
  simp [bp, h]

lemma bp_false {p : Prop} (h : ¬ p) : bp p = ⊥ := by
  simp [bp, h]

lemma le_bp {Γ : 𝔹c} {p : Prop} (h : p) : Γ ≤ bp p := by rw [bp_true h]; exact le_top

lemma le_bp_elim {Γ : 𝔹c} {p : Prop} (h : Γ ≤ bp p) : Γ ≤ ⊥ ∨ p := by
  by_cases hp : p
  · exact Or.inr hp
  · left; rwa [bp_false hp] at h

/-! ### The well-order on `I` with countable initial segments -/

/-- The ordinals below `ω₁`. -/
abbrev T : Type := ((Cardinal.aleph 1).ord).ToType

/-- The identification of `I` with `T`. -/
noncomputable def toT (i : I) : T := cast (PSet.ordinalMk_type) (check_cast i)

lemma toT_injective : Function.Injective toT := by
  intro i j h
  have h1 := (cast_inj _).1 h
  exact (cast_inj _).1 h1

lemma countable_pred (i₀ : I) : {i : I | toT i < toT i₀}.Countable := by
  have h1 : (Set.Iio (toT i₀)).Countable := by
    rw [← Cardinal.le_aleph0_iff_set_countable, ← Cardinal.lt_aleph_one_iff]
    have := Cardinal.mk_Iio_lt (toT i₀) (by rw [Cardinal.mk_toType, Cardinal.card_ord,
      Ordinal.type_toType])
    rwa [Cardinal.mk_toType, Cardinal.card_ord] at this
  have h2 : {i : I | toT i < toT i₀} = toT ⁻¹' Set.Iio (toT i₀) := rfl
  rw [h2]
  exact h1.preimage_of_injOn toT_injective.injOn

/-- A ground enumeration of the predecessors of `i₀` (together with `i₀`). -/
lemma exists_enum_pred (i₀ : I) : ∃ e : ℕ → I, ∀ i, toT i < toT i₀ → ∃ n, e n = i := by
  have hc : (insert i₀ {i : I | toT i < toT i₀}).Countable := (countable_pred i₀).insert i₀
  obtain ⟨e, he⟩ := hc.exists_eq_range (Set.insert_nonempty _ _)
  refine ⟨e, fun i hi => ?_⟩
  have : i ∈ Set.range e := by rw [← he]; exact Set.mem_insert_of_mem _ hi
  exact this

/-! ### Codes of reals as elements of the ground `𝒫(ω)` -/

/-- The set of codes of the rationals below `r`. -/
def codeSet' (r : ℝ) : Set (ULift ℕ) :=
  {n : ULift ℕ | ∃ q : ℚ, (q : ℝ) < r ∧ Encodable.encode q = n.down}

lemma codeSet'_injective : Function.Injective codeSet' := by
  intro r s h
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hlt
  · obtain ⟨q, hq1, hq2⟩ := exists_rat_btwn hlt
    have h1 : (⟨Encodable.encode q⟩ : ULift ℕ) ∈ codeSet' s := ⟨q, hq2, rfl⟩
    rw [← h] at h1
    obtain ⟨q', hq', he⟩ := h1
    have := Encodable.encode_injective he
    subst this
    exact absurd hq' (not_lt.2 hq1.le)
  · obtain ⟨q, hq1, hq2⟩ := exists_rat_btwn hlt
    have h1 : (⟨Encodable.encode q⟩ : ULift ℕ) ∈ codeSet' r := ⟨q, hq2, rfl⟩
    rw [h] at h1
    obtain ⟨q', hq', he⟩ := h1
    have := Encodable.encode_injective he
    subst this
    exact absurd hq' (not_lt.2 hq1.le)

/-- The set of codes of the rationals below `r`, as an index of `𝒫(ω)̌`. -/
def codeSet (r : ℝ) : (PSet.powerset PSet.omega : PSet.{0}).Type := codeSet' r

lemma codeSet_injective : Function.Injective codeSet := fun _ _ h => codeSet'_injective h

/-- The index of the code of `r`. -/
def codeIdx (r : ℝ) : J := check_cast_symm (codeSet r)

lemma codeIdx_injective : Function.Injective codeIdx := by
  intro r s h
  unfold codeIdx check_cast_symm at h
  exact codeSet_injective ((cast_inj _).1 h)

/-! ### The generic surjection: the Boolean values `π_af i (codeIdx r)` -/

/-- "The generic maps `i` to (the code of) `r`". -/
noncomputable def gen (i : I) (r : ℝ) : 𝔹c := π_af i (codeIdx r)

lemma gen_wide (r : ℝ) : (⨆ i : I, gen i r) = ⊤ := π_af_wide (codeIdx r)

lemma gen_anti {i : I} {r s : ℝ} (h : r ≠ s) : gen i r ⊓ gen i s ≤ ⊥ :=
  π_af_anti i _ _ fun e => h (codeIdx_injective e)

lemma bot_or_eq_of_le_gen {Γ : 𝔹c} {i : I} {r s : ℝ} (h1 : Γ ≤ gen i r) (h2 : Γ ≤ gen i s) :
    Γ ≤ ⊥ ∨ r = s := by
  by_cases hrs : r = s
  · exact Or.inr hrs
  · exact Or.inl ((le_inf h1 h2).trans (gen_anti hrs))

/-! ### The family -/

/-- "`i` lies below every preimage of `r`". -/
noncomputable def lessEv (i : I) (r : ℝ) : 𝔹c := ⨅ j : I, gen j r ⟹ bp (toT i < toT j)

/-- "`s ∈ A_r`" (apart from the size condition): some preimage of `s` lies below every preimage
of `r`. -/
noncomputable def memAEv (r s : ℝ) : 𝔹c := ⨆ i : I, gen i s ⊓ lessEv i r

/-- The name of `A_r = {s | |s| ≤ |r| + 1 ∧ memAEv r s}`. -/
noncomputable def Aset (r : ℝ) : bSet 𝔹c :=
  ⟨ℝ, fun s => rname s, fun s => bp (|s| ≤ |r| + 1) ⊓ memAEv r s⟩

/-- The name of the family `r ↦ A_r`, as a set of pairs. -/
noncomputable def Aname : bSet 𝔹c := ⟨ℝ, fun r => pair (rname r) (Aset r), fun _ => ⊤⟩

@[simp] lemma Aset_type (r : ℝ) : (Aset r).type = ℝ := rfl
@[simp] lemma Aset_func (r s : ℝ) : (Aset r).func s = rname s := rfl
@[simp] lemma Aset_bval (r s : ℝ) : (Aset r).bval s = bp (|s| ≤ |r| + 1) ⊓ memAEv r s := rfl
@[simp] lemma Aname_type : Aname.type = ℝ := rfl
@[simp] lemma Aname_func (r : Aname.type) : Aname.func r = pair (rname r) (Aset r) := rfl
@[simp] lemma Aname_bval (r : Aname.type) : Aname.bval r = ⊤ := rfl

theorem mem_Aset (r : ℝ) (x : bSet 𝔹c) :
    x ∈ᴮ Aset r = ⨆ s : ℝ, (bp (|s| ≤ |r| + 1) ⊓ memAEv r s) ⊓ x =ᴮ rname s := by
  rw [mem_unfold]; rfl

lemma le_mem_Aset {Γ : 𝔹c} {r s : ℝ} (h1 : |s| ≤ |r| + 1) (h2 : Γ ≤ memAEv r s) :
    Γ ≤ (rname s : bSet 𝔹c) ∈ᴮ Aset r := by
  rw [mem_Aset]
  exact le_iSup_of_le s (le_inf (le_inf (le_bp h1) h2) bv_refl)

lemma mem_Aset_elim {Γ b : 𝔹c} {r : ℝ} {x : bSet 𝔹c} (h : Γ ≤ x ∈ᴮ Aset r)
    (H : ∀ (s : ℝ) (Γ' : 𝔹c), Γ' ≤ Γ → |s| ≤ |r| + 1 → Γ' ≤ memAEv r s → Γ' ≤ x =ᴮ rname s →
      Γ' ≤ b) : Γ ≤ b := by
  refine (le_inf le_rfl h).trans ?_
  rw [mem_Aset]
  refine bv_cases_right fun s => ?_
  by_cases hs : |s| ≤ |r| + 1
  · exact H s _ inf_le_left hs (inf_le_right.trans (inf_le_left.trans inf_le_right))
      (inf_le_right.trans inf_le_right)
  · rw [bp_false hs, bot_inf_eq, bot_inf_eq, inf_bot_eq]
    exact bot_le

lemma Aset_subset_Rc {Γ : 𝔹c} (r : ℝ) : Γ ≤ Aset r ⊆ᴮ Rc := by
  rw [subset_unfold]
  refine le_iInf fun s => ?_
  rw [bv_imp_iff]; intro Γ' _ _
  exact rname_mem_Rc s

lemma Aset_mem_powerset {Γ : 𝔹c} (r : ℝ) : Γ ≤ Aset r ∈ᴮ bv_powerset Rc :=
  bv_powerset_spec.1 (Aset_subset_Rc r)

theorem app_Aname (x y : bSet 𝔹c) :
    Sem.app Aname x y = ⨆ r : ℝ, (x =ᴮ rname r) ⊓ (y =ᴮ Aset r) := by
  rw [Sem.app, mem_unfold]
  simp only [Aname_bval, Aname_func, top_inf_eq]
  apply le_antisymm
  · apply iSup_mono; intro r
    exact le_inf (eq_of_eq_pair_left' le_rfl) (eq_of_eq_pair_right' le_rfl)
  · apply iSup_mono; intro r
    exact pair_eq_pair_iff.mpr ⟨inf_le_left, inf_le_right⟩

lemma le_app_Aname {Γ : 𝔹c} {x y : bSet 𝔹c} {r : ℝ} (hx : Γ ≤ x =ᴮ rname r)
    (hy : Γ ≤ y =ᴮ Aset r) : Γ ≤ Sem.app Aname x y := by
  rw [app_Aname]; exact le_iSup_of_le r (le_inf hx hy)

lemma app_Aname_elim {Γ b : 𝔹c} {x y : bSet 𝔹c} (h : Γ ≤ Sem.app Aname x y)
    (H : ∀ (r : ℝ) (Γ' : 𝔹c), Γ' ≤ Γ → Γ' ≤ x =ᴮ rname r → Γ' ≤ y =ᴮ Aset r → Γ' ≤ b) :
    Γ ≤ b := by
  refine (le_inf le_rfl h).trans ?_
  rw [app_Aname]
  refine bv_cases_right fun r => ?_
  exact H r _ inf_le_left (inf_le_right.trans inf_le_left) (inf_le_right.trans inf_le_right)

/-- `Aname` is a function `Rc → 𝒫(Rc)`. -/
theorem isFun_Aname : ⊤ ≤ Sem.isFun (Rc : bSet 𝔹c) (bv_powerset Rc) Aname := by
  rw [Sem.isFun]
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hx
  refine mem_Rc_elim hx fun r Γ₂ h₂ hxr => ?_
  refine le_iSup_of_le (Aset r) (le_inf (Aset_mem_powerset r) (le_inf (le_app_Aname hxr bv_refl) ?_))
  refine le_iInf fun y' => ?_
  rw [bv_imp_iff]; intro Γ₃ h₃ hy'
  refine app_Aname_elim hy' fun r' Γ₄ h₄ hxr' hy'r' => ?_
  rcases eq_rname_trans ((h₄.trans h₃).trans hxr) hxr' with hb | rfl
  · exact le_of_le_bot hb
  exact hy'r'

/-- Every `A_r` is bounded. -/
theorem bounded_Aset (r : ℝ) : ⊤ ≤ Sem.bounded (Rc : bSet 𝔹c) ltC (Aset r) := by
  rw [Sem.bounded]
  refine le_iSup_of_le (rname (-(|r| + 2))) (le_inf (rname_mem_Rc _) ?_)
  refine le_iSup_of_le (rname (|r| + 2)) (le_inf (rname_mem_Rc _) ?_)
  refine le_iInf fun y => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hy
  refine mem_Aset_elim hy fun s Γ₂ _ hs _ hys => ?_
  have h1 := abs_le.1 hs
  exact le_inf (le_lt_ltC bv_refl hys (by linarith [h1.1])) (le_lt_ltC hys bv_refl (by linarith [h1.2]))


/-! ### Small facts about `ω`, `of_nat` and `Sem.succ` -/

lemma mem_omega_eq' (z : bSet 𝔹c) : (z ∈ᴮ omega) = ⨆ n : ℕ, z =ᴮ of_nat n := by
  rw [mem_unfold]
  simp only [omega_bval, omega_func, top_inf_eq]
  exact le_antisymm (iSup_le fun i => le_iSup_of_le i.down le_rfl)
    (iSup_le fun n => le_iSup_of_le (ULift.up n) le_rfl)

lemma mem_omega_elim {Γ b : 𝔹c} {x : bSet 𝔹c} (h : Γ ≤ x ∈ᴮ omega)
    (H : ∀ (n : ℕ) (Γ' : 𝔹c), Γ' ≤ Γ → Γ' ≤ x =ᴮ of_nat n → Γ' ≤ b) : Γ ≤ b := by
  refine (le_inf le_rfl h).trans ?_
  rw [mem_omega_eq']
  exact bv_cases_right fun n => H n _ inf_le_left inf_le_right

lemma bot_or_eq_of_of_nat_eq {Γ : 𝔹c} {n m : ℕ} (h : Γ ≤ (of_nat n : bSet 𝔹c) =ᴮ of_nat m) :
    Γ ≤ ⊥ ∨ n = m := by
  by_cases hnm : n = m
  · exact Or.inr hnm
  · left; rwa [of_nat_inj' hnm] at h

lemma of_nat_zero_eq' : (of_nat 0 : bSet 𝔹c) = bSet.empty := by
  show check (PSet.ofNat 0) = bSet.empty
  rw [show PSet.ofNat 0 = ∅ from rfl]
  exact check_empty_eq_empty

lemma mem_of_nat_succ' (z : bSet 𝔹c) (n : ℕ) :
    (z ∈ᴮ of_nat (n + 1)) = (z ∈ᴮ of_nat n ⊔ z =ᴮ of_nat n) := by
  show z ∈ᴮ check (PSet.insert (PSet.ofNat n) (PSet.ofNat n)) = _
  rw [check_insert]
  show z ∈ᴮ insert (check (PSet.ofNat n)) (check (PSet.ofNat n)) = _
  rw [mem_insert1, sup_comm]

lemma succ_of_nat' {Γ : 𝔹c} (n : ℕ) : Γ ≤ Sem.succ (of_nat n : bSet 𝔹c) (of_nat (n + 1)) := by
  rw [Sem.succ]
  refine le_iInf fun z => ?_
  rw [mem_of_nat_succ', bihimp_self]
  exact le_top

lemma succ_unique' {Γ : 𝔹c} {n m m' : bSet 𝔹c} (h : Γ ≤ Sem.succ n m) (h' : Γ ≤ Sem.succ n m') :
    Γ ≤ m =ᴮ m' := by
  refine le_trans ?_ (bSet_axiom_of_extensionality m m')
  refine le_iInf fun z => ?_
  rw [Sem.succ] at h h'
  have h1 := le_bihimp_iff'.mp (h.trans (iInf_le _ z))
  have h2 := le_bihimp_iff'.mp (h'.trans (iInf_le _ z))
  refine le_inf ?_ ?_
  · rw [← _root_.deduction]; exact (le_inf inf_le_left h1.1).trans h2.2
  · rw [← _root_.deduction]; exact (le_inf inf_le_left h2.1).trans h1.2

lemma succ_congr_left' {Γ : 𝔹c} {n n' m : bSet 𝔹c} (h : Γ ≤ n =ᴮ n') (hs : Γ ≤ Sem.succ n m) :
    Γ ≤ Sem.succ n' m := by
  rw [Sem.succ] at hs ⊢
  refine le_iInf fun z => ?_
  have h1 := le_bihimp_iff'.mp (hs.trans (iInf_le _ z))
  refine le_bihimp' ?_ ?_
  · refine (le_inf inf_le_left h1.1).trans ?_
    rw [inf_sup_left]
    refine sup_le (le_sup_of_le_left ?_) (le_sup_of_le_right ?_)
    · exact mem_congr bv_refl (inf_le_left.trans h) inf_le_right
    · exact bv_trans inf_le_right (inf_le_left.trans h)
  · refine le_trans ?_ h1.2
    refine le_inf inf_le_left ?_
    rw [inf_sup_left] at *
    refine sup_le (le_sup_of_le_left ?_) (le_sup_of_le_right ?_)
    · exact mem_congr bv_refl (bv_symm (inf_le_left.trans h)) inf_le_right
    · exact bv_trans inf_le_right (bv_symm (inf_le_left.trans h))

/-! ### The outer-measure witnesses for `A_r` -/

/-- The half-lengths of the covering intervals. -/
noncomputable def δ (n : ℕ) : ℝ := 1 / 2 ^ (n + 3)

lemma δ_pos (n : ℕ) : 0 < δ n := by unfold δ; positivity

/-- The partial sums of the lengths `2 δ n`. -/
noncomputable def Ssum (n : ℕ) : ℝ := ∑ i ∈ Finset.range n, 2 * δ i

lemma Ssum_zero : Ssum 0 = 0 := by simp [Ssum]

lemma Ssum_succ (n : ℕ) : Ssum (n + 1) = Ssum n + 2 * δ n := by
  simp [Ssum, Finset.sum_range_succ]

lemma Ssum_le (n : ℕ) : Ssum n ≤ 1 / 2 := by
  have h : ∀ i : ℕ, 2 * δ i = (1 / 4 : ℝ) * (1 / 2 : ℝ) ^ i := by
    intro i
    unfold δ
    rw [one_div_pow, pow_add]
    field_simp
    norm_num
  calc Ssum n = ∑ i ∈ Finset.range n, (1 / 4 : ℝ) * (1 / 2 : ℝ) ^ i :=
        Finset.sum_congr rfl fun i _ => h i
    _ = (1 / 4 : ℝ) * ∑ i ∈ Finset.range n, (1 / 2 : ℝ) ^ i := by rw [Finset.mul_sum]
    _ ≤ (1 / 4 : ℝ) * 2 := by gcongr; exact sum_geometric_two_le n
    _ = 1 / 2 := by norm_num

/-- The event "the generic maps the `n`-th predecessor to (the code of) `s`". -/
noncomputable def cEv (e : ℕ → I) (n : ℕ) (s : ℝ) : 𝔹c := gen (e n) s

/-- The event "the generic maps the `n`-th predecessor to no code of a real". -/
noncomputable def noneEv (e : ℕ → I) (n : ℕ) : 𝔹c := ⨅ s : ℝ, (gen (e n) s)ᶜ

/-- The weight of the value `s` at position `n`: `s` is the value there, or there is no value and
`s = 0`. -/
noncomputable def wEv (e : ℕ → I) (n : ℕ) (s : ℝ) : 𝔹c := cEv e n s ⊔ (noneEv e n ⊓ bp (s = 0))

lemma wEv_total (e : ℕ → I) (n : ℕ) : (⨆ s : ℝ, wEv e n s) = ⊤ := by
  apply top_unique
  have h1 : (⨆ s : ℝ, cEv e n s) ⊔ noneEv e n = ⊤ := by
    rw [noneEv, ← compl_iSup]
    exact sup_compl_eq_top
  rw [← h1]
  refine sup_le ?_ ?_
  · exact iSup_mono fun s => le_sup_left
  · refine le_iSup_of_le 0 (le_sup_of_le_right ?_)
    rw [bp_true rfl, inf_top_eq]

lemma wEv_disjoint (e : ℕ → I) (n : ℕ) {s s' : ℝ} (h : s ≠ s') : wEv e n s ⊓ wEv e n s' ≤ ⊥ := by
  unfold wEv
  rw [inf_sup_left, inf_sup_right, inf_sup_right]
  refine sup_le (sup_le ?_ ?_) (sup_le ?_ ?_)
  · exact gen_anti h
  · have : noneEv e n ⊓ bp (s = 0) ≤ (cEv e n s')ᶜ := inf_le_left.trans (iInf_le _ s')
    exact (inf_le_inf_right _ this).trans (by rw [compl_inf_eq_bot])
  · have : noneEv e n ⊓ bp (s' = 0) ≤ (cEv e n s)ᶜ := inf_le_left.trans (iInf_le _ s)
    exact (inf_le_inf_left _ this).trans (by rw [inf_compl_eq_bot])
  · by_cases hs : s = 0
    · subst hs
      rw [bp_false (Ne.symm h), inf_bot_eq, inf_bot_eq]
    · rw [bp_false hs, inf_bot_eq, bot_inf_eq]

lemma le_wEv_of_cEv {Γ : 𝔹c} {e : ℕ → I} {n : ℕ} {s : ℝ} (h : Γ ≤ cEv e n s) : Γ ≤ wEv e n s :=
  h.trans le_sup_left

lemma bot_or_eq_of_le_wEv {Γ : 𝔹c} {e : ℕ → I} {n : ℕ} {s s' : ℝ} (h1 : Γ ≤ wEv e n s)
    (h2 : Γ ≤ wEv e n s') : Γ ≤ ⊥ ∨ s = s' := by
  by_cases hss : s = s'
  · exact Or.inr hss
  · exact Or.inl ((le_inf h1 h2).trans (wEv_disjoint e n hss))

/-- The name of the sequence of endpoints `n ↦ (value at n) + sgn * δ n`. -/
noncomputable def endName (e : ℕ → I) (sgn : ℝ) : bSet 𝔹c :=
  ⟨ℕ × ℝ, fun p => pair (of_nat p.1) (rname (p.2 + sgn * δ p.1)), fun p => wEv e p.1 p.2⟩

/-- The name of a ground sequence of reals. -/
noncomputable def seqName (f : ℕ → ℝ) : bSet 𝔹c :=
  ⟨ℕ, fun n => pair (of_nat n) (rname (f n)), fun _ => ⊤⟩

@[simp] lemma seqName_bval (f : ℕ → ℝ) (n : (seqName f).type) : (seqName f).bval n = ⊤ := rfl
@[simp] lemma seqName_func (f : ℕ → ℝ) (n : (seqName f).type) :
    (seqName f).func n = pair (of_nat n) (rname (f n)) := rfl

theorem app_endName (e : ℕ → I) (sgn : ℝ) (x y : bSet 𝔹c) :
    Sem.app (endName e sgn) x y =
      ⨆ p : ℕ × ℝ, wEv e p.1 p.2 ⊓ (x =ᴮ of_nat p.1 ⊓ y =ᴮ rname (p.2 + sgn * δ p.1)) := by
  rw [Sem.app, mem_unfold]
  apply le_antisymm
  · apply iSup_mono; intro p
    exact inf_le_inf_left _ (le_inf (eq_of_eq_pair_left' le_rfl) (eq_of_eq_pair_right' le_rfl))
  · apply iSup_mono; intro p
    exact inf_le_inf_left _ (pair_eq_pair_iff.mpr ⟨inf_le_left, inf_le_right⟩)

lemma le_app_endName {Γ : 𝔹c} {e : ℕ → I} {sgn : ℝ} {x y : bSet 𝔹c} {n : ℕ} {s : ℝ}
    (hw : Γ ≤ wEv e n s) (hx : Γ ≤ x =ᴮ of_nat n) (hy : Γ ≤ y =ᴮ rname (s + sgn * δ n)) :
    Γ ≤ Sem.app (endName e sgn) x y := by
  rw [app_endName]
  exact le_iSup_of_le (n, s) (le_inf hw (le_inf hx hy))

lemma app_endName_elim {Γ b : 𝔹c} {e : ℕ → I} {sgn : ℝ} {x y : bSet 𝔹c}
    (h : Γ ≤ Sem.app (endName e sgn) x y)
    (H : ∀ (n : ℕ) (s : ℝ) (Γ' : 𝔹c), Γ' ≤ Γ → Γ' ≤ wEv e n s → Γ' ≤ x =ᴮ of_nat n →
      Γ' ≤ y =ᴮ rname (s + sgn * δ n) → Γ' ≤ b) : Γ ≤ b := by
  refine (le_inf le_rfl h).trans ?_
  rw [app_endName]
  refine bv_cases_right fun p => ?_
  exact H p.1 p.2 _ inf_le_left (inf_le_right.trans inf_le_left)
    (inf_le_right.trans (inf_le_right.trans inf_le_left))
    (inf_le_right.trans (inf_le_right.trans inf_le_right))

theorem app_seqName (f : ℕ → ℝ) (x y : bSet 𝔹c) :
    Sem.app (seqName f) x y = ⨆ n : ℕ, x =ᴮ of_nat n ⊓ y =ᴮ rname (f n) := by
  rw [Sem.app, mem_unfold]
  simp only [seqName_bval, seqName_func, top_inf_eq]
  apply le_antisymm
  · apply iSup_mono; intro n
    exact le_inf (eq_of_eq_pair_left' le_rfl) (eq_of_eq_pair_right' le_rfl)
  · apply iSup_mono; intro n
    exact pair_eq_pair_iff.mpr ⟨inf_le_left, inf_le_right⟩

lemma le_app_seqName {Γ : 𝔹c} {f : ℕ → ℝ} {x y : bSet 𝔹c} {n : ℕ} (hx : Γ ≤ x =ᴮ of_nat n)
    (hy : Γ ≤ y =ᴮ rname (f n)) : Γ ≤ Sem.app (seqName f) x y := by
  rw [app_seqName]; exact le_iSup_of_le n (le_inf hx hy)

lemma app_seqName_elim {Γ b : 𝔹c} {f : ℕ → ℝ} {x y : bSet 𝔹c} (h : Γ ≤ Sem.app (seqName f) x y)
    (H : ∀ (n : ℕ) (Γ' : 𝔹c), Γ' ≤ Γ → Γ' ≤ x =ᴮ of_nat n → Γ' ≤ y =ᴮ rname (f n) → Γ' ≤ b) :
    Γ ≤ b := by
  refine (le_inf le_rfl h).trans ?_
  rw [app_seqName]
  refine bv_cases_right fun n => ?_
  exact H n _ inf_le_left (inf_le_right.trans inf_le_left) (inf_le_right.trans inf_le_right)

theorem isFun_endName (e : ℕ → I) (sgn : ℝ) : ⊤ ≤ Sem.isFun omega (Rc : bSet 𝔹c) (endName e sgn) := by
  rw [Sem.isFun]
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hx
  refine mem_omega_elim hx fun n Γ₂ _ hxn => ?_
  have hsplit : Γ₂ = ⨆ s : ℝ, Γ₂ ⊓ wEv e n s := by
    rw [← inf_iSup_eq, wEv_total, inf_top_eq]
  rw [hsplit]
  refine iSup_le fun s => ?_
  refine le_iSup_of_le (rname (s + sgn * δ n)) (le_inf (rname_mem_Rc _) (le_inf ?_ ?_))
  · exact le_app_endName inf_le_right (inf_le_left.trans hxn) bv_refl
  · refine le_iInf fun y' => ?_
    rw [bv_imp_iff]; intro Γ₃ h₃ hy'
    refine app_endName_elim hy' fun m s' Γ₄ h₄ hw' hxm hy's' => ?_
    have hxn' : Γ₄ ≤ x =ᴮ of_nat n := (h₄.trans h₃).trans (inf_le_left.trans hxn)
    rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm hxn') hxm) with hb | rfl
    · exact le_of_le_bot hb
    rcases bot_or_eq_of_le_wEv ((h₄.trans h₃).trans inf_le_right) hw' with hb | rfl
    · exact le_of_le_bot hb
    exact hy's'

theorem isFun_seqName (f : ℕ → ℝ) : ⊤ ≤ Sem.isFun omega (Rc : bSet 𝔹c) (seqName f) := by
  rw [Sem.isFun]
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hx
  refine mem_omega_elim hx fun n Γ₂ _ hxn => ?_
  refine le_iSup_of_le (rname (f n)) (le_inf (rname_mem_Rc _) (le_inf (le_app_seqName hxn bv_refl) ?_))
  refine le_iInf fun y' => ?_
  rw [bv_imp_iff]; intro Γ₃ h₃ hy'
  refine app_seqName_elim hy' fun m Γ₄ h₄ hxm hy'm => ?_
  rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm ((h₄.trans h₃).trans hxn)) hxm) with hb | rfl
  · exact le_of_le_bot hb
  exact hy'm

theorem nondegenerate_endName (e : ℕ → I) :
    ⊤ ≤ Sem.nondegenerate ltC (endName e (-1) : bSet 𝔹c) (endName e 1) := by
  rw [Sem.nondegenerate]
  refine le_iInf fun n => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hn
  refine le_iInf fun u => le_iInf fun v => ?_
  rw [bv_imp_iff]; intro Γ₂ h₂ hu
  rw [bv_imp_iff]; intro Γ₃ h₃ hv
  refine app_endName_elim (h₃.trans hu) fun k s Γ₄ h₄ hw hnk hu' => ?_
  refine app_endName_elim (h₄.trans hv) fun k' s' Γ₅ h₅ hw' hnk' hv' => ?_
  rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm (h₅.trans hnk)) hnk') with hb | rfl
  · exact le_of_le_bot hb
  rcases bot_or_eq_of_le_wEv (h₅.trans hw) hw' with hb | rfl
  · exact le_of_le_bot hb
  refine le_lt_ltC (h₅.trans hu') hv' ?_
  have := δ_pos k
  linarith

theorem covers_endName {r : ℝ} {i₀ : I} {e : ℕ → I} (he : ∀ i, toT i < toT i₀ → ∃ n, e n = i) :
    gen i₀ r ≤ Sem.covers ltC (Aset r) (endName e (-1) : bSet 𝔹c) (endName e 1) := by
  rw [Sem.covers]
  refine le_iInf fun y => ?_
  rw [bv_imp_iff]; intro Γ₁ h₁ hy
  refine mem_Aset_elim hy fun s Γ₂ h₂ _ hmem hys => ?_
  refine (le_inf le_rfl hmem).trans ?_
  rw [memAEv]
  refine bv_cases_right fun i => ?_
  have hgen : Γ₂ ⊓ (gen i s ⊓ lessEv i r) ≤ gen i s := inf_le_right.trans inf_le_left
  have hless : Γ₂ ⊓ (gen i s ⊓ lessEv i r) ≤ bp (toT i < toT i₀) := by
    have h1 : Γ₂ ⊓ (gen i s ⊓ lessEv i r) ≤ gen i₀ r ⟹ bp (toT i < toT i₀) :=
      (inf_le_right.trans inf_le_right).trans (iInf_le _ i₀)
    exact bv_imp_iff.1 h1 le_rfl ((inf_le_left.trans h₂).trans h₁)
  rcases le_bp_elim hless with hb | hlt
  · exact le_of_le_bot hb
  obtain ⟨n, rfl⟩ := he i hlt
  refine le_iSup_of_le (of_nat n) (le_inf of_nat_mem_omega ?_)
  refine le_iSup_of_le (rname (s + (-1) * δ n)) (le_iSup_of_le (rname (s + 1 * δ n)) ?_)
  have hys' : Γ₂ ⊓ (gen (e n) s ⊓ lessEv (e n) r) ≤ y =ᴮ rname s := inf_le_left.trans hys
  have hδ := δ_pos n
  refine le_inf (le_app_endName (le_wEv_of_cEv hgen) bv_refl bv_refl)
    (le_inf (le_app_endName (le_wEv_of_cEv hgen) bv_refl bv_refl)
    (le_inf (le_lt_ltC bv_refl hys' (by linarith)) (le_lt_ltC hys' bv_refl (by linarith))))

theorem app_seqName_zero : ⊤ ≤ Sem.app (seqName Ssum) bSet.empty (zeroC : bSet 𝔹c) := by
  refine le_app_seqName (n := 0) ?_ ?_
  · rw [of_nat_zero_eq']; exact bv_refl
  · rw [Ssum_zero]; exact bv_refl

theorem partialSums_endName (e : ℕ → I) :
    ⊤ ≤ Sem.partialSums plusC (endName e (-1) : bSet 𝔹c) (endName e 1) (seqName Ssum) := by
  rw [Sem.partialSums]
  refine le_iInf fun n => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hn
  refine le_iInf fun m => ?_
  rw [bv_imp_iff]; intro Γ₂ h₂ hnm
  refine le_iInf fun u => le_iInf fun v => le_iInf fun w => le_iInf fun w' =>
    le_iInf fun t => le_iInf fun t' => ?_
  rw [bv_imp_iff]; intro Γ₃ h₃ hu
  rw [bv_imp_iff]; intro Γ₄ h₄ hv
  rw [bv_imp_iff]; intro Γ₅ h₅ hw
  rw [bv_imp_iff]; intro Γ₆ h₆ hw'
  rw [bv_imp_iff]; intro Γ₇ h₇ ht
  rw [bv_imp_iff]; intro Γ₈ h₈ ht'
  have H₇ : Γ₈ ≤ Γ₇ := h₈
  have H₆ : Γ₈ ≤ Γ₆ := H₇.trans h₇
  have H₅ : Γ₈ ≤ Γ₅ := H₆.trans h₆
  have H₄ : Γ₈ ≤ Γ₄ := H₅.trans h₅
  have H₃ : Γ₈ ≤ Γ₃ := H₄.trans h₄
  have H₂ : Γ₈ ≤ Γ₂ := H₃.trans h₃
  refine mem_omega_elim (H₂.trans (h₂.trans hn)) fun k Γ₉ h₉ hnk => ?_
  have hm : Γ₉ ≤ m =ᴮ of_nat (k + 1) :=
    succ_unique' (succ_congr_left' hnk ((h₉.trans H₂).trans hnm)) (succ_of_nat' k)
  refine app_endName_elim ((h₉.trans H₃).trans hu) fun k₁ s₁ Γ₁₀ h₁₀ hw₁ hnk₁ hu₁ => ?_
  refine app_endName_elim ((h₁₀.trans (h₉.trans H₄)).trans hv) fun k₂ s₂ Γ₁₁ h₁₁ hw₂ hnk₂ hv₂ => ?_
  refine app_seqName_elim (((h₁₁.trans h₁₀).trans (h₉.trans H₅)).trans hw)
    fun k₃ Γ₁₂ h₁₂ hnk₃ hw₃ => ?_
  refine app_seqName_elim ((((h₁₂.trans h₁₁).trans h₁₀).trans (h₉.trans H₆)).trans hw')
    fun k₄ Γ₁₃ h₁₃ hmk₄ hw₄ => ?_
  refine app2_opC_elim (((((h₁₃.trans h₁₂).trans h₁₁).trans h₁₀).trans (h₉.trans H₇)).trans ht)
    fun a₁ b₁ Γ₁₄ h₁₄ hwa hub htab => ?_
  refine app2_opC_elim ((((((h₁₄.trans h₁₃).trans h₁₂).trans h₁₁).trans h₁₀).trans h₉).trans ht')
    fun a₂ b₂ Γ₁₅ h₁₅ hwa₂ hvb ht'ab => ?_
  have G₁₄ : Γ₁₅ ≤ Γ₁₄ := h₁₅
  have G₁₃ : Γ₁₅ ≤ Γ₁₃ := G₁₄.trans h₁₄
  have G₁₂ : Γ₁₅ ≤ Γ₁₂ := G₁₃.trans h₁₃
  have G₁₁ : Γ₁₅ ≤ Γ₁₁ := G₁₂.trans h₁₂
  have G₁₀ : Γ₁₅ ≤ Γ₁₀ := G₁₁.trans h₁₁
  have G₉ : Γ₁₅ ≤ Γ₉ := G₁₀.trans h₁₀
  rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm (G₉.trans hnk)) (G₁₀.trans hnk₁)) with hb | rfl
  · exact le_of_le_bot hb
  rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm (G₉.trans hnk)) (G₁₁.trans hnk₂)) with hb | rfl
  · exact le_of_le_bot hb
  rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm (G₉.trans hnk)) (G₁₂.trans hnk₃)) with hb | rfl
  · exact le_of_le_bot hb
  rcases bot_or_eq_of_of_nat_eq (bv_trans (bv_symm (G₉.trans hm)) (G₁₃.trans hmk₄)) with hb | hk₄
  · exact le_of_le_bot hb
  subst hk₄
  rcases bot_or_eq_of_le_wEv (G₁₀.trans hw₁) (G₁₁.trans hw₂) with hb | rfl
  · exact le_of_le_bot hb
  rcases eq_rname_trans (G₁₃.trans hw₄) (G₁₄.trans hwa) with hb | rfl
  · exact le_of_le_bot hb
  rcases eq_rname_trans (G₁₀.trans hu₁) (G₁₄.trans hub) with hb | rfl
  · exact le_of_le_bot hb
  rcases eq_rname_trans (G₁₂.trans hw₃) hwa₂ with hb | rfl
  · exact le_of_le_bot hb
  rcases eq_rname_trans (G₁₁.trans hv₂) hvb with hb | rfl
  · exact le_of_le_bot hb
  refine bv_eq_of_eq_rname (G₁₄.trans htab) ?_
  rw [Ssum_succ]
  convert ht'ab using 3
  ring

theorem sumsBounded_seqName : ⊤ ≤ Sem.sumsBounded (Rc : bSet 𝔹c) ltC oneC (seqName Ssum) := by
  rw [Sem.sumsBounded]
  refine le_iSup_of_le (rname (1 / 2)) (le_inf (rname_mem_Rc _) (le_inf ?_ ?_))
  · exact lt_ltC_rname (by norm_num)
  · refine le_iInf fun n => ?_
    rw [bv_imp_iff]; intro Γ₁ _ hn
    refine le_iInf fun w => ?_
    rw [bv_imp_iff]; intro Γ₂ h₂ hw
    refine app_seqName_elim hw fun k Γ₃ h₃ _ hwk => ?_
    exact le_le_ltC hwk bv_refl (Ssum_le k)

/-- On the piece where the generic maps `i₀` to `r`, `A_r` has outer measure `< 1`. -/
theorem outerMeasureLtOne_Aset_piece (r : ℝ) (i₀ : I) :
    gen i₀ r ≤ Sem.outerMeasureLtOne (Rc : bSet 𝔹c) plusC ltC zeroC oneC (Aset r) := by
  obtain ⟨e, he⟩ := exists_enum_pred i₀
  rw [Sem.outerMeasureLtOne]
  refine le_iSup_of_le (endName e (-1)) (le_iSup_of_le (endName e 1) (le_iSup_of_le (seqName Ssum) ?_))
  refine le_inf (le_top.trans (isFun_endName e (-1))) (le_inf (le_top.trans (isFun_endName e 1))
    (le_inf (le_top.trans (isFun_seqName Ssum)) (le_inf (le_top.trans (nondegenerate_endName e))
    (le_inf (covers_endName he) (le_inf (le_top.trans app_seqName_zero)
    (le_inf (le_top.trans (partialSums_endName e)) (le_top.trans sumsBounded_seqName)))))))

/-- Every `A_r` has outer measure `< 1`. -/
theorem outerMeasureLtOne_Aset (r : ℝ) :
    ⊤ ≤ Sem.outerMeasureLtOne (Rc : bSet 𝔹c) plusC ltC zeroC oneC (Aset r) := by
  rw [← gen_wide r]
  exact iSup_le fun i₀ => outerMeasureLtOne_Aset_piece r i₀

/-! ### Extensionality of the hypotheses in the set variable, and the hypothesis on `Aname` -/

lemma B_ext_bounded : B_ext (fun S : bSet 𝔹c => Sem.bounded Rc ltC S) := by
  unfold Sem.bounded
  exact B_ext_iSup (h := fun m₁ => B_ext_inf B_ext_const (B_ext_iSup (h := fun m₂ =>
    B_ext_inf B_ext_const (B_ext_iInf (h := fun y =>
      B_ext_imp (h₁ := B_ext_mem_right) (h₂ := B_ext_const))))))

lemma B_ext_covers (a b : bSet 𝔹c) : B_ext (fun S : bSet 𝔹c => Sem.covers ltC S a b) := by
  unfold Sem.covers
  exact B_ext_iInf (h := fun y => B_ext_imp (h₁ := B_ext_mem_right) (h₂ := B_ext_const))

lemma B_ext_outerMeasureLtOne :
    B_ext (fun S : bSet 𝔹c => Sem.outerMeasureLtOne Rc plusC ltC zeroC oneC S) := by
  unfold Sem.outerMeasureLtOne
  exact B_ext_iSup (h := fun a => B_ext_iSup (h := fun b => B_ext_iSup (h := fun s =>
    B_ext_inf B_ext_const (B_ext_inf B_ext_const (B_ext_inf B_ext_const (B_ext_inf B_ext_const
      (B_ext_inf (B_ext_covers a b) B_ext_const)))))))

/-- The values of `Aname` are bounded and of outer measure `< 1`. -/
theorem hyp_Aname :
    ⊤ ≤ ⨅ x : bSet 𝔹c, x ∈ᴮ Rc ⟹ ⨅ Ax : bSet 𝔹c, Sem.app Aname x Ax ⟹
      (Sem.bounded Rc ltC Ax ⊓ Sem.outerMeasureLtOne Rc plusC ltC zeroC oneC Ax) := by
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ _ _
  refine le_iInf fun Ax => ?_
  rw [bv_imp_iff]; intro Γ₂ _ hAx
  refine app_Aname_elim hAx fun r Γ₃ _ _ hAxr => ?_
  refine le_inf ?_ ?_
  · exact bv_rw' hAxr (h_congr := B_ext_bounded) (H_new := le_top.trans (bounded_Aset r))
  · exact bv_rw' hAxr (h_congr := B_ext_outerMeasureLtOne)
      (H_new := le_top.trans (outerMeasureLtOne_Aset r))

theorem no_descent {α : Type*} [LinearOrder α] [WellFoundedLT α] (w : ℕ → α)
    (hw : Function.Injective w) (v : ℕ → ℝ)
    (hv : ∀ k, 0 ≤ v k) (hlt : ∀ k l, w k < w l → v l + 1 < v k) : False := by
  classical
  set N : ℕ → ℕ := fun k => ⌊v k⌋₊ with hN
  have hNlt : ∀ k l, w k < w l → N l < N k := by
    intro k l h
    have hfl := Nat.floor_le (hv l)
    have h2 := hlt k l h
    have h3 : N l + 1 ≤ N k := Nat.le_floor (by push_cast [hN]; linarith)
    omega
  have hmin : ∀ s : Finset ℕ, ∃ k, k ∉ s ∧ ∀ l, l ∉ s → N k ≤ N l := by
    intro s
    have hne : (N '' {k | k ∉ s}).Nonempty := by
      obtain ⟨k, hk⟩ := (Set.Finite.infinite_compl s.finite_toSet).nonempty
      exact ⟨N k, k, hk, rfl⟩
    refine ⟨(Nat.sInf_mem hne).choose, (Nat.sInf_mem hne).choose_spec.1, fun l hl => ?_⟩
    rw [(Nat.sInf_mem hne).choose_spec.2]; exact Nat.sInf_le ⟨l, hl, rfl⟩
  let st : ℕ → Finset ℕ := fun n => Nat.rec ∅ (fun _ s => insert (hmin s).choose s) n
  let k : ℕ → ℕ := fun n => (hmin (st n)).choose
  have hst_succ : ∀ n, st (n + 1) = insert (k n) (st n) := fun n => rfl
  have hknotin : ∀ n, k n ∉ st n := fun n => (hmin (st n)).choose_spec.1
  have hkmin : ∀ n l, l ∉ st n → N (k n) ≤ N l := fun n => (hmin (st n)).choose_spec.2
  have hst_mono : ∀ m n, m ≤ n → st m ⊆ st n := by
    intro m n hmn
    induction n with
    | zero => rw [Nat.le_zero.1 hmn]
    | succ n ih =>
      rcases Nat.lt_succ_iff_lt_or_eq.1 (Nat.lt_succ_of_le hmn) with h | h
      · exact (ih (Nat.lt_succ_iff.1 h)).trans (by rw [hst_succ]; exact Finset.subset_insert _ _)
      · rw [← h]
  have hk_mem : ∀ n, k n ∈ st (n + 1) := fun n => by rw [hst_succ]; exact Finset.mem_insert_self _ _
  have hkmax : ∀ n l, l ∉ st n → w l ≤ w (k n) := by
    intro n l hl; by_contra h
    exact absurd (hkmin n l hl) (not_le.2 (hNlt _ _ (not_le.1 h)))
  have hsucc_lt : ∀ n, w (k (n + 1)) < w (k n) := by
    intro n
    have hne : k (n + 1) ≠ k n := fun h => hknotin (n + 1) (h ▸ hk_mem n)
    have hle : w (k (n + 1)) ≤ w (k n) :=
      hkmax n (k (n + 1)) (fun hmem => hknotin (n + 1) ((hst_mono n (n + 1) (Nat.le_succ n)) hmem))
    exact lt_of_le_of_ne hle (fun e => hne (hw e))
  exact not_strictAnti_of_wellFoundedLT (fun n => w (k n)) (strictAnti_nat_of_succ_lt hsucc_lt)

noncomputable def leastEv (i : I) (r : ℝ) : 𝔹c := gen i r ⊓ ⨅ j : I, gen j r ⟹ bp (toT i ≤ toT j)
lemma leastEv_gen {Γ : 𝔹c} {i : I} {r : ℝ} (h : Γ ≤ leastEv i r) : Γ ≤ gen i r := h.trans inf_le_left
lemma exists_least_of_gen {Γ : 𝔹c} {r : ℝ} {i₀ : I} (hΓ : ⊥ < Γ) (hg : Γ ≤ gen i₀ r) :
    ∃ (i : I) (Γ' : 𝔹c), ⊥ < Γ' ∧ Γ' ≤ Γ ∧ Γ' ≤ leastEv i r := by
  classical
  set U : Set T := {t | ∃ i : I, toT i = t ∧ ⊥ < Γ ⊓ gen i r} with hU
  have hUne : U.Nonempty := ⟨toT i₀, i₀, rfl, by rwa [inf_of_le_left hg]⟩
  obtain ⟨t, ⟨i, hti, hposi⟩, hmin⟩ := (wellFounded_lt (α := T)).has_min U hUne
  refine ⟨i, Γ ⊓ gen i r, hposi, inf_le_left, le_inf inf_le_right ?_⟩
  refine le_iInf fun j => ?_
  rw [bv_imp_iff]; intro Γ' hΓ' hgj
  by_cases hpos : ⊥ < Γ'
  · rcases le_or_gt (toT i) (toT j) with hij | hji
    · exact le_bp hij
    · exact absurd (hmin (toT j) ⟨j, rfl, lt_of_lt_of_le hpos (le_inf (hΓ'.trans inf_le_left) hgj)⟩)
        (not_not.2 (hti ▸ hji))
  · exact (le_bot_iff_not_bot_lt.1 hpos).trans bot_le
lemma memAEv_of_lt {Γ : 𝔹c} {r s : ℝ} {i iᵣ : I} (hgs : Γ ≤ gen i s)
    (hleast : Γ ≤ leastEv iᵣ r) (hlt : toT i < toT iᵣ) : Γ ≤ memAEv r s := by
  rw [memAEv]
  refine le_iSup_of_le i (le_inf hgs ?_)
  rw [lessEv]
  refine le_iInf fun j => ?_
  rw [bv_imp_iff]; intro Γ' hΓ' hgj
  have h2 := (hΓ'.trans hleast).trans inf_le_right
  rcases le_bp_elim (bv_imp_iff.1 (h2.trans (iInf_le _ j)) le_rfl hgj) with hb | hle
  · exact hb.trans bot_le
  · exact le_bp (lt_of_lt_of_le hlt hle)

theorem no_infinite_independent (X : bSet 𝔹c) :
    (X ⊆ᴮ Rc) ⊓ Sem.infinite X ⊓ Sem.independent Aname X ≤ ⊥ := by
  classical
  by_contra hbot0
  set Γ : 𝔹c := (X ⊆ᴮ Rc) ⊓ Sem.infinite X ⊓ Sem.independent Aname X with hΓdef
  have hbot : ⊥ < Γ := bot_lt_iff_ne_bot.2 (fun h => hbot0 (le_of_eq h))
  have hsub : Γ ≤ X ⊆ᴮ Rc := inf_le_left.trans inf_le_left
  have hind : Γ ≤ Sem.independent Aname X := inf_le_right
  have hinf : Γ ≤ Sem.infinite X := inf_le_left.trans inf_le_right
  rw [Sem.infinite] at hinf
  obtain ⟨f, hf₀⟩ := nonzero_wit' hbot hinf
  set inj0 : 𝔹c := ⨅ n : bSet 𝔹c, n ∈ᴮ omega ⟹ ⨅ m : bSet 𝔹c, m ∈ᴮ omega ⟹ ⨅ u : bSet 𝔹c,
    Sem.app f n u ⟹ (Sem.app f m u ⟹ n =ᴮ m) with hinj0
  set Γ₁ : 𝔹c := (Sem.isFun omega X f ⊓ inj0) ⊓ Γ with hΓ₁def
  have hΓ₁ : ⊥ < Γ₁ := hf₀
  have hΓ₁Γ : Γ₁ ≤ Γ := inf_le_right
  have hfun : Γ₁ ≤ Sem.isFun omega X f := inf_le_left.trans inf_le_left
  have hfinj : Γ₁ ≤ inj0 := inf_le_left.trans inf_le_right
  obtain ⟨Γ', c, hΓ'pos, hΓ'Γ₁, hc⟩ := exists_forall_of_denseOmegaClosed
    Collapse.denseOmegaClosed_D_col hΓ₁ (ι := fun _ => ℝ × I)
    (fun n p => Sem.app f (of_nat n) (rname p.1) ⊓ leastEv p.2 p.1)
    (by
      intro n Γ'' hΓ''pos hΓ''le
      have hval : Γ'' ≤ ⨆ y : bSet 𝔹c, y ∈ᴮ X ⊓ (Sem.app f (of_nat n) y ⊓
          ⨅ y' : bSet 𝔹c, Sem.app f (of_nat n) y' ⟹ y' =ᴮ y) :=
        bv_imp_iff.1 ((hΓ''le.trans hfun).trans (iInf_le _ (of_nat n))) le_rfl of_nat_mem_omega
      obtain ⟨y, hy₀⟩ := nonzero_wit' hΓ''pos hval
      set Δ₁ := (y ∈ᴮ X ⊓ (Sem.app f (of_nat n) y ⊓
          ⨅ y' : bSet 𝔹c, Sem.app f (of_nat n) y' ⟹ y' =ᴮ y)) ⊓ Γ'' with hΔ₁
      have hΔ₁pos : ⊥ < Δ₁ := hy₀
      have hyX : Δ₁ ≤ y ∈ᴮ X := inf_le_left.trans inf_le_left
      have happy : Δ₁ ≤ Sem.app f (of_nat n) y := inf_le_left.trans (inf_le_right.trans inf_le_left)
      have hyRc : Δ₁ ≤ y ∈ᴮ Rc :=
        mem_of_mem_subset ((inf_le_right.trans hΓ''le).trans (hΓ₁Γ.trans hsub)) hyX
      rw [mem_Rc] at hyRc
      obtain ⟨r, hr₀⟩ := nonzero_wit' hΔ₁pos hyRc
      set Δ₂ := (y =ᴮ rname r) ⊓ Δ₁ with hΔ₂
      have hΔ₂pos : ⊥ < Δ₂ := hr₀
      have hyr : Δ₂ ≤ y =ᴮ rname r := inf_le_left
      have happr : Δ₂ ≤ Sem.app f (of_nat n) (rname r) := by
        rw [Sem.app] at happy ⊢
        exact subst_congr_mem_left' (pair_congr bv_refl hyr) (inf_le_right.trans happy)
      have hgw : Δ₂ ≤ ⨆ i : I, gen i r := by rw [gen_wide]; exact le_top
      obtain ⟨i₀, hi₀⟩ := nonzero_wit' hΔ₂pos hgw
      set Δ₃ := gen i₀ r ⊓ Δ₂ with hΔ₃
      have hΔ₃pos : ⊥ < Δ₃ := hi₀
      have hΔ₃g : Δ₃ ≤ gen i₀ r := inf_le_left
      obtain ⟨i, Δ₄, hΔ₄pos, hΔ₄Δ₃, hΔ₄least⟩ := exists_least_of_gen hΔ₃pos hΔ₃g
      have hΔ₄Γ'' : Δ₄ ≤ Γ'' :=
        hΔ₄Δ₃.trans (inf_le_right.trans (inf_le_right.trans inf_le_right))
      have hΔ₄app : Δ₄ ≤ Sem.app f (of_nat n) (rname r) :=
        (hΔ₄Δ₃.trans inf_le_right).trans happr
      exact ⟨(r, i), lt_of_lt_of_le hΔ₄pos (le_inf hΔ₄Γ'' (le_inf hΔ₄app hΔ₄least))⟩)
  set rr : ℕ → ℝ := fun n => (c n).1 with hrr
  set ii : ℕ → I := fun n => (c n).2 with hii
  have hcapp : ∀ n, Γ' ≤ Sem.app f (of_nat n) (rname (rr n)) := fun n => (hc n).trans inf_le_left
  have hcleast : ∀ n, Γ' ≤ leastEv (ii n) (rr n) := fun n => (hc n).trans inf_le_right
  have hcgen : ∀ n, Γ' ≤ gen (ii n) (rr n) := fun n => leastEv_gen (hcleast n)
  have hΓ'Γ : Γ' ≤ Γ := hΓ'Γ₁.trans hΓ₁Γ
  have hmemX : ∀ n, Γ' ≤ (rname (rr n) : bSet 𝔹c) ∈ᴮ X := by
    intro n
    have hval : Γ' ≤ ⨆ y : bSet 𝔹c, y ∈ᴮ X ⊓ (Sem.app f (of_nat n) y ⊓
        ⨅ y' : bSet 𝔹c, Sem.app f (of_nat n) y' ⟹ y' =ᴮ y) :=
      bv_imp_iff.1 ((hΓ'Γ₁.trans hfun).trans (iInf_le _ (of_nat n))) le_rfl of_nat_mem_omega
    refine (le_inf le_rfl hval).trans (bv_cases_right fun y => ?_)
    have huniq : Γ' ⊓ (y ∈ᴮ X ⊓ (Sem.app f (of_nat n) y ⊓
        ⨅ y' : bSet 𝔹c, Sem.app f (of_nat n) y' ⟹ y' =ᴮ y)) ≤ rname (rr n) =ᴮ y := by
      have hiInf : Γ' ⊓ (y ∈ᴮ X ⊓ (Sem.app f (of_nat n) y ⊓
          ⨅ y' : bSet 𝔹c, Sem.app f (of_nat n) y' ⟹ y' =ᴮ y)) ≤
          ⨅ y' : bSet 𝔹c, Sem.app f (of_nat n) y' ⟹ y' =ᴮ y :=
        inf_le_right.trans (inf_le_right.trans inf_le_right)
      have h1 := hiInf.trans (iInf_le _ (rname (rr n)))
      exact bv_imp_iff.1 h1 le_rfl (inf_le_left.trans (hcapp n))
    exact subst_congr_mem_left' (bv_symm huniq) (inf_le_right.trans inf_le_left)
  have hne_real : ∀ n m, n ≠ m → rr n ≠ rr m := by
    intro n m hnm heq
    have h1 : Γ' ≤ (of_nat n : bSet 𝔹c) =ᴮ of_nat m := by
      have h2 := bv_imp_iff.1 ((hΓ'Γ₁.trans hfinj).trans (iInf_le _ (of_nat n))) le_rfl
        of_nat_mem_omega
      have h3 := bv_imp_iff.1 (h2.trans (iInf_le _ (of_nat m))) le_rfl of_nat_mem_omega
      have h4 := h3.trans (iInf_le _ (rname (rr n)))
      have happm : Γ' ≤ Sem.app f (of_nat m) (rname (rr n)) := by rw [heq]; exact hcapp m
      exact bv_imp_iff.1 (bv_imp_iff.1 h4 le_rfl (hcapp n)) le_rfl happm
    rcases bot_or_eq_of_of_nat_eq h1 with hb | he
    · exact absurd (lt_of_lt_of_le hΓ'pos hb) (lt_irrefl _)
    · exact hnm he
  have hne_idx : ∀ n m, n ≠ m → ii n ≠ ii m := by
    intro n m hnm heq
    have : Γ' ≤ ⊥ := (le_inf (hcgen n) (heq ▸ hcgen m)).trans (gen_anti (hne_real n m hnm))
    exact absurd (lt_of_lt_of_le hΓ'pos this) (lt_irrefl _)
  have hdesc : ∀ n m, toT (ii n) < toT (ii m) → |rr m| + 1 < |rr n| := by
    intro n m hlt
    have hnm : n ≠ m := by rintro rfl; exact lt_irrefl _ hlt
    have hmem : Γ' ≤ memAEv (rr m) (rr n) := memAEv_of_lt (hcgen n) (hcleast m) hlt
    have hxne : Γ' ≤ ((rname (rr n) : bSet 𝔹c) =ᴮ rname (rr m))ᶜ := by
      rw [rname_bv_eq_of_ne (hne_real n m hnm), compl_bot]; exact le_top
    have hnotmem : Γ' ≤ ((rname (rr n) : bSet 𝔹c) ∈ᴮ Aset (rr m))ᶜ := by
      rw [Sem.independent] at hind
      have h1 := bv_imp_iff.1 ((hΓ'Γ.trans hind).trans (iInf_le _ (rname (rr n)))) le_rfl (hmemX n)
      have h2 := bv_imp_iff.1 (h1.trans (iInf_le _ (rname (rr m)))) le_rfl (hmemX m)
      have h3 := bv_imp_iff.1 h2 le_rfl hxne
      exact bv_imp_iff.1 (h3.trans (iInf_le _ (Aset (rr m)))) le_rfl (le_app_Aname bv_refl bv_refl)
    have hge : Γ' ⊓ bp (|rr n| ≤ |rr m| + 1) ≤ (rname (rr n) : bSet 𝔹c) ∈ᴮ Aset (rr m) := by
      rw [mem_Aset]
      exact le_iSup_of_le (rr n) (le_inf (le_inf inf_le_right (inf_le_left.trans hmem)) bv_refl)
    have hbotpiece : Γ' ⊓ bp (|rr n| ≤ |rr m| + 1) ≤ ⊥ :=
      (le_inf hge (inf_le_left.trans hnotmem)).trans (by rw [inf_compl_eq_bot])
    by_contra hcon
    rw [not_lt] at hcon
    rw [bp_true hcon, inf_top_eq] at hbotpiece
    exact absurd (lt_of_lt_of_le hΓ'pos hbotpiece) (lt_irrefl _)
  have hwinj : Function.Injective (fun n => toT (ii n)) := by
    intro n m h; by_contra hnm; exact hne_idx n m hnm (toT_injective h)
  exact no_descent (fun n => toT (ii n)) hwinj (fun n => |rr n|) (fun n => abs_nonneg _) hdesc



/-! ### The conclusion -/

/-- The Erdős property fails (has Boolean value `⊥`) for the check reals in `V 𝔹_collapse`. -/
theorem erdosProperty_Rc_eq_bot :
    Sem.erdosProperty (Rc : bSet 𝔹c) plusC ltC zeroC oneC = ⊥ := by
  refine le_antisymm ?_ bot_le
  rw [Sem.erdosProperty]
  have h1 : (⨅ A : bSet 𝔹c, Sem.isFun Rc (bv_powerset Rc) A ⟹
      ((⨅ x : bSet 𝔹c, x ∈ᴮ Rc ⟹ ⨅ Ax : bSet 𝔹c, Sem.app A x Ax ⟹
        (Sem.bounded Rc ltC Ax ⊓ Sem.outerMeasureLtOne Rc plusC ltC zeroC oneC Ax)) ⟹
        ⨆ X : bSet 𝔹c, X ∈ᴮ bv_powerset Rc ⊓ (Sem.infinite X ⊓ Sem.independent A X))) ≤
      Sem.isFun Rc (bv_powerset Rc) Aname ⟹ _ := iInf_le _ Aname
  have h2 := bv_imp_iff.1 h1 le_rfl (le_top.trans isFun_Aname)
  have h3 := bv_imp_iff.1 h2 le_rfl (le_top.trans hyp_Aname)
  refine h3.trans (iSup_le fun X => ?_)
  refine (le_inf (le_inf (inf_le_left.trans (bv_powerset_spec.2 le_rfl))
    (inf_le_right.trans inf_le_left)) (inf_le_right.trans inf_le_right)).trans ?_
  exact no_infinite_independent X

/-- The Boolean value of `Erdos501_f` in `V 𝔹_collapse` is `⊥`. -/
theorem erdos501_eq_bot : (Sem.erdos501 : 𝔹c) = ⊥ := by
  refine le_antisymm ?_ bot_le
  rw [Sem.erdos501]
  have h1 : (⨅ R : bSet 𝔹c, ⨅ plus : bSet 𝔹c, ⨅ times : bSet 𝔹c, ⨅ ltR : bSet 𝔹c,
      ⨅ zero : bSet 𝔹c, ⨅ one : bSet 𝔹c,
        Sem.completeOrderedField R plus times ltR zero one ⟹ Sem.erdosProperty R plus ltR zero one) ≤
      Sem.completeOrderedField Rc plusC timesC ltC zeroC oneC ⟹
        Sem.erdosProperty Rc plusC ltC zeroC oneC :=
    (iInf_le _ Rc).trans ((iInf_le _ plusC).trans ((iInf_le _ timesC).trans ((iInf_le _ ltC).trans
      ((iInf_le _ zeroC).trans (iInf_le _ oneC)))))
  have h2 := bv_imp_iff.1 h1 le_rfl (le_top.trans completeOrderedField_Rc_collapse)
  rw [erdosProperty_Rc_eq_bot] at h2
  exact h2

/-- **The negation of `Erdos501_f` is forced in the collapse model.** -/
theorem neg_erdos501_forced_collapse :
    (⊤ : 𝔹c) ⊩[V 𝔹c] (bd_not Erdos501_f : sentence L_ZFC) := by
  show (⊤ : 𝔹c) ≤ ⟦bd_not Erdos501_f⟧[V 𝔹c]
  have hnot : ⟦bd_not Erdos501_f⟧[V 𝔹c] = (⟦Erdos501_f⟧[V 𝔹c])ᶜ :=
    boolean_realize_bounded_formula_not
  rw [hnot, realize_Erdos501_f, erdos501_eq_bot, compl_bot]

instance V_𝔹c_nonempty : Nonempty (V 𝔹c) := ⟨bSet.empty⟩

/-- **`ZFC` does not prove `Erdos501_f`**: since `CH` holds in the collapse model and Hechler's
family is a counterexample there, `Erdos501_f` fails in a model of `ZFC`. -/
theorem Erdos501_f_unprovable : ¬ (ZFC ⊢ₛ' Erdos501_f) :=
  unprovable_of_model_neg (V 𝔹c) bSet_models_ZFC nontrivial_bot_lt_top neg_erdos501_forced_collapse

/-- **Erdős problem #501 (first question) is independent of `ZFC`** (for the sentence `Erdos501_f`):
neither `Erdos501_f` nor its negation is provable.  The positive direction (`¬ ZFC ⊢ ∼Erdos501_f`,
`neg_Erdos501_f_unprovable`) is the random-real consistency of a positive answer (`Main.lean`); the
negative direction (`¬ ZFC ⊢ Erdos501_f`) is Hechler's `CH` counterexample in the collapse model. -/
theorem independence_of_Erdos501 : independent ZFC Erdos501_f :=
  ⟨Erdos501_f_unprovable, neg_Erdos501_f_unprovable⟩

end Hechler

end Flypitch.Erdos501
