/-
Copyright (c) 2026 The Flypitch Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

The transport of the Erdős property from `Rdot` to an arbitrary internal complete ordered field along
the internal isomorphism `psi` (unit (F8), part 3, `PLAN.md` §6), and the universal sentence.
-/
import ErdosProblems.Erdos501.Flypitch4.Erdos501.InternalIso
import ErdosProblems.Erdos501.Flypitch4.Erdos501.Assembly

set_option relaxedAutoImplicit true

/-!
# Transport of the Erdős property along `psi` (unit (F8), part 3)

Let `F` be an internal complete ordered field on `Γ` and `A : F.R → 𝒫 F.R` a function name all of
whose values have internal outer measure `< 1`.  Its transport `Atr F A = {(psi r, psi[A(r)]) | r ∈ F.R}`
is a function name `Rdot → 𝒫 Rdot` (`Atr_isFun`) whose values have outer measure `< 1` in `Rdot`
(`Atr_values`): the covering sequences `a b s : ω → F.R` of `A(r)` are read through `psi`
(`rd F`), and the eight clauses of `Sem.outerMeasureLtOne` for `Rdot` are established from the ground
readings by the introduction rule `outerMeasureLtOne_of_readings` (the converse of the reading theorem
of `RealReading.lean`).  Theorem 3.2 in `V^{randomAlgebra ι}` (`exists_infinite_independent_of_omlt1`,
`Assembly.lean`) then gives an infinite independent `X' ⊆ Rdot` for `Atr F A`, and its pull-back
`Xpb F X' = {r ∈ F.R | psi r ∈ X'}` is infinite (`infinite_Xpb`) and independent for `A`
(`independent_Xpb`).  Hence

* `erdosProperty_of_COF : 𝔠⁺ ≤ #ι → Γ ≤ F.COF → Γ ≤ Sem.erdosProperty F.R F.plus F.ltR F.zero F.one`,

for **every** internal complete ordered field, and therefore, by `forced_Erdos501_f_iff`,

* `erdos501_forced : 𝔠⁺ ≤ #ι → ⊤ ⊩[V (randomAlgebra ι)] Erdos501_f` — **the universal sentence is
  forced by `𝔠⁺` random reals**, without `sorry`.
-/

open MeasureTheory ProbabilityTheory Set Flypitch bSet Lattice
open scoped ENNReal Flypitch Fol

namespace Flypitch.Erdos501.RandomForcing

variable {ι : Type}

/-- `le_bihimp_iff` in the orientation `a ≤ b ⇔ c ↔ a ⊓ b ≤ c ∧ a ⊓ c ≤ b` (Mathlib's statement is
now generated by `to_dual` and reads `c ⊓ a ≤ b ∧ b ⊓ a ≤ c`). -/
private lemma le_bihimp_iff' {α : Type*} [GeneralizedHeytingAlgebra α] {a b c : α} :
    a ≤ bihimp b c ↔ a ⊓ b ≤ c ∧ a ⊓ c ≤ b := by
  rw [le_bihimp_iff, inf_comm c a, inf_comm b a, and_comm]

private lemma le_bihimp' {α : Type*} [GeneralizedHeytingAlgebra α] {a b c : α}
    (h₁ : a ⊓ b ≤ c) (h₂ : a ⊓ c ≤ b) : a ≤ bihimp b c :=
  le_bihimp_iff'.mpr ⟨h₁, h₂⟩

/-! ### Names for the values of a function name, and successors -/

section appN

/-- A name for `f(n)`, by the maximum principle. -/
noncomputable def appN (f n : bSet (randomAlgebra ι)) : bSet (randomAlgebra ι) :=
  Classical.choose (maximum_principle (fun y => Sem.app f n y) B_ext_pair_mem_right)

lemma appN_spec (f n : bSet (randomAlgebra ι)) :
    (⨆ y : bSet (randomAlgebra ι), Sem.app f n y) = Sem.app f n (appN f n) :=
  Classical.choose_spec (maximum_principle (fun y => Sem.app f n y) B_ext_pair_mem_right)

variable {Γ : randomAlgebra ι} {D C f n : bSet (randomAlgebra ι)}

lemma isFun_elim (hf : Γ ≤ Sem.isFun D C f) (hn : Γ ≤ n ∈ᴮ D) :
    Γ ≤ ⨆ y : bSet (randomAlgebra ι), y ∈ᴮ C ⊓
      (Sem.app f n y ⊓ ⨅ y' : bSet (randomAlgebra ι), Sem.app f n y' ⟹ y' =ᴮ y) := by
  rw [Sem.isFun] at hf
  exact BV.mp (hf.trans (iInf_le _ n)) hn

lemma app_appN (hf : Γ ≤ Sem.isFun D C f) (hn : Γ ≤ n ∈ᴮ D) : Γ ≤ Sem.app f n (appN f n) := by
  rw [← appN_spec]
  refine (isFun_elim hf hn).trans (iSup_le fun y => ?_)
  exact le_iSup_of_le y (inf_le_right.trans inf_le_left)

lemma appN_unique (hf : Γ ≤ Sem.isFun D C f) (hn : Γ ≤ n ∈ᴮ D) {y : bSet (randomAlgebra ι)}
    (hy : Γ ≤ Sem.app f n y) : Γ ≤ y =ᴮ appN f n :=
  isFun_unique hf hn hy (app_appN hf hn)

lemma appN_mem (hf : Γ ≤ Sem.isFun D C f) (hn : Γ ≤ n ∈ᴮ D) : Γ ≤ appN f n ∈ᴮ C := by
  refine BV.iSup_elim (isFun_elim hf hn) fun y Γ' h' hy => ?_
  have h1 : Γ' ≤ appN f n =ᴮ y :=
    BV.mp ((bv_and_right (bv_and_right hy)).trans (iInf_le _ (appN f n))) (h'.trans (app_appN hf hn))
  exact mem_congr (bv_symm h1) bv_refl (bv_and_left hy)

/-- Successors are unique. -/
lemma succ_unique {n m m' : bSet (randomAlgebra ι)} (h : Γ ≤ Sem.succ n m) (h' : Γ ≤ Sem.succ n m') :
    Γ ≤ m =ᴮ m' := by
  refine le_trans ?_ (bSet_axiom_of_extensionality m m')
  refine le_iInf fun z => ?_
  rw [Sem.succ] at h h'
  have h1 := le_bihimp_iff'.mp (h.trans (iInf_le _ z))
  have h2 := le_bihimp_iff'.mp (h'.trans (iInf_le _ z))
  refine le_inf ?_ ?_
  · rw [← deduction]; exact (le_inf inf_le_left h1.1).trans h2.2
  · rw [← deduction]; exact (le_inf inf_le_left h2.1).trans h1.2

/-- `Sem.succ` is congruent in its first argument. -/
lemma succ_congr_left {n n' m : bSet (randomAlgebra ι)} (h : Γ ≤ n =ᴮ n') (hs : Γ ≤ Sem.succ n m) :
    Γ ≤ Sem.succ n' m := by
  rw [Sem.succ] at hs ⊢
  refine le_iInf fun z => ?_
  have h1 := le_bihimp_iff'.mp (hs.trans (iInf_le _ z))
  refine le_bihimp' ?_ ?_
  · refine (le_inf inf_le_left h1.1).trans ?_
    rw [inf_sup_left]
    refine sup_le (le_sup_of_le_left ?_) (le_sup_of_le_right ?_)
    · exact mem_congr bv_refl (inf_le_left.trans h) inf_le_right
    · exact bv_trans inf_le_right (inf_le_left.trans h)
  · refine le_trans ?_ h1.2
    refine le_inf inf_le_left ?_
    rw [inf_sup_left]
    refine sup_le (le_sup_of_le_left ?_) (le_sup_of_le_right ?_)
    · exact mem_congr bv_refl (inf_le_left.trans (bv_symm h)) inf_le_right
    · exact bv_trans inf_le_right (inf_le_left.trans (bv_symm h))

end appN

/-! ### Names of ground sequences of reals, and the introduction rule for `outerMeasureLtOne` -/

section rSeq

/-- The name of the sequence `n ↦ realName (a n)`, as a function `ω → Rdot`. -/
noncomputable def rSeq (a : ℕ → MeasReal ι) : bSet (randomAlgebra ι) :=
  ⟨ℕ, fun n => pair (of_nat n) (realName (a n).1 (a n).2), fun _ => ⊤⟩

variable {Γ : randomAlgebra ι} (a : ℕ → MeasReal ι)

lemma mem_rSeq (z : bSet (randomAlgebra ι)) :
    (z ∈ᴮ rSeq a) = ⨆ n : ℕ, z =ᴮ pair (of_nat n) (realName (a n).1 (a n).2) := by
  rw [mem_unfold]
  show (⨆ n : ℕ, ⊤ ⊓ z =ᴮ pair (of_nat n) (realName (a n).1 (a n).2)) = _
  simp only [top_inf_eq]

lemma app_rSeq (k : ℕ) : Γ ≤ Sem.app (rSeq a) (of_nat k) (realName (a k).1 (a k).2) := by
  rw [Sem.app, mem_rSeq]
  exact le_iSup_of_le k bv_refl

lemma app_rSeq_elim {n u : bSet (randomAlgebra ι)} {b : randomAlgebra ι}
    (h : Γ ≤ Sem.app (rSeq a) n u)
    (H : ∀ (k : ℕ) (Γ' : randomAlgebra ι), Γ' ≤ Γ → Γ' ≤ n =ᴮ of_nat k →
      Γ' ≤ u =ᴮ realName (a k).1 (a k).2 → Γ' ≤ b) : Γ ≤ b := by
  rw [Sem.app, mem_rSeq] at h
  refine BV.iSup_elim h fun k Γ' h' hk => ?_
  have h1 := pair_eq_pair_iff.mp hk
  exact H k Γ' h' h1.1 h1.2

/-- Two indices of a name in `ω` agree, or the context is `⊥`. -/
lemma of_nat_eq_elim {n : bSet (randomAlgebra ι)} {k k' : ℕ} {b : randomAlgebra ι}
    (h1 : Γ ≤ n =ᴮ of_nat k) (h2 : Γ ≤ n =ᴮ of_nat k') (H : k = k' → Γ ≤ b) : Γ ≤ b := by
  by_cases hkk : k = k'
  · exact H hkk
  · have := bv_trans (bv_symm h1) h2
    rw [of_nat_inj' hkk] at this
    exact BV.of_bot this

theorem rSeq_isFun : Γ ≤ Sem.isFun bSet.omega Rdot (rSeq a) := by
  rw [Sem.isFun]
  refine le_iInf fun n => ?_
  rw [bv_imp_iff]; intro Γ₁ _ hn
  rw [mem_omega_eq] at hn
  refine BV.iSup_elim hn fun k Γ₂ h₂ hk => ?_
  refine le_iSup_of_le (realName (a k).1 (a k).2) (le_inf realName_mem_Rdot (le_inf ?_ ?_))
  · exact app_congr_arg (bv_symm hk) (app_rSeq a k)
  · refine le_iInf fun y' => ?_
    rw [bv_imp_iff]; intro Γ₃ h₃ hy'
    refine app_rSeq_elim a hy' fun k' Γ₄ h₄ hk' hy'' => ?_
    refine of_nat_eq_elim ((h₄.trans h₃).trans hk) hk' fun hkk => ?_
    subst hkk
    exact hy''

/-- The names `n ↦ realName (a n)` and `n ↦ realName (a' n)` agree on `Γ ≤ [∀ n, a n = a' n]`. -/
lemma app_rSeq_of_eq {n u : bSet (randomAlgebra ι)} {k : ℕ} (hn : Γ ≤ n =ᴮ of_nat k)
    (hu : Γ ≤ u =ᴮ realName (a k).1 (a k).2) : Γ ≤ Sem.app (rSeq a) n u :=
  app_congr_arg (bv_symm hn) (app_congr_val (bv_symm hu) (app_rSeq a k))

end rSeq

section omlt1_intro

variable {Γ : randomAlgebra ι}

/-- **Introduction rule for `Sem.outerMeasureLtOne Rdot …`** from ground readings: sequences
`a b s : ℕ → MeasReal ι` and a bound `ρ` such that (on `Γ`) `aₙ < bₙ`, every element of `S` lies in
some `(aₙ, bₙ)`, `s₀ = 0`, `s_{n+1} + aₙ = sₙ + bₙ`, `ρ < 1` and `sₙ ≤ ρ`. -/
theorem outerMeasureLtOne_of_readings (a b s : ℕ → MeasReal ι) (ρ : MeasReal ι)
    {S : bSet (randomAlgebra ι)} (hS : Γ ≤ S ⊆ᴮ Rdot)
    (hnd : ∀ n, Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (a n).1 w < (b n).1 w}
      (measurableSet_lt (a n).2 (b n).2))
    (hcov : ∀ g : MeasReal ι, Γ ⊓ realName g.1 g.2 ∈ᴮ S ≤
      MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | ∃ n, (a n).1 w < g.1 w ∧ g.1 w < (b n).1 w}
        (measurableSet_openSet a b g.2))
    (h0 : Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (s 0).1 w = 0}
      (measurableSet_eq_fun (s 0).2 measurable_const))
    (hps : ∀ n, Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι)
      {w | (s (n + 1)).1 w + (a n).1 w = (s n).1 w + (b n).1 w}
      (measurableSet_eq_fun ((s (n + 1)).2.add (a n).2) ((s n).2.add (b n).2)))
    (hρ : Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | ρ.1 w < 1}
      (measurableSet_lt ρ.2 measurable_const))
    (hbd : ∀ n, Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (s n).1 w ≤ ρ.1 w}
      (measurableSet_le (s n).2 ρ.2)) :
    Γ ≤ Sem.outerMeasureLtOne Rdot plusDot ltDot zeroDot oneDot S := by
  rw [Sem.outerMeasureLtOne]
  refine le_iSup_of_le (rSeq a) (le_iSup_of_le (rSeq b) (le_iSup_of_le (rSeq s) ?_))
  refine le_inf (rSeq_isFun a) (le_inf (rSeq_isFun b) (le_inf (rSeq_isFun s)
    (le_inf ?_ (le_inf ?_ (le_inf ?_ (le_inf ?_ ?_))))))
  · -- nondegenerate
    rw [Sem.nondegenerate]
    refine le_iInf fun n => ?_
    rw [bv_imp_iff]; intro Γ₁ _ hn
    rw [mem_omega_eq] at hn
    refine BV.iSup_elim hn fun k Γ₂ h₂ hk => ?_
    refine le_iInf fun u => le_iInf fun v => ?_
    rw [bv_imp_iff]; intro Γ₃ h₃ hu
    rw [bv_imp_iff]; intro Γ₄ h₄ hv
    refine app_rSeq_elim a (h₄.trans hu) fun k₁ Γ₅ h₅ hk₁ hu' => ?_
    refine app_rSeq_elim b (h₅.trans hv) fun k₂ Γ₆ h₆ hk₂ hv' => ?_
    refine of_nat_eq_elim (((h₆.trans h₅).trans (h₄.trans h₃)).trans hk) (h₆.trans hk₁) fun e₁ => ?_
    refine of_nat_eq_elim (((h₆.trans h₅).trans (h₄.trans h₃)).trans hk) hk₂ fun e₂ => ?_
    subst e₁; subst e₂
    exact le_lt_ltDot (h₆.trans hu') hv'
      ((((h₆.trans h₅).trans (h₄.trans h₃)).trans (h₂.trans ‹Γ₁ ≤ Γ›)).trans (hnd k))
  · -- covers
    rw [Sem.covers]
    refine le_iInf fun y => ?_
    rw [bv_imp_iff]; intro Γ₁ h₁ hy
    have hyR : Γ₁ ≤ y ∈ᴮ Rdot := mem_of_mem_subset (h₁.trans hS) hy
    refine mem_Rdot_elim hyR fun g Γ₂ h₂ hyg => ?_
    have h3 : Γ₂ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι)
        {w | ∃ n, (a n).1 w < g.1 w ∧ g.1 w < (b n).1 w} (measurableSet_openSet a b g.2) :=
      (le_inf ((h₂.trans h₁)) (mem_congr hyg bv_refl (h₂.trans hy))).trans (hcov g)
    have e : {w | ∃ n, (a n).1 w < g.1 w ∧ g.1 w < (b n).1 w} =
        ⋃ n, {w | (a n).1 w < g.1 w} ∩ {w | g.1 w < (b n).1 w} := by
      ext w; simp only [mem_setOf_eq, mem_iUnion, mem_inter_iff]
    have h4 : Γ₂ ≤ ⨆ n : ℕ, MeasureAlgebra.mk (RandomAlgebra.μ_random ι)
        ({w | (a n).1 w < g.1 w} ∩ {w | g.1 w < (b n).1 w})
        ((measurableSet_lt (a n).2 g.2).inter (measurableSet_lt g.2 (b n).2)) := by
      rw [← mk_iUnion_eq]
      exact le_mk_of_le (MeasureAlgebra.mk_congr e.symm (ht := measurableSet_openSet a b g.2)) h3
    refine BV.iSup_elim h4 fun n Γ₃ h₃ hn => ?_
    refine le_iSup_of_le (of_nat n) (le_inf of_nat_mem_omega
      (le_iSup_of_le (realName (a n).1 (a n).2) (le_iSup_of_le (realName (b n).1 (b n).2)
        (le_inf (app_rSeq a n) (le_inf (app_rSeq b n) (le_inf ?_ ?_))))))
    · have h5 : Γ₃ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (a n).1 w < g.1 w}
          (measurableSet_lt (a n).2 g.2) := hn.trans (mk_mono fun w hw => hw.1)
      exact le_lt_ltDot bv_refl (h₃.trans hyg) h5
    · have h5 : Γ₃ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | g.1 w < (b n).1 w}
          (measurableSet_lt g.2 (b n).2) := hn.trans (mk_mono fun w hw => hw.2)
      exact le_lt_ltDot (h₃.trans hyg) bv_refl h5
  · -- `s 0 = 0`
    rw [← of_nat_zero_eq]
    refine app_congr_val ?_ (app_rSeq s 0)
    rw [zeroDot, bv_eq_realName]
    exact h0
  · -- partial sums
    rw [Sem.partialSums]
    refine le_iInf fun n => ?_
    rw [bv_imp_iff]; intro Γ₁ _ hn
    rw [mem_omega_eq] at hn
    refine BV.iSup_elim hn fun k Γ₂ h₂ hk => ?_
    refine le_iInf fun m => ?_
    rw [bv_imp_iff]; intro Γ₃ h₃ hm
    have hm' : Γ₃ ≤ m =ᴮ of_nat (k + 1) :=
      succ_unique (succ_congr_left (h₃.trans hk) hm) (succ_of_nat k)
    refine le_iInf fun u => le_iInf fun v => le_iInf fun w => le_iInf fun w' =>
      le_iInf fun t => le_iInf fun t' => ?_
    rw [bv_imp_iff]; intro Γ₄ h₄ hu
    rw [bv_imp_iff]; intro Γ₅ h₅ hv
    rw [bv_imp_iff]; intro Γ₆ h₆ hw
    rw [bv_imp_iff]; intro Γ₇ h₇ hw'
    rw [bv_imp_iff]; intro Γ₈ h₈ ht
    rw [bv_imp_iff]; intro Γ₉ h₉ ht'
    have hΓ₈ : Γ₉ ≤ Γ₈ := h₉
    have hΓ₇ : Γ₉ ≤ Γ₇ := h₉.trans h₈
    have hΓ₆ : Γ₉ ≤ Γ₆ := hΓ₇.trans h₇
    have hΓ₅ : Γ₉ ≤ Γ₅ := hΓ₆.trans h₆
    have hΓ₄ : Γ₉ ≤ Γ₄ := hΓ₅.trans h₅
    have hΓ₃ : Γ₉ ≤ Γ₃ := hΓ₄.trans h₄
    have hk₉ : Γ₉ ≤ n =ᴮ of_nat k := (hΓ₃.trans h₃).trans hk
    refine app_rSeq_elim a (hΓ₄.trans hu) fun k₁ Γ₁₀ h₁₀ hk₁ hu' => ?_
    refine of_nat_eq_elim (h₁₀.trans hk₉) hk₁ fun e₁ => ?_
    subst e₁
    refine app_rSeq_elim b ((h₁₀.trans hΓ₅).trans hv) fun k₂ Γ₁₁ h₁₁ hk₂ hv' => ?_
    refine of_nat_eq_elim ((h₁₁.trans h₁₀).trans hk₉) hk₂ fun e₂ => ?_
    subst e₂
    refine app_rSeq_elim s (((h₁₁.trans h₁₀).trans hΓ₆).trans hw) fun k₃ Γ₁₂ h₁₂ hk₃ hw₁ => ?_
    refine of_nat_eq_elim (((h₁₂.trans h₁₁).trans h₁₀).trans hk₉) hk₃ fun e₃ => ?_
    subst e₃
    refine app_rSeq_elim s ((((h₁₂.trans h₁₁).trans h₁₀).trans hΓ₇).trans hw')
      fun k₄ Γ₁₃ h₁₃ hk₄ hw₂ => ?_
    have hΓ₉ : Γ₁₃ ≤ Γ₉ := ((h₁₃.trans h₁₂).trans h₁₁).trans h₁₀
    have hm₁₃ : Γ₁₃ ≤ m =ᴮ of_nat (k + 1) := (hΓ₉.trans hΓ₃).trans hm'
    refine of_nat_eq_elim hm₁₃ hk₄ fun e₄ => ?_
    subst e₄
    -- `t = s (k+1) + a k`, `t' = s k + b k`
    have ht₁ : Γ₁₃ ≤ Sem.app2 plusDot (realName (s (k + 1)).1 (s (k + 1)).2)
        (realName (a k).1 (a k).2) t :=
      Fld.app2_congr hw₂ (((h₁₃.trans h₁₂).trans h₁₁).trans hu') bv_refl ((hΓ₉.trans hΓ₈).trans ht)
    have ht₂ : Γ₁₃ ≤ Sem.app2 plusDot (realName (s k).1 (s k).2) (realName (b k).1 (b k).2) t' :=
      Fld.app2_congr (h₁₃.trans hw₁) ((h₁₃.trans h₁₂).trans hv') bv_refl (hΓ₉.trans ht')
    unfold plusDot at ht₁ ht₂
    rw [app2_opDot_realName] at ht₁ ht₂
    have e : Γ₁₃ ≤ realName (fun w => (s (k + 1)).1 w + (a k).1 w)
        (measurable_add.comp ((s (k+1)).2.prodMk (a k).2)) =ᴮ
        realName (fun w => (s k).1 w + (b k).1 w) (measurable_add.comp ((s k).2.prodMk (b k).2)) := by
      rw [bv_eq_realName]
      exact (hΓ₉.trans (hΓ₃.trans (h₃.trans (h₂.trans ‹Γ₁ ≤ Γ›)))).trans (hps k)
    exact bv_trans ht₁ (bv_trans e (bv_symm ht₂))
  · -- bounded by `ρ`
    rw [Sem.sumsBounded]
    refine le_iSup_of_le (realName ρ.1 ρ.2) (le_inf realName_mem_Rdot (le_inf ?_ ?_))
    · rw [oneDot]
      exact le_lt_ltDot bv_refl bv_refl hρ
    · refine le_iInf fun n => ?_
      rw [bv_imp_iff]; intro Γ₁ h₁ hn
      rw [mem_omega_eq] at hn
      refine BV.iSup_elim hn fun k Γ₂ h₂ hk => ?_
      refine le_iInf fun w => ?_
      rw [bv_imp_iff]; intro Γ₃ h₃ hw
      refine app_rSeq_elim s hw fun k' Γ₄ h₄ hk' hw' => ?_
      refine of_nat_eq_elim ((h₄.trans h₃).trans hk) hk' fun e => ?_
      subst e
      refine le_ltDot_congr_left hw' ?_
      rw [le_ltDot_realName]
      exact ((h₄.trans h₃).trans (h₂.trans h₁)).trans (hbd k)

end omlt1_intro

/-! ### Congruence of `outerMeasureLtOne` in the set -/

section omlt1_congr

variable {Γ : randomAlgebra ι}

lemma covers_congr {ltR S S' a b : bSet (randomAlgebra ι)} (h : Γ ≤ S =ᴮ S')
    (hc : Γ ≤ Sem.covers ltR S a b) : Γ ≤ Sem.covers ltR S' a b := by
  rw [Sem.covers] at hc ⊢
  refine le_iInf fun y => ?_
  rw [bv_imp_iff]; intro Γ' h' hy
  exact BV.mp ((h'.trans hc).trans (iInf_le _ y)) (mem_congr bv_refl (bv_symm (h'.trans h)) hy)

lemma outerMeasureLtOne_congr {R plus ltR zero one S S' : bSet (randomAlgebra ι)} (hSS : Γ ≤ S =ᴮ S')
    (hom : Γ ≤ Sem.outerMeasureLtOne R plus ltR zero one S) :
    Γ ≤ Sem.outerMeasureLtOne R plus ltR zero one S' := by
  rw [Sem.outerMeasureLtOne] at hom ⊢
  refine BV.iSup_elim hom fun a Γ₁ h₁ h => ?_
  refine BV.iSup_elim h fun b Γ₂ h₂ h => ?_
  refine BV.iSup_elim h fun s Γ₃ h₃ h => ?_
  refine le_iSup_of_le a (le_iSup_of_le b (le_iSup_of_le s ?_))
  refine le_inf (bv_and_left h) (le_inf (bv_and_left (bv_and_right h))
    (le_inf (bv_and_left (bv_and_right (bv_and_right h)))
    (le_inf (bv_and_left (bv_and_right (bv_and_right (bv_and_right h))))
    (le_inf ?_ (bv_and_right (bv_and_right (bv_and_right (bv_and_right (bv_and_right h)))))))))
  exact covers_congr ((h₃.trans (h₂.trans h₁)).trans hSS)
    (bv_and_left (bv_and_right (bv_and_right (bv_and_right (bv_and_right h)))))

end omlt1_congr

/-! ### The transported family `Atr F A` -/

section transfer

variable {F : Fld (randomAlgebra ι)} {Γ : randomAlgebra ι} {A : bSet (randomAlgebra ι)}

/-- The value `A(r)`. -/
noncomputable def Aval (A r : bSet (randomAlgebra ι)) : bSet (randomAlgebra ι) := appN A r

lemma app_Aval (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A) {r : bSet (randomAlgebra ι)}
    (hr : Γ ≤ r ∈ᴮ F.R) : Γ ≤ Sem.app A r (Aval A r) :=
  app_appN hA1 hr

lemma Aval_subset (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A) {r : bSet (randomAlgebra ι)}
    (hr : Γ ≤ r ∈ᴮ F.R) : Γ ≤ Aval A r ⊆ᴮ F.R :=
  bv_powerset_spec.mpr (appN_mem hA1 hr)

lemma Aval_unique (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A) {r Ar : bSet (randomAlgebra ι)}
    (hr : Γ ≤ r ∈ᴮ F.R) (h : Γ ≤ Sem.app A r Ar) : Γ ≤ Ar =ᴮ Aval A r :=
  appN_unique hA1 hr h

lemma Aval_congr (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A) {r r' : bSet (randomAlgebra ι)}
    (hr : Γ ≤ r ∈ᴮ F.R) (h : Γ ≤ r =ᴮ r') : Γ ≤ Aval A r =ᴮ Aval A r' :=
  Aval_unique hA1 (mem_congr h bv_refl hr) (app_congr_arg h (app_Aval hA1 hr))

/-- The image `psi[A(r)]` of the value `A(r)`, a subset of `Rdot`. -/
noncomputable def imgSet (F : Fld (randomAlgebra ι)) (A r : bSet (randomAlgebra ι)) :
    bSet (randomAlgebra ι) :=
  ⟨MeasReal ι, fun g => realName g.1 g.2, fun g => ⨆ i : F.R.type,
    F.R.bval i ⊓ (F.R.func i ∈ᴮ Aval A r) ⊓ (rdName F (F.R.func i) =ᴮ realName g.1 g.2)⟩

@[simp] lemma imgSet_func (r : bSet (randomAlgebra ι)) (g : (imgSet F A r).type) :
    (imgSet F A r).func g = realName g.1 g.2 := rfl
@[simp] lemma imgSet_bval (r : bSet (randomAlgebra ι)) (g : (imgSet F A r).type) :
    (imgSet F A r).bval g = ⨆ i : F.R.type,
      F.R.bval i ⊓ (F.R.func i ∈ᴮ Aval A r) ⊓ (rdName F (F.R.func i) =ᴮ realName g.1 g.2) := rfl

lemma imgSet_subset_Rdot (r : bSet (randomAlgebra ι)) : Γ ≤ imgSet F A r ⊆ᴮ Rdot := by
  rw [subset_unfold]
  refine le_iInf fun g => ?_
  rw [← deduction, imgSet_func]
  exact realName_mem_Rdot

lemma mem_imgSet_realName {r : bSet (randomAlgebra ι)} {f : RandomAlgebra.Ω ι → ℝ}
    (hf : Measurable f) : (realName f hf ∈ᴮ imgSet F A r) = ⨆ i : F.R.type,
      F.R.bval i ⊓ (F.R.func i ∈ᴮ Aval A r) ⊓ (rdName F (F.R.func i) =ᴮ realName f hf) := by
  rw [mem_unfold]
  simp only [imgSet_bval, imgSet_func]
  apply le_antisymm
  · refine iSup_le fun g' => ?_
    rw [iSup_inf_eq]
    refine iSup_le fun i => le_iSup_of_le i ?_
    refine le_inf (inf_le_left.trans inf_le_left) ?_
    refine (le_inf (inf_le_left.trans inf_le_right) inf_le_right).trans ?_
    rw [bv_eq_symm (x := realName f hf)]
    exact bv_eq_trans
  · exact le_iSup_of_le ⟨f, hf⟩ (by simp only [bv_eq_refl, inf_top_eq, le_refl])

lemma le_mem_imgSet {r : bSet (randomAlgebra ι)} (i : F.R.type) (hi : Γ ≤ F.R.bval i)
    (hmem : Γ ≤ F.R.func i ∈ᴮ Aval A r) : Γ ≤ rdName F (F.R.func i) ∈ᴮ imgSet F A r := by
  rw [rdName, mem_imgSet_realName]
  exact le_iSup_of_le i (le_inf (le_inf hi hmem) bv_refl)

lemma mem_imgSet_elim {r : bSet (randomAlgebra ι)} {f : RandomAlgebra.Ω ι → ℝ} {hf : Measurable f}
    {b : randomAlgebra ι} (h : Γ ≤ realName f hf ∈ᴮ imgSet F A r)
    (H : ∀ (i : F.R.type) (Γ' : randomAlgebra ι), Γ' ≤ Γ → Γ' ≤ F.R.bval i →
      Γ' ≤ F.R.func i ∈ᴮ Aval A r → Γ' ≤ rdName F (F.R.func i) =ᴮ realName f hf → Γ' ≤ b) :
    Γ ≤ b := by
  rw [mem_imgSet_realName] at h
  refine BV.iSup_elim h fun i Γ' h' hi => ?_
  exact H i Γ' h' (bv_and_left (bv_and_left hi)) (bv_and_right (bv_and_left hi)) (bv_and_right hi)

lemma imgSet_congr (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A) {r r' : bSet (randomAlgebra ι)}
    (hr : Γ ≤ r ∈ᴮ F.R) (h : Γ ≤ r =ᴮ r') : Γ ≤ imgSet F A r =ᴮ imgSet F A r' := by
  refine eq_of_forall_realName_mem_eq' (imgSet_subset_Rdot r) (imgSet_subset_Rdot r')
    (fun g => ?_) (fun g => ?_)
  · refine mem_imgSet_elim inf_le_right fun i Γ' h' hi hmem heq => ?_
    exact le_mem_imgSet i hi (mem_congr bv_refl (Aval_congr (h'.trans (inf_le_left.trans hA1))
      (h'.trans (inf_le_left.trans hr)) (h'.trans (inf_le_left.trans h))) hmem)
      |> fun h1 => mem_congr heq bv_refl h1
  · refine mem_imgSet_elim inf_le_right fun i Γ' h' hi hmem heq => ?_
    have hr' : Γ' ≤ r' ∈ᴮ F.R :=
      mem_congr (h'.trans (inf_le_left.trans h)) bv_refl (h'.trans (inf_le_left.trans hr))
    exact le_mem_imgSet i hi (mem_congr bv_refl (Aval_congr (h'.trans (inf_le_left.trans hA1)) hr'
      (bv_symm (h'.trans (inf_le_left.trans h)))) hmem)
      |> fun h1 => mem_congr heq bv_refl h1

/-- **The transported family** `Atr F A = {(psi r, psi[A(r)]) | r ∈ F.R}`. -/
noncomputable def Atr (F : Fld (randomAlgebra ι)) (A : bSet (randomAlgebra ι)) :
    bSet (randomAlgebra ι) :=
  ⟨F.R.type, fun i => pair (rdName F (F.R.func i)) (imgSet F A (F.R.func i)), F.R.bval⟩

lemma mem_Atr (z : bSet (randomAlgebra ι)) : (z ∈ᴮ Atr F A) = ⨆ i : F.R.type,
    F.R.bval i ⊓ z =ᴮ pair (rdName F (F.R.func i)) (imgSet F A (F.R.func i)) := by
  rw [mem_unfold]; rfl

lemma app_Atr_intro (i : F.R.type) :
    F.R.bval i ≤ Sem.app (Atr F A) (rdName F (F.R.func i)) (imgSet F A (F.R.func i)) := by
  rw [Sem.app, mem_Atr]
  exact le_iSup_of_le i (by simp only [bv_eq_refl, inf_top_eq, le_refl])

lemma app_Atr_elim {x y : bSet (randomAlgebra ι)} {b : randomAlgebra ι}
    (h : Γ ≤ Sem.app (Atr F A) x y)
    (H : ∀ (i : F.R.type) (Γ' : randomAlgebra ι), Γ' ≤ Γ → Γ' ≤ F.R.bval i →
      Γ' ≤ x =ᴮ rdName F (F.R.func i) → Γ' ≤ y =ᴮ imgSet F A (F.R.func i) → Γ' ≤ b) : Γ ≤ b := by
  rw [Sem.app, mem_Atr] at h
  refine BV.iSup_elim h fun i Γ' h' hi => ?_
  have h1 := pair_eq_pair_iff.mp (bv_and_right hi)
  exact H i Γ' h' (bv_and_left hi) h1.1 h1.2

lemma func_mem_R (i : F.R.type) : F.R.bval i ≤ F.R.func i ∈ᴮ F.R := mem_mk' F.R i

variable (hF : Γ ≤ F.COF)
include hF

/-- **`Atr F A` is a function `Rdot → 𝒫 Rdot`.** -/
theorem Atr_isFun (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A) :
    Γ ≤ Sem.isFun Rdot (bv_powerset Rdot) (Atr F A) := by
  rw [Sem.isFun]
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ h₁ hx
  refine mem_Rdot_elim hx fun g Γ₂ h₂ hxg => ?_
  have H₂ := Fld.cof_mono hF (h₂.trans h₁)
  refine BV.iSup_elim (psi_surj_app H₂ g) fun u Γ₃ h₃ hu => ?_
  refine mem_R_elim (bv_and_left hu) fun i Γ₄ h₄ hi hui => ?_
  have H₄ := Fld.cof_mono H₂ (h₄.trans h₃)
  have hgi : Γ₄ ≤ rdName F (F.R.func i) =ᴮ x := by
    have e1 : Γ₄ ≤ realName g.1 g.2 =ᴮ rdName F u :=
      eq_of_app_psi H₄ (h₄.trans (bv_and_left hu)) (h₄.trans (bv_and_right hu))
    have e2 : Γ₄ ≤ rdName F u =ᴮ rdName F (F.R.func i) :=
      rdName_congr H₄ (h₄.trans (bv_and_left hu)) hui
    exact bv_trans (bv_symm e2) (bv_trans (bv_symm e1) (bv_symm ((h₄.trans h₃).trans hxg)))
  refine le_iSup_of_le (imgSet F A (F.R.func i))
    (le_inf (bv_powerset_spec.mp (imgSet_subset_Rdot _)) (le_inf ?_ ?_))
  · exact app_congr_arg hgi (hi.trans (app_Atr_intro i))
  · refine le_iInf fun y' => ?_
    rw [bv_imp_iff]; intro Γ₅ h₅ hy'
    refine app_Atr_elim hy' fun j Γ₆ h₆ hj hxj hy'j => ?_
    have H₆ := Fld.cof_mono H₄ (h₆.trans h₅)
    have hiR : Γ₆ ≤ F.R.func i ∈ᴮ F.R := (h₆.trans h₅).trans (hi.trans (func_mem_R i))
    have hjR : Γ₆ ≤ F.R.func j ∈ᴮ F.R := hj.trans (func_mem_R j)
    have e1 : Γ₆ ≤ rdName F (F.R.func i) =ᴮ rdName F (F.R.func j) :=
      bv_trans ((h₆.trans h₅).trans hgi) hxj
    have e2 : Γ₆ ≤ F.R.func i =ᴮ F.R.func j := by
      rw [rdName, rdName, bv_eq_realName] at e1
      exact (le_inf le_rfl e1).trans (eq_of_rd_eq H₆ hiR hjR)
    exact bv_trans hy'j (imgSet_congr ((h₆.trans h₅).trans ((h₄.trans h₃).trans (h₂.trans (h₁.trans hA1)))) hjR (bv_symm e2))

/-! #### The readings of the covering sequences -/

omit hF in
/-- The reading of `f(k)`, for an internal sequence `f : ω → F.R`. -/
noncomputable def seqRd (F : Fld (randomAlgebra ι)) (f : bSet (randomAlgebra ι)) (k : ℕ) :
    MeasReal ι :=
  ⟨rd F (appN f (of_nat k)), measurable_rd F _⟩

omit hF in
lemma appN_mem_R {f : bSet (randomAlgebra ι)} (hf : Γ ≤ Sem.isFun bSet.omega F.R f) (k : ℕ) :
    Γ ≤ appN f (of_nat k) ∈ᴮ F.R :=
  appN_mem hf of_nat_mem_omega

lemma readings_nondeg {a b : bSet (randomAlgebra ι)} (ha : Γ ≤ Sem.isFun bSet.omega F.R a)
    (hb : Γ ≤ Sem.isFun bSet.omega F.R b) (hnd : Γ ≤ Sem.nondegenerate F.ltR a b) (k : ℕ) :
    Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (seqRd F a k).1 w < (seqRd F b k).1 w}
      (measurableSet_lt (seqRd F a k).2 (seqRd F b k).2) := by
  rw [Sem.nondegenerate] at hnd
  have h1 := BV.mp (hnd.trans (iInf_le _ (of_nat k))) of_nat_mem_omega
  have h2 : Γ ≤ F.lt (appN a (of_nat k)) (appN b (of_nat k)) :=
    BV.mp (BV.mp ((h1.trans (iInf_le _ (appN a (of_nat k)))).trans (iInf_le _ (appN b (of_nat k))))
      (app_appN ha of_nat_mem_omega)) (app_appN hb of_nat_mem_omega)
  exact (le_inf le_rfl h2).trans (rd_lt_of_lt hF (appN_mem_R ha k) (appN_mem_R hb k))

lemma readings_zero {s : bSet (randomAlgebra ι)} (hs : Γ ≤ Sem.isFun bSet.omega F.R s)
    (h0 : Γ ≤ Sem.app s bSet.empty F.zero) :
    Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (seqRd F s 0).1 w = 0}
      (measurableSet_eq_fun (seqRd F s 0).2 measurable_const) := by
  rw [← of_nat_zero_eq] at h0
  have e : Γ ≤ F.zero =ᴮ appN s (of_nat 0) := appN_unique hs of_nat_mem_omega h0
  have h1 := rd_congr hF (Fld.cof_zero_mem hF) e
  have h2 := rd_zero hF
  have := le_inf h1 h2
  rw [MeasureAlgebra.mk_inf] at this
  refine mk_le_of_forall this fun w hw => ?_
  simp only [mem_inter_iff, mem_setOf_eq] at hw ⊢
  show rd F (appN s (of_nat 0)) w = 0
  rw [← hw.1, hw.2]

lemma readings_ps {a b s : bSet (randomAlgebra ι)} (ha : Γ ≤ Sem.isFun bSet.omega F.R a)
    (hb : Γ ≤ Sem.isFun bSet.omega F.R b) (hs : Γ ≤ Sem.isFun bSet.omega F.R s)
    (hps : Γ ≤ Sem.partialSums F.plus a b s) (k : ℕ) :
    Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι)
      {w | (seqRd F s (k + 1)).1 w + (seqRd F a k).1 w = (seqRd F s k).1 w + (seqRd F b k).1 w}
      (measurableSet_eq_fun ((seqRd F s (k + 1)).2.add (seqRd F a k).2)
        ((seqRd F s k).2.add (seqRd F b k).2)) := by
  rw [Sem.partialSums] at hps
  have h1 := BV.mp (hps.trans (iInf_le _ (of_nat k))) of_nat_mem_omega
  have h2 := BV.mp (h1.trans (iInf_le _ (of_nat (k + 1)))) (succ_of_nat k)
  have haN := appN_mem_R ha k
  have hbN := appN_mem_R hb k
  have hsN := appN_mem_R hs k
  have hsN' := appN_mem_R hs (k + 1)
  have h3 := h2.trans (iInf_le _ (appN a (of_nat k))) |>.trans (iInf_le _ (appN b (of_nat k)))
    |>.trans (iInf_le _ (appN s (of_nat k))) |>.trans (iInf_le _ (appN s (of_nat (k + 1))))
    |>.trans (iInf_le _ (F.add (appN s (of_nat (k + 1))) (appN a (of_nat k))))
    |>.trans (iInf_le _ (F.add (appN s (of_nat k)) (appN b (of_nat k))))
  have e : Γ ≤ F.add (appN s (of_nat (k + 1))) (appN a (of_nat k)) =ᴮ
      F.add (appN s (of_nat k)) (appN b (of_nat k)) :=
    BV.mp (BV.mp (BV.mp (BV.mp (BV.mp (BV.mp h3 (app_appN ha of_nat_mem_omega))
      (app_appN hb of_nat_mem_omega)) (app_appN hs of_nat_mem_omega))
      (app_appN hs of_nat_mem_omega)) (Fld.add_app2 hF hsN' haN)) (Fld.add_app2 hF hsN hbN)
  have r1 := rd_add hF hsN' haN (Fld.add_mem hF hsN' haN) (Fld.add_app2 hF hsN' haN)
  have r2 := rd_add hF hsN hbN (Fld.add_mem hF hsN hbN) (Fld.add_app2 hF hsN hbN)
  have r3 := rd_congr hF (Fld.add_mem hF hsN' haN) e
  have := le_inf r1 (le_inf r2 r3)
  simp only [MeasureAlgebra.mk_inf] at this
  refine mk_le_of_forall this fun w hw => ?_
  simp only [mem_inter_iff, mem_setOf_eq] at hw ⊢
  show rd F (appN s (of_nat (k + 1))) w + rd F (appN a (of_nat k)) w =
    rd F (appN s (of_nat k)) w + rd F (appN b (of_nat k)) w
  rw [← hw.1, ← hw.2.1, hw.2.2]

lemma readings_lt_one {ρ' : bSet (randomAlgebra ι)} (hρ' : Γ ≤ ρ' ∈ᴮ F.R)
    (h : Γ ≤ F.lt ρ' F.one) :
    Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | rd F ρ' w < 1}
      (measurableSet_lt (measurable_rd F ρ') measurable_const) := by
  have h1 := (le_inf le_rfl h).trans (rd_lt_of_lt hF hρ' (Fld.cof_one_mem hF))
  have h2 := rd_one hF
  have := le_inf h1 h2
  rw [MeasureAlgebra.mk_inf] at this
  refine mk_le_of_forall this fun w hw => ?_
  simp only [mem_inter_iff, mem_setOf_eq] at hw ⊢
  rw [← hw.2]; exact hw.1

lemma readings_le {s ρ' : bSet (randomAlgebra ι)} (hs : Γ ≤ Sem.isFun bSet.omega F.R s)
    (hρ' : Γ ≤ ρ' ∈ᴮ F.R)
    (hle : Γ ≤ ⨅ n : bSet (randomAlgebra ι), n ∈ᴮ bSet.omega ⟹ ⨅ w : bSet (randomAlgebra ι),
      Sem.app s n w ⟹ Sem.le F.ltR w ρ') (k : ℕ) :
    Γ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | (seqRd F s k).1 w ≤ rd F ρ' w}
      (measurableSet_le (seqRd F s k).2 (measurable_rd F ρ')) := by
  have h1 : Γ ≤ F.le (appN s (of_nat k)) ρ' :=
    BV.mp ((BV.mp (hle.trans (iInf_le _ (of_nat k))) of_nat_mem_omega).trans
      (iInf_le _ (appN s (of_nat k)))) (app_appN hs of_nat_mem_omega)
  refine Fld.le_elim h1 (fun Γ' h' hlt => ?_) fun Γ' h' heq => ?_
  · have := (le_inf h' hlt).trans (rd_lt_of_lt hF (appN_mem_R hs k) hρ')
    exact mk_le_of_forall this fun w hw => (show rd F (appN s (of_nat k)) w < rd F ρ' w from hw).le
  · have := rd_congr (Fld.cof_mono hF h') (h'.trans (appN_mem_R hs k)) heq
    exact mk_le_of_forall this fun w hw => (show rd F (appN s (of_nat k)) w = rd F ρ' w from hw).le

lemma readings_cov {r a b : bSet (randomAlgebra ι)}
    (ha : Γ ≤ Sem.isFun bSet.omega F.R a) (hb : Γ ≤ Sem.isFun bSet.omega F.R b)
    (hcov : Γ ≤ Sem.covers F.ltR (Aval A r) a b) (g : MeasReal ι) :
    Γ ⊓ realName g.1 g.2 ∈ᴮ imgSet F A r ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι)
      {w | ∃ n, (seqRd F a n).1 w < g.1 w ∧ g.1 w < (seqRd F b n).1 w}
      (measurableSet_openSet (seqRd F a) (seqRd F b) g.2) := by
  refine mem_imgSet_elim inf_le_right fun j Γ₁ h₁ hj hmem heq => ?_
  have hΓ₁ : Γ₁ ≤ Γ := h₁.trans inf_le_left
  rw [Sem.covers] at hcov
  have h2 := BV.mp ((hΓ₁.trans hcov).trans (iInf_le _ (F.R.func j))) hmem
  refine BV.iSup_elim h2 fun n Γ₂ h₂ hn => ?_
  have hnω := bv_and_left hn
  rw [mem_omega_eq] at hnω
  refine BV.iSup_elim hnω fun k Γ₃ h₃ hk => ?_
  refine BV.iSup_elim (h₃.trans (bv_and_right hn)) fun u Γ₄ h₄ hu => ?_
  refine BV.iSup_elim hu fun v Γ₅ h₅ huv => ?_
  have hΓ₅ : Γ₅ ≤ Γ := (((h₅.trans h₄).trans h₃).trans h₂).trans hΓ₁
  have H₅ := Fld.cof_mono hF hΓ₅
  have hk₅ : Γ₅ ≤ n =ᴮ of_nat k := (h₅.trans h₄).trans hk
  have hjR : Γ₅ ≤ F.R.func j ∈ᴮ F.R := (((h₅.trans h₄).trans h₃).trans h₂).trans (hj.trans (func_mem_R j))
  have hu' : Γ₅ ≤ u =ᴮ appN a (of_nat k) :=
    appN_unique (hΓ₅.trans ha) of_nat_mem_omega (app_congr_arg hk₅ (bv_and_left huv))
  have hv' : Γ₅ ≤ v =ᴮ appN b (of_nat k) :=
    appN_unique (hΓ₅.trans hb) of_nat_mem_omega (app_congr_arg hk₅ (bv_and_left (bv_and_right huv)))
  have hlt1 : Γ₅ ≤ F.lt (appN a (of_nat k)) (F.R.func j) :=
    Fld.lt_congr hu' bv_refl (bv_and_left (bv_and_right (bv_and_right huv)))
  have hlt2 : Γ₅ ≤ F.lt (F.R.func j) (appN b (of_nat k)) :=
    Fld.lt_congr bv_refl hv' (bv_and_right (bv_and_right (bv_and_right huv)))
  have m1 := (le_inf le_rfl hlt1).trans (rd_lt_of_lt H₅ (appN_mem_R (hΓ₅.trans ha) k) hjR)
  have m2 := (le_inf le_rfl hlt2).trans (rd_lt_of_lt H₅ hjR (appN_mem_R (hΓ₅.trans hb) k))
  have m3 : Γ₅ ≤ MeasureAlgebra.mk (RandomAlgebra.μ_random ι) {w | rd F (F.R.func j) w = g.1 w}
      (measurableSet_eq_fun (measurable_rd F _) g.2) := by
    have := (((h₅.trans h₄).trans h₃).trans h₂).trans heq
    rw [rdName, bv_eq_realName] at this
    exact this
  have := le_inf m1 (le_inf m2 m3)
  simp only [MeasureAlgebra.mk_inf] at this
  refine mk_le_of_forall this fun w hw => ?_
  simp only [mem_inter_iff, mem_setOf_eq] at hw ⊢
  refine ⟨k, ?_, ?_⟩
  · show rd F (appN a (of_nat k)) w < g.1 w
    rw [← hw.2.2]; exact hw.1
  · show g.1 w < rd F (appN b (of_nat k)) w
    rw [← hw.2.2]; exact hw.2.1

/-- **The values of `Atr F A` have outer measure `< 1`.** -/
theorem omlt1_imgSet {r : bSet (randomAlgebra ι)}
    (hom : Γ ≤ Sem.outerMeasureLtOne F.R F.plus F.ltR F.zero F.one (Aval A r)) :
    Γ ≤ Sem.outerMeasureLtOne Rdot plusDot ltDot zeroDot oneDot (imgSet F A r) := by
  rw [Sem.outerMeasureLtOne] at hom
  refine BV.iSup_elim hom fun a Γ₁ h₁ h => ?_
  refine BV.iSup_elim h fun b Γ₂ h₂ h => ?_
  refine BV.iSup_elim h fun s Γ₃ h₃ h => ?_
  have hΓ : Γ₃ ≤ Γ := h₃.trans (h₂.trans h₁)
  have ha := bv_and_left h
  have hb := bv_and_left (bv_and_right h)
  have hs := bv_and_left (bv_and_right (bv_and_right h))
  have hnd := bv_and_left (bv_and_right (bv_and_right (bv_and_right h)))
  have hcov := bv_and_left (bv_and_right (bv_and_right (bv_and_right (bv_and_right h))))
  have h0 := bv_and_left (bv_and_right (bv_and_right (bv_and_right (bv_and_right (bv_and_right h)))))
  have hps := bv_and_left (bv_and_right (bv_and_right (bv_and_right (bv_and_right (bv_and_right
    (bv_and_right h))))))
  have hsb := bv_and_right (bv_and_right (bv_and_right (bv_and_right (bv_and_right (bv_and_right
    (bv_and_right h))))))
  rw [Sem.sumsBounded] at hsb
  refine BV.iSup_elim hsb fun ρ' Γ₄ h₄ hρ' => ?_
  have hΓ₄ : Γ₄ ≤ Γ := h₄.trans hΓ
  have H₄ := Fld.cof_mono hF hΓ₄
  have hρ'R := bv_and_left hρ'
  have hρ'lt := bv_and_left (bv_and_right hρ')
  have hρ'le := bv_and_right (bv_and_right hρ')
  refine outerMeasureLtOne_of_readings (seqRd F a) (seqRd F b) (seqRd F s)
    ⟨rd F ρ', measurable_rd F ρ'⟩ (imgSet_subset_Rdot r) ?_ ?_ ?_ ?_ ?_ ?_
  · exact fun n => readings_nondeg H₄ (h₄.trans ha) (h₄.trans hb) (h₄.trans hnd) n
  · exact fun g => readings_cov H₄ (h₄.trans ha) (h₄.trans hb) (h₄.trans hcov) g
  · exact readings_zero H₄ (h₄.trans hs) (h₄.trans h0)
  · exact fun n => readings_ps H₄ (h₄.trans ha) (h₄.trans hb) (h₄.trans hs) (h₄.trans hps) n
  · exact readings_lt_one H₄ hρ'R hρ'lt
  · exact fun n => readings_le H₄ (h₄.trans hs) hρ'R hρ'le n

theorem Atr_values (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A)
    (hA2 : Γ ≤ ⨅ x : bSet (randomAlgebra ι), x ∈ᴮ F.R ⟹ ⨅ Ax : bSet (randomAlgebra ι),
      Sem.app A x Ax ⟹ Sem.outerMeasureLtOne F.R F.plus F.ltR F.zero F.one Ax) :
    Γ ≤ ⨅ x : bSet (randomAlgebra ι), x ∈ᴮ Rdot ⟹ ⨅ Ax' : bSet (randomAlgebra ι),
      Sem.app (Atr F A) x Ax' ⟹ Sem.outerMeasureLtOne Rdot plusDot ltDot zeroDot oneDot Ax' := by
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ h₁ _
  refine le_iInf fun Ax' => ?_
  rw [bv_imp_iff]; intro Γ₂ h₂ hAx'
  refine app_Atr_elim hAx' fun i Γ₃ h₃ hi hxi hAi => ?_
  have hΓ : Γ₃ ≤ Γ := (h₃.trans h₂).trans h₁
  have H₃ := Fld.cof_mono hF hΓ
  have hiR : Γ₃ ≤ F.R.func i ∈ᴮ F.R := hi.trans (func_mem_R i)
  have hom : Γ₃ ≤ Sem.outerMeasureLtOne F.R F.plus F.ltR F.zero F.one (Aval A (F.R.func i)) :=
    BV.mp ((BV.mp ((hΓ.trans hA2).trans (iInf_le _ (F.R.func i))) hiR).trans
      (iInf_le _ (Aval A (F.R.func i)))) (app_Aval (hΓ.trans hA1) hiR)
  exact outerMeasureLtOne_congr (bv_symm hAi) (omlt1_imgSet H₃ hom)

end transfer

/-! ### The pull-back of the independent set -/

section pullback

variable {F : Fld (randomAlgebra ι)} {Γ : randomAlgebra ι} {A X' : bSet (randomAlgebra ι)}

/-- The pull-back `{r ∈ F.R | psi r ∈ X'}`. -/
noncomputable def Xpb (F : Fld (randomAlgebra ι)) (X' : bSet (randomAlgebra ι)) :
    bSet (randomAlgebra ι) :=
  ⟨F.R.type, F.R.func, fun i => F.R.bval i ⊓ (rdName F (F.R.func i) ∈ᴮ X')⟩

lemma mem_Xpb (z : bSet (randomAlgebra ι)) : (z ∈ᴮ Xpb F X') =
    ⨆ i : F.R.type, (F.R.bval i ⊓ rdName F (F.R.func i) ∈ᴮ X') ⊓ z =ᴮ F.R.func i := by
  rw [mem_unfold]; rfl

lemma le_mem_Xpb (i : F.R.type) (hi : Γ ≤ F.R.bval i) (hX : Γ ≤ rdName F (F.R.func i) ∈ᴮ X') :
    Γ ≤ F.R.func i ∈ᴮ Xpb F X' := by
  rw [mem_Xpb]
  exact le_iSup_of_le i (le_inf (le_inf hi hX) bv_refl)

lemma mem_Xpb_elim {z : bSet (randomAlgebra ι)} {b : randomAlgebra ι} (h : Γ ≤ z ∈ᴮ Xpb F X')
    (H : ∀ (i : F.R.type) (Γ' : randomAlgebra ι), Γ' ≤ Γ → Γ' ≤ F.R.bval i →
      Γ' ≤ rdName F (F.R.func i) ∈ᴮ X' → Γ' ≤ z =ᴮ F.R.func i → Γ' ≤ b) : Γ ≤ b := by
  rw [mem_Xpb] at h
  refine BV.iSup_elim h fun i Γ' h' hi => ?_
  exact H i Γ' h' (bv_and_left (bv_and_left hi)) (bv_and_right (bv_and_left hi)) (bv_and_right hi)

lemma Xpb_subset_R : Γ ≤ Xpb F X' ⊆ᴮ F.R := by
  rw [subset_unfold]
  refine le_iInf fun i => ?_
  rw [← deduction]
  exact (inf_le_right.trans inf_le_left).trans (func_mem_R i)

/-- The pull-back of an injection `ω → X'` along `psi`. -/
noncomputable def fpb (F : Fld (randomAlgebra ι)) (f' : bSet (randomAlgebra ι)) :
    bSet (randomAlgebra ι) :=
  ⟨ℕ × F.R.type, fun p => pair (of_nat p.1) (F.R.func p.2),
    fun p => F.R.bval p.2 ⊓ Sem.app f' (of_nat p.1) (rdName F (F.R.func p.2))⟩

lemma mem_fpb {f' : bSet (randomAlgebra ι)} (z : bSet (randomAlgebra ι)) : (z ∈ᴮ fpb F f') =
    ⨆ p : ℕ × F.R.type, (F.R.bval p.2 ⊓ Sem.app f' (of_nat p.1) (rdName F (F.R.func p.2))) ⊓
      z =ᴮ pair (of_nat p.1) (F.R.func p.2) := by
  rw [mem_unfold]; rfl

lemma app_fpb_intro {f' : bSet (randomAlgebra ι)} (k : ℕ) (i : F.R.type) (hi : Γ ≤ F.R.bval i)
    (h : Γ ≤ Sem.app f' (of_nat k) (rdName F (F.R.func i))) :
    Γ ≤ Sem.app (fpb F f') (of_nat k) (F.R.func i) := by
  rw [Sem.app, mem_fpb]
  exact le_iSup_of_le (k, i) (le_inf (le_inf hi h) bv_refl)

lemma app_fpb_elim {f' n u : bSet (randomAlgebra ι)} {b : randomAlgebra ι}
    (h : Γ ≤ Sem.app (fpb F f') n u)
    (H : ∀ (k : ℕ) (i : F.R.type) (Γ' : randomAlgebra ι), Γ' ≤ Γ → Γ' ≤ F.R.bval i →
      Γ' ≤ Sem.app f' (of_nat k) (rdName F (F.R.func i)) → Γ' ≤ n =ᴮ of_nat k →
      Γ' ≤ u =ᴮ F.R.func i → Γ' ≤ b) : Γ ≤ b := by
  rw [Sem.app, mem_fpb] at h
  refine BV.iSup_elim h fun p Γ' h' hp => ?_
  have h1 := pair_eq_pair_iff.mp (bv_and_right hp)
  exact H p.1 p.2 Γ' h' (bv_and_left (bv_and_left hp)) (bv_and_right (bv_and_left hp)) h1.1 h1.2

variable (hF : Γ ≤ F.COF)
include hF

/-- **The pull-back of an infinite set is infinite.** -/
theorem infinite_Xpb (hX' : Γ ≤ X' ⊆ᴮ Rdot) (hinf : Γ ≤ Sem.infinite X') :
    Γ ≤ Sem.infinite (Xpb F X') := by
  rw [Sem.infinite] at hinf ⊢
  refine BV.iSup_elim hinf fun f' Γ₁ h₁ hf' => ?_
  have hfun := bv_and_left hf'
  have hinj := bv_and_right hf'
  refine le_iSup_of_le (fpb F f') (le_inf ?_ ?_)
  · rw [Sem.isFun]
    refine le_iInf fun n => ?_
    rw [bv_imp_iff]; intro Γ₂ h₂ hn
    rw [mem_omega_eq] at hn
    refine BV.iSup_elim hn fun k Γ₃ h₃ hk => ?_
    have hy' := isFun_elim ((h₃.trans h₂).trans hfun) (of_nat_mem_omega (n := k))
    refine BV.iSup_elim hy' fun y' Γ₄ h₄ hy => ?_
    have hy'X := bv_and_left hy
    have happ := bv_and_left (bv_and_right hy)
    have huniq := bv_and_right (bv_and_right hy)
    have hΓ₄ : Γ₄ ≤ Γ := (((h₄.trans h₃).trans h₂).trans h₁)
    have hy'R : Γ₄ ≤ y' ∈ᴮ Rdot := mem_of_mem_subset (hΓ₄.trans hX') hy'X
    refine mem_Rdot_elim hy'R fun g Γ₅ h₅ hyg => ?_
    have H₅ := Fld.cof_mono hF (h₅.trans hΓ₄)
    refine BV.iSup_elim (psi_surj_app H₅ g) fun u Γ₆ h₆ hu => ?_
    refine mem_R_elim (bv_and_left hu) fun i Γ₇ h₇ hi hui => ?_
    have H₇ := Fld.cof_mono H₅ (h₇.trans h₆)
    have huR : Γ₇ ≤ u ∈ᴮ F.R := h₇.trans (bv_and_left hu)
    have hiR : Γ₇ ≤ F.R.func i ∈ᴮ F.R := hi.trans (func_mem_R i)
    have e1 : Γ₇ ≤ rdName F (F.R.func i) =ᴮ y' :=
      bv_trans (bv_symm (rdName_congr H₇ huR hui))
        (bv_trans (bv_symm (eq_of_app_psi H₇ huR (h₇.trans (bv_and_right hu))))
          (bv_symm ((h₇.trans h₆).trans hyg)))
    refine le_iSup_of_le (F.R.func i) (le_inf ?_ (le_inf ?_ ?_))
    · exact le_mem_Xpb i hi (mem_congr (bv_symm e1) bv_refl (((h₇.trans h₆).trans h₅).trans hy'X))
    · exact app_congr_arg (bv_symm ((((h₇.trans h₆).trans h₅).trans h₄).trans hk))
        (app_fpb_intro k i hi (app_congr_val (bv_symm e1) (((h₇.trans h₆).trans h₅).trans happ)))
    · refine le_iInf fun y'' => ?_
      rw [bv_imp_iff]; intro Γ₈ h₈ hy''
      refine app_fpb_elim hy'' fun k' j Γ₉ h₉ hj happ' hnk' huj => ?_
      have hΓ₇ : Γ₉ ≤ Γ₇ := h₉.trans h₈
      refine of_nat_eq_elim ((hΓ₇.trans (((h₇.trans h₆).trans h₅).trans h₄)).trans hk) hnk' fun e => ?_
      subst e
      have H₉ := Fld.cof_mono H₇ hΓ₇
      have hjR : Γ₉ ≤ F.R.func j ∈ᴮ F.R := hj.trans (func_mem_R j)
      have e2 : Γ₉ ≤ rdName F (F.R.func j) =ᴮ y' :=
        BV.mp (((hΓ₇.trans ((h₇.trans h₆).trans h₅)).trans huniq).trans
          (iInf_le _ (rdName F (F.R.func j)))) happ'
      have e3 : Γ₉ ≤ rdName F (F.R.func j) =ᴮ rdName F (F.R.func i) :=
        bv_trans e2 (bv_symm (hΓ₇.trans e1))
      have e4 : Γ₉ ≤ F.R.func j =ᴮ F.R.func i := by
        rw [rdName, rdName, bv_eq_realName] at e3
        exact (le_inf le_rfl e3).trans (eq_of_rd_eq H₉ hjR (hΓ₇.trans hiR))
      exact bv_trans huj e4
  · refine le_iInf fun n => ?_
    rw [bv_imp_iff]; intro Γ₂ h₂ hn
    refine le_iInf fun m => ?_
    rw [bv_imp_iff]; intro Γ₃ h₃ hm
    refine le_iInf fun u => ?_
    rw [bv_imp_iff]; intro Γ₄ h₄ hnu
    rw [bv_imp_iff]; intro Γ₅ h₅ hmu
    refine app_fpb_elim (h₅.trans hnu) fun k i Γ₆ h₆ hi happ hnk hui => ?_
    refine app_fpb_elim (h₆.trans hmu) fun k' j Γ₇ h₇ hj happ' hmk' huj => ?_
    have hΓ₇ : Γ₇ ≤ Γ := (((((h₇.trans h₆).trans h₅).trans h₄).trans h₃).trans h₂).trans h₁
    have H₇ := Fld.cof_mono hF hΓ₇
    have hiR : Γ₇ ≤ F.R.func i ∈ᴮ F.R := (h₇.trans hi).trans (func_mem_R i)
    have e : Γ₇ ≤ F.R.func i =ᴮ F.R.func j := bv_trans (bv_symm (h₇.trans hui)) huj
    have e' := rdName_congr H₇ hiR e
    have happ'' : Γ₇ ≤ Sem.app f' (of_nat k') (rdName F (F.R.func i)) :=
      app_congr_val (bv_symm e') happ'
    have hinj₇ := ((((((h₇.trans h₆).trans h₅).trans h₄).trans h₃).trans h₂)).trans hinj
    have h1 := BV.mp (BV.mp (((BV.mp ((BV.mp (hinj₇.trans (iInf_le _ (of_nat k))) of_nat_mem_omega).trans
      (iInf_le _ (of_nat k'))) of_nat_mem_omega).trans (iInf_le _ (rdName F (F.R.func i)))))
      (h₇.trans happ)) happ''
    exact bv_trans (h₇.trans hnk) (bv_trans h1 (bv_symm hmk'))

/-- **The pull-back of an independent set for `Atr F A` is independent for `A`.** -/
theorem independent_Xpb (hA1 : Γ ≤ Sem.isFun F.R (bv_powerset F.R) A)
    (hind : Γ ≤ Sem.independent (Atr F A) X') : Γ ≤ Sem.independent A (Xpb F X') := by
  rw [Sem.independent] at hind ⊢
  refine le_iInf fun x => ?_
  rw [bv_imp_iff]; intro Γ₁ h₁ hx
  refine le_iInf fun y => ?_
  rw [bv_imp_iff]; intro Γ₂ h₂ hy
  rw [bv_imp_iff]; intro Γ₃ h₃ hxy
  refine le_iInf fun Ay => ?_
  rw [bv_imp_iff]; intro Γ₄ h₄ hAy
  refine mem_Xpb_elim ((h₄.trans (h₃.trans h₂)).trans hx) fun i Γ₅ h₅ hi hiX hxi => ?_
  refine mem_Xpb_elim ((h₅.trans (h₄.trans h₃)).trans hy) fun j Γ₆ h₆ hj hjX hyj => ?_
  have hΓ₆ : Γ₆ ≤ Γ := (((h₆.trans h₅).trans (h₄.trans h₃)).trans h₂).trans h₁
  refine BV.compl_of_inf_le_bot ?_
  have hΓ₇ : Γ₆ ⊓ x ∈ᴮ Ay ≤ Γ := inf_le_left.trans hΓ₆
  have H₇ := Fld.cof_mono hF hΓ₇
  have hiR : Γ₆ ⊓ x ∈ᴮ Ay ≤ F.R.func i ∈ᴮ F.R := (inf_le_left.trans (h₆.trans hi)).trans (func_mem_R i)
  have hjR : Γ₆ ⊓ x ∈ᴮ Ay ≤ F.R.func j ∈ᴮ F.R := (inf_le_left.trans hj).trans (func_mem_R j)
  have hAy' : Γ₆ ⊓ x ∈ᴮ Ay ≤ Ay =ᴮ Aval A (F.R.func j) :=
    Aval_unique (hΓ₇.trans hA1) hjR
      (app_congr_arg (inf_le_left.trans hyj) (inf_le_left.trans ((h₆.trans h₅).trans hAy)))
  have hmem : Γ₆ ⊓ x ∈ᴮ Ay ≤ F.R.func i ∈ᴮ Aval A (F.R.func j) :=
    mem_congr (inf_le_left.trans (h₆.trans hxi)) hAy' inf_le_right
  have h1 : Γ₆ ⊓ x ∈ᴮ Ay ≤ rdName F (F.R.func i) ∈ᴮ imgSet F A (F.R.func j) :=
    le_mem_imgSet i (inf_le_left.trans (h₆.trans hi)) hmem
  have hne : Γ₆ ⊓ x ∈ᴮ Ay ≤ (rdName F (F.R.func i) =ᴮ rdName F (F.R.func j))ᶜ := by
    refine BV.compl_of_inf_le_bot ?_
    have e1 : Γ₆ ⊓ x ∈ᴮ Ay ⊓ (rdName F (F.R.func i) =ᴮ rdName F (F.R.func j)) ≤
        F.R.func i =ᴮ F.R.func j := by
      rw [rdName, rdName, bv_eq_realName]
      exact eq_of_rd_eq H₇ hiR hjR
    have e2 : Γ₆ ⊓ x ∈ᴮ Ay ⊓ (rdName F (F.R.func i) =ᴮ rdName F (F.R.func j)) ≤ x =ᴮ y :=
      bv_trans (inf_le_left.trans (inf_le_left.trans (h₆.trans hxi)))
        (bv_trans e1 (bv_symm (inf_le_left.trans (inf_le_left.trans hyj))))
    exact BV.bot_of_compl e2
      (inf_le_left.trans (inf_le_left.trans ((h₆.trans (h₅.trans h₄)).trans hxy)))
  have hAtr : Γ₆ ⊓ x ∈ᴮ Ay ≤ Sem.app (Atr F A) (rdName F (F.R.func j)) (imgSet F A (F.R.func j)) :=
    (inf_le_left.trans hj).trans (app_Atr_intro j)
  have hiX' : Γ₆ ⊓ x ∈ᴮ Ay ≤ rdName F (F.R.func i) ∈ᴮ X' := inf_le_left.trans (h₆.trans hiX)
  have hjX' : Γ₆ ⊓ x ∈ᴮ Ay ≤ rdName F (F.R.func j) ∈ᴮ X' := inf_le_left.trans hjX
  have h2a := BV.mp ((BV.mp ((hΓ₇.trans hind).trans (iInf_le _ (rdName F (F.R.func i)))) hiX').trans
    (iInf_le _ (rdName F (F.R.func j)))) hjX'
  have h2 := BV.mp h2a hne
  exact BV.bot_of_compl h1 (BV.mp (h2.trans (iInf_le _ (imgSet F A (F.R.func j)))) hAtr)

end pullback

/-! ### The Erdős property of every internal complete ordered field, and the universal sentence -/

section main

open Cardinal in
/-- **Every internal complete ordered field of `V (randomAlgebra ι)`, `𝔠⁺ ≤ #ι`, has the Erdős
property.** -/
theorem erdosProperty_of_COF (hι : Order.succ 𝔠 ≤ #ι) {F : Fld (randomAlgebra ι)}
    {Γ : randomAlgebra ι} (hF : Γ ≤ F.COF) :
    Γ ≤ Sem.erdosProperty F.R F.plus F.ltR F.zero F.one := by
  rw [Sem.erdosProperty]
  refine le_iInf fun A => ?_
  rw [bv_imp_iff]; intro Γ₁ h₁ hA1
  rw [bv_imp_iff]; intro Γ₂ h₂ hA2'
  have hΓ₂ : Γ₂ ≤ Γ := h₂.trans h₁
  have H₂ := Fld.cof_mono hF hΓ₂
  have hA1' : Γ₂ ≤ Sem.isFun F.R (bv_powerset F.R) A := h₂.trans hA1
  have hA2 : Γ₂ ≤ ⨅ x : bSet (randomAlgebra ι), x ∈ᴮ F.R ⟹ ⨅ Ax : bSet (randomAlgebra ι),
      Sem.app A x Ax ⟹ Sem.outerMeasureLtOne F.R F.plus F.ltR F.zero F.one Ax := by
    refine le_iInf fun x => ?_
    rw [bv_imp_iff]; intro Γ' h' hx
    refine le_iInf fun Ax => ?_
    rw [bv_imp_iff]; intro Γ'' h'' hAx
    have h := BV.mp ((h''.trans (h'.trans hA2')).trans (iInf_le _ x)) (h''.trans hx)
    exact bv_and_right (BV.mp (h.trans (iInf_le _ Ax)) hAx)
  have hX := exists_infinite_independent_of_omlt1 hι (Atr_isFun H₂ hA1') (Atr_values H₂ hA1' hA2)
  refine BV.iSup_elim hX fun X' Γ₃ h₃ hX' => ?_
  have H₃ := Fld.cof_mono H₂ h₃
  refine le_iSup_of_le (Xpb F X') (le_inf (bv_powerset_spec.mp Xpb_subset_R) (le_inf ?_ ?_))
  · exact infinite_Xpb H₃ (bv_powerset_spec.mpr (bv_and_left hX')) (bv_and_left (bv_and_right hX'))
  · exact independent_Xpb H₃ (h₃.trans hA1') (bv_and_right (bv_and_right hX'))

open Cardinal in
/-- **The universal sentence `Erdos501_f` is forced by `𝔠⁺` random reals** (no `sorry`). -/
theorem erdos501_forced (hι : Order.succ 𝔠 ≤ #ι) :
    ⊤ ⊩[V (randomAlgebra ι)] Erdos501_f := by
  rw [forced_Erdos501_f_iff]
  intro R plus times ltR zero one
  exact erdosProperty_of_COF hι (F := ⟨R, plus, times, ltR, zero, one⟩) inf_le_right

end main

end Flypitch.Erdos501.RandomForcing
