/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/
import ErdosProblems.Erdos171.Correlation
import ErdosProblems.Erdos171.FaceDensity
import ErdosProblems.Erdos171.IncrementArithmetic
import ErdosProblems.Erdos171.Insensitive
import ErdosProblems.Erdos171.Tiling

/-!
# The structured correlation alternative

This file formalizes Dodos--Kanellopoulos--Tyros Lemma 10 and Corollary 11.
The numerical parameters `eta` and `gamma` are frozen at an initial density
floor `delta0`, while `rho` is the density at the current stage of the
iteration.
-/

open scoped BigOperators

namespace Erdos171

attribute [local instance] Classical.dec

/-! ## Endpoint cylinders -/

/-- The old-alphabet part of a set in the enlarged cube. -/
noncomputable def oldPart {k m : ℕ} (A : Finset (Word (k + 1) m)) :
    Finset (Word k m) :=
  Finset.univ.filter fun x ↦ liftWord x ∈ A

@[simp] theorem mem_oldPart {k m : ℕ} (A : Finset (Word (k + 1) m))
    (x : Word k m) : x ∈ oldPart A ↔ liftWord x ∈ A := by
  simp [oldPart]

/-- The `(i,last)`-insensitive cylinder generated by the old part of `A`. -/
noncomputable def endpointCell {k m : ℕ} (i : Fin k)
    (A : Finset (Word (k + 1) m)) : Finset (Word (k + 1) m) :=
  setFinset (endpointCylinder i (oldPart A : Set (Word k m)))

@[simp] theorem mem_endpointCell {k m : ℕ} (i : Fin k)
    (A : Finset (Word (k + 1) m)) (x : Word (k + 1) m) :
    x ∈ endpointCell i A ↔ liftWord (endpoint i x) ∈ A := by
  simp [endpointCell]

theorem endpointCell_isLastInsensitive {k m : ℕ} (i : Fin k)
    (A : Finset (Word (k + 1) m)) :
    IsLastInsensitive i (endpointCell i A : Set (Word (k + 1) m)) := by
  intro x y hxy
  simpa [endpointCell] using
    (endpointCylinder_isLastInsensitive i (oldPart A : Set (Word k m)) x y hxy)

/-- The structured endpoint set: all old-letter endpoints must lie in `A`. -/
noncomputable def endpointCore {k m : ℕ} (A : Finset (Word (k + 1) m)) :
    Finset (Word (k + 1) m) :=
  familyInter fun i : Fin k ↦ endpointCell i A

@[simp] theorem mem_endpointCore {k m : ℕ} (A : Finset (Word (k + 1) m))
    (x : Word (k + 1) m) :
    x ∈ endpointCore A ↔ ∀ i : Fin k, liftWord (endpoint i x) ∈ A := by
  simp [endpointCore]

/-- Wildcard words associated to restricted internal lines contained in `A`. -/
noncomputable def cubeRestrictedLines {k m : ℕ}
    (A : Finset (Word (k + 1) m)) :
    Finset (Combinatorics.Line (Fin k) (Fin m)) :=
  Finset.univ.filter fun l ↦ ∀ a : Fin k, liftWord (l a) ∈ A

@[simp] theorem mem_cubeRestrictedLines {k m : ℕ}
    (A : Finset (Word (k + 1) m))
    (l : Combinatorics.Line (Fin k) (Fin m)) :
    l ∈ cubeRestrictedLines A ↔ ∀ a : Fin k, liftWord (l a) ∈ A := by
  simp [cubeRestrictedLines]

/-- Fraction of internal old-alphabet lines contained in `A`. -/
noncomputable def cubeRestrictedLineFraction {k m : ℕ}
    (A : Finset (Word (k + 1) m)) : ℝ :=
  density (cubeRestrictedLines A)

noncomputable def restrictedEndpointSet {k m : ℕ}
    (A : Finset (Word (k + 1) m)) : Finset (Word (k + 1) m) :=
  (cubeRestrictedLines A).image templateEndpoint

@[simp] theorem mem_restrictedEndpointSet {k m : ℕ}
    (A : Finset (Word (k + 1) m)) (x : Word (k + 1) m) :
    x ∈ restrictedEndpointSet A ↔
      ∃ l : Combinatorics.Line (Fin k) (Fin m),
        (∀ a : Fin k, liftWord (l a) ∈ A) ∧ templateEndpoint l = x := by
  simp [restrictedEndpointSet]

theorem restrictedEndpointSet_subset_endpointCore {k m : ℕ}
    (A : Finset (Word (k + 1) m)) :
    restrictedEndpointSet A ⊆ endpointCore A := by
  intro x hx
  rw [mem_restrictedEndpointSet] at hx
  obtain ⟨l, hl, rfl⟩ := hx
  rw [mem_endpointCore]
  simpa only [endpoint_templateEndpoint] using hl

theorem card_restrictedEndpointSet {k m : ℕ}
    (A : Finset (Word (k + 1) m)) :
    (restrictedEndpointSet A).card =
      (cubeRestrictedLines A).card := by
  simp [restrictedEndpointSet, Finset.card_image_of_injective,
    templateEndpoint_injective]

/-- Endpoint templates occupy the same fraction of the non-old face as the
corresponding restricted lines occupy among all internal lines. -/
theorem density_restrictedEndpointSet_eq {k m : ℕ}
    (A : Finset (Word (k + 1) m)) (hR : (cubeRestrictedLines A).Nonempty) :
    density (restrictedEndpointSet A) =
      cubeRestrictedLineFraction A *
        (1 - density (liftFinset (Finset.univ : Finset (Word k m)))) := by
  let : Nonempty (Combinatorics.Line (Fin k) (Fin m)) := ⟨hR.choose⟩
  have hq : ((Fintype.card (Combinatorics.Line (Fin k) (Fin m)) : ℕ) : ℝ) ≠ 0 := by
    exact_mod_cast Fintype.card_ne_zero
  have hN : (((k + 1) ^ m : ℕ) : ℝ) ≠ 0 := by positivity
  have hle : k ^ m ≤ (k + 1) ^ m := by
    simpa [Nat.succ_eq_add_one] using Nat.pow_le_pow_left (Nat.le_succ k) m
  have hqeq :
      ((Fintype.card (Combinatorics.Line (Fin k) (Fin m)) : ℕ) : ℝ) =
        (((k + 1) ^ m : ℕ) : ℝ) - ((k ^ m : ℕ) : ℝ) := by
    rw [Combinatorics.Line.card_fin, Nat.cast_sub hle]
  rw [density_eq_card_div_card, card_restrictedEndpointSet,
    cubeRestrictedLineFraction, density_eq_card_div_card,
    density_eq_card_div_card]
  simp only [card_word, card_liftFinset, Finset.card_univ]
  field_simp [hq, hN]
  rw [hqeq]

/-- Many restricted lines and a sparse old face give a genuinely dense
endpoint core. -/
theorem endpointCore_density_lower_bound {k m : ℕ}
    (A : Finset (Word (k + 1) m)) {theta eta : ℝ}
    (htheta : 0 < theta) (heta : eta < 1 / 2)
    (hface : density (liftFinset (Finset.univ : Finset (Word k m))) < eta)
    (hlines : theta / 2 < cubeRestrictedLineFraction A) :
    theta / 4 < density (endpointCore A) := by
  have hRpos : 0 < density (cubeRestrictedLines A) := by
    exact (lt_trans (half_pos htheta) hlines)
  have hR : (cubeRestrictedLines A).Nonempty :=
    (density_pos (cubeRestrictedLines A)).1 hRpos
  have hendpoint : (theta / 2) * (1 - eta) <
      density (restrictedEndpointSet A) := by
    rw [density_restrictedEndpointSet_eq A hR]
    have hone : 0 < 1 - density
        (liftFinset (Finset.univ : Finset (Word k m))) := by
      have hnonneg := density_nonneg
        (liftFinset (Finset.univ : Finset (Word k m)))
      nlinarith
    exact mul_lt_mul hlines (by linarith) (by linarith) hRpos.le
  have hquarter := IncrementArithmetic.theta_div_four_lt htheta heta
  exact hquarter.trans (hendpoint.trans_le
    (density_mono (restrictedEndpointSet_subset_endpointCore A)))

/-! ## The line-free restriction -/

theorem templateEndpoint_endpointLine {k m : ℕ} (x : Word (k + 1) m)
    (hx : ∃ r, x r = Fin.last k) :
    templateEndpoint (endpointLine x hx) = x := by
  funext r
  by_cases hr : x r = Fin.last k
  · simp [endpointLine, templateEndpoint, hr]
  · simp [endpointLine, templateEndpoint, hr]

/-- If `A` is line-free, an element of `A` in all endpoint cylinders must
belong to the old-alphabet face. -/
theorem inter_endpointCore_subset_oldFace {k m : ℕ}
    (A : Finset (Word (k + 1) m))
    (hA : ¬ ContainsLine (A : Set (Word (k + 1) m))) :
    A ∩ endpointCore A ⊆ liftFinset (Finset.univ : Finset (Word k m)) := by
  intro x hx
  have hxA := (Finset.mem_inter.1 hx).1
  have hxC := (Finset.mem_inter.1 hx).2
  by_contra hxold
  have hxlast : ∃ r, x r = Fin.last k := by
    have hxnr : ¬IsRestrictedWord x := by
      intro hxr
      obtain ⟨y, hy⟩ := (Set.ext_iff.1 range_restrictWord x).2 hxr
      subst x
      apply hxold
      change liftWord y ∈ liftFinset (Finset.univ : Finset (Word k m))
      simp
    simpa only [IsRestrictedWord, not_forall, not_ne_iff] using hxnr
  apply hA
  rw [containsLine_coe_finset_iff]
  refine ⟨templateExtension (endpointLine x hxlast), ?_⟩
  intro a
  refine Fin.lastCases ?_ (fun i ↦ ?_) a
  · simpa [templateEndpoint_endpointLine x hxlast] using hxA
  · rw [templateExtension_castSucc]
    change liftWord (endpointLine x hxlast i) ∈ A
    rw [endpointLine_apply]
    exact (mem_endpointCore A x).1 hxC i

/-! ## First-failed-cell partition -/

/-- Words for which `i` is the first endpoint condition that fails. -/
noncomputable def firstFailedPiece {k m : ℕ} (A : Finset (Word (k + 1) m))
    (i : Fin k) : Finset (Word (k + 1) m) :=
  Finset.univ.filter fun x ↦
    (∀ j : Fin k, j < i → x ∈ endpointCell j A) ∧ x ∉ endpointCell i A

@[simp] theorem mem_firstFailedPiece {k m : ℕ}
    (A : Finset (Word (k + 1) m)) (i : Fin k) (x : Word (k + 1) m) :
    x ∈ firstFailedPiece A i ↔
      (∀ j : Fin k, j < i → x ∈ endpointCell j A) ∧ x ∉ endpointCell i A := by
  simp [firstFailedPiece]

theorem firstFailedPiece_pairwiseDisjoint {k m : ℕ}
    (A : Finset (Word (k + 1) m)) :
    ((Finset.univ : Finset (Fin k)) : Set (Fin k)).PairwiseDisjoint
      (firstFailedPiece A) := by
  intro i _ j _ hij
  change Disjoint (firstFailedPiece A i) (firstFailedPiece A j)
  rw [Finset.disjoint_left]
  intro x hxi hxj
  have hi := (mem_firstFailedPiece A i x).1 hxi
  have hj := (mem_firstFailedPiece A j x).1 hxj
  rcases lt_trichotomy i j with hij' | hij' | hij'
  · exact hi.2 (hj.1 i hij')
  · exact hij hij'
  · exact hj.2 (hi.1 j hij')

/-- The first-failed pieces partition the complement of the endpoint core. -/
theorem biUnion_firstFailedPiece {k m : ℕ} (_hk : 0 < k)
    (A : Finset (Word (k + 1) m)) :
    Finset.univ.biUnion (firstFailedPiece A) = Finset.univ \ endpointCore A := by
  ext x
  constructor
  · intro hx
    obtain ⟨i, _, hxi⟩ := Finset.mem_biUnion.1 hx
    have hi := (mem_firstFailedPiece A i x).1 hxi
    simp only [Finset.mem_sdiff, Finset.mem_univ, true_and]
    intro hxC
    exact hi.2 ((mem_endpointCell i A x).2 ((mem_endpointCore A x).1 hxC i))
  · intro hx
    have hxnot : ¬∀ i : Fin k, x ∈ endpointCell i A := by
      simpa [mem_endpointCore] using (Finset.mem_sdiff.1 hx).2
    push Not at hxnot
    let i : Fin k := Fin.find (fun j ↦ x ∉ endpointCell j A) hxnot
    have hi : x ∉ endpointCell i A :=
      Fin.find_spec hxnot
    have hprev : ∀ j : Fin k, j < i → x ∈ endpointCell j A := by
      intro j hj
      exact not_not.mp (Fin.find_min hxnot hj)
    exact Finset.mem_biUnion.2 ⟨i, Finset.mem_univ i,
      (mem_firstFailedPiece A i x).2 ⟨hprev, hi⟩⟩

/-- Factors whose intersection is a prescribed first-failed piece.  Earlier
conditions are imposed positively, the selected condition negatively, and
later factors impose no restriction. -/
noncomputable def structuredFactors {k m : ℕ}
    (A : Finset (Word (k + 1) m)) (i : Fin k) (j : Fin k) :
    Finset (Word (k + 1) m) :=
  if j < i then endpointCell j A
  else if j = i then Finset.univ \ endpointCell j A
  else Finset.univ

theorem structuredFactors_isLastInsensitive {k m : ℕ}
    (A : Finset (Word (k + 1) m)) (i j : Fin k) :
    IsLastInsensitive j
      (structuredFactors A i j : Set (Word (k + 1) m)) := by
  by_cases hji : j < i
  · simpa [structuredFactors, hji] using endpointCell_isLastInsensitive j A
  · by_cases hEq : j = i
    · have hcell := endpointCell_isLastInsensitive j A
      intro x y hxy
      simpa [structuredFactors, hji, hEq] using not_congr (hcell x y hxy)
    · intro x y _
      simp [structuredFactors, hji, hEq]

theorem familyInter_structuredFactors {k m : ℕ}
    (A : Finset (Word (k + 1) m)) (i : Fin k) :
    familyInter (structuredFactors A i) = firstFailedPiece A i := by
  ext x
  rw [mem_familyInter, mem_firstFailedPiece]
  constructor
  · intro hx
    constructor
    · intro j hj
      simpa [structuredFactors, hj, ne_of_lt hj] using hx j
    · simpa [structuredFactors] using hx i
  · rintro ⟨hprev, hi⟩ j
    by_cases hj : j < i
    · simpa [structuredFactors, hj, ne_of_lt hj] using hprev j hj
    · by_cases hEq : j = i
      · subst j
        simpa [structuredFactors] using hi
      · simp [structuredFactors, hj, hEq]

theorem biUnion_inter_firstFailedPiece {k m : ℕ} (hk : 0 < k)
    (A : Finset (Word (k + 1) m)) :
    Finset.univ.biUnion (fun i : Fin k ↦ A ∩ firstFailedPiece A i) =
      A ∩ (Finset.univ \ endpointCore A) := by
  ext x
  constructor
  · intro hx
    obtain ⟨i, _, hxi⟩ := Finset.mem_biUnion.1 hx
    refine Finset.mem_inter.2 ⟨(Finset.mem_inter.1 hxi).1, ?_⟩
    rw [← biUnion_firstFailedPiece hk A]
    exact Finset.mem_biUnion.2 ⟨i, Finset.mem_univ i, (Finset.mem_inter.1 hxi).2⟩
  · intro hx
    have hxQ : x ∈ Finset.univ.biUnion (firstFailedPiece A) := by
      rw [biUnion_firstFailedPiece hk A]
      exact (Finset.mem_inter.1 hx).2
    obtain ⟨i, _, hxi⟩ := Finset.mem_biUnion.1 hxQ
    exact Finset.mem_biUnion.2 ⟨i, Finset.mem_univ i,
      Finset.mem_inter.2 ⟨(Finset.mem_inter.1 hx).1, hxi⟩⟩

/-! ## DKT Lemma 10 and Corollary 11 on a coordinate cube -/

/-- The many-restricted-lines branch yields a positive-density intersection
of `k` insensitive sets on which `A` has a fixed relative increment.

The error and increment are frozen at `delta0`; `rho` is the actual current
density. -/
theorem structured_correlation_of_many_lines
    {k m : ℕ} (hk : 2 ≤ k)
    (A : Finset (Word (k + 1) m))
    (hlineFree : ¬ContainsLine (A : Set (Word (k + 1) m)))
    (delta0 rho theta : ℝ)
    (hdelta0 : 0 < delta0) (hdelta0_one : delta0 ≤ 1)
    (hdelta_rho : delta0 ≤ rho)
    (htheta : 0 < theta) (htheta_one : theta ≤ 1)
    (hface : density (liftFinset (Finset.univ : Finset (Word k m))) <
      IncrementArithmetic.eta delta0 theta)
    (hAdense : rho - 2 * IncrementArithmetic.eta delta0 theta < density A)
    (hlines : theta / 2 < cubeRestrictedLineFraction A) :
    ∃ D : Fin k → Finset (Word (k + 1) m),
      (∀ i, IsLastInsensitive i (D i : Set (Word (k + 1) m))) ∧
      IncrementArithmetic.gamma delta0 (IncrementArithmetic.eta delta0 theta) k <
        density (familyInter D) ∧
      (rho + IncrementArithmetic.gamma delta0
          (IncrementArithmetic.eta delta0 theta) k) * density (familyInter D) <
        density (A ∩ familyInter D) := by
  let eta := IncrementArithmetic.eta delta0 theta
  let gamma := IncrementArithmetic.gamma delta0 eta k
  let C := endpointCore A
  let Q : Finset (Word (k + 1) m) := Finset.univ \ C
  let P : Fin k → Finset (Word (k + 1) m) := firstFailedPiece A
  have hkpos : 0 < (k : ℝ) := by exact_mod_cast (lt_of_lt_of_le (by omega) hk)
  have hkreal : (2 : ℝ) ≤ (k : ℝ) := by exact_mod_cast hk
  have hknat : 0 < k := lt_of_lt_of_le (by omega) hk
  have heta_pos : 0 < eta := IncrementArithmetic.eta_pos hdelta0 htheta
  have hparam := IncrementArithmetic.fixed_parameter_bounds
    hdelta0 hdelta0_one htheta htheta_one hkreal
  have heta_half : eta < 1 / 2 := hparam.2.1.trans_le (by linarith [htheta_one])
  have hthree_eta : 3 * eta < delta0 := hparam.2.2.1
  have hgamma_pos : 0 < gamma := hparam.2.2.2.1
  have hgamma_three : gamma < 3 * eta := hparam.2.2.2.2.2.1
  have hCdense : theta / 4 < density C := by
    exact endpointCore_density_lower_bound A htheta heta_half hface hlines
  have hACface : A ∩ C ⊆ liftFinset (Finset.univ : Finset (Word k m)) := by
    exact inter_endpointCore_subset_oldFace A hlineFree
  have hACsmall : density (A ∩ C) < eta :=
    (density_mono hACface).trans_lt hface
  have hAQ : rho - 3 * eta < density (A ∩ Q) := by
    have hsplit := density_sdiff_add_density_inter A C
    have hdiff : A \ C = A ∩ Q := by
      ext x
      simp [Q, C]
    rw [hdiff] at hsplit
    linarith
  have hQpos : 0 < density Q := by
    have hbase : 0 < rho - 3 * eta := by linarith
    exact hbase.trans hAQ |>.trans_le (density_inter_le_right A Q)
  have hQupper : density Q < 1 - theta / 4 := by
    have hcomp : density Q = 1 - density C := by
      simpa only [Q] using density_compl C
    rw [hcomp]
    linarith
  have hconditional :
      (rho + 6 * eta) * density Q < density (A ∩ Q) := by
    have hcoef : 0 ≤ rho + 6 * eta := by linarith
    have hmul : (rho + 6 * eta) * density Q <
        (rho + 6 * eta) * (1 - theta / 4) :=
      mul_lt_mul_of_pos_left hQupper (by linarith)
    have hfixed := IncrementArithmetic.fixed_lower_density_increment_mul
      hdelta0 hdelta_rho htheta
    exact hmul.trans (hfixed.trans hAQ)
  have hPdisj :
      ((Finset.univ : Finset (Fin k)) : Set (Fin k)).PairwiseDisjoint P :=
    firstFailedPiece_pairwiseDisjoint A
  have hPunion : Finset.univ.biUnion P = Q := by
    simpa [P, Q, C] using biUnion_firstFailedPiece hknat A
  have hAPdisj :
      ((Finset.univ : Finset (Fin k)) : Set (Fin k)).PairwiseDisjoint
        (fun i ↦ A ∩ P i) := by
    intro i _ j _ hij
    exact (hPdisj (Finset.mem_univ i) (Finset.mem_univ j) hij).mono
      Finset.inter_subset_right Finset.inter_subset_right
  have hAPunion : Finset.univ.biUnion (fun i ↦ A ∩ P i) = A ∩ Q := by
    simpa [P, Q, C] using biUnion_inter_firstFailedPiece hknat A
  let weight : Fin k → ℝ := fun i ↦ density (P i) / density Q
  let value : Fin k → ℝ := fun i ↦
    if density (P i) = 0 then 0 else density (A ∩ P i) / density (P i)
  have hweight_nonneg : ∀ i ∈ (Finset.univ : Finset (Fin k)), 0 ≤ weight i := by
    intro i _
    exact div_nonneg (density_nonneg _) hQpos.le
  have hvalue_le : ∀ i ∈ (Finset.univ : Finset (Fin k)), value i ≤ 1 := by
    intro i _
    by_cases hi : density (P i) = 0
    · change (if density (P i) = 0 then 0 else
          density (A ∩ P i) / density (P i)) ≤ 1
      rw [if_pos hi]
      norm_num
    · change (if density (P i) = 0 then 0 else
          density (A ∩ P i) / density (P i)) ≤ 1
      rw [if_neg hi]
      rw [div_le_one (lt_of_le_of_ne (density_nonneg _) (Ne.symm hi))]
      exact density_inter_le_right A (P i)
  have hweight_sum : ∑ i ∈ (Finset.univ : Finset (Fin k)), weight i = 1 := by
    change (∑ i ∈ (Finset.univ : Finset (Fin k)),
      density (P i) / density Q) = 1
    rw [← Finset.sum_div]
    rw [← density_biUnion hPdisj, hPunion]
    exact div_self hQpos.ne'
  have hpoint (i : Fin k) :
      weight i * value i = density (A ∩ P i) / density Q := by
    by_cases hi : density (P i) = 0
    · have hPi : P i = ∅ := (density_eq_zero (P i)).1 hi
      simp [weight, value, hPi]
    · simp only [weight, value, hi, if_false]
      field_simp [hi, hQpos.ne']
  have haverage_eq :
      (∑ i ∈ (Finset.univ : Finset (Fin k)), weight i * value i) =
        density (A ∩ Q) / density Q := by
    simp_rw [hpoint]
    rw [← Finset.sum_div, ← density_biUnion hAPdisj, hAPunion]
  have haverage : rho + 6 * eta <
      ∑ i ∈ (Finset.univ : Finset (Fin k)), weight i * value i := by
    rw [haverage_eq, lt_div_iff₀ hQpos]
    exact hconditional
  obtain ⟨i, _, hweight, hvalue⟩ :=
    IncrementArithmetic.exists_large_weight_and_value
      (Finset.univ : Finset (Fin k)) weight value
      hkpos (by simp) heta_pos hweight_nonneg hvalue_le hweight_sum
      (by linarith) haverage
  have hPi_pos : 0 < density (P i) := by
    have hsmallpos : 0 < 3 * eta / (k : ℝ) := by positivity
    have : 0 < weight i := hsmallpos.trans hweight
    by_contra hnot
    have hzero : density (P i) = 0 := le_antisymm (le_of_not_gt hnot) (density_nonneg _)
    have : weight i = 0 := by
      change density (P i) / density Q = 0
      rw [hzero, zero_div]
    linarith
  have hPi_lower :
      (3 * eta / (k : ℝ)) * (rho - 3 * eta) < density (P i) := by
    have hweight_mul : (3 * eta / (k : ℝ)) * density Q < density (P i) := by
      change 3 * eta / (k : ℝ) < density (P i) / density Q at hweight
      exact (lt_div_iff₀ hQpos).mp hweight
    have hqbase : rho - 3 * eta < density Q :=
      hAQ.trans_le (density_inter_le_right A Q)
    have hcoef : 0 < 3 * eta / (k : ℝ) := by positivity
    exact (mul_lt_mul_of_pos_left hqbase hcoef).trans hweight_mul
  have hPi_gamma : gamma < density (P i) := by
    exact (IncrementArithmetic.fixed_gamma_lt_structured_piece
      hdelta0 hdelta0_one hdelta_rho htheta htheta_one hkpos).trans hPi_lower
  have hAPi : (rho + 3 * eta) * density (P i) < density (A ∩ P i) := by
    simp only [value, hPi_pos.ne', if_false] at hvalue
    exact (lt_div_iff₀ hPi_pos).mp hvalue
  have hAPi_gamma :
      (rho + gamma) * density (P i) < density (A ∩ P i) := by
    have hleft : (rho + gamma) * density (P i) <
        (rho + 3 * eta) * density (P i) :=
      mul_lt_mul_of_pos_right (by linarith) hPi_pos
    exact hleft.trans hAPi
  refine ⟨structuredFactors A i, structuredFactors_isLastInsensitive A i,
    ?_, ?_⟩
  · simpa [gamma, P, familyInter_structuredFactors] using hPi_gamma
  · simpa [gamma, P, familyInter_structuredFactors] using hAPi_gamma

/-! ## Transport to an arbitrary subspace and the Lemma 8 alternative -/

theorem cubeRestrictedLines_pullback {k m : ℕ} {iota : Type*}
    (W : Combinatorics.Subspace (Fin m) (Fin (k + 1)) iota)
    (A : Finset (iota → Fin (k + 1))) :
    cubeRestrictedLines (pullbackFinset W A) = restrictedInternalLines W A := by
  ext l
  simp [cubeRestrictedLines, restrictedInternalLines]

theorem cubeRestrictedLineFraction_pullback {k m : ℕ} {iota : Type*}
    (W : Combinatorics.Subspace (Fin m) (Fin (k + 1)) iota)
    (A : Finset (iota → Fin (k + 1))) :
    cubeRestrictedLineFraction (pullbackFinset W A) =
      restrictedInternalLineFraction W A := by
  rw [cubeRestrictedLineFraction, restrictedInternalLineFraction,
    cubeRestrictedLines_pullback]

/-- Coordinate-type-independent form of line containment, needed because the
correlation step naturally uses a sum of coordinate types. -/
def ContainsLineOn {alpha iota : Type*} (A : Set (iota → alpha)) : Prop :=
  ∃ l : Combinatorics.Line alpha iota, Set.range l ⊆ A

theorem pullback_lineFree {k m : ℕ} {iota : Type*}
    (W : Combinatorics.Subspace (Fin m) (Fin (k + 1)) iota)
    (A : Finset (iota → Fin (k + 1)))
    (hA : ¬ContainsLineOn (A : Set (iota → Fin (k + 1)))) :
    ¬ContainsLine (pullbackFinset W A : Set (Word (k + 1) m)) := by
  intro h
  apply hA
  obtain ⟨l, hl⟩ := h
  refine ⟨W.lineMap l, ?_⟩
  rintro _ ⟨a, rfl⟩
  rw [Combinatorics.Subspace.lineMap_apply]
  exact (mem_pullbackFinset W A (l a)).1 (hl ⟨a, rfl⟩)

/-- Subspace form of the many-lines branch. -/
theorem structured_correlation_on_subspace_of_many_lines
    {k m : ℕ} (hk : 2 ≤ k) {iota : Type*}
    (W : Combinatorics.Subspace (Fin m) (Fin (k + 1)) iota)
    (A : Finset (iota → Fin (k + 1)))
    (hlineFree : ¬ContainsLineOn (A : Set (iota → Fin (k + 1))))
    (delta0 rho theta : ℝ)
    (hdelta0 : 0 < delta0) (hdelta0_one : delta0 ≤ 1)
    (hdelta_rho : delta0 ≤ rho)
    (htheta : 0 < theta) (htheta_one : theta ≤ 1)
    (hface : density (liftFinset (Finset.univ : Finset (Word k m))) <
      IncrementArithmetic.eta delta0 theta)
    (hWdense : rho - 2 * IncrementArithmetic.eta delta0 theta <
      subspaceDensityFinset W A)
    (hWlines : theta / 2 < restrictedInternalLineFraction W A) :
    ∃ D : Fin k → Finset (Word (k + 1) m),
      (∀ i, IsLastInsensitive i (D i : Set (Word (k + 1) m))) ∧
      IncrementArithmetic.gamma delta0 (IncrementArithmetic.eta delta0 theta) k <
        density (familyInter D) ∧
      (rho + IncrementArithmetic.gamma delta0
          (IncrementArithmetic.eta delta0 theta) k) * density (familyInter D) <
        density (pullbackFinset W A ∩ familyInter D) := by
  apply structured_correlation_of_many_lines hk (pullbackFinset W A)
    (pullback_lineFree W A hlineFree) delta0 rho theta hdelta0 hdelta0_one
    hdelta_rho htheta htheta_one hface
  · exact hWdense
  · simpa only [cubeRestrictedLineFraction_pullback] using hWlines

/-- DKT Corollary 11 directly from the disjunction in Correlation Lemma 8.
Both branches have the same structured conclusion: in the direct increment
branch all insensitive factors are the whole cube. -/
theorem structured_correlation_of_correlated_sections
    {k m : ℕ} (hk : 2 ≤ k) (hm : 0 < m) {iota kappa : Type*}
    [Fintype kappa]
    (U : Combinatorics.Subspace (Fin m) (Fin (k + 1)) iota)
    (A : Finset (iota ⊕ kappa → Fin (k + 1)))
    (hlineFree : ¬ContainsLineOn (A : Set (iota ⊕ kappa → Fin (k + 1))))
    (delta0 rho theta : ℝ)
    (hdelta0 : 0 < delta0) (hdelta0_one : delta0 ≤ 1)
    (hdelta_rho : delta0 ≤ rho)
    (htheta : 0 < theta) (htheta_one : theta ≤ 1)
    (hface : density (liftFinset (Finset.univ : Finset (Word k m))) <
      IncrementArithmetic.eta delta0 theta)
    (hsection : ∀ x : Word (k + 1) m,
      rho - (IncrementArithmetic.eta delta0 theta) ^ 2 / 2 ≤
        density (sectionTails U A x))
    (hcorrelation : ∀ l : Combinatorics.Line (Fin k) (Fin m),
      theta ≤ density (restrictedLineTails U A l)) :
    ∃ W : Combinatorics.Subspace (Fin m) (Fin (k + 1)) (iota ⊕ kappa),
      ∃ D : Fin k → Finset (Word (k + 1) m),
        (∀ i, IsLastInsensitive i (D i : Set (Word (k + 1) m))) ∧
        IncrementArithmetic.gamma delta0 (IncrementArithmetic.eta delta0 theta) k <
          density (familyInter D) ∧
        (rho + IncrementArithmetic.gamma delta0
            (IncrementArithmetic.eta delta0 theta) k) * density (familyInter D) <
          density (pullbackFinset W A ∩ familyInter D) := by
  let eta := IncrementArithmetic.eta delta0 theta
  let gamma := IncrementArithmetic.gamma delta0 eta k
  have hkreal : (2 : ℝ) ≤ (k : ℝ) := by exact_mod_cast hk
  have hparam := IncrementArithmetic.fixed_parameter_bounds
    hdelta0 hdelta0_one htheta htheta_one hkreal
  have heta_pos : 0 < eta := hparam.1
  have heta_theta : eta < theta / 2 := hparam.2.1
  have hgamma_pos : 0 < gamma := hparam.2.2.2.1
  have hgamma_half : gamma ≤ eta ^ 2 / 2 := hparam.2.2.2.2.1
  have hgamma_one : gamma < 1 := hparam.2.2.2.2.2.2.2.1
  let : Nonempty (Fin m) := Fin.pos_iff_nonempty.mp hm
  rcases density_increment_or_many_restricted_lines U A rho eta theta
      heta_pos htheta heta_theta hsection hcorrelation with hinc | hmany
  · obtain ⟨W, hW⟩ := hinc
    let D : Fin k → Finset (Word (k + 1) m) := fun _ ↦ Finset.univ
    refine ⟨W, D, ?_, ?_, ?_⟩
    · intro i x y _
      simp [D]
    · have : density (familyInter D) = 1 := by
        have : Nonempty (Word (k + 1) m) := inferInstance
        rw [show familyInter D = Finset.univ by ext x; simp [D], density_univ]
      change gamma < density (familyInter D)
      rw [this]
      exact hgamma_one
    · have hinter : pullbackFinset W A ∩ familyInter D = pullbackFinset W A := by
        ext x
        simp [D]
      rw [hinter]
      have hden : subspaceDensityFinset W A = density (pullbackFinset W A) := rfl
      rw [hden] at hW
      have hfamily : density (familyInter D) = 1 := by
        have : Nonempty (Word (k + 1) m) := inferInstance
        rw [show familyInter D = Finset.univ by ext x; simp [D], density_univ]
      rw [hfamily, mul_one]
      nlinarith
  · obtain ⟨W, hWdense, hWlines⟩ := hmany
    refine ⟨W, ?_⟩
    exact structured_correlation_on_subspace_of_many_lines hk W A hlineFree
      delta0 rho theta hdelta0 hdelta0_one hdelta_rho htheta htheta_one
      hface hWdense hWlines

/-- Lemma 7 followed by Lemma 8 and Corollary 11.  This is the uniform-section
interface used by the density-increment iteration: once all point sections of
a sufficiently large prefix subspace have the required lower bound, the
conclusion is a structured relative increment on an `m`-dimensional subspace. -/
theorem structured_correlation_of_uniform_sections
    (k m0 m : ℕ) (hk : 2 ≤ k) (hm0 : 0 < m0) (hm0m : m0 ≤ m)
    {iota kappa : Type*} [Fintype kappa]
    (delta0 : ℝ) (hdelta0 : 0 < delta0) (hdelta0_one : delta0 ≤ 1)
    (htheta : 0 < IncrementArithmetic.theta delta0
      (Fintype.card (Combinatorics.Line (Fin k) (Fin m0))))
    (htheta_one : IncrementArithmetic.theta delta0
      (Fintype.card (Combinatorics.Line (Fin k) (Fin m0))) ≤ 1)
    (herror : (IncrementArithmetic.eta delta0
      (IncrementArithmetic.theta delta0
        (Fintype.card (Combinatorics.Line (Fin k) (Fin m0))))) ^ 2 / 2 ≤
        delta0 / 2)
    (hface : density (liftFinset (Finset.univ : Finset (Word k m))) <
      IncrementArithmetic.eta delta0
        (IncrementArithmetic.theta delta0
          (Fintype.card (Combinatorics.Line (Fin k) (Fin m0)))))
    (hDHJ : ∀ B : Finset (Word k m0),
      delta0 / 4 ≤ density B → ContainsLine (B : Set (Word k m0))) :
    ∃ N : ℕ, ∀ r ≥ N,
      ∀ (U : Combinatorics.Subspace (Fin r) (Fin (k + 1)) iota)
        (A : Finset (iota ⊕ kappa → Fin (k + 1))) (rho : ℝ),
        delta0 ≤ rho →
        ¬ContainsLineOn (A : Set (iota ⊕ kappa → Fin (k + 1))) →
        (∀ x : Word (k + 1) r,
          rho - (IncrementArithmetic.eta delta0
            (IncrementArithmetic.theta delta0
              (Fintype.card (Combinatorics.Line (Fin k) (Fin m0))))) ^ 2 / 2 ≤
            density (sectionTails U A x)) →
        ∃ W : Combinatorics.Subspace (Fin m) (Fin (k + 1)) (iota ⊕ kappa),
          ∃ D : Fin k → Finset (Word (k + 1) m),
            (∀ i, IsLastInsensitive i (D i : Set (Word (k + 1) m))) ∧
            IncrementArithmetic.gamma delta0
                (IncrementArithmetic.eta delta0
                  (IncrementArithmetic.theta delta0
                    (Fintype.card (Combinatorics.Line (Fin k) (Fin m0))))) k <
              density (familyInter D) ∧
            (rho + IncrementArithmetic.gamma delta0
                (IncrementArithmetic.eta delta0
                  (IncrementArithmetic.theta delta0
                    (Fintype.card (Combinatorics.Line (Fin k) (Fin m0))))) k) *
                density (familyInter D) <
              density (pullbackFinset W A ∩ familyInter D) := by
  let theta : ℝ := IncrementArithmetic.theta delta0
    (Fintype.card (Combinatorics.Line (Fin k) (Fin m0)))
  let eta : ℝ := IncrementArithmetic.eta delta0 theta
  have hkpos : 0 < k := lt_of_lt_of_le (by omega) hk
  have hm : 0 < m := hm0.trans_le hm0m
  obtain ⟨N, hN⟩ := exists_correlated_subspace_of_uniform_sections
    k m0 m hkpos hm0 hm0m delta0 eta hdelta0 herror hDHJ
  refine ⟨N, ?_⟩
  intro r hr U A rho hdelta_rho hlineFree hsection
  obtain ⟨V, hVsection, hVcorrelation⟩ :=
    hN r hr U A rho hdelta_rho hsection
  exact structured_correlation_of_correlated_sections hk hm V A hlineFree
    delta0 rho theta hdelta0 hdelta0_one hdelta_rho htheta htheta_one
    hface hVsection hVcorrelation

end Erdos171
