/-
Copyright (c) 2026 The lean-proofs contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-proofs contributors
-/

import ErdosProblems.Erdos599.GroundingEqualRootedOutput

/-!
# Output boundary for the equal-stage active closure

The collision-free stationary equal subwarp reserves one grounded,
inessential parent.  The relation which roots the whole essential terminal
cut must, however, be larger than the relation generated by that sparse
subwarp: every untouched hanging essential component has to be absorbed by
the active closure.

This file separates those two roles.  `EqualActiveClosureOutput` records the
exact relation-theoretic output of the enlarged closure.  It makes no claim
that the relation is the sparse canonical repaired relation.  Its roots omit
one reserved original source, which is the only fact about the reserved
stationary seed needed by the final finite-reachability compiler.
-/

noncomputable section

open Set

namespace Erdos599
namespace DWeb

universe u

variable {V : Type u} {Gamma : DWeb V} {kappa : Cardinal.{u}}

namespace KappaLadder

open GroundingRootedReachabilityWarp

/-- Remove exactly the edges which leave `S`.  This local pruning is useful
for reserving an inessential ladder parent: it cannot create a uniqueness or
adjacency conflict, and it makes `S` forward closed by construction. -/
def forwardClosurePrune (E : Set (V × V)) (S : Set V) : Set (V × V) :=
  {e | e ∈ E ∧ (e.1 ∈ S → e.2 ∈ S)}

theorem forwardClosurePrune_subset (E : Set (V × V)) (S : Set V) :
    forwardClosurePrune E S ⊆ E := by
  intro e he
  exact he.1

theorem forwardClosurePrune_biUnique
    {E : Set (V × V)} {S : Set V}
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E) :
    Relator.BiUnique fun x y ↦ (x, y) ∈ forwardClosurePrune E S := by
  constructor
  · intro a b c hac hbc
    exact hbi.1 hac.1 hbc.1
  · intro a b c hab hac
    exact hbi.2 hab.1 hac.1

theorem forwardClosurePrune_noOutgoing
    {E : Set (V × V)} {S B : Set V}
    (h : ∀ b ∈ B, ¬ Alternating.HasOutgoing E b) :
    ∀ b ∈ B, ¬ Alternating.HasOutgoing (forwardClosurePrune E S) b := by
  intro b hb
  rintro ⟨c, hbc⟩
  exact h b hb ⟨c, hbc.1⟩

theorem forwardClosurePrune_closed
    (E : Set (V × V)) (S : Set V) {e : V × V}
    (he : e ∈ forwardClosurePrune E S) (htail : e.1 ∈ S) :
    e.2 ∈ S :=
  he.2 htail

/-- A sink boundary is a reachability antichain.  The active closure normally
stops every added route at the essential terminal cut, so this local form is
often easier to establish than antichainness directly. -/
theorem isReachabilityAntichain_of_noOutgoing
    {E : Set (V × V)} {B : Set V}
    (h : ∀ b ∈ B, ¬ Alternating.HasOutgoing E b) :
    IsReachabilityAntichain E B := by
  intro b hb c _hc hbc
  rcases hbc.cases_head with hcb | ⟨x, hbx, _hxc⟩
  · exact hcb
  · exact False.elim (h b hb ⟨x, hbx⟩)

/-- The complete relation-level output required from the enlarged
equal-stage active closure.

The boundary is fixed to the essential terminal cut of the limiting ladder.
In particular the construction may freely add routes for hanging components;
it is not tied to the sparse stationary seed relation. -/
structure EqualActiveClosureOutput
    (L : Gamma.KappaLadder kappa) (hL : L.IsKappaHindrance) where
  edges : Set (V × V)
  allowedRoots : Set V
  edges_subset_adj : edges ⊆ {e | Gamma.graph.Adj e.1 e.2}
  edges_biUnique : Relator.BiUnique fun x y ↦ (x, y) ∈ edges
  allowedRoots_subset_source : allowedRoots ⊆ Gamma.source
  terminalCut_antichain : IsReachabilityAntichain edges
    (L.popularAuxiliaryInput hL.legal).terminalCut
  terminalCut_rooted :
    ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ allowedRoots,
        Relation.ReflTransGen (fun x y ↦ (x, y) ∈ edges) a b
  reservedSource : V
  reservedSource_mem : reservedSource ∈ Gamma.source
  reservedSource_not_allowed : reservedSource ∉ allowedRoots

namespace EqualActiveClosureOutput

variable {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}

/-- Compile an enlarged equal-stage active closure directly to an ordinary
hindrance.  All global graph geometry has already been reduced to the local
bi-unique rooted relation recorded in the structure. -/
theorem exists_hindrance (O : L.EqualActiveClosureOutput hL) :
    ∃ H : Set Gamma.DPath, Gamma.IsHindrance H := by
  exact L.exists_hindrance_of_rootedTerminalCut hL O.edges O.allowedRoots
    O.edges_subset_adj O.edges_biUnique O.allowedRoots_subset_source
    O.terminalCut_antichain O.terminalCut_rooted O.reservedSource
    O.reservedSource_mem O.reservedSource_not_allowed

end EqualActiveClosureOutput

/-- Turn source-rooted coverage into an active-closure output after removing
one source which cannot reach the terminal cut in the enlarged relation.

This is the generic unused-source step.  For the equal branch the excluded
source is the initial vertex of the reserved grounded parent; avoidance of
that parent by every added active route is used only to prove `hreserved`.
-/
theorem equalActiveClosureOutput_of_sourceRooted_excluding
    (L : Gamma.KappaLadder kappa) (hL : L.IsKappaHindrance)
    (E : Set (V × V))
    (hEadj : E ⊆ {e | Gamma.graph.Adj e.1 e.2})
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E)
    (hanti : IsReachabilityAntichain E
      (L.popularAuxiliaryInput hL.legal).terminalCut)
    (hroot : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ Gamma.source,
        Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E) a b)
    (reserved : V) (hreservedSource : reserved ∈ Gamma.source)
    (hreserved : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ¬ Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E) reserved b) :
    Nonempty (L.EqualActiveClosureOutput hL) := by
  refine ⟨{
    edges := E
    allowedRoots := Gamma.source \ {reserved}
    edges_subset_adj := hEadj
    edges_biUnique := hbi
    allowedRoots_subset_source := fun _ ha ↦ ha.1
    terminalCut_antichain := hanti
    terminalCut_rooted := ?_
    reservedSource := reserved
    reservedSource_mem := hreservedSource
    reservedSource_not_allowed := by simp }⟩
  intro b hb
  obtain ⟨a, haSource, hab⟩ := hroot b hb
  have hne : a ≠ reserved := by
    intro har
    subst a
    exact hreserved b hb hab
  exact ⟨a, ⟨haSource, by simpa using hne⟩, hab⟩

/-- Reserved-parent specialization of the generic unused-source step.  The
sparse stationary equal subwarp supplies `R`; the enlarged ordered closure
supplies `E` and proves that the reserved parent initial still cannot reach
the terminal cut. -/
theorem ReservedGroundedParent.equalActiveClosureOutput_of_sourceRooted
    {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}
    {q : DirectedPath.FinitePath
      (L.popularAuxiliaryInput hL.legal).lambda.graph}
    {hqsource : q.start ∈
      (L.popularAuxiliaryInput hL.legal).lambda.source}
    (R : L.ReservedGroundedParent hL q hqsource)
    (E : Set (V × V))
    (hEadj : E ⊆ {e | Gamma.graph.Adj e.1 e.2})
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E)
    (hanti : IsReachabilityAntichain E
      (L.popularAuxiliaryInput hL.legal).terminalCut)
    (hroot : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ Gamma.source,
        Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E) a b)
    (hreserved :
      ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
        ¬ Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E)
          R.parent.initial b) :
    Nonempty (L.EqualActiveClosureOutput hL) := by
  exact equalActiveClosureOutput_of_sourceRooted_excluding L hL E hEadj hbi
    hanti hroot R.parent.initial R.parent_initial_source hreserved

/-- Forward closure of the reserved inessential parent is enough to exclude
its initial vertex from all terminal-cut rooting witnesses.  This is the
form naturally proved by an active construction: residual ladder edges stay
on their unique parent, and every newly inserted route avoids that parent. -/
theorem ReservedGroundedParent.not_reaches_terminalCut_of_forwardClosed
    {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}
    {q : DirectedPath.FinitePath
      (L.popularAuxiliaryInput hL.legal).lambda.graph}
    {hqsource : q.start ∈
      (L.popularAuxiliaryInput hL.legal).lambda.source}
    (R : L.ReservedGroundedParent hL q hqsource)
    (E : Set (V × V))
    (hclosed : ∀ e ∈ E, e.1 ∈ R.parent.support →
      e.2 ∈ R.parent.support)
    {b : V} (hb : b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut) :
    ¬ Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E)
      R.parent.initial b := by
  intro hreach
  have hstay : ∀ {x : V},
      Relation.ReflTransGen (fun u v ↦ (u, v) ∈ E)
        R.parent.initial x → x ∈ R.parent.support := by
    intro x hx
    induction hx with
    | refl => exact R.parent.initial_mem_support
    | @tail x y _hxy hxy ih => exact hclosed (x, y) hxy ih
  have hbSupport : b ∈ R.parent.support := hstay hreach
  exact terminalCut_not_mem_support_of_inessential L hL hb
    R.parent_inessential hbSupport

/-- Constructor form using the forward-closure invariant maintained by the
ordered active relation. -/
theorem ReservedGroundedParent.equalActiveClosureOutput_of_sourceRooted_of_forwardClosed
    {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}
    {q : DirectedPath.FinitePath
      (L.popularAuxiliaryInput hL.legal).lambda.graph}
    {hqsource : q.start ∈
      (L.popularAuxiliaryInput hL.legal).lambda.source}
    (R : L.ReservedGroundedParent hL q hqsource)
    (E : Set (V × V))
    (hEadj : E ⊆ {e | Gamma.graph.Adj e.1 e.2})
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E)
    (hanti : IsReachabilityAntichain E
      (L.popularAuxiliaryInput hL.legal).terminalCut)
    (hroot : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ Gamma.source,
        Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E) a b)
    (hclosed : ∀ e ∈ E, e.1 ∈ R.parent.support →
      e.2 ∈ R.parent.support) :
    Nonempty (L.EqualActiveClosureOutput hL) := by
  apply R.equalActiveClosureOutput_of_sourceRooted E hEadj hbi hanti hroot
  intro b hb
  exact R.not_reaches_terminalCut_of_forwardClosed E hclosed hb

/-- Sink-boundary specialization of the forward-closure constructor. -/
theorem ReservedGroundedParent.equalActiveClosureOutput_of_sourceRooted_of_noOutgoing
    {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}
    {q : DirectedPath.FinitePath
      (L.popularAuxiliaryInput hL.legal).lambda.graph}
    {hqsource : q.start ∈
      (L.popularAuxiliaryInput hL.legal).lambda.source}
    (R : L.ReservedGroundedParent hL q hqsource)
    (E : Set (V × V))
    (hEadj : E ⊆ {e | Gamma.graph.Adj e.1 e.2})
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E)
    (hnoOutgoing :
      ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
        ¬ Alternating.HasOutgoing E b)
    (hroot : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ Gamma.source,
        Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E) a b)
    (hclosed : ∀ e ∈ E, e.1 ∈ R.parent.support →
      e.2 ∈ R.parent.support) :
    Nonempty (L.EqualActiveClosureOutput hL) := by
  exact R.equalActiveClosureOutput_of_sourceRooted_of_forwardClosed E hEadj
    hbi (isReachabilityAntichain_of_noOutgoing hnoOutgoing) hroot hclosed

/-- Escape-pruned constructor for an enlarged active relation.  Starting
from an adjacent bi-unique relation `E`, remove only edges leaving the
reserved parent.  The structural output obligations are then automatic;
the construction only has to show that every essential terminal remains
rooted after this local pruning. -/
theorem ReservedGroundedParent.equalActiveClosureOutput_of_forwardClosurePrune
    {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}
    {q : DirectedPath.FinitePath
      (L.popularAuxiliaryInput hL.legal).lambda.graph}
    {hqsource : q.start ∈
      (L.popularAuxiliaryInput hL.legal).lambda.source}
    (R : L.ReservedGroundedParent hL q hqsource)
    (E : Set (V × V))
    (hEadj : E ⊆ {e | Gamma.graph.Adj e.1 e.2})
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E)
    (hnoOutgoing :
      ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
        ¬ Alternating.HasOutgoing E b)
    (hroot : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ Gamma.source,
        Relation.ReflTransGen
          (fun x y ↦ (x, y) ∈
            forwardClosurePrune E R.parent.support) a b) :
    Nonempty (L.EqualActiveClosureOutput hL) := by
  apply R.equalActiveClosureOutput_of_sourceRooted_of_noOutgoing
    (forwardClosurePrune E R.parent.support)
  · exact (forwardClosurePrune_subset E R.parent.support).trans hEadj
  · exact forwardClosurePrune_biUnique hbi
  · exact forwardClosurePrune_noOutgoing hnoOutgoing
  · exact hroot
  · intro e he htail
    exact forwardClosurePrune_closed E R.parent.support he htail

/-- Direct compiler form of the reserved-parent specialization. -/
theorem ReservedGroundedParent.exists_hindrance_of_activeClosure
    {L : Gamma.KappaLadder kappa} {hL : L.IsKappaHindrance}
    {q : DirectedPath.FinitePath
      (L.popularAuxiliaryInput hL.legal).lambda.graph}
    {hqsource : q.start ∈
      (L.popularAuxiliaryInput hL.legal).lambda.source}
    (R : L.ReservedGroundedParent hL q hqsource)
    (E : Set (V × V))
    (hEadj : E ⊆ {e | Gamma.graph.Adj e.1 e.2})
    (hbi : Relator.BiUnique fun x y ↦ (x, y) ∈ E)
    (hanti : IsReachabilityAntichain E
      (L.popularAuxiliaryInput hL.legal).terminalCut)
    (hroot : ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
      ∃ a ∈ Gamma.source,
        Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E) a b)
    (hreserved :
      ∀ b ∈ (L.popularAuxiliaryInput hL.legal).terminalCut,
        ¬ Relation.ReflTransGen (fun x y ↦ (x, y) ∈ E)
          R.parent.initial b) :
    ∃ H : Set Gamma.DPath, Gamma.IsHindrance H := by
  exact (R.equalActiveClosureOutput_of_sourceRooted E hEadj hbi hanti
    hroot hreserved).some.exists_hindrance

/-- End-to-end reduction of the target-pure stationary equal branch to the
enlarged active-closure output.

The stationary selection reserves one seed path and thins the remaining
equal family so that its decoded carriers are pairwise disjoint and avoid the
reserved collision carrier.  The callback receives the resulting reserved
grounded parent together with every selection invariant.  Unlike the older
canonical-relation callback, its output may use any enlarged relation which
absorbs all essential hanging components. -/
theorem exists_hindrance_of_targetPure_stationary_equalSubwarp_of_activeClosureOutput
    (L : Gamma.KappaLadder kappa) (hL : L.IsKappaHindrance)
    (P : Popular.XSWarp
      (L.popularAuxiliaryInput hL.legal).lambda
      (L.popularAuxiliaryInput hL.legal).lambda.target)
    (hpure : ∀ p ∈ P.paths,
      (L.popularAuxiliaryInput hL.legal).IsTargetPure p)
    (hstat : Stationary.IsStationaryBelow kappa
      (Popular.initialIndicesOf (L.popularAuxiliaryIndexed hL)
        ((L.popularAuxiliaryIndexed hL).equalSubwarp P).paths
        ((L.popularAuxiliaryIndexed hL).equalSubwarp P).starts_in_source))
    (activeClosure : ∀
      (q : DirectedPath.FinitePath
        (L.popularAuxiliaryInput hL.legal).lambda.graph)
      (hq : q ∈ ((L.popularAuxiliaryIndexed hL).equalSubwarp P).paths)
      (Q : Popular.XSWarp
        (L.popularAuxiliaryInput hL.legal).lambda
        (L.popularAuxiliaryInput hL.legal).lambda.target),
      Q.paths ⊆ ((L.popularAuxiliaryIndexed hL).equalSubwarp P).paths →
      (∀ p ∈ Q.paths,
        (L.popularAuxiliaryInput hL.legal).IsTargetPure p) →
      Stationary.IsStationaryBelow kappa
        (Popular.initialIndicesOf (L.popularAuxiliaryIndexed hL)
          ((L.popularAuxiliaryIndexed hL).equalSubwarp Q).paths
          ((L.popularAuxiliaryIndexed hL).equalSubwarp Q).starts_in_source) →
      Q.paths.PairwiseDisjoint
        (L.popularAuxiliaryInput hL.legal).decodedVertexCarrier →
      (∀ p ∈ Q.paths,
        Disjoint p.support
          (GroundingEqualActiveSelection.collisionCarrier
            (L.popularAuxiliaryInput hL.legal) q)) →
      ∀ R : L.ReservedGroundedParent hL q
        (((L.popularAuxiliaryIndexed hL).equalSubwarp P).starts_in_source hq),
        Nonempty (L.EqualActiveClosureOutput hL)) :
    ∃ H : Set Gamma.DPath, Gamma.IsHindrance H := by
  obtain ⟨q, hq, Q, hQP, hQpure, hQstat, hQdisjoint, hQavoid⟩ :=
    L.exists_reserved_targetPure_stationary_equalSubwarp hL P hpure hstat
  obtain ⟨R⟩ := L.reservedGroundedParent_nonempty hL q
    (((L.popularAuxiliaryIndexed hL).equalSubwarp P).starts_in_source hq)
  exact (activeClosure q hq Q hQP hQpure hQstat hQdisjoint hQavoid R).some
    |>.exists_hindrance

end KappaLadder
end DWeb
end Erdos599

#print axioms Erdos599.DWeb.KappaLadder.EqualActiveClosureOutput.exists_hindrance
#print axioms Erdos599.DWeb.KappaLadder.equalActiveClosureOutput_of_sourceRooted_excluding
#print axioms Erdos599.DWeb.KappaLadder.ReservedGroundedParent.exists_hindrance_of_activeClosure
#print axioms Erdos599.DWeb.KappaLadder.ReservedGroundedParent.equalActiveClosureOutput_of_sourceRooted_of_forwardClosed
#print axioms Erdos599.DWeb.KappaLadder.ReservedGroundedParent.equalActiveClosureOutput_of_forwardClosurePrune
#print axioms Erdos599.DWeb.KappaLadder.exists_hindrance_of_targetPure_stationary_equalSubwarp_of_activeClosureOutput
