/-
Copyright (c) 2026 The lean-proofs contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-proofs contributors
-/

import ErdosProblems.Erdos599.MovingSchedulerSuccessor
import ErdosProblems.Erdos599.HalfwayIndexedRelationScheduler

/-!
# Fair repeated scheduling from the moving 9.34 compiler

This is the final mechanical composition layer.  It instantiates the total
indexed successor from the source-faithful all-real-terminal moving compiler,
uses the canonical indexed relation limit at every proper ordinal, and then
uses the canonical all-real relation at the final fair limit.
-/

noncomputable section

open Cardinal Order Set

namespace Erdos599
namespace Blueprint
namespace LinkageBlueprint
namespace IndexedTerminalResolutionState
namespace ReachableResolutionRecursor
namespace ResolutionChain

universe u w

variable {V : Type u}
variable {Gamma : DWeb V} {Y : Set Gamma.DPath} {kappa : Cardinal.{u}}
variable {persistent B : Set V}
variable {Stage : Type w} [LinearOrder Stage]
variable {slice closure : Stage → Set V}

/-- The repeated request chain generated by the actual moving-slice
all-real-terminal successor and honest proper relation limits. -/
noncomputable def movingRepeatedChain
    {Request : Set V} [LinearOrder Request] [WellFoundedLT Request]
    (M : AllRealTerminalMovingCompiler
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure))
    (seed : IndexedTerminalResolutionState
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B) slice closure)
    (u₀ : V) (hu₀ : u₀ ∈ seed.blueprint.realPart.terminals)
    (P : ProperRelationLimitBoundaryProvider
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure)
      (repeatedRequestLength Request)) :
    ResolutionChain
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure)
      (TerminalResolutionState.RepeatedRequestIndex Request) :=
  repeatedChain (SchedulerSuccessor.ofMovingCompiler M) seed u₀ hu₀
    (properLimitCompilerOfBoundaryProvider P)

/-- The moving repeated run resolves every real terminal appearing at any
stage, provided the global request carrier contains every stage closure. -/
noncomputable def movingSuccessfulEnumeration
    {Request : Set V} [LinearOrder Request] [WellFoundedLT Request]
    (M : AllRealTerminalMovingCompiler
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure))
    (seed : IndexedTerminalResolutionState
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B) slice closure)
    (u₀ : V) (hu₀ : u₀ ∈ seed.blueprint.realPart.terminals)
    (P : ProperRelationLimitBoundaryProvider
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure)
      (repeatedRequestLength Request))
    (hclosure : ∀ s, closure s ⊆ Request) :
    SuccessfulResolutionEnumeration
      (movingRepeatedChain M seed u₀ hu₀ P) seed :=
  successfulRepeatedEnumeration (SchedulerSuccessor.ofMovingCompiler M)
    seed u₀ hu₀ (properLimitCompilerOfBoundaryProvider P) hclosure

/-- Full fair final output of the moving-slice recursion.  The only final
input is the honest IsLB/stability/supremum-index boundary for the canonical
all-real relation. -/
noncomputable def movingFairResolutionLimit
    {Request : Set V} [LinearOrder Request] [WellFoundedLT Request]
    [Nonempty Request]
    (M : AllRealTerminalMovingCompiler
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure))
    (seed : IndexedTerminalResolutionState
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B) slice closure)
    (u₀ : V) (hu₀ : u₀ ∈ seed.blueprint.realPart.terminals)
    (P : ProperRelationLimitBoundaryProvider
      (Gamma := Gamma) (Y := Y) (kappa := kappa)
      (persistent := persistent) (B := B)
      (slice := slice) (closure := closure)
      (repeatedRequestLength Request))
    (hclosure : ∀ s, closure s ⊆ Request)
    (D : FinalRelationLimitBoundary
      (movingRepeatedChain M seed u₀ hu₀ P)) :
    FairResolutionLimit (movingRepeatedChain M seed u₀ hu₀ P) seed :=
  FairResolutionLimit.ofSuccessfulEnumeration D
    (movingSuccessfulEnumeration M seed u₀ hu₀ P hclosure)

end ResolutionChain
end ReachableResolutionRecursor
end IndexedTerminalResolutionState
end LinkageBlueprint
end Blueprint
end Erdos599

