/-
Copyright (c) 2026 The lean-proofs contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-proofs contributors
-/

import ErdosProblems.Erdos599.AlternatingComponents

/-!
# Components generated by an indexed family of warps

For two finite-character warps, alternating components are countable.  The
singular-cardinal analogue needed for a cofinal family of linkages is the
corresponding sharp cardinal estimate: a component generated by `I` many
warps has cardinality at most `max aleph_0 #I`.  Finite character is not
needed for this bound, since the support of a ray is still countable; the
file also retains a finite-character wrapper matching the two-warp API.

We use the harmlessly enlarged adjacency relation saying that two vertices
lie on a common member of one indexed warp.  It has the same closure property
needed for componentwise exchanges, and makes the cardinal argument
independent of orientations of the individual path edges.
-/

noncomputable section

open Cardinal Set

namespace Erdos599
namespace IndexedWarpComponents

universe u

variable {V I : Type u} {G : DWeb V}

/-- Two vertices lie on one member of one of the indexed path families. -/
def SameIndexedWarpPath (W : I → Set G.DPath) (x y : V) : Prop :=
  ∃ i p, p ∈ W i ∧ x ∈ p.support ∧ y ∈ p.support

/-- The component generated by all members of the indexed path families. -/
def component (W : I → Set G.DPath) (root : V) : Set V :=
  {x | Relation.ReflTransGen (SameIndexedWarpPath W) root x}

theorem sameIndexedWarpPath_symm {W : I → Set G.DPath} {x y : V}
    (h : SameIndexedWarpPath W x y) : SameIndexedWarpPath W y x := by
  obtain ⟨i, p, hp, hx, hy⟩ := h
  exact ⟨i, p, hp, hy, hx⟩

theorem mem_component_self (W : I → Set G.DPath) (root : V) :
    root ∈ component W root :=
  Relation.ReflTransGen.refl

theorem component_trans {W : I → Set G.DPath} {x y z : V}
    (hxy : y ∈ component W x) (hyz : z ∈ component W y) :
    z ∈ component W x :=
  hxy.trans hyz

private theorem reflTransGen_symm_of_symm
    {α : Type u} {r : α → α → Prop}
    (hr : ∀ {x y}, r x y → r y x) {x y : α}
    (h : Relation.ReflTransGen r x y) : Relation.ReflTransGen r y x := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail hab hbc ih =>
      exact (Relation.ReflTransGen.single (hr hbc)).trans ih

theorem component_symm {W : I → Set G.DPath} {x y : V}
    (h : y ∈ component W x) : x ∈ component W y :=
  reflTransGen_symm_of_symm (fun {_ _} hxy ↦
    sameIndexedWarpPath_symm hxy) h

/-- A member of an indexed family is contained wholly in every component
which it touches. -/
theorem support_subset_component_of_touches
    {W : I → Set G.DPath} {i : I} {p : G.DPath} {root x : V}
    (hxroot : x ∈ component W root) (hp : p ∈ W i)
    (hxp : x ∈ p.support) : p.support ⊆ component W root := by
  intro y hyp
  exact hxroot.trans (Relation.ReflTransGen.single ⟨i, p, hp, hxp, hyp⟩)

/-- Vertices reachable in exactly `n` applications of a relation, with the
root in layer zero. -/
def reachLayer (r : V → V → Prop) (root : V) : ℕ → Set V
  | 0 => {root}
  | n + 1 => ⋃ x ∈ reachLayer r root n, {y | r x y}

private theorem mem_reachLayer_of_reflTransGen
    {r : V → V → Prop} {root x : V}
    (h : Relation.ReflTransGen r root x) :
    ∃ n, x ∈ reachLayer r root n := by
  induction h with
  | refl => exact ⟨0, by simp [reachLayer]⟩
  | @tail y z hxy hyz ih =>
      obtain ⟨n, hyn⟩ := ih
      refine ⟨n + 1, ?_⟩
      simp only [reachLayer, Set.mem_iUnion]
      exact ⟨y, hyn, hyz⟩

private theorem mk_iUnion_le_of_le {J X : Type u} {f : J → Set X}
    {kappa : Cardinal.{u}} (hkappa : aleph0 ≤ kappa)
    (hJ : #J ≤ kappa) (hf : ∀ j, #(f j) ≤ kappa) :
    #(⋃ j, f j) ≤ kappa := by
  refine (Cardinal.mk_iUnion_le f).trans ?_
  exact Cardinal.mul_le_of_le hkappa hJ (ciSup_le' hf)

/-- Generic finite-reachability estimate.  If every one-step neighborhood
has size at most an infinite cardinal, then every finite-path component has
size at most that cardinal. -/
theorem mk_reflTransGen_le_of_neighbors_le
    {r : V → V → Prop} {kappa : Cardinal.{u}}
    (hkappa : aleph0 ≤ kappa)
    (hneighbors : ∀ x, #({y | r x y} : Set V) ≤ kappa)
    (root : V) :
    #({x | Relation.ReflTransGen r root x} : Set V) ≤ kappa := by
  have hlayer : ∀ n, #(reachLayer r root n) ≤ kappa := by
    intro n
    induction n with
    | zero =>
        rw [reachLayer, Cardinal.mk_singleton]
        exact (one_le_aleph0.trans hkappa)
    | succ n ih =>
        refine (Cardinal.mk_biUnion_le
          (fun x : V ↦ {y | r x y}) (reachLayer r root n)).trans ?_
        exact Cardinal.mul_le_of_le hkappa ih (ciSup_le' fun x ↦
          hneighbors x.1)
  have hsub : {x | Relation.ReflTransGen r root x} ⊆
      ⋃ n, reachLayer r root n := by
    intro x hx
    obtain ⟨n, hxn⟩ := mem_reachLayer_of_reflTransGen hx
    exact Set.mem_iUnion.2 ⟨n, hxn⟩
  have hnat : Cardinal.mk (ULift.{u} ℕ) = aleph0 := by
    rw [Cardinal.mk_uLift, Cardinal.mk_nat, Cardinal.lift_aleph0]
  have hunion : (⋃ n, reachLayer r root n) =
      ⋃ n : ULift.{u} ℕ, reachLayer r root n.down := by
    ext x
    simp only [Set.mem_iUnion]
    constructor
    · rintro ⟨n, hxn⟩
      exact ⟨⟨n⟩, hxn⟩
    · rintro ⟨n, hxn⟩
      exact ⟨n.down, hxn⟩
  refine (Cardinal.mk_subtype_mono hsub).trans ?_
  rw [hunion]
  apply mk_iUnion_le_of_le hkappa (by rw [hnat]; exact hkappa)
  exact fun n ↦ hlayer n.down

/-- In an arbitrary warp, the vertices sharing a member with a fixed vertex
form a countable set.  Finite character is unnecessary here: a ray also has
countable support. -/
theorem sameWarpPath_neighbors_countable
    (W : Set G.DPath) (hW : G.IsWarp W) (x : V) :
    {y | AlternatingComponents.SameWarpPath W x y}.Countable := by
  by_cases hx : ∃ p ∈ W, x ∈ p.support
  · obtain ⟨p, hpW, hxp⟩ := hx
    refine p.support_countable.mono ?_
    intro y hy
    obtain ⟨q, hqW, hxq, hyq⟩ := hy
    have hqp : q = p :=
      Alternating.DWeb.IsWarp.eq_of_mem_support hW hqW hpW hxq hxp
    rwa [hqp] at hyq
  · have hempty :
        {y | AlternatingComponents.SameWarpPath W x y} = (∅ : Set V) := by
      ext y
      constructor
      · rintro ⟨p, hpW, hxp, _⟩
        exact (hx ⟨p, hpW, hxp⟩).elim
      · simp
    rw [hempty]
    exact Set.countable_empty

/-- The one-step neighborhood bound does not require finite character. -/
theorem mk_sameIndexedWarpPath_neighbors_le_general
    (W : I → Set G.DPath) (hW : ∀ i, G.IsWarp (W i)) (x : V) :
    #({y | SameIndexedWarpPath W x y} : Set V) ≤ max aleph0 #I := by
  have heq : {y | SameIndexedWarpPath W x y} =
      ⋃ i, {y | AlternatingComponents.SameWarpPath (W i) x y} := by
    ext y
    simp only [SameIndexedWarpPath, Set.mem_ofPred_eq, Set.mem_iUnion]
    constructor
    · rintro ⟨i, p, hp, hxp, hyp⟩
      exact ⟨i, p, hp, hxp, hyp⟩
    · rintro ⟨i, p, hp, hxp, hyp⟩
      exact ⟨i, p, hp, hxp, hyp⟩
  rw [heq]
  apply mk_iUnion_le_of_le (le_max_left aleph0 #I)
      (le_max_right aleph0 #I)
  intro i
  exact (sameWarpPath_neighbors_countable (W i) (hW i) x).le_aleph0.trans
    (le_max_left aleph0 #I)

/-- General indexed-warp component bound, allowing rays in the warps. -/
theorem mk_component_le_general
    (W : I → Set G.DPath) (hW : ∀ i, G.IsWarp (W i)) (root : V) :
    #(component W root) ≤ max aleph0 #I := by
  exact mk_reflTransGen_le_of_neighbors_le (le_max_left aleph0 #I)
    (mk_sameIndexedWarpPath_neighbors_le_general W hW) root

/-- The one-step neighborhood in an indexed family of finite-character
warps has cardinality at most `max aleph_0 #I`. -/
theorem mk_sameIndexedWarpPath_neighbors_le
    (W : I → Set G.DPath)
    (hW : ∀ i, G.IsWarp (W i))
    (hfinite : ∀ i, G.HasFiniteCharacter (W i)) (x : V) :
    #({y | SameIndexedWarpPath W x y} : Set V) ≤ max aleph0 #I := by
  have heq : {y | SameIndexedWarpPath W x y} =
      ⋃ i, {y | AlternatingComponents.SameWarpPath (W i) x y} := by
    ext y
    simp only [SameIndexedWarpPath, Set.mem_ofPred_eq, Set.mem_iUnion]
    constructor
    · rintro ⟨i, p, hp, hxp, hyp⟩
      exact ⟨i, p, hp, hxp, hyp⟩
    · rintro ⟨i, p, hp, hxp, hyp⟩
      exact ⟨i, p, hp, hxp, hyp⟩
  rw [heq]
  apply mk_iUnion_le_of_le (le_max_left aleph0 #I)
      (le_max_right aleph0 #I)
  intro i
  exact (AlternatingComponents.finite_sameWarpPath_neighbors
    (hW i) (hfinite i) x).countable.le_aleph0.trans
      (le_max_left aleph0 #I)

/-- A component generated by `I` many finite-character warps has size at
most `max aleph_0 #I`. -/
theorem mk_component_le
    (W : I → Set G.DPath)
    (hW : ∀ i, G.IsWarp (W i))
    (hfinite : ∀ i, G.HasFiniteCharacter (W i)) (root : V) :
    #(component W root) ≤ max aleph0 #I := by
  exact mk_reflTransGen_le_of_neighbors_le (le_max_left aleph0 #I)
    (mk_sameIndexedWarpPath_neighbors_le W hW hfinite) root

/-- For a countable indexed family, every generated component is
countable. -/
theorem component_countable
    (W : I → Set G.DPath)
    (hW : ∀ i, G.IsWarp (W i))
    (hfinite : ∀ i, G.HasFiniteCharacter (W i))
    (hI : #I ≤ aleph0) (root : V) :
    (component W root).Countable := by
  rw [← Cardinal.le_aleph0_iff_set_countable]
  exact (mk_component_le W hW hfinite root).trans (max_le le_rfl hI)

/-- Countable specialization for arbitrary indexed warps, including rays. -/
theorem component_countable_general
    (W : I → Set G.DPath) (hW : ∀ i, G.IsWarp (W i))
    (hI : #I ≤ aleph0) (root : V) :
    (component W root).Countable := by
  rw [← Cardinal.le_aleph0_iff_set_countable]
  exact (mk_component_le_general W hW root).trans (max_le le_rfl hI)

#print axioms mk_reflTransGen_le_of_neighbors_le
#print axioms sameWarpPath_neighbors_countable
#print axioms mk_component_le_general
#print axioms mk_sameIndexedWarpPath_neighbors_le
#print axioms mk_component_le
#print axioms component_countable
#print axioms component_countable_general

end IndexedWarpComponents
end Erdos599
