/-
Copyright (c) 2026 The lean-proofs contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-proofs contributors
-/

import ErdosProblems.Erdos599.SliceAuxiliaryCore
import ErdosProblems.Erdos599.RegularSliceComponentClosure

/-!
# Ordinary linkages in the regular-slice auxiliary web

The regular slice argument first constructs, for every nonexceptional
half-way terminal, a concrete finite path in the quotient/retarget web.
This file packages that pathwise construction and proves once and for all
that its range is the exact complementary-source linkage consumed by
`RegularSliceStageCompletion`.

Keeping the realization indexed by `C \ E` is useful in the component
argument: coverage and injectivity are then definitionally source-faithful,
while disjointness and the two boundary-purity statements are discharged
componentwise.
-/

noncomputable section

open Cardinal Set

namespace Erdos599
namespace CardinalInduction
namespace RegularAuxiliaryOrdinaryLinkage

open DirectedPath

universe u

variable {V : Type u}

/-! ## The small exceptional terminal set -/

/-- Half-way terminals lying in an alternating component generated by the
bad seed.  These are precisely the terminals withheld from the ordinary
auxiliary linkage. -/
def exceptionalTerminals
    (Q : DWeb V) (W Y : Set Q.DPath) (C bad : Set V) : Set V :=
  C ∩ RegularSliceComponentClosure.seededComponentClosure W Y bad

theorem exceptionalTerminals_subset
    (Q : DWeb V) (W Y : Set Q.DPath) (C bad : Set V) :
    exceptionalTerminals Q W Y C bad ⊆ C :=
  Set.inter_subset_left

/-- Closing fewer than `kappa` bad vertices under the countable alternating
components of two finite-character warps still withholds fewer than
`kappa` half-way terminals. -/
theorem mk_exceptionalTerminals_lt
    {kappa : Cardinal.{u}} (hkappa : kappa.IsRegular)
    (huncountable : Cardinal.aleph0 < kappa)
    {Q : DWeb V} {W Y : Set Q.DPath} {C bad : Set V}
    (hW : Q.IsWarp W) (hY : Q.IsWarp Y)
    (hWfinite : Q.HasFiniteCharacter W)
    (hYfinite : Q.HasFiniteCharacter Y)
    (hbad : #bad < kappa) :
    #(exceptionalTerminals Q W Y C bad) < kappa := by
  exact (Cardinal.mk_subtype_mono Set.inter_subset_right).trans_lt
    (RegularSliceComponentClosure.mk_seededComponentClosure_lt
      hkappa huncountable hW hY hWfinite hYfinite hbad)

/-! ## Source-faithful component replacement

The source proof does **not** keep the original stop-over as the terminal
frontier of the half-way warp.  On an ordinary alternating component it
replaces the old member by the prefix of the later path ending at its last
visit to the old stop-over.  The corresponding suffix then survives the
quotient by the old stop-over. -/

/-- The prefix of `p` ending at the vertex at which its last `C`-suffix
starts.  Simplicity of `p` makes the first visit to this singleton the
unique visit, hence this really is the complementary prefix. -/
noncomputable def lastHitPrefix
    {D : Digraph V} (p : DirectedPath.FinitePath D) (C : Set V)
    (hC : p.walk.Meets C) : DirectedPath.FinitePath D :=
  let q := p.lastHit C hC
  p.firstHit {q.start}
    ⟨q.start, p.lastHit_support_subset C hC q.start_mem_support,
      Set.mem_singleton q.start⟩

@[simp] theorem lastHitPrefix_start
    {D : Digraph V} (p : DirectedPath.FinitePath D) (C : Set V)
    (hC : p.walk.Meets C) :
    (lastHitPrefix p C hC).start = p.start := by
  rfl

@[simp] theorem lastHitPrefix_finish
    {D : Digraph V} (p : DirectedPath.FinitePath D) (C : Set V)
    (hC : p.walk.Meets C) :
    (lastHitPrefix p C hC).finish = (p.lastHit C hC).start := by
  exact Set.mem_singleton_iff.mp
    (DirectedPath.FinitePath.firstHit_finish_mem _ _ _)

theorem lastHitPrefix_finish_mem
    {D : Digraph V} (p : DirectedPath.FinitePath D) (C : Set V)
    (hC : p.walk.Meets C) :
    (lastHitPrefix p C hC).finish ∈ C := by
  rw [lastHitPrefix_finish]
  exact p.lastHit_start_mem C hC

theorem lastHitPrefix_support_subset
    {D : Digraph V} (p : DirectedPath.FinitePath D) (C : Set V)
    (hC : p.walk.Meets C) :
    (lastHitPrefix p C hC).support ⊆ p.support :=
  DirectedPath.FinitePath.firstHit_support_subset _ _ _

/-- Abstract stage-local input for the replacement.  In the canonical
application `ordinary` is obtained by lowering the survivor interval
realization from the ambient ladder to the earlier stage web. -/
structure OrdinaryInput (Q : DWeb V) (A C T S : Set V) where
  Y : Set Q.DPath
  isWarp : Q.IsWarp Y
  ordinary : SliceSegmentCore.SegmentRealization Q Y A T S
  segment_mem : ∀ x, (Sum.inl (ordinary.segment x) : Q.DPath) ∈ Y
  separates : RelationalRoof.Separates Q.graph.Adj A T C

namespace OrdinaryInput

variable {Q : DWeb V} {A C T S : Set V}

/-- Every ordinary interval meets the old stop-over. -/
theorem segment_meets (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinary.segment x).walk.Meets C := by
  apply I.separates (I.ordinary.segment x).walk
  · rw [I.ordinary.segment_start x]
    exact I.ordinary.source_subset x.2
  · exact I.ordinary.segment_finish_mem x

/-- Last-stop-over prefix of an ordinary interval. -/
noncomputable def ordinaryPrefix (I : OrdinaryInput Q A C T S) (x : S) :
    DirectedPath.FinitePath Q.graph :=
  lastHitPrefix (I.ordinary.segment x) C (I.segment_meets x)

/-- Matching suffix, beginning at the same last stop-over vertex. -/
noncomputable def ordinarySuffix (I : OrdinaryInput Q A C T S) (x : S) :
    DirectedPath.FinitePath Q.graph :=
  (I.ordinary.segment x).lastHit C (I.segment_meets x)

@[simp] theorem ordinaryPrefix_start (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinaryPrefix x).start = x.1 := by
  rw [ordinaryPrefix, lastHitPrefix_start, I.ordinary.segment_start]

@[simp] theorem ordinaryPrefix_finish_eq_ordinarySuffix_start
    (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinaryPrefix x).finish = (I.ordinarySuffix x).start := by
  exact lastHitPrefix_finish _ _ _

theorem ordinaryPrefix_finish_mem (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinaryPrefix x).finish ∈ C :=
  lastHitPrefix_finish_mem _ _ _

@[simp] theorem ordinarySuffix_finish (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinarySuffix x).finish = (I.ordinary.segment x).finish := rfl

theorem ordinaryPrefix_support_subset (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinaryPrefix x).support ⊆ (I.ordinary.segment x).support :=
  lastHitPrefix_support_subset _ _ _

theorem ordinarySuffix_support_subset (I : OrdinaryInput Q A C T S) (x : S) :
    (I.ordinarySuffix x).support ⊆ (I.ordinary.segment x).support :=
  DirectedPath.FinitePath.lastHit_support_subset _ _ _

end OrdinaryInput

private theorem exists_linkageMemberAt
    {Q : DWeb V} {A C : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (x : A) :
    ∃ p ∈ W, p.initial = x.1 := by
  have hx : x.1 ∈ Q.initialSet W := hW.initialSet_eq.symm ▸ x.2
  exact hx

/-- The path of a source-faithful linkage beginning at a prescribed source. -/
noncomputable def linkageMemberAt
    {Q : DWeb V} {A C : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (x : A) : W :=
  ⟨Classical.choose (exists_linkageMemberAt hW x),
    (Classical.choose_spec (exists_linkageMemberAt hW x)).1⟩

@[simp] theorem linkageMemberAt_initial
    {Q : DWeb V} {A C : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (x : A) :
    (linkageMemberAt hW x).1.initial = x.1 :=
  (Classical.choose_spec (exists_linkageMemberAt hW x)).2

/-- Chosen finite representative of the linkage member at `x`. -/
noncomputable def linkageFiniteAt
    {Q : DWeb V} {A C : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (x : A) :
    DirectedPath.FinitePath Q.graph :=
  SliceAuxiliaryCore.linkageFinitePath hW (linkageMemberAt hW x)

@[simp] theorem linkageFiniteAt_start
    {Q : DWeb V} {A C : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (x : A) :
    (linkageFiniteAt hW x).start = x.1 := by
  rw [linkageFiniteAt, SliceAuxiliaryCore.linkageFinitePath_start,
    linkageMemberAt_initial]

theorem linkageFiniteAt_support
    {Q : DWeb V} {A C : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (x : A) :
    (linkageFiniteAt hW x).support = (linkageMemberAt hW x).1.support := by
  have h := congrArg DirectedPath.Path.support
    (SliceAuxiliaryCore.linkageFinitePath_spec hW (linkageMemberAt hW x))
  exact h.symm

/-- Seeds of the components which must retain the old half-way member. -/
def replacementSeed
    (Q : DWeb V) {A C T S : Set V} (W : Set Q.DPath)
    (I : OrdinaryInput Q A C T S) (K : Set Q.DPath) : Set V :=
  Q.vertexSet K ∪ (A \ S)

/-- Alternating-component closure of the retained seeds. -/
def replacementClosure
    (Q : DWeb V) {A C T S : Set V} (W : Set Q.DPath)
    (I : OrdinaryInput Q A C T S) (K : Set Q.DPath) : Set V :=
  RegularSliceComponentClosure.seededComponentClosure W I.Y
    (replacementSeed Q W I K)

theorem replacementSeed_subset_closure
    (Q : DWeb V) {A C T S : Set V} (W : Set Q.DPath)
    (I : OrdinaryInput Q A C T S) (K : Set Q.DPath) :
    replacementSeed Q W I K ⊆ replacementClosure Q W I K := by
  intro x hx
  exact Set.mem_iUnion.2 ⟨x, Set.mem_iUnion.2 ⟨hx,
    AlternatingComponents.mem_component_self W I.Y x⟩⟩

/-- Every source outside the exceptional closure is an ordinary source. -/
theorem ordinary_of_not_mem_replacementClosure
    (Q : DWeb V) {A C T S : Set V} (W : Set Q.DPath)
    (I : OrdinaryInput Q A C T S) (K : Set Q.DPath)
    {x : V} (hxA : x ∈ A) (hxD : x ∉ replacementClosure Q W I K) :
    x ∈ S := by
  by_contra hxS
  exact hxD (replacementSeed_subset_closure Q W I K
    (Or.inr ⟨hxA, hxS⟩))

/-- Source-indexed component replacement.  Sources in the exceptional
closure retain their old half-way member; every other source takes the
last-`C` prefix of its ordinary later-stage interval. -/
noncomputable def replacedPath
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x : A) : DirectedPath.FinitePath Q.graph := by
  classical
  by_cases hx : x.1 ∈ replacementClosure Q W I K
  · exact linkageFiniteAt hW x
  · exact I.ordinaryPrefix ⟨x.1,
      ordinary_of_not_mem_replacementClosure Q W I K x.2 hx⟩

@[simp] theorem replacedPath_start
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x : A) :
    (replacedPath hW I K x).start = x.1 := by
  classical
  unfold replacedPath
  split
  · exact linkageFiniteAt_start hW x
  · exact I.ordinaryPrefix_start _

/-- The replaced half-way family and its honest new terminal frontier. -/
def replacedFamily
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) : Set Q.DPath :=
  Set.range fun x : A ↦ (Sum.inl (replacedPath hW I K x) : Q.DPath)

def replacedFrontier
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) : Set V :=
  Q.terminalFrontier (replacedFamily hW I K)

/-- Terminals of the retained old components. -/
def retainedTerminals
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) : Set V :=
  replacedFrontier hW I K ∩ replacementClosure Q W I K

private theorem left_support_subset_replacementClosure
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (I : OrdinaryInput Q A C T S) (K : Set Q.DPath)
    {p : DirectedPath.FinitePath Q.graph}
    (hp : (Sum.inl p : Q.DPath) ∈ W)
    {x : V} (hx : x ∈ replacementClosure Q W I K)
    (hxp : x ∈ p.support) :
    p.support ⊆ replacementClosure Q W I K := by
  intro y hyp
  simp only [replacementClosure,
    RegularSliceComponentClosure.seededComponentClosure,
    Set.mem_iUnion] at hx ⊢
  obtain ⟨root, hroot, hxroot⟩ := hx
  exact ⟨root, hroot,
    hxroot.trans
      (AlternatingComponents.finitePath_support_subset_component_left
        (Y := I.Y) hp hxp hyp)⟩

private theorem right_support_subset_replacementClosure
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (I : OrdinaryInput Q A C T S) (K : Set Q.DPath)
    {p : DirectedPath.FinitePath Q.graph}
    (hp : (Sum.inl p : Q.DPath) ∈ I.Y)
    {x : V} (hx : x ∈ replacementClosure Q W I K)
    (hxp : x ∈ p.support) :
    p.support ⊆ replacementClosure Q W I K := by
  intro y hyp
  simp only [replacementClosure,
    RegularSliceComponentClosure.seededComponentClosure,
    Set.mem_iUnion] at hx ⊢
  obtain ⟨root, hroot, hxroot⟩ := hx
  exact ⟨root, hroot,
    hxroot.trans
      (AlternatingComponents.finitePath_support_subset_component_right
        (Z := W) hp hxp hyp)⟩

theorem replacedPath_finish_mem
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x : A) :
    (replacedPath hW I K x).finish ∈ C := by
  classical
  unfold replacedPath
  split
  next hx =>
    apply hW.terminalFrontier_subset
    refine ⟨(linkageMemberAt hW x).1, (linkageMemberAt hW x).2, ?_⟩
    rw [SliceAuxiliaryCore.linkageFinitePath_spec]
    rfl
  next hx => exact I.ordinaryPrefix_finish_mem _

theorem replacedPath_source_pure
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x : A) :
    (replacedPath hW I K x).support ∩ A =
      {(replacedPath hW I K x).start} := by
  classical
  unfold replacedPath
  split
  next hx =>
    obtain ⟨p, hp, _hend, hsource⟩ :=
      hW.endpointPure (linkageMemberAt hW x).1
        (linkageMemberAt hW x).2
    have hp' : p = linkageFiniteAt hW x := by
      apply Sum.inl.inj
      exact hp.symm.trans
        (SliceAuxiliaryCore.linkageFinitePath_spec hW
          (linkageMemberAt hW x))
    simpa only [hp'] using hsource
  next hx =>
    let z : S := ⟨x.1,
      ordinary_of_not_mem_replacementClosure Q W I K x.2 hx⟩
    apply Set.Subset.antisymm
    · rintro y ⟨hy, hyA⟩
      have hy' : y ∈ (I.ordinary.segment z).support ∩ A :=
        ⟨I.ordinaryPrefix_support_subset z hy, hyA⟩
      rw [I.ordinary.segment_source z] at hy'
      exact Set.mem_singleton_iff.mpr
        (calc
          y = (I.ordinary.segment z).start := Set.mem_singleton_iff.mp hy'
          _ = z.1 := I.ordinary.segment_start z
          _ = (I.ordinaryPrefix z).start :=
            (I.ordinaryPrefix_start z).symm)
    · rintro y hy
      have hys : y = (I.ordinaryPrefix z).start := Set.mem_singleton_iff.mp hy
      subst y
      refine ⟨(I.ordinaryPrefix z).start_mem_support, ?_⟩
      rw [I.ordinaryPrefix_start z]
      exact x.2

private theorem retained_ordinary_disjoint
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x y : A)
    (hx : x.1 ∈ replacementClosure Q W I K)
    (hy : y.1 ∉ replacementClosure Q W I K) :
    Disjoint (linkageFiniteAt hW x).support
      (I.ordinaryPrefix
        ⟨y.1, ordinary_of_not_mem_replacementClosure Q W I K y.2 hy⟩).support := by
  let z : S := ⟨y.1,
    ordinary_of_not_mem_replacementClosure Q W I K y.2 hy⟩
  have hpW : (Sum.inl (linkageFiniteAt hW x) : Q.DPath) ∈ W := by
    unfold linkageFiniteAt
    rw [← SliceAuxiliaryCore.linkageFinitePath_spec hW
      (linkageMemberAt hW x)]
    exact (linkageMemberAt hW x).2
  have hleft : (linkageFiniteAt hW x).support ⊆
      replacementClosure Q W I K :=
    left_support_subset_replacementClosure I K hpW hx
      (linkageFiniteAt_start hW x ▸
        (linkageFiniteAt hW x).start_mem_support)
  apply Set.disjoint_left.2
  intro v hvOld hvOrd
  have hvD : v ∈ replacementClosure Q W I K := hleft hvOld
  have hvSegment : v ∈ (I.ordinary.segment z).support :=
    I.ordinaryPrefix_support_subset z hvOrd
  have hright : (I.ordinary.segment z).support ⊆
      replacementClosure Q W I K := by
    exact right_support_subset_replacementClosure I K
      (I.segment_mem z) hvD hvSegment
  apply hy
  apply hright
  have hs := (I.ordinary.segment z).start_mem_support
  simpa only [I.ordinary.segment_start z] using hs

theorem replacedPath_pairwise_disjoint
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x y : A) (hxy : x ≠ y) :
    Disjoint (replacedPath hW I K x).support
      (replacedPath hW I K y).support := by
  classical
  by_cases hx : x.1 ∈ replacementClosure Q W I K
  · by_cases hy : y.1 ∈ replacementClosure Q W I K
    · have hmembers : (linkageMemberAt hW x).1 ≠
          (linkageMemberAt hW y).1 := by
        intro h
        apply hxy
        apply Subtype.ext
        calc
          x.1 = (linkageMemberAt hW x).1.initial :=
            (linkageMemberAt_initial hW x).symm
          _ = (linkageMemberAt hW y).1.initial := congrArg _ h
          _ = y.1 := linkageMemberAt_initial hW y
      have hd := hW.isWarp (linkageMemberAt hW x).2
        (linkageMemberAt hW y).2 hmembers
      rw [replacedPath, dif_pos hx, replacedPath, dif_pos hy]
      exact hd.mono
        (linkageFiniteAt_support hW x).le
        (linkageFiniteAt_support hW y).le
    · rw [replacedPath, dif_pos hx, replacedPath, dif_neg hy]
      exact retained_ordinary_disjoint hW I K x y hx hy
  · by_cases hy : y.1 ∈ replacementClosure Q W I K
    · rw [replacedPath, dif_neg hx, replacedPath, dif_pos hy]
      exact (retained_ordinary_disjoint hW I K y x hy hx).symm
    · let zx : S := ⟨x.1,
          ordinary_of_not_mem_replacementClosure Q W I K x.2 hx⟩
      let zy : S := ⟨y.1,
          ordinary_of_not_mem_replacementClosure Q W I K y.2 hy⟩
      have hz : zx ≠ zy := by
        intro h
        apply hxy
        have hv : x.1 = y.1 := congrArg (fun z : S ↦ z.1) h
        exact Subtype.ext hv
      have hc : (Sum.inl (I.ordinary.segment zx) : Q.DPath) ≠
          Sum.inl (I.ordinary.segment zy) := by
        intro h
        apply hxy
        apply Subtype.ext
        have hs : (I.ordinary.segment zx).start =
            (I.ordinary.segment zy).start :=
          congrArg DirectedPath.FinitePath.start (Sum.inl.inj h)
        exact (I.ordinary.segment_start zx).symm.trans
          (hs.trans (I.ordinary.segment_start zy))
      rw [replacedPath, dif_neg hx, replacedPath, dif_neg hy]
      exact (I.isWarp (I.segment_mem zx) (I.segment_mem zy) hc).mono
        (I.ordinaryPrefix_support_subset zx)
        (I.ordinaryPrefix_support_subset zy)

@[simp] theorem mem_replacedFrontier_iff
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    {hW : IsLinkageBetween Q A C W} {I : OrdinaryInput Q A C T S}
    {K : Set Q.DPath} {v : V} :
    v ∈ replacedFrontier hW I K ↔
      ∃ x : A, (replacedPath hW I K x).finish = v := by
  constructor
  · rintro ⟨p, ⟨x, rfl⟩, hp⟩
    exact ⟨x, Option.some.inj hp⟩
  · rintro ⟨x, rfl⟩
    exact ⟨Sum.inl (replacedPath hW I K x), ⟨x, rfl⟩, rfl⟩

theorem replacedFrontier_subset
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) : replacedFrontier hW I K ⊆ C := by
  intro v hv
  rw [mem_replacedFrontier_iff] at hv
  obtain ⟨x, rfl⟩ := hv
  exact replacedPath_finish_mem hW I K x

theorem replacedPath_terminal_pure
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) (x : A) :
    (replacedPath hW I K x).support ∩ replacedFrontier hW I K =
      {(replacedPath hW I K x).finish} := by
  apply Set.Subset.antisymm
  · rintro v ⟨hv, hvfrontier⟩
    rw [mem_replacedFrontier_iff] at hvfrontier
    obtain ⟨z, hz⟩ := hvfrontier
    apply Set.mem_singleton_iff.mpr
    by_cases hxz : x = z
    · subst z
      exact hz.symm
    · exact False.elim (Set.disjoint_left.1
        (replacedPath_pairwise_disjoint hW I K x z hxz) hv
        (hz ▸ (replacedPath hW I K z).finish_mem_support))
  · intro v hv
    have hv' : v = (replacedPath hW I K x).finish :=
      Set.mem_singleton_iff.mp hv
    subst v
    refine ⟨(replacedPath hW I K x).finish_mem_support, ?_⟩
    rw [mem_replacedFrontier_iff]
    exact ⟨x, rfl⟩

theorem replacedFamily_isLinkageBetween
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) :
    IsLinkageBetween Q A (replacedFrontier hW I K)
      (replacedFamily hW I K) := by
  refine ⟨?_, ?_, ?_, Set.Subset.rfl, ?_⟩
  · rintro p ⟨x, rfl⟩ q ⟨y, rfl⟩ hpq
    apply replacedPath_pairwise_disjoint hW I K x y
    intro hxy
    subst y
    exact hpq rfl
  · rintro p ⟨x, rfl⟩
    exact ⟨replacedPath hW I K x, rfl⟩
  · ext v
    constructor
    · rintro ⟨p, ⟨x, rfl⟩, hp⟩
      exact (replacedPath_start hW I K x).symm.trans hp ▸ x.2
    · intro hv
      let x : A := ⟨v, hv⟩
      exact ⟨Sum.inl (replacedPath hW I K x), ⟨x, rfl⟩,
        replacedPath_start hW I K x⟩
  · rintro p ⟨x, rfl⟩
    refine ⟨replacedPath hW I K x, rfl, ?_,
      replacedPath_source_pure hW I K x⟩
    rw [Set.inter_union_distrib_left,
      replacedPath_source_pure hW I K x,
      replacedPath_terminal_pure hW I K x]
    rfl

theorem replacedFamily_terminalFrontier_eq
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) :
    Q.terminalFrontier (replacedFamily hW I K) =
      replacedFrontier hW I K := rfl

theorem replacedFamily_terminalClean
    {Q : DWeb V} {A C T S : Set V} {W : Set Q.DPath}
    (hW : IsLinkageBetween Q A C W) (I : OrdinaryInput Q A C T S)
    (K : Set Q.DPath) :
    SliceSpliceSource.MeetsOnlyAtTerminal Q (replacedFamily hW I K)
      (replacedFrontier hW I K) := by
  rintro p ⟨x, rfl⟩ v hv hvC
  have h : v ∈ (replacedPath hW I K x).support ∩
      replacedFrontier hW I K := ⟨hv, hvC⟩
  rw [replacedPath_terminal_pure hW I K x] at h
  change some (replacedPath hW I K x).finish = some v
  exact congrArg some (Set.mem_singleton_iff.mp h).symm

/-- The seed for component replacement is small when both the retained
subfamily and the set of nonsurviving sources are small. -/
theorem mk_replacementSeed_lt
    {kappa : Cardinal.{u}} (hkappa : kappa.IsRegular)
    {Q : DWeb V} {A C T S : Set V} {W K : Set Q.DPath}
    (I : OrdinaryInput Q A C T S)
    (hW : IsLinkageBetween Q A C W)
    (hKsub : K ⊆ W) (hKsmall : #K < kappa)
    (hbad : #(↑(A \ S)) < kappa) :
    #(replacementSeed Q W I K) < kappa := by
  have hKvertices : #(Q.vertexSet K) < kappa :=
    ControlledSlices.mk_vertexSet_exceptional_lt Q hkappa hKsub hKsmall
      hW.finiteCharacter
  exact RegularCardinal.mk_union_lt hkappa hKvertices hbad

/-- Consequently only fewer than `kappa` terminals of the honest
replacement frontier belong to retained components. -/
theorem mk_retainedTerminals_lt
    {kappa : Cardinal.{u}} (hkappa : kappa.IsRegular)
    (huncountable : Cardinal.aleph0 < kappa)
    {Q : DWeb V} {A C T S : Set V} {W K : Set Q.DPath}
    (I : OrdinaryInput Q A C T S)
    (hW : IsLinkageBetween Q A C W)
    (hIfinite : Q.HasFiniteCharacter I.Y)
    (hKsub : K ⊆ W) (hKsmall : #K < kappa)
    (hbad : #(↑(A \ S)) < kappa) :
    #(retainedTerminals hW I K) < kappa := by
  apply (Cardinal.mk_subtype_mono Set.inter_subset_right).trans_lt
  exact RegularSliceComponentClosure.mk_seededComponentClosure_lt
    hkappa huncountable hW.isWarp I.isWarp hW.finiteCharacter hIfinite
      (mk_replacementSeed_lt hkappa I hW hKsub hKsmall hbad)

/-- Pathwise output of the ordinary alternating-component construction.
The paths already live in the quotient/retarget auxiliary web. -/
structure Realization (Q : DWeb V) (C T E : Set V) where
  path : ↑(C \ E) →
    DirectedPath.FinitePath
      (SliceAuxiliaryCore.auxiliaryWeb Q C T).graph
  path_start : ∀ x, (path x).start = x.1
  path_finish : ∀ x, (path x).finish ∈ T
  endpoint_pure : ∀ x,
    (path x).support ∩ ((C \ E) ∪ T) =
      {(path x).start, (path x).finish}
  source_pure : ∀ x,
    (path x).support ∩ (C \ E) = {(path x).start}
  pairwise_disjoint : ∀ x y, x ≠ y →
    Disjoint (path x).support (path y).support

/-- The family realized by the nonexceptional half-way terminals. -/
def family {Q : DWeb V} {C T E : Set V}
    (R : Realization Q C T E) :
    Set (SliceAuxiliaryCore.auxiliaryWeb Q C T).DPath :=
  Set.range fun x : ↑(C \ E) ↦
    (Sum.inl (R.path x) :
      (SliceAuxiliaryCore.auxiliaryWeb Q C T).DPath)

@[simp]
theorem mem_family_iff {Q : DWeb V} {C T E : Set V}
    {R : Realization Q C T E}
    {p : (SliceAuxiliaryCore.auxiliaryWeb Q C T).DPath} :
    p ∈ family R ↔
      ∃ x : ↑(C \ E),
        p = (Sum.inl (R.path x) :
          (SliceAuxiliaryCore.auxiliaryWeb Q C T).DPath) := by
  constructor
  · rintro ⟨x, rfl⟩
    exact ⟨x, rfl⟩
  · rintro ⟨x, rfl⟩
    exact ⟨x, rfl⟩

theorem family_isWarp {Q : DWeb V} {C T E : Set V}
    (R : Realization Q C T E) :
    (SliceAuxiliaryCore.auxiliaryWeb Q C T).IsWarp (family R) := by
  rintro p ⟨x, rfl⟩ q ⟨y, rfl⟩ hpq
  apply R.pairwise_disjoint x y
  intro hxy
  subst y
  exact hpq rfl

theorem family_hasFiniteCharacter {Q : DWeb V} {C T E : Set V}
    (R : Realization Q C T E) :
    (SliceAuxiliaryCore.auxiliaryWeb Q C T).HasFiniteCharacter
      (family R) := by
  rintro p ⟨x, rfl⟩
  exact ⟨R.path x, rfl⟩

@[simp]
theorem family_initialSet {Q : DWeb V} {C T E : Set V}
    (R : Realization Q C T E) :
    (SliceAuxiliaryCore.auxiliaryWeb Q C T).initialSet (family R) =
      C \ E := by
  ext v
  constructor
  · rintro ⟨p, ⟨x, rfl⟩, hp⟩
    change (R.path x).start = v at hp
    exact (R.path_start x).symm.trans hp ▸ x.2
  · intro hv
    let x : ↑(C \ E) := ⟨v, hv⟩
    refine ⟨(Sum.inl (R.path x) :
      (SliceAuxiliaryCore.auxiliaryWeb Q C T).DPath),
      ⟨x, rfl⟩, ?_⟩
    exact R.path_start x

theorem family_terminalFrontier_subset {Q : DWeb V} {C T E : Set V}
    (R : Realization Q C T E) :
    (SliceAuxiliaryCore.auxiliaryWeb Q C T).terminalFrontier
      (family R) ⊆ T := by
  rintro v ⟨p, ⟨x, rfl⟩, hp⟩
  change some (R.path x).finish = some v at hp
  exact Option.some.inj hp ▸ R.path_finish x

/-- A pathwise ordinary realization is exactly the complementary-source
linkage required by the lower-cardinal completion step. -/
theorem isLinkageBetween_family
    {Q : DWeb V} {C T E : Set V}
    (R : Realization Q C T E) :
    IsLinkageBetween (SliceAuxiliaryCore.auxiliaryWeb Q C T)
      (C \ E) T (family R) := by
  refine ⟨family_isWarp R, family_hasFiniteCharacter R,
    family_initialSet R, family_terminalFrontier_subset R, ?_⟩
  rintro p ⟨x, rfl⟩
  exact ⟨R.path x, rfl, R.endpoint_pure x, R.source_pure x⟩

/-- The same result with the auxiliary web's source written explicitly.
This is the literal form expected by
`exists_tightAnnularAmbientLinkage_of_halfwayPayload_lower`. -/
theorem isLinkageBetween_auxiliary_source_sdiff
    {Q : DWeb V} {C T E : Set V}
    (hsep : IsSeparatorFrom Q Q.source C)
    (htrim : IsTrimmedSeparator Q C)
    (R : Realization Q C T E) :
    IsLinkageBetween (SliceAuxiliaryCore.auxiliaryWeb Q C T)
      ((SliceAuxiliaryCore.auxiliaryWeb Q C T).source \ E)
      (SliceAuxiliaryCore.auxiliaryWeb Q C T).target (family R) := by
  simpa only [SliceAuxiliaryCore.auxiliaryWeb_target,
    SliceAuxiliaryCore.auxiliaryWeb_source_eq_stopover Q hsep htrim]
    using isLinkageBetween_family R

end RegularAuxiliaryOrdinaryLinkage
end CardinalInduction
end Erdos599
