/-
Copyright (c) 2026 The lean-proofs contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-proofs contributors
-/

import ErdosProblems.Erdos599.AlternatingComponents
import ErdosProblems.Erdos599.SliceSpliceSource

/-!
# Small closures under alternating components

This file isolates the cardinal estimate used in the regular-cardinal
slice construction.  The union of the alternating components generated by
fewer than `kappa` seed vertices is still smaller than `kappa`: every one
of those components is countable, and `kappa` is regular and uncountable.

The second estimate records the form needed by a slice.  Restrict a linkage
to paths whose initial vertices lie both on a prescribed frontier and in
the component closure.  Initial vertices distinguish members of a warp, so
the restricted linkage has cardinality at most the component closure and is
therefore smaller than `kappa`.
-/

noncomputable section

open Cardinal Set

namespace Erdos599
namespace RegularSliceComponentClosure

open CardinalInduction
open CardinalInduction.SliceSpliceSource

universe u

variable {V : Type u} {Gamma : DWeb V}

/-- The union of all alternating components of two path families which meet
the seed set `S`. -/
def seededComponentClosure (T Y : Set Gamma.DPath) (S : Set V) : Set V :=
  ⋃ x ∈ S, AlternatingComponents.component T Y x

/-- Fewer than `kappa` countable alternating components have union smaller
than the uncountable regular cardinal `kappa`. -/
theorem mk_seededComponentClosure_lt
    {kappa : Cardinal.{u}} (hkappa : kappa.IsRegular)
    (hkappaUncountable : ℵ₀ < kappa)
    {T Y : Set Gamma.DPath} (hT : Gamma.IsWarp T)
    (hY : Gamma.IsWarp Y) (hTfinite : Gamma.HasFiniteCharacter T)
    (hYfinite : Gamma.HasFiniteCharacter Y) {S : Set V}
    (hS : #S < kappa) :
    #(seededComponentClosure T Y S) < kappa := by
  apply FamilyTools.mk_biUnion_lt_of_isRegular hkappa hS
  intro x _hx
  exact (AlternatingComponents.component_countable hT hY hTfinite hYfinite x).le_aleph0.trans_lt
    hkappaUncountable

/-- In a warp, restricting to members whose initials belong to a small set
produces a small subfamily.  The proof chooses the initial vertex in the
support of each member. -/
theorem mk_initialRestriction_lt_of_isWarp
    {kappa : Cardinal.{u}} {W : Set Gamma.DPath} (hW : Gamma.IsWarp W)
    {A : Set V} (hA : #A < kappa) :
    #(initialRestriction Gamma W A) < kappa := by
  refine (FamilyTools.mk_le_of_pairwiseDisjoint_of_meets
    (I := initialRestriction Gamma W A)
    (F := fun p : Gamma.DPath ↦ p.support) (S := A) ?_ ?_).trans_lt hA
  · exact hW.subset fun _ hp ↦ hp.1
  · intro p hp
    exact ⟨p.initial, hp.2, p.initial_mem_support⟩

/-- Let `T` be a linkage and `Y` a second finite-character warp.  If `S`
has size below an uncountable regular cardinal `kappa`, then the part of
`T` whose initial vertices lie on `frontier` and in the alternating
component closure of `S` also has size below `kappa`. -/
theorem mk_initialRestriction_frontier_componentClosure_lt
    {kappa : Cardinal.{u}} (hkappa : kappa.IsRegular)
    (hkappaUncountable : ℵ₀ < kappa)
    {A B frontier S : Set V} {T Y : Set Gamma.DPath}
    (hT : IsLinkageBetween Gamma A B T)
    (hY : Gamma.IsWarp Y) (hYfinite : Gamma.HasFiniteCharacter Y)
    (hS : #S < kappa) :
    #(initialRestriction Gamma T
        (frontier ∩ seededComponentClosure T Y S)) < kappa := by
  apply mk_initialRestriction_lt_of_isWarp hT.isWarp
  exact (Cardinal.mk_subtype_mono Set.inter_subset_right).trans_lt
    (mk_seededComponentClosure_lt hkappa hkappaUncountable hT.isWarp hY
      hT.finiteCharacter hYfinite hS)

end RegularSliceComponentClosure
end Erdos599

