/-
Copyright (c) 2026 The lean-proofs contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The lean-proofs contributors
-/

import ErdosProblems.Erdos599.IndexedWarpComponents
import ErdosProblems.Erdos599.SliceSpliceSource
import ErdosProblems.Erdos599.SingularRetargetedRow

/-!
# Bounded components generated by cofinal linkage rows

A singular source can be covered by a family of lower-cardinality linkage
rows indexed by its cofinality.  The union of the row carriers need not be a
warp, but its common-path components are small.  This file packages the
precise positive conclusion: every source belongs to a component of size at
most `max aleph_0 #I`, and that same component contains a target vertex.

The components here are generated only by the selected rows, not by all
ambient graph edges.  Thus these theorems deliberately do not claim a global
componentwise Menger assembly; ambient edges crossing between row components
are the remaining cut problem.
-/

noncomputable section

open Cardinal Set

namespace Erdos599
namespace UndirectedCofinalRows

open CardinalInduction

universe u

variable {V I : Type u}

/-- An indexed family of genuine target linkages whose left sides cover the
whole source. -/
structure SourceCoveringRows (G : DWeb V) (I : Type u) where
  sourceAt : I → Set V
  paths : I → Set G.DPath
  linkage : ∀ i, IsLinkageBetween G (sourceAt i) G.target (paths i)
  source_cover : G.source ⊆ ⋃ i, sourceAt i

namespace SourceCoveringRows

variable {G : DWeb V} (R : SourceCoveringRows G I)

/-- The common-path component generated by all cofinal rows. -/
abbrev component (x : V) : Set V :=
  IndexedWarpComponents.component R.paths x

/-- Each row is a finite-character warp. -/
theorem row_isWarp (i : I) : G.IsWarp (R.paths i) :=
  (R.linkage i).isWarp

/-- Each row has finite character. -/
theorem row_finiteCharacter (i : I) :
    G.HasFiniteCharacter (R.paths i) :=
  (R.linkage i).finiteCharacter

/-- Every source shares its row component with a target. -/
theorem exists_target_mem_component {x : V} (hx : x ∈ G.source) :
    ∃ t ∈ G.target, t ∈ R.component x := by
  have hxUnion := R.source_cover hx
  simp only [Set.mem_iUnion] at hxUnion
  obtain ⟨i, hxi⟩ := hxUnion
  obtain ⟨p, hp, hpInitial, t, ht, hpTerminal⟩ :=
    SliceSpliceSource.exists_member_terminal_of_linkage (R.linkage i) hxi
  have hxSupport : x ∈ p.support := by
    rw [← hpInitial]
    exact p.initial_mem_support
  have htSupport : t ∈ p.support :=
    G.terminal_mem_support hpTerminal
  refine ⟨t, ht, ?_⟩
  exact IndexedWarpComponents.support_subset_component_of_touches
    (IndexedWarpComponents.mem_component_self R.paths x) hp hxSupport
      htSupport

/-- Sharp cardinal bound for a row component. -/
theorem mk_component_le (x : V) :
    #(R.component x) ≤ max ℵ₀ #I :=
  IndexedWarpComponents.mk_component_le R.paths R.row_isWarp
    R.row_finiteCharacter x

/-- If the row index is below an uncountable cardinal, every row component
is strictly below that cardinal.  No regularity assumption is needed. -/
theorem mk_component_lt {kappa : Cardinal.{u}}
    (huncountable : ℵ₀ < kappa) (hI : #I < kappa) (x : V) :
    #(R.component x) < kappa := by
  exact (R.mk_component_le x).trans_lt (max_lt huncountable hI)

/-- Both endpoint slices inside a row component inherit the strict bound. -/
theorem mk_source_inter_component_lt {kappa : Cardinal.{u}}
    (huncountable : ℵ₀ < kappa) (hI : #I < kappa) (x : V) :
    #(G.source ∩ R.component x : Set V) < kappa :=
  (Cardinal.mk_subtype_mono Set.inter_subset_right).trans_lt
    (R.mk_component_lt huncountable hI x)

theorem mk_target_inter_component_lt {kappa : Cardinal.{u}}
    (huncountable : ℵ₀ < kappa) (hI : #I < kappa) (x : V) :
    #(G.target ∩ R.component x : Set V) < kappa :=
  (Cardinal.mk_subtype_mono Set.inter_subset_right).trans_lt
    (R.mk_component_lt huncountable hI x)

#print axioms exists_target_mem_component
#print axioms mk_component_lt
#print axioms mk_source_inter_component_lt
#print axioms mk_target_inter_component_lt

end SourceCoveringRows

open CardinalInduction.SingularRetargetedRow
open SingularMatrix

/-- Lower induction supplies a genuine target linkage for each canonical
bounded source layer of a normalized unhindered singular web. -/
private theorem exists_canonicalRow
    {kappa : Cardinal.{u}} {G : DWeb V}
    (hlower : UniversalCardinalInductionBelow V kappa)
    (hG : G.IsUnhindered) (hNorm : G.IsNormalized)
    (hcard : #G.source = kappa)
    (huncountable : ℵ₀ < kappa) (hsingular : kappa.IsSingular)
    (i : Index kappa) :
    ∃ L : Set G.DPath,
      IsLinkageBetween G
        (sourceLayer G.source kappa hcard huncountable hsingular i)
        G.target L := by
  let B := sourceLayer G.source kappa hcard huncountable hsingular i
  have hBsub : B ⊆ G.source :=
    sourceLayer_subset G.source kappa hcard huncountable hsingular i
  have hBcard : #B = scale kappa huncountable hsingular i :=
    sourceLayer_card G.source kappa hcard huncountable hsingular i
  have hempty : IsLinkageBetween G (G.source \ G.source) G.target ∅ := by
    simpa using empty_linkage G
  exact exists_boundedTargetLinkage hlower
    (scale_below kappa huncountable hsingular i)
    hG hNorm Set.Subset.rfl hBsub hBcard hempty

/-- The canonical cofinal family of bounded target linkages. -/
noncomputable def canonicalRows
    {kappa : Cardinal.{u}} (G : DWeb V)
    (hlower : UniversalCardinalInductionBelow V kappa)
    (hG : G.IsUnhindered) (hNorm : G.IsNormalized)
    (hcard : #G.source = kappa)
    (huncountable : ℵ₀ < kappa) (hsingular : kappa.IsSingular) :
    SourceCoveringRows G (Index kappa) where
  sourceAt := sourceLayer G.source kappa hcard huncountable hsingular
  paths i := Classical.choose
    (exists_canonicalRow hlower hG hNorm hcard huncountable hsingular i)
  linkage i := Classical.choose_spec
    (exists_canonicalRow hlower hG hNorm hcard huncountable hsingular i)
  source_cover := by
    rw [sourceLayer_cover G.source kappa hcard huncountable hsingular]

/-- The canonical cofinality index is strictly below a singular cardinal. -/
theorem mk_index_lt
    {kappa : Cardinal.{u}} (hsingular : kappa.IsSingular) :
    #(Index kappa) < kappa := by
  change #(kappa.ord.cof.ord.ToType) < kappa
  rw [Cardinal.mk_toType, Cardinal.card_ord]
  exact hsingular.cof_ord_lt

/-- Hence every component generated by all canonical lower linkages is
strictly smaller than the singular source cardinal. -/
theorem mk_canonicalRows_component_lt
    {kappa : Cardinal.{u}} (G : DWeb V)
    (hlower : UniversalCardinalInductionBelow V kappa)
    (hG : G.IsUnhindered) (hNorm : G.IsNormalized)
    (hcard : #G.source = kappa)
    (huncountable : ℵ₀ < kappa) (hsingular : kappa.IsSingular)
    (x : V) :
    #((canonicalRows G hlower hG hNorm hcard huncountable hsingular).component x)
      < kappa :=
  (canonicalRows G hlower hG hNorm hcard huncountable hsingular).mk_component_lt
    huncountable (mk_index_lt hsingular) x

/-- Every source lies with a target in its small canonical-row component. -/
theorem exists_target_mem_canonicalRows_component
    {kappa : Cardinal.{u}} (G : DWeb V)
    (hlower : UniversalCardinalInductionBelow V kappa)
    (hG : G.IsUnhindered) (hNorm : G.IsNormalized)
    (hcard : #G.source = kappa)
    (huncountable : ℵ₀ < kappa) (hsingular : kappa.IsSingular)
    {x : V} (hx : x ∈ G.source) :
    ∃ t ∈ G.target,
      t ∈ (canonicalRows G hlower hG hNorm hcard huncountable hsingular).component x :=
  (canonicalRows G hlower hG hNorm hcard huncountable hsingular).exists_target_mem_component hx

#print axioms canonicalRows
#print axioms mk_canonicalRows_component_lt
#print axioms exists_target_mem_canonicalRows_component

end UndirectedCofinalRows
end Erdos599
