/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
/-
Copyright (c) 2026 Boris Alexeev. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/

import ErdosProblems.Erdos874.ResidueAlignment

/-!
# Aligned sums of bounded residue blocks

This file records the finite bookkeeping needed to combine residue witnesses
coming from pairwise-disjoint support blocks.  Each block supplies one
fixed-cardinality restricted-sum witness for every element of a coset of a
subgroup of `ZMod q`, with all integer values in a controlled interval.  The
blockwise witnesses combine without collisions, cover the range of the sum
homomorphism on the product of the subgroups, and their interval widths add.

The final alignment lemma chooses the cyclic `d`-step ordering of the summed
subgroup.  Choosing the integer representative of the coset immediately below
the common lower endpoint prevents a wraparound loss: if the total diameter is
at most `q * Z` and `q = d * |H|`, all quotient shifts lie in `[0,Z]`.
-/

open scoped BigOperators

namespace Erdos874

noncomputable section

attribute [local instance] Classical.propDecidable

/-! ## One bounded fixed-cardinality coset block -/

/-- One family of fixed-cardinality witnesses supported on `T`.  There is
one witness set for every member of the subgroup `H`; its sum lies above the
corresponding member of the coset `coset + H`.  All integer witness sums lie
in the same interval, whose width is charged to `q * loss`. -/
structure BoundedCosetBlock
    (q : ℕ) (T : Finset ℤ) (layer loss : ℕ)
    (H : AddSubgroup (ZMod q)) where
  coset : ZMod q
  lower : ℤ
  upper : ℤ
  witness : H → Finset ℤ
  witness_subset : ∀ x, witness x ⊆ T
  witness_card : ∀ x, (witness x).card = layer
  witness_residue : ∀ x,
    ((∑ a ∈ witness x, a : ℤ) : ZMod q) = coset + (x : ZMod q)
  lower_le_value : ∀ x, lower ≤ ∑ a ∈ witness x, a
  value_le_upper : ∀ x, (∑ a ∈ witness x, a) ≤ upper
  diameter_le : upper - lower ≤ (q : ℤ) * (loss : ℤ)

/-- Turn value-level bounded coset coverage into explicit fixed-cardinality
support witnesses.  This bridges `BoundedCosetWitnesses`, whose API is
convenient for constructing one block, to the block-sum bookkeeping below. -/
noncomputable def BoundedCosetBlock.ofBoundedCosetWitnesses
    {q layer loss : ℕ} {T : Finset ℤ} {H : AddSubgroup (ZMod q)}
    (W : BoundedCosetWitnesses q layer T H)
    (hdiam : W.upper - W.lower ≤ (q : ℤ) * (loss : ℤ)) :
    BoundedCosetBlock q T layer loss H := by
  let value : H → ℤ := fun x ↦ Classical.choose (W.cover x x.property)
  have hvalue : ∀ x, value x ∈ restrictedSumset layer T ∧
      (value x : ZMod q) = W.coset + (x : ZMod q) ∧
      W.lower ≤ value x ∧ value x ≤ W.upper := by
    intro x
    exact Classical.choose_spec (W.cover x x.property)
  let witness : H → Finset ℤ := fun x ↦
    Classical.choose (mem_restrictedSumset.mp (hvalue x).1)
  have hwitness : ∀ x,
      witness x ⊆ T ∧ (witness x).card = layer ∧
        (∑ a ∈ witness x, a) = value x := by
    intro x
    exact Classical.choose_spec (mem_restrictedSumset.mp (hvalue x).1)
  refine
    { coset := W.coset
      lower := W.lower
      upper := W.upper
      witness := witness
      witness_subset := fun x ↦ (hwitness x).1
      witness_card := fun x ↦ (hwitness x).2.1
      witness_residue := ?_
      lower_le_value := ?_
      value_le_upper := ?_
      diameter_le := hdiam }
  · intro x
    rw [(hwitness x).2.2]
    exact (hvalue x).2.1
  · intro x
    rw [(hwitness x).2.2]
    exact (hvalue x).2.2.1
  · intro x
    rw [(hwitness x).2.2]
    exact (hvalue x).2.2.2

/-! ## The subgroup generated by summing the blocks -/

/-- The homomorphism which sums one subgroup element chosen from every
block.  Its range is the sum (equivalently, the join) of the block
subgroups. -/
def blockChoiceSumHom {ι : Type*} [Fintype ι]
    {q : ℕ} (H : ι → AddSubgroup (ZMod q)) :
    (∀ i, H i) →+ ZMod q where
  toFun x := ∑ i, (x i : ZMod q)
  map_zero' := by simp
  map_add' x y := by
    simp only [Pi.add_apply, AddSubgroup.coe_add, Finset.sum_add_distrib]

/-- The subgroup generated by the block subgroups, presented as the range of
the finite-product sum map.  This presentation carries the decomposition
needed to choose witnesses without a separate closure argument. -/
def blockSumSubgroup {ι : Type*} [Fintype ι]
    {q : ℕ} (H : ι → AddSubgroup (ZMod q)) : AddSubgroup (ZMod q) :=
  (blockChoiceSumHom H).range

/-- The range presentation really is the lattice sum of the block
subgroups. -/
lemma blockSumSubgroup_eq_iSup {ι : Type*} [Fintype ι]
    {q : ℕ} (H : ι → AddSubgroup (ZMod q)) :
    blockSumSubgroup H = ⨆ i, H i := by
  apply le_antisymm
  · rintro x ⟨y, rfl⟩
    exact sum_mem fun i _hi ↦ (le_iSup H i) (y i).property
  · refine iSup_le ?_
    intro i x hx
    let y : ∀ j, H j := fun j ↦
      if hij : i = j then ⟨x, by simpa [← hij] using hx⟩ else 0
    refine ⟨y, ?_⟩
    dsimp [blockChoiceSumHom]
    rw [Finset.sum_eq_single i]
    · simp [y]
    · intro j _hj hji
      have hij : i ≠ j := Ne.symm hji
      simp [y, hij]
    · simp

/-- A canonical (classically chosen) decomposition of a member of the
generated subgroup into one member of every block subgroup. -/
def blockChoiceOf {ι : Type*} [Fintype ι]
    {q : ℕ} (H : ι → AddSubgroup (ZMod q))
    (x : blockSumSubgroup H) : ∀ i, H i :=
  Classical.choose x.property

@[simp] lemma blockChoiceOf_sum {ι : Type*} [Fintype ι]
    {q : ℕ} (H : ι → AddSubgroup (ZMod q))
    (x : blockSumSubgroup H) :
    ∑ i, ((blockChoiceOf H x i : H i) : ZMod q) = (x : ZMod q) :=
  Classical.choose_spec x.property

/-! ## Combining disjoint supports -/

/-- The union of the witness subsets selected in every block. -/
def combinedBlockWitness {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (x : ∀ i, H i) : Finset ℤ :=
  Finset.univ.biUnion fun i ↦ (B i).witness (x i)

private lemma combinedBlockWitness_pairwise {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : ∀ i, H i) :
    (Set.univ : Set ι).PairwiseDisjoint fun i ↦ (B i).witness (x i) := by
  intro i _hi j _hj hij
  exact (hT (Set.mem_univ i) (Set.mem_univ j) hij).mono
    ((B i).witness_subset (x i)) ((B j).witness_subset (x j))

lemma combinedBlockWitness_subset {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (x : ∀ i, H i) :
    combinedBlockWitness B x ⊆ Finset.univ.biUnion T := by
  apply Finset.biUnion_subset.2
  intro i _hi
  exact (B i).witness_subset (x i) |>.trans
    (Finset.subset_biUnion_of_mem T (Finset.mem_univ i))

lemma combinedBlockWitness_card {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : ∀ i, H i) :
    (combinedBlockWitness B x).card = ∑ i, layer i := by
  have hpw : ((Finset.univ : Finset ι) : Set ι).PairwiseDisjoint
      fun i ↦ (B i).witness (x i) := by
    simpa using combinedBlockWitness_pairwise B hT x
  rw [combinedBlockWitness,
    Finset.card_biUnion hpw]
  apply Finset.sum_congr rfl
  intro i _hi
  exact (B i).witness_card (x i)

lemma combinedBlockWitness_value {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : ∀ i, H i) :
    (∑ a ∈ combinedBlockWitness B x, a) =
      ∑ i, ∑ a ∈ (B i).witness (x i), a := by
  have hpw : ((Finset.univ : Finset ι) : Set ι).PairwiseDisjoint
      fun i ↦ (B i).witness (x i) := by
    simpa using combinedBlockWitness_pairwise B hT x
  rw [combinedBlockWitness,
    Finset.sum_biUnion hpw]

lemma combinedBlockWitness_residue {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : ∀ i, H i) :
    ((∑ a ∈ combinedBlockWitness B x, a : ℤ) : ZMod q) =
      (∑ i, (B i).coset) + ∑ i, (x i : ZMod q) := by
  rw [combinedBlockWitness_value B hT x]
  push_cast
  calc
    ∑ i, ∑ a ∈ (B i).witness (x i), (a : ZMod q) =
        ∑ i, ((B i).coset + (x i : ZMod q)) := by
          apply Finset.sum_congr rfl
          intro i _hi
          have hres := (B i).witness_residue (x i)
          push_cast at hres
          exact hres
    _ = (∑ i, (B i).coset) + ∑ i, (x i : ZMod q) :=
      Finset.sum_add_distrib

lemma combinedBlockWitness_lower {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : ∀ i, H i) :
    (∑ i, (B i).lower) ≤ ∑ a ∈ combinedBlockWitness B x, a := by
  rw [combinedBlockWitness_value B hT x]
  exact Finset.sum_le_sum fun i _hi ↦ (B i).lower_le_value (x i)

lemma combinedBlockWitness_upper {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : ∀ i, H i) :
    (∑ a ∈ combinedBlockWitness B x, a) ≤ ∑ i, (B i).upper := by
  rw [combinedBlockWitness_value B hT x]
  exact Finset.sum_le_sum fun i _hi ↦ (B i).value_le_upper (x i)

/-- The diameter charges add exactly: the summed witness family has integer
diameter at most `q * ∑ i, loss i`. -/
lemma combinedBlockWitness_diameter {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i)) :
    (∑ i, (B i).upper) - ∑ i, (B i).lower ≤
      (q : ℤ) * (∑ i, loss i : ℕ) := by
  rw [← Finset.sum_sub_distrib]
  calc
    ∑ i, ((B i).upper - (B i).lower) ≤
        ∑ i, (q : ℤ) * (loss i : ℤ) :=
      Finset.sum_le_sum fun i _hi ↦ (B i).diameter_le
    _ = (q : ℤ) * (∑ i, loss i : ℕ) := by
      push_cast
      rw [Finset.mul_sum]

/-! ## One witness above every residue of the summed subgroup -/

/-- The combined witness chosen above a member of the sum subgroup. -/
def summedBlockWitness {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (x : blockSumSubgroup H) : Finset ℤ :=
  combinedBlockWitness B (blockChoiceOf H x)

lemma summedBlockWitness_mem_restrictedSumset
    {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : blockSumSubgroup H) :
    (∑ a ∈ summedBlockWitness B x, a) ∈
      restrictedSumset (∑ i, layer i) (Finset.univ.biUnion T) := by
  apply mem_restrictedSumset.mpr
  refine ⟨summedBlockWitness B x, ?_, ?_, rfl⟩
  · exact combinedBlockWitness_subset B (blockChoiceOf H x)
  · exact combinedBlockWitness_card B hT (blockChoiceOf H x)

lemma summedBlockWitness_residue
    {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : blockSumSubgroup H) :
    ((∑ a ∈ summedBlockWitness B x, a : ℤ) : ZMod q) =
      (∑ i, (B i).coset) + (x : ZMod q) := by
  rw [summedBlockWitness, combinedBlockWitness_residue B hT,
    blockChoiceOf_sum]

lemma summedBlockWitness_lower
    {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : blockSumSubgroup H) :
    (∑ i, (B i).lower) ≤ ∑ a ∈ summedBlockWitness B x, a :=
  combinedBlockWitness_lower B hT (blockChoiceOf H x)

lemma summedBlockWitness_upper
    {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T)
    (x : blockSumSubgroup H) :
    (∑ a ∈ summedBlockWitness B x, a) ≤ ∑ i, (B i).upper :=
  combinedBlockWitness_upper B hT (blockChoiceOf H x)

/-! ## Quotient-spread estimate -/

/-- If a complete `d`-spaced residue block (`q = d*h`) is lifted into an
integer interval of width at most `q*Z`, then any two quotient shifts differ
by at most `Z`.  The strict saving comes from `d*(h-1) < q`; this is the
integer alignment estimate missing from a residue-only argument. -/
lemma quotient_sub_le_of_complete_residue_block
    {q d h Z : ℕ} (hq : 0 < q) (hfactor : q = d * h)
    {c lower upper : ℤ} (w z : Fin h → ℤ)
    (hwform : ∀ j, w j = c + (d : ℤ) * (j : ℕ) + (q : ℤ) * z j)
    (hlower : ∀ j, lower ≤ w j) (hupper : ∀ j, w j ≤ upper)
    (hdiam : upper - lower ≤ (q : ℤ) * (Z : ℤ)) :
    ∀ j k, z j - z k ≤ (Z : ℤ) := by
  have hd : 0 < d := by
    by_contra hd0
    have : d = 0 := Nat.eq_zero_of_not_pos hd0
    subst d
    simp at hfactor
    omega
  intro j k
  have hjlt : (j : ℕ) < h := j.isLt
  have hklt : (k : ℕ) < h := k.isLt
  have hqcast : (q : ℤ) = (d : ℤ) * (h : ℤ) := by exact_mod_cast hfactor
  have hvalue : w j - w k ≤ upper - lower := by
    linarith [hupper j, hlower k]
  have hstep : (d : ℤ) * (k : ℤ) - (d : ℤ) * (j : ℤ) < (q : ℤ) := by
    have hjnonneg : (0 : ℤ) ≤ (j : ℕ) := by positivity
    have hkcast : ((k : ℕ) : ℤ) < (h : ℤ) := by exact_mod_cast hklt
    have hdcast : (0 : ℤ) < (d : ℤ) := by exact_mod_cast hd
    nlinarith
  have hzscaled : (q : ℤ) * (z j - z k) <
      (q : ℤ) * ((Z : ℤ) + 1) := by
    rw [hwform j, hwform k] at hvalue
    have := hdiam
    nlinarith
  have hqcastpos : (0 : ℤ) < (q : ℤ) := by exact_mod_cast hq
  nlinarith

/-! ## Canonical aligned witnesses for the generated subgroup -/

/-- Pairwise-disjoint bounded coset blocks produce an aligned complete
residue block for their generated subgroup.  The resulting witnesses all
belong to the sum of the fixed restricted-sum layers, and the quotient-span
loss is at most the sum of the individual block losses.

This is the finite block-sum replacement for choosing unrelated modular
witnesses and then charging their entire ambient integer range. -/
theorem nonempty_alignedResidueWitnesses_of_boundedCosetBlocks
    {ι : Type*} [Fintype ι]
    {q : ℕ} {T : ι → Finset ℤ} {layer loss : ι → ℕ}
    {H : ι → AddSubgroup (ZMod q)}
    (hq : 0 < q)
    (B : ∀ i, BoundedCosetBlock q (T i) (layer i) (loss i) (H i))
    (hT : (Set.univ : Set ι).PairwiseDisjoint T) :
    let S := blockSumSubgroup H
    Nonempty (AlignedResidueWitnesses q (∑ i, layer i) (Nat.card S)
      (q / Nat.card S) (∑ i, loss i) (Finset.univ.biUnion T)) := by
  dsimp only
  let : NeZero q := ⟨hq.ne'⟩
  let S := blockSumSubgroup H
  let h := Nat.card S
  let d := q / h
  have hh : 0 < h := by
    dsimp [h]
    exact Nat.card_pos
  have hclassification := zmod_subgroup_index_eq_div_card_and_multiples_mem hq S
  have hindex : S.index = d := by
    simpa [d, h] using hclassification.1
  have hmultiple : ∀ j : Fin h,
      (((d * (j : ℕ) : ℕ) : ZMod q)) ∈ S := by
    simpa [d, h] using hclassification.2
  have hmul : S.index * Nat.card S = q := by
    simpa using S.index_mul_card
  have hfactor : q = d * h := by
    rw [← hmul, hindex]
  let eta : Fin h → S := fun j ↦
    ⟨(((d * (j : ℕ) : ℕ) : ZMod q)), hmultiple j⟩
  let w : Fin h → ℤ := fun j ↦
    ∑ a ∈ summedBlockWitness B (eta j), a
  have hwmem : ∀ j, w j ∈
      restrictedSumset (∑ i, layer i) (Finset.univ.biUnion T) := by
    intro j
    exact summedBlockWitness_mem_restrictedSumset B hT (eta j)
  have hwcast : ∀ j, (w j : ZMod q) =
      (∑ i, (B i).coset) + (((d * (j : ℕ) : ℕ) : ZMod q)) := by
    intro j
    dsimp [w]
    rw [summedBlockWitness_residue B hT]
  obtain ⟨z, hzform⟩ := exists_integer_lifts_of_residue_block hq
    (∑ i, (B i).coset) w hwcast
  have hwlower : ∀ j, (∑ i, (B i).lower) ≤ w j := by
    intro j
    exact summedBlockWitness_lower B hT (eta j)
  have hwupper : ∀ j, w j ≤ ∑ i, (B i).upper := by
    intro j
    exact summedBlockWitness_upper B hT (eta j)
  have hdiam := combinedBlockWitness_diameter B
  have hzpair : ∀ j k, z j - z k ≤ (∑ i, loss i : ℕ) :=
    quotient_sub_le_of_complete_residue_block hq hfactor w z hzform
      hwlower hwupper hdiam
  have huniv : (Finset.univ : Finset (Fin h)).Nonempty :=
    ⟨⟨0, hh⟩, Finset.mem_univ _⟩
  obtain ⟨jlo, _hjlo_mem, hjlo⟩ :=
    Finset.exists_min_image (Finset.univ : Finset (Fin h)) z huniv
  obtain ⟨jhi, _hjhi_mem, hjhi⟩ :=
    Finset.exists_max_image (Finset.univ : Finset (Fin h)) z huniv
  have hlohi : z jlo ≤ z jhi := hjlo jhi (Finset.mem_univ _)
  have hspanInt : z jhi - z jlo ≤ (∑ i, loss i : ℕ) := hzpair jhi jlo
  have hspanNat : (z jhi - z jlo).toNat ≤ ∑ i, loss i := by
    have hnonneg : 0 ≤ z jhi - z jlo := sub_nonneg.mpr hlohi
    have hcast : (((z jhi - z jlo).toNat : ℕ) : ℤ) = z jhi - z jlo :=
      Int.toNat_of_nonneg hnonneg
    exact_mod_cast (hcast ▸ hspanInt)
  refine ⟨{
    factor := hfactor
    card_pos := hh
    base := ((∑ i, (B i).coset).val : ℤ)
    lower := z jlo
    upper := z jhi
    witness := w
    quotient := z
    witness_mem := hwmem
    witness_eq := hzform
    lower_le := ?_
    le_upper := ?_
    span_le := hspanNat }⟩
  · intro j
    exact hjlo j (Finset.mem_univ _)
  · intro j
    exact hjhi j (Finset.mem_univ _)


end

end Erdos874
