/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0
-/

import ErdosProblems.Erdos874.ProgressionExtraction

/-!
# Filling a small residue subgroup by a fixed restricted-sum layer

This file contains the elementary finite-group selection argument used in
the modular part of the Deshouillers--Freiman proof.  If fewer than `R`
residue classes occur and every difference from a distinguished class has
additive order less than `R`, every element of the subgroup generated by the
differences has a bounded-coefficient representation.  Taking the indicated
number of representatives from each non-base fibre and filling the remaining
places from `R ^ 2` representatives of the base fibre realizes the whole
subgroup coset in one restricted-sum layer.
-/

open scoped BigOperators

namespace Erdos874

noncomputable section

attribute [local instance] Classical.propDecidable

private theorem closure_image_exists_bounded_coefficients
    {I M : Type*} [DecidableEq I] [AddCommGroup M]
    (S : Finset I) (f : I → M)
    (horder : ∀ i ∈ S, 0 < addOrderOf (f i)) {x : M}
    (hx : x ∈ AddSubgroup.closure (f '' (S : Set I))) :
    ∃ c : I → ℕ,
      (∀ i ∈ S, c i < addOrderOf (f i)) ∧
      x = ∑ i ∈ S, c i • f i := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
      obtain ⟨i, hi, rfl⟩ := hx
      let c : I → ℕ := fun j ↦ if j = i then 1 % addOrderOf (f i) else 0
      refine ⟨c, ?_, ?_⟩
      · intro j hj
        by_cases hji : j = i
        · subst j
          simp only [c, if_pos]
          exact Nat.mod_lt _ (horder i hi)
        · simp [c, hji, horder j hj]
      · rw [Finset.sum_eq_single i]
        · simp [c]
        · intro j hj hji
          simp [c, hji]
        · intro hi'
          exact (hi' hi).elim
  | zero =>
      refine ⟨fun _ ↦ 0, ?_, by simp⟩
      intro i hi
      simpa using horder i hi
  | add x y hx hy ihx ihy =>
      obtain ⟨c, hc, rfl⟩ := ihx
      obtain ⟨d, hd, rfl⟩ := ihy
      let e : I → ℕ := fun i ↦ (c i + d i) % addOrderOf (f i)
      refine ⟨e, ?_, ?_⟩
      · intro i hi
        exact Nat.mod_lt _ (horder i hi)
      · rw [← Finset.sum_add_distrib]
        apply Finset.sum_congr rfl
        intro i hi
        simp [e, add_nsmul]
  | neg x hx ih =>
      obtain ⟨c, hc, rfl⟩ := ih
      let e : I → ℕ := fun i ↦
        if c i = 0 then 0 else addOrderOf (f i) - c i
      have heq : ∀ i ∈ S, e i • f i = -(c i • f i) := by
        intro i hi
        by_cases hci : c i = 0
        · simp [e, hci]
        · have hcle : c i ≤ addOrderOf (f i) := (hc i hi).le
          have hz : addOrderOf (f i) • f i = 0 := addOrderOf_nsmul_eq_zero (f i)
          have hadd : (addOrderOf (f i) - c i) • f i + c i • f i = 0 := by
            rw [← add_nsmul, Nat.sub_add_cancel hcle, hz]
          simpa [e, hci] using (eq_neg_of_add_eq_zero_left hadd)
      refine ⟨e, ?_, ?_⟩
      · intro i hi
        by_cases hci : c i = 0
        · simpa [e, hci] using horder i hi
        · simp only [e, if_neg hci]
          have hlt := hc i hi
          omega
      · rw [Finset.sum_congr rfl heq, Finset.sum_neg_distrib]

/-- Select prescribed numbers of integers from distinct residue fibres.
The selected set remembers its residue support; this is what makes the
inductive unions disjoint. -/
private theorem exists_subset_with_residue_counts
    {q : ℕ} (A : Finset ℤ) (S : Finset (ZMod q)) (n : ZMod q → ℕ)
    (hcard : ∀ g ∈ S,
      n g ≤ (A.filter fun (a : ℤ) ↦ (a : ZMod q) = g).card) :
    ∃ C : Finset ℤ,
      C ⊆ A ∧
      C.card = ∑ g ∈ S, n g ∧
      ((∑ a ∈ C, a : ℤ) : ZMod q) = ∑ g ∈ S, n g • g ∧
      ∀ a ∈ C, (a : ZMod q) ∈ S := by
  induction S using Finset.induction_on with
  | empty =>
      exact ⟨∅, by simp⟩
  | @insert g S hg ih =>
      have hchoose : ∃ Cg : Finset ℤ,
          Cg ⊆ A.filter (fun a : ℤ ↦ (a : ZMod q) = g) ∧ Cg.card = n g :=
        Finset.exists_subset_card_eq (hcard g (Finset.mem_insert_self g S))
      obtain ⟨Cg, hCg, hCgcard⟩ := hchoose
      have hcardS : ∀ s ∈ S,
          n s ≤ (A.filter fun (a : ℤ) ↦ (a : ZMod q) = s).card := by
        intro s hs
        exact hcard s (Finset.mem_insert_of_mem hs)
      obtain ⟨CS, hCSA, hCScard, hCSsum, hCSsupport⟩ := ih hcardS
      have hCgA : Cg ⊆ A := hCg.trans (Finset.filter_subset _ _)
      have hCgres : ∀ a ∈ Cg, (a : ZMod q) = g := by
        intro a ha
        exact (Finset.mem_filter.mp (hCg ha)).2
      have hdisj : Disjoint Cg CS := by
        rw [Finset.disjoint_left]
        intro a haCg haCS
        have hgmem : (a : ZMod q) = g := hCgres a haCg
        have hSmem : (a : ZMod q) ∈ S := hCSsupport a haCS
        exact hg (hgmem ▸ hSmem)
      have hCgsum : ((∑ a ∈ Cg, a : ℤ) : ZMod q) = Cg.card • g := by
        push_cast
        calc
          ∑ a ∈ Cg, (a : ZMod q) = ∑ _a ∈ Cg, g := by
            apply Finset.sum_congr rfl
            intro a ha
            exact hCgres a ha
          _ = Cg.card • g := by simp
      refine ⟨Cg ∪ CS, Finset.union_subset hCgA hCSA, ?_, ?_, ?_⟩
      · rw [Finset.card_union_of_disjoint hdisj, hCgcard, hCScard,
          Finset.sum_insert hg]
      · rw [Finset.sum_union hdisj]
        push_cast at hCgsum hCSsum ⊢
        rw [hCgsum, hCSsum, hCgcard, Finset.sum_insert hg]
      · intro a ha
        rcases Finset.mem_union.mp ha with ha | ha
        · exact Finset.mem_insert.mpr (Or.inl (hCgres a ha))
        · exact Finset.mem_insert_of_mem (hCSsupport a ha)

/-- A subgroup of `ZMod q` of cardinality `h` contains every multiple of
`d = q / h`; moreover `d` is its index.  Thus each coset of the subgroup is
one residue class modulo `d`, and the `h` displayed multiples give its
canonical `d`-step residue block. -/
theorem zmod_subgroup_index_eq_div_card_and_multiples_mem
    {q : ℕ} (hq : 0 < q) (H : AddSubgroup (ZMod q)) :
    H.index = q / Nat.card H ∧
      ∀ j : Fin (Nat.card H),
        (((q / Nat.card H) * (j : ℕ) : ℕ) : ZMod q) ∈ H := by
  let : NeZero q := ⟨hq.ne'⟩
  have hmul : H.index * Nat.card H = q := by
    simpa using H.index_mul_card
  have hcardpos : 0 < Nat.card H := Nat.card_pos
  have hindex : H.index = q / Nat.card H := by
    calc
      H.index = (H.index * Nat.card H) / Nat.card H := by
        rw [Nat.mul_div_left _ hcardpos]
      _ = q / Nat.card H := by rw [hmul]
  refine ⟨hindex, ?_⟩
  intro j
  have hj := H.nsmul_index_mem ((j : ℕ) : ZMod q)
  rw [hindex] at hj
  simpa [nsmul_eq_mul] using hj

/-- If two residue fibres contain `R` elements and the difference of their
residues has additive order at least `R`, the mixed `R`-term sums contain `R`
elements with pairwise distinct residues.  The `j`-th witness uses `j`
elements of the second fibre and `R-j` elements of the first. -/
theorem exists_mixed_restrictedSums_cast_injOn
    {q R : ℕ} {T : Finset ℤ} {g₀ g : ZMod q} (hgg₀ : g ≠ g₀)
    (hbase : R ≤ (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g₀).card)
    (hfiber : R ≤ (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g).card)
    (horder : R ≤ addOrderOf (g - g₀)) :
    ∃ X : Finset ℤ,
      X ⊆ restrictedSumset R T ∧ X.card = R ∧
      Set.InjOn (fun x : ℤ ↦ (x : ZMod q)) X := by
  have hwitness : ∀ j : Fin R, ∃ z ∈ restrictedSumset R T,
      (z : ZMod q) = R • g₀ + (j : ℕ) • (g - g₀) := by
    intro j
    have hchoose₀ : ∃ C₀ : Finset ℤ,
        C₀ ⊆ T.filter (fun (a : ℤ) ↦ (a : ZMod q) = g₀) ∧
          C₀.card = R - (j : ℕ) :=
      Finset.exists_subset_card_eq ((Nat.sub_le R (j : ℕ)).trans hbase)
    have hchoose₁ : ∃ C₁ : Finset ℤ,
        C₁ ⊆ T.filter (fun (a : ℤ) ↦ (a : ZMod q) = g) ∧
          C₁.card = (j : ℕ) :=
      Finset.exists_subset_card_eq ((Nat.le_of_lt j.isLt).trans hfiber)
    obtain ⟨C₀, hC₀, hC₀card⟩ := hchoose₀
    obtain ⟨C₁, hC₁, hC₁card⟩ := hchoose₁
    have hC₀T : C₀ ⊆ T := hC₀.trans (Finset.filter_subset _ _)
    have hC₁T : C₁ ⊆ T := hC₁.trans (Finset.filter_subset _ _)
    have hC₀res : ∀ a ∈ C₀, (a : ZMod q) = g₀ := by
      intro a ha
      exact (Finset.mem_filter.mp (hC₀ ha)).2
    have hC₁res : ∀ a ∈ C₁, (a : ZMod q) = g := by
      intro a ha
      exact (Finset.mem_filter.mp (hC₁ ha)).2
    have hdisj : Disjoint C₀ C₁ := by
      rw [Finset.disjoint_left]
      intro a ha₀ ha₁
      exact hgg₀ ((hC₁res a ha₁).symm.trans (hC₀res a ha₀))
    have hC₀sum : ((∑ a ∈ C₀, a : ℤ) : ZMod q) = C₀.card • g₀ := by
      push_cast
      calc
        ∑ a ∈ C₀, (a : ZMod q) = ∑ _a ∈ C₀, g₀ := by
          apply Finset.sum_congr rfl
          exact hC₀res
        _ = C₀.card • g₀ := by simp
    have hC₁sum : ((∑ a ∈ C₁, a : ℤ) : ZMod q) = C₁.card • g := by
      push_cast
      calc
        ∑ a ∈ C₁, (a : ZMod q) = ∑ _a ∈ C₁, g := by
          apply Finset.sum_congr rfl
          exact hC₁res
        _ = C₁.card • g := by simp
    let C := C₀ ∪ C₁
    have hjle : (j : ℕ) ≤ R := Nat.le_of_lt j.isLt
    have hCcard : C.card = R := by
      dsimp [C]
      rw [Finset.card_union_of_disjoint hdisj, hC₀card, hC₁card,
        Nat.sub_add_cancel hjle]
    have hCsum : ((∑ a ∈ C, a : ℤ) : ZMod q) =
        R • g₀ + (j : ℕ) • (g - g₀) := by
      dsimp [C]
      rw [Finset.sum_union hdisj]
      push_cast at hC₀sum hC₁sum ⊢
      rw [hC₀sum, hC₁sum, hC₀card, hC₁card]
      have hfill : R - (j : ℕ) + (j : ℕ) = R := Nat.sub_add_cancel hjle
      have hfill_smul :
          (R - (j : ℕ)) • g₀ + (j : ℕ) • g₀ = R • g₀ := by
        rw [← add_nsmul, hfill]
      rw [← hfill_smul]
      simp_rw [nsmul_sub]
      abel
    refine ⟨∑ a ∈ C, a, ?_, hCsum⟩
    exact mem_restrictedSumset.mpr
      ⟨C, Finset.union_subset hC₀T hC₁T, hCcard, rfl⟩
  let w : Fin R → ℤ := fun j ↦ Classical.choose (hwitness j)
  have hwmem : ∀ j, w j ∈ restrictedSumset R T := fun j ↦
    (Classical.choose_spec (hwitness j)).1
  have hwcast : ∀ j, (w j : ZMod q) =
      R • g₀ + (j : ℕ) • (g - g₀) := fun j ↦
    (Classical.choose_spec (hwitness j)).2
  have hw_injective : Function.Injective w := by
    intro i j hij
    have hcast := congrArg (fun x : ℤ ↦ (x : ZMod q)) hij
    rw [hwcast i, hwcast j] at hcast
    have hsmul : (i : ℕ) • (g - g₀) = (j : ℕ) • (g - g₀) :=
      add_left_cancel hcast
    have hmod : (i : ℕ) ≡ (j : ℕ) [MOD addOrderOf (g - g₀)] :=
      nsmul_eq_nsmul_iff_modEq.mp hsmul
    apply Fin.ext
    exact hmod.eq_of_lt_of_lt (i.isLt.trans_le horder) (j.isLt.trans_le horder)
  let X := Finset.univ.image w
  refine ⟨X, ?_, ?_, ?_⟩
  · intro x hx
    obtain ⟨j, _hj, rfl⟩ := Finset.mem_image.mp hx
    exact hwmem j
  · dsimp [X]
    rw [Finset.card_image_of_injective _ hw_injective]
    simp
  · intro x hx y hy hxy
    obtain ⟨i, _hi, rfl⟩ := Finset.mem_image.mp hx
    obtain ⟨j, _hj, rfl⟩ := Finset.mem_image.mp hy
    have hcasti := hwcast i
    have hcastj := hwcast j
    change (w i : ZMod q) = (w j : ZMod q) at hxy
    rw [hcasti, hcastj] at hxy
    have hsmul : (i : ℕ) • (g - g₀) = (j : ℕ) • (g - g₀) :=
      add_left_cancel hxy
    have hmod : (i : ℕ) ≡ (j : ℕ) [MOD addOrderOf (g - g₀)] :=
      nsmul_eq_nsmul_iff_modEq.mp hsmul
    have hij : i = j :=
      Fin.ext (hmod.eq_of_lt_of_lt (i.isLt.trans_le horder) (j.isLt.trans_le horder))
    exact congrArg w hij

/-- **Fixed-layer subgroup coverage.**

Let `G` be fewer than `R` residue classes modulo `q`, with distinguished
class `g₀`.  Suppose `T` contains at least `R²` representatives of `g₀`
and at least `R` representatives of every other class in `G`.  If each
difference `g - g₀` has additive order less than `R`, then the residues of
the `R²`-term restricted sums from `T` contain the complete coset

`R² • g₀ + closure {g - g₀ | g ∈ G \ {g₀}}`.

The witnesses are actual subsets of `T`, so no coverage statement is hidden
among the assumptions. -/
theorem restrictedSumset_sq_covers_differenceSubgroup
    {q R : ℕ} {G : Finset (ZMod q)} {g₀ : ZMod q} {T : Finset ℤ}
    (hq : 0 < q) (hg₀ : g₀ ∈ G) (hG : G.card < R)
    (hbase : R * R ≤
      (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g₀).card)
    (hfiber : ∀ g ∈ G.erase g₀,
      R ≤ (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g).card)
    (horder : ∀ g ∈ G.erase g₀, addOrderOf (g - g₀) < R) :
    ∀ h ∈ AddSubgroup.closure
        ((fun g : ZMod q ↦ g - g₀) '' ((G.erase g₀ : Finset (ZMod q)) : Set (ZMod q))),
      ∃ z ∈ restrictedSumset (R * R) T,
        (z : ZMod q) = (R * R) • g₀ + h := by
  intro h hh
  let : NeZero q := ⟨hq.ne'⟩
  let E := G.erase g₀
  have hR : 0 < R := by
    have : 0 < G.card := Finset.card_pos.mpr ⟨g₀, hg₀⟩
    omega
  have horderpos : ∀ g ∈ E, 0 < addOrderOf (g - g₀) := by
    intro g hg
    exact addOrderOf_pos (g - g₀)
  obtain ⟨c, hcorder, hrepr⟩ :=
    closure_image_exists_bounded_coefficients E (fun g ↦ g - g₀)
      horderpos hh
  have hcR : ∀ g ∈ E, c g < R := by
    intro g hg
    exact (hcorder g hg).trans (horder g hg)
  let t := ∑ g ∈ E, c g
  have hEcard : E.card < R :=
    (Finset.card_erase_le : (G.erase g₀).card ≤ G.card).trans_lt hG
  have ht_le : t ≤ E.card * R := by
    calc
      t = ∑ g ∈ E, c g := rfl
      _ ≤ ∑ _g ∈ E, R := by
        apply Finset.sum_le_sum
        intro g hg
        exact (hcR g hg).le
      _ = E.card * R := by simp
  have ht_lt : t < R * R :=
    ht_le.trans_lt (Nat.mul_lt_mul_of_pos_right hEcard hR)
  have hc_card : ∀ g ∈ E,
      c g ≤ (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g).card := by
    intro g hg
    exact (hcR g hg).le.trans (hfiber g hg)
  obtain ⟨C₁, hC₁T, hC₁card, hC₁sum, hC₁support⟩ :=
    exists_subset_with_residue_counts T E c hc_card
  have hchoose₀ : ∃ C₀ : Finset ℤ,
      C₀ ⊆ T.filter (fun a : ℤ ↦ (a : ZMod q) = g₀) ∧
        C₀.card = R * R - t :=
    Finset.exists_subset_card_eq ((Nat.sub_le (R * R) t).trans hbase)
  obtain ⟨C₀, hC₀, hC₀card⟩ := hchoose₀
  have hC₀T : C₀ ⊆ T := hC₀.trans (Finset.filter_subset _ _)
  have hC₀res : ∀ a ∈ C₀, (a : ZMod q) = g₀ := by
    intro a ha
    exact (Finset.mem_filter.mp (hC₀ ha)).2
  have hdisj : Disjoint C₀ C₁ := by
    rw [Finset.disjoint_left]
    intro a ha₀ ha₁
    have haE : (a : ZMod q) ∈ E := hC₁support a ha₁
    have hne : (a : ZMod q) ≠ g₀ := (Finset.mem_erase.mp haE).1
    exact hne (hC₀res a ha₀)
  have hC₀sum : ((∑ a ∈ C₀, a : ℤ) : ZMod q) = C₀.card • g₀ := by
    push_cast
    calc
      ∑ a ∈ C₀, (a : ZMod q) = ∑ _a ∈ C₀, g₀ := by
        apply Finset.sum_congr rfl
        intro a ha
        exact hC₀res a ha
      _ = C₀.card • g₀ := by simp
  let C := C₀ ∪ C₁
  have ht_le_sq : t ≤ R * R := ht_lt.le
  have hCcard : C.card = R * R := by
    dsimp [C]
    rw [Finset.card_union_of_disjoint hdisj, hC₀card, hC₁card]
    exact Nat.sub_add_cancel ht_le_sq
  have hsum_nsmul : ∑ g ∈ E, c g • g₀ = t • g₀ := by
    dsimp [t]
    induction E using Finset.induction_on with
    | empty => simp
    | @insert g E hg ih =>
        rw [Finset.sum_insert hg, Finset.sum_insert hg, add_nsmul, ih]
  have hdiff :
      ∑ g ∈ E, c g • (g - g₀) =
        (∑ g ∈ E, c g • g) - t • g₀ := by
    simp_rw [nsmul_sub]
    rw [Finset.sum_sub_distrib]
    congr 1
  have hCsum : ((∑ a ∈ C, a : ℤ) : ZMod q) = (R * R) • g₀ + h := by
    dsimp [C]
    rw [Finset.sum_union hdisj]
    push_cast at hC₀sum hC₁sum ⊢
    rw [hC₀sum, hC₁sum, hC₀card]
    rw [hrepr, hdiff]
    have hfill : R * R - t + t = R * R := Nat.sub_add_cancel ht_le_sq
    have hfill_smul : (R * R - t) • g₀ + t • g₀ = (R * R) • g₀ := by
      rw [← add_nsmul, hfill]
    rw [← hfill_smul]
    abel
  refine ⟨∑ a ∈ C, a, ?_, hCsum⟩
  exact mem_restrictedSumset.mpr
    ⟨C, Finset.union_subset hC₀T hC₁T, hCcard, rfl⟩

/-- Functional residue-block form of
`restrictedSumset_sq_covers_differenceSubgroup`.  It combines subgroup
coverage with the cyclic classification above and chooses one actual
restricted sum above each term of the canonical `d`-step residue block. -/
theorem exists_restrictedSumset_sq_residue_block
    {q R : ℕ} {G : Finset (ZMod q)} {g₀ : ZMod q} {T : Finset ℤ}
    (hq : 0 < q) (hg₀ : g₀ ∈ G) (hG : G.card < R)
    (hbase : R * R ≤
      (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g₀).card)
    (hfiber : ∀ g ∈ G.erase g₀,
      R ≤ (T.filter fun (a : ℤ) ↦ (a : ZMod q) = g).card)
    (horder : ∀ g ∈ G.erase g₀, addOrderOf (g - g₀) < R) :
    let H := AddSubgroup.closure
      ((fun g : ZMod q ↦ g - g₀) '' ((G.erase g₀ : Finset (ZMod q)) : Set (ZMod q)))
    let d := q / Nat.card H
    ∃ w : Fin (Nat.card H) → ℤ, ∀ j,
      w j ∈ restrictedSumset (R * R) T ∧
      (w j : ZMod q) = (R * R) • g₀ + (((d * (j : ℕ) : ℕ) : ZMod q)) := by
  dsimp only
  let H := AddSubgroup.closure
    ((fun g : ZMod q ↦ g - g₀) '' ((G.erase g₀ : Finset (ZMod q)) : Set (ZMod q)))
  have hmultiple := (zmod_subgroup_index_eq_div_card_and_multiples_mem hq H).2
  have hchoose : ∀ j : Fin (Nat.card H), ∃ z ∈ restrictedSumset (R * R) T,
      (z : ZMod q) = (R * R) • g₀ +
        ((((q / Nat.card H) * (j : ℕ) : ℕ) : ZMod q)) := by
    intro j
    exact restrictedSumset_sq_covers_differenceSubgroup hq hg₀ hG hbase hfiber horder
      _ (hmultiple j)
  choose w hwmem hwcast using hchoose
  exact ⟨w, fun j ↦ ⟨hwmem j, hwcast j⟩⟩

/-- Lift a complete residue block to exact integer representatives.  The
quotient shifts `z j` are the quantities whose spread is charged by
`ContainsAP.combine_residue_witnesses`. -/
theorem exists_integer_lifts_of_residue_block
    {q h d : ℕ} (hq : 0 < q) (b : ZMod q) (w : Fin h → ℤ)
    (hw : ∀ j, (w j : ZMod q) = b + (((d * (j : ℕ) : ℕ) : ZMod q))) :
    ∃ z : Fin h → ℤ, ∀ j,
      w j = (b.val : ℤ) + (d : ℤ) * (j : ℕ) + (q : ℤ) * z j := by
  let : NeZero q := ⟨hq.ne'⟩
  have hchoose : ∀ j : Fin h, ∃ z : ℤ,
      w j = (b.val : ℤ) + (d : ℤ) * (j : ℕ) + (q : ℤ) * z := by
    intro j
    let target : ℤ := (b.val : ℤ) + (d : ℤ) * (j : ℕ)
    have heq : (w j : ZMod q) = (target : ZMod q) := by
      rw [hw j]
      have hb : (b.val : ZMod q) = b := ZMod.natCast_zmod_val b
      rw [← hb]
      simp [target]
    have hdvd : (q : ℤ) ∣ target - w j :=
      (ZMod.intCast_eq_intCast_iff_dvd_sub (w j) target q).mp heq
    obtain ⟨k, hk⟩ := hdvd
    refine ⟨-k, ?_⟩
    dsimp [target] at hk ⊢
    linarith
  choose z hz using hchoose
  exact ⟨z, hz⟩

private lemma add_restrictedSumsets_disjoint_residueSubgroup
    {A B : Finset ℤ} {r s : ℕ} (hAB : Disjoint A B)
    {x y : ℤ} (hx : x ∈ restrictedSumset r A)
    (hy : y ∈ restrictedSumset s B) :
    x + y ∈ restrictedSumset (r + s) (A ∪ B) := by
  obtain ⟨X, hXA, hXcard, hXsum⟩ := mem_restrictedSumset.mp hx
  obtain ⟨Y, hYB, hYcard, hYsum⟩ := mem_restrictedSumset.mp hy
  have hXY : Disjoint X Y := hAB.mono hXA hYB
  exact mem_restrictedSumset.mpr
    ⟨X ∪ Y,
      Finset.union_subset (hXA.trans Finset.subset_union_left)
        (hYB.trans Finset.subset_union_right),
      by rw [Finset.card_union_of_disjoint hXY, hXcard, hYcard],
      by rw [Finset.sum_union hXY, hXsum, hYsum]⟩

/-- Align one witness in each of `h` consecutive residue classes with a long
`q`-progression, where `q = d*h`.  The quotient shifts of the witnesses are
allowed to vary in the integer interval `[zlo,zhi]`; intersecting the shifted
copies of the long progression loses exactly `toNat (zhi-zlo)` blocks.

This is the correct integer-level replacement for the false assertion that
covering a coset modulo `q` by itself produces a literal `d`-progression. -/
theorem ContainsAP.combine_residue_witnesses
    {B T : Finset ℤ} {t u d q h L K : ℕ} {c zlo zhi : ℤ}
    (hBT : Disjoint B T) (hh : 0 < h) (hq : q = d * h)
    (hlong : ContainsAP (restrictedSumset t B) (q : ℤ) L)
    (w : Fin h → ℤ) (z : Fin h → ℤ)
    (hwmem : ∀ j, w j ∈ restrictedSumset u T)
    (hwform : ∀ j, w j = c + (d : ℤ) * (j : ℕ) + (q : ℤ) * z j)
    (hzlo : ∀ j, zlo ≤ z j) (hzhi : ∀ j, z j ≤ zhi)
    (hfit : (zhi - zlo).toNat + K ≤ L) :
    ContainsAP (restrictedSumset (t + u) (B ∪ T)) (d : ℤ) (h * K) := by
  obtain ⟨a, ha⟩ := hlong
  refine ⟨a + c + (q : ℤ) * zhi, ?_⟩
  intro x hx
  obtain ⟨n, hn, rfl⟩ := mem_arithmeticProgression.mp hx
  let j : Fin h := ⟨n % h, Nat.mod_lt n hh⟩
  let i : ℕ := n / h
  have hi : i < K := by
    apply (Nat.div_lt_iff_lt_mul hh).2
    simpa [i, Nat.mul_comm] using hn
  have hdiffnonneg : 0 ≤ zhi - z j := sub_nonneg.mpr (hzhi j)
  have hdiffle : zhi - z j ≤ zhi - zlo := sub_le_sub_left (hzlo j) zhi
  have hdiffNat : (zhi - z j).toNat ≤ (zhi - zlo).toNat :=
    Int.toNat_le_toNat hdiffle
  let k : ℕ := (zhi - z j).toNat + i
  have hk : k < L := by
    dsimp [k]
    omega
  have hxlong : a + (q : ℤ) * (k : ℕ) ∈ restrictedSumset t B :=
    ha (mem_arithmeticProgression.mpr ⟨k, hk, rfl⟩)
  have hxsum := add_restrictedSumsets_disjoint_residueSubgroup hBT hxlong (hwmem j)
  have hn_decomp : h * i + (j : ℕ) = n := by
    simpa [i, j] using Nat.div_add_mod n h
  have hk_cast : (k : ℤ) = zhi - z j + (i : ℕ) := by
    dsimp [k]
    push_cast
    rw [Int.toNat_of_nonneg hdiffnonneg]
  have heq :
      a + (q : ℤ) * (k : ℕ) + w j =
        a + c + (q : ℤ) * zhi + (d : ℤ) * (n : ℕ) := by
    rw [hwform j, hk_cast]
    norm_cast at hn_decomp
    rw [← hn_decomp, hq]
    push_cast
    ring
  rw [← heq]
  exact hxsum

end

end Erdos874
