/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import Mathlib

/-!
# Cyclic Bohr sets for Erdős Problem 721

This file begins the construction-level part of the quantitative Roth input.
It uses the chord-length convention: a point `x : ZMod N` belongs to the
Bohr set generated by `Γ` with radius `ρ` when every character indexed by
`r ∈ Γ` satisfies `‖1 - χᵣ(x)‖ ≤ ρ`.

All statements here are elementary and fully proved.  In particular, no
regularity or density-increment theorem is postulated.
-/

namespace Erdos721

open AddChar Finset
open scoped BigOperators

namespace CyclicBohr

variable {N : ℕ} [NeZero N]

/-- The standard complex additive character of `ZMod N` indexed by `r`. -/
noncomputable def character (r : ZMod N) : AddChar (ZMod N) ℂ :=
  AddChar.zmodAddEquiv r

@[simp] lemma character_zero (r : ZMod N) : character r 0 = 1 := by
  exact AddChar.map_zero_eq_one _

@[simp] lemma character_add (r x y : ZMod N) :
    character r (x + y) = character r x * character r y := by
  exact AddChar.map_add_eq_mul _ _ _

@[simp] lemma norm_character (r x : ZMod N) : ‖character r x‖ = 1 := by
  simpa [character] using AddChar.norm_apply (AddChar.zmodAddEquiv r) x

/-- The standard cyclic character pairing is symmetric in its two inputs. -/
lemma character_comm (r x : ZMod N) : character r x = character x r := by
  obtain ⟨r, rfl⟩ := ZMod.intCast_surjective r
  obtain ⟨x, rfl⟩ := ZMod.intCast_surjective x
  change (↑(AddChar.zmod N (r : ZMod N) (x : ZMod N)) : ℂ) =
    ↑(AddChar.zmod N (x : ZMod N) (r : ZMod N))
  rw [AddChar.zmod_intCast, AddChar.zmod_intCast]
  congr 1
  ring_nf
  rfl

@[simp] lemma character_zero_index (x : ZMod N) : character 0 x = 1 := by
  rw [character_comm, character_zero]

@[simp] lemma character_add_index (r s x : ZMod N) :
    character (r + s) x = character r x * character s x := by
  rw [character_comm, character_add, character_comm x r, character_comm x s]

/-- The chord-distance triangle inequality used under addition of points. -/
lemma norm_one_sub_mul_of_norm_le_one {a b : ℂ} (ha : ‖a‖ ≤ 1) :
    ‖1 - a * b‖ ≤ ‖1 - a‖ + ‖1 - b‖ := by
  calc
    ‖1 - a * b‖ = ‖(1 - a) + a * (1 - b)‖ := by ring_nf
    _ ≤ ‖1 - a‖ + ‖a * (1 - b)‖ := norm_add_le _ _
    _ ≤ ‖1 - a‖ + ‖1 - b‖ := by
      gcongr
      exact (norm_mul_le _ _).trans (mul_le_of_le_one_left (norm_nonneg _) ha)

/-- A finite-frequency cyclic Bohr set with a uniform chord radius. -/
structure Set (N : ℕ) [NeZero N] where
  frequencies : Finset (ZMod N)
  radius : ℝ
  radius_nonneg : 0 ≤ radius

namespace Set

/-- The underlying finite subset of the cyclic group. -/
noncomputable def carrier (B : Set N) : Finset (ZMod N) :=
  Finset.univ.filter fun x ↦
    ∀ r ∈ B.frequencies, ‖1 - character r x‖ ≤ B.radius

instance : Membership (ZMod N) (Set N) := ⟨fun B x ↦ x ∈ B.carrier⟩

@[simp] lemma mem_carrier {B : Set N} {x : ZMod N} :
    x ∈ B.carrier ↔
      ∀ r ∈ B.frequencies, ‖1 - character r x‖ ≤ B.radius := by
  simp [carrier]

lemma mem_iff {B : Set N} {x : ZMod N} :
    x ∈ B ↔ ∀ r ∈ B.frequencies, ‖1 - character r x‖ ≤ B.radius :=
  mem_carrier

/-- The rank is the number of frequencies. -/
def rank (B : Set N) : ℕ := B.frequencies.card

/-- Dilation scales the chord radius and leaves frequencies unchanged. -/
def dilate (ρ : ℝ) (B : Set N) : Set N where
  frequencies := B.frequencies
  radius := |ρ| * B.radius
  radius_nonneg := mul_nonneg (abs_nonneg _) B.radius_nonneg

/-- The Bohr set with prescribed frequencies and uniform radius. -/
def ofFrequencies (Γ : Finset (ZMod N)) (ρ : ℝ) (hρ : 0 ≤ ρ) : Set N where
  frequencies := Γ
  radius := ρ
  radius_nonneg := hρ

/-- A uniform-radius refinement of two cyclic Bohr sets.  Its frequencies are
the union and its radius is the smaller of the two radii. -/
def meet (B C : Set N) : Set N where
  frequencies := B.frequencies ∪ C.frequencies
  radius := min B.radius C.radius
  radius_nonneg := le_min B.radius_nonneg C.radius_nonneg

@[simp] lemma frequencies_ofFrequencies (Γ : Finset (ZMod N)) (ρ : ℝ) (hρ : 0 ≤ ρ) :
    (ofFrequencies Γ ρ hρ).frequencies = Γ := rfl

@[simp] lemma radius_ofFrequencies (Γ : Finset (ZMod N)) (ρ : ℝ) (hρ : 0 ≤ ρ) :
    (ofFrequencies Γ ρ hρ).radius = ρ := rfl

@[simp] lemma rank_ofFrequencies (Γ : Finset (ZMod N)) (ρ : ℝ) (hρ : 0 ≤ ρ) :
    (ofFrequencies Γ ρ hρ).rank = Γ.card := rfl

@[simp] lemma frequencies_meet (B C : Set N) :
    (B.meet C).frequencies = B.frequencies ∪ C.frequencies := rfl

@[simp] lemma radius_meet (B C : Set N) :
    (B.meet C).radius = min B.radius C.radius := rfl

lemma rank_meet_le (B C : Set N) : (B.meet C).rank ≤ B.rank + C.rank := by
  exact Finset.card_union_le _ _

@[simp] lemma frequencies_dilate (ρ : ℝ) (B : Set N) :
    (B.dilate ρ).frequencies = B.frequencies := rfl

@[simp] lemma radius_dilate (ρ : ℝ) (B : Set N) :
    (B.dilate ρ).radius = |ρ| * B.radius := rfl

@[simp] lemma rank_dilate (ρ : ℝ) (B : Set N) :
    (B.dilate ρ).rank = B.rank := rfl

/-- Zero belongs to every cyclic Bohr set. -/
@[simp] lemma zero_mem (B : Set N) : (0 : ZMod N) ∈ B := by
  rw [mem_iff]
  intro r hr
  simp [B.radius_nonneg]

/-- Every cyclic Bohr set is nonempty. -/
lemma carrier_nonempty (B : Set N) : B.carrier.Nonempty :=
  ⟨0, B.zero_mem⟩

lemma card_pos (B : Set N) : 0 < B.carrier.card :=
  Finset.card_pos.mpr B.carrier_nonempty

/-- Cyclic Bohr sets are symmetric. -/
lemma neg_mem_iff (B : Set N) (x : ZMod N) : -x ∈ B ↔ x ∈ B := by
  rw [mem_iff, mem_iff]
  have hnorm (z : ℂ) : ‖1 - (starRingEnd ℂ) z‖ = ‖1 - z‖ := by
    simpa using (RCLike.norm_conj (1 - z))
  constructor
  · intro h r hr
    have hr' := h r hr
    rw [AddChar.map_neg_eq_conj, hnorm] at hr'
    exact hr'
  · intro h r hr
    rw [AddChar.map_neg_eq_conj, hnorm]
    exact h r hr

/-- Addition sends `B(Γ,ρ) × B(Γ,σ)` into `B(Γ,ρ+σ)`. -/
lemma add_mem_of_mem {B₁ B₂ B₃ : Set N}
    (hfreq₁ : B₃.frequencies ⊆ B₁.frequencies)
    (hfreq₂ : B₃.frequencies ⊆ B₂.frequencies)
    (hradius : B₁.radius + B₂.radius ≤ B₃.radius)
    {x y : ZMod N} (hx : x ∈ B₁) (hy : y ∈ B₂) : x + y ∈ B₃ := by
  rw [mem_iff] at hx hy ⊢
  intro r hr
  calc
    ‖1 - character r (x + y)‖ =
        ‖1 - character r x * character r y‖ := by rw [character_add]
    _ ≤ ‖1 - character r x‖ + ‖1 - character r y‖ :=
      norm_one_sub_mul_of_norm_le_one (by rw [norm_character])
    _ ≤ B₁.radius + B₂.radius := add_le_add (hx r (hfreq₁ hr)) (hy r (hfreq₂ hr))
    _ ≤ B₃.radius := hradius

/-- In particular, the sum of two dilates lies in the dilate by the sum of
their nonnegative scaling factors. -/
lemma add_mem_dilate {B : Set N} {ρ σ : ℝ} (hρ : 0 ≤ ρ) (hσ : 0 ≤ σ)
    {x y : ZMod N} (hx : x ∈ B.dilate ρ) (hy : y ∈ B.dilate σ) :
    x + y ∈ B.dilate (ρ + σ) := by
  apply add_mem_of_mem (B₁ := B.dilate ρ) (B₂ := B.dilate σ)
      (B₃ := B.dilate (ρ + σ))
  · simp
  · simp
  · simp [abs_of_nonneg hρ, abs_of_nonneg hσ, abs_of_nonneg (add_nonneg hρ hσ), add_mul]
  · exact hx
  · exact hy

/-- Subtraction obeys the same dilation rule because Bohr sets are symmetric. -/
lemma sub_mem_dilate {B : Set N} {ρ σ : ℝ} (hρ : 0 ≤ ρ) (hσ : 0 ≤ σ)
    {x y : ZMod N} (hx : x ∈ B.dilate ρ) (hy : y ∈ B.dilate σ) :
    x - y ∈ B.dilate (ρ + σ) := by
  rw [sub_eq_add_neg]
  apply add_mem_dilate hρ hσ hx
  exact (B.dilate σ).neg_mem_iff y |>.2 hy

/-- Increasing the radius enlarges a Bohr set. -/
lemma carrier_mono {B₁ B₂ : Set N} (hfreq : B₂.frequencies ⊆ B₁.frequencies)
    (hradius : B₁.radius ≤ B₂.radius) : B₁.carrier ⊆ B₂.carrier := by
  intro x hx
  rw [mem_carrier] at hx ⊢
  intro r hr
  exact (hx r (hfreq hr)).trans hradius

/-- The uniform-radius meet refines its left input. -/
lemma carrier_meet_subset_left (B C : Set N) : (B.meet C).carrier ⊆ B.carrier := by
  apply carrier_mono
  · exact Finset.subset_union_left
  · exact min_le_left _ _

/-- The uniform-radius meet refines its right input. -/
lemma carrier_meet_subset_right (B C : Set N) : (B.meet C).carrier ⊆ C.carrier := by
  apply carrier_mono
  · exact Finset.subset_union_right
  · exact min_le_right _ _

/-- Nonnegative dilations are monotone in the scale. -/
lemma dilate_mono (B : Set N) {ρ σ : ℝ} (hρ : 0 ≤ ρ) (hρσ : ρ ≤ σ) :
    (B.dilate ρ).carrier ⊆ (B.dilate σ).carrier := by
  apply carrier_mono
  · simp
  · have hσ : 0 ≤ σ := hρ.trans hρσ
    simp only [radius_dilate, ge_iff_le]
    rw [abs_of_nonneg hρ, abs_of_nonneg hσ]
    exact mul_le_mul_of_nonneg_right hρσ B.radius_nonneg

/-- Chord distance is at most two, so radius at least two gives the whole
cyclic group. -/
lemma carrier_eq_univ_of_two_le_radius (B : Set N) (hB : 2 ≤ B.radius) :
    B.carrier = Finset.univ := by
  apply Finset.eq_univ_of_forall
  intro x
  rw [mem_carrier]
  intro r hr
  calc
    ‖1 - character r x‖ ≤ ‖(1 : ℂ)‖ + ‖character r x‖ := norm_sub_le _ _
    _ = 2 := by rw [norm_character]; norm_num
    _ ≤ B.radius := hB

/-! ## Control of the signed span -/

/-- A product of unit-disc complex numbers remains close to one by at most
the sum of the individual errors. -/
lemma norm_one_sub_prod_le_sum {ι : Type*} [DecidableEq ι]
    (s : Finset ι) (f : ι → ℂ) (hf : ∀ i ∈ s, ‖f i‖ ≤ 1) :
    ‖1 - ∏ i ∈ s, f i‖ ≤ ∑ i ∈ s, ‖1 - f i‖ := by
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.prod_insert ha, Finset.sum_insert ha]
      exact (norm_one_sub_mul_of_norm_le_one (hf a (by simp))).trans
        (add_le_add le_rfl (ih fun i hi ↦ hf i (by simp [hi])))

/-- The character indexed by a finite sum is the product of the indexed
characters. -/
lemma character_sum {ι : Type*} [DecidableEq ι] (s : Finset ι)
    (f : ι → ZMod N) (x : ZMod N) :
    character (∑ i ∈ s, f i) x = ∏ i ∈ s, character (f i) x := by
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih => simp [ha, ih, character_add_index]

/-- Negating a frequency conjugates the corresponding character. -/
@[simp] lemma character_neg_index (r x : ZMod N) :
    character (-r) x = (starRingEnd ℂ) (character r x) := by
  rw [character_comm, AddChar.map_neg_eq_conj, character_comm]

@[simp]
lemma norm_one_sub_character_neg_index (r x : ZMod N) :
    ‖1 - character (-r) x‖ = ‖1 - character r x‖ := by
  rw [character_neg_index]
  simpa using (RCLike.norm_conj (1 - character r x))

/-- The `{-1,0,1}`-span of the frequencies of a Bohr set. -/
def signedSpan (B : Set N) : _root_.Set (ZMod N) :=
  B.frequencies.addSpan

/-- Membership in a Bohr set controls every character in the signed span of
its frequencies, losing only a factor equal to the rank.  This is the exact
elementary estimate used after Chang's spectral lemma. -/
lemma norm_one_sub_character_le_rank_mul {B : Set N} {r x : ZMod N}
    (hr : r ∈ B.signedSpan) (hx : x ∈ B) :
    ‖1 - character r x‖ ≤ B.rank * B.radius := by
  rw [signedSpan] at hr
  obtain ⟨ε, hε, hsum⟩ := Finset.mem_addSpan.mp hr
  rw [← hsum]
  rw [character_sum]
  calc
    ‖1 - ∏ g ∈ B.frequencies, character (ε g • g) x‖ ≤
        ∑ g ∈ B.frequencies, ‖1 - character (ε g • g) x‖ :=
      norm_one_sub_prod_le_sum B.frequencies (fun g ↦ character (ε g • g) x)
        (fun g hg ↦ by rw [norm_character])
    _ ≤ ∑ _g ∈ B.frequencies, B.radius := by
      apply Finset.sum_le_sum
      intro g hg
      rcases hε g with hneg | hzero | hone
      · rw [hneg, neg_one_zsmul, norm_one_sub_character_neg_index]
        exact mem_iff.mp hx g hg
      · simp [hzero, B.radius_nonneg]
      · simpa [hone] using mem_iff.mp hx g hg
    _ = B.rank * B.radius := by simp [rank]

/-- If all dissociated subsets of a frequency set have cardinality at most
`d`, a subset of at most `d` frequencies generates the whole set and the
associated Bohr set controls every original frequency.  This is the purely
combinatorial extraction step in Chang's spectral lemma. -/
theorem exists_small_bohr_controlling_of_dissociated_card_le
    (S : Finset (ZMod N)) (d : ℕ) (ρ : ℝ) (hρ : 0 ≤ ρ)
    (hdiss : ∀ Δ : Finset (ZMod N), Δ ⊆ S →
      AddDissociated (Δ : _root_.Set (ZMod N)) → Δ.card ≤ d) :
    ∃ B : Set N,
      B.frequencies ⊆ S ∧ B.rank ≤ d ∧
        ∀ r ∈ S, ∀ x ∈ B,
          ‖1 - character r x‖ ≤ (d : ℝ) * ρ := by
  obtain ⟨Δ, hΔS, hΔcard, hSspan⟩ :=
    Finset.exists_subset_addSpan_card_le_of_forall_addDissociated hdiss
  let B := ofFrequencies Δ ρ hρ
  refine ⟨B, ?_, ?_, ?_⟩
  · simpa [B] using hΔS
  · simpa [B] using hΔcard
  · intro r hr x hx
    have hrspan : r ∈ B.signedSpan := by
      simpa [B, signedSpan] using hSspan hr
    have hcontrol := norm_one_sub_character_le_rank_mul hrspan hx
    have hrank : (B.rank : ℝ) ≤ d := by exact_mod_cast hΔcard
    calc
      ‖1 - character r x‖ ≤ B.rank * B.radius := hcontrol
      _ ≤ (d : ℝ) * ρ := by
        simpa [B] using mul_le_mul_of_nonneg_right hrank hρ

/-- The same extraction with the constructed radius and the sharper
`rank * radius` character bound retained.  This form is useful when the
radius is chosen adaptively after the frequency set is known. -/
theorem exists_small_bohr_controlling_of_dissociated_card_le_sharp
    (S : Finset (ZMod N)) (d : ℕ) (ρ : ℝ) (hρ : 0 ≤ ρ)
    (hdiss : ∀ Δ : Finset (ZMod N), Δ ⊆ S →
      AddDissociated (Δ : _root_.Set (ZMod N)) → Δ.card ≤ d) :
    ∃ B : Set N,
      B.radius = ρ ∧ B.frequencies ⊆ S ∧ B.rank ≤ d ∧
        ∀ r ∈ S, ∀ x ∈ B,
          ‖1 - character r x‖ ≤ (B.rank : ℝ) * ρ := by
  obtain ⟨Δ, hΔS, hΔcard, hSspan⟩ :=
    Finset.exists_subset_addSpan_card_le_of_forall_addDissociated hdiss
  let B := ofFrequencies Δ ρ hρ
  refine ⟨B, rfl, ?_, ?_, ?_⟩
  · simpa [B] using hΔS
  · simpa [B] using hΔcard
  · intro r hr x hx
    have hrspan : r ∈ B.signedSpan := by
      simpa [B, signedSpan] using hSspan hr
    simpa [B] using norm_one_sub_character_le_rank_mul hrspan hx

end Set
end CyclicBohr
end Erdos721
