/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/
import Mathlib

/-!
# From finite linear covers to finiteness of nondegenerate unit equations

This file isolates the elementary induction which follows the Subspace
Theorem.  The deep input is deliberately an argument: for every affine unit
equation of arity at least two, its nondegenerate solutions are contained in
finitely many proper rational linear hyperplanes.  The conclusion is that the
set of nondegenerate solutions is finite.

The formulation is independent of the particular finitely generated group.
It will be applied to the subgroup of `ℚˣ` generated by `-1`, `2`, and `3`.
-/

namespace Erdos407.FiniteCover

open scoped BigOperators

variable (U : Subgroup ℚˣ)

/-- A weighted subsum of a tuple of elements of `U`. -/
def subsum {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (x : ι → U) (I : Finset ι) : ℚ :=
  ∑ i ∈ I, a i * ((x i : ℚˣ) : ℚ)

/-- The affine equation `∑ i, a i x i = 1`. -/
def IsSolution {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (x : ι → U) : Prop :=
  subsum U a x Finset.univ = 1

/-- No nonempty subsum of the left hand side vanishes. -/
def IsNondegenerate {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (x : ι → U) : Prop :=
  ∀ I : Finset ι, I.Nonempty → subsum U a x I ≠ 0

/-- The nondegenerate solutions of a rational affine unit equation. -/
def solutions {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) : Set (ι → U) :=
  {x | IsSolution U a x ∧ IsNondegenerate U a x}

/--
The qualitative output of the Subspace Theorem used in the elementary
induction.  A nonzero coefficient vector cuts out a proper linear
hyperplane.  Thus this says that the nondegenerate solutions of every affine
unit equation of arity at least two lie in a finite union of proper linear
subspaces.
-/
def HasFiniteLinearCovers : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι],
    2 ≤ Fintype.card ι → ∀ a : ι → ℚ, (∀ i, a i ≠ 0) →
      ∃ B : Finset (ι → ℚ),
        (∀ b ∈ B, b ≠ 0) ∧
        ∀ x ∈ solutions U a,
          ∃ b ∈ B, subsum U b x Finset.univ = 0

/-- The finite-linear-cover property restricted to equations of arity at
most `N`.  This bounded form is sufficient when an application only creates
unit equations from blocks inside a fixed finite ambient relation. -/
def HasFiniteLinearCoversUpTo (N : ℕ) : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι],
    2 ≤ Fintype.card ι → Fintype.card ι ≤ N →
      ∀ a : ι → ℚ, (∀ i, a i ≠ 0) →
        ∃ B : Finset (ι → ℚ),
          (∀ b ∈ B, b ≠ 0) ∧
          ∀ x ∈ solutions U a,
            ∃ b ∈ B, subsum U b x Finset.univ = 0

private theorem solutions_finite_of_card_le_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (ha : ∀ i, a i ≠ 0) (hcard : Fintype.card ι ≤ 1) :
    (solutions U a).Finite := by
  cases isEmpty_or_nonempty ι with
  | inl hempty =>
      have hnone : solutions U a = ∅ := by
        ext x
        simp only [solutions, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
        rintro ⟨hx, _⟩
        simpa [IsSolution, subsum] using hx
      simp [hnone]
  | inr hnonempty =>
      let : Nonempty ι := hnonempty
      let : Subsingleton ι :=
        Fintype.card_le_one_iff_subsingleton.mp hcard
      apply Set.Subsingleton.finite
      intro x hx y hy
      funext i
      apply Subtype.ext
      apply Units.ext
      have huniv : (Finset.univ : Finset ι) = {i} := by
        ext j
        simp [Subsingleton.elim j i]
      have hx' : a i * ((x i : ℚˣ) : ℚ) = 1 := by
        simpa [solutions, IsSolution, subsum, huniv] using hx.1
      have hy' : a i * ((y i : ℚˣ) : ℚ) = 1 := by
        simpa [solutions, IsSolution, subsum, huniv] using hy.1
      exact mul_left_cancel₀ (ha i) (hx'.trans hy'.symm)

/-- A minimal vanishing block for a homogeneous relation.  Restricting the
block to the support of `b` rules out spurious one-element blocks coming from
zero coefficients. -/
def IsMinimalVanishing {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : ι → ℚ) (x : ι → U) (J : Finset ι) : Prop :=
  J.Nonempty ∧
    (∀ i ∈ J, b i ≠ 0) ∧
    subsum U b x J = 0 ∧
    ∀ K : Finset ι, K.Nonempty → K ⊂ J → subsum U b x K ≠ 0

private theorem exists_minimalVanishing
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : ι → ℚ) (hb : b ≠ 0) (x : ι → U)
    (hzero : subsum U b x Finset.univ = 0) :
    ∃ J : Finset ι, IsMinimalVanishing U b x J := by
  let supp : Finset ι := Finset.univ.filter fun i => b i ≠ 0
  have hsupp_nonempty : supp.Nonempty := by
    by_contra hs
    have hs : supp = ∅ := Finset.not_nonempty_iff_eq_empty.mp hs
    apply hb
    funext i
    have hi : i ∉ supp := by simp [hs]
    simpa [supp] using hi
  have hsupp_zero : subsum U b x supp = 0 := by
    rw [← hzero]
    apply Finset.sum_subset (by simp [supp])
    intro i hi hi'
    have hbi : b i = 0 := by
      simpa [supp, hi] using hi'
    simp [subsum, hbi]
  let candidates : Finset (Finset ι) :=
    supp.powerset.filter fun J => J.Nonempty ∧ subsum U b x J = 0
  have hcandidates : candidates.Nonempty := by
    refine ⟨supp, ?_⟩
    simp [candidates, hsupp_nonempty, hsupp_zero]
  obtain ⟨J, hJ, hmin⟩ :=
    candidates.exists_min_image Finset.card hcandidates
  have hJall : J ⊆ supp ∧ J.Nonempty ∧ subsum U b x J = 0 := by
    simpa [candidates] using hJ
  have hJsub : J ⊆ supp := hJall.1
  have hJdata : J.Nonempty ∧ subsum U b x J = 0 := hJall.2
  refine ⟨J, hJdata.1, ?_, hJdata.2, ?_⟩
  · intro i hi
    have : i ∈ supp := hJsub hi
    simpa [supp] using this
  · intro K hKne hKproper hKzero
    have hKsubsupp : K ⊆ supp := hKproper.le.trans hJsub
    have hKcand : K ∈ candidates := by
      simp [candidates, hKsubsupp, hKne, hKzero]
    have hcardle : J.card ≤ K.card := hmin K hKcand
    exact (not_lt_of_ge hcardle) (Finset.card_lt_card hKproper)

private theorem minimalVanishing_card_two_le
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {b : ι → ℚ} {x : ι → U} {J : Finset ι}
    (hJ : IsMinimalVanishing U b x J) : 2 ≤ J.card := by
  rcases hJ.1 with ⟨j, hj⟩
  have hcardpos : 0 < J.card := Finset.card_pos.mpr ⟨j, hj⟩
  suffices J.card ≠ 1 by omega
  intro hcard
  obtain ⟨k, hk⟩ := Finset.card_eq_one.mp hcard
  have hjk : j = k := by
    simpa [hk] using hj
  have hsingle : J = {j} := by simpa [hjk] using hk
  have hbj : b j ≠ 0 := hJ.2.1 j hj
  have hxj : (((x j : ℚˣ) : ℚ)) ≠ 0 := Units.ne_zero (x j : ℚˣ)
  have : b j * ((x j : ℚˣ) : ℚ) = 0 := by
    simpa [subsum, hsingle] using hJ.2.2.1
  exact mul_ne_zero hbj hxj this

private def ratioTuple {ι : Type*} [Fintype ι] [DecidableEq ι]
    (x : ι → U) (J : Finset ι) (j : ι) : {i // i ∈ J.erase j} → U :=
  fun i => x i.1 / x j

private def ratioCoeff {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : ι → ℚ) (J : Finset ι) (j : ι) : {i // i ∈ J.erase j} → ℚ :=
  fun i => -(b i.1 / b j)

private theorem ratioCoeff_ne_zero
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {b : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    (hJ : IsMinimalVanishing U b x J) (hj : j ∈ J) :
    ∀ i, ratioCoeff b J j i ≠ 0 := by
  intro i
  simp only [ratioCoeff, neg_ne_zero]
  exact div_ne_zero (hJ.2.1 i.1 (Finset.mem_of_mem_erase i.2)) (hJ.2.1 j hj)

private theorem ratio_sum_eq
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : ι → ℚ) (x : ι → U) (j : ι) (K : Finset ι) :
    (∑ i ∈ K, -(b i / b j) * (((x i / x j : U) : ℚˣ) : ℚ)) =
      -(∑ i ∈ K, b i * ((x i : ℚˣ) : ℚ)) /
        (b j * ((x j : ℚˣ) : ℚ)) := by
  calc
    (∑ i ∈ K, -(b i / b j) * (((x i / x j : U) : ℚˣ) : ℚ)) =
        ∑ i ∈ K, -(b i * ((x i : ℚˣ) : ℚ)) /
          (b j * ((x j : ℚˣ) : ℚ)) := by
            apply Finset.sum_congr rfl
            intro i hi
            push_cast
            ring
    _ = -(∑ i ∈ K, b i * ((x i : ℚˣ) : ℚ)) /
        (b j * ((x j : ℚˣ) : ℚ)) := by
          rw [← Finset.sum_neg_distrib, ← Finset.sum_div]

private theorem ratioTuple_isSolution
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {b : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    (hJ : IsMinimalVanishing U b x J) (hj : j ∈ J) :
    IsSolution U (ratioCoeff b J j) (ratioTuple U x J j) := by
  have hbj : b j ≠ 0 := hJ.2.1 j hj
  have hxj : (((x j : ℚˣ) : ℚ)) ≠ 0 := Units.ne_zero (x j : ℚˣ)
  have hrest :
      (∑ i ∈ J.erase j, b i * ((x i : ℚˣ) : ℚ)) =
        -(b j * ((x j : ℚˣ) : ℚ)) := by
    have hsplit := Finset.sum_erase_add J
      (fun i => b i * ((x i : ℚˣ) : ℚ)) hj
    have hzero := hJ.2.2.1
    simp only [subsum] at hzero
    linarith
  rw [IsSolution, subsum]
  simp only [ratioCoeff, ratioTuple]
  rw [← Finset.sum_subtype (J.erase j) (by simp)
    (fun i => -(b i / b j) * (((x i / x j : U) : ℚˣ) : ℚ))]
  have hden : b j * ((x j : ℚˣ) : ℚ) ≠ 0 := mul_ne_zero hbj hxj
  rw [ratio_sum_eq U b x j (J.erase j), hrest]
  field_simp

private theorem ratioTuple_isNondegenerate
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {b : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    (hJ : IsMinimalVanishing U b x J) (hj : j ∈ J) :
    IsNondegenerate U (ratioCoeff b J j) (ratioTuple U x J j) := by
  intro L hL
  let K : Finset ι := L.image fun i => i.1
  have hKne : K.Nonempty := hL.image _
  have hKsub : K ⊆ J.erase j := by
    intro i hi
    rcases Finset.mem_image.mp hi with ⟨k, hk, rfl⟩
    exact k.2
  have hKproper : K ⊂ J := by
    refine ⟨hKsub.trans (Finset.erase_subset j J), ?_⟩
    intro hJK
    have hjK : j ∈ K := hJK hj
    exact (Finset.mem_erase.mp (hKsub hjK)).1 rfl
  have hKzero := hJ.2.2.2 K hKne hKproper
  rw [subsum]
  simp only [ratioCoeff, ratioTuple]
  rw [← Finset.sum_image (f := fun i =>
      -(b i / b j) * (((x i / x j : U) : ℚˣ) : ℚ))
    (g := fun i : {i // i ∈ J.erase j} => i.1)
    Subtype.val_injective.injOn]
  change (∑ i ∈ K,
    -(b i / b j) * (((x i / x j : U) : ℚˣ) : ℚ)) ≠ 0
  have hbj : b j ≠ 0 := hJ.2.1 j hj
  have hxj : (((x j : ℚˣ) : ℚ)) ≠ 0 := Units.ne_zero (x j : ℚˣ)
  have hden : b j * ((x j : ℚˣ) : ℚ) ≠ 0 := mul_ne_zero hbj hxj
  intro hz
  apply hKzero
  simp only [subsum]
  have :
      -(∑ i ∈ K, b i * ((x i : ℚˣ) : ℚ)) /
          (b j * ((x j : ℚˣ) : ℚ)) = 0 := by
    rw [← ratio_sum_eq U b x j K]
    exact hz
  rcases div_eq_zero_iff.mp this with hnum | hdenzero
  · exact neg_eq_zero.mp hnum
  · exact (hden hdenzero).elim

private def blockWeight {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (J : Finset ι) (j : ι) (z : {i // i ∈ J.erase j} → U) : ℚ :=
  a j + ∑ i, a i.1 * ((z i : ℚˣ) : ℚ)

private def retained {ι : Type*} [Fintype ι] [DecidableEq ι]
    (J : Finset ι) (j : ι) : Finset ι :=
  insert j (Finset.univ \ J)

private def collapsedCoeff {ι : Type*} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (J : Finset ι) (j : ι) (z : {i // i ∈ J.erase j} → U) :
    {i // i ∈ retained J j} → ℚ :=
  fun i => if i.1 = j then blockWeight U a J j z else a i.1

private def collapsedTuple {ι : Type*} [Fintype ι] [DecidableEq ι]
    (x : ι → U) (J : Finset ι) (j : ι) :
    {i // i ∈ retained J j} → U :=
  fun i => x i.1

private def expandBlock {ι : Type*} [Fintype ι] [DecidableEq ι]
    (J : Finset ι) (j : ι) (L : Finset {i // i ∈ retained J j}) : Finset ι :=
  let L₀ := L.image fun i => i.1
  if j ∈ L₀ then J ∪ L₀.erase j else L₀

private theorem blockWeight_mul_eq_subsum
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {a : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    {z : {i // i ∈ J.erase j} → U} (hj : j ∈ J)
    (hratio : ratioTuple U x J j = z) :
    blockWeight U a J j z * ((x j : ℚˣ) : ℚ) = subsum U a x J := by
  have hterm (i : {i // i ∈ J.erase j}) :
      a i.1 * ((z i : ℚˣ) : ℚ) * ((x j : ℚˣ) : ℚ) =
        a i.1 * ((x i.1 : ℚˣ) : ℚ) := by
    have hi := congrFun hratio i
    have hix : x i.1 = z i * x j := by
      exact eq_mul_of_div_eq hi
    rw [hix]
    push_cast
    ring
  rw [subsum, blockWeight, add_mul]
  have hsums :
      (∑ i, a i.1 * ((z i : ℚˣ) : ℚ)) * ((x j : ℚˣ) : ℚ) =
        ∑ i ∈ J.erase j, a i * ((x i : ℚˣ) : ℚ) := by
    rw [Finset.sum_mul]
    rw [Finset.sum_subtype (J.erase j) (fun _ => Iff.rfl)
      (fun i => a i * ((x i : ℚˣ) : ℚ))]
    apply Finset.sum_congr rfl
    intro i hi
    exact hterm i
  rw [hsums, add_comm, Finset.sum_erase_add J
    (fun i => a i * ((x i : ℚˣ) : ℚ)) hj]

private theorem collapsed_subsum_eq
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {a : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    {z : {i // i ∈ J.erase j} → U} (hj : j ∈ J)
    (hratio : ratioTuple U x J j = z)
    (L : Finset {i // i ∈ retained J j}) :
    subsum U (collapsedCoeff U a J j z) (collapsedTuple U x J j) L =
      subsum U a x (expandBlock J j L) := by
  let L₀ : Finset ι := L.image fun i => i.1
  have hsumMap :
      subsum U (collapsedCoeff U a J j z) (collapsedTuple U x J j) L =
        ∑ i ∈ L₀, (if i = j then blockWeight U a J j z else a i) *
          ((x i : ℚˣ) : ℚ) := by
    rw [subsum]
    simp only [collapsedCoeff, collapsedTuple]
    rw [← Finset.sum_image (f := fun i =>
        (if i = j then blockWeight U a J j z else a i) * ((x i : ℚˣ) : ℚ))
      (g := fun i : {i // i ∈ retained J j} => i.1)
      Subtype.val_injective.injOn]
  rw [hsumMap]
  have houtside {i : ι} (hi : i ∈ L₀) (hij : i ≠ j) : i ∉ J := by
    rcases Finset.mem_image.mp hi with ⟨k, hk, rfl⟩
    have hkret := k.2
    simp only [retained, Finset.mem_insert, Finset.mem_sdiff,
      Finset.mem_univ, true_and] at hkret
    exact hkret.resolve_left hij
  by_cases hjL : j ∈ L₀
  · rw [expandBlock]
    simp only [L₀, hjL, if_true]
    have hdis : Disjoint J (L₀.erase j) := by
      refine Finset.disjoint_left.mpr ?_
      intro i hiJ hiL
      exact (houtside (Finset.mem_of_mem_erase hiL) (Finset.mem_erase.mp hiL).1) hiJ
    rw [subsum, Finset.sum_union hdis]
    have hblock := blockWeight_mul_eq_subsum U (a := a) hj hratio
    rw [subsum] at hblock
    calc
      (∑ i ∈ L₀, (if i = j then blockWeight U a J j z else a i) *
          ((x i : ℚˣ) : ℚ)) =
          blockWeight U a J j z * ((x j : ℚˣ) : ℚ) +
            ∑ i ∈ L₀.erase j, a i * ((x i : ℚˣ) : ℚ) := by
        rw [← Finset.sum_erase_add L₀
          (fun i => (if i = j then blockWeight U a J j z else a i) *
            ((x i : ℚˣ) : ℚ)) hjL, add_comm]
        apply congrArg₂ (· + ·)
        · simp
        · apply Finset.sum_congr rfl
          intro i hi
          simp [(Finset.mem_erase.mp hi).1]
      _ = (∑ i ∈ J, a i * ((x i : ℚˣ) : ℚ)) +
            ∑ i ∈ L₀.erase j, a i * ((x i : ℚˣ) : ℚ) := by rw [hblock]
  · rw [expandBlock]
    simp only [L₀, hjL, if_false, subsum]
    apply Finset.sum_congr rfl
    intro i hi
    simp [ne_of_mem_of_not_mem hi hjL]

private theorem collapsedTuple_mem_solutions
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {a : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    {z : {i // i ∈ J.erase j} → U} (hj : j ∈ J)
    (hx : x ∈ solutions U a) (hratio : ratioTuple U x J j = z) :
    collapsedTuple U x J j ∈ solutions U (collapsedCoeff U a J j z) := by
  constructor
  · rw [IsSolution, collapsed_subsum_eq U hj hratio]
    have hexpand : expandBlock J j Finset.univ = Finset.univ := by
      have himage :
          Finset.image (fun i : {i // i ∈ retained J j} => i.1) Finset.univ =
            retained J j := by
        ext i
        simp
      rw [expandBlock, himage]
      have hjretained : j ∈ retained J j := by
        simp [retained]
      rw [if_pos hjretained]
      ext i
      simp only [Finset.mem_union, Finset.mem_erase, Finset.mem_univ, iff_true]
      by_cases hi : i ∈ J
      · exact Or.inl hi
      · exact Or.inr ⟨fun hij => hi (hij ▸ hj), by simp [retained, hi]⟩
    rw [hexpand]
    exact hx.1
  · intro L hL
    rw [collapsed_subsum_eq U hj hratio]
    apply hx.2
    rw [expandBlock]
    let L₀ : Finset ι := L.image fun i => i.1
    have hL₀ : L₀.Nonempty := hL.image _
    by_cases h : j ∈ L₀
    · simp only [L₀, h, if_true]
      exact ⟨j, Finset.mem_union_left _ hj⟩
    · simp only [L₀, h, if_false]
      exact hL₀

private theorem collapsedCoeff_ne_zero
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {a : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    {z : {i // i ∈ J.erase j} → U} (ha : ∀ i, a i ≠ 0)
    (hj : j ∈ J) (hx : x ∈ solutions U a)
    (hratio : ratioTuple U x J j = z) :
    ∀ i, collapsedCoeff U a J j z i ≠ 0 := by
  intro i
  rw [collapsedCoeff]
  split_ifs with hij
  · have hsub : subsum U a x J ≠ 0 := hx.2 J ⟨j, hj⟩
    have hw := blockWeight_mul_eq_subsum U (a := a) hj hratio
    intro hzero
    apply hsub
    rw [← hw, hzero, zero_mul]
  · exact ha i.1

private theorem ratio_index_card_lt
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {J : Finset ι} {j : ι} (hj : j ∈ J) :
    Fintype.card {i // i ∈ J.erase j} < Fintype.card ι := by
  rw [Fintype.card_coe]
  apply Finset.card_lt_card
  refine ⟨Finset.subset_univ _, ?_⟩
  intro h
  have : j ∈ J.erase j := h (Finset.mem_univ j)
  exact (Finset.mem_erase.mp this).1 rfl

private theorem retained_index_card_lt
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {b : ι → ℚ} {x : ι → U} {J : Finset ι} {j : ι}
    (hJ : IsMinimalVanishing U b x J) (hj : j ∈ J) :
    Fintype.card {i // i ∈ retained J j} < Fintype.card ι := by
  rw [Fintype.card_coe]
  apply Finset.card_lt_card
  refine ⟨Finset.subset_univ _, ?_⟩
  obtain ⟨k, hkJ, hkj⟩ : ∃ k ∈ J, k ≠ j := by
    by_contra hn
    push_neg at hn
    have hsub : J ⊆ {j} := fun k hk => by simp [hn k hk]
    have : J.card ≤ 1 := (Finset.card_le_card hsub).trans (by simp)
    exact (not_lt_of_ge this) (minimalVanishing_card_two_le U hJ)
  intro h
  have hkret : k ∈ retained J j := h (Finset.mem_univ k)
  simp only [retained, Finset.mem_insert, Finset.mem_sdiff,
    Finset.mem_univ, true_and] at hkret
  exact hkret.elim (fun h => hkj h) (fun h => h hkJ)

private theorem ratio_collapse_injective
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {J : Finset ι} {j : ι} (hj : j ∈ J) :
    Function.Injective (fun x : ι → U =>
      (ratioTuple U x J j, collapsedTuple U x J j)) := by
  intro x y hxy
  funext i
  by_cases hij : i = j
  · subst i
    exact congrFun (congrArg Prod.snd hxy) ⟨j, by simp [retained]⟩
  by_cases hiJ : i ∈ J
  · have hiErase : i ∈ J.erase j := Finset.mem_erase.mpr ⟨hij, hiJ⟩
    let k : {i // i ∈ J.erase j} := ⟨i, hiErase⟩
    have hr := congrFun (congrArg Prod.fst hxy) k
    have hp := congrFun (congrArg Prod.snd hxy) ⟨j, by simp [retained]⟩
    change ratioTuple U x J j k = ratioTuple U y J j k at hr
    change x j = y j at hp
    have hx : x i = ratioTuple U x J j k * x j := eq_mul_of_div_eq rfl
    have hy : y i = ratioTuple U y J j k * y j := eq_mul_of_div_eq rfl
    rw [hx, hy, hr, hp]
  · exact congrFun (congrArg Prod.snd hxy)
      ⟨i, by simp [retained, hij, hiJ]⟩

private theorem minimalBlockSet_finite
    {ι : Type} [Fintype ι] [DecidableEq ι]
    {a b : ι → ℚ} (ha : ∀ i, a i ≠ 0) {J : Finset ι} {j : ι}
    (hj : j ∈ J)
    (hrec : ∀ (κ : Type) [Fintype κ] [DecidableEq κ],
      Fintype.card κ < Fintype.card ι → ∀ c : κ → ℚ,
        (∀ i, c i ≠ 0) → (solutions U c).Finite) :
    {x | x ∈ solutions U a ∧ IsMinimalVanishing U b x J}.Finite := by
  let T : Set (ι → U) :=
    {x | x ∈ solutions U a ∧ IsMinimalVanishing U b x J}
  by_cases hT : T.Nonempty
  · obtain ⟨x₀, hx₀, hJ₀⟩ := hT
    let β := ratioCoeff b J j
    have hβne : ∀ i, β i ≠ 0 := ratioCoeff_ne_zero U hJ₀ hj
    have hratioFinite : (solutions U β).Finite :=
      hrec {i // i ∈ J.erase j} (ratio_index_card_lt hj) β hβne
    let Z : Set ({i // i ∈ J.erase j} → U) :=
      (fun x => ratioTuple U x J j) '' T
    have hZsub : Z ⊆ solutions U β := by
      rintro z ⟨x, hxT, rfl⟩
      exact ⟨ratioTuple_isSolution U hxT.2 hj,
        ratioTuple_isNondegenerate U hxT.2 hj⟩
    have hZ : Z.Finite := hratioFinite.subset hZsub
    let P : Set (({i // i ∈ J.erase j} → U) ×
        ({i // i ∈ retained J j} → U)) :=
      ⋃ z ∈ Z, ({z} : Set ({i // i ∈ J.erase j} → U)) ×ˢ
        solutions U (collapsedCoeff U a J j z)
    have hP : P.Finite := by
      apply hZ.biUnion
      intro z hz
      rcases hz with ⟨xz, hxzT, hzdef⟩
      have hcoeff : ∀ i, collapsedCoeff U a J j z i ≠ 0 :=
        collapsedCoeff_ne_zero U ha hj hxzT.1 hzdef
      have hcollapsed :
          (solutions U (collapsedCoeff U a J j z)).Finite :=
        hrec {i // i ∈ retained J j}
          (retained_index_card_lt U hxzT.2 hj)
          (collapsedCoeff U a J j z) hcoeff
      exact (Set.finite_singleton z).prod hcollapsed
    let F : (ι → U) →
        ({i // i ∈ J.erase j} → U) × ({i // i ∈ retained J j} → U) :=
      fun x => (ratioTuple U x J j, collapsedTuple U x J j)
    have hFsub : F '' T ⊆ P := by
      rintro _ ⟨x, hxT, rfl⟩
      simp only [P]
      apply Set.mem_iUnion_of_mem (ratioTuple U x J j)
      apply Set.mem_iUnion_of_mem ⟨x, hxT, rfl⟩
      exact ⟨rfl, collapsedTuple_mem_solutions U hj hxT.1 rfl⟩
    have hFfinite : (F '' T).Finite := hP.subset hFsub
    have hTfinite : T.Finite :=
      Set.Finite.of_finite_image hFfinite (ratio_collapse_injective U hj).injOn
    exact hTfinite
  · have : T = ∅ := Set.not_nonempty_iff_eq_empty.mp hT
    simpa [T, this]

/-- Finite linear covers imply finiteness of every nondegenerate affine unit
equation.  This is the elementary induction-on-arity step in the usual proof
of the qualitative S-unit theorem. -/
theorem solutions_finite_of_finiteLinearCovers
    (hcover : HasFiniteLinearCovers U)
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (ha : ∀ i, a i ≠ 0) :
    (solutions U a).Finite := by
  generalize hn : Fintype.card ι = n
  induction n using Nat.strong_induction_on generalizing ι with
  | h n ih =>
      by_cases hsmall : Fintype.card ι ≤ 1
      · exact solutions_finite_of_card_le_one U a ha hsmall
      have htwo : 2 ≤ Fintype.card ι := by omega
      obtain ⟨B, hBnonzero, hBcover⟩ := hcover ι htwo a ha
      let fiber (b : ι → ℚ) : Set (ι → U) :=
        {x | x ∈ solutions U a ∧ subsum U b x Finset.univ = 0}
      have hfiber (b : ι → ℚ) (hbB : b ∈ B) : (fiber b).Finite := by
        have hb : b ≠ 0 := hBnonzero b hbB
        let pieces (J : Finset ι) (j : ι) : Set (ι → U) :=
          if hj : j ∈ J then
            {x | x ∈ solutions U a ∧ IsMinimalVanishing U b x J}
          else ∅
        have hpieces : (⋃ J : Finset ι, ⋃ j : ι, pieces J j).Finite := by
          apply Set.finite_iUnion
          intro J
          apply Set.finite_iUnion
          intro j
          simp only [pieces]
          split_ifs with hj
          · apply minimalBlockSet_finite U ha hj
            intro κ _ _ hκ c hc
            exact ih (Fintype.card κ) (by rw [← hn]; exact hκ) c hc rfl
          · exact Set.finite_empty
        apply hpieces.subset
        intro x hx
        obtain ⟨J, hJ⟩ := exists_minimalVanishing U b hb x hx.2
        obtain ⟨j, hj⟩ := hJ.1
        apply Set.mem_iUnion_of_mem J
        apply Set.mem_iUnion_of_mem j
        simp only [pieces, hj, dite_true]
        exact ⟨hx.1, hJ⟩
      let covered : Set (ι → U) := ⋃ b ∈ (B : Set (ι → ℚ)), fiber b
      have hcovered : covered.Finite := by
        exact B.finite_toSet.biUnion fun b hb => hfiber b hb
      apply hcovered.subset
      intro x hx
      obtain ⟨b, hbB, hbzero⟩ := hBcover x hx
      apply Set.mem_iUnion_of_mem b
      apply Set.mem_iUnion_of_mem hbB
      exact ⟨hx, hbzero⟩

/-- Finite linear covers through arity `N` imply finiteness of every
nondegenerate affine unit equation whose arity is at most `N`.  All recursive
equations in the minimal-block induction have strictly smaller arity, so the
bounded cover hypothesis is preserved. -/
theorem solutions_finite_of_hasFiniteLinearCoversUpTo
    {N : ℕ} (hcover : HasFiniteLinearCoversUpTo U N)
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (hcard : Fintype.card ι ≤ N)
    (a : ι → ℚ) (ha : ∀ i, a i ≠ 0) :
    (solutions U a).Finite := by
  generalize hn : Fintype.card ι = n
  induction n using Nat.strong_induction_on generalizing ι with
  | h n ih =>
      by_cases hsmall : Fintype.card ι ≤ 1
      · exact solutions_finite_of_card_le_one U a ha hsmall
      have htwo : 2 ≤ Fintype.card ι := by omega
      obtain ⟨B, hBnonzero, hBcover⟩ := hcover ι htwo hcard a ha
      let fiber (b : ι → ℚ) : Set (ι → U) :=
        {x | x ∈ solutions U a ∧ subsum U b x Finset.univ = 0}
      have hfiber (b : ι → ℚ) (hbB : b ∈ B) : (fiber b).Finite := by
        have hb : b ≠ 0 := hBnonzero b hbB
        let pieces (J : Finset ι) (j : ι) : Set (ι → U) :=
          if hj : j ∈ J then
            {x | x ∈ solutions U a ∧ IsMinimalVanishing U b x J}
          else ∅
        have hpieces : (⋃ J : Finset ι, ⋃ j : ι, pieces J j).Finite := by
          apply Set.finite_iUnion
          intro J
          apply Set.finite_iUnion
          intro j
          simp only [pieces]
          split_ifs with hj
          · apply minimalBlockSet_finite U ha hj
            intro κ _ _ hκ c hc
            have hκN : Fintype.card κ ≤ N := by
              exact (Nat.le_of_lt hκ).trans hcard
            exact ih (Fintype.card κ) (by rw [← hn]; exact hκ) hκN c hc rfl
          · exact Set.finite_empty
        apply hpieces.subset
        intro x hx
        obtain ⟨J, hJ⟩ := exists_minimalVanishing U b hb x hx.2
        obtain ⟨j, hj⟩ := hJ.1
        apply Set.mem_iUnion_of_mem J
        apply Set.mem_iUnion_of_mem j
        simp only [pieces, hj, dite_true]
        exact ⟨hx.1, hJ⟩
      let covered : Set (ι → U) := ⋃ b ∈ (B : Set (ι → ℚ)), fiber b
      have hcovered : covered.Finite := by
        exact B.finite_toSet.biUnion fun b hb => hfiber b hb
      apply hcovered.subset
      intro x hx
      obtain ⟨b, hbB, hbzero⟩ := hBcover x hx
      apply Set.mem_iUnion_of_mem b
      apply Set.mem_iUnion_of_mem hbB
      exact ⟨hx, hbzero⟩

/-- Alias with the hypothesis name spelled out, for downstream applications. -/
theorem solutions_finite_of_hasFiniteLinearCovers
    (hcover : HasFiniteLinearCovers U)
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (a : ι → ℚ) (ha : ∀ i, a i ≠ 0) :
    (solutions U a).Finite :=
  solutions_finite_of_finiteLinearCovers U hcover a ha

#print axioms solutions_finite_of_finiteLinearCovers
#check solutions_finite_of_hasFiniteLinearCovers
#print axioms solutions_finite_of_hasFiniteLinearCoversUpTo

end Erdos407.FiniteCover
