/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
import ErdosProblems.Erdos407.FiniteCover
import ErdosProblems.Erdos407.GeneralPosition
import ErdosProblems.Erdos407.PadicProduct
import ErdosProblems.Erdos407.Primitive

/-!
# The rational three-place Subspace-Theorem application

This file states the exact qualitative, specialized Subspace-Theorem input
needed for Erdős Problem 407 and proves the elementary implication from that
input to finite linear covers for the rational unit group generated by
`-1`, `2`, and `3`.

The deep input is an ordinary proposition supplied by the analytic file. Its
points are primitive
integer vectors and its inequality is the product, over the Archimedean,
`2`-adic, and `3`-adic places, of the coordinate-and-weighted-sum forms after
one largest form is omitted at each place.  The general-position assertion
for those forms is proved below.
-/

namespace Erdos407.SubspaceApplication

open scoped BigOperators

open Erdos407

namespace U23

/-- A rational unit with a specified nonzero value. -/
private def unitOf (q : ℚ) (hq : q ≠ 0) : ℚˣ := Units.mk0 q hq

/-- The three standard generators, regarded as rational units. -/
def generators : Set ℚˣ :=
  {unitOf (-1) (by norm_num), unitOf 2 (by norm_num), unitOf 3 (by norm_num)}

private theorem isUnit23_one : PadicProduct.IsUnit23 (1 : ℚ) := by
  exact ⟨0, 0, Or.inl (by simp)⟩

private theorem isUnit23_mul {x y : ℚ}
    (hx : PadicProduct.IsUnit23 x) (hy : PadicProduct.IsUnit23 y) :
    PadicProduct.IsUnit23 (x * y) := by
  rcases hx with ⟨a, b, rfl | rfl⟩ <;>
    rcases hy with ⟨c, d, rfl | rfl⟩
  · refine ⟨a + c, b + d, Or.inl ?_⟩
    rw [zpow_add₀ (by norm_num : (2 : ℚ) ≠ 0) a c,
      zpow_add₀ (by norm_num : (3 : ℚ) ≠ 0) b d]
    ring
  · refine ⟨a + c, b + d, Or.inr ?_⟩
    rw [zpow_add₀ (by norm_num : (2 : ℚ) ≠ 0) a c,
      zpow_add₀ (by norm_num : (3 : ℚ) ≠ 0) b d]
    ring
  · refine ⟨a + c, b + d, Or.inr ?_⟩
    rw [zpow_add₀ (by norm_num : (2 : ℚ) ≠ 0) a c,
      zpow_add₀ (by norm_num : (3 : ℚ) ≠ 0) b d]
    ring
  · refine ⟨a + c, b + d, Or.inl ?_⟩
    rw [zpow_add₀ (by norm_num : (2 : ℚ) ≠ 0) a c,
      zpow_add₀ (by norm_num : (3 : ℚ) ≠ 0) b d]
    ring

private theorem isUnit23_inv {x : ℚ} (hx : PadicProduct.IsUnit23 x) :
    PadicProduct.IsUnit23 x⁻¹ := by
  rcases hx with ⟨a, b, rfl | rfl⟩
  · exact ⟨-a, -b, Or.inl (by simp only [zpow_neg, mul_inv_rev]; ring)⟩
  · exact ⟨-a, -b, Or.inr (by simp only [inv_neg, zpow_neg, mul_inv_rev]; ring)⟩

/-- The rational multiplicative subgroup generated by `-1`, `2`, and `3`,
presented by its explicit signed-power membership criterion. -/
def group : Subgroup ℚˣ where
  carrier := {u | PadicProduct.IsUnit23 ((u : ℚˣ) : ℚ)}
  one_mem' := isUnit23_one
  mul_mem' := fun hx hy => by simpa using isUnit23_mul hx hy
  inv_mem' := fun hx => by simpa using isUnit23_inv hx

/-- Every element of the generated group is a signed rational `{2,3}`-unit. -/
theorem isUnit23 (u : group) : PadicProduct.IsUnit23 (((u : ℚˣ) : ℚ)) := by
  exact u.2

private theorem negOne_mem : unitOf (-1) (by norm_num) ∈ group := by
  exact ⟨0, 0, Or.inr (by simp [unitOf])⟩

private theorem two_mem : unitOf 2 (by norm_num) ∈ group := by
  exact ⟨1, 0, Or.inl (by simp [unitOf])⟩

private theorem three_mem : unitOf 3 (by norm_num) ∈ group := by
  exact ⟨0, 1, Or.inl (by simp [unitOf])⟩

/-- Conversely, every signed rational `{2,3}`-unit belongs to the generated
subgroup. -/
theorem mem_group_of_isUnit23 {q : ℚ} (hq : PadicProduct.IsUnit23 q) :
    unitOf q hq.ne_zero ∈ group := hq

/-- Package a signed rational `{2,3}`-unit as an element of the generated
subgroup. -/
def ofIsUnit23 (q : ℚ) (hq : PadicProduct.IsUnit23 q) : group :=
  ⟨unitOf q hq.ne_zero, mem_group_of_isUnit23 hq⟩

@[simp] theorem coe_ofIsUnit23 (q : ℚ) (hq : PadicProduct.IsUnit23 q) :
    (((ofIsUnit23 q hq : group) : ℚˣ) : ℚ) = q := rfl

end U23

/-! ## The three places and the coordinate--sum forms -/

/-- The places retained for the `{2,3}`-unit equation. -/
inductive Place23
  | infinite
  | two
  | three
  deriving DecidableEq

/-- The normalized absolute value at one of the three retained places. -/
def placeNorm : Place23 → ℚ → ℚ
  | .infinite => PadicProduct.archNorm
  | .two => padicNorm 2
  | .three => padicNorm 3

theorem placeNorm_mul (v : Place23) (q r : ℚ) :
    placeNorm v (q * r) = placeNorm v q * placeNorm v r := by
  cases v with
  | infinite => exact PadicProduct.archNorm_mul q r
  | two => exact padicNorm.mul q r
  | three => exact padicNorm.mul q r

/-- Coordinate forms together with the coefficient-weighted total form.
`none` labels the total form and `some i` labels the `i`th coordinate. -/
def weightedForm {ι : Type*} [Fintype ι] (a : ι → ℚ) :
    Option ι → ((ι → ℚ) →ₗ[ℚ] ℚ)
  | none =>
      { toFun := fun x => ∑ i, a i * x i
        map_add' := by intros; simp only [Pi.add_apply]; rw [← Finset.sum_add_distrib];
                       apply Finset.sum_congr rfl; intros; ring
        map_smul' := by intros; simp only [Pi.smul_apply, smul_eq_mul, RingHom.id_apply];
                        rw [Finset.mul_sum]; apply Finset.sum_congr rfl; intros; ring }
  | some i => LinearMap.proj i

@[simp] theorem weightedForm_none_apply {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (x : ι → ℚ) :
    weightedForm a none x = ∑ i, a i * x i := rfl

@[simp] theorem weightedForm_some_apply {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (i : ι) (x : ι → ℚ) :
    weightedForm a (some i) x = x i := rfl

/- The direct coefficient proof below is retained as development notes while
the final bridge uses the general-position theorem packaged by the analytic
Subspace-Theorem interface.

/-- The weighted coordinate-and-sum forms are in general position: omitting
any one leaves a basis-sized linearly independent family. -/
theorem discarded_generic_weightedForm_proof {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (ha : ∀ i, a i ≠ 0) (k : Option ι) :
    LinearIndependent ℚ
      (fun j : {j : Option ι // j ≠ k} => weightedForm a j.1) := by
  classical
  rw [Fintype.linearIndependent_iff]
  intro c hc j
  cases k with
  | none =>
      rcases j with ⟨j, hj⟩
      cases j with
      | none => exact False.elim (hj rfl)
      | some i =>
          have h := LinearMap.congr_fun hc (Pi.single i 1)
          have hsum :
              (∑ t : {t : Option ι // t ≠ none},
                c t * weightedForm a t.1 (Pi.single i 1)) =
                c ⟨some i, by simp⟩ := by
            calc
              _ = c ⟨some i, by simp⟩ *
                    weightedForm a (some i) (Pi.single i 1) := by
                apply Fintype.sum_eq_single ⟨some i, by simp⟩
                intro t hti
                rcases t with ⟨t, ht⟩
                cases t with
                | none => exact False.elim (ht rfl)
                | some l =>
                    have hli : l ≠ i := by
                      intro hli
                      apply hti
                      subst l
                      rfl
                    simp [Pi.single_apply, hli]
              _ = c ⟨some i, by simp⟩ := by simp
          simpa [hsum] using h
  | some i₀ =>
      let nidx : {t : Option ι // t ≠ some i₀} := ⟨none, by simp⟩
      have hcnone : c nidx = 0 := by
        have h := LinearMap.congr_fun hc (Pi.single i₀ 1)
        have hsum :
            (∑ t : {t : Option ι // t ≠ some i₀},
              c t * weightedForm a t.1 (Pi.single i₀ 1)) = c nidx * a i₀ := by
          calc
            _ = c nidx * weightedForm a none (Pi.single i₀ 1) := by
              apply Fintype.sum_eq_single nidx
              intro t htn
              rcases t with ⟨t, ht⟩
              cases t with
              | none => exact False.elim (htn (by apply Subtype.ext; rfl))
              | some l =>
                  have hli : l ≠ i₀ := by
                    intro hli
                    exact ht (by simp [hli])
                  simp [Pi.single_apply, hli]
            _ = c nidx * a i₀ := by simp
        have : c nidx * a i₀ = 0 := by simpa [hsum] using h
        exact (mul_eq_zero.mp this).resolve_right (ha i₀)
      rcases j with ⟨j, hj⟩
      cases j with
      | none => exact hcnone
      | some i =>
          have hii₀ : i ≠ i₀ := by
            intro h
            exact hj (by simp [h])
          have h := LinearMap.congr_fun hc (Pi.single i 1)
          let tidx : {t : Option ι // t ≠ some i₀} := ⟨some i, by simp [hii₀]⟩
          have hsum :
              (∑ t : {t : Option ι // t ≠ some i₀},
                c t * weightedForm a t.1 (Pi.single i 1)) =
                c nidx * a i + c tidx := by
            let f : {t : Option ι // t ≠ some i₀} → ℚ := fun t =>
              c t * weightedForm a t.1 (Pi.single i 1)
            have hnmem : nidx ∈ (Finset.univ : Finset {t : Option ι // t ≠ some i₀}) :=
              Finset.mem_univ _
            have htmem : tidx ∈ (Finset.univ.erase nidx :
                Finset {t : Option ι // t ≠ some i₀}) := by
              simp [tidx, nidx]
            have herase : (∑ t ∈ (Finset.univ.erase nidx), f t) = f tidx := by
              apply Finset.sum_eq_single tidx
              · intro t ht hti
                rcases t with ⟨t, htvalid⟩
                cases t with
                | none =>
                    exact False.elim ((Finset.mem_erase.mp ht).1 (by apply Subtype.ext; rfl))
                | some l =>
                    have hli : l ≠ i := by
                      intro hli
                      apply hti
                      subst l
                      rfl
                    simp [f, Pi.single_apply, hli]
              · intro hnot
                exact False.elim (hnot htmem)
            have hsplit := Finset.sum_erase_add (Finset.univ :
              Finset {t : Option ι // t ≠ some i₀}) f hnmem
            rw [herase] at hsplit
            change (∑ t, f t) = _
            rw [← hsplit]
            simp [f, tidx, nidx, add_comm]
          simpa [hsum, hcnone] using h

-/

/-- General-position predicate for the coefficient-weighted coordinate and
sum forms.  This is the exact nonsingularity hypothesis in the specialized
Subspace-Theorem statement. -/
def WeightedFormsInGeneralPosition {ι : Type*} [Fintype ι]
    (a : ι → ℚ) : Prop :=
  ∀ k : Option ι,
    LinearIndependent ℚ
      (fun j : {j : Option ι // j ≠ k} => weightedForm a j.1)

private def diagonalEquiv {n : ℕ} (a : Fin n → ℚ) (ha : ∀ i, a i ≠ 0) :
    (Fin n → ℚ) ≃ₗ[ℚ] (Fin n → ℚ) where
  toFun x i := a i * x i
  invFun x i := (a i)⁻¹ * x i
  left_inv x := by ext i; simp [ha i]
  right_inv x := by ext i; simp [ha i]
  map_add' x y := by ext i; simp [mul_add]
  map_smul' q x := by ext i; simp; ring

/-- For `Fin n`, the coefficient-weighted coordinate-and-sum forms are in
general position.  This packages the diagonal-change-of-variables reduction
to `GeneralPosition.coordSumForm_omit_linearIndependent`. -/
theorem weightedFormsInGeneralPosition_fin {n : ℕ} (a : Fin n → ℚ)
    (ha : ∀ i, a i ≠ 0) : WeightedFormsInGeneralPosition a := by
  classical
  intro k
  let D := diagonalEquiv a ha
  let base : {j : Option (Fin n) // j ≠ k} →
      ((Fin n → ℚ) →ₗ[ℚ] ℚ) := fun j => GeneralPosition.coordSumForm n j.1
  have hbase : LinearIndependent ℚ base := by
    exact GeneralPosition.coordSumForm_omit_linearIndependent n k
  have hdual : LinearIndependent ℚ (D.dualMap ∘ base) :=
    hbase.map' D.dualMap.toLinearMap (LinearMap.ker_eq_bot.mpr D.dualMap.injective)
  let scale : {j : Option (Fin n) // j ≠ k} → ℚˣ := fun j =>
    match j.1 with
    | none => Units.mk0 1 one_ne_zero
    | some i => Units.mk0 (a i)⁻¹ (inv_ne_zero (ha i))
  have hscaled := hdual.units_smul scale
  have heq :
      (scale • (D.dualMap ∘ base)) =
        (fun j : {j : Option (Fin n) // j ≠ k} => weightedForm a j.1) := by
    funext j
    apply LinearMap.ext
    intro x
    rcases j with ⟨j, hj⟩
    cases j with
    | none =>
        simp [scale, D, base, diagonalEquiv, weightedForm,
          LinearEquiv.dualMap_apply, GeneralPosition.coordSumForm]
    | some i =>
        simp [scale, D, base, diagonalEquiv, weightedForm,
          LinearEquiv.dualMap_apply, GeneralPosition.coordSumForm, ha i]
  rw [← heq]
  exact hscaled

/-- Pointwise form of `weightedFormsInGeneralPosition_fin`, convenient when
constructing one omitted-form basis at each retained place. -/
theorem weightedForm_omit_linearIndependent_fin {n : ℕ} (a : Fin n → ℚ)
    (ha : ∀ i, a i ≠ 0) (k : Option (Fin n)) :
    LinearIndependent ℚ
      (fun j : {j : Option (Fin n) // j ≠ k} => weightedForm a j.1) :=
  weightedFormsInGeneralPosition_fin a ha k

/-! ## The exact three-place product attached to the forms -/

/-- Product of all `card ι + 1` form values over the three retained places. -/
def fullFormProduct23 {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (x : ι → ℚ) : ℚ :=
  ∏ j : Option ι, PadicProduct.normProduct23 (weightedForm a j x)

/-- Scaling all coordinates scales the full form product by the expected
`card ι + 1`st power of the three-place norm product. -/
theorem fullFormProduct23_smul {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (q : ℚ) (x : ι → ℚ) :
    fullFormProduct23 a (q • x) =
      PadicProduct.normProduct23 q ^ (Fintype.card ι + 1) *
        fullFormProduct23 a x := by
  classical
  unfold fullFormProduct23
  have hform (j : Option ι) : weightedForm a j (q • x) = q * weightedForm a j x := by
    exact (weightedForm a j).map_smul q x
  simp only [hform, PadicProduct.normProduct23_mul, Finset.prod_mul_distrib,
    Finset.prod_const, Finset.card_univ, Fintype.card_option]

/-- A primitive projective point all of whose coordinate forms and weighted
sum form become `{2,3}`-units after one common rational rescaling. -/
def IsThreePlaceUnitPoint {ι : Type*} [Fintype ι]
    (a : ι → ℚ) (z : ι → ℤ) : Prop :=
  Primitive.IsPrimitive z ∧
    ∃ q : ℚ, q ≠ 0 ∧
      (∀ i, PadicProduct.IsUnit23 (q * (z i : ℚ))) ∧
      PadicProduct.IsUnit23 (q * ∑ i, a i * (z i : ℚ))

/-- Bézout primitivity used by the normalization file implies the gcd-one
primitivity used by the p-adic height interface. -/
theorem isPadicPrimitive_of_isPrimitive {ι : Type*} [Fintype ι]
    {z : ι → ℤ} (hz : Primitive.IsPrimitive z) :
    PadicProduct.IsPrimitive z := by
  classical
  obtain ⟨u, hu⟩ := hz
  have hd : Finset.univ.gcd z ∣ ∑ i, u i * z i := by
    apply Finset.dvd_sum
    intro i hi
    exact dvd_mul_of_dvd_right (Finset.gcd_dvd hi) (u i)
  have hd1 : Finset.univ.gcd z ∣ (1 : ℤ) := by simpa [hu] using hd
  unfold PadicProduct.IsPrimitive
  rw [← Finset.normalize_gcd, normalize_eq_one]
  exact isUnit_iff_dvd_one.mpr hd1

/-- The product formula gives the exact full-form product identity used in
the Subspace-Theorem inequality. -/
theorem fullFormProduct23_eq_of_threePlaceUnitPoint
    {ι : Type*} [Fintype ι] {a : ι → ℚ} {z : ι → ℤ}
    (hz : IsThreePlaceUnitPoint a z) :
    ∃ q : ℚ, q ≠ 0 ∧
      PadicProduct.normProduct23 q ^ (Fintype.card ι + 1) *
        fullFormProduct23 a (fun i => (z i : ℚ)) = 1 := by
  classical
  rcases hz.2 with ⟨q, hq, hcoord, hsum⟩
  refine ⟨q, hq, ?_⟩
  rw [← fullFormProduct23_smul]
  unfold fullFormProduct23
  apply Finset.prod_eq_one
  intro j hj
  cases j with
  | none =>
      simpa [weightedForm_none_apply, Finset.mul_sum] using hsum.normProduct23_eq_one
  | some i =>
      simpa using (hcoord i).normProduct23_eq_one

/-! ## Specialized finite-cover statement and its application -/

/-- The precise qualitative rational p-adic Subspace-Theorem consequence
used here.  The preceding product identity and general-position theorem are
the two hypotheses entering the standard proof at the places
`infinite, 2, 3`.

This is deliberately a proposition proved by the formalized three-place
Subspace Theorem. -/
def SpecializedPadicSubspaceFiniteCover : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι],
    2 ≤ Fintype.card ι → ∀ a : ι → ℚ, (∀ i, a i ≠ 0) →
      ∃ B : Finset (ι → ℚ),
        (∀ b ∈ B, b ≠ 0) ∧
        ∀ z : ι → ℤ, IsThreePlaceUnitPoint a z →
          ∃ b ∈ B, ∑ i, b i * (z i : ℚ) = 0

private theorem finiteLinearCover_of_threePlaceCover
    {ι : Type} [Fintype ι] [DecidableEq ι]
    (hcard : 2 ≤ Fintype.card ι) (a : ι → ℚ) (ha : ∀ i, a i ≠ 0)
    (hcover : ∃ B : Finset (ι → ℚ),
      (∀ b ∈ B, b ≠ 0) ∧
      ∀ z : ι → ℤ, IsThreePlaceUnitPoint a z →
        ∃ b ∈ B, ∑ i, b i * (z i : ℚ) = 0) :
    ∃ B : Finset (ι → ℚ),
      (∀ b ∈ B, b ≠ 0) ∧
      ∀ x ∈ FiniteCover.solutions U23.group a,
        ∃ b ∈ B, FiniteCover.subsum U23.group b x Finset.univ = 0 := by
  obtain ⟨B, hBne, hBcover⟩ := hcover
  refine ⟨B, hBne, ?_⟩
  intro x hx
  let u : ι → ℚ := fun i => (((x i : U23.group) : ℚˣ) : ℚ)
  have : Nonempty ι := Fintype.card_pos_iff.mp (by omega)
  have hu : u ≠ 0 := by
    intro hzero
    obtain ⟨i⟩ := ‹Nonempty ι›
    have hi := congrFun hzero i
    exact Units.ne_zero (x i : ℚˣ) (by simpa [u] using hi)
  let z : ι → ℤ := Primitive.normalize u
  let q : ℚ := Primitive.normalizationScale u
  have hqu : u = q • Primitive.intCastVec z := by
    exact Primitive.eq_normalizationScale_smul u
  have hzpoint : IsThreePlaceUnitPoint a z := by
    refine ⟨Primitive.normalize_primitive hu, q,
      Primitive.normalizationScale_ne_zero hu, ?_, ?_⟩
    · intro i
      have hi : q * (z i : ℚ) = u i := by
        simpa [Primitive.intCastVec, Pi.smul_apply, smul_eq_mul] using
          (congrFun hqu i).symm
      rw [hi]
      exact U23.isUnit23 (x i)
    · have hsumu : ∑ i, a i * u i = 1 := by
        simpa [FiniteCover.solutions, FiniteCover.IsSolution,
          FiniteCover.subsum, u] using hx.1
      have hscale : q * ∑ i, a i * (z i : ℚ) = ∑ i, a i * u i := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro i hi
        have hui := congrFun hqu i
        simp only [Primitive.intCastVec, Pi.smul_apply, smul_eq_mul] at hui
        rw [hui]
        ring
      rw [hscale, hsumu]
      exact ⟨0, 0, Or.inl (by simp)⟩
  obtain ⟨b, hbB, hbzero⟩ := hBcover z hzpoint
  refine ⟨b, hbB, ?_⟩
  unfold FiniteCover.subsum
  have hrel : (∑ i, b i * u i) = 0 := by
    calc
      (∑ i, b i * u i) = q * ∑ i, b i * (z i : ℚ) := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro i hi
        have hui := congrFun hqu i
        simp only [Primitive.intCastVec, Pi.smul_apply, smul_eq_mul] at hui
        rw [hui]
        ring
      _ = 0 := by rw [hbzero, mul_zero]
  simpa [u] using hrel

/-- The specialized three-place Subspace Theorem supplies exactly the finite
linear-cover property required by the abstract unit-equation induction. -/
theorem hasFiniteLinearCovers_of_specializedPadicSubspace
    (hST : SpecializedPadicSubspaceFiniteCover) :
    FiniteCover.HasFiniteLinearCovers U23.group := by
  intro ι _ _ hcard a ha
  exact finiteLinearCover_of_threePlaceCover hcard a ha (hST ι hcard a ha)

/-- Bounded-arity version of the specialized three-place finite-cover
statement.  The resolution of Erdős 407 only needs `N = 5`. -/
def SpecializedPadicSubspaceFiniteCoverUpTo (N : ℕ) : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι],
    2 ≤ Fintype.card ι → Fintype.card ι ≤ N →
      ∀ a : ι → ℚ, (∀ i, a i ≠ 0) →
        ∃ B : Finset (ι → ℚ),
          (∀ b ∈ B, b ≠ 0) ∧
          ∀ z : ι → ℤ, IsThreePlaceUnitPoint a z →
            ∃ b ∈ B, ∑ i, b i * (z i : ℚ) = 0

/-- A bounded specialized Subspace-Theorem conclusion gives the bounded
linear-cover property used by the bounded unit-equation induction. -/
theorem hasFiniteLinearCoversUpTo_of_specializedPadicSubspace {N : ℕ}
    (hST : SpecializedPadicSubspaceFiniteCoverUpTo N) :
    FiniteCover.HasFiniteLinearCoversUpTo U23.group N := by
  intro ι _ _ hlow hhigh a ha
  exact finiteLinearCover_of_threePlaceCover hlow a ha
    (hST ι hlow hhigh a ha)

#print axioms hasFiniteLinearCovers_of_specializedPadicSubspace
#print axioms hasFiniteLinearCoversUpTo_of_specializedPadicSubspace

end Erdos407.SubspaceApplication
