/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
import ErdosProblems.Erdos407.EGST
import ErdosProblems.Erdos407.SubspaceApplication

/-!
# The terminal bridge from unit equations to Erdős 407

This file carries out the last elementary passage in the proof.  A minimal
zero block in the difference of two Newman representations is divided by one
of its terms.  The remaining ratios solve a nondegenerate affine equation in
the rational group generated by `-1`, `2`, and `3`.  Finiteness of all such
affine equations therefore makes the set of projective ratios used by the
EGST reduction finite.
-/

namespace Erdos407.TerminalBridge

open scoped BigOperators

/-- The rational coefficient attached to a signed term. -/
def signCoeff (i : EGST.Six) : ℚ := (EGST.sixSign i : ℚ)

@[simp] theorem signCoeff_ne_zero (i : EGST.Six) : signCoeff i ≠ 0 := by
  cases i <;> norm_num [signCoeff, EGST.sixSign]

/-- A positive integral `{2,3}`-smooth number is a rational `{2,3}`-unit. -/
theorem isUnit23_natCast_of_smooth {m : ℕ} (hm : EGST.IsSmooth23 m) :
    PadicProduct.IsUnit23 (m : ℚ) := by
  rcases hm with ⟨a, b, rfl⟩
  refine ⟨(a : ℤ), (b : ℤ), Or.inl ?_⟩
  simp only [Nat.cast_mul, Nat.cast_pow, Nat.cast_ofNat, zpow_natCast]

/-- Package a smooth natural number as an element of the rational unit group. -/
def smoothUnit (m : ℕ) (hm : EGST.IsSmooth23 m) : SubspaceApplication.U23.group :=
  SubspaceApplication.U23.ofIsUnit23 (m : ℚ) (isUnit23_natCast_of_smooth hm)

@[simp] theorem coe_smoothUnit (m : ℕ) (hm : EGST.IsSmooth23 m) :
    ((((smoothUnit m hm : SubspaceApplication.U23.group) : ℚˣ) : ℚ)) = (m : ℚ) :=
  SubspaceApplication.U23.coe_ofIsUnit23 _ _

/-- The unit tuple underlying a six-term smooth relation. -/
def unitTuple (x : EGST.Six → ℕ) (hx : ∀ i, EGST.IsSmooth23 (x i)) :
    EGST.Six → SubspaceApplication.U23.group :=
  fun i ↦ smoothUnit (x i) (hx i)

@[simp] theorem coe_unitTuple (x : EGST.Six → ℕ)
    (hx : ∀ i, EGST.IsSmooth23 (x i)) (i : EGST.Six) :
    ((((unitTuple x hx i : SubspaceApplication.U23.group) : ℚˣ) : ℚ)) = (x i : ℚ) :=
  coe_smoothUnit _ _

/-- Divide every non-anchor coordinate of a block by its anchor. -/
def ratioTuple (x : EGST.Six → ℕ) (hx : ∀ i, EGST.IsSmooth23 (x i))
    (I : Finset EGST.Six) (b : EGST.Six) :
    {i // i ∈ I.erase b} → SubspaceApplication.U23.group :=
  fun i ↦ unitTuple x hx i.1 / unitTuple x hx b

@[simp] theorem coe_ratioTuple (x : EGST.Six → ℕ)
    (hx : ∀ i, EGST.IsSmooth23 (x i)) (I : Finset EGST.Six) (b : EGST.Six)
    (i : {i // i ∈ I.erase b}) :
    ((((ratioTuple x hx I b i : SubspaceApplication.U23.group) : ℚˣ) : ℚ)) =
      (x i.1 : ℚ) / (x b : ℚ) := by
  simp [ratioTuple]

/-- Coefficients of the affine equation obtained after division by an anchor. -/
def ratioCoeff (I : Finset EGST.Six) (b : EGST.Six) :
    {i // i ∈ I.erase b} → ℚ :=
  fun i ↦ -(signCoeff i.1 / signCoeff b)

theorem ratioCoeff_ne_zero (I : Finset EGST.Six) (b : EGST.Six) :
    ∀ i, ratioCoeff I b i ≠ 0 := by
  intro i
  exact neg_ne_zero.mpr (div_ne_zero (signCoeff_ne_zero i.1) (signCoeff_ne_zero b))

private theorem signedSum_cast (x : EGST.Six → ℕ) (I : Finset EGST.Six) :
    ((EGST.signedSum x I : ℤ) : ℚ) =
      ∑ i ∈ I, signCoeff i * (x i : ℚ) := by
  simp [EGST.signedSum, signCoeff]

private theorem ratio_sum_eq
    (x : EGST.Six → ℕ) (hx : ∀ i, EGST.IsSmooth23 (x i))
    (b : EGST.Six) (K : Finset EGST.Six) :
    (∑ i ∈ K, -(signCoeff i / signCoeff b) *
        ((((unitTuple x hx i / unitTuple x hx b : SubspaceApplication.U23.group) : ℚˣ) : ℚ))) =
      -(∑ i ∈ K, signCoeff i * (x i : ℚ)) /
        (signCoeff b * (x b : ℚ)) := by
  calc
    (∑ i ∈ K, -(signCoeff i / signCoeff b) *
        ((((unitTuple x hx i / unitTuple x hx b : SubspaceApplication.U23.group) : ℚˣ) : ℚ))) =
        ∑ i ∈ K, -(signCoeff i * (x i : ℚ)) /
          (signCoeff b * (x b : ℚ)) := by
            apply Finset.sum_congr rfl
            intro i hi
            change -(signCoeff i / signCoeff b) *
                ((x i : ℚ) / (x b : ℚ)) =
              -(signCoeff i * (x i : ℚ)) /
                (signCoeff b * (x b : ℚ))
            ring
    _ = -(∑ i ∈ K, signCoeff i * (x i : ℚ)) /
        (signCoeff b * (x b : ℚ)) := by
          rw [← Finset.sum_neg_distrib, ← Finset.sum_div]

/-- A minimal signed zero block gives an affine unit-equation solution after
division by any one of its terms. -/
theorem ratioTuple_mem_solutions
    {x : EGST.Six → ℕ} (hx : ∀ i, EGST.IsSmooth23 (x i) ∧ 0 < x i)
    {I : Finset EGST.Six} (hI : EGST.IsMinimalZeroBlock x I)
    {b : EGST.Six} (hb : b ∈ I) :
    ratioTuple x (fun i ↦ (hx i).1) I b ∈
      FiniteCover.solutions SubspaceApplication.U23.group (ratioCoeff I b) := by
  classical
  let hsmooth : ∀ i, EGST.IsSmooth23 (x i) := fun i ↦ (hx i).1
  have hxb : (x b : ℚ) ≠ 0 := by
    exact_mod_cast Nat.ne_of_gt (hx b).2
  have hden : signCoeff b * (x b : ℚ) ≠ 0 :=
    mul_ne_zero (signCoeff_ne_zero b) hxb
  constructor
  · rw [FiniteCover.IsSolution, FiniteCover.subsum]
    simp only [ratioCoeff, ratioTuple]
    rw [← Finset.sum_subtype (I.erase b) (by simp)
      (fun i ↦ -(signCoeff i / signCoeff b) *
        ((((unitTuple x hsmooth i / unitTuple x hsmooth b : SubspaceApplication.U23.group) : ℚˣ) : ℚ)))]
    have hzeroQ : ∑ i ∈ I, signCoeff i * (x i : ℚ) = 0 := by
      rw [← signedSum_cast]
      simp [hI.2.1]
    have hrest :
        (∑ i ∈ I.erase b, signCoeff i * (x i : ℚ)) =
          -(signCoeff b * (x b : ℚ)) := by
      have hsplit := Finset.sum_erase_add I
        (fun i ↦ signCoeff i * (x i : ℚ)) hb
      linarith
    rw [ratio_sum_eq x hsmooth b (I.erase b), hrest]
    field_simp
  · intro L hL
    let K : Finset EGST.Six := L.image fun i ↦ i.1
    have hKne : K.Nonempty := hL.image _
    have hKsub : K ⊆ I.erase b := by
      intro i hi
      rcases Finset.mem_image.mp hi with ⟨j, hj, rfl⟩
      exact j.2
    have hKproper : K ⊂ I := by
      refine ⟨hKsub.trans (Finset.erase_subset b I), ?_⟩
      intro hIK
      have hbK : b ∈ K := hIK hb
      exact (Finset.mem_erase.mp (hKsub hbK)).1 rfl
    have hKnz : EGST.signedSum x K ≠ 0 :=
      hI.2.2 K hKne hKproper.le hKproper.ne
    rw [FiniteCover.subsum]
    simp only [ratioCoeff, ratioTuple]
    rw [← Finset.sum_image (f := fun i ↦
        -(signCoeff i / signCoeff b) *
          ((((unitTuple x hsmooth i / unitTuple x hsmooth b : SubspaceApplication.U23.group) : ℚˣ) : ℚ)))
      (g := fun i : {i // i ∈ I.erase b} ↦ i.1)
      Subtype.val_injective.injOn]
    change (∑ i ∈ K, -(signCoeff i / signCoeff b) *
      ((((unitTuple x hsmooth i / unitTuple x hsmooth b : SubspaceApplication.U23.group) : ℚˣ) : ℚ))) ≠ 0
    rw [ratio_sum_eq x hsmooth b K]
    exact div_ne_zero (neg_ne_zero.mpr (by
      rw [← signedSum_cast]
      exact_mod_cast hKnz)) hden

/-- Finiteness of every nondegenerate affine equation over the rational
`{2,3}`-unit group. -/
def AffineU23Finiteness : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι] (a : ι → ℚ),
    (∀ i, a i ≠ 0) →
      (FiniteCover.solutions SubspaceApplication.U23.group a).Finite

/-- Bounded-arity finiteness for nondegenerate affine equations over the
rational `{2,3}`-unit group.  The terminal application below only needs
arity at most five: dividing a nonempty block of the six-term comparison by
one anchor removes that anchor. -/
def AffineU23FinitenessUpTo (N : ℕ) : Prop :=
  ∀ (ι : Type) [Fintype ι] [DecidableEq ι] (a : ι → ℚ),
    Fintype.card ι ≤ N → (∀ i, a i ≠ 0) →
      (FiniteCover.solutions SubspaceApplication.U23.group a).Finite

/-- Removing an anchor from a block of the six comparison coordinates leaves
at most five indices. -/
theorem ratioIndex_card_le_five {I : Finset EGST.Six} {b : EGST.Six}
    (hb : b ∈ I) : Fintype.card {i // i ∈ I.erase b} ≤ 5 := by
  rw [Fintype.card_coe, Finset.card_erase_of_mem hb]
  have hI : I.card ≤ 6 := by
    calc
      I.card ≤ Finset.univ.card := Finset.card_le_card (Finset.subset_univ I)
      _ = 6 := by simp [EGST.Six]
  omega

private def fixedRatioSet (I : Finset EGST.Six) (b : EGST.Six) : Set ℚ :=
  {q | ∃ z ∈ FiniteCover.solutions SubspaceApplication.U23.group (ratioCoeff I b),
    ∃ i, q = ((((z i : SubspaceApplication.U23.group) : ℚˣ) : ℚ))}

private theorem fixedRatioSet_finite (hU : AffineU23Finiteness)
    (I : Finset EGST.Six) (b : EGST.Six) : (fixedRatioSet I b).Finite := by
  classical
  let S := FiniteCover.solutions SubspaceApplication.U23.group (ratioCoeff I b)
  have hS : S.Finite := hU _ (ratioCoeff I b) (ratioCoeff_ne_zero I b)
  let : Fintype S := hS.fintype
  let f : S × {i // i ∈ I.erase b} → ℚ :=
    fun zi ↦ ((((zi.1.1 zi.2 : SubspaceApplication.U23.group) : ℚˣ) : ℚ))
  refine (Set.finite_range f).subset ?_
  rintro q ⟨z, hz, i, rfl⟩
  exact ⟨(⟨z, hz⟩, i), rfl⟩

private theorem fixedRatioSet_finite_upTo_five
    (hU : AffineU23FinitenessUpTo 5)
    (I : Finset EGST.Six) (b : EGST.Six) (hb : b ∈ I) :
    (fixedRatioSet I b).Finite := by
  classical
  let S := FiniteCover.solutions SubspaceApplication.U23.group (ratioCoeff I b)
  have hS : S.Finite :=
    hU _ (ratioCoeff I b) (ratioIndex_card_le_five hb) (ratioCoeff_ne_zero I b)
  let : Fintype S := hS.fintype
  let f : S × {i // i ∈ I.erase b} → ℚ :=
    fun zi ↦ ((((zi.1.1 zi.2 : SubspaceApplication.U23.group) : ℚˣ) : ℚ))
  refine (Set.finite_range f).subset ?_
  rintro q ⟨z, hz, i, rfl⟩
  exact ⟨(⟨z, hz⟩, i), rfl⟩

/-- The exact elementary terminal implication: affine `{2,3}`-unit equation
finiteness implies the restricted projective ratio theorem used by EGST. -/
theorem restrictedProjectiveU23_of_affine (hU : AffineU23Finiteness) :
    EGST.RestrictedProjectiveU23Finiteness := by
  classical
  let R : Set ℚ := {1} ∪ ⋃ I : Finset EGST.Six, ⋃ b : EGST.Six, fixedRatioSet I b
  have hR : R.Finite := by
    apply Set.Finite.union (Set.finite_singleton 1)
    apply Set.finite_iUnion
    intro I
    apply Set.finite_iUnion
    intro b
    exact fixedRatioSet_finite hU I b
  refine hR.subset ?_
  intro q hq
  rcases hq with ⟨x, I, a, b, hx, hI, ha, hb, rfl⟩
  by_cases hab : a = b
  · subst a
    left
    exact div_self (by exact_mod_cast Nat.ne_of_gt (hx b).2)
  · right
    refine Set.mem_iUnion.2 ⟨I, Set.mem_iUnion.2 ⟨b, ?_⟩⟩
    refine ⟨ratioTuple x (fun i ↦ (hx i).1) I b,
      ratioTuple_mem_solutions hx hI hb,
      ⟨a, Finset.mem_erase.mpr ⟨hab, ha⟩⟩, ?_⟩
    exact (coe_ratioTuple x (fun i ↦ (hx i).1) I b
      ⟨a, Finset.mem_erase.mpr ⟨hab, ha⟩⟩).symm

/-- Only affine equations of arity at most five are needed for the terminal
EGST ratio argument. -/
theorem restrictedProjectiveU23_of_affineUpToFive
    (hU : AffineU23FinitenessUpTo 5) :
    EGST.RestrictedProjectiveU23Finiteness := by
  classical
  let R : Set ℚ :=
    {1} ∪ ⋃ I : Finset EGST.Six, ⋃ b : {b // b ∈ I}, fixedRatioSet I b.1
  have hR : R.Finite := by
    apply Set.Finite.union (Set.finite_singleton 1)
    apply Set.finite_iUnion
    intro I
    apply Set.finite_iUnion
    intro b
    exact fixedRatioSet_finite_upTo_five hU I b.1 b.2
  refine hR.subset ?_
  intro q hq
  rcases hq with ⟨x, I, a, b, hx, hI, ha, hb, rfl⟩
  by_cases hab : a = b
  · subst a
    left
    exact div_self (by exact_mod_cast Nat.ne_of_gt (hx b).2)
  · right
    refine Set.mem_iUnion.2 ⟨I, Set.mem_iUnion.2 ⟨⟨b, hb⟩, ?_⟩⟩
    refine ⟨ratioTuple x (fun i ↦ (hx i).1) I b,
      ratioTuple_mem_solutions hx hI hb,
      ⟨a, Finset.mem_erase.mpr ⟨hab, ha⟩⟩, ?_⟩
    exact (coe_ratioTuple x (fun i ↦ (hx i).1) I b
      ⟨a, Finset.mem_erase.mpr ⟨hab, ha⟩⟩).symm

/-- The abstract finite-cover induction supplies the affine finiteness input
used above. -/
theorem affineU23Finiteness_of_finiteLinearCovers
    (hcover : FiniteCover.HasFiniteLinearCovers SubspaceApplication.U23.group) :
    AffineU23Finiteness := by
  intro ι _ _ a ha
  exact FiniteCover.solutions_finite_of_hasFiniteLinearCovers
    SubspaceApplication.U23.group hcover a ha

/-- The bounded finite-cover induction supplies affine finiteness through the
same arity bound. -/
theorem affineU23FinitenessUpTo_of_finiteLinearCoversUpTo {N : ℕ}
    (hcover :
      FiniteCover.HasFiniteLinearCoversUpTo SubspaceApplication.U23.group N) :
    AffineU23FinitenessUpTo N := by
  intro ι _ _ a hcard ha
  exact FiniteCover.solutions_finite_of_hasFiniteLinearCoversUpTo
    SubspaceApplication.U23.group hcover hcard a ha

/-- The specialized rational three-place Subspace Theorem implies the exact
restricted projective `{2,3}`-unit finiteness statement used by EGST. -/
theorem restrictedProjectiveU23_of_specializedPadicSubspace
    (hST : SubspaceApplication.SpecializedPadicSubspaceFiniteCover) :
    EGST.RestrictedProjectiveU23Finiteness :=
  restrictedProjectiveU23_of_affine
    (affineU23Finiteness_of_finiteLinearCovers
      (SubspaceApplication.hasFiniteLinearCovers_of_specializedPadicSubspace hST))

/-- The arity-five specialization is already sufficient for the exact
restricted projective `{2,3}`-unit theorem used by EGST. -/
theorem restrictedProjectiveU23_of_specializedPadicSubspaceUpToFive
    (hST : SubspaceApplication.SpecializedPadicSubspaceFiniteCoverUpTo 5) :
    EGST.RestrictedProjectiveU23Finiteness :=
  restrictedProjectiveU23_of_affineUpToFive
    (affineU23FinitenessUpTo_of_finiteLinearCoversUpTo
      (SubspaceApplication.hasFiniteLinearCoversUpTo_of_specializedPadicSubspace hST))

/-- All deductions from the specialized p-adic Subspace Theorem to the
literal ordered-exponent statement of Erdős Problem 407. -/
theorem erdos407_of_specializedPadicSubspace
    (hST : SubspaceApplication.SpecializedPadicSubspaceFiniteCover) :
    ∃ C : ℕ, ∀ n : ℕ, w n ≤ C :=
  EGST.erdos_407_of_restrictedProjectiveU23
    (restrictedProjectiveU23_of_specializedPadicSubspace hST)

/-- The complete terminal deduction using only dimensions/affine arities at
most five. -/
theorem erdos407_of_specializedPadicSubspaceUpToFive
    (hST : SubspaceApplication.SpecializedPadicSubspaceFiniteCoverUpTo 5) :
    ∃ C : ℕ, ∀ n : ℕ, w n ≤ C :=
  EGST.erdos_407_of_restrictedProjectiveU23
    (restrictedProjectiveU23_of_specializedPadicSubspaceUpToFive hST)

#print axioms restrictedProjectiveU23_of_affine
#print axioms restrictedProjectiveU23_of_affineUpToFive
#print axioms erdos407_of_specializedPadicSubspace
#print axioms erdos407_of_specializedPadicSubspaceUpToFive

end Erdos407.TerminalBridge
