import ErdosProblems.Erdos957.HullRadial
import ErdosProblems.Erdos957.TurnSum

/-!
# Radial and edge-angle lift for the cyclic convex hull

This bridge constructs the once-around real lift of the edge directions
required by the turn-sum bookkeeping from the production gift-wrap cycle.
-/

namespace Erdos957HullAngleLift

open Erdos957
open Erdos957TurnSum

noncomputable section

/-! ## The sector between the endpoints of a hull edge is empty -/

/-- No third hull vertex can have its ray from an interior center strictly
inside the positive cone generated by the rays to the endpoints of a strict
supporting edge. -/
theorem no_hullVertex_in_positiveCone_of_strictSupportingEdge
    (A : Finset Point) {C p q x : Point}
    (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    (hp : p ∈ hullVertices A) (hq : q ∈ hullVertices A)
    (hx : x ∈ hullVertices A) (hedge : IsStrictSupportingEdge A p q)
    (hxp : x ≠ p) (hxq : x ≠ q) :
    ¬ ∃ a b t : ℝ, 0 < a ∧ 0 < b ∧ 0 < t ∧
      x - C = t • (a • (p - C) + b • (q - C)) := by
  rintro ⟨a, b, t, ha, hb, ht, hcone⟩
  have hab : 0 < a + b := add_pos ha hb
  let ca : ℝ := a / (a + b)
  let cb : ℝ := b / (a + b)
  have hca : 0 ≤ ca := (div_pos ha hab).le
  have hcb : 0 ≤ cb := (div_pos hb hab).le
  have hsum : ca + cb = 1 := by
    dsimp [ca, cb]
    field_simp
  have haca : (a + b) * ca = a := by
    dsimp [ca]
    field_simp
  have hbcb : (a + b) * cb = b := by
    dsimp [cb]
    field_simp
  let y : Point := ca • p + cb • q
  have hyseg : y ∈ segment ℝ p q := ⟨ca, cb, hca, hcb, hsum, rfl⟩
  have hyfront : y ∈ frontier (convexHull ℝ (A : Set Point)) :=
    hedge.segment_subset_frontier (hullVertices_subset A hp)
      (hullVertices_subset A hq) hyseg
  have hxfront : x ∈ frontier (convexHull ℝ (A : Set Point)) :=
    hullVertex_mem_frontier A hx
  have hyC : y - C = ca • (p - C) + cb • (q - C) := by
    dsimp [y]
    calc
      ca • p + cb • q - C = ca • p + cb • q - (ca + cb) • C := by
        rw [hsum, one_smul]
      _ = ca • (p - C) + cb • (q - C) := by module
  have hscale :
      a • (p - C) + b • (q - C) = (a + b) • (y - C) := by
    rw [hyC, smul_add, smul_smul, smul_smul, haca, hbcb]
  have hray : SameRay ℝ (x - C) (y - C) := by
    right
    right
    refine ⟨1, t * (a + b), one_pos, mul_pos ht hab, ?_⟩
    rw [one_smul, hcone, hscale, smul_smul]
  have hxy : x = y := sameRay_frontier_eq
    (convex_convexHull ℝ (A : Set Point))
    (Set.Finite.isCompact_convexHull ℝ A.finite_toSet).isClosed
    hC hxfront hyfront hray
  have hxseg : x ∈ segment ℝ p q := hxy.symm ▸ hyseg
  have hext := (mem_extremePoints_iff_forall_segment.mp (mem_hullVertices.mp hx)).2
    p (extremePoints_subset (mem_hullVertices.mp hp))
    q (extremePoints_subset (mem_hullVertices.mp hq)) hxseg
  exact hext.elim (fun h ↦ hxp h.symm) (fun h ↦ hxq h.symm)

/-- Cramer's rule in the standard complex orientation. -/
theorem exists_pos_smul_add_pos_smul_of_complexCross_pos {u v w : Point}
    (huv : 0 < complexCross (pointComplexEquiv u) (pointComplexEquiv v))
    (huw : 0 < complexCross (pointComplexEquiv u) (pointComplexEquiv w))
    (hwv : 0 < complexCross (pointComplexEquiv w) (pointComplexEquiv v)) :
    ∃ a b : ℝ, 0 < a ∧ 0 < b ∧ w = a • u + b • v := by
  let d := complexCross (pointComplexEquiv u) (pointComplexEquiv v)
  let a : ℝ := complexCross (pointComplexEquiv w) (pointComplexEquiv v) / d
  let b : ℝ := complexCross (pointComplexEquiv u) (pointComplexEquiv w) / d
  have hd : 0 < d := huv
  have ha : 0 < a := div_pos hwv hd
  have hb : 0 < b := div_pos huw hd
  have hd0 : d ≠ 0 := hd.ne'
  refine ⟨a, b, ha, hb, ?_⟩
  ext i
  fin_cases i
  · simp only [PiLp.add_apply, PiLp.smul_apply, smul_eq_mul]
    dsimp only [a, b, d]
    field_simp [hd0]
    simp only [complexCross_pointComplexEquiv]
    simp only [Fin.zero_eta, Fin.mk_one, Fin.isValue]
    ring
  · simp only [PiLp.add_apply, PiLp.smul_apply, smul_eq_mul]
    dsimp only [a, b, d]
    field_simp [hd0]
    simp only [complexCross_pointComplexEquiv]
    simp only [Fin.zero_eta, Fin.mk_one, Fin.isValue]
    ring

/-- No third hull-vertex ray lies in the open counterclockwise sector from
one endpoint of a directed strict supporting edge to the other. -/
theorem no_hullVertex_mem_openCCWSector_of_strictSupportingEdge
    (A : Finset Point) {C p q x : Point}
    (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    (hp : p ∈ hullVertices A) (hq : q ∈ hullVertices A)
    (hx : x ∈ hullVertices A) (hedge : IsStrictSupportingEdge A p q)
    (hxp : x ≠ p) (hxq : x ≠ q)
    (hpq : ccwAngleDiff (pointComplexEquiv (p - C))
      (pointComplexEquiv (q - C)) ∈ Set.Ioo 0 Real.pi) :
    ¬ InOpenCCWSector (pointComplexEquiv (p - C))
      (pointComplexEquiv (q - C)) (pointComplexEquiv (x - C)) := by
  intro hxsector
  have hp_ne_C : p ≠ C := by
    intro h
    subst p
    exact Set.disjoint_left.mp disjoint_interior_frontier hC
      (hullVertex_mem_frontier A hp)
  have hq_ne_C : q ≠ C := by
    intro h
    subst q
    exact Set.disjoint_left.mp disjoint_interior_frontier hC
      (hullVertex_mem_frontier A hq)
  have hx_ne_C : x ≠ C := by
    intro h
    subst x
    exact Set.disjoint_left.mp disjoint_interior_frontier hC
      (hullVertex_mem_frontier A hx)
  have hpC : pointComplexEquiv (p - C) ≠ 0 := by
    intro hzero
    exact (sub_ne_zero.mpr hp_ne_C)
      (pointComplexEquiv.injective (by simpa using hzero))
  have hqC : pointComplexEquiv (q - C) ≠ 0 := by
    intro hzero
    exact (sub_ne_zero.mpr hq_ne_C)
      (pointComplexEquiv.injective (by simpa using hzero))
  have hxC : pointComplexEquiv (x - C) ≠ 0 := by
    intro hzero
    exact (sub_ne_zero.mpr hx_ne_C)
      (pointComplexEquiv.injective (by simpa using hzero))
  have hpqCross := complexCross_pos_of_ccwAngleDiff_mem_Ioo hpC hqC hpq
  obtain ⟨hpx, hxqCross⟩ := complexCross_pos_of_mem_openCCWSector
    hpC hqC hxC hpq hxsector
  obtain ⟨a, b, ha, hb, hcone⟩ :=
    exists_pos_smul_add_pos_smul_of_complexCross_pos hpqCross hpx hxqCross
  apply no_hullVertex_in_positiveCone_of_strictSupportingEdge
    A hC hp hq hx hedge hxp hxq
  exact ⟨a, b, 1, ha, hb, one_pos, by simpa using hcone⟩

/-! ## The angularly sorted enumeration is the gift-wrap enumeration -/

theorem radial_complexCross_eq_orientedTurn (p q C : Point) :
    complexCross (pointComplexEquiv (p - C)) (pointComplexEquiv (q - C)) =
      orientedTurn p q C := by
  rw [complexCross_pointComplexEquiv, orientedTurn_eq_crossVec]
  simp only [crossVec, PiLp.sub_apply]
  ring

theorem cyclicSucc_val_local {n : ℕ} (i : Fin n) :
    (cyclicSucc i).val = (i.val + 1) % n := by
  letI : NeZero n := i.neZero
  change (finRotate n i).val = _
  rw [finRotate_apply, Fin.val_add, Fin.val_one']
  nth_rw 1 [← Nat.mod_eq_of_lt i.isLt]
  exact (Nat.add_mod i.val 1 n).symm

/-- In a strictly increasing finite list, the cyclic successor of `i` lies
in the open circular interval from `i` to every other index `j`. -/
theorem strictMono_cyclicSucc_between_local {n : ℕ} (hn : 2 ≤ n)
    {f : Fin n → ℝ} (hf : StrictMono f) (i j : Fin n)
    (hji : j ≠ i) (hjs : j ≠ cyclicSucc i) :
    if f i < f j then f i < f (cyclicSucc i) ∧ f (cyclicSucc i) < f j
    else f i < f (cyclicSucc i) ∨ f (cyclicSucc i) < f j := by
  have hnpos : 0 < n := by omega
  by_cases hi : i.val + 1 < n
  · have hsval : (cyclicSucc i).val = i.val + 1 := by
      rw [cyclicSucc_val_local, Nat.mod_eq_of_lt hi]
    have his : i < cyclicSucc i := by
      rw [Fin.lt_iff_val_lt_val, hsval]
      exact i.val.lt_succ_self
    have hfis : f i < f (cyclicSucc i) := hf his
    by_cases hij : i < j
    · rw [if_pos (hf hij)]
      refine ⟨hfis, hf ?_⟩
      rw [Fin.lt_iff_val_lt_val, hsval]
      have hijval : i.val < j.val := hij
      have hneval : i.val + 1 ≠ j.val := by
        intro h
        apply hjs
        apply Fin.ext
        rw [hsval]
        exact h.symm
      omega
    · have hji' : j < i := lt_of_le_of_ne (not_lt.mp hij) hji
      rw [if_neg (not_lt_of_ge (hf hji').le)]
      exact Or.inl hfis
  · have hilast : i.val + 1 = n := by omega
    have hsval : (cyclicSucc i).val = 0 := by
      rw [cyclicSucc_val_local, hilast, Nat.mod_self]
    have hji' : j < i := by
      rw [Fin.lt_iff_val_lt_val]
      have hjlt := j.isLt
      have hjne : j.val ≠ i.val := fun h ↦ hji (Fin.ext h)
      omega
    have hfji : f j < f i := hf hji'
    rw [if_neg (not_lt_of_ge hfji.le)]
    apply Or.inr
    apply hf
    rw [Fin.lt_iff_val_lt_val, hsval]
    have hjpos : 0 < j.val := by
      by_contra hjzero
      have hjzero' : j.val = 0 := Nat.eq_zero_of_not_pos hjzero
      apply hjs
      apply Fin.ext
      rw [hsval]
      exact hjzero'
    exact hjpos

theorem angleSorted_cyclicSucc_mem_openCCWSector_local {n : ℕ} (hn : 2 ≤ n)
    {C : Point} {v : Fin n → Point}
    (hsorted : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i j : Fin n) (hji : j ≠ i) (hjs : j ≠ cyclicSucc i) :
    InOpenCCWSector (pointComplexEquiv (v i - C))
      (pointComplexEquiv (v j - C))
      (pointComplexEquiv (v (cyclicSucc i) - C)) := by
  change if centerAngle C (v i) < centerAngle C (v j) then
      centerAngle C (v i) < centerAngle C (v (cyclicSucc i)) ∧
        centerAngle C (v (cyclicSucc i)) < centerAngle C (v j)
    else centerAngle C (v i) < centerAngle C (v (cyclicSucc i)) ∨
      centerAngle C (v (cyclicSucc i)) < centerAngle C (v j)
  exact strictMono_cyclicSucc_between_local hn
    (fun _ _ hij ↦ hsorted _ _ hij) i j hji hjs

/-- In the principal-argument sorted enumeration, cyclic successor is the
unique counterclockwise gift-wrap successor. -/
theorem isCCWNext_angleSorted_cyclicSucc
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    {v : Fin (hullVertexCount A) ↪ Point}
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin (hullVertexCount A)) :
    IsCCWNext A (v i) (v (cyclicSucc i)) := by
  have hp : v i ∈ hullVertices A := by
    have hi : v i ∈ Set.range v := ⟨i, rfl⟩
    have hi' : v i ∈ (hullVertices A : Set Point) := hvrange ▸ hi
    exact hi'
  have hs : v (cyclicSucc i) ∈ hullVertices A := by
    have hs' : v (cyclicSucc i) ∈ Set.range v := ⟨cyclicSucc i, rfl⟩
    have hs'' : v (cyclicSucc i) ∈ (hullVertices A : Set Point) := hvrange ▸ hs'
    exact hs''
  obtain ⟨q, hqnext, hqunique⟩ :=
    hullVertex_existsUnique_isCCWNext A hthree hp
  obtain ⟨j, hj⟩ : ∃ j, v j = q := by
    have : q ∈ Set.range v := hvrange.symm ▸ hqnext.1
    exact this
  have hqeq : q = v (cyclicSucc i) := by
    by_contra hne
    have hji : j ≠ i := by
      intro h
      subst j
      exact hqnext.2.1.1 hj
    have hjs : j ≠ cyclicSucc i := by
      intro h
      subst j
      exact hne hj.symm
    have hsector := angleSorted_cyclicSucc_mem_openCCWSector_local
      (by omega : 2 ≤ hullVertexCount A) hvmono i j hji hjs
    have hturn : 0 < orientedTurn (v i) q C :=
      hqnext.turn_interior_pos hthree hp hC
    have hcross : 0 < complexCross (pointComplexEquiv (v i - C))
        (pointComplexEquiv (q - C)) := by
      rw [radial_complexCross_eq_orientedTurn]
      exact hturn
    have hdiff := ccwAngleDiff_mem_Ioo_of_complexCross_pos hcross
    have hs_ne_i : cyclicSucc i ≠ i := by
      by_cases hi : i.val + 1 < hullVertexCount A
      · intro heq
        have hval := congrArg Fin.val heq
        rw [cyclicSucc_val_local, Nat.mod_eq_of_lt hi] at hval
        omega
      · have hilast : i.val + 1 = hullVertexCount A := by omega
        intro heq
        have hval := congrArg Fin.val heq
        rw [cyclicSucc_val_local, hilast, Nat.mod_self] at hval
        omega
    apply no_hullVertex_mem_openCCWSector_of_strictSupportingEdge
      A hC hp hqnext.1 hs hqnext.2.1
      (v.injective.ne hs_ne_i) (Ne.symm hne) hdiff
    simpa [hj] using hsector
  rw [← hqeq]
  exact hqnext

theorem cyclicSucc_ne_self_of_two_le {n : ℕ} (hn : 2 ≤ n) (i : Fin n) :
    cyclicSucc i ≠ i := by
  by_cases hi : i.val + 1 < n
  · intro heq
    have hval := congrArg Fin.val heq
    rw [cyclicSucc_val_local, Nat.mod_eq_of_lt hi] at hval
    omega
  · have hilast : i.val + 1 = n := by omega
    intro heq
    have hval := congrArg Fin.val heq
    rw [cyclicSucc_val_local, hilast, Nat.mod_self] at hval
    omega

theorem cyclicSucc_cyclicSucc_ne_self_of_three_le {n : ℕ}
    (hn : 3 ≤ n) (i : Fin n) : cyclicSucc (cyclicSucc i) ≠ i := by
  by_cases hi : i.val + 1 < n
  · have hsval : (cyclicSucc i).val = i.val + 1 := by
      rw [cyclicSucc_val_local, Nat.mod_eq_of_lt hi]
    by_cases hii : i.val + 2 < n
    · intro heq
      have hval := congrArg Fin.val heq
      rw [cyclicSucc_val_local, hsval, Nat.mod_eq_of_lt] at hval
      · omega
      · simpa [Nat.add_assoc] using hii
    · have hiilast : i.val + 2 = n := by omega
      intro heq
      have hval := congrArg Fin.val heq
      rw [cyclicSucc_val_local, hsval] at hval
      have hsum : i.val + 1 + 1 = n := by omega
      rw [hsum, Nat.mod_self] at hval
      omega
  · have hilast : i.val + 1 = n := by omega
    have hsval : (cyclicSucc i).val = 0 := by
      rw [cyclicSucc_val_local, hilast, Nat.mod_self]
    intro heq
    have hval := congrArg Fin.val heq
    rw [cyclicSucc_val_local, hsval, Nat.zero_add,
      Nat.mod_eq_of_lt (by omega : 1 < n)] at hval
    omega

/-- The principal-argument sorted embedding, with cyclic successor, is a
genuine counterclockwise cyclic hull order. -/
noncomputable def angleSortedCyclicHullOrder
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    (v : Fin (hullVertexCount A) ↪ Point)
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j)) :
    CyclicHullOrder A where
  vertex := v
  range_vertex := hvrange
  edge_support i :=
    (isCCWNext_angleSorted_cyclicSucc A hthree hC hvrange hvmono i).2.1
  strict_turn i := by
    have hi := isCCWNext_angleSorted_cyclicSucc A hthree hC hvrange hvmono i
    have hs := isCCWNext_angleSorted_cyclicSucc A hthree hC hvrange hvmono
      (cyclicSucc i)
    apply hi.2.2 (v (cyclicSucc (cyclicSucc i)))
    · have hrange : v (cyclicSucc (cyclicSucc i)) ∈ Set.range v :=
        ⟨cyclicSucc (cyclicSucc i), rfl⟩
      have : v (cyclicSucc (cyclicSucc i)) ∈
          (hullVertices A : Set Point) := hvrange ▸ hrange
      exact this
    · exact v.injective.ne (cyclicSucc_cyclicSucc_ne_self hthree i)
    · exact hs.2.1.1.symm

/-! ## Radial and chord representatives -/

noncomputable def radialPhase {n : ℕ} (C : Point) (v : Fin n → Point)
    (i : Fin n) : ℝ := centerAngle C (v i)

noncomputable def radialLift {n : ℕ} (hn : 0 < n)
    (C : Point) (v : Fin n → Point) : ℕ → ℝ :=
  closedPhaseLift hn (radialPhase C v)

noncomputable def outgoingEdge {n : ℕ} (v : Fin n → Point)
    (i : Fin n) : Point := v (cyclicSucc i) - v i

noncomputable def chordIncrement {n : ℕ} (C : Point) (v : Fin n → Point)
    (i : Fin n) : ℝ :=
  ccwAngleDiff (pointComplexEquiv (v i - C))
    (pointComplexEquiv (outgoingEdge v i))

noncomputable def chordPhase {n : ℕ} (C : Point) (v : Fin n → Point)
    (i : Fin n) : ℝ := radialPhase C v i + chordIncrement C v i

noncomputable def chordLift {n : ℕ} (hn : 0 < n)
    (C : Point) (v : Fin n → Point) : ℕ → ℝ :=
  closedPhaseLift hn (chordPhase C v)

@[simp]
theorem radialLift_apply_fin {n : ℕ} (hn : 0 < n)
    (C : Point) (v : Fin n → Point) (i : Fin n) :
    radialLift hn C v i = radialPhase C v i := by
  simp [radialLift, i.isLt]

@[simp]
theorem chordLift_apply_fin {n : ℕ} (hn : 0 < n)
    (C : Point) (v : Fin n → Point) (i : Fin n) :
    chordLift hn C v i = chordPhase C v i := by
  simp [chordLift, i.isLt]

/-- The increment of the closed radial lift is exactly the normalized
counterclockwise principal-argument displacement to cyclic successor. -/
theorem radialLift_gap_eq_ccwAngleDiff {n : ℕ} (hn : 0 < n)
    {C : Point} {v : Fin n → Point}
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin n) :
    radialLift hn C v (i.val + 1) - radialLift hn C v i =
      ccwAngleDiff (pointComplexEquiv (v i - C))
        (pointComplexEquiv (v (cyclicSucc i) - C)) := by
  letI : NeZero n := ⟨hn.ne'⟩
  by_cases hi : i.val + 1 < n
  · have hsval : (cyclicSucc i).val = i.val + 1 := by
      rw [cyclicSucc_val, Nat.mod_eq_of_lt hi]
    have his : i < cyclicSucc i := by
      rw [Fin.lt_def, hsval]
      omega
    have hphase : centerAngle C (v i) < centerAngle C (v (cyclicSucc i)) :=
      hvmono i (cyclicSucc i) his
    have hphase' :
        Complex.arg (pointComplexEquiv (v i - C)) <
          Complex.arg (pointComplexEquiv (v (cyclicSucc i) - C)) := by
      simpa [centerAngle] using hphase
    rw [radialLift, closedPhaseLift_of_lt hn _ hi,
      closedPhaseLift_of_lt hn _ i.isLt]
    rw [ccwAngleDiff, if_pos hphase']
    have hsfin : (⟨i.val + 1, hi⟩ : Fin n) = cyclicSucc i := Fin.ext hsval.symm
    rw [hsfin]
    rfl
  · have hilast : i.val + 1 = n := by omega
    have hsval : cyclicSucc i = ⟨0, hn⟩ := by
      apply Fin.ext
      rw [cyclicSucc_val, hilast, Nat.mod_self]
    have hphase : ¬ centerAngle C (v i) < centerAngle C (v (cyclicSucc i)) := by
      rw [hsval]
      have hzero_le_i : (⟨0, hn⟩ : Fin n) ≤ i := Fin.zero_le i
      exact not_lt_of_ge (StrictMono.monotone
        (fun a b hab ↦ hvmono a b hab) hzero_le_i)
    have hphase' : ¬
        Complex.arg (pointComplexEquiv (v i - C)) <
          Complex.arg (pointComplexEquiv (v (cyclicSucc i) - C)) := by
      simpa [centerAngle] using hphase
    rw [hilast, radialLift, closedPhaseLift_at_card,
      closedPhaseLift_of_lt hn _ i.isLt]
    rw [ccwAngleDiff, if_neg hphase', hsval]
    simp [radialLift, radialPhase, centerAngle, hn]
    ring

theorem complexCross_radial_outgoingEdge_left {n : ℕ}
    (C : Point) (v : Fin n → Point) (i : Fin n) :
    complexCross (pointComplexEquiv (v i - C))
        (pointComplexEquiv (outgoingEdge v i)) =
      complexCross (pointComplexEquiv (v i - C))
        (pointComplexEquiv (v (cyclicSucc i) - C)) := by
  simp only [complexCross_pointComplexEquiv, outgoingEdge]
  simp only [PiLp.sub_apply]
  ring

theorem complexCross_radial_outgoingEdge_right {n : ℕ}
    (C : Point) (v : Fin n → Point) (i : Fin n) :
    complexCross (pointComplexEquiv (v (cyclicSucc i) - C))
        (pointComplexEquiv (outgoingEdge v i)) =
      complexCross (pointComplexEquiv (v i - C))
        (pointComplexEquiv (v (cyclicSucc i) - C)) := by
  simp only [complexCross_pointComplexEquiv, outgoingEdge]
  simp only [PiLp.sub_apply]
  ring

/-- Every radial gap of the sorted hull is a strict counterclockwise angle
smaller than `π`. -/
theorem radialLift_gap_mem_Ioo
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    {v : Fin (hullVertexCount A) ↪ Point}
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin (hullVertexCount A)) :
    radialLift (by omega : 0 < hullVertexCount A) C v (i.val + 1) -
        radialLift (by omega : 0 < hullVertexCount A) C v i ∈
      Set.Ioo 0 Real.pi := by
  have hp : v i ∈ hullVertices A := by
    have hi : v i ∈ Set.range v := ⟨i, rfl⟩
    have hi' : v i ∈ (hullVertices A : Set Point) := hvrange ▸ hi
    exact hi'
  have hnext := isCCWNext_angleSorted_cyclicSucc
    A hthree hC hvrange hvmono i
  have hturn : 0 < orientedTurn (v i) (v (cyclicSucc i)) C :=
    hnext.turn_interior_pos hthree hp hC
  have hcross : 0 < complexCross (pointComplexEquiv (v i - C))
      (pointComplexEquiv (v (cyclicSucc i) - C)) := by
    rw [radial_complexCross_eq_orientedTurn]
    exact hturn
  rw [radialLift_gap_eq_ccwAngleDiff (by omega) hvmono i]
  exact ccwAngleDiff_mem_Ioo_of_complexCross_pos hcross

/-- The outgoing chord lies strictly counterclockwise of the current radial
ray by an angle less than `π`. -/
theorem chordIncrement_mem_Ioo
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    {v : Fin (hullVertexCount A) ↪ Point}
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin (hullVertexCount A)) :
    chordIncrement C v i ∈ Set.Ioo 0 Real.pi := by
  have hp : v i ∈ hullVertices A := by
    have hi : v i ∈ Set.range v := ⟨i, rfl⟩
    have hi' : v i ∈ (hullVertices A : Set Point) := hvrange ▸ hi
    exact hi'
  have hnext := isCCWNext_angleSorted_cyclicSucc
    A hthree hC hvrange hvmono i
  have hturn : 0 < orientedTurn (v i) (v (cyclicSucc i)) C :=
    hnext.turn_interior_pos hthree hp hC
  have hcross : 0 < complexCross (pointComplexEquiv (v i - C))
      (pointComplexEquiv (v (cyclicSucc i) - C)) := by
    rw [radial_complexCross_eq_orientedTurn]
    exact hturn
  unfold chordIncrement
  apply ccwAngleDiff_mem_Ioo_of_complexCross_pos
  rwa [complexCross_radial_outgoingEdge_left]

/-- The same chord lies strictly counterclockwise of the successor radial
ray, again by an angle less than `π`. -/
theorem successorRadial_to_outgoingEdge_mem_Ioo
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    {v : Fin (hullVertexCount A) ↪ Point}
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin (hullVertexCount A)) :
    ccwAngleDiff (pointComplexEquiv (v (cyclicSucc i) - C))
      (pointComplexEquiv (outgoingEdge v i)) ∈ Set.Ioo 0 Real.pi := by
  have hp : v i ∈ hullVertices A := by
    have hi : v i ∈ Set.range v := ⟨i, rfl⟩
    have hi' : v i ∈ (hullVertices A : Set Point) := hvrange ▸ hi
    exact hi'
  have hnext := isCCWNext_angleSorted_cyclicSucc
    A hthree hC hvrange hvmono i
  have hturn : 0 < orientedTurn (v i) (v (cyclicSucc i)) C :=
    hnext.turn_interior_pos hthree hp hC
  have hcross : 0 < complexCross (pointComplexEquiv (v i - C))
      (pointComplexEquiv (v (cyclicSucc i) - C)) := by
    rw [radial_complexCross_eq_orientedTurn]
    exact hturn
  apply ccwAngleDiff_mem_Ioo_of_complexCross_pos
  rwa [complexCross_radial_outgoingEdge_right]

theorem unitDirection_chordPhase {n : ℕ} (C : Point) (v : Fin n → Point)
    (i : Fin n) :
    unitDirection (chordPhase C v i) =
      unitDirection (Complex.arg (pointComplexEquiv (outgoingEdge v i))) := by
  unfold chordPhase radialPhase chordIncrement centerAngle
  exact unitDirection_arg_add_ccwAngleDiff _ _

theorem unitDirection_radialLift_succ {n : ℕ} (hn : 0 < n)
    {C : Point} {v : Fin n → Point}
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin n) :
    unitDirection (radialLift hn C v (i.val + 1)) =
      unitDirection (Complex.arg (pointComplexEquiv (v (cyclicSucc i) - C))) := by
  have hgap := radialLift_gap_eq_ccwAngleDiff hn hvmono i
  have hbase : radialLift hn C v i =
      Complex.arg (pointComplexEquiv (v i - C)) := by
    simp [radialPhase, centerAngle]
  have hsum : radialLift hn C v (i.val + 1) =
      Complex.arg (pointComplexEquiv (v i - C)) +
        ccwAngleDiff (pointComplexEquiv (v i - C))
          (pointComplexEquiv (v (cyclicSucc i) - C)) := by
    linarith
  rw [hsum]
  exact unitDirection_arg_add_ccwAngleDiff _ _

theorem unitDirection_chordLift_fin {n : ℕ} (hn : 0 < n)
    (C : Point) (v : Fin n → Point) (i : Fin n) :
    unitDirection (chordLift hn C v i) =
      unitDirection (Complex.arg (pointComplexEquiv (outgoingEdge v i))) := by
  rw [chordLift_apply_fin]
  exact unitDirection_chordPhase C v i

theorem unitDirection_chordLift_succ {n : ℕ} (hn : 0 < n)
    (C : Point) (v : Fin n → Point) (i : Fin n) :
    unitDirection (chordLift hn C v (i.val + 1)) =
      unitDirection (Complex.arg
        (pointComplexEquiv (outgoingEdge v (cyclicSucc i)))) := by
  by_cases hi : i.val + 1 < n
  · have hsval : (⟨i.val + 1, hi⟩ : Fin n) = cyclicSucc i := by
      apply Fin.ext
      rw [cyclicSucc_val, Nat.mod_eq_of_lt hi]
    rw [chordLift, closedPhaseLift_of_lt hn _ hi, hsval]
    exact unitDirection_chordPhase C v (cyclicSucc i)
  · have hilast : i.val + 1 = n := by omega
    rw [hilast, chordLift, closedPhaseLift_at_card]
    have hzero : (⟨0, hn⟩ : Fin n) = cyclicSucc i := by
      apply Fin.ext
      rw [cyclicSucc_val, hilast, Nat.mod_self]
    rw [show closedPhaseLift hn (chordPhase C v) 0 =
        chordPhase C v ⟨0, hn⟩ by simp [hn]]
    calc
      unitDirection (chordPhase C v ⟨0, hn⟩ + 2 * Real.pi) =
          unitDirection (chordPhase C v ⟨0, hn⟩) :=
        unitDirection_add_two_pi _
      _ = unitDirection (chordPhase C v (cyclicSucc i)) := by rw [hzero]
      _ = _ := unitDirection_chordPhase C v (cyclicSucc i)

/-- The radial/chord representatives associated to the angularly sorted hull
satisfy all interval, closing, and positive-turn conditions consumed by the
turn-sum module. -/
noncomputable def radialChordAngleDataOfAngleSorted
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    (v : Fin (hullVertexCount A) ↪ Point)
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j)) :
    RadialChordAngleData (hullVertexCount A) := by
  have hm : 0 < hullVertexCount A := by omega
  let P : CyclicHullOrder A :=
    angleSortedCyclicHullOrder A hthree hC v hvrange hvmono
  refine
    { three_le := hthree
      radial := radialLift hm C v
      chord := chordLift hm C v
      radial_strict := ?_
      radial_closes := ?_
      chord_lower := ?_
      chord_upper := ?_
      chord_closes := ?_
      strict_turn := ?_ }
  · intro i
    have h := (radialLift_gap_mem_Ioo A hthree hC hvrange hvmono i).1
    linarith
  · exact closedPhaseLift_at_card hm (radialPhase C v)
  · intro i
    have hgap := radialLift_gap_mem_Ioo A hthree hC hvrange hvmono i
    have hinc := chordIncrement_mem_Ioo A hthree hC hvrange hvmono i
    have heps := successorRadial_to_outgoingEdge_mem_Ioo
      A hthree hC hvrange hvmono i
    have hsinPrincipal : 0 < Real.sin
        (Complex.arg (pointComplexEquiv (outgoingEdge v i)) -
          Complex.arg (pointComplexEquiv (v (cyclicSucc i) - C))) := by
      rw [← sin_ccwAngleDiff]
      exact Real.sin_pos_of_pos_of_lt_pi heps.1 heps.2
    have hradDir := unitDirection_radialLift_succ hm hvmono i
    have hchordDir := unitDirection_chordLift_fin hm C v i
    have hsin : 0 < Real.sin
        (chordLift hm C v i - radialLift hm C v (i.val + 1)) := by
      rw [← det_unitDirection, hradDir, hchordDir, det_unitDirection]
      exact hsinPrincipal
    have hnegpi : -Real.pi <
        chordLift hm C v i - radialLift hm C v (i.val + 1) := by
      rw [chordLift_apply_fin, chordPhase]
      have hbase : radialLift hm C v i = radialPhase C v i := by simp
      rw [hbase] at hgap
      linarith [hgap.2, hinc.1]
    have hpos := pos_of_neg_pi_lt_of_sin_pos hnegpi hsin
    linarith
  · intro i
    have hinc := chordIncrement_mem_Ioo A hthree hC hvrange hvmono i
    rw [chordLift_apply_fin, chordPhase, radialLift_apply_fin]
    simpa [add_comm] using
      add_lt_add_left hinc.2 (radialPhase C v i)
  · exact closedPhaseLift_at_card hm (chordPhase C v)
  · intro i
    have hturn := P.strict_turn i
    change 0 < orientedTurn (v i) (v (cyclicSucc i))
      (v (cyclicSucc (cyclicSucc i))) at hturn
    rw [orientedTurn_eq_crossVec] at hturn
    have hdetEdge : 0 < det (outgoingEdge v i)
        (outgoingEdge v (cyclicSucc i)) := by
      rw [det_eq_crossVec]
      change 0 < crossVec (v (cyclicSucc i) - v i)
        (v (cyclicSucc (cyclicSucc i)) - v (cyclicSucc i))
      have heq : crossVec (v (cyclicSucc i) - v i)
          (v (cyclicSucc (cyclicSucc i)) - v (cyclicSucc i)) =
          crossVec (v (cyclicSucc i) - v i)
            (v (cyclicSucc (cyclicSucc i)) - v i) := by
        simp only [crossVec, PiLp.sub_apply]
        ring
      rw [heq]
      exact hturn
    have hei : outgoingEdge v i ≠ 0 := by
      rw [outgoingEdge, sub_ne_zero]
      exact v.injective.ne (cyclicSucc_ne_self (by omega) i)
    have hes : outgoingEdge v (cyclicSucc i) ≠ 0 := by
      rw [outgoingEdge, sub_ne_zero]
      exact v.injective.ne
        (cyclicSucc_ne_self (by omega) (cyclicSucc i))
    have hni : 0 < ‖outgoingEdge v i‖ := norm_pos_iff.mpr hei
    have hns : 0 < ‖outgoingEdge v (cyclicSucc i)‖ := norm_pos_iff.mpr hes
    have hfactor := hdetEdge
    rw [← norm_smul_unitDirection_arg (outgoingEdge v i),
      ← norm_smul_unitDirection_arg (outgoingEdge v (cyclicSucc i)),
      det_smul_smul] at hfactor
    have hdetUnit : 0 < det
        (unitDirection (Complex.arg (pointComplexEquiv (outgoingEdge v i))))
        (unitDirection (Complex.arg
          (pointComplexEquiv (outgoingEdge v (cyclicSucc i))))) := by
      rcases mul_pos_iff.mp hfactor with hpos | hneg
      · exact hpos.2
      · exact False.elim ((not_lt_of_ge (mul_pos hni hns).le) hneg.1)
    rw [← det_unitDirection,
      unitDirection_chordLift_fin hm C v i,
      unitDirection_chordLift_succ hm C v i]
    exact hdetUnit

/-- The data above represents the actual outgoing edges of its aligned
cyclic hull order. -/
theorem radialChordAngleData_represents
    (A : Finset Point) (hthree : 3 ≤ hullVertexCount A)
    {C : Point} (hC : C ∈ interior (convexHull ℝ (A : Set Point)))
    (v : Fin (hullVertexCount A) ↪ Point)
    (hvrange : Set.range v = (hullVertices A : Set Point))
    (hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j))
    (i : Fin (hullVertexCount A)) :
    let P := angleSortedCyclicHullOrder A hthree hC v hvrange hvmono
    let D := radialChordAngleDataOfAngleSorted A hthree hC v hvrange hvmono
    unitDirection (D.chord i) =
      unitDirection (Complex.arg (pointComplexEquiv
        (P.vertex (finRotate (hullVertexCount A) i) - P.vertex i))) := by
  dsimp only
  change unitDirection
      (chordLift (by omega : 0 < hullVertexCount A) C v i) = _
  rw [unitDirection_chordLift_fin]
  rfl

/-- The radial witness and the direction lift can be retained over exactly
the same cyclic hull order.  This form is useful to combine the turn-sum
theorems with chord/arc statements proved from the radial ordering. -/
theorem exists_radiallySorted_liftedCyclicHullOrder (A : Finset Point)
    (hthree : 3 ≤ hullVertexCount A) :
    ∃ R : RadiallySortedCyclicHullOrder A,
      Nonempty
        (Erdos957TurnSum.HullOrderBridge.LiftedCyclicHullOrder R.order) := by
  obtain ⟨R⟩ := exists_radiallySortedCyclicHullOrder A hthree
  let C : Point := R.center
  let v : Fin (hullVertexCount A) ↪ Point := R.order.vertex
  have hC : C ∈ interior (convexHull ℝ (A : Set Point)) := R.center_mem_interior
  have hvrange : Set.range v = (hullVertices A : Set Point) := R.order.range_vertex
  have hvmono : ∀ i j, i < j → centerAngle C (v i) < centerAngle C (v j) :=
    fun _ _ hij ↦ R.angle_strictMono hij
  let D : RadialChordAngleData (hullVertexCount A) :=
    radialChordAngleDataOfAngleSorted A hthree hC v hvrange hvmono
  have hrep : ∀ i : Fin (hullVertexCount A),
      unitDirection (D.chord i) =
        unitDirection (Complex.arg (pointComplexEquiv
          (R.order.vertex (finRotate (hullVertexCount A) i) -
            R.order.vertex i))) := by
    intro i
    change unitDirection
        (chordLift (by omega : 0 < hullVertexCount A) C v i) = _
    rw [unitDirection_chordLift_fin]
    rfl
  refine ⟨R, ⟨?_⟩⟩
  exact (Erdos957TurnSum.HullOrderBridge.UnwrappedCyclicEdgeAngles.ofRadialChord
    D hrep).toLiftedCyclicHullOrder

/-- Every finite planar convex hull with at least three vertices admits an
aligned cyclic order together with the once-around edge-direction lift used
by the exterior-angle theorem. -/
theorem exists_liftedCyclicHullOrder (A : Finset Point)
    (hthree : 3 ≤ hullVertexCount A) :
    ∃ P : CyclicHullOrder A,
      Nonempty (Erdos957TurnSum.HullOrderBridge.LiftedCyclicHullOrder P) := by
  obtain ⟨R, hL⟩ := exists_radiallySorted_liftedCyclicHullOrder A hthree
  exact ⟨R.order, hL⟩

/-- A direct callable form of the convex-polygon exterior-angle theorem:
the concrete exterior turns are nonnegative and sum to one full turn. -/
theorem exists_exteriorTurn_spec (A : Finset Point)
    (hthree : 3 ≤ hullVertexCount A) :
    ∃ (P : CyclicHullOrder A)
      (L : Erdos957TurnSum.HullOrderBridge.LiftedCyclicHullOrder P),
      (∀ i, 0 ≤ Erdos957TurnSum.HullOrderBridge.exteriorTurn P i) ∧
      (∀ i, Erdos957TurnSum.HullOrderBridge.exteriorTurn P i =
        Real.pi - InnerProductGeometry.angle
          (P.vertex ((finRotate (hullVertexCount A)).symm i) - P.vertex i)
          (P.vertex (finRotate (hullVertexCount A) i) - P.vertex i)) ∧
      (∑ i, Erdos957TurnSum.HullOrderBridge.exteriorTurn P i) =
        2 * Real.pi := by
  obtain ⟨P, ⟨L⟩⟩ := exists_liftedCyclicHullOrder A hthree
  exact ⟨P, L, L.exteriorTurn_spec⟩

end

end Erdos957HullAngleLift
