import Mathlib.Data.Finset.Image
import Mathlib.SetTheory.Cardinal.Arithmetic
import Mathlib.SetTheory.Cardinal.Ordinal

set_option relaxedAutoImplicit true
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# Cardinal bounds for finite closures

This module proves the cardinality component of the finite-closure layering
construction.  A closure step adds the finite outputs attached to all
admissible `r`-element subsets of a set.  Its countable iteration remains
strictly below an uncountable cardinal whenever the initial set does.

The proof deliberately uses an explicit bound
`max ℵ₀ #S`, rather than a regular-cardinal argument.  It is therefore valid
at singular cardinals as well.
-/

namespace Erdos593

namespace FiniteClosureCardinality

open Set

universe u

variable {V : Type u}

/-- The union of all finite iterates of a set operator. -/
def iterUnion (f : Set V → Set V) (S : Set V) : Set V :=
  ⋃ n : Nat, (f^[n]) S

/-- The `r`-element finite subsets of `S`. -/
def admissible (r : Nat) (S : Set V) : Type u :=
  {s : Finset V // s.card = r ∧ ∀ x ∈ s, x ∈ S}

/-- The set underlying the finite output assigned to an admissible input. -/
def output (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    {S : Set V} (s : admissible r S) : Set V :=
  ((Φ ⟨s.1, s.2.1⟩ : Finset V) : Set V)

/-- One finite-closure step. -/
def closureStep (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) : Set V :=
  S ∪ ⋃ s : admissible r S, output r Φ s

theorem mem_closureStep_iff
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) (x : V) :
    x ∈ closureStep r Φ S ↔ x ∈ S ∨
      ∃ s : {s : Finset V // s.card = r},
        (∀ z ∈ s.1, z ∈ S) ∧ x ∈ Φ s := by
  simp only [closureStep, Set.mem_union, Set.mem_iUnion]
  constructor
  · rintro (hx | ⟨⟨a, ha, hinside⟩, hx⟩)
    · exact Or.inl hx
    · refine Or.inr ⟨⟨a, ha⟩, hinside, ?_⟩
      simpa [output] using! hx
  · rintro (hx | ⟨s, hinside, hx⟩)
    · exact Or.inl hx
    · refine Or.inr ⟨⟨s.1, s.2, hinside⟩, ?_⟩
      simpa [output] using! hx

/-- Finite closure steps are monotone in their input set. -/
theorem closureStep_mono
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V) :
    Monotone (closureStep r Φ) := by
  intro S T hST x hx
  rw [mem_closureStep_iff] at hx
  rw [mem_closureStep_iff]
  rcases hx with hx | ⟨s, hinside, hx⟩
  · exact Or.inl (hST hx)
  · exact Or.inr ⟨s, fun z hz => hST (hinside z hz), hx⟩

theorem mk_admissible_le_finset (r : Nat) (S : Set V) :
    Cardinal.mk (admissible r S) ≤ Cardinal.mk (Finset S) := by
  classical
  calc
    Cardinal.mk (admissible r S) ≤
        Cardinal.mk {s : Finset V // ∀ x ∈ s, x ∈ S} :=
      Cardinal.mk_subtype_le_of_subset fun _ hs => hs.2
    _ = Cardinal.mk (Finset S) :=
      (Cardinal.mk_congr (Equiv.finsetSubtypeComm fun x : V => x ∈ S)).symm

theorem mk_admissible_le
    (r : Nat) (S : Set V) (c : Cardinal.{u})
    (hc : Cardinal.aleph0 ≤ c) (hS : Cardinal.mk S ≤ c) :
    Cardinal.mk (admissible r S) ≤ c := by
  classical
  calc
    Cardinal.mk (admissible r S) ≤ Cardinal.mk (Finset S) :=
      mk_admissible_le_finset r S
    _ ≤ Cardinal.mk (List S) :=
      Cardinal.mk_le_of_surjective List.toFinset_surjective
    _ ≤ max Cardinal.aleph0 (Cardinal.mk S) := Cardinal.mk_list_le_max S
    _ ≤ c := max_le hc hS

/-- A single finite-closure step preserves every infinite cardinal bound. -/
theorem mk_closureStep_le
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) (c : Cardinal.{u})
    (hc : Cardinal.aleph0 ≤ c) (hS : Cardinal.mk S ≤ c) :
    Cardinal.mk (closureStep r Φ S) ≤ c := by
  classical
  have houtputOne (s : admissible r S) : Cardinal.mk (output r Φ s) ≤ c := by
    change Cardinal.mk ((Φ ⟨s.1, s.2.1⟩ : Finset V) : Set V) ≤ c
    exact (Cardinal.finset_card_lt_aleph0 (Φ ⟨s.1, s.2.1⟩)).le.trans hc
  have houtput :
      Cardinal.mk (⋃ s : admissible r S, output r Φ s) ≤ c := by
    calc
      Cardinal.mk (⋃ s : admissible r S, output r Φ s) ≤
          Cardinal.mk (admissible r S) *
            ⨆ s : admissible r S,
              Cardinal.mk (output r Φ s) := by
        exact Cardinal.mk_iUnion_le (output r Φ)
      _ ≤ c * c := by
        exact mul_le_mul' (mk_admissible_le r S c hc hS) (ciSup_le' houtputOne)
      _ = c := Cardinal.mul_eq_self hc
  calc
    Cardinal.mk (closureStep r Φ S) ≤
        Cardinal.mk S + Cardinal.mk (⋃ s : admissible r S, output r Φ s) :=
      Cardinal.mk_union_le _ _
    _ ≤ c + c := add_le_add hS houtput
    _ = c := Cardinal.add_eq_self hc

/-- The countable closure generated by finite closure steps. -/
def closure (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) : Set V :=
  iterUnion (closureStep r Φ) S

/-- A finite-closure step contains its input set. -/
theorem extensive_closureStep
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V) (S : Set V) :
    S ⊆ closureStep r Φ S := fun _ hx => Or.inl hx

theorem iterUnion_mem_iff
    (f : Set V → Set V) (S : Set V) (x : V) :
    x ∈ iterUnion f S ↔ ∃ n : Nat, x ∈ (f^[n]) S := by
  simp [iterUnion]

theorem iterate_stage_succ_subset
    (f : Set V → Set V) (hExt : ∀ T : Set V, T ⊆ f T)
    (S : Set V) (n : Nat) :
    (f^[n]) S ⊆ (f^[n + 1]) S := by
  simpa [Function.iterate_succ_apply'] using! hExt ((f^[n]) S)

theorem iterate_stage_mono
    (f : Set V → Set V) (hExt : ∀ T : Set V, T ⊆ f T)
    (S : Set V) {n m : Nat} (hnm : n ≤ m) :
    (f^[n]) S ⊆ (f^[m]) S := by
  obtain ⟨d, rfl⟩ := Nat.le.dest hnm
  induction d with
  | zero => simp
  | succ d ih =>
      exact (ih (Nat.le_add_right _ _)).trans (by
        simpa [Nat.add_assoc] using! iterate_stage_succ_subset f hExt S (n + d))

/-- A finite set in an increasing union of iterates already occurs at one
finite stage. -/
theorem finset_subset_iterate_stage
    (f : Set V → Set V) (hExt : ∀ T : Set V, T ⊆ f T)
    (S : Set V) (s : Finset V) :
    (∀ x ∈ s, x ∈ iterUnion f S) →
      ∃ n : Nat, ∀ x ∈ s, x ∈ (f^[n]) S := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      intro _
      exact ⟨0, by simp⟩
  | @insert a s ha ih =>
      intro hs
      have haUnion : a ∈ iterUnion f S := hs a (by simp)
      rcases (iterUnion_mem_iff f S a).mp haUnion with ⟨na, hna⟩
      have hsUnion : ∀ x ∈ s, x ∈ iterUnion f S := by
        intro x hx
        exact hs x (by simp [hx])
      rcases ih hsUnion with ⟨ns, hns⟩
      refine ⟨max na ns, ?_⟩
      intro x hx
      rcases Finset.mem_insert.mp hx with rfl | hx
      · exact iterate_stage_mono f hExt S (Nat.le_max_left _ _) hna
      · exact iterate_stage_mono f hExt S (Nat.le_max_right _ _) (hns x hx)

/-- The seed set is contained in its finite closure. -/
theorem subset_closure
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) :
    S ⊆ closure r Φ S := by
  intro x hx
  apply (iterUnion_mem_iff (closureStep r Φ) S x).mpr
  exact ⟨0, by simpa using! hx⟩

/-- The countable finite closure is closed under one further finite-output
step. -/
theorem closureStep_closure_subset
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) :
    closureStep r Φ (closure r Φ S) ⊆ closure r Φ S := by
  intro x hx
  rw [mem_closureStep_iff] at hx
  rcases hx with hx | ⟨s, hinside, hxout⟩
  · exact hx
  · have hExt : ∀ T : Set V, T ⊆ closureStep r Φ T :=
      extensive_closureStep r Φ
    obtain ⟨n, hn⟩ :=
      finset_subset_iterate_stage (closureStep r Φ) hExt S s.1 hinside
    apply (iterUnion_mem_iff (closureStep r Φ) S x).mpr
    refine ⟨n + 1, ?_⟩
    have hnext : x ∈ closureStep r Φ ((closureStep r Φ)^[n] S) := by
      rw [mem_closureStep_iff]
      exact Or.inr ⟨s, hn, hxout⟩
    simpa [Function.iterate_succ_apply'] using! hnext

/-- A finite closure is a fixed point of its closure step. -/
theorem closureStep_closure_eq
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) :
    closureStep r Φ (closure r Φ S) = closure r Φ S := by
  apply Set.Subset.antisymm (closureStep_closure_subset r Φ S)
  exact extensive_closureStep r Φ _

/-- The finite closure is contained in every closed superset of its seed. -/
theorem closure_min
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    {S T : Set V} (hST : S ⊆ T)
    (hTclosed : closureStep r Φ T ⊆ T) :
    closure r Φ S ⊆ T := by
  intro x hx
  rcases (iterUnion_mem_iff (closureStep r Φ) S x).mp hx with ⟨n, hx⟩
  have hstage : ∀ n : Nat, (closureStep r Φ)^[n] S ⊆ T := by
    intro n
    induction n with
    | zero => simpa using! hST
    | succ n ih =>
        have hnext : closureStep r Φ ((closureStep r Φ)^[n] S) ⊆
            closureStep r Φ T :=
          (closureStep_mono r Φ) ih
        simpa [Function.iterate_succ_apply'] using! hnext.trans hTclosed
  exact hstage n hx

/-- Finite closures are monotone in their seed sets. -/
theorem closure_mono
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V) :
    Monotone (closure r Φ) := by
  intro S T hST x hx
  simp only [closure, iterUnion, Set.mem_iUnion] at hx ⊢
  rcases hx with ⟨n, hx⟩
  have hiter : Monotone ((closureStep r Φ)^[n]) :=
    (closureStep_mono r Φ).iterate n
  exact ⟨n, hiter hST hx⟩

/-- A countable union of iterates preserves every infinite cardinal bound
preserved by the step function. -/
theorem mk_iterUnion_le
    (f : Set V → Set V) (S : Set V) (c : Cardinal.{u})
    (hc : Cardinal.aleph0 ≤ c)
    (hstep : ∀ T : Set V, Cardinal.mk T ≤ c → Cardinal.mk (f T) ≤ c)
    (hS : Cardinal.mk S ≤ c) :
    Cardinal.mk (iterUnion f S) ≤ c := by
  have hiter : ∀ n : Nat, Cardinal.mk ((f^[n]) S) ≤ c := by
    intro n
    induction n with
    | zero => simpa using! hS
    | succ n ih =>
        simpa [Function.iterate_succ_apply'] using! hstep ((f^[n]) S) ih
  calc
    Cardinal.mk (iterUnion f S) ≤
        Cardinal.lift.{u} (Cardinal.mk Nat) *
          ⨆ n : Nat, Cardinal.lift.{0} (Cardinal.mk ((f^[n]) S)) := by
      simpa [iterUnion] using!
        (Cardinal.mk_iUnion_le_lift (fun n : Nat => (f^[n]) S))
    _ ≤ c * c := by
      exact mul_le_mul' (by simpa using! hc) (ciSup_le fun n => by simpa using! hiter n)
    _ = c := Cardinal.mul_eq_self hc

theorem mk_iterUnion_lt_of_bound
    (f : Set V → Set V) (S : Set V) (c κ : Cardinal.{u})
    (hc : Cardinal.aleph0 ≤ c)
    (hcκ : c < κ)
    (hstep : ∀ T : Set V, Cardinal.mk T ≤ c → Cardinal.mk (f T) ≤ c)
    (hS : Cardinal.mk S ≤ c) :
    Cardinal.mk (iterUnion f S) < κ :=
  (mk_iterUnion_le f S c hc hstep hS).trans_lt hcκ

/-- A finite closure of a set below an infinite cardinal stays below that
same cardinal. -/
theorem mk_closure_le
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) (c : Cardinal.{u})
    (hc : Cardinal.aleph0 ≤ c) (hS : Cardinal.mk S ≤ c) :
    Cardinal.mk (closure r Φ S) ≤ c := by
  apply mk_iterUnion_le (closureStep r Φ) S c hc
  · intro T hT
    exact mk_closureStep_le r Φ T c hc hT
  · exact hS

/-- A finite closure of a set of cardinality below an uncountable cardinal
again has cardinality below that cardinal.  No regularity assumption on `κ`
is used. -/
theorem mk_closure_lt
    (r : Nat) (Φ : {s : Finset V // s.card = r} → Finset V)
    (S : Set V) (κ : Cardinal.{u})
    (hκ : Cardinal.aleph0 < κ) (hS : Cardinal.mk S < κ) :
    Cardinal.mk (closure r Φ S) < κ := by
  let c : Cardinal.{u} := max Cardinal.aleph0 (Cardinal.mk S)
  have hc : Cardinal.aleph0 ≤ c := le_max_left _ _
  have hSc : Cardinal.mk S ≤ c := le_max_right _ _
  have hcκ : c < κ := max_lt hκ hS
  exact (mk_closure_le r Φ S c hc hSc).trans_lt hcκ

/-- The image of a proper initial segment of the canonical well-order of a
cardinal has strictly smaller cardinality. -/
theorem mk_ordInitialImage_lt
    (κ : Cardinal.{u}) (e : κ.ord.ToType → V) (i : κ.ord.ToType) :
    Cardinal.mk (e '' Set.Iio i) < κ := by
  have hIio : Cardinal.mk (Set.Iio i) < Cardinal.mk κ.ord.ToType := by
    simpa using! Cardinal.mk_Iio_lt i
  exact ((Cardinal.mk_image_le (f := e) (s := Set.Iio i)).trans_lt hIio).trans_eq
    (Cardinal.mk_ord_toType κ)

/-- The image of a closed initial segment of the canonical well-order of an
uncountable cardinal has strictly smaller cardinality. -/
theorem mk_ordClosedInitialImage_lt
    (κ : Cardinal.{u}) (e : κ.ord.ToType → V) (i : κ.ord.ToType)
    (hκ : Cardinal.aleph0 < κ) :
    Cardinal.mk (e '' Set.Iic i) < κ := by
  have hIic : Cardinal.mk (Set.Iic i) < Cardinal.mk κ.ord.ToType := by
    simpa using! Cardinal.mk_Iic_lt i (by simp) (by simpa using! hκ.le)
  exact ((Cardinal.mk_image_le (f := e) (s := Set.Iic i)).trans_lt hIic).trans_eq
    (Cardinal.mk_ord_toType κ)

end FiniteClosureCardinality

end Erdos593
