import Mathlib.Combinatorics.Compactness
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise
import Mathlib.Algebra.BigOperators.Group.Finset.Sigma
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Finset.Card
import Mathlib.Tactic.GCongr
import Mathlib.Tactic.Linarith

set_option relaxedAutoImplicit true
set_option backward.defeqAttrib.useBackward true
set_option backward.isDefEq.respectTransparency false

/-!
# Finite-outdegree colouring

This file isolates the compactness lemma used by the rooted-abundance
argument.  A family `targets x` specifies at most `d` directed neighbours of
each vertex.  The undirected graph generated by those arrows has a proper
colouring with `2 * d + 1` colours.  The finite argument is greedy deletion
after a double-counting estimate, and `Finset.rado_selection` supplies the
global colouring.
-/

namespace Erdos593

open scoped BigOperators

universe u

namespace FiniteOutdegreeColoring

variable {α : Type u}

section Finite

variable [DecidableEq α]

/-- Neighbours, inside `s`, in the undirected graph generated by the directed
sets `targets`. -/
def neighbors (targets : α → Finset α) (s : Finset α) (x : α) : Finset α :=
  s.filter fun y => y ≠ x ∧ (y ∈ targets x ∨ x ∈ targets y)

/-- Outgoing targets which remain inside a finite set. -/
private def outgoing (targets : α → Finset α) (s : Finset α) (x : α) : Finset α :=
  (targets x).filter fun y => y ∈ s

/-- Generators inside a finite set which point to a prescribed vertex. -/
private def incoming (targets : α → Finset α) (s : Finset α) (x : α) : Finset α :=
  s.filter fun y => x ∈ targets y

private theorem neighbors_subset_union (targets : α → Finset α)
    (s : Finset α) (x : α) :
    neighbors targets s x ⊆ outgoing targets s x ∪ incoming targets s x := by
  intro y hy
  simp only [neighbors, Finset.mem_filter] at hy
  rcases hy.2.2 with hyout | hyin
  · exact Finset.mem_union_left _ (by simp [outgoing, hy.1, hyout])
  · exact Finset.mem_union_right _ (by simp [incoming, hy.1, hyin])

private theorem sum_incoming_eq_sum_outgoing (targets : α → Finset α)
    (s : Finset α) :
    (∑ x ∈ s, (incoming targets s x).card) =
      ∑ x ∈ s, (outgoing targets s x).card := by
  rw [show (∑ x ∈ s, (incoming targets s x).card) =
      ∑ x ∈ s, ∑ y ∈ s, if x ∈ targets y then 1 else 0 by
        simp only [incoming, Finset.card_filter]]
  rw [Finset.sum_comm]
  simp only [outgoing, Finset.card_filter]
  apply Finset.sum_congr rfl
  intro y hy
  rw [← Finset.card_filter, ← Finset.card_filter]
  congr 1
  ext z
  simp [and_comm]

/-- The generated undirected graph has average degree at most `2*d` on every
finite vertex set. -/
theorem sum_neighbors_le (targets : α → Finset α) (d : ℕ)
    (hcard : ∀ x, (targets x).card ≤ d) (s : Finset α) :
    (∑ x ∈ s, (neighbors targets s x).card) ≤ 2 * s.card * d := by
  calc
    (∑ x ∈ s, (neighbors targets s x).card) ≤
        ∑ x ∈ s, ((outgoing targets s x).card + (incoming targets s x).card) := by
      gcongr with x hx
      exact (Finset.card_le_card (neighbors_subset_union targets s x)).trans
        (Finset.card_union_le _ _)
    _ = (∑ x ∈ s, (outgoing targets s x).card) +
        ∑ x ∈ s, (incoming targets s x).card := by
      simp only [Finset.sum_add_distrib]
    _ = 2 * (∑ x ∈ s, (outgoing targets s x).card) := by
      rw [sum_incoming_eq_sum_outgoing]
      rw [two_mul]
    _ ≤ 2 * (s.card * d) := by
      gcongr
      calc
        (∑ x ∈ s, (outgoing targets s x).card) ≤ ∑ _x ∈ s, d := by
          gcongr with x hx
          exact (Finset.card_filter_le _ _).trans (hcard x)
        _ = s.card * d := by simp
    _ = 2 * s.card * d := by ac_rfl

/-- Some vertex of every nonempty finite set has at most `2*d` generated
neighbours in that set. -/
theorem exists_neighbors_card_le (targets : α → Finset α) (d : ℕ)
    (hcard : ∀ x, (targets x).card ≤ d) {s : Finset α} (hs : s.Nonempty) :
    ∃ x ∈ s, (neighbors targets s x).card ≤ 2 * d := by
  by_contra h
  push Not at h
  have hlower : s.card * (2 * d + 1) ≤
      ∑ x ∈ s, (neighbors targets s x).card := by
    calc
      s.card * (2 * d + 1) = ∑ _x ∈ s, (2 * d + 1) := by simp
      _ ≤ ∑ x ∈ s, (neighbors targets s x).card := by
        gcongr with x hx
        exact Nat.succ_le_iff.mpr (h x hx)
  have hupper := sum_neighbors_le targets d hcard s
  have hpos : 0 < s.card := Finset.card_pos.mpr hs
  nlinarith

/-- Properness of a colouring on a finite vertex set for the graph generated
by `targets`. -/
def ProperOn (targets : α → Finset α) (s : Finset α)
    {C : Type*} (color : α → C) : Prop :=
  ∀ ⦃x y : α⦄, x ∈ s → y ∈ s → x ≠ y →
    (y ∈ targets x ∨ x ∈ targets y) → color x ≠ color y

/-- Every finite induced subgraph generated by `targets` has the greedy
`2*d+1` colouring. -/
theorem finite_properColoring (targets : α → Finset α) (d : ℕ)
    (hcard : ∀ x, (targets x).card ≤ d) (s : Finset α) :
    ∃ color : α → Fin (2 * d + 1), ProperOn targets s color := by
  classical
  induction hsize : s.card using Nat.strong_induction_on generalizing s with
  | h n ih =>
      by_cases hs : s.Nonempty
      · obtain ⟨x, hx, hxdeg⟩ := exists_neighbors_card_le targets d hcard hs
        have herase_card : (s.erase x).card < n := by
          rw [← hsize]
          exact Finset.card_erase_lt_of_mem hx
        obtain ⟨color, hcolor⟩ := ih (s.erase x).card herase_card (s.erase x) rfl
        let used : Finset (Fin (2 * d + 1)) :=
          (neighbors targets s x).image color
        have hused : used.card < Fintype.card (Fin (2 * d + 1)) := by
          calc
            used.card ≤ (neighbors targets s x).card := Finset.card_image_le
            _ ≤ 2 * d := hxdeg
            _ < 2 * d + 1 := Nat.lt_succ_self _
            _ = Fintype.card (Fin (2 * d + 1)) := by simp
        obtain ⟨fresh, hfresh⟩ : ∃ fresh : Fin (2 * d + 1), fresh ∉ used := by
          by_contra hall
          push Not at hall
          have huniv : used = Finset.univ := Finset.eq_univ_of_forall hall
          rw [huniv, Finset.card_univ] at hused
          exact (Nat.lt_irrefl _ hused)
        let color' : α → Fin (2 * d + 1) := fun y =>
          if y = x then fresh else color y
        refine ⟨color', ?_⟩
        intro y z hy hz hyz hadj
        by_cases hyx : y = x
        · subst y
          have hzmem : z ∈ neighbors targets s x := by
            exact Finset.mem_filter.mpr ⟨hz, hyz.symm, hadj⟩
          have hcz : color z ∈ used := by
            exact Finset.mem_image.mpr ⟨z, hzmem, rfl⟩
          simp only [color', if_pos rfl, if_neg hyz.symm]
          intro heq
          apply hfresh
          rw [heq]
          exact hcz
        · by_cases hzx : z = x
          · subst z
            have hymem : y ∈ neighbors targets s x := by
              exact Finset.mem_filter.mpr ⟨hy, hyx, hadj.elim Or.inr Or.inl⟩
            have hcy : color y ∈ used := by
              exact Finset.mem_image.mpr ⟨y, hymem, rfl⟩
            simp only [color', if_neg hyx, if_pos rfl]
            intro heq
            apply hfresh
            rw [← heq]
            exact hcy
          · simp only [color', if_neg hyx, if_neg hzx]
            apply hcolor
            · simpa [Finset.mem_erase, hyx] using! hy
            · simpa [Finset.mem_erase, hzx] using! hz
            · exact hyz
            · exact hadj
      · have hempty : s = ∅ := Finset.not_nonempty_iff_eq_empty.mp hs
        exact ⟨fun _ => 0, by simp [ProperOn, hempty]⟩

end Finite

section Infinite

/-- A uniformly finite family of directed target sets generates a finitely
colourable undirected graph.  This is the exact de Bruijn--Erdős compactness
boundary used in the rooted-abundance proof. -/
theorem exists_coloring (targets : α → Finset α) (d : ℕ)
    (hcard : ∀ x, (targets x).card ≤ d) :
    ∃ color : α → Fin (2 * d + 1),
      ∀ ⦃x y : α⦄, x ≠ y → (y ∈ targets x ∨ x ∈ targets y) →
        color x ≠ color y := by
  classical
  let localColor : Finset α → α → Fin (2 * d + 1) := fun s =>
    Classical.choose (finite_properColoring targets d hcard s)
  have hlocal (s : Finset α) : ProperOn targets s (localColor s) :=
    Classical.choose_spec (finite_properColoring targets d hcard s)
  obtain ⟨color, hcolor⟩ := Finset.rado_selection localColor
  refine ⟨color, ?_⟩
  intro x y hxy hadj
  obtain ⟨t, hsub, hagree⟩ := hcolor {x, y}
  have hxt : x ∈ t := hsub (by simp)
  have hyt : y ∈ t := hsub (by simp)
  rw [hagree x (by simp), hagree y (by simp)]
  exact hlocal t hxt hyt hxy hadj

end Infinite

end FiniteOutdegreeColoring

end Erdos593
