import ErdosProblems.Erdos228.FullColoring
import ErdosProblems.Erdos228.KernelClaims
import ErdosProblems.Erdos228.Rounding

/-!
# The odd-sine part of the BBMST construction

This file isolates Section 5 of Balister--Bollobas--Morris--Sahasrabudhe--
Tiba.  A suitable family of short, separated grid intervals first gets a
symmetric sign colouring.  Its odd Fourier coefficients form a point of the
cube.  A second full-colouring argument rounds that point to signs while
controlling every derivative on a finite mesh.  Taylor expansion then gives
the uniform rounding error, which is combined with the odd Dirichlet-kernel
estimate.

The geometric facts about the interval family and the aggregate output of
the three kernel claims are explicit structures.  Thus downstream files can
construct them from the dangerous intervals without hiding any analytic
hypothesis in the final polynomial theorem.
-/

namespace Erdos228.OddSine

open scoped BigOperators Interval
open Set

noncomputable section

/-! ## Suitable interval families and their Fourier data -/

/-- The numerical multiplier in BBMST Section 5. -/
def K : ℝ := 2 ^ 7

@[simp] theorem K_eq : K = 128 := by norm_num [K]

/-- A closed real interval represented by its ordered endpoints. -/
abbrev RealInterval := ℝ × ℝ

/-- Membership in the closed interval represented by `I`. -/
def InInterval (I : RealInterval) (theta : ℝ) : Prop :=
  theta ∈ Icc I.1 I.2

/-- The part of a suitable fourfold-symmetric family in `[0, pi / 2]`.
The remaining intervals are obtained by the reflections used in BBMST.
All geometric properties consumed by the two colouring arguments are stated
here, rather than being implicit in an enumeration. -/
structure SuitableIntervalFamily (n : ℕ) where
  base : Finset RealInterval
  ordered : ∀ I ∈ base, I.1 ≤ I.2
  /-- Suitable intervals contain at least one full `pi / n` grid cell.
  In particular their two grid endpoints are distinct.  This is the
  `a < b` hypothesis in BBMST Lemma 5.8. -/
  nondegenerate : ∀ I ∈ base, I.1 < I.2
  in_first_quadrant : ∀ I ∈ base, 0 ≤ I.1 ∧ I.2 ≤ Real.pi / 2
  grid_endpoints : ∀ I ∈ base, ∃ a b : ℤ,
    I.1 = (a : ℝ) * Real.pi / n ∧ I.2 = (b : ℝ) * Real.pi / n
  short : ∀ I ∈ base, I.2 - I.1 ≤ 6 * Real.pi / n
  separated : Set.Pairwise ((↑base : Set RealInterval))
    (fun I J ↦ ∀ x ∈ Icc I.1 I.2, ∀ y ∈ Icc J.1 J.2,
      Real.pi / n ≤ |x - y|)
  away_from_axes : ∀ I ∈ base,
    100 * Real.pi / n ≤ I.1 ∧ I.2 ≤ Real.pi / 2 - 100 * Real.pi / n

/-- The dangerous set generated by the base intervals and the three
reflections `theta ↦ -theta`, `theta ↦ pi-theta`, and
`theta ↦ pi+theta`. -/
def IsDangerous {n : ℕ} (F : SuitableIntervalFamily n) (theta : ℝ) : Prop :=
  ∃ I ∈ F.base,
    InInterval I theta ∨ InInterval I (-theta) ∨
      InInterval I (Real.pi - theta) ∨ InInterval I (theta - Real.pi)

/-- One coordinate vector in the first discrepancy problem. -/
def firstVector {n : ℕ} (F : SuitableIntervalFamily n) (j : Fin n) :
    (↑F.base : Type) → ℝ :=
  fun I ↦ 4 * K * Real.sqrt n *
    ∫ theta in I.1.1..I.1.2,
      Real.sin ((Erdos228.Rounding.oddFrequency j : ℝ) * theta)

/-- The shortness of every interval gives the sup-norm estimate used in the
first colouring.  This is the unsimplified form
`24*pi*K*sqrt(n)/n`, avoiding division by `sqrt n` downstream. -/
theorem norm_firstVector_le {n : ℕ} (hn : 0 < n)
    (F : SuitableIntervalFamily n) (j : Fin n) :
    ‖firstVector F j‖ ≤
      24 * K * Real.pi * Real.sqrt n / n := by
  rw [pi_norm_le_iff_of_nonneg]
  · intro I
    rw [Real.norm_eq_abs]
    simp only [firstVector, abs_mul]
    have hintegral :
        ‖∫ theta in I.1.1..I.1.2,
            Real.sin ((Erdos228.Rounding.oddFrequency j : ℝ) * theta)‖ ≤
          I.1.2 - I.1.1 := by
      have h := intervalIntegral.norm_integral_le_of_norm_le_const
        (a := I.1.1) (b := I.1.2) (C := (1 : ℝ))
        (f := fun theta : ℝ ↦
          Real.sin ((Erdos228.Rounding.oddFrequency j : ℝ) * theta))
        (fun theta htheta ↦ by
          simpa [Real.norm_eq_abs] using
            Real.abs_sin_le_one
              ((Erdos228.Rounding.oddFrequency j : ℝ) * theta))
      simpa [abs_of_nonneg (sub_nonneg.2 (F.ordered I I.2))] using h
    have hwidth := F.short I I.2
    have hnR : (0 : ℝ) < n := by exact_mod_cast hn
    have hK : (0 : ℝ) ≤ K := by norm_num [K]
    have hcoefficient : 0 ≤ 4 * K * Real.sqrt n := by positivity
    calc
      |4| * |K| * |Real.sqrt ↑n| *
          |∫ theta in I.1.1..I.1.2,
            Real.sin ((Erdos228.Rounding.oddFrequency ↑j : ℝ) * theta)| ≤
          (4 * K * Real.sqrt n) * (I.1.2 - I.1.1) := by
            rw [abs_of_nonneg (by norm_num : (0 : ℝ) ≤ 4),
              abs_of_nonneg (by norm_num [K] : (0 : ℝ) ≤ K),
              abs_of_nonneg (Real.sqrt_nonneg _)]
            exact mul_le_mul_of_nonneg_left hintegral hcoefficient
      _ ≤ (4 * K * Real.sqrt n) * (6 * Real.pi / n) := by
            exact mul_le_mul_of_nonneg_left hwidth hcoefficient
      _ = 24 * K * Real.pi * Real.sqrt n / n := by ring
  · have hK : (0 : ℝ) ≤ K := by norm_num [K]
    positivity

/-- The target coefficient obtained from a colouring of the base intervals.
Fourfold symmetry is responsible for the factor `4`. -/
def fourierTarget {n : ℕ} (F : SuitableIntervalFamily n)
    (alpha : (↑F.base : Type) → ℝ) (j : ℕ) : ℝ :=
  if _hj : j < n then
    ∑ I : (↑F.base : Type),
      alpha I * (4 * K * Real.sqrt n *
        ∫ theta in I.1.1..I.1.2,
          Real.sin ((Erdos228.Rounding.oddFrequency j : ℝ) * theta))
  else 0

theorem fourierTarget_eq_dot {n : ℕ} (F : SuitableIntervalFamily n)
    (alpha : (↑F.base : Type) → ℝ) (j : Fin n) :
    fourierTarget F alpha j = Erdos228.Discrepancy.dot alpha (firstVector F j) := by
  simp [fourierTarget, firstVector, Erdos228.Discrepancy.dot, j.isLt]

/-- The trigonometric polynomial with the target Fourier coefficients. -/
def targetSine {n : ℕ} (F : SuitableIntervalFamily n)
    (alpha : (↑F.base : Type) → ℝ) (theta : ℝ) : ℝ :=
  Erdos228.Rounding.oddSineSum n (fourierTarget F alpha) theta

/-! ## First colouring -/

/-- The finite numerical conditions needed for the first invocation of the
full-colouring corollary.  For the BBMST family they follow from
`F.base.card ≤ gamma*n`, `gamma ≤ 2^-40`, and `F.short`. -/
structure FirstColoringAdmissible {n : ℕ}
    (F : SuitableIntervalFamily n) (c : Fin n → ℝ) : Prop where
  parameter_nonneg : ∀ j, 0 ≤ c j
  budget : (∑ j, Real.exp (-(c j) ^ 2 / 196)) ≤
    (Fintype.card (↑F.base : Type) : ℝ) / 16
  unit_error : ∀ j,
    (c j + 30) * Real.sqrt (Fintype.card (↑F.base : Type)) *
      ‖firstVector F j‖ ≤ 1

/-- Reduce admissibility to the scalar BBMST estimate after applying the
interval-length bound. -/
theorem firstColoringAdmissible_of_numeric {n : ℕ} (hn : 0 < n)
    (F : SuitableIntervalFamily n) (c : Fin n → ℝ)
    (hc : ∀ j, 0 ≤ c j)
    (hbudget : (∑ j, Real.exp (-(c j) ^ 2 / 196)) ≤
      (Fintype.card (↑F.base : Type) : ℝ) / 16)
    (hscalar : ∀ j,
      (c j + 30) * Real.sqrt (Fintype.card (↑F.base : Type)) *
        (24 * K * Real.pi * Real.sqrt n / n) ≤ 1) :
    FirstColoringAdmissible F c := by
  refine ⟨hc, hbudget, ?_⟩
  intro j
  have hleft : 0 ≤
      (c j + 30) * Real.sqrt (Fintype.card (↑F.base : Type)) :=
    mul_nonneg (by linarith [hc j]) (Real.sqrt_nonneg _)
  exact (mul_le_mul_of_nonneg_left (norm_firstVector_le hn F j) hleft).trans
    (hscalar j)

/-- The first full colouring chooses the interval signs and puts every odd
Fourier target coefficient in `[-1,1]`. -/
theorem exists_intervalColoring {n : ℕ} (F : SuitableIntervalFamily n)
    (c : Fin n → ℝ) (hc : FirstColoringAdmissible F c)
    (hLM : ∀ (I : Type) [Fintype I] [DecidableEq I],
      Erdos228.Discrepancy.PartialColoringPrinciple I (Fin n)) :
    ∃ alpha : (↑F.base : Type) → ℝ,
      Erdos228.Discrepancy.IsSign alpha ∧ ∀ j < n, |fourierTarget F alpha j| ≤ 1 := by
  classical
  have hzero : Erdos228.Discrepancy.InCube (0 : (↑F.base : Type) → ℝ) := by
    intro I
    simp
  obtain ⟨alpha, halpha, herror⟩ :=
    Erdos228.Discrepancy.hasFullColoring_of_partialColoringPrinciple hLM
      (firstVector F) (0 : (↑F.base : Type) → ℝ) c hzero
      hc.parameter_nonneg hc.budget
  refine ⟨alpha, halpha, ?_⟩
  intro j hj
  let jf : Fin n := ⟨j, hj⟩
  rw [fourierTarget_eq_dot F alpha jf]
  simpa [jf] using (herror jf).trans (hc.unit_error jf)

/-! ## Aggregate odd-kernel certificate -/

/-- A decomposition of the normalized odd Dirichlet-kernel integral into
its main interval and the aggregate of Claims 1--3.  The local calculus and
telescoping estimates producing these fields live in `KernelClaims`. -/
structure KernelCertificate {n : ℕ} (F : SuitableIntervalFamily n)
    (alpha : (↑F.base : Type) → ℝ) where
  main : ℝ → ℝ
  error : ℝ → ℝ
  decomposition : ∀ theta,
    targetSine F alpha theta =
      (K * Real.sqrt n) * (main theta + error theta)
  main_lower : ∀ theta, IsDangerous F theta → 4 / 3 ≤ |main theta|
  main_upper : ∀ theta, |main theta| ≤ 4
  error_bound : ∀ theta, |error theta| ≤ 2 / 3

/-- The aggregate kernel certificate gives precisely BBMST Lemma 5.6. -/
theorem targetSine_kernel_bounds {n : ℕ} (_hn : 0 < n)
    (F : SuitableIntervalFamily n) (alpha : (↑F.base : Type) → ℝ)
    (hkernel : KernelCertificate F alpha) :
    (∀ theta, IsDangerous F theta →
      (2 * K / 3) * Real.sqrt n ≤ |targetSine F alpha theta|) ∧
    (∀ theta, |targetSine F alpha theta| ≤ 5 * K * Real.sqrt n) := by
  constructor
  · intro theta htheta
    have hnormalized := Erdos228.KernelClaims.normalized_kernel_bounds
      (value := hkernel.main theta + hkernel.error theta)
      (main := hkernel.main theta) (error := hkernel.error theta)
      (hvalue := (rfl : hkernel.main theta + hkernel.error theta =
        hkernel.main theta + hkernel.error theta))
      (hmain_lower := hkernel.main_lower theta htheta)
      (hmain_upper := hkernel.main_upper theta)
      (herror := hkernel.error_bound theta)
    rw [hkernel.decomposition theta, abs_mul]
    have hK : 0 ≤ K := by norm_num [K]
    have hfactor : 0 ≤ K * Real.sqrt n := mul_nonneg hK
      (Real.sqrt_nonneg _)
    rw [abs_of_nonneg hfactor]
    calc
      (2 * K / 3) * Real.sqrt n = (K * Real.sqrt n) * (2 / 3) := by ring
      _ ≤ (K * Real.sqrt n) * |hkernel.main theta + hkernel.error theta| :=
        mul_le_mul_of_nonneg_left hnormalized.1 hfactor
  · intro theta
    have hnormalized : |hkernel.main theta + hkernel.error theta| ≤ 5 := by
      calc
        |hkernel.main theta + hkernel.error theta| ≤
            |hkernel.main theta| + |hkernel.error theta| := abs_add_le _ _
        _ ≤ 4 + 2 / 3 :=
          add_le_add (hkernel.main_upper theta) (hkernel.error_bound theta)
        _ ≤ 5 := by norm_num
    rw [hkernel.decomposition theta, abs_mul]
    have hK : 0 ≤ K := by norm_num [K]
    have hfactor : 0 ≤ K * Real.sqrt n := mul_nonneg hK
      (Real.sqrt_nonneg _)
    rw [abs_of_nonneg hfactor]
    calc
      (K * Real.sqrt n) * |hkernel.main theta + hkernel.error theta|
          ≤ (K * Real.sqrt n) * 5 :=
        mul_le_mul_of_nonneg_left hnormalized hfactor
      _ = 5 * K * Real.sqrt n := by ring

/-! ## Second colouring and Taylor rounding -/

/-- The contribution of coefficient `j` to the `l`-th formal derivative at
`theta`. -/
def derivativeVector (n l : ℕ) (theta : ℝ) : Fin n → ℝ :=
  fun j ↦
    ((((((Erdos228.Rounding.oddFrequency j : ℝ) : ℂ) * Complex.I) ^ l) *
      Complex.exp ((((Erdos228.Rounding.oddFrequency j : ℝ) * theta : ℝ) : ℂ) *
        Complex.I))).im

/-- A finite mesh whose derivative constraints suffice for the global Taylor
estimate.  The `cover` field incorporates the elementary odd-frequency
reflections and translations which reduce an arbitrary angle to the mesh. -/
structure RoundingSetup (n : ℕ) (G : Type) [Fintype G] where
  point : G → ℝ
  parameter : G × Fin n → ℝ
  parameter_nonneg : ∀ q, 0 ≤ parameter q
  budget : (∑ q, Real.exp (-(parameter q) ^ 2 / 196)) ≤ (n : ℝ) / 16
  parameter_bound : ∀ g l, parameter (g, l) + 30 ≤ 65 + 2 * (l : ℕ)
  cover : ∀ (a : ℕ → ℝ) (theta : ℝ), ∃ g theta',
    |theta' - point g| ≤ Real.pi / (64 * n) ∧
      |Erdos228.Rounding.oddSineSum n a theta| =
        |Erdos228.Rounding.oddSineSum n a theta'|

theorem oddSineDerivative_eq_dot (n l : ℕ) (a : ℕ → ℝ) (theta : ℝ) :
    Erdos228.Rounding.oddSineDerivative l n a theta =
      Erdos228.Discrepancy.dot (fun j : Fin n ↦ a j)
        (derivativeVector n l theta) := by
  classical
  simp only [Erdos228.Rounding.oddSineDerivative,
    Erdos228.Rounding.oddExponentialDerivative,
    derivativeVector, Erdos228.Discrepancy.dot]
  change Complex.imLm
      (∑ j ∈ Finset.range n, (a j : ℂ) *
        (((Erdos228.Rounding.oddFrequency j : ℝ) : ℂ) * Complex.I) ^ l *
          Complex.exp ((((Erdos228.Rounding.oddFrequency j : ℝ) * theta : ℝ) : ℂ) *
            Complex.I)) = _
  rw [map_sum Complex.imLm]
  change (∑ j ∈ Finset.range n,
    ((a j : ℂ) *
      (((Erdos228.Rounding.oddFrequency j : ℝ) : ℂ) * Complex.I) ^ l *
        Complex.exp ((((Erdos228.Rounding.oddFrequency j : ℝ) * theta : ℝ) : ℂ) *
          Complex.I)).im) = _
  rw [← Fin.sum_univ_eq_sum_range (fun j : ℕ ↦
    ((a j : ℂ) *
      (((Erdos228.Rounding.oddFrequency j : ℝ) : ℂ) * Complex.I) ^ l *
        Complex.exp ((((Erdos228.Rounding.oddFrequency j : ℝ) * theta : ℝ) : ℂ) *
          Complex.I)).im) n]
  apply Finset.sum_congr rfl
  intro j hj
  rw [mul_assoc, Complex.mul_im]
  simp

theorem norm_derivativeVector_le {n l : ℕ} (theta : ℝ) :
    ‖derivativeVector n l theta‖ ≤ (2 * n : ℝ) ^ l := by
  rw [pi_norm_le_iff_of_nonneg (by positivity)]
  intro j
  rw [Real.norm_eq_abs]
  have him := Complex.abs_im_le_norm
    ((((((Erdos228.Rounding.oddFrequency j : ℝ) : ℂ) * Complex.I) ^ l) *
      Complex.exp ((((Erdos228.Rounding.oddFrequency j : ℝ) * theta : ℝ) : ℂ) *
        Complex.I)))
  change |((((((Erdos228.Rounding.oddFrequency j : ℝ) : ℂ) * Complex.I) ^ l) *
      Complex.exp ((((Erdos228.Rounding.oddFrequency j : ℝ) * theta : ℝ) : ℂ) *
        Complex.I))).im| ≤ _
  refine him.trans ?_
  simp only [norm_mul, norm_pow, Complex.norm_I, mul_one,
      Complex.norm_exp_ofReal_mul_I]
  rw [Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg (by positivity)]
  have hfreq : (Erdos228.Rounding.oddFrequency j : ℝ) ≤ 2 * n := by
    exact_mod_cast Erdos228.Rounding.oddFrequency_le_two_mul
      (Finset.mem_range.2 j.isLt)
  exact pow_le_pow_left₀ (by positivity) hfreq l

theorem oddSineSum_sub (n : ℕ) (a b : ℕ → ℝ) (theta : ℝ) :
    Erdos228.Rounding.oddSineSum n (a - b) theta =
      Erdos228.Rounding.oddSineSum n a theta -
        Erdos228.Rounding.oddSineSum n b theta := by
  classical
  simp only [Erdos228.Rounding.oddSineSum, Pi.sub_apply, sub_mul,
    Finset.sum_sub_distrib]

/-- Every odd sine sum is odd. -/
theorem oddSineSum_neg (n : ℕ) (a : ℕ → ℝ) (theta : ℝ) :
    Erdos228.Rounding.oddSineSum n a (-theta) =
      -Erdos228.Rounding.oddSineSum n a theta := by
  classical
  simp [Erdos228.Rounding.oddSineSum, mul_neg]

/-- Reflection in `pi / 2` fixes every odd sine sum. -/
theorem oddSineSum_pi_sub (n : ℕ) (a : ℕ → ℝ) (theta : ℝ) :
    Erdos228.Rounding.oddSineSum n a (Real.pi - theta) =
      Erdos228.Rounding.oddSineSum n a theta := by
  classical
  simp only [Erdos228.Rounding.oddSineSum]
  apply Finset.sum_congr rfl
  intro j hj
  congr 1
  rw [mul_sub]
  have hrewrite :
      (Erdos228.Rounding.oddFrequency j : ℝ) * Real.pi -
          (Erdos228.Rounding.oddFrequency j : ℝ) * theta =
        (Erdos228.Rounding.oddFrequency j : ℕ) * Real.pi -
          (Erdos228.Rounding.oddFrequency j : ℝ) * theta := by
    norm_num
  rw [hrewrite, Real.sin_nat_mul_pi_sub]
  simp [Erdos228.Rounding.oddFrequency, pow_add]

/-- Translation by `pi` negates every odd sine sum. -/
theorem oddSineSum_add_pi (n : ℕ) (a : ℕ → ℝ) (theta : ℝ) :
    Erdos228.Rounding.oddSineSum n a (theta + Real.pi) =
      -Erdos228.Rounding.oddSineSum n a theta := by
  classical
  simp only [Erdos228.Rounding.oddSineSum, mul_add]
  rw [← Finset.sum_neg_distrib]
  apply Finset.sum_congr rfl
  intro j hj
  rw [show (Erdos228.Rounding.oddFrequency j : ℝ) * theta +
      (Erdos228.Rounding.oddFrequency j : ℝ) * Real.pi =
      (Erdos228.Rounding.oddFrequency j : ℝ) * theta +
        (Erdos228.Rounding.oddFrequency j : ℕ) * Real.pi by norm_num,
    Real.sin_add_nat_mul_pi]
  simp [Erdos228.Rounding.oddFrequency, pow_add]

/-- Absolute values of odd sine sums reduce to the first quadrant. -/
theorem exists_firstQuadrant_abs_oddSineSum_eq
    (n : ℕ) (a : ℕ → ℝ) (theta : ℝ) :
    ∃ theta' ∈ Icc (0 : ℝ) (Real.pi / 2),
      |Erdos228.Rounding.oddSineSum n a theta| =
        |Erdos228.Rounding.oddSineSum n a theta'| := by
  let x := toIcoMod Real.pi_pos 0 theta
  have hxmem : x ∈ Ico (0 : ℝ) Real.pi := by
    simpa [x] using toIcoMod_mem_Ico Real.pi_pos 0 theta
  have hperiodic : Function.Periodic
      (fun y : ℝ ↦ |Erdos228.Rounding.oddSineSum n a y|) Real.pi := by
    intro y
    change |Erdos228.Rounding.oddSineSum n a (y + Real.pi)| =
      |Erdos228.Rounding.oddSineSum n a y|
    rw [oddSineSum_add_pi n a y, abs_neg]
  have hreduce : |Erdos228.Rounding.oddSineSum n a theta| =
      |Erdos228.Rounding.oddSineSum n a x| := by
    have heq := toIcoMod_add_toIcoDiv_zsmul Real.pi_pos 0 theta
    rw [← heq]
    exact hperiodic.zsmul (toIcoDiv Real.pi_pos 0 theta) x
  by_cases hx : x ≤ Real.pi / 2
  · exact ⟨x, ⟨show (0 : ℝ) ≤ x from hxmem.1, hx⟩, hreduce⟩
  · refine ⟨Real.pi - x, ?_, ?_⟩
    · constructor
      · linarith [hxmem.2]
      · linarith
    · rw [hreduce, oddSineSum_pi_sub]

/-- The second full colouring rounds all target coefficients to signs and
costs at most `72*sqrt n` uniformly. -/
theorem exists_rounding {n : ℕ} (hn : 0 < n) {G : Type} [Fintype G]
    [DecidableEq G] (setup : RoundingSetup n G) (hat : ℕ → ℝ)
    (hhat : ∀ j < n, |hat j| ≤ 1)
    (hLM : ∀ (I : Type) [Fintype I] [DecidableEq I],
      Erdos228.Discrepancy.PartialColoringPrinciple I (G × Fin n)) :
    ∃ eps : ℕ → ℝ, (∀ j, eps j = 1 ∨ eps j = -1) ∧
      ∀ theta,
        |Erdos228.Rounding.oddSineSum n eps theta -
          Erdos228.Rounding.oddSineSum n hat theta| ≤
          72 * Real.sqrt n := by
  classical
  let x₀ : Fin n → ℝ := fun j ↦ hat j
  let v : G × Fin n → Fin n → ℝ :=
    fun q ↦ derivativeVector n q.2 (setup.point q.1)
  have hx₀ : Erdos228.Discrepancy.InCube x₀ := by
    intro j
    exact hhat j j.isLt
  have hbudget : (∑ q, Real.exp (-(setup.parameter q) ^ 2 / 196)) ≤
      (Fintype.card (Fin n) : ℝ) / 16 := by
    simpa using setup.budget
  obtain ⟨epsFin, hepsSign, hepsDisc⟩ :=
    Erdos228.Discrepancy.hasFullColoring_of_partialColoringPrinciple
      hLM v x₀ setup.parameter
      hx₀ setup.parameter_nonneg hbudget
  let eps : ℕ → ℝ := fun j ↦ if hj : j < n then epsFin ⟨j, hj⟩ else 1
  refine ⟨eps, ?_, ?_⟩
  · intro j
    by_cases hj : j < n
    · simpa [eps, hj] using hepsSign ⟨j, hj⟩
    · simp [eps, hj]
  · intro theta
    let a : ℕ → ℝ := eps - hat
    obtain ⟨g, theta', hnear, habs⟩ := setup.cover a theta
    have hdisc : ∀ l : ℕ,
        |Erdos228.Rounding.oddSineDerivative l n a (setup.point g)| ≤
          (65 + 2 * l) * Real.sqrt n * (2 * n : ℝ) ^ l := by
      intro l
      by_cases hl : l < n
      · let lf : Fin n := ⟨l, hl⟩
        have hfull := hepsDisc (g, lf)
        have hdot : Erdos228.Discrepancy.dot (epsFin - x₀) (v (g, lf)) =
            Erdos228.Rounding.oddSineDerivative l n a (setup.point g) := by
          rw [oddSineDerivative_eq_dot]
          apply congrArg (fun z : Fin n → ℝ ↦
            Erdos228.Discrepancy.dot z (derivativeVector n l (setup.point g)))
          funext j
          simp [a, eps, x₀, j.isLt]
        rw [← hdot]
        calc
          |Erdos228.Discrepancy.dot (epsFin - x₀) (v (g, lf))| ≤
              (setup.parameter (g, lf) + 30) * Real.sqrt n *
                ‖v (g, lf)‖ := by simpa [v] using hfull
          _ ≤ (65 + 2 * l) * Real.sqrt n * (2 * n : ℝ) ^ l := by
            apply mul_le_mul
            · apply mul_le_mul_of_nonneg_right (setup.parameter_bound g lf)
                (Real.sqrt_nonneg _)
            · simpa [v, lf] using
                (norm_derivativeVector_le (n := n) (l := l) (setup.point g))
            · exact norm_nonneg _
            · exact mul_nonneg (by linarith [setup.parameter_nonneg (g, lf)])
                (Real.sqrt_nonneg _)
      · have hcoeff : ∀ j < n, |a j| ≤ 2 := by
          intro j hj
          have heps : |eps j| = 1 := by
            rcases (show eps j = 1 ∨ eps j = -1 by
              simp only [eps, dif_pos hj]
              exact hepsSign ⟨j, hj⟩) with h | h <;> simp [h]
          calc
            |a j| = |eps j - hat j| := rfl
            _ ≤ |eps j| + |hat j| := abs_sub _ _
            _ ≤ 2 := by linarith [hhat j hj]
        have htrivial :=
          Erdos228.Rounding.abs_oddSineDerivative_le_card_mul l n a 2 hcoeff
          (by norm_num) (setup.point g)
        have hsqrt : 1 ≤ Real.sqrt n := by
          rw [Real.one_le_sqrt]
          exact_mod_cast hn
        have hln : n ≤ l := Nat.le_of_not_gt hl
        calc
          |Erdos228.Rounding.oddSineDerivative l n a (setup.point g)| ≤
              n * 2 * (2 * n : ℝ) ^ l := htrivial
          _ ≤ (65 + 2 * l) * Real.sqrt n * (2 * n : ℝ) ^ l := by
            apply mul_le_mul_of_nonneg_right _ (by positivity)
            have : (n : ℝ) ≤ l := by exact_mod_cast hln
            nlinarith
    have hround := Erdos228.Rounding.abs_oddSineSum_le_seventy_two_sqrt hn a
      (setup.point g) theta' hnear hdisc
    rw [← oddSineSum_sub] at ⊢
    rw [habs]
    exact hround

/-! ## Final odd-sine theorem -/

/-- BBMST's odd-sine construction, with the interval geometry, kernel
certificate, and the two explicit Lovett--Meka inputs exposed at the module
boundary. -/
theorem exists_oddSine {n : ℕ} (hn : 0 < n)
    (F : SuitableIntervalFamily n) (c : Fin n → ℝ)
    (hc : FirstColoringAdmissible F c)
    (hLM₁ : ∀ (I : Type) [Fintype I] [DecidableEq I],
      Erdos228.Discrepancy.PartialColoringPrinciple I (Fin n))
    (hkernel : ∀ alpha : (↑F.base : Type) → ℝ,
      Erdos228.Discrepancy.IsSign alpha → KernelCertificate F alpha)
    {G : Type} [Fintype G] [DecidableEq G] (setup : RoundingSetup n G)
    (hLM₂ : ∀ (I : Type) [Fintype I] [DecidableEq I],
      Erdos228.Discrepancy.PartialColoringPrinciple I (G × Fin n)) :
    ∃ eps : ℕ → ℝ, (∀ j, eps j = 1 ∨ eps j = -1) ∧
      (∀ theta, IsDangerous F theta →
        10 * Real.sqrt n < |Erdos228.Rounding.oddSineSum n eps theta|) ∧
      (∀ theta, |Erdos228.Rounding.oddSineSum n eps theta| ≤
        2 ^ 10 * Real.sqrt n) := by
  obtain ⟨alpha, halpha, htarget⟩ := exists_intervalColoring F c hc hLM₁
  obtain ⟨eps, heps, hround⟩ :=
    exists_rounding hn setup (fourierTarget F alpha) htarget hLM₂
  obtain ⟨hkernelLower, hkernelUpper⟩ :=
    targetSine_kernel_bounds hn F alpha (hkernel alpha halpha)
  refine ⟨eps, heps, ?_, ?_⟩
  · intro theta htheta
    have htri : |targetSine F alpha theta| ≤
        |Erdos228.Rounding.oddSineSum n eps theta| +
          |Erdos228.Rounding.oddSineSum n eps theta - targetSine F alpha theta| := by
      calc
        |targetSine F alpha theta| =
            |Erdos228.Rounding.oddSineSum n eps theta -
              (Erdos228.Rounding.oddSineSum n eps theta -
                targetSine F alpha theta)| := by ring_nf
        _ ≤ _ := abs_sub _ _
    have hlower := hkernelLower theta htheta
    have herror := hround theta
    change |Erdos228.Rounding.oddSineSum n eps theta -
      targetSine F alpha theta| ≤ 72 * Real.sqrt n at herror
    rw [K_eq] at hlower
    have hnR : (0 : ℝ) < n := by exact_mod_cast hn
    nlinarith [Real.sqrt_pos.2 hnR]
  · intro theta
    have htri := abs_add_le (targetSine F alpha theta)
      (Erdos228.Rounding.oddSineSum n eps theta - targetSine F alpha theta)
    have heq : targetSine F alpha theta +
        (Erdos228.Rounding.oddSineSum n eps theta - targetSine F alpha theta) =
          Erdos228.Rounding.oddSineSum n eps theta := by ring
    rw [heq] at htri
    have hu := hkernelUpper theta
    have he := hround theta
    change |Erdos228.Rounding.oddSineSum n eps theta -
      targetSine F alpha theta| ≤ 72 * Real.sqrt n at he
    rw [K_eq] at hu
    norm_num at ⊢
    nlinarith [Real.sqrt_nonneg n]

end

end Erdos228.OddSine
