/-
Copyright (c) 2026.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI Codex
-/
import ErdosProblems.Erdos240.Kummer
import ErdosProblems.Erdos240.RadicalBasisCore
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure

/-!
# The monomial basis for distinct prime thirteenth roots

This module combines the exact degree theorem from `Kummer.lean` with the
purely linear-algebraic construction in `RadicalBasisCore.lean`.  It gives
both the ambient linear-independence statement used in Baker's argument and
an explicit basis of the field generated by the radicals.
-/

noncomputable section

namespace Erdos240.Kummer

/-- For arbitrary choices of thirteenth roots of distinct rational primes in
an algebraic closure, the bounded-exponent monomials are linearly independent
over `ℚ`.  This is the direct consequence of the exact Kummer degree
calculation. -/
theorem linearIndependent_thirteenthRootMonomials_in_isAlgClosure
    {ι Ω : Type*} [Fintype ι] [DecidableEq ι]
    [Field Ω] [Algebra ℚ Ω] [IsAlgClosure ℚ Ω]
    (p : ι → ℕ) (hp : ∀ i, (p i).Prime)
    (hinj : Function.Injective p)
    (beta : ι → Ω)
    (hbeta : ∀ i, beta i ^ 13 = algebraMap ℚ Ω (p i : ℚ)) :
    LinearIndependent ℚ (thirteenthRootMonomial beta) :=
  linearIndependent_thirteenthRootMonomials_of_finrank p beta hbeta
    (finrank_adjoin_thirteenthRoots_primes_rat p hp hinj beta hbeta)

/-- The bounded-exponent monomials are independent in *any* characteristic-zero
field containing the chosen thirteenth roots.  The proof embeds the finite
algebraic field generated by the roots into `AlgebraicClosure ℚ` and pulls
back the algebraic-closure result above.  In particular this theorem applies
directly with ambient field `ℂ`. -/
theorem linearIndependent_thirteenthRootMonomials
    {ι Ω : Type*} [Fintype ι] [DecidableEq ι]
    [Field Ω] [Algebra ℚ Ω] [CharZero Ω]
    (p : ι → ℕ) (hp : ∀ i, (p i).Prime)
    (hinj : Function.Injective p)
    (beta : ι → Ω)
    (hbeta : ∀ i, beta i ^ 13 = algebraMap ℚ Ω (p i : ℚ)) :
    LinearIndependent ℚ (thirteenthRootMonomial beta) := by
  let F := IntermediateField.adjoin ℚ (Set.range beta)
  have hIntegral : ∀ x ∈ Set.range beta, IsIntegral ℚ x := by
    rintro _ ⟨i, rfl⟩
    apply IsIntegral.of_pow (by norm_num : 0 < 13)
    rw [hbeta i]
    exact isIntegral_algebraMap
  letI : Algebra ℚ F := IntermediateField.algebra' F
  letI : Module ℚ F := Algebra.toModule
  letI : Algebra.IsAlgebraic ℚ F :=
    IntermediateField.isAlgebraic_adjoin hIntegral
  letI : Algebra ℚ (AlgebraicClosure ℚ) :=
    AlgebraicClosure.instAlgebra ℚ
  let phi : F →ₐ[ℚ] AlgebraicClosure ℚ := IsAlgClosed.lift
  let betaF : ι → F := fun i ↦
    ⟨beta i, IntermediateField.subset_adjoin ℚ _ (Set.mem_range_self i)⟩
  let betaA : ι → AlgebraicClosure ℚ := fun i ↦ phi (betaF i)
  have hbetaF : ∀ i, betaF i ^ 13 = algebraMap ℚ F (p i : ℚ) := by
    intro i
    apply Subtype.ext
    simpa [betaF] using hbeta i
  have hbetaA : ∀ i, betaA i ^ 13 =
      algebraMap ℚ (AlgebraicClosure ℚ) (p i : ℚ) := by
    intro i
    change phi (betaF i) ^ 13 =
      algebraMap ℚ (AlgebraicClosure ℚ) (p i : ℚ)
    rw [← map_pow, hbetaF i]
    simp
  have hmap : phi.toLinearMap ∘ thirteenthRootMonomialInAdjoin beta =
      thirteenthRootMonomial betaA := by
    funext e
    simp only [Function.comp_apply, AlgHom.toLinearMap_apply]
    rw [show thirteenthRootMonomialInAdjoin beta e =
      ∏ i, betaF i ^ (e i : ℕ) by
        apply Subtype.ext
        simp [thirteenthRootMonomialInAdjoin, thirteenthRootMonomial, betaF]]
    simp [thirteenthRootMonomial, betaA, map_prod, map_pow]
  have hF : LinearIndependent ℚ
      (thirteenthRootMonomialInAdjoin beta) := by
    apply LinearIndependent.of_comp phi.toLinearMap
    rw [hmap]
    exact linearIndependent_thirteenthRootMonomials_in_isAlgClosure
      p hp hinj betaA hbetaA
  have hval : F.val.toLinearMap ∘ thirteenthRootMonomialInAdjoin beta =
      thirteenthRootMonomial beta := by
    funext e
    rfl
  have himage := hF.map' F.val.toLinearMap
    (LinearMap.ker_eq_bot.mpr F.val.injective)
  rw [hval] at himage
  exact himage

/-- The same independent family, with values in the generated intermediate
field rather than in the ambient algebraic closure. -/
theorem linearIndependent_thirteenthRootMonomialsInAdjoin
    {ι Ω : Type*} [Fintype ι] [DecidableEq ι]
    [Field Ω] [Algebra ℚ Ω] [IsAlgClosure ℚ Ω]
    (p : ι → ℕ) (hp : ∀ i, (p i).Prime)
    (hinj : Function.Injective p)
    (beta : ι → Ω)
    (hbeta : ∀ i, beta i ^ 13 = algebraMap ℚ Ω (p i : ℚ)) :
    LinearIndependent ℚ (thirteenthRootMonomialInAdjoin beta) :=
  linearIndependent_thirteenthRootMonomialsInAdjoin_of_finrank p beta hbeta
    (finrank_adjoin_thirteenthRoots_primes_rat p hp hinj beta hbeta)

/-- The bounded-exponent monomial basis of the field obtained by adjoining
thirteenth roots of a finite family of distinct rational primes. -/
noncomputable def thirteenthRootMonomialBasis
    {ι Ω : Type*} [Fintype ι] [DecidableEq ι]
    [Field Ω] [Algebra ℚ Ω] [IsAlgClosure ℚ Ω]
    (p : ι → ℕ) (hp : ∀ i, (p i).Prime)
    (hinj : Function.Injective p)
    (beta : ι → Ω)
    (hbeta : ∀ i, beta i ^ 13 = algebraMap ℚ Ω (p i : ℚ)) :
    Module.Basis (ι → Fin 13) ℚ
      (IntermediateField.adjoin ℚ (Set.range beta)) :=
  thirteenthRootMonomialBasisOfFinrank p beta hbeta
    (finrank_adjoin_thirteenthRoots_primes_rat p hp hinj beta hbeta)

@[simp]
theorem coe_thirteenthRootMonomialBasis
    {ι Ω : Type*} [Fintype ι] [DecidableEq ι]
    [Field Ω] [Algebra ℚ Ω] [IsAlgClosure ℚ Ω]
    (p : ι → ℕ) (hp : ∀ i, (p i).Prime)
    (hinj : Function.Injective p)
    (beta : ι → Ω)
    (hbeta : ∀ i, beta i ^ 13 = algebraMap ℚ Ω (p i : ℚ)) :
    ⇑(thirteenthRootMonomialBasis p hp hinj beta hbeta) =
      thirteenthRootMonomialInAdjoin beta := by
  simp [thirteenthRootMonomialBasis]

end Erdos240.Kummer
