/- leanprover/lean4:v4.33.0  mathlib v4.33.0 -/
import Mathlib
import ErdosProblems.Erdos360.TernaryClosure

/-!
# Structured integer sets from the `3k - 4` bound

This module formalizes the induction of Balasubramanian--Pandey,
*On Freiman's 3k-4 theorem*.  The conclusion is exactly the universal
ternary-generation predicate used by the fibre argument for Erdős 360.
-/

namespace Erdos360

open scoped Pointwise

/-- A finite integer set is structured up to dilation when some ordered
pair ternary-generates it.  The difference of the pair is automatically a
common modulus for the whole set. -/
def ProgressionTernaryGenerates (A : Finset ℕ) : Prop :=
  ∃ p q : ℕ, p < q ∧ TernaryGenerates A p q

/-- Every point generated by `p,q` is congruent to `p` modulo `q-p`. -/
lemma modEq_of_ternaryGenerates
    {A : Finset ℕ} {p q : ℕ} (hpq : p < q)
    (hgen : TernaryGenerates A p q) :
    ∀ a ∈ A, a ≡ p [MOD q - p] := by
  let C : Set ℕ := {a | a ∈ A ∧ a ≡ p [MOD q - p]}
  have hpC : p ∈ C := ⟨hgen.1, Nat.ModEq.rfl⟩
  have hqC : q ∈ C := by
    refine ⟨hgen.2.1, ?_⟩
    exact ((Nat.modEq_iff_dvd' hpq.le).2 ⟨1, by omega⟩).symm
  have hclosed : ∀ a ∈ C, ∀ b ∈ C, ∀ c ∈ C, ∀ z ∈ A,
      z + a = b + c → z ∈ C := by
    intro a ha b hb c hc z hz hrel
    refine ⟨hz, ?_⟩
    apply Nat.ModEq.add_right_cancel ha.2
    calc
      z + a ≡ b + c [MOD q - p] := by rw [hrel]
      _ ≡ p + p [MOD q - p] := hb.2.add hc.2
  have hall := hgen.2.2 C (fun _ h ↦ h.1) hpC hqC hclosed
  intro a ha
  exact (hall ha).2

/-- Normalization by gcd turns the generating step into one. -/
lemma adjacent_of_progressionTernaryGenerates
    {A : Finset ℕ} (hzero : 0 ∈ A)
    (hgcd : A.gcd (fun n : ℕ ↦ n) = 1)
    (hstruct : ProgressionTernaryGenerates A) :
    ∃ p : ℕ, TernaryGenerates A p (p + 1) := by
  obtain ⟨p, q, hpq, hgen⟩ := hstruct
  have hmod := modEq_of_ternaryGenerates hpq hgen
  have hdiv : q - p ∣ A.gcd (fun n : ℕ ↦ n) := by
    apply Finset.dvd_gcd
    intro a ha
    apply Nat.modEq_zero_iff_dvd.mp
    exact (hmod 0 hzero).trans (hmod a ha).symm |>.symm
  have hstep : q - p = 1 := by
    rw [hgcd] at hdiv
    exact Nat.eq_one_of_dvd_one hdiv
  refine ⟨p, ?_⟩
  convert hgen using 1 <;> omega

/-- The three-point base case of the structured-set induction. -/
lemma progressionTernaryGenerates_of_card_eq_three
    {A : Finset ℕ} (hcard : A.card = 3)
    (hsmall : (A + A).card ≤ 5) :
    ProgressionTernaryGenerates A := by
  classical
  have hAne : A.Nonempty := Finset.card_pos.mp (by omega)
  let m := A.max' hAne
  let B := A.erase m
  have hmA : m ∈ A := A.max'_mem hAne
  have hBcard : B.card = 2 := by
    dsimp [B]
    rw [Finset.card_erase_of_mem hmA, hcard]
  obtain ⟨u, v, huv, hBuv⟩ := Finset.card_eq_two.mp hBcard
  rcases lt_or_gt_of_ne huv with huvlt | hvult
  · let a := u
    let b := v
    have hab : a < b := huvlt
    have haB : a ∈ B := by simp [hBuv, a]
    have hbB : b ∈ B := by simp [hBuv, b]
    have hbm : b < m := by
      exact A.lt_max'_of_mem_erase_max' hAne hbB
    have hAeq : A = {a, b, m} := by
      calc
        A = insert m B := (Finset.insert_erase hmA).symm
        _ = {a, b, m} := by
          ext x
          simp only [hBuv, a, b, Finset.mem_insert, Finset.mem_singleton]
          aesop
    have haA : a ∈ A := Finset.mem_of_mem_erase haB
    have hbA : b ∈ A := Finset.mem_of_mem_erase hbB
    by_cases hrel : a + m = b + b
    · refine ⟨a, b, hab, ?_⟩
      refine ⟨by simp [hAeq], by simp [hAeq], ?_⟩
      intro C _ haC hbC hclosed z hz
      have hz' : z = a ∨ z = b ∨ z = m := by
        rw [hAeq] at hz
        simpa [eq_comm] using hz
      rcases hz' with hza | hzb | hzm
      · simpa [hza] using haC
      · simpa [hzb] using hbC
      · subst z
        apply hclosed a haC b hbC b hbC m
          (by simp [hAeq])
        omega
    · let g : Fin 6 → ℕ :=
        ![a + a, a + b, a + m, b + b, b + m, m + m]
      have hginj : Function.Injective g := by
        intro i j hij
        fin_cases i <;> fin_cases j <;> simp [g] at hij ⊢ <;> omega
      have hgsub : Finset.univ.image g ⊆ A + A := by
        intro x hx
        obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp hx
        fin_cases i <;> simp only [g, Matrix.cons_val_zero,
          Matrix.cons_val_one, Matrix.head_cons, Matrix.tail_cons]
        · exact Finset.mem_add.mpr ⟨a, haA, a, haA, rfl⟩
        · exact Finset.mem_add.mpr ⟨a, haA, b, hbA, rfl⟩
        · exact Finset.mem_add.mpr ⟨a, haA, m, hmA, rfl⟩
        · exact Finset.mem_add.mpr ⟨b, hbA, b, hbA, rfl⟩
        · exact Finset.mem_add.mpr ⟨b, hbA, m, hmA, rfl⟩
        · exact Finset.mem_add.mpr ⟨m, hmA, m, hmA, rfl⟩
      have hsix : 6 ≤ (A + A).card := by
        calc
          6 = (Finset.univ : Finset (Fin 6)).card := by simp
          _ = (Finset.univ.image g).card := by
            rw [Finset.card_image_iff.mpr hginj.injOn]
          _ ≤ (A + A).card := Finset.card_le_card hgsub
      omega
  · let a := v
    let b := u
    have hab : a < b := hvult
    have haB : a ∈ B := by simp [hBuv, a]
    have hbB : b ∈ B := by simp [hBuv, b]
    have hbm : b < m := by
      exact A.lt_max'_of_mem_erase_max' hAne hbB
    have hAeq : A = {a, b, m} := by
      calc
        A = insert m B := (Finset.insert_erase hmA).symm
        _ = {a, b, m} := by
          ext x
          simp only [hBuv, a, b, Finset.mem_insert, Finset.mem_singleton]
          aesop
    have haA : a ∈ A := Finset.mem_of_mem_erase haB
    have hbA : b ∈ A := Finset.mem_of_mem_erase hbB
    by_cases hrel : a + m = b + b
    · refine ⟨a, b, hab, ?_⟩
      refine ⟨by simp [hAeq], by simp [hAeq], ?_⟩
      intro C _ haC hbC hclosed z hz
      have hz' : z = a ∨ z = b ∨ z = m := by
        rw [hAeq] at hz
        simpa [eq_comm] using hz
      rcases hz' with hza | hzb | hzm
      · simpa [hza] using haC
      · simpa [hzb] using hbC
      · subst z
        apply hclosed a haC b hbC b hbC m
          (by simp [hAeq])
        omega
    · let g : Fin 6 → ℕ :=
        ![a + a, a + b, a + m, b + b, b + m, m + m]
      have hginj : Function.Injective g := by
        intro i j hij
        fin_cases i <;> fin_cases j <;> simp [g] at hij ⊢ <;> omega
      have hgsub : Finset.univ.image g ⊆ A + A := by
        intro x hx
        obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp hx
        fin_cases i <;> simp only [g, Matrix.cons_val_zero,
          Matrix.cons_val_one, Matrix.head_cons, Matrix.tail_cons]
        · exact Finset.mem_add.mpr ⟨a, haA, a, haA, rfl⟩
        · exact Finset.mem_add.mpr ⟨a, haA, b, hbA, rfl⟩
        · exact Finset.mem_add.mpr ⟨a, haA, m, hmA, rfl⟩
        · exact Finset.mem_add.mpr ⟨b, hbA, b, hbA, rfl⟩
        · exact Finset.mem_add.mpr ⟨b, hbA, m, hmA, rfl⟩
        · exact Finset.mem_add.mpr ⟨m, hmA, m, hmA, rfl⟩
      have hsix : 6 ≤ (A + A).card := by
        calc
          6 = (Finset.univ : Finset (Fin 6)).card := by simp
          _ = (Finset.univ.image g).card := by
            rw [Finset.card_image_iff.mpr hginj.injOn]
          _ ≤ (A + A).card := Finset.card_le_card hgsub
      omega

/-- A single additive collision attaches a new point to a ternary-generating
set.  This is the elementary extension step in the `3k - 4` induction. -/
lemma ternaryGenerates_insert_of_relation
    {B : Finset ℕ} {m p q a u v : ℕ}
    (hgen : TernaryGenerates B p q)
    (ha : a ∈ B) (hu : u ∈ B) (hv : v ∈ B)
    (hrel : m + a = u + v) :
    TernaryGenerates (insert m B) p q := by
  refine ⟨Finset.mem_insert_of_mem hgen.1,
    Finset.mem_insert_of_mem hgen.2.1, ?_⟩
  intro C hC hpC hqC hclosed
  let D : Set ℕ := {x | x ∈ B ∧ x ∈ C}
  have hpD : p ∈ D := ⟨hgen.1, hpC⟩
  have hqD : q ∈ D := ⟨hgen.2.1, hqC⟩
  have hDclosed : ∀ x ∈ D, ∀ y ∈ D, ∀ z ∈ D, ∀ w ∈ B,
      w + x = y + z → w ∈ D := by
    intro x hx y hy z hz w hw hsum
    exact ⟨hw, hclosed x hx.2 y hy.2 z hz.2 w
      (Finset.mem_insert_of_mem hw) hsum⟩
  have hBC : (B : Set ℕ) ⊆ C := by
    intro x hx
    exact (hgen.2.2 D (fun _ h ↦ h.1) hpD hqD hDclosed hx).2
  have hmC : m ∈ C := hclosed a (hBC ha) u (hBC hu) v (hBC hv) m
    (Finset.mem_insert_self _ _) hrel
  intro x hx
  rw [Finset.mem_coe, Finset.mem_insert] at hx
  rcases hx with rfl | hx
  · exact hmC
  · exact hBC hx

private lemma add_subset_add_of_subset {A B : Finset ℕ} (hBA : B ⊆ A) :
    B + B ⊆ A + A := by
  intro z hz
  obtain ⟨x, hx, y, hy, rfl⟩ := Finset.mem_add.mp hz
  exact Finset.mem_add.mpr ⟨x, hBA hx, y, hBA hy, rfl⟩

private lemma translate_card (m : ℕ) (B : Finset ℕ) :
    (B.image fun x ↦ m + x).card = B.card := by
  exact Finset.card_image_of_injective B (fun _ _ h ↦ Nat.add_left_cancel h)

/-- The integer `3k - 4` structure theorem in the exact closure form needed
below.  Its proof is the maximal-element induction of
Balasubramanian--Pandey. -/
theorem progressionTernaryGenerates_of_three_card_sub_four
    {A : Finset ℕ} (hcard : 3 ≤ A.card)
    (hsmall : (A + A).card ≤ 3 * A.card - 4) :
    ProgressionTernaryGenerates A := by
  classical
  generalize hk : A.card = k at hcard hsmall ⊢
  induction k using Nat.strong_induction_on generalizing A with
  | h k ih =>
      by_cases hk3 : k = 3
      · subst k
        apply progressionTernaryGenerates_of_card_eq_three (by omega)
        omega
      have hk4 : 4 ≤ k := by omega
      have hAne : A.Nonempty := Finset.card_pos.mp (by omega)
      let m := A.max' hAne
      let B := A.erase m
      have hmA : m ∈ A := A.max'_mem hAne
      have hBA : B ⊆ A := Finset.erase_subset _ _
      have hBcard : B.card = k - 1 := by
        dsimp [B]
        rw [Finset.card_erase_of_mem hmA, hk]
      have hBcard3 : 3 ≤ B.card := by omega
      have hBlt : B.card < k := by omega
      have hBne : B.Nonempty := Finset.card_pos.mp (by omega)
      have hBmem_lt : ∀ {x}, x ∈ B → x < m := by
        intro x hx
        exact A.lt_max'_of_mem_erase_max' hAne hx
      by_cases hBstruct : ProgressionTernaryGenerates B
      · obtain ⟨p, q, hpq, hgen⟩ := hBstruct
        by_cases hcollision : ∃ a ∈ B, m + a ∈ B + B
        · obtain ⟨a, ha, hma⟩ := hcollision
          obtain ⟨u, hu, v, hv, huv⟩ := Finset.mem_add.mp hma
          refine ⟨p, q, hpq, ?_⟩
          rw [show A = insert m B by exact (Finset.insert_erase hmA).symm]
          exact ternaryGenerates_insert_of_relation hgen ha hu hv huv.symm
        · push_neg at hcollision
          let T := B.image fun x ↦ m + x
          have hdis : Disjoint (B + B) T := by
            rw [Finset.disjoint_left]
            intro z hzBB hzT
            obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hzT
            exact hcollision x hx hzBB
          have htwo_not_BB : m + m ∉ B + B := by
            intro hz
            obtain ⟨x, hx, y, hy, hxy⟩ := Finset.mem_add.mp hz
            have hxm := hBmem_lt hx
            have hym := hBmem_lt hy
            omega
          have htwo_not_T : m + m ∉ T := by
            intro hz
            obtain ⟨x, hx, hmx⟩ := Finset.mem_image.mp hz
            have hxm := hBmem_lt hx
            omega
          let U := insert (m + m) ((B + B) ∪ T)
          have hUsub : U ⊆ A + A := by
            intro z hz
            rw [show U = insert (m + m) ((B + B) ∪ T) by rfl,
              Finset.mem_insert, Finset.mem_union] at hz
            rcases hz with rfl | hzBB | hzT
            · exact Finset.mem_add.mpr ⟨m, hmA, m, hmA, rfl⟩
            · exact add_subset_add_of_subset hBA hzBB
            · obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hzT
              exact Finset.mem_add.mpr ⟨m, hmA, x, hBA hx, rfl⟩
          have hUcard : U.card = (B + B).card + B.card + 1 := by
            dsimp [U]
            rw [Finset.card_insert_of_notMem, Finset.card_union_of_disjoint hdis,
              translate_card]
            simp only [Finset.mem_union, not_or]
            exact ⟨htwo_not_BB, htwo_not_T⟩
          have hBB : B.card + B.card - 1 ≤ (B + B).card :=
            cauchy_davenport_add_of_linearOrder_isCancelAdd hBne hBne
          have hUle : U.card ≤ (A + A).card := Finset.card_le_card hUsub
          omega
      · have hBBlarge : 3 * B.card - 3 ≤ (B + B).card := by
          by_contra hnot
          have hBBsmall : (B + B).card ≤ 3 * B.card - 4 := by omega
          exact hBstruct (ih B.card hBlt rfl hBcard3 hBBsmall)
        let b := B.max' hBne
        let C := B.erase b
        have hbB : b ∈ B := B.max'_mem hBne
        have hb_lt_m : b < m := hBmem_lt hbB
        have hCB : C ⊆ B := Finset.erase_subset _ _
        have hCcard : C.card = B.card - 1 := by
          dsimp [C]
          rw [Finset.card_erase_of_mem hbB]
        have hCmem_lt : ∀ {x}, x ∈ C → x < b := by
          intro x hx
          exact B.lt_max'_of_mem_erase_max' hBne hx
        have hmC_in : ∀ a ∈ C, m + a ∈ B + B := by
          intro a ha
          by_contra hma
          have haB : a ∈ B := hCB ha
          have ha_lt_b : a < b := hCmem_lt ha
          have hmb_not : m + b ∉ B + B := by
            intro hmb
            obtain ⟨x, hx, y, hy, hxy⟩ := Finset.mem_add.mp hmb
            have hxb : x ≤ b := Finset.le_max' B x hx
            have hyb : y ≤ b := Finset.le_max' B y hy
            omega
          have htwo_not : m + m ∉ B + B := by
            intro hmm
            obtain ⟨x, hx, y, hy, hxy⟩ := Finset.mem_add.mp hmm
            have hxb : x ≤ b := Finset.le_max' B x hx
            have hyb : y ≤ b := Finset.le_max' B y hy
            omega
          let U := insert (m + m) (insert (m + b) (insert (m + a) (B + B)))
          have hUsub : U ⊆ A + A := by
            intro z hz
            simp only [U, Finset.mem_insert] at hz
            rcases hz with rfl | rfl | rfl | hzBB
            · exact Finset.mem_add.mpr ⟨m, hmA, m, hmA, rfl⟩
            · exact Finset.mem_add.mpr ⟨m, hmA, b, hBA hbB, rfl⟩
            · exact Finset.mem_add.mpr ⟨m, hmA, a, hBA haB, rfl⟩
            · exact add_subset_add_of_subset hBA hzBB
          have hUcard : U.card = (B + B).card + 3 := by
            dsimp [U]
            rw [Finset.card_insert_of_notMem, Finset.card_insert_of_notMem,
              Finset.card_insert_of_notMem]
            · omega
            · simpa only [Finset.mem_insert, not_or] using
                (show m + b ≠ m + a ∧ m + b ∉ B + B by
                  exact ⟨by omega, hmb_not⟩)
            · simpa only [Finset.mem_insert, not_or] using
                (show m + m ≠ m + b ∧ m + m ≠ m + a ∧ m + m ∉ B + B by
                  exact ⟨by omega, by omega, htwo_not⟩)
          have hUle : U.card ≤ (A + A).card := Finset.card_le_card hUsub
          omega
        refine ⟨b, m, hb_lt_m, ?_⟩
        rw [show A = insert m B by exact (Finset.insert_erase hmA).symm]
        refine ⟨Finset.mem_insert_of_mem hbB, Finset.mem_insert_self _ _, ?_⟩
        intro D hD hbD hmD hclosed
        have hBDaux : ∀ d : ℕ, ∀ z ∈ B, b - z = d → z ∈ D := by
          intro d
          induction d using Nat.strong_induction_on with
          | h d ihd =>
              intro z hz hdist
              have hzb : z ≤ b := Finset.le_max' B z hz
              by_cases hzb_eq : z = b
              · simpa [hzb_eq] using hbD
              have hz_lt_b : z < b := lt_of_le_of_ne hzb hzb_eq
              have hzC : z ∈ C := by
                exact Finset.mem_erase.mpr ⟨hzb_eq, hz⟩
              obtain ⟨u, hu, v, hv, huv⟩ := Finset.mem_add.mp (hmC_in z hzC)
              have hub : u ≤ b := Finset.le_max' B u hu
              have hvb : v ≤ b := Finset.le_max' B v hv
              have hzu : z < u := by omega
              have hzv : z < v := by omega
              have huD : u ∈ D := ihd (b - u) (by omega) u hu rfl
              have hvD : v ∈ D := ihd (b - v) (by omega) v hv rfl
              apply hclosed m hmD u huD v hvD z
                (Finset.mem_insert_of_mem hz)
              omega
        have hBD : (B : Set ℕ) ⊆ D := by
          intro z hz
          exact hBDaux (b - z) z hz rfl
        intro z hz
        rw [Finset.mem_coe, Finset.mem_insert] at hz
        rcases hz with rfl | hz
        · exact hmD
        · exact hBD hz

end Erdos360
