/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.RandomGreedyCorollary217Density
import ErdosProblems.Erdos186.CFP.Corollary217

/-!
# Transporting a common generated lattice into basis coordinates

Corollary 2.17 produces an integral basis of the lattice generated by a
dense coordinate set.  All completed random-greedy reserves generate that
same lattice.  This file records the exact finite transport into that basis:
cardinality is unchanged, generation becomes generation of the full
coordinate lattice, and hence the transported subset-sum sets are reduced.
-/

namespace Erdos186.CFP

open scoped BigOperators Pointwise
open Module LatticeBasis

noncomputable section

/-- Lift an ambient finite set known to lie in `Gamma` to the subtype
`Gamma`. -/
def liftToSublattice {d : ℕ} (Gamma : Sublattice d)
    (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma) : Finset Gamma :=
  S.attach.image fun x ↦ ⟨x.1, hS x.2⟩

@[simp]
theorem image_liftToSublattice_subtype {d : ℕ} (Gamma : Sublattice d)
    (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma) :
    (liftToSublattice Gamma S hS).image Gamma.subtype = S := by
  classical
  ext x
  constructor
  · intro hx
    obtain ⟨y, hy, rfl⟩ := Finset.mem_image.mp hx
    obtain ⟨z, _hz, rfl⟩ := Finset.mem_image.mp hy
    exact z.2
  · intro hx
    apply Finset.mem_image.mpr
    refine ⟨⟨x, hS hx⟩, ?_, rfl⟩
    apply Finset.mem_image.mpr
    exact ⟨⟨x, hx⟩, by simp, rfl⟩

/-- Lifting into a specified ambient lattice preserves cardinality. -/
@[simp]
theorem card_liftToSublattice {d : ℕ} (Gamma : Sublattice d)
    (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma) :
    (liftToSublattice Gamma S hS).card = S.card := by
  classical
  have hcard := congrArg Finset.card
    (image_liftToSublattice_subtype Gamma S hS)
  rw [Finset.card_image_of_injective _ Gamma.subtype_injective] at hcard
  exact hcard

/-- If the original set generates exactly `Gamma`, its subtype lift
generates all of the subtype group. -/
theorem closure_liftToSublattice_eq_top {d : ℕ} (Gamma : Sublattice d)
    (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma)
    (hgen : generatedSublattice S = Gamma) :
    AddSubgroup.closure (liftToSublattice Gamma S hS : Set Gamma) = ⊤ := by
  let K := AddSubgroup.closure
    (liftToSublattice Gamma S hS : Set Gamma)
  have hSm : (S : Set (LatticePoint d)) ⊆ K.map Gamma.subtype := by
    intro x hx
    refine ⟨⟨x, hS hx⟩, ?_, rfl⟩
    apply AddSubgroup.subset_closure
    apply Finset.mem_image.mpr
    exact ⟨⟨x, hx⟩, by simp, rfl⟩
  have hclosure : generatedSublattice S ≤ K.map Gamma.subtype := by
    rw [generatedSublattice, AddSubgroup.closure_le]
    exact hSm
  have hGamma : Gamma ≤ K.map Gamma.subtype := by
    simpa only [hgen] using hclosure
  apply top_unique
  intro y _hy
  obtain ⟨z, hz, hzy⟩ := hGamma y.property
  have : z = y := Subtype.ext hzy
  simpa [this] using hz

/-- Integral coordinates in a chosen basis of `Gamma`. -/
def sublatticeBasisEquiv {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) : Gamma ≃+ LatticePoint d :=
  b.equivFun.toAddEquiv

/-- Evaluate basis coordinates back into the ambient lattice. -/
def sublatticeBasisEvaluation {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) : LatticePoint d →+ LatticePoint d :=
  Gamma.subtype.comp (sublatticeBasisEquiv b).symm.toAddMonoidHom

/-- The image of an ambient set in the coordinates of a basis of its
specified containing lattice. -/
def sublatticeBasisImage {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma) :
    Finset (LatticePoint d) :=
  (liftToSublattice Gamma S hS).image (sublatticeBasisEquiv b)

/-- Basis-coordinate transport preserves cardinality exactly. -/
@[simp]
theorem card_sublatticeBasisImage {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma) :
    (sublatticeBasisImage b S hS).card = S.card := by
  classical
  rw [sublatticeBasisImage,
    Finset.card_image_of_injective _ (sublatticeBasisEquiv b).injective,
    card_liftToSublattice Gamma S hS]

/-- Evaluating a basis-coordinate image recovers the original ambient
finite set exactly. -/
@[simp]
theorem image_sublatticeBasisImage_evaluation
    {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma) :
    (sublatticeBasisImage b S hS).image
        (sublatticeBasisEvaluation b) = S := by
  classical
  rw [sublatticeBasisImage, Finset.image_image]
  have hfun :
      (sublatticeBasisEvaluation b ∘ sublatticeBasisEquiv b) =
        Gamma.subtype := by
    funext x
    change Gamma.subtype
        ((sublatticeBasisEquiv b).symm (sublatticeBasisEquiv b x)) =
      Gamma.subtype x
    rw [AddEquiv.symm_apply_apply]
  rw [hfun, image_liftToSublattice_subtype Gamma S hS]

/-- Additive maps commute with finite heterogeneous sumsets. -/
theorem image_heterogeneousSumset_addMonoidHom
    {d e ell : ℕ} (f : LatticePoint d →+ LatticePoint e)
    (A : Fin ell → Finset (LatticePoint d)) :
    (heterogeneousSumset A).image f =
      heterogeneousSumset (fun i ↦ (A i).image f) := by
  classical
  ext y
  constructor
  · intro hy
    obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hy
    obtain ⟨a, ha, rfl⟩ := mem_heterogeneousSumset.mp hx
    apply mem_heterogeneousSumset.mpr
    refine ⟨fun i ↦ f (a i), fun i ↦ ?_, ?_⟩
    · exact Finset.mem_image.mpr ⟨a i, ha i, rfl⟩
    · simp
  · intro hy
    obtain ⟨a, ha, rfl⟩ := mem_heterogeneousSumset.mp hy
    choose x hx hfx using fun i ↦ Finset.mem_image.mp (ha i)
    apply Finset.mem_image.mpr
    refine ⟨∑ i, x i, mem_heterogeneousSumset.mpr ⟨x, hx, rfl⟩, ?_⟩
    simp_rw [map_sum, hfx]

/-- A generating family becomes a full-lattice generating family after
passing to coordinates in a basis of its common generated lattice. -/
theorem generatedSublattice_sublatticeBasisImage_eq_top
    {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma)
    (hgen : generatedSublattice S = Gamma) :
    generatedSublattice (sublatticeBasisImage b S hS) = ⊤ := by
  let e := sublatticeBasisEquiv b
  rw [generatedSublattice, sublatticeBasisImage]
  have hset :
      ((liftToSublattice Gamma S hS).image e : Set (LatticePoint d)) =
        e '' (liftToSublattice Gamma S hS : Set Gamma) := by
    simp
  rw [hset]
  calc
    AddSubgroup.closure
        (e '' (liftToSublattice Gamma S hS : Set Gamma)) =
      AddSubgroup.map e.toAddMonoidHom
        (AddSubgroup.closure
          (liftToSublattice Gamma S hS : Set Gamma)) := by
      symm
      change AddSubgroup.map e.toAddMonoidHom
          (AddSubgroup.closure
            (liftToSublattice Gamma S hS : Set Gamma)) =
        AddSubgroup.closure
          (e.toAddMonoidHom ''
            (liftToSublattice Gamma S hS : Set Gamma))
      exact AddMonoidHom.map_closure e.toAddMonoidHom
        (liftToSublattice Gamma S hS : Set Gamma)
    _ = AddSubgroup.map e.toAddMonoidHom ⊤ := by
      rw [closure_liftToSublattice_eq_top Gamma S hS hgen]
    _ = ⊤ :=
      AddSubgroup.map_top_of_surjective e.toAddMonoidHom e.surjective

/-- Consequently, subset sums of every common-lattice generating reserve
are Reduced after basis-coordinate transport. -/
theorem reduced_subsetSums_sublatticeBasisImage
    {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma)
    (hgen : generatedSublattice S = Gamma) :
    Reduced (GAP.subsetSums (sublatticeBasisImage b S hS)) := by
  apply reduced_subsetSums_of_generatedSublattice_eq_top
  exact generatedSublattice_sublatticeBasisImage_eq_top b S hS hgen

/-- The stronger form used for the DenseBox family: the transported set
itself is Reduced as soon as the original set contains zero and generates
the common lattice. -/
theorem reduced_sublatticeBasisImage
    {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma)
    (hzero : (0 : LatticePoint d) ∈ S)
    (hgen : generatedSublattice S = Gamma) :
    Reduced (sublatticeBasisImage b S hS) := by
  apply reduced_of_zero_mem_generatedSublattice_eq_top
  · apply Finset.mem_image.mpr
    refine ⟨0, ?_, (sublatticeBasisEquiv b).map_zero⟩
    apply Finset.mem_image.mpr
    exact ⟨⟨0, hzero⟩, by simp, rfl⟩
  · exact generatedSublattice_sublatticeBasisImage_eq_top b S hS hgen

/-- Every set is contained in the lattice it generates, with a displayed
common-lattice equality used to retarget the codomain. -/
theorem subset_sublattice_of_generatedSublattice_eq
    {d : ℕ} {Gamma : Sublattice d} {S : Finset (LatticePoint d)}
    (hgen : generatedSublattice S = Gamma) :
    (S : Set (LatticePoint d)) ⊆ Gamma := by
  intro x hx
  rw [← hgen]
  exact subset_generatedSublattice S hx

/-- If an ambient set lies in a centered basis progression, its basis
coordinates lie in the corresponding symmetric axis box. -/
theorem sublatticeBasisImage_subset_symmetricAxisBox
    {d : ℕ} {Gamma : Sublattice d}
    (b : Basis (Fin d) ℤ Gamma) (radius : Fin d → ℕ)
    (S : Finset (LatticePoint d))
    (hS : (S : Set (LatticePoint d)) ⊆ Gamma)
    (hprogression : S ⊆ (AdaptedHNF.centeredBasisGAP b radius).carrier) :
    sublatticeBasisImage b S hS ⊆
      (symmetricAxisBox radius).carrier := by
  classical
  intro x hx
  obtain ⟨y, hy, rfl⟩ := Finset.mem_image.mp hx
  obtain ⟨z, _hz, rfl⟩ := Finset.mem_image.mp hy
  have hzP := hprogression z.2
  rw [centeredBasisGAP_carrier_eq_basisProgression] at hzP
  change ((⟨z.1, hS z.2⟩ : Gamma) : LatticePoint d) ∈
    basisProgression b radius at hzP
  rw [mem_basisProgression_iff] at hzP
  rw [mem_symmetricAxisBox_iff]
  intro i
  change |basisCoeff b ⟨z.1, hS z.2⟩ i| ≤ (radius i : ℤ)
  exact hzP i

/-- Inflate every basis radius by the same positive integer.  This forces
the eventual DenseBox width threshold while losing only a fixed
dimension-dependent volume factor. -/
def inflatedBasisRadius {d : ℕ} (width : ℕ)
    (radius : Fin d → ℕ) : Fin d → ℕ :=
  fun i ↦ width * (radius i + 1)

theorem symmetricAxisBox_subset_inflatedBasisRadius
    {d width : ℕ} {radius : Fin d → ℕ} (hwidth : 0 < width) :
    (symmetricAxisBox radius).carrier ⊆
      (symmetricAxisBox (inflatedBasisRadius width radius)).carrier := by
  intro x hx
  rw [mem_symmetricAxisBox_iff] at hx ⊢
  intro i
  exact (hx i).trans (by
    exact_mod_cast (show radius i ≤ width * (radius i + 1) by
      nlinarith))

/-- The inflated symmetric box is uniformly wide. -/
theorem le_minWidth_symmetricAxisBox_inflatedBasisRadius
    {d width : ℕ} (hd : 0 < d) (radius : Fin d → ℕ) :
    width ≤
      (symmetricAxisBox (inflatedBasisRadius width radius)).minWidth := by
  rw [AxisBox.minWidth, dif_pos hd]
  apply Finset.le_inf'
  intro i _hi
  change width ≤ 2 * (width * (radius i + 1)) + 1
  nlinarith

/-- Exact volume of a symmetric radius box. -/
@[simp]
theorem symmetricAxisBox_volume {d : ℕ} (radius : Fin d → ℕ) :
    (symmetricAxisBox radius).volume = ∏ i, (2 * radius i + 1) := by
  rfl

/-- Uniform volume cost of forcing the width threshold. -/
theorem symmetricAxisBox_inflatedBasisRadius_volume_le
    {d width : ℕ} (radius : Fin d → ℕ) :
    (symmetricAxisBox (inflatedBasisRadius width radius)).volume ≤
      (2 * width + 1) ^ d * (symmetricAxisBox radius).volume := by
  simp only [symmetricAxisBox_volume]
  calc
    ∏ i, (2 * inflatedBasisRadius width radius i + 1) ≤
        ∏ i, ((2 * width + 1) * (2 * radius i + 1)) := by
      apply Finset.prod_le_prod (fun _ _ ↦ Nat.zero_le _)
      intro i _hi
      change 2 * (width * (radius i + 1)) + 1 ≤
        (2 * width + 1) * (2 * radius i + 1)
      nlinarith
    _ = (∏ _i : Fin d, (2 * width + 1)) *
        ∏ i, (2 * radius i + 1) := Finset.prod_mul_distrib
    _ = (2 * width + 1) ^ d * ∏ i, (2 * radius i + 1) := by
      simp

/-- A box dilation costs at most `(k+1)^d` in displayed volume. -/
theorem AxisBox.dilate_volume_le {d : ℕ} (Q : AxisBox d) (k : ℕ) :
    (Q.dilate k).volume ≤ (k + 1) ^ d * Q.volume := by
  rw [AxisBox.volume, AxisBox.volume]
  calc
    ∏ i, (Q.dilate k).widths i ≤
        ∏ i, ((k + 1) * Q.widths i) := by
      apply Finset.prod_le_prod (fun _ _ ↦ Nat.zero_le _)
      intro i _hi
      rw [AxisBox.dilate_width]
      have hi := Q.width_pos i
      calc
        k * (Q.widths i - 1) + 1 ≤ k * Q.widths i + 1 := by
          gcongr
          omega
        _ ≤ (k + 1) * Q.widths i := by nlinarith
    _ = (∏ _i : Fin d, (k + 1)) * ∏ i, Q.widths i :=
      Finset.prod_mul_distrib
    _ = (k + 1) ^ d * ∏ i, Q.widths i := by simp

/-- The symmetric coefficient box belonging to a Corollary 2.17
certificate has volume controlled by the original common box. -/
theorem Corollary217Certificate.symmetricBasisBox_volume_le
    {d : ℕ} {Q : AxisBox d} {S : Finset (LatticePoint d)}
    (cert : Corollary217Certificate Q S) :
    (symmetricAxisBox cert.radius).volume ≤
      (cert.constant + 1) ^ d * Q.volume := by
  have hcard := Finset.card_le_card cert.geometric_bound
  have hleft : cert.progression.carrier.card =
      (symmetricAxisBox cert.radius).volume := by
    rw [cert.progression_eq,
      centeredBasisGAP_carrier_eq_basisProgression,
      card_basisProgression, symmetricAxisBox_volume]
  have hright :
      (Elementary.translate cert.geometricTranslate
        (Q.dilate cert.constant).carrier).card =
          (Q.dilate cert.constant).volume := by
    rw [Elementary.card_translate, AxisBox.card_carrier]
  rw [hleft, hright] at hcard
  exact hcard.trans (Q.dilate_volume_le cert.constant)

/-- The source common-box width is inherited by the coefficient box in the
adapted basis selected by Corollary 2.17. -/
theorem Corollary217Certificate.minWidth_le_symmetricBasisBox
    {d : ℕ} {Q : AxisBox d} {S : Finset (LatticePoint d)}
    (cert : Corollary217Certificate Q S) :
    Q.minWidth ≤ (symmetricAxisBox cert.radius).minWidth := by
  by_cases hd : 0 < d
  · have hmin : (symmetricAxisBox cert.radius).minWidth =
        Finset.univ.inf'
          (show (Finset.univ : Finset (Fin d)).Nonempty from
            ⟨⟨0, hd⟩, Finset.mem_univ _⟩)
          (symmetricAxisBox cert.radius).widths := by
      simp only [AxisBox.minWidth, hd, dite_true]
    rw [hmin]
    apply Finset.le_inf'
    intro i _hi
    change Q.minWidth ≤ 2 * cert.radius i + 1
    have hi := cert.radius_lower i
    omega
  · have hd0 : d = 0 := Nat.eq_zero_of_not_pos hd
    subst d
    simp [AxisBox.minWidth]

/-- Uniform constants for the common-lattice family form of the dense-box
step.  Corollary 2.17 is applied to one reference member only to choose a
basis of the common generated lattice.  Every member is then transported
to that same basis, where generation is full and Reducedness follows
without an extra hypothesis. -/
theorem exists_commonBasis_denseBoxConstants
    (d : ℕ) (hd : 0 < d) (cNum cDen : ℕ)
    (hcNum : 0 < cNum) (hc : cNum ≤ cDen) :
    ∃ corConstant corWidth denseConstant denseEll denseWidth : ℕ,
      0 < corConstant ∧ 0 < denseConstant ∧
      ∀ {q : ℕ} (Q : AxisBox d)
        (A : Fin (q + 1) → Finset (LatticePoint d)),
        (hwidth : max corWidth denseWidth ≤ Q.minWidth) →
        (hzero : ∀ i, (0 : LatticePoint d) ∈ A i) →
        (hsubset : ∀ i, A i ⊆ Q.carrier) →
        (hdensity : ∀ i,
          cNum * Q.volume ≤ cDen * (A i).card) →
        (hgenerated : ∀ i, generatedSublattice (A i) =
          generatedSublattice (A 0)) →
        (hell : denseEll ≤ q + 1) →
        ∃ cert : Corollary217Certificate Q (A 0),
          cert.constant = corConstant ∧
          ContainsTranslate
            (heterogeneousSumset (fun i ↦
              sublatticeBasisImage cert.basis (A i)
                (subset_sublattice_of_generatedSublattice_eq
                  (show generatedSublattice (A i) =
                      generatedSublattice (A 0) by
                    exact hgenerated i))))
            ((symmetricAxisBox cert.radius).dilate
              ((q + 1) / denseConstant)) := by
  obtain ⟨corConstant, corWidth, hcorPos, hcor⟩ :=
    exists_corollary217Certificate d hd cNum cDen hcNum hc
  let denseDen := cDen * (corConstant + 1) ^ d
  have hdenseDen : 0 < denseDen := by
    dsimp only [denseDen]
    exact Nat.mul_pos (lt_of_lt_of_le hcNum hc) (pow_pos (by omega) d)
  have hcDense : cNum ≤ denseDen := by
    calc
      cNum ≤ cDen := hc
      _ ≤ cDen * (corConstant + 1) ^ d :=
        Nat.le_mul_of_pos_right _ (pow_pos (by omega) d)
  obtain ⟨denseConstant, denseEll, denseWidth, hdensePos, hDense⟩ :=
    denseBoxLemma d hd cNum denseDen hcNum hcDense
  refine ⟨corConstant, corWidth, denseConstant, denseEll, denseWidth,
    hcorPos, hdensePos, ?_⟩
  intro q Q A hwidth hzero hsubset hdensity hgenerated hell
  have hcorWidth : corWidth ≤ Q.minWidth :=
    (Nat.le_max_left _ _).trans hwidth
  obtain ⟨cert, hcertConstant⟩ :=
    hcor Q (A 0) hcorWidth (hzero 0) (hsubset 0) (hdensity 0)
  let Gamma := generatedSublattice (A 0)
  let hAGamma : ∀ i, (A i : Set (LatticePoint d)) ⊆ Gamma :=
    fun i ↦ subset_sublattice_of_generatedSublattice_eq (hgenerated i)
  let family : Fin (q + 1) → Finset (LatticePoint d) := fun i ↦
    sublatticeBasisImage cert.basis (A i) (hAGamma i)
  have hfamilySubset : ∀ i, family i ⊆
      (symmetricAxisBox cert.radius).carrier := by
    intro i
    apply sublatticeBasisImage_subset_symmetricAxisBox
      cert.basis cert.radius (A i) (hAGamma i)
    intro x hx
    rw [← cert.progression_eq]
    exact cert.box_lattice_subset x (hsubset i hx) (hAGamma i hx)
  have hfamilyDensity : ∀ i,
      cNum * (symmetricAxisBox cert.radius).volume ≤
        denseDen * (family i).card := by
    intro i
    have hvol := cert.symmetricBasisBox_volume_le
    have hcard : (family i).card = (A i).card := by
      exact card_sublatticeBasisImage cert.basis (A i) (hAGamma i)
    rw [hcard]
    calc
      cNum * (symmetricAxisBox cert.radius).volume ≤
          cNum * ((cert.constant + 1) ^ d * Q.volume) := by gcongr
      _ = (cert.constant + 1) ^ d * (cNum * Q.volume) := by ring
      _ ≤ (cert.constant + 1) ^ d * (cDen * (A i).card) := by
        exact Nat.mul_le_mul_left ((cert.constant + 1) ^ d) (hdensity i)
      _ = denseDen * (A i).card := by
        simp only [denseDen, hcertConstant]
        ring
  have hfamilyReduced : ∀ i, Reduced (family i) := by
    intro i
    apply reduced_sublatticeBasisImage cert.basis (A i) (hAGamma i)
      (hzero i)
    exact hgenerated i
  have hdenseWidth : denseWidth ≤
      (symmetricAxisBox cert.radius).minWidth := by
    calc
      denseWidth ≤ Q.minWidth :=
        (Nat.le_max_right _ _).trans hwidth
      _ ≤ (symmetricAxisBox cert.radius).minWidth :=
        cert.minWidth_le_symmetricBasisBox
  refine ⟨cert, hcertConstant, ?_⟩
  simpa only [family, Gamma, hAGamma] using
    hDense (q + 1) (symmetricAxisBox cert.radius) family hell
      hdenseWidth hfamilySubset hfamilyDensity hfamilyReduced

end

end Erdos186.CFP

#print axioms Erdos186.CFP.generatedSublattice_sublatticeBasisImage_eq_top
#print axioms Erdos186.CFP.reduced_subsetSums_sublatticeBasisImage
