/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.BoundingBox

/-!
# Finite stability predicates for the Conlon--Fox--Pham argument

This file gives exact, finite versions of the stability notions in
Conlon--Fox--Pham, Definitions 2.28 and 2.33.  The paper works with a real
deletion parameter `x`, the rank cutoff `1 + beta`, and the volume comparison
`Vol(Q) <= 3/4 * Vol(P_d(A))`.  In the applications all deletion counts are
integral.  We consequently use a natural deletion budget and write the volume
comparison without division as

`4 * Q.volume <= 3 * (box d).volume`.

The family `box` is deliberately an input to the predicates.  A subsequent
specialization supplies the minimal bounding GAPs.  Keeping the definitions
parametric is useful because all monotonicity and deletion bookkeeping is
independent of the existence and minimality proof for those GAPs.

The subgroup generated by a finite coordinate image is represented by
`AddSubgroup.closure`.  `SpanRobust` is the extra clause in strong stability:
deleting the allowed number of elements does not change this subgroup in any
relevant dimension.
-/

namespace Erdos186.CFP.Stability

open scoped BigOperators

/-! ## Integer points and bounded differences -/

/-- The standard embedding of an integer in the one-dimensional lattice. -/
def integerPoint (a : ℤ) : LatticePoint 1 :=
  BoundingBox.intPoint a

@[simp]
theorem integerPoint_apply (a : ℤ) (i : Fin 1) : integerPoint a i = a :=
  rfl

/-- The finite set of one-dimensional lattice points represented by a finite
set of integers. -/
def integerPoints (A : Finset ℤ) : Finset (LatticePoint 1) :=
  A.image integerPoint

@[simp]
theorem mem_integerPoints_iff {A : Finset ℤ} {x : LatticePoint 1} :
    x ∈ integerPoints A ↔ ∃ a ∈ A, integerPoint a = x := by
  classical
  simp [integerPoints]

@[simp]
theorem integerPoint_mem_integerPoints_iff {A : Finset ℤ} {a : ℤ} :
    integerPoint a ∈ integerPoints A ↔ a ∈ A := by
  classical
  constructor
  · intro h
    obtain ⟨b, hb, hba⟩ := mem_integerPoints_iff.mp h
    have : b = a := by
      have hcomponent := congrFun hba (0 : Fin 1)
      simpa using hcomponent
    simpa [this] using hb
  · intro ha
    exact mem_integerPoints_iff.mpr ⟨a, ha, rfl⟩

/-- All displayed GAP differences are bounded coordinatewise in absolute
value.  For a rank-`d` GAP in `ℤ`, this is exactly the paper's condition that
its `d` differences are at most the supplied bound. -/
def HasDifferencesAtMost {d : ℕ} (P : GAP 1 d) (bound : ℕ) : Prop :=
  ∀ i, |P.steps i 0| ≤ (bound : ℤ)

theorem HasDifferencesAtMost.mono {d bound bound' : ℕ} {P : GAP 1 d}
    (hP : HasDifferencesAtMost P bound) (hbound : bound ≤ bound') :
    HasDifferencesAtMost P bound' := by
  intro i
  exact (hP i).trans (by exact_mod_cast hbound)

/-! ## Relevant dimensions -/

/-- The finite set of dimensions attained by a natural-valued dimension
function on the integer interval `[hLower, hUpper]`.

With `hDimension h` instantiated as the CFP `h`-dimension of `A ∪ {0}` and
`hLower = ceil (n^(1/beta))`, this is the natural-parameter version of the set
`D_A` immediately preceding CFP Lemma 2.32. -/
def relevantDimensions (hDimension : ℕ → ℕ) (hLower hUpper : ℕ) :
    Finset ℕ :=
  (Finset.Icc hLower hUpper).image hDimension

@[simp]
theorem mem_relevantDimensions_iff {hDimension : ℕ → ℕ}
    {hLower hUpper d : ℕ} :
    d ∈ relevantDimensions hDimension hLower hUpper ↔
      ∃ h, hLower ≤ h ∧ h ≤ hUpper ∧ hDimension h = d := by
  classical
  simp [relevantDimensions, and_assoc]

theorem relevantDimensions_mono_interval {hDimension : ℕ → ℕ}
    {a b a' b' : ℕ} (ha : a' ≤ a) (hb : b ≤ b') :
    relevantDimensions hDimension a b ⊆
      relevantDimensions hDimension a' b' := by
  intro d hd
  rw [mem_relevantDimensions_iff] at hd ⊢
  obtain ⟨h, hah, hhb, rfl⟩ := hd
  exact ⟨h, ha.trans hah, hhb.trans hb, rfl⟩

/-! ## Generated coordinate subgroups -/

/-- The additive subgroup generated by the coordinate images of a finite set. -/
def generatedSubgroup {α : Type*} {d : ℕ} [DecidableEq α]
    (φ : α → LatticePoint d) (A : Finset α) :
    AddSubgroup (LatticePoint d) :=
  AddSubgroup.closure (φ '' (A : Set α))

theorem generatedSubgroup_mono {α : Type*} {d : ℕ} [DecidableEq α]
    {φ : α → LatticePoint d} {A B : Finset α} (hAB : A ⊆ B) :
    generatedSubgroup φ A ≤ generatedSubgroup φ B := by
  apply AddSubgroup.closure_mono
  exact Set.image_mono (by exact_mod_cast hAB)

@[simp]
theorem generatedSubgroup_empty {α : Type*} {d : ℕ} [DecidableEq α]
    (φ : α → LatticePoint d) :
    generatedSubgroup φ ∅ = ⊥ := by
  simp [generatedSubgroup]

theorem image_mem_generatedSubgroup {α : Type*} {d : ℕ} [DecidableEq α]
    {φ : α → LatticePoint d} {A : Finset α} {a : α} (ha : a ∈ A) :
    φ a ∈ generatedSubgroup φ A := by
  exact AddSubgroup.subset_closure ⟨a, by exact_mod_cast ha, rfl⟩

/-! ## Weak stability (CFP Definition 2.28) -/

/-- Weak stability for a set already containing zero, relative to a supplied
family of reference boxes.

`deletionBudget` is the integral version of `x`, `maxRank` is the integral
rank cutoff corresponding to `1 + beta`, and `differenceBound` is `n^2` in
the paper.  The inequality `A.card ≤ B.card + deletionBudget` is equivalent
to `B.card ≥ A.card - deletionBudget`, without truncated-subtraction
bookkeeping. -/
def WeaklyStableFor (A : Finset ℤ) (box : (d : ℕ) → GAP 1 d)
    (deletionBudget maxRank differenceBound : ℕ) : Prop :=
  0 ∈ A ∧
    ∀ {B : Finset ℤ}, B ⊆ A →
      A.card ≤ B.card + deletionBudget → 0 ∈ B →
      ∀ {d : ℕ}, 0 < d → d ≤ maxRank →
        ∀ P : GAP 1 d, HasDifferencesAtMost P differenceBound →
          4 * P.volume ≤ 3 * (box d).volume →
            ¬ integerPoints B ⊆ P.carrier

/-- The paper's convention for a set not known to contain zero: adjoin zero
before testing weak stability. -/
def WeaklyStable (A : Finset ℤ) (box : (d : ℕ) → GAP 1 d)
    (deletionBudget maxRank differenceBound : ℕ) : Prop :=
  WeaklyStableFor (insert 0 A) box deletionBudget maxRank differenceBound

namespace WeaklyStableFor

theorem zero_mem {A : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D q : ℕ} (h : WeaklyStableFor A box x D q) : 0 ∈ A :=
  h.1

theorem avoids {A : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D q : ℕ} (h : WeaklyStableFor A box x D q)
    {B : Finset ℤ} (hBA : B ⊆ A) (hcard : A.card ≤ B.card + x)
    (hzero : 0 ∈ B) {d : ℕ} (hd : 0 < d) (hdD : d ≤ D)
    (P : GAP 1 d) (hsteps : HasDifferencesAtMost P q)
    (hvolume : 4 * P.volume ≤ 3 * (box d).volume) :
    ¬ integerPoints B ⊆ P.carrier :=
  h.2 hBA hcard hzero hd hdD P hsteps hvolume

/-- Reducing the allowed number of deletions weakens the assertion. -/
theorem mono_deletionBudget {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x x' D q : ℕ}
    (h : WeaklyStableFor A box x D q) (hxx : x' ≤ x) :
    WeaklyStableFor A box x' D q := by
  refine ⟨h.zero_mem, ?_⟩
  intro B hBA hcard hzero d hd hdD P hsteps hvolume
  exact h.avoids hBA (hcard.trans (by omega)) hzero hd hdD P hsteps hvolume

/-- Reducing the range of tested dimensions weakens the assertion. -/
theorem mono_maxRank {A : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D D' q : ℕ} (h : WeaklyStableFor A box x D q) (hDD : D' ≤ D) :
    WeaklyStableFor A box x D' q := by
  refine ⟨h.zero_mem, ?_⟩
  intro B hBA hcard hzero d hd hdD P hsteps hvolume
  exact h.avoids hBA hcard hzero hd (hdD.trans hDD) P hsteps hvolume

/-- Reducing the allowed difference bound weakens the assertion. -/
theorem mono_differenceBound {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x D q q' : ℕ}
    (h : WeaklyStableFor A box x D q) (hqq : q' ≤ q) :
    WeaklyStableFor A box x D q' := by
  refine ⟨h.zero_mem, ?_⟩
  intro B hBA hcard hzero d hd hdD P hsteps hvolume
  exact h.avoids hBA hcard hzero hd hdD P (hsteps.mono hqq) hvolume

/-- If the comparison boxes are replaced by no-larger boxes, weak stability
remains true. -/
theorem mono_boxVolume {A : Finset ℤ}
    {box box' : (d : ℕ) → GAP 1 d} {x D q : ℕ}
    (h : WeaklyStableFor A box x D q)
    (hbox : ∀ d, (box' d).volume ≤ (box d).volume) :
    WeaklyStableFor A box' x D q := by
  refine ⟨h.zero_mem, ?_⟩
  intro B hBA hcard hzero d hd hdD P hsteps hvolume
  apply h.avoids hBA hcard hzero hd hdD P hsteps
  exact hvolume.trans (Nat.mul_le_mul_left 3 (hbox d))

/-- Deletions can be split into an initial deletion and a subsequent one.
This is the cardinal bookkeeping used whenever weak stability is applied to
a large survivor set. -/
theorem avoids_after_deletions {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x D q removed extra : ℕ}
    (h : WeaklyStableFor A box x D q)
    {B C : Finset ℤ} (hBA : B ⊆ A) (hCB : C ⊆ B)
    (hfirst : A.card ≤ B.card + removed)
    (hsecond : B.card ≤ C.card + extra) (hbudget : removed + extra ≤ x)
    (hzero : 0 ∈ C) {d : ℕ} (hd : 0 < d) (hdD : d ≤ D)
    (P : GAP 1 d) (hsteps : HasDifferencesAtMost P q)
    (hvolume : 4 * P.volume ≤ 3 * (box d).volume) :
    ¬ integerPoints C ⊆ P.carrier := by
  exact h.avoids (hCB.trans hBA) (by omega) hzero hd hdD P hsteps hvolume

/-- Weak stability descends to an initial survivor set when the first loss
and its future deletion budget fit inside the original budget.  The reference
boxes remain fixed; later analytic arguments compare them with the survivor's
own minimal bounding boxes. -/
theorem delete {A B : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D q removed extra : ℕ} (h : WeaklyStableFor A box x D q)
    (hBA : B ⊆ A) (hzero : 0 ∈ B)
    (hloss : A.card ≤ B.card + removed) (hbudget : removed + extra ≤ x) :
    WeaklyStableFor B box extra D q := by
  refine ⟨hzero, ?_⟩
  intro C hCB hcard hzeroC d hd hdD P hsteps hvolume
  exact h.avoids_after_deletions hBA hCB hloss hcard hbudget hzeroC
    hd hdD P hsteps hvolume

end WeaklyStableFor

/-! ## Span robustness and strong stability (CFP Definition 2.33) -/

/-- Robustness of generated coordinate subgroups under bounded deletion.
The distinguished point is zero in the CFP application, but the generic
form is useful for the elementary pruning bookkeeping. -/
def SpanRobust {α : Type*} [DecidableEq α] (anchor : α)
    (A : Finset α) (deletionBudget : ℕ) (relevant : Finset ℕ)
    (φ : (d : ℕ) → α → LatticePoint d) : Prop :=
  ∀ {d : ℕ}, d ∈ relevant → ∀ {B : Finset α}, B ⊆ A →
    A.card ≤ B.card + deletionBudget → anchor ∈ B →
      generatedSubgroup (φ d) B = generatedSubgroup (φ d) A

namespace SpanRobust

/-- Reducing the deletion budget weakens span robustness. -/
theorem mono_deletionBudget {α : Type*} [DecidableEq α]
    {anchor : α} {A : Finset α} {x x' : ℕ} {relevant : Finset ℕ}
    {φ : (d : ℕ) → α → LatticePoint d}
    (h : SpanRobust anchor A x relevant φ) (hxx : x' ≤ x) :
    SpanRobust anchor A x' relevant φ := by
  intro d hd B hBA hcard hanchor
  exact h hd hBA (hcard.trans (by omega)) hanchor

/-- Testing fewer relevant dimensions weakens span robustness. -/
theorem mono_relevant {α : Type*} [DecidableEq α]
    {anchor : α} {A : Finset α} {x : ℕ} {relevant relevant' : Finset ℕ}
    {φ : (d : ℕ) → α → LatticePoint d}
    (h : SpanRobust anchor A x relevant φ) (hsub : relevant' ⊆ relevant) :
    SpanRobust anchor A x relevant' φ := by
  intro d hd
  exact h (hsub hd)

/-- Span robustness descends to a large subset whose coordinate span is
already the full old span.  The two cardinal hypotheses exactly add the
first deletion loss to the permitted future loss. -/
theorem delete {α : Type*} [DecidableEq α]
    {anchor : α} {A B : Finset α} {x removed extra : ℕ}
    {relevant : Finset ℕ} {φ : (d : ℕ) → α → LatticePoint d}
    (h : SpanRobust anchor A x relevant φ) (hBA : B ⊆ A)
    (hloss : A.card ≤ B.card + removed)
    (hbudget : removed + extra ≤ x)
    (hspan : ∀ {d}, d ∈ relevant →
      generatedSubgroup (φ d) B = generatedSubgroup (φ d) A) :
    SpanRobust anchor B extra relevant φ := by
  intro d hd C hCB hcard hanchorC
  have hCA : C ⊆ A := hCB.trans hBA
  have hlarge : A.card ≤ C.card + x := by omega
  exact (h hd hCA hlarge hanchorC).trans (hspan hd).symm

end SpanRobust

/-- Strong stability relative to fixed reference boxes and coordinate maps.
The condition `0 < C0` records the source's `C0 ≥ 1`; the robust deletion
budget is the exact natural quotient `deletionBudget / C0`. -/
def StronglyStableFor (A : Finset ℤ) (box : (d : ℕ) → GAP 1 d)
    (deletionBudget maxRank differenceBound : ℕ)
    (relevant : Finset ℕ) (φ : (d : ℕ) → ℤ → LatticePoint d)
    (C0 : ℕ) : Prop :=
  WeaklyStableFor A box deletionBudget maxRank differenceBound ∧
    0 < C0 ∧ SpanRobust 0 A (deletionBudget / C0) relevant φ

/-- The source convention for strong stability when zero is not known to be
in the original set. -/
def StronglyStable (A : Finset ℤ) (box : (d : ℕ) → GAP 1 d)
    (deletionBudget maxRank differenceBound : ℕ)
    (relevant : Finset ℕ) (φ : (d : ℕ) → ℤ → LatticePoint d)
    (C0 : ℕ) : Prop :=
  StronglyStableFor (insert 0 A) box deletionBudget maxRank differenceBound
    relevant φ C0

namespace StronglyStableFor

theorem weaklyStable {A : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D q C0 : ℕ} {relevant : Finset ℕ}
    {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0) :
    WeaklyStableFor A box x D q :=
  h.1

theorem C0_pos {A : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D q C0 : ℕ} {relevant : Finset ℕ}
    {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0) : 0 < C0 :=
  h.2.1

theorem spanRobust {A : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x D q C0 : ℕ} {relevant : Finset ℕ}
    {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0) :
    SpanRobust 0 A (x / C0) relevant φ :=
  h.2.2

theorem generatedSubgroup_eq {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x D q C0 : ℕ}
    {relevant : Finset ℕ} {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0)
    {d : ℕ} (hd : d ∈ relevant) {B : Finset ℤ} (hBA : B ⊆ A)
    (hcard : A.card ≤ B.card + x / C0) (hzero : 0 ∈ B) :
    generatedSubgroup (φ d) B = generatedSubgroup (φ d) A :=
  h.spanRobust hd hBA hcard hzero

/-- Strong stability is monotone in the deletion budget. -/
theorem mono_deletionBudget {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x x' D q C0 : ℕ}
    {relevant : Finset ℕ} {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0) (hxx : x' ≤ x) :
    StronglyStableFor A box x' D q relevant φ C0 := by
  refine ⟨h.weaklyStable.mono_deletionBudget hxx, h.C0_pos, ?_⟩
  exact SpanRobust.mono_deletionBudget h.spanRobust
    (Nat.div_le_div_right hxx)

/-- Strong stability remains true when fewer dimensions are tested in its
weak-stability clause. -/
theorem mono_maxRank {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x D D' q C0 : ℕ}
    {relevant : Finset ℕ} {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0) (hDD : D' ≤ D) :
    StronglyStableFor A box x D' q relevant φ C0 := by
  exact ⟨h.weaklyStable.mono_maxRank hDD, h.C0_pos, h.spanRobust⟩

/-- Strong stability remains true when the tested difference bound is
reduced. -/
theorem mono_differenceBound {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x D q q' C0 : ℕ}
    {relevant : Finset ℕ} {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0) (hqq : q' ≤ q) :
    StronglyStableFor A box x D q' relevant φ C0 := by
  exact ⟨h.weaklyStable.mono_differenceBound hqq, h.C0_pos, h.spanRobust⟩

/-- Strong stability remains true after discarding relevant dimensions from
the subgroup condition. -/
theorem mono_relevant {A : Finset ℤ}
    {box : (d : ℕ) → GAP 1 d} {x D q C0 : ℕ}
    {relevant relevant' : Finset ℕ}
    {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0)
    (hsub : relevant' ⊆ relevant) :
    StronglyStableFor A box x D q relevant' φ C0 := by
  exact ⟨h.weaklyStable, h.C0_pos, SpanRobust.mono_relevant h.spanRobust hsub⟩

/-- Strong stability descends through an initial deletion, provided both the
weak-stability budget and the span-stability budget have enough room and the
survivor already spans the original coordinate subgroups. -/
theorem delete {A B : Finset ℤ} {box : (d : ℕ) → GAP 1 d}
    {x x' D q C0 removed : ℕ} {relevant : Finset ℕ}
    {φ : (d : ℕ) → ℤ → LatticePoint d}
    (h : StronglyStableFor A box x D q relevant φ C0)
    (hBA : B ⊆ A) (hzero : 0 ∈ B)
    (hloss : A.card ≤ B.card + removed) (hweak : removed + x' ≤ x)
    (hstrong : removed + x' / C0 ≤ x / C0)
    (hspan : ∀ {d}, d ∈ relevant →
      generatedSubgroup (φ d) B = generatedSubgroup (φ d) A) :
    StronglyStableFor B box x' D q relevant φ C0 := by
  refine ⟨?_, h.C0_pos, ?_⟩
  · exact h.weaklyStable.delete hBA hzero hloss hweak
  · exact SpanRobust.delete h.spanRobust hBA hloss hstrong hspan

end StronglyStableFor

/-! ## Specialization to the canonical minimal bounding boxes -/

/-- The canonical minimal bounding GAP in every positive rank.  The rank-zero
value is an inert singleton presentation; stability only tests positive ranks.
This total family lets the general finite API above be reused without carrying
a positivity proof through every declaration. -/
noncomputable def minimalBoxFamily (A : Finset ℤ) : (d : ℕ) → GAP 1 d
  | 0 =>
      { offset := 0
        steps := fun i ↦ Fin.elim0 i
        widths := fun i ↦ Fin.elim0 i
        width_pos := fun i ↦ Fin.elim0 i }
  | d + 1 =>
      (BoundingBox.dBoundingBox A (d + 1) (by omega)).progression

theorem minimalBoxFamily_eq_dBoundingBox (A : Finset ℤ) {d : ℕ}
    (hd : 0 < d) :
    minimalBoxFamily A d = (BoundingBox.dBoundingBox A d hd).progression := by
  cases d with
  | zero => omega
  | succ d => rfl

/-- Weak stability using the actual least-volume `d`-bounding boxes of `A`
and the paper's difference bound `n^2`.  This is the exact natural-parameter
form of CFP Definition 2.28 for a set already containing zero. -/
def WeaklyStableMinimalFor (A : Finset ℤ)
    (deletionBudget maxRank n : ℕ) : Prop :=
  WeaklyStableFor A (minimalBoxFamily A) deletionBudget maxRank (n ^ 2)

/-- CFP's convention when zero is not assumed to lie in the original set. -/
def WeaklyStableMinimal (A : Finset ℤ)
    (deletionBudget maxRank n : ℕ) : Prop :=
  WeaklyStableMinimalFor (insert 0 A) deletionBudget maxRank n

namespace WeaklyStableMinimalFor

theorem avoids {A : Finset ℤ} {x D n : ℕ}
    (h : WeaklyStableMinimalFor A x D n)
    {B : Finset ℤ} (hBA : B ⊆ A) (hcard : A.card ≤ B.card + x)
    (hzero : 0 ∈ B) {d : ℕ} (hd : 0 < d) (hdD : d ≤ D)
    (P : GAP 1 d) (hsteps : HasDifferencesAtMost P (n ^ 2))
    (hvolume : 4 * P.volume ≤
      3 * (BoundingBox.dBoundingBox A d hd).progression.volume) :
    ¬ integerPoints B ⊆ P.carrier := by
  apply WeaklyStableFor.avoids h hBA hcard hzero hd hdD P hsteps
  simpa only [minimalBoxFamily_eq_dBoundingBox A hd] using hvolume

theorem mono_deletionBudget {A : Finset ℤ} {x x' D n : ℕ}
    (h : WeaklyStableMinimalFor A x D n) (hxx : x' ≤ x) :
    WeaklyStableMinimalFor A x' D n :=
  WeaklyStableFor.mono_deletionBudget h hxx

theorem mono_maxRank {A : Finset ℤ} {x D D' n : ℕ}
    (h : WeaklyStableMinimalFor A x D n) (hDD : D' ≤ D) :
    WeaklyStableMinimalFor A x D' n :=
  WeaklyStableFor.mono_maxRank h hDD

end WeaklyStableMinimalFor

/-- Properness data for the canonical bounding boxes in all relevant
dimensions.  CFP obtains this in the relevant dimensions from Lemma 2.26;
Definition 2.33 then uses the resulting identification maps. -/
structure RelevantBoxesProper (A : Finset ℤ) (relevant : Finset ℕ) : Prop where
  positive : ∀ {d}, d ∈ relevant → 0 < d
  proper : ∀ {d} (hd : d ∈ relevant),
    (BoundingBox.dBoundingBox A d (positive hd)).progression.Proper

/-- The actual CFP identification coordinates in relevant dimensions.  The
function is extended by zero outside those dimensions and outside `A`; neither
extension is observed by `StronglyStableMinimalFor`. -/
noncomputable def minimalIdentificationFamily {A : Finset ℤ}
    {relevant : Finset ℕ} (hproper : RelevantBoxesProper A relevant) :
    (d : ℕ) → ℤ → LatticePoint d :=
  fun d z ↦
    if hd : d ∈ relevant then
      if hz : z ∈ A then
        (BoundingBox.dBoundingBox A d (hproper.positive hd)).identificationMap
          (hproper.proper hd) ⟨z, hz⟩
      else 0
    else 0

@[simp]
theorem minimalIdentificationFamily_apply {A : Finset ℤ}
    {relevant : Finset ℕ} (hproper : RelevantBoxesProper A relevant)
    {d : ℕ} (hd : d ∈ relevant) {z : ℤ} (hz : z ∈ A) :
    minimalIdentificationFamily hproper d z =
      (BoundingBox.dBoundingBox A d (hproper.positive hd)).identificationMap
        (hproper.proper hd) ⟨z, hz⟩ := by
  simp [minimalIdentificationFamily, hd, hz]

/-- Strong stability using the canonical minimal bounding boxes and their
proper identification maps.  This is the exact natural-parameter form of CFP
Definition 2.33 for a set containing zero. -/
def StronglyStableMinimalFor (A : Finset ℤ)
    (deletionBudget maxRank n : ℕ) (relevant : Finset ℕ)
    (hproper : RelevantBoxesProper A relevant) (C0 : ℕ) : Prop :=
  StronglyStableFor A (minimalBoxFamily A) deletionBudget maxRank (n ^ 2)
    relevant (minimalIdentificationFamily hproper) C0

/-- CFP's zero-adjoining convention for canonical strong stability. -/
def StronglyStableMinimal (A : Finset ℤ)
    (deletionBudget maxRank n : ℕ) (relevant : Finset ℕ)
    (hproper : RelevantBoxesProper (insert 0 A) relevant) (C0 : ℕ) : Prop :=
  StronglyStableMinimalFor (insert 0 A) deletionBudget maxRank n relevant
    hproper C0

namespace StronglyStableMinimalFor

theorem weaklyStable {A : Finset ℤ} {x D n C0 : ℕ}
    {relevant : Finset ℕ} {hproper : RelevantBoxesProper A relevant}
    (h : StronglyStableMinimalFor A x D n relevant hproper C0) :
    WeaklyStableMinimalFor A x D n :=
  StronglyStableFor.weaklyStable h

theorem generatedSubgroup_eq {A : Finset ℤ} {x D n C0 : ℕ}
    {relevant : Finset ℕ} {hproper : RelevantBoxesProper A relevant}
    (h : StronglyStableMinimalFor A x D n relevant hproper C0)
    {d : ℕ} (hd : d ∈ relevant) {B : Finset ℤ} (hBA : B ⊆ A)
    (hcard : A.card ≤ B.card + x / C0) (hzero : 0 ∈ B) :
    generatedSubgroup (minimalIdentificationFamily hproper d) B =
      generatedSubgroup (minimalIdentificationFamily hproper d) A :=
  StronglyStableFor.generatedSubgroup_eq h hd hBA hcard hzero

theorem mono_deletionBudget {A : Finset ℤ} {x x' D n C0 : ℕ}
    {relevant : Finset ℕ} {hproper : RelevantBoxesProper A relevant}
    (h : StronglyStableMinimalFor A x D n relevant hproper C0)
    (hxx : x' ≤ x) :
    StronglyStableMinimalFor A x' D n relevant hproper C0 :=
  StronglyStableFor.mono_deletionBudget h hxx

end StronglyStableMinimalFor

end Erdos186.CFP.Stability
