/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.Stability

/-!
# Pruning finite sets until their generated subgroups are robust

This file isolates the terminating pruning argument used in the preprocessing
stage of the Conlon--Fox--Pham proof.  The argument itself is independent of
the structure of subgroups.  A finite set has a `state`, and a natural-valued
rank is required to decrease whenever a deletion changes that state.  Repeated
deletions of at most `b` elements therefore stop after at most the initial
rank, with total loss at most `b` times that rank.

The final section applies the abstract lemma to the tuple of additive
subgroups generated by a finite family of coordinate maps.  The groups may
depend on the coordinate index.  Thus one rank can measure simultaneous
strict descent in all relevant dimensions.
-/

namespace Erdos186.CFP.SubgroupPruning

open scoped BigOperators

/-! ## Abstract finite pruning with a rank potential -/

/-- A set is locally stable for a state map if deleting at most `budget`
elements cannot change its state. -/
def LocallyStable {α σ : Type*} [DecidableEq α]
    (state : Finset α → σ) (budget : ℕ) (A : Finset α) : Prop :=
  ∀ ⦃B : Finset α⦄, B ⊆ A → A.card ≤ B.card + budget →
    state B = state A

/-- Rank-potential form of the finite pruning lemma.

Whenever a subset has different state, its rank is strictly smaller.  Starting
from `A`, one may consequently prune witnesses to non-stability until reaching
a locally stable subset.  The stronger, intrinsic loss bound in this theorem
uses the initial rank itself. -/
theorem exists_locallyStable_subset_of_rank
    {α σ : Type*} [DecidableEq α]
    (state : Finset α → σ) (rank : σ → ℕ) (budget : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A → state B ≠ state A →
      rank (state B) < rank (state A))
    (A : Finset α) :
    ∃ B : Finset α, B ⊆ A ∧
      A.card ≤ B.card + budget * rank (state A) ∧
      LocallyStable state budget B := by
  classical
  induction hrank : rank (state A) using Nat.strong_induction_on generalizing A with
  | h n ih =>
      by_cases hstable : LocallyStable state budget A
      · exact ⟨A, Finset.Subset.rfl, by simp, hstable⟩
      · rw [LocallyStable] at hstable
        push Not at hstable
        obtain ⟨B₀, hB₀A, hloss₀, hne₀⟩ := hstable
        have hrank₀ : rank (state B₀) < n := by
          simpa [hrank] using hdrop hB₀A hne₀
        obtain ⟨B, hBB₀, hlossB, hstableB⟩ :=
          ih (rank (state B₀)) hrank₀ B₀ rfl
        refine ⟨B, hBB₀.trans hB₀A, ?_, hstableB⟩
        have hcardB₀A : B₀.card ≤ A.card := Finset.card_le_card hB₀A
        have hcardBB₀ : B.card ≤ B₀.card := Finset.card_le_card hBB₀
        have hstep : A.card - B₀.card ≤ budget := by omega
        have htail : B₀.card - B.card ≤ budget * rank (state B₀) := by omega
        have hsum : A.card - B.card =
            (A.card - B₀.card) + (B₀.card - B.card) := by
          omega
        have hrank_succ : rank (state B₀) + 1 ≤ rank (state A) := by
          rw [hrank]
          omega
        have hmul : budget * (rank (state B₀) + 1) ≤
            budget * rank (state A) :=
          Nat.mul_le_mul_left budget hrank_succ
        rw [Nat.add_comm, ← Nat.sub_le_iff_le_add]
        rw [hsum]
        calc
          (A.card - B₀.card) + (B₀.card - B.card)
              ≤ budget + budget * rank (state B₀) :=
            Nat.add_le_add hstep htail
          _ = budget * (rank (state B₀) + 1) := by
            simp [Nat.mul_add, Nat.add_comm]
          _ ≤ budget * rank (state A) := hmul
          _ = budget * n := by rw [hrank]

/-- Version with a supplied uniform upper bound `L` on the initial rank. -/
theorem exists_locallyStable_subset
    {α σ : Type*} [DecidableEq α]
    (state : Finset α → σ) (rank : σ → ℕ) (budget L : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A → state B ≠ state A →
      rank (state B) < rank (state A))
    (A : Finset α) (hrank : rank (state A) ≤ L) :
    ∃ B : Finset α, B ⊆ A ∧ A.card ≤ B.card + budget * L ∧
      LocallyStable state budget B := by
  obtain ⟨B, hBA, hloss, hstable⟩ :=
    exists_locallyStable_subset_of_rank state rank budget hdrop A
  refine ⟨B, hBA, hloss.trans ?_, hstable⟩
  exact Nat.add_le_add_left (Nat.mul_le_mul_left budget hrank) _

/-! ## Anchor-preserving pruning -/

/-- Local stability when all admissible deletions, and the surviving set
itself, must contain a distinguished anchor. -/
def LocallyStableAt {α σ : Type*} [DecidableEq α]
    (anchor : α) (state : Finset α → σ) (budget : ℕ)
    (A : Finset α) : Prop :=
  anchor ∈ A ∧
    ∀ ⦃B : Finset α⦄, B ⊆ A → A.card ≤ B.card + budget →
      anchor ∈ B → state B = state A

/-- Anchor-preserving rank-potential pruning.  Only anchored deletions need to
decrease the potential, and every set occurring in the recursion retains the
anchor. -/
theorem exists_locallyStableAt_subset_of_rank
    {α σ : Type*} [DecidableEq α]
    (anchor : α) (state : Finset α → σ) (rank : σ → ℕ) (budget : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A → anchor ∈ B →
      state B ≠ state A → rank (state B) < rank (state A))
    (A : Finset α) (hanchor : anchor ∈ A) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card + budget * rank (state A) ∧
      LocallyStableAt anchor state budget B := by
  classical
  induction hrank : rank (state A) using Nat.strong_induction_on generalizing A with
  | h n ih =>
      by_cases hstable : ∀ ⦃B : Finset α⦄, B ⊆ A →
          A.card ≤ B.card + budget → anchor ∈ B → state B = state A
      · exact ⟨A, Finset.Subset.rfl, hanchor, by simp,
          ⟨hanchor, hstable⟩⟩
      · push Not at hstable
        obtain ⟨B₀, hB₀A, hloss₀, hanchor₀, hne₀⟩ := hstable
        have hrank₀ : rank (state B₀) < n := by
          simpa [hrank] using hdrop hB₀A hanchor₀ hne₀
        obtain ⟨B, hBB₀, hanchorB, hlossB, hstableB⟩ :=
          ih (rank (state B₀)) hrank₀ B₀ hanchor₀ rfl
        refine ⟨B, hBB₀.trans hB₀A, hanchorB, ?_, hstableB⟩
        have hcardB₀A : B₀.card ≤ A.card := Finset.card_le_card hB₀A
        have hcardBB₀ : B.card ≤ B₀.card := Finset.card_le_card hBB₀
        have hstep : A.card - B₀.card ≤ budget := by omega
        have htail : B₀.card - B.card ≤ budget * rank (state B₀) := by omega
        have hsum : A.card - B.card =
            (A.card - B₀.card) + (B₀.card - B.card) := by
          omega
        have hrank_succ : rank (state B₀) + 1 ≤ rank (state A) := by
          rw [hrank]
          omega
        have hmul : budget * (rank (state B₀) + 1) ≤
            budget * rank (state A) :=
          Nat.mul_le_mul_left budget hrank_succ
        rw [Nat.add_comm, ← Nat.sub_le_iff_le_add]
        rw [hsum]
        calc
          (A.card - B₀.card) + (B₀.card - B.card)
              ≤ budget + budget * rank (state B₀) :=
            Nat.add_le_add hstep htail
          _ = budget * (rank (state B₀) + 1) := by
            simp [Nat.mul_add, Nat.add_comm]
          _ ≤ budget * rank (state A) := hmul
          _ = budget * n := by rw [hrank]

/-- Ambient-restricted anchor-preserving pruning.  The decrease hypothesis is
needed only when the current set lies in the fixed finite ambient set.  This
is useful when the rank is defined by counting profiles reachable from that
ambient set rather than on all finite sets of `α`. -/
theorem exists_locallyStableAt_subset_of_rank_ambient
    {α σ : Type*} [DecidableEq α]
    (anchor : α) (state : Finset α → σ) (rank : σ → ℕ) (budget : ℕ)
    (ambient : Finset α)
    (hdrop : ∀ ⦃B C : Finset α⦄, B ⊆ ambient → C ⊆ B → anchor ∈ C →
      state C ≠ state B → rank (state C) < rank (state B))
    (A : Finset α) (hAambient : A ⊆ ambient) (hanchor : anchor ∈ A) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card + budget * rank (state A) ∧
      LocallyStableAt anchor state budget B := by
  classical
  induction hrank : rank (state A) using Nat.strong_induction_on generalizing A with
  | h n ih =>
      by_cases hstable : ∀ ⦃B : Finset α⦄, B ⊆ A →
          A.card ≤ B.card + budget → anchor ∈ B → state B = state A
      · exact ⟨A, Finset.Subset.rfl, hanchor, by simp,
          ⟨hanchor, hstable⟩⟩
      · push Not at hstable
        obtain ⟨B₀, hB₀A, hloss₀, hanchor₀, hne₀⟩ := hstable
        have hB₀ambient : B₀ ⊆ ambient := hB₀A.trans hAambient
        have hrank₀ : rank (state B₀) < n := by
          simpa [hrank] using hdrop hAambient hB₀A hanchor₀ hne₀
        obtain ⟨B, hBB₀, hanchorB, hlossB, hstableB⟩ :=
          ih (rank (state B₀)) hrank₀ B₀ hB₀ambient hanchor₀ rfl
        refine ⟨B, hBB₀.trans hB₀A, hanchorB, ?_, hstableB⟩
        have hcardB₀A : B₀.card ≤ A.card := Finset.card_le_card hB₀A
        have hcardBB₀ : B.card ≤ B₀.card := Finset.card_le_card hBB₀
        have hstep : A.card - B₀.card ≤ budget := by omega
        have htail : B₀.card - B.card ≤ budget * rank (state B₀) := by omega
        have hsum : A.card - B.card =
            (A.card - B₀.card) + (B₀.card - B.card) := by
          omega
        have hrank_succ : rank (state B₀) + 1 ≤ rank (state A) := by
          rw [hrank]
          omega
        have hmul : budget * (rank (state B₀) + 1) ≤
            budget * rank (state A) :=
          Nat.mul_le_mul_left budget hrank_succ
        rw [Nat.add_comm, ← Nat.sub_le_iff_le_add]
        rw [hsum]
        calc
          (A.card - B₀.card) + (B₀.card - B.card)
              ≤ budget + budget * rank (state B₀) :=
            Nat.add_le_add hstep htail
          _ = budget * (rank (state B₀) + 1) := by
            simp [Nat.mul_add, Nat.add_comm]
          _ ≤ budget * rank (state A) := hmul
          _ = budget * n := by rw [hrank]

/-- Uniform upper-bound form of anchor-preserving pruning. -/
theorem exists_locallyStableAt_subset
    {α σ : Type*} [DecidableEq α]
    (anchor : α) (state : Finset α → σ) (rank : σ → ℕ)
    (budget L : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A → anchor ∈ B →
      state B ≠ state A → rank (state B) < rank (state A))
    (A : Finset α) (hanchor : anchor ∈ A)
    (hrank : rank (state A) ≤ L) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card + budget * L ∧
      LocallyStableAt anchor state budget B := by
  obtain ⟨B, hBA, hanchorB, hloss, hstable⟩ :=
    exists_locallyStableAt_subset_of_rank
      anchor state rank budget hdrop A hanchor
  refine ⟨B, hBA, hanchorB, hloss.trans ?_, hstable⟩
  exact Nat.add_le_add_left (Nat.mul_le_mul_left budget hrank) _

/-! ## Families of generated additive subgroups -/

/-- The tuple of subgroups generated by the images of `A` in a family of
additive groups. -/
def generatedProfile {α D : Type*} [DecidableEq α]
    (G : D → Type*) [∀ d, AddGroup (G d)]
    (φ : ∀ d, α → G d) (A : Finset α) :
    ∀ d, AddSubgroup (G d) :=
  fun d ↦ AddSubgroup.closure (φ d '' (A : Set α))

/-- Generated subgroup profiles are monotone under inclusion. -/
theorem generatedProfile_mono
    {α D : Type*} [DecidableEq α]
    (G : D → Type*) [∀ d, AddGroup (G d)]
    (φ : ∀ d, α → G d) {A B : Finset α} (hAB : A ⊆ B) :
    ∀ d, generatedProfile G φ A d ≤ generatedProfile G φ B d := by
  intro d
  apply AddSubgroup.closure_mono
  exact Set.image_mono (by exact_mod_cast hAB)

/-- Simultaneous subgroup pruning for a finite family of coordinate maps.

The potential `rank` is evaluated on the entire subgroup profile.  The
decrease hypothesis says exactly that any deletion which changes at least one
generated coordinate subgroup makes strict progress. -/
theorem exists_subset_generatedProfile_stable_of_rank
    {α D : Type*} [DecidableEq α] [Fintype D]
    (G : D → Type*) [∀ d, AddGroup (G d)]
    (φ : ∀ d, α → G d)
    (rank : (∀ d, AddSubgroup (G d)) → ℕ) (budget : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A →
      (∃ d, generatedProfile G φ B d ≠ generatedProfile G φ A d) →
      rank (generatedProfile G φ B) < rank (generatedProfile G φ A))
    (A : Finset α) :
    ∃ B : Finset α, B ⊆ A ∧
      A.card ≤ B.card + budget * rank (generatedProfile G φ A) ∧
      ∀ ⦃C : Finset α⦄, C ⊆ B → B.card ≤ C.card + budget →
        ∀ d, generatedProfile G φ C d = generatedProfile G φ B d := by
  have hdrop' : ∀ ⦃A B : Finset α⦄, B ⊆ A →
      generatedProfile G φ B ≠ generatedProfile G φ A →
      rank (generatedProfile G φ B) < rank (generatedProfile G φ A) := by
    intro A B hBA hne
    apply hdrop hBA
    by_contra hall
    push Not at hall
    exact hne (funext hall)
  obtain ⟨B, hBA, hloss, hstable⟩ :=
    exists_locallyStable_subset_of_rank
      (generatedProfile G φ) rank budget hdrop' A
  refine ⟨B, hBA, hloss, ?_⟩
  intro C hCB hcard d
  exact congrFun (hstable hCB hcard) d

/-- Uniform-`L` form of simultaneous subgroup pruning.  At most `budget * L`
elements are lost, and every subsequent deletion of at most `budget` elements
preserves every generated subgroup. -/
theorem exists_subset_generatedProfile_stable
    {α D : Type*} [DecidableEq α] [Fintype D]
    (G : D → Type*) [∀ d, AddGroup (G d)]
    (φ : ∀ d, α → G d)
    (rank : (∀ d, AddSubgroup (G d)) → ℕ) (budget L : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A →
      (∃ d, generatedProfile G φ B d ≠ generatedProfile G φ A d) →
      rank (generatedProfile G φ B) < rank (generatedProfile G φ A))
    (A : Finset α) (hrank : rank (generatedProfile G φ A) ≤ L) :
    ∃ B : Finset α, B ⊆ A ∧ A.card ≤ B.card + budget * L ∧
      ∀ ⦃C : Finset α⦄, C ⊆ B → B.card ≤ C.card + budget →
        ∀ d, generatedProfile G φ C d = generatedProfile G φ B d := by
  obtain ⟨B, hBA, hloss, hstable⟩ :=
    exists_subset_generatedProfile_stable_of_rank G φ rank budget hdrop A
  refine ⟨B, hBA, hloss.trans ?_, hstable⟩
  exact Nat.add_le_add_left (Nat.mul_le_mul_left budget hrank) _

/-! ## The CFP lattice-coordinate specialization -/

/-- The generated subgroup profile over the finite set of relevant
dimensions, using the existing CFP definition of `generatedSubgroup`. -/
def relevantGeneratedProfile {α : Type*} [DecidableEq α]
    (relevant : Finset ℕ) (φ : (d : ℕ) → α → LatticePoint d)
    (A : Finset α) :
    ∀ d : ↥relevant, AddSubgroup (LatticePoint (d : ℕ)) :=
  fun d ↦ Stability.generatedSubgroup (φ d) A

/-- Anchor-preserving simultaneous subgroup pruning in precisely the form
needed by `Stability.SpanRobust`. -/
theorem exists_subset_spanRobust_of_rank
    {α : Type*} [DecidableEq α]
    (anchor : α) (relevant : Finset ℕ)
    (φ : (d : ℕ) → α → LatticePoint d)
    (rank : (∀ d : ↥relevant,
      AddSubgroup (LatticePoint (d : ℕ))) → ℕ)
    (budget : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A → anchor ∈ B →
      (∃ d : ↥relevant,
        Stability.generatedSubgroup (φ d) B ≠
          Stability.generatedSubgroup (φ d) A) →
      rank (relevantGeneratedProfile relevant φ B) <
        rank (relevantGeneratedProfile relevant φ A))
    (A : Finset α) (hanchor : anchor ∈ A) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card +
        budget * rank (relevantGeneratedProfile relevant φ A) ∧
      Stability.SpanRobust anchor B budget relevant φ := by
  have hdrop' : ∀ ⦃A B : Finset α⦄, B ⊆ A → anchor ∈ B →
      relevantGeneratedProfile relevant φ B ≠
        relevantGeneratedProfile relevant φ A →
      rank (relevantGeneratedProfile relevant φ B) <
        rank (relevantGeneratedProfile relevant φ A) := by
    intro A B hBA hanchorB hne
    apply hdrop hBA hanchorB
    by_contra hall
    push Not at hall
    exact hne (funext hall)
  obtain ⟨B, hBA, hanchorB, hloss, hstable⟩ :=
    exists_locallyStableAt_subset_of_rank anchor
      (relevantGeneratedProfile relevant φ) rank budget hdrop' A hanchor
  refine ⟨B, hBA, hanchorB, hloss, ?_⟩
  intro d hd C hCB hcard hanchorC
  exact congrFun (hstable.2 hCB hcard hanchorC) ⟨d, hd⟩

/-- Ambient-restricted form of simultaneous CFP subgroup pruning.  The rank
drop need only be proved for a current set `B` lying in `ambient` and an
anchored deletion `C ⊆ B`; the recursion maintains this ambient invariant. -/
theorem exists_subset_spanRobust_of_rank_ambient
    {α : Type*} [DecidableEq α]
    (anchor : α) (relevant : Finset ℕ)
    (φ : (d : ℕ) → α → LatticePoint d)
    (rank : (∀ d : ↥relevant,
      AddSubgroup (LatticePoint (d : ℕ))) → ℕ)
    (budget : ℕ) (ambient : Finset α)
    (hdrop : ∀ ⦃B C : Finset α⦄, B ⊆ ambient → C ⊆ B → anchor ∈ C →
      (∃ d : ↥relevant,
        Stability.generatedSubgroup (φ d) C ≠
          Stability.generatedSubgroup (φ d) B) →
      rank (relevantGeneratedProfile relevant φ C) <
        rank (relevantGeneratedProfile relevant φ B))
    (A : Finset α) (hAambient : A ⊆ ambient) (hanchor : anchor ∈ A) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card +
        budget * rank (relevantGeneratedProfile relevant φ A) ∧
      Stability.SpanRobust anchor B budget relevant φ := by
  have hdrop' : ∀ ⦃B C : Finset α⦄, B ⊆ ambient → C ⊆ B → anchor ∈ C →
      relevantGeneratedProfile relevant φ C ≠
        relevantGeneratedProfile relevant φ B →
      rank (relevantGeneratedProfile relevant φ C) <
        rank (relevantGeneratedProfile relevant φ B) := by
    intro B C hBambient hCB hanchorC hne
    apply hdrop hBambient hCB hanchorC
    by_contra hall
    push Not at hall
    exact hne (funext hall)
  obtain ⟨B, hBA, hanchorB, hloss, hstable⟩ :=
    exists_locallyStableAt_subset_of_rank_ambient anchor
      (relevantGeneratedProfile relevant φ) rank budget ambient hdrop'
      A hAambient hanchor
  refine ⟨B, hBA, hanchorB, hloss, ?_⟩
  intro d hd C hCB hcard hanchorC
  exact congrFun (hstable.2 hCB hcard hanchorC) ⟨d, hd⟩

/-- Uniform-`L` form of the CFP span-pruning theorem. -/
theorem exists_subset_spanRobust
    {α : Type*} [DecidableEq α]
    (anchor : α) (relevant : Finset ℕ)
    (φ : (d : ℕ) → α → LatticePoint d)
    (rank : (∀ d : ↥relevant,
      AddSubgroup (LatticePoint (d : ℕ))) → ℕ)
    (budget L : ℕ)
    (hdrop : ∀ ⦃A B : Finset α⦄, B ⊆ A → anchor ∈ B →
      (∃ d : ↥relevant,
        Stability.generatedSubgroup (φ d) B ≠
          Stability.generatedSubgroup (φ d) A) →
      rank (relevantGeneratedProfile relevant φ B) <
        rank (relevantGeneratedProfile relevant φ A))
    (A : Finset α) (hanchor : anchor ∈ A)
    (hrank : rank (relevantGeneratedProfile relevant φ A) ≤ L) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card + budget * L ∧
      Stability.SpanRobust anchor B budget relevant φ := by
  obtain ⟨B, hBA, hanchorB, hloss, hrobust⟩ :=
    exists_subset_spanRobust_of_rank
      anchor relevant φ rank budget hdrop A hanchor
  refine ⟨B, hBA, hanchorB, hloss.trans ?_, hrobust⟩
  exact Nat.add_le_add_left (Nat.mul_le_mul_left budget hrank) _

/-- Uniform-`L` corollary of ambient-restricted CFP span pruning. -/
theorem exists_subset_spanRobust_ambient
    {α : Type*} [DecidableEq α]
    (anchor : α) (relevant : Finset ℕ)
    (φ : (d : ℕ) → α → LatticePoint d)
    (rank : (∀ d : ↥relevant,
      AddSubgroup (LatticePoint (d : ℕ))) → ℕ)
    (budget L : ℕ) (ambient : Finset α)
    (hdrop : ∀ ⦃B C : Finset α⦄, B ⊆ ambient → C ⊆ B → anchor ∈ C →
      (∃ d : ↥relevant,
        Stability.generatedSubgroup (φ d) C ≠
          Stability.generatedSubgroup (φ d) B) →
      rank (relevantGeneratedProfile relevant φ C) <
        rank (relevantGeneratedProfile relevant φ B))
    (A : Finset α) (hAambient : A ⊆ ambient) (hanchor : anchor ∈ A)
    (hrank : rank (relevantGeneratedProfile relevant φ A) ≤ L) :
    ∃ B : Finset α, B ⊆ A ∧ anchor ∈ B ∧
      A.card ≤ B.card + budget * L ∧
      Stability.SpanRobust anchor B budget relevant φ := by
  obtain ⟨B, hBA, hanchorB, hloss, hrobust⟩ :=
    exists_subset_spanRobust_of_rank_ambient
      anchor relevant φ rank budget ambient hdrop A hAambient hanchor
  refine ⟨B, hBA, hanchorB, hloss.trans ?_, hrobust⟩
  exact Nat.add_le_add_left (Nat.mul_le_mul_left budget hrank) _

end Erdos186.CFP.SubgroupPruning
