/-
Copyright (c) 2026 The Formal Conjectures Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Formal Conjectures Authors
-/

import ErdosProblems.Erdos446.Moment
import ErdosProblems.Erdos446.Endpoint
import ErdosProblems.Erdos446.SieveFamilyLower

/-!
# Erdős Problem 446: second moments for natural densities

The logarithmic cluster estimate controls overlaps.  This module provides the
matching density-level second-moment inequality for a finite collection of
sets of integers.
-/

namespace Erdos446

open Filter Finset Set MeasureTheory Real
open scoped BigOperators ENNReal Topology

private theorem restrict_count_real (A : Set ℕ) (n : ℕ) :
    (Measure.count.restrict (Set.Iio n)).real A =
      ((A ∩ Set.Iio n).ncard : ℝ) := by
  rw [Measure.real, Measure.restrict_apply MeasurableSet.of_discrete]
  rw [Measure.count_apply_finite _ (Set.toFinite (A ∩ Set.Iio n))]
  rw [Set.ncard_eq_toFinset_card (A ∩ Set.Iio n)
    (Set.toFinite (A ∩ Set.Iio n))]
  simp

/-- The finite-union second-moment inequality, expressed in normalized prefix
counts. -/
theorem partialDensity_finite_union_second_moment
    {ι : Type*} (s : Finset ι) (A : ι → Set ℕ) (n : ℕ) :
    (∑ i ∈ s, (A i).partialDensity Set.univ n) ^ 2 ≤
      (⋃ i ∈ s, A i).partialDensity Set.univ n *
        (∑ i ∈ s, ∑ j ∈ s,
          (A i ∩ A j).partialDensity Set.univ n) := by
  classical
  by_cases hn : n = 0
  · subst n
    simp [Set.partialDensity]
  have hnR : (0 : ℝ) < n := by exact_mod_cast (Nat.pos_of_ne_zero hn)
  have hmoment := finite_union_second_moment
    (μ := Measure.count.restrict (Set.Iio n)) s A
    (fun _ _ ↦ MeasurableSet.of_discrete)
    (fun i hi ↦ by
      rw [Measure.restrict_apply MeasurableSet.of_discrete]
      exact ne_of_lt (lt_of_le_of_lt (measure_mono inter_subset_right) (by simp)))
  have hrewrite (B : Set ℕ) :
      (Measure.count.restrict (Set.Iio n)).real B =
        (n : ℝ) * B.partialDensity Set.univ n := by
    rw [restrict_count_real]
    simp only [Set.partialDensity, Set.inter_univ, Set.univ_inter,
      Set.ncard_Iio_nat]
    field_simp [hnR.ne']
  simp_rw [hrewrite] at hmoment
  simp_rw [← Finset.mul_sum] at hmoment
  nlinarith [mul_pos hnR hnR]

/-- Passing the finite-union second moment to natural-density limits. -/
theorem density_finite_union_second_moment
    {ι : Type*} (s : Finset ι) (A : ι → Set ℕ)
    (a : ι → ℝ) (b : ι → ι → ℝ) (u : ℝ)
    (hA : ∀ i ∈ s, (A i).HasDensity (a i))
    (hpair : ∀ i ∈ s, ∀ j ∈ s,
      (A i ∩ A j).HasDensity (b i j))
    (hU : (⋃ i ∈ s, A i).HasDensity u) :
    (∑ i ∈ s, a i) ^ 2 ≤ u * ∑ i ∈ s, ∑ j ∈ s, b i j := by
  classical
  have hsum : Tendsto
      (fun n : ℕ ↦ ∑ i ∈ s, (A i).partialDensity Set.univ n)
      atTop (nhds (∑ i ∈ s, a i)) :=
    tendsto_finset_sum s hA
  have hpairs : Tendsto
      (fun n : ℕ ↦ ∑ i ∈ s, ∑ j ∈ s,
        (A i ∩ A j).partialDensity Set.univ n)
      atTop (nhds (∑ i ∈ s, ∑ j ∈ s, b i j)) := by
    apply tendsto_finset_sum
    intro i hi
    exact tendsto_finset_sum s (hpair i hi)
  have hdiff := (hsum.pow 2).sub (hU.mul hpairs)
  have hle :
      (∑ i ∈ s, a i) ^ 2 - u * ∑ i ∈ s, ∑ j ∈ s, b i j ≤ 0 := by
    apply le_of_tendsto hdiff
    exact Eventually.of_forall fun n ↦ by
      exact sub_nonpos.mpr (partialDensity_finite_union_second_moment s A n)
  linarith

/-! ## Specialization to finite unions of divisibility events -/

/-- The union of the sets of multiples generated by `C`. -/
def finiteMultipleSet (C : Finset ℕ) : Set ℕ :=
  {m | ∃ c ∈ C, c ∣ m}

/-- The product is a (not necessarily minimal) period of the finite union. -/
theorem finiteMultipleSet_periodic (C : Finset ℕ) :
    Function.Periodic (fun m ↦ m ∈ finiteMultipleSet C) (∏ c ∈ C, c) := by
  classical
  intro m
  apply propext
  constructor
  · rintro ⟨c, hc, hcm⟩
    exact ⟨c, hc, (Nat.dvd_add_iff_left (Finset.dvd_prod_of_mem id hc)).mpr hcm⟩
  · rintro ⟨c, hc, hcm⟩
    exact ⟨c, hc, (Nat.dvd_add_iff_left (Finset.dvd_prod_of_mem id hc)).mp hcm⟩

/-- Exact residue density of a finite union of sets of multiples. -/
noncomputable def finiteMultipleDensity (C : Finset ℕ) : ℝ :=
  by
    classical
    exact (((((Finset.range (∏ c ∈ C, c)).filter
      (fun m ↦ m ∈ finiteMultipleSet C)).card : ℕ) : ℝ) /
        ((∏ c ∈ C, c) : ℝ))

theorem finiteMultipleSet_hasDensity (C : Finset ℕ)
    (hpos : ∀ c ∈ C, 0 < c) :
    (finiteMultipleSet C).HasDensity (finiteMultipleDensity C) := by
  classical
  have hperiodPos : 0 < ∏ c ∈ C, c := by
    exact Finset.prod_pos hpos
  simpa [finiteMultipleDensity] using
    hasDensity_of_periodic (fun m ↦ m ∈ finiteMultipleSet C)
      (∏ c ∈ C, c) hperiodPos (finiteMultipleSet_periodic C)

theorem iUnion_multipleSet_eq (C : Finset ℕ) :
    (⋃ c ∈ C, multipleSet c) = finiteMultipleSet C := by
  ext m
  simp [finiteMultipleSet, multipleSet]

theorem multipleSet_inter (c d : ℕ) :
    multipleSet c ∩ multipleSet d = multipleSet (Nat.lcm c d) := by
  ext m
  simp [multipleSet, Nat.lcm_dvd_iff]

/-- The exact density second moment for a finite divisor family. -/
theorem finite_multiples_density_second_moment
    (C : Finset ℕ) (hpos : ∀ c ∈ C, 0 < c) :
    (∑ c ∈ C, 1 / (c : ℝ)) ^ 2 ≤
      finiteMultipleDensity C *
        ∑ c ∈ C, ∑ d ∈ C, 1 / (Nat.lcm c d : ℝ) := by
  have hmoment := density_finite_union_second_moment C multipleSet
    (fun c ↦ 1 / (c : ℝ))
    (fun c d ↦ 1 / (Nat.lcm c d : ℝ))
    (finiteMultipleDensity C)
    (fun c hc ↦ multipleSet_hasDensity c (hpos c hc))
    (fun c hc d hd ↦ by
      rw [multipleSet_inter]
      exact multipleSet_hasDensity (Nat.lcm c d)
        (Nat.lcm_pos (hpos c hc) (hpos d hd)))
    (by simpa [iUnion_multipleSet_eq] using finiteMultipleSet_hasDensity C hpos)
  exact hmoment

/-- A family contained in `(y,z]` gives a lower bound for the divisor
density in terms of its reciprocal first and lcm second moments. -/
theorem finite_divisor_family_moment_lower
    {y z : ℕ} (hy : 0 < y) (C : Finset ℕ)
    (hinterval : ∀ c ∈ C, c ∈ Finset.Ioc y z) :
    (∑ c ∈ C, 1 / (c : ℝ)) ^ 2 ≤
      epsilon y z *
        ∑ c ∈ C, ∑ d ∈ C, 1 / (Nat.lcm c d : ℝ) := by
  have hpos : ∀ c ∈ C, 0 < c := fun c hc ↦
    lt_trans hy (Finset.mem_Ioc.mp (hinterval c hc)).1
  have hsub : finiteMultipleSet C ⊆ divisorSetIoc y z := by
    rintro m ⟨c, hc, hcm⟩
    rw [divisorSetIoc, Set.mem_setOf_eq, divisorCountIoc]
    exact Finset.card_pos.mpr
      ⟨c, Finset.mem_filter.mpr ⟨hinterval c hc, hcm⟩⟩
  have hdensityLe : finiteMultipleDensity C ≤ epsilon y z :=
    density_le_of_subset (finiteMultipleSet_hasDensity C hpos)
      (divisorSetIoc_hasDensity y z hy) hsub
  calc
    (∑ c ∈ C, 1 / (c : ℝ)) ^ 2 ≤
        finiteMultipleDensity C *
          ∑ c ∈ C, ∑ d ∈ C, 1 / (Nat.lcm c d : ℝ) :=
      finite_multiples_density_second_moment C hpos
    _ ≤ epsilon y z *
          ∑ c ∈ C, ∑ d ∈ C, 1 / (Nat.lcm c d : ℝ) := by
      apply mul_le_mul_of_nonneg_right hdensityLe
      positivity

/-- More flexible form: a modulus need not itself lie in `(y,z]`; it is
enough that it contain an interval divisor.  This is the form used for
Ford's moduli `a*p`. -/
theorem finite_divisor_moduli_moment_lower
    {y z : ℕ} (hy : 0 < y) (C : Finset ℕ)
    (hpos : ∀ c ∈ C, 0 < c)
    (hwitness : ∀ c ∈ C, ∃ d ∈ Finset.Ioc y z, d ∣ c) :
    (∑ c ∈ C, 1 / (c : ℝ)) ^ 2 ≤
      epsilon y z *
        ∑ c ∈ C, ∑ d ∈ C, 1 / (Nat.lcm c d : ℝ) := by
  have hsub : finiteMultipleSet C ⊆ divisorSetIoc y z := by
    rintro m ⟨c, hc, hcm⟩
    obtain ⟨d, hdIoc, hdc⟩ := hwitness c hc
    rw [divisorSetIoc, Set.mem_setOf_eq, divisorCountIoc]
    exact Finset.card_pos.mpr
      ⟨d, Finset.mem_filter.mpr ⟨hdIoc, hdc.trans hcm⟩⟩
  have hdensityLe : finiteMultipleDensity C ≤ epsilon y z :=
    density_le_of_subset (finiteMultipleSet_hasDensity C hpos)
      (divisorSetIoc_hasDensity y z hy) hsub
  exact (finite_multiples_density_second_moment C hpos).trans
    (mul_le_mul_of_nonneg_right hdensityLe (by positivity))

end Erdos446
