import Wikipedia.HopfProblem.CuspNormalizationGermsBasicDomain
import Wikipedia.HopfProblem.CuspNormalizationGermsLocalRing
import Mathlib.Analysis.Analytic.Order
import Mathlib.RingTheory.DiscreteValuationRing.Basic

/-!
# Factoriality of actual analytic germs in one variable

The analytic order theorem factors each nonzero neighbourhood germ as a power
of the centered coordinate times the germ of a nonvanishing analytic function.
The latter is a unit in the actual analytic-germ ring.  This identifies the
maximal ideal and makes the ring a discrete valuation ring, hence a principal
ideal domain and a unique factorization domain.

All these conclusions concern the subring of actual neighbourhood germs;
no identification with a formal power-series ring is assumed.
-/

open Set Filter Topology

namespace Wikipedia.HopfProblem.CuspNormalization.Germs

/-- The actual germ of the centered coordinate in one complex variable. -/
noncomputable def centeredCoordinateGerm (a : ℂ) : AnalyticGerm a :=
  ofAnalytic (fun z : ℂ => z - a) (analyticAt_id.sub analyticAt_const)

@[simp] theorem eval_centeredCoordinateGerm (a : ℂ) :
    eval a (centeredCoordinateGerm a) = 0 := by
  simp [centeredCoordinateGerm]

/-- The centered coordinate does not vanish on a neighbourhood of its center. -/
theorem centeredCoordinateGerm_ne_zero (a : ℂ) : centeredCoordinateGerm a ≠ 0 := by
  intro h
  have hz : (fun z : ℂ => z - a) =ᶠ[𝓝 a] 0 :=
    (ofAnalytic_eq_zero_iff _ _).mp h
  have horder := analyticOrderAt_eq_top.mpr hz
  simp only [analyticOrderAt_id_sub_const_self, ENat.one_ne_top] at horder

/-- Analytic order gives an exact factorization in the ring of actual germs. -/
theorem exists_eq_centeredCoordinateGerm_pow_mul_unit {a : ℂ}
    (φ : AnalyticGerm a) (hφ : φ ≠ 0) :
    ∃ (n : ℕ) (u : (AnalyticGerm a)ˣ), φ = centeredCoordinateGerm a ^ n * u := by
  obtain ⟨f, hf, rfl⟩ := exists_representative φ
  have hfinite : analyticOrderAt f a ≠ ⊤ := by
    intro htop
    exact hφ ((ofAnalytic_eq_zero_iff f hf).mpr (analyticOrderAt_eq_top.mp htop))
  obtain ⟨g, hg, hg0, hfg⟩ := hf.analyticOrderAt_ne_top.mp hfinite
  refine ⟨analyticOrderNatAt f a, unitOfAnalytic g hg hg0, ?_⟩
  apply ext
  change (f : Filter.Germ (𝓝 a) ℂ) =
    ((fun z : ℂ => z - a) : Filter.Germ (𝓝 a) ℂ) ^ analyticOrderNatAt f a *
      (g : Filter.Germ (𝓝 a) ℂ)
  rw [← Filter.Germ.coe_pow, ← Filter.Germ.coe_mul]
  apply Filter.Germ.coe_eq.mpr
  filter_upwards [hfg] with z hz
  simpa only [Pi.mul_apply, Pi.pow_apply, smul_eq_mul] using hz

/-- The maximal ideal of one-variable analytic germs is generated by the
centered coordinate. -/
theorem maximalIdeal_eq_span_centeredCoordinateGerm (a : ℂ) :
    IsLocalRing.maximalIdeal (AnalyticGerm a) = Ideal.span {centeredCoordinateGerm a} := by
  apply Ideal.ext
  intro φ
  rw [mem_maximalIdeal_iff_eval_eq_zero, Ideal.mem_span_singleton]
  constructor
  · intro hφ
    by_cases hzero : φ = 0
    · simp [hzero]
    obtain ⟨n, u, rfl⟩ := exists_eq_centeredCoordinateGerm_pow_mul_unit φ hzero
    cases n with
    | zero =>
        simp only [pow_zero, one_mul] at hφ
        exact False.elim ((isUnit_iff_eval_ne_zero (u : AnalyticGerm a)).mp u.isUnit hφ)
    | succ n =>
        exact ⟨centeredCoordinateGerm a ^ n * u, by rw [pow_succ', mul_assoc]⟩
  · rintro ⟨ψ, rfl⟩
    simp

/-- The centered coordinate is an irreducible element of the actual germ ring. -/
theorem centeredCoordinateGerm_irreducible (a : ℂ) :
    Irreducible (centeredCoordinateGerm a) :=
  IsDiscreteValuationRing.irreducible_of_span_eq_maximalIdeal _
    (centeredCoordinateGerm_ne_zero a) (maximalIdeal_eq_span_centeredCoordinateGerm a)

/-- Actual analytic germs in one complex variable form a discrete valuation ring. -/
instance analyticGerm_oneVariable_isDiscreteValuationRing (a : ℂ) :
    IsDiscreteValuationRing (AnalyticGerm a) := by
  apply IsDiscreteValuationRing.ofHasUnitMulPowIrreducibleFactorization
  refine ⟨centeredCoordinateGerm a, centeredCoordinateGerm_irreducible a, ?_⟩
  intro φ hφ
  obtain ⟨n, u, h⟩ := exists_eq_centeredCoordinateGerm_pow_mul_unit φ hφ
  exact ⟨n, u, h.symm⟩

/-- Every ideal of actual one-variable analytic germs is principal. -/
theorem oneVariable_isPrincipalIdealRing (a : ℂ) :
    IsPrincipalIdealRing (AnalyticGerm a) := inferInstance

/-- Unique factorization for actual one-variable analytic germs. -/
theorem oneVariable_uniqueFactorizationMonoid (a : ℂ) :
    UniqueFactorizationMonoid (AnalyticGerm a) := inferInstance

end Wikipedia.HopfProblem.CuspNormalization.Germs
