import Wikipedia.HopfProblem.DegreeCollapseRationalResidue
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.LinearAlgebra.Isomorphisms

/-!
# A normalized rational coordinate on an actual cyclic extension

For a finite quotient with kernel generated by an infinite-order meridian,
the quotient's cardinality sends every original element into that kernel.
Its unique integer coefficient constructs a rational linear functional
whose value on the original meridian is one. No splitting of the integral
extension is assumed. The normalized rational functional is unique.
-/

noncomputable section

open Function

namespace Wikipedia.HopfProblem.DegreeCollapse.CyclicExtensionCharacter

variable {G H : Type*} [AddCommGroup G] [AddCommGroup H]
  (μ : G) (q : G →+ H) (hker : q.ker = AddSubgroup.zmultiples μ)

include hker in
theorem exists_coefficient (g : G) :
    ∃ k : ℤ, k • μ = (Nat.card H : ℤ) • g := by
  have hz : q ((Nat.card H : ℤ) • g) = 0 := by
    rw [map_zsmul]
    exact_mod_cast (card_nsmul_eq_zero' : Nat.card H • q g = 0)
  have hm : (Nat.card H : ℤ) • g ∈ AddSubgroup.zmultiples μ := by
    rw [← hker]
    exact hz
  exact AddSubgroup.mem_zmultiples_iff.mp hm

def coefficient (g : G) : ℤ := (exists_coefficient μ q hker g).choose

theorem coefficient_spec (g : G) :
    coefficient μ q hker g • μ = (Nat.card H : ℤ) • g :=
  (exists_coefficient μ q hker g).choose_spec

variable (hμ : Injective (fun k : ℤ ↦ k • μ))

def coefficientMap : G →+ ℤ where
  toFun := coefficient μ q hker
  map_zero' := by
    apply hμ
    change coefficient μ q hker 0 • μ = (0 : ℤ) • μ
    rw [coefficient_spec, smul_zero, zero_smul]
  map_add' g h := by
    apply hμ
    change coefficient μ q hker (g + h) • μ =
      (coefficient μ q hker g + coefficient μ q hker h) • μ
    rw [add_zsmul, coefficient_spec, coefficient_spec, coefficient_spec, smul_add]

def rationalCoordinate : G →ₗ[ℤ] ℚ :=
  (Nat.card H : ℚ)⁻¹ • ((Int.castAddHom ℚ).toIntLinearMap.comp
    (coefficientMap μ q hker hμ).toIntLinearMap)

theorem rationalCoordinate_apply (g : G) :
    rationalCoordinate μ q hker hμ g =
      (coefficient μ q hker g : ℚ) / (Nat.card H : ℚ) := by
  change (Nat.card H : ℚ)⁻¹ * (coefficient μ q hker g : ℚ) = _
  rw [div_eq_mul_inv, mul_comm]

variable [Finite H]

theorem rationalCoordinate_denominator (g : G) :
    (Nat.card H : ℚ) * rationalCoordinate μ q hker hμ g =
      (coefficient μ q hker g : ℚ) := by
  rw [rationalCoordinate_apply]
  have hn : (Nat.card H : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr Nat.card_pos.ne'
  field_simp

theorem rationalCoordinate_meridian : rationalCoordinate μ q hker hμ μ = 1 := by
  have he : coefficient μ q hker μ = (Nat.card H : ℤ) :=
    hμ (coefficient_spec μ q hker μ)
  rw [rationalCoordinate_apply, he, Int.cast_natCast]
  exact div_self (Nat.cast_ne_zero.mpr Nat.card_pos.ne')

include hμ in
theorem rationalCoordinate_unique (f : G →ₗ[ℤ] ℚ) (hf : f μ = 1) :
    f = rationalCoordinate μ q hker hμ := by
  ext g
  have he := congrArg f (coefficient_spec μ q hker g)
  simp only [map_zsmul, hf, zsmul_eq_mul, mul_one, Int.cast_natCast] at he
  have hn : (Nat.card H : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr Nat.card_pos.ne'
  apply mul_left_cancel₀ hn
  exact he.symm.trans (rationalCoordinate_denominator μ q hker hμ g).symm

theorem rationalCoordinate_of_relation (g : G) (l p : ℤ) (hl : l ≠ 0)
    (hrel : l • g + p • μ = 0) :
    rationalCoordinate μ q hker hμ g = -(p : ℚ) / (l : ℚ) := by
  have he := congrArg (rationalCoordinate μ q hker hμ) hrel
  simp only [map_add, map_zsmul, rationalCoordinate_meridian, map_zero,
    zsmul_eq_mul, mul_one] at he
  apply (eq_div_iff (Int.cast_ne_zero.mpr hl)).mpr
  linarith

end Wikipedia.HopfProblem.DegreeCollapse.CyclicExtensionCharacter
