import Wikipedia.HopfProblem.EllipticFundamentalGroupAction
import Wikipedia.HopfProblem.EllipticFundamentalGroupUniversalProperty

/-!
# The presentation of the actual elliptic fundamental groups

The proof of Theorem 5.4(iii), `tex/s6.tex` lines 17218--17268, identifies
the fundamental group with the affine group generated by lattice
translations and `h(x) = A x + v/m`. Its defining relations are
`h T_w h⁻¹ = T_(A w)` and `h^m = T_v`, together with the additive
translation relations. Here the exact universal property of that
presentation is proved for the actual affine deck subgroup and for the
actual surface and filling fundamental groups. The latter identification
uses the universal covering and the filling's strong deformation
retraction, not an assumed presentation of its fundamental group.
-/

noncomputable section

open scoped Matrix

namespace Wikipedia.HopfProblem.Elliptic

variable {H : Type*} [Group H]

/-- The actual affine subgroup has precisely the translation,
conjugation, and order relations: every realization of them in another
group extends to one and only one homomorphism. -/
theorem affineDeckGroup_presentation (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (τ : Multiplicative Lattice →* H) (k : H)
    (hkconj : ∀ w, k * τ (Multiplicative.ofAdd w) =
      τ (Multiplicative.ofAdd (j.matrix *ᵥ w)) * k)
    (hkpow : k ^ j.order = τ (Multiplicative.ofAdd v)) :
    ∃! F : AffineDeckGroup j v →* H,
      (∀ w, F (deckTranslationHom j v (Multiplicative.ofAdd w)) =
        τ (Multiplicative.ofAdd w)) ∧ F (deckGenerator j v) = k := by
  exact CyclicNormalForms.existsUnique_hom_of_normalForms
    (deckTranslationHom j v) (deckGenerator j v) j.order j.order_pos
    (latticeMonodromy j) v (deckGenerator_translation j v)
    (deckGenerator_pow_order j v hv.1) (deckNormalForm_bijective j v hv)
    τ k hkconj hkpow

/-- The marked translation homomorphism into the actual surface
fundamental group. The monodromy inversion convention is recorded in
`surfaceFundamentalGroupDeckEquiv_monodromy`. -/
def surfaceTranslationHom (j : Kind) (p : FixedPeriod j) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    Multiplicative Lattice →*
      FundamentalGroup (Surface j p v hv) (affineCoverProjection j p v hv y) :=
  (surfaceFundamentalGroupDeckEquiv j p v hv y).symm.toMonoidHom.comp
    (deckTranslationHom j v)

/-- The affine generator as an element of the actual surface
fundamental group, via the proved universal-cover monodromy equivalence. -/
def surfaceAffineGenerator (j : Kind) (p : FixedPeriod j) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    FundamentalGroup (Surface j p v hv) (affineCoverProjection j p v hv y) :=
  (surfaceFundamentalGroupDeckEquiv j p v hv y).symm (deckGenerator j v)

@[simp] theorem surfaceFundamentalGroupDeckEquiv_translation
    (j : Kind) (p : FixedPeriod j) (v : Lattice) (hv : AdmissibleTwist j v)
    (y : RealCoordinates) (w : Multiplicative Lattice) :
    surfaceFundamentalGroupDeckEquiv j p v hv y
        (surfaceTranslationHom j p v hv y w) = deckTranslationHom j v w :=
  (surfaceFundamentalGroupDeckEquiv j p v hv y).apply_symm_apply _

@[simp] theorem surfaceFundamentalGroupDeckEquiv_generator
    (j : Kind) (p : FixedPeriod j) (v : Lattice) (hv : AdmissibleTwist j v)
    (y : RealCoordinates) :
    surfaceFundamentalGroupDeckEquiv j p v hv y
        (surfaceAffineGenerator j p v hv y) = deckGenerator j v :=
  (surfaceFundamentalGroupDeckEquiv j p v hv y).apply_symm_apply _

theorem surfaceTranslationHom_injective (j : Kind) (p : FixedPeriod j)
    (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    Function.Injective (surfaceTranslationHom j p v hv y) :=
  (surfaceFundamentalGroupDeckEquiv j p v hv y).symm.injective.comp
    (deckTranslationHom_injective j v)

/-- The conjugation relation holds for the actual surface loops. -/
theorem surfaceAffineGenerator_translation (j : Kind) (p : FixedPeriod j)
    (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates) (w : Lattice) :
    surfaceAffineGenerator j p v hv y *
        surfaceTranslationHom j p v hv y (Multiplicative.ofAdd w) =
      surfaceTranslationHom j p v hv y (Multiplicative.ofAdd (j.matrix *ᵥ w)) *
        surfaceAffineGenerator j p v hv y := by
  apply (surfaceFundamentalGroupDeckEquiv j p v hv y).injective
  simpa only [map_mul, surfaceFundamentalGroupDeckEquiv_generator,
    surfaceFundamentalGroupDeckEquiv_translation, latticeMonodromy_apply] using
      deckGenerator_translation j v w

theorem surfaceAffineGenerator_conj_translation (j : Kind) (p : FixedPeriod j)
    (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates) (w : Lattice) :
    surfaceAffineGenerator j p v hv y *
        surfaceTranslationHom j p v hv y (Multiplicative.ofAdd w) *
        (surfaceAffineGenerator j p v hv y)⁻¹ =
      surfaceTranslationHom j p v hv y (Multiplicative.ofAdd (j.matrix *ᵥ w)) := by
  rw [surfaceAffineGenerator_translation, mul_inv_cancel_right]

/-- The elliptic power relation holds in the actual surface fundamental group. -/
theorem surfaceAffineGenerator_pow_order (j : Kind) (p : FixedPeriod j)
    (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    surfaceAffineGenerator j p v hv y ^ j.order =
      surfaceTranslationHom j p v hv y (Multiplicative.ofAdd v) := by
  apply (surfaceFundamentalGroupDeckEquiv j p v hv y).injective
  simpa only [map_pow, surfaceFundamentalGroupDeckEquiv_generator,
    surfaceFundamentalGroupDeckEquiv_translation] using deckGenerator_pow_order j v hv.1

/-- Every actual surface loop class has one and only one finite affine
normal form in these marked generators. -/
theorem surface_normalForm_bijective (j : Kind) (p : FixedPeriod j)
    (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    Function.Bijective (CyclicNormalForms.normalForm
      (surfaceTranslationHom j p v hv y) (surfaceAffineGenerator j p v hv y) j.order) := by
  have he : CyclicNormalForms.normalForm (surfaceTranslationHom j p v hv y)
      (surfaceAffineGenerator j p v hv y) j.order =
      (surfaceFundamentalGroupDeckEquiv j p v hv y).symm ∘ deckNormalForm j v := by
    funext a
    change (surfaceFundamentalGroupDeckEquiv j p v hv y).symm
        (deckTranslationHom j v (Multiplicative.ofAdd a.1)) *
        (surfaceFundamentalGroupDeckEquiv j p v hv y).symm (deckGenerator j v) ^ a.2.val =
      (surfaceFundamentalGroupDeckEquiv j p v hv y).symm
        (deckTranslationHom j v (Multiplicative.ofAdd a.1) * deckGenerator j v ^ a.2.val)
    rw [map_mul, map_pow]
  rw [he]
  exact (surfaceFundamentalGroupDeckEquiv j p v hv y).symm.bijective.comp
    (deckNormalForm_bijective j v hv)

/-- Exact presentation of the actual surface fundamental group. -/
theorem surfaceFundamentalGroup_presentation (j : Kind) (p : FixedPeriod j)
    (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates)
    (τ : Multiplicative Lattice →* H) (k : H)
    (hkconj : ∀ w, k * τ (Multiplicative.ofAdd w) =
      τ (Multiplicative.ofAdd (j.matrix *ᵥ w)) * k)
    (hkpow : k ^ j.order = τ (Multiplicative.ofAdd v)) :
    ∃! F : FundamentalGroup (Surface j p v hv)
        (affineCoverProjection j p v hv y) →* H,
      (∀ w, F (surfaceTranslationHom j p v hv y (Multiplicative.ofAdd w)) =
        τ (Multiplicative.ofAdd w)) ∧ F (surfaceAffineGenerator j p v hv y) = k := by
  exact CyclicNormalForms.existsUnique_hom_of_normalForms
    (surfaceTranslationHom j p v hv y) (surfaceAffineGenerator j p v hv y)
    j.order j.order_pos (latticeMonodromy j) v
    (surfaceAffineGenerator_translation j p v hv y)
    (surfaceAffineGenerator_pow_order j p v hv y) (surface_normalForm_bijective j p v hv y)
    τ k hkconj hkpow

/-- Translation loops in the actual filling, marked using the proved
strong deformation retraction and universal affine cover. -/
def fillingTranslationHom (j : Kind) (v : Lattice) (hv : AdmissibleTwist j v)
    (y : RealCoordinates) : Multiplicative Lattice →*
      FundamentalGroup (Filling j v hv)
        (centralFibreInclusion j v hv (affineCoverProjection j (centralPeriod j) v hv y)) :=
  (fillingFundamentalGroupDeckEquiv j v hv y).symm.toMonoidHom.comp (deckTranslationHom j v)

/-- The affine generator in the actual filling fundamental group. -/
def fillingAffineGenerator (j : Kind) (v : Lattice) (hv : AdmissibleTwist j v)
    (y : RealCoordinates) : FundamentalGroup (Filling j v hv)
      (centralFibreInclusion j v hv (affineCoverProjection j (centralPeriod j) v hv y)) :=
  (fillingFundamentalGroupDeckEquiv j v hv y).symm (deckGenerator j v)

@[simp] theorem fillingFundamentalGroupDeckEquiv_translation
    (j : Kind) (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates)
    (w : Multiplicative Lattice) :
    fillingFundamentalGroupDeckEquiv j v hv y (fillingTranslationHom j v hv y w) =
      deckTranslationHom j v w :=
  (fillingFundamentalGroupDeckEquiv j v hv y).apply_symm_apply _

@[simp] theorem fillingFundamentalGroupDeckEquiv_generator
    (j : Kind) (v : Lattice) (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    fillingFundamentalGroupDeckEquiv j v hv y (fillingAffineGenerator j v hv y) =
      deckGenerator j v :=
  (fillingFundamentalGroupDeckEquiv j v hv y).apply_symm_apply _

theorem fillingTranslationHom_injective (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    Function.Injective (fillingTranslationHom j v hv y) :=
  (fillingFundamentalGroupDeckEquiv j v hv y).symm.injective.comp
    (deckTranslationHom_injective j v)

theorem fillingAffineGenerator_translation (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) (w : Lattice) :
    fillingAffineGenerator j v hv y *
        fillingTranslationHom j v hv y (Multiplicative.ofAdd w) =
      fillingTranslationHom j v hv y (Multiplicative.ofAdd (j.matrix *ᵥ w)) *
        fillingAffineGenerator j v hv y := by
  apply (fillingFundamentalGroupDeckEquiv j v hv y).injective
  simpa only [map_mul, fillingFundamentalGroupDeckEquiv_generator,
    fillingFundamentalGroupDeckEquiv_translation, latticeMonodromy_apply] using
      deckGenerator_translation j v w

theorem fillingAffineGenerator_conj_translation (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) (w : Lattice) :
    fillingAffineGenerator j v hv y *
        fillingTranslationHom j v hv y (Multiplicative.ofAdd w) *
        (fillingAffineGenerator j v hv y)⁻¹ =
      fillingTranslationHom j v hv y (Multiplicative.ofAdd (j.matrix *ᵥ w)) := by
  rw [fillingAffineGenerator_translation, mul_inv_cancel_right]

theorem fillingAffineGenerator_pow_order (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    fillingAffineGenerator j v hv y ^ j.order =
      fillingTranslationHom j v hv y (Multiplicative.ofAdd v) := by
  apply (fillingFundamentalGroupDeckEquiv j v hv y).injective
  simpa only [map_pow, fillingFundamentalGroupDeckEquiv_generator,
    fillingFundamentalGroupDeckEquiv_translation] using deckGenerator_pow_order j v hv.1

theorem filling_normalForm_bijective (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates) :
    Function.Bijective (CyclicNormalForms.normalForm
      (fillingTranslationHom j v hv y) (fillingAffineGenerator j v hv y) j.order) := by
  have he : CyclicNormalForms.normalForm (fillingTranslationHom j v hv y)
      (fillingAffineGenerator j v hv y) j.order =
      (fillingFundamentalGroupDeckEquiv j v hv y).symm ∘ deckNormalForm j v := by
    funext a
    change (fillingFundamentalGroupDeckEquiv j v hv y).symm
        (deckTranslationHom j v (Multiplicative.ofAdd a.1)) *
        (fillingFundamentalGroupDeckEquiv j v hv y).symm (deckGenerator j v) ^ a.2.val =
      (fillingFundamentalGroupDeckEquiv j v hv y).symm
        (deckTranslationHom j v (Multiplicative.ofAdd a.1) * deckGenerator j v ^ a.2.val)
    rw [map_mul, map_pow]
  rw [he]
  exact (fillingFundamentalGroupDeckEquiv j v hv y).symm.bijective.comp
    (deckNormalForm_bijective j v hv)

/-- Exact presentation of the actual elliptic filling fundamental group,
as required for the cap groups in Lemma 7.3(i). -/
theorem fillingFundamentalGroup_presentation (j : Kind) (v : Lattice)
    (hv : AdmissibleTwist j v) (y : RealCoordinates)
    (τ : Multiplicative Lattice →* H) (k : H)
    (hkconj : ∀ w, k * τ (Multiplicative.ofAdd w) =
      τ (Multiplicative.ofAdd (j.matrix *ᵥ w)) * k)
    (hkpow : k ^ j.order = τ (Multiplicative.ofAdd v)) :
    ∃! F : FundamentalGroup (Filling j v hv)
        (centralFibreInclusion j v hv (affineCoverProjection j (centralPeriod j) v hv y)) →* H,
      (∀ w, F (fillingTranslationHom j v hv y (Multiplicative.ofAdd w)) =
        τ (Multiplicative.ofAdd w)) ∧ F (fillingAffineGenerator j v hv y) = k := by
  exact CyclicNormalForms.existsUnique_hom_of_normalForms
    (fillingTranslationHom j v hv y) (fillingAffineGenerator j v hv y)
    j.order j.order_pos (latticeMonodromy j) v (fillingAffineGenerator_translation j v hv y)
    (fillingAffineGenerator_pow_order j v hv y) (filling_normalForm_bijective j v hv y)
    τ k hkconj hkpow

/-- The presentation specializes to the source's two explicit main
fillings, with their admissibility already proved. -/
theorem mainFillingFundamentalGroup_presentation (j : Kind) (y : RealCoordinates)
    (τ : Multiplicative Lattice →* H) (k : H)
    (hkconj : ∀ w, k * τ (Multiplicative.ofAdd w) =
      τ (Multiplicative.ofAdd (j.matrix *ᵥ w)) * k)
    (hkpow : k ^ j.order = τ (Multiplicative.ofAdd j.twist)) :
    ∃! F : FundamentalGroup (MainFilling j)
        (centralFibreInclusion j j.twist (mainTwist_admissible j)
          (affineCoverProjection j (centralPeriod j) j.twist (mainTwist_admissible j) y)) →* H,
      (∀ w, F (fillingTranslationHom j j.twist (mainTwist_admissible j) y
          (Multiplicative.ofAdd w)) = τ (Multiplicative.ofAdd w)) ∧
        F (fillingAffineGenerator j j.twist (mainTwist_admissible j) y) = k :=
  fillingFundamentalGroup_presentation j j.twist (mainTwist_admissible j) y τ k hkconj hkpow

end Wikipedia.HopfProblem.Elliptic
