import Wikipedia.HopfProblem.HigherHurewiczCubeTriangulationSort
import Mathlib.GroupTheory.Perm.Support

/-!
# Induction on permutations preserving a finite tuple

A nonidentity value-preserving permutation can be shortened by swapping
a moved point with its image. These two points have equal tuple values.
The number of moved points strictly decreases, giving an induction with
no hypothesis about a pre-existing transposition factorization.
-/

noncomputable section

namespace Wikipedia.HopfProblem.HigherHurewicz.CubeTriangulation

variable {ι β : Type*} [DecidableEq ι]

private theorem label_swap_apply (v : ι → β) {a b : ι} (hab : v a = v b) (z : ι) :
    v (Equiv.swap a b z) = v z := by
  by_cases hza : z = a
  · subst z
    simpa only [Equiv.swap_apply_left] using hab.symm
  by_cases hzb : z = b
  · subst z
    simpa only [Equiv.swap_apply_right] using hab
  rw [Equiv.swap_apply_of_ne_of_ne hza hzb]

/-- Value-preserving permutations are generated by swaps of equal-value positions. -/
theorem valuePreservingPermutation_induction [Finite ι] (v : ι → β)
    {P : Equiv.Perm ι → Prop} (hone : P 1)
    (hswap : ∀ (r : Equiv.Perm ι) (a b : ι), v a = v b →
      (∀ i, v (r i) = v i) → P r → P (Equiv.swap a b * r))
    (r : Equiv.Perm ι) (hr : ∀ i, v (r i) = v i) : P r := by
  classical
  let _ := Fintype.ofFinite ι
  suffices h : ∀ k : ℕ, ∀ q : Equiv.Perm ι,
      q.support.card = k → (∀ i, v (q i) = v i) → P q from h _ r rfl hr
  intro k
  induction k using Nat.strong_induction_on with
  | h k ih =>
    intro q hq hvalues
    by_cases hqone : q = 1
    · simpa only [hqone] using hone
    have hmoved : ∃ a, q a ≠ a := by
      by_contra! hn
      exact hqone (Equiv.ext hn)
    obtain ⟨a, ha⟩ := hmoved
    let q' := Equiv.swap a (q a) * q
    have hlt : q'.support.card < k := by
      rw [← hq]
      exact Equiv.Perm.card_support_swap_mul ha
    have hvalues' : ∀ i, v (q' i) = v i := by
      intro i
      change v (Equiv.swap a (q a) (q i)) = v i
      exact (label_swap_apply v (hvalues a).symm (q i)).trans (hvalues i)
    have hstep := hswap q' a (q a) (hvalues a).symm hvalues'
      (ih q'.support.card hlt q' rfl hvalues')
    simpa only [q', Equiv.swap_mul_self_mul] using hstep

/-- A function invariant under every equal-value swap is constant on the
value-preserving permutations. -/
theorem eq_of_value_preserving_swaps [Finite ι] (v : ι → β) {A : Type*}
    (G : Equiv.Perm ι → A)
    (hswap : ∀ (r : Equiv.Perm ι), (∀ i, v (r i) = v i) →
      ∀ a b, v a = v b → G r = G (Equiv.swap a b * r))
    (r : Equiv.Perm ι) (hr : ∀ i, v (r i) = v i) : G 1 = G r :=
  valuePreservingPermutation_induction v (P := fun q => G 1 = G q) rfl
    (fun q a b hab hq ih => ih.trans (hswap q hq a b hab)) r hr

end Wikipedia.HopfProblem.HigherHurewicz.CubeTriangulation
