import Wikipedia.HopfProblem.HolomorphicMeromorphicPolarAlgebraBasic
import Wikipedia.HopfProblem.HolomorphicMeromorphicPolarAlgebraReduced
import Wikipedia.HopfProblem.HolomorphicMeromorphicPolarAlgebraUniqueness

/-!
# Principality of denominator ideals in a unique factorization domain

The actual denominator ideal of a fraction is generated by its reduced
denominator. This is a statement about these particular ideals, not an
assertion that every ideal of the domain is principal. Reduced pairs are
unique up to the same unit in both coordinates.

Unique factorization remains an explicit generic algebraic hypothesis.
No factoriality of an analytic stalk or global polar-divisor construction
is asserted in this module.
-/

noncomputable section

namespace Wikipedia.HopfProblem.HolomorphicMeromorphic.PolarAlgebra

variable (R : Type*) [CommRing R]
  {K : Type*} [Field K] [Algebra R K]

/-- A generator of the denominator ideal is a unit exactly when the
fraction is represented by an element of the original ring. -/
theorem denominator_generator_isUnit_iff (x : K) {q : R}
    (hq : denominatorIdeal R x = Ideal.span ({q} : Set R)) :
    IsUnit q ↔ ∃ b : R, algebraMap R K b = x := by
  rw [← Ideal.span_singleton_eq_top, ← hq, denominatorIdeal_eq_top_iff]

variable [IsDomain R]

/-- Any two generators of the same actual denominator ideal are associated. -/
theorem denominator_generators_associated (x : K) {q q' : R}
    (hq : denominatorIdeal R x = Ideal.span ({q} : Set R))
    (hq' : denominatorIdeal R x = Ideal.span ({q'} : Set R)) :
    Associated q q' :=
  Ideal.span_singleton_eq_span_singleton.mp (hq.symm.trans hq')

variable [IsFractionRing R K]

/-- A generator of a fraction's denominator ideal cannot vanish. -/
theorem denominator_generator_ne_zero (x : K) {q : R}
    (hq : denominatorIdeal R x = Ideal.span ({q} : Set R)) : q ≠ 0 := by
  intro hzero
  apply denominatorIdeal_ne_bot R x
  simpa only [hzero, Ideal.span_singleton_zero] using hq

variable [UniqueFactorizationMonoid R]

/-- The ideal is generated by the existing reduced denominator chosen
by Mathlib's fraction-ring construction. -/
theorem denominatorIdeal_eq_span_den (x : K) :
    denominatorIdeal R x = Ideal.span ({(IsFractionRing.den R x : R)} : Set R) := by
  calc
    denominatorIdeal R x = denominatorIdeal R
        (algebraMap R K (IsFractionRing.num R x) /
          algebraMap R K (IsFractionRing.den R x)) :=
      congrArg (denominatorIdeal R) (IsFractionRing.mk'_num_den' R x).symm
    _ = _ := denominatorIdeal_eq_span_of_reduced R
      (IsFractionRing.num R x) (IsFractionRing.den R x)
      (nonZeroDivisors.ne_zero (IsFractionRing.den R x).property)
      (IsFractionRing.num_den_reduced R x)

/-- The canonical reduced denominator divides exactly the clearing elements. -/
theorem mem_denominatorIdeal_iff_den_dvd (x : K) (a : R) :
    a ∈ denominatorIdeal R x ↔ (IsFractionRing.den R x : R) ∣ a := by
  rw [denominatorIdeal_eq_span_den, Ideal.mem_span_singleton]

/-- Denominator ideals, specifically, are principal in a UFD. -/
theorem denominatorIdeal_isPrincipal (x : K) : (denominatorIdeal R x).IsPrincipal :=
  ⟨(IsFractionRing.den R x : R), denominatorIdeal_eq_span_den R x⟩

/-- Principality together with the nonvanishing required of a denominator. -/
theorem exists_nonzero_generator_denominatorIdeal (x : K) :
    ∃ q : R, q ≠ 0 ∧ denominatorIdeal R x = Ideal.span ({q} : Set R) :=
  ⟨IsFractionRing.den R x, nonZeroDivisors.ne_zero (IsFractionRing.den R x).property,
    denominatorIdeal_eq_span_den R x⟩

/-- A reduced pair and its actual denominator-ideal generator can be
chosen together, with no condition on the numerator. -/
theorem exists_reduced_denominator_generator (x : K) :
    ∃ p q : R, q ≠ 0 ∧ IsRelPrime p q ∧
      algebraMap R K p / algebraMap R K q = x ∧
      denominatorIdeal R x = Ideal.span ({q} : Set R) := by
  obtain ⟨p, q, hq, hpq, he⟩ := exists_reduced_representation R x
  refine ⟨p, q, hq, hpq, he, ?_⟩
  rw [← he]
  exact denominatorIdeal_eq_span_of_reduced R p q hq hpq

theorem denominatorIdeal_eq_top_iff_isUnit_den (x : K) :
    denominatorIdeal R x = ⊤ ↔ IsUnit (IsFractionRing.den R x : R) := by
  rw [denominatorIdeal_eq_span_den, Ideal.span_singleton_eq_top]

end Wikipedia.HopfProblem.HolomorphicMeromorphic.PolarAlgebra
