import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.UniqueFactorizationDomain.Basic
import Mathlib.RingTheory.Ideal.IsPrincipal

/-!
# The denominator ideal of a fraction-field element

The denominator ideal consists literally of the ring elements that clear a
given fraction's denominator. It is an actual ideal and is nonzero for every
fraction-field element. In a unique factorization domain, the ideal of a
reduced fraction `p / q` is exactly the principal ideal generated by `q`.

This file is generic algebra. In particular, it does not assert unique
factorization for a holomorphic stalk or any analytic polar-divisor result.
-/

noncomputable section

namespace Wikipedia.HopfProblem.HolomorphicMeromorphic.PolarAlgebra

variable (R : Type*) [CommRing R]
  {K : Type*} [Field K] [Algebra R K]

/-- The actual ring elements whose product with the fraction lies back
in the image of the original ring. -/
def denominatorIdeal (x : K) : Ideal R where
  carrier := {a : R | ∃ b : R, algebraMap R K a * x = algebraMap R K b}
  zero_mem' := ⟨0, by simp only [map_zero, zero_mul]⟩
  add_mem' := by
    rintro a b ⟨p, hp⟩ ⟨q, hq⟩
    refine ⟨p + q, ?_⟩
    rw [map_add, add_mul, hp, hq, map_add]
  smul_mem' := by
    rintro r a ⟨b, hb⟩
    refine ⟨r * b, ?_⟩
    change algebraMap R K (r * a) * x = algebraMap R K (r * b)
    rw [map_mul, map_mul, mul_assoc, hb]

@[simp] theorem mem_denominatorIdeal_iff (x : K) (a : R) :
    a ∈ denominatorIdeal R x ↔
      ∃ b : R, algebraMap R K a * x = algebraMap R K b := Iff.rfl

/-- The unit denominator belongs precisely when the fraction comes from
an element of the original ring. -/
theorem one_mem_denominatorIdeal_iff (x : K) :
    (1 : R) ∈ denominatorIdeal R x ↔ ∃ b : R, algebraMap R K b = x := by
  simp only [mem_denominatorIdeal_iff, map_one, one_mul, eq_comm]

theorem denominatorIdeal_eq_top_iff (x : K) :
    denominatorIdeal R x = ⊤ ↔ ∃ b : R, algebraMap R K b = x := by
  rw [Ideal.eq_top_iff_one, one_mem_denominatorIdeal_iff]

@[simp] theorem denominatorIdeal_algebraMap (b : R) :
    denominatorIdeal R (algebraMap R K b) = ⊤ :=
  (denominatorIdeal_eq_top_iff R _).mpr ⟨b, rfl⟩

@[simp] theorem denominatorIdeal_zero : denominatorIdeal R (0 : K) = ⊤ := by
  rw [← map_zero (algebraMap R K)]
  exact denominatorIdeal_algebraMap R 0

variable [IsDomain R] [IsFractionRing R K]

omit [IsDomain R] in
/-- Any displayed nonzero fraction denominator clears that fraction. -/
theorem denominator_mem_denominatorIdeal_div (p q : R) (hq : q ≠ 0) :
    q ∈ denominatorIdeal R (algebraMap R K p / algebraMap R K q) := by
  have hqK : algebraMap R K q ≠ 0 :=
    (map_ne_zero_iff (algebraMap R K) (IsFractionRing.injective R K)).mpr hq
  refine ⟨p, ?_⟩
  rw [mul_div_cancel₀ _ hqK]

/-- Every fraction-field element has a nonzero clearing denominator. -/
theorem exists_nonzero_mem_denominatorIdeal (x : K) :
    ∃ a : R, a ≠ 0 ∧ a ∈ denominatorIdeal R x := by
  obtain ⟨p, q, hq, rfl⟩ := IsFractionRing.div_surjective R x
  have hq0 : q ≠ 0 := nonZeroDivisors.ne_zero hq
  exact ⟨q, hq0, denominator_mem_denominatorIdeal_div R p q hq0⟩

theorem denominatorIdeal_ne_bot (x : K) : denominatorIdeal R x ≠ ⊥ := by
  obtain ⟨a, ha, hamem⟩ := exists_nonzero_mem_denominatorIdeal R x
  intro hbot
  rw [hbot, Ideal.mem_bot] at hamem
  exact ha hamem

omit [IsDomain R] in
/-- Clearing a displayed fraction is exactly a divisibility condition
in the original domain, with no factorization assumption. -/
theorem mem_denominatorIdeal_div_iff (p q : R) (hq : q ≠ 0) (a : R) :
    a ∈ denominatorIdeal R (algebraMap R K p / algebraMap R K q) ↔ q ∣ a * p := by
  have hqK : algebraMap R K q ≠ 0 :=
    (map_ne_zero_iff (algebraMap R K) (IsFractionRing.injective R K)).mpr hq
  constructor
  · rintro ⟨b, hb⟩
    have he : algebraMap R K (a * p) = algebraMap R K (b * q) := by
      rw [map_mul, map_mul]
      apply (div_eq_iff hqK).mp
      simpa only [mul_div_assoc] using hb
    have heR := IsFractionRing.injective R K he
    exact ⟨b, heR.trans (mul_comm b q)⟩
  · rintro ⟨b, hb⟩
    refine ⟨b, ?_⟩
    rw [← mul_div_assoc]
    apply (div_eq_iff hqK).mpr
    have he := congrArg (algebraMap R K) hb
    simp only [map_mul] at he
    exact he.trans (mul_comm _ _)

variable [UniqueFactorizationMonoid R]

omit [IsDomain R] in
/-- The denominator ideal of a reduced fraction is literally `(q)`. -/
theorem denominatorIdeal_eq_span_of_reduced (p q : R) (hq : q ≠ 0)
    (hpq : IsRelPrime p q) :
    denominatorIdeal R (algebraMap R K p / algebraMap R K q) =
      Ideal.span ({q} : Set R) := by
  ext a
  rw [mem_denominatorIdeal_div_iff R p q hq, Ideal.mem_span_singleton]
  exact ⟨hpq.symm.dvd_of_dvd_mul_right, fun h => dvd_mul_of_dvd_left h p⟩

end Wikipedia.HopfProblem.HolomorphicMeromorphic.PolarAlgebra
