import Wikipedia.HopfProblem.Lattice
import Mathlib.Algebra.Group.TypeTags.Basic
import Mathlib.Algebra.Group.End
import Mathlib.GroupTheory.Subgroup.Center

/-!
# The lattice relations forced by the actual cusp kernel

Killing the last two coordinate axes and closing these relations under
the first elliptic conjugation kills the whole kernel of `γ`.  Hence the
lattice image is generated by the image of `ε`.  The actual two matrix
conjugation laws make this remaining image commute with both meridians.
These are group-theoretic consequences of the displayed relations, not
assumptions about a normal closure or about the resulting fundamental group.
-/

namespace Wikipedia.HopfProblem.LatticeCuspNormalClosure

open scoped Matrix

/-- The second coordinate basis vector of the source lattice. -/
def uHat : Lattice := ![0, 1, 0, 0]

/-- The third coordinate basis vector killed by the cusp relation. -/
def wHat : Lattice := ![0, 0, 1, 0]

/-- The fourth coordinate basis vector killed by the cusp relation. -/
def deltaHat : Lattice := ![0, 0, 0, 1]

/-- The first elliptic conjugation supplies the missing second coordinate. -/
theorem first_matrix_wHat : A₁ *ᵥ wHat = uHat - wHat := by decide

variable {G : Type*} [Group G] (φ : Multiplicative Lattice →* G)

theorem image_wHat_eq_one
    (hc : ∀ v : Lattice, v 0 = 0 → v 1 = 0 → φ (Multiplicative.ofAdd v) = 1) :
    φ (Multiplicative.ofAdd wHat) = 1 := hc wHat rfl rfl

theorem image_deltaHat_eq_one
    (hc : ∀ v : Lattice, v 0 = 0 → v 1 = 0 → φ (Multiplicative.ofAdd v) = 1) :
    φ (Multiplicative.ofAdd deltaHat) = 1 := hc deltaHat rfl rfl

section FirstConjugation

variable (x : G)
  (hx : ∀ v : Lattice, x * φ (Multiplicative.ofAdd v) * x⁻¹ =
    φ (Multiplicative.ofAdd (A₁ *ᵥ v)))
  (hc : ∀ v : Lattice, v 0 = 0 → v 1 = 0 → φ (Multiplicative.ofAdd v) = 1)

include hx hc

/-- Conjugating the killed third coordinate also kills the second coordinate. -/
theorem image_uHat_eq_one : φ (Multiplicative.ofAdd uHat) = 1 := by
  have h := hx wHat
  rw [first_matrix_wHat, ofAdd_sub, map_div,
    image_wHat_eq_one φ hc] at h
  simpa only [mul_one, mul_inv_cancel, div_one] using h.symm

/-- Every vector in the actual kernel of `γ` is killed. -/
theorem image_eq_one_of_gamma_eq_zero (v : Lattice) (hv : γ v = 0) :
    φ (Multiplicative.ofAdd v) = 1 := by
  have hv₀ : v 0 = 0 := hv
  have hrest := hc (v - v 1 • uHat) (by simp [uHat, hv₀]) (by simp [uHat])
  have hu : φ (Multiplicative.ofAdd (v 1 • uHat)) = 1 := by
    rw [ofAdd_zsmul, map_zpow, image_uHat_eq_one φ x hx hc, one_zpow]
  simpa only [ofAdd_sub, map_div, hu, div_one] using hrest

/-- The surviving lattice image is precisely the displayed power of `ε`'s image. -/
theorem image_eq_zpow_gamma (v : Lattice) :
    φ (Multiplicative.ofAdd v) = φ (Multiplicative.ofAdd ε) ^ γ v := by
  have hk : γ (v - γ v • ε) = 0 := by simp [γ, ε]
  have h := image_eq_one_of_gamma_eq_zero φ x hx hc (v - γ v • ε) hk
  rw [ofAdd_sub, map_div, ofAdd_zsmul, map_zpow] at h
  exact div_eq_one.mp h

/-- The two invariant twist vectors have the same image after the cusp relations. -/
theorem image_epsilon_prime_eq :
    φ (Multiplicative.ofAdd ε') = φ (Multiplicative.ofAdd ε) := by
  simpa only [γ_ε', zpow_one] using image_eq_zpow_gamma φ x hx hc ε'

end FirstConjugation

/-- The invariant first twist already commutes with the first meridian. -/
theorem image_epsilon_commute_first (x : G)
    (hx : ∀ v : Lattice, x * φ (Multiplicative.ofAdd v) * x⁻¹ =
      φ (Multiplicative.ofAdd (A₁ *ᵥ v))) :
    Commute (φ (Multiplicative.ofAdd ε)) x := by
  have h := hx ε
  rw [A₁_fixes_ε] at h
  exact ((mul_inv_eq_iff_eq_mul).mp h).symm

/-- The second invariant twist becomes `ε`, so the second meridian commutes too. -/
theorem image_epsilon_commute_second (x y : G)
    (hx : ∀ v : Lattice, x * φ (Multiplicative.ofAdd v) * x⁻¹ =
      φ (Multiplicative.ofAdd (A₁ *ᵥ v)))
    (hy : ∀ v : Lattice, y * φ (Multiplicative.ofAdd v) * y⁻¹ =
      φ (Multiplicative.ofAdd (A₂ *ᵥ v)))
    (hc : ∀ v : Lattice, v 0 = 0 → v 1 = 0 → φ (Multiplicative.ofAdd v) = 1) :
    Commute (φ (Multiplicative.ofAdd ε)) y := by
  have h := hy ε'
  rw [A₂_fixes_ε', image_epsilon_prime_eq φ x hx hc] at h
  exact ((mul_inv_eq_iff_eq_mul).mp h).symm

/-- Images of lattice elements commute because the original lattice is abelian. -/
theorem image_epsilon_commute_lattice (v : Multiplicative Lattice) :
    Commute (φ (Multiplicative.ofAdd ε)) (φ v) := by
  change φ (Multiplicative.ofAdd ε) * φ v = φ v * φ (Multiplicative.ofAdd ε)
  rw [← map_mul, ← map_mul, mul_comm]

/-- If the lattice and two meridians determine homomorphisms, the surviving
lattice generator lies in the center of the entire group. -/
theorem image_epsilon_mem_center_of_hom_ext (x y : G)
    (hx : ∀ v : Lattice, x * φ (Multiplicative.ofAdd v) * x⁻¹ =
      φ (Multiplicative.ofAdd (A₁ *ᵥ v)))
    (hy : ∀ v : Lattice, y * φ (Multiplicative.ofAdd v) * y⁻¹ =
      φ (Multiplicative.ofAdd (A₂ *ᵥ v)))
    (hc : ∀ v : Lattice, v 0 = 0 → v 1 = 0 → φ (Multiplicative.ofAdd v) = 1)
    (hext : ∀ f g : G →* G,
      (∀ v : Multiplicative Lattice, f (φ v) = g (φ v)) →
      f x = g x → f y = g y → f = g) :
    φ (Multiplicative.ofAdd ε) ∈ Subgroup.center G := by
  let a := φ (Multiplicative.ofAdd ε)
  have hconj : (MulAut.conj a).toMonoidHom = MonoidHom.id G := by
    apply hext
    · intro v
      change a * φ v * a⁻¹ = φ v
      rw [(image_epsilon_commute_lattice φ v).eq, mul_inv_cancel_right]
    · change a * x * a⁻¹ = x
      rw [(image_epsilon_commute_first φ x hx).eq, mul_inv_cancel_right]
    · change a * y * a⁻¹ = y
      rw [(image_epsilon_commute_second φ x y hx hy hc).eq, mul_inv_cancel_right]
  apply Subgroup.mem_center_iff.mpr
  intro g
  have h : a * g * a⁻¹ = g := DFunLike.congr_fun hconj g
  exact ((mul_inv_eq_iff_eq_mul).mp h).symm

end Wikipedia.HopfProblem.LatticeCuspNormalClosure
