import Wikipedia.HopfProblem.OrbitPairDualSubdivisionInitialEmbedding
import Mathlib.CategoryTheory.Limits.Types.Pushouts

/-!
# Detecting the zeroth face in a generated simplicial subcomplex

An operator factors through the zeroth face exactly when it omits vertex
zero. If a characteristic simplex is injective on parameters containing
zero, membership in the subcomplex generated by its zeroth face is
detected by this same condition.
-/

noncomputable section

universe u

open CategoryTheory CategoryTheory.Limits Simplicial

namespace Wikipedia.HopfProblem.OrbitPair.InitialFace

def InitialInjective {X : SSet.{u}} {n : ℕ} (z : X _⦋n⦌) : Prop :=
  ∀ (l : ℕ) (f g : ⦋l⦌ ⟶ ⦋n⦌), f.toOrderHom 0 = 0 →
    X.map f.op z = X.map g.op z → f = g

theorem comp_delta_zero_ne {l n : ℕ} (f : ⦋l⦌ ⟶ ⦋n⦌) :
    (f ≫ SimplexCategory.δ (0 : Fin (n + 2))).toOrderHom 0 ≠ 0 := by
  change (0 : Fin (n + 2)).succAbove (f.toOrderHom 0) ≠ 0
  exact Fin.succAbove_ne _ _

theorem factor_delta_zero {l n : ℕ} (f : ⦋l⦌ ⟶ ⦋n + 1⦌) (hf : f.toOrderHom 0 ≠ 0) :
    ∃ g : ⦋l⦌ ⟶ ⦋n⦌, g ≫ SimplexCategory.δ 0 = f := by
  obtain ⟨g, hg⟩ := SimplexCategory.eq_comp_δ_of_not_surjective' f 0 (by
    intro i hi
    have hle := f.toOrderHom.monotone (Fin.zero_le i)
    rw [hi] at hle
    exact hf (le_antisymm hle (Fin.zero_le _)))
  exact ⟨g, hg.symm⟩

theorem std_mem_range_delta_zero_iff {l n : ℕ}
    (t : (SSet.stdSimplex.{u}.obj ⦋n + 1⦌) _⦋l⦌) :
    t ∈ Set.range ((SSet.stdSimplex.δ (0 : Fin (n + 2))).app (Opposite.op ⦋l⦌)) ↔
      (SSet.stdSimplex.objEquiv t).toOrderHom 0 ≠ 0 := by
  constructor
  · rintro ⟨s, rfl⟩
    exact comp_delta_zero_ne (SSet.stdSimplex.objEquiv s)
  · intro ht
    obtain ⟨g, hg⟩ := factor_delta_zero (SSet.stdSimplex.objEquiv t) ht
    refine ⟨SSet.stdSimplex.objEquiv.symm g, ?_⟩
    apply SSet.stdSimplex.objEquiv.injective
    exact hg

variable {X : SSet.{u}} {n : ℕ} (z : X _⦋n + 1⦌)

theorem map_mem_initialFace_iff (hz : InitialInjective z) {l : ℕ}
    (f : ⦋l⦌ ⟶ ⦋n + 1⦌) :
    X.map f.op z ∈ (SSet.Subcomplex.ofSimplex (X.δ 0 z)).obj (Opposite.op ⦋l⦌) ↔
      f.toOrderHom 0 ≠ 0 := by
  constructor
  · intro h hf
    obtain ⟨g, hg⟩ := (SSet.Subcomplex.mem_ofSimplex_obj_iff (X.δ 0 z) (X.map f.op z)).mp h
    have he : X.map f.op z = X.map (g ≫ SimplexCategory.δ 0).op z :=
      hg.symm.trans (Functor.map_comp_apply X (SimplexCategory.δ 0).op g.op z).symm
    have hfg := hz l f (g ≫ SimplexCategory.δ 0) hf he
    exact comp_delta_zero_ne g (hfg ▸ hf)
  · intro hf
    obtain ⟨g, rfl⟩ := factor_delta_zero f hf
    apply (SSet.Subcomplex.mem_ofSimplex_obj_iff (X.δ 0 z) _).mpr
    exact ⟨g, (Functor.map_comp_apply X (SimplexCategory.δ 0).op g.op z).symm⟩

def inclusion : (SSet.Subcomplex.ofSimplex (X.δ 0 z) : SSet) ⟶
    (SSet.Subcomplex.ofSimplex z : SSet) :=
  SSet.Subcomplex.homOfLE (SSet.Subcomplex.ofSimplex_map_le (SimplexCategory.δ 0) z)

instance inclusion_mono : Mono (inclusion z) :=
  inferInstanceAs (Mono (SSet.Subcomplex.homOfLE
    (SSet.Subcomplex.ofSimplex_map_le (SimplexCategory.δ 0) z)))

theorem square : SSet.Subcomplex.toOfSimplex (X.δ 0 z) ≫ inclusion z =
    SSet.stdSimplex.δ 0 ≫ SSet.Subcomplex.toOfSimplex z := by
  apply (cancel_mono (SSet.Subcomplex.ofSimplex z).ι).mp
  change SSet.yonedaEquiv.symm (X.δ 0 z) =
    SSet.stdSimplex.δ 0 ≫ SSet.yonedaEquiv.symm z
  exact (SSet.yonedaEquiv_symm_naturality_left (SimplexCategory.δ 0) z).symm

end Wikipedia.HopfProblem.OrbitPair.InitialFace
