import Wikipedia.HopfProblem.OrbitPairSubdivisionColimit
import Wikipedia.HopfProblem.OrbitPairDualSubdivision

/-!
# Exact cell identifications in native ordinary and dual subdivision

The equivalence relation generated by simplex operators accounts for all
identifications in every degree of the actual left Kan extension. This
provides a native starting point for carrier and regularity arguments.
-/

noncomputable section

universe u

open CategoryTheory CategoryTheory.Limits Simplicial

namespace Wikipedia.HopfProblem.OrbitPair.SubdivisionParameters

open SubdivisionColimit

variable (A : SimplexCategory ⥤ SSet.{u}) (L : SSet.{u} ⥤ SSet.{u})
    (α : A ⟶ SSet.stdSimplex.{u} ⋙ L) (X : SSet.{u}) (k : ℕ)

abbrev Parameters := Σ a : (Σ n : ℕ, X _⦋n⦌), (A.obj ⦋a.1⦌) _⦋k⦌

def projection (p : Parameters A X k) : (L.obj X) _⦋k⦌ :=
  (cellMap A L α X p.1.1 p.1.2).app (Opposite.op ⦋k⦌) p.2

theorem projection_surjective [SSet.stdSimplex.{u}.HasPointwiseLeftKanExtension A]
    [L.IsLeftKanExtension α] : Function.Surjective (projection A L α X k) := by
  intro y
  obtain ⟨n, x, t, ht⟩ := exists_cell A L α X k y
  exact ⟨⟨⟨n, x⟩, t⟩, ht⟩

inductive Glue : Parameters A X k → Parameters A X k → Prop where
  | of_map (m n : ℕ) (f : ⦋m⦌ ⟶ ⦋n⦌) (x : X _⦋n⦌) (t : (A.obj ⦋m⦌) _⦋k⦌) :
      Glue ⟨⟨m, X.map f.op x⟩, t⟩
        ⟨⟨n, x⟩, (A.map f).app (Opposite.op ⦋k⦌) t⟩

theorem glue_projection_eq {a b : Parameters A X k} (h : Glue A X k a b) :
    projection A L α X k a = projection A L α X k b := by
  cases h with
  | of_map m n f x t =>
    exact congrArg (fun g ↦ g.app (Opposite.op ⦋k⦌) t) (cellMap_operator A L α X m n f x)

theorem eqvGen_projection_eq {a b : Parameters A X k}
    (h : Relation.EqvGen (Glue A X k) a b) :
    projection A L α X k a = projection A L α X k b := by
  induction h with
  | rel a b h => exact glue_projection_eq A L α X k h
  | refl => rfl
  | symm a b h ih => exact ih.symm
  | trans a b c hab hbc ihab ihbc => exact ihab.trans ihbc

local instance : Category.{0} (CostructuredArrow SSet.stdSimplex.{u} X) :=
  inferInstanceAs (Category.{0} (CostructuredArrow uliftYoneda.{u} X))

def rawDiagram := (CostructuredArrow.proj SSet.stdSimplex.{u} X ⋙ A) ⋙
  SSet.evaluation.obj (Opposite.op ⦋k⦌)

def rawToParameters (a : Σ j, (rawDiagram A X k).obj j) : Parameters A X k :=
  ⟨⟨a.1.left.len, SSet.yonedaEquiv a.1.hom⟩, a.2⟩

def parametersToRaw (a : Parameters A X k) : Σ j, (rawDiagram A X k).obj j :=
  ⟨CostructuredArrow.mk (SSet.yonedaEquiv.symm a.1.2), a.2⟩

theorem rawToParameters_parametersToRaw (a : Parameters A X k) :
    rawToParameters A X k (parametersToRaw A X k a) = a := by
  rcases a with ⟨⟨n, x⟩, t⟩
  change (⟨⟨n, SSet.yonedaEquiv (SSet.yonedaEquiv.symm x)⟩, t⟩ : Parameters A X k) = _
  rw [Equiv.apply_symm_apply]

theorem raw_relation_glue {a b : Σ j, (rawDiagram A X k).obj j}
    (h : (rawDiagram A X k).ColimitTypeRel a b) :
    Glue A X k (rawToParameters A X k a) (rawToParameters A X k b) := by
  rcases a with ⟨a, t⟩
  rcases b with ⟨b, v⟩
  change ∃ f : a ⟶ b, v = (rawDiagram A X k).map f t at h
  obtain ⟨f, rfl⟩ := h
  have hx : X.map f.left.op (SSet.yonedaEquiv b.hom) = SSet.yonedaEquiv a.hom := by
    rw [SSet.yonedaEquiv_naturality, CostructuredArrow.w f]
  change Glue A X k ⟨⟨a.left.len, SSet.yonedaEquiv a.hom⟩, t⟩
    ⟨⟨b.left.len, SSet.yonedaEquiv b.hom⟩, (A.map f.left).app (Opposite.op ⦋k⦌) t⟩
  rw [← hx]
  exact Glue.of_map _ _ _ _ _

theorem raw_eqvGen_glue {a b : Σ j, (rawDiagram A X k).obj j}
    (h : Relation.EqvGen (rawDiagram A X k).ColimitTypeRel a b) :
    Relation.EqvGen (Glue A X k) (rawToParameters A X k a) (rawToParameters A X k b) := by
  induction h with
  | rel a b h => exact .rel _ _ (raw_relation_glue A X k h)
  | refl => exact .refl _
  | symm a b h ih => exact .symm _ _ ih
  | trans a b c hab hbc ihab ihbc => exact .trans _ _ _ ihab ihbc

theorem raw_eqvGen_of_projection_eq [SSet.stdSimplex.{u}.HasPointwiseLeftKanExtension A]
    [L.IsLeftKanExtension α] {a b : Σ j, (rawDiagram A X k).obj j}
    (h : projection A L α X k (rawToParameters A X k a) =
      projection A L α X k (rawToParameters A X k b)) :
    Relation.EqvGen (rawDiagram A X k).ColimitTypeRel a b := by
  let c := (SSet.evaluation.obj (Opposite.op ⦋k⦌)).mapCocone (cellCocone A L α X)
  have hc : ((rawDiagram A X k).coconeTypesEquiv.symm c).IsColimit :=
    (Types.isColimit_iff_coconeTypesIsColimit c).mp
      ⟨isColimitOfPreserves (SSet.evaluation.obj (Opposite.op ⦋k⦌))
        (cellCoconeIsColimit A L α X)⟩
  apply Quot.eq.mp
  apply hc.bijective.1
  rcases a with ⟨a, t⟩
  rcases b with ⟨b, v⟩
  change ((cellCocone A L α X).ι.app a).app (Opposite.op ⦋k⦌) t =
    ((cellCocone A L α X).ι.app b).app (Opposite.op ⦋k⦌) v
  have ha := congrArg (fun g ↦ g.app (Opposite.op ⦋k⦌) t) (cellMap_eq_cocone_leg A L α X a)
  have hb := congrArg (fun g ↦ g.app (Opposite.op ⦋k⦌) v) (cellMap_eq_cocone_leg A L α X b)
  exact ha.symm.trans (h.trans hb)

theorem projection_eq_iff [SSet.stdSimplex.{u}.HasPointwiseLeftKanExtension A]
    [L.IsLeftKanExtension α] (a b : Parameters A X k) :
    projection A L α X k a = projection A L α X k b ↔ Relation.EqvGen (Glue A X k) a b := by
  constructor
  · intro h
    have hraw : projection A L α X k (rawToParameters A X k (parametersToRaw A X k a)) =
        projection A L α X k (rawToParameters A X k (parametersToRaw A X k b)) := by
      rwa [rawToParameters_parametersToRaw, rawToParameters_parametersToRaw]
    have hg := raw_eqvGen_glue A X k (raw_eqvGen_of_projection_eq A L α X k hraw)
    rwa [rawToParameters_parametersToRaw, rawToParameters_parametersToRaw] at hg
  · exact eqvGen_projection_eq A L α X k

end Wikipedia.HopfProblem.OrbitPair.SubdivisionParameters
