import Wikipedia.HopfProblem.PeriodTorusNeronSeveri
import Wikipedia.HopfProblem.PeriodTorusLineBundleChernEta

/-!
# The native Néron--Severi image of the actual special period tori

Outside the proved countable exceptional locus, the image of the genuine
first Chern map on all original native line bundles is exactly `ℤη`.
The generator is realized by an actual native bundle, and evaluation on
the original positive `u,w` period cycle gives the inverse integer marking.
No meromorphic-function or algebraic-dimension assertion is used.
-/

noncomputable section

open Bundle
open scoped ContDiff

namespace Wikipedia.HopfProblem.PeriodTorusLineBundle.ChernNative

open SingularCohomologyFree PeriodTorusCohomology PeriodTorusTypeOneOne
open SpecialPeriods UpperHalfPlane

/-- The distinguished native class is genuinely realized on every period torus. -/
theorem etaClass_mem_neronSeveri (p : PeriodDomain) : etaClass p ∈ neronSeveri p := by
  rw [neronSeveri_eq_integralTypeOneOneSubgroup]
  exact etaClass_mem_integralTypeOneOneSubgroup p

/-- Its integer multiples are the classes of the already constructed original native bundles. -/
theorem etaChernFactor_nativeClass (p : PeriodDomain) (n : ℤ) :
    (NativeLineBundle.ofFactor p (Chern.etaChernFactor p n)).chernClass = n • etaClass p := by
  rw [NativeLineBundle.chernClass_ofFactor, Chern.firstChernClass_etaChernFactor]

/-- Exact original coefficient membership for the actual native Chern image of a special torus. -/
theorem coefficientClass_mem_neronSeveri_special_iff (z : ℍ) (E : Fin 6 → ℤ) :
    coefficientClass (specialPeriodMap.point z) E ∈ neronSeveri (specialPeriodMap.point z) ↔
      specialPeriodRelation E z = 0 :=
  coefficientClass_mem_neronSeveri_iff_periodPolynomial (specialPeriodMap.point z) E

/-- The genuine native Chern image is generated by `η` away from the actual exceptional set. -/
theorem neronSeveri_special_eq_zmultiples_eta (z : ℍ)
    (hz : z ∉ exceptionalTypeOneOneSet) :
    neronSeveri (specialPeriodMap.point z) =
      AddSubgroup.zmultiples (etaClass (specialPeriodMap.point z)) :=
  (neronSeveri_eq_integralTypeOneOneSubgroup _).trans
    (integralTypeOneOneSubgroup_eq_zmultiples_eta z hz)

/-- The actual cohomology marking recognizes precisely the original integer multiples. -/
theorem coefficientClass_mem_zmultiples_eta_iff (p : PeriodDomain) (E : Fin 6 → ℤ) :
    coefficientClass p E ∈ AddSubgroup.zmultiples (etaClass p) ↔
      ∃ n : ℤ, E = n • periodRelationEta := by
  rw [AddSubgroup.mem_zmultiples_iff]
  apply exists_congr
  intro n
  change n • coefficientClassEquiv p periodRelationEta = coefficientClassEquiv p E ↔ _
  rw [← map_zsmul, (coefficientClassEquiv p).injective.eq_iff]
  exact eq_comm

/-- The exceptional locus is defined by the actual native-bundle Chern image. -/
def exceptionalNeronSeveriSet : Set ℍ :=
  {z | neronSeveri (specialPeriodMap.point z) ≠
    AddSubgroup.zmultiples (etaClass (specialPeriodMap.point z))}

/-- The native geometric exceptional set agrees with the independently proved period locus. -/
theorem exceptionalNeronSeveriSet_eq : exceptionalNeronSeveriSet = exceptionalTypeOneOneSet := by
  ext z
  change (neronSeveri (specialPeriodMap.point z) ≠
      AddSubgroup.zmultiples (etaClass (specialPeriodMap.point z))) ↔
    ∃ E : Fin 6 → ℤ, (¬ ∃ n : ℤ, E = n • periodRelationEta) ∧
      IsTypeOneOne (tangentForm (specialPeriodMap.point z) E)
  constructor
  · intro hne
    by_contra hz
    exact hne (neronSeveri_special_eq_zmultiples_eta z hz)
  · rintro ⟨E, hE, hType⟩ heq
    have hmem := (coefficientClass_mem_neronSeveri_iff (specialPeriodMap.point z) E).mpr hType
    rw [heq] at hmem
    exact hE ((coefficientClass_mem_zmultiples_eta_iff (specialPeriodMap.point z) E).mp hmem)

/-- Countability concerns the exceptional set of the actual native Chern image. -/
theorem exceptionalNeronSeveriSet_countable : exceptionalNeronSeveriSet.Countable := by
  rw [exceptionalNeronSeveriSet_eq]
  exact exceptionalTypeOneOneSet_countable

/-- The positively normalized integral generator maps into the actual native Chern image. -/
def neronSeveriEtaHom (p : PeriodDomain) : ℤ →+ neronSeveri p where
  toFun n := ⟨n • etaClass p, (neronSeveri p).zsmul_mem (etaClass_mem_neronSeveri p) n⟩
  map_zero' := Subtype.ext (zero_zsmul _)
  map_add' m n := Subtype.ext (add_zsmul (etaClass p) m n)

@[simp] theorem neronSeveriEtaHom_coe (p : PeriodDomain) (n : ℤ) :
    (neronSeveriEtaHom p n : SingularCohomology p.Torus 2) = n • etaClass p := rfl

theorem neronSeveriEtaHom_injective (p : PeriodDomain) :
    Function.Injective (neronSeveriEtaHom p) := by
  intro m n h
  exact etaClass_zsmul_injective p (congrArg Subtype.val h)

/-- A genuine additive isomorphism, preserving the specified native generator. -/
def specialNeronSeveriEquiv (z : ℍ) (hz : z ∉ exceptionalTypeOneOneSet) :
    ℤ ≃+ neronSeveri (specialPeriodMap.point z) :=
  AddEquiv.ofBijective (neronSeveriEtaHom (specialPeriodMap.point z))
    ⟨neronSeveriEtaHom_injective _, by
      intro a
      have ha := (mem_neronSeveri_iff (specialPeriodMap.point z) a.val).mp a.property
      obtain ⟨n, hn⟩ :=
        (cohomologyRealForm_typeOneOne_iff_of_not_exceptional z hz a.val).mp ha
      exact ⟨n, Subtype.ext hn.symm⟩⟩

@[simp] theorem specialNeronSeveriEquiv_coe (z : ℍ) (hz : z ∉ exceptionalTypeOneOneSet)
    (n : ℤ) :
    (specialNeronSeveriEquiv z hz n : SingularCohomology (specialPeriodMap.point z).Torus 2) =
      n • etaClass (specialPeriodMap.point z) := rfl

/-- The inverse marking is evaluation on the actual positive `u,w` period two-cycle. -/
theorem specialNeronSeveriEquiv_symm_apply (z : ℍ) (hz : z ∉ exceptionalTypeOneOneSet)
    (a : neronSeveri (specialPeriodMap.point z)) :
    (specialNeronSeveriEquiv z hz).symm a = etaEvaluation (specialPeriodMap.point z) a := by
  have h := congrArg (fun b : neronSeveri (specialPeriodMap.point z) =>
      etaEvaluation (specialPeriodMap.point z) b)
    ((specialNeronSeveriEquiv z hz).apply_symm_apply a)
  simpa only [specialNeronSeveriEquiv_coe, map_zsmul, etaEvaluation_etaClass,
    zsmul_eq_mul, mul_one, Int.cast_id] using h

/-- Every original native holomorphic line bundle has one uniquely determined multiple of `η`.
There is no chosen factor, frame, or Appell--Humbert datum among the hypotheses. -/
theorem firstChernClass_special_existsUnique_eta (z : ℍ)
    (hz : z ∉ exceptionalTypeOneOneSet) (V : (specialPeriodMap.point z).Torus → Type*)
    [∀ x, AddCommMonoid (V x)] [∀ x, Module ℂ (V x)]
    [∀ x, TopologicalSpace (V x)] [TopologicalSpace (TotalSpace ℂ V)]
    [FiberBundle ℂ V] [VectorBundle ℂ ℂ V]
    [ContMDiffVectorBundle ω ℂ V (modelWithCornersSelf ℂ ComplexPlane₂)] :
    ∃! n : ℤ, firstChernClass (specialPeriodMap.point z) V =
      n • etaClass (specialPeriodMap.point z) :=
  (cohomologyRealForm_typeOneOne_iff_existsUnique_eta z hz _).mp
    (firstChernClass_isTypeOneOne _ V)

end Wikipedia.HopfProblem.PeriodTorusLineBundle.ChernNative
