import Wikipedia.HopfProblem.PeriodFamilyHolomorphicCohomologyRelativeFormsCotangent
import Wikipedia.HopfProblem.PeriodFamilyHolomorphicCohomologyRelativeFormsVerticalDolbeault

/-!
# A full pointwise antiholomorphic frame from the original period coordinates

The three covectors are the actual differential of the conjugate base
coordinate and the actual full antiholomorphic differentials of the first two
inverse real period coordinates. The vertical block is the previously proved
original `firstDbarEquiv`; the remaining base block is triangular with diagonal
entry one. The target consists of genuine covectors on the unchanged model.
-/

noncomputable section

open TopologicalSpace

namespace Wikipedia.HopfProblem.PeriodFamilyHolomorphicCohomology.RelativeForms

open HolomorphicDolbeaultThree

variable {U : Opens ℂ} (P : HolomorphicPeriodMap ℂ U)

/-- An actual full coordinate differential, bundled with its proved
antiholomorphic complex-structure relation. -/
def coordinateCovector (j : Fin 4) (q : Model) : AntiCovector Model :=
  ⟨dbar (coordinate P j) q, dbar_mem _ _⟩

@[simp] theorem coordinateCovector_apply (j : Fin 4) (q v : Model) :
    (coordinateCovector P j q).val v = dbar (coordinate P j) q v := rfl

/-- The actual three proposed covering-space covectors, with arbitrary
complex coefficients. No spanning property is built into this definition. -/
def frameLinear (q : Model) : Model →ₗ[ℂ] AntiCovector Model where
  toFun c := c.1 • baseCovector + c.2 0 • coordinateCovector P 0 q +
    c.2 1 • coordinateCovector P 1 q
  map_add' c e := by
    simp only [Prod.fst_add, Prod.snd_add, Pi.add_apply, add_smul]
    abel
  map_smul' a c := by
    simp only [Prod.smul_fst, Prod.smul_snd, Pi.smul_apply, smul_eq_mul,
      mul_smul, smul_add, RingHom.id_apply]

/-- Evaluation of the full proposed frame on the original base direction. -/
theorem frameLinear_base (q : Model) (c : Model) :
    (frameLinear P q c).val (1, 0) = c.1 +
      c.2 0 * dbar (coordinate P 0) q (1, 0) +
      c.2 1 * dbar (coordinate P 1) q (1, 0) := by
  change c.1 * baseCovector.val (1, 0) +
    c.2 0 * dbar (coordinate P 0) q (1, 0) +
    c.2 1 * dbar (coordinate P 1) q (1, 0) = _
  rw [baseCovector_base, mul_one]

/-- The actual vertical block is exactly the original marked Dolbeault
isomorphism, even though the full covectors also have base components. -/
theorem frameLinear_vertical (b : U) (z : ComplexPlane₂) (c : Model) (i : Fin 2) :
    (frameLinear P ((b : ℂ), z) c).val (0, Pi.single i 1) =
      MarkedLinear.firstDbarEquiv (P.point b) c.2 i := by
  change c.1 * baseCovector.val (0, Pi.single i 1) +
    c.2 0 * dbar (coordinate P 0) ((b : ℂ), z) (0, Pi.single i 1) +
    c.2 1 * dbar (coordinate P 1) ((b : ℂ), z) (0, Pi.single i 1) = _
  rw [baseCovector_vertical, mul_zero, zero_add]
  exact first_coordinate_dbar_vertical_basis P b z c.2 i

/-- Independence follows from the proved vertical block and the remaining
base direction; it is not assumed in the construction. -/
theorem frameLinear_injective (b : U) (z : ComplexPlane₂) :
    Function.Injective (frameLinear P ((b : ℂ), z)) := by
  intro c e h
  have hv : MarkedLinear.firstDbarEquiv (P.point b) c.2 =
      MarkedLinear.firstDbarEquiv (P.point b) e.2 := by
    ext i
    have hi := congrArg (fun L : AntiCovector Model => L.val (0, Pi.single i 1)) h
    simpa only [frameLinear_vertical] using hi
  have hc := (MarkedLinear.firstDbarEquiv (P.point b)).injective hv
  apply Prod.ext
  · have hb := congrArg (fun L : AntiCovector Model => L.val (1, 0)) h
    simp only [frameLinear_base, hc] at hb
    exact add_right_cancel (add_right_cancel hb)
  · exact hc

/-- Explicit coefficients of an arbitrary genuine antiholomorphic covector
in the proposed full frame. -/
def frameCoefficients (b : U) (z : ComplexPlane₂) (L : AntiCovector Model) : Model :=
  let c := (MarkedLinear.firstDbarEquiv (P.point b)).symm
    (fun i => L.val (0, Pi.single i 1))
  (L.val (1, 0) -
    (c 0 * dbar (coordinate P 0) ((b : ℂ), z) (1, 0) +
      c 1 * dbar (coordinate P 1) ((b : ℂ), z) (1, 0)), c)

/-- These explicitly constructed coefficients reconstruct the actual
covector, by equality on the three original complex directions. -/
theorem frameLinear_frameCoefficients (b : U) (z : ComplexPlane₂)
    (L : AntiCovector Model) :
    frameLinear P ((b : ℂ), z) (frameCoefficients P b z L) = L := by
  apply antiCovector_ext
  · rw [frameLinear_base]
    dsimp only [frameCoefficients]
    ring
  · intro i
    rw [frameLinear_vertical]
    change MarkedLinear.firstDbarEquiv (P.point b)
      ((MarkedLinear.firstDbarEquiv (P.point b)).symm
        (fun j => L.val (0, Pi.single j 1))) i = _
    rw [LinearEquiv.apply_symm_apply]

/-- All actual antiholomorphic covectors are generated by the three
original coordinate differentials. -/
theorem frameLinear_surjective (b : U) (z : ComplexPlane₂) :
    Function.Surjective (frameLinear P ((b : ℂ), z)) :=
  fun L => ⟨frameCoefficients P b z L, frameLinear_frameCoefficients P b z L⟩

/-- The genuine pointwise full antiholomorphic frame on the original
covering model, proved from the actual period-coordinate derivatives. -/
def frameEquiv (b : U) (z : ComplexPlane₂) : Model ≃ₗ[ℂ] AntiCovector Model :=
  LinearEquiv.ofBijective (frameLinear P ((b : ℂ), z))
    ⟨frameLinear_injective P b z, frameLinear_surjective P b z⟩

@[simp] theorem frameEquiv_apply (b : U) (z : ComplexPlane₂) (c : Model) :
    frameEquiv P b z c = frameLinear P ((b : ℂ), z) c := rfl

/-- The inverse of the actual full frame is the explicit triangular solve. -/
theorem frameEquiv_symm_apply (b : U) (z : ComplexPlane₂) (L : AntiCovector Model) :
    (frameEquiv P b z).symm L = frameCoefficients P b z L := by
  apply (frameEquiv P b z).injective
  rw [LinearEquiv.apply_symm_apply, frameEquiv_apply, frameLinear_frameCoefficients]

end Wikipedia.HopfProblem.PeriodFamilyHolomorphicCohomology.RelativeForms
