import Wikipedia.HopfProblem.SingularMayerVietorisFormalChains
import Wikipedia.HopfProblem.SingularMayerVietorisFormalChainsSubdivision
import Wikipedia.HopfProblem.SingularMayerVietorisFormalChainsHomotopy
import Wikipedia.HopfProblem.SingularMayerVietorisFormalChainsIteration
import Mathlib.LinearAlgebra.Finsupp.Supported

/-!
# Vertex support of augmented formal chains

The support condition in this file concerns every vertex of every simplex with
nonzero coefficient. It is stable under the augmented boundary, coning to a
vertex in the same set, and maps of vertices.
-/

noncomputable section

namespace Wikipedia.HopfProblem.SingularMayerVietoris

open scoped BigOperators

variable {V W M : Type*} {n : ℕ}

/-- Formal chains whose nonzero simplices have all their vertices in `S`. -/
def formalChainsSupported (S : Set V) (n : ℕ) : Submodule ℤ (FormalChains V n) :=
  Finsupp.supported ℤ ℤ {v | ∀ i, v i ∈ S}

theorem mem_formalChainsSupported_iff {S : Set V} {c : FormalChains V n} :
    c ∈ formalChainsSupported S n ↔ ∀ v ∈ c.support, ∀ i, v i ∈ S :=
  Iff.rfl

theorem formalChainsSupported_mono {S T : Set V} (h : S ⊆ T) :
    formalChainsSupported S n ≤ formalChainsSupported T n := by
  intro c hc v hv i
  exact h (hc hv i)

@[simp] theorem formalChainsSupported_univ (n : ℕ) :
    formalChainsSupported (Set.univ : Set V) n = ⊤ := by
  apply top_unique
  intro c _ v hv i
  exact Set.mem_univ _

/-- Empty simplices have no vertices, so satisfy every vertex-support condition. -/
@[simp] theorem formalChainsSupported_zero (S : Set V) :
    formalChainsSupported S 0 = ⊤ := by
  apply top_unique
  intro c _ v hv i
  exact Fin.elim0 i

theorem formalChainsSupported_inter (S T : Set V) (n : ℕ) :
    formalChainsSupported (S ∩ T) n =
      formalChainsSupported S n ⊓ formalChainsSupported T n := by
  ext c
  simp only [Submodule.mem_inf, mem_formalChainsSupported_iff, Set.mem_inter_iff]
  constructor
  · intro h
    exact ⟨fun v hv i => (h v hv i).1, fun v hv i => (h v hv i).2⟩
  · rintro ⟨hS, hT⟩ v hv i
    exact ⟨hS v hv i, hT v hv i⟩

@[simp] theorem formalSimplex_mem_supported_iff {S : Set V} (v : Fin n → V) :
    formalSimplex v ∈ formalChainsSupported S n ↔ ∀ i, v i ∈ S := by
  classical
  simp [formalSimplex, formalChainsSupported, Finsupp.mem_supported]

theorem formalSimplex_mem_supported {S : Set V} {v : Fin n → V}
    (hv : ∀ i, v i ∈ S) : formalSimplex v ∈ formalChainsSupported S n :=
  (formalSimplex_mem_supported_iff v).mpr hv

/-- The supported submodule is generated by its coefficient-one simplices. -/
theorem formalChainsSupported_le {S : Set V} {P : Submodule ℤ (FormalChains V n)}
    (h : ∀ v, (∀ i, v i ∈ S) → formalSimplex v ∈ P) :
    formalChainsSupported S n ≤ P := by
  rw [formalChainsSupported, Finsupp.supported_eq_span_single]
  apply Submodule.span_le.mpr
  rintro _ ⟨v, hv, rfl⟩
  exact h v hv

/-- To control a linear map on supported chains, it suffices to control its generators. -/
theorem formalLinearMap_mem_of_supported [AddCommGroup M] [Module ℤ M]
    {S : Set V} (f : FormalChains V n →ₗ[ℤ] M) (P : Submodule ℤ M)
    {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n)
    (h : ∀ v, (∀ i, v i ∈ S) → f (formalSimplex v) ∈ P) : f c ∈ P := by
  exact (formalChainsSupported_le (P := P.comap f) h) hc

/-- A linear extension stays in a submodule if all supported generators do. -/
theorem formalLift_mem_of_supported [AddCommGroup M] [Module ℤ M]
    {S : Set V} (f : (Fin n → V) → M) (P : Submodule ℤ M)
    {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n)
    (h : ∀ v, (∀ i, v i ∈ S) → f v ∈ P) : formalLift f c ∈ P := by
  apply formalLinearMap_mem_of_supported (formalLift f) P hc
  intro v hv
  simpa only [formalLift_simplex] using h v hv

/-- Vertex deletion cannot enlarge support, including in augmented degree zero. -/
theorem formalBoundary_mem_supported {S : Set V} (n : ℕ)
    {c : FormalChains V (n + 1)} (hc : c ∈ formalChainsSupported S (n + 1)) :
    formalBoundary n c ∈ formalChainsSupported S n := by
  apply formalLinearMap_mem_of_supported (formalBoundary n) (formalChainsSupported S n) hc
  intro v hv
  rw [formalBoundary_simplex]
  apply Submodule.sum_mem
  intro i hi
  apply Submodule.smul_mem
  exact formalSimplex_mem_supported fun j => hv (i.succAbove j)

/-- Coning stays supported when the apex belongs to the support set. -/
theorem formalCone_mem_supported {S : Set V} {a : V} (ha : a ∈ S)
    {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n) :
    formalCone a n c ∈ formalChainsSupported S (n + 1) := by
  apply formalLinearMap_mem_of_supported (formalCone a n) (formalChainsSupported S (n + 1)) hc
  intro v hv
  rw [formalCone_simplex]
  apply formalSimplex_mem_supported
  intro i
  exact Fin.cases ha hv i

/-- In general, coning can add only the apex to the support. -/
theorem formalCone_mem_supported_insert {S : Set V} (a : V)
    {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n) :
    formalCone a n c ∈ formalChainsSupported (insert a S) (n + 1) :=
  formalCone_mem_supported (Set.mem_insert a S)
    (formalChainsSupported_mono (Set.subset_insert a S) hc)

/-- A map of vertices transports the corresponding supported submodules. -/
theorem formalMap_mem_supported {S : Set V} {T : Set W} (f : V → W)
    (hf : Set.MapsTo f S T) {c : FormalChains V n}
    (hc : c ∈ formalChainsSupported S n) :
    formalMap f n c ∈ formalChainsSupported T n := by
  apply formalLinearMap_mem_of_supported (formalMap f n) (formalChainsSupported T n) hc
  intro v hv
  rw [formalMap_simplex]
  exact formalSimplex_mem_supported fun i => hf (hv i)

theorem formalMap_mem_supported_image {S : Set V} (f : V → W)
    {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n) :
    formalMap f n c ∈ formalChainsSupported (f '' S) n :=
  formalMap_mem_supported (T := f '' S) f (fun v hv => ⟨v, hv, rfl⟩) hc

theorem formalMap_mem_supported_of_preimage {T : Set W} (f : V → W)
    {c : FormalChains V n} (hc : c ∈ formalChainsSupported (f ⁻¹' T) n) :
    formalMap f n c ∈ formalChainsSupported T n :=
  formalMap_mem_supported f (fun _ hv => hv) hc

/-- Subdivision preserves a vertex set closed under the chosen centers. -/
theorem formalSubdivision_mem_supported (center : FormalCenter V) {S : Set V}
    (hcenter : ∀ k v, (∀ i, v i ∈ S) → center k v ∈ S) :
    ∀ (n : ℕ) {c : FormalChains V n}, c ∈ formalChainsSupported S n →
      formalSubdivision center n c ∈ formalChainsSupported S n := by
  intro n
  induction n with
  | zero =>
      intro c hc
      exact hc
  | succ n ih =>
      intro c hc
      apply formalLinearMap_mem_of_supported (formalSubdivision center (n + 1))
        (formalChainsSupported S (n + 1)) hc
      intro v hv
      rw [formalSubdivision_simplex_succ]
      exact formalCone_mem_supported (hcenter n v hv)
        (ih (formalBoundary_mem_supported n (formalSimplex_mem_supported hv)))

/-- Every finite iterate of subdivision preserves such a vertex set. -/
theorem formalSubdivision_iterate_mem_supported (center : FormalCenter V) {S : Set V}
    (hcenter : ∀ k v, (∀ i, v i ∈ S) → center k v ∈ S)
    (n k : ℕ) {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n) :
    (formalSubdivision center n)^[k] c ∈ formalChainsSupported S n := by
  induction k with
  | zero => exact hc
  | succ k ih =>
      rw [Function.iterate_succ_apply']
      exact formalSubdivision_mem_supported center hcenter n ih

/-- Every simplex occurring in a cone comes from prepending the apex. -/
theorem formalCone_support_exists (a : V) {c : FormalChains V n}
    {w : Fin (n + 1) → V} (hw : w ∈ (formalCone a n c).support) :
    ∃ v ∈ c.support, w = Fin.cons a v := by
  classical
  change w ∈ (Finsupp.mapDomain (Fin.cons a) c).support at hw
  obtain ⟨v, hv, heq⟩ := Finset.mem_image.mp (Finsupp.mapDomain_support hw)
  exact ⟨v, hv, heq.symm⟩

/-- A simplex in a linear extension occurs in the image of an input generator. -/
theorem formalLift_support_exists {m : ℕ}
    (f : (Fin n → V) → FormalChains W m) {c : FormalChains V n}
    {w : Fin m → W} (hw : w ∈ (formalLift f c).support) :
    ∃ v ∈ c.support, w ∈ (f v).support := by
  classical
  change w ∈ (c.sum fun v z => z • f v).support at hw
  obtain ⟨v, hv, hterm⟩ := Finset.mem_biUnion.mp (Finsupp.support_sum hw)
  exact ⟨v, hv, Finsupp.support_smul hterm⟩

/-- The same support extraction applies to any linear map of formal chains. -/
theorem formalLinearMap_support_exists {m : ℕ}
    (f : FormalChains V n →ₗ[ℤ] FormalChains W m) {c : FormalChains V n}
    {w : Fin m → W} (hw : w ∈ (f c).support) :
    ∃ v ∈ c.support, w ∈ (f (formalSimplex v)).support := by
  have hf : f = formalLift (fun v => f (formalSimplex v)) := by
    apply formalChains_ext
    intro v
    simp only [formalLift_simplex]
  rw [hf] at hw
  exact formalLift_support_exists _ hw

/-- Every simplex in the boundary of a generator is one of its vertex deletions. -/
theorem formalBoundary_support_exists (n : ℕ) (v : Fin (n + 1) → V)
    {w : Fin n → V} (hw : w ∈ (formalBoundary n (formalSimplex v)).support) :
    ∃ i : Fin (n + 1), w = v ∘ i.succAbove := by
  classical
  rw [formalBoundary_simplex] at hw
  obtain ⟨i, hi, hterm⟩ := Finset.mem_biUnion.mp (Finsupp.support_finsetSum hw)
  refine ⟨i, ?_⟩
  have hs : w ∈ (formalSimplex (v ∘ i.succAbove)).support := Finsupp.support_smul hterm
  simpa [formalSimplex] using hs

/-- The explicit subdivision homotopy stays within any center-closed vertex set. -/
theorem formalSubdivisionHomotopy_mem_supported (center : FormalCenter V) {S : Set V}
    (hcenter : ∀ k v, (∀ i, v i ∈ S) → center k v ∈ S) :
    ∀ (n : ℕ) {c : FormalChains V n}, c ∈ formalChainsSupported S n →
      formalSubdivisionHomotopy center n c ∈ formalChainsSupported S (n + 1) := by
  intro n
  induction n with
  | zero =>
      intro c hc
      rw [formalSubdivisionHomotopy_zero]
      exact Submodule.zero_mem _
  | succ n ih =>
      intro c hc
      apply formalLinearMap_mem_of_supported (formalSubdivisionHomotopy center (n + 1))
        (formalChainsSupported S (n + 2)) hc
      intro v hv
      rw [formalSubdivisionHomotopy_simplex_succ]
      apply formalCone_mem_supported (hv 0)
      apply Submodule.sub_mem
      · exact Submodule.sub_mem _ (formalSimplex_mem_supported hv)
          (formalSubdivision_mem_supported center hcenter (n + 1)
            (formalSimplex_mem_supported hv))
      · exact ih (formalBoundary_mem_supported n (formalSimplex_mem_supported hv))

/-- The finite homotopy to an iterated subdivision preserves center-closed support. -/
theorem formalSubdivisionIteratedHomotopy_mem_supported (center : FormalCenter V) {S : Set V}
    (hcenter : ∀ k v, (∀ i, v i ∈ S) → center k v ∈ S)
    (k n : ℕ) {c : FormalChains V n} (hc : c ∈ formalChainsSupported S n) :
    formalSubdivisionIteratedHomotopy center k n c ∈ formalChainsSupported S (n + 1) := by
  rw [formalSubdivisionIteratedHomotopy_apply]
  apply Submodule.sum_mem
  intro j hj
  exact formalSubdivisionHomotopy_mem_supported center hcenter n
    (formalSubdivision_iterate_mem_supported center hcenter n j hc)

end Wikipedia.HopfProblem.SingularMayerVietoris
