import Wikipedia.HopfProblem.FirstHurewiczChainNaturality

/-!
# Actual small singular chains for two subsets

The small chains are submodules of Mathlib's integral singular chain groups,
spanned by singular simplices lying wholly in either subset. Their restricted
differentials and inclusion form an actual chain complex and chain map.
No openness, covering, or quasi-isomorphism assumption is used here.
-/

noncomputable section

open CategoryTheory Set

namespace Wikipedia.HopfProblem.SingularMayerVietoris

open FirstHurewicz

variable {X : Type} [TopologicalSpace X]

/-- Chains generated by actual singular simplices supported in one subset. -/
def supportedChainSubmodule (U : Set X) (n : ℕ) : Submodule ℤ (Chains X n) :=
  Submodule.span ℤ (simplexChain X n '' {σ : SingularSimplex X n | range σ ⊆ U})

/-- The sum of the two supported-chain submodules in the actual ambient chain group. -/
def smallChainSubmodule (U V : Set X) (n : ℕ) : Submodule ℤ (Chains X n) :=
  supportedChainSubmodule U n ⊔ supportedChainSubmodule V n

theorem smallChainSubmodule_eq_span (U V : Set X) (n : ℕ) :
    smallChainSubmodule U V n = Submodule.span ℤ
      (simplexChain X n '' {σ : SingularSimplex X n | range σ ⊆ U ∨ range σ ⊆ V}) := by
  rw [smallChainSubmodule, supportedChainSubmodule, supportedChainSubmodule,
    ← Submodule.span_union, ← image_union]
  rfl

theorem simplexChain_mem_supported (U : Set X) (n : ℕ) (σ : SingularSimplex X n)
    (hσ : range σ ⊆ U) : simplexChain X n σ ∈ supportedChainSubmodule U n :=
  Submodule.subset_span ⟨σ, hσ, rfl⟩

theorem simplexChain_mem_small (U V : Set X) (n : ℕ) (σ : SingularSimplex X n)
    (hσ : range σ ⊆ U ∨ range σ ⊆ V) : simplexChain X n σ ∈ smallChainSubmodule U V n := by
  rw [smallChainSubmodule_eq_span]
  exact Submodule.subset_span ⟨σ, hσ, rfl⟩

theorem simplex_face_supported (U : Set X) (n : ℕ) (σ : SingularSimplex X (n + 1))
    (hσ : range σ ⊆ U) (i : Fin (n + 2)) : range (σ.comp (simplexFace n i)) ⊆ U := by
  rintro x ⟨s, rfl⟩
  exact hσ ⟨simplexFace n i s, rfl⟩

theorem boundary_mem_small_succ (U V : Set X) (n : ℕ) (c : Chains X (n + 1))
    (hc : c ∈ smallChainSubmodule U V (n + 1)) :
    ((singularComplex X).d (n + 1) n).hom c ∈ smallChainSubmodule U V n := by
  have hle : smallChainSubmodule U V (n + 1) ≤
      (smallChainSubmodule U V n).comap ((singularComplex X).d (n + 1) n).hom := by
    rw [smallChainSubmodule_eq_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨σ, hσ, rfl⟩
    change (singularComplex X).d (n + 1) n (simplexChain X (n + 1) σ) ∈
      smallChainSubmodule U V n
    rw [boundary_simplex]
    apply Submodule.sum_mem
    intro i hi
    apply (smallChainSubmodule U V n).toAddSubgroup.zsmul_mem
    apply simplexChain_mem_small
    exact hσ.imp (fun h => simplex_face_supported U n σ h i)
      (fun h => simplex_face_supported V n σ h i)
  exact hle hc

/-- Every actual differential preserves the small-chain submodules. -/
theorem boundary_mem_small (U V : Set X) (i j : ℕ) (c : Chains X i)
    (hc : c ∈ smallChainSubmodule U V i) :
    ((singularComplex X).d i j).hom c ∈ smallChainSubmodule U V j := by
  by_cases hij : (ComplexShape.down ℕ).Rel i j
  · have he : j + 1 = i := hij
    subst i
    exact boundary_mem_small_succ U V j c hc
  · have he := congrArg (fun f : Chains X i ⟶ Chains X j => f.hom c)
      ((singularComplex X).shape i j hij)
    rw [he]
    exact Submodule.zero_mem _

instance smallChainModule (U V : Set X) (n : ℕ) : Module ℤ (smallChainSubmodule U V n) :=
  (smallChainSubmodule U V n).module

/-- Restrict the actual singular differential, without changing its values. -/
def smallDifferential (U V : Set X) (i j : ℕ) :
    smallChainSubmodule U V i →ₗ[ℤ] smallChainSubmodule U V j :=
  (((singularComplex X).d i j).hom.comp (smallChainSubmodule U V i).subtype).codRestrict _
    (fun c => boundary_mem_small U V i j c.1 c.2)

@[simp] theorem smallDifferential_val (U V : Set X) (i j : ℕ)
    (c : smallChainSubmodule U V i) :
    (smallDifferential U V i j c).1 = ((singularComplex X).d i j).hom c.1 := rfl

/-- The genuine small-chain subcomplex of the singular chain complex. -/
def smallComplex (U V : Set X) : ChainComplex (ModuleCat ℤ) ℕ where
  X n := ModuleCat.of ℤ (smallChainSubmodule U V n)
  d i j := ModuleCat.ofHom (smallDifferential U V i j)
  shape i j hij := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro c
    apply Subtype.ext
    exact congrArg (fun f : Chains X i ⟶ Chains X j => f.hom c.1)
      ((singularComplex X).shape i j hij)
  d_comp_d' i j k hij hjk := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro c
    apply Subtype.ext
    exact congrArg (fun f : Chains X i ⟶ Chains X k => f.hom c.1)
      ((singularComplex X).d_comp_d i j k)

/-- The inclusion of actual small chains in actual singular chains. -/
def smallInclusion (U V : Set X) : smallComplex U V ⟶ singularComplex X where
  f n := ModuleCat.ofHom (smallChainSubmodule U V n).subtype
  comm' i j hij := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro c
    rfl

@[simp] theorem smallInclusion_f_apply (U V : Set X) (n : ℕ)
    (c : (smallComplex U V).X n) : (smallInclusion U V).f n c = c.1 := rfl

theorem smallInclusion_f_injective (U V : Set X) (n : ℕ) :
    Function.Injective ((smallInclusion U V).f n) :=
  Subtype.val_injective

end Wikipedia.HopfProblem.SingularMayerVietoris
