import Wikipedia.HopfProblem.FirstHurewiczChains

/-!
# A genuine basis of the actual singular chain groups

The basis and finitely supported coordinates are derived from Mathlib's
actual coproduct chain groups using their proved universal property.
This supplies the coefficient-support intersection calculation for small chains.
-/

noncomputable section

namespace Wikipedia.HopfProblem.FirstHurewicz

variable (X : Type) [TopologicalSpace X] (n : ℕ)

/-- Coefficients of actual singular chains, defined by the coproduct universal map. -/
def chainsRepr : Chains X n →ₗ[ℤ] (SingularSimplex X n →₀ ℤ) :=
  chainLift X n (fun σ => Finsupp.single σ 1)

@[simp] theorem chainsRepr_simplex (σ : SingularSimplex X n) :
    chainsRepr X n (simplexChain X n σ) = Finsupp.single σ 1 :=
  chainLift_simplex X n _ σ

/-- Form an actual chain by summing its finitely many simplex coefficients. -/
def chainsFromFinsupp : (SingularSimplex X n →₀ ℤ) →ₗ[ℤ] Chains X n :=
  Finsupp.linearCombination ℤ (simplexChain X n)

@[simp] theorem chainsFromFinsupp_single (σ : SingularSimplex X n) (a : ℤ) :
    chainsFromFinsupp X n (Finsupp.single σ a) = a • simplexChain X n σ :=
  (Finsupp.linearCombination_single ℤ (v := simplexChain X n) a σ).trans
    (int_smul_eq_zsmul (Chains X n).isModule a (simplexChain X n σ))

theorem chainsFromFinsupp_comp_repr :
    (chainsFromFinsupp X n).comp (chainsRepr X n) = LinearMap.id := by
  apply chainMap_ext X n
  intro σ
  simp only [LinearMap.comp_apply, chainsRepr_simplex, chainsFromFinsupp_single,
    one_smul, LinearMap.id_apply]

theorem chainsRepr_comp_fromFinsupp :
    (chainsRepr X n).comp (chainsFromFinsupp X n) = LinearMap.id := by
  apply Finsupp.lhom_ext
  intro σ a
  simp only [LinearMap.comp_apply, chainsFromFinsupp_single, map_zsmul,
    chainsRepr_simplex, Finsupp.smul_single, smul_eq_mul, mul_one, LinearMap.id_apply]

/-- Actual integral singular chains are freely generated by their singular simplices. -/
def chainsEquivFinsupp : Chains X n ≃ₗ[ℤ] (SingularSimplex X n →₀ ℤ) where
  toLinearMap := chainsRepr X n
  invFun := chainsFromFinsupp X n
  left_inv c := LinearMap.congr_fun (chainsFromFinsupp_comp_repr X n) c
  right_inv c := LinearMap.congr_fun (chainsRepr_comp_fromFinsupp X n) c

@[simp] theorem chainsEquivFinsupp_simplex (σ : SingularSimplex X n) :
    chainsEquivFinsupp X n (simplexChain X n σ) = Finsupp.single σ 1 :=
  chainsRepr_simplex X n σ

@[simp] theorem chainsEquivFinsupp_symm_single (σ : SingularSimplex X n) (a : ℤ) :
    (chainsEquivFinsupp X n).symm (Finsupp.single σ a) = a • simplexChain X n σ :=
  chainsFromFinsupp_single X n σ a

def chainBasis : Module.Basis (SingularSimplex X n) ℤ (Chains X n) :=
  Module.Basis.ofRepr (chainsEquivFinsupp X n)

@[simp] theorem chainBasis_repr : (chainBasis X n).repr = chainsEquivFinsupp X n := rfl

@[simp] theorem chainBasis_apply (σ : SingularSimplex X n) :
    chainBasis X n σ = simplexChain X n σ := by
  change chainsFromFinsupp X n (Finsupp.single σ 1) = _
  rw [chainsFromFinsupp_single, one_smul]

theorem chainBasis_coe : ⇑(chainBasis X n) = simplexChain X n :=
  funext (chainBasis_apply X n)

theorem simplexChain_injective : Function.Injective (simplexChain X n) := by
  simpa only [chainBasis_coe] using (chainBasis X n).injective

theorem simplexChain_linearIndependent : LinearIndependent ℤ (simplexChain X n) := by
  simpa only [chainBasis_coe] using (chainBasis X n).linearIndependent

theorem simplexChain_span : Submodule.span ℤ (Set.range (simplexChain X n)) = ⊤ := by
  simpa only [chainBasis_coe] using (chainBasis X n).span_eq

theorem mem_simplex_span_iff (S : Set (SingularSimplex X n)) (c : Chains X n) :
    c ∈ Submodule.span ℤ (simplexChain X n '' S) ↔
      ↑(chainsEquivFinsupp X n c).support ⊆ S := by
  simpa only [chainBasis_coe, chainBasis_repr] using
    (chainBasis X n).mem_span_image (m := c) (s := S)

theorem simplex_span_inter (S T : Set (SingularSimplex X n)) :
    Submodule.span ℤ (simplexChain X n '' S) ⊓
      Submodule.span ℤ (simplexChain X n '' T) =
        Submodule.span ℤ (simplexChain X n '' (S ∩ T)) := by
  ext c
  simp only [Submodule.mem_inf, mem_simplex_span_iff, Set.subset_inter_iff]

theorem simplex_span_union (S T : Set (SingularSimplex X n)) :
    Submodule.span ℤ (simplexChain X n '' S) ⊔
      Submodule.span ℤ (simplexChain X n '' T) =
        Submodule.span ℤ (simplexChain X n '' (S ∪ T)) := by
  rw [Set.image_union, Submodule.span_union]


end Wikipedia.HopfProblem.FirstHurewicz
