import Wikipedia.HopfProblem.SpecialPeriodsIntegralRelations
import Wikipedia.HopfProblem.UpperHalfPlaneHolomorphicZeros
import Mathlib.Topology.Algebra.Module.Cardinality

/-!
# Countably many exceptional integral period relations

The genuine special period functions have only the universal relation
outside a countable set. This proves the analytic countability step in
Proposition 9.5, separately from its Néron--Severi and algebraic-dimension
interpretations, which require geometric comparison theorems.
-/

noncomputable section

open Set UpperHalfPlane

namespace Wikipedia.HopfProblem.SpecialPeriods

theorem specialPeriodRelation_zero_set_countable (E : Fin 6 → ℤ)
    (hE : ¬ ∃ n : ℤ, E = n • periodRelationEta) :
    Set.Countable {z : ℍ | specialPeriodRelation E z = 0} :=
  upperHalfPlane_holomorphic_zero_set_countable (specialPeriodRelation_holomorphic E)
    (specialPeriodRelation_exists_ne_zero E hE)

/-- Points admitting an integral period relation not generated by `η`. -/
def exceptionalPeriodRelationSet : Set ℍ :=
  {z | ∃ E : Fin 6 → ℤ, (¬ ∃ n : ℤ, E = n • periodRelationEta) ∧
    specialPeriodRelation E z = 0}

theorem exceptionalPeriodRelationSet_countable : exceptionalPeriodRelationSet.Countable := by
  let T := {E : Fin 6 → ℤ // ¬ ∃ n : ℤ, E = n • periodRelationEta}
  have hc : ∀ E : T, Set.Countable {z : ℍ | specialPeriodRelation E.val z = 0} :=
    fun E => specialPeriodRelation_zero_set_countable E.val E.property
  apply (Set.countable_iUnion hc).mono
  intro z hz
  obtain ⟨E, hE, hz⟩ := hz
  exact mem_iUnion.mpr ⟨⟨E, hE⟩, hz⟩

/-- Outside the proved countable exceptional set, the only integral
relations at the given point are the actual multiples of `η`. -/
theorem specialPeriodRelation_iff_of_not_exceptional (z : ℍ)
    (hz : z ∉ exceptionalPeriodRelationSet) (E : Fin 6 → ℤ) :
    specialPeriodRelation E z = 0 ↔ ∃ n : ℤ, E = n • periodRelationEta := by
  constructor
  · intro hzero
    by_contra hE
    exact hz ⟨E, hE, hzero⟩
  · intro hE
    exact (specialPeriodRelation_identically_zero_iff E).mpr hE z

/-- The exceptional values in the actual normalized finite base. -/
def exceptionalPeriodBaseValues : Set ℂ := specialSourceCoordinate '' exceptionalPeriodRelationSet

theorem exceptionalPeriodBaseValues_countable : exceptionalPeriodBaseValues.Countable :=
  exceptionalPeriodRelationSet_countable.image specialSourceCoordinate

theorem exceptionalPeriodBaseValues_compl_dense : Dense exceptionalPeriodBaseValuesᶜ :=
  Set.Countable.dense_compl ℂ exceptionalPeriodBaseValues_countable

theorem specialPeriodRelation_iff_of_base_not_exceptional (z : ℍ)
    (hz : specialSourceCoordinate z ∉ exceptionalPeriodBaseValues) (E : Fin 6 → ℤ) :
    specialPeriodRelation E z = 0 ↔ ∃ n : ℤ, E = n • periodRelationEta :=
  specialPeriodRelation_iff_of_not_exceptional z
    (fun h => hz ⟨z, h, rfl⟩) E

end Wikipedia.HopfProblem.SpecialPeriods
