import Wikipedia.HopfProblem.SpecialPeriodsThreefoldVerticalActionFlow
import Wikipedia.HopfProblem.SpecialPeriodsThreefoldVerticalActionGeneratorCover

/-!
# The actual native holomorphic vertical generator

Differentiating the constructed global flow gives a section of the
original holomorphic tangent bundle.  Its pullback along the original
regular period-vector covering is exactly the constant vector `(0,e₂)`.
The genuine invertible covering derivative proves that this section is
nonzero; no vector-field dimension or automorphism classification is used.
-/

noncomputable section

open Set Topology
open scoped ContDiff Manifold

namespace Wikipedia.HopfProblem.SpecialPeriods.Threefold.VerticalAction

open HolomorphicForms.RegularCover
  (Cover globalCover globalCover_holomorphic globalCover_isLocalDiffeomorph)

local notation "Model" => ℂ × ComplexPlane₂
local notation "IF" => modelWithCornersSelf ℂ Model
local notation "I₁" => modelWithCornersSelf ℂ ℂ

attribute [local instance] chartedSpace space_isManifold
  HolomorphicForms.RegularCover.coverChartedSpace HolomorphicForms.RegularCover.cover_isManifold

/-- The genuine holomorphic tangent section generated by the original
additive parameter, normalized as `e₂` in period-vector coordinates. -/
def generator : Wikipedia.HopfProblem.HolomorphicVectorFields.Field Model Space :=
  Wikipedia.HopfProblem.HolomorphicVectorFields.timeGenerator Model Space
    (fun p : Space × ℂ => flow p.2 p.1) jointFlow_holomorphic flow_zero

@[simp] theorem generator_apply (x : Space) :
    generator x = mfderiv I₁ IF (fun s : ℂ => flow s x) 0 (1 : ℂ) := rfl

/-- The constructed global flow retains the original vector-cover formula. -/
theorem flow_globalCover (s : ℂ) (x : Cover) :
    flow s (globalCover x) = globalCover (Period.vectorFlow s x) := by
  change flow s (regularFamilyInclusion
      (Regular.data.quotient (Regular.data.periods.quotientMap x))) =
    regularFamilyInclusion
      (Regular.data.quotient (Regular.data.periods.quotientMap (Period.vectorFlow s x)))
  rw [flow_regular, Regular.flow_vectorCover]

/-- Exact native derivative formula, with no scalar normalization change. -/
theorem generator_globalCover (x : Cover) :
    generator (globalCover x) =
      mfderiv IF IF globalCover x (0, (![0, 1] : ComplexPlane₂)) := by
  have hn := Wikipedia.HopfProblem.HolomorphicVectorFields.timeGenerator_naturality
    Model Cover Model Space vectorJointFlow vectorJointFlow_holomorphic vectorJointFlow_zero
    (fun p : Space × ℂ => flow p.2 p.1) jointFlow_holomorphic flow_zero
    globalCover globalCover_holomorphic (fun y s => (flow_globalCover s y).symm) x
  change mfderiv IF IF globalCover x (vectorGenerator x) = generator (globalCover x) at hn
  rw [vectorGenerator_apply] at hn
  exact hn.symm

/-- On every point reached by the actual regular vector cover the
native generator is nonzero. -/
theorem generator_globalCover_ne_zero (x : Cover) : generator (globalCover x) ≠ 0 := by
  rw [generator_globalCover]
  intro h
  have hi : Function.Injective (mfderiv IF IF globalCover x) :=
    (globalCover_isLocalDiffeomorph x).mfderivToContinuousLinearEquiv (by simp) |>.injective
  have hv : (0, (![0, 1] : ComplexPlane₂)) = (0 : Model) :=
    hi (h.trans (map_zero (mfderiv IF IF globalCover x)).symm)
  have he := congrArg (fun v : Model => v.2 1) hv
  norm_num at he

theorem generator_ne_zero_on_regular (x : Space) (hx : x ∈ regularLocus) :
    generator x ≠ 0 := by
  have hx' : x ∈ range globalCover := by
    rw [HolomorphicForms.RegularCover.range_globalCover]
    exact hx
  obtain ⟨y, rfl⟩ := hx'
  exact generator_globalCover_ne_zero y

/-- The constructed native holomorphic vector field is not the zero section. -/
theorem generator_ne_zero : generator ≠ 0 := by
  intro h
  let x : Cover := Classical.choice (inferInstance : Nonempty Cover)
  have hx := congrArg
    (fun v : Wikipedia.HopfProblem.HolomorphicVectorFields.Field Model Space => v (globalCover x)) h
  exact generator_globalCover_ne_zero x hx

/-- Fibre preservation differentiates to the actual tangent-kernel
identity for the original holomorphic map to the sphere. -/
theorem generator_projectionSphere (x : Space) :
    mfderiv IF I₁ projectionSphere x (generator x) = 0 := by
  have hn := Wikipedia.HopfProblem.HolomorphicVectorFields.timeGenerator_naturality
    Model Space ℂ RiemannSphere
    (fun p : Space × ℂ => flow p.2 p.1) jointFlow_holomorphic flow_zero
    (fun p : RiemannSphere × ℂ => p.1) contMDiff_fst (fun _ => rfl)
    projectionSphere projectionSphere_holomorphic (fun y s => projectionSphere_flow s y) x
  change mfderiv IF I₁ projectionSphere x (generator x) =
    mfderiv I₁ I₁ (fun _ : ℂ => projectionSphere x) 0 (1 : ℂ) at hn
  rw [mfderiv_const] at hn
  exact hn.trans rfl

end Wikipedia.HopfProblem.SpecialPeriods.Threefold.VerticalAction
