import Wikipedia.HopfProblem.ThreefoldFundamentalGroupGluing
import Wikipedia.HopfProblem.FundamentalGroupVanKampenSurjectivity
import Wikipedia.HopfProblem.FundamentalGroupBasepointNaturality

/-!
# Generator surjectivity through the actual filling stages

The fundamental-group map of each genuine previous-stage inclusion is
surjective whenever the full regular overlap generates the filling group.
Iterating this statement uses actual basepoint-change paths in the stages.
The local overlap-surjectivity statements are geometric inputs to this
reduction and are not inferred merely from a presentation of a filling.
-/

noncomputable section

namespace Wikipedia.HopfProblem.SpecialPeriods.Threefold

/-- Surjectivity for a single actual attachment, transferred through the
three pointed homeomorphisms of its van Kampen diagram. -/
theorem previousStageHom_surjective_of_overlapFillingHom_surjective
    (s : Finset Puncture) (i : Puncture) (hi : i ∉ s)
    (hF : Function.Surjective (overlapFillingHom i)) :
    Function.Surjective (previousStageHom s i) := by
  have hV : Function.Surjective (attachmentCover s i hi).overlapHomV := by
    intro γ
    obtain ⟨δ, hδ⟩ := hF (attachmentRightGroupEquiv s i hi γ)
    obtain ⟨ε, hε⟩ := (attachmentOverlapGroupEquiv s i hi).surjective δ
    refine ⟨ε, (attachmentRightGroupEquiv s i hi).injective ?_⟩
    exact (DFunLike.congr_fun (attachmentRightGroupEquiv_overlap s i hi) ε).trans
      ((congrArg (overlapFillingHom i) hε).trans hδ)
  intro γ
  obtain ⟨δ, hδ⟩ :=
    (attachmentCover s i hi).inclusionHomU_surjective_of_overlapHomV_surjective hV γ
  exact ⟨attachmentLeftGroupEquiv s i hi δ,
    (DFunLike.congr_fun (attachmentLeftGroupEquiv_inclusion s i hi) δ).trans hδ⟩

/-- The literal inclusion of the regular patch in an attachment stage. -/
def stageRegularInclusion (s : Finset Puncture) : C(liftedPatch none, partialPatch s) :=
  ⟨fun x => ⟨x.val, regular_le_partialPatch s x.property⟩,
    continuous_subtype_val.subtype_mk _⟩

theorem stageRegularInclusion_empty_fundamentalGroup_map_surjective
    (x : liftedPatch none) :
    Function.Surjective (FundamentalGroup.map (stageRegularInclusion ∅) x) := by
  exact (homeomorphFundamentalGroupEquiv emptyStageHomeomorph.symm x).surjective

theorem stageRegularInclusion_insert_fundamentalGroup_map
    (s : Finset Puncture) (i : Puncture) (x : liftedPatch none) :
    (FundamentalGroup.map (previousStageInclusion s i) (stageRegularInclusion s x)).comp
        (FundamentalGroup.map (stageRegularInclusion s) x) =
      FundamentalGroup.map (stageRegularInclusion (insert i s)) x := by
  ext γ
  obtain ⟨p⟩ := γ
  apply congrArg Path.Homotopic.Quotient.mk
  ext t
  rfl

/-- The regular patch generates every stage once each attached filling
is generated by its actual full overlap.  Basepoints are transported
inside the preceding stage, not identified by an unproved marking. -/
theorem stageRegularInclusion_fundamentalGroup_map_surjective
    (hF : ∀ i : Puncture, Function.Surjective (overlapFillingHom i))
    (s : Finset Puncture) (x : liftedPatch none) :
    Function.Surjective (FundamentalGroup.map (stageRegularInclusion s) x) := by
  induction s using Finset.induction_on with
  | empty => exact stageRegularInclusion_empty_fundamentalGroup_map_surjective x
  | @insert i s hi ih =>
    have := partialPatch_pathConnectedSpace s
    have hprev := fundamentalGroup_map_surjective_at_of_pathConnected
      (previousStageInclusion s i)
      ⟨attachmentPoint i, attachmentPoint_mem_partialPatch s i⟩
      (stageRegularInclusion s x)
      (previousStageHom_surjective_of_overlapFillingHom_surjective s i hi (hF i))
    have hcomp := hprev.comp ih
    rw [← stageRegularInclusion_insert_fundamentalGroup_map s i x]
    exact hcomp

/-- The actual inclusion of the regular lifted patch into the whole threefold. -/
def regularLiftedInclusion : C(liftedPatch none, Space) :=
  ⟨Subtype.val, continuous_subtype_val⟩

theorem regularLiftedInclusion_fundamentalGroup_map_surjective
    (hF : ∀ i : Puncture, Function.Surjective (overlapFillingHom i))
    (x : liftedPatch none) :
    Function.Surjective (FundamentalGroup.map regularLiftedInclusion x) := by
  have hstage := stageRegularInclusion_fundamentalGroup_map_surjective hF Finset.univ x
  have hfull := (fullStageFundamentalGroupEquiv
    (stageRegularInclusion Finset.univ x)).surjective
  have hmap :
      (fullStageFundamentalGroupEquiv
        (stageRegularInclusion Finset.univ x)).toMonoidHom.comp
          (FundamentalGroup.map (stageRegularInclusion Finset.univ) x) =
        FundamentalGroup.map regularLiftedInclusion x := by
    ext γ
    obtain ⟨p⟩ := γ
    apply congrArg Path.Homotopic.Quotient.mk
    ext t
    rfl
  rw [← hmap]
  exact hfull.comp hstage

end Wikipedia.HopfProblem.SpecialPeriods.Threefold
