import Wikipedia.HopfProblem.ThreefoldHomologyCuspFibre
import Wikipedia.HopfProblem.TrianglePeriodFamilyBoundaryEllipticCapProductHomologyFilling
import Wikipedia.HopfProblem.ThreefoldHomologySecondCokernel

/-!
# Eliminate the actual filling coordinates from second homology

Every original overlap maps onto the homology of its original filling.
The genuine star-cover exact sequence therefore identifies the kernel
of the original regular inclusion with the regular image of the actual
filling kernel.  In degree two the proved surjectivity of the original
piece-inclusion map lets every class be represented by the regular
piece alone, after subtracting an actual signed overlap class.

The resulting quotient equivalence is induced by the literal regular
inclusion.  No boundary matrix or vanishing of this quotient is assumed.
-/

noncomputable section

namespace Wikipedia.HopfProblem.SpecialPeriods.Threefold.Homology.CapElimination

open SingularMayerVietoris PeriodTorusHigherHomology ThreefoldOverlapMappingTorus

/-- Each original boundary-to-filling coefficient is onto in every integral degree. -/
theorem boundaryFillingHomologyMap_surjective (i : Puncture) (n : ℕ) :
    Function.Surjective (boundaryFillingHomologyMap i n) := by
  cases i with
  | none => exact ThreefoldHomologyCuspFibre.boundaryFillingHomologyMap_surjective n
  | some j =>
    exact TrianglePeriodFamily.Boundary.EllipticCapProduct.boundaryFillingHomologyMap_surjective j n

/-- The same surjectivity for the literal original overlap inclusion. -/
theorem overlapToFilling_homology_surjective (i : Puncture) (n : ℕ) :
    Function.Surjective (singularHomologyMap (overlapToFilling i) n) := by
  intro a
  obtain ⟨b, hb⟩ := boundaryFillingHomologyMap_surjective i n a
  refine ⟨(overlapHomologyEquiv i n).symm b, ?_⟩
  exact (LinearMap.congr_fun (boundaryFillingHomologyMap_eq i n) b).symm.trans hb

/-- The original componentwise filling map is onto, with its native integer action. -/
theorem starOverlapToFillingsHomologyMap_surjective (n : ℕ) :
    Function.Surjective (starOverlapToFillingsHomologyMap n) := by
  classical
  intro a
  choose b hb using fun i : Puncture => overlapToFilling_homology_surjective i n (a i)
  refine ⟨b, ?_⟩
  funext i
  exact hb i

/-- Restrict the original regular coefficient to the actual filling kernel.
The additive subtype composition retains the native integer action on that kernel. -/
def capKernelRegularMap (n : ℕ) :
    LinearMap.ker (starOverlapToFillingsHomologyMap n) →ₗ[ℤ]
      SingularHomology SpecialRegularFamily n :=
  intLinearMapOfAddHom
    { toFun a := starOverlapToRegularHomologyMap n a.val
      map_zero' := (starOverlapToRegularHomologyMap n).map_zero
      map_add' a b := (starOverlapToRegularHomologyMap n).map_add a.val b.val }

@[simp] theorem capKernelRegularMap_apply (n : ℕ)
    (a : LinearMap.ker (starOverlapToFillingsHomologyMap n)) :
    capKernelRegularMap n a = starOverlapToRegularHomologyMap n a.val := rfl

/-- The actual regular classes generated by overlap classes killed by all fillings. -/
def capKernelRegularImage (n : ℕ) : Submodule ℤ (SingularHomology SpecialRegularFamily n) :=
  LinearMap.range (capKernelRegularMap n)

/-- The original signed overlap map, retaining its positive regular and negative cap components. -/
theorem starLeft_regular_fillings (n : ℕ) (a : StarOverlapHomology n) :
    starLeftHomologyMap n a =
      (starOverlapToRegularHomologyMap n a, -starOverlapToFillingsHomologyMap n a) := rfl

/-- The original right map on the regular summand is literally the regular inclusion. -/
@[simp] theorem starRight_regular (n : ℕ) (a : SingularHomology SpecialRegularFamily n) :
    starRightHomologyMap n (a, 0) = singularHomologyMap originalRegularInclusion n a := by
  change singularHomologyMap originalRegularInclusion n a + starFillingsToSpaceHomologyMap n 0 = _
  rw [map_zero, add_zero]

/-- Genuine star exactness computes the kernel of the actual regular inclusion in every degree. -/
theorem regularInclusion_kernel (n : ℕ) :
    LinearMap.ker (singularHomologyMap originalRegularInclusion n) = capKernelRegularImage n := by
  ext a
  change singularHomologyMap originalRegularInclusion n a = 0 ↔
    ∃ b : LinearMap.ker (starOverlapToFillingsHomologyMap n), capKernelRegularMap n b = a
  constructor
  · intro ha
    have hright : starRightHomologyMap n (a, 0) = 0 := (starRight_regular n a).trans ha
    obtain ⟨b, hb⟩ := (star_exact_at_pair n (a, 0)).mp hright
    have hreg : starOverlapToRegularHomologyMap n b = a := congrArg Prod.fst hb
    have hcap : starOverlapToFillingsHomologyMap n b = 0 := by
      have hneg : -starOverlapToFillingsHomologyMap n b = 0 := congrArg Prod.snd hb
      exact neg_eq_zero.mp hneg
    exact ⟨⟨b, hcap⟩, hreg⟩
  · rintro ⟨b, hb⟩
    have hcap : starOverlapToFillingsHomologyMap n b.val = 0 := b.property
    have hleft : starLeftHomologyMap n b.val = (a, 0) := by
      rw [starLeft_regular_fillings, hcap, neg_zero]
      exact Prod.ext hb rfl
    have hright := (star_exact_at_pair n).apply_apply_eq_zero b.val
    rw [hleft, starRight_regular] at hright
    exact hright

/-- The actual regular relations, stated without quotient or subtype notation. -/
theorem regularInclusion_eq_zero_iff (n : ℕ) (a : SingularHomology SpecialRegularFamily n) :
    singularHomologyMap originalRegularInclusion n a = 0 ↔
      ∃ b : StarOverlapHomology n, starOverlapToFillingsHomologyMap n b = 0 ∧
        starOverlapToRegularHomologyMap n b = a := by
  change a ∈ LinearMap.ker (singularHomologyMap originalRegularInclusion n) ↔ _
  rw [regularInclusion_kernel]
  constructor
  · rintro ⟨b, hb⟩
    exact ⟨b.val, b.property, hb⟩
  · rintro ⟨b, hcap, hreg⟩
    exact ⟨⟨b, hcap⟩, hreg⟩

/-- Every actual second homology class is represented by the regular piece alone. -/
theorem regularInclusion_two_surjective :
    Function.Surjective (singularHomologyMap originalRegularInclusion 2) := by
  intro x
  obtain ⟨p, hp⟩ := SecondDegree.starRight_two_surjective x
  obtain ⟨a, ha⟩ := starOverlapToFillingsHomologyMap_surjective 2 (-p.2)
  have hshape : p - starLeftHomologyMap 2 a =
      (p.1 - starOverlapToRegularHomologyMap 2 a, 0) := by
    rw [starLeft_regular_fillings]
    apply Prod.ext
    · rfl
    · change p.2 - -starOverlapToFillingsHomologyMap 2 a = 0
      rw [ha, neg_neg, sub_self]
  refine ⟨p.1 - starOverlapToRegularHomologyMap 2 a, ?_⟩
  calc
    singularHomologyMap originalRegularInclusion 2
        (p.1 - starOverlapToRegularHomologyMap 2 a) =
        starRightHomologyMap 2 (p.1 - starOverlapToRegularHomologyMap 2 a, 0) :=
      (starRight_regular 2 _).symm
    _ = starRightHomologyMap 2 (p - starLeftHomologyMap 2 a) :=
      congrArg (starRightHomologyMap 2) hshape.symm
    _ = starRightHomologyMap 2 p - starRightHomologyMap 2 (starLeftHomologyMap 2 a) :=
      map_sub _ _ _
    _ = x := by rw [hp, (star_exact_at_pair 2).apply_apply_eq_zero a, sub_zero]

private def regularCapKernelCokernelAddEquiv :
    (SingularHomology SpecialRegularFamily 2 ⧸ capKernelRegularImage 2) ≃+
      SingularHomology Space 2 := by
  letI := Submodule.Quotient.module (capKernelRegularImage 2)
  letI := Submodule.Quotient.module (LinearMap.ker (singularHomologyMap originalRegularInclusion 2))
  exact (Submodule.quotEquivOfEq _ _ (regularInclusion_kernel 2).symm).toAddEquiv.trans
    ((singularHomologyMap originalRegularInclusion 2).quotKerEquivOfSurjective
      regularInclusion_two_surjective).toAddEquiv

/-- The remaining genuine regular-family quotient is actual second integral homology. -/
def regularCapKernelCokernelEquiv :
    (SingularHomology SpecialRegularFamily 2 ⧸ capKernelRegularImage 2) ≃ₗ[ℤ]
      SingularHomology Space 2 :=
  regularCapKernelCokernelAddEquiv.toIntLinearEquiv

/-- The quotient equivalence is exactly the homology map of the original regular inclusion. -/
@[simp] theorem regularCapKernelCokernelEquiv_mk (a : SingularHomology SpecialRegularFamily 2) :
    regularCapKernelCokernelEquiv (Submodule.Quotient.mk a) =
      singularHomologyMap originalRegularInclusion 2 a := rfl

@[simp] theorem regularCapKernelCokernelEquiv_symm_inclusion
    (a : SingularHomology SpecialRegularFamily 2) :
    regularCapKernelCokernelEquiv.symm (singularHomologyMap originalRegularInclusion 2 a) =
      Submodule.Quotient.mk a :=
  regularCapKernelCokernelEquiv.symm_apply_apply (Submodule.Quotient.mk a)

end Wikipedia.HopfProblem.SpecialPeriods.Threefold.Homology.CapElimination
