import Wikipedia.HopfProblem.ThreefoldHomologyThirdCyclic

/-!
# The genuine integral residual relation in third homology

The full regular image of the original positive reference tuple lies
in the original primitive fibre copy of the integers.  Its unique
coefficient is defined using that actual image, not a replacement
attachment matrix.  Exactness proves that this coefficient generates
all relations on the genuine global third-homology generator.

This identifies the remaining coefficient without claiming a numerical
value for it; its evaluation requires the actual boundary geometry.
-/

noncomputable section

namespace Wikipedia.HopfProblem.SpecialPeriods.Threefold.Homology.ThirdDegree

open SingularMayerVietoris PeriodTorusHigherHomology TrianglePeriodFamily
open TrianglePeriodFamily.Homology CapElimination

local notation "Dsp" =>
  regularData specialPeriodMap specialPeriodMap_generator₁ specialPeriodMap_generator₂

/-- The full original regular reference image has a unique primitive fibre coefficient. -/
theorem existsUnique_referenceFibreCoefficient :
    ∃! z : ℤ, thirdFibreCyclicMap z = nativeCapKernelRegularMap 3 referenceClasses := by
  have hr : nativeCapKernelRegularMap 3 referenceClasses ∈
      LinearMap.ker (sourceKernelProjection Dsp 2) := referenceClasses_source_eq_zero
  rw [sourceKernelProjection_kernel, thirdFibre_range_eq] at hr
  obtain ⟨z, hz⟩ := hr
  refine ⟨z, hz, ?_⟩
  intro w hw
  exact thirdFibreCyclicMap_injective (hw.trans hz.symm)

/-- The integer defined by the actual full regular attachment of the original reference tuple. -/
def referenceFibreCoefficient : ℤ :=
  Classical.choose existsUnique_referenceFibreCoefficient

/-- This is an equality of original regular homology classes, not merely source coordinates. -/
theorem referenceFibreCoefficient_spec :
    thirdFibreCyclicMap referenceFibreCoefficient =
      nativeCapKernelRegularMap 3 referenceClasses :=
  (Classical.choose_spec existsUnique_referenceFibreCoefficient).1

/-- Any genuine geometric evaluation determines exactly this coefficient. -/
theorem referenceFibreCoefficient_eq_iff (z : ℤ) :
    referenceFibreCoefficient = z ↔
      nativeCapKernelRegularMap 3 referenceClasses = thirdFibreCyclicMap z := by
  rw [← referenceFibreCoefficient_spec]
  exact thirdFibreCyclicMap_injective.eq_iff.symm

/-- The full original reference multiples retain their actual integral fibre coefficients. -/
theorem nativeCapKernelRegularMap_smul_reference (k : ℤ) :
    nativeCapKernelRegularMap 3 (k • referenceClasses) =
      thirdFibreCyclicMap (k * referenceFibreCoefficient) := by
  rw [map_zsmul, ← referenceFibreCoefficient_spec, ← map_zsmul]
  rfl

/-- The actual global generator is annihilated by the genuine residual coefficient. -/
theorem homologyThreeCyclicMap_referenceFibreCoefficient :
    homologyThreeCyclicMap referenceFibreCoefficient = 0 := by
  rw [homologyThreeCyclicMap_regular, referenceFibreCoefficient_spec]
  exact (regularInclusion_eq_zero_iff_native 3 _).mpr ⟨referenceClasses, rfl⟩

/-- These are exactly all integral relations on the original global fibre generator. -/
theorem homologyThreeCyclicMap_eq_zero_iff (z : ℤ) :
    homologyThreeCyclicMap z = 0 ↔ ∃ k : ℤ, k * referenceFibreCoefficient = z := by
  constructor
  · intro hz
    obtain ⟨a, ha⟩ := (regularInclusion_eq_zero_iff_native 3 (thirdFibreCyclicMap z)).mp hz
    have hs : nativeCapKernelSourceMap 2 a = 0 :=
      (congrArg (sourceKernelProjection Dsp 2) ha).trans
        (thirdFibreCyclicMap_source_eq_zero z)
    obtain ⟨k, rfl⟩ := ThirdSource.nativeCapKernelSourceMap_two_eq_zero_exists a hs
    rw [nativeCapKernelRegularMap_smul_reference] at ha
    exact ⟨k, thirdFibreCyclicMap_injective ha⟩
  · rintro ⟨k, rfl⟩
    change homologyThreeCyclicMap (k • referenceFibreCoefficient) = 0
    rw [map_zsmul, homologyThreeCyclicMap_referenceFibreCoefficient]
    exact @zsmul_zero (SingularHomology Space 3) _ k

/-- The literal kernel of the original cyclic map is generated by its genuine residual integer. -/
theorem homologyThreeCyclicMap_ker :
    LinearMap.ker homologyThreeCyclicMap = Submodule.span ℤ {referenceFibreCoefficient} := by
  ext z
  rw [LinearMap.mem_ker, homologyThreeCyclicMap_eq_zero_iff, Submodule.mem_span_singleton]
  rfl

/-- Third homology is exactly the integer quotient by the actual original residual relation. -/
def homologyThreeResidualCokernelEquiv :
    (ℤ ⧸ Submodule.span ℤ {referenceFibreCoefficient}) ≃ₗ[ℤ] SingularHomology Space 3 :=
  ((Submodule.quotEquivOfEq _ _ homologyThreeCyclicMap_ker.symm).toAddEquiv.trans
    (homologyThreeCyclicMap.quotKerEquivOfSurjective
      homologyThreeCyclicMap_surjective).toAddEquiv).toIntLinearEquiv

/-- The quotient map is induced by the literal original fibre inclusion. -/
@[simp] theorem homologyThreeResidualCokernelEquiv_mk (z : ℤ) :
    homologyThreeResidualCokernelEquiv (Submodule.Quotient.mk z) = homologyThreeCyclicMap z := rfl

/-- The kernel of the full native third relation map is determined by the same actual integer. -/
theorem nativeCapKernelRegularMap_three_eq_zero_iff
    (a : ∀ i : Puncture, NativeCapKernel i 3) :
    nativeCapKernelRegularMap 3 a = 0 ↔
      ∃ k : ℤ, a = k • referenceClasses ∧ k * referenceFibreCoefficient = 0 := by
  constructor
  · intro ha
    have hs : nativeCapKernelSourceMap 2 a = 0 := by
      rw [nativeCapKernelSourceMap_apply, ha, map_zero]
    obtain ⟨k, hk⟩ := ThirdSource.nativeCapKernelSourceMap_two_eq_zero_exists a hs
    refine ⟨k, hk, ?_⟩
    rw [hk, nativeCapKernelRegularMap_smul_reference] at ha
    exact (thirdFibreCyclicMap_eq_zero_iff _).mp ha
  · rintro ⟨k, rfl, hk⟩
    rw [nativeCapKernelRegularMap_smul_reference, hk, map_zero]

end Wikipedia.HopfProblem.SpecialPeriods.Threefold.Homology.ThirdDegree
