import Wikipedia.HopfProblem.ToricHolomorphicSheafCohomologyOpenRestrictionGlobal

/-!
# Genuine cohomology of an open subspace

Mathlib's cohomology presheaf at an actual open U is defined by Ext from
the free abelian sheaf generated by U. Its actual canonical representing
map and exact, injective-preserving restriction identify this group in
every degree with genuine sheaf cohomology on the open subspace.

Both sides are the existing Mathlib Ext groups. This does not define
cohomology by a chart complex or assume a comparison theorem.
-/

noncomputable section

open TopologicalSpace Opposite CategoryTheory CategoryTheory.Limits CategoryTheory.Abelian

namespace Wikipedia.HopfProblem.HolomorphicSheafCohomology.OpenRestriction

open CuspNormalization.SheafCohomologyFinitePushforward

variable {X : TopCat.{0}} (U : Opens X)

/-- Degree zero of the actual cohomology presheaf is the actual
section group, by free sheafification and Yoneda. -/
def zeroEquiv (F : TopCat.Sheaf AddCommGrpCat.{0} X) :
    CategoryTheory.Sheaf.H'.{0} F 0 U ≃+ F.obj.obj (op U) :=
  (Ext.addEquiv₀ (C := TopCat.Sheaf AddCommGrpCat.{0} X)
    (X := freeOpen U) (Y := F)).trans (freeHomAddEquiv U F)

/-- The canonical exact-restriction map on actual Ext groups. -/
def cohomologyForward (F : TopCat.Sheaf AddCommGrpCat.{0} X) (n : ℕ) :
    CategoryTheory.Sheaf.H'.{0} F n U →+
      CategoryTheory.Sheaf.H.{0} ((restriction U).obj F) n :=
  ExtComparison.comparison (restriction U) (representingUnit U) F n

/-- The actual comparison is bijective in every degree, by injective
presentations and the proved degree-zero representation. -/
theorem cohomologyForward_bijective (F : TopCat.Sheaf AddCommGrpCat.{0} X) (n : ℕ) :
    Function.Bijective (cohomologyForward U F n) :=
  ExtComparison.comparison_bijective (restriction U) (representingUnit U)
    (representingUnit_bijective U) F n

/-- Genuine Ext-defined cohomology of an open is genuine cohomology of
the actual restricted sheaf on the open subspace, in every degree. -/
def cohomologyEquiv (F : TopCat.Sheaf AddCommGrpCat.{0} X) (n : ℕ) :
    CategoryTheory.Sheaf.H'.{0} F n U ≃+
      CategoryTheory.Sheaf.H.{0} ((restriction U).obj F) n :=
  AddEquiv.ofBijective (cohomologyForward U F n) (cohomologyForward_bijective U F n)

theorem cohomologyEquiv_mk₀ {F : TopCat.Sheaf AddCommGrpCat.{0} X}
    (h : freeOpen U ⟶ F) :
    cohomologyEquiv U F 0 (Ext.mk₀ h) =
      Ext.mk₀ (representingUnit U ≫ (restriction U).map h) :=
  ExtComparison.comparison_mk₀ (restriction U) (representingUnit U) h

/-- The comparison commutes with the actual sheaf maps on both Ext
cohomology constructions. -/
theorem cohomologyEquiv_naturality {F G : TopCat.Sheaf AddCommGrpCat.{0} X}
    (g : F ⟶ G) (n : ℕ) (x : CategoryTheory.Sheaf.H'.{0} F n U) :
    cohomologyEquiv U G n
        (((CategoryTheory.Sheaf.cohomologyPresheafFunctor
          (Opens.grothendieckTopology X) n).map g).app (op U) x) =
      CategoryTheory.Sheaf.H.map ((restriction U).map g) n (cohomologyEquiv U F n x) := by
  exact ExtComparison.comparison_naturality (restriction U) (representingUnit U) g x

end Wikipedia.HopfProblem.HolomorphicSheafCohomology.OpenRestriction
