import Wikipedia.HopfProblem.SpecialPeriodsTriangleCuspStabilizer
import Wikipedia.HopfProblem.TrianglePeriodFamilyBoundaryEllipticTailHomology

/-!
# The cusp centralizer and its action on invariant classes

A real special-linear lift whose Möbius transformation commutes with the
literal cusp translation is upper triangular.  The proved cusp stabilizer
calculation then identifies its abstract triangle element as an integer
power of the original cusp generator.  Consequently every such element
fixes every class invariant under that generator, in any degree of actual
integral singular homology.

These are generic centralizer statements.  No assertion about a geometric
attaching tail, or a boundary map, is built into their hypotheses.
-/

noncomputable section

open scoped MatrixGroups

namespace Wikipedia.HopfProblem.TrianglePeriodFamily.Boundary

open SpecialPeriods SpecialPeriods.Triangle Homology SingularMayerVietoris

/-- Commutation with the actual nontrivial cusp translation forces a
special-linear lift to be upper triangular, irrespective of its central sign. -/
theorem realSLPermutation_commute_cusp_lower_left (A : SL(2, ℝ))
    (h : Commute (realSLPermutation cuspSL) (realSLPermutation A)) :
    A 1 0 = 0 := by
  have he : realSLPermutation (cuspSL * A) = realSLPermutation (A * cuspSL) := by
    simpa only [map_mul] using h.eq
  rcases (realSLPermutation_eq_iff (cuspSL * A) (A * cuspSL)).mp he with hp | hm
  · have he₀ := congrArg (fun B : SL(2, ℝ) => B 0 0) hp
    simp only [Matrix.SpecialLinearGroup.coe_mul, coe_cuspSL, Matrix.mul_apply,
      Fin.sum_univ_two, Matrix.of_apply, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_fin_one, one_mul, mul_one, mul_zero, add_zero] at he₀
    have hz : width * A 1 0 = 0 := by linarith
    exact (mul_eq_zero.mp hz).resolve_left width_ne_zero
  · have he₁ := congrArg (fun B : SL(2, ℝ) => B 1 0) hm
    simp only [Matrix.SpecialLinearGroup.coe_mul, coe_cuspSL,
      Matrix.SpecialLinearGroup.coe_neg, Matrix.neg_apply, Matrix.mul_apply,
      Fin.sum_univ_two, Matrix.of_apply, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_fin_one, one_mul, zero_mul, mul_one, mul_zero,
      zero_add, add_zero] at he₁
    linarith

/-- Every element commuting with the literal cusp generator belongs to
the cyclic subgroup generated by that same element. -/
theorem triangleCuspGenerator_commute_mem_zpowers (g : TriangleGroup)
    (h : Commute triangleCuspGenerator g) :
    g ∈ Subgroup.zpowers triangleCuspGenerator := by
  obtain ⟨A, hA⟩ := triangleGeometricRepresentation_matrixGroup_lift g
  apply (triangleGeometric_upperTriangular_lift_iff g A hA).mp
  apply realSLPermutation_commute_cusp_lower_left
  rw [hA, ← triangleGeometricRepresentation_cusp]
  exact h.map triangleGeometricRepresentation

/-- The centralizer has no additional deck frames beyond integer powers
of the original cusp generator. -/
theorem triangleCuspGenerator_commute_eq_zpow (g : TriangleGroup)
    (h : Commute triangleCuspGenerator g) :
    ∃ k : ℤ, g = triangleCuspGenerator ^ k := by
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp
    (triangleCuspGenerator_commute_mem_zpowers g h)
  exact ⟨k, hk.symm⟩

/-- This cyclic subgroup is exactly the cusp generator's centralizer. -/
theorem triangleCuspGenerator_commute_iff (g : TriangleGroup) :
    Commute triangleCuspGenerator g ↔ g ∈ Subgroup.zpowers triangleCuspGenerator := by
  constructor
  · exact triangleCuspGenerator_commute_mem_zpowers g
  · rintro hg
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hg
    exact (Commute.refl triangleCuspGenerator).zpow_right k

/-- In any actual triangle action a cusp-invariant point is fixed by
every element of the cusp centralizer. -/
theorem cuspCentralizer_smul_fixed {A : Type*} [MulAction TriangleGroup A]
    (g : TriangleGroup) (h : Commute triangleCuspGenerator g)
    (a : A) (ha : triangleCuspGenerator • a = a) : g • a = a := by
  have hs : Subgroup.zpowers triangleCuspGenerator ≤ MulAction.stabilizer TriangleGroup a :=
    Subgroup.zpowers_le_of_mem (MulAction.mem_stabilizer_iff.mpr ha)
  exact MulAction.mem_stabilizer_iff.mp
    (hs (triangleCuspGenerator_commute_mem_zpowers g h))

/-- The inverse of a commuting deck frame fixes the same invariant point. -/
theorem cuspCentralizer_inv_smul_fixed {A : Type*} [MulAction TriangleGroup A]
    (g : TriangleGroup) (h : Commute triangleCuspGenerator g)
    (a : A) (ha : triangleCuspGenerator • a = a) : g⁻¹ • a = a :=
  cuspCentralizer_smul_fixed g⁻¹ h.inv_right a ha

/-- Integer powers of an actual triangle homeomorphism fix every actual
homology class fixed by that homeomorphism. -/
theorem triangleHomologyEquiv_zpow_fixed (g : TriangleGroup) (n : ℕ)
    (a : SingularHomology RealTorus₄ n) (ha : triangleHomologyEquiv g n a = a)
    (k : ℤ) : triangleHomologyEquiv (g ^ k) n a = a := by
  cases k with
  | ofNat k =>
    simpa only [Int.ofNat_eq_natCast, zpow_natCast] using triangleHomologyEquiv_pow_fixed g n a ha k
  | negSucc k =>
    rw [zpow_negSucc, triangleHomologyEquiv_inv]
    apply (triangleHomologyEquiv (g ^ (k + 1)) n).injective
    rw [LinearEquiv.apply_symm_apply, triangleHomologyEquiv_pow_fixed g n a ha]

/-- In every degree the cusp centralizer fixes the invariant subgroup
of actual integral singular homology. -/
theorem cuspCentralizer_homology_fixed (g : TriangleGroup)
    (h : Commute triangleCuspGenerator g) (n : ℕ)
    (a : SingularHomology RealTorus₄ n)
    (ha : triangleHomologyEquiv triangleCuspGenerator n a = a) :
    triangleHomologyEquiv g n a = a := by
  obtain ⟨k, hk⟩ := triangleCuspGenerator_commute_eq_zpow g h
  rw [hk]
  exact triangleHomologyEquiv_zpow_fixed triangleCuspGenerator n a ha k

/-- The inverse deck-frame change also fixes every actual cusp-invariant class. -/
theorem cuspCentralizer_inv_homology_fixed (g : TriangleGroup)
    (h : Commute triangleCuspGenerator g) (n : ℕ)
    (a : SingularHomology RealTorus₄ n)
    (ha : triangleHomologyEquiv triangleCuspGenerator n a = a) :
    triangleHomologyEquiv g⁻¹ n a = a :=
  cuspCentralizer_homology_fixed g⁻¹ h.inv_right n a ha

end Wikipedia.HopfProblem.TrianglePeriodFamily.Boundary
