import StackExchange.Puzzling139335.SquareSymmetry

#print axioms Puzzling139335.SquareSymmetry.preserves_square_of_corner_neighborhood
#print axioms Puzzling139335.SquareSymmetry.center_fixed_of_corner_neighborhood
#print axioms Puzzling139335.SquareSymmetry.side_rigidity_unordered
#print axioms Puzzling139335.SquareSymmetry.exists_corner_permutation_of_maps_square_into_square
#print axioms Puzzling139335.SquareSymmetry.coordinate_forms_of_maps_square_into_square
#print axioms Puzzling139335.SquareDissection.unique_corner_congruence_preserves_square
#print axioms Puzzling139335.SquareDissection.center_not_mem_unique_corner_pair
#print axioms Puzzling139335.SquareDissection.center_not_mem_side_pair
#print axioms Puzzling139335.SquareDissection.not_protectedCenter_of_square_placements
