import Mathlib
import CebotarevDensity.Frobenius

/-!
# Algebraic input for the completely-split prime transfer

This file records the elementary algebraic facts used to pass from prime
ideals of a Galois number field `L / ℚ` to rational primes.  In particular,
the norm of a prime ideal is a power of the rational prime below it, and an
unramified prime has residue degree one precisely when its Frobenius class is
the identity class.
-/

namespace Erdos980.NaturalChebotarev.SplitTransfer

open NumberField Chebotarev

noncomputable section

variable (L : Type*) [Field L] [NumberField L] [Algebra ℚ L] [IsGalois ℚ L]

/-- The prime ideal of `𝒪 ℚ` associated with a natural number. -/
def rationalIdeal (p : ℕ) : Ideal (𝓞 ℚ) := Ideal.span {(p : 𝓞 ℚ)}

/-- The absolute norm of the rational ideal `(p)` is `p`. -/
theorem absNorm_rationalIdeal (p : ℕ) : Ideal.absNorm (rationalIdeal p) = p := by
  rw [rationalIdeal, Ideal.absNorm_span_natCast, NumberField.RingOfIntegers.rank,
    Module.finrank_self, pow_one]

private theorem rationalIdeal_eq_comap_intSpan (p : ℕ) :
    rationalIdeal p =
      Ideal.comap Rat.ringOfIntegersEquiv (Ideal.span {(p : ℤ)}) := by
  rw [rationalIdeal, ← Ideal.map_symm Rat.ringOfIntegersEquiv, Ideal.map_span,
    Set.image_singleton]
  congr 2
  simp [map_natCast]

/-- The ideal `(p)` of `𝒪 ℚ` is prime when `p` is a rational prime. -/
theorem rationalIdeal_isPrime {p : ℕ} (hp : p.Prime) : (rationalIdeal p).IsPrime := by
  have : (Ideal.span {(p : ℤ)}).IsPrime :=
    (Ideal.span_singleton_prime (by exact_mod_cast hp.ne_zero)).mpr
      (Nat.prime_iff_prime_int.mp hp)
  rw [rationalIdeal_eq_comap_intSpan]
  exact Ideal.comap_isPrime Rat.ringOfIntegersEquiv (Ideal.span {(p : ℤ)})

/-- Every nonzero prime ideal of `𝒪 ℚ` is generated by a unique rational
prime; the generator is its absolute norm. -/
theorem rational_prime_eq_rationalIdeal_absNorm
    (p : Ideal (𝓞 ℚ)) (hp : p.IsPrime) (hne : p ≠ ⊥) :
    p = rationalIdeal (Ideal.absNorm p) ∧ (Ideal.absNorm p).Prime := by
  let e := Rat.ringOfIntegersEquiv
  have hbij : Function.Bijective e := e.bijective
  have hJp : (Ideal.map e p).IsPrime := Ideal.map_isPrime_of_equiv e
  have hcomap : Ideal.comap e (Ideal.map e p) = p :=
    Ideal.comap_map_of_bijective e hbij
  have hJne : Ideal.map e p ≠ ⊥ := by
    intro h
    apply hne
    rw [← hcomap, h, Ideal.comap_bot_of_injective e hbij.injective]
  rcases Ideal.isPrime_int_iff.mp hJp with hbot | ⟨q, hq, hqeq⟩
  · exact (hJne hbot).elim
  · have hpq : p = rationalIdeal q := by
      rw [← hcomap, hqeq, rationalIdeal_eq_comap_intSpan]
    have hnorm : Ideal.absNorm p = q := by
      rw [hpq, absNorm_rationalIdeal]
    refine ⟨?_, hnorm.symm ▸ hq⟩
    calc
      p = rationalIdeal q := hpq
      _ = rationalIdeal (Ideal.absNorm p) := by rw [hnorm]

/-- The rational prime below a nonzero prime ideal of `L`. -/
def primeBelow (P : Ideal (𝓞 L)) : ℕ :=
  Ideal.absNorm (P.under (𝓞 ℚ))

/-- The residue degree of a prime ideal of `L` over `ℚ`. -/
def residueDegree (P : Ideal (𝓞 L)) : ℕ :=
  (P.under (𝓞 ℚ)).inertiaDeg' P

/-- A rational prime splits completely in `L` when it is unramified and its
Frobenius conjugacy class is the identity class. -/
def IsCompletelySplit (p : ℕ) : Prop :=
  p.Prime ∧ UnramifiedIn ℚ L (rationalIdeal p) ∧
    frobeniusClass ℚ L (rationalIdeal p) = ConjClasses.mk 1

/-- The ideal below a nonzero prime `P` is generated by `primeBelow P`, and
that natural number is prime. -/
theorem under_eq_rationalIdeal_primeBelow
    {P : Ideal (𝓞 L)} (hP : P.IsPrime) (hP0 : P ≠ ⊥) :
    P.under (𝓞 ℚ) = rationalIdeal (primeBelow L P) ∧ (primeBelow L P).Prime := by
  have : P.IsPrime := hP
  have hp0 : P.under (𝓞 ℚ) ≠ ⊥ := Ideal.under_ne_bot (A := 𝓞 ℚ) hP0
  exact rational_prime_eq_rationalIdeal_absNorm _ inferInstance hp0

/-- For a nonzero prime ideal `P`, `N P = p^f`, where `p` is the rational
prime below `P` and `f` is its residue degree. -/
theorem absNorm_eq_primeBelow_pow_residueDegree
    {P : Ideal (𝓞 L)} (hP : P.IsPrime) (hP0 : P ≠ ⊥) :
    Ideal.absNorm P = primeBelow L P ^ residueDegree L P := by
  have : P.IsPrime := hP
  have : P.LiesOver (P.under (𝓞 ℚ)) :=
    Ideal.over_under (A := 𝓞 ℚ) (P := P)
  have hp0 : P.under (𝓞 ℚ) ≠ ⊥ := Ideal.under_ne_bot (A := 𝓞 ℚ) hP0
  exact Ideal.absNorm_eq_pow_inertiaDeg'_of_liesOver
    P (P.under (𝓞 ℚ)) inferInstance hp0

/-- A degree-one prime ideal above an unramified rational prime forces that
rational prime to split completely. -/
theorem isCompletelySplit_primeBelow_of_residueDegree_eq_one
    {P : Ideal (𝓞 L)} (hP : P.IsPrime) (hP0 : P ≠ ⊥)
    (hunr : UnramifiedIn ℚ L (P.under (𝓞 ℚ)))
    (hdeg : residueDegree L P = 1) :
    IsCompletelySplit L (primeBelow L P) := by
  have : P.IsPrime := hP
  have : P.LiesOver (P.under (𝓞 ℚ)) :=
    Ideal.over_under (A := 𝓞 ℚ) (P := P)
  obtain ⟨hunder, hp⟩ := under_eq_rationalIdeal_primeBelow L hP hP0
  let C := frobeniusClass ℚ L (P.under (𝓞 ℚ))
  have hfinrank :
      Module.finrank (𝓞 ℚ ⧸ P.under (𝓞 ℚ)) (𝓞 L ⧸ P) = orderOf C.out := by
    exact finrank_residue_eq_orderOf ℚ L C.out C (Quotient.out_eq C)
      (P.under (𝓞 ℚ)) hunr rfl P inferInstance
  have hord : orderOf C.out = 1 := by
    rw [← hfinrank, ← Ideal.inertiaDeg'_algebraMap]
    exact hdeg
  have hout : C.out = 1 := orderOf_eq_one_iff.mp hord
  have hC : C = ConjClasses.mk (1 : Gal(L/ℚ)) := by
    calc
      C = ConjClasses.mk C.out := (Quotient.out_eq C).symm
      _ = ConjClasses.mk 1 := congrArg ConjClasses.mk hout
  refine ⟨hp, hunder ▸ hunr, ?_⟩
  rw [← hunder]
  exact hC

/-- Every prime ideal above a completely split rational prime has residue
degree one. -/
theorem residueDegree_eq_one_of_isCompletelySplit
    {p : ℕ} (hsplit : IsCompletelySplit L p)
    {P : Ideal (𝓞 L)} (hP : P.IsPrime) (hP0 : P ≠ ⊥)
    (hlo : P.LiesOver (rationalIdeal p)) :
    residueDegree L P = 1 := by
  have : P.IsPrime := hP
  let : (rationalIdeal p).IsPrime := rationalIdeal_isPrime hsplit.1
  have : P.LiesOver (rationalIdeal p) := hlo
  have hunder : P.under (𝓞 ℚ) = rationalIdeal p := hlo.over.symm
  have hfinrank := finrank_residue_eq_orderOf ℚ L (1 : Gal(L/ℚ))
    (ConjClasses.mk (1 : Gal(L/ℚ))) rfl (rationalIdeal p) hsplit.2.1 hsplit.2.2 P hlo
  rw [orderOf_one, ← Ideal.inertiaDeg'_algebraMap] at hfinrank
  simpa [residueDegree, hunder] using hfinrank

/-- Exactly `[L : ℚ]` prime ideals lie above a completely split rational
prime. -/
theorem card_primesAbove_of_isCompletelySplit
    {p : ℕ} (hsplit : IsCompletelySplit L p) :
    Nat.card {P : Ideal (𝓞 L) //
      P.IsPrime ∧ P.LiesOver (rationalIdeal p) ∧ P ≠ ⊥} =
      Module.finrank ℚ L := by
  let : (rationalIdeal p).IsPrime := rationalIdeal_isPrime hsplit.1
  have h := card_primesAbove_mul_orderOf_eq ℚ L (1 : Gal(L/ℚ))
    (ConjClasses.mk (1 : Gal(L/ℚ))) rfl (rationalIdeal p) hsplit.2.1 hsplit.2.2
  rw [orderOf_one, mul_one] at h
  exact h.trans (IsGalois.card_aut_eq_finrank ℚ L)

end

end Erdos980.NaturalChebotarev.SplitTransfer
