import Wikipedia.HomotopyGroupsOfSpheres.SamelsonBilinear
import Wikipedia.HomotopyGroupsOfSpheres.SamelsonNullhomotopy
import Wikipedia.HomotopyGroupsOfSpheres.Reindex
import Wikipedia.HomotopyGroupsOfSpheres.SphereThree
import Wikipedia.HopfProblem.UnitQuaternionSphere
import Wikipedia.HopfProblem.HomotopyGroupPowerMap

/-!
# The quaternion Samelson class in the actual sixth homotopy group

The generator of `π₃(S³)` supplied by the proved Hurewicz calculation
defines a class by its Samelson square. Integer bilinearity shows that
all Samelson products of third homotopy classes are powers of this class.

The assertions that this class generates the whole sixth homotopy group
and that its order is twelve are not assumed and remain to be proved.
-/

noncomputable section

open scoped Topology

namespace Wikipedia.HomotopyGroupsOfSpheres.QuaternionSamelson

open HopfProblem.UnitQuaternionSphere

/-- A proved integral marking of the third homotopy group of unit quaternions. -/
def degreeEquiv : π_ 3 UnitQuaternions 1 ≃* Multiplicative ℤ :=
  (homeomorphMulEquiv (N := Fin 3) sphereHomeomorph 1).trans
    (pi3_sphere_three_mulEquiv (sphereHomeomorph 1))

/-- A generator of the actual third homotopy group, with integral degree one. -/
def fundamentalClass : π_ 3 UnitQuaternions 1 := degreeEquiv.symm (Multiplicative.ofAdd 1)

@[simp] theorem degree_fundamentalClass :
    degreeEquiv fundamentalClass = Multiplicative.ofAdd 1 := degreeEquiv.apply_symm_apply _

theorem fundamentalClass_zpow_degree (a : π_ 3 UnitQuaternions 1) :
    fundamentalClass ^ (degreeEquiv a).toAdd = a := by
  apply degreeEquiv.injective
  rw [map_zpow, degree_fundamentalClass]
  change (degreeEquiv a).toAdd • (1 : ℤ) = (degreeEquiv a).toAdd
  simp

/-- Reindex the two blocks of three coordinates as the standard six-cube. -/
def sixCoordinates :
    HomotopyGroup (Fin 3 ⊕ Fin 3) UnitQuaternions 1 ≃* π_ 6 UnitQuaternions 1 :=
  reindexMulEquiv 1 finSumFinEquiv

/-- The native degree `(3,3)` Samelson product with the standard `Fin 6` indexing. -/
def pairing (a b : π_ 3 UnitQuaternions 1) : π_ 6 UnitQuaternions 1 :=
  sixCoordinates (Samelson.product a b)

/-- The Samelson square of a proved degree-one class. No order is asserted here. -/
def nu : π_ 6 UnitQuaternions 1 := pairing fundamentalClass fundamentalClass

/-- A genuine based cubical representative of the degree-one class. -/
def fundamentalLoop : GenLoop (Fin 3) UnitQuaternions 1 := Quotient.out fundamentalClass

theorem fundamentalLoop_class : (⟦fundamentalLoop⟧ : π_ 3 UnitQuaternions 1) =
    fundamentalClass := Quotient.out_eq _

/-- The commutator representative on the standard six-cube. -/
def nuLoop : GenLoop (Fin 6) UnitQuaternions 1 :=
  GenLoop.congr 1 finSumFinEquiv (Samelson.loop fundamentalLoop fundamentalLoop)

theorem nuLoop_class : (⟦nuLoop⟧ : π_ 6 UnitQuaternions 1) = nu := by
  change sixCoordinates
      (Samelson.product (⟦fundamentalLoop⟧ : π_ 3 UnitQuaternions 1) ⟦fundamentalLoop⟧) = nu
  rw [fundamentalLoop_class]
  rfl

/-- Exact torsion of the distinguished class is a statement about actual relative homotopies. -/
theorem nu_pow_eq_one_iff (k : ℕ) : nu ^ k = 1 ↔
    GenLoop.Homotopic (HopfProblem.HomotopyGroupPowerMap.powLoop nuLoop k) GenLoop.const := by
  have hclass := HopfProblem.HomotopyGroupPowerMap.class_powLoop nuLoop k
  rw [nuLoop_class] at hclass
  constructor
  · intro h
    exact Quotient.exact (hclass.trans h)
  · intro h
    exact hclass.symm.trans (Quotient.sound h)

/-- This uses an actual commutator null-homotopy; it does not supply that geometric input. -/
theorem nu_pow_eq_one_of_commutator_nullhomotopy (k : ℕ)
    (h : (Samelson.commutatorMap (G := UnitQuaternions) ^ k).Homotopic
      (ContinuousMap.const _ 1)) : nu ^ k = 1 := by
  have hh := Samelson.product_pow_eq_one_of_nullhomotopy k h fundamentalClass fundamentalClass
  change sixCoordinates (Samelson.product fundamentalClass fundamentalClass) ^ k = 1
  exact (map_pow sixCoordinates _ k).symm.trans
    ((congrArg sixCoordinates hh).trans (map_one sixCoordinates))

theorem pairing_zpow_zpow (a b : π_ 3 UnitQuaternions 1) (k l : ℤ) :
    pairing (a ^ k) (b ^ l) = pairing a b ^ (k * l) := by
  unfold pairing
  rw [Samelson.product_zpow_zpow, map_zpow]

/-- Every Samelson product is the expected integer multiple of the distinguished class. -/
theorem pairing_eq_nu_zpow (a b : π_ 3 UnitQuaternions 1) :
    pairing a b = nu ^ ((degreeEquiv a).toAdd * (degreeEquiv b).toAdd) := by
  conv_lhs => rw [← fundamentalClass_zpow_degree a, ← fundamentalClass_zpow_degree b]
  exact pairing_zpow_zpow fundamentalClass fundamentalClass _ _

/-- The distinguished class transferred to the literal Euclidean three-sphere. -/
def sphereNu : π_ 6 (Sphere 3) (sphereHomeomorph 1) :=
  homeomorphMulEquiv (N := Fin 6) sphereHomeomorph 1 nu

/-- The subgroup generated by the commutator class in the actual homotopy group. -/
def samelsonSubgroup : Subgroup (π_ 6 UnitQuaternions 1) := Subgroup.zpowers nu

theorem pairing_mem_samelsonSubgroup (a b : π_ 3 UnitQuaternions 1) :
    pairing a b ∈ samelsonSubgroup := by
  rw [pairing_eq_nu_zpow]
  exact Subgroup.zpow_mem_zpowers _ _

/-- Conversely, every power of the class is a Samelson product. -/
theorem nu_zpow_eq_pairing (k : ℤ) :
    nu ^ k = pairing (fundamentalClass ^ k) fundamentalClass := by
  simpa only [nu, zpow_one, mul_one] using
    (pairing_zpow_zpow fundamentalClass fundamentalClass k 1).symm

/-- This identifies precisely the part of `π₆(S³)` already controlled by bilinearity. -/
theorem mem_samelsonSubgroup_iff (c : π_ 6 UnitQuaternions 1) :
    c ∈ samelsonSubgroup ↔ ∃ a b : π_ 3 UnitQuaternions 1, pairing a b = c := by
  constructor
  · intro hc
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hc
    exact ⟨fundamentalClass ^ k, fundamentalClass, (nu_zpow_eq_pairing k).symm.trans hk⟩
  · rintro ⟨a, b, rfl⟩
    exact pairing_mem_samelsonSubgroup a b

end Wikipedia.HomotopyGroupsOfSpheres.QuaternionSamelson
