import Wikipedia.HomotopyGroupsOfSpheres.QuaternionicSequence
import Wikipedia.HomotopyGroupsOfSpheres.SphereSeven

/-!
# Integral coordinates in the quaternionic exact sequence

The proved seventh-sphere calculation gives an integer coordinate on the
base group. The connecting image is cyclic. Its integer relations are
exactly the degrees of projected classes from `π₇(Sp(2))`.

This does not identify that image with `12ℤ` and does not assert that the
connecting image is all of `π₆(S³)`.
-/

noncomputable section

open scoped Topology

namespace Wikipedia.HomotopyGroupsOfSpheres.QuaternionicFibration

/-- A proved integral coordinate on the native seventh homotopy group of the base sphere.
Its construction stays abstract when proving downstream group identities. -/
@[irreducible] def baseDegreeEquiv : π_ 7 BaseSphere north ≃* Multiplicative ℤ :=
  (homeomorphMulEquiv (N := Fin 7) baseSphereHomeomorph north).trans
    (pi7_sphere_seven_mulEquiv (baseSphereHomeomorph north))

/-- The actual degree map induced by the first-column projection. -/
def projectionDegree : π_ 7 SpTwo 1 →* Multiplicative ℤ :=
  baseDegreeEquiv.toMonoidHom.comp (projectionMap 6)

/-- The connecting homomorphism expressed in the proved integer coordinate. -/
def integerConnecting : Multiplicative ℤ →* π_ 6 northSubgroup 1 :=
  (connectingHom 6).comp baseDegreeEquiv.symm.toMonoidHom

/-- The image of the integral generator; only the connecting image is asserted to be cyclic. -/
def boundaryClass : π_ 6 northSubgroup 1 := integerConnecting (Multiplicative.ofAdd 1)

theorem integerConnecting_eq_zpow (k : ℤ) :
    integerConnecting (Multiplicative.ofAdd k) = boundaryClass ^ k := by
  have h : (Multiplicative.ofAdd (1 : ℤ)) ^ k = Multiplicative.ofAdd k := by
    change k • (1 : ℤ) = k
    simp
  rw [← h, map_zpow]
  rfl

theorem connecting_eq_boundaryClass_zpow (a : π_ 7 BaseSphere north) :
    connecting 6 a = boundaryClass ^ (baseDegreeEquiv a).toAdd := by
  have h := integerConnecting_eq_zpow (baseDegreeEquiv a).toAdd
  change connecting 6 (baseDegreeEquiv.symm (baseDegreeEquiv a)) = _ at h
  exact (congrArg (connecting 6) (MulEquiv.symm_apply_apply baseDegreeEquiv a)).symm.trans h

/-- The kernel of the fiber inclusion is precisely the subgroup generated by the boundary class. -/
theorem inclusion_ker_eq_zpowers_boundaryClass :
    (inclusionMap 6).ker = Subgroup.zpowers boundaryClass := by
  ext a
  constructor
  · intro ha
    obtain ⟨b, hb⟩ := (connecting_range_eq_kernel a).mpr ha
    rw [← hb, connecting_eq_boundaryClass_zpow]
    exact Subgroup.zpow_mem_zpowers _ _
  · intro ha
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp ha
    rw [← integerConnecting_eq_zpow]
    exact inclusionMap_connecting _

/-- All relations of the connecting class are exactly projected integer degrees. -/
theorem boundaryClass_zpow_eq_one_iff (k : ℤ) :
    boundaryClass ^ k = 1 ↔
      ∃ a : π_ 7 SpTwo 1, projectionDegree a = Multiplicative.ofAdd k := by
  rw [← integerConnecting_eq_zpow]
  change connecting 6 (baseDegreeEquiv.symm (Multiplicative.ofAdd k)) = 1 ↔ _
  rw [← projectionMap_range_eq_connecting_kernel]
  constructor
  · rintro ⟨a, ha⟩
    refine ⟨a, ?_⟩
    change baseDegreeEquiv (projectionMap 6 a) = Multiplicative.ofAdd k
    exact (congrArg baseDegreeEquiv ha).trans (MulEquiv.apply_symm_apply baseDegreeEquiv _)
  · rintro ⟨a, ha⟩
    exact ⟨a, baseDegreeEquiv.injective
      (ha.trans (MulEquiv.apply_symm_apply baseDegreeEquiv _).symm)⟩

/-- The projection's actual integer image is the kernel of the connecting homomorphism. -/
theorem projectionDegree_range_eq_integerConnecting_ker :
    projectionDegree.range = integerConnecting.ker := by
  ext k
  change (∃ a, projectionDegree a = k) ↔ integerConnecting k = 1
  constructor
  · intro ha
    exact (integerConnecting_eq_zpow k.toAdd).trans
      ((boundaryClass_zpow_eq_one_iff k.toAdd).mpr ha)
  · intro hk
    exact (boundaryClass_zpow_eq_one_iff k.toAdd).mp
      ((integerConnecting_eq_zpow k.toAdd).symm.trans hk)

end Wikipedia.HomotopyGroupsOfSpheres.QuaternionicFibration
