import ErdosProblems.Erdos1211.Erdos1211Dynamics
import ErdosProblems.Erdos1211.Erdos1211DensityNat
import Mathlib.Order.KonigLemma

/-!
# The sharp two-colour interval process

This file formalizes the one-dimensional combinatorial lemma used by
Conlon--Fox--Pham.  A finite prefix is normalized by choosing, among all
prefixes whose shadows are contained in the original shadows, one with the
fewest changes.  Kőnig's lemma then supplies a compatible infinite normalized
colouring.  The normalized run endpoints give the controlled recurrence from
`Erdos1211Dynamics`.
-/

namespace Erdos1211Shadow

open BigOperators Filter Finset Set

attribute [local instance] Classical.propDecidable
noncomputable section

/-- The positive interval shadow generated by a colour sequence. -/
def shadow (α : ℕ → Fin 2) (i : Fin 2) : Set ℕ :=
  {n | ∃ j : ℕ, 1 ≤ j ∧ j ≤ n ∧ n ≤ 2 * j ∧ α j = i}

def bit (S : Finset ℕ) (n : ℕ) : Fin 2 :=
  if n ∈ S then 1 else 0

@[simp] lemma bit_eq_one_iff {S : Finset ℕ} {n : ℕ} :
    bit S n = 1 ↔ n ∈ S := by
  simp [bit]

@[simp] lemma bit_eq_zero_iff {S : Finset ℕ} {n : ℕ} :
    bit S n = 0 ↔ n ∉ S := by
  simp [bit]

def Admissible (α : ℕ → Fin 2) (N : ℕ) (S : Finset ℕ) : Prop :=
  S ⊆ Finset.range N ∧
    ∀ n < N, ∀ i : Fin 2, n ∈ shadow (bit S) i → n ∈ shadow α i

def changes (S : Finset ℕ) (N : ℕ) : Finset ℕ :=
  (Finset.Ico 1 N).filter fun q ↦ bit S (q - 1) ≠ bit S q

def Normal (S : Finset ℕ) (N : ℕ) : Prop :=
  ∀ q r : ℕ, 1 ≤ q → q < r → r < N →
    bit S (q - 1) ≠ bit S q →
    bit S (r - 1) ≠ bit S r →
    (∀ k, q ≤ k → k < r → bit S k = bit S q) →
    2 * (q - 1) < r

def originalPrefix (α : ℕ → Fin 2) (N : ℕ) : Finset ℕ :=
  (Finset.range N).filter fun n ↦ α n = 1

lemma bit_originalPrefix {α : ℕ → Fin 2} {N n : ℕ} (hn : n < N) :
    bit (originalPrefix α N) n = α n := by
  generalize h : α n = c
  fin_cases c <;> simp [bit, originalPrefix, hn, h]

lemma originalPrefix_admissible (α : ℕ → Fin 2) (N : ℕ) :
    Admissible α N (originalPrefix α N) := by
  constructor
  · exact Finset.filter_subset _ _
  · intro n hn i hshadow
    obtain ⟨j, hj1, hjn, hnj, hji⟩ := hshadow
    exact ⟨j, hj1, hjn, hnj, by simpa [bit_originalPrefix (hjn.trans_lt hn)] using hji⟩

def candidates (α : ℕ → Fin 2) (N : ℕ) : Finset (Finset ℕ) :=
  (Finset.range N).powerset.filter fun S ↦ Admissible α N S

lemma candidates_nonempty (α : ℕ → Fin 2) (N : ℕ) :
    (candidates α N).Nonempty := by
  refine ⟨originalPrefix α N, ?_⟩
  exact Finset.mem_filter.mpr ⟨
    Finset.mem_powerset.mpr (originalPrefix_admissible α N).1,
    originalPrefix_admissible α N⟩

/-- Recolour the middle run `[q,r)` with the colour immediately before it. -/
def mergeRun (S : Finset ℕ) (q r : ℕ) : Finset ℕ :=
  if bit S (q - 1) = 1 then S ∪ Finset.Ico q r else S \ Finset.Ico q r

lemma bit_mergeRun_of_mem {S : Finset ℕ} {q r k : ℕ}
    (hkq : q ≤ k) (hkr : k < r) :
    bit (mergeRun S q r) k = bit S (q - 1) := by
  generalize hprev : bit S (q - 1) = c
  fin_cases c
  · have hprev0 : bit S (q - 1) ≠ 1 := by simpa [hprev]
    have hk : k ∈ Finset.Ico q r := Finset.mem_Ico.mpr ⟨hkq, hkr⟩
    rw [mergeRun, if_neg hprev0]
    have hknot : k ∉ S \ Finset.Ico q r := by simp [hk]
    rw [show bit (S \ Finset.Ico q r) k = 0 by simp [bit, hknot]]
    rfl
  · have hprev1 : bit S (q - 1) = 1 := hprev
    have hk : k ∈ Finset.Ico q r := Finset.mem_Ico.mpr ⟨hkq, hkr⟩
    rw [mergeRun, if_pos hprev1]
    have hkmem : k ∈ S ∪ Finset.Ico q r := Finset.mem_union_right S hk
    rw [show bit (S ∪ Finset.Ico q r) k = 1 by simp [bit, hkmem]]
    rfl

lemma bit_mergeRun_of_not_mem {S : Finset ℕ} {q r k : ℕ}
    (hk : k ∉ Finset.Ico q r) :
    bit (mergeRun S q r) k = bit S k := by
  by_cases hprev : bit S (q - 1) = 1
  · rw [mergeRun, if_pos hprev]
    simp only [bit, Finset.mem_union, hk, or_false]
  · rw [mergeRun, if_neg hprev]
    simp only [bit, Finset.mem_sdiff, hk, not_false_eq_true, and_true]

lemma mergeRun_subset_range {S : Finset ℕ} {N q r : ℕ}
    (hS : S ⊆ Finset.range N) (hrN : r ≤ N) :
    mergeRun S q r ⊆ Finset.range N := by
  intro k hk
  by_cases hprev : bit S (q - 1) = 1
  · rw [mergeRun, if_pos hprev, Finset.mem_union] at hk
    exact hk.elim (fun hkS ↦ hS hkS)
      (fun hkI ↦ Finset.mem_range.mpr ((Finset.mem_Ico.mp hkI).2.trans_le hrN))
  · rw [mergeRun, if_neg hprev, Finset.mem_sdiff] at hk
    exact hS hk.1

lemma shadow_mergeRun_subset {S : Finset ℕ} {q r : ℕ}
    (hq : 1 ≤ q) (hqr : q < r) (hshort : r ≤ 2 * (q - 1))
    (hleft : bit S (q - 1) ≠ bit S q)
    (hright : bit S (r - 1) ≠ bit S r)
    (hconst : ∀ k, q ≤ k → k < r → bit S k = bit S q) :
    ∀ i : Fin 2, shadow (bit (mergeRun S q r)) i ⊆ shadow (bit S) i := by
  intro i n hn
  obtain ⟨j, hj1, hjn, hnj, hji⟩ := hn
  by_cases hjI : j ∈ Finset.Ico q r
  · have hjrange := Finset.mem_Ico.mp hjI
    have hnew : i = bit S (q - 1) := by
      rw [bit_mergeRun_of_mem hjrange.1 hjrange.2] at hji
      exact hji.symm
    subst i
    by_cases hnr : n < r
    · refine ⟨q - 1, by omega, ?_, ?_,
        Eq.symm (bit_mergeRun_of_mem hjrange.1 hjrange.2)⟩
      · omega
      · omega
    · have hrle : r ≤ n := Nat.le_of_not_gt hnr
      have hjle : j ≤ r - 1 := by omega
      have hmidLast : bit S (r - 1) = bit S q := hconst (r - 1) (by omega) (by omega)
      have hends : bit S r = bit S (q - 1) := by
        generalize ha : bit S (q - 1) = a
        generalize hb : bit S q = b
        generalize hc : bit S r = c
        fin_cases a <;> fin_cases b <;> fin_cases c <;> simp_all
      refine ⟨r, by omega, hrle, ?_,
        hends.trans (Eq.symm (bit_mergeRun_of_mem hjrange.1 hjrange.2))⟩
      omega
  · refine ⟨j, hj1, hjn, hnj, ?_⟩
    rw [bit_mergeRun_of_not_mem hjI] at hji
    exact hji

lemma mergeRun_admissible {α : ℕ → Fin 2} {N : ℕ} {S : Finset ℕ}
    (hS : Admissible α N S) {q r : ℕ}
    (hq : 1 ≤ q) (hqr : q < r) (hrN : r < N)
    (hshort : r ≤ 2 * (q - 1))
    (hleft : bit S (q - 1) ≠ bit S q)
    (hright : bit S (r - 1) ≠ bit S r)
    (hconst : ∀ k, q ≤ k → k < r → bit S k = bit S q) :
    Admissible α N (mergeRun S q r) := by
  constructor
  · exact mergeRun_subset_range hS.1 hrN.le
  · intro n hn i hni
    exact hS.2 n hn i
      (shadow_mergeRun_subset hq hqr hshort hleft hright hconst i hni)

lemma changes_mergeRun_subset {S : Finset ℕ} {N q r : ℕ}
    (hq : 1 ≤ q) (hqr : q < r) (hrN : r < N)
    (hleft : bit S (q - 1) ≠ bit S q)
    (hright : bit S (r - 1) ≠ bit S r)
    (hconst : ∀ k, q ≤ k → k < r → bit S k = bit S q) :
    changes (mergeRun S q r) N ⊆ changes S N := by
  intro k hk
  rw [changes, Finset.mem_filter] at hk ⊢
  refine ⟨hk.1, ?_⟩
  have hkRange := Finset.mem_Ico.mp hk.1
  by_cases hkleft : k < q
  · have hk1 : k - 1 ∉ Finset.Ico q r := by simp only [Finset.mem_Ico]; omega
    have hk2 : k ∉ Finset.Ico q r := by simp only [Finset.mem_Ico]; omega
    simpa [bit_mergeRun_of_not_mem hk1, bit_mergeRun_of_not_mem hk2] using hk.2
  · have hqk : q ≤ k := Nat.le_of_not_gt hkleft
    by_cases hkr : k < r
    · by_cases hkq : k = q
      · subst k
        have hprev : q - 1 ∉ Finset.Ico q r := by
          simp only [Finset.mem_Ico]
          omega
        rw [bit_mergeRun_of_not_mem hprev,
          bit_mergeRun_of_mem (q := q) (r := r) le_rfl hqr] at hk
        exact (hk.2 rfl).elim
      · have hkminus : q ≤ k - 1 := by omega
        have hkminuslt : k - 1 < r := by omega
        rw [bit_mergeRun_of_mem hkminus hkminuslt,
          bit_mergeRun_of_mem hqk hkr] at hk
        exact (hk.2 rfl).elim
    · have hrk : r ≤ k := Nat.le_of_not_gt hkr
      by_cases hkrEq : k = r
      · subst k
        have hprev : r - 1 ∈ Finset.Ico q r := Finset.mem_Ico.mpr ⟨by omega, by omega⟩
        have hnow : r ∉ Finset.Ico q r := by simp
        rw [bit_mergeRun_of_mem (by omega) (by omega), bit_mergeRun_of_not_mem hnow] at hk
        exact hright
      · have hk1 : k - 1 ∉ Finset.Ico q r := by
          simp only [Finset.mem_Ico]
          omega
        have hk2 : k ∉ Finset.Ico q r := by
          simp only [Finset.mem_Ico]
          omega
        simpa [bit_mergeRun_of_not_mem hk1, bit_mergeRun_of_not_mem hk2] using hk.2

lemma mergeRun_change_strict {S : Finset ℕ} {N q r : ℕ}
    (hq : 1 ≤ q) (hqr : q < r) (hrN : r < N)
    (hleft : bit S (q - 1) ≠ bit S q)
    (hright : bit S (r - 1) ≠ bit S r)
    (hconst : ∀ k, q ≤ k → k < r → bit S k = bit S q) :
    (changes (mergeRun S q r) N).card < (changes S N).card := by
  have hsub := changes_mergeRun_subset hq hqr hrN hleft hright hconst
  have hqold : q ∈ changes S N := by
    rw [changes, Finset.mem_filter]
    exact ⟨Finset.mem_Ico.mpr ⟨hq, hqr.trans hrN⟩, hleft⟩
  have hqnew : q ∉ changes (mergeRun S q r) N := by
    rw [changes, Finset.mem_filter]
    push_neg
    intro _
    have hprev : q - 1 ∉ Finset.Ico q r := by simp only [Finset.mem_Ico]; omega
    rw [bit_mergeRun_of_not_mem hprev,
      bit_mergeRun_of_mem (q := q) (r := r) le_rfl hqr]
  apply Finset.card_lt_card
  rw [ssubset_iff_subset_ne]
  refine ⟨hsub, ?_⟩
  intro heq
  have : q ∈ changes (mergeRun S q r) N := by simpa [heq] using hqold
  exact hqnew this

theorem exists_normal_admissible (α : ℕ → Fin 2) (N : ℕ) :
    ∃ S : Finset ℕ, Admissible α N S ∧ Normal S N := by
  obtain ⟨S, hScand, hmin⟩ :=
    (candidates α N).exists_min_image (fun T ↦ (changes T N).card)
      (candidates_nonempty α N)
  have hSad : Admissible α N S := (Finset.mem_filter.mp hScand).2
  refine ⟨S, hSad, ?_⟩
  intro q r hq hqr hrN hleft hright hconst
  by_contra hnot
  have hshort : r ≤ 2 * (q - 1) := Nat.le_of_not_gt hnot
  let T := mergeRun S q r
  have hTad : Admissible α N T :=
    mergeRun_admissible hSad hq hqr hrN hshort hleft hright hconst
  have hTrange : T ⊆ Finset.range N := hTad.1
  have hTcand : T ∈ candidates α N := by
    exact Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr hTrange, hTad⟩
  have hle := hmin T hTcand
  have hlt := mergeRun_change_strict hq hqr hrN hleft hright hconst
  exact (Nat.not_lt_of_ge hle) hlt

/-! ### A compatible infinite normalization -/

def restrictPrefix (S : Finset ℕ) (N : ℕ) : Finset ℕ :=
  S ∩ Finset.range N

lemma bit_restrictPrefix {S : Finset ℕ} {N n : ℕ} (hn : n < N) :
    bit (restrictPrefix S N) n = bit S n := by
  simp [restrictPrefix, bit, hn]

lemma restrictPrefix_admissible {α : ℕ → Fin 2} {M N : ℕ}
    (hMN : M ≤ N) {S : Finset ℕ} (hS : Admissible α N S) :
    Admissible α M (restrictPrefix S M) := by
  constructor
  · exact Finset.inter_subset_right
  · intro n hn i hshadow
    apply hS.2 n (hn.trans_le hMN) i
    obtain ⟨j, hj1, hjn, hnj, hji⟩ := hshadow
    refine ⟨j, hj1, hjn, hnj, ?_⟩
    simpa only [bit_restrictPrefix (hjn.trans_lt hn)] using hji

lemma restrictPrefix_normal {M N : ℕ} (hMN : M ≤ N)
    {S : Finset ℕ} (hS : Normal S N) :
    Normal (restrictPrefix S M) M := by
  intro q r hq hqr hrM hleft hright hconst
  have hqN : q < N := (hqr.trans hrM).trans_le hMN
  have hrN : r < N := hrM.trans_le hMN
  apply hS q r hq hqr hrN
  · rw [bit_restrictPrefix (by omega), bit_restrictPrefix (by omega)] at hleft
    exact hleft
  · rw [bit_restrictPrefix (by omega), bit_restrictPrefix (by omega)] at hright
    exact hright
  · intro k hqk hkr
    have hk := hconst k hqk hkr
    rw [bit_restrictPrefix (hkr.trans hrM), bit_restrictPrefix (by omega)] at hk
    exact hk

def Prefix (α : ℕ → Fin 2) (N : ℕ) :=
  {S : Finset ℕ // S ∈ candidates α N ∧ Normal S N}

instance prefixFinite (α : ℕ → Fin 2) (N : ℕ) : Finite (Prefix α N) := by
  let e : Prefix α N ↪ {S // S ∈ candidates α N} :=
    ⟨fun S ↦ ⟨S.1, S.2.1⟩, by
      intro S T h
      apply Subtype.ext
      exact congrArg (fun U : {S // S ∈ candidates α N} ↦ U.1) h⟩
  exact Finite.of_injective e e.injective

instance prefixNonempty (α : ℕ → Fin 2) (N : ℕ) : Nonempty (Prefix α N) := by
  obtain ⟨S, hSad, hSnorm⟩ := exists_normal_admissible α N
  exact ⟨⟨S, Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr hSad.1, hSad⟩,
    hSnorm⟩⟩

def prefixProj {α : ℕ → Fin 2} {M N : ℕ} (hMN : M ≤ N) :
    Prefix α N → Prefix α M := fun S ↦
  ⟨restrictPrefix S.1 M,
    Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr Finset.inter_subset_right,
      restrictPrefix_admissible hMN (Finset.mem_filter.mp S.2.1).2⟩,
    restrictPrefix_normal hMN S.2.2⟩

lemma prefixProj_refl {α : ℕ → Fin 2} {N : ℕ} (S : Prefix α N) :
    prefixProj (le_refl N) S = S := by
  apply Subtype.ext
  simp only [prefixProj, restrictPrefix]
  exact Finset.inter_eq_left.mpr (Finset.mem_powerset.mp (Finset.mem_filter.mp S.2.1).1)

lemma prefixProj_trans {α : ℕ → Fin 2} {L M N : ℕ}
    (hLM : L ≤ M) (hMN : M ≤ N) (S : Prefix α N) :
    prefixProj hLM (prefixProj hMN S) = prefixProj (hLM.trans hMN) S := by
  apply Subtype.ext
  simp only [prefixProj, restrictPrefix]
  ext n
  simp only [Finset.mem_inter, Finset.mem_range]
  constructor
  · exact fun h ↦ ⟨h.1.1, h.2⟩
  · exact fun h ↦ ⟨⟨h.1, h.2.trans_le hLM⟩, h.2⟩

/-- There is a globally normalized colouring whose two shadows are contained
in the corresponding shadows of the original colouring. -/
theorem exists_normalized_shadow_subcoloring (α : ℕ → Fin 2) :
    ∃ β : ℕ → Fin 2,
      (∀ i : Fin 2, shadow β i ⊆ shadow α i) ∧
      (∀ q r : ℕ, 1 ≤ q → q < r →
        β (q - 1) ≠ β q → β (r - 1) ≠ β r →
        (∀ k, q ≤ k → k < r → β k = β q) →
        2 * (q - 1) < r) := by
  let π : {M N : ℕ} → M ≤ N → Prefix α N → Prefix α M :=
    fun {_ _} h S ↦ prefixProj h S
  obtain ⟨f, hf⟩ := exists_seq_forall_proj_of_forall_finite
    (α := Prefix α) π
    (fun {_} S ↦ prefixProj_refl S)
    (fun {_ _ _} hLM hMN S ↦ prefixProj_trans hLM hMN S)
    (fun _ _ ↦ Set.toFinite _)
  let β : ℕ → Fin 2 := fun n ↦ bit (f (n + 1)).1 n
  have hcompat {n N : ℕ} (hnN : n < N) : bit (f N).1 n = β n := by
    have hproj := congrArg Subtype.val (hf (Nat.succ_le_iff.mpr hnN))
    change restrictPrefix (f N).1 (n + 1) = (f (n + 1)).1 at hproj
    have hbit := congrArg (fun S : Finset ℕ ↦ bit S n) hproj
    simpa only [β, bit_restrictPrefix (Nat.lt_succ_self n)] using hbit
  refine ⟨β, ?_, ?_⟩
  · intro i n hn
    obtain ⟨j, hj1, hjn, hnj, hji⟩ := hn
    have hprefixAd := (Finset.mem_filter.mp (f (n + 1)).2.1).2
    apply hprefixAd.2 n (Nat.lt_succ_self n) i
    refine ⟨j, hj1, hjn, hnj, ?_⟩
    rw [hcompat (hjn.trans_lt (Nat.lt_succ_self n))]
    exact hji
  · intro q r hq hqr hleft hright hconst
    have hnorm := (f (r + 1)).2.2
    apply hnorm q r hq hqr (Nat.lt_succ_self r)
    · rw [hcompat (by omega), hcompat (by omega)]
      exact hleft
    · rw [hcompat (by omega), hcompat (by omega)]
      exact hright
    · intro k hqk hkr
      rw [hcompat (by omega), hcompat (by omega)]
      exact hconst k hqk hkr

/-! ### Upper natural density of the interval shadows -/

def cutoffCount (X : Set ℕ) (N : ℕ) : ℕ :=
  ((Finset.Icc 1 N).filter fun n ↦ n ∈ X).card

def cutoffRatio (X : Set ℕ) (N : ℕ) : ℝ :=
  (cutoffCount X N : ℝ) / N

def upperDensity (X : Set ℕ) : ℝ :=
  Filter.limsup (cutoffRatio X) Filter.atTop

lemma cutoffCount_le (X : Set ℕ) (N : ℕ) : cutoffCount X N ≤ N := by
  calc
    cutoffCount X N ≤ (Finset.Icc 1 N).card :=
      Finset.card_le_card (Finset.filter_subset _ _)
    _ ≤ N := by simp

lemma cutoffRatio_nonneg (X : Set ℕ) (N : ℕ) : 0 ≤ cutoffRatio X N := by
  exact div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)

lemma cutoffRatio_le_one (X : Set ℕ) (N : ℕ) : cutoffRatio X N ≤ 1 := by
  by_cases hN : N = 0
  · simp [cutoffRatio, hN]
  · apply (div_le_one (by exact_mod_cast Nat.pos_of_ne_zero hN)).2
    exact_mod_cast cutoffCount_le X N

lemma cutoffRatio_mono {X Y : Set ℕ} (hXY : X ⊆ Y) (N : ℕ) :
    cutoffRatio X N ≤ cutoffRatio Y N := by
  apply div_le_div_of_nonneg_right _ (Nat.cast_nonneg N)
  exact_mod_cast Finset.card_le_card (by
    intro n hn
    rw [Finset.mem_filter] at hn ⊢
    exact ⟨hn.1, hXY hn.2⟩)

lemma cutoffRatio_bounded (X : Set ℕ) :
    IsBoundedUnder (· ≤ ·) atTop (cutoffRatio X) :=
  isBoundedUnder_of ⟨1, cutoffRatio_le_one X⟩

lemma cutoffRatio_cobounded (X : Set ℕ) :
    IsCoboundedUnder (· ≤ ·) atTop (cutoffRatio X) :=
  (isBoundedUnder_of ⟨0, cutoffRatio_nonneg X⟩).isCoboundedUnder_le

lemma upperDensity_mono {X Y : Set ℕ} (hXY : X ⊆ Y) :
    upperDensity X ≤ upperDensity Y := by
  exact Filter.limsup_le_limsup
    (Filter.Eventually.of_forall (cutoffRatio_mono hXY))
    (cutoffRatio_cobounded X) (cutoffRatio_bounded Y)

lemma eventually_cutoffRatio_lt {X : Set ℕ} {M : ℝ}
    (hXM : upperDensity X < M) :
    ∀ᶠ N : ℕ in atTop, cutoffRatio X N < M := by
  exact eventually_lt_of_limsup_lt hXM (cutoffRatio_bounded X)

def EventuallyConstant (β : ℕ → Fin 2) : Prop :=
  ∃ K i, ∀ n, K ≤ n → β n = i

lemma not_eventuallyConstant_of_shadow_bounds {β : ℕ → Fin 2} {M : ℝ}
    (hM : M < 1)
    (hbound : ∀ i : Fin 2, ∀ᶠ N : ℕ in atTop,
      cutoffRatio (shadow β i) N < M) :
    ¬ EventuallyConstant β := by
  rintro ⟨K, i, hconst⟩
  obtain ⟨T, hT⟩ := Filter.eventually_atTop.1 (hbound i)
  have honeM : 0 < 1 - M := sub_pos.mpr hM
  obtain ⟨n : ℕ, hnreal⟩ := exists_nat_gt
    (max (T : ℝ) (max (K + 1 : ℝ) ((K : ℝ) / (1 - M))))
  have hnT : T ≤ n := by exact_mod_cast (lt_of_le_of_lt (le_max_left _ _) hnreal).le
  have hnK : K + 1 ≤ n := by
    have hle : (K + 1 : ℝ) ≤
        max (T : ℝ) (max (K + 1 : ℝ) ((K : ℝ) / (1 - M))) :=
      (le_max_left _ _).trans (le_max_right _ _)
    exact_mod_cast (hle.trans hnreal.le)
  have hratio := hT n hnT
  have hinterval : Finset.Icc (K + 1) n ⊆
      (Finset.Icc 1 n).filter fun m ↦ m ∈ shadow β i := by
    intro m hm
    have hmI := Finset.mem_Icc.mp hm
    rw [Finset.mem_filter, Finset.mem_Icc]
    refine ⟨⟨by omega, hmI.2⟩, ?_⟩
    exact ⟨m, by omega, le_rfl, by omega, hconst m (by omega)⟩
  have hcount : n - K ≤ cutoffCount (shadow β i) n := by
    have := Finset.card_le_card hinterval
    simpa [cutoffCount, hnK] using this
  have hnpos : (0 : ℝ) < n := by exact_mod_cast (by omega : 0 < n)
  have hlarge : (K : ℝ) / (1 - M) < n :=
    lt_of_le_of_lt ((le_max_right _ _).trans (le_max_right _ _)) hnreal
  have hmul : (K : ℝ) < n * (1 - M) := by
    exact (div_lt_iff₀ honeM).mp hlarge
  have hlower : M < cutoffRatio (shadow β i) n := by
    rw [cutoffRatio]
    have hcast : (n : ℝ) - K ≤ (cutoffCount (shadow β i) n : ℝ) := by
      rw [← Nat.cast_sub (by omega : K ≤ n)]
      exact_mod_cast hcount
    apply (lt_div_iff₀ hnpos).2
    nlinarith
  exact (not_lt_of_ge hlower.le) hratio

/-! ### Normalized run endpoints -/

noncomputable def nextChange (β : ℕ → Fin 2) (k : ℕ) : ℕ :=
  if h : ∃ m, k < m ∧ β m ≠ β k then Nat.find h else k + 1

def runStart (β : ℕ → Fin 2) : ℕ → ℕ
  | 0 => 1
  | n + 1 => nextChange β (runStart β n)

lemma exists_change_after_of_not_eventuallyConstant {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) (k : ℕ) :
    ∃ m, k < m ∧ β m ≠ β k := by
  by_contra hnot
  push Not at hnot
  apply hβ
  exact ⟨k, β k, fun n hn ↦ (Nat.eq_or_lt_of_le hn).elim
    (fun h ↦ h ▸ rfl) (fun h ↦ hnot n h)⟩

lemma nextChange_spec {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (k : ℕ) :
    k < nextChange β k ∧ β (nextChange β k) ≠ β k := by
  rw [nextChange, dif_pos (exists_change_after_of_not_eventuallyConstant hβ k)]
  exact Nat.find_spec (exists_change_after_of_not_eventuallyConstant hβ k)

lemma nextChange_min {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β)
    {k m : ℕ} (hkm : k < m) (hchange : β m ≠ β k) :
    nextChange β k ≤ m := by
  rw [nextChange, dif_pos (exists_change_after_of_not_eventuallyConstant hβ k)]
  exact Nat.find_min' _ ⟨hkm, hchange⟩

lemma runStart_zero (β : ℕ → Fin 2) : runStart β 0 = 1 := rfl

lemma runStart_succ (β : ℕ → Fin 2) (n : ℕ) :
    runStart β (n + 1) = nextChange β (runStart β n) := rfl

lemma runStart_strict {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    runStart β n < runStart β (n + 1) := by
  rw [runStart_succ]
  exact (nextChange_spec hβ _).1

lemma runStart_change {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    β (runStart β (n + 1)) ≠ β (runStart β n) := by
  rw [runStart_succ]
  exact (nextChange_spec hβ _).2

lemma runStart_mono {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) :
    StrictMono (runStart β) :=
  strictMono_nat_of_lt_succ (runStart_strict hβ)

lemma runStart_const {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β)
    {n k : ℕ} (hlo : runStart β n ≤ k) (hhi : k < runStart β (n + 1)) :
    β k = β (runStart β n) := by
  rcases hlo.eq_or_lt with h | h
  · exact congrArg β h.symm
  · by_contra hchange
    have hmin := nextChange_min hβ h hchange
    rw [← runStart_succ] at hmin
    omega

lemma runStart_twoStep_color {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    β (runStart β (n + 2)) = β (runStart β n) := by
  have h1 := runStart_change hβ n
  have h2 := runStart_change hβ (n + 1)
  generalize ha : β (runStart β n) = a
  generalize hb : β (runStart β (n + 1)) = b
  generalize hc : β (runStart β (n + 2)) = c
  fin_cases a <;> fin_cases b <;> fin_cases c <;> simp_all

lemma runStart_growth {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (n : ℕ) :
    2 * (runStart β (n + 1) - 1) ≤ runStart β (n + 2) - 1 := by
  let q := runStart β (n + 1)
  let r := runStart β (n + 2)
  have hq1 : 1 ≤ q := by
    have hs := (runStart_mono hβ) (Nat.zero_lt_succ n)
    simpa only [q, runStart_zero] using hs.le
  have hqr : q < r := by
    exact runStart_strict hβ (n + 1)
  have hqprev : β (q - 1) = β (runStart β n) := by
    apply runStart_const hβ
    · have hs := runStart_strict hβ n
      dsimp only [q]
      omega
    · dsimp only [q]
      omega
  have hleft : β (q - 1) ≠ β q := by
    rw [hqprev]
    exact (runStart_change hβ n).symm
  have hrprev : β (r - 1) = β q := by
    apply runStart_const hβ
    · dsimp only [q, r]
      have hs := runStart_strict hβ (n + 1)
      omega
    · have hrEq : runStart β (n + 1 + 1) = r := by
        simp only [r]
      rw [hrEq]
      omega
  have hright : β (r - 1) ≠ β r := by
    rw [hrprev]
    exact (runStart_change hβ (n + 1)).symm
  have hmiddle : ∀ k, q ≤ k → k < r → β k = β q := by
    intro k hkq hkr
    exact runStart_const hβ hkq hkr
  have hg := hnorm q r hq1 hqr hleft hright hmiddle
  omega

def runHeight (β : ℕ → Fin 2) (n : ℕ) : ℕ := runStart β n - 1

lemma one_le_runStart {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    1 ≤ runStart β n := by
  have hm := (runStart_mono hβ).monotone (Nat.zero_le n)
  simpa only [runStart_zero] using hm

lemma runStart_eq_height_add_one {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    runStart β n = runHeight β n + 1 := by
  simp only [runHeight]
  exact (Nat.sub_add_cancel (one_le_runStart hβ n)).symm

lemma runHeight_zero (β : ℕ → Fin 2) : runHeight β 0 = 0 := by
  simp [runHeight, runStart_zero]

lemma runHeight_pos {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    0 < runHeight β (n + 1) := by
  have hs := (runStart_mono hβ) (Nat.zero_lt_succ n)
  rw [runStart_zero] at hs
  simp only [runHeight]
  exact Nat.sub_pos_of_lt hs

lemma runHeight_growth {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (n : ℕ) :
    2 * runHeight β (n + 1) ≤ runHeight β (n + 2) := by
  simpa only [runHeight] using runStart_growth hβ hnorm n

lemma runInterval_subset_shadow {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    Finset.Icc (runStart β n) (2 * runHeight β (n + 1)) ⊆
      (Finset.Icc 1 (2 * runHeight β (n + 1))).filter
        fun x ↦ x ∈ shadow β (β (runStart β n)) := by
  intro x hx
  have hxI := Finset.mem_Icc.mp hx
  rw [Finset.mem_filter, Finset.mem_Icc]
  constructor
  · constructor
    · have hstart : 1 ≤ runStart β n := by
        have hm := (runStart_mono hβ).monotone (Nat.zero_le n)
        rw [runStart_zero] at hm
        exact hm
      omega
    · exact hxI.2
  · by_cases hxlast : x ≤ runHeight β (n + 1)
    · refine ⟨x, ?_, le_rfl, by omega, ?_⟩
      · exact (one_le_runStart hβ n).trans hxI.1
      · apply runStart_const hβ hxI.1
        rw [runStart_eq_height_add_one hβ (n + 1)]
        omega
    · let j := runHeight β (n + 1)
      have hjrun : β j = β (runStart β n) := by
        apply runStart_const hβ
        · have hs := runStart_strict hβ n
          dsimp only [j, runHeight]
          omega
        · dsimp only [j, runHeight]
          rw [runStart_eq_height_add_one hβ (n + 1)]
          have hp := runHeight_pos hβ n
          omega
      refine ⟨j, ?_, by omega, hxI.2, hjrun⟩
      exact runHeight_pos hβ n

def coverSet (β : ℕ → Fin 2) : ℕ → Finset ℕ
  | 0 => ∅
  | 1 => Finset.Icc 1 (2 * runHeight β 1)
  | n + 2 => coverSet β n ∪
      Finset.Icc (runStart β (n + 1)) (2 * runHeight β (n + 2))

@[simp] lemma coverSet_zero (β : ℕ → Fin 2) : coverSet β 0 = ∅ := rfl

@[simp] lemma coverSet_one (β : ℕ → Fin 2) :
    coverSet β 1 = Finset.Icc 1 (2 * runHeight β 1) := rfl

lemma coverSet_add_two (β : ℕ → Fin 2) (n : ℕ) :
    coverSet β (n + 2) = coverSet β n ∪
      Finset.Icc (runStart β (n + 1)) (2 * runHeight β (n + 2)) := rfl

lemma coverSet_subset_cutoff {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) :
    ∀ j : ℕ, 1 ≤ j →
      coverSet β j ⊆ Finset.Icc 1 (2 * runHeight β j) := by
  intro j
  induction j using Nat.twoStepInduction with
  | zero => simp
  | one => simp
  | more n ih0 ih1 =>
      intro _ x hx
      rw [coverSet_add_two, Finset.mem_union] at hx
      rw [Finset.mem_Icc]
      rcases hx with hx | hx
      · by_cases hn : n = 0
        · subst n
          simp at hx
        · have hn1 : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr hn
          have hx' := Finset.mem_Icc.mp (ih0 hn1 hx)
          have hmono := (runStart_mono hβ).monotone (Nat.le_add_right n 2)
          simp only [runHeight]
          simp only [runHeight] at hx'
          omega
      · have hx' := Finset.mem_Icc.mp hx
        exact ⟨(one_le_runStart hβ (n + 1)).trans hx'.1, hx'.2⟩

lemma coverSet_subset_shadow {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) :
    ∀ j : ℕ, 1 ≤ j →
      coverSet β j ⊆
        (Finset.Icc 1 (2 * runHeight β j)).filter
          fun x ↦ x ∈ shadow β (β (runStart β (j - 1))) := by
  intro j
  induction j using Nat.twoStepInduction with
  | zero => omega
  | one =>
      intro _ x hx
      have hsub := runInterval_subset_shadow hβ 0
      simpa [runStart_zero, runHeight_zero] using hsub hx
  | more n ih0 ih1 =>
      intro hj x hx
      rw [coverSet_add_two, Finset.mem_union] at hx
      rcases hx with hx | hx
      · by_cases hn : n = 0
        · subst n
          simp at hx
        · have hn1 : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr hn
          have hxprev := ih0 hn1 hx
          rw [Finset.mem_filter] at hxprev ⊢
          refine ⟨?_, ?_⟩
          · have hcut := (coverSet_subset_cutoff hβ n hn1) hx
            have hmono := (runStart_mono hβ).monotone (Nat.le_add_right n 2)
            have hcutI := Finset.mem_Icc.mp hcut
            rw [Finset.mem_Icc]
            simp only [runHeight] at hcutI ⊢
            omega
          · have hcolor := runStart_twoStep_color hβ (n - 1)
            have hnform : n - 1 + 2 = n + 1 := by omega
            rw [hnform] at hcolor
            change x ∈ shadow β (β (runStart β (n + 1)))
            rw [hcolor]
            exact hxprev.2
      · have hnew := runInterval_subset_shadow hβ (n + 1) hx
        have hidx : n + 2 - 1 = n + 1 := by omega
        have hsum : n + 1 + 1 = n + 2 := by omega
        simpa only [hidx, hsum] using hnew

lemma coverSet_disjoint_new {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (n : ℕ) :
    Disjoint (coverSet β n)
      (Finset.Icc (runStart β (n + 1)) (2 * runHeight β (n + 2))) := by
  by_cases hn : n = 0
  · subst n
    simp
  · rw [Finset.disjoint_left]
    intro x hx hxi
    have hn1 : 1 ≤ n := Nat.one_le_iff_ne_zero.mpr hn
    have hxcut := Finset.mem_Icc.mp (coverSet_subset_cutoff hβ n hn1 hx)
    have hxnew := Finset.mem_Icc.mp hxi
    have hgrowth := runHeight_growth hβ hnorm (n - 1)
    have hnform : n - 1 + 1 = n := by omega
    have hnform2 : n - 1 + 2 = n + 1 := by omega
    rw [hnform, hnform2] at hgrowth
    simp only [runHeight] at hxcut hgrowth
    omega

lemma coverSet_card_add_two {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (n : ℕ) :
    (coverSet β (n + 2)).card = (coverSet β n).card +
      (2 * runHeight β (n + 2) - runHeight β (n + 1)) := by
  rw [coverSet_add_two, Finset.card_union_of_disjoint
    (coverSet_disjoint_new hβ hnorm n)]
  have hle : runStart β (n + 1) ≤ 2 * runHeight β (n + 2) := by
    have hs : runStart β (n + 1) < runStart β (n + 2) := by
      simpa only [show n + 1 + 1 = n + 2 by omega] using
        runStart_strict hβ (n + 1)
    rw [runStart_eq_height_add_one hβ (n + 2)] at hs
    have hp := runHeight_pos hβ (n + 1)
    omega
  rw [Nat.card_Icc, Nat.sub_add_comm hle]
  have hstart := runStart_eq_height_add_one hβ (n + 1)
  omega

lemma runStart_lower {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    n + 1 ≤ runStart β n := by
  induction n with
  | zero => simp [runStart_zero]
  | succ n ih =>
      have hs := runStart_strict hβ n
      omega

lemma runHeight_lower {β : ℕ → Fin 2} (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    n + 1 ≤ runHeight β (n + 1) := by
  have h := runStart_lower hβ (n + 1)
  simp only [runHeight]
  omega

def stateA (β : ℕ → Fin 2) (n : ℕ) : ℝ :=
  ((coverSet β (n + 1)).card : ℝ) / (2 * runHeight β (n + 1))

def stateB (β : ℕ → Fin 2) (n : ℕ) : ℝ :=
  ((coverSet β n).card : ℝ) / (2 * runHeight β (n + 1))

def controlZ (β : ℕ → Fin 2) (n : ℕ) : ℝ :=
  (runHeight β (n + 1) : ℝ) / runHeight β (n + 2)

lemma stateA_nonneg (β : ℕ → Fin 2) (n : ℕ) : 0 ≤ stateA β n := by
  exact div_nonneg (Nat.cast_nonneg _) (by positivity)

lemma stateB_nonneg (β : ℕ → Fin 2) (n : ℕ) : 0 ≤ stateB β n := by
  exact div_nonneg (Nat.cast_nonneg _) (by positivity)

lemma controlZ_bounds {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (n : ℕ) :
    0 ≤ controlZ β n ∧ controlZ β n ≤ 1 / 2 := by
  have hden : (0 : ℝ) < runHeight β (n + 2) := by
    exact_mod_cast runHeight_pos hβ (n + 1)
  have hgrowth := runHeight_growth hβ hnorm n
  constructor
  · exact div_nonneg (Nat.cast_nonneg _) hden.le
  · rw [controlZ]
    apply (div_le_iff₀ hden).2
    have hgrowthR : (2 : ℝ) * runHeight β (n + 1) ≤ runHeight β (n + 2) := by
      exact_mod_cast hgrowth
    nlinarith

lemma stateB_recurrence {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    stateB β (n + 1) = stateA β n * controlZ β n := by
  have hh1 : (0 : ℝ) < runHeight β (n + 1) := by
    exact_mod_cast runHeight_pos hβ n
  have hh2 : (0 : ℝ) < runHeight β (n + 2) := by
    exact_mod_cast runHeight_pos hβ (n + 1)
  rw [stateB, stateA, controlZ]
  field_simp

lemma stateA_recurrence {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (n : ℕ) :
    stateA β (n + 1) =
      stateB β n * controlZ β n + 1 - controlZ β n / 2 := by
  have hh1 : (0 : ℝ) < runHeight β (n + 1) := by
    exact_mod_cast runHeight_pos hβ n
  have hh2 : (0 : ℝ) < runHeight β (n + 2) := by
    exact_mod_cast runHeight_pos hβ (n + 1)
  have hcard := coverSet_card_add_two hβ hnorm n
  have hsub : runHeight β (n + 1) ≤ 2 * runHeight β (n + 2) := by
    have hg := runHeight_growth hβ hnorm n
    omega
  have hcardR : ((coverSet β (n + 2)).card : ℝ) =
      (coverSet β n).card +
        (2 * runHeight β (n + 2) - runHeight β (n + 1) : ℕ) := by
    exact_mod_cast hcard
  rw [stateA, stateB, controlZ]
  push_cast [Nat.cast_sub hsub] at hcardR
  rw [hcardR]
  field_simp
  ring

lemma stateA_le_shadow_ratio {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) (n : ℕ) :
    stateA β n ≤ cutoffRatio
      (shadow β (β (runStart β n))) (2 * runHeight β (n + 1)) := by
  have hsub := coverSet_subset_shadow hβ (n + 1) (by omega)
  have hcard : (coverSet β (n + 1)).card ≤
      cutoffCount (shadow β (β (runStart β n))) (2 * runHeight β (n + 1)) := by
    exact Finset.card_le_card hsub
  rw [stateA, cutoffRatio]
  simp only [Nat.cast_mul, Nat.cast_ofNat]
  change ((coverSet β (n + 1)).card : ℝ) /
      (2 * (runHeight β (n + 1) : ℝ)) ≤
    (cutoffCount (shadow β (β (runStart β n)))
      (2 * runHeight β (n + 1)) : ℝ) /
      (2 * (runHeight β (n + 1) : ℝ))
  apply div_le_div_of_nonneg_right _ (by positivity)
  exact_mod_cast hcard

lemma stateB_le_shadow_ratio {β : ℕ → Fin 2}
    (hβ : ¬ EventuallyConstant β) {n : ℕ} (hn : 1 ≤ n) :
    stateB β n ≤ cutoffRatio
      (shadow β (β (runStart β (n - 1)))) (2 * runHeight β (n + 1)) := by
  have hshadow := coverSet_subset_shadow hβ n hn
  have hcut := coverSet_subset_cutoff hβ n hn
  have hsub : coverSet β n ⊆
      (Finset.Icc 1 (2 * runHeight β (n + 1))).filter
        fun x ↦ x ∈ shadow β (β (runStart β (n - 1))) := by
    intro x hx
    have hs := Finset.mem_filter.mp (hshadow hx)
    rw [Finset.mem_filter]
    refine ⟨?_, hs.2⟩
    have hI := Finset.mem_Icc.mp (hcut hx)
    have hmono := (runStart_mono hβ).monotone (Nat.le_succ n)
    have hhmono : runHeight β n ≤ runHeight β (n + 1) := by
      exact Nat.sub_le_sub_right hmono 1
    rw [Finset.mem_Icc]
    exact ⟨hI.1, hI.2.trans (Nat.mul_le_mul_left 2 hhmono)⟩
  have hcard : (coverSet β n).card ≤
      cutoffCount (shadow β (β (runStart β (n - 1))))
        (2 * runHeight β (n + 1)) := Finset.card_le_card hsub
  rw [stateB, cutoffRatio]
  simp only [Nat.cast_mul, Nat.cast_ofNat]
  change ((coverSet β n).card : ℝ) /
      (2 * (runHeight β (n + 1) : ℝ)) ≤
    (cutoffCount (shadow β (β (runStart β (n - 1))))
      (2 * runHeight β (n + 1)) : ℝ) /
      (2 * (runHeight β (n + 1) : ℝ))
  apply div_le_div_of_nonneg_right _ (by positivity)
  exact_mod_cast hcard

theorem normalized_interval_process_impossible {β : ℕ → Fin 2} {M : ℝ}
    (hM : M < Erdos1211Dynamics.sharpConstant)
    (hnorm : ∀ q r : ℕ, 1 ≤ q → q < r →
      β (q - 1) ≠ β q → β (r - 1) ≠ β r →
      (∀ k, q ≤ k → k < r → β k = β q) →
      2 * (q - 1) < r)
    (hbound : ∀ i : Fin 2, ∀ᶠ N : ℕ in atTop,
      cutoffRatio (shadow β i) N < M) : False := by
  have hMone : M < 1 := hM.trans Erdos1211Dynamics.sharpConstant_lt_one
  have hβ : ¬ EventuallyConstant β :=
    not_eventuallyConstant_of_shadow_bounds hMone hbound
  apply Erdos1211Dynamics.no_eventually_bounded_orbit_below_sharp hM
    (stateA β) (stateB β) (controlZ β)
  · exact stateA_nonneg β
  · exact stateB_nonneg β
  · exact controlZ_bounds hβ hnorm
  · exact stateA_recurrence hβ hnorm
  · exact stateB_recurrence hβ
  · obtain ⟨T0, hT0⟩ := Filter.eventually_atTop.1 (hbound 0)
    obtain ⟨T1, hT1⟩ := Filter.eventually_atTop.1 (hbound 1)
    refine ⟨max 1 (max T0 T1), ?_⟩
    intro n hn
    have hn1 : 1 ≤ n := (le_max_left _ _).trans hn
    have hcut : max T0 T1 ≤ 2 * runHeight β (n + 1) := by
      have hlower := runHeight_lower hβ n
      have hTn : max T0 T1 ≤ n := (le_max_right _ _).trans hn
      omega
    have hratio (i : Fin 2) :
        cutoffRatio (shadow β i) (2 * runHeight β (n + 1)) < M := by
      generalize hi : i = c
      fin_cases c
      · exact hT0 _ ((le_max_left _ _).trans hcut)
      · exact hT1 _ ((le_max_right _ _).trans hcut)
    constructor
    · exact (stateA_le_shadow_ratio hβ n).trans (hratio _).le
    · exact (stateB_le_shadow_ratio hβ hn1).trans (hratio _).le

/-- The sharp two-colour interval-process lemma. -/
theorem interval_process (α : ℕ → Fin 2) :
    Erdos1211Dynamics.sharpConstant ≤
      max (upperDensity (shadow α 0)) (upperDensity (shadow α 1)) := by
  by_contra hnot
  have hmax : max (upperDensity (shadow α 0)) (upperDensity (shadow α 1)) <
      Erdos1211Dynamics.sharpConstant := lt_of_not_ge hnot
  let M : ℝ :=
    (max (upperDensity (shadow α 0)) (upperDensity (shadow α 1)) +
      Erdos1211Dynamics.sharpConstant) / 2
  have hM : M < Erdos1211Dynamics.sharpConstant := by
    dsimp only [M]
    linarith
  have h0M : upperDensity (shadow α 0) < M := by
    dsimp only [M]
    have := le_max_left (upperDensity (shadow α 0)) (upperDensity (shadow α 1))
    linarith
  have h1M : upperDensity (shadow α 1) < M := by
    dsimp only [M]
    have := le_max_right (upperDensity (shadow α 0)) (upperDensity (shadow α 1))
    linarith
  obtain ⟨β, hshadow, hnorm⟩ := exists_normalized_shadow_subcoloring α
  apply normalized_interval_process_impossible hM hnorm
  intro i
  have hiM : upperDensity (shadow β i) < M := by
    fin_cases i
    · exact (upperDensity_mono (hshadow 0)).trans_lt h0M
    · exact (upperDensity_mono (hshadow 1)).trans_lt h1M
  exact eventually_cutoffRatio_lt hiM

end

end Erdos1211Shadow
