/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.Bilu.Section5CubeLemma

/-!
# The full-dimensional branch of Bilu's Cube Lemma

A cube returned by Proposition 5.4 may be degenerate.  If its direction
span is proper, its large slice already lies in a proper affine plane.  In
the other branch its direction-synthesis map is a linear equivalence, so
the full-dimensional cube geometry of `Section5CubeGeometry` applies.
-/

namespace Erdos186.CFP.Bilu.Section5FullCube

open Set Module Submodule
open Section5TwoN Section5CubeGeometry Section5CubeLemma

noncomputable section

attribute [local instance] Classical.propDecidable

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]
  [FiniteDimensional ℝ V] [DecidableEq V]

/-- Synthesis from cube coordinates to the ambient vector space. -/
def cubeDirsLinearMap {n : ℕ} (dirs : Fin n → V) :
    (Fin n → ℝ) →ₗ[ℝ] V where
  toFun t := ∑ i, t i • dirs i
  map_add' := by
    intro x y
    simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
  map_smul' := by
    intro c x
    simp only [Pi.smul_apply, RingHom.id_apply, smul_eq_mul, smul_smul,
      Finset.smul_sum]

@[simp] theorem cubeDirsLinearMap_apply {n : ℕ} (dirs : Fin n → V)
    (t : Fin n → ℝ) :
    cubeDirsLinearMap dirs t = ∑ i, t i • dirs i := rfl

/-- The synthesis range is the span of the cube directions. -/
theorem range_cubeDirsLinearMap {n : ℕ} (dirs : Fin n → V) :
    LinearMap.range (cubeDirsLinearMap dirs) =
      Submodule.span ℝ (Set.range dirs) := by
  apply le_antisymm
  · rintro _ ⟨t, rfl⟩
    change ∑ i, t i • dirs i ∈ Submodule.span ℝ (Set.range dirs)
    apply Submodule.sum_mem
    intro i _
    exact Submodule.smul_mem _ _
      (Submodule.subset_span (Set.mem_range_self i))
  · rw [Submodule.span_le]
    rintro x ⟨i, rfl⟩
    apply LinearMap.mem_range.mpr
    refine ⟨singleCoordinate i 1, ?_⟩
    simp [cubeDirsLinearMap, singleCoordinate]

/-- A spanning `n`-tuple in an `n`-dimensional real vector space gives a
linear coordinate equivalence. -/
theorem exists_cubeDirsLinearEquiv_of_span_eq_top {n : ℕ}
    (dirs : Fin n → V) (hfinrank : finrank ℝ V = n)
    (hspan : Submodule.span ℝ (Set.range dirs) = ⊤) :
    ∃ e : (Fin n → ℝ) ≃ₗ[ℝ] V,
      ∀ t, e t = ∑ i, t i • dirs i := by
  let F := cubeDirsLinearMap dirs
  have hrange : LinearMap.range F = ⊤ := by
    simpa [F, range_cubeDirsLinearMap] using hspan
  have hsurj : Function.Surjective F := LinearMap.range_eq_top.mp hrange
  have hrank := F.finrank_range_add_finrank_ker
  have hdomain : finrank ℝ (Fin n → ℝ) = n := by simp
  have hkerRank : finrank ℝ (LinearMap.ker F) = 0 := by
    rw [hrange, finrank_top, hfinrank, hdomain] at hrank
    omega
  have hker : LinearMap.ker F = ⊥ := by
    rw [← Submodule.finrank_eq_zero]
    exact hkerRank
  have hinj : Function.Injective F := LinearMap.ker_eq_bot.mp hker
  let e : (Fin n → ℝ) ≃ₗ[ℝ] V :=
    LinearEquiv.ofBijective F ⟨hinj, hsurj⟩
  exact ⟨e, fun _ ↦ rfl⟩

/-- The affine plane generated by the directions of a possibly degenerate
cube. -/
def cubeDirectionPlane {n : ℕ} (center : V) (dirs : Fin n → V) :
    AffineSubspace ℝ V :=
  AffineSubspace.mk' center (Submodule.span ℝ (Set.range dirs))

/-- Every point in the zero-subspace tube lies in the direction plane. -/
theorem mem_cubeDirectionPlane_of_mem_cubeTube_bot {n : ℕ}
    (center : V) (dirs : Fin n → V) {x : V}
    (hx : x ∈ cubeTube center dirs (⊥ : Submodule ℝ V)) :
    x ∈ cubeDirectionPlane center dirs := by
  obtain ⟨t, _ht, hres⟩ := hx
  have hres0 : x - cubePoint center dirs t = 0 := by simpa using hres
  have hxEq : x = cubePoint center dirs t := sub_eq_zero.mp hres0
  rw [cubeDirectionPlane, AffineSubspace.mem_mk']
  rw [hxEq, cubePoint]
  change (center + ∑ i, t i • dirs i) - center ∈
    Submodule.span ℝ (Set.range dirs)
  rw [add_sub_cancel_left]
  apply Submodule.sum_mem
  intro i _
  exact Submodule.smul_mem _ _
    (Submodule.subset_span (Set.mem_range_self i))

/-- If the direction span is proper, a zero-tube witness is already an
affine-slice witness with the same denominator. -/
def affineSliceWitnessOfCubeSpanNeTop {n C : ℕ} {S : Finset V}
    {center : V} (W : TubeCubeWitness n C S center (⊥ : Submodule ℝ V))
    (hfinrank : finrank ℝ V = n)
    (hspan : Submodule.span ℝ (Set.range W.dirs) ≠ ⊤) :
    AffineSliceWitness n C S where
  plane := cubeDirectionPlane center W.dirs
  dimension_lt := by
    rw [cubeDirectionPlane]
    rw [AffineSubspace.direction_mk']
    change finrank ℝ (Submodule.span ℝ (Set.range W.dirs)) < n
    have hdim := Submodule.finrank_lt hspan
    simpa [hfinrank] using hdim
  slice := W.slice
  slice_subset := W.slice_subset
  slice_mem_plane := fun x hx ↦
    mem_cubeDirectionPlane_of_mem_cubeTube_bot center W.dirs
      (W.slice_mem_tube x hx)
  card_le := W.card_le

/-- Exact dichotomy needed after the Cube Lemma: either its large slice is
already contained in a proper affine plane, or its directions provide the
coordinate equivalence used by equation (5.13). -/
theorem affineSlice_or_cubeDirsLinearEquiv {n C : ℕ} {S : Finset V}
    {center : V} (W : TubeCubeWitness n C S center (⊥ : Submodule ℝ V))
    (hfinrank : finrank ℝ V = n) :
    Nonempty (AffineSliceWitness n C S) ∨
      ∃ e : (Fin n → ℝ) ≃ₗ[ℝ] V,
        (∀ t, e t = ∑ i, t i • W.dirs i) ∧
        (∀ s, affineCubeVertex e center s =
          cubeVertex center W.dirs s) := by
  by_cases hspan : Submodule.span ℝ (Set.range W.dirs) = ⊤
  · right
    obtain ⟨e, he⟩ := exists_cubeDirsLinearEquiv_of_span_eq_top
      W.dirs hfinrank hspan
    refine ⟨e, he, ?_⟩
    intro s
    simp [affineCubeVertex, cubeVertex, cubePoint, he]
  · left
    exact ⟨affineSliceWitnessOfCubeSpanNeTop W hfinrank hspan⟩

/-- Full-dimensional output of the Cube Lemma in the exact format consumed
by the face and outside-cell arguments. -/
structure FullCubeWitness (n proportionConstant : ℕ) (S : Finset V) where
  center : V
  coordinates : (Fin n → ℝ) ≃ₗ[ℝ] V
  slice : Finset V
  slice_subset : slice ⊆ S
  slice_mem_closed : ∀ x ∈ slice,
    x ∈ affineCubeClosed coordinates center
  vertex_mem : ∀ s : Fin n → Fin 2,
    affineCubeVertex coordinates center s ∈ S
  card_le : S.card ≤ proportionConstant * slice.card

/-- Translate zero-tube membership through the direction equivalence. -/
theorem mem_affineCubeClosed_of_mem_cubeTube_bot {n : ℕ}
    (center : V) (dirs : Fin n → V)
    (e : (Fin n → ℝ) ≃ₗ[ℝ] V)
    (he : ∀ t, e t = ∑ i, t i • dirs i) {x : V}
    (hx : x ∈ cubeTube center dirs (⊥ : Submodule ℝ V)) :
    x ∈ affineCubeClosed e center := by
  obtain ⟨t, ht, hres⟩ := hx
  have hres0 : x - cubePoint center dirs t = 0 := by simpa using hres
  have hxEq : x = cubePoint center dirs t := sub_eq_zero.mp hres0
  intro i
  have hePoint : cubePoint center dirs t = center + e t := by
    simp [cubePoint, he]
  rw [hxEq, hePoint]
  simp
  exact ht i

/-- Cube Lemma 5.2 followed by the exact dimension dichotomy. -/
theorem exists_affineSlice_or_fullCube {n tau : ℕ} (hn : 0 < n)
    (S : Finset V) (hS : S.Nonempty) (hfinrank : finrank ℝ V = n)
    (hdouble :
      (Section7FreimanMap.pairSumset S).card ≤ tau * S.card) :
    Nonempty (AffineSliceWitness n (cubeLemmaConstant n tau) S) ∨
      Nonempty (FullCubeWitness n (cubeLemmaConstant n tau) S) := by
  obtain ⟨center, ⟨W⟩⟩ :=
    exists_cubeLemmaWitness hn S hS hfinrank tau hdouble
  rcases affineSlice_or_cubeDirsLinearEquiv W hfinrank with hslice | hfull
  · exact Or.inl hslice
  · right
    obtain ⟨e, he, hvertices⟩ := hfull
    refine ⟨{
      center := center
      coordinates := e
      slice := W.slice
      slice_subset := W.slice_subset
      slice_mem_closed := ?_
      vertex_mem := fun s ↦ hvertices s ▸ W.vertex_mem s
      card_le := W.card_le }⟩
    intro x hx
    exact mem_affineCubeClosed_of_mem_cubeTube_bot center W.dirs e he
      (W.slice_mem_tube x hx)

end

end Erdos186.CFP.Bilu.Section5FullCube

#print axioms Erdos186.CFP.Bilu.Section5FullCube.affineSlice_or_cubeDirsLinearEquiv
#print axioms Erdos186.CFP.Bilu.Section5FullCube.exists_affineSlice_or_fullCube
