/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.Bilu.Section92OuterInjectivityBridge
import ErdosProblems.Erdos186.CFP.Bilu.SaturatedFlag

/-!
# Bilu Section 9.2: a short primitive kernel direction

Failure of injectivity on a seminorm ball gives two bounded integral
points with the same image.  Their difference is a nonzero kernel vector
of seminorm at most twice the radius.  The source then divides this vector
by its integral content before quotienting.  Instead of choosing signs or
gcd representatives, this file defines that primitive direction
canonically as the saturation of its rank-one integral span.

The saturation is contained in the kernel, admits an integral complement,
and therefore supplies the exact algebraic quotient/factorization used in
the rank descent.  The remaining analytic ingredient is the projected-body
volume estimate.
-/

namespace Erdos186.CFP.Bilu.Section92ShortKernel

open Module Submodule
open Mahler
open SaturatedFlag

noncomputable section

/-! ## Short kernel vectors -/

/-- The bounded nonzero kernel vector produced by a failed injectivity
test. -/
structure ShortKernelVector {n : ℕ} {H : Type*} [AddCommGroup H]
    (p : Seminorm ℝ (Fin n → ℝ))
    (phi : IntegralPoint n →+ H) (T : ℝ) where
  vector : IntegralPoint n
  ne_zero : vector ≠ 0
  map_eq_zero : phi vector = 0
  seminorm_le : p (integralEmbed vector) ≤ 2 * T

/-- Noninjectivity on the closed `T`-ball produces a literal short
nonzero integral kernel vector. -/
theorem exists_shortKernelVector_of_not_injOn_ball
    {n : ℕ} {H : Type*} [AddCommGroup H]
    (p : Seminorm ℝ (Fin n → ℝ))
    (phi : IntegralPoint n →+ H) (T : ℝ)
    (hbad : ¬ Set.InjOn phi
      {z : IntegralPoint n | p (integralEmbed z) ≤ T}) :
    Nonempty (ShortKernelVector p phi T) := by
  simp only [Set.InjOn] at hbad
  push Not at hbad
  obtain ⟨x, hx, y, hy, hxy, hne⟩ := hbad
  refine ⟨⟨x - y, sub_ne_zero.mpr hne, ?_, ?_⟩⟩
  · rw [map_sub, hxy, sub_self]
  · have hembed : integralEmbed (x - y) =
        integralEmbed x - integralEmbed y := by
      ext i
      simp [integralEmbed]
    rw [hembed]
    calc
      p (integralEmbed x - integralEmbed y) ≤
          p (integralEmbed x) + p (integralEmbed y) :=
        map_sub_le_add p _ _
      _ ≤ T + T := add_le_add hx hy
      _ = 2 * T := by ring

/-! ## Saturation of an integral submodule -/

/-- The smallest saturated submodule containing `P`.  This is the
coordinate-free operation of dividing every vector by its integral
content. -/
def saturation {M : Type*} [AddCommGroup M]
    (P : Submodule ℤ M) : Submodule ℤ M :=
  sInf {Q : Submodule ℤ M | IsSaturated Q ∧ P ≤ Q}

theorem le_saturation {M : Type*} [AddCommGroup M]
    (P : Submodule ℤ M) : P ≤ saturation P := by
  apply le_sInf
  intro Q hQ
  exact hQ.2

theorem saturation_le {M : Type*} [AddCommGroup M]
    {P Q : Submodule ℤ M} (hQ : IsSaturated Q) (hPQ : P ≤ Q) :
    saturation P ≤ Q := by
  exact sInf_le ⟨hQ, hPQ⟩

theorem isSaturated_saturation {M : Type*}
    [AddCommGroup M]
    (P : Submodule ℤ M) : IsSaturated (saturation P) := by
  intro a x ha hax
  rw [show saturation P = sInf
    {Q : Submodule ℤ M | IsSaturated Q ∧ P ≤ Q} from rfl]
  rw [Submodule.mem_sInf]
  intro Q hQ
  exact hQ.1 a x ha ((sInf_le hQ) hax)

/-- Kernels of maps into torsion-free integral modules are saturated. -/
theorem isSaturated_ker {M H : Type*}
    [AddCommGroup M] [AddCommGroup H] [Module.IsTorsionFree ℤ H]
    (f : M →ₗ[ℤ] H) : IsSaturated (LinearMap.ker f) := by
  intro a x ha hax
  rw [LinearMap.mem_ker] at hax ⊢
  have hsmul : a • f x = 0 := by
    rw [← f.map_smul]
    exact hax
  exact (smul_eq_zero.mp hsmul).resolve_left ha

/-! ## The canonical primitive line inside the kernel -/

/-- The primitive integral line generated by `q`: the saturation of its
integral span. -/
def primitiveDirection {n : ℕ} (q : IntegralPoint n) :
    Submodule ℤ (IntegralPoint n) :=
  saturation (ℤ ∙ q)

theorem mem_primitiveDirection {n : ℕ} (q : IntegralPoint n) :
    q ∈ primitiveDirection q := by
  exact le_saturation (ℤ ∙ q) (Submodule.mem_span_singleton_self q)

theorem isSaturated_primitiveDirection {n : ℕ}
    (q : IntegralPoint n) : IsSaturated (primitiveDirection q) :=
  isSaturated_saturation (ℤ ∙ q)

/-- The saturated primitive direction remains inside the rational line
spanned by its generating vector. -/
theorem primitiveDirection_le_rationalSpanLattice {n : ℕ}
    (q : IntegralPoint n) :
    primitiveDirection q ≤
      SaturatedFlag.rationalSpanLattice ({q} : Set (IntegralPoint n)) := by
  apply saturation_le
    (SaturatedFlag.isSaturated_rationalSpanLattice ({q} : Set (IntegralPoint n)))
  rw [Submodule.span_singleton_le_iff_mem]
  change SaturatedFlag.rationalEmbed n q ∈
    Submodule.span ℚ
      (SaturatedFlag.rationalEmbed n '' ({q} : Set (IntegralPoint n)))
  apply Submodule.subset_span
  exact ⟨q, Set.mem_singleton q, rfl⟩

theorem primitiveDirection_ne_bot {n : ℕ} {q : IntegralPoint n}
    (hq : q ≠ 0) : primitiveDirection q ≠ ⊥ := by
  intro hbot
  have : q = 0 := by
    rw [← Submodule.mem_bot (R := ℤ), ← hbot]
    exact mem_primitiveDirection q
  exact hq this

/-- The saturated line of a nonzero integral vector has an integral basis
with exactly one element. -/
theorem exists_basis_primitiveDirection {n : ℕ} {q : IntegralPoint n}
    (hq : q ≠ 0) :
    Nonempty (Basis (Fin 1) ℤ (primitiveDirection q)) := by
  classical
  obtain ⟨k, b⟩ := Submodule.basisOfPid
    (Pi.basisFun ℤ (Fin n)) (primitiveDirection q)
  let vZ : Fin k → IntegralPoint n :=
    fun i ↦ ((b i : primitiveDirection q) : IntegralPoint n)
  have hvZ : LinearIndependent ℤ vZ := by
    exact b.linearIndependent.map' (primitiveDirection q).subtype (by simp)
  let vQ : Fin k → (Fin n → ℚ) :=
    fun i ↦ SaturatedFlag.rationalEmbed n (vZ i)
  have hvQ : LinearIndependent ℚ vQ := by
    change LinearIndependent ℚ (fun i ↦
      algebraMap ℤ ℚ ∘ vZ i)
    rw [linearIndependent_algebraMap_comp_iff]
    exact hvZ
  have hspan : Submodule.span ℚ (Set.range vQ) ≤
      ℚ ∙ SaturatedFlag.rationalEmbed n q := by
    rw [Submodule.span_le]
    rintro z ⟨i, rfl⟩
    have hi := primitiveDirection_le_rationalSpanLattice q (b i).property
    change SaturatedFlag.rationalEmbed n (vZ i) ∈
      Submodule.span ℚ
        (SaturatedFlag.rationalEmbed n '' ({q} : Set (IntegralPoint n))) at hi
    simpa [vQ] using hi
  have hqQ : SaturatedFlag.rationalEmbed n q ≠ 0 := by
    intro hzero
    apply hq
    funext i
    have hi := congrFun hzero i
    change (q i : ℚ) = 0 at hi
    exact_mod_cast hi
  have hk_le : k ≤ 1 := by
    have hdim := Submodule.finrank_mono hspan
    rw [finrank_span_eq_card hvQ, Fintype.card_fin,
      finrank_span_singleton hqQ] at hdim
    exact hdim
  have hk_ne : k ≠ 0 := by
    intro hk
    subst k
    apply primitiveDirection_ne_bot hq
    rw [Submodule.eq_bot_iff]
    intro x hx
    let xp : primitiveDirection q := ⟨x, hx⟩
    have hxp : xp = 0 := by
      simpa [xp] using (b.sum_repr xp).symm
    exact congrArg Subtype.val hxp
  have hk : k = 1 := by omega
  subst k
  exact ⟨b⟩

/-- If the original vector lies in the kernel, then its whole primitive
direction lies in the kernel.  Torsion-freeness of the target is exactly
what justifies division by the vector's integral content. -/
theorem primitiveDirection_le_ker {n : ℕ}
    {H : Type*} [AddCommGroup H] [Module.IsTorsionFree ℤ H]
    (phi : IntegralPoint n →+ H) {q : IntegralPoint n}
    (hq : phi q = 0) :
    primitiveDirection q ≤ LinearMap.ker phi.toIntLinearMap := by
  apply saturation_le (isSaturated_ker phi.toIntLinearMap)
  rw [Submodule.span_singleton_le_iff_mem, LinearMap.mem_ker]
  exact hq

/-- A primitive kernel direction has an integral complementary lattice.
This is the Smith-normal-form basis extension used in the quotient step. -/
theorem exists_complement_primitiveDirection {n : ℕ}
    (q : IntegralPoint n) :
    ∃ Q : Submodule ℤ (IntegralPoint n),
      IsCompl (primitiveDirection q) Q := by
  exact exists_isCompl_of_isSaturated (Pi.basisFun ℤ (Fin n))
    (primitiveDirection q) (isSaturated_primitiveDirection q)

/-- A complement to a nonzero primitive direction is a proper submodule;
this is the integral form of strict rank decrease. -/
theorem complement_ne_top {n : ℕ} {q : IntegralPoint n}
    (hq : q ≠ 0) {Q : Submodule ℤ (IntegralPoint n)}
    (hcompl : IsCompl (primitiveDirection q) Q) : Q ≠ ⊤ := by
  intro htop
  have hqQ : q ∈ Q := by rw [htop]; exact Submodule.mem_top
  have hzero : q = 0 :=
    Submodule.disjoint_def.mp hcompl.disjoint q
      (mem_primitiveDirection q) hqQ
  exact hq hzero

/-- Fully explicit integral quotient data.  The primitive direction has
rank one, its chosen complement has rank `n-1`, and the original map
vanishes on the direction. -/
structure PrimitiveIntegralQuotient {n : ℕ} {H : Type*} [AddCommGroup H]
    (phi : IntegralPoint n →+ H) (q : IntegralPoint n) where
  complement : Submodule ℤ (IntegralPoint n)
  isCompl : IsCompl (primitiveDirection q) complement
  direction_le_ker :
    primitiveDirection q ≤ LinearMap.ker phi.toIntLinearMap
  primitiveBasis : Basis (Fin 1) ℤ (primitiveDirection q)
  complementRank : ℕ
  complementBasis : Basis (Fin complementRank) ℤ complement
  rank_eq : complementRank + 1 = n

/-- A nonzero kernel vector canonically supplies a rank-`n-1` integral
quotient presentation. -/
theorem exists_primitiveIntegralQuotient {n : ℕ}
    {H : Type*} [AddCommGroup H] [Module.IsTorsionFree ℤ H]
    (phi : IntegralPoint n →+ H) {q : IntegralPoint n}
    (hq0 : q ≠ 0) (hqker : phi q = 0) :
    Nonempty (PrimitiveIntegralQuotient phi q) := by
  classical
  obtain ⟨bP⟩ := exists_basis_primitiveDirection hq0
  obtain ⟨Q, hPQ⟩ := exists_complement_primitiveDirection q
  obtain ⟨k, bQ⟩ := Submodule.basisOfPid
    (Pi.basisFun ℤ (Fin n)) Q
  let e : (primitiveDirection q × Q) ≃ₗ[ℤ] IntegralPoint n :=
    (primitiveDirection q).prodEquivOfIsCompl Q hPQ
  let bM : Basis (Fin 1 ⊕ Fin k) ℤ (IntegralPoint n) :=
    (bP.prod bQ).map e
  let indexEquiv : (Fin 1 ⊕ Fin k) ≃ Fin n :=
    bM.indexEquiv (Pi.basisFun ℤ (Fin n))
  have hcard : 1 + k = n := by
    simpa only [Fintype.card_sum, Fintype.card_fin] using
      Fintype.card_congr indexEquiv
  refine ⟨⟨Q, hPQ, primitiveDirection_le_ker phi hqker,
    bP, k, bQ, ?_⟩⟩
  omega

/-- The map factors through the quotient by the full primitive direction.
-/
noncomputable def factoredMap {n : ℕ}
    {H : Type*} [AddCommGroup H] [Module.IsTorsionFree ℤ H]
    (phi : IntegralPoint n →+ H) {q : IntegralPoint n}
    (hq : phi q = 0) :
    (IntegralPoint n ⧸ primitiveDirection q) →ₗ[ℤ] H :=
  Submodule.liftQ (primitiveDirection q) phi.toIntLinearMap
    (primitiveDirection_le_ker phi hq)

@[simp]
theorem factoredMap_mkQ {n : ℕ}
    {H : Type*} [AddCommGroup H] [Module.IsTorsionFree ℤ H]
    (phi : IntegralPoint n →+ H) {q x : IntegralPoint n}
    (hq : phi q = 0) :
    factoredMap phi hq ((primitiveDirection q).mkQ x) = phi x := rfl

/-! ## Packaged source step -/

/-- The entire algebraic output of a failed enlarged-ball injectivity
test: a short nonzero kernel vector, its saturated primitive direction,
an integral complement, and the strictness of that complement. -/
structure PrimitiveKernelStep {n : ℕ} {H : Type*} [AddCommGroup H]
    (p : Seminorm ℝ (Fin n → ℝ))
    (phi : IntegralPoint n →+ H) (T : ℝ) where
  short : ShortKernelVector p phi T
  quotient : PrimitiveIntegralQuotient phi short.vector

/-- A failed injectivity test constructs the primitive integral descent
step with no user-supplied basis or quotient data. -/
theorem exists_primitiveKernelStep_of_not_injOn_ball
    {n : ℕ} {H : Type*} [AddCommGroup H]
    [Module.IsTorsionFree ℤ H]
    (p : Seminorm ℝ (Fin n → ℝ))
    (phi : IntegralPoint n →+ H) (T : ℝ)
    (hbad : ¬ Set.InjOn phi
      {z : IntegralPoint n | p (integralEmbed z) ≤ T}) :
    Nonempty (PrimitiveKernelStep p phi T) := by
  obtain ⟨short⟩ := exists_shortKernelVector_of_not_injOn_ball p phi T hbad
  obtain ⟨quotient⟩ := exists_primitiveIntegralQuotient phi
    short.ne_zero short.map_eq_zero
  exact ⟨⟨short, quotient⟩⟩

end

end Erdos186.CFP.Bilu.Section92ShortKernel

#print axioms Erdos186.CFP.Bilu.Section92ShortKernel.exists_shortKernelVector_of_not_injOn_ball
#print axioms Erdos186.CFP.Bilu.Section92ShortKernel.primitiveDirection_le_ker
#print axioms Erdos186.CFP.Bilu.Section92ShortKernel.exists_primitiveKernelStep_of_not_injOn_ball
