/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
import ErdosProblems.Erdos186.CFP.Bilu.Section5TwoN
import Mathlib.Algebra.Module.Submodule.Union
import Mathlib.LinearAlgebra.Dual.Lemmas

/-!
# Generic finite-dimensional projections in Bilu Theorem 5.6

Bilu projects along a subspace which is simultaneously in general position
with every span generated by a subset of the finite difference set.  The
family of spans is finite.  We construct the kernel one hyperplane at a
time, choosing each functional to be nonzero on every currently nonzero
intersection.  A finite union of proper subspaces of the dual cannot cover
the dual over `ℝ`, so one functional works simultaneously.
-/

namespace Erdos186.CFP.Bilu.Section5GenericProjection

open Set Module Submodule
open Section7FreimanMap

noncomputable section

variable {V : Type*} [AddCommGroup V] [Module ℝ V]
  [FiniteDimensional ℝ V]

/-- One generic hyperplane lowers the dimension of every nonzero member of
a finite family by exactly one. -/
theorem exists_functional_finrank_inf_ker_add_one
    (family : Finset (Submodule ℝ V)) :
    ∃ f : Module.Dual ℝ V, ∀ U ∈ family, U ≠ ⊥ →
      finrank ℝ (U ⊓ LinearMap.ker f : Submodule ℝ V) + 1 =
        finrank ℝ U := by
  classical
  let active : Finset (Submodule ℝ V) := family.filter fun U ↦ U ≠ ⊥
  have hactive_ne : ∀ U : {U // U ∈ active}, (U : Submodule ℝ V) ≠ ⊥ := by
    intro U
    have h := U.property
    change (U : Submodule ℝ V) ∈ family.filter (fun W ↦ W ≠ ⊥) at h
    exact (Finset.mem_filter.mp h).2
  let chosen : {U // U ∈ active} → V := fun U ↦
    (Submodule.exists_mem_ne_zero_of_ne_bot
      (p := (U : Submodule ℝ V)) (hactive_ne U)).choose
  have hchosen_mem : ∀ U : {U // U ∈ active}, chosen U ∈ (U : Submodule ℝ V) := by
    intro U
    exact (Submodule.exists_mem_ne_zero_of_ne_bot
      (p := (U : Submodule ℝ V)) (hactive_ne U)).choose_spec.1
  have hchosen_ne : ∀ U : {U // U ∈ active}, chosen U ≠ 0 := by
    intro U
    exact (Submodule.exists_mem_ne_zero_of_ne_bot
      (p := (U : Submodule ℝ V)) (hactive_ne U)).choose_spec.2
  obtain ⟨f, hf⟩ := Module.exists_dual_forall_apply_ne_zero
    (K := ℝ) (M := V) chosen hchosen_ne
  refine ⟨f, ?_⟩
  intro U hU hUne
  let Ua : {U // U ∈ active} := ⟨U, by simp [active, hU, hUne]⟩
  let g : Module.Dual ℝ U := f.domRestrict U
  have hg : g ≠ 0 := by
    intro hzero
    have hz := congrArg (fun q : Module.Dual ℝ U ↦
      q ⟨chosen Ua, hchosen_mem Ua⟩) hzero
    have hfne := hf Ua
    simp only [g, LinearMap.domRestrict_apply, LinearMap.zero_apply] at hz
    exact hfne hz
  have hker : LinearMap.ker g =
      (U ⊓ LinearMap.ker f).comap U.subtype := by
    ext x
    simp [g]
  have hfin := Module.Dual.finrank_ker_add_one_of_ne_zero hg
  rw [hker] at hfin
  have heq :=
    (Submodule.comapSubtypeEquivOfLe (show U ⊓ LinearMap.ker f ≤ U from inf_le_left)).finrank_eq
  rw [heq] at hfin
  exact hfin

/-- Iterating the preceding hyperplane construction gives a subspace in
simultaneous general position with a finite family.  Intersecting with the
kernel lowers each member's dimension once per step until it reaches zero. -/
theorem exists_submodule_finrank_inf_eq_tsub
    (family : Finset (Submodule ℝ V)) (steps : ℕ) :
    ∃ A : Submodule ℝ V, ∀ U ∈ family,
      finrank ℝ (A ⊓ U : Submodule ℝ V) = finrank ℝ U - steps := by
  classical
  induction steps with
  | zero =>
      refine ⟨⊤, ?_⟩
      intro U _hU
      rw [top_inf_eq]
      simp
  | succ steps ih =>
      obtain ⟨A, hA⟩ := ih
      let current : Finset (Submodule ℝ V) :=
        family.image fun U ↦ A ⊓ U
      obtain ⟨f, hf⟩ := exists_functional_finrank_inf_ker_add_one current
      refine ⟨A ⊓ LinearMap.ker f, ?_⟩
      intro U hU
      have hPmem : A ⊓ U ∈ current :=
        Finset.mem_image.mpr ⟨U, hU, rfl⟩
      have hprev := hA U hU
      by_cases hP : A ⊓ U = ⊥
      · have hleft :
            (A ⊓ LinearMap.ker f) ⊓ U = (⊥ : Submodule ℝ V) := by
          apply le_antisymm
          · rw [← hP]
            intro x hx
            have hxP : x ∈ A ⊓ U := ⟨hx.1.1, hx.2⟩
            exact hxP
          · exact bot_le
        rw [hleft, finrank_bot]
        have hzero : finrank ℝ U - steps = 0 := by
          rw [← hprev, hP, finrank_bot]
        omega
      · have hdrop := hf (A ⊓ U) hPmem hP
        have hinf :
            ((A ⊓ LinearMap.ker f) ⊓ U : Submodule ℝ V) =
              (A ⊓ U) ⊓ LinearMap.ker f := by
          ext x
          simp only [mem_inf]
          tauto
        rw [hinf]
        omega

/-- Source form of Bilu's "generic subspace": `A` has codimension
`steps` (until the ambient dimension is exhausted), and it has the expected
minimal intersection dimension with every member of the prescribed finite
family. -/
theorem exists_generic_subspace
    (family : Finset (Submodule ℝ V)) (steps : ℕ) :
    ∃ A : Submodule ℝ V,
      finrank ℝ A = finrank ℝ V - steps ∧
      ∀ U ∈ family,
        finrank ℝ (A ⊓ U : Submodule ℝ V) = finrank ℝ U - steps := by
  classical
  obtain ⟨A, hA⟩ :=
    exists_submodule_finrank_inf_eq_tsub (insert ⊤ family) steps
  refine ⟨A, ?_, ?_⟩
  · have htop := hA ⊤ (Finset.mem_insert_self ⊤ family)
    rw [inf_top_eq, finrank_top] at htop
    exact htop
  · intro U hU
    exact hA U (Finset.mem_insert_of_mem hU)

/-! ## The finite family needed for Theorem 5.6 -/

variable [DecidableEq V]

/-- All ordered differences from a finite set. -/
def differenceFinset (S : Finset V) : Finset V :=
  (S.product S).image fun p ↦ p.1 - p.2

@[simp]
theorem mem_differenceFinset (S : Finset V) (z : V) :
    z ∈ differenceFinset S ↔
      ∃ x ∈ S, ∃ y ∈ S, x - y = z := by
  simp only [differenceFinset, Finset.mem_image]
  constructor
  · rintro ⟨p, hp, rfl⟩
    exact ⟨p.1, (Finset.mem_product.mp hp).1,
      p.2, (Finset.mem_product.mp hp).2, rfl⟩
  · rintro ⟨x, hx, y, hy, rfl⟩
    exact ⟨(x, y), Finset.mem_product.mpr ⟨hx, hy⟩, rfl⟩

/-- The finite family of spans generated by subsets of a finite difference
set. -/
def differenceSpanFamily (S : Finset V) : Finset (Submodule ℝ V) := by
  classical
  exact (differenceFinset S).powerset.image fun (T : Finset V) ↦
    Submodule.span ℝ (T : Set V)

theorem span_mem_differenceSpanFamily (S T : Finset V)
    (hT : T ⊆ differenceFinset S) :
    Submodule.span ℝ (T : Set V) ∈ differenceSpanFamily S := by
  classical
  apply Finset.mem_image.mpr
  exact ⟨T, Finset.mem_powerset.mpr hT, rfl⟩

/-- Bilu's generic kernel for one finite set.  We build it relative to the
difference set of `S+S`, which both makes the quotient injective on `S+S`
and contains all affine directions generated inside `S`. -/
structure GenericProjection (S : Finset V) (rank : ℕ) where
  kernel : Submodule ℝ V
  finrank_kernel : finrank ℝ kernel = finrank ℝ V - rank
  generic : ∀ T : Finset V, T ⊆ differenceFinset (pairSumset S) →
    finrank ℝ
        (kernel ⊓ Submodule.span ℝ (T : Set V) : Submodule ℝ V) =
      finrank ℝ (Submodule.span ℝ (T : Set V)) - rank

/-- Existence of the simultaneous generic kernel used in the source proof
of Theorem 5.6. -/
def genericProjection (S : Finset V) (rank : ℕ) :
    GenericProjection S rank := by
  let hexists := exists_generic_subspace
    (differenceSpanFamily (pairSumset S)) rank
  let A := hexists.choose
  have hA := hexists.choose_spec
  exact
    { kernel := A
      finrank_kernel := hA.1
      generic := by
        intro T hT
        exact hA.2 _ (span_mem_differenceSpanFamily (pairSumset S) T hT) }

/-- The quotient map along Bilu's generic kernel is injective on the whole
double sumset. -/
theorem GenericProjection.mkQ_injOn_pairSumset
    {S : Finset V} {rank : ℕ} (P : GenericProjection S rank)
    (hrank : 0 < rank) :
    Set.InjOn P.kernel.mkQ (pairSumset S : Set V) := by
  intro x hx y hy hxy
  have hdiffA : x - y ∈ P.kernel := by
    rw [Submodule.mkQ_apply, Submodule.mkQ_apply] at hxy
    exact (Submodule.Quotient.eq P.kernel).mp hxy
  let T : Finset V := {x - y}
  have hT : T ⊆ differenceFinset (pairSumset S) := by
    intro z hz
    have hz' : z = x - y := Finset.mem_singleton.mp hz
    subst z
    exact mem_differenceFinset (pairSumset S) (x - y) |>.mpr
      ⟨x, hx, y, hy, rfl⟩
  have hgeneric := P.generic T hT
  have hspan_le :
      finrank ℝ (Submodule.span ℝ (T : Set V)) ≤ 1 := by
    have h := finrank_span_finset_le_card (R := ℝ) T
    change finrank ℝ (Submodule.span ℝ (T : Set V)) ≤ T.card at h
    simpa [T] using h
  have hright :
      finrank ℝ (Submodule.span ℝ (T : Set V)) - rank = 0 := by
    omega
  rw [hright] at hgeneric
  have hinf :
      P.kernel ⊓ Submodule.span ℝ (T : Set V) =
        (⊥ : Submodule ℝ V) :=
    Submodule.finrank_eq_zero.mp hgeneric
  have hdiffSpan : x - y ∈ Submodule.span ℝ (T : Set V) := by
    apply Submodule.subset_span
    simp [T]
  have hzero : x - y = 0 := by
    have : x - y ∈
        P.kernel ⊓ Submodule.span ℝ (T : Set V) := ⟨hdiffA, hdiffSpan⟩
    rw [hinf] at this
    exact this
  exact sub_eq_zero.mp hzero

/-- When the requested rank does not exceed the ambient dimension, the
generic quotient has exactly that rank. -/
theorem GenericProjection.finrank_quotient_eq
    {S : Finset V} {rank : ℕ} (P : GenericProjection S rank)
    (hrank : rank ≤ finrank ℝ V) :
    finrank ℝ (V ⧸ P.kernel) = rank := by
  have hquotient := P.kernel.finrank_quotient_add_finrank
  rw [P.finrank_kernel] at hquotient
  omega

/-- For a nonempty source set, injectivity on the double sumset implies
injectivity on the source itself by translating both points by one fixed
element of the set. -/
theorem GenericProjection.mkQ_injOn
    {S : Finset V} {rank : ℕ} (P : GenericProjection S rank)
    (hS : S.Nonempty) (hrank : 0 < rank) :
    Set.InjOn P.kernel.mkQ (S : Set V) := by
  obtain ⟨z, hz⟩ := hS
  intro x hx y hy hxy
  have hxz : x + z ∈ pairSumset S :=
    mem_pairSumset S (x + z) |>.mpr ⟨x, hx, z, hz, rfl⟩
  have hyz : y + z ∈ pairSumset S :=
    mem_pairSumset S (y + z) |>.mpr ⟨y, hy, z, hz, rfl⟩
  have hsum : P.kernel.mkQ (x + z) = P.kernel.mkQ (y + z) := by
    simpa using congrArg (fun w ↦ w + P.kernel.mkQ z) hxy
  exact add_right_cancel
    (P.mkQ_injOn_pairSumset hrank hxz hyz hsum)

/-- Genericity is precisely what prevents a low-dimensional quotient image
from hiding a high-dimensional source span.  This is the dimension argument
at the end of Bilu's proof of Theorem 5.6. -/
theorem GenericProjection.finrank_span_lt_of_map_lt
    {S : Finset V} {rank : ℕ} (P : GenericProjection S rank)
    (T : Finset V) (hT : T ⊆ differenceFinset (pairSumset S))
    (hmap : finrank ℝ
      ((Submodule.span ℝ (T : Set V)).map P.kernel.mkQ) < rank) :
    finrank ℝ (Submodule.span ℝ (T : Set V)) < rank := by
  let U : Submodule ℝ V := Submodule.span ℝ (T : Set V)
  let q := P.kernel.mkQ
  let g := q.domRestrict U
  have hranknull := LinearMap.finrank_range_add_finrank_ker g
  have hrange : LinearMap.range g = U.map q := by
    exact LinearMap.range_domRestrict U q
  have hker : LinearMap.ker g =
      (P.kernel ⊓ U : Submodule ℝ V).comap U.subtype := by
    rw [LinearMap.ker_domRestrict]
    change (LinearMap.ker q).comap U.subtype = _
    rw [Submodule.ker_mkQ]
    ext x
    simp
  rw [hrange, hker] at hranknull
  have hkerFinrank :
      finrank ℝ ((P.kernel ⊓ U : Submodule ℝ V).comap U.subtype) =
        finrank ℝ (P.kernel ⊓ U : Submodule ℝ V) :=
    (Submodule.comapSubtypeEquivOfLe
      (show (P.kernel ⊓ U : Submodule ℝ V) ≤ U from inf_le_right)).finrank_eq
  rw [hkerFinrank] at hranknull
  have hgeneric := P.generic T hT
  change finrank ℝ (P.kernel ⊓ U : Submodule ℝ V) =
    finrank ℝ U - rank at hgeneric
  change finrank ℝ (U.map q) < rank at hmap
  change finrank ℝ U < rank
  omega

end

end Erdos186.CFP.Bilu.Section5GenericProjection

#print axioms Erdos186.CFP.Bilu.Section5GenericProjection.exists_functional_finrank_inf_ker_add_one
#print axioms Erdos186.CFP.Bilu.Section5GenericProjection.exists_generic_subspace
#print axioms Erdos186.CFP.Bilu.Section5GenericProjection.GenericProjection.mkQ_injOn_pairSumset
#print axioms Erdos186.CFP.Bilu.Section5GenericProjection.GenericProjection.finrank_quotient_eq
#print axioms Erdos186.CFP.Bilu.Section5GenericProjection.GenericProjection.mkQ_injOn
#print axioms Erdos186.CFP.Bilu.Section5GenericProjection.GenericProjection.finrank_span_lt_of_map_lt
