import ErdosProblems.Erdos633.QuadraticAngleOrder

/-!
# Embeddings of a field generated by a primitive complex root

Cyclotomic irreducibility constructs an embedding sending the chosen root
to any coprime power. This is the algebraic existence input needed to
specialize the geometric conjugation equations to rational angle residues.
-/

namespace Erdos633

open Polynomial

theorem exists_primitive_root_adjoin_embedding (ζ : ℂ) (n k : ℕ)
    (hn : 0 < n) (hζ : IsPrimitiveRoot ζ n) (hk : k.Coprime n) :
    ∃ f : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ,
      f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩ = ζ ^ k := by
  have hi : IsIntegral ℚ ζ := (hζ.isIntegral hn).tower_top
  let pb := IntermediateField.adjoin.powerBasis hi
  have hpow : IsPrimitiveRoot (ζ ^ k) n := hζ.pow_of_coprime k hk
  have hgen : (algebraMap (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)) ℂ) pb.gen = ζ := rfl
  have hmin : minpoly ℚ pb.gen = minpoly ℚ ζ :=
    (minpoly.algebraMap_eq
      (algebraMap (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)) ℂ).injective pb.gen).symm.trans
      (congrArg (minpoly ℚ) hgen)
  have heval : aeval (ζ ^ k) (minpoly ℚ pb.gen) = 0 := by
    rw [hmin, ← cyclotomic_eq_minpoly_rat hζ hn, cyclotomic_eq_minpoly_rat hpow hn]
    exact minpoly.aeval ℚ (ζ ^ k)
  refine ⟨pb.lift (ζ ^ k) heval, ?_⟩
  exact pb.lift_gen (ζ ^ k) heval

theorem conjugate_mem_root_adjoin (ζ : ℂ) (hζ : ‖ζ‖ = 1)
    (x : ℂ) (hx : x ∈ IntermediateField.adjoin ℚ ({ζ} : Set ℂ)) :
    star x ∈ IntermediateField.adjoin ℚ ({ζ} : Set ℂ) := by
  induction hx using IntermediateField.adjoin_induction with
  | mem x hx =>
      have he : x = ζ := Set.mem_singleton_iff.mp hx
      subst x
      change starRingEnd ℂ ζ ∈ IntermediateField.adjoin ℚ ({ζ} : Set ℂ)
      rw [← Complex.inv_eq_conj hζ]
      exact (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)).inv_mem
        (IntermediateField.mem_adjoin_simple_self ℚ ζ)
  | algebraMap x =>
      simp
  | add x y hx hy ihx ihy =>
      simpa only [star_add] using
        (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)).add_mem ihx ihy
  | inv x hx ih =>
      simpa only [star_inv₀] using (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)).inv_mem ih
  | mul x y hx hy ihx ihy =>
      simpa only [star_mul, mul_comm] using
        (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)).mul_mem ihx ihy

def rootAdjoinConjugation (ζ : ℂ) (hζ : ‖ζ‖ = 1) :
    IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ]
      IntermediateField.adjoin ℚ ({ζ} : Set ℂ) where
  toFun x := ⟨star (x : ℂ), conjugate_mem_root_adjoin ζ hζ x x.property⟩
  map_zero' := by ext; simp
  map_one' := by ext; simp
  map_add' x y := by ext; simp
  map_mul' x y := by ext; simp
  commutes' x := by ext; simp

theorem root_adjoin_embedding_conjugation (ζ : ℂ) (hζ : ‖ζ‖ = 1)
    (f : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ)
    (hf : ‖f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩‖ = 1)
    (x : IntermediateField.adjoin ℚ ({ζ} : Set ℂ)) :
    f (rootAdjoinConjugation ζ hζ x) = star (f x) := by
  let c : ℂ →ₐ[ℚ] ℂ := (Complex.conjAe.restrictScalars ℚ).toAlgHom
  have heq : f.comp (rootAdjoinConjugation ζ hζ) = c.comp f := by
    apply IntermediateField.adjoin_algHom_ext
    intro z hz
    have he : z = ζ := Set.mem_singleton_iff.mp hz
    subst z
    let g : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) :=
      ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩
    have hg : rootAdjoinConjugation ζ hζ g = g⁻¹ := by
      apply Subtype.ext
      exact (Complex.inv_eq_conj hζ).symm
    change f (rootAdjoinConjugation ζ hζ g) = star (f g)
    rw [hg, map_inv₀, Complex.inv_eq_conj hf]
    rfl
  exact congrArg (fun g : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ => g x) heq

theorem root_adjoin_embedding_real (ζ : ℂ) (hζ : ‖ζ‖ = 1)
    (f : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ)
    (hf : ‖f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩‖ = 1)
    (x : IntermediateField.adjoin ℚ ({ζ} : Set ℂ)) (hx : (x : ℂ).im = 0) :
    (f x).im = 0 := by
  have hfix : rootAdjoinConjugation ζ hζ x = x := by
    apply Subtype.ext
    apply Complex.ext <;> simp [rootAdjoinConjugation, hx]
  have h := root_adjoin_embedding_conjugation ζ hζ f hf x
  rw [hfix] at h
  have hi := congrArg Complex.im h
  simp only [Complex.star_def, Complex.conj_im] at hi
  linarith

noncomputable def realRootField (ζ : ℂ) : Subfield ℝ :=
  (IntermediateField.adjoin ℚ ({ζ} : Set ℂ)).toSubfield.comap Complex.ofRealHom

noncomputable def realRootInclusion (ζ : ℂ) : realRootField ζ →+*
    IntermediateField.adjoin ℚ ({ζ} : Set ℂ) where
  toFun x := ⟨((x : ℝ) : ℂ), x.property⟩
  map_zero' := by ext; simp
  map_one' := by ext; simp
  map_add' x y := by ext; simp
  map_mul' x y := by ext; simp

noncomputable def realRootEmbedding (ζ : ℂ) (hζ : ‖ζ‖ = 1)
    (f : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ)
    (hf : ‖f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩‖ = 1) :
    realRootField ζ →+* ℝ where
  toFun x := (f (realRootInclusion ζ x)).re
  map_zero' := by simp
  map_one' := by simp
  map_add' x y := by simp
  map_mul' x y := by
    have hx := root_adjoin_embedding_real ζ hζ f hf (realRootInclusion ζ x) (by rfl)
    simp only [map_mul, Complex.mul_re, hx, zero_mul, sub_zero]

theorem realRootEmbedding_compatible (ζ : ℂ) (hζ : ‖ζ‖ = 1)
    (f : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ)
    (hf : ‖f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩‖ = 1)
    (x : realRootField ζ) :
    ((realRootEmbedding ζ hζ f hf x : ℝ) : ℂ) = f (realRootInclusion ζ x) := by
  apply Complex.ext
  · rfl
  · exact (root_adjoin_embedding_real ζ hζ f hf (realRootInclusion ζ x) (by rfl)).symm

theorem exists_primitive_root_real_embedding (ζ : ℂ) (n k : ℕ)
    (hn : 0 < n) (hζ : IsPrimitiveRoot ζ n) (hk : k.Coprime n) :
    ∃ f : IntermediateField.adjoin ℚ ({ζ} : Set ℂ) →ₐ[ℚ] ℂ,
      f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩ = ζ ^ k ∧
      ∃ σ : realRootField ζ →+* ℝ,
        ∀ x : realRootField ζ, (σ x : ℂ) = f (realRootInclusion ζ x) := by
  obtain ⟨f, hf⟩ := exists_primitive_root_adjoin_embedding ζ n k hn hζ hk
  have hnorm : ‖ζ‖ = 1 := hζ.norm'_eq_one hn.ne'
  have hfnorm : ‖f ⟨ζ, IntermediateField.mem_adjoin_simple_self ℚ ζ⟩‖ = 1 := by
    rw [hf, norm_pow, hnorm, one_pow]
  exact ⟨f, hf, realRootEmbedding ζ hnorm f hfnorm,
    realRootEmbedding_compatible ζ hnorm f hfnorm⟩

end Erdos633
