import ErdosProblems.Erdos1038.ResidualWidthSeries

/-!
# Lagrange coefficients from inverse moments

For a fixed Lagrange degree, the coefficient of the product kernel depends
only on finitely many inverse moments.  This file records that dependence as
an exact formal-power-series differential equation and a triangular
recurrence.  The recurrence is particularly convenient for canonical-mesh
limits because each of its inputs is a scalar Riemann-sum moment.
-/

set_option warningAsError false

open Filter
open scoped BigOperators Topology

noncomputable section

namespace PowerSeries

/-- The ordinary generating series of weighted inverse moments. -/
def inverseMomentSeries {iota : Type*} [Fintype iota]
    (a d : iota → ℝ) : RPS :=
  mk fun r ↦ ∑ i, a i * (d i)⁻¹ ^ (r + 1)

@[simp]
lemma coeff_inverseMomentSeries {iota : Type*} [Fintype iota]
    (a d : iota → ℝ) (r : ℕ) :
    coeff r (inverseMomentSeries a d) =
      ∑ i, a i * (d i)⁻¹ ^ (r + 1) := by
  rw [inverseMomentSeries, coeff_mk]

lemma lagrangeFactorSeries_add (a b d : ℝ) :
    lagrangeFactorSeries (a + b) d =
      lagrangeFactorSeries a d * lagrangeFactorSeries b d := by
  rw [lagrangeFactorSeries, lagrangeFactorSeries,
    lagrangeFactorSeries, ← map_mul, ← binomialSeries_add]
  congr 2
  ring

/-- Formal derivative of one binomial Lagrange factor. -/
lemma derivative_lagrangeFactorSeries (a d : ℝ) :
    (PowerSeries.derivative ℝ) (lagrangeFactorSeries a d) =
      C (a * d⁻¹) * lagrangeFactorSeries (a + 1) d := by
  ext r
  rw [coeff_derivative, coeff_C_mul,
    coeff_lagrangeFactorSeries, coeff_lagrangeFactorSeries]
  rw [ascPochhammer_succ_eval]
  rw [Nat.factorial_succ]
  push_cast
  have hfac : ((r.factorial : ℕ) : ℝ) ≠ 0 := by positivity
  field_simp [hfac]
  have hpoch :
      (ascPochhammer ℝ r).eval a * (a + (r : ℝ)) =
        a * (ascPochhammer ℝ r).eval (a + 1) := by
    calc
      (ascPochhammer ℝ r).eval a * (a + (r : ℝ)) =
          (ascPochhammer ℝ (r + 1)).eval a :=
        (ascPochhammer_succ_eval r a).symm
      _ = a * (ascPochhammer ℝ r).eval (a + 1) := by
        rw [ascPochhammer_succ_left]
        simp
  rw [pow_succ, hpoch]
  ring

/-- Logarithmic derivative of a finite product of Lagrange factors. -/
lemma derivative_prod_lagrangeFactorSeries
    {iota : Type*} [Fintype iota] [DecidableEq iota]
    (s : Finset iota) (a d : iota → ℝ) :
    (PowerSeries.derivative ℝ)
        (∏ i ∈ s, lagrangeFactorSeries (a i) (d i)) =
      (∏ i ∈ s, lagrangeFactorSeries (a i) (d i)) *
        (∑ i ∈ s, C (a i * (d i)⁻¹) *
          lagrangeFactorSeries 1 (d i)) := by
  induction s using Finset.induction_on with
  | empty =>
      simpa only [Finset.prod_empty, Finset.sum_empty, mul_zero] using!
        (PowerSeries.derivative_one (R := ℝ))
  | @insert i s hi ih =>
      rw [Finset.prod_insert hi, Finset.sum_insert hi,
        (PowerSeries.derivative ℝ).leibniz,
        derivative_lagrangeFactorSeries, ih,
        lagrangeFactorSeries_add]
      simp only [smul_eq_mul]
      ring

/-- The `n`th power of the Lagrange kernel satisfies the moment ODE
`P' = P · n M`, where `M` is the inverse-moment series. -/
theorem derivative_lagrangePhi_pow_eq_mul_inverseMomentSeries
    {iota : Type*} [Fintype iota] [DecidableEq iota]
    (a d : iota → ℝ) (n : ℕ) :
    (PowerSeries.derivative ℝ) ((lagrangePhi a d) ^ n) =
      (lagrangePhi a d) ^ n *
        (C (n : ℝ) * inverseMomentSeries a d) := by
  rw [lagrangePhi_pow]
  rw [derivative_prod_lagrangeFactorSeries Finset.univ
    (fun i ↦ (n : ℝ) * a i) d]
  congr 1
  ext r
  rw [map_sum, coeff_C_mul, coeff_inverseMomentSeries]
  simp only [coeff_C_mul, coeff_lagrangeFactorSeries]
  rw [show (ascPochhammer ℝ r).eval 1 /
      (r.factorial : ℝ) = 1 by
    rw [← real_multichoose_eq_ascPochhammer_div,
      Ring.multichoose_one]]
  simp only [one_mul]
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro i hi
  ring

end PowerSeries

namespace Erdos1038

/-- Triangular coefficient generated by a prescribed inverse-moment
sequence.  Its recursion is the coefficient form of `P' = P · cM`. -/
def momentKernelCoefficient (c : ℝ) (moment : ℕ → ℝ) (r : ℕ) : ℝ :=
  Nat.strongRec (t := r) (motive := fun _ => ℝ) fun r previous ↦
    if hr : r = 0 then 1 else
      (r : ℝ)⁻¹ *
        ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal (r - 1)),
          previous p.1.1 (by
            have hp := Finset.HasAntidiagonal.mem_antidiagonal.mp p.2
            omega) * (c * moment (p.1.2 + 1))

@[simp]
lemma momentKernelCoefficient_zero (c : ℝ) (moment : ℕ → ℝ) :
    momentKernelCoefficient c moment 0 = 1 := by
  rw [momentKernelCoefficient, Nat.strongRec_eq]
  simp

lemma momentKernelCoefficient_succ (c : ℝ) (moment : ℕ → ℝ)
    (r : ℕ) :
    momentKernelCoefficient c moment (r + 1) =
      ((r + 1 : ℕ) : ℝ)⁻¹ *
        ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
          momentKernelCoefficient c moment p.1.1 *
            (c * moment (p.1.2 + 1)) := by
  rw [momentKernelCoefficient, Nat.strongRec_eq]
  simp only [Nat.add_eq_zero_iff, one_ne_zero, and_false,
    ↓reduceDIte]
  congr 2

/-- Exact finite-moment formula for every coefficient of a powered
Lagrange kernel. -/
theorem coeff_lagrangePhi_pow_eq_momentKernelCoefficient
    {iota : Type*} [Fintype iota] [DecidableEq iota]
    (a d : iota → ℝ) (n r : ℕ) :
    PowerSeries.coeff r ((PowerSeries.lagrangePhi a d) ^ n) =
      momentKernelCoefficient (n : ℝ)
        (fun ell ↦ ∑ i, a i * (d i)⁻¹ ^ ell) r := by
  induction r using Nat.strongRecOn with
  | ind r ih =>
      cases r with
      | zero =>
          rw [PowerSeries.coeff_zero_eq_constantCoeff_apply,
            map_pow, PowerSeries.lagrangePhi_constantCoeff,
            one_pow, momentKernelCoefficient_zero]
      | succ r =>
          have hder := congrArg (PowerSeries.coeff r)
            (PowerSeries.derivative_lagrangePhi_pow_eq_mul_inverseMomentSeries
              a d n)
          rw [PowerSeries.coeff_derivative, PowerSeries.coeff_mul] at hder
          simp only [PowerSeries.coeff_C_mul,
            PowerSeries.coeff_inverseMomentSeries] at hder
          have hsum :
              (∑ p ∈ Finset.HasAntidiagonal.antidiagonal r,
                PowerSeries.coeff p.1
                    ((PowerSeries.lagrangePhi a d) ^ n) *
                  ((n : ℝ) *
                    ∑ i, a i * (d i)⁻¹ ^ (p.2 + 1))) =
                ∑ p ∈ Finset.HasAntidiagonal.antidiagonal r,
                  momentKernelCoefficient (n : ℝ)
                      (fun ell ↦ ∑ i, a i * (d i)⁻¹ ^ ell) p.1 *
                    ((n : ℝ) *
                      ∑ i, a i * (d i)⁻¹ ^ (p.2 + 1)) := by
            apply Finset.sum_congr rfl
            intro p hp
            rw [ih p.1 (by
              have hp' := Finset.HasAntidiagonal.mem_antidiagonal.mp hp
              omega)]
          rw [hsum] at hder
          rw [momentKernelCoefficient_succ]
          calc
            PowerSeries.coeff (r + 1)
                ((PowerSeries.lagrangePhi a d) ^ n) =
                ((r + 1 : ℕ) : ℝ)⁻¹ *
                  (PowerSeries.coeff (r + 1)
                    ((PowerSeries.lagrangePhi a d) ^ n) *
                      ((r : ℝ) + 1)) := by
                have hr : ((r : ℝ) + 1) ≠ 0 := by positivity
                field_simp
                push_cast
                rfl
            _ = ((r + 1 : ℕ) : ℝ)⁻¹ *
                ∑ p ∈ Finset.HasAntidiagonal.antidiagonal r,
                  momentKernelCoefficient (n : ℝ)
                      (fun ell ↦ ∑ i, a i * (d i)⁻¹ ^ ell) p.1 *
                    ((n : ℝ) *
                      ∑ i, a i * (d i)⁻¹ ^ (p.2 + 1)) := by
                rw [hder]
            _ = _ := by
                congr 1
                conv_lhs =>
                  rw [← Finset.sum_attach, Finset.attach_eq_univ]

/-- Fixed-degree moment coefficients are continuous under pointwise
convergence of their finitely many moment inputs. -/
theorem tendsto_momentKernelCoefficient
    {beta : Type*} {l : Filter beta}
    (c : ℝ) {momentSequence : beta → ℕ → ℝ}
    {momentLimit : ℕ → ℝ}
    (hmoment : ∀ ell, Tendsto (fun b ↦ momentSequence b ell) l
      (nhds (momentLimit ell))) (r : ℕ) :
    Tendsto
      (fun b ↦ momentKernelCoefficient c (momentSequence b) r) l
      (nhds (momentKernelCoefficient c momentLimit r)) := by
  induction r using Nat.strongRecOn with
  | ind r ih =>
      cases r with
      | zero =>
          simpa only [momentKernelCoefficient_zero] using!
            (tendsto_const_nhds : Tendsto (fun _b : beta ↦ (1 : ℝ)) l
              (nhds 1))
      | succ r =>
          have hsum : Tendsto
              (fun b ↦ ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                momentKernelCoefficient c (momentSequence b) p.1.1 *
                  (c * momentSequence b (p.1.2 + 1))) l
              (nhds (∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                momentKernelCoefficient c momentLimit p.1.1 *
                  (c * momentLimit (p.1.2 + 1)))) := by
            apply tendsto_finsetSum Finset.univ
            intro p hp
            exact (ih p.1.1 (by
              have hp' := Finset.HasAntidiagonal.mem_antidiagonal.mp p.2
              omega)).mul (tendsto_const_nhds.mul
                (hmoment (p.1.2 + 1)))
          simpa only [momentKernelCoefficient_succ] using!
            (tendsto_const_nhds.mul hsum : Tendsto
              (fun b ↦ ((r + 1 : ℕ) : ℝ)⁻¹ *
                ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                  momentKernelCoefficient c (momentSequence b) p.1.1 *
                    (c * momentSequence b (p.1.2 + 1))) l
              (nhds (((r + 1 : ℕ) : ℝ)⁻¹ *
                ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                  momentKernelCoefficient c momentLimit p.1.1 *
                    (c * momentLimit (p.1.2 + 1)))))

/-- Linearization of the triangular moment recurrence in a prescribed
moment velocity. -/
def momentKernelCoefficientDirectional
    (c : ℝ) (moment velocity : ℕ → ℝ) (r : ℕ) : ℝ :=
  Nat.strongRec (t := r) (motive := fun _ => ℝ) fun r previous ↦
    if hr : r = 0 then 0 else
      (r : ℝ)⁻¹ *
        ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal (r - 1)),
          (previous p.1.1 (by
              have hp := Finset.HasAntidiagonal.mem_antidiagonal.mp p.2
              omega) * (c * moment (p.1.2 + 1)) +
            momentKernelCoefficient c moment p.1.1 *
              (c * velocity (p.1.2 + 1)))

@[simp]
lemma momentKernelCoefficientDirectional_zero
    (c : ℝ) (moment velocity : ℕ → ℝ) :
    momentKernelCoefficientDirectional c moment velocity 0 = 0 := by
  rw [momentKernelCoefficientDirectional, Nat.strongRec_eq]
  simp

lemma momentKernelCoefficientDirectional_succ
    (c : ℝ) (moment velocity : ℕ → ℝ) (r : ℕ) :
    momentKernelCoefficientDirectional c moment velocity (r + 1) =
      ((r + 1 : ℕ) : ℝ)⁻¹ *
        ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
          (momentKernelCoefficientDirectional c moment velocity p.1.1 *
              (c * moment (p.1.2 + 1)) +
            momentKernelCoefficient c moment p.1.1 *
              (c * velocity (p.1.2 + 1))) := by
  rw [momentKernelCoefficientDirectional, Nat.strongRec_eq]
  simp only [Nat.add_eq_zero_iff, one_ne_zero, and_false, ↓reduceDIte]
  congr 2

/-- The linearized recurrence is the actual derivative of the moment
coefficient along any differentiable scalar moment path. -/
theorem hasDerivAt_momentKernelCoefficient
    (c : ℝ) {momentPath : ℝ → ℕ → ℝ}
    {velocity : ℕ → ℝ} {t : ℝ}
    (hmoment : ∀ ell, HasDerivAt (fun u ↦ momentPath u ell)
      (velocity ell) t) (r : ℕ) :
    HasDerivAt
      (fun u ↦ momentKernelCoefficient c (momentPath u) r)
      (momentKernelCoefficientDirectional c (momentPath t) velocity r) t := by
  induction r using Nat.strongRecOn with
  | ind r ih =>
      cases r with
      | zero =>
          simpa only [momentKernelCoefficient_zero,
            momentKernelCoefficientDirectional_zero] using!
            (hasDerivAt_const t (1 : ℝ))
      | succ r =>
          have hsum := HasDerivAt.sum (u :=
              (Finset.univ : Finset ↑(Finset.HasAntidiagonal.antidiagonal r))) fun p hp ↦
            (ih p.1.1 (by
                have hp' := Finset.HasAntidiagonal.mem_antidiagonal.mp p.2
                omega)).mul
              ((hmoment (p.1.2 + 1)).const_mul c)
          have hscaled := hsum.const_mul (((r + 1 : ℕ) : ℝ)⁻¹)
          simpa only [momentKernelCoefficient_succ,
            momentKernelCoefficientDirectional_succ,
            Finset.sum_apply] using! hscaled

/-- Linearized fixed-degree coefficients are continuous under pointwise
convergence of both moments and their velocities. -/
theorem tendsto_momentKernelCoefficientDirectional
    {beta : Type*} {l : Filter beta}
    (c : ℝ) {momentSequence velocitySequence : beta → ℕ → ℝ}
    {momentLimit velocityLimit : ℕ → ℝ}
    (hmoment : ∀ ell, Tendsto (fun b ↦ momentSequence b ell) l
      (nhds (momentLimit ell)))
    (hvelocity : ∀ ell, Tendsto (fun b ↦ velocitySequence b ell) l
      (nhds (velocityLimit ell))) (r : ℕ) :
    Tendsto
      (fun b ↦ momentKernelCoefficientDirectional c
        (momentSequence b) (velocitySequence b) r) l
      (nhds (momentKernelCoefficientDirectional c
        momentLimit velocityLimit r)) := by
  induction r using Nat.strongRecOn with
  | ind r ih =>
      cases r with
      | zero =>
          simpa only [momentKernelCoefficientDirectional_zero] using!
            (tendsto_const_nhds : Tendsto (fun _b : beta ↦ (0 : ℝ)) l
              (nhds 0))
      | succ r =>
          have hsum : Tendsto
              (fun b ↦ ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                (momentKernelCoefficientDirectional c
                    (momentSequence b) (velocitySequence b) p.1.1 *
                      (c * momentSequence b (p.1.2 + 1)) +
                  momentKernelCoefficient c (momentSequence b) p.1.1 *
                    (c * velocitySequence b (p.1.2 + 1)))) l
              (nhds (∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                (momentKernelCoefficientDirectional c
                    momentLimit velocityLimit p.1.1 *
                      (c * momentLimit (p.1.2 + 1)) +
                  momentKernelCoefficient c momentLimit p.1.1 *
                    (c * velocityLimit (p.1.2 + 1))))) := by
            apply tendsto_finsetSum Finset.univ
            intro p hp
            exact ((ih p.1.1 (by
                have hp' := Finset.HasAntidiagonal.mem_antidiagonal.mp p.2
                omega)).mul (tendsto_const_nhds.mul
                  (hmoment (p.1.2 + 1)))).add
              ((tendsto_momentKernelCoefficient c hmoment p.1.1).mul
                (tendsto_const_nhds.mul (hvelocity (p.1.2 + 1))))
          simpa only [momentKernelCoefficientDirectional_succ] using!
            (tendsto_const_nhds.mul hsum : Tendsto
              (fun b ↦ ((r + 1 : ℕ) : ℝ)⁻¹ *
                ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                  (momentKernelCoefficientDirectional c
                      (momentSequence b) (velocitySequence b) p.1.1 *
                        (c * momentSequence b (p.1.2 + 1)) +
                    momentKernelCoefficient c (momentSequence b) p.1.1 *
                      (c * velocitySequence b (p.1.2 + 1)))) l
              (nhds (((r + 1 : ℕ) : ℝ)⁻¹ *
                ∑ p : ↑(Finset.HasAntidiagonal.antidiagonal r),
                  (momentKernelCoefficientDirectional c
                      momentLimit velocityLimit p.1.1 *
                        (c * momentLimit (p.1.2 + 1)) +
                    momentKernelCoefficient c momentLimit p.1.1 *
                      (c * velocityLimit (p.1.2 + 1))))))

/-- Velocity of an inverse moment along the affine displacement from
`reference` to `target`. -/
def inverseMomentDirectional {iota : Type*} [Fintype iota]
    (a reference target : iota → ℝ) (ell : ℕ) : ℝ :=
  -(ell : ℝ) *
    ∑ i, a i * (target i - reference i) *
      (reference i)⁻¹ ^ (ell + 1)

/-- The preceding velocity is the actual derivative of the inverse
moment along the coordinate line. -/
theorem hasDerivAt_inverseMoment_line
    {iota : Type*} [Fintype iota]
    (a reference target : iota → ℝ)
    (href : reference ∈ positiveCoordinates iota) (ell : ℕ) :
    HasDerivAt
      (fun t ↦ ∑ i, a i *
        ((AffineMap.lineMap (k := ℝ) reference target t) i)⁻¹ ^ ell)
      (inverseMomentDirectional a reference target ell) 0 := by
  cases ell with
  | zero =>
      simp only [pow_zero, mul_one, inverseMomentDirectional,
        Nat.cast_zero, neg_zero, zero_mul]
      exact hasDerivAt_const (0 : ℝ) (∑ i, a i)
  | succ ell =>
      have hs := HasDerivAt.sum (u := Finset.univ) fun i hi ↦ by
        have hcoord := hasDerivAt_lineMap_coordinate reference target i
        have hinv := hcoord.inv (by simpa using! (href i).ne')
        exact (hinv.pow (ell + 1)).const_mul (a i)
      convert! hs using 1
      · funext t
        simp
      · simp only [inverseMomentDirectional, Nat.cast_add,
          Nat.cast_one, AffineMap.lineMap_apply_zero]
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro i hi
        have hsub : ell + 1 - 1 = ell := by omega
        rw [hsub]
        simp only [Pi.inv_apply, AffineMap.lineMap_apply_zero]
        rw [show ell + 1 + 1 = ell + 2 by omega, pow_add]
        norm_num [div_pow]
        ring

/-- Moment-recurrence formula for the material derivative of one scaled
Lagrange coefficient. -/
def scaledLagrangeCoefficientMomentDirectional
    {iota : Type*} [Fintype iota]
    (a : iota → ℝ) (degree : ℕ)
    (reference target : iota → ℝ) : ℝ :=
  inverseMonomialDirectional
      (fun i ↦ (degree : ℝ) * a i) reference target *
      ((degree : ℝ)⁻¹ *
        momentKernelCoefficient (degree : ℝ)
          (fun ell ↦ ∑ i, a i * (reference i)⁻¹ ^ ell)
          (degree - 1)) +
    inverseMonomial (fun i ↦ (degree : ℝ) * a i) reference *
      ((degree : ℝ)⁻¹ *
        momentKernelCoefficientDirectional (degree : ℝ)
          (fun ell ↦ ∑ i, a i * (reference i)⁻¹ ^ ell)
          (inverseMomentDirectional a reference target) (degree - 1))

/-- The recurrence formula is exactly the directional derivative already
defined by the positive multi-index expansion. -/
theorem scaledLagrangeCoefficientDirectional_eq_moment
    {iota : Type*} [Fintype iota] [DecidableEq iota]
    (a : iota → ℝ) {degree : ℕ} (hdegree : 0 < degree)
    (reference target : iota → ℝ)
    (href : reference ∈ positiveCoordinates iota) :
    scaledLagrangeCoefficientDirectional a degree reference target =
      scaledLagrangeCoefficientMomentDirectional a degree
        reference target := by
  let line : ℝ → iota → ℝ :=
    AffineMap.lineMap (k := ℝ) reference target
  let momentPath : ℝ → ℕ → ℝ := fun t ell ↦
    ∑ i, a i * (line t i)⁻¹ ^ ell
  have hmoment (ell : ℕ) : HasDerivAt
      (fun t ↦ momentPath t ell)
      (inverseMomentDirectional a reference target ell) 0 := by
    simpa only [momentPath, line] using!
      hasDerivAt_inverseMoment_line a reference target href ell
  have hmomentCoefficient := hasDerivAt_momentKernelCoefficient
    (degree : ℝ) hmoment (degree - 1)
  have hscale := hasDerivAt_inverseMonomial_line
    (fun i ↦ (degree : ℝ) * a i) reference target href
  have hformula := hscale.mul
    (hmomentCoefficient.const_mul (degree : ℝ)⁻¹)
  have hpositive : ∀ᶠ t in nhds (0 : ℝ),
      line t ∈ positiveCoordinates iota := by
    change ∀ᶠ t in nhds (0 : ℝ), ∀ i, 0 < line t i
    rw [Filter.eventually_all]
    intro i
    have hcontinuous :=
      (hasDerivAt_lineMap_coordinate reference target i).continuousAt
    have hrefline : 0 < line 0 i := by
      simpa only [line, AffineMap.lineMap_apply_zero] using! href i
    exact hcontinuous.eventually (Ioi_mem_nhds hrefline)
  have hevent :
      (fun t ↦ inverseMonomial
          (fun i ↦ (degree : ℝ) * a i) (line t) *
        ((degree : ℝ)⁻¹ *
          momentKernelCoefficient (degree : ℝ) (momentPath t)
            (degree - 1))) =ᶠ[nhds (0 : ℝ)]
        (scaledLagrangeCoefficient a degree ∘ line) := by
    filter_upwards [hpositive] with t ht
    change inverseMonomial
        (fun i ↦ (degree : ℝ) * a i) (line t) *
          ((degree : ℝ)⁻¹ *
            momentKernelCoefficient (degree : ℝ) (momentPath t)
              (degree - 1)) =
      scaledLagrangeCoefficient a degree (line t)
    rw [scaledLagrangeCoefficient_eq_mul_coeff_phi_pow
      a (line t) ht hdegree]
    rw [coeff_lagrangePhi_pow_eq_momentKernelCoefficient]
  have hevent' :
      (scaledLagrangeCoefficient a degree ∘ line) =ᶠ[nhds (0 : ℝ)]
        ((inverseMonomial (fun i ↦ (degree : ℝ) * a i) ∘ line) *
          fun t ↦ (degree : ℝ)⁻¹ *
            momentKernelCoefficient (degree : ℝ) (momentPath t)
              (degree - 1)) := by
    simpa only [Function.comp_apply, Pi.mul_apply] using! hevent.symm
  have hformulaActual := hformula.congr_of_eventuallyEq (by
    simpa only [line] using! hevent')
  have hactual := hasDerivAt_scaledLagrangeCoefficient_line
    a degree (reference := reference) (target := target) href
  have hderivative := hactual.unique hformulaActual
  simpa only [scaledLagrangeCoefficientMomentDirectional,
    line, momentPath, Function.comp_apply,
    AffineMap.lineMap_apply_zero] using! hderivative

end Erdos1038
